"""Entrega 3 · tanda t06 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"

# NEU-045 · TB en la gestante: estreptomicina contraindicada · TARJETAS
S("tarjetas", "NEU-045", "El antituberculoso contraindicado en la gestante es la estreptomicina (aminoglucósido ototóxico para el feto)",
  "Tuberculosis · embarazo",
  ("Antituberculosos en el embarazo", ["Isoniazida, rifampicina, pirazinamida y etambutol son seguros: se usa el esquema estándar.",
                                       "La estreptomicina cruza la placenta y daña el VIII par del feto (sordera congénita)."]),
  ("Pregunta de teoría", ["¿Qué antituberculoso está contraindicado", "en la gestante?"]),
  ["Esquema 2HRZE/4HR + piridoxina (B6) para prevenir la neuropatía por isoniazida.",
   "Evitar aminoglucósidos inyectables (estreptomicina, amikacina, kanamicina) y en lo posible etionamida.",
   "La lactancia se mantiene; separar al bebé solo si la madre es bacilífera y sin tratamiento."],
  OMS + ", guías consolidadas de TB (2025); " + MINSA + ", NTS de tuberculosis (2023).",
  op=("¿Contraindicado?", ["Sí: ototóxico para el feto", "No: segura (OMS)", "No: segura; dar vitamina K al RN", "No: seguro", "No: segura con piridoxina"]),
  d=dict(rotulo="Antituberculosos: ¿se pueden usar en el embarazo?", ans=0,
         cards=[dict(titulo="Estreptomicina", datos=[("Embarazo", "NO", True), ("Daño", "Sordera fetal", True), ("Tipo", "Aminoglucósido", True)], pie="Este caso."),
                dict(titulo="Isoniazida", datos=[("Embarazo", "Sí", False), ("Añadir", "Piridoxina (B6)", False), ("Efecto", "Hepatitis, neuropatía", False)], pie="Segura."),
                dict(titulo="Rifampicina", datos=[("Embarazo", "Sí", False), ("Al RN", "Vitamina K", False), ("Efecto", "Orina naranja", False)], pie="Segura."),
                dict(titulo="Etambutol", datos=[("Embarazo", "Sí", False), ("Efecto", "Neuritis óptica", False), ("Control", "Visión de colores", False)], pie="Seguro.")]))

# GIN-156 · Anti-D: RN Rh negativo · DECISIÓN
S("decision", "GIN-156", "Madre Rh negativo cuyo recién nacido también es Rh negativo: no se indica la inmunoglobulina anti-D (no hay riesgo de sensibilización)",
  "Isoinmunización Rh",
  ("Profilaxis anti-D", ["La madre Rh(−) se sensibiliza solo si recibe glóbulos rojos Rh(+) del bebé.",
                         "Si el recién nacido es Rh(−) no hay antígeno D que la sensibilice: no se da anti-D."]),
  ("Mujer de 32 años, Rh negativo", ["Recién nacido Rh negativo.", "Coombs directo positivo en el RN (buscar otra causa: ABO u otros anticuerpos)."]),
  ["Anti-D 300 µg IM en las primeras 72 h posparto SOLO si el RN es Rh(+) y la madre no está sensibilizada (Coombs indirecto negativo).",
   "Además: a las 28 semanas y tras aborto, ectópico, amniocentesis, sangrado o trauma.",
   "Un Coombs directo positivo con RN Rh(−) orienta a incompatibilidad ABO u otros anticuerpos."],
  ACOG + ", prevención de la aloinmunización Rh (2017; act. 2024); " + MINSA + ".",
  op=("¿Profilaxis anti-D?", ["No: el RN no es Rh(+)", "Sí: no hay riesgo de sensibilización", "No: el RN no es Rh(+)", "No: el RN no es Rh(+)", "Se decidirá en el próximo embarazo, no ahora"]),
  d=dict(rotulo="¿Dar anti-D después del parto?", eje_y="Recién nacido", ancho_filas=200,
         cols=["Madre no sensibilizada (Coombs indirecto −)", "Madre ya sensibilizada (Coombs indirecto +)"],
         rows=[("Rh positivo", "Tiene el antígeno D"), ("Rh negativo", "No tiene antígeno D")],
         cells=[[("Anti-D en < 72 h", ["300 µg IM"]), ("No sirve", ["Ya tiene anticuerpos"])],
                [("No indicar", ["No hay riesgo"]), ("No indicar", [])]],
         caso=(1, 0), nota="La pregunta clave es el Rh del recién nacido: aquí es negativo."))

# GIN-157 · Embarazo prolongado con Bishop desfavorable · PUNTAJE (Bishop)
S("arbol", "GIN-157", "Gestante de 42 semanas con monitoreo normal y Bishop desfavorable (4): madurar el cuello con misoprostol antes de inducir",
  "Embarazo prolongado · inducción",
  ("Embarazo en vías de prolongación", ["A las 41-42 semanas aumenta el riesgo de muerte fetal y de macrosomía: se termina la gestación.",
                                        "Si el cuello no está listo (Bishop ≤ 6), primero se madura (misoprostol, sonda de Foley) y luego oxitocina."]),
  ("Gestante de 42 semanas (eco de 1.er trimestre)", ["Test no estresante normal; AU 34 cm.", "Cérvix posterior, consistencia media, borramiento 40 %, estación −2, dilatación 1 cm."]),
  ["Misoprostol 25 µg vaginal cada 4-6 h (máximo según protocolo) o sonda de Foley.",
   "Cuando el Bishop sea > 6: oxitocina en infusión.",
   "Inducir desde las 41 semanas (ACOG/OMS); a las 42 semanas ya no se espera."],
  ACOG + ", embarazo prolongado (2014; act.); " + OMS + ", inducción del parto (2022).",
  op=("¿Conducta?", ["No: a las 42 semanas no se espera", "No: con Bishop 4 falla la oxitocina", "No: no está en trabajo de parto", "Sí: Bishop desfavorable", "No: no hay indicación de cesárea"]),
  arbol=Q("42 semanas: ¿cómo está el cuello (Bishop)?", [
      L("≤ 6, desfavorable (este caso)", "MADURAR CON MISOPROSTOL", ["O sonda de Foley", "Luego oxitocina"], path=True),
      L("> 6, favorable", "Inducir con oxitocina", ["Infusión con bomba"])], path=True),
  escala=dict(nombre="Puntaje de Bishop", modo="puntaje", que="Madurez del cuello: > 6 favorable para inducir con oxitocina.",
              items=[("Dil", "Dilatación (1 cm = 1)", "1 cm", 1), ("Borr", "Borramiento (40-50 % = 1)", "40 %", 1), ("Est", "Estación (−2 = 1)", "−2", 1),
                     ("Cons", "Consistencia (media = 1)", "Media", 1), ("Pos", "Posición (posterior = 0)", "Posterior", 0)],
              total_txt="Total: 4 puntos", total_nota="de 0 a 13",
              rangos=[("≤ 6", "Desfavorable", "Madurar el cuello"), ("> 6", "Favorable", "Oxitocina")], caso_rango=0,
              porque=[("Cuello posterior y poco dilatado", True)], conducta="Misoprostol o Foley y luego oxitocina."))

# GIN-158 · Fórmula obstétrica · CÁLCULO
S("arbol", "GIN-158", "Gestante actual con antecedentes de un aborto, un ectópico, un parto a término y un hijo vivo: G4 P1021",
  "Historia clínica perinatal · fórmula obstétrica",
  ("Fórmula obstétrica (G P a b c d)", ["G = todas las gestaciones (incluida la actual). P = a (término) · b (pretérmino) · c (abortos, incluye ectópicos y molas) · d (hijos vivos).",
                                        "El embarazo actual suma en G, pero no en P."]),
  ("Gestante actual", ["Antecedentes: 1 aborto, 1 ectópico, 1 parto a término, 1 hijo vivo.", "¿Cómo se escribe?"]),
  ["G: 1 aborto + 1 ectópico + 1 parto + la actual = 4.",
   "c (abortos): aborto + ectópico = 2. a = 1, b = 0, d = 1.",
   "Resultado: G4 P1021."],
  MINSA + ", Historia Clínica Perinatal (CLAP/OPS).",
  op=("¿Fórmula?", ["No: falta la gestación actual y el ectópico", "Sí: G4 P1021", "No: G debe ser 4", "No: solo 1 parto a término", "No: no hay pretérmino"]),
  arbol=Q("¿Cómo se cuenta cada antecedente?", [
      L("Gestaciones (incluye la actual)", "G = 4", ["Aborto + ectópico + parto + actual"], path=True),
      L("Abortos (incluye el ectópico)", "c = 2", ["Aborto + ectópico"], path=True),
      L("Término · pretérmino · vivos", "a = 1 · b = 0 · d = 1", ["P1021"], path=True)], path=True),
  banda=B("Cómo se lee la fórmula", P("dib_formula_obstetrica.jpg", 380, 220, [], credito=PROPIO, fondo="#ffffff"),
          [("G", "Todas las gestaciones."), ("a b c d", "Término, pretérmino, abortos, vivos."), ("Ectópico y mola", "Se cuentan como abortos (c).")],
          pie="Esquema."))

# REU-048 · Artritis gonocócica · LECTURA (Gram) + LCR-like laboratorio
S("lectura", "REU-048", "Mujer joven con fiebre, artralgias de muñecas y monoartritis de rodilla con leucorrea: artritis gonocócica, el Gram del líquido muestra diplococos gramnegativos",
  "Artritis séptica · gonococo",
  ("Infección gonocócica diseminada", ["En adultos jóvenes sexualmente activos: fiebre, poliartralgias, tenosinovitis, pústulas en la piel",
                                       "y luego artritis de una gran articulación (rodilla). La leucorrea da la pista."]),
  ("Mujer de 23 años", ["3 días de fiebre, artralgias de muñecas y rodilla derecha; leucorrea.", "Rodilla caliente, roja, hinchada y muy dolorosa."]),
  ["Artrocentesis: Gram, cultivo (rara vez positivo) y PCR de gonococo en cuello uterino, uretra, faringe y recto.",
   "Ceftriaxona 1 g EV/día; pasar a oral cuando mejore; total ≥ 7 días. Tratar clamidia si no se descartó (doxiciclina).",
   "Estudiar y tratar a la pareja; descartar VIH y sífilis."],
  CDC + ", guías de ITS (2021); " + IDSA + ".",
  op=("¿Qué muestra el Gram?", ["No: sería hongo", "Sí: Neisseria gonorrhoeae", "No: E. coli u otros gramnegativos", "No: sífilis o Lyme", "No: gota (cristales, no gérmenes)"],
      {1: "Diplococos gramnegativos"}),
  d=dict(rotulo="Lee el Gram en este orden", img_titulo="Gram: diplococos dentro de neutrófilos",
         img=P("gonococo.jpg", 300, 241, credito="Graham Beards" + CC + "CC BY-SA 4.0"), pines=[(0.5, 0.45)],
         pasos=[("Diplococos en forma de grano de café", "De dos en dos.", True),
                ("Color rojo (gramnegativos)", "No retienen el cristal violeta.", False),
                ("Dentro de los neutrófilos", "Intracelulares: típico del gonococo.", False),
                ("Tratar", "Ceftriaxona y buscar otras ITS.", False)],
         img_pie="Gram de otra muestra (secreción uretral).",
         veredicto=("Joven con leucorrea + monoartritis = artritis gonocócica", "Diplococos gramnegativos; ceftriaxona.")))

# REU-049 · Lupus con nefritis y serositis · CRITERIOS EULAR/ACR 2019 + foto
S("criterios", "REU-049", "Mujer joven con artritis, eritema malar, alopecia, derrame pleural, anemia, plaquetopenia y sedimento activo con cilindros: lupus eritematoso sistémico",
  "Lupus eritematoso sistémico",
  ("Lupus eritematoso sistémico", ["Enfermedad autoinmune multisistémica, sobre todo en mujeres jóvenes: piel, articulaciones, riñón, serosas, sangre.",
                                   "ANA positivo en > 95 % (criterio de entrada); anti-ADN y anti-Smith más específicos."]),
  ("Mujer de 25 años, 6 meses", ["Artritis de pequeñas articulaciones; eritema malar y alopecia.", "Derrame pleural; Hb 10, plaquetas 40 000; orina con hematíes y cilindros."]),
  ["Pedir ANA, anti-ADNdc, complemento (C3, C4 bajos), anti-Smith, antifosfolípidos.",
   "Nefritis: biopsia renal; inducción con micofenolato o ciclofosfamida + corticoide.",
   "Hidroxicloroquina para todos (salvo contraindicación): reduce brotes y mortalidad."],
  "EULAR/ACR, criterios de LES (2019); EULAR, manejo del LES (2023); KDIGO, nefritis lúpica (2024).",
  op=("¿Diagnóstico?", ["No: debilidad proximal y Gottron", "No: sin riñón, serosas ni citopenias", "No: monoartritis aguda", "Sí: piel + articulación + riñón + sangre + serosa", "No: piel dura y Raynaud"]),
  d=dict(rotulo="Criterios EULAR/ACR 2019 (con ANA ≥ 1:80)", lista_titulo="Dominios clínicos",
         items=[("Renal: cilindros / proteinuria (4-10)", True, "Cilindros leucocitarios y granulosos"), ("Hematológico: plaquetas < 100 000 (4)", True, "40 000"),
                ("Serosas: derrame pleural (5)", True, "Izquierdo"), ("Articular: artritis (6)", True, "Pequeñas articulaciones"),
                ("Piel: alopecia, lupus cutáneo agudo (2-6)", True, "Eritema malar"), ("ANA ≥ 1:80", None, "Por pedir (criterio de entrada)")],
         umbral="≥ 10 puntos + ANA = LES",
         veredicto="Suma muy por encima de 10: lupus con nefritis; pedir ANA, anti-ADN y complemento.",
         img=P("lupus_malar.jpg", 260, 77, [], credito="OpenStax" + CC + "CC BY 4.0"), img_titulo="Eritema malar",
         img_pie="En «alas de mariposa», respeta el surco nasogeniano.", conteo="5 dominios presentes"))

# END-046 · Graves en el 1.er trimestre: PTU · DECISIÓN
S("decision", "END-046", "Gestante de 10 semanas con hipertiroidismo por enfermedad de Graves (exoftalmos, mixedema pretibial, bocio, TSH suprimida): propiltiouracilo en el primer trimestre",
  "Tiroides y embarazo · hipertiroidismo",
  ("Antitiroideos en el embarazo", ["El metimazol en el primer trimestre puede causar malformaciones (aplasia cutis, atresia de coanas).",
                                    "Por eso: PTU en el primer trimestre y metimazol desde el segundo (el PTU daña el hígado)."]),
  ("Gestante de 10 semanas", ["Temblor, nerviosismo, pérdida de peso, intolerancia al calor.", "Exoftalmos, mixedema pretibial, bocio difuso; TSH 0,01, T4 libre alta."]),
  ["Propiltiouracilo a la menor dosis que mantenga la T4 libre en el límite alto normal.",
   "Propranolol por poco tiempo para los síntomas.",
   "Yodo radiactivo prohibido en el embarazo; cirugía solo en el 2.º trimestre si falla el tratamiento."],
  "ATA, tiroides y embarazo (2017; act. 2025); Endocrine Society.",
  op=("¿Tratamiento?", ["No: contraindicado en el embarazo", "No: es para hipotiroidismo", "Sí: elección en el 1.er trimestre", "Desde el 2.º trimestre", "No: solo si falla, en el 2.º trimestre"]),
  d=dict(rotulo="Antitiroideo según el trimestre", eje_y="Trimestre", ancho_filas=180,
         cols=["Antitiroideo de elección", "Por qué"],
         rows=[("Primero", "Hasta las 16 semanas"), ("Segundo y tercero", "")],
         cells=[[("Propiltiouracilo", ["Menos malformaciones"]), ("Metimazol es teratógeno", ["Aplasia cutis, atresia de coanas"])],
                [("Metimazol", ["Cambiar desde el 2.º trimestre"]), ("PTU daña el hígado", ["Hepatitis grave"])]],
         caso=(0, 0)),
  banda=B("Signos de Graves en los ojos", P("graves_ojos.jpg", 360, 130, [], credito="Jonathan Trobe" + CC + "CC BY 3.0"),
          [("Exoftalmos", "Solo en Graves (no en otros hipertiroidismos)."), ("Retracción palpebral", "Se ve el blanco sobre el iris."),
           ("Con mixedema pretibial", "Tríada de Graves: bocio, ojos, piel.")],
          pie="Foto de otra persona (solo los ojos)."),
  triada=TR([("Bocio difuso", "Sí", True), ("Oftalmopatía (exoftalmos)", "Sí", True), ("Dermopatía (mixedema pretibial)", "Edema duro pretibial", True)],
            [("Tríada de Graves-Basedow", 0, 2)], "Completa: hipertiroidismo por Graves."))

# END-047 · Tiroiditis subaguda · CASCADA (fases) + fases
S("fases", "END-047", "Dolor cervical y tirotoxicosis 10 días después de una infección respiratoria, con tiroides dolorosa y TSH baja: tiroiditis subaguda de De Quervain, AINE y propranolol",
  "Tiroiditis · tiroiditis subaguda",
  ("Tiroiditis subaguda (De Quervain)", ["Inflamación viral de la tiroides: se rompen los folículos y sale hormona guardada (no se fabrica más).",
                                          "Tiroides dolorosa, VSG alta y captación de yodo BAJA; pasa por fases."]),
  ("Mujer de 35 años", ["Infección respiratoria hace 10 días; dolor cervical, nerviosismo y temblor.", "Taquicardia, bocio difuso doloroso; TSH 0,2."]),
  ["AINE (o prednisona si el dolor es intenso) + propranolol para los síntomas.",
   "No sirven los antitiroideos: la tiroides no está fabricando de más.",
   "Controlar la TSH: puede haber hipotiroidismo transitorio."],
  "ATA, tirotoxicosis (2016); " + HARRISON + ".",
  op=("¿Tratamiento?", ["Sí: dolor + síntomas", "No: el antitiroideo no sirve aquí", "No: la levotiroxina no en la fase tóxica", "No: el metimazol no sirve", "No: sin indicación"]),
  d=dict(rotulo="Las fases de la tiroiditis subaguda", ans=0,
         fases=[("Tirotóxica", "2-8 semanas", "AINE + PROPRANOLOL", ["Sale hormona guardada", "Este caso"]),
                ("Hipotiroidea", "Semanas a meses", "LEVOTIROXINA SI HAY SÍNTOMAS", ["Se agotó la reserva"]),
                ("Recuperación", "6-12 meses", "NORMAL", ["~90 % se recupera"])]),
  triada=TR([("Tiroides dolorosa", "Dolor a la palpación", True), ("Infección viral previa", "Hace 10 días", True), ("Tirotoxicosis", "TSH 0,2, temblor", True)],
            [("Tiroiditis subaguda", 0, 2)], "Con captación de yodo baja (si se mide) se confirma."))

# END-048 · DM2 descompensada con falla renal: insulina · REGLA (TFG y metformina)
S("regla", "END-048", "Diabético tipo 2 con HbA1c 9,5 %, glucosa 450 y creatinina 2,3 que toma metformina: iniciar insulina",
  "Diabetes tipo 2 · intensificar el tratamiento",
  ("Cuándo insulina en la DM2", ["Glucosa ≥ 300 o HbA1c ≥ 10 %, síntomas de catabolismo (baja de peso, poliuria) o falla de otros fármacos.",
                                 "Con creatinina 2,3 la TFG está baja: la metformina se reduce o suspende y las sulfonilureas causan hipoglucemia."]),
  ("Varón de 57 años, DM2", ["Dieta + metformina 2 g/día; visión disminuida.", "HbA1c 9,5 %, glucosa 450, creatinina 2,3."]),
  ["Insulina basal (glargina o NPH nocturna, 0,1-0,2 U/kg) y ajustar; añadir rápida si hace falta.",
   "Metformina: reducir a la mitad con TFG 30-45; suspender si < 30.",
   "iSGLT2 y arGLP-1 protegen riñón y corazón: añadir según la TFG."],
  ADA + "; " + KDIGO + ", diabetes en la ERC (2022).",
  op=("¿Conducta?", ["No: hipoglucemia con falla renal", "Sí: glucosa 450 y riñón alterado", "No: hipoglucemia con falla renal", "No: no hay indicación urgente", "No: dosis máxima y riñón dañado"]),
  d=dict(rotulo="El riñón decide los fármacos",
         reglas=[dict(nombre="TFG estimada (mL/min/1,73 m²) y metformina", que="Con creatinina 2,3 en un varón de 57 años, la TFG es ~32.",
                      min=0, max=100, fmt="{}", ticks=[30, 45, 60, 90],
                      bandas=[(0, 30, "< 30: suspender", 3), (30, 45, "30-45: mitad", 2), (45, 100, "Dosis normal", 0)],
                      caso=32, caso_txt="ESTE CASO: ~32"),
                 dict(nombre="Glucemia (mg/dL)", que="Glucosa ≥ 300 con síntomas: insulina.",
                      min=0, max=500, fmt="{}", ticks=[130, 180, 300],
                      bandas=[(0, 130, "Meta en ayunas", 0), (130, 300, "Alta", 1), (300, 500, "≥ 300: insulina", 3)],
                      caso=450, caso_txt="Glucosa 450")],
         claves_titulo="Plan",
         claves=[("Insulina basal", ["0,1-0,2 U/kg/día y ajustar"], True), ("Metformina a la mitad", ["Por la TFG"], False),
                 ("Fondo de ojo y riñón", ["Visión disminuida: retinopatía"], False)]))

# NRL-044 · Síndrome prefrontal · CUADRÍCULA de lóbulos + dibujo
S("cuadricula", "NRL-044", "Varón con 7 meses de euforia, irritabilidad, desinhibición (se orina y desnuda en público), descuido personal y mal juicio: síndrome prefrontal",
  "Neurología de la conducta · lóbulo frontal",
  ("Síndrome prefrontal", ["La corteza prefrontal controla el juicio, la planificación, la inhibición de impulsos y la personalidad.",
                           "Su daño: desinhibición, apatía o euforia, mal juicio, conducta social inadecuada, incontinencia."]),
  ("Varón de 58 años, 7 meses", ["Euforia, irritabilidad, se orina y se desnuda en la sala, descuido personal.", "Problemas de memoria, concentración y decisiones."]),
  ["Causas: demencia frontotemporal (variante conductual), tumor frontal (meningioma), TEC, ACV.",
   "Estudio: RM cerebral, evaluación neuropsicológica.",
   "El tratamiento depende de la causa; apoyo a la familia."],
  HARRISON + "; Adams y Victor, Principios de Neurología 12.ª ed.",
  op=("¿Síndrome?", ["Sí: conducta, juicio e inhibición", "No: negligencia, apraxia, alteración sensitiva", "No: memoria, afasia de comprensión, crisis",
                     "No: alteraciones visuales", "No: ataxia, temblor de intención"]),
  d=dict(rotulo="Qué falla según el lóbulo dañado",
         celdas=[("Frontal (prefrontal)", ["Desinhibición, euforia, mal juicio", "Incontinencia, apatía"], None, True),
                 ("Parietal", ["Negligencia del lado opuesto", "Apraxia, agnosia"], None, False),
                 ("Temporal", ["Memoria, afasia de Wernicke", "Crisis con déjà vu"], None, False),
                 ("Occipital", ["Ceguera cortical", "Hemianopsia"], None, False)],
         veredicto=("Conducta desinhibida + mal juicio + incontinencia = síndrome prefrontal", "RM: buscar demencia frontotemporal o tumor frontal.")),
  banda=B("Dónde está cada lóbulo", P("lobulos.jpg", 380, 285, [("circulo", 0.27, 0.42, 0.12)], credito="ElizabethFG" + CC + "CC BY-SA 3.0", fondo="#ffffff"),
          [("Lóbulo frontal (círculo)", "Delante: conducta y juicio."),
           ("Parietal", "Arriba atrás: sensibilidad y espacio."),
           ("Temporal", "A los lados: memoria y lenguaje."),
           ("Occipital", "Atrás: visión.")],
          pie="Dibujo de los lóbulos."))

# NRL-045 · Cefalea tensional · TARJETAS
S("tarjetas", "NRL-045", "Mujer con cefalea semanal opresiva «en banda» de 2-6 horas que cede con AINE y contractura cervical: cefalea tensional",
  "Cefaleas primarias",
  ("Cefalea tensional", ["La cefalea primaria más frecuente: bilateral, opresiva, leve a moderada, no empeora con el esfuerzo.",
                         "Sin náuseas ni vómitos; como máximo foto o fonofobia (una)."]),
  ("Mujer de 29 años, 9 meses", ["Cefalea semanal de 2-6 horas como una venda apretada.", "Cede con AINE; músculos cervicales contracturados."]),
  ["Crisis: paracetamol o AINE; evitar tomarlos > 10-15 días al mes (cefalea por abuso de analgésicos).",
   "Frecuente o crónica: amitriptilina en dosis baja como profilaxis.",
   "Higiene del sueño, ejercicio, manejo del estrés, fisioterapia."],
  "International Headache Society, ICHD-3 (2018); EFNS (2010).",
  op=("¿Diagnóstico?", ["No: periocular, 15-180 min, con lagrimeo", "Sí: bilateral, opresiva, sin náuseas", "No: pulsátil unilateral con náuseas",
                       "No: dolor al masticar y chasquido", "No: pulsátil con náuseas"]),
  d=dict(rotulo="Cefaleas primarias: ¿cuál?", ans=0,
         cards=[dict(titulo="Tensional", datos=[("Dolor", "Opresivo, en banda", True), ("Lado", "Bilateral", True), ("Náuseas", "No", True)], pie="Este caso."),
                dict(titulo="Migraña", datos=[("Dolor", "Pulsátil", False), ("Lado", "Unilateral", False), ("Náuseas", "Sí", False)], pie="4-72 h."),
                dict(titulo="En racimos", datos=[("Dolor", "Terebrante", False), ("Lado", "Ojo, un lado", False), ("Además", "Lagrimeo, rinorrea", False)], pie="Varones."),
                dict(titulo="Temporomandibular", datos=[("Dolor", "Preauricular", False), ("Al", "Masticar", False), ("Además", "Chasquido", False)], pie="Bruxismo.")]))

# NRL-046 · FA sin anticoagular: ACV isquémico · DECISIÓN + CHA2DS2-VASc
S("decision", "NRL-046", "Anciano con fibrilación auricular sin anticoagular que en 2 horas desarrolla afasia y hemiparesia derecha, con TC normal: ACV isquémico (cardioembólico)",
  "Enfermedad cerebrovascular · ACV isquémico",
  ("ACV isquémico cardioembólico", ["En la FA se forman trombos en la orejuela izquierda que embolizan al cerebro.",
                                    "La TC precoz suele ser normal en el infarto (sirve para descartar sangrado)."]),
  ("Varón de 72 años, FA crónica sin anticoagular", ["Hace 2 horas: no puede hablar y hemiplejia derecha que aumenta.", "TC cerebral sin alteraciones."]),
  ["< 4,5 h y sin contraindicación: trombólisis EV (alteplasa o tenecteplasa).",
   "Oclusión de gran vaso: trombectomía hasta 24 h (angio-TC).",
   "Después: anticoagulación oral (anticoagulante directo) para prevenir otro embolismo."],
  "AHA/ASA, ACV isquémico agudo (2019; act. 2026); ESO (2021).",
  op=("¿Causa?", ["Sí: émbolo por FA; TC normal al inicio", "No: la TC lo mostraría", "No: la TC mostraría sangre y habría cefalea súbita", "No: tras trauma", "No: curso lento"]),
  d=dict(rotulo="Déficit neurológico agudo: ¿qué muestra la TC?", eje_y="TC sin contraste", ancho_filas=200,
         cols=["≤ 4,5 horas", "> 4,5 horas"],
         rows=[("Normal (no hay sangre)", "Infarto aún no visible"), ("Sangre", "Hemorragia")],
         cells=[[("ACV isquémico: trombólisis", ["± trombectomía si gran vaso"]), ("ACV isquémico", ["Trombectomía si hay tejido salvable"])],
                [("Hemorragia: no trombolizar", ["Controlar PA, revertir anticoagulantes"]), ("Hemorragia", [])]],
         caso=(0, 0), nota="Con FA sin anticoagular, el origen más probable es cardioembólico."),
  escala=dict(nombre="CHA₂DS₂-VASc (antes del ACV)", modo="puntaje", que="Riesgo de ACV en la FA: ≥ 2 en varones = anticoagular.",
              items=[("C", "Insuficiencia cardíaca (1)", "No informada", None), ("H", "Hipertensión (1)", "No informada", None), ("A₂", "Edad ≥ 75 (2) / 65-74 (1)", "72 años", 1),
                     ("D", "Diabetes (1)", "No informada", None), ("S₂", "ACV previo (2)", "No (este es el primero)", 0)],
              total_txt="Total: ≥ 1 antes; ahora ≥ 3 (ACV)", total_nota="máximo 9",
              rangos=[("0", "Bajo", "No anticoagular"), ("1", "Intermedio", "Considerar"), ("≥ 2", "Alto", "Anticoagular")],
              caso_rango=2, porque=[("Tras el ACV suma 2 puntos más", True)], conducta="Anticoagulación oral al pasar la fase aguda."))

# REU-050 · Psoriasis · LECTURA (foto) + uñas
S("lectura", "REU-050", "Varón con eritrodermia, uñas en dedal y placas eritematosas con escamas nacaradas en codos, rodillas y cuero cabelludo: psoriasis",
  "Dermatosis eritematoescamosas · psoriasis",
  ("Psoriasis", ["Enfermedad inflamatoria crónica: placas rojas bien delimitadas con escama blanca plateada en zonas de extensión.",
                 "Uñas: hoyuelos (dedal), mancha de aceite, onicólisis; puede asociarse a artritis psoriásica."]),
  ("Varón de 43 años, 1 mes", ["Eritrodermia y malestar general.", "Uñas en dedal; placas con escamas nacaradas en codos, rodillas y cuero cabelludo."]),
  ["Eritrodermia psoriásica: hospitalizar (pierde calor, líquidos y proteínas).",
   "Leve: corticoide tópico + calcipotriol. Moderada-grave: metotrexato, ciclosporina, fototerapia o biológicos.",
   "No dar corticoide sistémico: al retirarlo desencadena brotes pustulosos."],
  "AAD-NPF, psoriasis (2019-2021); EuroGuiDerm (2023).",
  op=("¿Diagnóstico?", ["No: placas en tronco, sin uñas en dedal", "Sí: escamas nacaradas + uñas en dedal", "No: pliegues, prurito, infancia", "No: aguda, dolorosa, febril", "No: máculas finas en tronco"]),
  d=dict(rotulo="Lee la imagen en este orden", img_titulo="Placa de psoriasis y uña",
         img=P("psoriasis_mont.jpg", 400, 230, [], credito="Marnanel (CC BY-SA 3.0) y Seenms (CC BY-SA 3.0)" + CC.rstrip(" · ")),
         pines=[(0.21, 0.45), (0.77, 0.40)],
         pasos=[("Placas rojas con escama plateada", "Bien delimitadas, en codos y rodillas.", False),
                ("Uña con hoyuelos (en dedal)", "Pitting: muy sugestivo.", True),
                ("Signo de Auspitz", "Al raspar, puntitos de sangre.", False),
                ("Eritrodermia", "> 90 % de la piel roja: hospitalizar.", False)],
         img_pie="Fotos de otros pacientes.",
         veredicto=("Placas con escama nacarada + uñas en dedal = psoriasis", "La eritrodermia se maneja hospitalizado; no corticoide sistémico.")))

# PED-156 · Faringoamigdalitis estreptocócica · CRITERIOS (Centor-McIsaac) + foto
S("criterios", "PED-156", "Escolar con fiebre, odinofagia, amígdalas con pus, petequias en el paladar, vómitos y dolor abdominal: faringoamigdalitis estreptocócica",
  "Faringoamigdalitis en el niño",
  ("Faringoamigdalitis por estreptococo", ["Streptococcus pyogenes: niños de 5-15 años; fiebre, exudado, adenopatías dolorosas, petequias en el paladar.",
                                           "Dolor abdominal y vómitos son frecuentes en niños; la tos y la rinorrea orientan a virus."]),
  ("Escolar de 8 años", ["2 días de fiebre, dolor de garganta y disfagia; hoy vómitos y dolor abdominal.", "Faringe roja, amígdalas grandes con pus, petequias en paladar blando."]),
  ["Confirmar con prueba rápida de antígeno o cultivo (en niños).",
   "Amoxicilina 50 mg/kg/día por 10 días o penicilina benzatínica IM dosis única: previene la fiebre reumática.",
   "Alergia: cefalexina o azitromicina (5 días)."],
  IDSA + ", faringitis por estreptococo (2012; act.); AHA, fiebre reumática; " + MINSA + ".",
  op=("¿Diagnóstico?", ["Sí: exudado + petequias + fiebre", "No: rigidez de cuello, abombamiento posterior", "No: adenopatías y bazo, 10+ días",
                        "No: membrana gris adherente", "No: tos y rinorrea, sin exudado"]),
  d=dict(rotulo="Puntaje de Centor-McIsaac", lista_titulo="Criterios",
         items=[("Fiebre > 38 °C (+1)", True, "Sí"), ("Exudado o hinchazón amigdalar (+1)", True, "Amígdalas con pus"),
                ("Adenopatía cervical anterior dolorosa (+1)", None, "No descrita"), ("Ausencia de tos (+1)", False, "Tiene tos"),
                ("Edad 3-14 años (+1)", True, "8 años")],
         umbral="≥ 3: prueba rápida o cultivo; positivo → antibiótico",
         veredicto="3 puntos + petequias en el paladar: prueba rápida y, si es positiva, amoxicilina 10 días.",
         img=P("strep_petequias.jpg", 250, 216, [], credito="CDC · dominio público"), img_titulo="Petequias en el paladar",
         img_pie="Foto de otro niño.", conteo="3 puntos"))

# SP-121 · Variable dependiente · ÁRBOL
S("arbol", "SP-121", "En un experimento, la variable dependiente es aquella en la que se observan los cambios (el efecto que se mide)",
  "Investigación · variables",
  ("Variables de un experimento", ["Independiente: la que el investigador manipula (la causa).",
                                   "Dependiente: la que se mide para ver el efecto. Controladas: se mantienen constantes."]),
  ("Pregunta de teoría", ["En un diseño experimental,", "¿qué es la variable dependiente?"]),
  ["Truco: la dependiente «depende» de lo que hace el investigador.",
   "Ejemplo: fármaco (independiente) → presión arterial (dependiente).",
   "Las que se mantienen constantes son variables controladas, no dependientes."],
  "Hernández Sampieri, Metodología de la investigación 7.ª ed.",
  op=("¿Variable dependiente?", ["No: no depende del investigador", "No: esa es la independiente", "Sí: donde se ven los cambios", "No: eso es un mal concepto", "No: es una variable controlada"],
      {1: "La que se manipula para causar efectos"}),
  arbol=Q("¿Qué papel cumple la variable?", [
      L("Se mide el cambio (este caso)", "DEPENDIENTE", ["El efecto"], path=True),
      L("Se manipula", "Independiente", ["La causa"]),
      L("Se mantiene igual", "Controlada", ["Evita confusión"])], path=True))

# PSI-031 · Delirium tremens · FASES (abstinencia) + CIWA
S("fases", "PSI-031", "Bebedor fuerte al 2.º día de una operación con confusión, zoopsias, fiebre, taquicardia, midriasis, temblor y sudoración: síndrome de abstinencia alcohólica (delirium tremens)",
  "Trastornos por alcohol · abstinencia",
  ("Abstinencia alcohólica", ["Al suspender el alcohol, el cerebro queda sin el freno GABA: hiperactividad simpática.",
                              "Delirium tremens a las 48-96 h: confusión, alucinaciones (zoopsias), fiebre, taquicardia; mortalidad sin tratamiento ~5-15 %."]),
  ("Varón de 40 años, 2.º día posoperatorio", ["Ansioso, confuso; ve serpientes y escorpiones en la cama; bebe > 40 g de alcohol al día.",
                                                "FC 100, T 38 °C, midriasis, temblor, sudoración profusa."]),
  ["Benzodiacepinas en dosis altas (diazepam, lorazepam si hay daño hepático) guiadas por síntomas (CIWA-Ar).",
   "Tiamina EV antes de la glucosa (Wernicke), líquidos, electrolitos y magnesio.",
   "Ambiente tranquilo; evitar haloperidol solo (baja el umbral convulsivo)."],
  "ASAM, manejo de la abstinencia alcohólica (2020); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["Sí: alcohol + zoopsias + hiperactividad simpática", "No: hipoxemia y petequias a 24-72 h de la fractura", "No: tras trauma craneal, sin hiperactividad simpática",
                        "No: sin falla renal", "No: confusión, ataxia y oftalmoplejía, sin fiebre ni zoopsias"]),
  d=dict(rotulo="Cuándo aparece cada síntoma de la abstinencia", ans=2,
         fases=[("Temblor y ansiedad", "6-24 h", "ABSTINENCIA MENOR", ["Taquicardia, sudor"]),
                ("Convulsiones", "12-48 h", "CRISIS", ["Tónico-clónicas"]),
                ("Delirium tremens", "48-96 h", "DELIRIUM", ["Zoopsias, fiebre", "Este caso (2.º día)"])]),
  escala=dict(nombre="Escala CIWA-Ar", modo="puntaje", que="Gravedad de la abstinencia; guía la dosis de benzodiacepina.",
              items=[("Temb", "Temblor (0-7)", "Manos y párpados", None), ("Sud", "Sudoración (0-7)", "Profusa", None),
                     ("Aluc", "Alucinaciones visuales (0-7)", "Serpientes, escorpiones", None), ("Orient", "Orientación (0-4)", "Confuso", None)],
              total_txt="Total: alto (> 20) por los datos", total_nota="máximo 67",
              rangos=[("< 8", "Leve", "Vigilar"), ("8-15", "Moderada", "Benzodiacepina"), ("> 15", "Grave", "Benzodiacepina, UCI")],
              caso_rango=2, porque=[("Alucinaciones + temblor + sudor + confusión", True)], conducta="Benzodiacepina EV y tiamina; UCI si no se controla."))

# REU-051 · Urticaria aguda · TARJETAS + foto
S("tarjetas", "REU-051", "Preescolar que tras comer cítricos presenta ronchas de distintos tamaños, rojas con centro pálido y muy pruriginosas: urticaria aguda",
  "Dermatología pediátrica · urticaria",
  ("Urticaria aguda", ["Ronchas (habones) que pican y desaparecen en < 24 h sin dejar marca; dura < 6 semanas.",
                       "Causas: infecciones virales (la más común en niños), alimentos, fármacos, picaduras."]),
  ("Preescolar", ["Tras comer cítricos.", "Pápulas rojas con centro pálido, de distintos tamaños y muy pruriginosas."]),
  ["Antihistamínico H1 de 2.ª generación (cetirizina, loratadina, desloratadina).",
   "Corticoide oral por 3-5 días solo si es muy extensa.",
   "Buscar signos de anafilaxia: disnea, estridor, vómitos, hipotensión → adrenalina IM."],
  "EAACI/GA²LEN/WAO, urticaria (2022); AAP.",
  op=("¿Diagnóstico?", ["No: eccema crónico, no ronchas migratorias", "Sí: habones que pican y migran", "No: anillo con borde descamativo",
                       "No: sin compromiso respiratorio ni circulatorio", "No: surcos y prurito nocturno"]),
  d=dict(rotulo="Lesiones rojas que pican: ¿cuál?", ans=0,
         cards=[dict(titulo="Urticaria", datos=[("Lesión", "Roncha que cambia de sitio", True), ("Dura", "< 24 h cada una", True), ("Marca", "No deja", True)], pie="Este caso."),
                dict(titulo="Anafilaxia", datos=[("Además", "Disnea, estridor", False), ("PA", "Puede bajar", False), ("Tratar", "Adrenalina IM", False)], pie="Urgencia."),
                dict(titulo="Tiña corporal", datos=[("Lesión", "Anillo descamativo", False), ("Crece", "Lento, días", False), ("Causa", "Hongo", False)], pie="KOH."),
                dict(titulo="Dermatitis atópica", datos=[("Lesión", "Eccema, piel seca", False), ("Zona", "Pliegues", False), ("Curso", "Crónico", False)], pie="Antecedentes.")]),
  banda=B("Así se ve la urticaria", P("urticaria.jpg", 210, 280, [], credito="Psixtras" + CC + "CC0"),
          [("Ronchas con borde rojo", "Elevadas, centro más pálido."), ("Cambian de lugar", "Cada una dura horas."), ("Prurito intenso", "Rascarse no deja costra.")],
          pie="Foto de otra persona."))

# GIN-159 · Endometritis puerperal · CHECKLIST
S("checklist", "GIN-159", "Para la endometritis puerperal el tratamiento antibiótico de elección es clindamicina + gentamicina EV",
  "Infección puerperal · endometritis",
  ("Endometritis puerperal", ["Infección del útero tras el parto, más tras cesárea, RPM prolongada o muchos tactos.",
                              "Polimicrobiana con anaerobios: fiebre, útero blando y doloroso, loquios fétidos."]),
  ("Pregunta de teoría", ["¿Antibiótico de elección", "en la endometritis puerperal?"]),
  ["Clindamicina 900 mg c/8 h + gentamicina 5 mg/kg/día EV hasta 24-48 h sin fiebre; no hace falta oral después.",
   "Si no mejora en 48-72 h: añadir ampicilina (enterococo) y buscar absceso o tromboflebitis pélvica.",
   "Revisar restos placentarios (eco)."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ".",
  op=("¿Tratamiento?", ["Sí: cubre anaerobios y gramnegativos", "No: cobertura incompleta de anaerobios", "No: falta gramnegativos", "Alternativa posible, no la clásica de elección", "No: solo anaerobios"]),
  d=dict(rotulo="Cómo tratar la endometritis puerperal", tag="ELECCIÓN",
         pasos=[("Clindamicina + gentamicina EV", "Hasta 24-48 h sin fiebre", True), ("Revisar restos placentarios", "Ecografía", False),
                ("Si no mejora en 48-72 h", "Añadir ampicilina; buscar absceso o tromboflebitis", False), ("Alta", "Sin antibiótico oral si respondió", False)],
         no_hacer=[("Tratar solo con metronidazol", "No cubre gramnegativos"), ("Esperar sin antibiótico", "Riesgo de sepsis")],
         veredicto=("Clindamicina + gentamicina", "Si no responde, añadir ampicilina y buscar complicaciones.")))

# REU-052 · Impétigo sobre lesiones de rascado · ÁRBOL + foto
S("arbol", "REU-052", "Niño con urticaria previa que presenta vesículas sobre zonas de rascado que se rompen y dejan erosiones con costras melicéricas: piodermitis (impétigo)",
  "Infecciones bacterianas de la piel",
  ("Piodermitis (impétigo secundario)", ["La piel rascada (urticaria, picaduras, sarna, eccema) se infecta con S. aureus o S. pyogenes.",
                                         "Vesículas que se rompen y dejan costras color miel: «impetiginización»."]),
  ("Preescolar de 5 años", ["Urticaria previa; vesículas en zonas de rascado desde hace 4 días.", "Se rompen y dejan erosión húmeda con costras melicéricas."]),
  ["Pocas lesiones: mupirocina o ácido fusídico tópico; muchas: cefalexina oral.",
   "Tratar la causa del rascado (antihistamínico).",
   "Higiene y uñas cortas."],
  IDSA + " (2014); AAP Red Book (2024).",
  op=("¿Diagnóstico?", ["No: placa roja difusa, profunda", "Sí: costras melicéricas sobre rascado", "No: placa roja de borde nítido con fiebre",
                        "No: lesiones en distintos estadios en todo el cuerpo", "No: vesículas agrupadas en un sitio, dolorosas"]),
  arbol=Q("Vesículas que dejan costras: ¿de qué color son las costras?", [
      L("Color miel (este caso)", "IMPÉTIGO / PIODERMITIS", ["Mupirocina o cefalexina"], path=True),
      L("Oscuras, en distintos estadios", "Varicela", ["Fiebre, todo el cuerpo"]),
      L("Agrupadas sobre base roja", "Herpes simple", ["Dolor, recurrente"])], path=True),
  banda=B("Así se ven las costras", P("impetigo.jpg", 270, 313, [], credito="Evanherk" + CC + "CC BY-SA 3.0"),
          [("Costras color miel", "Melicéricas."), ("Sobre piel rascada", "Infección secundaria."), ("Contagiosas", "Higiene y uñas cortas.")],
          pie="Foto de otro niño."))

# GIN-160 · Proteínas en el embarazo · RADIAL
S("radial", "GIN-160", "El objetivo de aumentar las proteínas en el embarazo es cubrir las necesidades de la madre y del feto",
  "Nutrición en el embarazo",
  ("Proteínas en el embarazo", ["Se necesitan para el feto, la placenta, el aumento del volumen de sangre, el útero y las mamas.",
                                "Requerimiento: ~1,1 g/kg/día (unos 25 g más por día en el 2.º y 3.er trimestre)."]),
  ("Pregunta de teoría", ["¿Para qué se aumenta la ingesta de proteínas", "en el embarazo?"]),
  ["Fuentes: huevo, pescado, carnes, legumbres, lácteos (mejor combinarlas).",
   "Las proteínas no previenen la preeclampsia (eso lo hacen el calcio y la aspirina en riesgo).",
   "El volumen sanguíneo AUMENTA ~40-50 % en el embarazo."],
  OMS + ", nutrición en el embarazo (2016); IOM.",
  op=("¿Objetivo?", ["Sí: madre y feto crecen", "No: lo previenen el calcio y la aspirina", "No: no es su fin", "No: el volumen aumenta", "No: no es su objetivo"]),
  d=dict(rotulo="Para qué sirven las proteínas extra", centro="MADRE Y FETO", centro_sub="este caso", ans=0,
         items=[("FETO", ["Crecimiento de órganos y músculo"]), ("PLACENTA", ["Se forma y crece"]), ("SANGRE MATERNA", ["+40-50 % de volumen"]),
                ("ÚTERO Y MAMAS", ["Crecen"]), ("RESERVA", ["Para la lactancia"])],
         ruta=["1,1 g/kg/día", "Fuentes variadas", "Hierro y calcio", "Controlar el peso"]))

# OFT-035 · Absceso periamigdalino · LECTURA (foto)
S("lectura", "OFT-035", "Joven con 5 días de odinofagia, fiebre, otalgia derecha, trismus y amígdala derecha abombada con pus: absceso periamigdalino",
  "Otorrinolaringología · complicaciones de la amigdalitis",
  ("Absceso periamigdalino", ["Pus entre la amígdala y su cápsula, casi siempre tras una faringoamigdalitis (S. pyogenes y anaerobios).",
                              "Trismus, voz de «papa caliente», úvula desviada al lado sano, otalgia refleja."]),
  ("Varón de 21 años, 5 días", ["Dolor faríngeo, fiebre, odinofagia y otalgia derecha.", "Trismus; amígdala derecha aumentada con pus."]),
  ["Drenaje: punción-aspiración con aguja o incisión.",
   "Antibiótico: ampicilina-sulbactam o amoxicilina-clavulánico (± clindamicina); analgesia, hidratación.",
   "Amigdalectomía si hay recurrencias."],
  "AAO-HNS; " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: hinchazón bajo la mandíbula, no amígdala", "No: úvula roja e hinchada", "Sí: trismus + abombamiento + úvula desviada",
                        "No: sin fiebre ni pus, edema blando", "No: sin trismus ni pus"]),
  d=dict(rotulo="Lee la imagen en este orden", img_titulo="Absceso periamigdalino",
         img=P("periamig.jpg", 270, 294, credito="James Heilman" + CC + "CC BY-SA 3.0"), pines=[(0.6, 0.45), (0.45, 0.55)],
         pasos=[("Abombamiento sobre la amígdala", "Pus que empuja el paladar.", True),
                ("Úvula desviada al lado sano", "Signo clave.", False),
                ("Trismus", "No abre bien la boca (músculo pterigoideo irritado).", False),
                ("Drenar", "Punción o incisión + antibiótico.", False)],
         img_pie="Foto de otro paciente.",
         veredicto=("Trismus + otalgia + amígdala abombada = absceso periamigdalino", "Drenaje y antibiótico.")))

# CIR-092 · Quemaduras: regla de los 9 · CÁLCULO + dibujo
S("arbol", "CIR-092", "Quemadura con agua hirviendo en ambas caras de los dos miembros superiores y la cara anterior del tronco: 36 % de superficie corporal (regla de los 9)",
  "Quemaduras · superficie corporal",
  ("Regla de los 9 de Wallace (adulto)", ["Cabeza 9 %, cada brazo 9 % (4,5 cada cara), cada pierna 18 %, tronco anterior 18 %, posterior 18 %, periné 1 %.",
                                          "Solo se suman las quemaduras de 2.º y 3.er grado."]),
  ("Mujer de 20 años", ["Quemadura con agua hervida.", "Ambas caras de los dos miembros superiores y cara anterior del tronco."]),
  ["Brazos: 9 + 9 = 18 %. Tronco anterior: 18 %. Total: 36 %.",
   "> 20 % en adultos: reposición con Parkland (4 mL × kg × % SCQ; mitad en 8 h).",
   "En niños se usa la tabla de Lund-Browder (la cabeza pesa más)."],
  "ABA; " + ATLS + ".",
  op=("¿Porcentaje?", ["Sí: 9 + 9 + 18", "No: falta un brazo", "No: no suma así", "No: solo el tronco anterior", "No: suma de más"]),
  arbol=Q("Suma por zonas", [
      L("Dos brazos completos", "9 % + 9 % = 18 %", ["Ambas caras"], path=True),
      L("Tronco anterior", "18 %", ["Pecho y abdomen"], path=True),
      L("Total", "36 %", ["→ Parkland"], path=True)], path=True),
  banda=B("La regla de los 9", PA("dib_regla9_adulto.jpg", 380, [], credito=PROPIO, fondo="#ffffff"),
          [("Brazo", "9 % cada uno (4,5 % por cara)."), ("Tronco anterior", "18 %."), ("Este caso", "18 + 18 = 36 %.")],
          pie="Esquema."))

# GAS-056 · Insuficiencia hepática aguda · LABORATORIO + West Haven
S("laboratorio", "GAS-056", "Joven con ictericia de una semana, luego vómitos y desorientación, flapping, equimosis y glucosa de 55: insuficiencia hepática aguda",
  "Hepatología · insuficiencia hepática aguda",
  ("Insuficiencia hepática aguda", ["Daño hepático grave en < 26 semanas sin hepatopatía previa: INR ≥ 1,5 + encefalopatía.",
                                    "Causas: paracetamol, virus (hepatitis A, B, E), fármacos, autoinmune."]),
  ("Mujer de 34 años", ["Ictericia hace 1 semana, vómitos y desde ayer desorientada.", "Soporosa, flapping (+), ictericia, equimosis; glucosa 55."]),
  ["UCI y referencia a un centro de trasplante; N-acetilcisteína (útil incluso sin paracetamol).",
   "Corregir la hipoglucemia, proteger la vía aérea si la encefalopatía es grado 3-4.",
   "Buscar la causa: paracetamol, serologías virales, autoinmunidad."],
  "AASLD, insuficiencia hepática aguda (2011; act.); EASL (2017).",
  op=("¿Diagnóstico?", ["No: la hipoglucemia es consecuencia", "No: sin dolor ni fiebre típica", "No: fiebre y dolor; no encefalopatía así", "Sí: ictericia + encefalopatía + coagulopatía", "No: sin antecedente de alcohol"]),
  d=dict(rotulo="Lo que indica cada dato", valores=[
            ("Encefalopatía", "Soporosa, flapping", "Alerta", "↑", "El hígado no limpia el amonio."),
            ("Coagulación", "Equimosis", "INR < 1,2", "↑", "No fabrica factores: INR alto."),
            ("Glucosa", "55 mg/dL", "70-100", "↓", "No hace gluconeogénesis."),
            ("Bilirrubina", "Ictericia", "< 1,2", "↑", "No conjuga ni excreta."),
            ("Tiempo", "< 2 semanas", "—", "=", "Hiperaguda/aguda: sin hepatopatía previa.")],
         veredicto=("Ictericia + encefalopatía + coagulopatía en días = insuficiencia hepática aguda", "UCI, N-acetilcisteína y centro de trasplante.")),
  escala=dict(nombre="Encefalopatía hepática (West Haven)", que="Grado de la encefalopatía.",
              grados=[("1", "Leve", ["Cambios del sueño y la atención"]), ("2", "Moderada", ["Desorientación, flapping"]),
                      ("3", "Grave", ["Somnolienta pero despierta al estímulo"]), ("4", "Coma", ["No responde"])],
              caso=[1, 2], porque=[("Desorientada y soporosa con flapping", True)], conducta="Proteger la vía aérea si avanza a grado 3-4."),
  banda=B("La ictericia", P("ictericia.jpg", 400, 125, [], credito="Dominio público" + CC.rstrip(" · ")),
          [("Escleras amarillas", "Bilirrubina > 2,5-3 mg/dL."), ("Con confusión", "Pensar en falla hepática."), ("Medir INR", "≥ 1,5 define la falla.")],
          pie="Foto de otra persona (solo los ojos)."))

# GAS-057 · HDA con choque hipovolémico · MONITOR + choque
S("monitor", "GAS-057", "Mujer con úlcera péptica mal tratada con melena, hematemesis abundante, PA 80/40 y FC 118: choque hipovolémico por hemorragia digestiva alta",
  "Choque · clasificación",
  ("Choque hipovolémico", ["Pérdida de volumen (sangre): baja la precarga y el gasto; el corazón se acelera.",
                           "Piel fría, pálida, yugulares planas, llenado capilar lento."]),
  ("Mujer de 45 años, úlcera péptica", ["Melena hace 2 h, ansiosa, luego hematemesis (2 tazas).", "PA 80/40, FC 118."]),
  ["2 vías gruesas, cristaloides y sangre (meta de Hb 7-8; transfundir de forma restrictiva).",
   "IBP EV en bolo e infusión; endoscopía en < 24 h (antes si no se estabiliza).",
   "Índice de choque = FC/PAS: 118/80 ≈ 1,5 (> 1 = choque)."],
  "ACG, hemorragia digestiva alta (2021); ESGE (2021); " + ATLS + ".",
  op=("¿Tipo de choque?", ["Sí: pierde volumen (sangre)", "No: sepsis o anafilaxia", "No: falla del corazón", "No: taponamiento o TEP", "No: lesión medular"]),
  d=dict(rotulo="Los signos vitales del caso", ecg="taquicardia sinusal 118",
         valores=[("PA", "80/40", "mmHg", "bajo"), ("FC", "118", "lpm", "alto"), ("ÍNDICE CHOQUE", "1,5", "FC/PAS", "alto"), ("PIEL", "pálida", "", "bajo")],
         lectura=[("PA baja + taquicardia + sangrado", "Hipovolémico: falta volumen.", True),
                  ("Índice de choque > 1", "Pérdida probable > 30 % (clase III).", True),
                  ("Si fuera piel caliente", "Distributivo (sepsis, anafilaxia).", False),
                  ("Si yugulares llenas", "Cardiogénico u obstructivo.", False)],
         veredicto=("Choque hipovolémico por hemorragia digestiva alta", "Volumen, sangre, IBP y endoscopía.")))

# CB-060 · SARS-CoV-2: neumocito tipo II · CASCADA + TC
S("cascada", "CB-060", "El SARS-CoV-2 infecta directamente a los neumocitos tipo II, que tienen el receptor ACE2",
  "Microbiología · patogenia de la COVID-19",
  ("Neumocito tipo II y el SARS-CoV-2", ["El virus entra por la proteína S unida al receptor ACE2 (y la proteasa TMPRSS2) del neumocito tipo II.",
                                         "Sin neumocitos II no hay surfactante ni reparación del alvéolo: daño alveolar difuso."]),
  ("Diabético de 58 años con sospecha de COVID-19", ["Dificultad respiratoria, SatO₂ 84 %.", "Rx: marcado compromiso alveolar."]),
  ["Neumocito I: 95 % de la superficie, intercambio gaseoso. Neumocito II: surfactante y regeneración del epitelio.",
   "El daño produce SDRA: vidrio esmerilado y consolidaciones bilaterales.",
   "Oxígeno, prono despierto, dexametasona si necesita oxígeno; anticoagulación profiláctica."],
  "Robbins y Cotran, Patología estructural y funcional 10.ª ed.; OMS, manejo clínico de la COVID-19 (2025).",
  op=("¿Célula afectada?", ["No es la diana directa principal", "Sí: tiene ACE2", "Se daña después", "No: es de la vía aérea", "No: es del bronquiolo"]),
  d=dict(rotulo="Del virus a la hipoxemia", cabeceras=("Mecanismo", "En este caso"),
         pasos=[("Proteína S se une a ACE2", "Del neumocito tipo II", [("Infección del neumocito II", "", True)]),
                ("Muere el neumocito II", "Menos surfactante y menos reparación", [("Alvéolos colapsados", "", False)]),
                ("Inflamación y edema", "Daño alveolar difuso (membranas hialinas)", [("Compromiso alveolar en la Rx", "", True)]),
                ("No pasa el oxígeno", "Cortocircuito", [("SatO₂ 84 %", "Diabético: más riesgo", True)])],
         veredicto=("La célula diana directa es el neumocito tipo II (ACE2)", "Su daño lleva al daño alveolar difuso.")),
  banda=B("Así se ve en la TC", PA("covid_tc.jpg", 330, [], credito="Wang et al. · Curr Med Imaging 2026 · PMC13613316 · CC BY 4.0"),
          [("Vidrio esmerilado bilateral", "Alvéolos con líquido, aún con aire."), ("Consolidaciones", "Alvéolos llenos."),
           ("Periférico y basal", "Patrón típico de COVID-19.")],
          pie="TC de otra paciente."))
