"""Entrega 2 · tanda 14 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from esc28 import HIPERK

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"

# CAR-047 · Toxicidad pulmonar por amiodarona · TARJETAS
S("tarjetas", "CAR-047", "Anciano con fibrilación auricular tratado 5 años con un antiarrítmico, con disnea progresiva, tos seca y pérdida de peso: toxicidad pulmonar por amiodarona",
  "Farmacología cardiovascular · efectos adversos",
  ("Toxicidad pulmonar por amiodarona", ["Neumonitis intersticial que puede llevar a fibrosis; más con dosis altas y uso prolongado.",
                                         "Disnea, tos seca, pérdida de peso; infiltrados en la Rx y DLCO baja."]),
  ("Varón de 70 años con FA crónica", ["Antiarrítmico desde hace 5 años.", "Disnea a mínimos esfuerzos, tos seca persistente y pérdida de peso."]),
  ["Suspender la amiodarona y dar corticoides; TC de tórax y espirometría con DLCO.",
   "Otros efectos: hipo o hipertiroidismo, hepatitis, depósitos corneales, piel gris-azulada, fotosensibilidad.",
   "Control basal y periódico: TSH, enzimas hepáticas, Rx de tórax y función pulmonar."],
  ESC + ", fibrilación auricular (2024); " + HARRISON + ".",
  op=("¿Fármaco?", ["No: estreñimiento, bradicardia", "No: lupus inducido", "Sí: fibrosis pulmonar", "No: proarritmia", "No: náuseas, visión amarilla"]),
  d=dict(rotulo="Antiarrítmico y su efecto adverso típico", ans=0,
         cards=[dict(titulo="Amiodarona", datos=[("Pulmón", "Fibrosis", True), ("Tiroides", "Hipo o hiper", True), ("Piel", "Gris-azulada", True)],
                     pie="Este caso."),
                dict(titulo="Procainamida", datos=[("Efecto", "Lupus inducido", False), ("Ac", "Antihistona", False), ("ECG", "QT largo", False)],
                     pie="Clase IA."),
                dict(titulo="Verapamilo", datos=[("Efecto", "Estreñimiento", False), ("Corazón", "Bradicardia", False), ("Evitar", "IC con FE baja", False)],
                     pie="Calcioantagonista."),
                dict(titulo="Digoxina", datos=[("Efecto", "Náuseas", False), ("Visión", "Amarilla", False), ("Riesgo", "Hipopotasemia", False)],
                     pie="Intoxicación.")]))

# PED-126 · Neumonía afebril del lactante por Chlamydia · TARJETAS + tríada
S("tarjetas", "PED-126", "Lactante de 2 meses con conjuntivitis previa, tos, taquipnea sin fiebre e infiltrados intersticiales con hiperinsuflación: neumonía por Chlamydia trachomatis",
  "Neumonía en el lactante · neumonía afebril",
  ("Neumonía afebril del lactante", ["Chlamydia trachomatis se adquiere en el parto: primero conjuntivitis (1-2 semanas), luego neumonía (2-19 semanas).",
                                     "Sin fiebre, tos en staccato, taquipnea; Rx con hiperinsuflación e infiltrado intersticial; puede haber eosinofilia."]),
  ("Lactante de 2 meses", ["5 días de rinorrea, tos y dificultad respiratoria, sin fiebre; conjuntivitis previa.",
                           "FR 62, SatO₂ 91 %, subcrépitos; Rx: hiperinsuflación e infiltrados intersticiales."]),
  ["Azitromicina 20 mg/kg/día por 3 días (o eritromicina 14 días; vigilar estenosis pilórica).",
   "Tratar a la madre y a su pareja.",
   "Oxígeno si SatO₂ < 92 %."],
  "AAP, Red Book (2024-2027); " + CDC + ", guías de ITS (2021, act. 2024).",
  op=("¿Agente?", ["Sí: afebril + conjuntivitis previa", "No: sepsis neonatal temprana", "No: fiebre, consolidación", "No: fiebre, consolidación",
                   "Causa bronquiolitis con sibilancias"]),
  d=dict(rotulo="Infección respiratoria en el lactante pequeño", ans=0,
         cards=[dict(titulo="Chlamydia", datos=[("Fiebre", "No", True), ("Antes", "Conjuntivitis", True), ("Rx", "Intersticial", True)],
                     pie="Este caso."),
                dict(titulo="VSR", datos=[("Clínica", "Bronquiolitis", False), ("Sonido", "Sibilancias", False), ("Época", "Invierno", False)],
                     pie="Viral."),
                dict(titulo="Neumococo", datos=[("Fiebre", "Alta", False), ("Rx", "Consolidación", False), ("Trato", "Amoxicilina", False)],
                     pie="Típica."),
                dict(titulo="Estreptococo B", datos=[("Edad", "Primeros días", False), ("Cuadro", "Sepsis", False), ("Madre", "Colonizada", False)],
                     pie="Neonatal.")]),
  triada=TR([("Afebril", "37 °C", True), ("Conjuntivitis previa", "Sí", True), ("Tos en staccato", "No se describe", None), ("Eosinofilia", "No se da", None)],
            [("Neumonía afebril por Chlamydia", 0, 3)],
            "Edad típica: 2 a 19 semanas."))

# SP-085 · Beneficencia: demora ante patrón fetal categoría III · TARJETAS + NICHD
S("tarjetas", "SP-085", "Obstetra que decide esperar un parto vaginal pese a bradicardia fetal, meconio espeso y patrón de categoría III: falta al principio de beneficencia",
  "Bioética · obstetricia",
  ("Beneficencia", ["Obligación de actuar en favor del paciente: aquí, sacar al feto en peligro.",
                    "Un trazado de categoría III indica hipoxia fetal: se debe terminar el parto ya."]),
  ("Primigesta de 41 semanas", ["RPM de 3 h; LCF 109; 4 cm; líquido meconial espeso.", "Monitoreo: categoría III; el médico (al final de su turno) decide esperar."]),
  ["Categoría III: medidas de reanimación intrauterina y parto inmediato (cesárea si no es inminente).",
   "El cambio de turno no justifica demorar una decisión urgente.",
   "Meconio espeso + bradicardia: equipo de reanimación neonatal presente."],
  ACOG + ", monitoreo fetal intraparto (2010, reafirmado); Beauchamp y Childress.",
  op=("¿Principio que falta?", ["No: la paciente no rechazó nada", "No es un principio clásico", "Sí: no actúa en favor del paciente",
                                "No: no es reparto de recursos", "No: no se revela información"]),
  d=dict(rotulo="Principios de la bioética", ans=0,
         cards=[dict(titulo="Beneficencia", datos=[("Idea", "Hacer el bien", True), ("Aquí", "Debía actuar", True), ("Faltó", "Sí", True)],
                     pie="Este caso."),
                dict(titulo="No maleficencia", datos=[("Idea", "No dañar", False), ("Ejemplo", "Evitar lo innecesario", False), ("Lema", "Primum non nocere", False)],
                     pie="Del médico."),
                dict(titulo="Autonomía", datos=[("Idea", "Decide el paciente", False), ("Requiere", "Información", False), ("Aquí", "No en juego", False)],
                     pie="Del paciente."),
                dict(titulo="Justicia", datos=[("Idea", "Equidad", False), ("Ámbito", "Recursos", False), ("Aquí", "No en juego", False)],
                     pie="Del sistema.")]),
  escala=dict(nombre="Categorías del monitoreo fetal (NICHD)", orden=True,
              que="Interpretación del trazado de la frecuencia cardiaca fetal.",
              grados=[("I", "Normal", ["FCF 110-160, variabilidad moderada", "Seguir"]), ("II", "Indeterminado", ["Vigilar y corregir causas"]),
                      ("III", "Anormal", ["Sin variabilidad con desaceleraciones o bradicardia", "Parto inmediato"])],
              caso=2, porque=[("Patrón de categoría III", True), ("LCF 109 y meconio espeso", True)],
              conducta="Reanimación intrauterina y cesárea urgente."))

# INF-061 · Contacto de TB menor de 5 años: terapia preventiva · ÁRBOL + PPD
S("arbol", "INF-061", "Niño de 3 años, contacto de su padre con TB pulmonar BK (+), con PPD de 8 mm: descartar TB activa e iniciar terapia preventiva",
  "Tuberculosis · contactos",
  ("Terapia preventiva en contactos", ["Los menores de 5 años contactos de TB pulmonar tienen alto riesgo de TB grave (miliar, meníngea).",
                                       "Tras descartar enfermedad activa, reciben terapia preventiva aunque el PPD sea negativo."]),
  ("Niño de 3 años", ["Padre con TB pulmonar BK (+) que inició tratamiento.", "PPD de 8 mm."]),
  ["Descartar TB activa: síntomas, examen y Rx de tórax.",
   "Esquemas: 3HP (isoniazida + rifapentina 12 semanas), 3HR, o isoniazida 6 meses.",
   "Controlar al niño cada mes; en contacto con TB resistente, esquema especial."],
  OMS + ", guías de TB, módulo 1: prevención (2024); " + MINSA + ", NTS de tuberculosis (2023).",
  op=("¿Conducta?", ["No: ya es positivo y retrasa", "El padre ya está en tratamiento", "No cambia la conducta en < 5 años", "Sí: tras descartar TB activa",
                     "No: no previene en el infectado"]),
  arbol=Q("Contacto menor de 5 años: ¿hay TB activa (síntomas o Rx anormal)?", [
      L("No (este caso)", "TERAPIA PREVENTIVA", ["3HP o 3HR", "o isoniazida 6 meses"], path=True),
      L("Sí", "Tratar TB activa", ["2HRZE + 4HR"])], path=True),
  escala=dict(nombre="Lectura del PPD (tuberculina)", orden=True,
              que="El corte depende del riesgo de la persona.",
              grados=[("≥ 5 mm", "Positivo en alto riesgo", ["Contactos, VIH, inmunosuprimidos", "Desnutridos"]),
                      ("≥ 10 mm", "Positivo en el resto", ["Población general"])],
              caso=0, porque=[("8 mm en un contacto: positivo", True), ("Aun negativo, en < 5 años se da terapia preventiva", True)],
              conducta="Rx de tórax y terapia preventiva."))

# GIN-118 · IECA en el embarazo: oligohidramnios · TARJETAS
S("tarjetas", "GIN-118", "Gestante hipertensa que siguió tomando enalapril y tiene oligohidramnios con feto sin malformaciones: efecto del IECA",
  "Fármacos en el embarazo · antihipertensivos",
  ("IECA y ARA II en el embarazo", ["En el 2.º y 3.er trimestre dañan el riñón fetal: oligohidramnios, falla renal, hipoplasia del cráneo y pulmón.",
                                    "Están contraindicados: cambiar a labetalol, nifedipino o metildopa."]),
  ("Primigesta de 31 semanas sin control", ["HTA crónica controlada con enalapril.", "Eco: oligohidramnios, feto sin malformaciones, peso normal."]),
  ["Suspender el enalapril y cambiar a labetalol o nifedipino.",
   "Vigilar el líquido amniótico y la función renal fetal (puede recuperarse).",
   "Ideal: cambiar el IECA antes de embarazarse o al confirmar el embarazo."],
  ACOG + ", hipertensión crónica en el embarazo (2019, act. 2022).",
  op=("¿Causa?", ["No: da hidrops y polihidramnios", "No: da polihidramnios", "No: da polihidramnios", "Sí: daña el riñón fetal",
                  "No: está controlada (120/80)"]),
  d=dict(rotulo="Líquido amniótico: ¿qué lo cambia?", ans=0,
         cards=[dict(titulo="IECA / ARA II", datos=[("Líquido", "Oligohidramnios", True), ("Por", "Riñón fetal", True), ("Trato", "Cambiar fármaco", True)],
                     pie="Este caso."),
                dict(titulo="Diabetes", datos=[("Líquido", "Polihidramnios", False), ("Por", "Poliuria fetal", False), ("Feto", "Macrosómico", False)],
                     pie="Más líquido."),
                dict(titulo="Isoinmunización", datos=[("Feto", "Anemia, hidrops", False), ("Líquido", "Polihidramnios", False), ("Prueba", "Coombs", False)],
                     pie="Rh."),
                dict(titulo="Corioangioma", datos=[("Qué", "Tumor placentario", False), ("Líquido", "Polihidramnios", False), ("Riesgo", "Hidrops", False)],
                     pie="Raro.")]))

# NEF-047 · Alcalosis metabólica por tiazidas · TARJETAS
S("tarjetas", "NEF-047", "Hipertensa con hidroclorotiazida y antiácidos, con K 2,8, Cl 88 y HCO₃ 32: alcalosis metabólica",
  "Trastornos ácido-base · alcalosis metabólica",
  ("Alcalosis metabólica", ["El bicarbonato sube: por pérdida de ácido o cloro (vómitos, diuréticos) o por álcali ingerido (antiácidos).",
                            "Las tiazidas hacen perder cloro y potasio, y la hipopotasemia mantiene la alcalosis."]),
  ("Mujer de 45 años", ["Hidroclorotiazida y antiácidos por su cuenta; mareos, debilidad, parestesias.",
                        "K 2,8, Cl 88, HCO₃ 32, Ca 10,2; creatinina normal."]),
  ["Compensación esperada: la pCO₂ sube unos 0,7 mmHg por cada mEq de HCO₃ (≈ 43 aquí).",
   "Cloro urinario < 20: responde a suero salino (vómitos); > 20: diuréticos activos o exceso de mineralocorticoides.",
   "Reponer potasio y cloro (KCl); suspender o ajustar la tiazida; cuidado con calcio y antiácidos (síndrome leche-álcali)."],
  HARRISON + "; " + KDIGO + ".",
  op=("¿Trastorno?", ["Sí: HCO₃ alto con hipopotasemia", "No: el HCO₃ está alto", "No: no hay hipoventilación primaria", "No: no hay hiperventilación",
                      "Faltan gases; nada sugiere lo respiratorio"]),
  d=dict(rotulo="Trastorno ácido-base primario", ans=0,
         cards=[dict(titulo="Alcalosis metabólica", datos=[("pH", "Alto", True), ("HCO₃", "Alto (32)", True), ("Causa", "Tiazida, antiácido", True)],
                     pie="Este caso."),
                dict(titulo="Acidosis metabólica", datos=[("pH", "Bajo", False), ("HCO₃", "Bajo", False), ("Causa", "Diarrea, cetoacidosis", False)],
                     pie="Anión gap."),
                dict(titulo="Acidosis respiratoria", datos=[("pH", "Bajo", False), ("pCO₂", "Alta", False), ("Causa", "Hipoventilación", False)],
                     pie="EPOC, opioides."),
                dict(titulo="Alcalosis respiratoria", datos=[("pH", "Alto", False), ("pCO₂", "Baja", False), ("Causa", "Hiperventilación", False)],
                     pie="Ansiedad, altura.")]))

# REU-036 · Dermatitis del pañal candidiásica · TARJETAS + imagen
S("tarjetas", "REU-036", "Lactante con placa roja brillante y bien delimitada en la zona del pañal que toma los pliegues: dermatitis del pañal por Candida, antifúngico tópico",
  "Dermatología pediátrica · dermatitis del pañal",
  ("Dermatitis del pañal por Candida", ["La humedad del pañal permite que Candida invada la piel irritada.",
                                        "Rojo intenso y brillante que SÍ toma los pliegues, con lesiones satélite; dura más de 3 días."]),
  ("Lactante de 9 meses", ["Lesión en la zona del pañal de 2 semanas.", "Placa roja brillante, bien delimitada, en pliegues inguinales y región perianal."]),
  ["Antifúngico tópico (econazol, clotrimazol, nistatina o miconazol) 2 veces al día por 1-2 semanas.",
   "Cambios frecuentes de pañal, secar bien y pasta de óxido de zinc encima del antifúngico.",
   "Evitar corticoides potentes en la zona del pañal (atrofia, absorción)."],
  "AAD, dermatitis del pañal (2023); " + NELSON + ".",
  op=("¿Tratamiento?", ["Sí: trata la Candida", "Protege, pero no trata el hongo", "Para impétigo (bacteria)", "Solo protege", "No: atrofia y absorción"]),
  d=dict(rotulo="Dermatitis del pañal: ¿cuál?", ans=0,
         cards=[dict(titulo="Candidiásica", datos=[("Pliegues", "Afectados", True), ("Borde", "Satélites", True), ("Trato", "Antifúngico", True)],
                     pie="Este caso."),
                dict(titulo="Irritativa", datos=[("Pliegues", "Respetados", False), ("Zona", "Contacto con el pañal", False), ("Trato", "Óxido de zinc", False)],
                     pie="La más común."),
                dict(titulo="Impétigo", datos=[("Lesión", "Ampollas, costras", False), ("Germen", "S. aureus", False), ("Trato", "Mupirocina", False)],
                     pie="Bacteriana."),
                dict(titulo="Seborreica", datos=[("Color", "Rosado, escama grasa", False), ("Otras zonas", "Cuero cabelludo", False), ("Edad", "< 3 meses", False)],
                     pie="Inflamatoria.")]),
  banda=B("Así se ve la candidiasis del pañal", P("panal_candida.jpg", 200, 304, [
            ("flecha", 0.70, 0.45, 0.45, 0.95, "placa roja con satélites")],
          credito="Siegfried y Hebert" + CC + "CC BY 4.0"),
          [("Roja brillante", "Bien delimitada."),
           ("Toma los pliegues", "La irritativa los respeta."),
           ("Satélites", "Pápulas y pústulas fuera del borde."),
           ("Más de 3 días", "Una dermatitis del pañal que no mejora: pensar en Candida.")],
          pie="Piel de otro lactante.", ans=1))

# CIR-063 · Colecistitis enfisematosa: colecistectomía de emergencia · ÁRBOL + Tokio
S("arbol", "CIR-063", "Colecistitis aguda con Murphy (++) y aire en la pared de la vesícula en la TC: colecistitis enfisematosa, colecistectomía de emergencia",
  "Vesícula biliar · colecistitis complicada",
  ("Colecistitis enfisematosa", ["Infección por gérmenes productores de gas (Clostridium, E. coli) con isquemia de la pared.",
                                 "Alto riesgo de gangrena y perforación: cirugía urgente."]),
  ("Varón de 25 años", ["Dolor cólico epigástrico tras comida grasa, irradiado a HCD y región lumbar; vómitos y fiebre.",
                        "Murphy (++); TC: inflamación pericolecística y aire en la pared vesicular."]),
  ["Antibiótico EV que cubra anaerobios (piperacilina-tazobactam).",
   "Colecistectomía de emergencia (laparoscópica si es posible).",
   "Si el paciente no tolera la cirugía: colecistostomía percutánea como puente."],
  "Guías de Tokio (TG18); WSES, colecistitis aguda (2020).",
  op=("¿Manejo?", ["Puente si no tolera la cirugía", "Insuficiente: hay gas en la pared", "No: riesgo de perforación", "Sí: forma complicada",
                   "No: no hay coledocolitiasis"],
      {4: "CPRE"}),
  arbol=Q("Colecistitis aguda: ¿hay gas, gangrena, perforación o absceso?", [
      L("Sí: gas en la pared (este caso)", "COLECISTECTOMÍA DE EMERGENCIA", ["Antibiótico EV", "Laparoscópica"], path=True),
      L("No: no complicada", "Colecistectomía temprana", ["En < 72 h"])], path=True),
  escala=dict(nombre="Gravedad de la colecistitis (Tokio 2018)", orden=True,
              que="Guía el momento y el tipo de tratamiento.",
              grados=[("Grado I", "Leve", ["Sin criterios de II o III"]),
                      ("Grado II", "Moderada", ["Leucocitos > 18 000, masa", "> 72 h, o inflamación local marcada (gangrenosa, enfisematosa)"]),
                      ("Grado III", "Grave", ["Falla de órganos"])],
              caso=1, porque=[("Colecistitis enfisematosa: inflamación local marcada", True), ("Sin falla de órganos descrita", True)],
              conducta="Antibiótico y colecistectomía urgente."))

# OFT-029 · Hipema traumático · TARJETAS + grados + imagen
S("tarjetas", "OFT-029", "Golpe en el ojo con dolor, fotofobia, visión borrosa y sangre con nivel en la cámara anterior: hipema",
  "Trauma ocular cerrado",
  ("Hipema", ["Sangre en la cámara anterior (entre la córnea y el iris) por rotura de vasos del iris o cuerpo ciliar.",
              "La sangre se deposita abajo y forma un nivel; puede subir la presión ocular."]),
  ("Varón de 18 años", ["Golpe en el ojo jugando fútbol hace 4 horas.", "Dolor, fotofobia, visión borrosa; sangre con nivel."]),
  ["Reposo con cabecera elevada 30-45°, escudo ocular, ciclopléjico y corticoide tópico.",
   "Evitar aspirina y AINE; medir la presión ocular cada día (resangrado a los 2-5 días).",
   "Descartar rotura del globo; prueba de drepanocitosis en riesgo."],
  "AAO, hipema traumático (2023).",
  op=("¿Diagnóstico?", ["No: secreción, sin trauma", "Sí: sangre con nivel", "Hay que descartarla; aquí no se describe", "No: no da sangre en cámara",
                        "No: no da sangre en cámara anterior"]),
  d=dict(rotulo="Golpe en el ojo: ¿qué lesión?", ans=0,
         cards=[dict(titulo="Hipema", datos=[("Dónde", "Cámara anterior", True), ("Ver", "Nivel de sangre", True), ("Riesgo", "Presión alta", True)],
                     pie="Este caso."),
                dict(titulo="Globo abierto", datos=[("Ver", "Pupila en gota", False), ("Seidel", "Positivo", False), ("Trato", "Cirugía", False)],
                     pie="Emergencia."),
                dict(titulo="Abrasión corneal", datos=[("Síntoma", "Cuerpo extraño", False), ("Prueba", "Fluoresceína", False), ("Visión", "Casi normal", False)],
                     pie="Superficial."),
                dict(titulo="Desprendimiento de retina", datos=[("Síntoma", "Moscas, cortina", False), ("Cámara", "Limpia", False), ("Trato", "Cirugía", False)],
                     pie="Fondo de ojo.")]),
  escala=dict(nombre="Grados del hipema", orden=True,
              que="Por cuánto ocupa la sangre la cámara anterior.",
              grados=[("Microhipema", "Sin nivel", ["Glóbulos rojos flotando"]), ("Grado I", "< 1/3", ["Nivel bajo"]),
                      ("Grado II", "1/3 a 1/2", ["Nivel medio"]), ("Grado III", "> 1/2", ["Casi lleno"]), ("Grado IV", "Total", ["«Bola ocho»"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Hay nivel de sangre", True), ("Falta medir cuánto ocupa", True)],
              conducta="Reposo, escudo y control de la presión ocular."),
  banda=B("Así se ve el hipema", P("hipema.jpg", 330, 254, [
            ("flecha", 0.62, 0.68, 0.40, 0.92, "sangre en la mitad inferior")],
          credito="Rakesh Ahuja" + CC + "CC BY-SA 2.5"),
          [("Sangre abajo", "Se deposita por gravedad."),
           ("Nivel horizontal", "Línea entre la sangre y el humor acuoso."),
           ("Mitad de la cámara", "En esta foto: grado II."),
           ("Cabecera elevada", "Para que la sangre baje y se reabsorba.")],
          pie="Ojo de otro paciente.", ans=1))

# CIR-064 · Gran quemado: sábana limpia y seca · ÁRBOL + regla de los 9 + dibujo propio
S("arbol", "CIR-064", "Quemadura de 2.º grado por agua hirviendo en ambos brazos y el tronco (más del 50 %): la medida inmediata es cubrirlo con una sábana limpia y seca",
  "Quemaduras · atención inicial",
  ("Atención inicial del gran quemado", ["Detener la quemadura, cubrir y evitar la hipotermia: la piel quemada pierde calor y agua.",
                                         "Luego ABCDE, dos vías, líquidos por superficie quemada y analgesia EV."]),
  ("Varón de 30 años", ["Quemadura con agua hirviendo hace 2 horas.", "2.º grado en ambos brazos (cara anterior y posterior) y en el tronco (adelante y atrás)."]),
  ["Ringer lactato: 2 mL × kg × % quemado en 24 h (ATLS), la mitad en las primeras 8 h; meta de diuresis 0,5 mL/kg/h.",
   "Analgesia con opioide EV (no IM); toxoide tetánico.",
   "Más del 20 % de superficie de 2.º grado: unidad de quemados."],
  ATLS + "; ABA, atención inicial del quemado (2023).",
  op=("¿Medida inmediata?", ["No: la vía IM no se absorbe bien", "Sí: protege y evita la hipotermia", "No: pierde calor", "No en grandes superficies: hipotermia",
                             "No: daña el tejido y enfría"]),
  arbol=Q("Quemadura extensa: ¿primera medida tras detener la quemadura?", [
      L("Cubrir (este caso)", "SÁBANA LIMPIA Y SECA", ["Evitar hipotermia", "Luego ABCDE y líquidos"], path=True),
      L("Quemadura pequeña", "Agua a temperatura ambiente", ["20 minutos"])], path=True),
  escala=dict(nombre="Regla de los 9 (Wallace)", modo="puntaje",
              que="Porcentaje de superficie corporal quemada en el adulto (solo 2.º y 3.er grado).",
              items=[("MSD", "Brazo derecho (ant. + post.)", "Quemado", 9), ("MSI", "Brazo izquierdo (ant. + post.)", "Quemado", 9),
                     ("TA", "Tronco anterior", "Quemado", 18), ("TP", "Tronco posterior", "Quemado", 18)],
              total_txt="Total: 54 % de superficie", total_nota="2.º grado",
              rangos=[("< 10 %", "Menor", "Ambulatorio"), ("10-20 %", "Moderada", "Hospital"), ("> 20 %", "Grave", "Líquidos EV y unidad de quemados")],
              caso_rango=2, porque=[("Brazos 9 + 9 y tronco 18 + 18", True)],
              conducta="Sábana seca, Ringer lactato y unidad de quemados."),
  banda=B("Regla de los 9 en este caso", P("dib_regla9.jpg", 380, 268, [], credito=PROPIO, fondo="#ffffff"),
          [("Cabeza 9 %", "4,5 adelante y 4,5 atrás."),
           ("Cada brazo 9 %", "Ambas caras."),
           ("Tronco 36 %", "18 adelante y 18 atrás."),
           ("Cada pierna 18 %", "Periné 1 %.")],
          pie="Esquema.", ans=2))

# GIN-119 · Ganancia de peso gestacional en sobrepeso · ÁRBOL + IOM
S("arbol", "GIN-119", "Gestante con sobrepeso (IMC 25-29,9) y embarazo único: ganancia de peso recomendada de 7 a 11,5 kg",
  "Nutrición en el embarazo",
  ("Ganancia de peso en el embarazo", ["Depende del IMC antes del embarazo: cuanto más alto, menos debe subir.",
                                       "Subir de más aumenta diabetes gestacional, preeclampsia, macrosomía y cesárea."]),
  ("Pregunta de concepto", ["Gestación única.", "Mujer con sobrepeso (IMC 26-29)."]),
  ["Controlar el peso en cada consulta y graficarlo.",
   "Actividad física moderada 150 min/semana si no hay contraindicación.",
   "Dieta saludable; el embarazo no es «comer por dos»."],
  "IOM/NAM (2009, vigente); " + ACOG + " (2020); " + MINSA + ".",
  op=("¿Ganancia?", ["Sí: sobrepeso", "Cerca del rango normal (11,5-16)", "Es para bajo peso", "Es para obesidad", "Excesivo"]),
  arbol=Q("Gestación única: ¿IMC previo entre 25 y 29,9?", [
      L("Sí: sobrepeso (este caso)", "SUBIR 7 A 11,5 KG", ["≈ 0,3 kg/semana en 2.º-3.er trimestre"], path=True),
      L("IMC ≥ 30", "Subir 5 a 9 kg", ["Obesidad"])], path=True),
  escala=dict(nombre="Ganancia de peso recomendada (IOM 2009)", orden=True,
              que="Según el IMC antes del embarazo (gestación única).",
              grados=[("Bajo peso", "IMC < 18,5", ["12,5 a 18 kg"]), ("Normal", "18,5-24,9", ["11,5 a 16 kg"]),
                      ("Sobrepeso", "25-29,9", ["7 a 11,5 kg"]), ("Obesidad", "≥ 30", ["5 a 9 kg"])],
              caso=2, porque=[("IMC 26-29: sobrepeso", True)],
              conducta="Meta de 7 a 11,5 kg."))

# CB-042 · Pelagra: déficit de niacina · TARJETAS + 4 D + imagen
S("tarjetas", "CB-042", "Alcohólico gastrectomizado con dermatitis en zonas expuestas al sol (collar de Casal), diarrea y pérdida de memoria: pelagra por déficit de niacina",
  "Nutrición · vitaminas del complejo B",
  ("Pelagra", ["Falta de niacina (vitamina B3) o de su precursor triptófano: alcoholismo, malabsorción, isoniazida, carcinoide.",
               "Las 4 D: dermatitis, diarrea, demencia y, sin tratamiento, defunción (death)."]),
  ("Varón de 50 años", ["Gastrectomizado y alcohólico; 2 meses de olvidos, lesiones de piel y diarrea.",
                        "Placas rojo-pardas con escamas en dorso de manos, antebrazos y escote (collar de Casal); glositis; ataxia."]),
  ["Nicotinamida 100 mg cada 6-8 h hasta mejorar; dieta y otras vitaminas B (suele haber déficit de tiamina).",
   "Fotoprotección: la dermatitis aparece en zonas expuestas al sol.",
   "Responde en días; la demencia avanzada puede no revertir."],
  HARRISON + "; " + OMS + ", pelagra.",
  op=("¿Micronutriente?", ["Sí: las 4 D", "No: escorbuto, encías", "No: miocardiopatía", "No: lesiones periorificiales", "No: Wernicke, sin dermatitis"]),
  d=dict(rotulo="Déficit de micronutrientes", ans=0,
         cards=[dict(titulo="Niacina (B3)", datos=[("Piel", "Fotoexpuesta", True), ("Intestino", "Diarrea", True), ("Mente", "Demencia", True)],
                     pie="Este caso."),
                dict(titulo="Tiamina (B1)", datos=[("Cerebro", "Wernicke", False), ("Corazón", "Beriberi húmedo", False), ("Nervio", "Neuropatía", False)],
                     pie="Alcohol."),
                dict(titulo="Vitamina C", datos=[("Encías", "Sangran", False), ("Piel", "Petequias perifoliculares", False), ("Herida", "No cicatriza", False)],
                     pie="Escorbuto."),
                dict(titulo="Zinc", datos=[("Piel", "Periorificial", False), ("Pelo", "Alopecia", False), ("Otro", "Diarrea", False)],
                     pie="Acrodermatitis.")]),
  triada=TR([("Dermatitis", "Zonas expuestas, collar de Casal", True), ("Diarrea", "Sí", True), ("Demencia", "Pérdida de memoria", True),
             ("Defunción", "Si no se trata", None)],
            [("Las 4 D de la pelagra", 0, 3)],
            "El collar de Casal en el escote es el signo clásico."),
  banda=B("Así se ve la pelagra", P("pelagra.jpg", 360, 165, [
            ("flecha", 0.40, 0.45, 0.50, 0.92, "dermatitis en el dorso de las manos")],
          credito="J. W. Babcock" + CC + "dominio público"),
          [("Zonas expuestas", "Manos, antebrazos, cuello."),
           ("Rojo-pardo con escamas", "Bordes bien marcados."),
           ("Collar de Casal", "Banda en el escote."),
           ("Respeta lo cubierto", "Por eso es fotosensible.")],
          pie="Foto histórica de otro paciente (manos).", ans=0))

# NEF-048 · Obstrucción de la sonda vesical: cambiarla · ÁRBOL + potasio
S("arbol", "NEF-048", "Parapléjico monorreno con sonda vesical permanente, anuria, hidronefrosis, creatinina 3 y K 5,8: sonda obstruida, cambiar el catéter vesical",
  "Uropatía obstructiva · sonda vesical",
  ("Anuria en un portador de sonda", ["Lo primero es pensar en la sonda tapada (moco, cálculos, incrustaciones).",
                                      "Si el riñón es único, cualquier obstrucción da anuria y falla renal."]),
  ("Varón de 58 años, parapléjico y monorreno", ["Usa sonda vesical; acude por anuria.", "Creatinina 3, K 5,8; eco: hidronefrosis."]),
  ["Cambiar la sonda (o lavarla) y ver si sale orina: resuelve la causa más simple primero.",
   "Si no drena: eco de vejiga y uréter; nefrostomía si la obstrucción es alta.",
   "Vigilar la poliuria posobstructiva y el potasio; ECG."],
  "EAU, neuro-urología y sondaje (2024); " + KDIGO + ".",
  op=("¿Conducta?", ["No: no hay cálculo demostrado", "Sí: la sonda tapada es lo primero", "Después, si no drena", "Si la obstrucción es alta y la sonda no resuelve",
                     "No: se corrige al drenar"]),
  arbol=Q("Portador de sonda con anuria e hidronefrosis: ¿la sonda drena?", [
      L("No: obstruida (este caso)", "CAMBIAR LA SONDA", ["Ver si sale orina", "Vigilar K y poliuria"], path=True),
      L("Sí, y sigue la hidronefrosis", "Obstrucción alta", ["Nefrostomía percutánea"])], path=True),
  escala=HIPERK(0, [("K⁺ 5,8 mEq/L", True), ("Falta el ECG", True)],
                "Drenar, ECG y repetir el potasio."))

# GIN-120 · Retinoides contraindicados en el embarazo · TARJETAS
S("tarjetas", "GIN-120", "Gestante de 6 semanas con acné a quien quieren dar retinoides: están contraindicados durante todo el embarazo",
  "Fármacos en el embarazo · teratógenos",
  ("Retinoides y embarazo", ["La isotretinoína es muy teratógena: malformaciones del sistema nervioso, cara, oído y corazón.",
                             "Los retinoides tópicos tampoco se recomiendan en el embarazo."]),
  ("Primigesta de 6 semanas", ["Asintomática; tiene acné.", "El dermatólogo quiere iniciar retinoides."]),
  ["Alternativas en el embarazo: peróxido de benzoilo, ácido azelaico, eritromicina o clindamicina tópica.",
   "Mujeres que toman isotretinoína: dos métodos anticonceptivos 1 mes antes, durante y 1 mes después.",
   "Tetraciclinas también contraindicadas (dientes y huesos)."],
  "AAD, acné (2024); " + ACOG + ".",
  op=("¿Recomendación?", ["Sí: teratógeno", "No: ninguna dosis es segura", "No: es teratógeno", "No: la organogénesis sigue", "No: también hay daño fetal"]),
  d=dict(rotulo="Tratamiento del acné en una gestante", ans=0,
         cards=[dict(titulo="Retinoides", datos=[("Embarazo", "Contraindicado", True), ("Riesgo", "Malformaciones", True), ("Ejemplo", "Isotretinoína", True)],
                     pie="Este caso."),
                dict(titulo="Tetraciclinas", datos=[("Embarazo", "Contraindicadas", False), ("Riesgo", "Dientes, hueso", False), ("Ejemplo", "Doxiciclina", False)],
                     pie="Evitar."),
                dict(titulo="Peróxido de benzoilo", datos=[("Embarazo", "Seguro", False), ("Uso", "Tópico", False), ("Efecto", "Antibacteriano", False)],
                     pie="Elegir."),
                dict(titulo="Ácido azelaico", datos=[("Embarazo", "Seguro", False), ("Uso", "Tópico", False), ("Sirve", "Comedones", False)],
                     pie="Elegir.")]))

# END-033 · Diabetes insípida · ÁRBOL + tipos
S("arbol", "END-033", "Joven con poliuria, polidipsia y cefalea: la diabetes insípida se reconoce por poliuria con orina diluida (densidad baja) y sodio alto",
  "Hipófisis · diabetes insípida",
  ("Diabetes insípida (deficiencia o resistencia a la vasopresina)", ["Falta ADH (central) o el riñón no responde (nefrogénica): se pierde agua libre.",
                                                                      "Mucha orina diluida (densidad < 1005, osmolaridad < 300) y tendencia a sodio alto."]),
  ("Varón de 20 años", ["6 meses de poliuria y polidipsia.", "Cefalea global (pensar en lesión hipotálamo-hipofisaria)."]),
  ["Prueba de restricción de agua: la orina no se concentra.",
   "Desmopresina: si la orina se concentra, es central; si no, nefrogénica (litio, hipercalcemia).",
   "Central con cefalea: RM de hipófisis; tratar con desmopresina."],
  "Endocrine Society; consenso de cambio de nombre (2022); " + HARRISON + ".",
  op=("¿Hallazgos?", ["No: densidad alta no es DI", "Sí: orina diluida + sodio alto", "No: es otro cuadro (SIADH)", "No: densidad alta",
                      "Es polidipsia primaria"]),
  arbol=Q("Poliuria: ¿orina diluida con sodio alto?", [
      L("Sí (este caso)", "DIABETES INSÍPIDA", ["Restricción de agua", "Desmopresina"], path=True),
      L("Orina diluida con sodio bajo", "Polidipsia primaria", ["Toma mucha agua"])], path=True),
  escala=dict(nombre="Tipos de poliuria hipotónica", orden=False,
              que="Se separan con la restricción de agua y la desmopresina.",
              grados=[("Central", "Falta ADH", ["Desmopresina concentra la orina", "Tumores, trauma, cirugía"]),
                      ("Nefrogénica", "Riñón no responde", ["Desmopresina no sirve", "Litio, calcio alto"]),
                      ("Polidipsia primaria", "Bebe de más", ["Sodio bajo-normal"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Cefalea: sospecha de causa central", True), ("Falta la prueba con desmopresina", True)],
              conducta="Restricción de agua, desmopresina y RM."))

# INF-062 · Neumonía por Pneumocystis: cotrimoxazol · ÁRBOL + Rx real
S("arbol", "INF-062", "Paciente con VIH y neumonía por Pneumocystis jirovecii: el tratamiento de elección es cotrimoxazol",
  "VIH · infecciones oportunistas",
  ("Neumonía por Pneumocystis (PCP)", ["Hongo que causa neumonía con CD4 < 200: disnea progresiva, tos seca, fiebre y desaturación al esfuerzo.",
                                       "Rx con infiltrado intersticial bilateral en vidrio esmerilado; LDH alta."]),
  ("Varón de 35 años con VIH", ["Diagnóstico de neumonía por Pneumocystis jirovecii.", "¿Tratamiento inicial?"]),
  ["Cotrimoxazol (TMP 15-20 mg/kg/día) por 21 días, EV si es grave.",
   "Prednisona si PaO₂ < 70 mmHg o gradiente A-a ≥ 35 (en las primeras 72 h).",
   "Iniciar TAR en las primeras 2 semanas; profilaxis con cotrimoxazol después."],
  "NIH/CDC/IDSA, infecciones oportunistas en VIH (act. 2025).",
  op=("¿Tratamiento?", ["No cubre Pneumocystis", "No cubre Pneumocystis", "No: anaerobios y protozoos", "Sí: de elección", "No: Pneumocystis no responde a azoles"]),
  arbol=Q("Neumonía por Pneumocystis: ¿PaO₂ < 70 o gradiente A-a ≥ 35?", [
      L("Tratar a todos (este caso)", "COTRIMOXAZOL 21 DÍAS", ["TMP 15-20 mg/kg/día"], path=True),
      L("Sí, hipoxemia", "Agregar prednisona", ["Iniciar en 72 h"])], path=True),
  banda=B("Rx de la neumonía por Pneumocystis", P("pcp_rx.jpg", 300, 281, [
            ("flechas", [(0.27, 0.60), (0.75, 0.60)], 0.50, 0.94, "vidrio esmerilado en ambos pulmones")],
          credito="C. M. Allen et al." + CC + "CC BY 4.0"),
          [("Velo bilateral", "Vidrio esmerilado alrededor de los hilios."),
           ("Puede ser normal", "Al inicio; la TC lo muestra mejor."),
           ("Neumotórax", "Complicación típica."),
           ("CD4 < 200", "Cuando aparece.")],
          pie="Rx de otro paciente.", ans=0))

# GIN-121 · Embarazo ectópico roto · ÁRBOL + manejo + imagen
S("arbol", "GIN-121", "Mujer con 6 semanas de amenorrea, síncope, hipotensión, taquicardia y culdocentesis positiva: embarazo ectópico roto",
  "Hemorragias de la primera mitad · embarazo ectópico",
  ("Embarazo ectópico roto", ["El embarazo crece fuera del útero (casi siempre en la trompa) y la rompe: sangra hacia el abdomen.",
                              "Amenorrea + dolor + choque; la culdocentesis con sangre que no coagula indica hemoperitoneo."]),
  ("Mujer de 24 años", ["Se desmayó hace 15 minutos; FUR hace 6 semanas.", "PA 80/50, FC 110, abdomen doloroso; culdocentesis (+)."]),
  ["Reanimación (dos vías, sangre) y laparotomía o laparoscopía urgente: salpingectomía.",
   "Hoy la ecografía FAST o transvaginal reemplaza a la culdocentesis.",
   "Estable y sin rotura: metotrexato o cirugía según la β-hCG y el tamaño."],
  ACOG + ", embarazo tubario (2018, act. 2023); NICE NG126 (2023).",
  op=("¿Diagnóstico?", ["No: sangrado vaginal, sin hemoperitoneo", "No: sangrado vaginal, cuello abierto", "Sí: amenorrea + choque + hemoperitoneo",
                        "Raro con choque; β-hCG negativa", "No: sin choque ni amenorrea"]),
  arbol=Q("Mujer en edad fértil con amenorrea, dolor y choque: ¿hemoperitoneo?", [
      L("Sí (este caso)", "ECTÓPICO ROTO: CIRUGÍA", ["Reanimar", "Salpingectomía"], path=True),
      L("Estable, sin rotura", "Metotrexato o laparoscopía", ["Según β-hCG y tamaño"])], path=True),
  escala=dict(nombre="Manejo del embarazo ectópico", orden=True,
              que="Según estabilidad, rotura y β-hCG.",
              grados=[("Expectante", "β-hCG baja y bajando", ["Sin síntomas"]), ("Metotrexato", "Estable, sin rotura", ["β-hCG < 5000", "Masa < 3,5 cm"]),
                      ("Cirugía", "Rotura o inestable", ["Salpingectomía urgente"])],
              caso=2, porque=[("PA 80/50, FC 110, síncope", True), ("Culdocentesis positiva: hemoperitoneo", True)],
              conducta="Reanimar y operar de urgencia."),
  banda=B("El ectópico visto por laparoscopía", P("ectopico_tubario.jpg", 330, 245, [
            ("flecha", 0.53, 0.30, 0.22, 0.12, "trompa dilatada\npor el embarazo"),
            ("flecha", 0.60, 0.64, 0.84, 0.88, "fimbrias")],
          credito="Hic et nunc" + CC + "CC BY-SA 3.0"),
          [("Trompa dilatada", "El embarazo crece en la ampolla."),
           ("Se rompe", "Hacia las 6-8 semanas."),
           ("Hemoperitoneo", "Sangre libre: choque."),
           ("Salpingectomía", "Se retira la trompa afectada.")],
          pie="Laparoscopía de otra paciente.", ans=2))

# SP-086 · Autoexamen de mama: prevención secundaria · FASES
S("fases", "SP-086", "El autoexamen de mama busca detectar temprano una lesión: es prevención secundaria",
  "Salud pública · niveles de prevención",
  ("Prevención secundaria", ["Detectar la enfermedad en etapa temprana, cuando aún no da síntomas o son mínimos.",
                             "Tamizajes: mamografía, PAP, prueba de VPH, sangre oculta en heces."]),
  ("Pregunta de concepto", ["Autoexamen de mama.", "¿Qué tipo de prevención?"]),
  ["El autoexamen solo no reduce la mortalidad; se promueve conocer las mamas y consultar ante cambios.",
   "Examen clínico de mamas y mamografía cada 2 años desde los 40-50 años (según la guía).",
   "Primaria: evitar el cáncer (actividad física, lactancia, no alcohol)."],
  OMS + "; USPSTF, cáncer de mama (2024); " + MINSA + ".",
  op=("¿Tipo de prevención?", ["Sí: detección temprana", "No: evitar el exceso de intervenciones", "No: rehabilitar", "No: evitar que aparezca",
                               "No: parte de la primaria"]),
  d=dict(rotulo="Niveles de prevención (Leavell y Clark)", ans=1,
         fases=[("Antes de enfermar", "Sano", "PRIMARIA", ["Hábitos, vacunas"]),
                ("Enfermo sin síntomas", "Detección", "SECUNDARIA", ["Autoexamen, mamografía", "Este caso"]),
                ("Enfermedad avanzada", "Secuelas", "TERCIARIA", ["Rehabilitar"]),
                ("En todo momento", "Exceso", "CUATERNARIA", ["Evitar daño médico"])]))

# CB-043 · Lesión del nervio femoral · TARJETAS
S("tarjetas", "CB-043", "Hipoestesia en la cara anterior del muslo y medial de la pierna tras una cirugía renal retroperitoneal: lesión del nervio femoral",
  "Anatomía · plexo lumbar",
  ("Nervio femoral (L2-L4)", ["Pasa junto al psoas en el retroperitoneo y sale por debajo del ligamento inguinal.",
                              "Sensibilidad: cara anterior del muslo y, por el safeno, cara medial de la pierna; motor: cuádriceps (extiende la rodilla), reflejo rotuliano."]),
  ("Varón de 63 años", ["Pielolitotomía en un riñón derecho ptósico.", "Hipoestesia en la cara anterior del muslo y medial de la pierna derecha."]),
  ["Causas de lesión: separadores en cirugía pélvica o retroperitoneal, hematoma del psoas, posición de litotomía.",
   "Buscar debilidad para extender la rodilla y reflejo rotuliano disminuido.",
   "Suele recuperarse si fue por compresión; fisioterapia."],
  "Moore, Anatomía con orientación clínica (9.ª ed.).",
  op=("¿Nervio?", ["No: cara posterior y pie", "Sí: muslo anterior + safeno", "No: planta del pie", "No: borde lateral del pie", "No: cara medial del muslo"]),
  d=dict(rotulo="¿Qué nervio da la sensibilidad?", ans=0,
         cards=[dict(titulo="Femoral", datos=[("Piel", "Muslo anterior", True), ("Rama", "Safeno: pierna medial", True), ("Músculo", "Cuádriceps", True)],
                     pie="Este caso."),
                dict(titulo="Obturador", datos=[("Piel", "Muslo medial", False), ("Músculo", "Aductores", False), ("Lesión", "Cirugía pélvica", False)],
                     pie="Aducción."),
                dict(titulo="Ciático", datos=[("Piel", "Pierna y pie", False), ("Músculo", "Isquiotibiales", False), ("Lesión", "Inyección glútea", False)],
                     pie="El más grande."),
                dict(titulo="Sural", datos=[("Piel", "Borde lateral del pie", False), ("Tipo", "Solo sensitivo", False), ("Uso", "Biopsia de nervio", False)],
                     pie="Sensitivo.")]))

# END-034 · Insuficiencia suprarrenal por ketoconazol · ÁRBOL + primaria/secundaria
S("arbol", "END-034", "Paciente con ketoconazol prolongado, debilidad, vómitos, hipotensión ortostática, hiperpigmentación, hiponatremia, hipoglucemia y cortisol que no sube con ACTH: cortisol bajo",
  "Suprarrenal · insuficiencia suprarrenal",
  ("Insuficiencia suprarrenal por ketoconazol", ["El ketoconazol bloquea enzimas que fabrican cortisol en la suprarrenal.",
                                                 "Falta cortisol: la ACTH sube (hiperpigmentación), hay hipotensión, hiponatremia e hipoglucemia."]),
  ("Mujer de 45 años", ["6 meses con ketoconazol; debilidad, dolor abdominal, náuseas y vómitos.",
                        "Hipotensión ortostática, adelgazada, piel y mucosas pigmentadas; Na 130, glucosa 65; el cortisol no sube con ACTH."]),
  ["Hidrocortisona 100 mg EV y suero salino si hay crisis; luego hidrocortisona oral.",
   "Suspender o cambiar el ketoconazol (por otro azol).",
   "Educación: duplicar la dosis en enfermedad y llevar identificación."],
  "Endocrine Society, insuficiencia suprarrenal primaria (2016, act. 2024).",
  op=("¿Hormona baja?", ["Sí: el ketoconazol la bloquea", "Puede bajar, pero K normal: no es lo principal", "No: está alta o normal",
                         "No: está alta (hiperpigmentación)", "No relacionada"]),
  arbol=Q("Sospecha de insuficiencia suprarrenal: ¿el cortisol sube con ACTH?", [
      L("No (este caso)", "CORTISOL BAJO", ["Hidrocortisona", "Suspender ketoconazol"], path=True),
      L("Sí", "Suprarrenal normal", ["Buscar otra causa"])], path=True),
  escala=dict(nombre="Insuficiencia suprarrenal: primaria o secundaria", orden=False,
              que="Se distingue por la ACTH y sus consecuencias.",
              grados=[("Primaria", "Falla la suprarrenal", ["ACTH alta: hiperpigmentación", "Puede haber K alto"]),
                      ("Secundaria", "Falla la hipófisis", ["ACTH baja: sin pigmento", "K normal"])],
              caso=0, porque=[("Hiperpigmentación: ACTH alta", True), ("El fármaco actúa en la suprarrenal", True)],
              conducta="Hidrocortisona y cambiar el antifúngico."),
  triada=TR([("Hiperpigmentación", "Piel y mucosas", True), ("Hipotensión ortostática", "Sí", True), ("Hiponatremia", "Na 130", True),
             ("Hipoglucemia", "65 mg/dL", True), ("Hiperpotasemia", "K 4,5 (normal)", False)],
            [("Insuficiencia suprarrenal", 0, 4)],
            "El potasio normal sugiere que la aldosterona aún funciona."))

# CAR-048 · Choque cardiogénico: precarga alta · MATRIZ de Forrester
S("matriz", "CAR-048", "Infarto con hipotensión, piel fría, llenado lento, crepitantes e ingurgitación yugular: choque cardiogénico con precarga alta (frío y húmedo)",
  "Síndrome coronario agudo · choque cardiogénico",
  ("Choque cardiogénico", ["El corazón infartado no bombea: baja el gasto (frío) y la sangre se acumula detrás (húmedo).",
                           "Precarga alta: yugulares ingurgitadas y crepitantes (presión de enclavamiento > 18)."]),
  ("Varón de 50 años, diabético", ["30 min de dolor retroesternal opresivo; CK-MB y troponina altas.",
                                   "PA 80/50, FC 60, SatO₂ 90 %; piel fría, llenado > 5 s; crepitantes e ingurgitación yugular."]),
  ["Reperfusión urgente (angioplastia primaria) es lo que más baja la mortalidad.",
   "Noradrenalina para la PA y dobutamina para el gasto; diurético con cuidado si hay congestión.",
   "Considerar soporte mecánico en centro especializado."],
  ESC + ", síndromes coronarios agudos (2023); AHA/ACC (2025).",
  op=("¿Precarga?", ["No: hay congestión", "Sí: yugulares y crepitantes", "No: congestión, no depleción", "No: sería frío y seco",
                     "No: la poscarga sube (vasoconstricción)"]),
  d=dict(rotulo="Perfil hemodinámico de Forrester", eje_x="Perfusión", eje_y="Congestión",
         cols=["Caliente (perfunde)", "Fría (hipoperfusión)"], rows=["Seco", "Húmedo (congestión)"], caso=(1, 1),
         cells=[[("I: caliente y seco", ["Normal", "Vigilar"]), ("III: frío y seco", ["Hipovolemia", "Volumen"])],
                [("II: caliente y húmedo", ["Congestión", "Diuréticos"]), ("IV: FRÍO Y HÚMEDO", ["Choque cardiogénico", "Precarga alta"])]]))

# SP-087 · Violencia contra la adulta mayor: denunciar · ÁRBOL
S("arbol", "SP-087", "Adulta mayor agredida física y amenazada de muerte por su hijo: la conducta urgente es denunciar a las autoridades",
  "Violencia familiar · adulto mayor",
  ("Violencia contra la persona adulta mayor", ["Maltrato físico, psicológico, económico o abandono por familiares o cuidadores.",
                                                "Con amenaza de muerte hay riesgo grave: el médico debe denunciar y activar la protección."]),
  ("Viuda de 81 años", ["Mantiene con su pensión a su hijo alcohólico de 41 años.", "Agresiones físicas y amenazas de muerte; muy ansiosa."]),
  ["Denunciar a la Policía o Fiscalía (Ley 30364); la ley obliga al personal de salud a comunicar.",
   "Línea 100 y Centro de Emergencia Mujer (CEM); medidas de protección.",
   "Atender su salud mental y física; registrar las lesiones."],
  "Ley 30364 y Ley 30490 de la Persona Adulta Mayor (Perú); " + OMS + ", maltrato de personas mayores (2024).",
  op=("¿Conducta urgente?", ["No: no protege", "No: hay que actuar", "No: no resuelve la violencia", "Sí: riesgo grave", "No: es urgente"]),
  arbol=Q("Adulta mayor con violencia en casa: ¿riesgo grave (amenaza de muerte, agresión física)?", [
      L("Sí (este caso)", "DENUNCIAR", ["Policía o Fiscalía", "Línea 100, CEM"], path=True),
      L("Riesgo leve", "Plan de seguridad", ["Seguimiento y red de apoyo"])], path=True))

# PED-127 · Neonato febril: antibióticos aunque falle la PL · ÁRBOL + AAP 2021
S("arbol", "PED-127", "Neonato de 2 semanas con fiebre, irritabilidad y succión débil en quien no se logra la punción lumbar: iniciar antibióticos parenterales sin esperar",
  "Fiebre en el recién nacido",
  ("Neonato febril", ["Todo recién nacido con fiebre ≥ 38 °C tiene riesgo alto de infección bacteriana grave.",
                      "Si no se puede hacer la punción lumbar, no se retrasa el antibiótico: se hace después."]),
  ("Neonato de 2 semanas", ["T 38,9 °C, irritabilidad y succión débil.", "Hemograma, PCR, procalcitonina, cultivos de sangre y orina; PL fallida."]),
  ["Ampicilina + cefotaxima (o gentamicina) EV a dosis meníngeas; aciclovir si hay sospecha de herpes.",
   "Hospitalizar; repetir la PL cuando se pueda (aunque sea tras el antibiótico).",
   "Si el LCR no se obtuvo, completar como meningitis si los cultivos o la clínica lo sugieren."],
  AAP + ", lactante febril de 8 a 60 días (2021).",
  op=("¿Conducta?", ["No reemplaza; retrasa", "No reemplaza la PL", "Se pide, pero no reemplaza el antibiótico", "Sí: no esperar",
                     "No: aumenta la mortalidad"]),
  arbol=Q("Neonato febril con mal aspecto y sin LCR: ¿esperar resultados?", [
      L("No (este caso)", "ANTIBIÓTICOS EV YA", ["Ampicilina + cefotaxima", "PL después"], path=True),
      L("Aspecto bueno, > 28 días", "Según marcadores", ["Guía AAP 2021"])], path=True),
  escala=dict(nombre="Lactante febril según la edad (AAP 2021)", orden=True,
              que="Cuanto menor, más estudio y tratamiento empírico.",
              grados=[("8-21 días", "Todos", ["Cultivos, PL, antibiótico", "Hospitalizar"]), ("22-28 días", "Según marcadores", ["PL si están alterados"]),
                      ("29-60 días", "Según marcadores", ["Más opciones ambulatorias"])],
              caso=0, porque=[("Tiene 2 semanas", True), ("Además se ve enfermo", True)],
              conducta="Antibióticos EV y hospitalizar."))

# SP-088 · Intersectorialidad frente al dengue · TARJETAS
S("tarjetas", "SP-088", "Ante transmisión de dengue, el médico jefe convoca al alcalde y a instituciones públicas y privadas: intersectorialidad",
  "Atención primaria de salud · principios",
  ("Intersectorialidad", ["Trabajo coordinado del sector salud con otros sectores (municipio, educación, empresas, comunidad).",
                          "El dengue no se controla solo desde el centro de salud: necesita limpieza, agua y educación."]),
  ("Centro de salud en escenario III", ["Hay transmisión de dengue en la zona.", "Reunión con el alcalde y otras instituciones."]),
  ["Escenario III: hay casos autóctonos (transmisión): control vectorial intensivo y vigilancia de febriles.",
   "El municipio: recojo de inservibles y criaderos; educación: escuelas.",
   "Comités multisectoriales con metas y responsables."],
  "OPS, APS renovada (2007); " + MINSA + ", NTS de dengue (2024).",
  op=("¿Principio?", ["No: diferencias injustas", "No: es un valor general", "Sí: varios sectores juntos", "No: es apoyo mutuo", "No: cubrir a todos"]),
  d=dict(rotulo="Principios de la atención primaria", ans=0,
         cards=[dict(titulo="Intersectorialidad", datos=[("Idea", "Varios sectores", True), ("Aquí", "Alcalde e instituciones", True), ("Logra", "Control del vector", True)],
                     pie="Este caso."),
                dict(titulo="Equidad", datos=[("Idea", "Sin brechas injustas", False), ("Ejemplo", "Priorizar al más pobre", False), ("Aquí", "No", False)],
                     pie="Valor."),
                dict(titulo="Universalidad", datos=[("Idea", "Cubrir a todos", False), ("Ejemplo", "Seguro universal", False), ("Aquí", "No", False)],
                     pie="Acceso."),
                dict(titulo="Participación social", datos=[("Idea", "La comunidad decide", False), ("Ejemplo", "Juntas vecinales", False), ("Aquí", "Parcial", False)],
                     pie="Comunidad.")]))

# END-035 · Tiroiditis subaguda de De Quervain · TARJETAS + fases
S("tarjetas", "END-035", "Mujer con dolor cervical que aumenta al tragar, tirotoxicosis, tiroides dolorosa, VSG alta y anticuerpos negativos tras una faringitis: tiroiditis subaguda de De Quervain",
  "Tiroides · tiroiditis",
  ("Tiroiditis subaguda (De Quervain)", ["Inflamación de la tiroides después de una infección viral: la glándula duele y libera la hormona guardada.",
                                         "Tiroides dolorosa, VSG alta, captación de yodo baja y anticuerpos negativos."]),
  ("Mujer de 48 años", ["3 semanas de dolor cervical al tragar, palpitaciones, calor y pérdida de peso; faringitis hace 2 meses.",
                        "Tiroides dolorosa, temblor; TSH baja, T4 alta; anticuerpos negativos; VSG 58."]),
  ["AINE para el dolor; prednisona si es intenso.",
   "Propranolol para los síntomas; no dar antitiroideos (la glándula no fabrica de más).",
   "Controlar la TSH: puede pasar por hipotiroidismo transitorio."],
  "ATA, tirotoxicosis (2016, act. 2024).",
  op=("¿Diagnóstico?", ["No: tiroides no dolorosa, ojos", "No: hipotiroidismo, anticuerpos (+)", "Sí: dolorosa + VSG alta + posviral",
                        "No: tiroides no palpable", "No: fiebre alta, absceso"]),
  d=dict(rotulo="Tirotoxicosis con tiroides: ¿cuál?", ans=0,
         cards=[dict(titulo="De Quervain", datos=[("Tiroides", "Dolorosa", True), ("VSG", "Alta", True), ("Antes", "Virosis", True)],
                     pie="Este caso."),
                dict(titulo="Graves", datos=[("Tiroides", "Bocio no doloroso", False), ("Ojos", "Exoftalmos", False), ("Captación", "Alta", False)],
                     pie="TRAb."),
                dict(titulo="Hashimoto", datos=[("Curso", "Hipotiroidismo", False), ("Ac", "Anti-TPO (+)", False), ("Dolor", "No", False)],
                     pie="Autoinmune."),
                dict(titulo="Supurativa", datos=[("Clínica", "Fiebre alta", False), ("Cuello", "Rojo, absceso", False), ("Trato", "Antibiótico, drenaje", False)],
                     pie="Bacteriana.")]),
  escala=dict(nombre="Fases de la tiroiditis subaguda", orden=True,
              que="Evolución en semanas a meses.",
              grados=[("Tirotóxica", "Semanas 1-6", ["Libera hormona guardada"]), ("Eutiroidea", "Transición", ["Hormonas normales"]),
                      ("Hipotiroidea", "Meses", ["Glándula vacía"]), ("Recuperación", "Final", ["Casi siempre normal"])],
              caso=0, porque=[("TSH baja y T4 alta", True), ("3 semanas de evolución", True)],
              conducta="AINE y propranolol."))
