"""Entrega 1 · tanda 12 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, MINSA, OMS, CDC, ESC, KDIGO, GINA, AAP

CC = " · Wikimedia Commons · "

# NEF-019 · Pericarditis urémica · ÁRBOL
S("arbol", "NEF-019", "Insuficiencia renal crónica con dolor pleurítico, ruidos apagados y frote pericárdico: pericarditis urémica, hemodiálisis",
  "Complicaciones de la uremia · pericarditis urémica",
  ("Pericarditis urémica", ["Las toxinas urémicas inflaman el pericardio en pacientes con ERC avanzada que aún no se dializan.",
                            "Dolor que empeora al inspirar, frote pericárdico; puede formar derrame y taponamiento."]),
  ("Mujer de 26 años con ERC", ["3 días de dolor precordial intenso que empeora al inspirar.",
                                "PA 100/70, FC 98, ruidos apagados, frote; creatinina 5, K⁺ 5,4."]),
  ["Es indicación de diálisis urgente: la hemodiálisis intensiva (sin heparina) la resuelve en 1-2 semanas.",
   "Ecocardiograma: buscar derrame y signos de taponamiento (que exigen pericardiocentesis).",
   "AINE y corticoides ayudan poco y dañan; la pericardiectomía es para la constricción."],
  ESC + ", miocarditis y pericarditis (2025); " + KDIGO + ", inicio de diálisis; " + HARRISON + ".",
  op=("¿Tratamiento inmediato?", ["Sí: retira las toxinas urémicas", "No: no tratan la causa", "No: es para la pericarditis constrictiva",
                                  "No: K⁺ 5,4 sin cambios en el ECG", "Poco útiles y dañan el riñón"]),
  arbol=Q("ERC con pericarditis: ¿ya está en diálisis?", [
      L("No: pericarditis urémica (este caso)", "HEMODIÁLISIS", ["Intensiva y sin heparina", "Eco para descartar taponamiento"], path=True),
      L("Sí: pericarditis de diálisis", "Intensificar la diálisis", ["Revisar si la dosis es suficiente"])], path=True))

# NEF-020 · Nefritis intersticial aguda · TARJETAS
S("tarjetas", "NEF-020", "Falla renal con eosinófilos en orina y complemento normal días después de iniciar ceftazidima: nefritis intersticial aguda",
  "Lesión renal aguda · nefritis intersticial",
  ("Nefritis intersticial aguda (NIA)", ["Reacción alérgica en el intersticio renal, casi siempre por fármacos (betalactámicos, AINE, IBP).",
                                         "Aparece 5-10 días después de iniciar el fármaco; puede haber fiebre, exantema y eosinofilia."]),
  ("Mujer de 35 años", ["Neumonía intrahospitalaria tratada con ceftazidima.",
                        "Al 5.º día: oliguria, hematuria; creatinina 2,4; proteinuria 2 g/24 h; eosinófilos en orina; complemento normal."]),
  ["Lo principal: suspender el fármaco sospechoso.",
   "Si la creatinina no mejora en pocos días: corticoides; la biopsia confirma (infiltrado intersticial con eosinófilos).",
   "La eosinofiluria orienta, pero su ausencia no la descarta."],
  KDIGO + ", lesión renal aguda (2012); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: el complemento estaría bajo", "No: sin hemoptisis ni anticuerpos", "Sí: fármaco + eosinófilos + C3 normal",
                        "No: nefrótico de inicio lento", "No: sin isquemia ni cilindros granulosos"]),
  d=dict(rotulo="Falla renal en el hospital: ¿cuál?", ans=0,
         cards=[dict(titulo="Nefritis intersticial", datos=[("Antes", "Fármaco nuevo", True), ("Orina", "Eosinófilos", True), ("Complemento", "Normal", True)],
                     pie="Este caso: suspender."),
                dict(titulo="GN postinfecciosa", datos=[("Antes", "Infección 1-3 sem", False), ("Orina", "Cilindros hemáticos", False),
                                                       ("Complemento", "C3 bajo", False)],
                     pie="Soporte."),
                dict(titulo="Necrosis tubular", datos=[("Antes", "Choque, contraste", False), ("Orina", "Cilindros granulosos", False),
                                                      ("Eosinófilos", "No", False)],
                     pie="La más común."),
                dict(titulo="Pulmón-riñón", datos=[("Pulmón", "Hemoptisis", False), ("Marcador", "Anti-MBG, ANCA", False), ("Curso", "Rápido", False)],
                     pie="Plasmaféresis.")]))

# REU-013 · Escabiosis del lactante · ÁRBOL + foto real
S("arbol", "REU-013", "Lactante con pápulas pruriginosas en axilas, cara, cuero cabelludo, palmas y plantas, y madre con lesiones iguales: escabiosis, permetrina",
  "Dermatología · ectoparasitosis",
  ("Escabiosis (sarna)", ["Sarcoptes scabiei excava surcos en la piel; prurito que empeora de noche.",
                          "En el lactante afecta también cara, cuero cabelludo, palmas y plantas (en el adulto los respeta)."]),
  ("Lactante de 10 meses", ["20 días de pápulas eritematosas en axilas, cara, cuero cabelludo, palmas y plantas.",
                            "La madre tiene lesiones en las mamas y las axilas."]),
  ["Permetrina al 5 % en todo el cuerpo (en el lactante también cabeza y cara), repetir a los 7 días.",
   "Tratar a todos los convivientes el mismo día; lavar ropa y sábanas con agua caliente.",
   "Ivermectina oral solo desde los 15 kg; el prurito puede durar 2-4 semanas tras curar."],
  "IUSTI, guía europea de escabiosis (2017); " + CDC + ", escabiosis (2024); " + NELSON + ".",
  op=("¿Tratamiento?", ["No: es para impétigo", "No: es para herpes", "Sí: mata al ácaro; a toda la familia", "No: calma, pero no cura",
                        "No: es para hongos"]),
  arbol=Q("Prurito nocturno con convivientes afectados: ¿escabiosis?", [
      L("Sí: madre con lesiones (este caso)", "PERMETRINA AL 5 %", ["Todo el cuerpo, repetir en 7 días", "A toda la familia"], path=True),
      L("Lesiones con costra amarilla", "Impétigo", ["Mupirocina"])], path=True),
  banda=B("Surco de escabiosis (foto real)", P("escabiosis.jpg", 300, 233, [
            ("flecha", 0.845, 0.14, 0.55, 0.1, "ácaro al final\ndel surco"),
            ("flecha", 0.78, 0.3, 0.82, 0.72, "surco"),
            ("flecha", 0.35, 0.55, 0.18, 0.9, "rascado")],
          credito="Michael Geary" + CC + "dominio público"),
          [("Surco acarino", "Línea fina de pocos milímetros: el túnel donde la hembra pone huevos."),
           ("El ácaro", "Punto al final del surco; se puede sacar con aguja y verlo al microscopio."),
           ("Lesiones por rascado", "Costras y excoriaciones; pueden infectarse (impétigo)."),
           ("En el lactante", "Pápulas y vesículas también en palmas, plantas y cabeza.")],
          pie="Piel de otro paciente (vista de cerca).", ans=0))

# CIR-027 · Quemado con inhalación · ÁRBOL + signos de inhalación
S("arbol", "CIR-027", "Quemado en un ambiente cerrado con humo, ronquera, esputo gris y quemaduras faciales: oxígeno por mascarilla de inmediato",
  "Quemaduras · lesión por inhalación",
  ("Lesión por inhalación", ["El humo quema la vía aérea y trae monóxido de carbono (CO) y cianuro.",
                             "La vía aérea se edematiza en horas: puede cerrarse."]),
  ("Varón de 25 años", ["Quemado en una habitación poco ventilada con mucho humo.",
                        "Ronquera, tos, esputo gris; FR 30, quejumbroso; quemaduras en párpados, nariz, boca y tórax."]),
  ["Primero A y B: oxígeno al 100 % con mascarilla de no reinhalación (desplaza el CO).",
   "Ronquera, estridor o quemaduras profundas de la cara y el cuello: intubar temprano, antes de que se cierre la vía.",
   "Luego: retirar ropa, líquidos según la superficie quemada (Parkland), analgesia."],
  ATLS + "; ABA, Advanced Burn Life Support (2023).",
  op=("¿Medida inmediata?", ["No: no es lo urgente", "Se hace, pero después de la vía aérea", "Sí: CO y vía aérea primero",
                             "Se hace, pero después de la vía aérea", "No: no es lo urgente"]),
  arbol=Q("Quemado: ¿signos de inhalación?", [
      L("Sí (este caso)", "OXÍGENO AL 100 % CON MASCARILLA", ["Preparar intubación temprana", "Medir carboxihemoglobina"], path=True),
      L("No", "Oxígeno según SatO₂", ["Seguir el ABCDE"])], path=True),
  triada=TR([("Espacio cerrado con humo", "Sí", True), ("Ronquera o estridor", "Ronquera", True), ("Esputo carbonáceo", "Gris", True),
             ("Quemaduras faciales", "Párpados, nariz, boca", True), ("Vibrisas nasales quemadas", "No se informa", False)],
            [("Signos de lesión por inhalación", 0, 4)],
            "Cuatro signos: alto riesgo de que se cierre la vía aérea; oxígeno y valorar intubación ya.",
            rotulo="Signos de alarma"))

# PED-047 · Estenosis hipertrófica del píloro · TARJETAS + eco real
S("tarjetas", "PED-047", "Recién nacido de 15 días con vómitos explosivos no biliosos, masa palpable y píloro engrosado en la ecografía: estenosis hipertrófica del píloro",
  "Cirugía pediátrica · vómitos del lactante",
  ("Estenosis hipertrófica del píloro", ["El músculo del píloro crece y cierra la salida del estómago.",
                                         "Varón de 2 a 8 semanas con vómitos en proyectil no biliosos y hambre después de vomitar."]),
  ("Recién nacido de 15 días", ["Vómitos explosivos no biliosos.", "Tumoración palpable («oliva»); ecografía: estómago distal engrosado."]),
  ["Ecografía: músculo ≥ 3 mm de grosor y canal ≥ 15 mm de largo.",
   "Alcalosis metabólica hipoclorémica e hipopotasémica: corregirla antes de operar.",
   "Piloromiotomía de Ramstedt (abierta o laparoscópica); no es una urgencia inmediata."],
  NELSON + "; APSA, guía de estenosis pilórica (2023).",
  op=("¿Diagnóstico?", ["No: vómito bilioso desde el 1.er día", "Sí: vómito no bilioso + oliva", "No: vómito bilioso, urgencia",
                        "No: vómito bilioso", "No: sin meconio, distensión"]),
  d=dict(rotulo="Vómitos en el recién nacido: ¿cuál?", ans=0,
         cards=[dict(titulo="Estenosis pilórica", datos=[("Vómito", "No bilioso", True), ("Edad", "2-8 semanas", True), ("Examen", "Oliva", True)],
                     pie="Este caso."),
                dict(titulo="Atresia duodenal", datos=[("Vómito", "Bilioso", False), ("Rx", "Doble burbuja", False), ("Asocia", "Síndrome de Down", False)],
                     pie="Primer día."),
                dict(titulo="Malrotación con vólvulo", datos=[("Vómito", "Bilioso", False), ("Curso", "Brusco", False), ("Riesgo", "Necrosis", False)],
                     pie="Cirugía urgente."),
                dict(titulo="Hirschsprung", datos=[("Meconio", "Tarda > 48 h", False), ("Abdomen", "Distendido", False), ("Biopsia", "Sin ganglios", False)],
                     pie="Biopsia rectal.")]),
  banda=B("Ecografía real de estenosis pilórica", P("piloro.jpg", 300, 282, [
            ("circulo", 0.43, 0.72, 0.17, "músculo grueso\ny canal largo", 0.78, 0.9)],
          credito="Laughlin Dawes" + CC + "CC BY-SA 4.0"),
          [("Músculo engrosado", "Pared del píloro ≥ 3 mm (normal < 2 mm)."),
           ("Canal alargado", "El canal pilórico mide ≥ 15 mm y no se abre."),
           ("Estómago lleno", "El líquido no pasa al duodeno aunque el bebé haya comido."),
           ("La flecha roja", "Marca del autor sobre el píloro engrosado.")],
          pie="Ecografía de otro lactante (6 semanas).", ans=0))

# PED-048 · Crisis asmática en preescolar · TARJETAS + gravedad
S("tarjetas", "PED-048", "Niña de 4 años con dificultad respiratoria aguda y sibilancias bilaterales tras un resfriado: crisis de asma",
  "Asma en el niño · crisis",
  ("Crisis de asma en el preescolar", ["Las infecciones virales son el desencadenante más común.",
                                       "Sibilancias difusas, tos y dificultad respiratoria que mejoran con broncodilatador."]),
  ("Niña de 4 años, hospitalizada", ["Síntomas catarrales 3 días; dificultad respiratoria aguda.", "Sibilancias en ambos campos pulmonares."]),
  ["Salbutamol con inhalador y espaciador: 2-6 puffs cada 20 minutos la primera hora.",
   "Oxígeno para SatO₂ 94-98 %; corticoide oral (prednisolona) en crisis que requieren hospitalización.",
   "Al alta: plan de acción y control; considerar corticoide inhalado si las crisis se repiten."],
  GINA + " (niños ≤ 5 años); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Sí: sibilancias difusas + gatillo viral", "No: es de menores de 2 años", "No: sin soplo, hepatomegalia ni edema",
                        "No: daría fiebre alta y crepitantes", "No: daría foco de crepitantes, no sibilancias difusas"]),
  d=dict(rotulo="Sibilancias en un niño: ¿cuál?", ans=0,
         cards=[dict(titulo="Asma", datos=[("Edad", "4 años", True), ("Sibilancias", "Difusas", True), ("Gatillo", "Resfriado", True)],
                     pie="Este caso: salbutamol."),
                dict(titulo="Bronquiolitis", datos=[("Edad", "< 2 años", False), ("Episodio", "Primero", False), ("Virus", "VSR", False)],
                     pie="Soporte."),
                dict(titulo="Bronconeumonía", datos=[("Fiebre", "Alta", False), ("Ruidos", "Crepitantes", False), ("Rx", "Parches", False)],
                     pie="Antibiótico."),
                dict(titulo="Insuficiencia cardiaca", datos=[("Soplo", "Sí", False), ("Hígado", "Grande", False), ("Edema", "Sí", False)],
                     pie="Diurético.")]),
  escala=dict(nombre="Gravedad de la crisis de asma en ≤ 5 años (GINA)", orden=True, que="Se decide con signos que se ven al lado de la cama.",
              grados=[("Leve o moderada", "Habla y bebe", ["SatO₂ ≥ 92 %", "FC ≤ 180 (0-3 años) o ≤ 150 (4-5 años)"]),
                      ("Grave", "No habla ni bebe", ["SatO₂ < 92 %, cianosis", "Confusión, tórax silente", "Hospitalizar"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Hospitalizada: medir SatO₂ y ver si habla o bebe", True), ("Sin esos datos no se puede graduar", False)],
              conducta="Salbutamol con espaciador, oxígeno si SatO₂ < 94 % y prednisolona oral."))

# PED-049 · Neumonía del preescolar hospitalizada · ÁRBOL
S("arbol", "PED-049", "Niña de 4 años hospitalizada con fiebre, tos, crepitantes bilaterales y leucocitosis con desviación: ceftriaxona",
  "Infecciones respiratorias agudas · neumonía en el niño",
  ("Neumonía bacteriana en el niño", ["Neumococo es el germen más común entre los 3 meses y los 5 años.",
                                      "Fiebre, tos, dificultad respiratoria, crepitantes; leucocitosis con desviación izquierda."]),
  ("Niña de 4 años, hospitalizada", ["24 horas de fiebre, tos y dificultad respiratoria.", "38 °C, FR 35, crepitantes bilaterales; leucocitosis con desviación."]),
  ["Si está hospitalizada por gravedad o no tolera la vía oral: antibiótico EV (ceftriaxona o ampicilina).",
   "Sin gravedad, en casa: amoxicilina oral en dosis altas (de primera elección).",
   "Macrólido (claritromicina) solo si se sospecha neumonía atípica (mayores de 5 años)."],
  OMS + ", manejo de la neumonía infantil (2024); BTS, neumonía en niños (2011); " + NELSON + ".",
  op=("¿Antibiótico?", ["No: para atípicas", "Sí: EV en la niña hospitalizada", "No: contraindicada < 8 años", "No: no es de elección en niños",
                        "Bastaría sin gravedad; hospitalizada va EV"]),
  arbol=Q("Neumonía bacteriana: ¿hospitalizada por gravedad o sin vía oral?", [
      L("Sí (este caso)", "CEFTRIAXONA EV", ["O ampicilina EV", "Pasar a oral al mejorar"], path=True),
      L("No", "Amoxicilina oral", ["Dosis altas, en casa"])], path=True))

# CB-014 · Aterosclerosis: íntima · TARJETAS
S("tarjetas", "CB-014", "LDL muy alto y obstrucción coronaria: la aterosclerosis compromete la capa íntima",
  "Patología vascular · aterosclerosis",
  ("Aterosclerosis", ["El LDL entra a la íntima dañada, se oxida y lo comen los macrófagos (células espumosas).",
                      "Se forma la placa: núcleo de lípidos con una capa fibrosa que estrecha la luz."]),
  ("Varón de 45 años con angina", ["Hipercolesterolemia con LDL muy alto.", "Obstrucción de una rama de la coronaria izquierda."]),
  ["Íntima: endotelio y subendotelio; ahí nace el ateroma.",
   "Media: músculo liso; su calcificación sin obstrucción es la esclerosis de Mönckeberg.",
   "Meta de LDL en prevención secundaria: < 55 mg/dL (ESC 2019, act. 2025)."],
  "Robbins y Cotran, Patología estructural y funcional 11.ª ed. (2025); " + ESC + ", dislipidemias (2019, act. 2025).",
  op=("¿Capa?", ["No: aortitis sifilítica, vasa vasorum", "No: es un límite, no una capa", "Sí: el ateroma nace en la íntima",
                 "No: esclerosis de Mönckeberg", "No: empieza en la íntima"]),
  d=dict(rotulo="Las capas de la arteria y su enfermedad", ans=0,
         cards=[dict(titulo="Íntima", datos=[("Tiene", "Endotelio", True), ("Lesión", "Ateroma", True), ("Ejemplo", "Placa coronaria", True)],
                     pie="Este caso."),
                dict(titulo="Media", datos=[("Tiene", "Músculo liso", False), ("Lesión", "Calcificación", False), ("Ejemplo", "Mönckeberg", False)],
                     pie="No obstruye."),
                dict(titulo="Adventicia", datos=[("Tiene", "Vasa vasorum", False), ("Lesión", "Endarteritis", False), ("Ejemplo", "Aortitis sifilítica", False)],
                     pie="Aneurisma."),
                dict(titulo="Elástica externa", datos=[("Es", "Un límite", False), ("Separa", "Media y adventicia", False), ("Lesión", "No propia", False)],
                     pie="Lámina, no capa.")]))

# CIR-028 · Enfermedad arterial periférica · ÁRBOL + Fontaine
S("arbol", "CIR-028", "Claudicación limitante pese al tratamiento médico con oclusión larga de la femoral superficial: bypass femoropoplíteo con safena",
  "Enfermedad arterial periférica · revascularización",
  ("Enfermedad arterial periférica", ["Aterosclerosis de las piernas: dolor al caminar que cede al parar (claudicación).",
                                      "Primero ejercicio supervisado y tratamiento médico; revascularizar si sigue limitando."]),
  ("Varón de 63 años", ["6 meses de claudicación limitante pese al tratamiento médico.",
                        "Oclusión larga de la femoral superficial; poplítea sana 5 cm por encima de la rodilla."]),
  ["Todos: dejar de fumar, estatina de alta intensidad, antiagregante y ejercicio.",
   "Oclusiones largas de la femoral: bypass con vena safena (dura más que la prótesis); cortas: angioplastia.",
   "Cilostazol mejora la distancia de marcha; la simpatectomía ya no se usa."],
  ESC + ", enfermedades arteriales periféricas y aórticas (2024); ESVS, isquemia crónica que amenaza la extremidad (2019).",
  op=("¿Primera elección?", ["Sí: lesión larga, la vena dura más", "Alternativa si no hay vena", "Mejor en lesiones cortas",
                             "Ya falló el tratamiento médico", "No: obsoleta"]),
  arbol=Q("Claudicación limitante pese a tratamiento médico: ¿cómo es la lesión?", [
      L("Oclusión larga (este caso)", "BYPASS CON VENA SAFENA", ["Femoropoplíteo sobre la rodilla"], path=True),
      L("Estenosis corta", "Angioplastia", ["± stent"])], path=True),
  escala=dict(nombre="Clasificación de Fontaine", que="Gradúa la enfermedad arterial periférica por los síntomas.",
              grados=[("I", "Sin síntomas", ["Pulsos bajos, ITB < 0,9"]), ("IIa", "Claudicación > 200 m", ["No limita"]),
                      ("IIb", "Claudicación < 200 m", ["Limita la vida diaria"]), ("III", "Dolor en reposo", ["De noche, mejora al colgar la pierna"]),
                      ("IV", "Úlcera o gangrena", ["Riesgo de amputación"])],
              caso=2, porque=[("Claudicación que limita pese al tratamiento", True), ("Sin dolor en reposo ni úlceras", True)],
              conducta="Tratamiento médico completo y bypass con safena por la lesión larga."))

# PED-050 · Hernia diafragmática congénita · ÁRBOL
S("arbol", "PED-050", "Recién nacido con sospecha de hernia diafragmática: la radiografía de tórax confirma",
  "Cirugía neonatal · hernia diafragmática congénita",
  ("Hernia diafragmática congénita", ["Un defecto del diafragma deja pasar las vísceras al tórax: el pulmón no crece (hipoplasia).",
                                      "Casi siempre es posterolateral izquierda (Bochdalek)."]),
  ("Pregunta de concepto", ["Recién nacido con sospecha de hernia diafragmática.", "¿Cómo se confirma?"]),
  ["Rx de tórax: asas con aire en el hemitórax izquierdo, mediastino desplazado; la sonda orogástrica sube al tórax.",
   "No ventilar con bolsa y mascarilla (llena de aire el intestino): intubar y colocar sonda orogástrica.",
   "La cirugía se hace después de estabilizar; hoy muchas se diagnostican en la ecografía prenatal."],
  "CDH EURO Consortium, consenso (2015, act. 2024); " + NELSON + ".",
  op=("¿Confirma?", ["No: es para motilidad", "No: no ve bien el tórax", "No: no sirve aquí", "Sí: asas en el tórax", "No: no ve el tórax"]),
  arbol=Q("Recién nacido con dificultad respiratoria y abdomen excavado", [
      L("Confirmar (este caso)", "RADIOGRAFÍA DE TÓRAX", ["Asas en el tórax", "Sonda que sube al tórax"], path=True),
      L("Mientras tanto", "Intubar + sonda orogástrica", ["Nunca bolsa y mascarilla"])], path=True),
  triada=TR([("Abdomen excavado", "Vísceras en el tórax", None), ("Ruidos intestinales en el tórax", "Lado izquierdo", None),
             ("Latido desplazado a la derecha", "Mediastino empujado", None), ("Dificultad respiratoria al nacer", "Hipoplasia pulmonar", None)],
            [("Pistas clínicas de la hernia de Bochdalek", 0, 3)],
            "Con estas pistas, Rx de tórax de inmediato.", rotulo="Pistas clínicas"))

# SP-033 · Derecho a la información · TARJETAS
S("tarjetas", "SP-033", "Complicación de una hernioplastia que no le advirtieron a la paciente: se vulneró el derecho a ser informado",
  "Derechos de los usuarios de salud · consentimiento informado",
  ("Derecho a la información", ["El paciente debe conocer en lenguaje sencillo su diagnóstico, tratamiento, riesgos y alternativas.",
                                "Se concreta en el consentimiento informado antes de operar."]),
  ("Mujer de 46 años", ["Operada de hernia inguinal no complicada.", "Infección profunda del sitio operatorio; dice que no le avisaron de ese riesgo."]),
  ["Ley 29414 (Perú): derechos de acceso, información, atención y recuperación, consentimiento informado y protección.",
   "Informar los riesgos frecuentes y los graves; registrarlo en el consentimiento firmado.",
   "Una complicación no es negligencia; no haberla informado sí vulnera un derecho."],
  "Ley n.º 29414 y su reglamento (DS 027-2015-SA); Ley General de Salud n.º 26842.",
  op=("¿Derecho vulnerado?", ["Sí: no conoció los riesgos", "No: no fue maltratada", "No: no se le impidió decidir ni moverse",
                              "No: no hubo discriminación", "No: no aplica"]),
  d=dict(rotulo="Derechos de las personas usuarias (Ley 29414)", ans=0,
         cards=[dict(titulo="A ser informado", datos=[("Qué", "Riesgos y alternativas", True), ("Cuándo", "Antes de operar", True),
                                                      ("Cómo", "Consentimiento", True)],
                     pie="Este caso."),
                dict(titulo="Dignidad", datos=[("Qué", "Trato respetuoso", False), ("Falta", "Maltrato", False), ("Ejemplo", "Humillar", False)],
                     pie="No aplica."),
                dict(titulo="Libertad individual", datos=[("Qué", "Decidir sin coacción", False), ("Falta", "Retener", False),
                                                         ("Ejemplo", "No dejar irse", False)],
                     pie="No aplica."),
                dict(titulo="Igualdad", datos=[("Qué", "Sin discriminación", False), ("Falta", "Excluir", False), ("Ejemplo", "Por raza o sexo", False)],
                     pie="No aplica.")]))

# HEM-006 · TRALI · TARJETAS + definición 2019
S("tarjetas", "HEM-006", "Edema pulmonar bilateral durante la transfusión de plasma en una paciente séptica: TRALI por anticuerpos contra granulocitos",
  "Reacciones transfusionales · TRALI",
  ("Lesión pulmonar aguda por transfusión (TRALI)", ["Anticuerpos del donante (anti-HLA o anti-HNA) activan los neutrófilos del receptor en el pulmón.",
                                                     "Edema pulmonar no cardiogénico durante o hasta 6 horas después de la transfusión."]),
  ("Mujer de 72 años", ["Posoperada de diverticulitis perforada, con hipotensión.",
                        "Con la 5.ª bolsa de plasma: disnea grave, esputo espumoso; Rx con edema bilateral."]),
  ["Detener la transfusión y dar soporte (oxígeno, ventilación); los diuréticos no ayudan.",
   "Lo producen sobre todo el plasma y las plaquetas de mujeres multíparas: por eso se prefiere plasma de varones.",
   "Distinguir de la sobrecarga (TACO): hipertensión, BNP alto y mejora con diuréticos."],
  "ISBT, redefinición de TRALI (Vlaar et al., 2019); " + HARRISON + ".",
  op=("¿Componente causante?", ["Sí: los neutrófilos se activan en el pulmón", "No: no causa edema pulmonar", "No: no causa edema pulmonar",
                                "No: no causa edema pulmonar", "No: el plasma no las trae"]),
  d=dict(rotulo="Disnea durante una transfusión: ¿cuál?", ans=0,
         cards=[dict(titulo="TRALI", datos=[("PA", "Baja", True), ("Edema", "No cardiogénico", True), ("Diurético", "No sirve", True)],
                     pie="Este caso: soporte."),
                dict(titulo="TACO (sobrecarga)", datos=[("PA", "Alta", False), ("BNP", "Alto", False), ("Diurético", "Mejora", False)],
                     pie="Furosemida."),
                dict(titulo="Anafilaxia", datos=[("Piel", "Urticaria", False), ("Vía aérea", "Broncoespasmo", False), ("Causa", "Déficit de IgA", False)],
                     pie="Adrenalina."),
                dict(titulo="Hemólisis aguda", datos=[("Causa", "ABO", False), ("Orina", "Oscura", False), ("Fiebre", "Sí", False)],
                     pie="Detener, hidratar.")]),
  escala=dict(nombre="Definición de TRALI (ISBT 2019)", orden=False, que="Separa el TRALI según haya o no otro riesgo de SDRA.",
              grados=[("Tipo I", "Sin factor de riesgo de SDRA", ["Edema bilateral < 6 h tras transfundir", "Hipoxemia"]),
                      ("Tipo II", "Con factor de riesgo de SDRA", ["Sepsis, cirugía mayor, choque", "Estable 12 h antes de transfundir"])],
              caso=1, porque=[("Perforación con hipotensión: tiene factor de riesgo de SDRA", True),
                              ("Edema bilateral durante la transfusión", True)],
              conducta="Detener la transfusión, oxígeno y ventilación; notificar al banco de sangre."))

# CAR-020 · Taponamiento cardiaco · ÁRBOL + tríada de Beck
S("arbol", "CAR-020", "Hipotensión, yugulares ingurgitadas, ruidos apagados, pulso paradójico y alternancia eléctrica: taponamiento cardiaco, pericardiocentesis",
  "Enfermedades del pericardio · taponamiento",
  ("Taponamiento cardiaco", ["El líquido del pericardio aprieta el corazón: no se llena y cae el gasto.",
                             "Es una emergencia: choque obstructivo."]),
  ("Varón de 24 años", ["Disnea y ortopnea; PA 70/40, FC 130, SatO₂ 92 %.",
                        "Pulso paradójico, ruidos apagados, yugulares ingurgitadas; ECG: bajo voltaje y alternancia eléctrica."]),
  ["Pericardiocentesis guiada por ecografía de inmediato.",
   "Mientras tanto: líquidos EV; evitar diuréticos y vasodilatadores (bajan más el llenado).",
   "Luego estudiar la causa: viral, tuberculosis, cáncer, trauma, uremia."],
  ESC + ", miocarditis y pericarditis (2025).",
  op=("¿Conducta?", ["Sí: drena el líquido", "No: no es un infarto", "No: no es un infarto ni TEP", "No: no es TEP",
                     "No: baja más el llenado"]),
  arbol=Q("Choque con yugulares llenas: ¿ruidos apagados y pulso paradójico?", [
      L("Sí (este caso)", "PERICARDIOCENTESIS", ["Guiada por eco", "Líquidos mientras tanto"], path=True),
      L("No: hipersonoridad", "Neumotórax a tensión", ["Descompresión"])], path=True),
  triada=TR([("Hipotensión", "70/40", True), ("Yugulares ingurgitadas", "Sí", True), ("Ruidos cardiacos apagados", "Sí", True),
             ("Pulso paradójico", "Sí", True), ("Alternancia eléctrica", "Sí", True)],
            [("Tríada de Beck", 0, 2), ("Otros signos", 3, 4)],
            "Tríada de Beck completa + pulso paradójico + alternancia eléctrica: taponamiento."))

# HEM-007 · Anemia microcítica: ferritina · ÁRBOL + gravedad OMS
S("arbol", "HEM-007", "Varón de 54 años con cansancio, Hb 10,7 y VCM 73: pedir ferritina para precisar la anemia",
  "Anemias microcíticas · estudio",
  ("Anemia microcítica", ["VCM < 80: ferropenia (la más común), talasemia, enfermedad crónica o sideroblástica.",
                          "La ferritina es el mejor examen para saber si falta hierro."]),
  ("Varón de 54 años", ["9 meses de cansancio al esfuerzo.", "Hb 10,7; VCM 73; leucocitos y plaquetas normales."]),
  ["Ferritina < 30 ng/mL = ferropenia (< 45 si hay duda); con inflamación puede salir normal.",
   "Varón adulto con ferropenia: buscar sangrado digestivo (endoscopia alta y colonoscopia) aunque no haya síntomas.",
   "Ferritina normal o alta: pensar en talasemia (electroforesis) o anemia de enfermedad crónica."],
  "BSG, anemia ferropénica en adultos (2021); " + OMS + ", puntos de corte de hemoglobina (2024).",
  op=("¿Examen?", ["No: es para hemólisis", "No: invasiva, no es el primer paso", "Después, si la ferritina es normal", "Sí: dice si falta hierro",
                   "No: es para anemia macrocítica"]),
  arbol=Q("Anemia microcítica: ¿ferritina?", [
      L("Baja (lo más probable)", "FERROPENIA", ["Buscar sangrado digestivo", "Hierro oral"], path=True),
      L("Normal o alta", "Talasemia o enfermedad crónica", ["Electroforesis, hierro"])], path=True),
  escala=dict(nombre="Gravedad de la anemia (OMS 2024)", que="Según la hemoglobina; valores para varones de 15 años o más.",
              grados=[("Hb 11-12,9", "Leve", ["Pocos síntomas"]), ("Hb 8-10,9", "Moderada", ["Cansancio al esfuerzo"]),
                      ("Hb < 8", "Grave", ["Síntomas en reposo", "Valorar transfusión"])],
              caso=1, porque=[("Hb 10,7 g/dL", True), ("Cansancio al esfuerzo", True)],
              conducta="Ferritina; si es baja, hierro y estudio del tubo digestivo."))

# CAR-021 · Estenosis mitral · TARJETAS
S("tarjetas", "CAR-021", "Disnea, hemoptisis, soplo diastólico en el ápex, fibrilación auricular y crepitantes: estenosis mitral",
  "Valvulopatías · estenosis mitral",
  ("Estenosis mitral", ["Casi siempre por fiebre reumática; la aurícula izquierda se dilata y aparece la FA.",
                        "La presión sube hacia los pulmones: disnea, hemoptisis, hipertensión pulmonar."]),
  ("Mujer de 33 años", ["6 meses de disnea progresiva y esputo con sangre.",
                        "Impulso paraesternal, ritmo irregular, soplo diastólico en el ápex, pulso deficitario, crepitantes."]),
  ["Soplo: retumbo diastólico en el ápex con chasquido de apertura; el impulso paraesternal es del VD (hipertensión pulmonar).",
   "Con FA: anticoagular con warfarina (los anticoagulantes directos no se usan en estenosis mitral reumática moderada o grave).",
   "Grave (área ≤ 1,5 cm²) y sintomática: valvuloplastia mitral con balón si la anatomía es favorable."],
  ESC + "/EACTS, valvulopatías (2025); ACC/AHA, valvulopatías (2020).",
  op=("¿Diagnóstico?", ["No: soplo en el borde esternal, aumenta al inspirar", "Sí: diastólico en ápex + FA + hemoptisis",
                        "No: el soplo sería sistólico", "No: soplo en foco aórtico, pulso saltón", "No: soplo sistólico pulmonar, desdoblamiento fijo"]),
  d=dict(rotulo="Soplo con disnea: ¿qué válvula?", ans=0,
         cards=[dict(titulo="Estenosis mitral", datos=[("Soplo", "Diastólico, ápex", True), ("Ritmo", "FA", True), ("Pulmón", "Hemoptisis", True)],
                     pie="Este caso."),
                dict(titulo="Insuficiencia mitral", datos=[("Soplo", "Sistólico, ápex", False), ("Irradia", "Axila", False), ("Ventrículo", "Dilatado", False)],
                     pie="Holosistólico."),
                dict(titulo="Insuficiencia aórtica", datos=[("Soplo", "Diastólico, aórtico", False), ("Pulso", "Saltón", False),
                                                           ("PA", "Diferencial amplia", False)],
                     pie="Signos periféricos."),
                dict(titulo="Estenosis tricuspídea", datos=[("Soplo", "Diastólico, esternal", False), ("Inspiración", "Aumenta", False),
                                                           ("Signo", "Rivero-Carvallo", False)],
                     pie="Rara sola.")]))

# CAR-022 · Fibrilación auricular · ÁRBOL + CHA₂DS₂-VA
S("arbol", "CAR-022", "Palpitaciones bruscas con ritmo irregular, FC 120 y pulso deficitario en una joven sin cardiopatía: fibrilación auricular",
  "Arritmias · fibrilación auricular",
  ("Fibrilación auricular (FA)", ["Ritmo totalmente irregular sin ondas P; el pulso va por debajo de la FC (pulso deficitario).",
                                  "La arritmia sostenida más frecuente; riesgo de ictus por trombos en la aurícula."]),
  ("Mujer de 35 años", ["Palpitaciones bruscas, fatiga y disnea; primer episodio.",
                        "FC 120 irregular, pulso 100 irregular, sin soplos; pulmones normales."]),
  ["ECG para confirmar; buscar causas: hipertiroidismo (TSH), valvulopatía (eco), alcohol.",
   "Inestable: cardioversión eléctrica; estable: controlar la FC (betabloqueador) o cardioversión si lleva < 24-48 h.",
   "Anticoagular según CHA₂DS₂-VA (ESC 2024); con 0 puntos no se anticoagula."],
  ESC + ", fibrilación auricular (2024).",
  op=("¿Diagnóstico?", ["No: sin soplo", "No: joven, sin angina", "Sí: ritmo irregular + pulso deficitario", "Diagnóstico de descarte; hay arritmia",
                        "No: sería regular"]),
  arbol=Q("Taquicardia: ¿ritmo irregular con pulso deficitario?", [
      L("Sí (este caso)", "FIBRILACIÓN AURICULAR", ["ECG, TSH, eco", "Controlar FC"], path=True),
      L("No, regular", "Sinusal o supraventricular", ["Buscar la causa"])], path=True),
  escala=dict(nombre="Puntaje CHA₂DS₂-VA (ESC 2024)", modo="puntaje", que="Riesgo de ictus en la FA; decide si anticoagular.",
              items=[("C", "Insuficiencia cardiaca (1)", "No", 0), ("H", "Hipertensión (1)", "PA 130/80", 0), ("A₂", "Edad ≥ 75 (2)", "35 años", 0),
                     ("D", "Diabetes (1)", "No", 0), ("S₂", "Ictus o embolia previa (2)", "No", 0), ("V", "Enfermedad vascular (1)", "No", 0),
                     ("A", "Edad 65-74 (1)", "No", 0)],
              total_txt="Total: 0 puntos",
              rangos=[("0", "Riesgo bajo", "Sin anticoagulante"), ("1", "Intermedio", "Considerar anticoagular"),
                      ("≥ 2", "Alto", "Anticoagular (DOAC)")],
              caso_rango=0, porque=[("Joven sin factores de riesgo", True), ("El sexo femenino ya no suma (ESC 2024)", True)],
              conducta="No anticoagular; controlar la FC y buscar la causa."))

# GAS-013 · CU con espondiloartritis · TARJETAS + manifestaciones extraintestinales
S("tarjetas", "GAS-013", "Lumbalgia con sacroilitis, sangre oculta y colon con mucosa granular, úlceras difusas y seudopólipos: colitis ulcerosa",
  "Enfermedad inflamatoria intestinal · manifestaciones extraintestinales",
  ("Colitis ulcerosa con espondiloartritis", ["La CU daña la mucosa de forma continua: granular, friable, úlceras y seudopólipos.",
                                              "Puede acompañarse de sacroilitis o espondilitis, que siguen su propio curso."]),
  ("Mujer de 35 años", ["5 años de lumbalgia progresiva; artralgias el último año; Thevenon positivo.",
                        "Rx: sacroilitis. Colectomía: mucosa granular y friable, ulceración difusa y seudopólipos."]),
  ["Sacroilitis y espondilitis no dependen de la actividad intestinal; la artritis periférica sí.",
   "Anti-TNF tratan a la vez el intestino y la columna.",
   "Otras: eritema nudoso, uveítis, colangitis esclerosante primaria (más en la CU)."],
  "ECCO, manifestaciones extraintestinales de la EII (2024); ECCO, colitis ulcerosa (2022).",
  op=("¿Diagnóstico?", ["Sí: ulceración difusa + seudopólipos", "No: úlceras en botón de camisa, no difusas", "No: ileocecal con granulomas",
                        "No: masa, no ulceración difusa", "No: daño salteado y transmural"]),
  d=dict(rotulo="Colitis crónica: ¿cuál?", ans=0,
         cards=[dict(titulo="Colitis ulcerosa", datos=[("Mucosa", "Granular, friable", True), ("Úlceras", "Difusas, continuas", True),
                                                       ("Seudopólipos", "Sí", True)],
                     pie="Este caso."),
                dict(titulo="Enfermedad de Crohn", datos=[("Daño", "Transmural, salteado", False), ("Mucosa", "Empedrado", False),
                                                         ("Fístulas", "Sí", False)],
                     pie="Íleon terminal."),
                dict(titulo="Colitis amebiana", datos=[("Úlceras", "En botón de camisa", False), ("Heces", "Trofozoítos", False),
                                                      ("Lugar", "Ciego", False)],
                     pie="Metronidazol."),
                dict(titulo="TB intestinal", datos=[("Lugar", "Ileocecal", False), ("Biopsia", "Granuloma caseoso", False), ("Pulmón", "A veces", False)],
                     pie="Antituberculosos.")]),
  triada=TR([("Sacroilitis o espondilitis", "Sacroilitis en Rx", True), ("Artritis periférica", "Artralgias", True), ("Eritema nudoso", "No se informa", False),
             ("Uveítis", "No se informa", False), ("Colangitis esclerosante", "No se informa", False)],
            [("Manifestaciones extraintestinales", 0, 4)],
            "La sacroilitis acompaña a la colitis ulcerosa y sigue su propio curso.", rotulo="Manifestaciones con nombre propio"))

# GAS-014 · Adenocarcinoma gástrico · TARJETAS + Lauren
S("tarjetas", "GAS-014", "Tumor ulcerado del píloro con obstrucción de la salida gástrica y H. pylori positivo: adenocarcinoma gástrico",
  "Neoplasias gástricas · adenocarcinoma",
  ("Adenocarcinoma gástrico", ["El 90-95 % de los cánceres de estómago; H. pylori es su principal factor.",
                               "Dolor, pérdida de peso, vómitos si obstruye el píloro; úlcera de bordes irregulares."]),
  ("Mujer de 53 años", ["5 meses de náuseas, vómitos y dolor epigástrico; TC: obstrucción de la salida gástrica.",
                        "Endoscopia: tumor ulcerado en el píloro de 2 × 4 cm; ureasa positiva."]),
  ["Biopsias múltiples del borde de la úlcera; TC de tórax, abdomen y pelvis para estadificar.",
   "Tratamiento: quimioterapia perioperatoria (FLOT) y gastrectomía con linfadenectomía D2.",
   "Erradicar H. pylori en la familia y en lesiones precursoras reduce el riesgo."],
  "NCCN, cáncer gástrico (2025); ESMO, cáncer gástrico (2022); Maastricht VI/Florencia, H. pylori (2022).",
  op=("¿Neoplasia?", ["No: tumor submucoso", "No: es de esófago", "No: raro y no ulcerado típicamente", "Sí: el más frecuente; H. pylori",
                      "Posible con H. pylori, pero menos frecuente"]),
  d=dict(rotulo="Tumor del estómago: ¿cuál?", ans=0,
         cards=[dict(titulo="Adenocarcinoma", datos=[("Frecuencia", "90-95 %", True), ("Factor", "H. pylori", True), ("Aspecto", "Úlcera irregular", True)],
                     pie="Este caso."),
                dict(titulo="Linfoma MALT", datos=[("Factor", "H. pylori", False), ("Aspecto", "Infiltrativo", False), ("Cura", "Erradicación", False)],
                     pie="Bajo grado."),
                dict(titulo="GIST / leiomiosarcoma", datos=[("Capa", "Submucosa", False), ("Marcador", "CD117 (KIT)", False), ("Aspecto", "Masa lisa", False)],
                     pie="Imatinib."),
                dict(titulo="Neuroendocrino", datos=[("Frecuencia", "Raro", False), ("Fondo", "Gastritis atrófica", False), ("Marcador", "Cromogranina", False)],
                     pie="Resección.")]),
  escala=dict(nombre="Clasificación de Lauren", orden=False, que="Tipo histológico del adenocarcinoma gástrico.",
              grados=[("Intestinal", "Forma glándulas", ["Ligado a H. pylori y metaplasia", "Antro, edad mayor", "Mejor pronóstico"]),
                      ("Difuso", "Células en anillo de sello", ["Linitis plástica", "Joven, peor pronóstico", "Gen CDH1"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Úlcera del píloro con H. pylori: más propio del tipo intestinal", True), ("Lo define la biopsia", True)],
              conducta="Biopsias, estadificación con TC y quimioterapia perioperatoria con gastrectomía."))

# NEU-009 · TB cavitada · TARJETAS
S("tarjetas", "NEU-009", "Fiebre, sudoración nocturna, baja de peso y hemoptisis con cavitación en el lóbulo superior: Mycobacterium tuberculosis",
  "Tuberculosis pulmonar",
  ("Tuberculosis pulmonar del adulto", ["Reactivación en los lóbulos superiores (más oxígeno): cavidades llenas de bacilos.",
                                        "Síntomas de meses: fiebre, sudor nocturno, baja de peso, tos y hemoptisis."]),
  ("Varón de 56 años", ["4 meses de fiebre, sudoración nocturna y pérdida de peso; hemoptisis.", "Estertores en el lóbulo superior; Rx: cavitación."]),
  ["Baciloscopia y prueba molecular (Xpert MTB/RIF Ultra), que además detecta resistencia a rifampicina.",
   "Esquema sensible: 2 meses HRZE y 4 meses HR (MINSA).",
   "Hemoptisis masiva: acostar del lado enfermo, asegurar la vía aérea; embolización de arterias bronquiales."],
  MINSA + ", norma técnica de tuberculosis (2023); " + OMS + ", guías consolidadas de tuberculosis (2025).",
  op=("¿Agente?", ["Sí: cavitación apical + síntomas crónicos", "No: joven, tos seca, curso corto", "No: en inmunodeprimidos",
                   "No: neumonía aguda con diarrea", "No: neumonía aguda lobar"]),
  d=dict(rotulo="Cavitación pulmonar: ¿qué germen?", ans=0,
         cards=[dict(titulo="M. tuberculosis", datos=[("Curso", "Meses", True), ("Lugar", "Lóbulo superior", True), ("Síntomas", "Sudor, baja de peso", True)],
                     pie="Este caso: Xpert."),
                dict(titulo="Nocardia", datos=[("Quién", "Inmunodeprimido", False), ("Otro", "Absceso cerebral", False), ("Tinción", "Ácido-alcohol débil", False)],
                     pie="Cotrimoxazol."),
                dict(titulo="S. pneumoniae", datos=[("Curso", "Agudo", False), ("Rx", "Lobar", False), ("Cavita", "Rara vez", False)],
                     pie="Amoxicilina."),
                dict(titulo="Absceso por anaerobios", datos=[("Quién", "Alcohólico, aspira", False), ("Esputo", "Fétido", False),
                                                            ("Lugar", "Segmentos posteriores", False)],
                     pie="Clindamicina.")]))

# NEU-010 · Fibrosis pulmonar idiopática · ÁRBOL + patrones de TCAR + TC real
S("arbol", "NEU-010", "Disnea progresiva y tos seca de 14 meses, panal de abeja y autoanticuerpos negativos: fibrosis pulmonar idiopática",
  "Enfermedades pulmonares intersticiales · fibrosis pulmonar idiopática",
  ("Fibrosis pulmonar idiopática (FPI)", ["Fibrosis progresiva de causa desconocida en mayores de 60 años, más en fumadores.",
                                          "Patrón de neumonía intersticial usual (NIU): panal de abeja subpleural y basal."]),
  ("Varón de 68 años", ["14 meses de disnea progresiva y tos seca; no mejora con corticoides.",
                        "Rx: panal de abeja; ANA, anti-ADN, anti-topoisomerasa I, ANCA y anticentrómero negativos."]),
  ["TC de alta resolución con NIU típica y sin otra causa (fármacos, polvos, colagenopatía) = FPI sin biopsia.",
   "Tratamiento: antifibróticos (nintedanib o pirfenidona); los corticoides no sirven y dañan.",
   "Oxígeno, rehabilitación, vacunas; trasplante pulmonar en candidatos."],
  "ATS/ERS/JRS/ALAT, fibrosis pulmonar idiopática y fibrosis progresiva (2022).",
  op=("¿Diagnóstico?", ["Sí: NIU + autoanticuerpos negativos", "No: hemoptisis y falla renal", "No: ANCA positivo, nódulos",
                        "No: anticuerpos positivos", "No: consolidaciones; responde a corticoides"]),
  arbol=Q("Fibrosis pulmonar: ¿hay una causa (fármaco, polvo, colagenopatía)?", [
      L("No: autoanticuerpos negativos (este caso)", "FIBROSIS PULMONAR IDIOPÁTICA", ["Antifibróticos", "Sin corticoides"], path=True),
      L("Sí", "Fibrosis secundaria", ["Tratar la causa"])], path=True),
  escala=dict(nombre="Patrones de TCAR para FPI (ATS/ERS 2022)", que="Cuanto más típico el patrón, menos falta la biopsia.",
              grados=[("NIU típica", "Panal de abeja", ["Subpleural y basal", "Basta para el diagnóstico"]),
                      ("NIU probable", "Reticulación sin panal", ["Bronquiectasias de tracción"]),
                      ("Indeterminado", "Hallazgos poco claros", ["Discutir en equipo"]),
                      ("Otro diagnóstico", "Vidrio esmerilado, quistes", ["Buscar otra enfermedad"])],
              caso=0, porque=[("Panal de abeja en la imagen", True), ("Autoanticuerpos negativos: sin colagenopatía", True)],
              conducta="Antifibróticos, oxígeno, rehabilitación y evaluar trasplante."),
  banda=B("TC real de neumonía intersticial usual", P("uip_tc.jpg", 340, 226, [
            ("flechas", [(0.12, 0.75), (0.86, 0.7)], 0.5, 0.92, "panal de abeja\nsubpleural")],
          credito="Yale Rosen" + CC + "CC BY-SA 2.0"),
          [("Panal de abeja", "Quistes pequeños apilados en hileras bajo la pleura."),
           ("Subpleural y basal", "Predomina en la periferia y las bases de los pulmones."),
           ("Bronquiectasias de tracción", "La fibrosis tira de los bronquios y los dilata."),
           ("Sin vidrio esmerilado", "Si predomina, pensar en otra enfermedad.")],
          pie="TC de otro paciente.", ans=0))

# CAR-023 · Miocardiopatía dilatada alcohólica · TARJETAS
S("tarjetas", "CAR-023", "Alcohol por 20 años e insuficiencia cardiaca descompensada: miocardiopatía dilatada",
  "Miocardiopatías · miocardiopatía alcohólica",
  ("Miocardiopatía dilatada alcohólica", ["El alcohol es tóxico para el miocardio: el ventrículo se dilata y pierde fuerza.",
                                          "Suele requerir más de 80 g de alcohol al día por más de 5 años."]),
  ("Varón de 45 años", ["Consumo crónico de alcohol por 20 años.", "Insuficiencia cardiaca descompensada."]),
  ["Dejar el alcohol por completo: la función puede recuperarse.",
   "Tratamiento de la IC con FE reducida: IECA/ARNI, betabloqueador, antagonista mineralocorticoide e iSGLT2.",
   "Ecocardiograma: VI dilatado con FE baja; descartar isquemia y otras causas."],
  ESC + ", miocardiopatías (2023); " + ESC + ", insuficiencia cardiaca (2021, act. 2023).",
  op=("¿Tipo?", ["No: es genética, pared gruesa", "Sí: el alcohol dilata el ventrículo", "No: amiloidosis, sarcoidosis",
                 "No: viral o autoinmune", "No: genética, ventrículo derecho"]),
  d=dict(rotulo="Miocardiopatías (ESC 2023): ¿cuál?", ans=0,
         cards=[dict(titulo="Dilatada", datos=[("Ventrículo", "Grande", True), ("FE", "Baja", True), ("Causa", "Alcohol, genética", True)],
                     pie="Este caso."),
                dict(titulo="Hipertrófica", datos=[("Pared", "Gruesa", False), ("FE", "Normal o alta", False), ("Causa", "Genética", False)],
                     pie="Muerte súbita."),
                dict(titulo="Restrictiva", datos=[("Llenado", "Rígido", False), ("FE", "Normal", False), ("Causa", "Amiloidosis", False)],
                     pie="Aurículas grandes."),
                dict(titulo="Arritmogénica", datos=[("Lado", "Derecho", False), ("Tejido", "Grasa y fibrosis", False), ("Riesgo", "Arritmias", False)],
                     pie="Jóvenes.")]))

# PED-051 · Maltrato infantil · ÁRBOL + señales de alarma
S("arbol", "PED-051", "Niño desnutrido con fractura, relato que no explica la lesión y cicatrices antiguas: sospechar maltrato infantil",
  "Pediatría social · maltrato infantil",
  ("Maltrato infantil", ["Físico, sexual, psicológico o por negligencia (la desnutrición puede ser su señal).",
                         "Sospechar cuando la historia no explica la lesión o hay lesiones de distinta antigüedad."]),
  ("Niño de 4 años, desnutrido", ["Dolor en el brazo; la madre dice que se golpeó jugando.",
                                  "Aumento de volumen y limitación; cicatrices antiguas en las extremidades; Rx: fractura en tallo verde."]),
  ["Atender la lesión y hospitalizar para protegerlo si hay riesgo.",
   "Registrar todo con detalle; en menores de 2 años, serie ósea completa.",
   "Denunciar ante la fiscalía, la policía o la DEMUNA: es obligación del personal de salud."],
  AAP + ", evaluación del maltrato físico (2015); Ley n.º 30364; Código de los Niños y Adolescentes; " + MINSA + ".",
  op=("¿Sospecha?", ["Sí: relato poco creíble + cicatrices", "No: no explica las cicatrices", "No: escleras azules, fracturas repetidas",
                     "No: es del adulto", "No: deformidades, no cicatrices"]),
  arbol=Q("Lesión en un niño: ¿la historia la explica?", [
      L("No: cicatrices antiguas y desnutrición (este caso)", "MALTRATO INFANTIL", ["Proteger y hospitalizar", "Denunciar"], path=True),
      L("Sí, coherente", "Lesión accidental", ["Tratar y educar"])], path=True),
  triada=TR([("Relato que no explica la lesión", "«Se golpeó jugando»", True), ("Lesiones de distinta antigüedad", "Cicatrices antiguas", True),
             ("Desnutrición o descuido", "Desnutrido", True), ("Demora en consultar", "No se informa", False)],
            [("Señales de alarma de maltrato", 0, 3)],
            "Tres señales presentes: obligación de proteger y denunciar.", rotulo="Señales de alarma"))

# INF-020 · LCR bacteriano · TARJETAS
S("tarjetas", "INF-020", "LCR con glucosa 40, proteínas 300 y 5000 leucocitos con 60 % de polimorfonucleares: meningitis bacteriana",
  "Infecciones del sistema nervioso · líquido cefalorraquídeo",
  ("Interpretación del LCR", ["Bacteriana: muchos neutrófilos, glucosa baja, proteínas altas.",
                              "Viral: linfocitos, glucosa normal; tuberculosa: linfocitos, glucosa muy baja, proteínas muy altas."]),
  ("Resultado de LCR", ["Glucosa 40 mg/dL; proteínas 300 mg/dL.", "Leucocitos 5000/mm³ con 60 % de polimorfonucleares."]),
  ["Glucosa LCR/sangre < 0,4 apoya bacteriana.",
   "Tratamiento empírico ya: ceftriaxona (± vancomicina) y dexametasona antes o con la primera dosis.",
   "Gram y cultivo del LCR, hemocultivos; PCR múltiple si está disponible."],
  "ESCMID, meningitis bacteriana (2016); NICE NG240 (2024); " + HARRISON + ".",
  op=("¿Tipo?", ["No: linfocitos, glucosa normal", "Sí: PMN + glucosa baja + proteínas altas", "No: linfocitos, tinta china",
                 "No: linfocitos, curso subagudo", "No: eosinófilos"]),
  d=dict(rotulo="¿Qué dice el LCR?", ans=0,
         cards=[dict(titulo="Bacteriana", datos=[("Células", "Miles, neutrófilos", True), ("Glucosa", "Baja", True), ("Proteínas", "Muy altas", True)],
                     pie="Este caso."),
                dict(titulo="Viral", datos=[("Células", "Cientos, linfocitos", False), ("Glucosa", "Normal", False), ("Proteínas", "Normales o poco altas", False)],
                     pie="Soporte, aciclovir si herpes."),
                dict(titulo="Tuberculosa", datos=[("Células", "Cientos, linfocitos", False), ("Glucosa", "Muy baja", False), ("ADA", "Alta", False)],
                     pie="Antituberculosos."),
                dict(titulo="Micótica", datos=[("Células", "Pocas, linfocitos", False), ("Prueba", "Tinta china", False), ("Quién", "VIH", False)],
                     pie="Anfotericina B.")]))

# PED-052 · Atresia esofágica · ÁRBOL + Gross + VACTERL
S("arbol", "PED-052", "Recién nacido con salivación excesiva, dificultad respiratoria y sonda orogástrica que no pasa: radiografía de tórax para confirmar atresia esofágica",
  "Cirugía neonatal · atresia de esófago",
  ("Atresia esofágica", ["El esófago termina en un fondo de saco; casi siempre con fístula traqueoesofágica distal.",
                         "Salivación excesiva, atoros y cianosis al alimentar; la sonda no pasa."]),
  ("Neonato de 1 día", ["Salivación excesiva desde el nacimiento.", "Dificultad respiratoria progresiva; la sonda orogástrica no pasa."]),
  ["Rx de tórax y abdomen con la sonda: se ve enrollada en el saco superior; aire en el estómago = fístula distal.",
   "No dar contraste (riesgo de aspiración); aspirar el saco continuamente y cabecera elevada.",
   "Buscar la asociación VACTERL (ecocardiograma, ecografía renal) antes de la cirugía."],
  NELSON + "; ERNICA, consenso de atresia esofágica (2021).",
  op=("¿Examen?", ["No: innecesaria y lenta", "No: no muestra la anatomía", "No: el contraste se puede aspirar",
                   "Sí: muestra la sonda enrollada", "No: no ve el esófago"]),
  arbol=Q("Salivación excesiva y la sonda no pasa", [
      L("Confirmar (este caso)", "RADIOGRAFÍA DE TÓRAX CON SONDA", ["Sonda enrollada en el saco", "¿Aire en el estómago?"], path=True),
      L("Mientras tanto", "Aspirar el saco", ["Nada por boca", "Cabecera elevada"])], path=True),
  escala=dict(nombre="Clasificación de Gross", que="Tipos de atresia esofágica según la fístula.",
              grados=[("A", "Sin fístula", ["8 %", "Sin aire en el abdomen"]), ("B", "Fístula proximal", ["1 %"]),
                      ("C", "Fístula distal", ["85 %", "Aire en el estómago"]), ("D", "Ambas fístulas", ["1 %"]),
                      ("E", "Fístula en H", ["4 %", "Sin atresia"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Lo más probable es el tipo C (85 %)", True), ("La Rx lo define: aire en el estómago = fístula distal", True)],
              conducta="Rx con sonda, aspiración del saco y cirugía tras estabilizar."),
  triada=TR([("V: vértebras", "Hemivértebras", None), ("A: ano imperforado", "Malformación anorrectal", None), ("C: cardiopatía", "Ecocardiograma", None),
             ("TE: tráquea y esófago", "Esta atresia", None), ("R: riñón", "Ecografía renal", None), ("L: extremidades", "Radio, pulgar", None)],
            [("Asociación VACTERL", 0, 5)],
            "Ante una atresia esofágica, buscar las demás.", rotulo="Asociación con nombre propio"))

# INF-021 · Giardia: trofozoítos · FASES
S("fases", "INF-021", "Diarrea aguda por Giardia: en las heces diarreicas se encuentran trofozoítos",
  "Parasitosis intestinales · giardiasis",
  ("Giardiasis", ["Giardia lamblia (G. intestinalis) se transmite por agua o manos con quistes.",
                  "Diarrea acuosa, distensión, flatulencia; puede dar malabsorción en niños."]),
  ("Preescolar", ["Diarrea aguda.", "Examen de heces confirma Giardia."]),
  ["Heces líquidas (tránsito rápido): trofozoítos; heces formadas: quistes.",
   "Se pide examen seriado (3 muestras) o antígeno en heces.",
   "Tratamiento: metronidazol 5-7 días, tinidazol dosis única o nitazoxanida."],
  CDC + ", DPDx giardiasis (2024); " + NELSON + ".",
  op=("¿Estadío?", ["No: Giardia no pone huevos", "Sí: forma que vive en el intestino", "En heces formadas, no en diarrea",
                    "No: no tiene larvas", "No: es de Taenia solium"]),
  d=dict(rotulo="Ciclo de Giardia lamblia", ans=1,
         fases=[("Ingestión", "Agua o manos", "QUISTE INFECTANTE", ["Resiste el cloro", "Bastan 10 quistes"]),
                ("Duodeno", "Se desenquista", "TROFOZOÍTO", ["Se pega con su disco ventral", "Causa la diarrea", "Este caso: en heces líquidas"]),
                ("Colon", "Heces formadas", "QUISTE", ["Sale al ambiente", "Contagia"])]))
