"""Entrega 1 · tanda 13 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AAP, NICE
from esc28 import DENGUE, HIPERK

CC = " · Wikimedia Commons · "

# PED-053 · Deshidratación grave: plan C · ÁRBOL + clasificación OMS
S("arbol", "PED-053", "Niño con diarrea, pliegue muy lento, llenado capilar lento, ojos hundidos y mucosas muy secas: plan C con solución isotónica",
  "Enfermedad diarreica aguda · deshidratación",
  ("Deshidratación grave (plan C)", ["Se pierde más del 10 % del peso en agua: riesgo de choque.",
                                     "Se repone por vena con solución isotónica, no por boca."]),
  ("Niño de 3 años", ["2 días de diarrea acuosa 6-8 veces al día y vómitos; 38,3 °C, FC 140.",
                      "Pliegue muy lento, llenado capilar lento, mucosas muy secas, ojos hundidos."]),
  ["Plan C (OMS): lactato de Ringer o suero fisiológico 100 mL/kg; en ≥ 12 meses, 30 mL/kg en 30 min y 70 mL/kg en 2 h 30 min.",
   "Reevaluar cada hora; iniciar SRO (5 mL/kg/h) apenas pueda beber.",
   "Zinc 10-14 días y seguir alimentando; nunca soluciones hipertónicas ni ayuno."],
  OMS + ", tratamiento de la diarrea (2005, act. 2024); " + MINSA + ", guía de enfermedad diarreica aguda en niños; " + NELSON + ".",
  op=("¿Tratamiento?", ["Es el plan A, sin deshidratación", "No: empeora la deshidratación", "Es el plan B, algún grado",
                        "Sí: plan C por vena", "No: el ayuno empeora"]),
  arbol=Q("Diarrea: ¿signos de deshidratación grave?", [
      L("Sí: pliegue muy lento, ojos hundidos (este caso)", "PLAN C: ISOTÓNICA EV", ["Ringer o salino 100 mL/kg", "Reevaluar cada hora"], path=True),
      L("Algún grado", "Plan B", ["SRO 75 mL/kg en 4 h"])], path=True),
  escala=dict(nombre="Clasificación de la deshidratación (OMS / AIEPI)", que="Basta con 2 signos para ubicar al niño en una fila.",
              grados=[("Plan A", "Sin deshidratación", ["Sin signos suficientes", "SRO en casa tras cada deposición"]),
                      ("Plan B", "Algún grado", ["Inquieto, ojos hundidos", "Bebe con avidez, pliegue lento", "SRO en el establecimiento"]),
                      ("Plan C", "Grave", ["Letárgico o no puede beber", "Ojos hundidos, pliegue muy lento", "Líquidos EV"])],
              caso=2, porque=[("Pliegue muy lento y ojos hundidos", True), ("Llenado capilar lento: riesgo de choque", True)],
              conducta="Lactato de Ringer o suero fisiológico EV según plan C y reevaluar cada hora."))

# GIN-046 · Hiperémesis grave y autonomía · ÁRBOL + gravedad
S("arbol", "GIN-046", "Gestante con ERC e hiperémesis grave que rechaza el aborto terapéutico: tratar la hiperémesis y la enfermedad de fondo",
  "Hiperémesis gravídica · bioética",
  ("Hiperémesis gravídica y autonomía", ["Vómitos intensos con deshidratación y pérdida de peso > 5 %.",
                                         "La paciente capaz decide: si rechaza el aborto, se le da el mejor tratamiento posible."]),
  ("Gestante de 10 semanas", ["Insuficiencia renal crónica en lista de trasplante.", "Hiperémesis grave; rechaza el aborto terapéutico."]),
  ["Hidratación EV con tiamina antes de la glucosa; antieméticos (doxilamina-piridoxina, ondansetrón, metoclopramida).",
   "Ajustar la diálisis (más frecuente, no suspenderla) y controlar la anemia y la PA.",
   "Su decisión se respeta: no se necesita permiso del esposo ni de los padres."],
  "RCOG Green-top n.º 69, náuseas, vómitos e hiperémesis (2024); " + ACOG + " Practice Bulletin n.º 189 (2018); " + WILLIAMS + ".",
  op=("¿Alternativa?", ["Sí: respeta su autonomía y la trata", "No: vulnera su autonomía", "No: decide ella, es capaz",
                        "No: no trata la causa", "No: la necesita aún más"]),
  arbol=Q("Gestante capaz rechaza el aborto terapéutico", [
      L("Respetar su decisión (este caso)", "TRATAR HIPERÉMESIS Y ERC", ["Hidratación + tiamina", "Antieméticos, ajustar diálisis"], path=True),
      L("Si cambia de opinión", "Reevaluar con ella", ["Información completa"])], path=True),
  escala=dict(nombre="Gravedad de náuseas y vómitos del embarazo (PUQE)", que="El puntaje PUQE suma náuseas, vómitos y arcadas de 24 horas.",
              grados=[("≤ 6", "Leve", ["Dieta, jengibre", "Doxilamina-piridoxina"]), ("7-11", "Moderada", ["Antieméticos orales"]),
                      ("≥ 12", "Grave", ["Hidratación EV + tiamina", "Hospitalizar"])],
              caso=2, porque=[("Hiperémesis descrita como grave", True), ("ERC: menos reserva para la deshidratación", True)],
              conducta="Hospitalizar, hidratación EV con tiamina, antieméticos y diálisis ajustada."))

# PED-054 · Meningitis neonatal · ÁRBOL + momento de la sepsis
S("arbol", "PED-054", "Neonato de 10 días con fiebre, mala succión, somnolencia y fontanela abombada: estudio del LCR",
  "Infecciones neonatales · meningitis",
  ("Meningitis neonatal", ["Signos poco específicos: fiebre o hipotermia, rechazo al alimento, letargia, irritabilidad.",
                           "La fontanela abombada indica presión intracraneal alta."]),
  ("Neonato de 10 días", ["2 días de fiebre, pobre succión y somnolencia.", "38,5 °C, FC 160, irritable, fontanela abombada."]),
  ["Punción lumbar (citoquímico, Gram, cultivo) junto con hemocultivo; si está inestable, antibiótico primero.",
   "Empírico: ampicilina + cefotaxima (o gentamicina); en neonatos se evita la ceftriaxona.",
   "Gérmenes: estreptococo B, E. coli, Listeria; ecografía transfontanelar para complicaciones."],
  NICE + " NG240, meningitis bacteriana (2024); " + AAP + ", Red Book (2024); " + NELSON + ".",
  op=("¿Examen?", ["Sí: confirma la meningitis", "Para complicaciones, no confirma", "Para complicaciones, no confirma",
                   "Se pide, pero no confirma meningitis", "Se pide, pero no confirma meningitis"]),
  arbol=Q("Neonato febril con fontanela abombada: ¿está estable?", [
      L("Sí (este caso)", "PUNCIÓN LUMBAR (LCR)", ["Citoquímico, Gram, cultivo", "Más hemocultivo"], path=True),
      L("No: choque o apnea", "Antibiótico primero", ["Punción al estabilizar"])], path=True),
  escala=dict(nombre="Sepsis neonatal según el momento", orden=False, que="El momento orienta el germen y el antibiótico.",
              grados=[("< 72 horas", "Temprana", ["Canal de parto: estreptococo B, E. coli"]),
                      ("> 72 horas", "Tardía", ["Comunidad u hospital", "Meningitis más frecuente"])],
              caso=1, porque=[("10 días de vida", True), ("Fontanela abombada: compromiso meníngeo", True)],
              conducta="Punción lumbar, hemocultivo y ampicilina + cefotaxima EV."))

# INF-022 · Dengue con signos de alarma · ÁRBOL + signos + clasificación
S("arbol", "INF-022", "Dengue con dolor abdominal intenso, vómitos persistentes, sangrado de mucosas, letargia, hepatomegalia y hematocrito de 50 %: dengue con signos de alarma",
  "Enfermedades metaxénicas · dengue",
  ("Dengue con signos de alarma", ["Aparecen al bajar la fiebre (fase crítica): anuncian la fuga de plasma.",
                                   "Se hospitaliza y se hidrata por vena para evitar el choque."]),
  ("Adulto en zona de dengue", ["5 días de fiebre; dolor abdominal intenso, vómitos persistentes, sangrado de mucosas.",
                                "Menos orina, estado mental alterado, hepatomegalia; hematocrito 50 %."]),
  ["Grupo B2: cristaloides 10 mL/kg en la 1.ª hora y reevaluar; controlar hematocrito y diuresis.",
   "Dengue grave: choque (pulso débil, PA diferencial ≤ 20), sangrado grave o daño grave de órganos (coma, hígado).",
   "«Dengue hemorrágico» es un término antiguo (OMS 1997); hoy se usa la clasificación OPS/OMS 2009."],
  "OPS, guía de dengue, chikungunya y zika (2022); " + MINSA + ", guía de práctica clínica de dengue (2024).",
  op=("¿Cómo se define?", ["Si hay choque o coma, pasa a grave", "Sí: varios signos de alarma", "Término antiguo, ya no se usa",
                           "No es una categoría oficial", "No: tiene varios signos de alarma"]),
  arbol=Q("Dengue: ¿algún signo de alarma?", [
      L("Sí, varios (este caso)", "DENGUE CON SIGNOS DE ALARMA", ["Hospitalizar (grupo B2)", "Cristaloides EV"], path=True),
      L("No", "Dengue sin signos de alarma", ["Grupo A o B1"])], path=True),
  triada=TR([("Dolor abdominal intenso", "Sí", True), ("Vómitos persistentes", "Sí", True), ("Sangrado de mucosas", "Sí", True),
             ("Letargia o irritabilidad", "Estado mental alterado", True), ("Hígado > 2 cm", "Sí", True),
             ("Hematocrito que sube", "50 %", True)],
            [("Signos de alarma (OPS)", 0, 5)],
            "Seis signos de alarma: hospitalizar e hidratar; vigilar el paso a choque.", rotulo="Signos de alarma"),
  escala=DENGUE(1, [("Varios signos de alarma presentes", True),
                    ("Si aparece choque o coma, pasa a dengue grave", False)],
                "Hospitalizar (B2): cristaloides 10 mL/kg/h, hematocrito y diuresis seriados."))

# SP-034 · Atención primaria de salud · TARJETAS
S("tarjetas", "SP-034", "«Asistencia sanitaria esencial, accesible a todos y núcleo del sistema de salud»: atención primaria de salud",
  "Salud pública · atención primaria",
  ("Atención primaria de salud (APS)", ["Definida en Alma-Ata (1978): asistencia esencial, accesible, con participación de la comunidad.",
                                        "Es el núcleo del sistema de salud; Astaná (2018) la renovó."]),
  ("Pregunta de concepto", ["«Núcleo del sistema de salud, asistencia sanitaria esencial y accesible a todos».", "¿Qué concepto es?"]),
  ["APS no es solo el primer nivel: es una estrategia que abarca promoción, prevención, curación y rehabilitación.",
   "«Salud para todos en el año 2000» fue la meta que se propuso alcanzar con la APS.",
   "En el Perú se aplica con el modelo de cuidado integral por curso de vida (MCI)."],
  OMS + ", Declaración de Alma-Ata (1978) y Declaración de Astaná (2018); " + MINSA + ", modelo de cuidado integral de salud (2020).",
  op=("¿Concepto?", ["Sí: definición de Alma-Ata", "No: concepto reducido", "Modelo de atención, no la definición", "Es la meta, no el concepto",
                     "Es una especialidad"]),
  d=dict(rotulo="Conceptos que se confunden", ans=0,
         cards=[dict(titulo="APS", datos=[("Origen", "Alma-Ata 1978", True), ("Es", "Estrategia", True), ("Idea", "Núcleo del sistema", True)],
                     pie="Este caso."),
                dict(titulo="Salud para todos 2000", datos=[("Es", "Una meta", False), ("Medio", "La APS", False), ("Año", "Fijado en 1977", False)],
                     pie="Objetivo."),
                dict(titulo="Atención integral", datos=[("Es", "Modelo", False), ("Perú", "MAIS / MCI", False), ("Idea", "Persona y familia", False)],
                     pie="Aplica la APS."),
                dict(titulo="Medicina familiar", datos=[("Es", "Especialidad", False), ("Lugar", "Primer nivel", False), ("Idea", "Médico de cabecera", False)],
                     pie="Un actor.")]))

# SP-035 · Salud mental en la pandemia · RADIAL
S("radial", "SP-035", "Autocuidado y promoción en el primer nivel durante la pandemia: incorporar el cuidado de la salud mental",
  "Salud mental · promoción en el primer nivel",
  ("Salud mental en la pandemia", ["El aislamiento, el duelo y la incertidumbre aumentaron la ansiedad y la depresión.",
                                   "El primer nivel debe promover autocuidado y detectar a tiempo."]),
  ("Pregunta de concepto", ["Autocuidado, promoción y prevención en el primer nivel.", "Contexto de la pandemia de COVID-19."]),
  ["Tamizaje breve (PHQ-9, GAD-7) y primeros auxilios psicológicos en el primer nivel.",
   "Derivar a los centros de salud mental comunitaria (CSMC) los casos que lo necesiten.",
   "Las demás opciones no son promoción ni autocuidado."],
  MINSA + ", guía técnica para el cuidado de la salud mental en COVID-19 (RM 180-2020); " + OMS + ", informe mundial de salud mental (2022).",
  op=("¿Intervención?", ["No: es atención de enfermos", "No: no es una acción de salud", "Sí: promoción y prevención",
                         "No: es investigación", "No: reduce el acceso"]),
  d=dict(rotulo="Salud mental en el primer nivel", centro="CUIDADO DE LA SALUD MENTAL", centro_sub="en el primer nivel", ans=0,
         items=[("PROMOCIÓN", ["Rutinas, sueño, actividad física"]), ("AUTOCUIDADO", ["Limitar noticias, mantener vínculos"]),
                ("TAMIZAJE", ["PHQ-9, GAD-7"]), ("APOYO", ["Primeros auxilios psicológicos"]),
                ("DERIVACIÓN", ["Centro de salud mental comunitario"])],
         ruta=["Detectar", "Acompañar", "Derivar si hace falta", "Seguimiento"]))

# OFT-008 · Otitis media aguda · ÁRBOL + otoscopia real
S("arbol", "OFT-008", "Preescolar con otalgia aguda, tímpano abombado y otorrea purulenta: otitis media aguda, amoxicilina",
  "Otorrinolaringología · otitis media aguda", esp="OTORRINOLARINGOLOGÍA",
  tema=("Otitis media aguda (OMA)", ["Infección del oído medio: neumococo, H. influenzae, Moraxella.",
                                     "Diagnóstico: tímpano abombado u otorrea nueva, con síntomas agudos."]),
  caso=("Preescolar", ["Otalgia de inicio agudo.", "Secreción purulenta en el conducto; tímpano abombado."]),
  perlas=["Amoxicilina 80-90 mg/kg/día; con otorrea se trata siempre con antibiótico.",
          "Si recibió amoxicilina en el último mes o hay conjuntivitis: amoxicilina-clavulánico.",
          "Sin otorrea, mayor de 2 años y leve: se puede observar 48-72 h con analgesia."],
  fuente=AAP + ", otitis media aguda (2013, reafirmada); " + NICE + " NG91 (2018, act. 2022).",
  op=("¿Primera elección?", ["Sí: cubre neumococo", "No: mucha resistencia", "No: es EV, no hace falta", "No: no cubre H. influenzae",
                             "No: no se usa por vía oral en niños"]),
  arbol=Q("OMA: ¿otorrea o enfermedad grave?", [
      L("Sí: otorrea purulenta (este caso)", "AMOXICILINA", ["80-90 mg/kg/día", "Analgesia"], path=True),
      L("No, leve y > 2 años", "Observar 48-72 h", ["Analgesia, control"])], path=True),
  banda=B("Otoscopia real de otitis media aguda", P("oma.jpg", 260, 260, [
            ("circulo", 0.6, 0.38, 0.2, "tímpano rojo,\nopaco y abombado", 0.5, 0.9)],
          credito="B. Welleschik" + CC + "CC BY-SA 3.0"),
          [("Tímpano rojo y abombado", "El pus empuja la membrana hacia afuera: es el signo que confirma la OMA."),
           ("Sin reflejo luminoso", "El tímpano sano es gris perla y brillante; aquí está opaco."),
           ("Si se perfora: otorrea", "Sale pus al conducto y el dolor suele aliviar."),
           ("Si no mejora en 48-72 h", "Revisar el diagnóstico o cambiar a amoxicilina-clavulánico.")],
          pie="Otoscopia de otro paciente.", ans=0))

# PED-055 · Rubéola congénita · TARJETAS + tríada de Gregg
S("tarjetas", "PED-055", "Lactante cuya madre tuvo fiebre con exantema a las 10 semanas de gestación: rubéola congénita, buscar catarata",
  "Infecciones congénitas · rubéola",
  ("Síndrome de rubéola congénita", ["Más grave si la madre se infecta antes de las 12 semanas (cuando se forman ojos y corazón).",
                                     "Tríada de Gregg: catarata, sordera neurosensorial y cardiopatía (ductus arterioso)."]),
  ("Lactante de 2 meses", ["Madre adolescente con fiebre y exantema a las 10 semanas.", "¿Qué se espera encontrar?"]),
  ["La catarata se ve al nacer (leucocoria, reflejo rojo ausente); la sordera es la más frecuente pero se detecta después.",
   "Confirmar con IgM antirrubéola o PCR; el bebé elimina virus meses: aislarlo de gestantes.",
   "Prevención: vacuna SPR; el Perú y las Américas eliminaron la rubéola endémica, se vigilan casos importados."],
  OMS + ", rubéola (2024); " + CDC + ", Pink Book (2024); " + NELSON + ".",
  op=("¿Hallazgo esperado?", ["Sí: se forma en el 1.er trimestre", "También, pero se detecta más tarde", "No: da microcefalia",
                              "Es de toxoplasma o CMV", "Es de toxoplasma"]),
  d=dict(rotulo="Infección congénita: ¿qué hallazgo?", ans=0,
         cards=[dict(titulo="Rubéola", datos=[("Ojo", "Catarata", True), ("Oído", "Sordera", True), ("Corazón", "Ductus", True)],
                     pie="Este caso."),
                dict(titulo="Toxoplasmosis", datos=[("Ojo", "Coriorretinitis", False), ("Cabeza", "Hidrocefalia", False),
                                                    ("Calcificaciones", "Difusas", False)],
                     pie="Gato, carne cruda."),
                dict(titulo="Citomegalovirus", datos=[("Cabeza", "Microcefalia", False), ("Calcificaciones", "Periventriculares", False),
                                                     ("Oído", "Sordera", False)],
                     pie="La más común."),
                dict(titulo="Sífilis", datos=[("Nariz", "Rinitis", False), ("Piel", "Pénfigo palmoplantar", False), ("Hueso", "Periostitis", False)],
                     pie="Penicilina.")]),
  triada=TR([("Catarata", "Leucocoria", None), ("Sordera neurosensorial", "La más frecuente", None), ("Cardiopatía", "Ductus arterioso", None)],
            [("Tríada de Gregg", 0, 2)],
            "Con infección en el primer trimestre, buscar las tres.", rotulo="Tríada con nombre propio"))

# SP-036 · Categorización: componente de organización · TARJETAS
S("tarjetas", "SP-036", "El registro y la categorización de los establecimientos de salud pertenecen al componente de organización del MAIS-BFC",
  "Gestión en salud · modelo de atención integral",
  ("Modelo de atención integral (MAIS-BFC)", ["Tiene cuatro componentes: organización, prestación, gestión y financiamiento.",
                                              "Organización: cómo se ordena la oferta (categorías, redes, territorio)."]),
  ("Pregunta de concepto", ["Registro y categorización de los establecimientos.", "¿Qué componente del modelo es?"]),
  ["Categorías: I-1 a I-4 (primer nivel), II-1 a II-E, III-1 a III-E (norma técnica de categorías).",
   "El registro es el RENIPRESS (SUSALUD).",
   "Prestación = paquetes de cuidado; gestión = planificar y dirigir; financiamiento = de dónde sale el dinero (SIS)."],
  MINSA + ", MAIS-BFC (2011); NTS n.º 021-MINSA, categorías de establecimientos de salud (2011).",
  op=("¿Componente?", ["No: de dónde sale el dinero", "No: planificar y dirigir", "No: los servicios que se dan", "Sí: ordena la oferta",
                       "No: no es un componente del modelo"]),
  d=dict(rotulo="Componentes del MAIS-BFC", ans=0,
         cards=[dict(titulo="Organización", datos=[("Qué", "Ordena la oferta", True), ("Ejemplo", "Categorizar", True), ("También", "Redes, sectores", True)],
                     pie="Este caso."),
                dict(titulo="Prestación", datos=[("Qué", "Los servicios", False), ("Ejemplo", "Paquetes de cuidado", False), ("Para", "Persona y familia", False)],
                     pie="Lo que se da."),
                dict(titulo="Gestión", datos=[("Qué", "Dirigir", False), ("Ejemplo", "Planificar, evaluar", False), ("Para", "Recursos", False)],
                     pie="Cómo se maneja."),
                dict(titulo="Financiamiento", datos=[("Qué", "El dinero", False), ("Ejemplo", "SIS", False), ("Para", "Sostener", False)],
                     pie="Quién paga.")]))

# END-008 · Diabetes: glucemia en ayunas · ÁRBOL + criterios ADA
S("arbol", "END-008", "Obeso con poliuria, nicturia, polidipsia y padres diabéticos: glucemia en ayunas en el primer nivel",
  "Diabetes mellitus · diagnóstico",
  ("Diagnóstico de diabetes", ["Glucemia en ayunas ≥ 126, HbA1c ≥ 6,5 %, glucosa 2 h en la PTOG ≥ 200, o glucosa al azar ≥ 200 con síntomas.",
                               "Sin síntomas hace falta confirmar con una segunda prueba."]),
  ("Varón de 55 años", ["1,60 m y 80 kg (IMC 31); poliuria, nicturia y polidipsia.", "Ambos padres diabéticos."]),
  ["En el primer nivel: glucemia en ayunas (o glucosa al azar si hay síntomas).",
   "La glucosa en orina, el péptido C y la insulinemia no sirven para diagnosticar.",
   "Confirmada: metformina, cambios de estilo de vida y, con riesgo cardiovascular o renal, iSGLT2 o arGLP-1."],
  ADA + "; " + MINSA + ", guía de diabetes tipo 2 en el primer nivel.",
  op=("¿Procedimiento?", ["Sí: simple, barato y diagnóstico", "No: no diagnostica", "No: no es criterio diagnóstico",
                          "No: distingue tipos, no diagnostica", "La PTOG sirve; la insulinemia sobra"], {4: "PTOG con insulinemia"}),
  arbol=Q("Síntomas de diabetes: ¿qué pedir en el primer nivel?", [
      L("Glucemia en ayunas (este caso)", "≥ 126 mg/dL = DIABETES", ["Con síntomas, una basta", "O glucosa al azar ≥ 200"], path=True),
      L("Si sale 100-125", "Prediabetes", ["HbA1c o PTOG"])], path=True),
  escala=dict(nombre="Glucemia en ayunas (ADA 2026)", orden=True, que="Ayuno de al menos 8 horas.",
              grados=[("< 100 mg/dL", "Normal", ["Repetir según riesgo"]), ("100-125 mg/dL", "Prediabetes", ["Estilo de vida", "Control anual"]),
                      ("≥ 126 mg/dL", "Diabetes", ["Confirmar si no hay síntomas"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Con síntomas clásicos, un solo valor ≥ 126 basta", True), ("Obesidad y padres diabéticos: riesgo alto", True)],
              conducta="Glucemia en ayunas; si es ≥ 126, iniciar tratamiento y educación."))

# NEF-021 · Hiperplasia benigna de próstata · ÁRBOL + IPSS
S("arbol", "NEF-021", "Hiperplasia benigna de próstata sintomática: alfabloqueadores e inhibidores de la 5-alfa reductasa",
  "Urología · hiperplasia benigna de próstata",
  ("Hiperplasia benigna de próstata (HBP)", ["La próstata crece con la edad y obstruye la salida de la orina.",
                                             "Chorro débil, pujo, goteo, nicturia, urgencia."]),
  ("Pregunta de concepto", ["HBP con síntomas.", "¿Fármacos de primera línea?"]),
  ["Alfabloqueador (tamsulosina, alfuzosina): alivia en días; efecto: hipotensión ortostática.",
   "Inhibidor de la 5-alfa reductasa (finasterida, dutasterida): achica la próstata en meses; útil si > 40 mL.",
   "Combinación si la próstata es grande; cirugía (RTU) si hay retención, cálculos, infecciones o falla renal."],
  "EAU, síntomas urinarios bajos en el varón (2025); AUA, HBP (2023).",
  op=("¿Primera línea?", ["Sí: relajan y reducen la próstata", "No: los anticolinérgicos pueden causar retención", "No: no actúan en la próstata",
                          "No: no tienen papel", "No: empeoran los síntomas"], {0: "Alfabloqueador / inhibidor de 5α-reductasa"}),
  arbol=Q("HBP con síntomas molestos: ¿próstata grande (> 40 mL)?", [
      L("No", "Alfabloqueador", ["Tamsulosina"]),
      L("Sí", "Alfabloqueador + inhibidor de 5α-reductasa", ["Finasterida o dutasterida"], path=True)], path=True),
  escala=dict(nombre="Puntaje internacional de síntomas prostáticos (IPSS)", orden=True, que="7 preguntas, de 0 a 35 puntos.",
              grados=[("0-7", "Leve", ["Vigilancia y consejos"]), ("8-19", "Moderado", ["Fármacos"]), ("20-35", "Grave", ["Fármacos o cirugía"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("«Sintomática»: suele ser IPSS moderado o grave", True), ("Sirve también para ver cómo mejora con el tratamiento", True)],
              conducta="Alfabloqueador; agregar inhibidor de 5α-reductasa si la próstata es grande."))

# END-009 · Insuficiencia suprarrenal por retiro de corticoides · ÁRBOL + tipo
S("arbol", "END-009", "Choque refractario a líquidos con hiponatremia e hipoglucemia tras suspender 20 días de corticoides: hidrocortisona",
  "Glándulas suprarrenales · insuficiencia suprarrenal",
  ("Insuficiencia suprarrenal por corticoides", ["Los corticoides largos frenan el eje: al suspenderlos, la suprarrenal no responde.",
                                                 "Crisis: hipotensión que no cede con líquidos, hipoglucemia, hiponatremia."]),
  ("Varón de 60 años", ["Corticoides 20 días por neumonía COVID-19; 7 días después anorexia, astenia, dolor abdominal, náuseas.",
                        "PA 80/50 pese a 2 L de salino; Na 130, glucosa 60, K 3,5."]),
  ["Hidrocortisona 100 mg EV en bolo, luego 200 mg/día; salino y glucosa.",
   "K⁺ normal: la aldosterona se conserva (es secundaria/terciaria), por eso no hay hiperpotasemia.",
   "Retirar los corticoides de forma gradual y dar dosis de estrés ante enfermedad o cirugía."],
  "ESE/Endocrine Society, insuficiencia suprarrenal por glucocorticoides (2024); " + HARRISON + ".",
  op=("¿Tratamiento?", ["No sin corregir la causa", "No: no hay coagulopatía", "Sí: crisis suprarrenal", "No: no hay sangrado",
                        "Útil si hay sepsis; aquí falta cortisol"]),
  arbol=Q("Choque que no responde a líquidos: ¿corticoides recientes, Na y glucosa bajos?", [
      L("Sí (este caso)", "HIDROCORTISONA EV", ["100 mg en bolo", "Salino y glucosa"], path=True),
      L("No", "Buscar otra causa", ["Sepsis, sangrado, corazón"])], path=True),
  escala=dict(nombre="Tipos de insuficiencia suprarrenal", orden=False, que="Según dónde falla el eje.",
              grados=[("Primaria (Addison)", "Falla la glándula", ["ACTH alta, piel oscura", "K⁺ alto: falta aldosterona"]),
                      ("Secundaria o terciaria", "Falla hipófisis o hipotálamo", ["Corticoides exógenos (la más común)", "K⁺ normal, sin hiperpigmentación"])],
              caso=1, porque=[("Corticoides por 20 días", True), ("K⁺ normal (3,5)", True)],
              conducta="Hidrocortisona EV ya; luego dosis de mantenimiento con retiro gradual."))

# SP-037 · Adulto mayor frágil · TARJETAS
S("tarjetas", "SP-037", "Adulto mayor de 85 años con deterioro cognitivo leve, dependencia parcial, caídas y depresión: adulto mayor frágil",
  "Salud del adulto mayor · clasificación MINSA",
  ("Clasificación de la persona adulta mayor (MINSA)", ["Activa saludable, enferma, frágil o geriátrica compleja.",
                                                        "Frágil: tiene reservas bajas; un evento menor puede llevarla a la dependencia."]),
  ("Varón de 85 años", ["Deterioro cognitivo leve y dependencia parcial.", "Dos caídas en el último año; síntomas depresivos."]),
  ["Criterios de fragilidad (MINSA): ≥ 80 años, caídas, deterioro cognitivo, depresión, dependencia parcial, polifarmacia, etc.",
   "Valoración geriátrica integral: funcional (Katz, Lawton), mental (Pfeiffer), social y nutricional.",
   "Ejercicio de fuerza y equilibrio, revisar fármacos y prevenir caídas."],
  MINSA + ", norma técnica de atención integral de las personas adultas mayores; " + OMS + ", atención integrada para personas mayores (ICOPE, 2024).",
  op=("¿Cómo se le considera?", ["Sí: caídas, deterioro y dependencia parcial", "No: tiene más que una enfermedad", "No: la dependencia no es total",
                                 "No: depende en parte", "No: tiene problemas"]),
  d=dict(rotulo="Clasificación de la persona adulta mayor", ans=0,
         cards=[dict(titulo="Frágil", datos=[("Edad", "≥ 80", True), ("Caídas", "Sí", True), ("Dependencia", "Parcial", True)],
                     pie="Este caso."),
                dict(titulo="Activa saludable", datos=[("Enfermedad", "No", False), ("Dependencia", "No", False), ("Meta", "Prevenir", False)],
                     pie="Promoción."),
                dict(titulo="Enferma", datos=[("Enfermedad", "Aguda o crónica", False), ("Dependencia", "No", False), ("Fragilidad", "No", False)],
                     pie="Tratar."),
                dict(titulo="Geriátrica compleja", datos=[("Enfermedades", "≥ 3 crónicas", False), ("Dependencia", "Total", False),
                                                         ("Otros", "Terminal o demencia grave", False)],
                     pie="Equipo geriátrico.")]))

# GAS-015 · Dispepsia funcional · TARJETAS + Roma IV
S("tarjetas", "GAS-015", "Dolor epigástrico, náuseas y llenura de 3 meses con laboratorio y endoscopia normales: dispepsia funcional",
  "Trastornos funcionales digestivos · dispepsia",
  ("Dispepsia funcional", ["Síntomas del estómago sin lesión que los explique en la endoscopia.",
                           "Dos tipos (Roma IV): distrés posprandial (llenura, saciedad) y dolor epigástrico."]),
  ("Varón de 30 años", ["3 meses de dolor epigástrico, náuseas y llenura.", "Laboratorio y endoscopia alta normales."]),
  ["Buscar y tratar H. pylori (prueba de aliento o antígeno en heces).",
   "IBP para el dolor; procinético para la llenura; neuromodulador (amitriptilina) si no responde.",
   "Signos de alarma (pérdida de peso, sangrado, anemia, > 60 años): endoscopia."],
  "Roma IV (2016); BSG, dispepsia funcional (2022); Maastricht VI/Florencia (2022).",
  op=("¿Diagnóstico?", ["Sí: síntomas con endoscopia normal", "No: la endoscopia es normal", "No: no hay úlcera", "No: sin pirosis ni regurgitación",
                        "No: requiere vaciamiento lento demostrado"]),
  d=dict(rotulo="Dolor epigástrico: ¿cuál?", ans=0,
         cards=[dict(titulo="Dispepsia funcional", datos=[("Endoscopia", "Normal", True), ("Síntoma", "Llenura, dolor", True), ("Tiempo", "Meses", True)],
                     pie="Este caso."),
                dict(titulo="Úlcera péptica", datos=[("Endoscopia", "Úlcera", False), ("Causa", "H. pylori, AINE", False), ("Riesgo", "Sangrado", False)],
                     pie="IBP + erradicar."),
                dict(titulo="ERGE", datos=[("Síntoma", "Pirosis", False), ("También", "Regurgitación", False), ("Endoscopia", "Esofagitis o normal", False)],
                     pie="IBP."),
                dict(titulo="Gastroparesia", datos=[("Síntoma", "Vómitos", False), ("Quién", "Diabéticos", False), ("Prueba", "Vaciamiento lento", False)],
                     pie="Procinéticos.")]),
  triada=TR([("Llenura o saciedad precoz", "Llenura", True), ("Dolor o ardor epigástrico", "Dolor", True),
             ("Endoscopia sin lesión", "Normal", True), ("Inicio ≥ 6 meses antes", "3 meses", False)],
            [("Criterios de Roma IV", 0, 3)],
            "Cuadro típico; para cumplir Roma IV estricto falta el tiempo de inicio.", rotulo="Criterios con nombre propio"))

# GAS-016 · Hemorragia por várices · ÁRBOL + Child-Pugh
S("arbol", "GAS-016", "Cirrótico estable con hematemesis y várices esofágicas sangrantes en la endoscopia: ligadura",
  "Hipertensión portal · hemorragia variceal",
  ("Hemorragia por várices esofágicas", ["La hipertensión portal dilata las venas del esófago, que se rompen.",
                                         "Mortalidad alta: vasoactivo, antibiótico y endoscopia en 12 horas."]),
  ("Adulto cirrótico", ["Hematemesis; hemodinámicamente estable.", "Endoscopia: várices esofágicas con sangrado."]),
  ["Antes de la endoscopia: octreotide o terlipresina, ceftriaxona profiláctica y transfusión restrictiva (Hb 7-8).",
   "Ligadura con bandas: tratamiento endoscópico de elección (mejor que escleroterapia).",
   "Child C (< 14) o B con sangrado activo: TIPS preventivo en 72 h (Baveno VII); luego betabloqueador + ligaduras."],
  "Baveno VII (2022); AASLD, hipertensión portal (2024).",
  op=("¿Tratamiento?", ["Sí: detiene el sangrado de la várice", "Solo si la endoscopia falla", "Se da junto, pero no basta",
                        "No: no es la causa", "Menos eficaz y más complicaciones"]),
  arbol=Q("Cirrótico con hematemesis: vasoactivo + antibiótico, luego endoscopia", [
      L("Várices esofágicas (este caso)", "LIGADURA CON BANDAS", ["En las primeras 12 h"], path=True),
      L("Si no se controla", "Balón o TIPS de rescate", ["Sengstaken como puente"])], path=True),
  escala=dict(nombre="Clasificación de Child-Pugh", orden=True, que="Bilirrubina, albúmina, INR, ascitis y encefalopatía (5 a 15 puntos).",
              grados=[("A (5-6)", "Compensada", ["Buen pronóstico"]), ("B (7-9)", "Moderada", ["TIPS si sangra activo"]),
                      ("C (10-15)", "Grave", ["TIPS preventivo si < 14", "Valorar trasplante"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Faltan bilirrubina, albúmina, INR y ascitis", False), ("El grado decide si poner TIPS preventivo", True)],
              conducta="Vasoactivo, ceftriaxona y ligadura en 12 h; Child-Pugh para el TIPS."))

# SP-038 · Minimización de costos · TARJETAS
S("tarjetas", "SP-038", "Si las alternativas tienen el mismo efecto, solo se comparan costos: análisis de minimización de costos",
  "Economía de la salud · evaluación económica",
  ("Evaluaciones económicas en salud", ["Comparan costos y resultados de dos o más alternativas.",
                                        "Se diferencian por cómo miden el resultado."]),
  ("Pregunta de concepto", ["No hay diferencias en los efectos de las alternativas.", "¿Qué evaluación usar?"]),
  ["Efectos iguales: minimización de costos (se elige la más barata).",
   "Costo-efectividad: resultado en unidades naturales (casos evitados); costo-utilidad: AVAC; costo-beneficio: dinero.",
   "La «estandarización de costos» no es un tipo de evaluación económica."],
  "Drummond et al., Methods for the Economic Evaluation of Health Care Programmes 4.ª ed. (2015).",
  op=("¿Evaluación?", ["No existe ese tipo", "No: mide en AVAC", "No: mide en unidades naturales", "Sí: efectos iguales, solo costos",
                       "No: mide todo en dinero"]),
  d=dict(rotulo="¿Cómo se mide el resultado?", ans=0,
         cards=[dict(titulo="Minimización de costos", datos=[("Efecto", "Igual", True), ("Compara", "Solo costos", True), ("Elige", "La más barata", True)],
                     pie="Este caso."),
                dict(titulo="Costo-efectividad", datos=[("Efecto", "Distinto", False), ("Unidad", "Casos, años de vida", False),
                                                        ("Da", "Costo por unidad", False)],
                     pie="La más usada."),
                dict(titulo="Costo-utilidad", datos=[("Efecto", "Distinto", False), ("Unidad", "AVAC", False), ("Incluye", "Calidad de vida", False)],
                     pie="Variante de la anterior."),
                dict(titulo="Costo-beneficio", datos=[("Efecto", "En dinero", False), ("Da", "Beneficio neto", False), ("Difícil", "Poner precio a la vida", False)],
                     pie="Todo en soles.")]))

# NEU-011 · Silicosis · TARJETAS
S("tarjetas", "NEU-011", "Minero con tos crónica, disnea, nódulos apicales y adenopatías hiliares con calcificación en «cáscara de huevo»: silicosis",
  "Enfermedades pulmonares ocupacionales · neumoconiosis",
  ("Silicosis", ["Inhalación de sílice cristalina (minería, canteras, arenado): nódulos fibrosos en los lóbulos superiores.",
                 "Calcificación ganglionar en «cáscara de huevo»; riesgo alto de tuberculosis."]),
  ("Minero de 43 años", ["Tos crónica, expectoración mucoide y disnea a medianos esfuerzos.",
                         "Rx: nódulos apicales y adenopatías hiliares calcificadas en «cáscara de huevo»."]),
  ["No tiene tratamiento curativo: retirar de la exposición y prevenir (protección respiratoria, humedecer).",
   "Descartar tuberculosis (silicotuberculosis) y tratar la infección latente.",
   "Aumenta el riesgo de cáncer de pulmón y de enfermedades autoinmunes."],
  "OIT, clasificación internacional de radiografías de neumoconiosis (2022); ATS, enfermedades ocupacionales; " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: bario, benigna, sin fibrosis", "Sí: minero + cáscara de huevo", "No: estaño, benigna",
                        "No: algodón, asma ocupacional", "No: bases y placas pleurales"]),
  d=dict(rotulo="Neumoconiosis: ¿cuál?", ans=0,
         cards=[dict(titulo="Silicosis", datos=[("Exposición", "Minería, sílice", True), ("Lugar", "Lóbulos superiores", True),
                                                ("Signo", "Cáscara de huevo", True)],
                     pie="Este caso."),
                dict(titulo="Asbestosis", datos=[("Exposición", "Asbesto", False), ("Lugar", "Bases", False), ("Signo", "Placas pleurales", False)],
                     pie="Mesotelioma."),
                dict(titulo="Neumoconiosis del carbón", datos=[("Exposición", "Carbón", False), ("Lugar", "Superiores", False), ("Signo", "Fibrosis masiva", False)],
                     pie="Pulmón negro."),
                dict(titulo="Bisinosis", datos=[("Exposición", "Algodón", False), ("Síntoma", "Opresión el lunes", False), ("Tipo", "Asma ocupacional", False)],
                     pie="Reversible al inicio.")]))

# OFT-009 · Rinitis alérgica · TARJETAS + estigmas atópicos
S("tarjetas", "OFT-009", "Escolar con estornudos, rinorrea, prurito nasal, ojeras, respiración bucal, pliegue nasal transverso e IgE alta: rinitis alérgica",
  "Otorrinolaringología · rinitis", esp="OTORRINOLARINGOLOGÍA",
  tema=("Rinitis alérgica", ["Inflamación de la mucosa nasal mediada por IgE ante alérgenos (ácaros, pólenes, mascotas).",
                             "Estornudos en salva, rinorrea acuosa, prurito y congestión."]),
  caso=("Escolar", ["Estornudos matutinos, rinorrea y prurito nasal.", "Ojeroso, respira por la boca, pliegue nasal transverso; IgE 500 UI/mL."]),
  perlas=["Primera línea: corticoide intranasal; antihistamínico oral de 2.ª generación si hay síntomas leves o oculares.",
          "Control ambiental de ácaros; inmunoterapia con alérgenos si no se controla.",
          "Se asocia con asma: preguntar por tos y sibilancias."],
  fuente="ARIA, guía de rinitis alérgica (2024); " + NELSON + ".",
  op=("¿Tipo?", ["No: sin IgE ni prurito", "Sí: prurito + estigmas + IgE alta", "No: sin fiebre ni secreción purulenta",
                 "No: sin descongestionantes", "No: sin costras ni mal olor"]),
  d=dict(rotulo="Rinitis: ¿cuál?", ans=0,
         cards=[dict(titulo="Alérgica", datos=[("Prurito", "Sí", True), ("IgE", "Alta", True), ("Estigmas", "Ojeras, pliegue", True)],
                     pie="Este caso."),
                dict(titulo="Vasomotora", datos=[("Gatillo", "Frío, olores", False), ("IgE", "Normal", False), ("Prurito", "Poco", False)],
                     pie="Ipratropio nasal."),
                dict(titulo="Infecciosa", datos=[("Fiebre", "Puede", False), ("Secreción", "Espesa", False), ("Curso", "Días", False)],
                     pie="Lavados."),
                dict(titulo="Medicamentosa", datos=[("Antecedente", "Oximetazolina", False), ("Tiempo", "> 5 días", False), ("Efecto", "Rebote", False)],
                     pie="Suspender.")]),
  triada=TR([("Saludo alérgico (pliegue nasal transverso)", "Sí", True), ("Ojeras alérgicas", "Sí", True), ("Respiración bucal", "Sí", True),
             ("Líneas de Dennie-Morgan", "No se informa", False)],
            [("Estigmas atópicos", 0, 3)],
            "Tres estigmas + IgE alta: rinitis alérgica.", rotulo="Signos con nombre propio"))

# CIR-029 · Colecistitis aguda · ÁRBOL + Tokio 2018
S("arbol", "CIR-029", "Dolor en hipocondrio derecho tras comida grasa, leucocitosis, pared vesicular de 5 mm y cálculo fijo en el bacinete: colecistitis aguda",
  "Patología biliar · colecistitis aguda",
  ("Colecistitis aguda calculosa", ["Un cálculo obstruye el cístico (bacinete) y la vesícula se inflama.",
                                    "Dolor continuo en hipocondrio derecho, Murphy, fiebre, leucocitosis."]),
  ("Mujer de 40 años", ["Dolor abdominal y vómitos tras comida grasa; resistencia muscular en hipocondrio derecho.",
                        "Leucocitos 16 000; BT 2, BD 0,8; eco: pared 5 mm, cálculo de 2 cm fijo en el bacinete, colédoco 4 mm."]),
  ["Grado I: colecistectomía laparoscópica temprana (idealmente < 72 h, hasta 7 días).",
   "Antibiótico según la gravedad; analgesia y ayuno.",
   "Colédoco normal (4 mm) y bilirrubina directa normal: no orienta a coledocolitiasis."],
  "Guías de Tokio 2018 (TG18); WSES, colecistitis aguda (2020).",
  op=("¿Diagnóstico?", ["Sí: Murphy + pared gruesa + cálculo fijo", "No: dolor en cinturón, páncreas", "No: dolor desproporcionado, sangre",
                        "No: fosa ilíaca derecha", "No: colédoco de 4 mm, BD normal"]),
  arbol=Q("Dolor en hipocondrio derecho: ¿cumple criterios de Tokio?", [
      L("A + B + C (este caso)", "COLECISTITIS AGUDA", ["Grado I", "Colecistectomía temprana"], path=True),
      L("Solo cólico que cede", "Cólico biliar", ["Colecistectomía programada"])], path=True),
  triada=TR([("A: signo local (Murphy, dolor o masa en HCD)", "Resistencia en HCD", True), ("B: signo sistémico (fiebre, PCR, leucocitos)", "16 000", True),
             ("C: imagen (pared > 4 mm, cálculo enclavado)", "Pared 5 mm, cálculo fijo", True)],
            [("Criterios diagnósticos de Tokio 2018", 0, 2)],
            "A + B + C: diagnóstico definitivo de colecistitis aguda.", rotulo="Criterios con nombre propio"),
  escala=dict(nombre="Gravedad según Tokio 2018", que="Define la urgencia y el tipo de tratamiento.",
              grados=[("Grado I", "Leve", ["Sin criterios de II ni III", "Colecistectomía temprana"]),
                      ("Grado II", "Moderada", ["Leucocitos > 18 000, masa palpable", "> 72 h o inflamación local marcada"]),
                      ("Grado III", "Grave", ["Falla de órganos", "Drenaje y soporte"])],
              caso=0, porque=[("Leucocitos 16 000 (< 18 000) y sin masa", True), ("Sin falla de órganos", True)],
              conducta="Colecistectomía laparoscópica temprana."))

# NEF-022 · Hiperpotasemia: ECG · TERMÓMETRO + gravedad
S("termometro", "NEF-022", "QRS ancho con ondas T altas, delgadas y puntiagudas: hiperpotasemia",
  "Trastornos del potasio · hiperpotasemia",
  ("Hiperpotasemia en el ECG", ["El ECG empeora a medida que sube el potasio.",
                                "T picudas → P aplanada → QRS ancho → onda sinusoidal y paro."]),
  ("Varón de 45 años", ["Dolor precordial y taquicardia.", "ECG: QRS ancho, ondas T muy altas, delgadas y puntiagudas."]),
  ["QRS ancho = emergencia: gluconato de calcio EV ya (protege el corazón).",
   "Luego insulina + glucosa y salbutamol; después eliminar el potasio (diuréticos, quelantes, diálisis).",
   "Hipopotasemia da lo contrario: T planas y onda U."],
  "UK Kidney Association, hiperpotasemia aguda (2023); " + HARRISON + ".",
  op=("¿Alteración?", ["No: no da estos cambios", "No: QT corto", "Sí: T picudas + QRS ancho", "No: T planas, onda U", "No: QT largo"]),
  d=dict(rotulo="El ECG empeora a medida que sube el potasio", caso_nivel=2, ruta_titulo="Qué hacer ya", paso_label="ESTE CASO",
         niveles=[("T picudas", "5,5-6,5", ["Ondas T altas y estrechas"]), ("P aplanada", "6,5-7,5", ["PR largo"]),
                  ("QRS ancho", "7-8", ["Bloqueos, bradicardia"]), ("Sinusoidal", "> 8", ["Fibrilación ventricular"])],
         pasos=[(1, "Gluconato de calcio EV", ["Protege el corazón en minutos"], True),
                (2, "Insulina + glucosa, salbutamol", ["Meten el K⁺ a la célula"], False),
                (3, "Eliminar el potasio", ["Diuréticos, quelantes o diálisis"], False)]),
  escala=HIPERK(2, [("QRS ancho y T picudas", True), ("Riesgo de arritmia inminente", True)],
                "Monitor, gluconato de calcio EV, insulina + glucosa y salbutamol."))

# INF-023 · Shigelosis · EMBUDO
S("embudo", "INF-023", "Diarrea con moco y poca sangre, fiebre de 38,5 °C, vómitos y comida en la calle: Shigella",
  "Enfermedad diarreica aguda · disentería",
  ("Disentería por Shigella", ["Invade el colon: deposiciones pequeñas con moco y sangre, fiebre, cólico y pujo.",
                               "Muy contagiosa: bastan 10-100 bacterias."]),
  ("Varón de 26 años", ["Comió en un puesto ambulante hace 3 días.", "Náuseas, vómitos, deposiciones líquidas con moco y sangre; 38,5 °C."]),
  ["Hidratación y antibiótico en la disentería: azitromicina o ciprofloxacino según la resistencia local.",
   "No dar antidiarreicos (loperamida) en diarrea con sangre y fiebre.",
   "Coprocultivo si es grave; S. dysenteriae tipo 1 puede dar síndrome urémico hemolítico."],
  OMS + ", tratamiento de la diarrea (2005, act. 2024); IDSA, diarrea infecciosa (2017).",
  op=("¿Etiología?", ["No: acuosa sin sangre", "Sí: disentería con fiebre", "No: no es patógena", "No: horas después, sin fiebre ni sangre",
                      "No: acuosa, niños pequeños"]),
  d=dict(rotulo="Diarrea aguda: ¿qué germen?", inicio="Diarrea con moco y sangre, fiebre, comida en la calle",
         candidatos=["Rotavirus", "Vibrio cholerae", "Toxina estafilocócica", "Entamoeba coli", "Shigella"],
         pasos=[("¿Diarrea acuosa sin sangre?", ["Rotavirus", "Vibrio cholerae"]),
                ("¿Sin fiebre o no patógena?", ["Toxina estafilocócica", "Entamoeba coli"])],
         final=("SHIGELLA", ["Disentería con fiebre"]),
         nota="Hidratar + azitromicina o ciprofloxacino."))

# GAS-017 · Hepatitis en el niño: transaminasas · ÁRBOL
S("arbol", "GAS-017", "Niña con fiebre, vómitos, dolor en hipocondrio derecho y hepatomegalia sin ictericia: transaminasas para ver inflamación del hígado",
  "Hepatitis aguda en el niño",
  ("Hepatitis aguda", ["Inflamación del hígado: las células rotas liberan ALT y AST.",
                       "En niños pequeños suele ser anictérica (sin ictericia), sobre todo la hepatitis A."]),
  ("Niña de 2 años", ["6 días de fiebre, anorexia, náuseas, vómitos y dolor abdominal.", "Dolor en hipocondrio derecho; hígado a 2 cm del reborde; sin ictericia."]),
  ["ALT y AST altas confirman daño hepatocelular; muy altas (> 10 veces) en la hepatitis viral.",
   "Luego la causa: IgM anti-VHA primero en niños peruanos; tiempo de protrombina para la gravedad.",
   "Fosfatasa alcalina y GGT orientan a colestasis, no a inflamación del hepatocito."],
  "AAP, Red Book (2024); " + NELSON + ".",
  op=("¿Prueba?", ["No: busca bacteriemia", "No: mide colestasis y hueso", "No: inflamación general", "Sí: daño del hepatocito",
                   "No: es para el páncreas"]),
  arbol=Q("Hepatomegalia dolorosa con fiebre y vómitos: ¿inflamación del hígado?", [
      L("Confirmar (este caso)", "TRANSAMINASAS (ALT, AST)", ["Muy altas: hepatitis aguda", "Luego IgM anti-VHA"], path=True),
      L("Si hay ictericia y acolia", "Bilirrubinas, FA, GGT", ["Colestasis"])], path=True),
  escala=dict(nombre="Patrón de daño hepático (índice R)", orden=False, que="R = (ALT / límite normal) ÷ (FA / límite normal).",
              grados=[("R > 5", "Hepatocelular", ["Hepatitis viral, tóxica"]), ("R 2-5", "Mixto", ["Fármacos"]),
                      ("R < 2", "Colestásico", ["Obstrucción biliar"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("En la hepatitis viral se espera un patrón hepatocelular", True), ("Las transaminasas lo definen", True)],
              conducta="Transaminasas, luego IgM anti-VHA y tiempo de protrombina."))

# GAS-018 · Pancreatitis aguda · ÁRBOL + Atlanta + Cullen real
S("arbol", "GAS-018", "Dolor epigástrico terebrante irradiado a la espalda tras beber licor, con vómitos y signo de Cullen: pancreatitis aguda",
  "Páncreas · pancreatitis aguda",
  ("Pancreatitis aguda", ["Las enzimas del páncreas se activan dentro de él: inflamación y a veces necrosis.",
                          "Causas principales: cálculos biliares y alcohol."]),
  ("Varón de 38 años", ["6 horas después de beber: epigastralgia brusca, intensa, en barra, que va a la espalda; náuseas y vómitos.",
                        "Signo de Cullen."]),
  ["Diagnóstico: 2 de 3 (dolor típico, lipasa o amilasa > 3 veces, imagen); la TC no es necesaria al inicio.",
   "Ringer lactato moderado y guiado por metas (WATERFALL 2022), analgesia, dieta oral precoz si tolera.",
   "No antibióticos profilácticos; Cullen y Grey Turner indican sangrado retroperitoneal (formas graves)."],
  "ACG, pancreatitis aguda (2024); Atlanta revisada (2012); IAP/APA (2013).",
  op=("¿Diagnóstico?", ["No: sin distensión ni niveles", "Sí: dolor en barra + alcohol + Cullen", "No: mayor edad, dolor desproporcionado",
                        "No: daría abdomen en tabla y aire libre", "No: sin cambios en el ECG descritos"]),
  arbol=Q("Dolor epigástrico a la espalda tras alcohol: ¿lipasa > 3 veces?", [
      L("Probable (este caso)", "PANCREATITIS AGUDA", ["Ringer lactato, analgesia", "Dieta oral precoz"], path=True),
      L("No: abdomen en tabla", "Úlcera perforada", ["Rx: aire libre"])], path=True),
  triada=TR([("Dolor típico", "En barra, a la espalda", True), ("Lipasa o amilasa > 3 veces", "Por medir", False), ("Imagen compatible", "Por medir", False),
             ("Signo de Cullen (periumbilical)", "Sí", True), ("Signo de Grey Turner (flancos)", "No se informa", False)],
            [("Criterios de Atlanta (2 de 3)", 0, 2), ("Signos con nombre propio", 3, 4)],
            "Con la lipasa > 3 veces se cumplen 2 de 3; el Cullen avisa de sangrado retroperitoneal."),
  escala=dict(nombre="Clasificación de Atlanta revisada (2012)", que="Se define por la falla de órganos y las complicaciones.",
              grados=[("Leve", "Sin falla de órganos", ["Sin complicaciones locales", "Alta en días"]),
                      ("Moderadamente grave", "Falla < 48 h", ["O complicaciones locales"]),
                      ("Grave", "Falla > 48 h", ["Persistente", "Mortalidad alta"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("El Cullen sugiere una forma con sangrado retroperitoneal", True), ("La gravedad se define con la evolución de 48 h", True)],
              conducta="Lipasa, Ringer lactato, analgesia y vigilar falla de órganos."),
  banda=B("Signo de Cullen en una pancreatitis (foto real)", P("cullen.jpg", 340, 210, [
            ("flecha", 0.54, 0.45, 0.2, 0.75, "equimosis\nperiumbilical"),
            ("flecha", 0.46, 0.2, 0.18, 0.15, "ombligo")],
          credito="H. L. Fred y H. A. van Dijk" + CC + "CC BY 2.0"),
          [("Equimosis periumbilical", "Sangre del retroperitoneo que llega a la piel del ombligo."),
           ("Aparece en 1-2 días", "No es precoz: su ausencia no descarta la pancreatitis."),
           ("Grey Turner", "La misma equimosis en los flancos."),
           ("Señal de gravedad", "Se asocia a pancreatitis necrótico-hemorrágica.")],
          pie="Paciente de 36 años con pancreatitis alcohólica.", ans=0))

# CIR-030 · Hemorragia intraabdominal · ÁRBOL + choque hemorrágico
S("arbol", "CIR-030", "Politraumatizado con PA 70/40, FC 156, palidez, yugulares colapsadas y tórax normal: hemorragia intraabdominal",
  "Trauma · choque hemorrágico",
  ("Choque hemorrágico en el trauma", ["La primera causa de choque en el trauma es la pérdida de sangre.",
                                       "Yugulares vacías = falta volumen; tórax normal = el sangrado está en otro lado."]),
  ("Politraumatizado", ["Mal estado general; PA 70/40, FC 156, FR 24, SatO₂ 92 %.", "Pálido, diaforético, yugulares colapsadas, tórax normal."]),
  ["Buscar el sangrado: tórax, abdomen (FAST), pelvis, huesos largos y fuera (piel).",
   "Dos vías gruesas, ácido tranexámico en < 3 h, sangre precoz 1:1:1; evitar mucho cristaloide.",
   "Inestable con FAST positivo: laparotomía."],
  ATLS + ".",
  op=("¿Diagnóstico?", ["Sí: choque con yugulares vacías y tórax normal", "No: yugulares llenas y tórax anormal", "No: yugulares llenas",
                        "No: arritmias, no hipovolemia", "No: daría bradicardia y piel caliente"]),
  arbol=Q("Choque en trauma: ¿cómo están las yugulares?", [
      L("Colapsadas, tórax normal (este caso)", "HEMORRAGIA INTRAABDOMINAL", ["FAST", "Laparotomía si inestable"], path=True),
      L("Ingurgitadas", "Choque obstructivo", ["Neumotórax o taponamiento"])], path=True),
  escala=dict(nombre="Clases de choque hemorrágico (ATLS)", que="Estima cuánta sangre se perdió por los signos vitales.",
              grados=[("Clase I", "< 15 %", ["FC y PA normales"]), ("Clase II", "15-30 %", ["FC > 100", "PA normal"]),
                      ("Clase III", "31-40 %", ["FC 120-140", "PA baja"]), ("Clase IV", "> 40 %", ["FC > 140", "PA muy baja"])],
              caso=3, porque=[("FC 156 (> 140)", True), ("PA 70/40", True)],
              conducta="Transfusión masiva 1:1:1, ácido tranexámico y control quirúrgico del sangrado."))

# INF-024 · Malaria en la gestante · TARJETAS + periodicidad
S("tarjetas", "INF-024", "Gestante de Tumbes con fiebre cíclica, escalofríos y sudoración profusa: paludismo (malaria)",
  "Enfermedades metaxénicas · malaria",
  ("Malaria (paludismo)", ["Plasmodium transmitido por Anopheles; en el Perú, sobre todo en Loreto y la costa norte (Tumbes, Piura).",
                           "Accesos de escalofrío, fiebre alta y sudoración que se repiten en ciclos."]),
  ("Primigesta de Tumbes", ["9 días de malestar, cefalea y fatiga.", "Fiebre alta cada 72 horas con escalofríos, sudoración, mialgias y artralgias."]),
  ["Gota gruesa y frotis: confirman y dicen la especie.",
   "Gestante: P. vivax → cloroquina (sin primaquina hasta después del parto); P. falciparum → artemeter-lumefantrina (OMS 2022, incluso en el 1.er trimestre).",
   "La malaria en el embarazo es más grave: anemia, hipoglucemia, parto pretérmino y bajo peso."],
  OMS + ", guías de malaria (2022, act. 2025); " + MINSA + ", norma técnica de malaria.",
  op=("¿Diagnóstico?", ["Sí: fiebre cíclica + zona endémica", "No: fiebre leve, exantema", "No: fiebre continua, no cíclica",
                        "No: agua contaminada, ictericia", "No: no cíclica, dolor retroocular"]),
  d=dict(rotulo="Fiebre en zona endémica: ¿cuál?", ans=0,
         cards=[dict(titulo="Malaria", datos=[("Fiebre", "Cíclica", True), ("Además", "Escalofrío, sudor", True), ("Zona", "Tumbes", True)],
                     pie="Este caso: gota gruesa."),
                dict(titulo="Dengue", datos=[("Fiebre", "Continua, 2-7 días", False), ("Dolor", "Retroocular", False), ("Exantema", "Sí", False)],
                     pie="Signos de alarma."),
                dict(titulo="Leptospirosis", datos=[("Contacto", "Agua, roedores", False), ("Mialgia", "Pantorrillas", False), ("Ojos", "Sufusión", False)],
                     pie="Doxiciclina."),
                dict(titulo="Fiebre tifoidea", datos=[("Fiebre", "En escalera", False), ("Pulso", "Bradicardia relativa", False),
                                                      ("Piel", "Roséola", False)],
                     pie="Hemocultivo.")]),
  escala=dict(nombre="Periodicidad de la fiebre según la especie", orden=False, que="El ciclo de la fiebre sigue la ruptura de los glóbulos rojos.",
              grados=[("Terciana", "Cada 48 horas", ["P. vivax y P. ovale", "Hipnozoítos: recaídas"]),
                      ("Cuartana", "Cada 72 horas", ["P. malariae"]),
                      ("Irregular", "Sin patrón fijo", ["P. falciparum", "Formas graves"])],
              caso=1, porque=[("Fiebre cada 72 horas: patrón cuartano", True),
                              ("En Tumbes predomina P. vivax: la gota gruesa define la especie", False)],
              conducta="Gota gruesa y tratamiento según especie y trimestre."))
