"""Bloque 6 · parte N."""
from c6 import F6, Q, L, A, V, NELSON, ATLS, ROSE, VIOLET, SKY, AMBER

WILLIAMS = "Williams Obstetrics 26.ª ed. (2022)"
HARRISON = "Harrison's Principles of Internal Medicine 22.ª ed. (2025)"

# HEM-028 · matriz
V("matriz", "HEM-028", "sangrado-mucocutaneo-ristocetina-baja-von-willebrand", "Trastornos de la hemostasia primaria",
  "HEMATOLOGÍA ENAM: ENFERMEDAD DE VON WILLEBRAND", "HEMATOLOGÍA",
  ("Enfermedad de von Willebrand", ["Trastorno hereditario de sangrado más frecuente",
   "Sangrado mucocutáneo; sangría larga, factor VIII bajo y ristocetina disminuida"]),
  ("Varón de 40 años con sangrados mucocutáneos", ["Antecedente familiar · petequias", "Sangría prolongada, FVIII bajo, ristocetina baja"]),
  {"rotulo": "Pruebas de laboratorio", "eje_x": "Prueba", "eje_y": "Trastorno",
   "cols": ["Sangría", "Factor VIII", "Ristocetina"], "rows": ["Von Willebrand", "Hemofilia A", "Hemofilia B", "Glanzmann"], "caso": (0, 2),
   "cells": [[("Prolongada", []), ("Bajo", ["El vWF lo protege"]), ("DISMINUIDA", [])],
             [("Normal", []), ("Muy bajo", []), ("Normal", [])],
             [("Normal", []), ("Normal", ["Falta el IX"]), ("Normal", [])],
             [("Prolongada", []), ("Normal", []), ("Normal", ["Falla con ADP"])]]},
  ["Tratamiento: desmopresina en el tipo 1; concentrado de FVIII/vWF si no responde.",
   "Evitar aspirina y AINE.",
   "Ácido tranexámico para sangrados mucosos."],
  "ASH/ISTH/NHF/WFH – Guidelines on the diagnosis and management of von Willebrand disease (2021)")

# CIR-084 · radial
V("radial", "CIR-084", "apendicitis-obesa-laparoscopia-menos-infeccion-herida", "Apendicectomía laparoscópica",
  "CIRUGÍA ENAM: APENDICECTOMÍA LAPAROSCÓPICA", "CIRUGÍA",
  ("Vía laparoscópica en obesos", ["Incisiones pequeñas: menos infección de herida",
   "Mejor visión sin agrandar la incisión"]),
  ("Mujer de 45 años obesa", ["Apendicitis aguda no complicada", "¿Ventaja de la laparoscopía?"]),
  {"rotulo": "Mapa del tema", "centro": "LAPAROSCOPÍA", "centro_sub": "Apendicectomía", "ans": 0,
   "items": [("MENOS INFECCIÓN", ["De la herida", "Más beneficio en obesos"]),
             ("Menos dolor", ["Menos analgésicos"]),
             ("Alta precoz", ["Retorno rápido"]),
             ("Exploración", ["Ve toda la cavidad"]),
             ("Desventaja", ["Costo y equipo"])],
   "ruta": ["Obesa con apendicitis", "Incisión grande en abierta", "Grasa: más infección", "MENOS INFECCIÓN"]},
  ["Sigue necesitando antibiótico profiláctico.",
   "El riesgo tromboembólico no cambia de forma importante.",
   "Útil en mujeres en edad fértil para descartar causa ginecológica."],
  "WSES – Jerusalem guidelines for acute appendicitis (2020) · SAGES – Laparoscopic appendectomy (2010)")

# CIR-085 · embudo
V("embudo", "CIR-085", "tumoracion-supraumbilical-reductible-hernia-epigastrica", "Tumoración supraumbilical",
  "CIRUGÍA ENAM: HERNIA EPIGÁSTRICA", "CIRUGÍA",
  ("Hernia epigástrica", ["Defecto en la línea alba entre el apéndice xifoides y el ombligo",
   "Aparece de pie o al pujar y desaparece al acostarse"]),
  ("Varón de 56 años", ["Tumoración blanda supraumbilical", "Aparece de pie, desaparece en decúbito"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Tumoración supraumbilical reductible",
   "candidatos": ["Hernia epigástrica", "Diástasis de rectos", "Hernia umbilical", "Tumor desmoides", "Lipoma"],
   "pasos": [("Aparece de pie y se reduce: es hernia", ["Tumor desmoides", "Lipoma"]),
             ("Tumoración localizada, no una cresta larga", ["Diástasis de rectos"]),
             ("Por encima del ombligo, en la línea alba", ["Hernia umbilical"])],
   "final": ("HERNIA EPIGÁSTRICA", ["Defecto de la línea alba", "Hernioplastia con malla si es > 1 cm"]),
   "nota": "La diástasis de rectos no tiene anillo herniario y no se estrangula."},
  ["Suele contener grasa preperitoneal.",
   "Puede ser múltiple.",
   "Riesgo de incarceración si el anillo es pequeño."],
  "EHS – Guidelines on umbilical and epigastric hernias (2020)")

# INF-076 · árbol
A("INF-076", "trofozoitos-entamoeba-metronidazol-paromomicina", "Amebiasis intestinal",
  "INFECTOLOGÍA ENAM: AMEBIASIS INTESTINAL", "INFECTOLOGÍA",
  ("Amebiasis intestinal", ["Metronidazol elimina las formas invasivas",
   "Luego un amebicida luminal (paromomicina) para los quistes"]),
  ("Varón de 24 años", ["Diarrea intermitente y pérdida de peso", "Trofozoítos de E. histolytica en heces"]),
  Q("¿Forma invasiva o solo quistes?", [
      L("Invasiva: colitis o absceso", "METRONIDAZOL + PAROMOMICINA", ["7-10 días + 7 días"], path=True),
      L("Portador asintomático", "Solo paromomicina", ["Amebicida luminal"])], path=True),
  ("Antiparasitarios", [("Uso", True)], [
      ("Metronidazol", ["Formas invasivas (tejido)"]),
      ("Paromomicina", ["Quistes en la luz"]),
      ("Albendazol", ["Helmintos, no amebas"])]),
  ["Sin el luminal, hay recaídas.",
   "Absceso hepático amebiano: metronidazol; drenar solo si no mejora.",
   "Praziquantel es para tenias y trematodos."],
  "CDC – Amebiasis: treatment (2024) · " + HARRISON)

# GIN-144 · fases
V("fases", "GIN-144", "salida-cabeza-rotacion-externa", "Mecanismo del parto",
  "OBSTETRICIA ENAM: MOVIMIENTOS CARDINALES DEL PARTO", "OBSTETRICIA",
  ("Movimientos cardinales del parto", ["Encajamiento, descenso, flexión, rotación interna, extensión",
   "Tras salir la cabeza: rotación externa (restitución) y expulsión"]),
  ("Pregunta de concepto", ["Parto vaginal a término", "¿Qué movimiento sigue a la salida de la cabeza?"]),
  {"rotulo": "Últimos movimientos", "ans": 2,
   "fases": [("Rot. interna", "Pelvis media", "Occipucio adelante", ["Bajo el pubis"]),
             ("Extensión", "Periné", "Sale la cabeza", ["Deflexión"]),
             ("Rot. externa", "Restitución", "ROTACIÓN EXTERNA", ["Mira al muslo materno"]),
             ("Expulsión", "Hombros", "Nace el cuerpo", ["Anterior y luego posterior"])],
   "curvas": [],
   "chips_titulo": "Movimiento · marcado el correcto",
   "chips": [("Rotación externa", True), ("Rotación interna", False), ("Flexión", False), ("Encajamiento", False)]},
  ["La rotación externa alinea los hombros en el diámetro anteroposterior.",
   "Distocia de hombros: la cabeza se retrae («signo de la tortuga»).",
   "El encajamiento ocurre antes, al entrar a la pelvis."],
  WILLIAMS)

# NRL-040 · puntaje
V("puntaje", "NRL-040", "cefalea-hemicraneal-pulsatil-48-h-fotofobia-migrana", "Migraña: criterios",
  "NEUROLOGÍA ENAM: MIGRAÑA", "NEUROLOGÍA",
  ("Migraña sin aura", ["Cefalea de 4-72 h, unilateral, pulsátil",
   "Con náuseas o foto/fonofobia; examen neurológico normal"]),
  ("Adolescente de 16 años", ["Cefalea hemicraneal pulsátil de 48 h", "Fotofobia, náuseas, vómitos · examen y TC normales"]),
  {"rotulo": "Criterios ICHD-3 en el caso", "escala": "ICHD-3", "total": 5, "max": 6,
   "total_label": "Criterios presentes",
   "interpreta": "Migraña sin aura",
   "items": [("Duración 4-72 horas", "1", True), ("Unilateral", "1", True), ("Pulsátil", "1", True),
             ("Náuseas o vómitos", "1", True), ("Fotofobia", "1", True), ("Empeora con la actividad", "1", False)],
   "bandas": [("No", "No cumple", "Otro tipo de cefalea", False),
              ("Sí", "Migraña", "AINE o triptán; profilaxis si es frecuente", True)]},
  ["Racimos: periocular, 15-180 min, lagrimeo y rinorrea.",
   "Tensional: bilateral, opresiva, sin náuseas.",
   "Signos de alarma: súbita, focalidad, fiebre, > 50 años de inicio."],
  "IHS – International Classification of Headache Disorders 3.ª ed. (ICHD-3, 2018) · AHS – Consensus statement (2021)")

# SP-106 · radial
V("radial", "SP-106", "leptospirosis-rural-calzado-agua-segura", "Prevención de la leptospirosis",
  "SALUD PÚBLICA ENAM: PREVENCIÓN DE LEPTOSPIROSIS", "SALUD PÚBLICA",
  ("Prevención comunitaria de la leptospirosis", ["Evitar el contacto con agua y suelo contaminados",
   "Calzado protector y agua segura"]),
  ("Zonas rurales pobres", ["Saneamiento deficiente", "¿Qué estrategia comunitaria es más efectiva?"]),
  {"rotulo": "Mapa del tema", "centro": "LEPTOSPIROSIS", "centro_sub": "Prevención", "ans": 0,
   "items": [("CALZADO Y AGUA", ["Botas en zonas inundadas", "Agua segura para beber"]),
             ("Roedores", ["Control y basura"]),
             ("Saneamiento", ["Desagüe y drenaje"]),
             ("Educación", ["Evitar bañarse en aguas estancadas"]),
             ("Profilaxis", ["Doxiciclina solo en exposición puntual"])],
   "ruta": ["Pobreza y mal saneamiento", "Agua y suelo contaminados", "Barrera al contacto", "CALZADO Y AGUA SEGURA"]},
  ["La transmisión aumenta tras lluvias e inundaciones.",
   "Vivir cerca de ríos aumenta el riesgo.",
   "Centralizar el diagnóstico en hospitales retrasa la atención."],
  "OMS – Human leptospirosis: guidance for diagnosis, surveillance and control (2003) · MINSA – NTS de leptospirosis")

# NEU-040 · termómetro
V("termometro", "NEU-040", "habla-entrecortada-sato2-93-pef-66-crisis-moderada", "Gravedad de la crisis asmática",
  "NEUMOLOGÍA ENAM: CRISIS ASMÁTICA MODERADA", "NEUMOLOGÍA",
  ("Crisis asmática moderada", ["Habla entrecortada, uso de accesorios, SatO₂ 90-95%",
   "PEF o FEV1 entre 50 y 70%"]),
  ("Varón de 26 años con asma no controlada", ["6 días de disnea, habla entrecortada", "SatO₂ 93%, FR 24, accesorios · PEF 66%"]),
  {"rotulo": "Según PEF y clínica",
   "niveles": [("PEF > 70%", "Leve", ["Habla normal"]),
               ("PEF 50-70%", "Moderada", ["Habla entrecortada"]),
               ("PEF < 50%", "Grave", ["Habla palabras, SatO₂ < 90%"]),
               ("Silencio", "Casi fatal", ["Somnolencia, bradicardia"])],
   "caso_nivel": 1, "ruta_titulo": "Tratamiento", "paso_label": "PASO",
   "pasos": [(1, "SALBUTAMOL REPETIDO", ["+ ipratropio"], True),
             (2, "Corticoide sistémico", ["Prednisona oral"], False),
             (3, "Oxígeno", ["Meta SatO₂ 93-95%"], False)]},
  ["Reevaluar a la hora con PEF y clínica.",
   "Al alta: corticoide inhalado de mantenimiento.",
   "Revisar técnica inhalatoria y adherencia."],
  "GINA – Global Strategy for Asthma Management (2024) · GEMA 5.4 – Guía española para el manejo del asma (2024)")

# PSI-030 · embudo
V("embudo", "PSI-030", "amenorrea-sintomas-embarazo-hcg-negativa-pseudociesis", "Síntomas de embarazo sin gestación",
  "PSIQUIATRÍA ENAM: PSEUDOCIESIS", "PSIQUIATRÍA",
  ("Pseudociesis (embarazo psicológico)", ["Creencia firme de estar embarazada con síntomas físicos",
   "β-hCG negativa y ecografía sin gestación"]),
  ("Mujer de 34 años", ["Amenorrea de 24 semanas, náuseas, mamas congestivas", "Siente movimientos fetales · β-hCG 0.1 · útero normal"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Síntomas de embarazo con β-hCG negativa",
   "candidatos": ["Pseudociesis", "Embarazo ectópico", "Gestación inicial", "Mola", "Aborto incompleto"],
   "pasos": [("β-hCG negativa", ["Embarazo ectópico", "Gestación inicial", "Mola"]),
             ("Útero normal, sin restos", ["Aborto incompleto"])],
   "final": ("PSEUDOCIESIS", ["Trastorno de síntomas somáticos", "Mostrar la ecografía y psicoterapia"]),
   "nota": "Descartar tumores secretores de hormonas y causas endocrinas."},
  ["Se asocia a deseo intenso de embarazo, infertilidad o pérdida.",
   "Abordaje empático: no confrontar con brusquedad.",
   "Diferenciar de delirio psicótico de embarazo."],
  "APA – DSM-5-TR (2022) · Williams Gynecology 4.ª ed. (2020)")

# REU-040 · tarjetas
V("tarjetas", "REU-040", "nodulo-perlado-telangiectasias-cara-basocelular", "Tumores de piel de la cara",
  "DERMATOLOGÍA ENAM: CARCINOMA BASOCELULAR", "DERMATOLOGÍA",
  ("Carcinoma basocelular", ["El cáncer de piel más frecuente; en zonas expuestas al sol",
   "Nódulo perlado con telangiectasias; crece lento y casi no metastatiza"]),
  ("Varón de 75 años", ["Nódulo facial de 1 año, ulceración reciente", "Borde perlado con telangiectasias arborizantes"]),
  {"rotulo": "¿Qué tumor es?", "ans": 0, "cards": [
      {"titulo": "BASOCELULAR", "datos": [
          ("Lesión", "Nódulo perlado", True), ("Crecimiento", "Lento, local", True),
          ("Clave", "Telangiectasias", True)],
       "pie": "Cirugía; Mohs en zonas críticas"},
      {"titulo": "Melanoma", "datos": [
          ("Lesión", "Pigmentada, asimétrica", False), ("Crecimiento", "Rápido, metastatiza", False),
          ("Clave", "Regla ABCDE", False)],
       "pie": "Espesor de Breslow"},
      {"titulo": "Espinocelular", "datos": [
          ("Lesión", "Úlcera infiltrada, costra", False), ("Crecimiento", "Moderado", False),
          ("Clave", "Sobre queratosis actínica", False)],
       "pie": "Puede dar metástasis"},
      {"titulo": "Lupus discoide", "datos": [
          ("Lesión", "Placa atrófica", False), ("Crecimiento", "Crónico", False),
          ("Clave", "Cicatriz, alopecia", False)],
       "pie": "Autoinmune"}]},
  ["Micosis fungoide: linfoma T cutáneo en placas.",
   "Dermatoscopía: vasos arborizantes.",
   "Protección solar desde la infancia."],
  "NCCN – Basal cell skin cancer (2024) · Fitzpatrick's Dermatology 9.ª ed. (2019)")

# SP-107 · termómetro
V("termometro", "SP-107", "formaldehido-planta-alimentos-eliminar-fuente", "Jerarquía de controles",
  "SALUD PÚBLICA ENAM: SALUD OCUPACIONAL", "SALUD PÚBLICA",
  ("Jerarquía de controles de riesgos", ["Lo más eficaz es eliminar o reducir la fuente",
   "El equipo de protección personal es la última barrera"]),
  ("Planta de alimentos", ["Irritación ocular, tos y disnea", "Formaldehído alto, sin protección, mala ventilación"]),
  {"rotulo": "Eficacia del control",
   "niveles": [("EPP", "Menos eficaz", ["Mascarillas, lentes"]),
               ("Admin.", "Procedimientos", ["Turnos, capacitación"]),
               ("Ingeniería", "Ventilación", ["Aislar la fuente"]),
               ("Eliminación", "Más eficaz", ["Eliminar o sustituir"])],
   "caso_nivel": 3, "ruta_titulo": "Medidas", "paso_label": "PASO",
   "pasos": [(1, "ELIMINAR O REDUCIR LA FUENTE", ["Sustituir el formaldehído"], True),
             (2, "Ventilación", ["Extracción localizada"], False),
             (3, "EPP mientras tanto", ["Protección respiratoria"], False)]},
  ["El control médico anual detecta el daño, no lo previene.",
   "Ley N.° 29783 de seguridad y salud en el trabajo.",
   "El formaldehído es carcinógeno (nasofaringe)."],
  "NIOSH – Hierarchy of controls (2023) · Ley N.° 29783 y su reglamento")

# SP-108 · tarjetas
V("tarjetas", "SP-108", "similitud-diluciones-homeopatia", "Medicinas no convencionales",
  "SALUD PÚBLICA ENAM: HOMEOPATÍA", "SALUD PÚBLICA",
  ("Homeopatía", ["Principio de similitud: «lo similar cura lo similar»",
   "Usa sustancias altamente diluidas"]),
  ("Pregunta de concepto", ["Terapia basada en la similitud", "con sustancias muy diluidas"]),
  {"rotulo": "¿Qué terapia es?", "ans": 0, "cards": [
      {"titulo": "HOMEOPATÍA", "datos": [
          ("Principio", "Similitud", True), ("Método", "Diluciones extremas", True),
          ("Origen", "Hahnemann, Alemania", True)],
       "pie": "Sin evidencia de eficacia"},
      {"titulo": "Naturopatía", "datos": [
          ("Principio", "Curación natural", False), ("Método", "Dieta, plantas, agua", False),
          ("Origen", "Europa", False)],
       "pie": "Estilos de vida"},
      {"titulo": "Acupuntura", "datos": [
          ("Principio", "Flujo de energía (qi)", False), ("Método", "Agujas en meridianos", False),
          ("Origen", "China", False)],
       "pie": "Complementaria"},
      {"titulo": "Ayurveda", "datos": [
          ("Principio", "Equilibrio de doshas", False), ("Método", "Dieta, plantas, masajes", False),
          ("Origen", "India", False)],
       "pie": "Tradicional"}]},
  ["Las diluciones suelen no contener moléculas del producto original.",
   "No debe reemplazar tratamientos eficaces.",
   "EsSalud ofrece terapias complementarias como apoyo."],
  "OMS – Estrategia sobre medicina tradicional 2014-2023 · NCCIH – Homeopathy (2021)")

# PED-143 · árbol
A("PED-143", "rn-bradicardia-fetal-convulsion-2-horas-fenobarbital", "Convulsiones neonatales",
  "PEDIATRÍA ENAM: CONVULSIONES NEONATALES", "PEDIATRÍA",
  ("Convulsiones neonatales", ["Causa más frecuente: encefalopatía hipóxico-isquémica",
   "Corregir glucosa y calcio; fármaco de primera línea: fenobarbital"]),
  ("RN a término por cesárea por bradicardia fetal", ["A las 2 horas de vida", "Movimientos tónico-clónicos generalizados"]),
  Q("¿Hipoglucemia o hipocalcemia?", [
      L("Sí", "Corregir", ["Dextrosa o gluconato de calcio"]),
      Q("¿Persiste la convulsión?", [
          L("Sí", "FENOBARBITAL 20 mg/kg EV", ["Primera línea"], path=True),
          L("Refractaria", "Levetiracetam o midazolam", ["Segunda línea"])],
        edge="No", path=True)], path=True),
  ("Causas de convulsión neonatal", [("Frecuencia", True)], [
      ("Encefalopatía hipóxica", ["La más frecuente"]),
      ("ACV o hemorragia", ["Segunda"]),
      ("Metabólicas", ["Glucosa, calcio, sodio"])]),
  ["Confirmar con EEG: muchas convulsiones neonatales son sutiles.",
   "Hipotermia terapéutica si es EHI moderada o grave (< 6 h).",
   "Fenitoína: segunda línea por su farmacocinética errática."],
  "ILAE – Guidelines on neonatal seizures (2023) · " + NELSON)

# NEF-065 · fases
V("fases", "NEF-065", "anciano-sintomas-prostaticos-alfa-bloqueante", "HBP: tratamiento escalonado",
  "NEFROLOGÍA ENAM: HIPERPLASIA PROSTÁTICA", "NEFROLOGÍA",
  ("Hiperplasia benigna de próstata", ["Síntomas de llenado y vaciado con próstata agrandada difusa",
   "Tratamiento inicial: bloqueador alfa-1 (tamsulosina)"]),
  ("Varón de 76 años con 1 año de síntomas", ["Polaquiuria, urgencia, vaciado incompleto, goteo", "Próstata aumentada difusa · PSA 5"]),
  {"rotulo": "Escalones", "ans": 1,
   "fases": [("Leves", "IPSS < 8", "Vigilancia", ["Medidas generales"]),
             ("Molestos", "IPSS ≥ 8", "ALFA-BLOQUEANTE", ["Tamsulosina"]),
             ("Grande", "> 40 mL", "+ Finasteride", ["Reduce el tamaño"]),
             ("Complicada", "Retención, ERC", "Cirugía", ["RTU de próstata"])],
   "curvas": [],
   "chips_titulo": "Tratamiento inicial · marcado el correcto",
   "chips": [("Alfa-bloqueantes", True), ("RTU", False), ("Agonistas GnRH", False), ("Láser", False)]},
  ["Efecto adverso: hipotensión ortostática.",
   "Finasteride baja el PSA a la mitad.",
   "Agonistas GnRH: cáncer de próstata avanzado."],
  "EAU – Management of non-neurogenic male LUTS (2024) · AUA – BPH guideline (2023)")

# OFT-033 · puntaje
V("puntaje", "OFT-033", "dolor-ocular-halos-midriasis-media-acetazolamida", "Glaucoma agudo de ángulo cerrado",
  "OFTALMOLOGÍA ENAM: GLAUCOMA AGUDO", "OFTALMOLOGÍA",
  ("Glaucoma agudo de ángulo cerrado", ["El iris bloquea el drenaje: PIO muy alta",
   "Emergencia: acetazolamida + colirios hipotensores + pilocarpina"]),
  ("Mujer de 60 años con 4 horas de síntomas", ["Visión borrosa, halos, dolor intenso, náuseas", "Cámara estrecha, midriasis media arreactiva, ojo duro"]),
  {"rotulo": "Signos en el caso", "escala": "Cierre angular", "total": 7, "max": 7,
   "total_label": "Signos presentes",
   "interpreta": "Glaucoma agudo de ángulo cerrado",
   "items": [("Dolor ocular intenso", "1", True), ("Halos alrededor de las luces", "1", True),
             ("Visión borrosa", "1", True), ("Náuseas y vómitos", "1", True),
             ("Cámara anterior estrecha", "1", True), ("Midriasis media arreactiva", "1", True),
             ("Ojo duro a la palpación", "1", True)],
   "bandas": [("0-2", "Poco probable", "Otras causas de ojo rojo", False),
              ("≥ 3", "Cierre angular", "ACETAZOLAMIDA 500 mg + timolol + pilocarpina", True)]},
  ["Tratamiento definitivo: iridotomía con láser (también en el otro ojo).",
   "Evitar midriáticos y anticolinérgicos.",
   "Manitol EV si la PIO no baja."],
  "AAO – Preferred Practice Pattern: Primary angle-closure disease (2020) · EGS – Guidelines 5.ª ed. (2020)")

# REU-041 · matriz
V("matriz", "REU-041", "costras-mielicericas-boca-antebrazos-mupirocina", "Impétigo: tratamiento",
  "DERMATOLOGÍA ENAM: IMPÉTIGO", "DERMATOLOGÍA",
  ("Impétigo", ["Costras color miel por S. aureus o S. pyogenes",
   "Pocas lesiones: antibiótico tópico (mupirocina)"]),
  ("Varón de 16 años sin afectación general", ["Costras mielicéricas escasas en boca y antebrazos", "Hermano con lesiones similares"]),
  {"rotulo": "Según la extensión", "eje_x": "Aspecto", "eje_y": "Forma",
   "cols": ["Clínica", "Tratamiento"], "rows": ["Localizado", "Extenso", "Ectima"], "caso": (0, 1),
   "cells": [[("Pocas lesiones", ["Sin fiebre"]), ("MUPIROCINA TÓPICA", ["5 días"])],
             [("Muchas lesiones o brote", []), ("Cefalexina oral", ["O dicloxacilina"])],
             [("Úlcera profunda", []), ("Antibiótico oral", [])]]},
  ["Lavar con agua y jabón y retirar costras.",
   "Muy contagioso: higiene y no compartir toallas.",
   "Complicación: glomerulonefritis postestreptocócica."],
  "IDSA – Skin and soft tissue infections guideline (2014) · AAP Red Book (2024)")

# NRL-041 · matriz
V("matriz", "NRL-041", "caida-escaleras-intervalo-lucido-midriasis-epidural", "Hematomas intracraneales",
  "NEUROLOGÍA ENAM: HEMATOMA EPIDURAL", "NEUROLOGÍA",
  ("Hematoma epidural", ["Lesión de la arteria meníngea media (fractura temporal/parietal)",
   "Intervalo lúcido y midriasis ipsilateral"]),
  ("Varón de 65 años que cayó por las escaleras", ["Pérdida inicial de conciencia, luego lucidez y somnolencia", "Midriasis derecha fija · Glasgow 10"]),
  {"rotulo": "Tipos de lesión", "eje_x": "Aspecto", "eje_y": "Lesión",
   "cols": ["TC", "Clínica"], "rows": ["Epidural", "Subdural agudo", "Axonal difusa", "Contusión"], "caso": (0, 1),
   "cells": [[("Biconvexa (lente)", ["Arteria meníngea media"]), ("INTERVALO LÚCIDO", ["Midriasis ipsilateral"])],
             [("Semiluna", ["Venas puente"]), ("Deterioro progresivo", ["Ancianos, alcohol"])],
             [("TC casi normal", []), ("Coma desde el inicio", [])],
             [("Focos hiperdensos", []), ("Variable", [])]]},
  ["Tratamiento: craneotomía urgente y evacuación.",
   "Glasgow ≤ 8: intubar.",
   "No respeta suturas el subdural; el epidural sí las respeta."],
  "Brain Trauma Foundation – Surgical management of acute epidural hematomas (2006) · " + ATLS)

# CIR-086 · puntaje
V("puntaje", "CIR-086", "litiasis-dolor-hcd-fiebre-masa-colecistitis", "Colecistitis aguda: criterios de Tokio",
  "CIRUGÍA ENAM: COLECISTITIS AGUDA", "CIRUGÍA",
  ("Colecistitis aguda litiásica", ["Inflamación local (Murphy, masa, dolor en HCD) + inflamación sistémica",
   "La ecografía confirma el diagnóstico"]),
  ("Varón de 60 años con litiasis vesicular", ["Dolor en HCD de 20 h, vómitos, alza térmica", "Taquicardia · masa dolorosa subcostal derecha"]),
  {"rotulo": "Criterios de Tokio en el caso", "escala": "Tokio 2018", "total": 3, "max": 5,
   "total_label": "Criterios presentes",
   "interpreta": "Sospecha de colecistitis (A + B)",
   "items": [("A: dolor en HCD", "1", True), ("A: masa en HCD", "1", True),
             ("B: fiebre", "1", True), ("B: PCR o leucocitos altos", "1", False),
             ("C: imagen compatible", "1", False)],
   "bandas": [("Solo A o B", "Posible", "Estudiar", False),
              ("A + B", "Sospecha", "Ecografía para confirmar", True),
              ("A + B + C", "Definitiva", "Colecistectomía temprana", False)]},
  ["Ecografía: pared > 4 mm, líquido perivesicular, Murphy ecográfico.",
   "Colecistectomía laparoscópica en las primeras 72 h.",
   "Úlcera perforada: neumoperitoneo."],
  "Tokyo Guidelines – TG18 diagnostic criteria for acute cholecystitis (2018)")

# INF-077 · puntaje
V("puntaje", "INF-077", "adolescente-amigdalas-exudativas-hepatoesplenomegalia-mononucleosis", "Mononucleosis infecciosa",
  "INFECTOLOGÍA ENAM: MONONUCLEOSIS INFECCIOSA", "INFECTOLOGÍA",
  ("Mononucleosis infecciosa (VEB)", ["Faringitis exudativa, adenopatías cervicales y hepatoesplenomegalia",
   "Linfocitos atípicos y anticuerpos heterófilos (Monotest)"]),
  ("Paciente de 12 años con 10 días de odinofagia", ["Amígdalas exudativas, adenopatías cervicales", "Hepatoesplenomegalia · exantema maculopapular"]),
  {"rotulo": "Hallazgos típicos en el caso", "escala": "Mononucleosis", "total": 4, "max": 5,
   "total_label": "Hallazgos presentes",
   "interpreta": "Mononucleosis probable",
   "items": [("Faringoamigdalitis exudativa", "1", True), ("Adenopatías cervicales", "1", True),
             ("Hepatoesplenomegalia", "1", True), ("Exantema maculopapular", "1", True),
             ("Fiebre", "1", False)],
   "bandas": [("0-1", "Poco probable", "Buscar otra causa", False),
              ("≥ 3", "Probable", "Monotest y frotis; evitar deportes de contacto", True)]},
  ["Amoxicilina en mononucleosis provoca exantema.",
   "Riesgo de rotura esplénica: sin deportes por 3-4 semanas.",
   "Adenopatías posteriores sugieren VEB más que estreptococo."],
  "AAP Red Book: Epstein-Barr virus infections (2024) · " + HARRISON)

# TRA-031 · radial
V("radial", "TRA-031", "fractura-tercio-medio-humero-mano-pendula-radial", "Nervios en las fracturas de húmero",
  "TRAUMATOLOGÍA ENAM: LESIÓN DEL NERVIO RADIAL", "TRAUMATOLOGÍA",
  ("Nervio radial y húmero", ["Corre por el surco espiral del tercio medio",
   "Lesión: mano péndula (no extiende muñeca ni dedos)"]),
  ("Varón de 20 años tras accidente de tránsito", ["Deformidad del tercio medio del brazo", "Mano péndula · Rx: fractura del tercio medio"]),
  {"rotulo": "Mapa del tema", "centro": "HÚMERO", "centro_sub": "Fractura y nervios", "ans": 0,
   "items": [("NERVIO RADIAL", ["Tercio medio (surco espiral)", "Mano péndula"]),
             ("Axilar", ["Cuello quirúrgico"]),
             ("Mediano", ["Supracondílea"]),
             ("Cubital", ["Epicóndilo medial"]),
             ("Arteria braquial", ["Supracondílea en niños"])],
   "ruta": ["Fractura del tercio medio", "Surco del nervio radial", "No extiende la muñeca", "NERVIO RADIAL"]},
  ["La mayoría de lesiones radiales cerradas se recupera sola (neuropraxia).",
   "Explorar si aparece tras la reducción o si es fractura abierta.",
   "Férula de extensión de muñeca mientras se recupera."],
  "AAOS – Humeral shaft fractures (2023) · Rockwood and Green's Fractures in Adults 10.ª ed. (2024)")

# NEF-066 · termómetro
V("termometro", "NEF-066", "adolescente-dolor-testicular-subito-testiculo-alto-torsion", "Torsión testicular",
  "NEFROLOGÍA ENAM: TORSIÓN TESTICULAR", "NEFROLOGÍA",
  ("Torsión testicular", ["Dolor testicular súbito, testículo alto y horizontal",
   "Emergencia: la viabilidad depende del tiempo"]),
  ("Adolescente de 13 años", ["Dolor intenso y súbito de 3 horas", "Testículo derecho aumentado y en posición alta"]),
  {"rotulo": "Tiempo de evolución",
   "niveles": [("< 6 h", "Salvable", ["> 90% de viabilidad"]),
               ("6-12 h", "En riesgo", ["~ 50%"]),
               ("> 24 h", "Casi perdido", ["< 10%"])],
   "caso_nivel": 0, "ruta_titulo": "Conducta", "paso_label": "PASO",
   "pasos": [(1, "EXPLORACIÓN QUIRÚRGICA", ["No retrasar por el Doppler"], True),
             (2, "Detorsión y orquidopexia", ["Bilateral"], False),
             (3, "Orquiectomía", ["Si no es viable"], False)]},
  ["Reflejo cremastérico ausente apoya la torsión.",
   "Signo de Prehn negativo (el dolor no cede al elevar).",
   "Torsión del apéndice testicular: «punto azul»."],
  "AUA – Pediatric urology: acute scrotum (2023) · EAU/ESPU – Paediatric urology guidelines (2024)")

# REU-042 · puntaje
V("puntaje", "REU-042", "poliartritis-simetrica-manos-rigidez-anti-ccp", "Artritis reumatoide: criterios",
  "REUMATOLOGÍA ENAM: ARTRITIS REUMATOIDE", "REUMATOLOGÍA",
  ("Artritis reumatoide", ["Poliartritis simétrica de pequeñas articulaciones con rigidez prolongada",
   "Anti-CCP: marcador diagnóstico (muy específico) y pronóstico"]),
  ("Mujer de 24 años con 3 meses de síntomas", ["Dolor y tumefacción en manos, muñecas y rodillas", "Simétrica · rigidez matutina prolongada"]),
  {"rotulo": "Criterios ACR/EULAR 2010 sin serología", "escala": "ACR/EULAR 2010", "total": 4, "max": 10,
   "total_label": "Puntaje sin laboratorio",
   "interpreta": "Faltan la serología y los reactantes",
   "items": [("4-10 articulaciones pequeñas", "3", True), ("> 10 articulaciones", "5", False),
             ("FR o anti-CCP positivos", "2-3", False), ("PCR o VSG altas", "1", False),
             ("Duración ≥ 6 semanas", "1", True)],
   "bandas": [("< 6", "Aún no clasifica", "PEDIR ANTI-CCP Y FR", True),
              ("≥ 6", "Artritis reumatoide", "Metotrexato precoz", False)]},
  ["Anti-CCP alto: enfermedad más erosiva.",
   "Anti-Smith y anti-DNA: lupus; anticentrómero: esclerosis limitada.",
   "Iniciar FAME en los primeros 3 meses."],
  "ACR/EULAR – Classification criteria for rheumatoid arthritis (2010) · EULAR – RA management recommendations (2022)")

# PED-144 · puntaje
V("puntaje", "PED-144", "prematuro-32-semanas-quejido-broncograma-membrana-hialina", "Dificultad respiratoria del prematuro",
  "PEDIATRÍA ENAM: ENFERMEDAD DE MEMBRANA HIALINA", "PEDIATRÍA",
  ("Enfermedad de membrana hialina", ["Déficit de surfactante: dificultad respiratoria desde el nacimiento",
   "Rx: patrón reticulogranular fino y broncograma aéreo"]),
  ("Neonato de 32 semanas, 2 horas de vida", ["Aleteo, quejido, tiraje intercostal marcado", "SatO₂ 88% · Rx: reticular fino con broncogramas"]),
  {"rotulo": "Silverman-Andersen en el caso", "escala": "Silverman-Andersen", "total": 6, "max": 10,
   "total_label": "Puntaje del caso",
   "interpreta": "Dificultad moderada por membrana hialina",
   "items": [("Tiraje intercostal marcado", "2", True), ("Aleteo nasal", "2", True),
             ("Quejido audible", "2", True), ("Retracción xifoidea", "0-2", False),
             ("Disociación toracoabdominal", "0-2", False)],
   "bandas": [("0-3", "Leve", "Oxígeno y vigilancia", False),
              ("4-6", "Moderada", "CPAP + surfactante", True),
              ("7-10", "Grave", "Intubar + surfactante", False)]},
  ["Taquipnea transitoria: cesárea, término, mejora en 24-72 h.",
   "Neumonía neonatal: RPM prolongada, fiebre materna.",
   "Corticoides prenatales previenen la membrana hialina."],
  "European Consensus Guidelines on RDS (2022) · " + NELSON)

# GAS-054 · puntaje
V("puntaje", "GAS-054", "fiebre-ictericia-dolor-coledoco-15-mm-colangitis", "Colangitis aguda",
  "GASTROENTEROLOGÍA ENAM: COLANGITIS AGUDA", "GASTROENTEROLOGÍA",
  ("Colangitis aguda", ["Infección de la vía biliar obstruida (coledocolitiasis)",
   "Tríada de Charcot: fiebre, ictericia y dolor en HCD"]),
  ("Mujer de 32 años con ictericias previas", ["Dolor en HCD, fiebre 39 °C, ictericia", "Colédoco de 15 mm en la ecografía"]),
  {"rotulo": "Charcot y Reynolds en el caso", "escala": "Charcot / Reynolds", "total": 3, "max": 5,
   "total_label": "Signos presentes",
   "interpreta": "Tríada de Charcot completa",
   "items": [("Fiebre", "1", True), ("Ictericia", "1", True), ("Dolor en HCD", "1", True),
             ("Hipotensión", "1", False), ("Confusión", "1", False)],
   "bandas": [("< 3", "Incompleta", "Estudiar la vía biliar", False),
              ("3", "Charcot", "Antibiótico + CPRE en 24-48 h", True),
              ("5", "Reynolds", "CPRE urgente + soporte", False)]},
  ["La CPRE drena y extrae el cálculo.",
   "Luego colecistectomía.",
   "Colecistitis: sin ictericia importante ni colédoco dilatado."],
  "Tokyo Guidelines – TG18: Acute cholangitis (2018) · ASGE – Choledocholithiasis (2019)")

# REU-043 · termómetro
V("termometro", "REU-043", "picadura-abejas-estridor-hipotension-adrenalina", "Anafilaxia por picadura de abejas",
  "INMUNOLOGÍA ENAM: ANAFILAXIA", "INMUNOLOGÍA",
  ("Anafilaxia", ["Reacción sistémica grave: vía aérea, respiración o circulación",
   "Tratamiento de elección: adrenalina IM inmediata"]),
  ("Joven de 20 años con picaduras de abejas", ["Disnea, estridor, sibilantes, cianosis", "PA 80/50, FC 120"]),
  {"rotulo": "Gravedad de la reacción",
   "niveles": [("Grado I", "Solo piel", ["Urticaria, angioedema"]),
               ("Grado II", "Moderada", ["Disnea leve, taquicardia"]),
               ("Grado III", "Grave", ["Estridor, hipotensión, cianosis"])],
   "caso_nivel": 2, "ruta_titulo": "Tratamiento", "paso_label": "PASO",
   "pasos": [(1, "ADRENALINA IM 0.5 mg", ["Muslo; repetir a los 5-15 min"], True),
             (2, "O₂ + fluidos EV", ["Decúbito con piernas elevadas"], False),
             (3, "Antihistamínico + corticoide", ["Complementarios"], False)]},
  ["Los antihistamínicos no tratan la obstrucción ni el choque.",
   "Observar 6-12 horas por reacción bifásica.",
   "Indicar autoinyector de adrenalina y referir a alergología."],
  "WAO – Anaphylaxis guidance (2020) · EAACI – Anaphylaxis guidelines (2021)")

# GIN-145 · embudo
V("embudo", "GIN-145", "gestante-28-semanas-fiebre-puno-percusion-ceftriaxona", "Pielonefritis en la gestante",
  "OBSTETRICIA ENAM: PIELONEFRITIS EN EL EMBARAZO", "OBSTETRICIA",
  ("Pielonefritis en el embarazo", ["Fiebre, dolor lumbar y puñopercusión positiva",
   "Hospitalizar y dar ceftriaxona EV"]),
  ("Gestante de 28 semanas", ["Malestar, dolor lumbar, fiebre 39 °C", "Puñopercusión lumbar derecha (+)"]),
  {"rotulo": "Embudo de antibióticos",
   "inicio": "Gestante con pielonefritis",
   "candidatos": ["Ceftriaxona", "Nitrofurantoína", "Doxiciclina", "Azitromicina", "Clindamicina"],
   "pasos": [("Pielonefritis: necesita niveles en sangre y riñón", ["Nitrofurantoína"]),
             ("Segura en el embarazo", ["Doxiciclina"]),
             ("Cubre E. coli y gramnegativos", ["Azitromicina", "Clindamicina"])],
   "final": ("CEFTRIAXONA", ["EV, hospitalizada", "Pasar a oral al mejorar"]),
   "nota": "Tras tratarla: profilaxis o urocultivo mensual hasta el parto."},
  ["Complicaciones: parto pretérmino, sepsis, SDRA.",
   "Urocultivo antes del antibiótico.",
   "Doxiciclina: contraindicada en el embarazo."],
  "ACOG – Clinical consensus N.° 4: UTI in pregnancy (2023) · " + WILLIAMS)

# TRA-032 · puntaje
V("puntaje", "TRA-032", "aplastamiento-dolor-refractario-palidez-sin-pulso-compartimental", "Síndrome compartimental",
  "TRAUMATOLOGÍA ENAM: SÍNDROME COMPARTIMENTAL", "TRAUMATOLOGÍA",
  ("Síndrome compartimental agudo", ["Presión alta en un compartimento cerrado: isquemia muscular",
   "Dolor desproporcionado es el signo más precoz; tratamiento: fasciotomía"]),
  ("Varón de 36 años aplastado por una pared", ["Parestesias y dolor refractario", "Palidez, tumefacción, pulso pedio ausente"]),
  {"rotulo": "Las «5 P» en el caso", "escala": "5 P", "total": 4, "max": 5,
   "total_label": "Signos presentes",
   "interpreta": "Síndrome compartimental",
   "items": [("Dolor desproporcionado", "1", True), ("Parestesias", "1", True),
             ("Palidez", "1", True), ("Pulso ausente", "1", True), ("Parálisis", "1", False)],
   "bandas": [("0-1", "Poco probable", "Vigilar", False),
              ("≥ 2", "Compartimental", "FASCIOTOMÍA urgente", True)]},
  ["El pulso ausente es tardío: no esperar a que falte.",
   "Presión compartimental > 30 mmHg o delta < 30: fasciotomía.",
   "Vigilar rabdomiólisis e hiperpotasemia."],
  "BOA/BAPRAS – BOAST 10: Diagnosis and management of compartment syndrome (2016) · " + ATLS)

# CB-054 · matriz
V("matriz", "CB-054", "discoteca-trago-flumazenilo-despierta-benzodiacepina", "Intoxicaciones y antídotos",
  "CIENCIAS BÁSICAS ENAM: INTOXICACIÓN POR BENZODIACEPINAS", "CIENCIAS BÁSICAS",
  ("Intoxicación por benzodiacepinas", ["Sopor, disartria, ataxia con respiración conservada",
   "Responde al flumazenilo (antagonista GABA-A)"]),
  ("Varón de 35 años en una discoteca", ["Disartria, ataxia, hipotonía · FR 16", "Despierta con flumazenilo · le invitaron un trago"]),
  {"rotulo": "Toxíndromes y antídotos", "eje_x": "Aspecto", "eje_y": "Tóxico",
   "cols": ["Clínica", "Antídoto"], "rows": ["Benzodiacepinas", "Opioides", "Paracetamol", "Organofosforados"], "caso": (0, 1),
   "cells": [[("Sopor, ataxia", ["Respira bien"]), ("FLUMAZENILO", ["Despierta"])],
             [("Miosis, apnea", []), ("Naloxona", [])],
             [("Daño hepático", []), ("N-acetilcisteína", [])],
             [("Miosis, broncorrea", []), ("Atropina + pralidoxima", [])]]},
  ["Flumazenilo puede precipitar convulsiones en usuarios crónicos.",
   "Sumisión química: registrar y denunciar.",
   "El soporte es el pilar del tratamiento."],
  "Goldfrank's Toxicologic Emergencies 11.ª ed. (2019)")

# PED-145 · fases
V("fases", "PED-145", "neonato-10-dias-vomitos-explosivos-oliva-ecografia", "Estenosis hipertrófica del píloro",
  "PEDIATRÍA ENAM: ESTENOSIS HIPERTRÓFICA DEL PÍLORO", "PEDIATRÍA",
  ("Estenosis hipertrófica del píloro", ["Vómitos en proyectil no biliosos a las 2-6 semanas",
   "«Oliva» pilórica; diagnóstico con ecografía"]),
  ("Neonato varón de 10 días", ["Vómitos explosivos tras lactar", "Masa palpable en epigastrio"]),
  {"rotulo": "Evolución y manejo", "ans": 2,
   "fases": [("Nacimiento", "Sem 0-2", "Asintomático", ["Engrosamiento progresivo"]),
             ("Síntomas", "Sem 2-6", "Vómitos en proyectil", ["Hambriento tras vomitar"]),
             ("Diagnóstico", "Ya", "ECOGRAFÍA", ["Músculo ≥ 3-4 mm"]),
             ("Cirugía", "Tras corregir", "Piloromiotomía", ["Ramstedt"])],
   "curvas": [],
   "chips_titulo": "Estudio · marcado el correcto",
   "chips": [("Ecografía", True), ("Endoscopía", False), ("Rx simple", False), ("RM", False)]},
  ["Alcalosis metabólica hipoclorémica e hipopotasémica.",
   "Corregir electrolitos antes de operar.",
   "Más frecuente en varones primogénitos; eritromicina neonatal es factor."],
  "APSA – Hypertrophic pyloric stenosis (2020) · " + NELSON)

# PED-146 · radial
V("radial", "PED-146", "rn-tos-asfixia-lactar-sonda-enrollada-atresia-esofagica", "Atresia esofágica",
  "PEDIATRÍA ENAM: ATRESIA ESOFÁGICA", "PEDIATRÍA",
  ("Atresia esofágica", ["El esófago termina en fondo ciego; suele tener fístula traqueal distal",
   "La sonda nasogástrica se enrolla en el bolsón proximal"]),
  ("Recién nacido varón", ["Tos y asfixia al lactar · crepitantes derechos", "Rx: la sonda se enrolla en el esófago proximal"]),
  {"rotulo": "Mapa del tema", "centro": "ATRESIA ESOFÁGICA", "centro_sub": "Recién nacido", "ans": 0,
   "items": [("SONDA ENROLLADA", ["En el bolsón proximal", "Confirma el diagnóstico"]),
             ("Clínica", ["Tos y asfixia al lactar"]),
             ("Tipo C", ["Fístula distal (85%)"]),
             ("Prenatal", ["Polihidramnios"]),
             ("VACTERL", ["Buscar otras anomalías"])],
   "ruta": ["RN con tos al lactar", "Pasar sonda nasogástrica", "Se enrolla en el esófago", "ATRESIA ESOFÁGICA"]},
  ["Nada por boca, aspiración del bolsón y cabecera elevada.",
   "Cirugía: cierre de la fístula y anastomosis.",
   "Aire en el estómago indica fístula distal."],
  "APSA – Esophageal atresia (2021) · " + NELSON)

# PED-147 · tarjetas
V("tarjetas", "PED-147", "vesiculas-costras-papulas-distintos-estadios-varicela", "Exantema vesicular en el niño",
  "PEDIATRÍA ENAM: VARICELA", "PEDIATRÍA",
  ("Varicela", ["Exantema pruriginoso con lesiones en distintos estadios al mismo tiempo",
   "Afecta cuero cabelludo y mucosas"]),
  ("Niño de 5 años con 5 días de lesiones", ["Prurito, malestar, fiebre", "Pápulas, vesículas y costras en cabeza, tronco y mucosas"]),
  {"rotulo": "¿Qué exantema es?", "ans": 0, "cards": [
      {"titulo": "VARICELA", "datos": [
          ("Lesiones", "Pápulas, vesículas, costras", True), ("Dónde", "Cuero cabelludo, mucosas", True),
          ("Clave", "«Cielo estrellado»", True)],
       "pie": "Aciclovir en grupos de riesgo"},
      {"titulo": "Sarampión", "datos": [
          ("Lesiones", "Maculopapular", False), ("Dónde", "Cefalocaudal", False),
          ("Clave", "Koplik y «3 C»", False)],
       "pie": "Notificación inmediata"},
      {"titulo": "Escabiosis", "datos": [
          ("Lesiones", "Pápulas y surcos", False), ("Dónde", "Pliegues", False),
          ("Clave", "Prurito nocturno", False)],
       "pie": "Respeta la cabeza"},
      {"titulo": "Piodermitis", "datos": [
          ("Lesiones", "Pústulas, costras de miel", False), ("Dónde", "Localizadas", False),
          ("Clave", "Sin fiebre ni mucosas", False)],
       "pie": "Impétigo"}]},
  ["Contagia desde 1-2 días antes del exantema hasta que todo sea costra.",
   "Nunca aspirina (síndrome de Reye).",
   "Vacuna contra varicela a los 12 meses (esquema MINSA)."],
  "AAP Red Book: Varicella-zoster infections (2024) · " + NELSON)

# PED-148 · embudo
V("embudo", "PED-148", "preescolar-rinorrea-afebril-faringe-normal-resfrio-comun", "Rinorrea en el preescolar",
  "PEDIATRÍA ENAM: RESFRÍO COMÚN", "PEDIATRÍA",
  ("Resfrío común", ["Infección viral de vías altas: rinorrea, congestión, dolor de garganta leve",
   "Tratamiento sintomático; dura 7-10 días"]),
  ("Niño de 3 años", ["Dolor de garganta, congestión nasal y rinorrea", "Afebril · faringe no congestiva, sin placas"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Preescolar con rinorrea",
   "candidatos": ["Resfrío común", "Faringitis aguda", "Influenza", "Rinosinusitis", "Rinitis vasomotora"],
   "pasos": [("Afebril, faringe no congestiva", ["Faringitis aguda", "Influenza"]),
             ("Cuadro agudo, sin rinorrea > 10 días", ["Rinosinusitis"]),
             ("Viral agudo en un niño pequeño", ["Rinitis vasomotora"])],
   "final": ("RESFRÍO COMÚN", ["Rinovirus el más frecuente", "Lavados nasales, paracetamol"]),
   "nota": "No usar antibióticos ni antitusígenos en menores de 6 años."},
  ["Signos de alarma AIEPI: respiración rápida, tiraje, no bebe.",
   "La rinorrea verdosa no significa infección bacteriana.",
   "6-8 resfríos al año es normal en preescolares."],
  "OMS/OPS – AIEPI · " + NELSON)
