"""Entrega 1 · tanda 04 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, AAP, OMS, IDSA, CDC
from esc28 import HTA_EMB, PAGE, GLASGOW_TEC

CC = " · Wikimedia Commons · "

# REU-007 · Vasculitis con púrpura palpable · TARJETAS
S("tarjetas", "REU-007", "Joven con artralgias, febrícula, púrpura palpable y livedo: vasculitis",
  "Reumatología · vasculitis sistémicas",
  ("Vasculitis", ["Inflamación de la pared de los vasos: la sangre sale y deja púrpura que se palpa.",
                  "Se clasifican por el tamaño del vaso afectado (Chapel Hill 2012)."]),
  ("Mujer de 20 años", ["1 año de artralgias, malestar y febrícula; lesiones en la piel.", "Púrpura palpable y piel marmórea (livedo reticularis)."]),
  ["Púrpura palpable = vasculitis de pequeño vaso (la plaquetopenia da púrpura plana).",
   "Estudiar: hemograma, función renal, orina (hematuria), ANCA, complemento, crioglobulinas, hepatitis B y C; biopsia de piel.",
   "Livedo + nódulos o mononeuritis: pensar en poliarteritis nodosa (vaso mediano)."],
  "Chapel Hill Consensus Conference (2012); ACR/EULAR, criterios de clasificación de vasculitis (2022); " + HARRISON + ".",
  op=("¿Encaja?", ["No: poliartritis sin púrpura", "No: mecánica, sin inflamación", "Sí: púrpura palpable + síntomas generales",
                   "No: piel dura, Raynaud", "No: dolor difuso sin lesiones"]),
  d=dict(rotulo="Artralgias con lesiones de piel", ans=0,
         cards=[dict(titulo="Vasculitis", datos=[("Piel", "Púrpura palpable, livedo", True), ("Síntomas", "Fiebre, malestar", True),
                                               ("Prueba", "Biopsia, ANCA", True)], pie="Este caso."),
                dict(titulo="Artritis reumatoide", datos=[("Piel", "Nódulos", False), ("Articulación", "Poliartritis", False),
                                                        ("Prueba", "Anti-CCP", False)], pie="Sin púrpura."),
                dict(titulo="Esclerodermia", datos=[("Piel", "Dura, engrosada", False), ("Manos", "Raynaud", False),
                                                  ("Prueba", "Anti-Scl-70", False)], pie="Fibrosis."),
                dict(titulo="Fibromialgia", datos=[("Piel", "Normal", False), ("Dolor", "Difuso", False),
                                                 ("Labs", "Normales", False)], pie="Sin inflamación.")]),
  escala=dict(nombre="Vasculitis por tamaño del vaso (Chapel Hill)", orden=False, que="Clasificación de 2012: orienta qué vasculitis buscar.",
              grados=[("Vaso grande", "Aorta y ramas", ["Arteritis de Takayasu", "Arteritis de células gigantes"]),
                      ("Vaso mediano", "Arterias viscerales", ["Poliarteritis nodosa", "Kawasaki"]),
                      ("Vaso pequeño", "Capilares, vénulas", ["ANCA: granulomatosis con poliangeítis", "IgA, crioglobulinémica"])],
              caso=2, porque=[("La púrpura palpable indica vasos pequeños de la piel", True), ("El livedo obliga a descartar también vaso mediano", False)],
              conducta="Biopsia de piel con inmunofluorescencia, ANCA, complemento, serologías y orina."))

# GIN-019 · VIH diagnosticado en el parto · ÁRBOL
S("arbol", "GIN-019", "Prueba rápida de VIH positiva en trabajo de parto inicial con membranas íntegras y sin TAR: cesárea",
  "VIH y embarazo · prevención de la transmisión vertical",
  ("Prevención de la transmisión materno-infantil del VIH", ["Sin TAR ni carga viral conocida, el parto vaginal expone al bebé a sangre y secreciones.",
                                                             "La cesárea antes de romper membranas reduce la transmisión."]),
  ("Gestante de 37 semanas en trabajo de parto", ["4 cm de dilatación, membranas íntegras.", "Prueba rápida de VIH positiva (sin TAR previo)."]),
  ["Carga viral desconocida o > 1000 copias: cesárea, idealmente antes de romper membranas; zidovudina EV intraparto + iniciar TAR.",
   "Recién nacido: profilaxis antirretroviral según riesgo y lactancia artificial (MINSA).",
   "Con TAR y carga viral indetectable (< 50) el parto puede ser vaginal."],
  "DHHS, Perinatal HIV clinical guidelines (2024); " + MINSA + ", NTS de prevención de la transmisión materno-infantil del VIH, sífilis y hepatitis B (2024).",
  op=("¿Manejo?", ["No: aumenta la exposición", "No: aumenta la exposición", "No: sin TAR ni carga viral", "Sí: membranas íntegras, sin TAR",
                   "No: la episiotomía aumenta la exposición"]),
  arbol=Q("Gestante con VIH en el parto: ¿carga viral < 1000 con TAR?", [
      L("Sí", "Parto vaginal posible", ["Continuar TAR", "Profilaxis al RN"]),
      L("No o desconocida (este caso)", "CESÁREA", ["Zidovudina EV intraparto", "Iniciar TAR; profilaxis al RN"], path=True)], path=True))

# CB-005 · Anafilaxia: el mastocito · TARJETAS
S("tarjetas", "CB-005", "Dificultad respiratoria e hipotensión tras penicilina IM (hipersensibilidad tipo I): el mastocito",
  "Inmunología · hipersensibilidad inmediata",
  ("Hipersensibilidad tipo I (anafilaxia)", ["La IgE se pega a los mastocitos; al volver el alérgeno, el mastocito se degranula.",
                                              "Histamina, leucotrienos y triptasa: broncoespasmo, edema, vasodilatación e hipotensión."]),
  ("Mujer de 20 años", ["Dificultad respiratoria e hipotensión tras penicilina IM.", "Hipersensibilidad mediada por IgE."]),
  ["Tratamiento: adrenalina IM 0,5 mg (0,01 mg/kg) en la cara lateral del muslo, repetir a los 5-15 min; luego fluidos y oxígeno.",
   "Triptasa sérica 1-2 h después confirma la activación del mastocito.",
   "La célula plasmática produce la IgE, pero la que libera los mediadores es el mastocito (y el basófilo)."],
  "WAO, anaphylaxis guidance (2020, act.); EAACI (2021); Abbas, Inmunología celular y molecular 10.ª ed.",
  op=("¿Responsable directo?", ["No: es tipo IV o presentación", "Produce la IgE, no la libera", "No: es tipo IV", "Sí: libera histamina",
                                "No: inflamación aguda"]),
  d=dict(rotulo="Tipos de hipersensibilidad (Gell y Coombs)", ans=0,
         cards=[dict(titulo="Tipo I: inmediata", datos=[("Anticuerpo", "IgE", True), ("Célula", "Mastocito", True),
                                                      ("Ejemplo", "Anafilaxia", True)], pie="Este caso."),
                dict(titulo="Tipo II: citotóxica", datos=[("Anticuerpo", "IgG, IgM", False), ("Blanco", "Célula", False),
                                                        ("Ejemplo", "Hemólisis", False)], pie="Contra la célula."),
                dict(titulo="Tipo III: inmunocomplejos", datos=[("Anticuerpo", "Complejos", False), ("Daño", "Vasos, riñón", False),
                                                              ("Ejemplo", "Lupus", False)], pie="Depósito."),
                dict(titulo="Tipo IV: tardía", datos=[("Célula", "Linfocito T", False), ("Tiempo", "48-72 h", False),
                                                    ("Ejemplo", "PPD, contacto", False)], pie="Sin anticuerpos.")]))

# NEU-004 · Tuberculosis pleural · ÁRBOL + criterios de Light
S("arbol", "NEU-004", "Exudado pleural linfocítico con ADA de 55 U/L en un joven con tos de 2 meses: tuberculosis pleural",
  "Tuberculosis extrapulmonar · derrame pleural",
  ("Tuberculosis pleural", ["Reacción de hipersensibilidad a pocos bacilos en la pleura: exudado con linfocitos.",
                            "En el Perú es la primera causa de derrame pleural en jóvenes."]),
  ("Varón de 23 años", ["2 meses de tos seca; Rx con borramiento del seno costofrénico derecho.",
                        "Líquido: LDH pleural/sérica > 0,6, proteínas pleural/sérica > 0,5, linfocitos, ADA 55 U/L."]),
  ["Exudado linfocítico + ADA > 40 U/L en zona de alta prevalencia = TB pleural; iniciar tratamiento.",
   "El Xpert y el cultivo del líquido suelen salir negativos; la biopsia pleural confirma (granulomas).",
   "Esquema antituberculoso de 6 meses (2HRZE/4HR)."],
  OMS + ", consolidated guidelines on tuberculosis (2024); " + MINSA + ", NTS de tuberculosis (2023); BTS, pleural disease (2023).",
  op=("¿Encaja?", ["No: placas pleurales, exposición laboral", "Sí: exudado linfocítico + ADA alta", "Posible ADA alta, pero menos frecuente",
                   "No: neutrófilos y neumonía", "No: es trasudado"]),
  arbol=Q("Derrame pleural: ¿cumple algún criterio de Light?", [
      Q("¿Predominan los linfocitos y el ADA es > 40 U/L?", [
          L("Sí: ADA 55 (este caso)", "TUBERCULOSIS PLEURAL", ["2HRZE/4HR", "Biopsia si hay duda"], path=True),
          L("Neutrófilos", "Paraneumónico", ["pH y glucosa: ¿drenar?"])], edge="Sí: exudado", path=True),
      L("No", "Trasudado", ["Falla cardiaca, cirrosis, nefrótico"])], path=True),
  triada=TR([("Proteína pleural/sérica > 0,5", "Cumple", True), ("LDH pleural/sérica > 0,6", "Cumple", True),
             ("LDH pleural > 2/3 del límite normal", "No se informa", False)],
            [("Criterios de Light (basta 1 = exudado)", 0, 2)],
            "Cumple dos de tres: es un exudado. Con linfocitos y ADA alta, tuberculosis.", rotulo="Criterios con nombre propio"))

# PED-028 · Púrpura trombocitopénica inmune · ÁRBOL + fases de la PTI
S("arbol", "PED-028", "Niño de 15 meses con petequias, equimosis y epistaxis 2 semanas tras la vacuna, plaquetas 20 000 y resto normal: PTI",
  "Trastornos plaquetarios · púrpura trombocitopénica inmune",
  ("Púrpura trombocitopénica inmune (PTI)", ["Anticuerpos destruyen las plaquetas tras una infección viral o una vacuna (SPR).",
                                             "Solo bajan las plaquetas; sin visceromegalias ni otras series alteradas."]),
  ("Niño de 15 meses", ["Vacuna contra el sarampión hace 2 semanas.", "Petequias, equimosis y epistaxis; Hb 11, leucocitos normales, plaquetas 20 000."]),
  ["Sin sangrado o solo en piel: observación aunque las plaquetas estén bajas (ASH 2019).",
   "Sangrado de mucosas o que no cede: corticoide corto o inmunoglobulina EV.",
   "Si hay anemia, leucocitos anormales, visceromegalias o dolor óseo: médula ósea para descartar leucemia."],
  "ASH, guía de PTI (2019); International Consensus Report on ITP (2019); " + NELSON + ".",
  op=("¿Encaja?", ["No: Hb y leucocitos normales, sin visceromegalia", "No: plaquetas normales, púrpura en piernas",
                   "No: afecta las tres series", "Sí: plaquetopenia aislada tras vacuna", "No: plaquetas normales, sangrado articular"]),
  arbol=Q("Plaquetas bajas aisladas: ¿sangrado más allá de la piel?", [
      L("Sí: epistaxis (este caso)", "PTI CON SANGRADO DE MUCOSA", ["Prednisona corta o inmunoglobulina EV", "Hospitalizar si no cede"], path=True),
      L("No: solo petequias", "Observar", ["Evitar AINE y traumatismos"])], path=True),
  escala=dict(nombre="Fases de la PTI", orden=True, que="Grupo de Trabajo Internacional (IWG): por el tiempo desde el diagnóstico.",
              grados=[("< 3 meses", "Recién diagnosticada", ["La mayoría de los niños se cura sola"]),
                      ("3-12 meses", "Persistente", ["Sin remisión aún"]), ("> 12 meses", "Crónica", ["Más frecuente en adolescentes y adultos"])],
              caso=0, porque=[("Inicio hace pocos días, 2 semanas después de la vacuna", True)],
              conducta="Epistaxis: tratar con corticoide corto o inmunoglobulina; control de plaquetas."))

# PED-029 · Urocultivo falso negativo · TARJETAS
S("tarjetas", "PED-029", "Urocultivo negativo en un niño con fiebre y síntomas urinarios: lo más probable es que haya recibido antibiótico",
  "Infección urinaria en pediatría · interpretación del urocultivo",
  ("Errores del urocultivo", ["Falso negativo: hay infección pero no crece (antibiótico previo, orina muy diluida, germen exigente).",
                              "Falso positivo: crece sin infección (contaminación con flora perineal, demora sin refrigerar)."]),
  ("Niño de 8 años", ["Fiebre y síntomas de infección urinaria.", "Urocultivo falso negativo."]),
  ["Tomar el urocultivo antes del primer antibiótico; es la causa más común de falso negativo.",
   "Orina diluida (mucha agua o diuréticos) también baja el recuento.",
   "La demora sin refrigerar y la contaminación aumentan las colonias: dan falsos positivos."],
  AAP + ", UTI in febrile infants and children 2-24 months (2011, reafirmada 2016); " + NELSON + ".",
  op=("¿Falso negativo?", ["Sí: inhibe el crecimiento", "No: da falso positivo", "No: más bacterias por mL", "No: da falso positivo",
                           "No: da falso positivo"],
      {0: "Antibiótico previo", 1: "Demora en el envío", 2: "Orina muy concentrada", 3: "Orina mal refrigerada", 4: "Contaminación perineal"}),
  d=dict(rotulo="¿Por qué falla el urocultivo?", ans=0,
         cards=[dict(titulo="Antibiótico previo", datos=[("Efecto", "No crece", True), ("Resultado", "Falso negativo", True),
                                                       ("Evitar", "Cultivar antes", True)], pie="Este caso."),
                dict(titulo="Orina muy diluida", datos=[("Efecto", "Pocas colonias", False), ("Resultado", "Falso negativo", False),
                                                      ("Evitar", "Primera orina", False)], pie="Concentrada es lo ideal."),
                dict(titulo="Demora sin frío", datos=[("Efecto", "Bacterias se multiplican", False), ("Resultado", "Falso positivo", False),
                                                    ("Evitar", "Procesar en 1 h o refrigerar", False)], pie="Hasta 24 h a 4 °C."),
                dict(titulo="Contaminación", datos=[("Efecto", "Flora de la piel", False), ("Resultado", "Falso positivo", False),
                                                  ("Evitar", "Chorro medio, sonda", False)], pie="Varios gérmenes.")]))

# PED-030 · Rinitis alérgica · MATRIZ (ARIA)
S("matriz", "PED-030", "Adolescente asmático con años de congestión, prurito y secreción nasal y pérdida del olfato: rinitis alérgica",
  "Enfermedades atópicas · rinitis alérgica",
  ("Rinitis alérgica", ["Inflamación de la mucosa nasal mediada por IgE: estornudos, prurito, rinorrea acuosa y obstrucción.",
                        "Va de la mano con el asma (una sola vía aérea)."]),
  ("Niño de 14 años con asma", ["Años de obstrucción nasal creciente, alteración del gusto y olfato.", "Prurito, secreción nasal; más irritable."]),
  ["Tratamiento de elección: corticoide intranasal (mometasona, fluticasona); antihistamínico oral de 2.ª generación si es leve.",
   "Controlar la rinitis mejora el control del asma.",
   "Clasificación ARIA: duración (intermitente o persistente) × gravedad (leve o moderada-grave)."],
  "ARIA, guía de rinitis alérgica (2019, act. 2024); " + NELSON + ".",
  op=("¿Encaja?", ["No: aguda, con fiebre", "Sí: atopia + síntomas nasales crónicos", "No: niños pequeños, ronquido",
                   "No: unilateral, secreción fétida", "No: aguda, con fiebre y dolor facial"]),
  d=dict(rotulo="Clasificación ARIA de la rinitis alérgica", eje_x="Gravedad", eje_y="Duración",
         cols=["Leve", "Moderada-grave"], rows=["Persistente", "Intermitente", "Con asma"], caso=(0, 1),
         cells=[[("Persistente leve", ["> 4 días/sem y > 4 semanas", "Sin afectar el sueño"]),
                 ("PERSISTENTE MODERADA-GRAVE", ["Años, afecta olfato y ánimo", "Corticoide intranasal"])],
                [("Intermitente leve", ["< 4 días/sem o < 4 semanas"]), ("Intermitente moderada-grave", ["Afecta sueño o actividades"])],
                [("Tratar ambas", ["Una sola vía aérea"]), ("Controlar la nariz", ["Mejora el asma"])]]))

# NRL-005 · Ataque isquémico transitorio · EMBUDO + ABCD2
S("embudo", "NRL-005", "Disartria y dificultad para caminar súbitas que desaparecen en 30 minutos: ataque isquémico transitorio",
  "Enfermedad cerebrovascular · ataque isquémico transitorio",
  ("Ataque isquémico transitorio (AIT)", ["Déficit neurológico focal por isquemia que se resuelve sin infarto en la imagen.",
                                          "Es una alarma: hasta 10 % hace un ictus en los siguientes días."]),
  ("Varón de 56 años", ["Cefalea súbita, dificultad para caminar y disartria.", "A los 30 minutos, examen neurológico normal."]),
  ["Estudiar en las primeras 24 h: RM con difusión, angio-TC o Doppler de carótidas, ECG y monitoreo (fibrilación auricular).",
   "Iniciar antiagregación (aspirina + clopidogrel 21 días si es de alto riesgo), estatina y control de la PA.",
   "Hoy se recomienda evaluar a todos con urgencia, sin importar el puntaje."],
  "AHA/ASA, prevención secundaria del ictus y AIT (2021); ESO (2021); " + HARRISON + ".",
  op=("¿Encaja?", ["No: mayor de 50, cefalea temporal y visión", "No: dolor periorbitario en salvas", "No: no da disartria",
                   "Sí: déficit focal que revierte", "No: cefalea en trueno con rigidez de nuca"]),
  d=dict(rotulo="Déficit neurológico que desaparece", inicio="Disartria y ataxia súbitas, normales a los 30 min",
         candidatos=["Crisis de pánico", "Cefalea en racimos", "Arteritis temporal", "Hemorragia subaracnoidea", "AIT"],
         pasos=[("¿Sin déficit focal real o dolor periocular en salvas?", ["Crisis de pánico", "Cefalea en racimos"]),
                ("¿Visión, arteria temporal dura o rigidez de nuca?", ["Arteritis temporal", "Hemorragia subaracnoidea"])],
         final=("ATAQUE ISQUÉMICO TRANSITORIO", ["Déficit focal que revierte"]),
         nota="Alarma de ictus: estudiar en 24 h."),
  escala=dict(nombre="Escala ABCD2", modo="puntaje", que="Riesgo de ictus a 2 días tras un AIT (0 a 7 puntos).",
              items=[("A", "Edad ≥ 60 años", "56 años", 0), ("B", "PA ≥ 140/90 al llegar", "No se informa", None),
                     ("C", "Clínica: debilidad (2) o trastorno del habla (1)", "Disartria", 1),
                     ("D", "Duración ≥ 60 min (2) o 10-59 min (1)", "Unos 30 minutos", 1), ("D", "Diabetes", "No se informa", None)],
              total_txt="Total: 2 puntos con los datos dados",
              rangos=[("0-3", "Riesgo bajo", "Igual se estudia en 24 h"), ("4-5", "Riesgo moderado", "Hospitalizar"),
                      ("6-7", "Riesgo alto", "Hospitalizar y doble antiagregación")],
              caso_rango=0, porque=[("Con PA alta o diabetes podría llegar a 3-4", False)],
              conducta="Estudio urgente (RM, vasos de cuello, ECG), antiagregación, estatina y control de factores de riesgo."))

# NRL-006 · TEC moderado · ÁRBOL + gravedad por Glasgow
S("arbol", "NRL-006", "Accidente de tránsito hace 6 horas con Glasgow 10 y TC cerebral: hematoma epidural",
  "Traumatismo craneoencefálico · hematomas intracraneales",
  ("Hematoma epidural", ["Sangre arterial (meníngea media) entre el hueso y la duramadre, casi siempre con fractura temporal.",
                         "En la TC: lente biconvexa que no cruza las suturas."]),
  ("Varón de 60 años", ["Accidente de tránsito hace 6 horas.", "Glasgow 10; tiene TC cerebral."]),
  ["Epidural: lente biconvexa que no cruza suturas; subdural: semiluna que cruza suturas y sigue el hemisferio.",
   "Cirugía si el volumen es > 30 cm³, el grosor > 15 mm, el desplazamiento > 5 mm o hay anisocoria con Glasgow < 9.",
   "Glasgow 9-12 = TEC moderado: hospitalizar con TC y evaluación por neurocirugía."],
  "Brain Trauma Foundation, guías de TEC grave (4.ª ed.) y manejo quirúrgico; " + ATLS + ".",
  op=("¿Encaja con la TC?", ["Puede coexistir; no es una colección", "Sí: lente biconvexa", "No: dentro del cerebro",
                             "No: semiluna que cruza suturas", "No: lesión del parénquima"]),
  arbol=Q("TEC con TC: ¿forma de la colección?", [
      L("Lente biconvexa (lo descrito)", "HEMATOMA EPIDURAL", ["No cruza suturas", "Cirugía si > 30 cm³"], path=True),
      L("Semiluna", "Hematoma subdural", ["Cruza suturas; ancianos, venas puente"]),
      L("Dentro del cerebro", "Contusión o hematoma intracerebral", ["Lóbulos frontal y temporal"])], path=True),
  escala=GLASGOW_TEC(1, [("Glasgow 10 al llegar", True), ("Por encima de 8: aún no exige intubación por el Glasgow", False)],
                     "TEC moderado: TC, hospitalización y neurocirugía; operar si el hematoma cumple criterios."))

# PSI-006 · Trastorno límite de la personalidad · TARJETAS + grupos DSM
S("tarjetas", "PSI-006", "Autoagresiones, impulsividad, promiscuidad, consumo de sustancias y relaciones caóticas: personalidad límite",
  "Trastornos de la personalidad",
  ("Trastorno límite (borderline) de la personalidad", ["Inestabilidad en el ánimo, la imagen de sí misma y las relaciones.",
                                                         "Impulsividad, autolesiones e intentos de suicidio repetidos."]),
  ("Mujer de 32 años", ["Autoagresiones y mal control de impulsos.", "Promiscuidad, abuso de sustancias, malas relaciones familiares; aliento alcohólico."]),
  ["Tratamiento de elección: psicoterapia (terapia dialéctico-conductual); los fármacos solo tratan síntomas.",
   "Evaluar siempre el riesgo de suicidio en cada crisis.",
   "Antisocial: viola derechos de otros sin culpa; histriónica: busca atención sin autolesiones repetidas."],
  "APA, DSM-5-TR (2022); APA, Practice guideline for borderline personality disorder (2024); NICE CG78.",
  op=("¿Encaja?", ["No: teatralidad sin autolesiones", "No: sin culpa, viola derechos", "No: perfeccionismo y control",
                   "Sí: impulsividad + autolesiones + relaciones inestables", "No: aislamiento y frialdad"]),
  d=dict(rotulo="¿Qué personalidad es?", ans=0,
         cards=[dict(titulo="Límite (borderline)", datos=[("Ánimo", "Inestable", True), ("Conducta", "Autolesiones, impulsos", True),
                                                        ("Relaciones", "Intensas y caóticas", True)], pie="Este caso."),
                dict(titulo="Antisocial", datos=[("Conducta", "Viola normas", False), ("Culpa", "No siente", False),
                                               ("Inicio", "Conducta antes de 15 años", False)], pie="Grupo B."),
                dict(titulo="Histriónica", datos=[("Busca", "Ser el centro", False), ("Emociones", "Teatrales", False),
                                                ("Autolesión", "No típica", False)], pie="Grupo B."),
                dict(titulo="Esquizoide", datos=[("Relaciones", "No le interesan", False), ("Emociones", "Frías", False),
                                               ("Vive", "Aislado", False)], pie="Grupo A.")]),
  escala=dict(nombre="Grupos de personalidad (DSM-5-TR)", orden=False, que="Se agrupan por su rasgo dominante.",
              grados=[("Grupo A", "Raros o excéntricos", ["Paranoide", "Esquizoide", "Esquizotípico"]),
                      ("Grupo B", "Dramáticos o impulsivos", ["Antisocial", "Límite", "Histriónico", "Narcisista"]),
                      ("Grupo C", "Ansiosos o temerosos", ["Evitativo", "Dependiente", "Obsesivo-compulsivo"])],
              caso=1, porque=[("Impulsividad, autolesiones e inestabilidad: grupo B, tipo límite", True)],
              conducta="Terapia dialéctico-conductual; evaluar riesgo suicida en cada crisis."))

# CIR-013 · Hernia crural encarcerada · TARJETAS
S("tarjetas", "CIR-013", "Mujer mayor con dolor y masa dolorosa debajo del pliegue inguinal, vómitos y distensión: hernia crural complicada",
  "Hernias de la pared abdominal",
  ("Hernia crural (femoral)", ["Sale por el anillo femoral, debajo del ligamento inguinal.",
                               "Más frecuente en mujeres mayores; es la que más se estrangula (cuello estrecho)."]),
  ("Mujer de 66 años", ["2 horas de dolor inguinal derecho tras levantar peso; náuseas y vómitos.",
                        "Distensión con ruidos de lucha; masa dolorosa de 2 × 2 cm debajo del pliegue inguinal."]),
  ["Encarcerada con obstrucción: cirugía urgente (no intentar reducirla si hay signos de estrangulación).",
   "Toda hernia crural se opera aunque no dé síntomas por su alto riesgo de estrangulación.",
   "Inguinal: por encima del ligamento inguinal; directa (Hesselbach) e indirecta (anillo profundo)."],
  "HerniaSurge, guía internacional de hernia inguinal (2018, act. 2023); " + "Sabiston Tratado de Cirugía 21.ª ed.",
  op=("¿Encaja?", ["No: encima del pliegue", "Sí: debajo del pliegue inguinal", "No: cara interna del muslo, dolor en la rodilla",
                   "No: encima del pliegue", "No: en el ombligo"]),
  d=dict(rotulo="¿Dónde sale la hernia?", ans=0,
         cards=[dict(titulo="Crural (femoral)", datos=[("Sitio", "Bajo el ligamento inguinal", True), ("Quién", "Mujer mayor", True),
                                                     ("Riesgo", "Se estrangula", True)], pie="Este caso: cirugía urgente."),
                dict(titulo="Inguinal indirecta", datos=[("Sitio", "Anillo profundo", False), ("Quién", "Varón joven", False),
                                                       ("Llega", "Al escroto", False)], pie="La más frecuente."),
                dict(titulo="Inguinal directa", datos=[("Sitio", "Triángulo de Hesselbach", False), ("Quién", "Varón mayor", False),
                                                     ("Riesgo", "Bajo", False)], pie="Pared débil."),
                dict(titulo="Obturatriz", datos=[("Sitio", "Agujero obturador", False), ("Signo", "Howship-Romberg", False),
                                               ("Quién", "Anciana delgada", False)], pie="Dolor en la rodilla.")]))

# SP-018 · Control de infecciones de TB · ÁRBOL + jerarquía de controles
S("arbol", "SP-018", "Trabajadores con tuberculosis tras remodelar consultorios: maximizar la ventilación natural (control ambiental)",
  "Bioseguridad · control de infecciones de tuberculosis",
  ("Control de infecciones de tuberculosis", ["El bacilo viaja en aerosoles que quedan en el aire de ambientes cerrados.",
                                              "Tres niveles: administrativo, ambiental y protección respiratoria."]),
  ("Centro de salud remodelado", ["Se crearon más consultorios.", "6 meses después, trabajadores con tuberculosis pulmonar."]),
  ["Control ambiental de elección: ventilación natural cruzada (ventanas y puertas opuestas abiertas); luz UV y extractores si no basta.",
   "Administrativo (el más importante en general): detectar, separar y tratar rápido al sintomático respiratorio.",
   "Protección personal: respirador N95 para el trabajador; mascarilla quirúrgica solo para el paciente."],
  OMS + ", guías de prevención y control de infecciones de TB (2019); " + MINSA + ", NTS de tuberculosis (2023).",
  op=("¿Control ambiental?", ["Sí: diluye los aerosoles", "No: es tratamiento preventivo", "No: es administrativo",
                              "No: es protección personal", "No: no protege al trabajador"],
      {4: "Mascarilla quirúrgica para todo el personal"}),
  arbol=Q("¿Qué nivel de control pide el caso?", [
      L("Ambiental (este caso)", "VENTILACIÓN NATURAL", ["Ventanas y puertas opuestas", "Luz UV, extractores"], path=True),
      L("Administrativo", "Detectar y tratar rápido", ["Triaje del sintomático respiratorio"]),
      L("Personal", "Respirador N95", ["Para el trabajador"])], path=True),
  escala=dict(nombre="Jerarquía de controles de la TB", orden=False, que="OMS 2019: se aplican juntos, en este orden de importancia.",
              grados=[("1.º", "Administrativo", ["Triaje, separar al tosedor", "Tratamiento rápido"]),
                      ("2.º", "Ambiental", ["Ventilación natural o mecánica", "Luz ultravioleta"]),
                      ("3.º", "Protección respiratoria", ["Respirador N95 al trabajador", "Mascarilla al paciente"])],
              caso=1, porque=[("La remodelación cerró la circulación del aire: falla ambiental", True)],
              conducta="Abrir ventilación cruzada, redistribuir consultorios y reforzar el triaje de sintomáticos respiratorios."))

# CB-006 · Anfetaminas e HTA · MATRIZ
S("matriz", "CB-006", "Consumidor de anfetaminas con cefalea, agitación y PA 140/110: sube la resistencia periférica",
  "Fisiología cardiovascular · determinantes de la presión arterial",
  ("Determinantes de la presión arterial", ["PA = gasto cardiaco × resistencia vascular periférica.",
                                            "La diastólica refleja sobre todo la resistencia periférica."]),
  ("Varón de 30 años", ["Cefalea y agitación psicomotriz; consume anfetaminas.", "PA 140/110; resto normal."]),
  ["Las anfetaminas liberan noradrenalina: los receptores alfa-1 contraen las arteriolas y sube la resistencia.",
   "La diastólica de 110 apunta a vasoconstricción.",
   "Tratamiento de la toxicidad simpaticomimética: benzodiacepinas; evitar betabloqueadores solos (deja alfa sin oposición)."],
  "Guyton y Hall, Tratado de fisiología médica 14.ª ed. (2021); Goldfrank's Toxicologic Emergencies 11.ª ed. (2019).",
  op=("¿Principal?", ["No: baja la PA", "No: no explica la diastólica", "Sí: vasoconstricción alfa-1", "No: bajaría la PA",
                      "No: efecto lento, no agudo"]),
  d=dict(rotulo="PA = gasto cardiaco × resistencia", eje_x="Componente", eje_y="Efecto de las anfetaminas",
         cols=["Resistencia periférica", "Gasto cardiaco"], rows=["Sube mucho", "Sube poco", "No cambia"], caso=(0, 0),
         cells=[[("VASOCONSTRICCIÓN ALFA-1", ["Arteriolas contraídas", "Diastólica 110"]), ("Taquicardia", ["Beta-1"])],
                [("Venoconstricción", ["Más retorno venoso"]), ("Contractilidad", ["Algo más de fracción de eyección"])],
                [("Volumen", ["Sin cambio agudo"]), ("—", ["—"])]]))

# GIN-020 · Hipodinamia en fase activa · ÁRBOL
S("arbol", "GIN-020", "Fase activa con 6 cm y contracciones débiles (3 en 10 minutos de 30 segundos): conducción con oxitocina",
  "Distocias de la dinámica uterina · hipodinamia",
  ("Hipodinamia uterina", ["Contracciones poco intensas o cortas: el parto avanza lento.",
                           "Si el feto está bien y no hay desproporción, se refuerzan con oxitocina."]),
  ("Gestante en trabajo de parto, 3 h después", ["Altura uterina 32 cm, 6 cm, presentación -2.", "3 contracciones en 10 minutos, débiles, de 30 segundos."]),
  ["Antes de la oxitocina: descartar desproporción céfalo-pélvica y confirmar bienestar fetal.",
   "Oxitocina EV en infusión creciente; amniotomía si las membranas están íntegras.",
   "Las prostaglandinas maduran el cuello antes del parto; no se usan en fase activa."],
  OMS + ", recomendaciones de conducción del trabajo de parto (2014, act. 2018); " + ACOG + "; " + WILLIAMS + ".",
  op=("¿Indicado?", ["No: no hay indicación de cesárea", "Sí: corrige la hipodinamia", "No: el parto no avanza", "No: son para el cuello inmaduro",
                     "No: no hay sufrimiento fetal ni desproporción"]),
  arbol=Q("Fase activa lenta: ¿contracciones adecuadas?", [
      L("No: débiles y cortas (este caso)", "OXITOCINA", ["Infusión EV creciente", "Amniotomía si están íntegras"], path=True),
      L("Sí", "Buscar desproporción", ["Si la hay: cesárea"])], path=True))

# GIN-021 · Síndrome de ovario poliquístico · TARJETAS + criterios de Rotterdam
S("tarjetas", "GIN-021", "Amenorrea que responde a progesterona, infertilidad, obesidad, acné y seborrea: factor ovárico (SOP)",
  "Infertilidad · anovulación",
  ("Síndrome de ovario poliquístico (SOP)", ["Anovulación crónica con exceso de andrógenos; la causa más frecuente de infertilidad anovulatoria.",
                                             "Sangra con progesterona: hay estrógenos y el útero responde."]),
  ("Mujer de 24 años", ["Menstrúa solo con progesterona; 4 meses de amenorrea; prueba de embarazo negativa.",
                        "Infertilidad primaria de 4 años; obesidad, acné y seborrea; pareja normal."]),
  ["Prueba de progesterona positiva = anovulación con estrógenos presentes (factor ovárico).",
   "Tratamiento de la infertilidad: bajar de peso; letrozol es el inductor de ovulación de elección.",
   "Diagnóstico con Rotterdam: 2 de 3 criterios, descartando hiperprolactinemia, tiroides e hiperplasia suprarrenal."],
  "International evidence-based guideline for PCOS (2023); ASRM; " + WILLIAMS + ".",
  op=("¿Factor?", ["No: moco y cuello normales", "No: no hay infección ni cirugía previa", "Sí: anovulación por SOP",
                   "No: sangra con progesterona", "No: pareja normal"]),
  d=dict(rotulo="Factores de infertilidad", ans=0,
         cards=[dict(titulo="Ovárico", datos=[("Problema", "No ovula", True), ("Prueba", "Progesterona (+)", True),
                                            ("Causa", "SOP", True)], pie="Este caso: letrozol."),
                dict(titulo="Tuboperitoneal", datos=[("Problema", "Trompas tapadas", False), ("Antecedente", "EPI, cirugía", False),
                                                   ("Prueba", "Histerosalpingografía", False)], pie="Ciclos normales."),
                dict(titulo="Uterino", datos=[("Problema", "Endometrio o cavidad", False), ("Prueba", "No sangra con hormonas", False),
                                            ("Causa", "Asherman, miomas", False)], pie="Histeroscopia."),
                dict(titulo="Masculino", datos=[("Problema", "Semen", False), ("Prueba", "Espermatograma", False),
                                              ("Aquí", "Normal", False)], pie="40 % de los casos.")]),
  triada=TR([("Oligo o anovulación", "Amenorrea, solo sangra con progesterona", True), ("Hiperandrogenismo", "Acné y seborrea", True),
             ("Ovarios poliquísticos en la ecografía", "No se informa", False)],
            [("Criterios de Rotterdam (2 de 3)", 0, 2)], "Cumple 2 de 3: SOP, tras descartar otras causas.",
            rotulo="Criterios con nombre propio"))

# PED-031 · Intoxicación por plomo · TARJETAS
S("tarjetas", "PED-031", "Niño de Cerro de Pasco con dolor abdominal, hiperactividad, talla baja y anemia microcítica: intoxicación por plomo",
  "Toxicología pediátrica · metales pesados",
  ("Intoxicación por plomo (saturnismo)", ["Exposición crónica en zonas mineras o por pinturas viejas: el plomo bloquea la síntesis del hem.",
                                           "Anemia microcítica, dolor abdominal, estreñimiento, problemas de conducta y aprendizaje."]),
  ("Niño de 8 años", ["Vive en Cerro de Pasco desde los 6 meses.", "Dolor abdominal crónico, hiporexia, hiperactividad; palidez, talla baja; Hb 10, microcitosis."]),
  ["Medir plomo en sangre: el valor de referencia es 3,5 µg/dL (CDC 2021); quelación (succímero) si ≥ 45 µg/dL.",
   "Lo principal es cortar la exposición (vivienda, juguetes, polvo) y corregir el hierro (la ferropenia aumenta la absorción de plomo).",
   "Frotis: punteado basófilo; Rx: líneas densas en las metáfisis."],
  CDC + ", Blood lead reference value (2021) y manejo de niños con plomo (2024); OMS, intoxicación por plomo (2024).",
  op=("¿Encaja?", ["Sí: zona minera + anemia + conducta", "No: esferocitos, ictericia", "Posible, pero no explica el resto",
                   "No: no da anemia microcítica", "No: sin exposición, asintomática"]),
  d=dict(rotulo="Anemia microcítica en el niño", ans=0,
         cards=[dict(titulo="Plomo", datos=[("Exposición", "Zona minera", True), ("Conducta", "Hiperactividad", True),
                                          ("Abdomen", "Cólico crónico", True)], pie="Este caso: medir plomo."),
                dict(titulo="Ferropenia", datos=[("Causa", "Dieta, parásitos", False), ("Conducta", "Irritable", False),
                                               ("Ferritina", "Baja", False)], pie="Suele coexistir."),
                dict(titulo="Talasemia menor", datos=[("Origen", "Hereditario", False), ("Hb A2", "Alta", False),
                                                    ("Síntomas", "Ninguno", False)], pie="Glóbulos muy pequeños."),
                dict(titulo="Esferocitosis", datos=[("VCM", "Normal", False), ("Signos", "Ictericia, bazo grande", False),
                                                  ("Frotis", "Esferocitos", False)], pie="No es microcítica.")]))

# GIN-022 · Preeclampsia severa en I-3 · ÁRBOL + clasificación
S("arbol", "GIN-022", "Primigesta de 25 semanas con cefalea y PA 160/110 en un centro de salud I-3: referir a un establecimiento obstétrico de mayor nivel",
  "Trastornos hipertensivos del embarazo · referencia",
  ("Preeclampsia con criterios de severidad", ["PA ≥ 160/110 o síntomas como cefalea intensa = severidad.",
                                               "Necesita un hospital con UCI materna y neonatal."]),
  ("Primigesta de 25 semanas", ["Control en un centro de salud I-3.", "Cefalea; PA 160/110 en dos tomas."]),
  ["Antes de referir: sulfato de magnesio (4 g EV de ataque) y antihipertensivo (nifedipino oral o labetalol) en el mismo centro.",
   "Referir acompañada, con vía EV, a un hospital nivel II-III con UCI neonatal (25 semanas = gran prematuro).",
   "Corticoides para maduración pulmonar si el traslado lo permite."],
  ACOG + " Practice Bulletin n.º 222 (2020); " + MINSA + ", guía de trastornos hipertensivos y sistema de referencia y contrarreferencia.",
  op=("¿Decisión?", ["Sí: necesita nivel II-III con UCI", "No: insuficiente para esta gravedad", "No: no es lugar para tratarla",
                     "No: retrasa la atención", "No: riesgo de eclampsia"],
      {0: "Referir a mayor nivel obstétrico", 1: "Coordinar con nivel intermedio"}),
  arbol=Q("Gestante con PA ≥ 160/110 en el primer nivel", [
      L("Estabilizar y referir (este caso)", "REFERIR A NIVEL II-III", ["Sulfato de magnesio + antihipertensivo", "Traslado acompañado"], path=True),
      L("Sin severidad", "Control estricto", ["Laboratorio y vigilancia"])], path=True),
  escala=HTA_EMB(3, [("PA 160/110 en dos tomas después de las 20 semanas", True), ("Cefalea: síntoma de severidad", True)],
                 "Sulfato de magnesio, antihipertensivo y referencia inmediata a un hospital con UCI materna y neonatal."))

# GIN-023 · Prolapso total ulcerado · ÁRBOL + POP-Q
S("arbol", "GIN-023", "Prolapso uterino total con úlceras sangrantes en una mujer de 62 años: estrógenos tópicos antes de operar",
  "Uroginecología · prolapso de órganos pélvicos",
  ("Prolapso de órganos pélvicos", ["Falla del soporte del piso pélvico: el útero o las paredes vaginales descienden.",
                                    "Con prolapso total, la mucosa se seca y se ulcera por roce."]),
  ("Mujer de 62 años", ["Sangrado genital.", "Prolapso total con úlceras sangrantes."]),
  ["Preparar con estrógenos vaginales 2-4 semanas: engrosan la mucosa y cicatrizan las úlceras antes de la cirugía.",
   "Biopsiar úlceras que no curan (descartar cáncer).",
   "Cirugía según el caso: histerectomía vaginal con colpopexia o colpocleisis en mujeres sin vida sexual."],
  "IUGA/ICS, terminología del prolapso (2016); NICE NG123 (2019); ACOG Practice Bulletin n.º 214 (2019).",
  op=("¿Preparación de elección?", ["No: daña más la mucosa", "No: no mejora el trofismo", "Solo si hay infección",
                                    "Sí: trofismo y cicatrización", "No: con úlceras se lesiona más"]),
  arbol=Q("Prolapso con úlceras: ¿curan con tratamiento local?", [
      L("Preparar (este caso)", "ESTRÓGENOS TÓPICOS", ["2-4 semanas", "Luego cirugía"], path=True),
      L("No curan", "Biopsia", ["Descartar cáncer"])], path=True),
  escala=dict(nombre="Estadios POP-Q", orden=True, que="Mide el punto más descendido respecto del himen (en cm).",
              grados=[("Estadio 0", "Sin prolapso", ["Soporte normal"]), ("Estadio I", "Leve", ["> 1 cm por encima del himen"]),
                      ("Estadio II", "Moderado", ["Entre 1 cm arriba y 1 cm abajo del himen"]),
                      ("Estadio III", "Avanzado", ["> 1 cm fuera del himen, sin salir todo"]), ("Estadio IV", "Total", ["Eversión completa"])],
              caso=4, porque=[("Prolapso total: el útero y la vagina están afuera", True)],
              conducta="Estrógenos tópicos para curar las úlceras y luego cirugía."))

# OFT-005 · Conjuntivitis alérgica · TARJETAS
S("tarjetas", "OFT-005", "Escolar con prurito ocular intenso bilateral, secreción mucoide, lagrimeo y ojo rojo: conjuntivitis alérgica",
  "Patología conjuntival · ojo rojo",
  ("Conjuntivitis alérgica", ["Reacción IgE de la conjuntiva: el prurito es el síntoma clave.",
                              "Bilateral, con secreción mucosa en hilos y lagrimeo; a menudo con rinitis."]),
  ("Niño de 12 años", ["Prurito ocular intenso en ambos ojos.", "Secreción mucoide espesa, lagrimeo, fotofobia e hiperemia conjuntival."]),
  ["Tratamiento: frío local, lágrimas artificiales y antihistamínico-estabilizador tópico (olopatadina, ketotifeno).",
   "Evitar corticoides tópicos sin control oftalmológico (glaucoma, cataratas, herpes).",
   "Signos de alarma de ojo rojo: dolor intenso, baja visión, pupila anormal, fotofobia marcada: derivar."],
  "AAO, Conjunctivitis Preferred Practice Pattern (2023); " + NELSON + ".",
  op=("¿Encaja?", ["No: bulto en el párpado", "No: carnosidad que invade la córnea", "No: dolor, miosis, sin secreción",
                   "Sí: prurito + secreción + bilateral", "No: dolor intenso, pupila media fija"]),
  d=dict(rotulo="Ojo rojo: ¿qué es?", ans=0,
         cards=[dict(titulo="Conjuntivitis alérgica", datos=[("Síntoma", "Prurito intenso", True), ("Secreción", "Mucosa", True),
                                                           ("Ojos", "Ambos", True)], pie="Este caso."),
                dict(titulo="Iritis (uveítis anterior)", datos=[("Síntoma", "Dolor, fotofobia", False), ("Pupila", "Miótica", False),
                                                              ("Rojo", "Alrededor de la córnea", False)], pie="Derivar."),
                dict(titulo="Glaucoma agudo", datos=[("Síntoma", "Dolor intenso, vómitos", False), ("Pupila", "Media fija", False),
                                                   ("Visión", "Baja, halos", False)], pie="Urgencia."),
                dict(titulo="Chalazión", datos=[("Lesión", "Nódulo en el párpado", False), ("Dolor", "Poco", False),
                                              ("Conjuntiva", "Normal", False)], pie="Calor local.")]))

# SP-019 · Dengue importado con vector · RADIAL
S("radial", "SP-019", "Caso febril de Piura atendido en Lima con aumento de mosquitos: priorizar el control vectorial",
  "Vigilancia epidemiológica · arbovirosis",
  ("Prevención de la transmisión autóctona de dengue", ["Un caso importado en una zona con Aedes aegypti puede iniciar la transmisión local.",
                                                       "La medida que corta la cadena es eliminar al vector."]),
  ("Varón procedente de Piura", ["3 días de fiebre, cefalea, dolor retroocular, mialgias y artralgias.", "Centro de salud en Lima con aumento de mosquitos."]),
  ["Control vectorial: eliminar criaderos (recipientes con agua), larvicidas, fumigación espacial en el cerco del caso.",
   "Notificar el caso, proteger al paciente de picaduras (mosquitero) durante la fiebre.",
   "No hay quimioprofilaxis; la vacuna de fiebre amarilla no protege contra el dengue."],
  MINSA + ", NTS de vigilancia y control del Aedes aegypti (2023); " + OMS + ", dengue (2024).",
  op=("¿Prioridad?", ["Sí: corta la transmisión", "Útil, pero no evita casos", "No existe", "Útil, no evita casos",
                      "No: no protege contra el dengue"],
      {4: "Vacunación contra fiebre amarilla"}),
  d=dict(rotulo="Cortar la transmisión del dengue", centro="CONTROL", centro_sub="vectorial", ans=0,
         items=[("CRIADEROS", ["Eliminar agua estancada"]), ("LARVICIDA", ["En depósitos de agua"]), ("FUMIGACIÓN", ["Cerco del caso"]),
                ("NOTIFICAR", ["Vigilancia epidemiológica"]), ("PROTEGER", ["Mosquitero al febril"])],
         ruta=["Caso importado", "Aedes presente", "Control vectorial", "Sin casos autóctonos"]))

# CAR-009 · Paro cardiaco · ÁRBOL
S("arbol", "CAR-009", "Pérdida súbita de conciencia, respiración agónica y sin pulso: iniciar compresiones torácicas",
  "Reanimación cardiopulmonar avanzada",
  ("Paro cardiorrespiratorio", ["Sin pulso y sin respiración normal (la respiración agónica no cuenta).",
                                "Cada minuto sin compresiones baja la supervivencia."]),
  ("Varón de 70 años", ["2 horas de disnea, palpitaciones y dolor precordial; en choque.", "Pierde la conciencia, respiración agónica, sin pulso."]),
  ["Iniciar compresiones de inmediato (100-120/min, 5-6 cm), pedir el desfibrilador y ventilar 30:2 o 1 cada 6 s con vía avanzada.",
   "Analizar el ritmo: FV o TV sin pulso → descarga y compresiones; asistolia o AESP → adrenalina cuanto antes.",
   "Amiodarona tras la 3.ª descarga; buscar causas reversibles (5 H y 5 T)."],
  "AHA/ILCOR, guías de reanimación cardiopulmonar (2025); ERC (2025).",
  op=("¿Primera acción?", ["Después de empezar compresiones", "Tras la 3.ª descarga", "Si el ritmo es desfibrilable, tras empezar RCP",
                           "Sí: compresiones ya", "Después, según el ritmo"]),
  arbol=Q("No responde, no respira normal, sin pulso", [
      L("Paro (este caso)", "COMPRESIONES YA", ["100-120/min, 5-6 cm", "Pedir desfibrilador"], path=True,
        children=[Q("¿Ritmo desfibrilable?", [L("FV o TV sin pulso", "Descarga", ["Y compresiones 2 min"]),
                                              L("Asistolia o AESP", "Adrenalina 1 mg", ["Cada 3-5 min"])], path=False)])], path=True))

# REU-008 · Tiña de la cabeza · TARJETAS
S("tarjetas", "REU-008", "Escolar con placas descamativas que crecen en anillo, pelo frágil y zonas sin pelo en el cuero cabelludo: tiña capitis",
  "Dermatología · micosis superficiales",
  ("Tiña de la cabeza (tinea capitis)", ["Dermatofitos (Microsporum, Trichophyton) que invaden el pelo del niño.",
                                         "Placas con descamación, pelos rotos cortos y alopecia; puede formar un querion."]),
  ("Escolar de 10 años", ["Lesiones pruriginosas en el cuero cabelludo.", "Placas eritematosas que crecen en anillo, descamación central, pelo frágil y alopecia."]),
  ["Tratamiento oral obligatorio (el tópico no llega al folículo): griseofulvina 6-8 semanas o terbinafina 4 semanas.",
   "Champú de ketoconazol o sulfuro de selenio para reducir el contagio; revisar a convivientes y mascotas.",
   "Confirmar con KOH y cultivo del pelo; luz de Wood fluorescente verde en Microsporum."],
  "British Association of Dermatologists, guía de tinea capitis (2014, act. 2023); AAP, Red Book (2024).",
  op=("¿Encaja?", ["Sí: placas con pelo roto y descamación", "No: placas plateadas sin alopecia", "No: piel lisa, sin descamación",
                   "No: pelos de distinto largo, sin descamación", "No: escamas grasas, sin alopecia"]),
  d=dict(rotulo="Alopecia en placas en el niño", ans=0,
         cards=[dict(titulo="Tiña de la cabeza", datos=[("Piel", "Descamación, eritema", True), ("Pelo", "Roto, frágil", True),
                                                      ("Prueba", "KOH, cultivo", True)], pie="Este caso: griseofulvina oral."),
                dict(titulo="Alopecia areata", datos=[("Piel", "Lisa, normal", False), ("Pelo", "En signo de exclamación", False),
                                                    ("Causa", "Autoinmune", False)], pie="Sin descamación."),
                dict(titulo="Tricotilomanía", datos=[("Pelo", "De distinto largo", False), ("Bordes", "Irregulares", False),
                                                   ("Causa", "Se lo arranca", False)], pie="Conducta."),
                dict(titulo="Dermatitis seborreica", datos=[("Escama", "Grasa, amarilla", False), ("Pelo", "Normal", False),
                                                          ("Prurito", "Leve", False)], pie="Sin alopecia.")]))

# NRL-007 · Síndrome de cola de caballo tras raquídea · TARJETAS
S("tarjetas", "NRL-007", "Tras raquianestesia: pérdida motora y sensitiva de piernas con disfunción vesical e intestinal: síndrome de cola de caballo",
  "Complicaciones de la anestesia neuroaxial",
  ("Síndrome de cola de caballo", ["Lesión de las raíces lumbosacras bajo el cono medular.",
                                   "Debilidad y anestesia en silla de montar de las piernas, retención urinaria y falta de control intestinal."]),
  ("Posoperado de apendicectomía con anestesia raquídea", ["Al primer día: disfunción intestinal y vesical.", "Pérdida sensitiva y motora de miembros inferiores."]),
  ["Urgencia: RM de columna para descartar hematoma o absceso epidural (descompresión en < 8-12 h).",
   "Causas tras la raquídea: hematoma epidural (anticoagulantes), toxicidad del anestésico local, infección.",
   "La cefalea pospunción es postural y no da déficit motor ni esfinteriano."],
  "ASRA, guía de anestesia regional en anticoagulados (2018, act.); " + HARRISON + ".",
  op=("¿Encaja?", ["No: una sola raíz, sin esfínteres", "Sí: déficit bilateral + esfínteres", "No: sin relación con la raquídea, una raíz",
                   "No: diagnóstico de exclusión, hay causa orgánica", "No: cefalea postural sin déficit"]),
  d=dict(rotulo="Déficit neurológico tras la raquídea", ans=0,
         cards=[dict(titulo="Cola de caballo", datos=[("Piernas", "Débiles y sin sensibilidad", True), ("Esfínteres", "Vejiga e intestino", True),
                                                    ("Urgencia", "RM ya", True)], pie="Este caso."),
                dict(titulo="Cefalea pospunción", datos=[("Síntoma", "Cefalea al pararse", False), ("Déficit", "No", False),
                                                       ("Tratamiento", "Parche hemático", False)], pie="Postural."),
                dict(titulo="Radiculopatía", datos=[("Raíz", "Una sola", False), ("Esfínteres", "Normales", False),
                                                  ("Dolor", "Irradiado", False)], pie="Hernia discal."),
                dict(titulo="Conversivo", datos=[("Examen", "No anatómico", False), ("Pruebas", "Normales", False),
                                               ("Diagnóstico", "De exclusión", False)], pie="Primero descartar lo orgánico.")]))

# NEF-009 · Torsión testicular · ÁRBOL + signos
S("arbol", "NEF-009", "Adolescente con dolor testicular de 6 horas, testículo horizontal y reflejo cremastérico ausente: torsión testicular",
  "Urología · escroto agudo",
  ("Torsión testicular", ["El cordón espermático se tuerce y corta la sangre al testículo: urgencia quirúrgica.",
                          "Más frecuente en adolescentes; antes de 6 horas se salva más del 90 %."]),
  ("Varón de 15 años", ["6 horas de dolor testicular derecho; testículo retráctil del mismo lado.", "Testículo horizontal y reflejo cremastérico ausente."]),
  ["Sospecha clínica alta: exploración quirúrgica inmediata (no esperar la ecografía) con detorsión y fijación bilateral.",
   "Si hay duda: eco-Doppler (flujo ausente), sin retrasar la cirugía.",
   "Epididimitis: inicio gradual, fiebre, síntomas urinarios y reflejo cremastérico presente."],
  "EAU, guía de urología pediátrica (2024); AUA (2023); " + NELSON + ".",
  op=("¿Encaja?", ["No: indoloro, transilumina", "No: gradual, cremastérico presente", "Sí: dolor + horizontal + sin cremastérico",
                   "No: indoloro", "No: parotiditis previa, ambos lados"]),
  arbol=Q("Dolor testicular agudo: ¿reflejo cremastérico ausente o testículo alto y horizontal?", [
      L("Sí (este caso)", "TORSIÓN: CIRUGÍA YA", ["Detorsión y orquidopexia bilateral", "< 6 horas: salvamento alto"], path=True),
      L("No: gradual, con fiebre", "Epididimitis u orquitis", ["Doppler con flujo aumentado"])], path=True),
  triada=TR([("Dolor súbito", "6 horas", True), ("Testículo horizontal (signo de Angell)", "Presente", True),
             ("Reflejo cremastérico ausente", "Ausente", True), ("Signo de Prehn negativo", "No se menciona", False)],
            [("Signos de la torsión testicular", 0, 3)],
            "Con tres signos presentes, no se necesita la ecografía para operar.", rotulo="Signos con nombre propio"))

# GIN-024 · DPP · TARJETAS + Page + pieza real
S("tarjetas", "GIN-024", "Multípara de 37 semanas con contracciones dolorosas, útero hipertónico y sangrado oscuro: desprendimiento prematuro de placenta",
  "Hemorragias de la segunda mitad del embarazo",
  ("Desprendimiento prematuro de placenta (DPP)", ["La placenta se separa antes del parto: sangra por detrás y el útero se contrae sin relajar.",
                                                   "Dolor, útero hipertónico y sangrado oscuro (a veces escaso)."]),
  ("Multípara de 37 semanas sin control", ["Contracciones frecuentes y dolorosas con sangrado vaginal.", "Útero hipertónico; sangrado oscuro moderado sin coágulos."]),
  ["Evaluar madre (PA, pulso, coagulación) y feto (latidos) para graduarlo y decidir la vía del parto.",
   "Feto vivo comprometido: cesárea; feto muerto con madre estable: parto vaginal con reposición.",
   "Placenta previa: sangrado rojo indoloro con útero blando; no hacer tacto vaginal."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ", guía de hemorragia obstétrica.",
  op=("¿Encaja?", ["No: indoloro, útero blando", "Sí: dolor + hipertonía + sangre oscura", "No: sangrado al romper membranas, feto afectado",
                   "No: no es causa a término", "No: cicatriz previa, dolor súbito, partes fetales palpables"]),
  d=dict(rotulo="Sangrado en el tercer trimestre", ans=0,
         cards=[dict(titulo="Desprendimiento de placenta", datos=[("Dolor", "Sí, continuo", True), ("Útero", "Hipertónico", True),
                                                                ("Sangre", "Oscura", True)], pie="Este caso."),
                dict(titulo="Placenta previa", datos=[("Dolor", "No", False), ("Útero", "Blando", False), ("Sangre", "Roja, rutilante", False)],
                     pie="No hacer tacto."),
                dict(titulo="Rotura uterina", datos=[("Antecedente", "Cesárea previa", False), ("Dolor", "Súbito, cede la dinámica", False),
                                                   ("Feto", "Se palpa fácil", False)], pie="Laparotomía."),
                dict(titulo="Vasa previa", datos=[("Cuándo", "Al romper membranas", False), ("Sangre", "Fetal", False),
                                                ("Feto", "Bradicardia", False)], pie="Cesárea urgente.")]),
  escala=PAGE(None, [("Dolor, hipertonía y sangrado oscuro: es un DPP", True),
                     ("Falta el estado del feto y de la madre para graduarlo", False)],
              "Monitorear al feto y a la madre; con feto vivo comprometido, cesárea; reponer sangre."),
  banda=B("Pieza real de un DPP", P("dpp_pieza.jpg", 330, 208, [
            ("flecha", 0.66, 0.22, 0.88, 0.10, "placenta"),
            ("flecha", 0.50, 0.57, 0.22, 0.12, "coágulo\nretroplacentario"),
            ("flecha", 0.36, 0.80, 0.74, 0.90, "pared del útero")], credito="Mikael Häggström" + CC + "CC0", fondo="#1d4ed8"),
          [("Coágulo detrás de la placenta", "La sangre queda atrapada: por eso a veces el sangrado externo es escaso y oscuro."),
           ("Útero «de madera»", "La sangre infiltra el miometrio y lo contrae sin relajar (hipertonía)."),
           ("Riesgo de coagulopatía", "Consume fibrinógeno y plaquetas: pedir coagulación.")],
          pie="Pieza quirúrgica de otra paciente.", ans=0))
