"""Entrega 3 · tanda t02 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO, GINA
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
from esc28 import GLASGOW_TEC, ITU
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
SABISTON = "Sabiston Tratado de Cirugía 21.ª ed."

# GIN-144 · Mecanismo del parto: rotación externa · RELOJ (7 movimientos cardinales)
S("reloj", "GIN-144", "Tras la salida de la cabeza fetal, el siguiente movimiento cardinal es la rotación externa (restitución), que alinea los hombros",
  "Parto · mecanismo del parto en vértice",
  ("Movimientos cardinales del parto", ["El feto se acomoda al canal de la pelvis con 7 movimientos en orden.",
                                       "Después de salir la cabeza, gira hacia el muslo de la madre (restitución) para que salgan los hombros."]),
  ("Parto vaginal a término", ["Ya salió la cabeza fetal.", "¿Qué movimiento sigue?"]),
  ["Orden: encajamiento → descenso → flexión → rotación interna → extensión → rotación externa → expulsión.",
   "La rotación externa devuelve la cabeza a la posición del dorso y coloca los hombros en el diámetro anteroposterior.",
   "Si los hombros no salen tras la cabeza: distocia de hombros (McRoberts y presión suprapúbica)."],
  WILLIAMS + "; " + MINSA + ", guía de atención del parto.",
  op=("¿Siguiente movimiento?", ["No: ocurre al inicio", "No: es antes del descenso de la cabeza", "No: es antes de la salida de la cabeza",
                                 "Sí: restitución tras salir la cabeza", "No: acompaña todo el trabajo de parto"]),
  d=dict(rotulo="Los 7 movimientos cardinales, en orden",
         pasos=[("1", "Encajamiento", "El diámetro mayor de la cabeza pasa el estrecho superior", False),
                ("2", "Descenso", "Progresa por el canal", False),
                ("3", "Flexión", "Mentón al pecho: presenta el diámetro menor", False),
                ("4", "Rotación interna", "Occipucio gira hacia el pubis", False),
                ("5", "Extensión", "Sale la cabeza (desprendimiento)", False),
                ("6", "Rotación externa", "Restitución: gira hacia el muslo de la madre", True),
                ("7", "Expulsión", "Salen hombros y cuerpo", False)], tag="SIGUE AHORA",
         veredicto=("Salió la cabeza → rotación externa (restitución)", "Alinea los hombros con el diámetro anteroposterior de la salida de la pelvis.")))

# NRL-040 · Migraña · ALARMA (sin banderas rojas) + criterios ICHD-3
S("alarma", "NRL-040", "Adolescente con cefalea hemicraneal pulsátil de 48 horas, fotofobia, náuseas y vómitos, examen y TC normales: migraña",
  "Cefaleas primarias · migraña",
  ("Migraña sin aura", ["Cefalea de 4-72 h, unilateral y pulsátil, que empeora con el esfuerzo, con náuseas o foto/fonofobia.",
                        "Cefalea primaria: el examen neurológico y las imágenes son normales."]),
  ("Adolescente de 16 años", ["Cefalea hemicraneal pulsátil de 48 horas.", "Fotofobia, náuseas, vómitos; examen y TC normales."]),
  ["Crisis: AINE (ibuprofeno, naproxeno) o paracetamol + antiemético; triptán si no responde.",
   "Más de 72 h: estado migrañoso (hidratar, metoclopramida, AINE EV o dexametasona).",
   "Profilaxis si ≥ 4 días al mes o muy incapacitante: propranolol, topiramato o amitriptilina."],
  "International Headache Society, ICHD-3 (2018); AHS, consenso de tratamiento de la migraña (2021); NICE (2021).",
  op=("¿Diagnóstico?", ["No: en varones, alrededor del ojo, 15-180 min con lagrimeo", "Sí: unilateral pulsátil + náuseas + fotofobia",
                        "No: bilateral en banda, sin náuseas", "No: súbita, la peor de su vida; TC normal no la apoya", "No: sin fiebre ni secreción nasal"]),
  d=dict(rotulo="Cefalea: ¿hay banderas rojas (SNOOP)?", lista_titulo="Banderas rojas",
         signos=[("Síntomas sistémicos: fiebre, baja de peso", "No", False), ("Neurológico: déficit, confusión, papiledema", "Examen normal", False),
                 ("Inicio súbito, en trueno", "No", False), ("Inicio después de los 50 años", "16 años", False),
                 ("Patrón nuevo o progresivo, o al toser", "Cuadro típico", False)],
         accion=("Sin banderas rojas: cefalea primaria", "No necesita más imágenes; tratar la crisis de migraña."),
         accion_rotulo="Si no hay ninguna",
         veredicto=("Ninguna bandera roja + cuadro típico = migraña", "AINE + antiemético; triptán si no cede.")),
  triada=TR([("Unilateral", "Hemicraneal", True), ("Pulsátil", "Sí", True), ("Náuseas o vómitos", "Sí", True),
             ("Fotofobia", "Sí", True), ("Dura 4-72 h", "48 horas", True)],
            [("Criterios C (2 de 4 del dolor)", 0, 1), ("Criterio D", 2, 3), ("Criterio B", 4, 4)],
            "Cumple B, C y D de la ICHD-3: migraña sin aura.", rotulo="Criterios con nombre propio (ICHD-3)"))

# SP-106 · Leptospirosis: calzado y agua segura · TRANSMISIÓN + foto
S("transmision", "SP-106", "Para reducir la leptospirosis en zonas rurales pobres con mal saneamiento, la estrategia comunitaria más efectiva es promover calzado y agua segura",
  "Zoonosis · prevención de la leptospirosis",
  ("Leptospirosis", ["Bacteria (Leptospira) que eliminan las ratas y otros animales en la orina.",
                     "Entra por piel con heridas o mojada mucho tiempo, o por mucosas, al tener contacto con agua o barro contaminados."]),
  ("Zona rural pobre", ["Saneamiento deficiente.", "¿Qué estrategia comunitaria reduce más los casos?"]),
  ["Prevención: botas y guantes, agua segura, control de roedores y manejo de basura; no bañarse en aguas estancadas.",
   "Doxiciclina profiláctica solo para exposiciones puntuales de alto riesgo (inundaciones, militares), no masiva.",
   "Tratamiento: doxiciclina (leve) o penicilina G / ceftriaxona (grave: Weil)."],
  MINSA + ", NTS de vigilancia y control de la leptospirosis; " + OMS + ", leptospirosis humana (2003; act. 2024).",
  op=("¿Estrategia?", ["No: no previene; lo necesario es local", "No: aumenta la exposición", "Sí: corta la entrada por piel y boca",
                       "No: solo en exposición puntual alta", "No: no previene el contagio"],
      {0: "Centralizar el diagnóstico en el III nivel"}),
  d=dict(rotulo="La cadena de la leptospirosis y dónde se corta",
         eslabones=[("Reservorio", "Ratas, perros, ganado", "Control de roedores y basura", False),
                    ("Salida", "Orina del animal", "Vacunar a los animales", False),
                    ("Medio", "Agua, barro y suelo húmedo", "Agua segura y saneamiento", True),
                    ("Puerta de entrada", "Piel lesionada, mucosas", "Botas, guantes, calzado", True),
                    ("Huésped", "Agricultor, niño que juega en charcos", "Educación y diagnóstico precoz", False)],
         veredicto=("Calzado y agua segura cortan el contacto con el agua contaminada", "Son medidas comunitarias, baratas y sostenibles.")),
  banda=B("Un signo típico del enfermo", P("lepto.jpg", 300, 212, [], credito="Daniel Ostermayer" + CC + "CC BY 4.0"),
          [("Sufusión conjuntival", "Ojo rojo sin secreción: muy sugestivo de leptospirosis."),
           ("Ictericia", "En la forma grave (enfermedad de Weil) con falla renal."),
           ("Antecedente", "Contacto con agua o barro: pensarla en zonas rurales e inundaciones.")],
          pie="Sufusión conjuntival"))

# NEU-040 · Crisis asmática moderada · MONITOR + GINA
S("monitor", "NEU-040", "Asmático con 6 días de disnea, habla entrecortada, FR 24, SatO₂ 93 %, músculos accesorios y PEF 66 %: crisis asmática moderada",
  "Asma · exacerbación",
  ("Crisis de asma", ["Empeoramiento de la obstrucción: disnea, sibilancias y caída del flujo espiratorio (PEF).",
                      "Se gradúa por cómo habla, la FR, la FC, la SatO₂ y el PEF."]),
  ("Varón de 26 años, asma no controlada", ["6 días de disnea; habla en frases entrecortadas.", "SatO₂ 93 %, FR 24, músculos accesorios, PEF 66 %."]),
  ["Salbutamol 4-10 puff con cámara cada 20 min en la primera hora + corticoide oral (prednisona 40-50 mg por 5-7 días).",
   "Oxígeno para SatO₂ 93-95 %; reevaluar a la hora con PEF.",
   "Al alta: subir el escalón de control (GINA: budesonida-formoterol como rescate y mantenimiento)."],
  GINA + "; " + MINSA + ", guía de asma.",
  op=("¿Clasificación?", ["No: requiere paro inminente o PaCO₂ alta", "No: grave es habla con palabras, FR > 30, PEF ≤ 50 %", "Sí: frases, PEF > 50 %, SatO₂ 90-95 %",
                          "No: con músculos accesorios ya no es leve", "No: no hay confusión ni tórax silencioso"]),
  d=dict(rotulo="Los datos del caso", ecg="",
         valores=[("SatO₂", "93", "%", "bajo"), ("FR", "24", "rpm", "alto"), ("PEF", "66", "%", "bajo"),
                  ("HABLA", "frases", "", "alto"), ("MÚSC. ACC.", "sí", "", "alto"), ("CONCIENCIA", "alerta", "", "ok")],
         lectura=[("Habla en frases, alerta", "Moderada (en grave habla con palabras sueltas).", True),
                  ("PEF 66 % y SatO₂ 93 %", "Moderada: PEF > 50 % y SatO₂ 90-95 %.", True),
                  ("Si FR > 30, SatO₂ < 90 % o PEF ≤ 50 %", "Grave: agitado, sentado inclinado.", False),
                  ("Si confuso o tórax silencioso", "Riesgo vital: UCI.", False)],
         veredicto=("Crisis asmática moderada", "Salbutamol repetido + corticoide oral + oxígeno; reevaluar a la hora.")),
  escala=dict(nombre="Gravedad de la crisis de asma (GINA 2025)", que="En adultos y adolescentes, en el servicio de emergencia.",
              grados=[("Leve a moderada", "Habla en frases", ["Prefiere sentarse", "FR aumentada, FC 100-120", "SatO₂ 90-95 %, PEF > 50 %"]),
                      ("Grave", "Habla con palabras", ["Agitado, inclinado", "FR > 30, FC > 120", "SatO₂ < 90 %, PEF ≤ 50 %"]),
                      ("Riesgo vital", "Somnoliento o confuso", ["Tórax silencioso", "PaCO₂ normal o alta"])],
              caso=0, porque=[("Habla en frases y está alerta", True), ("PEF 66 % y SatO₂ 93 %", True)],
              conducta="Salbutamol + prednisona oral + O₂; si no mejora, añadir bromuro de ipratropio y reevaluar."))

# PSI-030 · Pseudociesis · LABORATORIO
S("laboratorio", "PSI-030", "Amenorrea de 24 semanas, náuseas, mamas congestionadas y «movimientos fetales» con útero vacío y β-hCG 0,1: pseudociesis",
  "Trastornos de síntomas somáticos · embarazo psicológico",
  ("Pseudociesis", ["La mujer cree firmemente que está embarazada y tiene síntomas reales (amenorrea, náuseas, crece el abdomen),",
                    "pero no hay embarazo. Se asocia a deseo intenso de embarazo, duelo o depresión."]),
  ("Mujer de 34 años", ["Amenorrea de 24 semanas, náuseas, congestión mamaria y percibe movimientos fetales.",
                        "Eco: útero normal sin saco; β-hCG 0,1 mUI/mL."]),
  ["Mostrar con empatía la ecografía y la prueba negativa; no confrontar ni burlarse.",
   "Evaluar depresión, duelo perinatal o infertilidad; apoyo psicológico.",
   "Diferencia con el delirio de embarazo (psicosis): en la pseudociesis hay cambios del cuerpo."],
  "DSM-5-TR (APA, 2022): otro trastorno de síntomas somáticos especificado; " + WILLIAMS + ".",
  op=("¿Diagnóstico?", ["No: la β-hCG sería positiva", "No: 24 semanas y β-hCG negativa", "No: sangrado y β-hCG positiva",
                        "Sí: síntomas sin embarazo, β-hCG negativa", "No: β-hCG muy alta"]),
  d=dict(rotulo="Lo que dicen los exámenes", valores=[
            ("β-hCG", "0,1 mUI/mL", "< 5 = no gestante", "=", "Negativa: no hay tejido trofoblástico."),
            ("Ecografía", "Útero normal", "Feto a las 24 sem", "=", "Sin saco ni embrión: no hay embarazo."),
            ("Amenorrea", "24 semanas", "Ciclos regulares", "↑", "Real: el estrés altera la regulación hormonal."),
            ("Síntomas", "Náuseas, mamas", "—", "↑", "Reales, pero sin embarazo detrás.")],
         veredicto=("Cree estar embarazada, con síntomas, y las pruebas son negativas = pseudociesis", "Abordaje empático y psicológico."),
         claves_titulo="Cómo se distingue",
         claves=[("Pseudociesis (este caso)", ["Cambios corporales reales", "β-hCG negativa"], True),
                 ("Delirio de embarazo", ["Psicosis, sin cambios corporales"], False),
                 ("Mola o ectópico", ["β-hCG positiva"], False)]))

# REU-040 · Carcinoma basocelular · CUADRÍCULA de tumores de piel
S("cuadricula", "REU-040", "Anciano con nódulo perlado en la cara, de crecimiento lento, telangiectasias y ulceración central: carcinoma basocelular",
  "Cáncer de piel · lesiones de la cara",
  ("Carcinoma basocelular", ["El cáncer de piel más frecuente; crece lento, casi nunca da metástasis pero destruye localmente (ulcus rodens).",
                             "Se asocia al sol acumulado; aparece en cara y cuello de personas de piel clara."]),
  ("Varón de 75 años", ["Nódulo en la cara de 1 año, con úlcera central reciente.", "Perlado, con telangiectasias arborizantes."]),
  ["Confirmar con biopsia; la dermatoscopía muestra vasos arborizantes.",
   "Tratamiento: cirugía con márgenes (cirugía de Mohs en cara y zonas de riesgo).",
   "Fotoprotección y control de la piel: riesgo de nuevos cánceres."],
  "NCCN, cáncer de piel basocelular (2025); EADO (2023).",
  op=("¿Diagnóstico?", ["No: placas en tronco, linfoma de piel", "No: pigmentado, asimétrico, de colores", "Sí: perlado + telangiectasias + úlcera",
                        "No: placa con cicatriz y atrofia", "No: «pegada», verrugosa y benigna"]),
  d=dict(rotulo="Tumores de la piel de la cara: cómo se ven", alto_img=140,
         celdas=[("Carcinoma basocelular", ["Clínica: nódulo perlado, telangiectasias, úlcera", "Biopsia: nidos basaloides en empalizada"], PA("bcc_patologia.jpg", 400), True),
                 ("Melanoma", ["Asimétrico, bordes irregulares, varios colores", "Crece rápido; ABCDE"], P("melanoma.jpg", 400, 255), False),
                 ("Carcinoma epidermoide", ["Placa costrosa o úlcera en labio o dorso de manos", "Puede dar metástasis"], P("cec_labio.jpg", 380, 229), False),
                 ("Queratosis seborreica", ["Lesión marrón «pegada», verrugosa", "Benigna"], P("qseb.jpg", 360, 196), False)],
         credito="M. Häggström (CC0), NCI (dominio público), Coronation Dental Specialty Group (CC BY-SA 4.0) · Wikimedia Commons" + " · Queratosis: Lubis y Putra · Front Med 2026 · PMC13587691 · CC BY 4.0",
         veredicto=("Nódulo perlado + telangiectasias + úlcera central = carcinoma basocelular", "Biopsia y extirpación con márgenes (Mohs en la cara).")),
  triada=TR([("Borde perlado", "Sí", True), ("Telangiectasias arborizantes", "Sí", True), ("Úlcera central (ulcus rodens)", "Reciente", True)],
            [("Signos del basocelular nodular", 0, 2)], "Los tres presentes en una zona con sol crónico."))

# SP-107 · Formaldehído: eliminar la fuente · PIRÁMIDE de jerarquía de controles
S("piramide", "SP-107", "Planta con trabajadores irritados por formaldehído, sin protección y con mala ventilación: la medida prioritaria es eliminar o reducir la fuente",
  "Salud ocupacional · control de riesgos",
  ("Jerarquía de controles", ["De más a menos eficaz: eliminar, sustituir, controles de ingeniería, controles administrativos y EPP.",
                              "El equipo de protección personal es la última barrera, no la primera."]),
  ("Planta de alimentos", ["Irritación ocular, tos y disnea en trabajadores.", "Formaldehído alto, sin protección respiratoria y mala ventilación."]),
  ["Primero eliminar o sustituir el formaldehído o encerrar el proceso; ventilación localizada (ingeniería).",
   "Mientras tanto: EPP (respiradores) y rotación como medidas complementarias.",
   "Vigilancia médica de los expuestos; el formaldehído es cancerígeno (nasofaringe, leucemia)."],
  "NIOSH, jerarquía de controles; " + MINSA + ", Ley 29783 de seguridad y salud en el trabajo; IARC.",
  op=("¿Medida prioritaria?", ["Complementa; no es lo primero", "Sí: lo más eficaz es quitar la fuente", "No: no controla el químico",
                               "Útil, pero no reduce la exposición", "No: sin otras medidas no protege"]),
  d=dict(rotulo="Jerarquía de controles (de más a menos eficaz)", caso=0, pie="▲ más eficaz · ▼ menos eficaz",
         niveles=[("ELIMINAR", "Eliminar o reducir la fuente", "Quitar el formaldehído o encerrar el proceso"),
                  ("SUSTITUIR", "Cambiar por algo menos tóxico", "Otro conservante o desinfectante"),
                  ("INGENIERÍA", "Aislar al trabajador del peligro", "Ventilación localizada, campanas"),
                  ("ADMINISTRATIVO", "Cambiar la forma de trabajar", "Rotación, capacitación, señales"),
                  ("EPP", "Equipo de protección personal", "Respiradores, gafas: la última barrera")],
         veredicto=("Primero eliminar o reducir la fuente", "El EPP y la rotación ayudan, pero no resuelven la exposición.")))

# SP-108 · Homeopatía · TARJETAS
S("tarjetas", "SP-108", "La terapia que se basa en el principio de similitud («lo similar cura lo similar») y usa sustancias muy diluidas es la homeopatía",
  "Medicina complementaria",
  ("Homeopatía", ["Creada por Hahnemann (siglo XVIII): «similia similibus curantur» y diluciones extremas.",
                  "A esas diluciones no queda molécula activa; las revisiones no muestran efecto mayor que el placebo."]),
  ("Pregunta de teoría", ["¿Qué terapia usa el principio de similitud", "y sustancias muy diluidas?"]),
  ["Naturopatía: estilo de vida y medios «naturales». Fitoterapia: plantas con principios activos medibles.",
   "Acupuntura: agujas en puntos de la medicina china. Ayurveda: medicina tradicional de la India.",
   "Al aconsejar: no reemplazar un tratamiento eficaz; preguntar siempre por terapias complementarias."],
  "OMS, estrategia de medicina tradicional y complementaria; NHMRC, revisión sobre homeopatía (2015).",
  op=("¿Terapia?", ["No: estilo de vida natural", "No: agujas en puntos", "Sí: similitud + diluciones", "No: medicina tradicional india", "No: plantas medicinales"]),
  d=dict(rotulo="Terapias complementarias: en qué se basa cada una", ans=0,
         cards=[dict(titulo="Homeopatía", datos=[("Principio", "Lo similar cura", True), ("Dosis", "Muy diluidas", True), ("Origen", "Hahnemann", True)], pie="Este caso."),
                dict(titulo="Fitoterapia", datos=[("Principio", "Plantas medicinales", False), ("Dosis", "Medibles", False), ("Ej.", "Valeriana", False)], pie="Puede interactuar."),
                dict(titulo="Acupuntura", datos=[("Principio", "Energía (qi)", False), ("Técnica", "Agujas", False), ("Origen", "China", False)], pie="Dolor crónico."),
                dict(titulo="Ayurveda", datos=[("Principio", "3 doshas", False), ("Técnica", "Dieta, hierbas", False), ("Origen", "India", False)], pie="Tradicional.")]))

# PED-143 · Convulsiones neonatales por asfixia: fenobarbital · TERMÓMETRO + Sarnat
S("termometro", "PED-143", "Recién nacido con bradicardia fetal previa que convulsiona a las 2 horas de vida: encefalopatía hipóxico-isquémica, el anticonvulsivante de elección es el fenobarbital",
  "Neonatología · convulsiones neonatales",
  ("Convulsiones neonatales", ["La causa más frecuente es la encefalopatía hipóxico-isquémica (asfixia), en las primeras 24-48 h.",
                               "Antes de dar fármacos: vía aérea, glucosa, calcio, sodio y descartar infección."]),
  ("RN a término, cesárea por bradicardia fetal", ["A las 2 horas, movimientos tónico-clónicos generalizados.", ""]),
  ["Fenobarbital 20 mg/kg EV (puede añadirse 10-20 mg/kg más); confirmar con EEG si es posible.",
   "Segunda línea: levetiracetam, fenitoína o midazolam en infusión.",
   "Asfixia moderada-grave ≥ 36 semanas: hipotermia terapéutica antes de las 6 horas de vida."],
  "ILAE, guía de convulsiones neonatales (2023); OMS, convulsiones neonatales (2011); AAP; " + NELSON + ".",
  op=("¿Medicamento de elección?", ["Segunda línea (ILAE la acepta si no hay fenobarbital)", "Sí: primera línea neonatal", "Segunda línea",
                                    "Para casos refractarios, en infusión", "No: no se usa en el neonato"]),
  d=dict(rotulo="Escalera de las convulsiones neonatales", caso_nivel=0, ruta_titulo="Antes y durante", paso_label="ESTE CASO",
         niveles=[("Fenobarbital", "20 mg/kg EV", ["Primera línea"]), ("Otra dosis", "10-20 mg/kg más", ["Si persiste"]),
                  ("Levetiracetam", "o fenitoína", ["Segunda línea"]), ("Midazolam", "Infusión", ["Refractaria, UCI"])],
         pasos=[(1, "ABC, glucosa y calcio", ["Corregir lo que causa la crisis"], False),
                (2, "Fenobarbital 20 mg/kg EV", ["Elección"], True),
                (3, "Hipotermia terapéutica", ["Si asfixia moderada-grave, < 6 h"], False)]),
  escala=dict(nombre="Estadios de Sarnat (encefalopatía hipóxico-isquémica)", que="Gravedad de la encefalopatía del recién nacido asfixiado.",
              grados=[("I", "Leve", ["Hiperalerta, irritable", "Sin convulsiones"]), ("II", "Moderada", ["Letárgico, hipotónico", "Convulsiones"]),
                      ("III", "Grave", ["Estupor o coma", "Flácido, sin reflejos"])],
              caso=1, porque=[("Bradicardia fetal (asfixia) y convulsiones a las 2 h", True)],
              conducta="Fenobarbital y evaluar hipotermia terapéutica antes de las 6 horas."))

# NEF-065 · HBP: alfabloqueadores · DECISIÓN
S("decision", "NEF-065", "Anciano con síntomas urinarios de llenado y vaciado de 1 año, próstata grande y lisa y PSA 5: hiperplasia benigna, iniciar alfabloqueador",
  "Urología · hiperplasia benigna de próstata",
  ("Hiperplasia benigna de próstata", ["La próstata crece con la edad y estrecha la uretra: chorro débil, goteo, vaciado incompleto, urgencia y polaquiuria.",
                                       "El tratamiento depende de cuánto molesta y del tamaño de la próstata."]),
  ("Varón de 76 años", ["Polaquiuria, disuria, urgencia; luego vaciado incompleto y goteo.", "Tacto: próstata grande difusa; PSA 5 ng/mL."]),
  ["Alfabloqueador (tamsulosina, doxazosina): mejora los síntomas en días; mareo e hipotensión ortostática.",
   "Próstata > 40 mL o PSA > 1,5: añadir inhibidor de 5-alfa reductasa (finasterida/dutasterida) — reduce el tamaño en meses.",
   "Cirugía (RTU) si hay retención, infecciones, cálculos, hematuria o daño renal."],
  "EAU, síntomas urinarios masculinos (2024); AUA, HBP (2023).",
  op=("¿Tratamiento inicial?", ["No: son para cáncer de próstata", "No: cirugía si falla o hay complicaciones", "Sí: primera línea, rápido",
                                "No: cirugía, no de inicio", "No: es para cáncer localizado"]),
  d=dict(rotulo="Qué tratamiento según síntomas y tamaño (EAU)", eje_y="Situación", ancho_filas=210,
         cols=["Próstata < 40 mL", "Próstata > 40 mL o PSA > 1,5"],
         rows=[("Síntomas leves", "IPSS 0-7"), ("Síntomas moderados o graves", "Molestan"),
               ("Complicaciones", "Retención, ITU, cálculos, daño renal")],
         cells=[[("Vigilar", ["Hábitos: menos líquido de noche"]), ("Vigilar", ["Control anual"])],
                [("Alfabloqueador", ["Tamsulosina"]), ("Alfabloqueador + 5-ARI", ["Tamsulosina + dutasterida"])],
                [("Cirugía", ["RTU de próstata"]), ("Cirugía", ["RTU, enucleación o abierta"])]],
         caso=(1, None), nota="PSA 5 con próstata grande y lisa: compatible con HBP; si sube o hay nódulo, RM y biopsia."))

# OFT-033 · Glaucoma agudo: acetazolamida · CUADRÍCULA ojo rojo doloroso + foto
S("cuadricula", "OFT-033", "Mujer con dolor ocular intenso, halos, visión borrosa, náuseas, ojo rojo, pupila en midriasis media fija y ojo duro: glaucoma agudo, acetazolamida 500 mg",
  "Ojo rojo doloroso · glaucoma agudo",
  ("Glaucoma agudo de ángulo cerrado", ["El iris tapa el ángulo de drenaje: la presión del ojo sube de golpe (> 40-50 mmHg).",
                                        "Dolor intenso, halos, visión borrosa, náuseas; pupila semidilatada fija y córnea opaca."]),
  ("Mujer de 60 años, 4 horas", ["Disminución de la visión, halos, dolor ocular intenso, cefalea, náuseas y vómitos.",
                                 "Ojo rojo, cámara anterior estrecha, pupila en midriasis media no reactiva, ojo tenso."]),
  ["Bajar la presión ya: acetazolamida 500 mg EV/VO + timolol + apraclonidina/brimonidina tópicos; manitol si no baja.",
   "Pilocarpina cuando la presión baja (cierra la pupila y abre el ángulo).",
   "Definitivo: iridotomía con láser en ambos ojos. Nunca dilatar (atropina) un ojo con ángulo estrecho."],
  "AAO, Preferred Practice Pattern de glaucoma de ángulo cerrado (2020); European Glaucoma Society (2020).",
  op=("¿Indicación prioritaria?", ["No: no baja la presión", "No: solo calma el dolor", "No: no hay infección", "Sí: baja la producción de humor acuoso",
                                   "No: dilata y cierra más el ángulo"]),
  d=dict(rotulo="Ojo rojo y doloroso: ¿cuál es?", alto_img=130,
         celdas=[("Glaucoma agudo", ["Pupila media fija, córnea turbia, ojo duro", "Halos, náuseas → acetazolamida"], P("glaucoma_agudo.jpg", 360, 274), True),
                 ("Conjuntivitis", ["Secreción, pupila normal, visión normal", "Sin dolor intenso"], P("conjuntivitis.jpg", 330, 202), False),
                 ("Uveítis anterior", ["Pupila pequeña (miosis), fotofobia", "Atropina sí está indicada aquí"], P("hipopion.jpg", 330, 318), False),
                 ("Queratitis", ["Úlcera en la córnea, lagrimeo", "Lente de contacto, trauma"], P("queratitis.jpg", 360, 291), False)],
         credito="Jonathan Trobe, MD (CC BY 3.0) y Gzzz (CC BY-SA 4.0) · Wikimedia Commons" + " · Hipopion: Ajabshir et al. · Cureus 2024 · PMC11707805 · Queratitis: Gardeli et al. · Cureus 2026 · PMC13552464 · CC BY 4.0",
         veredicto=("Pupila en midriasis media fija + ojo duro + halos = glaucoma agudo", "Acetazolamida 500 mg + gotas hipotensoras; luego iridotomía láser.")))

# REU-041 · Impétigo localizado: mupirocina · ÁRBOL + foto
S("arbol", "REU-041", "Adolescente con vesículas y costras color miel en antebrazos y alrededor de la boca, hermano con lo mismo y sin compromiso general: impétigo localizado, mupirocina tópica",
  "Infecciones de la piel · impétigo",
  ("Impétigo", ["Infección superficial por Staphylococcus aureus o Streptococcus pyogenes; muy contagiosa en niños y hacinamiento.",
                "Vesículas que se rompen y dejan costras «melicéricas» (color miel)."]),
  ("Varón de 16 años, pueblo joven sin servicios", ["Vesículas y costras melicéricas en antebrazos y alrededor de la boca.", "Hermano con lesiones iguales; sin afectación general."]),
  ["Localizado (pocas lesiones): mupirocina o ácido fusídico tópico 2-3 veces al día por 5 días + lavar y retirar costras.",
   "Extenso, ampolloso o brotes: cefalexina o dicloxacilina oral; clindamicina si hay SAMR.",
   "Higiene, uñas cortas, no compartir toallas; complicación tardía: glomerulonefritis posestreptocócica."],
  IDSA + ", infecciones de piel y partes blandas (2014); AAP Red Book (2024).",
  op=("¿Tratamiento?", ["No: para infecciones graves por SAMR", "Sí: localizado sin síntomas generales", "No: es para hongos",
                        "No: no es herpes", "No: es para hongos"]),
  arbol=Q("Impétigo: ¿cuántas lesiones y cómo está el paciente?", [
      L("Pocas lesiones, sin fiebre (este caso)", "MUPIROCINA TÓPICA", ["5 días", "Lavar y retirar costras"], path=True),
      L("Muchas lesiones o ampollas", "Antibiótico oral", ["Cefalexina o dicloxacilina"]),
      L("Fiebre, celulitis", "Evaluar sistémico", ["Hospitalizar si es grave"])], path=True),
  banda=B("Así se ve el impétigo", P("impetigo.jpg", 270, 313, [], credito="Evanherk" + CC + "CC BY-SA 3.0"),
          [("Costras color miel", "Costras melicéricas sobre piel roja."),
           ("Alrededor de nariz y boca", "Donde se rasca; se contagia a otras zonas."),
           ("Contagio familiar", "Por eso el hermano tiene lo mismo.")],
          pie="Impétigo con costras melicéricas"))

# NRL-041 · Hematoma epidural · LECTURA (TC) + Glasgow
S("lectura", "NRL-041", "Caída con pérdida de conciencia, intervalo lúcido, deterioro, Glasgow 10 y midriasis fija del lado de la herida: hematoma epidural",
  "Traumatismo craneoencefálico · hematomas",
  ("Hematoma epidural", ["Sangre entre el cráneo y la duramadre, casi siempre por rotura de la arteria meníngea media con fractura temporal o parietal.",
                         "Clásico: pierde la conciencia, despierta (intervalo lúcido) y luego se deteriora; midriasis del mismo lado."]),
  ("Varón de 65 años, cayó por las escaleras", ["Pérdida inicial de la conciencia, lucidez y luego somnolencia.",
                                                "Laceración parietal derecha, pupila derecha fija y dilatada, Glasgow 10."]),
  ["TC sin contraste inmediata: lente biconvexa que no cruza las suturas.",
   "Craneotomía de urgencia si > 30 mL, desviación > 5 mm o hay deterioro o anisocoria.",
   "Mientras tanto: vía aérea (intubar si Glasgow ≤ 8), cabecera a 30°, evitar hipotensión e hipoxia."],
  "Brain Trauma Foundation (4.ª ed., 2016); " + ATLS + ".",
  op=("¿Diagnóstico?", ["No: coma desde el inicio sin intervalo lúcido", "Sí: intervalo lúcido + midriasis del mismo lado",
                        "No: venoso, más lento y en ancianos con atrofia; sin intervalo típico", "No: menos típico tras golpe con intervalo lúcido", "No: no explica el intervalo lúcido"]),
  d=dict(rotulo="Lee la TC en este orden", img_titulo="TC de cráneo sin contraste",
         img=P("epidural_derecho.jpg", 300, 337, [("texto", 0.10, 0.05, "DER"), ("texto", 0.90, 0.05, "IZQ")],
               credito="Hellerhoff" + CC + "CC BY-SA 4.0"),
         pines=[(0.22, 0.52), (0.49, 0.36)],
         pasos=[("Lente biconvexa blanca", "Sangre fresca entre hueso y duramadre (epidural).", True),
                ("Línea media desplazada", "Efecto de masa: empuja el cerebro al otro lado.", False),
                ("Mismo lado que la pupila dilatada", "Hernia del uncus que comprime el III par.", False),
                ("No cruza las suturas", "La duramadre está pegada en las suturas (el subdural sí las cruza).", False)],
         img_pie="Hematoma epidural derecho",
         veredicto=("Intervalo lúcido + lente biconvexa + anisocoria = hematoma epidural", "Craneotomía de urgencia.")),
  escala=GLASGOW_TEC(1, [("Glasgow 10 tras el golpe", True), ("Además, pupila fija: neurocirugía urgente", True)],
                     "TC inmediata y craneotomía; vigilar Glasgow y pupilas."))

# CIR-086 · Colecistitis aguda · ÁRBOL + Tokio 2018 + dibujo
S("arbol", "CIR-086", "Dolor de 20 horas en hipocondrio derecho, vómitos, fiebre, taquicardia, masa dolorosa subcostal y litiasis conocida: colecistitis aguda",
  "Patología biliar · colecistitis",
  ("Colecistitis aguda litiásica", ["Un cálculo tapa el cístico: la vesícula se distiende, inflama y puede infectarse.",
                                    "Dolor continuo > 6 h en hipocondrio derecho, fiebre, Murphy positivo; a veces vesícula palpable."]),
  ("Varón de 60 años, litiasis vesicular", ["Dolor en HCD de 20 h, vómitos y sensación de fiebre.", "Taquicardia; masa dolorosa subcostal derecha."]),
  ["Ecografía: pared > 4 mm, líquido alrededor, Murphy ecográfico y cálculo en el cuello.",
   "Antibiótico, analgesia y colecistectomía laparoscópica temprana (idealmente < 72 h).",
   "Grado III o paciente muy grave: drenaje (colecistostomía percutánea) y cirugía diferida."],
  "Guías de Tokio 2018 (TG18); WSES, colecistitis aguda (2020); " + SABISTON + ".",
  op=("¿Diagnóstico?", ["Sí: dolor en HCD + fiebre + masa + litiasis", "No: dolor súbito en epigastrio con abdomen en tabla", "No: masa en fosa ilíaca derecha",
                        "No: dolor epigástrico en banda", "No: sin cálculos ni masa; ictericia y transaminasas altas"]),
  arbol=Q("Dolor en HCD con litiasis: ¿qué más tiene?", [
      L("Fiebre + Murphy o masa (este caso)", "COLECISTITIS AGUDA", ["Eco + antibiótico", "Colecistectomía temprana"], path=True),
      L("Fiebre + ictericia", "Colangitis", ["CPRE urgente"]),
      L("Dolor < 6 h, sin fiebre", "Cólico biliar", ["Analgesia; cirugía electiva"])], path=True),
  escala=dict(nombre="Gravedad de la colecistitis (Tokio 2018)", que="Decide si operar ya, drenar o esperar.",
              grados=[("Grado I", "Leve", ["Sin criterios de II ni III"]),
                      ("Grado II", "Moderada", ["Masa dolorosa palpable", "> 72 h, leucocitos > 18 000", "Inflamación local marcada"]),
                      ("Grado III", "Grave", ["Falla de un órgano (choque, confusión, riñón…)"])],
              caso=1, porque=[("Masa dolorosa palpable en HCD", True), ("Sin falla de órganos descrita", True)],
              conducta="Colecistectomía laparoscópica temprana por cirujano experto; si no es posible, drenaje."),
  triada=TR([("Dolor en hipocondrio derecho", "20 horas", True), ("Fiebre", "Sensación de alza térmica", True),
             ("Murphy (+) o masa", "Masa dolorosa subcostal", True)], [("Signos locales y sistémicos de Tokio", 0, 2)],
            "Signos locales + sistémicos: falta la imagen para confirmar (ecografía)."),
  banda=B("Qué pasa en la vesícula", D(lambda s, x, y: I.via_biliar(s, x, y, calculos=["vesicula", "cistico"], vesicula="inflamada", sc=1.0), 320, 262),
          [("Cálculo en el cístico", "Tapa la salida de la bilis."),
           ("Vesícula roja y gruesa", "Inflamada; en la eco: pared > 4 mm."),
           ("Colédoco normal", "Por eso no hay ictericia (si la hay, pensar en colangitis).")],
          pie="Colecistitis aguda"))

# INF-077 · Mononucleosis · CRITERIOS de Hoagland + linfocito atípico
S("criterios", "INF-077", "Escolar con 10 días de odinofagia, amígdalas exudativas, adenopatías cervicales grandes, hepatoesplenomegalia y exantema: mononucleosis infecciosa",
  "Infecciones virales · faringitis con adenopatías",
  ("Mononucleosis infecciosa", ["Virus de Epstein-Barr: fiebre, faringitis exudativa, adenopatías cervicales posteriores y esplenomegalia.",
                                "Linfocitosis con linfocitos atípicos; anticuerpos heterófilos (Paul-Bunnell) positivos."]),
  ("Escolar de 12 años, 10 días", ["Odinofagia, exantema maculopapular sin prurito; amígdalas exudativas con membranas.",
                                    "Adenopatías cervicales de 2 × 3 cm y hepatoesplenomegalia. (La «fiebre de 36 °C» del enunciado parece una errata.)"]),
  ["Confirmar: hemograma (linfocitos atípicos > 10 %) y anticuerpos heterófilos; en < 4 años, anti-VCA IgM.",
   "Sintomático; evitar deportes de contacto 3-4 semanas (rotura del bazo).",
   "No dar amoxicilina: el exantema aparece en casi todos con VEB."],
  CDC + ", Epstein-Barr (2024); AAP Red Book (2024); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: sin hepatoesplenomegalia ni 10 días de evolución", "No: exantema en lija con lengua aframbuesada", "No: líneas rojas de un miembro",
                        "Sí: faringitis + adenopatías + hepatoesplenomegalia", "No: adenopatías retroauriculares y cuadro leve"]),
  d=dict(rotulo="Criterios de Hoagland para mononucleosis", lista_titulo="Criterios clínicos y de laboratorio",
         items=[("Fiebre", None, "El enunciado dice 36 °C: probable errata"), ("Faringitis", True, "Amígdalas exudativas con membranas"),
                ("Adenopatías cervicales", True, "2 × 3 cm"), ("Linfocitos ≥ 50 % y atípicos ≥ 10 %", None, "Pedir hemograma"),
                ("Anticuerpos heterófilos (+)", None, "Pedir prueba")],
         umbral="Hoagland: fiebre, faringitis y adenopatías + laboratorio",
         veredicto="Cuadro clínico típico (+ hepatoesplenomegalia): mononucleosis; confirmar con hemograma y heterófilos.",
         img=P("linfo_reactivo.jpg", 260, 248, [("flecha", 0.62, 0.62, 0.8, 0.92, "citoplasma azul\nabundante")],
               credito="SpicyMilkBoy" + CC + "CC BY-SA 4.0"), img_titulo="Linfocito atípico",
         img_pie="Lo que se busca en el frotis.", conteo="2 clínicos presentes + hepatoesplenomegalia"),
  triada=TR([("Fiebre", "Probable errata (36 °C)", None), ("Faringitis exudativa", "Con membranas", True), ("Adenopatías", "Cervicales 2 × 3 cm", True)],
            [("Tríada de la mononucleosis", 0, 2)], "Más hepatoesplenomegalia y exantema: muy sugestivo de VEB."))

# TRA-031 · Fractura de húmero y nervio radial · ÁRBOL + Rx
S("arbol", "TRA-031", "Joven con fractura del tercio medio del húmero tras un accidente y mano caída (no extiende muñeca ni dedos): lesión del nervio radial",
  "Fracturas del miembro superior · lesiones nerviosas",
  ("Nervio radial y húmero", ["El radial rodea el húmero por el canal de torsión (surco espiral) en su tercio medio.",
                              "Si se lesiona: no extiende la muñeca ni los dedos («mano péndula» o caída) y se duerme el dorso del pulgar."]),
  ("Varón de 20 años, accidente de tránsito", ["Deformidad del tercio medio del brazo derecho, estable.", "Mano péndula; Rx: fractura del tercio medio del húmero."]),
  ["Explorar y documentar la función del radial antes y después de reducir.",
   "Fractura cerrada con lesión del radial al inicio: casi siempre es neuropraxia y se recupera (observar 3-4 meses).",
   "Explorar el nervio si la fractura es abierta o la parálisis aparece después de reducir."],
  "AAOS; Rockwood and Green's Fractures in Adults 9.ª ed.",
  op=("¿Nervio?", ["Sí: canal de torsión, mano caída", "No: daría mano de predicador", "No: daría garra cubital", "No: deltoides, fractura del cuello", "No: flexión del codo"]),
  arbol=Q("Fractura de húmero: ¿dónde está y qué falla?", [
      L("Tercio medio + mano caída (este caso)", "NERVIO RADIAL", ["Canal de torsión", "Observar si es cerrada"], path=True),
      L("Cuello quirúrgico + hombro sin abducción", "Nervio axilar", ["Deltoides"]),
      L("Supracondílea en niño", "Mediano / interóseo anterior", ["Y arteria braquial"])], path=True),
  banda=B("Así se ve la fractura", P("humero_fx.jpg", 280, 317, [("flecha", 0.55, 0.42, 0.25, 0.85, "trazo de\nfractura")],
          credito="Ivtorov" + CC + "CC BY-SA 4.0"),
          [("Tercio medio de la diáfisis", "Donde el radial va pegado al hueso."),
           ("Fragmentos desplazados", "Pueden estirar o atrapar el nervio."),
           ("Revisar la extensión", "Muñeca y dedos antes y después de inmovilizar.")],
          pie="Fractura de húmero"))

# NEF-066 · Torsión testicular · RELOJ (ventana de horas) + TWIST + dibujo + eco
S("reloj", "NEF-066", "Adolescente con dolor testicular súbito e intenso de 3 horas y testículo derecho alto y aumentado: torsión testicular, cirugía urgente",
  "Escroto agudo · torsión testicular",
  ("Torsión testicular", ["El cordón espermático gira y corta la sangre al testículo; más en adolescentes (anomalía en badajo de campana).",
                          "Dolor súbito e intenso, testículo alto y horizontal, reflejo cremastérico ausente; Prehn negativo."]),
  ("Adolescente de 13 años", ["Dolor intenso y súbito en el testículo derecho hace 3 horas.", "Testículo derecho aumentado y en posición alta."]),
  ["Sospecha clara: exploración quirúrgica inmediata, sin esperar la ecografía (destorsión y orquidopexia bilateral).",
   "Si hay duda y no retrasa: eco Doppler (sin flujo, signo del remolino).",
   "Detorsión manual («abrir el libro») mientras se prepara la cirugía."],
  "EAU, urología pediátrica (2024); AUA; " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: tras un trauma", "No: indoloro, transilumina", "Sí: dolor súbito + testículo alto",
                        "No: masa inguinal irreductible", "No: dolor gradual, fiebre, Prehn (+)"]),
  d=dict(rotulo="El testículo se salva según las horas", intro="Cada hora cuenta: operar dentro de las primeras 6 horas.",
         pasos=[("0-6 h", "Salva > 90 %", "Operar ya", True), ("6-12 h", "Salva ~50 %", "Aún operar", False),
                ("12-24 h", "Salva ~20 %", "Menos probable", False), ("> 24 h", "< 10 %", "Orquiectomía frecuente", False)],
         tag="ESTE CASO: 3 h",
         veredicto=("Torsión testicular de 3 horas: exploración quirúrgica inmediata", "No esperar la ecografía si la clínica es clara.")),
  escala=dict(nombre="Puntaje TWIST", modo="puntaje", que="Probabilidad de torsión ante un escroto agudo.",
              items=[("Hinch.", "Testículo hinchado (2)", "Aumento de volumen", 2), ("Duro", "Testículo duro (2)", "No se informa", None),
                     ("Crem.", "Reflejo cremastérico ausente (1)", "No se informa", None), ("N/V", "Náuseas o vómitos (1)", "No se informa", None),
                     ("Alto", "Testículo alto (1)", "Posición alta", 1)],
              total_txt="Total: ≥ 3 con los datos dados", total_nota="máximo 7",
              rangos=[("0-2", "Riesgo bajo", "Eco Doppler"), ("3-4", "Intermedio", "Eco urgente"), ("5-7", "Alto", "Cirugía sin eco")],
              caso_rango=1, porque=[("Hinchado (2) + alto (1) = 3, sin los demás datos", True), ("La clínica (súbito, 3 h) es muy típica", True)],
              conducta="Exploración quirúrgica urgente; eco Doppler solo si no la retrasa."),
  banda=B("Cómo se ve la torsión", DOS(PA("dib_torsion.jpg", 230, [], credito=PROPIO, fondo="#ffffff"),
                                       P("torsion_eco.jpg", 220, 179, [], credito="Abu-Sharikh et al. · PMC13574465 · CC BY 4.0")),
          [("Alto y horizontal", "El cordón se acorta al girar (signo de Brunzel/Angell)."),
           ("Cordón enrollado", "Signo del remolino en la eco."),
           ("Doppler sin flujo dentro", "Solo hay flujo alrededor, no en el testículo."),
           ("Cremastérico ausente", "Y el dolor no calma al levantarlo (Prehn negativo).")],
          pie="Torsión testicular y Doppler sin flujo"))

# REU-042 · Artritis reumatoide: anti-CCP · RADIAL de autoanticuerpos + criterios ACR/EULAR
S("radial", "REU-042", "Joven con poliartritis simétrica de manos, muñecas y rodillas por 3 meses y rigidez matinal prolongada: pedir anticuerpos anti-péptido citrulinado (anti-CCP)",
  "Artritis reumatoide · autoanticuerpos",
  ("Artritis reumatoide", ["Poliartritis simétrica de pequeñas articulaciones (manos, muñecas) con rigidez matinal > 1 hora.",
                           "Anti-CCP: muy específico (~95 %), aparece temprano y predice enfermedad más erosiva."]),
  ("Mujer de 24 años, 3 meses", ["Dolor, tumefacción y limitación de manos, muñecas y rodillas, simétrico.", "Rigidez matinal prolongada."]),
  ["Pedir anti-CCP + factor reumatoide + VSG/PCR + Rx de manos y pies.",
   "Tratar temprano: metotrexato (+ ácido fólico) como primer FAME; corticoide a dosis baja como puente.",
   "Meta: remisión o baja actividad (DAS28); escalar a biológicos si no se logra en 3-6 meses."],
  "ACR/EULAR, criterios de AR (2010); EULAR, manejo de la AR (2022); ACR (2021).",
  op=("¿Marcador diagnóstico y pronóstico?", ["No: es del lupus", "No: es del lupus (actividad renal)", "No: esclerosis sistémica limitada (CREST)",
                                             "Sí: específico y pronóstico", "Menos específico (también en otras enfermedades)"],
      {3: "Ac anti-péptidos citrulinados (anti-CCP)"}),
  d=dict(rotulo="Cada autoanticuerpo con su enfermedad", centro="ANTI-CCP", centro_sub="artritis reumatoide", ans=0,
         items=[("ANTI-CCP", ["Artritis reumatoide", "Pronóstico erosivo"]), ("ANTI-SMITH", ["Lupus (específico)"]),
                ("ANTI-ADN DC", ["Lupus, nefritis"]), ("ANTICENTRÓMERO", ["Esclerosis limitada"]), ("ANTI-SCL-70", ["Esclerosis difusa"])],
         ruta=["Poliartritis simétrica", "Anti-CCP + FR + PCR", "Rx manos y pies", "Metotrexato temprano"]),
  escala=dict(nombre="Criterios ACR/EULAR 2010 de artritis reumatoide", modo="puntaje", que="Con ≥ 6 de 10 puntos se clasifica como AR.",
              items=[("Art.", "Articulaciones (4-10 pequeñas = 3; > 10 con 1 pequeña = 5)", "Manos, muñecas y rodillas", 3),
                     ("Sero", "FR o anti-CCP (bajo = 2; alto = 3)", "Por pedir", None),
                     ("RFA", "PCR o VSG alta (1)", "Por pedir", None),
                     ("Dur.", "Duración ≥ 6 semanas (1)", "3 meses", 1)],
              total_txt="Total: 4 sin la serología", total_nota="AR si ≥ 6",
              rangos=[("< 6", "No clasifica aún", "Completar estudio"), ("≥ 6", "Artritis reumatoide", "Iniciar FAME")],
              caso_rango=0, porque=[("Con anti-CCP alto (+3) llegaría a 7: AR", True)],
              conducta="Pedir anti-CCP y FR: el anti-CCP define el diagnóstico y el pronóstico."))

# PED-144 · Enfermedad de membrana hialina · CUADRÍCULA de Rx neonatales + Silverman
S("cuadricula", "PED-144", "Prematuro de 32 semanas con quejido, aleteo, tiraje y Rx con patrón reticular fino y broncograma aéreo: enfermedad de membrana hialina",
  "Dificultad respiratoria del recién nacido",
  ("Enfermedad de membrana hialina", ["Falta de surfactante en el prematuro: los alvéolos colapsan al espirar.",
                                      "Dificultad respiratoria desde las primeras horas, que empeora; Rx en vidrio esmerilado con broncograma aéreo."]),
  ("RN de 32 semanas, 2 horas de vida", ["Aleteo nasal, quejido y tiraje intercostal marcado; SatO₂ 88 %.", "Rx: reticular fino difuso con broncograma aéreo."]),
  ["CPAP temprano (5-8 cm H₂O) y surfactante (técnica LISA/INSURE) si FiO₂ > 30 %.",
   "Prevención: corticoides prenatales entre las 24 y 34 semanas.",
   "Metas de SatO₂ 90-94 %; vigilar neumotórax."],
  "Consenso europeo de distrés respiratorio (2022); AAP (2014; act.); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: madre afebril y RPM corta; Rx parcheada", "Sí: prematuro + vidrio esmerilado + broncograma",
                        "No: a término por cesárea; mejora en 24-72 h", "No: aire alrededor del corazón", "No: término con líquido meconial"]),
  d=dict(rotulo="Dificultad respiratoria neonatal: cómo se ve la Rx", alto_img=150,
         celdas=[("Membrana hialina", ["Prematuro; vidrio esmerilado + broncograma", "Pulmones pequeños"], P("emh_rx2.jpg", 420, 373), True),
                 ("Aspiración meconial", ["Término o postérmino, líquido meconial", "Infiltrados gruesos + aire atrapado"], P("meconio_rx.jpg", 300, 287), False),
                 ("Taquipnea transitoria", ["Término por cesárea", "Líquido en cisuras; mejora en 72 h"], D(lambda s, x, y: I.torax_rx(s, x, y, "edema", sc=0.5), 150, 140), False),
                 ("Neumonía neonatal", ["RPM larga, madre febril", "Infiltrados parcheados"], D(lambda s, x, y: I.torax_rx(s, x, y, "consolidacion", sc=0.5), 150, 140), False)],
         credito="Xie et al. · Front Pediatr 2026 · PMC13260572 (CC BY 4.0) y Kinderradiologie Olgahospital Stuttgart (CC BY-SA 4.0, Commons)" + " · Abajo: esquemas propios",
         veredicto=("Prematuro de 32 semanas + vidrio esmerilado + broncograma = membrana hialina", "CPAP y surfactante.")),
  escala=dict(nombre="Escala de Silverman-Andersen", modo="puntaje", que="Grado de dificultad respiratoria del recién nacido (0 = sin dificultad).",
              items=[("Tórax", "Disociación tórax-abdomen", "No se informa", None), ("Tiraje", "Tiraje intercostal (marcado = 2)", "Marcado", 2),
                     ("Xifoides", "Retracción xifoidea", "No se informa", None), ("Aleteo", "Aleteo nasal (marcado = 2)", "Presente", 2),
                     ("Quejido", "Quejido espiratorio (audible = 2)", "Presente", 1)],
              total_txt="Total: ≥ 5 con los datos dados", total_nota="máximo 10",
              rangos=[("1-3", "Leve", "Oxígeno"), ("4-6", "Moderada", "CPAP"), ("7-10", "Grave", "Intubar")],
              caso_rango=1, porque=[("Tiraje marcado + aleteo + quejido suman ≥ 5", True)],
              conducta="CPAP y surfactante si necesita FiO₂ > 30 %."))

# GAS-054 · Colangitis aguda · ÁRBOL + Charcot + Tokio + CPRM
S("arbol", "GAS-054", "Mujer con ictericias previas, dolor cólico en hipocondrio derecho, fiebre de 39 °C, ictericia y colédoco de 15 mm: colangitis aguda",
  "Patología biliar · colangitis",
  ("Colangitis aguda", ["Infección de la vía biliar obstruida (casi siempre por un cálculo en el colédoco).",
                        "Tríada de Charcot: fiebre, ictericia y dolor en hipocondrio derecho; con choque y confusión es la péntada de Reynolds."]),
  ("Mujer de 32 años, multípara", ["Ictericias previas; dolor cólico en HCD de 2 días, náuseas y vómitos.", "T 39 °C, ictericia; eco: colédoco de 15 mm."]),
  ["Hemocultivos, líquidos y antibiótico EV (ceftriaxona + metronidazol, o piperacilina-tazobactam).",
   "Drenaje biliar por CPRE: urgente (< 24 h) si es grave, en 24-48 h si es moderada.",
   "Luego colecistectomía para evitar nuevos episodios."],
  "Guías de Tokio 2018 (TG18); ASGE, coledocolitiasis (2019); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: dolor en fosa ilíaca derecha, sin ictericia", "Sí: tríada de Charcot + colédoco dilatado", "No: dolor epigástrico en banda; sin colédoco grande",
                        "No: daría fiebre y dolor, pero no ictericia con colédoco de 15 mm", "No: no explica el colédoco dilatado ni la fiebre alta"]),
  arbol=Q("Fiebre + ictericia + dolor en HCD: ¿hay choque o confusión?", [
      L("No (este caso)", "COLANGITIS (CHARCOT)", ["Antibiótico EV", "CPRE en 24-48 h"], path=True),
      L("Sí", "Colangitis grave (Reynolds)", ["Reanimar", "CPRE urgente"])], path=True),
  triada=TR([("Fiebre", "39 °C", True), ("Ictericia", "Sí", True), ("Dolor en hipocondrio derecho", "Cólico de 2 días", True),
             ("Hipotensión (choque)", "No descrita", False), ("Confusión", "No descrita", False)],
            [("Tríada de Charcot", 0, 2), ("Péntada de Reynolds", 0, 4)], "Charcot completa sin datos de Reynolds."),
  escala=dict(nombre="Gravedad de la colangitis (Tokio 2018)", que="Decide la urgencia del drenaje biliar.",
              grados=[("Grado I", "Leve", ["Responde al tratamiento inicial"]),
                      ("Grado II", "Moderada", ["2 de: leucocitos > 12 000 o < 4000, fiebre ≥ 39 °C, edad ≥ 75, bilirrubina ≥ 5, albúmina baja"]),
                      ("Grado III", "Grave", ["Falla de órganos: choque, confusión, riñón, pulmón, coagulación"])],
              caso=[0, 1], porque=[("Fiebre de 39 °C (un criterio de grado II)", True), ("Faltan leucocitos y bilirrubina", True)],
              conducta="Antibiótico EV y CPRE temprana; si se agrava, drenaje urgente."),
  banda=B("Así se ve la obstrucción", P("cprm_coledoco.jpg", 240, 287, [
            ("flecha", 0.665, 0.52, 0.80, 0.36, "colédoco\ndilatado"),
            ("circulo", 0.56, 0.72, 0.075, "cálculos", 0.26, 0.66)],
          credito="Hellerhoff" + CC + "CC BY-SA 3.0"),
          [("Colédoco ancho", "Más de 6-8 mm: algo lo tapa abajo."),
           ("Cálculos en el colédoco", "Huecos oscuros dentro de la bilis (blanca)."),
           ("Bilis detenida", "Se infecta: fiebre e ictericia."),
           ("La CPRE drena y extrae", "Esfinterotomía y extracción del cálculo.")],
          pie="Coledocolitiasis"))

# REU-043 · Anafilaxia por abejas: adrenalina · RELOJ + criterios + urticaria
S("reloj", "REU-043", "Joven con picaduras de abejas, disnea, estridor, sibilancias, cianosis y PA 80/50: anafilaxia, el tratamiento es adrenalina intramuscular",
  "Urgencias · anafilaxia",
  ("Anafilaxia", ["Reacción alérgica grave y rápida (IgE) con compromiso de vía aérea, respiración o circulación.",
                  "La adrenalina IM es el único fármaco que la revierte; antihistamínicos y corticoides solo ayudan."]),
  ("Joven de 20 años, picaduras de abejas", ["Cuerpo extraño en la garganta, cefalea y disnea.", "PA 80/50, FC 120, cianosis, estridor y sibilancias."]),
  ["Adrenalina 0,5 mg IM (1 mg/mL) en la cara lateral del muslo; repetir cada 5-15 min si no mejora.",
   "Acostado con piernas elevadas, oxígeno a flujo alto y suero fisiológico 1-2 L rápido.",
   "Observar 6-12 h (reacción bifásica); al alta, autoinyector y referencia a alergología (inmunoterapia con veneno)."],
  "WAO, guía de anafilaxia (2020); EAACI (2021); Resuscitation Council UK (2021); " + AHA + ".",
  op=("¿Tratamiento?", ["Ayuda con la piel; no revierte el choque", "Sí: revierte vía aérea y circulación", "Tardía; no es de rescate",
                        "Solo broncoespasmo; no el choque ni el edema", "No: no trata la anafilaxia"]),
  d=dict(rotulo="Minuto a minuto en la anafilaxia",
         pasos=[("0'", "Adrenalina IM", "0,5 mg en el muslo", True), ("0'", "Posición y O₂", "Acostado, piernas arriba", False),
                ("1-5'", "Suero rápido", "1-2 L de cristaloides", False), ("5-15'", "Repetir adrenalina", "Si no mejora", False),
                ("Luego", "Antihistamínico ± corticoide", "Para la piel", False), ("6-12 h", "Observar", "Riesgo bifásico", False)],
         tag="PRIMERO",
         veredicto=("Choque + estridor tras picadura: adrenalina IM ya", "Nada la reemplaza; lo demás es complementario.")),
  triada=TR([("Piel o mucosas", "Sensación de cuerpo extraño", None), ("Respiratorio", "Estridor, sibilancias, cianosis", True),
             ("Circulatorio", "PA 80/50, FC 120", True)],
            [("Criterio de anafilaxia (WAO 2020)", 0, 2)], "Exposición a un alérgeno + compromiso respiratorio o circulatorio = anafilaxia."),
  banda=B("Lo que suele verse en la piel", P("urticaria.jpg", 210, 280, [], credito="Psixtras" + CC + "CC0"),
          [("Ronchas que pican", "Urticaria: aparece en el 80-90 %."),
           ("Puede faltar", "En el choque la piel puede estar pálida."),
           ("No esperar la piel", "Con vía aérea o PA comprometidas, adrenalina.")],
          pie="Urticaria"))

# GIN-145 · Pielonefritis en la gestante: ceftriaxona · CHECKLIST + ITU
S("checklist", "GIN-145", "Gestante de 28 semanas con fiebre de 39 °C, escalofríos, dolor lumbar y puño-percusión positiva: pielonefritis, ceftriaxona EV",
  "Infección urinaria en el embarazo",
  ("Pielonefritis en el embarazo", ["La progesterona dilata los uréteres y el útero los comprime: la bacteriuria sube al riñón.",
                                    "Riesgo de parto prematuro, sepsis y SDRA: se hospitaliza."]),
  ("Gestante de 28 semanas", ["Malestar, dolor lumbar y escalofríos.", "T 39 °C, puño-percusión derecha (+)."]),
  ["Hospitalizar; urocultivo y hemocultivos antes del antibiótico.",
   "Ceftriaxona 1-2 g EV/día; pasar a oral (cefalexina) 48 h sin fiebre; total 10-14 días.",
   "Luego profilaxis (nitrofurantoína o cefalexina nocturna) hasta el parto y urocultivo de control."],
  ACOG + "; " + MINSA + ", guía de ITU en gestantes; IDSA; " + WILLIAMS + ".",
  op=("¿Antibiótico?", ["No: no cubre bien E. coli", "Sí: segura y eficaz", "No: contraindicada en el embarazo",
                        "No: no alcanza niveles en el riñón", "No: no cubre gramnegativos"]),
  d=dict(rotulo="Qué hacer con una gestante con pielonefritis", tag="ELECCIÓN",
         pasos=[("Hospitalizar", "Vigilar contracciones y bienestar fetal", False),
                ("Urocultivo y hemocultivos", "Antes del antibiótico", False),
                ("Ceftriaxona EV", "1-2 g/día; oral cuando esté 48 h sin fiebre", True),
                ("Profilaxis hasta el parto", "Y urocultivo de control", False)],
         no_hacer=[("Nitrofurantoína para tratar", "No llega al riñón (sí sirve de profilaxis)"), ("Quinolonas o doxiciclina", "Contraindicadas en el embarazo"),
                   ("Tratar en casa", "Riesgo de sepsis y parto prematuro")],
         veredicto=("Pielonefritis en la gestante: ceftriaxona EV hospitalizada", "Completar 10-14 días y profilaxis hasta el parto.")),
  escala=ITU(2, [("Fiebre 39 °C + escalofríos", True), ("Dolor lumbar y puño-percusión (+)", True)],
             "Hospitalizar, cultivos y ceftriaxona EV."))

# TRA-032 · Síndrome compartimental · REGLA de presión + 6 P
S("regla", "TRA-032", "Aplastamiento de piernas hace 2 horas con dolor que no cede con analgésicos, parestesias, palidez, tumefacción y pulso pedio ausente: síndrome compartimental",
  "Trauma de extremidades · síndrome compartimental",
  ("Síndrome compartimental agudo", ["El músculo se hincha dentro de una fascia que no se estira: sube la presión y deja de llegar sangre.",
                                     "Lo primero es el dolor desproporcionado y al estirar el músculo; el pulso ausente es tardío."]),
  ("Varón de 36 años, 2 horas", ["Aplastamiento de miembros inferiores por una pared.", "Dolor que no cede, parestesias, palidez, tumefacción, sin pulso pedio izquierdo."]),
  ["Retirar yesos y vendajes, pierna a la altura del corazón (no elevar).",
   "Fasciotomía urgente de los 4 compartimentos: es una emergencia (en menos de 6 h).",
   "Vigilar rabdomiólisis: CPK, potasio, función renal; líquidos abundantes."],
  ATLS + "; BOAST, síndrome compartimental (2016); AAOS.",
  op=("¿Diagnóstico?", ["No: 24-72 h tras fractura de huesos largos, con petequias y disnea", "No: dolor y edema, pero pulso presente",
                        "No: dolor lumbar con irradiación", "Sí: aplastamiento + dolor desproporcionado + parestesias", "Se asocia, pero no explica el pulso ausente"]),
  d=dict(rotulo="Cuándo hay que abrir: la presión del compartimento",
         reglas=[dict(nombre="Presión de perfusión = presión diastólica − presión del compartimento (mmHg)",
                      que="Si la diferencia es < 30 mmHg, la sangre ya no entra: fasciotomía.",
                      min=0, max=70, fmt="{}", ticks=[0, 10, 20, 30, 40, 50, 60, 70],
                      bandas=[(0, 30, "< 30: FASCIOTOMÍA", 3), (30, 40, "Vigilar", 1), (40, 70, "Normal", 0)],
                      caso=None, pie="Este caso: la clínica basta; no esperar la medición para operar", pie_on=True)],
         claves_titulo="Lo que se hace",
         claves=[("Quitar vendajes y yesos", ["Pierna a la altura del corazón"], False), ("Fasciotomía urgente", ["4 compartimentos"], True),
                 ("Riñón", ["CPK, potasio; líquidos"], False)]),
  triada=TR([("Dolor que no cede", "Pese a analgésicos", True), ("Parestesias", "Sí", True), ("Palidez", "Sí", True),
             ("Pulso ausente", "Pedio izquierdo", True), ("Parálisis", "No descrita", False), ("Poiquilotermia (frío)", "No descrita", False)],
            [("Las 6 P (las últimas son tardías)", 0, 5)], "El dolor y las parestesias son tempranos; sin pulso ya es tarde: fasciotomía ya."))

# CB-054 · Benzodiacepinas: flumazenilo · RADIAL de antídotos
S("radial", "CB-054", "Joven sedado tras un trago ofrecido en una discoteca, con disartria, ataxia e hipotonía, que despierta con flumazenilo: le dieron una benzodiacepina (diazepam)",
  "Toxicología · antídotos",
  ("Intoxicación por benzodiacepinas", ["Sedación, disartria, ataxia e hipotonía con signos vitales casi normales.",
                                        "El flumazenilo las revierte: si despierta, confirma la sospecha."]),
  ("Varón de 35 años, discoteca", ["Alteración de la conciencia; PA 100/60, FC 62, FR 16.", "Disartria, ataxia e hipotonía; despierta con flumazenilo."]),
  ["Soporte: vía aérea, oxígeno, monitorizar; casi siempre basta.",
   "Flumazenilo con cuidado: puede desencadenar convulsiones en dependientes de BZD o en intoxicación mixta con tricíclicos.",
   "Pensar en sumisión química: guardar muestras y notificar."],
  "Goldfrank's Toxicologic Emergencies 11.ª ed.; AHA, toxicología (2023).",
  op=("¿Sustancia?", ["No: no se revierte con flumazenilo", "Sí: el flumazenilo lo revierte", "No: daría agitación y midriasis",
                      "No: no responde al flumazenilo", "No: no se revierte con flumazenilo"]),
  d=dict(rotulo="Cada antídoto con su tóxico", centro="FLUMAZENILO", centro_sub="benzodiacepinas", ans=0,
         items=[("FLUMAZENILO", ["Benzodiacepinas"]), ("NALOXONA", ["Opioides"]), ("ATROPINA", ["Organofosforados"]),
                ("N-ACETILCISTEÍNA", ["Paracetamol"]), ("FISOSTIGMINA", ["Anticolinérgicos"])],
         ruta=["Soporte ABC", "Sospechar por la clínica", "Flumazenilo con cuidado", "Notificar si hubo sumisión"]))

# PED-145 · Estenosis pilórica: ecografía · LECTURA (eco real) + regla
S("lectura", "PED-145", "Lactante varón de 10 días con vómitos explosivos tras lactar y masa en el epigastrio: estenosis hipertrófica del píloro, pedir ecografía",
  "Vómitos en el lactante · estenosis pilórica",
  ("Estenosis hipertrófica del píloro", ["El músculo del píloro se engruesa y no deja pasar la leche: vómitos «en proyectil» sin bilis entre las 2 y 8 semanas.",
                                         "Se palpa la «oliva» pilórica; alcalosis metabólica hipoclorémica e hipopotasémica."]),
  ("Neonato varón de 10 días", ["Vómitos explosivos después de lactar.", "Masa palpable en el epigastrio."]),
  ["Ecografía: músculo ≥ 3-4 mm de grosor y canal ≥ 15-17 mm de largo.",
   "Primero corregir líquidos y la alcalosis (ClNa + KCl); luego piloromiotomía de Ramstedt.",
   "No es urgencia quirúrgica: es urgencia metabólica."],
  "APSA; " + NELSON + "; AAP.",
  op=("¿Estudio?", ["No: invasiva y no necesaria", "No: no se usa", "No: poco específica", "Sí: de elección, sin radiación", "Ya no de rutina: la eco basta"]),
  d=dict(rotulo="Lee la ecografía en este orden", img_titulo="Ecografía del píloro",
         img=P("piloro.jpg", 340, 320, [], credito="Laughlin Dawes" + CC + "CC BY-SA 4.0"),
         pines=[(0.30, 0.66), (0.55, 0.72)],
         pasos=[("Pared del músculo gruesa", "≥ 3-4 mm (normal < 2 mm).", True),
                ("Canal largo", "≥ 15-17 mm.", False),
                ("No pasa contenido", "El estómago no vacía durante el estudio.", False),
                ("Corregir antes de operar", "Alcalosis hipoclorémica e hipopotasemia.", False)],
         img_pie="Estenosis pilórica",
         veredicto=("Vómitos en proyectil + oliva = estenosis pilórica: ecografía", "Corregir la alcalosis y luego piloromiotomía.")))
