"""Entrega 1 · tanda 00 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, AAP, OMS, IDSA
from esc28 import HTA_EMB

CC = " · Wikimedia Commons · "

# OFT-002 · Quemadura química ocular · ÁRBOL + clasificación de Roper-Hall
S("arbol", "OFT-002", "Ácido en el ojo: irrigar de inmediato, antes de cualquier otra cosa",
  "Urgencias oftalmológicas · quemadura química",
  ("Quemadura química del ojo", ["El químico sigue dañando mientras esté en contacto con la córnea y la conjuntiva.",
                                 "Los álcalis penetran más que los ácidos, pero ambos se lavan de inmediato."]),
  ("Mujer de 25 años", ["Le salpicó ácido muriático (clorhídrico) en el ojo derecho al limpiar el inodoro."]),
  ["Lavar ya con suero fisiológico o agua del caño, 30 minutos o hasta pH 7-7,5; no esperar al especialista.",
   "No neutralizar con otra sustancia: la reacción química libera calor y daña más.",
   "Tras el lavado: evertir párpados, retirar partículas, graduar la lesión (Roper-Hall o Dua) y derivar."],
  "AAO, EyeWiki: Chemical (alkali and acid) injury of the eye (2024); Dua et al., Br J Ophthalmol; " + HARRISON + ".",
  op=("¿Correcto?", ["Sí: lavar es lo primero", "No: frotar y cubrir retrasa el lavado", "No: primero lavar; corticoides después",
                     "No: el parche retiene el químico", "No: neutralizar produce calor y más daño"],
      {0: "Irrigar de inmediato", 1: "Limpiar con paño y ungüento", 2: "Corticoides tópicos", 3: "Parche y llamar al especialista",
       4: "Neutralizar con un álcali"}),
  arbol=Q("¿Entró un químico (ácido o álcali) al ojo?", [
      L("Sí (este caso)", "IRRIGAR YA", ["Suero fisiológico o agua, 30 min", "Hasta pH 7-7,5 en el fondo de saco",
                                          "Anestésico tópico y evertir párpados"], path=True),
      L("Después del lavado", "Graduar y derivar", ["Roper-Hall: opacidad corneal e isquemia del limbo",
                                                     "Lubricantes, antibiótico tópico, analgesia"])], path=True),
  escala=dict(nombre="Clasificación de Roper-Hall", que="Gravedad de la quemadura química según la córnea y el limbo; se gradúa DESPUÉS de lavar.",
              grados=[("Grado I", "Buen pronóstico", ["Daño del epitelio corneal", "Sin isquemia del limbo"]),
                      ("Grado II", "Buen pronóstico", ["Córnea algo opaca, se ve el iris", "Isquemia < 1/3 del limbo"]),
                      ("Grado III", "Pronóstico reservado", ["Pérdida total del epitelio", "Estroma opaco: el iris se ve borroso",
                                                            "Isquemia de 1/3 a 1/2 del limbo"]),
                      ("Grado IV", "Mal pronóstico", ["Córnea opaca: no se ve el iris ni la pupila", "Isquemia > 1/2 del limbo"])],
              caso=None, porque_titulo="En este caso",
              porque=[("Todavía no se gradúa: primero se lava; el grado se define al examinar después", True),
                      ("Esperar al especialista sin lavar empeora el grado final", False)],
              conducta="Lavado inmediato y abundante; luego examen con fluoresceína, graduación y derivación a oftalmología."))

# PED-003 · Síndrome de Down · TARJETAS
S("tarjetas", "PED-003", "Nariz plana, epicanto, manchas de Brushfield y soplo: trisomía 21",
  "Genética · cromosomopatías del recién nacido",
  ("Síndrome de Down (trisomía 21)", ["La cromosomopatía más frecuente en el recién nacido vivo.",
                                       "Rasgos faciales típicos, hipotonía y cardiopatía en casi la mitad (canal AV)."]),
  ("Varón de 7 días, parto en casa", ["Nariz plana, manchas grises alrededor del iris (Brushfield).",
                                      "Braquicefalia, epicanto y soplo sistólico."]),
  ["Confirmar con cariotipo; ecocardiograma a todos (el canal AV y la CIV son las más frecuentes).",
   "Buscar hipotiroidismo, cataratas, sordera y atresia duodenal; controles según la AAP (2022).",
   "Edad materna avanzada es el principal factor de riesgo (no disyunción en la meiosis I)."],
  "AAP, Health supervision for children and adolescents with Down syndrome (Pediatrics 2022); " + NELSON + ".",
  op=("¿Encaja?", ["No: talla baja y cuello alado, sin Brushfield", "Sí: Brushfield, epicanto, braquicefalia y soplo",
                   "No: labio leporino, polidactilia, defectos del cuero cabelludo", "No: se nota en la pubertad (testículos pequeños)",
                   "No: puños cerrados, pies en mecedora"],
      {0: "Monosomía X (Turner)", 1: "Trisomía 21", 2: "Trisomía 13", 3: "XXY (Klinefelter)", 4: "Trisomía 18"}),
  d=dict(rotulo="Cromosomopatías en el recién nacido", ans=0,
         cards=[dict(titulo="Trisomía 21 (Down)", datos=[("Cara", "Plana, epicanto", True), ("Ojos", "Manchas de Brushfield", True),
                                                       ("Corazón", "Canal AV o CIV", True)], pie="Este caso."),
                dict(titulo="Trisomía 18 (Edwards)", datos=[("Manos", "Puños cerrados, dedos montados", False),
                                                          ("Pies", "En mecedora", False), ("Cráneo", "Occipucio prominente", False)],
                     pie="Mal pronóstico el primer año."),
                dict(titulo="Trisomía 13 (Patau)", datos=[("Cara", "Labio y paladar hendido", False), ("Manos", "Polidactilia", False),
                                                        ("Cráneo", "Defectos del cuero cabelludo", False)], pie="Holoprosencefalia."),
                dict(titulo="Turner (45,X)", datos=[("Cuello", "Alado", False), ("Edema", "Manos y pies (RN)", False),
                                                  ("Corazón", "Coartación aórtica", False)], pie="Talla baja, amenorrea.")]))

# CIR-003 · Tórax inestable con insuficiencia respiratoria · ÁRBOL
S("arbol", "CIR-003", "Fracturas costales dobles del 2.º al 6.º arco con dificultad respiratoria: tórax inestable",
  "Trauma torácico · tórax inestable",
  ("Tórax inestable (volet costal)", ["Dos o más costillas seguidas rotas en dos o más sitios: un segmento se mueve al revés (respiración paradójica).",
                                      "Lo grave es la contusión pulmonar que hay debajo y el dolor que impide respirar."]),
  ("Mujer de 34 años, accidente de tránsito", ["Disnea, FR 27, FC 105; murmullo disminuido en hemitórax izquierdo.",
                                               "Rx: doble trazo de fractura del 2.º al 6.º arco; senos costofrénicos libres."]),
  ["Manejo: oxígeno, analgesia potente (bloqueo regional o epidural) y vigilancia; el tórax se fija solo en casos seleccionados.",
   "Intubar si hay insuficiencia respiratoria (hipoxemia, fatiga, FR alta) pese al oxígeno y la analgesia.",
   "Senos libres: no hay hemotórax que drenar; la tomografía no es lo primero si respira mal."],
  ATLS + "; EAST, guía de fracturas costales (2023).",
  op=("¿Correcto ahora?", ["No: primero asegurar la vía aérea", "No: no hay hemotórax ni neumotórax", "Necesaria, pero no basta con IR",
                           "Sí: insuficiencia respiratoria", "No: es diferida y selectiva"],
      {0: "TC de tórax", 1: "Drenaje torácico", 2: "Analgesia óptima", 3: "Intubación orotraqueal", 4: "Fijación costal inmediata"}),
  arbol=Q("¿Dos o más costillas seguidas con doble fractura (segmento libre)?", [
      L("Sí: 2.º a 6.º arco (este caso)", "TÓRAX INESTABLE", ["Oxígeno, analgesia y monitoreo", "Buscar contusión pulmonar"], path=True,
        children=[Q("¿Insuficiencia respiratoria (disnea, FR > 25, hipoxemia)?", [
            L("Sí (este caso)", "INTUBAR Y VENTILAR", ["Ventilación con presión positiva", "Analgesia y fijación diferida si se indica"], path=True),
            L("No", "Manejo conservador", ["Bloqueo regional o epidural", "Fisioterapia respiratoria"])], path=True)]),
      L("No", "Fractura costal simple", ["Analgesia y control"])], path=True))

# INF-002 · Coronavirus · TARJETAS
S("tarjetas", "INF-002", "Fiebre, cefalea, estornudos y tos de 2 días: coronavirus (virus ARN)",
  "Virología · infecciones respiratorias",
  ("Virus de las infecciones respiratorias", ["Coronavirus: ARN de cadena simple positiva, con envoltura.",
                                              "El diagnóstico es por RT-PCR o antígeno en hisopado nasofaríngeo, no en sangre."]),
  ("Varón de 30 años, sano", ["2 días de fiebre (38,6 °C), cefalea, estornudos y tos.", "FC 90, FR 18: sin signos de gravedad."]),
  ["SARS-CoV-2 y los coronavirus estacionales: ARN (+), envoltura, espículas que se unen a ACE2 (SARS-CoV-2).",
   "Se confirma con RT-PCR o prueba de antígeno de hisopado nasofaríngeo.",
   "Herpesvirus es ADN; paramixovirus (sarampión, parotiditis, VSR) y rabdovirus (rabia) son ARN (-); flavivirus (dengue) es ARN (+)."],
  "OMS, manejo clínico de la COVID-19 (2025); CDC, Overview of testing for SARS-CoV-2 (2024); " + HARRISON + ".",
  op=("Genoma y cuadro", ["ARN (-): sarampión, parotiditis, VSR", "ARN (-): rabia", "ARN (+): dengue, zika, fiebre amarilla",
                          "ARN (+): resfrío y COVID-19", "ADN: no es ARN"]),
  d=dict(rotulo="¿Qué virus da este cuadro respiratorio?", ans=0,
         cards=[dict(titulo="Coronavirus", datos=[("Genoma", "ARN (+), envoltura", True), ("Cuadro", "Fiebre, tos, rinorrea", True),
                                                ("Prueba", "RT-PCR nasofaríngea", True)], pie="Este caso."),
                dict(titulo="Paramixovirus", datos=[("Genoma", "ARN (-)", False), ("Cuadro", "Sarampión, parotiditis", False),
                                                  ("Prueba", "Serología, PCR", False)], pie="Exantema o parótidas."),
                dict(titulo="Flavivirus", datos=[("Genoma", "ARN (+)", False), ("Cuadro", "Dengue, zika", False),
                                               ("Transmisión", "Mosquito Aedes", False)], pie="Fiebre sin cuadro catarral."),
                dict(titulo="Herpesvirus", datos=[("Genoma", "ADN", False), ("Cuadro", "Vesículas, mononucleosis", False),
                                                ("Latencia", "Sí, de por vida", False)], pie="No es ARN.")]))

# GIN-003 · Detención de la dilatación con desaceleraciones · ÁRBOL
S("arbol", "GIN-003", "Fase activa detenida 6 horas en 6 cm con desaceleraciones: cesárea",
  "Distocias · trabajo de parto detenido",
  ("Detención de la fase activa", ["La fase activa empieza a los 6 cm (OMS 2018, ACOG).",
                                   "Detención: sin cambio por ≥ 4 h con contracciones adecuadas o ≥ 6 h si son inadecuadas, con membranas rotas."]),
  ("Gestante a término, fase activa", ["6 cm sin avance por 6 horas, membranas íntegras.",
                                       "Contracciones 3 en 10 minutos de 40 segundos; desaceleraciones de la FCF."]),
  ["Detención de la dilatación + desaceleraciones (bienestar fetal no tranquilizador) = cesárea.",
   "Si el feto estuviera bien, antes de llamarla detención se rompen membranas y se refuerzan contracciones con oxitocina.",
   "Ante desaceleraciones: decúbito lateral izquierdo, suspender oxitocina, oxígeno si hay hipoxemia materna y evaluar el registro."],
  ACOG + ", Obstetric Care Consensus n.º 1 (2014, reafirmado); OMS, recomendaciones de cuidados intraparto (2018); " + WILLIAMS + ".",
  op=("¿Adecuada?", ["Sí: detención + sufrimiento fetal", "No: si se cambia de posición es al lado izquierdo",
                     "No: no corrige el riesgo fetal", "No: la oxitocina empeora las desaceleraciones", "No: 6 h sin avance"],
      {1: "Decúbito lateral derecho", 3: "Acentuar con oxitocina"}),
  arbol=Q("¿Dilatación ≥ 6 cm sin cambios ≥ 4 h (o ≥ 6 h con contracciones débiles)?", [
      L("Sí: 6 cm por 6 horas (este caso)", "Detención de la fase activa", ["Evaluar bienestar fetal"], path=True,
        children=[Q("¿Desaceleraciones o registro no tranquilizador?", [
            L("Sí (este caso)", "CESÁREA", ["Reanimación intrauterina mientras se prepara"], path=True),
            L("No", "Amniotomía y oxitocina", ["Reevaluar en 2-4 horas"])], path=True)]),
      L("No", "Progreso normal", ["Vigilancia con partograma"])], path=True))

# CIR-002 · Apendicitis aguda en escolar · TÉRMINO + escala PAS
S("embudo", "CIR-002", "Escolar con dolor periumbilical que baja a fosa ilíaca derecha, vómitos y rebote: apendicitis aguda",
  "Abdomen agudo · apendicitis en el niño",
  ("Apendicitis aguda", ["La urgencia quirúrgica abdominal más frecuente en niños.",
                         "Dolor periumbilical que migra a fosa ilíaca derecha, vómitos después del dolor, fiebre y signos peritoneales."]),
  ("Escolar con 24 horas de dolor", ["Dolor periumbilical, luego vómitos y sensación de alza térmica.",
                                     "Defensa en hemiabdomen inferior derecho y rebote (+)."]),
  ["En el niño se usa la escala pediátrica de apendicitis (PAS): ≥ 7 cirugía, 4-6 ecografía, ≤ 3 poco probable.",
   "La ecografía es el primer examen de imagen en niños (sin radiación).",
   "Gastroenteritis: diarrea antes o junto al dolor; adenitis mesentérica: tras un cuadro viral, sin rebote."],
  "WSES Jerusalem guidelines on acute appendicitis (2020, act. 2024); Samuel M, J Pediatr Surg (2002); " + NELSON + ".",
  op=("¿Encaja?", ["No: sin diarrea; el dolor es localizado", "Sí: migración, vómitos, defensa y rebote",
                   "No: sin rebote, suele seguir a un cuadro viral", "No: menor de 2 años, cólicos y heces en jalea",
                   "No: fiebre alta, disuria, dolor lumbar"]),
  d=dict(rotulo="Del dolor abdominal al diagnóstico", inicio="Escolar con dolor abdominal de 24 horas",
         candidatos=["Gastroenterocolitis", "Invaginación", "Pielonefritis", "Adenitis mesentérica", "Apendicitis aguda"],
         pasos=[("¿Diarrea, edad < 2 años o síntomas urinarios?", ["Gastroenterocolitis", "Invaginación", "Pielonefritis"]),
                ("¿Defensa y rebote localizados en fosa ilíaca derecha?", ["Adenitis mesentérica"])],
         final=("APENDICITIS AGUDA", ["Dolor que migra + vómitos + rebote"]),
         nota="Signos peritoneales localizados: apendicitis hasta demostrar lo contrario."),
  escala=dict(nombre="Escala pediátrica de apendicitis (PAS)", modo="puntaje",
              que="Samuel 2002: suma 8 datos (máximo 10) para decidir entre observar, ecografía o cirugía.",
              items=[("M", "Migración del dolor a fosa ilíaca derecha", "Dolor periumbilical que baja al lado derecho", 1),
                     ("A", "Anorexia", "No se menciona", None),
                     ("N", "Náuseas o vómitos", "Vómitos", 1),
                     ("D", "Dolor en fosa ilíaca derecha", "Defensa en el lado derecho", 2),
                     ("T", "Dolor al toser, saltar o percutir", "Rebote (+): irritación del peritoneo", 2),
                     ("F", "Fiebre ≥ 38 °C", "Solo «sensación de alza térmica»", None),
                     ("L", "Leucocitos > 10 000", "Sin hemograma", None),
                     ("N", "Neutrófilos > 75 %", "Sin hemograma", None)],
              total_txt="Total: 6 puntos con los datos dados", total_nota="faltan fiebre medida y hemograma",
              rangos=[("≤ 3", "Poco probable", "Observar o buscar otra causa"), ("4-6", "Riesgo intermedio", "Ecografía y hemograma"),
                      ("≥ 7", "Riesgo alto", "Valoración por cirugía")],
              caso_rango=1,
              porque=[("Con fiebre ≥ 38 °C o leucocitosis llegaría a 7 o más: riesgo alto", True)],
              conducta="Hemograma y ecografía; con rebote localizado, interconsulta a cirugía sin demora."))

# PED-002 · Artritis séptica de rodilla · TARJETAS
S("tarjetas", "PED-002", "Niño con fiebre y rodilla roja, caliente e inflamada: artritis séptica",
  "Infecciones osteoarticulares en el niño",
  ("Artritis séptica", ["Infección bacteriana de la articulación: urgencia por destrucción del cartílago.",
                        "En niños, S. aureus es el germen más frecuente; Kingella kingae en menores de 4 años."]),
  ("Niño de 5 años", ["Cayó sobre la rodilla hace 6 días; ahora fiebre de 38,5 °C, decaimiento.",
                      "Rodilla con dolor, gran aumento de volumen, calor, rubor y posición antiálgica."]),
  ["Confirmar con artrocentesis (> 50 000 leucocitos/mm³, Gram y cultivo) y ecografía; hemocultivos.",
   "Tratamiento: lavado articular urgente + antibiótico EV (cefazolina o clindamicina; vancomicina si hay SARM).",
   "La sinovitis transitoria afecta la cadera, sin fiebre alta ni signos inflamatorios intensos."],
  "IDSA/PIDS, guía de artritis séptica pediátrica (2023); " + NELSON + ".",
  op=("¿Encaja?", ["No: es aguda (6 días)", "No: no explica la fiebre", "Sí: fiebre + articulación roja y caliente",
                   "No: sin fiebre; sangre en la articulación", "No: es de cadera y sin fiebre alta"]),
  d=dict(rotulo="Rodilla dolorosa e hinchada en el niño", ans=0,
         cards=[dict(titulo="Artritis séptica", datos=[("Fiebre", "Sí, 38,5 °C", True), ("Articulación", "Roja, caliente, hinchada", True),
                                                     ("Líquido", "Purulento, > 50 000 leucocitos", True)], pie="Este caso: lavado + antibiótico."),
                dict(titulo="Sinovitis transitoria", datos=[("Fiebre", "No o leve", False), ("Dónde", "Cadera", False),
                                                          ("Antes", "Cuadro viral", False)], pie="Reposo y AINE."),
                dict(titulo="Hemartrosis", datos=[("Fiebre", "No", False), ("Líquido", "Sangre", False),
                                                ("Antes", "Trauma o hemofilia", False)], pie="Buscar coagulopatía."),
                dict(titulo="Osteomielitis crónica", datos=[("Tiempo", "Semanas a meses", False), ("Signo", "Fístula, secuestro", False),
                                                          ("Rx", "Lisis y esclerosis", False)], pie="No es aguda.")]))

# NRL-002 · Hemorragia subaracnoidea · EMBUDO + TC real + Hunt-Hess
S("embudo", "NRL-002", "Cefalea súbita «la peor de su vida», vómitos, pérdida de conciencia y rigidez de nuca: hemorragia subaracnoidea",
  "Enfermedad cerebrovascular · hemorragia subaracnoidea",
  ("Hemorragia subaracnoidea (HSA)", ["Sangre en el espacio subaracnoideo, casi siempre por rotura de un aneurisma.",
                                      "Cefalea en trueno: máxima intensidad en menos de un minuto."]),
  ("Mujer de 62 años", ["Cefalea súbita muy intensa con vómitos mientras hacía labores del hogar.",
                        "Luego pierde la conciencia; rigidez de nuca al examen."]),
  ["TC sin contraste en las primeras 6 horas detecta casi el 100 %; si es normal y la sospecha sigue, punción lumbar (xantocromía).",
   "Angio-TC para buscar el aneurisma; tratarlo (coil o clip) en las primeras 24-72 h; nimodipino por 21 días.",
   "Graduar con Hunt-Hess o WFNS (Glasgow + déficit motor): guía el pronóstico."],
  "AHA/ASA, guía de hemorragia subaracnoidea aneurismática (2023); " + HARRISON + ".",
  op=("¿Encaja?", ["No: tras trauma, curso de días", "No: cefalea progresiva, no súbita", "No: no da cefalea en trueno ni rigidez de nuca",
                   "Sí: cefalea súbita + rigidez de nuca", "No: aura previa, sin pérdida de conciencia ni rigidez"]),
  d=dict(rotulo="Cefalea súbita: ¿qué es?", inicio="Cefalea súbita intensa con vómitos",
         candidatos=["Migraña con aura", "Tumor cerebral", "Hematoma subdural", "Isquemia transitoria", "Hemorragia subaracnoidea"],
         pasos=[("¿Inicio progresivo, aura o trauma previo?", ["Migraña con aura", "Tumor cerebral", "Hematoma subdural"]),
                ("¿Déficit que se recupera sin cefalea ni rigidez?", ["Isquemia transitoria"])],
         final=("HEMORRAGIA SUBARACNOIDEA", ["Cefalea en trueno + rigidez de nuca"]),
         nota="Cefalea en trueno = TC sin contraste urgente."),
  escala=dict(nombre="Escala de Hunt y Hess", que="Gravedad clínica de la HSA al ingreso; predice el pronóstico.",
              grados=[("Grado I", "Leve", ["Sin síntomas o cefalea leve", "Rigidez de nuca leve"]),
                      ("Grado II", "Moderado", ["Cefalea moderada a intensa", "Rigidez de nuca", "Sin déficit (salvo pares craneales)"]),
                      ("Grado III", "Somnolencia", ["Somnoliento o confuso", "Déficit focal leve"]),
                      ("Grado IV", "Estupor", ["Estupor", "Hemiparesia moderada a grave"]),
                      ("Grado V", "Coma", ["Coma profundo", "Rigidez de descerebración"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Cefalea intensa con rigidez de nuca: al menos grado II", True),
                      ("Perdió la conciencia: si sigue somnolienta, en estupor o en coma, sube a III, IV o V; falta el examen actual", False)],
              conducta="TC sin contraste ya, angio-TC, nimodipino y tratar el aneurisma en 24-72 h; la escala orienta el pronóstico."),
  banda=B("TC real de hemorragia subaracnoidea", P("hsa_tc.jpg", 300, 344, [
            ("flecha", 0.48, 0.42, 0.5, 0.05, "sangre en las\ncisternas basales"),
            ("flecha", 0.385, 0.39, 0.16, 0.6, "cisura de\nSilvio"),
            ("flecha", 0.575, 0.39, 0.84, 0.6, "cisura de\nSilvio")],
          credito="George Jallo" + CC + "CC BY-SA 3.0"),
          [("Blanco donde debería ser negro", "El líquido cefalorraquídeo se ve oscuro; la sangre fresca se ve blanca en la TC."),
           ("Estrella en la base del cerebro", "La sangre llena las cisternas alrededor del polígono de Willis, donde nacen los aneurismas."),
           ("Se extiende por las cisuras", "Sigue las cisuras de Silvio a ambos lados: por eso irrita las meninges y da rigidez de nuca."),
           ("Si la TC sale normal", "Pasadas 6 horas la sensibilidad baja: punción lumbar buscando xantocromía (pigmento amarillo).")],
          pie="TC de otro paciente con el mismo hallazgo (se borró una línea del autor).", ans=1))

# REU-002 · Carotinemia · MATRIZ
S("matriz", "REU-002", "Piel amarilla con escleras limpias en una vegana: carotinemia",
  "Dermatología · trastornos de la pigmentación",
  ("Carotinemia", ["Exceso de carotenos en la dieta (zanahoria, zapallo, papaya): tiñe la capa córnea.",
                   "Respeta las escleras y las mucosas, y no hay coluria: la bilirrubina es normal."]),
  ("Mujer de 24 años, dieta vegana", ["Piel amarillenta sin coluria.", "Escleras limpias."]),
  ["Escleras amarillas = bilirrubina alta (ictericia); escleras limpias con piel amarilla = carotinemia.",
   "Predomina en palmas, plantas y surcos nasogenianos; es benigna y cede al reducir los carotenos.",
   "Descartar hipotiroidismo, diabetes y anorexia nerviosa, que reducen la conversión de carotenos."],
  "DermNet, Carotenaemia (2023); " + HARRISON + ".",
  op=("¿Encaja?", ["No: no toma quinacrina", "No: daría escleras amarillas y coluria", "No: es el LCR amarillo, no la piel",
                   "Sí: dieta + escleras limpias", "No: escleras amarillas y coluria"],
      {0: "Quinacrina", 2: "Xantocromía", 4: "Ictericia obstructiva"}),
  d=dict(rotulo="¿Piel amarilla por bilirrubina o por carotenos?", eje_x="Escleras", eje_y="Orina",
         cols=["Amarillas", "Limpias"], rows=["Coluria (orina oscura)", "Sin coluria", "Con fármaco amarillo"], caso=(1, 1),
         cells=[[("ICTERICIA COLESTÁSICA", ["Bilirrubina directa alta", "Acolia, prurito"]), ("Rara", ["Revisar de nuevo las escleras"])],
                [("Ictericia hemolítica", ["Bilirrubina indirecta alta", "Anemia"]), ("CAROTINEMIA", ["Palmas y plantas", "Dieta rica en carotenos"])],
                [("Fármaco + ictericia", ["Hepatotoxicidad"]), ("Quinacrina", ["Tiñe la piel; antecedente del fármaco"])]]))

# GIN-002 · RPM pretérmino · ÁRBOL por edad gestacional + test del helecho real
S("arbol", "GIN-002", "Rotura prematura de membranas a las 32 semanas confirmada con el test del helecho: antibióticos",
  "Rotura prematura de membranas pretérmino",
  ("Rotura prematura de membranas (RPM)", ["Salida de líquido amniótico antes del inicio del trabajo de parto.",
                                            "La conducta depende de la edad gestacional y de si hay infección o sufrimiento fetal."]),
  ("Gestante de 32 semanas", ["Pérdida de líquido en regular cantidad.", "Test del helecho positivo: confirma la RPM."]),
  ["24 a 33 semanas 6 días sin infección: conducta expectante con antibióticos (ampicilina + azitromicina) y corticoides.",
   "Sulfato de magnesio para neuroprotección si es menor de 32 semanas; parto a las 34 semanas o antes si hay corioamnionitis.",
   "No hacer tacto vaginal: aumenta la infección; examen con espéculo estéril."],
  ACOG + " Practice Bulletin n.º 217, Prelabor rupture of membranes (2020); " + MINSA + ", guía de RPM; " + WILLIAMS + ".",
  op=("¿Adecuada a las 32 semanas?", ["No: no hay indicación de terminar ya", "No: se busca prolongar la gestación",
                                      "No: antes de las 34 semanas se espera", "Sí: con corticoides y vigilancia",
                                      "No: requiere hospitalización"]),
  arbol=Q("RPM confirmada: ¿infección, sufrimiento fetal o trabajo de parto?", [
      L("Sí", "Terminar la gestación", ["Antibióticos y vía según obstetricia"]),
      Q("¿Edad gestacional?", [
          L("24-33 sem 6 d (32 sem: este caso)", "EXPECTANTE HOSPITALIZADA", ["Ampicilina + azitromicina 7 días",
                                                                              "Betametasona; vigilar corioamnionitis"], path=True),
          L("≥ 34 semanas", "Inducción del parto", ["Profilaxis para estreptococo B si corresponde"])], edge="No", path=True)], path=True),
  banda=B("Test del helecho positivo (foto real)", P("helecho.jpg", 300, 300, [
            ("circulo", 0.5, 0.48, 0.2, "cristales en\nhoja de helecho", 0.5, 0.88)],
          credito="Paul_012" + CC + "CC BY-SA 2.0"),
          [("Cómo se hace", "Se toma líquido del fondo de saco vaginal con espéculo estéril y se deja secar en una lámina."),
           ("Qué se ve", "Las sales del líquido amniótico cristalizan en ramas, como hojas de helecho."),
           ("Qué significa", "Confirma que es líquido amniótico: hay rotura de membranas; la orina o el moco no cristalizan así.")],
          pie="Muestra de otra paciente.", ans=1))

# PED-004 · Enfermedad de membrana hialina · TARJETAS + Rx real
S("tarjetas", "PED-004", "Prematuro con dificultad respiratoria y pulmones en vidrio esmerilado: enfermedad de membrana hialina",
  "Neonatología · dificultad respiratoria del recién nacido",
  ("Enfermedad de membrana hialina (SDR)", ["Falta de surfactante en el prematuro: los alvéolos colapsan al espirar.",
                                            "Dificultad respiratoria progresiva desde las primeras horas."]),
  ("Recién nacido pretérmino", ["Madre sin control prenatal y con preeclampsia.", "Dificultad respiratoria marcada; Rx en vidrio esmerilado."]),
  ["Prevención: corticoides prenatales (betametasona) entre las 24 y 34 semanas si hay riesgo de parto pretérmino.",
   "Tratamiento: CPAP desde la sala de partos y surfactante (técnica poco invasiva) si necesita FiO₂ > 30 %.",
   "Taquipnea transitoria: a término o por cesárea, mejora en 24-72 h y la Rx muestra líquido en las cisuras."],
  "Consenso europeo de síndrome de dificultad respiratoria (Sweet et al., Neonatology 2023); " + NELSON + ".",
  op=("¿Encaja?", ["Sí: prematuro + vidrio esmerilado", "No: a término, cisuras con líquido, mejora rápido",
                   "No: infiltrados, madre con fiebre o RPM", "No: líquido meconial, a término o postérmino",
                   "No: soplo, pulsos saltones; no da vidrio esmerilado"]),
  d=dict(rotulo="Dificultad respiratoria en el recién nacido", ans=0,
         cards=[dict(titulo="Membrana hialina", datos=[("Quién", "Prematuro", True), ("Rx", "Vidrio esmerilado", True),
                                                     ("Causa", "Falta de surfactante", True)], pie="Este caso: CPAP + surfactante."),
                dict(titulo="Taquipnea transitoria", datos=[("Quién", "A término, cesárea", False), ("Rx", "Líquido en cisuras", False),
                                                          ("Curso", "Mejora en 24-72 h", False)], pie="Solo oxígeno."),
                dict(titulo="Aspiración de meconio", datos=[("Quién", "A término o postérmino", False), ("Rx", "Parches y atrapamiento", False),
                                                          ("Líquido", "Meconial", False)], pie="Riesgo de hipertensión pulmonar."),
                dict(titulo="Neumonía connatal", datos=[("Quién", "RPM, fiebre materna", False), ("Rx", "Infiltrados", False),
                                                      ("Labs", "PCR alta", False)], pie="Antibióticos.")]),
  banda=B("Rx real de membrana hialina", P("emh_rx.jpg", 330, 260, [
            ("flechas", [(0.3, 0.6), (0.73, 0.6)], 0.5, 0.93, "vidrio esmerilado en ambos pulmones")],
          credito="Mikael Häggström" + CC + "CC0"),
          [("Pulmones blancos y granulosos", "Opacidad fina y uniforme en ambos lados: alvéolos colapsados sin aire."),
           ("Volumen pulmonar bajo", "Sin surfactante el pulmón no se mantiene abierto al espirar."),
           ("Los tubos que se ven", "Tubo endotraqueal y catéteres: es un prematuro de 29 semanas ya en soporte.")],
          pie="Rx de otro prematuro con el mismo diagnóstico.", ans=0))

# HEM-002 · Anemia ferropénica · MATRIZ + frotis real
S("matriz", "HEM-002", "Hemoglobina baja, VCM bajo y ferritina baja: anemia ferropénica",
  "Anemias · anemias microcíticas",
  ("Anemia ferropénica", ["La anemia más frecuente: se agota el hierro y los glóbulos rojos salen pequeños y pálidos.",
                          "La ferritina baja es el dato que la confirma (refleja las reservas)."]),
  ("Hemograma", ["Hemoglobina baja, microcitosis (VCM bajo).", "Ferritina sérica disminuida."]),
  ["Microcítica + ferritina baja = ferropenia; buscar la causa (sangrado digestivo, menstruación, dieta, parásitos).",
   "Tratamiento: sulfato ferroso oral (en días alternos se absorbe mejor) hasta normalizar la Hb y 3 meses más.",
   "Ferritina normal o alta con microcitosis: anemia de enfermedad crónica, talasemia o sideroblástica."],
  "OMS, uso de la ferritina para evaluar el hierro (2020); BSG, guía de anemia ferropénica en adultos (2021); " + MINSA + ".",
  op=("¿Encaja?", ["Sí: microcítica + ferritina baja", "No: VCM alto", "No: VCM normal, reticulocitos altos",
                   "No: drepanocitos, VCM normal", "No: ferritina normal o alta"]),
  d=dict(rotulo="Anemia microcítica: lee la ferritina", eje_x="Ferritina", eje_y="Otros datos",
         cols=["Baja", "Normal o alta"], rows=["Sin inflamación", "Con inflamación crónica", "Hb A2 alta o sideroblastos"], caso=(0, 0),
         cells=[[("FERROPÉNICA", ["Reservas agotadas", "ADE alto"]), ("Talasemia", ["Hb A2 o F alta", "Glóbulos muy pequeños"])],
                [("Ferropenia + inflamación", ["Ferritina < 100 en inflamación"]), ("Enfermedad crónica", ["Hierro bajo, ferritina alta"])],
                [("Rara", ["Revisar el diagnóstico"]), ("Sideroblástica", ["Sideroblastos en anillo", "Plomo, alcohol, isoniacida"])]]),
  banda=B("Frotis real de anemia ferropénica", P("ferropenia.jpg", 330, 249, [
            ("flechas", [(0.27, 0.57), (0.405, 0.43)], 0.25, 0.9, "hematíes pequeños y pálidos"),
            ("flecha", 0.55, 0.52, 0.78, 0.1, "linfocito\n(referencia)")],
          credito="Ed Uthman" + CC + "CC BY 2.0"),
          [("Glóbulos rojos pequeños", "Microcitosis: son más chicos que el núcleo de un linfocito pequeño."),
           ("Centro muy pálido", "Hipocromía: tienen poca hemoglobina; la palidez central ocupa más de un tercio."),
           ("Formas variadas", "Anisocitosis y poiquilocitosis: el ADE sube antes que baje el VCM.")],
          pie="Frotis de otro paciente (VCM 55 fL).", ans=0))

# NEF-002 · Hiperpotasemia · TERMÓMETRO de cambios en el ECG + ECG real
S("termometro", "NEF-002", "Insuficiencia renal oligúrica con ondas T picudas: hiperpotasemia",
  "Trastornos del potasio · hiperpotasemia",
  ("Hiperpotasemia", ["K⁺ > 5,0-5,5 mEq/L; la causa más frecuente es la falla renal (no lo elimina).",
                      "Su peligro es cardiaco: arritmias y paro."]),
  ("Mujer de 70 años", ["Diarreas profusas y oligoanuria; creatinina 3,6 mg/dL.", "ECG: ondas T picudas."]),
  ["Con cambios en el ECG es una emergencia: gluconato de calcio EV primero (protege el corazón en minutos).",
   "Luego meter el potasio a la célula: insulina + glucosa y salbutamol nebulizado; después eliminarlo (diuréticos, quelantes, diálisis).",
   "Aquí la diarrea causó deshidratación y falla renal aguda prerrenal: hidratar."],
  "UK Kidney Association, Treatment of acute hyperkalaemia in adults (2023); KDIGO, potasio (2020); " + HARRISON + ".",
  op=("¿Encaja?", ["No: da QT corto", "No: no da T picudas", "No: da QT largo, torsades", "Sí: falla renal + T picudas",
                   "No: da T planas y onda U"]),
  d=dict(rotulo="El ECG empeora a medida que sube el potasio", caso_nivel=0, ruta_titulo="Qué hacer ya", paso_label="ESTE CASO",
         niveles=[("T picudas", "5,5-6,5", ["Ondas T altas y estrechas"]), ("P aplanada", "6,5-7,5", ["PR largo, P que desaparece"]),
                  ("QRS ancho", "7-8", ["Bloqueos, bradicardia"]), ("Sinusoidal", "> 8", ["Fibrilación ventricular, asistolia"])],
         pasos=[(1, "Gluconato de calcio EV", ["Protege la membrana del corazón"], True),
                (2, "Insulina + glucosa, salbutamol", ["Meten el K⁺ a la célula"], False),
                (3, "Eliminar el potasio", ["Diuréticos, quelantes o diálisis"], False)]),
  escala=dict(nombre="Gravedad de la hiperpotasemia", que="UK Kidney Association 2023: por el nivel de K⁺ y por los cambios en el ECG.",
              grados=[("K⁺ 5,5-5,9", "Leve", ["Sin cambios en el ECG", "Corregir la causa"]),
                      ("K⁺ 6,0-6,4", "Moderada", ["Insulina + glucosa", "Monitoreo cardiaco"]),
                      ("K⁺ ≥ 6,5 o ECG alterado", "Grave", ["Gluconato de calcio EV ya", "Insulina + glucosa, salbutamol", "Valorar diálisis"])],
              caso=2, porque=[("T picudas en el ECG: se trata como grave aunque falte el valor de K⁺", True),
                              ("Falla renal oligúrica: el potasio seguirá subiendo si no se corrige", True)],
              conducta="Monitor, gluconato de calcio EV, insulina + glucosa y salbutamol; hidratar y valorar diálisis."),
  banda=B("ECG real de hiperpotasemia", P("hiperk_ecg.jpg", 400, 231, [
            ("flechas", [(0.255, 0.66), (0.625, 0.64)], 0.45, 0.94, "ondas T altas y picudas")],
          credito="M. J. F. Agbayani y E. Gonzales" + CC + "CC BY 4.0"),
          [("Ondas T en carpa", "Altas, estrechas y simétricas: es el primer signo en el ECG."),
           ("Se ven mejor en V2-V4", "Las derivaciones precordiales muestran las T más altas que el QRS."),
           ("Este trazado: K⁺ 8,2", "Paciente renal con potasio muy alto: riesgo inminente de arritmia.")],
          pie="ECG de otro paciente.", ans=0))

# GIN-004 · Hipertensión gestacional · ÁRBOL + clasificación
S("arbol", "GIN-004", "PA 145/90 a las 38 semanas sin proteinuria ni daño de órganos: hipertensión gestacional",
  "Trastornos hipertensivos del embarazo",
  ("Hipertensión gestacional", ["PA ≥ 140/90 después de las 20 semanas, sin proteinuria ni daño de órganos.",
                                "Hasta la mitad evoluciona a preeclampsia: se vigila."]),
  ("Gestante de 24 años, 38 semanas", ["Contracciones; PA 145/90, sin proteinuria.",
                                       "DHL 376, TGO 23, plaquetas 176 000: laboratorio normal."]),
  ["Hipertensión gestacional a término (≥ 37 semanas): se indica el parto.",
   "Si aparece proteinuria o daño de órganos pasa a preeclampsia; con PA ≥ 160/110, preeclampsia con severidad.",
   "Hipertensión crónica: antes de las 20 semanas o que persiste más de 12 semanas tras el parto."],
  ACOG + " Practice Bulletin n.º 222 (2020); ISSHP (2021); " + MINSA + ", guía de trastornos hipertensivos del embarazo.",
  op=("¿Encaja?", ["No: no hay proteinuria ni daño de órganos", "No: PA < 160/110 y laboratorio normal",
                   "Sí: PA ≥ 140/90 aislada tras las 20 semanas", "No: no convulsionó", "No: no era hipertensa antes"]),
  arbol=Q("PA ≥ 140/90 en gestante: ¿antes de las 20 semanas?", [
      L("Sí", "Hipertensión crónica", ["Vigilar preeclampsia sobreagregada"]),
      Q("¿Proteinuria o daño de órganos?", [
          L("No: laboratorio normal (este caso)", "HIPERTENSIÓN GESTACIONAL", ["A término: terminar la gestación",
                                                                               "Vigilar PA y laboratorio"], path=True),
          L("Sí", "Preeclampsia", ["Buscar criterios de severidad"])], edge="No: 38 semanas", path=True)], path=True),
  escala=HTA_EMB(1, [("PA 145/90 después de las 20 semanas", True), ("Sin proteinuria; plaquetas, TGO y DHL normales", True),
                     ("No es preeclampsia: no hay proteinuria ni daño de órganos", False)],
                 "Hipertensión gestacional a las 38 semanas: terminar la gestación y vigilar la PA."))

# SP-002 · Interculturalidad · RADIAL
S("radial", "SP-002", "Gestante que no habla castellano y teme dar a luz con «extraños»: parto con adecuación intercultural y acompañante",
  "Salud pública · interculturalidad en salud",
  ("Interculturalidad en salud", ["Adaptar la atención a la lengua, costumbres y creencias de la usuaria sin perder la seguridad.",
                                  "Así se reduce el parto domiciliario sin atención calificada."]),
  ("Gestante quechuahablante o de otra lengua", ["No habla ni entiende castellano.", "Rechaza el parto en el establecimiento por miedo a «personas extrañas»."]),
  ["El MINSA promueve el parto vertical con adecuación intercultural: acompañante, idioma, posición y costumbres.",
   "Casas de espera materna: para las que viven lejos, se alojan cerca del establecimiento antes del parto.",
   "Derivar sin resolver el miedo o dejarla sin atención no protege a la madre ni al recién nacido."],
  MINSA + ", norma técnica de atención del parto vertical con adecuación intercultural; " + OMS + ", recomendaciones de cuidados intraparto (2018).",
  op=("¿Resuelve su temor?", ["No: la aleja más de su entorno", "Sí: confianza con su familia y costumbres",
                              "Útil si vive lejos, no resuelve el temor", "No: la partera no reemplaza la atención calificada",
                              "No: riesgo de muerte materna"],
      {1: "Parto humanizado con acompañante"}),
  d=dict(rotulo="Parto con adecuación intercultural", centro="PARTO HUMANIZADO", centro_sub="con acompañante", ans=0,
         items=[("ACOMPAÑANTE", ["Esposo, madre o partera a su lado"]), ("IDIOMA", ["Personal o intérprete en su lengua"]),
                ("POSICIÓN", ["Vertical si ella lo elige"]), ("COSTUMBRES", ["Abrigo, mates, entrega de la placenta"]),
                ("SEGURIDAD", ["Monitoreo y personal calificado"])],
         ruta=["Escuchar su temor", "Ofrecer acompañante e idioma", "Parto en el establecimiento", "Madre y bebé seguros"]))

# GIN-005 · Preeclampsia con severidad · TÉRMÓMETRO + clasificación
S("termometro", "GIN-005", "Gestante de 35 semanas con PA 150/98, transaminasas altas y creatinina 1,3: preeclampsia con severidad",
  "Trastornos hipertensivos del embarazo",
  ("Preeclampsia con criterios de severidad", ["Hipertensión tras las 20 semanas con daño de órganos, aunque no haya proteinuria.",
                                               "Basta un criterio de severidad (ACOG 2020)."]),
  ("Gestante de 35 semanas, asintomática", ["Cesárea previa; PA 150/98; proteinuria negativa.",
                                            "Plaquetas 140 000; TGO y TGP 60; DHL 600; creatinina 1,3 mg/dL."]),
  ["Creatinina > 1,1 mg/dL es criterio de severidad: preeclampsia con severidad aunque la PA sea < 160/110.",
   "Conducta: sulfato de magnesio, antihipertensivo si PA ≥ 160/110 y terminar la gestación (≥ 34 semanas).",
   "HELLP completo exige plaquetas < 100 000, DHL ≥ 600 y transaminasas altas: aquí las plaquetas aún no bajan."],
  ACOG + " Practice Bulletin n.º 222 (2020); ISSHP (2021); " + MINSA + ".",
  op=("¿Encaja?", ["No: hay daño de órganos", "No: la creatinina es criterio de severidad", "No: empezó después de las 20 semanas",
                   "Sí: creatinina 1,3 y transaminasas altas", "No: plaquetas > 100 000"]),
  d=dict(rotulo="Del aumento de la PA al daño de órganos", caso_nivel=2, ruta_titulo="Qué hacer", paso_label="ESTE CASO",
         niveles=[("Gestacional", "PA ≥ 140/90", ["Sin proteinuria ni daño"]),
                  ("Preeclampsia", "+ proteinuria o daño", ["Sin severidad"]),
                  ("Con severidad", "1 criterio basta", ["Creatinina > 1,1 (este caso)"]),
                  ("Eclampsia", "o HELLP", ["Convulsión; plaquetas < 100 000"])],
         pasos=[(1, "Sulfato de magnesio", ["Previene la eclampsia"], True),
                (2, "Controlar la PA", ["Labetalol o nifedipino si ≥ 160/110"], False),
                (3, "Terminar la gestación", ["35 semanas: parto"], False)]),
  escala=HTA_EMB(3, [("PA 150/98 después de las 20 semanas, sin proteinuria", True),
                     ("Creatinina 1,3 mg/dL (> 1,1): criterio de severidad", True),
                     ("No es HELLP completo: plaquetas 140 000 (> 100 000)", False)],
                 "Sulfato de magnesio, control de la PA y terminar la gestación a las 35 semanas."))

# NRL-003 · Hematoma epidural de fosa posterior · TARJETAS
S("tarjetas", "NRL-003", "Hematoma epidural de fosa posterior: cirugía inmediata",
  "Traumatismo craneoencefálico · hematoma epidural",
  ("Hematoma epidural", ["Sangre entre el hueso y la duramadre, casi siempre arterial (arteria meníngea media) tras fractura.",
                         "En la fosa posterior hay poco espacio: comprime pronto el tronco y el cuarto ventrículo."]),
  ("Pregunta de concepto", ["¿Qué hematomas epidurales se operan de inmediato?"]),
  ["Indicación general (Brain Trauma Foundation): volumen > 30 cm³ sin importar el Glasgow, o anisocoria con Glasgow < 9.",
   "En la fosa posterior se operan antes: aun pequeños pueden comprimir el tronco y causar hidrocefalia.",
   "Se puede observar uno < 30 cm³, < 15 mm de grosor, desplazamiento < 5 mm, Glasgow > 8 y sin focalidad."],
  "Brain Trauma Foundation, Surgical management of traumatic brain injury; " + ATLS + ".",
  op=("¿Urgente siempre?", ["No: depende del volumen y la clínica", "No: depende del volumen y la clínica",
                            "No: depende del volumen y la clínica", "Sí: comprime el tronco", "No: muchos requieren cirugía urgente"],
      {4: "Ninguno requiere cirugía urgente"}),
  d=dict(rotulo="¿Dónde está el hematoma epidural?", ans=0,
         cards=[dict(titulo="Fosa posterior", datos=[("Espacio", "Muy poco", True), ("Riesgo", "Compresión del tronco", True),
                                                   ("Conducta", "Cirugía inmediata", True)], pie="Lo que pregunta el caso."),
                dict(titulo="Fosa temporal", datos=[("Arteria", "Meníngea media", False), ("Riesgo", "Herniación del uncus", False),
                                                  ("Conducta", "Según volumen y clínica", False)], pie="La más frecuente."),
                dict(titulo="Fosa parietal", datos=[("Espacio", "Mayor", False), ("Riesgo", "Efecto de masa", False),
                                                  ("Conducta", "> 30 cm³ o déficit: cirugía", False)], pie="Puede observarse si es pequeño."),
                dict(titulo="Piso anterior", datos=[("Origen", "Senos venosos, etmoidal", False), ("Riesgo", "Frontal, más lento", False),
                                                  ("Conducta", "Según volumen y clínica", False)], pie="Vigilar con TC.")]))

# REU-003 · Artritis reumatoide · EMBUDO + criterios ACR/EULAR 2010
S("embudo", "REU-003", "Poliartritis de manos y muñecas con rigidez matutina: el anticuerpo más específico es el anti-CCP",
  "Reumatología · artritis reumatoide",
  ("Artritis reumatoide", ["Poliartritis simétrica de pequeñas articulaciones con rigidez matutina mayor de 1 hora.",
                           "Los anti-CCP tienen especificidad cercana al 95 % y predicen erosiones."]),
  ("Mujer de 40 años", ["2 meses de dolor en hombros y muñecas; luego manos con rigidez matutina.",
                        "Sinovitis de pequeñas articulaciones."]),
  ["Anti-CCP: el más específico; factor reumatoide: más sensible pero menos específico.",
   "Clasificar con ACR/EULAR 2010 (≥ 6 de 10 puntos); iniciar metotrexato pronto (ventana de oportunidad).",
   "ANA y anti-DNA son para lupus; la VSG solo mide inflamación."],
  "ACR/EULAR 2010, criterios de clasificación de la AR; EULAR, recomendaciones de manejo de la AR (2022); " + HARRISON + ".",
  op=("Especificidad para AR", ["Baja: positivos en muchas enfermedades", "Moderada: 70-80 %", "La más alta: ~95 %",
                                "Es de lupus", "Inespecífica: solo inflamación"]),
  d=dict(rotulo="¿Qué examen confirma la artritis reumatoide?", inicio="Poliartritis de manos con rigidez matutina",
         candidatos=["Velocidad de sedimentación", "Anticuerpos antinucleares", "Anti-DNA", "Factor reumatoide", "Anti-CCP"],
         pasos=[("¿Solo mide inflamación o es propio del lupus?", ["Velocidad de sedimentación", "Anticuerpos antinucleares", "Anti-DNA"]),
                ("¿Sale positivo también en sanos, hepatitis C o Sjögren?", ["Factor reumatoide"])],
         final=("ANTI-CCP", ["El más específico para AR"]),
         nota="El FR es más sensible; el anti-CCP, más específico."),
  escala=dict(nombre="Criterios ACR/EULAR 2010 de la AR", modo="puntaje",
              que="Se clasifica como AR con 6 o más de 10 puntos en un paciente con al menos una articulación con sinovitis.",
              items=[("A", "Articulaciones afectadas (0 a 5)", "Hombros, muñecas y manos: pequeñas articulaciones (2-3 puntos según cuántas)", 2),
                     ("B", "Serología: FR o anti-CCP (0 a 3)", "Pendiente: es lo que pregunta el caso", None),
                     ("C", "Reactantes: PCR o VSG altas (0 a 1)", "No se informan", None),
                     ("D", "Duración ≥ 6 semanas (0 a 1)", "2 meses", 1)],
              total_txt="Total: 3 puntos sin serología",
              rangos=[("< 6 puntos", "No clasifica todavía", "Repetir la evaluación en el tiempo"),
                      ("≥ 6 puntos", "Artritis reumatoide", "Iniciar metotrexato")],
              caso_rango=0,
              porque=[("Un anti-CCP alto suma 3 puntos: llegaría a 6 y se clasifica como AR", True)],
              conducta="Pedir anti-CCP y FR (con PCR y VSG); si clasifica, metotrexato precoz."))

# INF-003 · Mononucleosis infecciosa · TARJETAS + tríada + frotis real
S("tarjetas", "INF-003", "Fiebre, faringitis, adenopatías cervicales posteriores y esplenomegalia: mononucleosis infecciosa",
  "Infecciones virales · virus de Epstein-Barr",
  ("Mononucleosis infecciosa", ["Infección por el virus de Epstein-Barr, típica de adolescentes y adultos jóvenes.",
                                "Tríada: fiebre, faringitis y adenopatías; esplenomegalia en la mitad."]),
  ("Varón de 18 años", ["20 días de malestar y mialgias; luego fiebre de 38,3 °C, faringitis y adenopatías cervicales posteriores.",
                        "Amígdalas grandes, exantema morbiliforme en brazos y esplenomegalia."]),
  ["Confirmar con anticuerpos heterófilos (Paul-Bunnell) y linfocitos atípicos > 10 %; si son negativos, VCA-IgM.",
   "Evitar deportes de contacto 3-4 semanas por riesgo de rotura del bazo.",
   "La amoxicilina o ampicilina provocan exantema en la mayoría: es otra pista diagnóstica."],
  "CDC, About infectious mononucleosis (2024); " + HARRISON + ".",
  op=("¿Encaja?", ["Sí: tríada + esplenomegalia", "No: adenopatías sin faringitis tan marcada", "No: exantema y adenopatías retroauriculares, cuadro corto",
                   "No: sin faringitis aguda; adenopatías indoloras de semanas", "No: no da esplenomegalia ni adenopatías posteriores"]),
  d=dict(rotulo="Fiebre, faringitis y adenopatías: ¿cuál es?", ans=0,
         cards=[dict(titulo="Mononucleosis (EBV)", datos=[("Adenopatías", "Cervicales posteriores", True), ("Bazo", "Grande", True),
                                                        ("Sangre", "Linfocitos atípicos", True)], pie="Este caso."),
                dict(titulo="Faringitis por estreptococo", datos=[("Adenopatías", "Cervicales anteriores", False), ("Bazo", "Normal", False),
                                                                ("Tos", "Ausente", False)], pie="Criterios de Centor."),
                dict(titulo="Toxoplasmosis aguda", datos=[("Adenopatías", "Indoloras", False), ("Faringe", "Poco afectada", False),
                                                        ("Contacto", "Gatos, carne cruda", False)], pie="Serología IgM."),
                dict(titulo="Linfoma", datos=[("Curso", "Semanas a meses", False), ("Síntomas", "Fiebre, sudor, baja de peso", False),
                                            ("Ganglios", "Duros, indoloros", False)], pie="Biopsia.")]),
  triada=TR([("Fiebre", "38,3 °C", True), ("Faringitis", "Amígdalas grandes", True),
             ("Adenopatías cervicales", "Cadena posterior", True)],
            [("Tríada de la mononucleosis", 0, 2)],
            "Tríada completa más esplenomegalia: muy sugestivo de virus de Epstein-Barr."),
  banda=B("Linfocito atípico (foto real)", P("linfo_reactivo.jpg", 280, 267, [
            ("flecha", 0.62, 0.62, 0.8, 0.92, "citoplasma azul\nabundante"),
            ("flecha", 0.86, 0.22, 0.8, 0.06, "glóbulo rojo")],
          credito="SpicyMilkBoy" + CC + "CC BY-SA 4.0"),
          [("Célula grande", "Mide más del doble que un glóbulo rojo: es un linfocito T activado contra el virus."),
           ("Citoplasma azul que «abraza»", "Se adapta a los glóbulos rojos vecinos (célula de Downey)."),
           ("Más del 10 %", "Junto con los anticuerpos heterófilos confirman la mononucleosis.")],
          pie="Frotis de otro paciente.", ans=1))

# PED-005 · Rubéola · TARJETAS + exantema real
S("tarjetas", "PED-005", "Lactante con fiebre, adenopatías retroauriculares dolorosas y exantema que baja de la cara al tronco: rubéola",
  "Enfermedades exantemáticas de la infancia",
  ("Rubéola", ["Virus de la rubéola (togavirus): cuadro leve con exantema que va de la cara al tronco en 1-3 días.",
               "Adenopatías retroauriculares y suboccipitales dolorosas (signo de Theodor)."]),
  ("Lactante de 10 meses", ["3 días de fiebre y anorexia.", "Adenopatías suboccipitales y retroauriculares; exantema macular de la cara al tronco."]),
  ["Es de notificación obligatoria: tomar IgM y muestra para PCR (vigilancia de sarampión y rubéola).",
   "El riesgo grave es la rubéola congénita: cataratas, sordera y cardiopatía (ductus).",
   "Prevención: vacuna SPR a los 12 y 18 meses (esquema MINSA)."],
  MINSA + ", esquema nacional de vacunación (2024); OPS, eliminación del sarampión y la rubéola (2024); " + NELSON + ".",
  op=("¿Encaja?", ["No: el exantema aparece cuando cae la fiebre alta", "No: no es un diagnóstico; no da adenopatías",
                   "No: vesículas en distintos estadios", "Sí: adenopatías retroauriculares + exantema de cara a tronco",
                   "No: tos, conjuntivitis, Koplik"]),
  d=dict(rotulo="Exantemas de la infancia", ans=0,
         cards=[dict(titulo="Rubéola", datos=[("Ganglios", "Retroauriculares", True), ("Exantema", "Cara → tronco, rosado", True),
                                            ("Fiebre", "Leve", True)], pie="Este caso."),
                dict(titulo="Sarampión", datos=[("Pródromo", "Tos, coriza, conjuntivitis", False), ("Boca", "Manchas de Koplik", False),
                                              ("Fiebre", "Alta", False)], pie="Más grave."),
                dict(titulo="Exantema súbito", datos=[("Edad", "6-24 meses", False), ("Fiebre", "Alta 3 días", False),
                                                    ("Exantema", "Al caer la fiebre", False)], pie="Herpes 6."),
                dict(titulo="Varicela", datos=[("Lesión", "Vesículas", False), ("Estadios", "Varios a la vez", False),
                                             ("Prurito", "Intenso", False)], pie="Cielo estrellado.")]),
  banda=B("Exantema de rubéola (foto real)", P("rubeola.jpg", 260, 271, [
            ("circulo", 0.42, 0.32, 0.16, "máculas rosadas\nfinas y separadas", 0.42, 0.72)],
          credito="CDC" + CC + "dominio público"),
          [("Máculas finas rosadas", "Menos intensas que las del sarampión y no tienden a juntarse."),
           ("Avanza rápido", "Empieza en la cara y en 24 horas llega al tronco; se va en unos 3 días."),
           ("Buscar los ganglios", "Retroauriculares y suboccipitales dolorosos: dato que la diferencia.")],
          pie="Espalda de otro niño con rubéola.", ans=0))

# END-002 · Hipotiroidismo subclínico · MATRIZ
S("matriz", "END-002", "TSH alta con T4 libre normal: hipotiroidismo subclínico",
  "Trastornos tiroideos · interpretación de la función tiroidea",
  ("Hipotiroidismo subclínico", ["TSH elevada con T4 libre normal: la hipófisis «empuja» a una tiroides que empieza a fallar.",
                                 "Causa más frecuente: tiroiditis de Hashimoto (anti-TPO positivos)."]),
  ("Mujer de 58 años, diabética", ["Malestar leve y somnolencia; delgada y algo pálida.", "TSH aumentada con T4 libre normal."]),
  ["Repetir TSH en 2-3 meses antes de etiquetar (puede ser transitoria); medir anti-TPO.",
   "Tratar con levotiroxina si TSH ≥ 10 mUI/L; entre 4,5 y 10, según síntomas, edad, anti-TPO y embarazo.",
   "Eutiroideo enfermo: enfermedad grave aguda con T3 baja y TSH normal o baja."],
  "ETA, guía de hipotiroidismo subclínico (2013); ATA, guía de hipotiroidismo (2014); " + HARRISON + ".",
  op=("¿Encaja?", ["Sí: TSH alta + T4L normal", "No: TSH baja + T4L alta", "No: TSH baja + T4L normal",
                   "No: requiere T4L baja", "No: enfermedad grave aguda, TSH normal o baja"]),
  d=dict(rotulo="Lee la TSH y la T4 libre juntas", eje_x="T4 libre", eje_y="TSH",
         cols=["Normal", "Alterada"], rows=["Alta", "Baja", "Normal"], caso=(0, 0),
         cells=[[("HIPOTIROIDISMO SUBCLÍNICO", ["Repetir y medir anti-TPO"]), ("Hipotiroidismo primario", ["T4L baja: levotiroxina"])],
                [("Hipertiroidismo subclínico", ["Riesgo de FA y osteoporosis"]), ("Hipertiroidismo", ["T4L alta: Graves, nódulo"])],
                [("Eutiroideo", ["Sin enfermedad tiroidea"]), ("Eutiroideo enfermo o central", ["T4L baja con TSH normal"])]]))

# GIN-006 · Mastitis puerperal · ÁRBOL
S("arbol", "GIN-006", "Puérpera con fiebre y zona roja, dura y caliente en la mama: mastitis, dicloxacilina sin suspender la lactancia",
  "Complicaciones del puerperio · mastitis",
  ("Mastitis puerperal", ["Inflamación de la mama que lacta; si hay fiebre y signos sistémicos, infección por S. aureus.",
                          "Lo más frecuente entre la 2.ª y 6.ª semana posparto."]),
  ("Puérpera de 25 días", ["Dolor en la mama izquierda y fiebre de 38,7 °C.", "Zona de 6 cm endurecida, roja y caliente."]),
  ["Antibiótico contra S. aureus 10-14 días: dicloxacilina o cefalexina; clindamicina si hay alergia o SARM.",
   "Seguir dando de lactar (o extraer la leche): vaciar la mama ayuda; no masajear fuerte; frío y AINE.",
   "Si hay masa fluctuante o no mejora en 48-72 h: ecografía para descartar absceso (drenaje)."],
  "Academy of Breastfeeding Medicine, protocolo n.º 36: espectro de la mastitis (2022); " + OMS + "; " + WILLIAMS + ".",
  op=("¿Adecuado?", ["No: no cubre bien S. aureus de piel", "Sí: cubre S. aureus", "No: no es de primera línea",
                     "No: contraindicada en la lactancia", "No: vaciar la mama ayuda a curar"]),
  arbol=Q("Mama roja y dolorosa en la lactancia: ¿fiebre o malestar general?", [
      Q("¿Masa fluctuante en la ecografía?", [
          L("No (este caso)", "MASTITIS INFECCIOSA", ["Dicloxacilina o cefalexina 10-14 días",
                                                      "Seguir la lactancia, AINE, frío"], path=True),
          L("Sí", "Absceso mamario", ["Drenaje (aspiración) + antibiótico"])], edge="Sí: 38,7 °C", path=True),
      L("No", "Mastitis inflamatoria", ["Frío, AINE, lactancia a demanda", "Sin antibiótico al inicio"])], path=True))

# GAS-002 · Diarrea disentérica del adulto · EMBUDO
S("embudo", "GAS-002", "Diarrea con sangre, fiebre y leucocitos en heces tras comer en la calle: antibióticos",
  "Enfermedad diarreica aguda · diarrea invasiva",
  ("Diarrea disentérica (invasiva)", ["Bacterias que invaden el colon: sangre, moco, fiebre y leucocitos en heces.",
                                      "Shigella y Campylobacter son las más frecuentes; también Salmonella y E. coli enteroinvasiva."]),
  ("Varón de 27 años", ["3 días de diarrea con sangre, fiebre y dolor abdominal tras comer en un ambulante.",
                        "Deshidratado; leucocitos en heces."]),
  ["Primero hidratar (SRO o EV si no tolera); luego antibiótico empírico: azitromicina (o ciprofloxacino según resistencia local).",
   "Tomar coprocultivo antes del antibiótico si es posible.",
   "No dar loperamida en diarrea con sangre o fiebre: retiene el germen (riesgo de megacolon y SHU)."],
  IDSA + ", guía de diarrea infecciosa (2017); " + MINSA + ", guía de enfermedad diarreica aguda; " + OMS + ".",
  op=("¿Indicado?", ["Sí: disentería con fiebre", "No: alivio sintomático", "Solo para la fiebre", "No: no tratan la diarrea",
                     "Contraindicada con sangre o fiebre"]),
  d=dict(rotulo="Diarrea con sangre y fiebre: ¿qué se trata?", inicio="Diarrea disentérica, fiebre, deshidratación",
         candidatos=["Loperamida", "Bloqueadores H2", "Sales de bismuto", "Antipiréticos", "Antibióticos"],
         pasos=[("¿Contraindicado o sin efecto sobre la diarrea?", ["Loperamida", "Bloqueadores H2"]),
                ("¿Solo alivia síntomas sin tratar la invasión?", ["Sales de bismuto", "Antipiréticos"])],
         final=("ANTIBIÓTICOS + HIDRATACIÓN", ["Azitromicina empírica"]),
         nota="Sangre + fiebre + leucocitos: bacteria invasiva."))

# SP-003 · Consejería nutricional · RADIAL
S("radial", "SP-003", "Suegra que prohíbe carne y sangrecita a la gestante: consejería nutricional a la familia",
  "Salud pública · nutrición materna",
  ("Consejería nutricional", ["Diálogo educativo que adapta la alimentación a las costumbres de la familia.",
                              "Se dirige a la gestante y a quien decide en casa (aquí, la suegra)."]),
  ("Gestante de 21 años", ["Vive con la suegra, que no le deja comer carne ni sangrecita.", "Cree que «afectará el parto»."]),
  ["El problema es una creencia: primero se informa y se negocia con la familia (consejería), no solo se suplementa.",
   "La sangrecita y las vísceras son fuentes baratas de hierro hemínico: previenen anemia materna e infantil.",
   "Igual se indica hierro + ácido fólico desde la semana 14 (MINSA), pero no reemplaza la consejería."],
  MINSA + ", directiva de suplementación con hierro y lineamientos de consejería nutricional; " + OMS + ", nutrición en el embarazo (2016, act. 2020).",
  op=("¿Resuelve el problema?", ["Sí: cambia la creencia familiar", "Necesario, pero no cambia la dieta", "No es la prioridad",
                                 "No: el problema es familiar, no del gobierno local", "No es la prioridad en este caso"]),
  d=dict(rotulo="Consejería nutricional a la familia", centro="CONSEJERÍA", centro_sub="gestante + suegra", ans=0,
         items=[("ESCUCHAR", ["Qué creen y por qué"]), ("INFORMAR", ["Hierro de la sangrecita y la carne"]),
                ("NEGOCIAR", ["Acuerdos que la familia acepte"]), ("SUPLEMENTAR", ["Hierro + ácido fólico"]),
                ("SEGUIR", ["Control de Hb en el embarazo"])],
         ruta=["Identificar la creencia", "Consejería con la suegra", "Dieta con hierro", "Gestante sin anemia"]))

# PED-006 · Disentería en lactante: Campylobacter · TARJETAS + plan de hidratación
S("tarjetas", "PED-006", "Lactante de 11 meses con diarrea con moco y sangre y fiebre de 39 °C: Campylobacter",
  "Enfermedad diarreica en pediatría · diarrea disentérica",
  ("Diarrea disentérica en el lactante", ["Moco y sangre con fiebre: bacteria invasiva del colon.",
                                          "En menores de 2 años de países en desarrollo, Campylobacter es la causa más frecuente; Shigella predomina en preescolares."]),
  ("Lactante de 11 meses", ["24 horas de deposiciones semilíquidas con moco y sangre, 4-6 veces al día.",
                            "Somnoliento, deshidratación leve, temperatura 39 °C."]),
  ["Hidratar según el plan de la OMS y continuar la alimentación; zinc por 10-14 días.",
   "Antibiótico en disentería del niño: azitromicina (cubre Campylobacter y Shigella).",
   "Rotavirus y enterovirus dan diarrea acuosa; Vibrio cholerae, acuosa «en agua de arroz» sin fiebre."],
  OMS + ", tratamiento de la diarrea (2005, act.); " + MINSA + ", guía de enfermedad diarreica aguda en niños; " + NELSON + ".",
  op=("¿Encaja?", ["No: diarrea acuosa", "No: acuosa con vómitos", "Sí: disentería en menor de 2 años",
                   "Posible, pero predomina en preescolares", "No: acuosa, sin fiebre ni sangre"]),
  d=dict(rotulo="Diarrea con moco y sangre en el lactante", ans=0,
         cards=[dict(titulo="Campylobacter", datos=[("Edad", "Menor de 2 años", True), ("Heces", "Moco y sangre", True),
                                                  ("Fuente", "Pollo, leche cruda", True)], pie="Este caso."),
                dict(titulo="Shigella", datos=[("Edad", "Preescolar", False), ("Heces", "Moco y sangre", False),
                                             ("Extra", "Convulsiones febriles", False)], pie="Muy contagiosa."),
                dict(titulo="Rotavirus", datos=[("Edad", "6-24 meses", False), ("Heces", "Acuosas", False),
                                              ("Extra", "Vómitos, deshidratación", False)], pie="Prevenible con vacuna."),
                dict(titulo="Vibrio cholerae", datos=[("Heces", "Agua de arroz", False), ("Fiebre", "No", False),
                                                    ("Riesgo", "Deshidratación grave", False)], pie="Brotes.")]),
  escala=dict(nombre="Planes de hidratación de la OMS", que="Se elige por los signos de deshidratación del niño (OMS / AIEPI, MINSA).",
              grados=[("Plan A", "Sin deshidratación", ["Más líquidos y SRO en casa", "Seguir la alimentación", "Zinc"]),
                      ("Plan B", "Algún grado de deshidratación", ["2 o más: inquieto o irritable, ojos hundidos, bebe con avidez, pliegue lento",
                                                                   "SRO 75 mL/kg en 4 horas en el establecimiento"]),
                      ("Plan C", "Deshidratación grave", ["2 o más: letárgico, ojos hundidos, bebe mal, pliegue muy lento",
                                                          "Hidratación EV (100 mL/kg)"])],
              caso=1, porque=[("Deshidratación leve descrita: plan B con SRO en el establecimiento", True),
                              ("Somnoliento: si se suma otro signo grave (bebe mal, pliegue muy lento) pasa a plan C", False)],
              conducta="SRO 75 mL/kg en 4 horas, reevaluar, zinc y azitromicina por la disentería."))
