"""Bloque ENAM 2026 · Cardiología y Neumología."""
from c26 import S, D, P, B, ILU, Q, L, HARRISON, MINSA
from engine7 import _img_draw
import ilu7 as I

O = I.ORANGE
EC = "CARDIOLOGÍA ENAM"
EN = "NEUMOLOGÍA ENAM"
AHA = "AHA, guías de reanimación (2020-2025)"
ESC = "ESC"

# CAR-075 · Trombosis venosa profunda · TARJETAS + franja
_tvp = {"muslo_d": "#fca5a5", "pierna_d": "#f87171", "pie_d": "#fca5a5"}
S("tarjetas", "CAR-075", "pierna-derecha-hinchada-hasta-muslo-dolor-pantorrilla-trombosis-venosa-profunda",
  "Pierna hinchada, roja y dolorosa de inicio súbito hasta el muslo: trombosis venosa profunda",
  "Enfermedad vascular · pierna hinchada", EC,
  ("Trombosis venosa profunda (TVP)", ["Un coágulo en las venas profundas: pierna hinchada, dolorosa y caliente, de un solo lado.",
                                       "La proximal (poplítea hacia arriba) es la que más embolias da."]),
  ("Mujer de 54 años", ["Dolor intenso y súbito en la pierna derecha hace 24 h; pesadez bilateral de meses.",
                        "Edema y eritema hasta el tercio proximal del muslo, dolor en la pantorrilla, calor local."]),
  ["Edema unilateral súbito + dolor a la palpación profunda + calor = TVP (proximal si llega al muslo).",
   "Confirmar con ecografía Doppler de compresión; puntaje de Wells y dímero D según la probabilidad.",
   "Tratar con anticoagulación; la insuficiencia venosa de fondo es un factor que predispone."],
  "ACCP/CHEST (2021); ESC (2019); " + HARRISON + ".",
  d=dict(rotulo="Cuatro diagnósticos posibles", ans=0,
         cards=[dict(titulo="Trombosis venosa profunda", datos=[("Inicio", "Súbito", True), ("Lado", "Uno, hasta el muslo", True),
                                                                ("Clave", "Dolor en pantorrilla, calor", True)], pie="Confirmar con Doppler."),
                dict(titulo="Insuficiencia arterial", datos=[("Pierna", "Fría y pálida", False), ("Pulsos", "Ausentes", False),
                                                             ("Edema", "No", False)], pie="Isquemia, no edema."),
                dict(titulo="Dermatopatía hipostática", datos=[("Curso", "Crónico", False), ("Piel", "Ocre, endurecida", False),
                                                               ("Dolor agudo", "No", False)], pie="Sin cambios tróficos aquí."),
                dict(titulo="Insuficiencia venosa", datos=[("Curso", "Meses o años", False), ("Lado", "Ambas piernas", False),
                                                           ("Síntoma", "Pesadez, várices", False)], pie="Es el fondo, no el cuadro agudo.")]),
  banda=B("La pierna del caso", D(lambda s, x, y: I.cuerpo(s, x + 40, y, _tvp, marcas=[(1, 96, 320), (2, 99, 392)], sc=0.7), 250, 312),
          ["Pierna derecha roja e hinchada hasta el muslo (en el dibujo, a la izquierda).", "Dolor a la palpación profunda de la pantorrilla.",
           "La otra pierna no se hinchó: el cuadro es de un solo lado."], ans=0),
  tabla=("Opciones de la pregunta", [("Trombosis venosa profunda", True), ("Insuficiencia arterial", False), ("Dermatopatía hipostática", False),
                                     ("Insuficiencia venosa", False)],
         [("¿Encaja?", ["Sí", "No: sería fría y sin pulsos", "No: es crónica", "No: es crónica y bilateral"])]))

# CAR-076 · IC con FEVI preservada · EMBUDO + franja
S("embudo", "CAR-076", "mujer-hipertensa-ortopnea-crepitantes-probnp-alto-ic-fevi-preservada",
  "Mujer mayor hipertensa con ortopnea, crepitantes y proBNP alto: insuficiencia cardiaca con FEVI preservada",
  "Insuficiencia cardiaca · tipos", EC,
  ("IC con fracción de eyección preservada", ["El VI bombea bien (FEVI ≥ 50 %) pero es rígido y se llena mal.",
                                               "Típica de mujeres mayores con hipertensión de años, obesidad o diabetes."]),
  ("Mujer de 67 años con HTA de larga data", ["2 meses de disnea progresiva hasta ortopnea.",
                                              "PA 150/90, crepitantes bibasales, edema maleolar; proBNP alto."]),
  ["Congestión (ortopnea, crepitantes, edema) + proBNP alto + HTA crónica = insuficiencia cardiaca, probablemente con FEVI preservada.",
   "Se confirma con ecocardiograma: FEVI ≥ 50 % y signos de disfunción diastólica o hipertrofia.",
   "Tratamiento: diurético para la congestión, control de la PA e iSGLT2."],
  "ESC, insuficiencia cardiaca (2021, actualización 2023); AHA/ACC/HFSA (2022).",
  d=dict(rotulo="De la disnea a la causa", inicio="Mujer hipertensa con disnea, ortopnea y proBNP alto",
         candidatos=["Embolia pulmonar", "EPOC descompensada", "Taponamiento", "IC con FEVI preservada"],
         pasos=[("¿Inicio súbito con dolor torácico o síncope?", ["Embolia pulmonar"]),
                ("¿Fumadora con sibilancias y espiración prolongada?", ["EPOC descompensada"]),
                ("¿Hipotensión, yugulares llenas y ruidos apagados?", ["Taponamiento"])],
         final=("IC con FEVI preservada", ["Congestión progresiva en una hipertensa de años"]),
         nota="La disnea fue progresiva en 2 meses y el proBNP es alto: el corazón es la causa."),
  banda=B("Corazón del caso (esquema)", D(lambda s, x, y: I.corazon4(s, x + 20, y, "hvi", sc=0.95), 290, 240),
          ["Años de hipertensión engrosan la pared del VI.", "El VI rígido se llena mal: la presión sube y congestiona los pulmones.",
           "Bombea bien: la FEVI se mantiene ≥ 50 % (se confirma con eco)."]),
  tabla=("Opciones de la pregunta", [("Embolia pulmonar aguda", False), ("EPOC descompensada", False), ("IC con FEVI preservada", True),
                                     ("Taponamiento cardiaco", False)],
         [("¿Encaja?", ["No: sería súbita", "No: sin tabaco ni sibilancias", "Sí", "No: sin hipotensión ni ruidos apagados"])]))

# CAR-077 · FV refractaria · ESCALERA
S("escalera", "CAR-077", "fibrilacion-ventricular-tras-tercera-descarga-amiodarona-300-mg",
  "Fibrilación ventricular que sigue tras la tercera descarga: amiodarona 300 mg EV",
  "Reanimación cardiopulmonar · ritmos desfibrilables", EC,
  ("FV o TV sin pulso", ["Ritmos desfibrilables: descarga, RCP de alta calidad y adrenalina cada 3-5 minutos.",
                         "Si persisten tras la 3.ª descarga se agrega un antiarrítmico."]),
  ("Varón de 50 años en paro por FV", ["Compresiones de calidad; adrenalina 1 mg tras la 2.ª descarga.",
                                       "Tras la 3.ª descarga sigue en FV."]),
  ["FV refractaria tras la 3.ª descarga: amiodarona 300 mg EV en bolo; 2.ª dosis de 150 mg si persiste.",
   "La lidocaína (1-1,5 mg/kg) es alternativa; la dosis de la opción (0,5-0,75 mg/kg) es la de repetición.",
   "Atropina y calcio no se usan en la FV (calcio solo si hay hiperpotasemia o intoxicación)."],
  AHA + "; ERC (2021).",
  d=dict(rotulo="El ritmo y la secuencia del paro",
         img=dict(titulo="Fibrilación ventricular (esquema de ECG)", IH=104,
                  ilu=lambda s, x, y: I.ecg_tira(s, x + 58, y + 2, "fv", W=760),
                  pie="Ondas caóticas, sin QRS: el corazón tiembla y no bombea. Es un ritmo desfibrilable."),
         check_titulo="¿Dónde está el paciente?",
         check=[("Sigue en FV tras 3 descargas", True), ("Ya recibió adrenalina 1 mg", True), ("RCP de alta calidad en curso", True)],
         veredicto="FV REFRACTARIA: antiarrítmico ahora",
         peldanos=[("RCP y 1.ª descarga", ["Desfibrilar apenas se pueda."]),
                   ("2.ª descarga", ["Acceso EV; adrenalina 1 mg."]),
                   ("3.ª descarga", ["Si sigue en FV: antiarrítmico."]),
                   ("Amiodarona 300 mg", ["Luego 150 mg si persiste."])],
         ans=3, tag="ESTE CASO", salto="Tras la 3.ª descarga",
         leyenda_estable="Cada 2 minutos: analizar ritmo, descargar si es FV y seguir comprimiendo.",
         leyenda_inestable="Este caso: FV tras la 3.ª descarga → amiodarona 300 mg EV en bolo."),
  tabla=("Opciones de la pregunta", [("Gluconato de calcio", False), ("Lidocaína 0,5-0,75 mg/kg", False), ("Atropina", False),
                                     ("Amiodarona 300 mg", True)],
         [("Comentario", ["Solo si hay hiperpotasemia", "Alternativa; esa es la dosis de repetición", "No se usa en paro", "Elección"])]))

# CAR-078 · Insuficiencia aórtica crónica · MAPA DE SIGNOS
S("mapa_signos", "CAR-078", "pa-150-50-pulsos-saltones-musset-quincke-insuficiencia-aortica-reumatica",
  "PA 150/50, pulsos saltones, Musset y Quincke con soplo diastólico: insuficiencia aórtica crónica",
  "Valvulopatías · insuficiencia aórtica", EC,
  ("Insuficiencia aórtica crónica", ["La válvula aórtica no cierra: en cada diástole la sangre vuelve al VI.",
                                     "El VI se dilata y bombea más volumen: pulsos amplios y presión diferencial grande."]),
  ("Agricultor de 52 años", ["Fiebre reumática en la adolescencia; disnea de esfuerzo y ortopnea.",
                             "PA 150/50, pulsos amplios, balanceo de la cabeza, pulso capilar; soplo diastólico en decrescendo."]),
  ["Presión diferencial amplia + signos periféricos (Corrigan, Musset, Quincke) + soplo diastólico aspirativo = insuficiencia aórtica.",
   "Se oye mejor en el borde esternal izquierdo con el paciente inclinado hacia adelante y en espiración.",
   "Con síntomas o VI dilatado: reemplazo valvular."],
  "AHA/ACC, valvulopatías (2020); " + HARRISON + ".",
  d=dict(rotulo="Los signos del paciente", PH=500, tag="ESTE CASO",
         ilu_titulo="El paciente del caso",
         ilu=lambda s, x, y: I.cuerpo(s, x + 39, y + 4, {"torax": "#fde2e2"},
                                      marcas=[(1, 150, 22), (2, 136, 74), (3, 37, 252), (4, 134, 112), (5, 62, 140)], sc=0.9),
         ilu_pie="1 cabeza que se balancea, 2 pulso carotídeo saltón, 3 uñas, 4 foco del soplo, 5 PA 150/50.",
         signos=[dict(tit="Signo de Musset", lines=["La cabeza se balancea con cada latido."]),
                 dict(tit="Pulso de Corrigan", lines=["Pulso amplio que sube y cae rápido."]),
                 dict(tit="Signo de Quincke", lines=["Pulso capilar visible en el lecho de la uña."]),
                 dict(tit="Soplo diastólico en decrescendo", lines=["Borde esternal izquierdo, inclinado hacia adelante."]),
                 dict(tit="Presión diferencial amplia", lines=["150/50: diferencia de 100 mmHg."]),
                 dict(tit="Causa: insuficiencia aórtica reumática", on=True, lines=["Antecedente de fiebre reumática."])]),
  tabla=("Opciones de la pregunta", [("Miocardiopatía dilatada", False), ("Estenosis aórtica", False), ("Insuficiencia aórtica", True),
                                     ("Insuficiencia mitral", False)],
         [("Clave", ["Sin soplo diastólico", "Soplo sistólico, pulso débil", "Diastólico + pulsos saltones", "Soplo sistólico en ápex"])]))

# CAR-080 · Edema agudo de pulmón · ÁRBOL + franja
S("arbol", "CAR-080", "mujer-80-anos-edema-agudo-pulmon-hipertensa-furosemida-ev",
  "Edema agudo de pulmón con sobrecarga de volumen: furosemida EV",
  "Insuficiencia cardiaca aguda · edema pulmonar", EC,
  ("Edema agudo de pulmón cardiogénico", ["El líquido pasa de los capilares al alveolo: disnea, ortopnea, crepitantes, hipoxemia.",
                                          "Primero sentar y dar oxígeno; luego sacar líquido y bajar la precarga."]),
  ("Mujer de 80 años en urgencias", ["Disnea en reposo, ortopnea y edema generalizado.",
                                     "PA 180/100, FC 110, SatO₂ 88 %, crepitantes; proBNP 1200; Rx: edema alveolar."]),
  ["Congestión con sobrecarga de volumen (edema generalizado): furosemida EV 40-80 mg en bolo como primer fármaco.",
   "Con PA alta se suma nitroglicerina como complemento; no si la PAS es < 90-110.",
   "La morfina ya no es de rutina; el salbutamol no trata el edema pulmonar."],
  "ESC, insuficiencia cardiaca aguda (2021, actualización 2023); " + HARRISON + ".",
  arbol=Q("¿PAS ≥ 90 mmHg (no está en shock)?", [
      L("No", "Shock cardiogénico", ["Inotrópico o vasopresor", "Diurético cuando suba la PA"]),
      Q("¿Hay sobrecarga de volumen (edemas, peso)?", [
          L("No", "Vasodilatador", ["Nitroglicerina si predomina la HTA"]),
          L("Sí", "FUROSEMIDA EV", ["40-80 mg en bolo", "+ nitroglicerina si la PA sigue alta"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("Rx de tórax (esquema)", D(lambda s, x, y: I.torax_rx(s, x, y, "edema", sc=0.95), 285, 266),
          ["Opacidades alveolares en ambos pulmones, en «alas de mariposa».", "Corazón grande.",
           "La furosemida saca el líquido y alivia la congestión."], ans=2),
  tabla=("Opciones de la pregunta", [("Nitroglicerina EV", False), ("Furosemida EV", True), ("Salbutamol", False), ("Morfina EV", False)],
         [("Comentario", ["Complemento si la PA es alta", "Primera elección", "No trata el edema", "Ya no es de rutina"])]))

# CAR-081 · TEP de alto riesgo · ÁRBOL CON IMAGEN
S("arbol_imagen", "CAR-081", "tep-alto-riesgo-hipotension-vd-dilatado-trombolisis-sistemica",
  "Embolia pulmonar con hipotensión y VD dilatado: trombólisis sistémica",
  "Tromboembolismo pulmonar · alto riesgo", EC,
  ("Tromboembolismo pulmonar de alto riesgo", ["El coágulo obstruye la arteria pulmonar: el VD se dilata y falla.",
                                               "Con hipotensión o shock hay que disolver el coágulo ya."]),
  ("Agricultor de 70 años, obeso, viaje largo", ["Disnea súbita, dolor torácico y síncope; PA 80/50, FC 125, SatO₂ 82 %.",
                                                 "ECG: taquicardia y eje a la derecha; eco: VD dilatado. Sin sangrado ni hemorragia cerebral."]),
  ["TEP con hipotensión persistente pese a fluidos o vasopresor: trombólisis sistémica (alteplasa) y luego anticoagulación.",
   "Inestable: no esperar la angioTC; el eco con VD dilatado basta para decidir.",
   "Si la trombólisis está contraindicada o falla: embolectomía quirúrgica o por catéter."],
  ESC + ", embolia pulmonar (2019); CHEST (2021).",
  d=dict(rotulo="¿Qué tan grave es la embolia?", tag="ESTE CASO",
         pregunta="Sospecha de TEP: ¿hay hipotensión o shock que no cede?",
         ramas=[("No: PA estable", "Anticoagular y estratificar", ["Heparina; troponina y eco para el riesgo intermedio.",
                                                                   "AngioTC para confirmar."]),
                ("Sí: PA 80/50, VD dilatado", "Trombólisis sistémica",
                 ["Si no hay contraindicación y la PA no se recupera con fluidos o vasopresor.",
                  "Luego anticoagular y trasladar a mayor complejidad."])],
         ilu=lambda s, x, y: I.corazon4(s, x, y, "vd_dilatado"), IW=260, IH=250,
         ilu_pie="Eco del caso (esquema): el VD dilatado empuja el tabique y aplasta al VI.",
         luego_titulo="Qué más",
         luego=[("Trombólisis", ["Alteplasa 100 mg en 2 horas."], True),
                ("Si no se puede", ["Embolectomía quirúrgica o por catéter."], False),
                ("No esperar la angioTC", ["El paciente inestable no se traslada a otro centro antes."], False)]),
  tabla=("Opciones de la pregunta", [("Heparina y derivar a embolectomía", False), ("Trombólisis si no responde a fluidos/vasopresor", True),
                                     ("Derivar para angioTC", False), ("Esperar la angioTC", False)],
         [("Problema", ["Omite la trombólisis disponible", "Ninguno", "Traslado de un inestable", "Retrasa el tratamiento"])]))

# CAR-082 · LDL 195 · TERMÓMETRO + franja
S("termometro", "CAR-082", "ldl-195-antecedente-familiar-infarto-estatina-alta-intensidad",
  "LDL de 195 con historia familiar de infarto precoz: estatina de alta intensidad",
  "Dislipidemias · hipercolesterolemia", EC,
  ("Colesterol LDL muy alto", ["Con LDL ≥ 190 mg/dL se trata con estatina sin calcular el riesgo.",
                               "Pensar en hipercolesterolemia familiar si hay infarto precoz en la familia."]),
  ("Mujer de 55 años en un tamizaje", ["Sin HTA ni diabetes; IMC 29, sedentaria.",
                                       "LDL 195, HDL 28, TG 140; madre con colesterol muy alto e infarto a los 48 años."]),
  ["LDL ≥ 190 mg/dL: estatina de alta intensidad desde el inicio + cambios de estilo de vida.",
   "Infarto materno a los 48 años: sospechar hipercolesterolemia familiar y estudiar a la familia.",
   "Los fibratos bajan triglicéridos, no el LDL; los suplementos no reemplazan a la estatina."],
  "AHA/ACC, colesterol (2018); ESC/EAS, dislipidemias (2019, 2025).",
  d=dict(rotulo="Nivel de LDL y conducta",
         niveles=[("LDL < 100", "Deseable", ["Estilo de vida"]),
                  ("LDL 100-159", "Límite alto", ["Según riesgo calculado"]),
                  ("LDL 160-189", "Alto", ["Calcular riesgo; estatina frecuente"]),
                  ("LDL ≥ 190", "Muy alto", ["Estatina alta intensidad sin calcular riesgo"])],
         caso_nivel=3, ruta_titulo="Qué se hace", paso_label="ESTE CASO",
         pasos=[(1, "Estatina de alta intensidad", ["Atorvastatina 40-80 o rosuvastatina 20-40 mg"], True),
                (2, "Estilo de vida", ["Dieta sin frituras, ejercicio, bajar peso"], False),
                (3, "Estudiar a la familia", ["Posible hipercolesterolemia familiar"], False)]),
  banda=B("Perfil lipídico del caso", D(lambda s, x, y: I.lab_barras(s, x, y, [("LDL", "195 mg/dL", 195, True), ("Colesterol total", "260", 260, False),
                                                                              ("HDL", "28 (bajo)", 28, False), ("Triglicéridos", "140", 140, False)],
                                                                   W=340, xmax=280, titulo="mg/dL", ref=None), 340, 160),
          ["LDL de 195: por encima de 190.", "HDL bajo: otro factor de riesgo.", "Triglicéridos normales: el problema es el LDL."], ans=0),
  tabla=("Opciones de la pregunta", [("Solo suplementos", False), ("Dieta 6 meses y reevaluar", False), ("Estatina alta intensidad + estilo de vida", True),
                                     ("Fibratos", False)],
         [("Problema", ["No bajan el LDL lo suficiente", "Retrasa con LDL ≥ 190", "Ninguno", "No bajan el LDL"])]))

# CAR-083 · Paro con recursos limitados · CICLO
_dea = (f'<rect x="78" y="96" width="26" height="18" rx="3" fill="#fde047" stroke="#a16207" stroke-width="1.5"/>'
        + f'<rect x="156" y="148" width="26" height="18" rx="3" fill="#fde047" stroke="#a16207" stroke-width="1.5"/>'
        + I.P("M91 96 C80 70 40 70 20 60 M169 148 C196 120 212 90 222 60", "none", "#334155", 2))
S("ciclo", "CAR-083", "paro-cardiaco-primer-nivel-compresiones-alta-calidad-dea",
  "Paro cardiaco en el primer nivel: compresiones de alta calidad y DEA cuanto antes",
  "Reanimación cardiopulmonar · soporte básico", EC,
  ("Soporte vital básico con DEA", ["Lo que más salva cerebro: compresiones inmediatas, con pocas pausas, y desfibrilar pronto.",
                                    "El DEA analiza y descarga; las compresiones solo se detienen para eso."]),
  ("Varón de 65 años en paro, centro de salud", ["Hay AMBU, oxígeno y DEA; nadie entrenado en ACLS.", "¿Qué secuencia seguir?"]),
  ["Empezar compresiones de inmediato (100-120/min, 5-6 cm, dejar que el tórax vuelva).",
   "Colocar el DEA apenas esté disponible; pausar solo para analizar y descargar; reanudar enseguida 2 minutos.",
   "Ventilar con AMBU 30:2; la vía venosa y la adrenalina vienen después y no deben interrumpir la RCP."],
  AHA + "; ILCOR.",
  d=dict(rotulo="El ciclo de la reanimación", tag="ESTE CASO",
         img_titulo="Compresiones y parches del DEA",
         img=D(lambda s, x, y: I.cuerpo(s, x + 20, y, {"torax": "#fde2e2"}, extra=_dea, marcas=[(1, 120, 130), (2, 91, 105)], sc=0.72), 280, 330),
         img_pie="1 compresiones en el centro del tórax; 2 parches del DEA (debajo de la clavícula derecha y en el costado izquierdo).",
         centro="RCP básica con DEA", ans=0,
         pasos=[("Compresiones ya", "100-120/min, 5-6 cm"), ("Colocar el DEA", "apenas llegue"),
                ("Analizar el ritmo", "pausa mínima"), ("Descarga si la indica", "y seguir comprimiendo"),
                ("2 minutos de RCP", "30:2 con AMBU")],
         claves_titulo="Por qué no las otras",
         claves=[("Oxígeno y vía venosa primero", ["Retrasa las compresiones."], False),
                 ("Trasladar en paro", ["La RCP en movimiento es de mala calidad."], False),
                 ("DEA antes de comprimir", ["No se espera al DEA para empezar."], False)]),
  tabla=("Opciones de la pregunta", [("Compresiones + DEA apenas llegue", True), ("Oxígeno y adrenalina primero", False),
                                     ("Trasladar comprimiendo", False), ("DEA primero, luego compresiones", False)],
         [("Problema", ["Ninguno", "Retrasa las compresiones", "RCP de mala calidad", "Retrasa las compresiones"])]))

# CAR-084 · Hipertrigliceridemia · MATRIZ + franja
S("matriz", "CAR-084", "hipertrigliceridemia-persistente-pese-estilo-vida-fenofibrato",
  "Triglicéridos altos que no bajan con dieta y ejercicio: fenofibrato",
  "Dislipidemias · hipertrigliceridemia", EC,
  ("Cada fármaco tiene su blanco", ["Estatinas, ezetimiba y ácido bempedoico bajan sobre todo el LDL.",
                                    "Los fibratos son los que más bajan los triglicéridos."]),
  ("Varón de 50 años", ["Triglicéridos altos persistentes.", "6 meses de dieta y ejercicio bien cumplidos."]),
  ["Hipertrigliceridemia aislada que no responde al estilo de vida: fenofibrato.",
   "Con triglicéridos ≥ 500 mg/dL el riesgo es la pancreatitis: fibrato y dieta muy baja en grasa.",
   "Si el LDL también está alto, la estatina sigue siendo la base."],
  "AHA/ACC (2018, 2021); ESC/EAS, dislipidemias (2019).",
  d=dict(rotulo="Problema lipídico y fármaco", eje_x="Fármaco", eje_y="Problema", caso=(1, 1),
         cols=["Estatina", "Fibrato", "Ezetimiba o bempedoico"],
         rows=["LDL alto", "Triglicéridos altos", "Triglicéridos ≥ 500", "LDL alto sin tolerar estatina"],
         cells=[[("Elección", ["Baja LDL 30-50 %"]), ("No", ["Poco efecto en LDL"]), ("Agregar", ["Si no llega a la meta"])],
                [("Ayuda poco", ["Baja TG 10-30 %"]), ("Fenofibrato", ["Elección: TG −30 a −50 %"]), ("No", ["Casi no bajan TG"])],
                [("No basta", ["Riesgo de pancreatitis"]), ("Fibrato pronto", ["+ dieta muy baja en grasa"]), ("No", ["Sin efecto en TG"])],
                [("Dosis baja", ["Si la tolera"]), ("No", ["No es su blanco"]), ("Alternativa", ["Para bajar el LDL"])]]),
  banda=B("Cuánto baja cada uno los triglicéridos", D(lambda s, x, y: I.lab_barras(s, x, y, [("Fenofibrato", "−30 a −50 %", 40, True),
                                                                                         ("Estatina", "−10 a −30 %", 20, False),
                                                                                         ("Ezetimiba", "≈ −5 %", 5, False),
                                                                                         ("Á. bempedoico", "≈ 0", 0.5, False)],
                                                                                W=340, xmax=50, titulo="Reducción de triglicéridos (%)", ref=None), 340, 160),
          ["El fibrato es el que más los baja.", "La estatina ayuda poco con los triglicéridos.", "Ezetimiba y bempedoico actúan sobre el LDL."], ans=0),
  tabla=("Opciones de la pregunta", [("Ezetimiba", False), ("Atorvastatina", False), ("Ácido bempedoico", False), ("Fenofibrato", True)],
         [("Blanco principal", ["LDL", "LDL", "LDL", "Triglicéridos: este caso"])]))

# CAR-085 · Ginecomastia por espironolactona · BALANZA + franja
_gm = I.E(98, 120, 18, 12, "#fecdd3", "#be185d", 1.6) + I.E(142, 120, 18, 12, "#fecdd3", "#be185d", 1.6)
S("balanza", "CAR-085", "insuficiencia-cardiaca-ginecomastia-espironolactona-cambiar-eplerenona",
  "Ginecomastia por espironolactona en insuficiencia cardiaca: cambiar a eplerenona",
  "Insuficiencia cardiaca · efectos adversos", EC,
  ("Antagonistas de la aldosterona", ["Reducen mortalidad en la insuficiencia cardiaca con FEVI reducida.",
                                      "La espironolactona también bloquea andrógenos: ginecomastia y menos libido."]),
  ("Varón de 45 años con IC", ["Losartán, hidroclorotiazida, bisoprolol y espironolactona.",
                               "2 meses de aumento de volumen mamario y menos libido."]),
  ["Ginecomastia + menos libido con espironolactona: efecto antiandrogénico.",
   "Se cambia por eplerenona: antagonista de aldosterona selectivo, mismo beneficio, casi sin efecto hormonal.",
   "Seguir vigilando potasio y creatinina."],
  ESC + ", insuficiencia cardiaca (2021); " + HARRISON + ".",
  d=dict(rotulo="¿Qué conviene?", gana="izq", tag="ESTE CASO",
         pregunta="Ginecomastia por espironolactona",
         izq=dict(titulo="Cambiar a eplerenona", peso="elige",
                  items=["Antagonista de aldosterona selectivo", "Mantiene el beneficio en la IC", "Casi sin efecto antiandrogénico"]),
         der=dict(titulo="Seguir con espironolactona", peso="no",
                  items=["Bloquea receptores de andrógenos", "Ginecomastia y menos libido", "Lleva a abandonar el tratamiento"]),
         veredicto=("Reemplazar espironolactona por eplerenona",
                    ["Enalapril, furosemida o metoprolol no hacen el trabajo de la espironolactona."])),
  banda=B("El paciente", D(lambda s, x, y: I.cuerpo(s, x + 40, y, extra=_gm, marcas=[(1, 120, 140)], sc=0.7), 250, 312),
          ["Aumento de volumen de ambas mamas (ginecomastia).", "Causa: efecto antiandrogénico de la espironolactona.",
           "Suele mejorar al suspenderla."], ans=0),
  tabla=("Opciones de la pregunta", [("Enalapril", False), ("Furosemida", False), ("Eplerenona", True), ("Metoprolol", False)],
         [("¿Reemplaza a la espironolactona?", ["No: ya recibe losartán", "No: es diurético de asa", "Sí", "No: ya recibe bisoprolol"])]))

# NEU-071 · EPOC por espirometría · CÁLCULO
S("calculo", "NEU-071", "fumador-fev1-fvc-menor-07-fev1-45-epoc-gold-3",
  "Fumador con FEV1/FVC < 0,7 sin reversibilidad y FEV1 45 %: EPOC moderada-grave",
  "EPOC · diagnóstico y gravedad", EN,
  ("Diagnóstico de EPOC", ["Exposición (tabaco) + síntomas + espirometría posbroncodilatador con FEV1/FVC < 0,7.",
                           "El FEV1 da la gravedad (GOLD 1-4); las exacerbaciones, el grupo (A, B, E)."]),
  ("Varón de 60 años, 40 paquetes-año", ["Tos productiva y disnea progresiva de 3 años; 2 exacerbaciones con corticoide en 1 año.",
                                         "FEV1/FVC < 0,7 sin reversibilidad; FEV1 45 %; eosinófilos 350/µL; sin asma previa."]),
  ["FEV1/FVC < 0,7 que no revierte en un fumador sin asma = EPOC.",
   "FEV1 45 % = GOLD 3 (grave, 30-49 %); 2 exacerbaciones con corticoide = grupo E.",
   "Eosinófilos ≥ 300: anuncian que el corticoide inhalado ayudará más; no lo convierten en asma."],
  "GOLD (2025); " + HARRISON + ".",
  d=dict(rotulo="Se lee la espirometría paso a paso", tag="ESTE CASO",
         ilu_titulo="Espirometría (esquema)",
         ilu=ILU(D(lambda s, x, y: I.espirometria(s, x - 20, y + 10, W_=170, H_=250), 218, 330)),
         ilu_pie="La curva de EPOC sale lento: en 1 s bota poco aire (FEV1 bajo).",
         pasos=[("Relación FEV1/FVC", ["< 0,7 tras broncodilatador: obstrucción."], False),
                ("Reversibilidad", ["No significativa: no es asma."], False),
                ("Gravedad", ["FEV1 45 % = GOLD 3 (grave)."], False),
                ("Exacerbaciones", ["2 con corticoide en 1 año: grupo E."], False),
                ("Resultado", ["EPOC estable moderada-grave."], True)]),
  tabla=("Opciones de la pregunta", [("Mixto asma-EPOC", False), ("Bronquitis sin obstrucción", False), ("Asma persistente", False),
                                     ("EPOC moderada-grave", True)],
         [("Problema", ["Sin asma previa ni reversibilidad", "Sí hay obstrucción", "No revierte", "Ninguno"])]))

# NEU-072 · Neumonía intrahospitalaria · CRONOLOGÍA
S("cronologia", "NEU-072", "hospitalizada-7-dias-fiebre-esputo-purulento-neumonia-intrahospitalaria",
  "Neumonía que aparece al séptimo día de hospitalización: neumonía intrahospitalaria",
  "Neumonía · clasificación por lugar de adquisición", EN,
  ("Neumonía intrahospitalaria", ["Aparece 48 horas o más después del ingreso y no se incubaba al ingresar.",
                                  "Cambia los gérmenes (más resistentes) y el antibiótico."]),
  ("Mujer de 70 años hospitalizada por IC", ["Día 7: somnolencia, desorientación, fiebre 38,5 °C, esputo purulento.",
                                             "Crépitos en la base izquierda."]),
  ["Neumonía que empieza ≥ 48 h después del ingreso = intrahospitalaria.",
   "Gérmenes: S. aureus, Pseudomonas, enterobacterias; cobertura según riesgo de resistencia.",
   "La confusión en el adulto mayor puede ser la primera señal de la neumonía."],
  "IDSA/ATS, neumonía intrahospitalaria (2016); ERS/ESICM (2017).",
  d=dict(rotulo="Cuándo empezó la neumonía", tag="ESTE CASO",
         ilu_titulo="Rx de tórax (esquema)",
         ilu=ILU(D(lambda s, x, y: I.torax_rx(s, x + 20, y, "consolidacion", "izq", sc=0.95), 330, 280)),
         ilu_pie="Consolidación en la base izquierda.",
         claves=[("Neumonía intrahospitalaria", ["Empezó al día 7 del ingreso."], True),
                 ("Neumonía de la comunidad", ["Solo si empieza antes de las 48 h."], False),
                 ("TEP o neumonía atípica", ["No explican el esputo purulento ni la cronología."], False)],
         eje_titulo="Días desde el ingreso", eje=(0, 10), paso=1, marca=7, unidad="d",
         eje_nombre="días de hospitalización",
         hitos=[(0, 7, "Hospitalizada por IC", "sin neumonía", False),
                (0, 2, "Primeras 48 h", "sería de la comunidad", False),
                (2, 10, "Desde las 48 h", "intrahospitalaria", False),
                (7, 8, "Este caso: día 7", "fiebre y esputo purulento", True)]),
  tabla=("Opciones de la pregunta", [("Neumonía de la comunidad", False), ("Neumonía intrahospitalaria", True), ("Neumonía atípica", False),
                                     ("Tromboembolismo pulmonar", False)],
         [("¿Encaja?", ["No: empezó en el día 7", "Sí", "No: esputo purulento", "No: hay fiebre y esputo"])]))

# NEU-073 · FPI: insuficiencia tipo I y TCAR · ÁRBOL + franja
S("arbol", "NEU-073", "fibrosis-pulmonar-pao2-50-paco2-38-insuficiencia-tipo-1-tcar",
  "Fibrosis pulmonar con PaO₂ 50 y PaCO₂ 38: insuficiencia respiratoria tipo I y TC de alta resolución",
  "Enfermedad pulmonar intersticial · fibrosis", EN,
  ("Insuficiencia respiratoria", ["Tipo I (hipoxémica): PaO₂ < 60 con PaCO₂ normal o baja.",
                                  "Tipo II (hipercápnica): PaCO₂ > 45 por falla de la ventilación."]),
  ("Varón de 72 años con fibrosis pulmonar idiopática", ["Necesita más oxígeno (4 L/min), sin infección; SatO₂ 88 %.",
                                                          "AGA: pH 7,43, PaCO₂ 38, PaO₂ 50, HCO₃ 28."]),
  ["PaO₂ 50 con PaCO₂ 38 = insuficiencia respiratoria tipo I (el oxígeno no difunde; el CO₂ sí).",
   "Para ver extensión y progresión de la fibrosis: TC de tórax de alta resolución.",
   "La caminata de 6 minutos y la espirometría miden función; el eco busca hipertensión pulmonar."],
  "ATS/ERS/JRS/ALAT, fibrosis pulmonar idiopática (2022); " + HARRISON + ".",
  arbol=Q("¿La PaO₂ está bajo 60 mmHg?", [
      L("No", "Sin insuficiencia respiratoria", ["Vigilar"]),
      Q("¿La PaCO₂ está sobre 45 mmHg?", [
          L("Sí", "Tipo II (hipercápnica)", ["Falla de la bomba: EPOC grave, neuromuscular"]),
          L("No: PaCO₂ 38", "TIPO I (HIPOXÉMICA)", ["Fibrosis: el oxígeno no difunde", "Extensión: TC de alta resolución"], path=True)],
        edge="Sí: 50", path=True)], path=True),
  banda=B("Rx de tórax (esquema)", D(lambda s, x, y: I.torax_rx(s, x, y, "fibrosis", sc=0.95), 285, 266),
          ["Patrón reticular en las bases (fibrosis).", "La TC de alta resolución muestra panal de abejas y su extensión.",
           "Sirve para seguir la progresión."], ans=1),
  tabla=("Opciones de la pregunta", [("I; caminata 6 min", False), ("II; ecocardiograma", False), ("I; TC alta resolución", True),
                                     ("II; espirometría", False)],
         [("Problema", ["No mide la extensión", "No es tipo II", "Ninguno", "No es tipo II"])]))


# NEU-074 · Absceso pulmonar refractario · ÁRBOL CON IMAGEN (foto real)
def _absceso(s, x, y):
    _img_draw(s, x, y, P("absceso_rx.jpg", 300, 276, [("caja", 0.26, 0.55, 0.48, 0.78, "absceso", 0.04, 0.88)],
                         credito="Rx: James Heilman · Wikimedia Commons · CC BY-SA 4.0"))


S("arbol_imagen", "NEU-074", "absceso-pulmonar-sin-mejoria-tras-3-semanas-antibiotico-broncoscopia",
  "Absceso pulmonar que no mejora tras 3 semanas de antibiótico: broncoscopía",
  "Infecciones pulmonares · absceso pulmonar", EN,
  ("Absceso pulmonar", ["Cavidad con nivel hidroaéreo; esputo fétido por anaerobios.",
                        "La mayoría cura con antibiótico; si no, hay que buscar por qué."]),
  ("Varón de 45 años", ["3 meses de tos con esputo fétido, fiebre y baja de peso.",
                        "> 3 semanas de antibiótico EV sin mejoría; TC: cavidad con nivel en el lóbulo inferior derecho."]),
  ["Absceso que no mejora con antibiótico adecuado: broncoscopía para buscar obstrucción (tumor, cuerpo extraño) y tomar muestras.",
   "Se mantiene el antibiótico mientras se estudia.",
   "La cirugía queda para el fracaso definitivo o complicaciones; el tubo de tórax es para el empiema, no para el absceso."],
  "BTS; " + HARRISON + ".",
  d=dict(rotulo="¿Por qué no mejora?", tag="ESTE CASO",
         pregunta="Absceso pulmonar tratado ≥ 3 semanas: ¿mejora?",
         ramas=[("Sí", "Completar el antibiótico", ["Hasta que la cavidad se reduzca (4-6 semanas o más)."]),
                ("No: sigue igual", "Broncoscopía",
                 ["Busca algo que tape el bronquio: tumor o cuerpo extraño.", "Toma muestras para cultivo y biopsia."])],
         ilu=_absceso, IW=300, IH=294,
         ilu_pie="Rx real: absceso en la base derecha (recuadro); la flecha roja es de la imagen original.",
         luego_titulo="Qué hacer y qué no",
         luego=[("Broncoscopía sin cambiar el antibiótico", ["Lo correcto en este caso."], True),
                ("Tubo de tórax", ["Es para el empiema, no para una cavidad dentro del pulmón."], False),
                ("Lobectomía de entrada", ["Solo si fracasa todo o hay complicación."], False)]),
  tabla=("Opciones de la pregunta", [("Tubo de tórax", False), ("4 semanas más de antibiótico", False), ("Broncoscopía", True),
                                     ("Lobectomía", False)],
         [("Problema", ["No drena un absceso", "No busca la causa", "Ninguno", "Prematura"])]))

# NEU-075 · Neumonitis por hipersensibilidad · RADIAL + franja
S("radial", "NEU-075", "criador-palomas-vidrio-esmerilado-mosaico-neumonitis-hipersensibilidad-prednisona",
  "Criador de palomas con vidrio esmerilado y mosaico: neumonitis por hipersensibilidad, prednisona oral",
  "Enfermedad pulmonar intersticial · neumonitis por hipersensibilidad", EN,
  ("Neumonitis por hipersensibilidad", ["Reacción inmune del pulmón a un antígeno inhalado (aves, hongos).",
                                        "Lo primero es evitar la exposición; si hay compromiso, corticoide sistémico."]),
  ("Varón de 40 años, cría palomas hace 10 años", ["3 meses de tos seca, disnea y baja de peso; SatO₂ 91 %.",
                                                   "Restricción con DLCO baja; TC: vidrio esmerilado, nódulos centrolobulillares y mosaico."]),
  ["Exposición a aves + restricción + TC con vidrio esmerilado y mosaico = neumonitis por hipersensibilidad.",
   "Tratamiento: alejarse de las aves + prednisona oral (0,5 mg/kg/día) con reducción progresiva.",
   "El corticoide inhalado y el antileucotrieno no llegan al intersticio; los pulsos son para casos graves agudos."],
  "ATS/JRS/ALAT, neumonitis por hipersensibilidad (2020); " + HARRISON + ".",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Neumonitis por aves con hipoxemia",
         items=[("Prednisona oral con reducción", ["Actúa en el intersticio; junto con evitar las aves"]),
                ("Corticoide inhalado en dosis alta", ["No llega al intersticio"]),
                ("Antagonista de leucotrienos", ["Sirve en asma, no aquí"]),
                ("Pulsos de metilprednisolona", ["Solo en formas agudas graves"])],
         ruta=["Cría palomas", "Tos y disnea, restricción", "TC: vidrio esmerilado y mosaico", "Evitar aves + prednisona"]),
  banda=B("Rx de tórax (esquema)", D(lambda s, x, y: I.torax_rx(s, x, y, "intersticial", sc=0.95), 285, 266),
          ["Infiltrado intersticial difuso.", "La TC lo precisa: vidrio esmerilado, nódulos y mosaico.",
           "Si sigue expuesto avanza a fibrosis: por eso se separa de las aves."], ans=2),
  tabla=("Opciones de la pregunta", [("Corticoide inhalado", False), ("Prednisona oral con reducción", True), ("Antileucotrieno", False),
                                     ("Pulsos de metilprednisolona", False)],
         [("¿Indicado?", ["No llega al intersticio", "Sí", "No", "Excesivo aquí"])]))

# NEU-076 · TB sensible confirmada por Xpert · FASES + franja (foto real)
S("fases", "NEU-076", "tos-3-meses-cavidad-xpert-positivo-sin-resistencia-rhze-notificar",
  "TB pulmonar confirmada por Xpert, sensible a rifampicina: iniciar RHZE y notificar",
  "Tuberculosis · tratamiento de la TB sensible", EN,
  ("Tuberculosis sensible", ["Xpert MTB/RIF positivo sin resistencia a rifampicina = TB sensible.",
                             "Esquema de 6 meses: 2 meses de RHZE y 4 de RH; la notificación es obligatoria."]),
  ("Varón de 30 años", ["3 meses de tos productiva, sudoración nocturna y baja de 8 kg.",
                        "Rx: cavidad en el lóbulo superior derecho; Xpert positivo sin resistencia."]),
  ["Iniciar ya: fase intensiva RHZE (2 meses) y continuación RH (4 meses), con tratamiento supervisado.",
   "Notificar el caso y estudiar a los contactos; ofrecer prueba de VIH.",
   "No hace falta TC ni repetir el Xpert para empezar."],
  MINSA + ", norma técnica de tuberculosis; OMS (2022).",
  d=dict(rotulo="El tratamiento por fases", ans=1,
         fases=[("Diagnóstico", "Día 0", "XPERT +, SENSIBLE", ["Notificar el caso", "Estudiar contactos"]),
                ("Fase intensiva", "2 meses", "RHZE DIARIO", ["Rifampicina, isoniacida, pirazinamida, etambutol"]),
                ("Fase de continuación", "4 meses", "RH", ["Rifampicina e isoniacida"]),
                ("Fin", "Mes 6", "CURADO", ["Baciloscopía negativa"])],
         curvas=[("Bacilos en el esputo", "#dc2626", [0.95, 0.95, 0.5, 0.15, 0.05, 0.02, 0.0]),
                 ("Síntomas", "#0f766e", [0.9, 0.85, 0.45, 0.2, 0.1, 0.05, 0.03])]),
  banda=B("Rx real del caso típico", P("tb_cavitaria.jpg", 330, 303, [("circulo", 0.25, 0.25, 0.08, "cavidad", 0.48, 0.06)],
                                         credito="CDC · Wikimedia Commons · dominio público"),
          ["Cavidad en el lóbulo superior derecho (círculo).", "Las cavidades tienen muchos bacilos: es muy contagiosa.",
           "Con el Xpert sensible se empieza RHZE sin más estudios."], ans=0),
  tabla=("Opciones de la pregunta", [("RHZE y notificar", True), ("Derivar y estudiar inmunodeficiencia", False),
                                     ("Sintomáticos y repetir Xpert", False), ("TC para descartar neoplasia", False)],
         [("Problema", ["Ninguno", "Retrasa el tratamiento", "Deja contagiar", "El diagnóstico ya está hecho"])]))
