"""Entrega 3 · tanda t11 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
BEAUCHAMP = "Beauchamp y Childress, Principios de ética biomédica 8.ª ed."

# SP-130 · Autonomía frente a no maleficencia · RADIAL
S("radial", "SP-130", "Paciente con COVID-19 que sale a trabajar sin avisar invocando su autonomía: predomina el principio de no maleficencia (no dañar a terceros)",
  "Bioética · conflicto de principios",
  ("Los cuatro principios de la bioética", ["Autonomía, beneficencia, no maleficencia y justicia. Cuando chocan, se pondera el caso.",
                                            "La autonomía tiene un límite: no puede usarse para dañar a otros. En salud pública pesa más evitar el contagio."]),
  ("Vendedor de 28 años con COVID-19 sintomático", ["No avisa a sus vecinos y sale a trabajar «por autonomía».", "Debería aislarse para no contagiar."]),
  ["No maleficencia: no causar daño (aquí, contagiar a otros).",
   "El aislamiento obligatorio en una epidemia es una limitación legítima de la autonomía (Ley General de Salud).",
   "La confidencialidad no es uno de los cuatro principios; se rompe si hay riesgo grave para terceros."],
  BEAUCHAMP + "; Ley General de Salud n.º 26842 (art. 76-79: enfermedades transmisibles).",
  op=("¿Predomina?", ["No: tiene límite cuando daña a otros", "Sí: evitar contagiar", "No: reparte recursos con equidad", "No: hacer el bien al paciente", "No: no es uno de los 4 principios"]),
  d=dict(rotulo="¿Qué principio pesa más aquí?", centro="BIOÉTICA", centro_sub="4 principios", ans=1,
         items=[("AUTONOMÍA", ["Decidir sobre uno mismo", "Su límite: dañar a otros"]), ("NO MALEFICENCIA", ["No dañar (no contagiar)", "Este caso"]),
                ("BENEFICENCIA", ["Hacer el bien al paciente"]), ("JUSTICIA", ["Equidad en los recursos"]),
                ("CONFIDENCIALIDAD", ["Deber, no principio", "Cede ante riesgo a terceros"])],
         ruta=["Conflicto", "Autonomía vs daño a otros", "Gana no maleficencia", "Aislamiento"]))

# INF-088 · Prevención de NAV: cabecera elevada · CHECKLIST
S("checklist", "INF-088", "Elevar la cabecera de la cama 30-45° reduce la neumonía asociada al ventilador (evita la aspiración)",
  "Neumonía asociada a la ventilación mecánica · prevención",
  ("Paquete de prevención de la NAV", ["La NAV se produce por aspiración de secreciones de la boca y el estómago alrededor del tubo.",
                                       "Medidas con efecto: cabecera 30-45°, retirar la ventilación lo antes posible (pausa diaria de sedación), aspiración subglótica, higiene de manos."]),
  ("Pregunta de teoría", ["¿Qué medida ha mostrado disminuir la neumonía asociada al ventilador?"]),
  ["Cabecera semisentada (30-45°) salvo contraindicación.",
   "Interrupción diaria de la sedación y prueba de respiración espontánea; tubo con aspiración subglótica.",
   "No cambiar los circuitos de rutina (solo si están sucios o dañados)."],
  "SHEA/IDSA/APIC, prevención de NAV (2022); " + IDSA + "/ATS (2016).",
  op=("¿Disminuye la NAV?", ["Sí: evita la aspiración", "No: cambiarlos de rutina no ayuda", "No: no se recomienda de rutina (resistencias)",
                             "No: previene úlceras, no neumonía", "No: aumenta la aspiración"],
      {0: "Cabecera elevada más de 45 grados", 1: "Cambiar el circuito cada 24 horas"}),
  d=dict(rotulo="Paquete para prevenir la NAV", tag="EFECTIVA",
         pasos=[("Cabecera a 30-45°", "Semisentado: menos aspiración", True),
                ("Pausa diaria de sedación", "Y prueba para retirar el ventilador", False),
                ("Aspiración subglótica", "Tubo con puerto especial", False),
                ("Higiene de manos y de la boca", "Cuidado del tubo y la sonda", False)],
         no_hacer=[("Cambiar el circuito cada 24 h", "No reduce la NAV"), ("Decúbito supino plano", "Aumenta la aspiración"),
                   ("Antibiótico profiláctico de rutina", "Resistencias")],
         veredicto=("Cabecera elevada = menos neumonía", "La medida más simple y con evidencia.")))

# SP-131 · Brote febril con Aedes: control de focos · TRANSMISIÓN + foto
S("transmision", "SP-131", "Aumento de febriles con Aedes aegypti en el territorio: los equipos extramurales priorizan el control de fuentes de infección (criaderos) y contactos",
  "Dengue · control de brote",
  ("Control de un brote de dengue", ["Sin vacuna de uso masivo, el dengue se controla cortando al vector: eliminar criaderos (recipientes con agua), larvicida y fumigación en brote.",
                                     "Además: búsqueda activa de febriles, notificación y vigilancia de casos."]),
  ("Centro de salud", ["Aumento de pacientes febriles.", "Salud ambiental informa Aedes aegypti en el territorio."]),
  ["Visita casa por casa: eliminar o tapar recipientes con agua, larvicida (temefós), fumigación en el brote.",
   "Búsqueda y notificación de febriles; control de contactos.",
   "Educación: «tapa, lava, voltea, tira»; repelente y mosquiteros."],
  OMS + ", dengue (2024); " + MINSA + ", NTS de vigilancia y control de Aedes aegypti (2023).",
  op=("¿Acción prioritaria?", ["No: es para eventos de importancia internacional", "Sí: cortar la transmisión local", "No: no es la medida de control de brote",
                               "No: el dengue es viral", "No: no tiene relación"]),
  d=dict(rotulo="Dónde se corta la cadena del dengue", tag="PRIORIDAD",
         eslabones=[("Virus del dengue", "Agente", "No hay antiviral", False), ("Persona infectada", "Reservorio", "Detectar y notificar febriles", False),
                    ("Aedes aegypti", "Vector", "Eliminar criaderos y fumigar", True), ("Picadura", "Vía", "Repelente y mosquitero", False),
                    ("Persona sana", "Susceptible", "Vacuna (grupos priorizados)", False)],
         img=B("El vector", P("aedes.jpg", 300, 228, [], credito="John Ragai" + CC + "CC BY 2.0"),
               [("Aedes aegypti", "Patas con anillos blancos; pica de día."), ("Criaderos", "Agua limpia estancada en recipientes."),
                ("En brote", "Fumigación espacial + control de criaderos.")], pie="Foto de un mosquito."),
         veredicto=("Prioridad: control de focos y contactos", "Eliminar criaderos y buscar febriles en el territorio.")))

# NEF-073 · Atrofia testicular por ligadura de la arteria testicular · TARJETAS + esquema
S("tarjetas", "NEF-073", "Varón con disminución del tamaño testicular un año después de una cirugía pélvica: atrofia por ligadura de la arteria testicular",
  "Complicaciones quirúrgicas · atrofia testicular",
  ("Irrigación del testículo", ["La arteria testicular (rama de la aorta) es la principal; también llegan la deferencial y la cremastérica.",
                               "Si se liga o lesiona la testicular en una cirugía (pélvica, hernia, varicocele), el testículo puede atrofiarse."]),
  ("Varón de 33 años", ["Disminución del volumen testicular.", "Cirugía por trauma pélvico hace un año."]),
  ["Ecografía Doppler testicular: tamaño y flujo.",
   "Hormonas (testosterona, FSH, LH) y espermatograma si hay deseo de fertilidad.",
   "Prevención: identificar y respetar los elementos del cordón en la cirugía inguinal y pélvica."],
  "EAU, salud sexual y reproductiva masculina (2025); " + "Campbell-Walsh-Wein Urology 12.ª ed.",
  op=("¿Complicación?", ["No: da obstrucción, no atrofia", "Sí: quita la irrigación principal", "No: da infertilidad, no atrofia", "No: término impreciso", "No: no reduce el testículo"]),
  d=dict(rotulo="Qué pasa si se lesiona cada elemento del cordón", ans=0,
         cards=[dict(titulo="Arteria testicular", datos=[("Función", "Irrigación principal", True), ("Si se liga", "Atrofia testicular", True), ("Ejemplo", "Cirugía pélvica", True)], pie="Este caso."),
                dict(titulo="Conducto deferente", datos=[("Función", "Lleva espermatozoides", False), ("Si se corta", "Infertilidad", False), ("Testículo", "Tamaño normal", False)], pie="Vasectomía."),
                dict(titulo="Plexo pampiniforme", datos=[("Función", "Drena y enfría", False), ("Si se dilata", "Varicocele", False), ("Riesgo", "Atrofia leve", False)], pie="Venas."),
                dict(titulo="Epidídimo", datos=[("Función", "Madura espermatozoides", False), ("Si se lesiona", "Obstrucción", False), ("Testículo", "Tamaño normal", False)], pie="Detrás del testículo.")]),
  banda=B("El testículo y su cordón", D(lambda s, x, y: I.testiculo(s, x + 10, y, "normal"), 270, 232),
          [("Arteria testicular", "Viaja en el cordón espermático desde la aorta."),
           ("Sin flujo", "El testículo se achica en meses (atrofia)."),
           ("Doppler", "Muestra el flujo disminuido o ausente.")],
          pie="Esquema (derecha del paciente = izquierda del dibujo)."))

# GIN-179 · Prevención de preeclampsia: aspirina · ALARMA
S("alarma", "GIN-179", "Gestante de 12 semanas con preeclampsia severa previa, lupus y sobrepeso: alto riesgo de preeclampsia, la profilaxis más efectiva es aspirina a dosis bajas",
  "Preeclampsia · prevención",
  ("Prevención de la preeclampsia", ["Con un factor de riesgo alto (o dos moderados) se indica aspirina a dosis baja desde las 12-16 semanas hasta las 36.",
                                     "Reduce la preeclampsia pretérmino; en zonas con dieta pobre en calcio se añade calcio."]),
  ("Segundigesta de 12 semanas", ["Sobrepeso y lupus eritematoso sistémico no activo.", "Preeclampsia severa y parto pretérmino en la gestación anterior."]),
  ["Aspirina 100-150 mg cada noche desde las 12 (hasta 16) semanas y hasta las 36.",
   "Calcio 1-2 g/día si la ingesta es baja (MINSA: desde las 20 semanas).",
   "En lupus: hidroxicloroquina, anticuerpos antifosfolípidos (si son positivos: heparina + aspirina)."],
  "USPSTF (2021); ACOG (2018; act.); FIGO (2019); " + MINSA + ".",
  op=("¿Más efectiva?", ["No: no previene la preeclampsia", "Sí: reduce la preeclampsia pretérmino", "No: sin evidencia suficiente", "No: solo si hay antifosfolípidos",
                         "No: contraindicado en el embarazo"]),
  d=dict(rotulo="Factores de riesgo de preeclampsia", lista_titulo="Riesgo ALTO (basta uno)",
         signos=[("Preeclampsia previa", "Severa, con parto pretérmino", True), ("Enfermedad autoinmune (lupus, antifosfolípidos)", "Lupus", True),
                 ("Hipertensión crónica", "No", False), ("Diabetes pregestacional", "No", False), ("Enfermedad renal", "No", False),
                 ("Embarazo múltiple", "No", False)],
         accion=("Aspirina 100-150 mg cada noche", "Desde las 12-16 semanas hasta las 36."),
         accion_rotulo="CON 1 FACTOR ALTO",
         veredicto=("Dos factores altos + sobrepeso: aspirina a dosis baja", "Más calcio si la dieta es pobre en calcio.")))

# TRA-039 · Luxación posterior de cadera: necrosis avascular · GRÁFICA
S("grafica", "TRA-039", "Luxación posterior de cadera reducida a las 72 horas: la complicación ósea a mediano y largo plazo es la necrosis avascular de la cabeza femoral",
  "Luxación de cadera",
  ("Luxación posterior de cadera", ["Por choque frontal (rodilla contra el tablero): la pierna queda corta, en flexión, aducción y rotación interna.",
                                    "La cabeza femoral fuera de su sitio estira y ocluye sus vasos: cuanto más tarda la reducción, más necrosis avascular."]),
  ("Varón de 45 años, accidente de tránsito", ["Dolor 9/10 e impotencia funcional.", "Luxación posterior de cadera reducida recién a las 72 horas."]),
  ["Reducción cerrada urgente bajo sedación en las primeras 6 horas; TC después para ver fracturas del acetábulo.",
   "Explorar el nervio ciático antes y después (lesión en ~10-20 %).",
   "Seguimiento con RM: la necrosis puede aparecer hasta 2-5 años después; luego artrosis."],
  ATLS + " (2025); Rockwood y Green, Fracturas en el adulto 10.ª ed.",
  op=("¿Complicación ósea tardía?", ["No: rara", "Sí: por la reducción tardía", "No: es una lesión asociada inmediata", "No: es nerviosa e inmediata", "No: no hubo herida"]),
  d=dict(rotulo="Riesgo de necrosis avascular según la hora de reducción", eje_x="Horas hasta reducir la luxación", eje_y="Necrosis avascular (%)",
         x=(0, 72, [(0, "0"), (6, "6 h"), (12, "12"), (24, "24"), (48, "48"), (72, "72 h")]),
         y=(0, 60, [(0, "0"), (20, "20"), (40, "40"), (60, "60")]),
         series=[("Riesgo", [(0, 3), (6, 5), (9, 18), (12, 30), (18, 40), (24, 45), (36, 49), (48, 52), (60, 54), (72, 55)], "#0f766e")],
         zonas=[(0, 6, "ideal", "#dcfce7")],
         caso=(72, 55, "72 h"),
         notas=[("Antes de 6 h: ~5 %", "Reducir de urgencia.", False),
                ("Después de 6 h: hasta ~50 %", "Los vasos de la cabeza quedan estirados.", False),
                ("Este caso: 72 h", "Riesgo muy alto de necrosis avascular.", True)],
         veredicto=("Reducción tardía = necrosis avascular", "Vigilar con RM; luego puede venir artrosis."),
         claves_titulo="Otras complicaciones",
         claves=[("Lesión del ciático", ["Inmediata, en la exploración inicial"], False), ("Fractura del acetábulo", ["Asociada, se ve en la TC"], False),
                 ("Artrosis postraumática", ["Años después"], False)]))

# SP-132 · Muerte encefálica: retirar soporte · BALANZA
S("balanza", "SP-132", "Paciente con muerte encefálica establecida al que se le retira el soporte ventilatorio: no se vulnera ningún principio ético (ya está fallecido)",
  "Bioética · muerte encefálica",
  ("Muerte encefálica", ["Cese irreversible de todas las funciones del encéfalo, incluido el tronco: legal y médicamente es la muerte de la persona.",
                         "Retirar el ventilador no es eutanasia ni abandono: se reconoce un fallecimiento ya ocurrido."]),
  ("Varón de 66 años en UCI", ["TEC grave con diagnóstico establecido de muerte encefálica.", "La junta médica decide suspender el soporte ventilatorio."]),
  ["Diagnóstico: coma sin causas reversibles, ausencia de reflejos del tronco y prueba de apnea; pruebas complementarias según la norma.",
   "Se informa a la familia y se evalúa la donación de órganos antes de retirar el soporte.",
   "Ley 28189 (donación y trasplante) y su reglamento."],
  "Ley n.º 28189 y reglamento (Perú); AAN/SCCM, muerte encefálica (2023).",
  op=("¿Valor vulnerado?", ["No: no se afecta", "No: se respeta al fallecido", "Sí: está fallecido", "No: no se afecta", "No: no aplica"]),
  d=dict(rotulo="¿Retirar el ventilador vulnera algún principio?", gana="der", pregunta="¿Hacia dónde se inclina?",
         izq=dict(titulo="Sería un problema si…", peso="SÍ VULNERA", items=["El paciente estuviera vivo (sin muerte encefálica)", "No se hubiera confirmado el diagnóstico",
                                                                           "Se ocultara a la familia"]),
         der=dict(titulo="En este caso", peso="NINGUNO", items=["Muerte encefálica establecida = muerte", "Decisión de una junta médica",
                                                                "Ventilar un cadáver no tiene fin terapéutico", "Posible donación de órganos"]),
         veredicto=("No se vulnera ningún principio", ["La persona ya falleció; se informa a la familia.", "Se evalúa la donación de órganos."])))

# GIN-180 · Amenaza de parto pretérmino: corticoides y tocólisis · TERMÓMETRO
S("termometro", "GIN-180", "Primigesta de 32 semanas con contracciones cada 4 minutos, 1 cm de dilatación y membranas íntegras: amenaza de parto pretérmino, maduración pulmonar y tocólisis",
  "Parto pretérmino",
  ("Amenaza de parto pretérmino", ["Contracciones regulares con cambios cervicales mínimos (< 2-3 cm) entre las 22 y 36+6 semanas.",
                                   "Antes de las 34 semanas: corticoide para el pulmón fetal y tocólisis por 48 h para dar tiempo a que actúe."]),
  ("Primigesta de 32 semanas", ["Dolor tipo cólico y pérdida de moco; contracciones de 30 s cada 4 min.", "LCF 158; sin pérdida de líquido; cérvix blando, 1 cm, membranas íntegras."]),
  ["Betametasona 12 mg IM, 2 dosis cada 24 h (o dexametasona 6 mg c/12 h × 4).",
   "Tocólisis 48 h: nifedipino (de elección) o indometacina antes de las 32 sem; no si hay infección o sufrimiento fetal.",
   "Sulfato de magnesio si el parto es inminente antes de las 32 semanas (neuroprotección)."],
  ACOG + " n.º 171 (2016; act.) y n.º 713 (corticoides); FIGO (2021); " + MINSA + ".",
  op=("¿Conducta?", ["No: no se induce a las 32 sem", "No: requiere hospitalización", "Sí: corticoide + tocólisis", "No: no hay indicación de terminar", "No: no aporta ahora"]),
  d=dict(rotulo="¿Qué tan avanzado está el parto pretérmino?", caso_nivel=1, ruta_titulo="Qué hacer a las 32 semanas", paso_label="ESTE CASO",
         niveles=[("Falso", "Contracciones sin cambios", ["Observar 2-3 h"]), ("Amenaza", "Contracciones + < 2-3 cm", ["Cérvix blando, 1 cm"]),
                  ("En trabajo", "≥ 3 cm o borramiento ≥ 80 %", ["Ya no se frena"])],
         pasos=[(1, "Hospitalizar y monitorear", ["Descartar infección"], False),
                (2, "Corticoide + tocólisis (nifedipino)", ["48 horas"], True),
                (3, "Sulfato de magnesio", ["Si el parto es inminente < 32 sem"], False)]))

# GIN-181 · Embarazo con DIU y hilos visibles · ÁRBOL + foto
S("arbol", "GIN-181", "Usuaria de DIU con prueba de embarazo positiva y hilos visibles: retirar el dispositivo",
  "Anticoncepción · embarazo con DIU",
  ("Embarazo con DIU", ["Raro, pero si ocurre: más riesgo de aborto, aborto séptico, parto pretérmino y ectópico.",
                        "Si los hilos se ven, retirarlo lo antes posible disminuye esos riesgos."]),
  ("Usuaria de DIU", ["Retraso menstrual de 3 días; prueba de embarazo positiva.", "Se ven los hilos del dispositivo."]),
  ["Retirar con tracción suave en el primer trimestre si los hilos son visibles.",
   "Ecografía transvaginal para ubicar el embarazo (descartar ectópico) y el DIU.",
   "Hilos no visibles: no intentar sacarlo a ciegas; eco y seguimiento de alto riesgo."],
  OMS + ", criterios médicos de elegibilidad (2015; act. 2023); ACOG; " + MINSA + ".",
  op=("¿Conducta?", ["No: ya es positivo", "Útil, pero no es la conducta principal", "No: no cambia la conducta", "Sí: hilos visibles → retirar", "No: más aborto séptico y pretérmino"]),
  arbol=Q("Embarazo con DIU: ¿se ven los hilos?", [
      L("Sí (este caso)", "RETIRAR EL DIU", ["Tracción suave", "Y eco transvaginal"], path=True),
      L("No", "Ecografía", ["Ubicar embarazo y DIU", "Descartar ectópico"])], path=True),
  banda=B("El dispositivo y sus hilos", P("diu.jpg", 190, 269, [], credito="Hic et nunc" + CC + "dominio público", fondo="#ffffff"),
          [("DIU de cobre en T", "Los hilos salen por el cuello del útero."),
           ("Hilos visibles", "Se puede retirar con una pinza en la consulta."),
           ("Si se deja", "Más aborto séptico y parto pretérmino.")],
          pie="Foto de un DIU."))

# REU-054 · Artritis psoriásica · CRITERIOS CASPAR + foto
S("criterios", "REU-054", "Placas eritematodescamativas en los codos, artritis con erosiones de interfalángicas distales y factor reumatoide negativo: artritis psoriásica",
  "Espondiloartritis · artritis psoriásica",
  ("Artritis psoriásica", ["Afecta a ~30 % de quienes tienen psoriasis; FR negativo (seronegativa).",
                           "Patrones: interfalángicas distales, oligoartritis asimétrica, dactilitis («dedo en salchicha»), entesitis, axial; en la Rx: «lápiz en copa»."]),
  ("Taxista de 42 años", ["Placas eritematosas descamativas en codos (1 año); dolor e hinchazón articular (6 meses).",
                          "ANA, FR y VDRL negativos; VSG 50; Rx: erosiones en IFD del 2.º y 3.er dedo."]),
  ["Criterios CASPAR: enfermedad articular inflamatoria + ≥ 3 puntos.",
   "Tratamiento: AINE; metotrexato si hay artritis periférica activa; biológicos (anti-TNF, anti-IL-17, anti-IL-23) si no responde.",
   "Revisar las uñas (piqueteado, onicólisis): predicen afectación de IFD."],
  "GRAPPA (2021); EULAR, artritis psoriásica (2023); CASPAR (2006).",
  op=("¿Diagnóstico?", ["No: FR negativo y respeta las IFD", "Sí: psoriasis + IFD + FR negativo", "No: no hay uretritis ni conjuntivitis",
                        "No: no hay enfermedad de base", "No: sin tofos ni cristales"]),
  d=dict(rotulo="Criterios CASPAR (con artritis inflamatoria)", lista_titulo="Puntos de este paciente",
         items=[("Psoriasis actual (2 puntos)", True, "Placas en los codos"), ("Factor reumatoide negativo (1)", True, "Negativo"),
                ("Distrofia ungueal (1)", None, "No se describe: revisar uñas"), ("Dactilitis (1)", None, "No se describe"),
                ("Neoformación ósea yuxtaarticular en Rx (1)", None, "Rx con erosiones en IFD")],
         umbral="≥ 3 puntos = artritis psoriásica",
         veredicto="3 puntos o más: artritis psoriásica; AINE y metotrexato.",
         img=PA("psoriasis_mont.jpg", 260, [], credito="Marnanel y Seenms · Wikimedia Commons · CC BY-SA 3.0"), img_titulo="Placas y uñas psoriásicas",
         img_pie="Placas con escama plateada; uñas con piqueteado (otras personas).", conteo="3 de 3 necesarios"))

# PSI-036 · Depresión psicótica · EMBUDO
S("embudo", "PSI-036", "Mujer con tristeza persistente, desesperanza, ideas suicidas y alucinaciones auditivas y visuales: depresión mayor con síntomas psicóticos",
  "Trastornos del ánimo · depresión psicótica",
  ("Depresión con síntomas psicóticos", ["Episodio depresivo mayor grave con alucinaciones o delirios (a menudo de culpa, ruina o enfermedad).",
                                         "La psicosis aparece solo durante el episodio del ánimo: eso la separa de la esquizofrenia y del esquizoafectivo."]),
  ("Mujer de 50 años", ["Tristeza y desesperanza persistentes, poca concentración, ideas suicidas.", "Escucha voces y ve personas que su familia no percibe."]),
  ["Antidepresivo + antipsicótico; la terapia electroconvulsiva es muy eficaz (y de primera línea si hay riesgo suicida alto).",
   "Evaluar riesgo suicida y hospitalizar si es alto.",
   "Descartar causa orgánica (tiroides, fármacos, tumor) en un primer episodio a los 50 años."],
  "APA, DSM-5-TR (2022); NICE NG222 (2022).",
  op=("¿Diagnóstico?", ["No: depende de la estación", "Incompleto: falta la psicosis", "No: leve y crónica, sin psicosis", "Sí: depresión + alucinaciones", "No: sin ánimo depresivo como eje"]),
  d=dict(rotulo="Tristeza con alucinaciones: ¿qué es?", inicio="Ánimo deprimido + alucinaciones",
         candidatos=["Distimia", "Trastorno estacional", "Esquizofrenia", "Esquizoafectivo", "Depresión con psicosis"],
         pasos=[("¿Es un episodio depresivo mayor grave (ideas suicidas)?", ["Distimia", "Trastorno estacional"]),
                ("¿La psicosis aparece solo dentro del episodio depresivo?", ["Esquizofrenia", "Esquizoafectivo"])],
         final=("DEPRESIÓN MAYOR CON SÍNTOMAS PSICÓTICOS", ["Antidepresivo + antipsicótico", "o terapia electroconvulsiva"]),
         nota="Con ideas suicidas y psicosis el riesgo es alto: evaluar hospitalización."))

# END-051 · Cetoacidosis: compensación renal · CASCADA
S("cascada", "END-051", "En la cetoacidosis diabética el riñón compensa reabsorbiendo todo el bicarbonato (disminuye su excreción) y eliminando más ácido como amonio",
  "Equilibrio ácido-base · cetoacidosis",
  ("Compensación de la acidosis metabólica", ["Pulmón (minutos): hiperventila (Kussmaul) y baja la PaCO₂.",
                                              "Riñón (horas-días): reabsorbe todo el HCO₃⁻ filtrado, fabrica bicarbonato nuevo y excreta más H⁺ como amonio (NH₄⁺) y acidez titulable."]),
  ("Diabético de 65 años", ["Trastorno de conciencia y respiración de Kussmaul; glucosa 400.", "pH 7,23, PaCO₂ 30, HCO₃⁻ 18; betahidroxibutirato en orina."]),
  ["Tratamiento: suero fisiológico, insulina en infusión (tras K ≥ 3,3), potasio, buscar el desencadenante.",
   "Bicarbonato EV solo si el pH < 6,9-7,0.",
   "Brecha aniónica alta por cetoácidos."],
  ADA + ", crisis hiperglucémicas (2024); " + "Guyton y Hall, Tratado de Fisiología Médica 14.ª ed.",
  op=("¿Cambio esperado?", ["Sí: el riñón guarda bicarbonato", "No: la excreción de amonio AUMENTA", "No: el pulmón no excreta amonio", "No: elimina MÁS CO₂ (hiperventila)",
                            "No: lo contrario"],
      {0: "Menos excreción renal de bicarbonato", 1: "Menos excreción de amonio en orina", 2: "Más excreción pulmonar de amonio",
       3: "Menos eliminación pulmonar de CO₂", 4: "Más excreción renal de bicarbonato"}),
  d=dict(rotulo="Cómo compensa el cuerpo la cetoacidosis", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Cetoácidos en la sangre", "Consumen bicarbonato", [("HCO₃⁻ 18, pH 7,23", "Acidosis metabólica", False)]),
                ("Pulmón: hiperventila", "Elimina más CO₂ (minutos)", [("Respiración de Kussmaul", "PaCO₂ 30", False)]),
                ("Riñón: guarda bicarbonato", "Reabsorbe todo el HCO₃⁻ filtrado", [("Menos HCO₃⁻ en la orina", "Esta pregunta", True)]),
                ("Riñón: elimina ácido", "Más amonio (NH₄⁺) y acidez titulable", [("Orina ácida", "Más amonio urinario", False)])],
         veredicto=("Disminuye la excreción renal de bicarbonato", "Y aumenta la de amonio; el pulmón baja la PaCO₂.")))

# PED-177 · Invaginación complicada: laparotomía · ÁRBOL + eco
S("arbol", "PED-177", "Niño de 2 años con 24 horas de cólicos, vómitos, masa abdominal, obstrucción intestinal y líquido libre: invaginación complicada, laparotomía exploratoria",
  "Invaginación intestinal",
  ("Invaginación intestinal", ["Un segmento del intestino se mete en el siguiente (ileocólica): cólico intermitente, vómitos, masa en «salchicha», heces en «jalea de grosella».",
                               "Sin complicaciones se reduce con enema de aire o suero guiado por imagen; con perforación, peritonitis o choque, cirugía."]),
  ("Niño de 2 años, 24 horas", ["Dolor cólico, náuseas y vómitos; masa alargada dolorosa; RHA metálicos.",
                                "Rx: niveles hidroaéreos; TC: signo de la salchicha y ~200 mL de líquido libre."]),
  ["Contraindicaciones del enema: peritonitis, perforación (neumoperitoneo), choque.",
   "Laparotomía: reducción manual; resección si hay intestino necrótico.",
   "Líquidos EV, sonda nasogástrica y antibiótico antes de la cirugía."],
  "ACR, criterios de imagen; APSA, invaginación (2021); " + NELSON + ".",
  op=("¿Conducta inmediata?", ["No: con líquido libre y obstrucción hay riesgo de perforar", "No: no tiene rol", "No: mismo riesgo que el enema de aire",
                               "Sí: invaginación complicada", "No: el intestino se necrosa"]),
  arbol=Q("Invaginación: ¿hay perforación, peritonitis o choque?", [
      L("Sí: líquido libre y obstrucción (este caso)", "LAPAROTOMÍA EXPLORATORIA", ["Reducción manual o resección"], path=True),
      L("No: estable", "Enema de aire o suero", ["Guiado por eco o fluoroscopía", "Éxito ~80-90 %"])], path=True),
  banda=B("Así se ve en la ecografía", P("invaginacion_eco.jpg", 300, 261, [], credito="Kalumet" + CC + "CC BY-SA 3.0"),
          [("Signo de la diana", "Anillos de intestino uno dentro de otro (corte transversal)."),
           ("Signo de la salchicha", "El mismo hallazgo en corte longitudinal."),
           ("Líquido libre", "Sufrimiento o perforación: contraindica el enema.")],
          pie="Ecografía de otro niño."))

# PED-178 · Déficit de vitamina A: manchas de Bitot · LECTURA + OMS
S("lectura", "PED-178", "Niño de 2 años con ceguera nocturna, fotofobia, xerosis conjuntival y manchas de Bitot: déficit de vitamina A (xeroftalmía)",
  "Micronutrientes · vitamina A",
  ("Xeroftalmía", ["La vitamina A forma la rodopsina de los bastones (visión nocturna) y mantiene los epitelios.",
                   "Primero ceguera nocturna, luego sequedad de la conjuntiva, manchas de Bitot y, sin tratamiento, úlcera y queratomalacia (ceguera)."]),
  ("Niño de 2 años", ["Se choca con las cosas en ambientes oscuros; molestia con la luz.", "Xerosis conjuntival y manchas de Bitot."]),
  ["Vitamina A oral: 200 000 UI (≥ 1 año) los días 1, 2 y 14 (100 000 UI de 6 a 12 meses).",
   "Prevención: suplementación cada 6 meses de 6 a 59 meses en zonas de riesgo (MINSA) y alimentos ricos en vitamina A.",
   "Con úlcera corneal: urgencia oftalmológica."],
  OMS + ", xeroftalmía y suplementación con vitamina A (2011; act.); " + MINSA + ".",
  op=("¿Deficiencia?", ["No: sangrado", "No: escorbuto (encías, hemorragias)", "No: neuropatía y hemólisis", "Sí: ojo seco y ceguera nocturna", "No: anemia y neuropatía"]),
  d=dict(rotulo="Lee el ojo", img_titulo="Mancha de Bitot",
         img=P("bitot.jpg", 330, 233, credito="CDC/Nutrition Program" + CC + "dominio público"), pines=[(0.8, 0.45)],
         pasos=[("Mancha espumosa blanca", "En la conjuntiva, al lado del iris: mancha de Bitot (X1B).", True),
                ("Conjuntiva seca y opaca", "Xerosis conjuntival (X1A).", False),
                ("Córnea", "Si se seca o ulcera: X2-X3, riesgo de ceguera.", False),
                ("Tratar", "Vitamina A días 1, 2 y 14.", False)],
         img_pie="Foto de otra persona (solo el ojo).",
         veredicto=("Ceguera nocturna + Bitot = déficit de vitamina A", "Vitamina A oral los días 1, 2 y 14.")),
  escala=dict(nombre="Clasificación de la xeroftalmía (OMS)", que="Del signo más leve al más grave.",
              grados=[("XN", "Ceguera nocturna", ["Primer síntoma"]), ("X1A / X1B", "Xerosis conjuntival / Bitot", ["Este caso"]),
                      ("X2", "Xerosis corneal", ["Córnea seca"]), ("X3", "Úlcera / queratomalacia", ["Ceguera"])],
              caso=1, porque=[("Ceguera nocturna", True), ("Xerosis conjuntival y manchas de Bitot", True)],
              conducta="Vitamina A oral y dieta; control oftalmológico."))

# NRL-047 · ACV isquémico con PA muy alta · REGLA
S("regla", "NRL-047", "Mujer con ACV isquémico agudo (afasia y hemiparesia) y PA 208/108: lo primero es bajar la PA a < 185/110 para poder trombolizar",
  "Ataque cerebrovascular isquémico agudo",
  ("Trombólisis y presión arterial", ["La alteplasa o tenecteplasa solo se da con PA < 185/110 (y se mantiene < 180/105 por 24 h).",
                                      "Con INR ≤ 1,7 la anticoagulación con warfarina no impide trombolizar; con anticoagulantes directos recientes, sí."]),
  ("Mujer de 75 años, HTA y FA anticoagulada", ["Trastorno de conciencia, afasia y hemiparesia derecha.", "PA 208/108, FC 108; INR 1,6."]),
  ["TC sin contraste urgente (descartar hemorragia) y glucemia.",
   "Labetalol 10-20 mg EV o nicardipino en infusión hasta PA < 185/110.",
   "Luego trombólisis si está dentro de la ventana (≤ 4,5 h) y trombectomía si hay oclusión de gran vaso."],
  "AHA/ASA, ACV isquémico agudo (2019; act. 2026); ESO (2021).",
  op=("¿Primera acción?", ["Sí: requisito para trombolizar", "No: primero bajar la PA", "No: no en la fase aguda", "No: INR 1,6 no lo exige", "No: no en la fase aguda"],
      {0: "Bajar la PA sistólica a < 185 mmHg"}),
  d=dict(rotulo="Dos números que deciden la trombólisis",
         reglas=[dict(nombre="PA sistólica (mmHg)", que="Debe ser < 185 (y diastólica < 110) antes de trombolizar.",
                      min=120, max=230, fmt="{}", ticks=[185],
                      bandas=[(120, 185, "Se puede trombolizar", 0), (185, 230, "Bajar primero", 3)],
                      caso=208, caso_txt="ESTE CASO: 208"),
                 dict(nombre="INR (con warfarina)", que="≤ 1,7 permite trombolizar.",
                      min=1, max=3, fmt="{}", ticks=[1.7],
                      bandas=[(1, 1.7, "Permite", 0), (1.7, 3, "Contraindica", 3)],
                      caso=1.6, caso_txt="INR 1,6")],
         claves_titulo="Orden de acción",
         claves=[("1. TC sin contraste", ["Descartar hemorragia"], False), ("2. Bajar la PA < 185/110", ["Labetalol o nicardipino"], True),
                 ("3. Trombólisis ± trombectomía", ["Si está en ventana"], False)]))

# CAR-062 · Paro: compresiones · RELOJ
S("reloj", "CAR-062", "Paciente que deja de respirar, no responde y no tiene pulso: lo primero es iniciar compresiones torácicas",
  "Reanimación cardiopulmonar",
  ("Secuencia C-A-B", ["En el adulto en paro, primero las compresiones (C), luego vía aérea (A) y ventilación (B): la sangre oxigenada que queda solo circula si se comprime.",
                       "Comprobar pulso no más de 10 segundos."]),
  ("Varón de 40 años en trauma shock", ["Dificultad respiratoria progresiva.", "Deja de respirar, no responde y no hay pulso carotídeo."]),
  ["Compresiones 100-120/min, 5-6 cm, dejar que el tórax vuelva, mínimas pausas; 30:2 sin vía avanzada.",
   "Conectar el monitor desfibrilador apenas llegue; descarga si es FV/TV sin pulso.",
   "Con causa respiratoria: asegurar la vía aérea sin interrumpir las compresiones."],
  AHA + "; ERC (2025).",
  op=("¿Primer paso?", ["No: retrasa", "No: primero comprimir mientras llega el monitor", "No: no retrasar las compresiones", "Sí: C primero",
                        "No: la ventilación va después de 30 compresiones"],
      {4: "Ventilar con bolsa antes de comprimir"}),
  d=dict(rotulo="Los primeros segundos del paro", tag="PRIMERO",
         pasos=[("< 10 s", "Reconocer el paro", "No responde, no respira, sin pulso", False), ("Ya", "Compresiones", "100-120/min, 5-6 cm", True),
                ("30:2", "Ventilación", "Bolsa-máscara tras 30 compresiones", False), ("< 3 min", "Monitor desfibrilador", "Descarga si es FV/TV", False),
                ("2 min", "Ciclos", "Cambiar a quien comprime", False)],
         veredicto=("Compresiones de inmediato", "Todo lo demás se hace sin detenerlas.")))

# SP-133 · Medios masivos de comunicación · CUADRÍCULA
S("cuadricula", "SP-133", "Para que toda la población use mascarilla, se lave las manos y guarde distancia al inicio de la pandemia, la intervención clave fueron los medios masivos de comunicación",
  "Promoción de la salud · comunicación en salud",
  ("Comunicación en salud", ["El alcance de la intervención debe ser del tamaño del problema: una medida para todo el país necesita medios masivos (TV, radio, redes).",
                             "Las intervenciones interpersonales (charlas, visitas) profundizan, pero llegan a pocos."]),
  ("Inicio de la pandemia de COVID-19", ["Sin vacunas: solo mascarilla, lavado de manos y distanciamiento.", "¿Cómo se logró que la población cumpla?"]),
  ["Mensajes claros, repetidos y coherentes por medios masivos y redes sociales.",
   "Complementar con líderes comunitarios para grupos difíciles de alcanzar.",
   "La vacunación vino después: no era una medida disponible al inicio."],
  OMS + ", comunicación de riesgos en emergencias (2018); " + MINSA + ".",
  op=("¿Intervención?", ["Sí: alcance poblacional", "No: llega a pocos y con riesgo de contagio", "No: poco alcance", "No: poco alcance", "No: aún no había vacuna"]),
  d=dict(rotulo="¿Cuánta gente alcanza cada intervención?", alto_img=0,
         celdas=[("Medios masivos", ["TV, radio, redes sociales", "Llegan a todo el país (este caso)"], None, True),
                 ("Educación a domicilio", ["Profunda pero lenta", "Además, contacto en pandemia"], None, False),
                 ("Teatro en parques", ["Alcance local", "Reúne gente: riesgo"], None, False),
                 ("Charlas en centros laborales", ["Grupos pequeños", "Complementa"], None, False)],
         veredicto=("Medios masivos de comunicación", "Una medida para toda la población necesita alcance masivo.")))

# NEF-074 · Hipopotasemia por tiazidas: ECG · CASCADA + ECG
S("cascada", "NEF-074", "Anciano con hidroclorotiazida, debilidad muscular, caídas e hiporreflexia: sospecha de hipopotasemia, lo inicial es el electrocardiograma",
  "Trastornos del potasio · hipopotasemia",
  ("Hipopotasemia por tiazidas", ["Las tiazidas aumentan la pérdida de potasio por la orina.",
                                  "Músculo: debilidad, calambres, hiporreflexia, íleo. Corazón: T aplanada, onda U, arritmias: por eso el ECG va primero."]),
  ("Varón de 68 años con hidroclorotiazida", ["15 días de debilidad muscular; dos caídas.", "Debilidad generalizada con hiporreflexia."]),
  ["ECG y potasio sérico (y magnesio) de inmediato.",
   "K < 2,5 o con ECG alterado: cloruro de potasio EV (≤ 10-20 mEq/h por vía periférica) con monitoreo; si es leve, oral.",
   "Corregir el magnesio; cambiar o añadir ahorrador de potasio (espironolactona, amilorida)."],
  KDIGO + "; " + HARRISON + ".",
  op=("¿Procedimiento inicial?", ["No: no hay focalización", "No: no es lo urgente", "No: no hay convulsiones", "Sí: busca el efecto del potasio en el corazón",
                                  "No: no es lo inicial"]),
  d=dict(rotulo="De la tiazida a la debilidad", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Tiazida", "Más sodio en el túbulo distal: se pierde potasio", [("Potasio bajo", "Pedir K y Mg", False)]),
                ("Músculo hiperpolarizado", "Le cuesta despolarizarse", [("Debilidad, caídas, hiporreflexia", "Este caso", False)]),
                ("Corazón", "Repolarización alterada", [("T aplanada, onda U, QT-U largo", "El ECG lo muestra en minutos", True),
                                                        ("Arritmias", "Extrasístoles, TV", False)])],
         veredicto=("ECG primero: dice si el potasio ya afecta al corazón", "Luego potasio y magnesio séricos y reponer.")),
  banda=B("Así se ve la hipopotasemia en el ECG", P("ecg_hipok.jpg", 380, 228, [("flecha", 0.39, 0.25, 0.6, 0.06, "onda U")], credito=ECG_PROPIO, fondo="#ffffff"),
          [("T aplanada", "Pequeña, casi plana."), ("Onda U", "Joroba después de la T."), ("Más grave", "ST deprimido, arritmias.")],
          pie="Trazado de enseñanza."))

# TRA-040 · Displasia de cadera: Galeazzi · LECTURA (esquema)
S("lectura", "TRA-040", "Lactante de 11 meses, nacida en podálica, con pliegues glúteos asimétricos y signo de Galeazzi positivo: displasia del desarrollo de la cadera",
  "Displasia del desarrollo de la cadera",
  ("Displasia del desarrollo de la cadera", ["El acetábulo y la cabeza femoral no encajan bien: subluxación o luxación.",
                                             "Factores: mujer, podálica, primogénita, antecedente familiar, oligohidramnios. Después de los 3 meses ya no sirven Ortolani y Barlow: se ven Galeazzi, asimetría y limitación de la abducción."]),
  ("Lactante mujer de 11 meses", ["Cesárea por presentación podálica y macrosomía.", "Pliegues glúteos asimétricos y Galeazzi positivo."]),
  ["Imagen: ecografía (Graf) hasta los 4-6 meses; después, Rx de pelvis.",
   "< 6 meses: arnés de Pavlik. 6-18 meses: reducción cerrada y yeso. Mayores: cirugía.",
   "Tamizaje: examen de caderas en cada control y eco a los 6 semanas si hay factores de riesgo."],
  AAP + ", displasia de cadera (2016); AAOS (2022).",
  op=("¿Diagnóstico?", ["No: fiebre y dolor agudo", "No: malformación de columna", "No: del adulto", "Sí: Galeazzi + factores de riesgo", "No: rara, ángulo cervicodiafisario"]),
  d=dict(rotulo="Los signos de esta lactante", img_titulo="Galeazzi y pliegues (esquema)",
         img=PA("dib_galeazzi.jpg", 380, credito=PROPIO, fondo="#ffffff"), pines=[(0.33, 0.33), (0.65, 0.55)],
         pasos=[("Galeazzi: una rodilla más baja", "Caderas y rodillas flexionadas: el fémur «se acorta» por la luxación.", True),
                ("Pliegues asimétricos", "Más pliegues del lado luxado.", False),
                ("Abducción limitada", "El signo más útil después de los 3 meses.", False),
                ("Confirmar con Rx de pelvis", "A los 11 meses la eco ya no sirve.", False)],
         img_pie="Esquema: cadera izquierda luxada.",
         veredicto=("Podálica + Galeazzi + pliegues asimétricos = displasia de cadera", "Rx de pelvis y tratamiento ortopédico.")),
  triada=TR([("Mujer", "Sí", True), ("Presentación podálica", "Sí", True), ("Primogénita o antecedente familiar", "No se informa", False)],
            [("Factores de riesgo de displasia", 0, 2)], "Ortolani y Barlow solo sirven en los primeros 3 meses."))

# END-052 · Neuropatía diabética dolorosa: gabapentina · PIRÁMIDE
S("piramide", "END-052", "Diabética con dolor y parestesias en las piernas y pérdida de sensibilidad: neuropatía diabética dolorosa, tratar con gabapentinoides (gabapentina o pregabalina)",
  "Diabetes · neuropatía periférica",
  ("Neuropatía diabética dolorosa", ["Polineuropatía distal simétrica «en guante y calcetín»: dolor quemante, parestesias y pérdida de sensibilidad (riesgo de pie diabético).",
                                     "Primera línea: gabapentinoides, duloxetina o amitriptilina; los opioides quedan al final."]),
  ("Mujer de 50 años con DM2 de 15 años", ["Mal control metabólico.", "1 año de dolor y parestesias en piernas; pérdida de sensibilidad al dolor."]),
  ["Gabapentina 300 mg/noche y subir (hasta 1800-3600 mg/día) o pregabalina; ajustar por función renal.",
   "Mejorar el control glucémico (frena la progresión, no quita el dolor).",
   "Examen anual de pies con monofilamento; educación para el cuidado del pie."],
  ADA + "; AAN, neuropatía diabética dolorosa (2022).",
  op=("¿Medicamento?", ["No: es para el déficit de B1", "Sí: primera línea", "No: opioide de último escalón", "No: no trata el dolor neuropático", "No: no trata el dolor"]),
  d=dict(rotulo="Escalones del dolor neuropático diabético", caso=0, tag="ESTE CASO", ancho=400,
         niveles=[("1.ª", "Gabapentina o pregabalina", "O duloxetina o amitriptilina."),
                  ("2.ª", "Combinar dos de primera línea", "Si el alivio es parcial."),
                  ("3.ª", "Tramadol o tapentadol", "Corto plazo; riesgo de dependencia."),
                  ("Local", "Capsaicina 8 % o lidocaína tópica", "Dolor localizado.")],
         pie="Empezar por arriba",
         veredicto=("Gabapentina (o pregabalina, duloxetina)", "Además: control de la glucosa y cuidado de los pies.")))

# GIN-182 · Trabajo de parto pretérmino establecido · REGLA
S("regla", "GIN-182", "Gestante de 28 semanas con contracciones regulares, 4 cm de dilatación y 80 % de borramiento: trabajo de parto pretérmino establecido",
  "Parto pretérmino",
  ("Trabajo de parto pretérmino", ["Contracciones regulares + cambios cervicales: dilatación ≥ 3 cm o borramiento ≥ 80 % entre las 22 y 36+6 semanas.",
                                   "Con menos cambios es amenaza; sin cambios, falso trabajo de parto."]),
  ("Segundigesta de 28 semanas", ["Contracciones desde hace 12 h: 2 en 10 min, 30 s; hijo previo pretérmino por cesárea.", "Dilatación 4 cm, borramiento 80 %."]),
  ["Corticoide (betametasona) y sulfato de magnesio (neuroprotección, < 32 semanas).",
   "Tocólisis solo para completar el corticoide si no hay contraindicación; antibiótico para estreptococo B si no hay cultivo.",
   "Referir a un centro con UCI neonatal; vía del parto según obstetricia (cesárea previa)."],
  ACOG + " n.º 171 (2016; act.); FIGO (2021); " + MINSA + ".",
  op=("¿Diagnóstico?", ["No: hay cambios cervicales", "Sí: 4 cm y 80 %", "No: cambios ya avanzados", "No: no es indolora ni aislada", "No: 28 semanas"]),
  d=dict(rotulo="El cuello decide: ¿amenaza o trabajo de parto?",
         reglas=[dict(nombre="Dilatación (cm)", que="≥ 3 cm con contracciones = trabajo de parto pretérmino.",
                      min=0, max=10, fmt="{}", ticks=[3],
                      bandas=[(0, 3, "Amenaza", 2), (3, 10, "Trabajo de parto", 3)], caso=4, caso_txt="ESTE CASO: 4 cm"),
                 dict(nombre="Borramiento (%)", que="≥ 80 % también lo define.",
                      min=0, max=100, fmt="{}", ticks=[80],
                      bandas=[(0, 80, "Amenaza", 2), (80, 100, "Trabajo de parto", 3)], caso=80, caso_txt="80 %")],
         claves_titulo="Qué hacer a las 28 semanas",
         claves=[("Corticoide", ["Betametasona"], True), ("Sulfato de magnesio", ["Neuroprotección < 32 sem"], True),
                 ("Centro con UCI neonatal", ["Referir"], False)]))

# GAS-062 · Cáncer gástrico avanzado con ganglio de Virchow · MAPA DE SIGNOS
S("mapa_signos", "GAS-062", "Varón con saciedad precoz, baja de peso, anemia microcítica, ascitis y ganglio supraclavicular izquierdo pétreo (Virchow): cáncer gástrico avanzado, endoscopia con biopsia",
  "Cáncer gástrico",
  ("Cáncer gástrico avanzado", ["Síntomas de alarma: baja de peso, saciedad precoz, anemia ferropénica, vómitos, disfagia, sangrado.",
                                "Signos de diseminación: ganglio de Virchow, nódulo umbilical (hermana María José), ascitis (carcinomatosis), Krukenberg, tacto rectal con «repisa» de Blumer."]),
  ("Varón de 65 años, 8 semanas", ["Llenura precoz, baja de peso, distensión abdominal.", "Pálido, ganglio supraclavicular izquierdo pétreo, ascitis; anemia microcítica."]),
  ["Endoscopia digestiva alta con biopsias múltiples: confirma el tumor primario (adenocarcinoma).",
   "Luego TC de tórax, abdomen y pelvis para estadificar (y citología del líquido ascítico).",
   "Estadio IV: quimioterapia paliativa y soporte nutricional."],
  "NCCN, cáncer gástrico (2026); ESMO (2022).",
  op=("¿Examen para el diagnóstico?", ["Confirma metástasis, no el origen", "Solo citología, no el tumor", "Sí: ve el tumor y toma biopsia", "No: no es el colon", "No: no estudia el estómago"]),
  d=dict(rotulo="Los signos del paciente", PH=500, tag="CONFIRMAR",
         ilu_titulo="El paciente del caso",
         ilu=lambda s, x, y: I.cuerpo(s, x + 39, y + 4, {"abdomen": "#fef3c7"},
                                      marcas=[(1, 148, 72), (2, 120, 140), (3, 120, 185), (4, 120, 30)], sc=0.9),
         ilu_pie="1 ganglio supraclavicular izquierdo, 2 estómago, 3 abdomen con ascitis, 4 palidez.",
         signos=[dict(tit="Ganglio de Virchow (supraclavicular izquierdo)", lines=["Pétreo: metástasis por el conducto torácico."]),
                 dict(tit="Llenura precoz y baja de peso", lines=["Tumor que ocupa el estómago."]),
                 dict(tit="Ascitis (signo de la oleada)", lines=["Carcinomatosis peritoneal."]),
                 dict(tit="Palidez con anemia microcítica", lines=["Sangrado crónico del tumor."]),
                 dict(tit="Endoscopia digestiva alta con biopsia", on=True, lines=["Confirma el cáncer gástrico; luego TC para estadificar."])]),
  triada=TR([("Ganglio de Virchow", "Sí", True), ("Nódulo de la hermana María José (ombligo)", "No se describe", False),
             ("Ascitis por carcinomatosis", "Sí", True), ("Tumor de Krukenberg (ovario)", "Varón: no aplica", False)],
            [("Signos de diseminación del cáncer gástrico", 0, 3)], "Con Virchow y ascitis ya es estadio IV."))

# TRA-041 · Artritis séptica en el adolescente · DECISIÓN
S("decision", "TRA-041", "Adolescente con fiebre, monoartritis aguda de rodilla y leucocitosis con desviación izquierda: artritis séptica, el germen más probable es Staphylococcus aureus",
  "Artritis séptica",
  ("Artritis séptica", ["Infección de la articulación: dolor intenso, no apoya, rodilla caliente y roja, fiebre. Urgencia: el cartílago se destruye en días.",
                        "S. aureus es el germen más frecuente a cualquier edad; en adolescentes sexualmente activos pensar también en gonococo."]),
  ("Varón de 13 años, 3 días", ["Dolor en la rodilla derecha que impide caminar; fiebre 38,5 °C.", "Rodilla aumentada de volumen con signos inflamatorios; leucocitos 25 000, 10 % abastonados."]),
  ["Artrocentesis antes del antibiótico: > 50 000 leucocitos con > 90 % neutrófilos, Gram y cultivo; hemocultivos.",
   "Antibiótico EV empírico: cefazolina u oxacilina (± vancomicina si hay SARM en la comunidad).",
   "Lavado articular (artroscopía o artrotomía)."],
  "IDSA/PIDS, artritis séptica pediátrica (2023); " + NELSON + ".",
  op=("¿Germen?", ["Sí: el más frecuente", "No: neonatos y adultos mayores", "No: no causa artritis séptica habitual", "No: raro desde la vacuna Hib", "No: poco frecuente en articulaciones"],
      {2: "Corynebacterium (Arcanobacterium) pyogenes"}),
  d=dict(rotulo="Germen de la artritis séptica según la edad", eje_y="Edad", ancho_filas=180,
         cols=["Germen más frecuente", "Además pensar en"],
         rows=[("Neonato", "< 3 meses"), ("Niño y adolescente", "Este caso"), ("Joven sexualmente activo", "")],
         cells=[[("S. aureus, estreptococo B", ["Y gramnegativos"]), ("Candida", ["En UCI neonatal"])],
                [("STAPHYLOCOCCUS AUREUS", ["Cefazolina u oxacilina"]), ("Kingella (< 4 años), S. pyogenes", [])],
                [("S. aureus", ["Sigue siendo el primero"]), ("Gonococo", ["Ceftriaxona"])]],
         caso=(1, 0), nota="Haemophilus casi desapareció con la vacuna."))

# GIN-183 · Sangrado del tercer trimestre: evitar el tacto · ALARMA + esquema
S("alarma", "GIN-183", "Gestante de 33 semanas con cesárea previa, sangrado indoloro y presentación flotante: sospecha de placenta previa, se debe evitar el tacto vaginal",
  "Hemorragias del tercer trimestre",
  ("Placenta previa", ["La placenta cubre o está cerca del orificio cervical: sangrado rojo, indoloro, sin contracciones; la presentación queda alta.",
                       "El tacto vaginal puede desprenderla y causar una hemorragia masiva: se confirma con ecografía."]),
  ("Gestante de 33 semanas sin control prenatal", ["Sangrado vaginal sin otras molestias; cesárea hace 3 años.", "PA 100/60, AU 30 cm, LCF 130, presentación flotante, sin contracciones."]),
  ["Ecografía (la transvaginal cuidadosa es segura y la más exacta).",
   "Hospitalizar, vía EV, grupo y Rh, corticoide (< 34 semanas) y reserva de sangre.",
   "Con cesárea previa: buscar acretismo (eco Doppler o RM)."],
  ACOG + "; RCOG Green-top n.º 27a (2018); " + MINSA + ".",
  op=("¿Qué evitar?", ["No: es la que confirma", "Sí: puede desencadenar hemorragia", "No: cuidadosa, es segura", "No: segura y más exacta", "No: necesario"]),
  d=dict(rotulo="Pistas de placenta previa", lista_titulo="Lo que tiene esta gestante",
         signos=[("Sangrado rojo indoloro", "Sin otras molestias", True), ("Sin contracciones", "No se constatan", True),
                 ("Presentación alta o flotante", "Flotante", True), ("Cesárea previa", "Hace 3 años", True),
                 ("Útero duro y doloroso", "No: eso sería desprendimiento", False)],
         img=P("placenta_previa.jpg", 300, 154, [], credito="BruceBlaus" + CC + "CC BY-SA 4.0", fondo="#ffffff"), img_titulo="Placenta previa",
         accion=("NO hacer tacto vaginal", "Confirmar con ecografía y hospitalizar."),
         accion_rotulo="CON SOSPECHA DE PREVIA",
         veredicto=("Sangrado indoloro + presentación alta = placenta previa hasta descartarla", "Nada de tacto vaginal hasta tener la ecografía.")))

# OFT-040 · Epistaxis posterior: taponamiento posterior · ÁRBOL + foto
S("arbol", "OFT-040", "Anciano con epistaxis severa que sangra por la fosa nasal y por la boca: epistaxis posterior, taponamiento posterior",
  "Epistaxis",
  ("Epistaxis anterior y posterior", ["Anterior (90 %): plexo de Kiesselbach, en niños y jóvenes; se controla con presión y taponamiento anterior.",
                                      "Posterior: arteria esfenopalatina, en ancianos e hipertensos; sangra hacia la faringe (sale por la boca) y es más grave."]),
  ("Varón de 83 años", ["Sangrado nasal severo; signos vitales estables, palidez leve.", "Sangra por la fosa derecha y por la boca."]),
  ["Taponamiento posterior con sonda de Foley o balón doble + taponamiento anterior; hospitalizar y vigilar la vía aérea.",
   "Controlar la PA, revisar anticoagulantes, hemograma.",
   "Si no cede: ligadura o embolización de la arteria esfenopalatina."],
  "AAO-HNS, epistaxis (2020).",
  op=("¿Procedimiento?", ["Sí: sangrado posterior", "No: no alcanza el sangrado posterior", "No: para sangrado anterior visible", "No: para el sangrado anterior", "No: no controla el sangrado"]),
  arbol=Q("Epistaxis: ¿de dónde sangra?", [
      L("Posterior: sale por la boca, anciano (este caso)", "TAPONAMIENTO POSTERIOR", ["Sonda de Foley o balón", "Hospitalizar"], path=True),
      L("Anterior: punto visible", "Presión 10-15 min", ["Cauterizar o taponamiento anterior"])], path=True),
  triada=TR([("Edad avanzada", "83 años", True), ("Sangre hacia la boca", "Sí", True), ("Sin punto sangrante anterior visible", "Fosa derecha con sangrado", True)],
            [("Pistas de epistaxis posterior", 0, 2)], "La anterior (Kiesselbach) es la más frecuente y la de niños y jóvenes."))
