"""Entrega 3 · tanda t13 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
GORDIS = "Gordis, Epidemiología 6.ª ed."
SABISTON = "Sabiston Tratado de Cirugía 21.ª ed."

# PED-182 · Gastroenteritis aguda en el lactante: rotavirus · TARJETAS
S("tarjetas", "PED-182", "Lactante de 6 meses con diarrea acuosa abundante y vómitos de inicio brusco, sin fiebre ni sangre, y deshidratación: gastroenteritis por rotavirus",
  "Enfermedad diarreica aguda · etiología viral",
  ("Rotavirus", ["Principal causa de diarrea grave con deshidratación en menores de 2 años (sobre todo en no vacunados).",
                 "Vómitos que preceden o acompañan a una diarrea acuosa abundante, sin moco ni sangre; fiebre baja o ausente."]),
  ("Lactante de 6 meses, 8 horas", ["6 deposiciones líquidas y 2 vómitos; lactancia materna exclusiva.", "Peso 7 kg (antes 8,1 kg), irritable, labios secos, ojos hundidos, afebril."]),
  ["Bajó 1,1 kg de 8,1 kg (≈ 13 %): por peso la deshidratación es importante; evaluar plan B o C según los signos.",
   "SRO de baja osmolaridad, continuar la lactancia, zinc; sin antibióticos.",
   "Prevención: vacuna contra rotavirus a los 2 y 4 meses."],
  OMS + ", tratamiento de la diarrea (2005; act.); " + MINSA + ", guía de EDA en niños (2017).",
  op=("¿Agente?", ["No: diarrea crónica, grasosa", "No: disentería con fiebre", "Sí: acuosa con vómitos en lactante", "No: disentería", "No: diarrea con sangre, sin fiebre, SHU"]),
  d=dict(rotulo="Diarrea en el lactante: ¿quién la causa?", ans=0,
         cards=[dict(titulo="Rotavirus", datos=[("Edad", "6-24 meses", True), ("Heces", "Acuosas, abundantes", True), ("Clave", "Vómitos + deshidratación", True)], pie="Este caso."),
                dict(titulo="Shigella / Campylobacter", datos=[("Heces", "Moco y sangre", False), ("Fiebre", "Alta", False), ("Trata", "Antibiótico", False)], pie="Disentería."),
                dict(titulo="E. coli enterohemorrágica", datos=[("Heces", "Sangre", False), ("Fiebre", "Poca o nada", False), ("Riesgo", "SHU", False)], pie="No dar antibiótico."),
                dict(titulo="Giardia", datos=[("Curso", "Crónico", False), ("Heces", "Grasosas, fétidas", False), ("Trata", "Metronidazol", False)], pie="Malabsorción.")]))

# GAS-064 · Criterios de Ranson · PUNTAJE + TC
S("puntaje", "GAS-064", "Alcohólico de 60 años con pancreatitis aguda: de los criterios de Ranson al ingreso solo cumple la edad (> 55 años)",
  "Pancreatitis aguda · pronóstico",
  ("Criterios de Ranson", ["Al ingreso (no biliar): edad > 55, leucocitos > 16 000, glucosa > 200, LDH > 350, AST > 250.",
                           "A las 48 h: caída del Hto > 10 %, BUN ↑ > 5, Ca < 8, PaO₂ < 60, déficit de base > 4, secuestro de líquidos > 6 L. ≥ 3 = grave."]),
  ("Varón de 60 años, alcohólico", ["Dolor en faja de 24 h; amilasa y lipasa altas.", "Leucocitos 11 000, AST 100, bilirrubina 2."]),
  ["Hoy se prefieren BISAP y la clasificación de Atlanta (falla orgánica > 48 h = grave).",
   "La lipasa y la amilasa confirman, pero su nivel no indica gravedad.",
   "Tratamiento: Ringer lactato moderado, analgesia, nutrición enteral temprana."],
  "Ranson (1974); Atlanta revisada (2012); ACG, pancreatitis aguda (2024).",
  op=("¿Indicador de Ranson presente?", ["No: 11 000 < 16 000", "Sí: > 55 años", "No: no es parte de Ranson", "No: 100 < 250", "No: no mide gravedad"]),
  d=dict(rotulo="Ranson al ingreso, punto por punto", escala="Ranson (ingreso, no biliar)", total=1, max=5,
         interpreta="< 3: pancreatitis leve por Ranson",
         items=[("Edad > 55 años (tiene 60)", 1, True), ("Leucocitos > 16 000 (tiene 11 000)", 1, False),
                ("Glucosa > 200 mg/dL (no informada)", 1, False), ("LDH > 350 UI/L (no informada)", 1, False), ("AST > 250 UI/L (tiene 100)", 1, False)],
         bandas=[("0-2", "Leve", "Mortalidad < 1-3 %.", True), ("3-5", "Grave", "Mortalidad ~15 %.", False),
                 ("≥ 6", "Muy grave", "Mortalidad > 40 % (con criterios de 48 h).", False)]),
  banda=B("Así se ve la pancreatitis en la TC", P("pancreatitis_tc.jpg", 300, 234, [], credito="Hellerhoff" + CC + "CC BY-SA 3.0"),
          [("Páncreas aumentado", "Con líquido alrededor."), ("TC solo si hay duda o a las 72 h", "Para buscar necrosis."),
           ("Bilirrubina", "No es criterio de Ranson.")],
          pie="Pancreatitis aguda"))

# SP-136 · Esterilización en incapacidad mental · CHECKLIST
S("checklist", "SP-136", "Familiares piden ligar las trompas de una mujer con alteración mental severa: se requiere evaluación psiquiátrica y autorización judicial",
  "Ética y legislación · consentimiento en la incapacidad",
  ("Esterilización de personas sin capacidad de decidir", ["Es un procedimiento irreversible que afecta derechos reproductivos: no basta la voluntad de la familia.",
                                                           "Se necesita demostrar la incapacidad (psiquiatría) y que un juez lo autorice protegiendo el interés de la persona."]),
  ("Mujer en edad reproductiva", ["Alteración mental severa.", "La familia solicita la ligadura de trompas."]),
  ["Evaluar primero métodos reversibles (implante, DIU, inyectable).",
   "Informar a la paciente en la medida de su comprensión y considerar su opinión.",
   "Norma técnica de planificación familiar del MINSA; Código Civil (curatela) y Ley 29973 de la persona con discapacidad."],
  MINSA + ", NTS de planificación familiar (2017; act.); Ley n.º 29973.",
  op=("¿Requisito?", ["No: no basta", "Sí: psiquiatría + juez", "No: la familia no puede decidir sola", "No: falta la autorización judicial", "No: no es capaz de consentir"],
      {1: "Evaluación psiquiátrica + autorización judicial", 2: "Basta la solicitud de la familia"}),
  d=dict(rotulo="Qué se necesita antes de esterilizar", tag="REQUISITO",
         pasos=[("Evaluación psiquiátrica", "Que documente la incapacidad para decidir", True),
                ("Autorización judicial", "Protege los derechos de la paciente", True),
                ("Ofrecer métodos reversibles", "Implante, DIU, inyectable", False),
                ("Informar a la paciente", "Según su capacidad de comprender", False)],
         no_hacer=[("Operar solo por pedido de la familia", "No tienen esa facultad"), ("Solo con una junta médica", "No reemplaza al juez"),
                   ("Hacerla firmar sin capacidad", "El consentimiento no es válido")],
         veredicto=("Psiquiatría + juez", "Es irreversible: necesita resguardo legal.")))

# CIR-101 · Trauma pancreático en el niño · LABORATORIO + esquema
S("laboratorio", "CIR-101", "Niño con dolor abdominal, palidez y náuseas 3 días después de un golpe en el abdomen, con leucocitosis, anemia e hipocalcemia: lesión del páncreas",
  "Trauma abdominal cerrado · páncreas",
  ("Trauma pancreático", ["El páncreas queda contra la columna: un golpe en el epigastrio (manubrio, codo, balón) lo aplasta.",
                          "Se manifiesta tarde (horas-días) como pancreatitis traumática: dolor, vómitos, hipocalcemia (saponificación de la grasa)."]),
  ("Niño de 12 años", ["Golpe jugando básquet hace 3 días; dolor abdominal agudo, palidez y náuseas.", "Leucocitos 18 000, Hb 10, calcio 6."]),
  ["Amilasa y lipasa (pueden estar normales al inicio) y TC con contraste: ve la lesión y el conducto pancreático.",
   "Sin lesión del conducto: manejo conservador; con sección del conducto: CPRE con prótesis o cirugía.",
   "Complicación tardía frecuente: seudoquiste."],
  "APSA, trauma pancreático pediátrico (2019); " + SABISTON + ".",
  op=("¿Órgano?", ["No: no explica la hipocalcemia", "No: no explica la hipocalcemia", "No: daría peritonitis", "Sí: hipocalcemia de pancreatitis", "No: daría hematuria"]),
  d=dict(rotulo="Qué dice el laboratorio",
         valores=[("Calcio", "6 mg/dL", "8,5-10,5", "↓", "Se consume en la necrosis de la grasa (saponificación): pancreatitis."),
                  ("Leucocitos", "18 000", "5000-12 000", "↑", "Inflamación."),
                  ("Hemoglobina", "10 g/dL", "12-14", "↓", "Sangrado o hemodilución."),
                  ("Amilasa y lipasa", "Por pedir", "Normales", "=", "Suben en la lesión pancreática (pueden tardar)."),
                  ("TC con contraste", "Por pedir", "—", "=", "Muestra la lesión y si hay sección del conducto.")],
         veredicto=("Golpe epigástrico + hipocalcemia = páncreas", "Pancreatitis traumática; TC con contraste.")),
  banda=B("Dónde está el páncreas", D(lambda s, x, y: I.abdomen(s, x, y, on={"pancreas"}, sc=0.8), 264, 260),
          [("Detrás del estómago", "Cruza delante de la columna."), ("Golpe en el epigastrio", "Lo aplasta contra la columna."),
           ("Síntomas tardíos", "Por eso aparece días después.")],
          pie="Páncreas delante de la columna"))

# CIR-102 · Apendicitis en la mujer joven: ecografía · ÁRBOL + Alvarado + eco
S("arbol", "CIR-102", "Mujer de 30 años con 18 horas de dolor en fosa ilíaca derecha, fiebre, vómitos y leucocitosis con desviación: sospecha de apendicitis, pedir ecografía",
  "Abdomen agudo · apendicitis",
  ("Imagen en la sospecha de apendicitis", ["En la mujer en edad fértil hay que descartar causas ginecológicas (ectópico, quiste, EPI): la ecografía abdominal y pélvica es el primer estudio.",
                                            "Si la eco no es concluyente: TC (o RM en la gestante)."]),
  ("Mujer de 30 años, 18 horas", ["Dolor en FID, náuseas, vómitos; T 38 °C, FC 100.", "Leucocitos 12 000, 8 % abastonados."]),
  ["Prueba de embarazo (beta-hCG) siempre en la mujer en edad fértil.",
   "Apéndice > 6 mm, no compresible, con grasa inflamada: apendicitis.",
   "Tratamiento: apendicectomía laparoscópica + antibiótico."],
  "WSES, guía de Jerusalén de apendicitis (2020); ACR Appropriateness Criteria (2022).",
  op=("¿Estudio?", ["No: invasiva", "No: poco útil", "Sí: ve apéndice y pelvis, sin radiación", "No: no aplica", "No: contraindicada"]),
  arbol=Q("Mujer en edad fértil con dolor en FID: ¿qué imagen?", [
      L("Primero (este caso)", "ECOGRAFÍA ABDOMINAL Y PÉLVICA", ["+ beta-hCG", "Apéndice y anexos"], path=True),
      L("Eco no concluyente", "TC con contraste", ["RM si está gestando"])], path=True),
  escala=dict(nombre="Escala de Alvarado", modo="puntaje", que="Probabilidad de apendicitis (máximo 10).",
              items=[("Migración", "Dolor que migra a FID (1)", "No se informa", None), ("Anorexia", "Anorexia (1)", "No se informa", None),
                     ("Náuseas", "Náuseas o vómitos (1)", "Sí", 1), ("FID", "Dolor en FID (2)", "Sí", 2), ("Rebote", "Rebote (1)", "No se informa", None),
                     ("Fiebre", "T > 37,3 °C (1)", "38 °C", 1), ("Leuco", "Leucocitos > 10 000 (2)", "12 000", 2), ("Desv.", "Desviación izquierda (1)", "8 % abastonados", 1)],
              total_txt="Total: ≥ 7 con lo informado", total_nota="máximo 10",
              rangos=[("0-4", "Poco probable", "Observar"), ("5-6", "Posible", "Imagen"), ("7-10", "Probable", "Cirugía + imagen en la mujer")],
              caso_rango=2, porque=[("Ya suma 7 sin contar los datos que faltan", True)],
              conducta="Ecografía para confirmar y descartar causa ginecológica."),
  banda=B("Así se ve la apendicitis en la eco", P("apendicitis_eco.jpg", 300, 259, [], credito="Borbély Márton" + CC + "CC BY-SA 4.0"),
          [("Apéndice engrosado", "> 6 mm, no se comprime."), ("Grasa alrededor brillante", "Inflamación."),
           ("Sin radiación", "Ideal en mujeres jóvenes y gestantes.")],
          pie="Apendicitis aguda"))

# CIR-103 · Insuficiencia venosa crónica: compresión · TERMÓMETRO (CEAP)
S("termometro", "CIR-103", "Mujer de 65 años con pesadez, prurito y ardor vespertino en las piernas y várices que aumentan de pie: insuficiencia venosa crónica, terapia compresiva",
  "Insuficiencia venosa crónica",
  ("Insuficiencia venosa crónica", ["Las válvulas venosas fallan: la sangre se acumula en las piernas (hipertensión venosa).",
                                    "Pesadez y dolor que empeoran de pie y al final del día; várices, edema, cambios de piel y úlceras. Se gradúa con CEAP."]),
  ("Mujer de 65 años, 5 meses", ["Pesadez y prurito vespertinos; ardor que le impide caminar.", "Várices en la cara interna de ambas piernas que aumentan de pie; Perthes (+)."]),
  ["Medias de compresión graduada (20-30 o 30-40 mmHg) + elevar las piernas, caminar, bajar de peso.",
   "Eco Doppler venoso: reflujo de safena y estado del sistema profundo (Perthes + sugiere obstrucción o insuficiencia profunda).",
   "Ablación endovenosa o cirugía de la safena si hay reflujo y síntomas pese a la compresión (no de emergencia)."],
  "ESVS, enfermedad venosa crónica (2022); SVS/AVF (2023).",
  op=("¿Tratamiento?", ["No: no hay trombosis aguda", "Ayudan, pero no bastan", "Sí: base del tratamiento", "No: para várices pequeñas tras estudio", "No: no es una emergencia"]),
  d=dict(rotulo="Clasificación CEAP (clínica)", caso_nivel=1, ruta_titulo="Qué hacer en este caso", paso_label="ESTE CASO",
         niveles=[("C1", "Telangiectasias", ["Arañas vasculares"]), ("C2", "Várices", ["≥ 3 mm, aumentan de pie"]),
                  ("C3", "Edema", ["Por la tarde"]), ("C4", "Cambios de piel", ["Pigmentación, eccema"]), ("C5-C6", "Úlcera", ["Cicatrizada o activa"])],
         pasos=[(1, "Eco Doppler venoso", ["Reflujo y sistema profundo"], False),
                (2, "Terapia compresiva", ["Medias 20-30 mmHg + elevar"], True),
                (3, "Ablación o cirugía", ["Si persisten los síntomas"], False)]))

# GIN-187 · Lupus y embarazo: 6 meses inactiva · RELOJ
S("reloj", "GIN-187", "Paciente con lupus que desea embarazarse: debe tener al menos 6 meses de enfermedad inactiva antes de concebir (manteniendo hidroxicloroquina)",
  "Lupus y embarazo · consulta preconcepcional",
  ("Lupus y embarazo", ["Embarazarse con el lupus activo aumenta brotes, preeclampsia, pérdida fetal y parto pretérmino.",
                        "Se recomienda planificar con ≥ 6 meses de enfermedad inactiva y fármacos compatibles."]),
  ("Paciente con LES en tratamiento", ["Sin complicaciones sistémicas.", "Consulta preconcepcional: desea embarazarse."]),
  ["Mantener la hidroxicloroquina (reduce brotes y bloqueo cardíaco congénito).",
   "Cambiar micofenolato, metotrexato o ciclofosfamida por azatioprina meses antes; prednisona a la menor dosis.",
   "Pedir anti-Ro/La y antifosfolípidos; aspirina a dosis baja desde las 12 semanas."],
  "EULAR, salud reproductiva en enfermedades reumáticas (2017; act. 2024); ACR (2020).",
  op=("¿Recomendación?", ["Sí: ≥ 6 meses inactiva", "No: debe mantenerse", "No: no se sube sin brote", "No: puede embarazarse si planifica", "No: riesgo de brote"]),
  d=dict(rotulo="Plan para embarazarse con lupus", tag="CLAVE",
         pasos=[("−6 m", "Lupus inactivo", "Al menos 6 meses sin actividad", True), ("−3 m", "Cambiar fármacos", "Azatioprina en vez de micofenolato o MTX", False),
                ("Siempre", "Hidroxicloroquina", "No suspender", False), ("Antes", "Anticuerpos", "Anti-Ro/La y antifosfolípidos", False),
                ("12 sem", "Aspirina", "Prevención de preeclampsia", False), ("Gesta", "Control conjunto", "Reumatología + alto riesgo obstétrico", False)],
         veredicto=("Seis meses de enfermedad inactiva", "Con hidroxicloroquina y fármacos compatibles con el embarazo.")))

# SP-137 · Riesgo relativo igual a 1 · REGLA
S("regla", "SP-137", "Un riesgo relativo igual a 1 significa que no hay asociación entre el factor y la enfermedad",
  "Epidemiología · riesgo relativo",
  ("Riesgo relativo (RR)", ["RR = incidencia en expuestos ÷ incidencia en no expuestos (estudios de cohortes).",
                            "RR = 1: el riesgo es igual en ambos grupos (sin asociación). > 1: factor de riesgo. < 1: factor protector."]),
  ("Pregunta de teoría", ["El riesgo relativo resultó igual a 1.", "¿Qué se concluye?"]),
  ["Mirar el intervalo de confianza del 95 %: si incluye el 1, la asociación no es significativa.",
   "Asociación no es causalidad: se necesitan criterios de Bradford Hill.",
   "En casos y controles se usa el odds ratio (OR), que se interpreta igual."],
  GORDIS + ".",
  op=("¿Conclusión?", ["Sí: riesgos iguales", "No: sería < 1", "No: sería > 1", "No: sería > 1", "No: ni siquiera hay asociación"]),
  d=dict(rotulo="Dónde cae un RR de 1",
         reglas=[dict(nombre="Riesgo relativo", que="Compara el riesgo de los expuestos con el de los no expuestos.",
                      min=0, max=3, fmt="{}", ticks=[1],
                      bandas=[(0, 0.95, "< 1: protector", 1), (0.95, 1.05, "1", 0), (1.05, 3, "> 1: factor de riesgo", 3)],
                      caso=1, caso_txt="ESTE CASO: RR = 1")],
         claves_titulo="Cómo se lee",
         claves=[("RR = 1", ["Sin asociación"], True), ("RR = 2", ["El doble de riesgo"], False), ("RR = 0,5", ["La mitad: protege"], False)]))

# END-054 · Coma mixedematoso posoperatorio · ALARMA
S("alarma", "END-054", "Anciana estuporosa tras una cirugía, con cicatriz de tiroidectomía, hipotermia de 32 °C, hipoventilación e hiponatremia: coma mixedematoso",
  "Hipotiroidismo · coma mixedematoso",
  ("Coma mixedematoso", ["Hipotiroidismo grave descompensado (cirugía, infección, frío, sedantes): alteración de conciencia, hipotermia, hipoventilación, hiponatremia, bradicardia.",
                         "Mortalidad 25-50 %: se trata sin esperar el resultado de la TSH."]),
  ("Mujer de 76 años, posoperada", ["Sigue estuporosa tras cirugía sin incidentes; en ventilación mecánica por insuficiencia respiratoria.", "Cicatriz en la base del cuello, T 32 °C, Na 127."]),
  ["Hidrocortisona 100 mg EV c/8 h primero (puede haber insuficiencia suprarrenal) y levotiroxina EV 200-400 µg de carga.",
   "Recalentamiento pasivo, soporte ventilatorio, corregir la hiponatremia con cuidado.",
   "Pedir TSH, T4 libre y cortisol antes de tratar."],
  "ATA, hipotiroidismo (2014; act.); " + HARRISON + ".",
  op=("¿Sospecha?", ["Sí: tiroidectomía + hipotermia + hiponatremia + estupor", "No: 127 no explica la hipotermia", "No: no hubo hipoxia", "No: sin focalización",
                     "No: no hay hiperglucemia"],
      {0: "Coma mixedematoso"}),
  d=dict(rotulo="Signos de coma mixedematoso", lista_titulo="Lo que tiene esta paciente",
         signos=[("Alteración de conciencia", "Estuporosa", True), ("Hipotermia", "32 °C", True), ("Hipoventilación", "Insuficiencia respiratoria", True),
                 ("Hiponatremia", "Na 127", True), ("Antecedente tiroideo", "Cicatriz de tiroidectomía", True), ("Bradicardia", "No se informa", False)],
         accion=("Hidrocortisona + levotiroxina EV", "Sin esperar la TSH; recalentar y ventilar."),
         accion_rotulo="TRATAR YA",
         veredicto=("Tiroidectomía + hipotermia + estupor = coma mixedematoso", "El desencadenante fue la cirugía.")))

# PED-183 · Invaginación intestinal: enema · ÁRBOL + tríada
S("arbol", "PED-183", "Niño de 3 años con cólicos y vómitos intermitentes, heces en «jalea de grosella» y masa en hipocondrio derecho, sin peritonitis: invaginación intestinal, enema con aire o contraste",
  "Invaginación intestinal",
  ("Invaginación ileocólica", ["El íleon se mete en el colon (a menudo tras una infección viral que agranda las placas de Peyer).",
                               "Sin peritonitis ni perforación, el enema (aire o contraste) confirma y reduce; la ecografía es la mejor prueba para diagnosticar."]),
  ("Niño de 3 años, 2 días", ["Tras un resfrío: dolor y vómitos intermitentes; heces «tipo gelatina rosada».", "Distensión, RHA aumentados, masa de 5 cm en CSD; Rx sin aire en colon izquierdo."]),
  ["Ecografía: signo de la diana (si está disponible, primero).",
   "Enema neumático o hidrostático guiado: diagnostica y reduce (éxito 80-90 %).",
   "Cirugía si falla la reducción o hay peritonitis, perforación o choque."],
  "ACR, criterios de imagen; APSA, invaginación (2021); " + NELSON + ".",
  op=("¿Examen?", ["No: no tiene rol", "Sí: confirma y reduce", "No: lenta, no disponible", "No: radiación, no reduce", "No: no corresponde"]),
  arbol=Q("Sospecha de invaginación: ¿hay peritonitis, perforación o choque?", [
      L("No (este caso)", "ENEMA CON AIRE O CONTRASTE", ["Diagnostica y reduce", "Eco antes si está disponible"], path=True),
      L("Sí", "Cirugía", ["Reducción manual o resección"])], path=True),
  triada=TR([("Dolor cólico intermitente", "Sí", True), ("Masa abdominal en «salchicha»", "5 cm en CSD", True), ("Heces en jalea de grosella", "Gelatina rosada", True)],
            [("Tríada clásica de la invaginación", 0, 2)], "Solo ~20 % tiene la tríada completa; este niño la tiene."),
  banda=B("Así se ve en la ecografía", P("invaginacion_eco.jpg", 300, 261, [], credito="Kalumet" + CC + "CC BY-SA 3.0"),
          [("Signo de la diana", "Intestino dentro de intestino."), ("Sin líquido libre", "Permite intentar el enema."),
           ("Enema", "Empuja el segmento invaginado de vuelta.")],
          pie="Invaginación intestinal"))

# CB-072 · Intoxicación por metanol · CUADRÍCULA
S("cuadricula", "CB-072", "Bebedor con vómitos, visión borrosa, somnolencia, taquipnea y acidosis metabólica con anión gap alto: intoxicación por metanol",
  "Toxicología · alcoholes tóxicos",
  ("Metanol", ["Alcohol adulterado: se metaboliza a ácido fórmico, que daña la retina y el nervio óptico (visión «en nieve», ceguera) y causa acidosis grave.",
               "Acidosis con anión gap alto y gap osmolar alto al inicio."]),
  ("Diabético de 68 años, bebedor", ["Mareos, vómitos, visión borrosa («ve bultos»), somnoliento.", "FR 35, FC 115, PA 90/60; acidosis metabólica con anión gap elevado."]),
  ["Fomepizol (o etanol si no hay) para bloquear la alcohol deshidrogenasa.",
   "Bicarbonato si pH < 7,3; ácido fólico (ayuda a eliminar el fórmico).",
   "Hemodiálisis si hay alteración visual, acidosis grave o falla renal."],
  "Goldfrank, toxicología 11.ª ed.; EXTRIP, metanol (2015).",
  op=("¿Diagnóstico?", ["Sí: visión + acidosis con gap alto", "No: no se describe hiperglucemia ni cetonas", "Posible en diabéticos, pero no explica la visión",
                        "No explica la visión", "No: daña el riñón, no la retina"]),
  d=dict(rotulo="Acidosis con anión gap alto: ¿qué la causa?", alto_img=120,
         celdas=[("Metanol", ["Visión borrosa o ceguera", "Fomepizol + diálisis"], P("metanol_tc.jpg", 300, 417), True),
                 ("Etilenglicol", ["Falla renal, cristales de oxalato", "Fomepizol + diálisis"], P("oxalato.jpg", 330, 236), False),
                 ("Cetoacidosis diabética", ["Glucosa alta, cetonas", "Insulina y líquidos"], D(lambda s, x, y: I.tira_orina(s, x, y, [("Glucosa", "#7c2d12", "+++", True), ("Cetonas", "#7e22ce", "+++", True), ("pH", "#f59e0b", "5", False)], sc=1.0), 230, 120), False),
                 ("Acidosis láctica (metformina)", ["Choque, falla renal, lactato alto", "Diálisis si es grave"], P("metformina.jpg", 330, 140), False)],
         credito="Cristales de oxalato: NASA/JSC · Wikimedia Commons · dominio público" + " · TC: Sandhu et al. · Case Rep Radiol 2026 · PMC13527635 · CC BY 4.0 · Metformina: User:Ash (dominio público)",
         veredicto=("Alcohol + visión borrosa + gap alto = metanol", "Fomepizol y hemodiálisis; ácido fólico.")))

# CB-073 · Ácido sulfhídrico en pozo séptico · TARJETAS
S("tarjetas", "CB-073", "Trabajador que se desmaya limpiando un pozo séptico, con irritación ocular, tos y disnea: intoxicación por ácido sulfhídrico (H₂S)",
  "Toxicología · gases",
  ("Ácido sulfhídrico (H₂S)", ["Gas de la materia orgánica en descomposición (pozos sépticos, desagües, alcantarillas): olor a huevo podrido que deja de percibirse (fatiga olfatoria).",
                               "Irrita ojos y vías respiratorias y, en concentraciones altas, bloquea la citocromo oxidasa: pérdida brusca de conciencia («knockdown»)."]),
  ("Varón de 25 años", ["Hallado desmayado limpiando un pozo séptico.", "Desorientado, disnea, leve cianosis, ojos congestionados, tos; SatO₂ 96 %."]),
  ["Retirar de la fuente (los rescatistas con equipo autónomo), oxígeno al 100 % y soporte.",
   "Vigilar edema pulmonar en las primeras 24-72 h.",
   "Nitritos en casos graves (como en el cianuro); prevención: ventilar y medir gases antes de entrar."],
  "Goldfrank, toxicología 11.ª ed.; NIOSH.",
  op=("¿Agente?", ["No: incendios o industria", "Sí: pozo séptico", "No: combustión en lugar cerrado", "No: industria del vidrio, quemaduras", "No: asfixiante simple, sin irritación"]),
  d=dict(rotulo="Gases tóxicos: ¿dónde y cómo?", ans=0,
         cards=[dict(titulo="Ácido sulfhídrico", datos=[("Dónde", "Pozos, desagües", True), ("Olor", "Huevo podrido", True), ("Además", "Irrita ojos y vías", True)], pie="Este caso."),
                dict(titulo="Monóxido de carbono", datos=[("Dónde", "Braseros, calentadores", False), ("Olor", "Ninguno", False), ("Clave", "SatO₂ falsamente normal", False)], pie="Cefalea grupal."),
                dict(titulo="Cianuro", datos=[("Dónde", "Incendios, minería", False), ("Olor", "Almendras amargas", False), ("Clave", "Lactato muy alto", False)], pie="Hidroxocobalamina."),
                dict(titulo="Metano", datos=[("Dónde", "Minas, biodigestores", False), ("Efecto", "Desplaza el O₂", False), ("Irrita", "No", False)], pie="Asfixiante simple.")]))

# PED-184 · Síndrome nefrótico corticodependiente · DECISIÓN
S("decision", "PED-184", "Niño con síndrome nefrótico por cambios mínimos cuya proteinuria reaparece al bajar la dosis de corticoides: síndrome nefrótico corticodependiente",
  "Síndrome nefrótico · evolución con corticoides",
  ("Evolución con corticoides (IPNA/KDIGO)", ["Corticosensible: remite con prednisona en 4-6 semanas. Corticorresistente: no remite.",
                                                "Corticodependiente: 2 recaídas durante la reducción o en las 2 semanas tras suspender. Recaídas frecuentes: ≥ 2 en 6 meses o ≥ 3 en un año."]),
  ("Escolar de 6 años", ["Síndrome nefrótico por cambios mínimos.", "Al reducir la dosis de corticoides vuelve la proteinuria."]),
  ["Tratar la recaída con prednisona hasta la remisión y luego días alternos.",
   "Ahorradores de corticoides: levamisol, micofenolato, ciclofosfamida, rituximab o anticalcineurínicos.",
   "Vigilar efectos de los corticoides (talla, PA, ojos, huesos)."],
  "IPNA, síndrome nefrótico corticosensible (2023); " + KDIGO + " (2021).",
  op=("¿Diagnóstico?", ["No: definida por número, no por la reducción", "No: término no usado así", "Sí: recae al bajar la dosis", "No: sí respondió al inicio",
                        "No: recae justo al reducir"]),
  d=dict(rotulo="¿Cómo respondió a la prednisona?", eje_y="Remisión inicial", ancho_filas=190,
         cols=["Recae al bajar o ≤ 2 sem de suspender", "Recae más tarde"],
         rows=[("Sí remite", "Corticosensible"), ("No remite en 4-6 sem", "")],
         cells=[[("CORTICODEPENDIENTE", ["Ahorrador de corticoides"]), ("Recaída infrecuente o frecuente", ["Según el número"])],
                [("Corticorresistente", ["Biopsia y genética"]), ("Corticorresistente", [])]],
         caso=(0, 0), nota="Cambios mínimos: la forma más frecuente en niños y la más corticosensible."))

# PED-185 · Osteogénesis imperfecta · RADIAL
S("radial", "PED-185", "Niño con fracturas a repetición, escleróticas azules, huesos largos cortos y arqueados e hipomineralización: osteogénesis imperfecta",
  "Enfermedades óseas hereditarias",
  ("Osteogénesis imperfecta", ["Defecto del colágeno tipo I (COL1A1/COL1A2): huesos frágiles que se fracturan con traumas mínimos.",
                               "Escleróticas azules, dentinogénesis imperfecta, sordera en el adulto, laxitud, talla baja y deformidades."]),
  ("Varón de 3 años", ["Fracturas a repetición.", "Escleróticas azules, huesos largos cortos y arqueados; Rx con hipomineralización."]),
  ["Clasificación de Sillence (I leve a III grave; II letal).",
   "Bifosfonatos (pamidronato, zoledronato) reducen fracturas; enclavado intramedular para deformidades.",
   "Diferencial importante: maltrato infantil (en OI hay escleróticas azules y antecedentes familiares)."],
  NELSON + "; Sillence (clasificación).",
  op=("¿Diagnóstico?", ["No: piel elástica, articulaciones laxas, sin fracturas", "No: talla alta, cristalino luxado", "Sí: fracturas + escleróticas azules",
                        "No: contracturas congénitas", "No: sin escleróticas azules; metáfisis en copa"]),
  d=dict(rotulo="Lo que hace el colágeno I defectuoso", centro="COLÁGENO TIPO I", centro_sub="defectuoso", ans=0,
         items=[("HUESOS FRÁGILES", ["Fracturas con traumas mínimos", "Este caso"]), ("ESCLERÓTICAS AZULES", ["Se transparenta la coroides"]),
                ("DIENTES", ["Dentinogénesis imperfecta"]), ("OÍDO", ["Sordera desde la adolescencia"]), ("HUESOS ARQUEADOS", ["Talla baja"])],
         ruta=["Fracturas a repetición", "Escleróticas azules", "Descartar maltrato", "Osteogénesis imperfecta"]))

# GIN-188 · Translucencia nucal: 11-14 semanas · CRONOLOGÍA
S("cronologia", "GIN-188", "Para tamizar síndrome de Down por ecografía, la translucencia nucal se mide entre las semanas 11 y 14",
  "Tamizaje prenatal de aneuploidías",
  ("Translucencia nucal", ["Líquido detrás de la nuca del feto: aumentada (> 3 mm o > p95) se asocia a trisomías y cardiopatías.",
                           "Solo se puede medir entre las 11 y 13+6 semanas (longitud cráneo-caudal 45-84 mm)."]),
  ("Segundigesta de 8 semanas", ["Hijo previo con síndrome de Down.", "¿Cuándo hacer la ecografía de tamizaje?"]),
  ["Tamizaje combinado del 1.er trimestre: translucencia nucal + PAPP-A + beta-hCG libre + edad (detecta ~90 %).",
   "ADN fetal libre en sangre materna desde las 10 semanas (el más sensible).",
   "Diagnóstico: biopsia de vellosidades (11-14 sem) o amniocentesis (desde las 15-16 sem)."],
  "ISUOG, ecografía de 11-14 semanas (2023); ACOG n.º 226 (2020); FMF.",
  op=("¿Semanas?", ["Sí: ventana de la translucencia nucal", "No: es la ecografía morfológica", "No: muy temprano", "No: ya no se mide", "No: crecimiento fetal"]),
  d=dict(rotulo="Qué se hace y cuándo en el tamizaje prenatal", tag="ESTE CASO",
         ilu_titulo="La gestante",
         ilu=ILU(D(lambda s, x, y: I.gestante(s, x + 100, y, sc=0.6), 330, 270)),
         ilu_pie="Hoy tiene 8 semanas: citar entre las 11 y 14.",
         claves=[("Translucencia nucal", ["11-14 semanas: esta pregunta"], True), ("ADN fetal libre", ["Desde las 10 semanas"], False),
                 ("Diagnóstico", ["Vellosidades 11-14 sem; amniocentesis ≥ 15 sem"], False)],
         eje_titulo="Semanas de gestación", eje=(6, 34), paso=2, marca=12, unidad="sem",
         hitos=[(10, 34, "ADN fetal libre", "desde las 10 semanas", False), (11, 14, "Translucencia nucal", "ventana única", True),
                (11, 14, "Biopsia de vellosidades", "diagnóstica", False), (15, 20, "Amniocentesis", "diagnóstica", False),
                (18, 22, "Ecografía morfológica", "malformaciones", False), (28, 32, "Ecografía de crecimiento", "tercer trimestre", False)]))

# REU-056 · Monoartritis con hiperuricemia: líquido sinovial · LECTURA
S("lectura", "REU-056", "Joven obeso con primera monoartritis aguda de rodilla y ácido úrico de 9: para confirmar gota se estudia el líquido sinovial (cristales de urato)",
  "Gota · diagnóstico",
  ("Diagnóstico de la gota", ["La hiperuricemia no basta (muchos la tienen sin gota y en la crisis el ácido úrico puede ser normal).",
                              "El estándar es ver cristales de urato monosódico en el líquido sinovial: agujas con birrefringencia negativa. Además descarta infección."]),
  ("Varón de 23 años, obeso", ["Primer episodio de rodilla muy inflamada y dolorosa.", "Ácido úrico sérico 9 mg/dL."]),
  ["Artrocentesis: cristales, Gram y cultivo, recuento celular.",
   "Crisis: colchicina, AINE o corticoide; no iniciar ni suspender el alopurinol durante la crisis.",
   "Hipouricemiante (alopurinol) si hay crisis recurrentes, tofos o daño; meta < 6 mg/dL."],
  "ACR, gota (2020); EULAR (2016; act.).",
  op=("¿Examen para confirmar?", ["Sí: cristales en el líquido", "No: normal al inicio", "No: no confirma", "No: apoya, no confirma", "No: clasifica, no diagnostica"]),
  d=dict(rotulo="Lee el líquido sinovial", img_titulo="Cristales de urato con luz polarizada",
         img=P("urato.jpg", 340, 255, credito="Gabriel Caponetti" + CC + "CC BY-SA 3.0"), pines=[(0.55, 0.52), (0.25, 0.35)],
         pasos=[("Agujas finas", "Cristales de urato monosódico.", True),
                ("Amarillas paralelas al eje / azules perpendiculares", "Birrefringencia negativa.", False),
                ("Dentro de neutrófilos", "Fagocitados en la crisis.", False),
                ("Gram y cultivo", "Descartar artritis séptica a la vez.", False)],
         img_pie="Cristales de urato con luz polarizada",
         veredicto=("Cristales en aguja con birrefringencia negativa = gota", "Si fueran romboidales y positivos: seudogota (pirofosfato).")))

# PED-186 · Enterocolitis necrotizante · LECTURA + Bell
S("lectura", "PED-186", "Prematuro de 32 semanas y 1200 g que a los 5 días deja de tolerar, con vómitos, distensión y aire en la pared intestinal: enterocolitis necrotizante",
  "Enterocolitis necrotizante",
  ("Enterocolitis necrotizante", ["Necrosis del intestino del prematuro (inmadurez, isquemia, bacterias, fórmula).",
                                  "Intolerancia, residuo gástrico, distensión, sangre en heces; la neumatosis intestinal (aire en la pared) confirma (Bell II)."]),
  ("RN de 32 semanas, 1200 g, Apgar 3-6", ["A los 5 días: deja de tolerar, leche en el aspirado, vómitos, distensión marcada.", "Rx: asas dilatadas, pared engrosada, aire intramural."]),
  ["Nada por boca, sonda orogástrica abierta, nutrición parenteral.",
   "Antibióticos EV (ampicilina + gentamicina + metronidazol) 7-14 días.",
   "Rx seriadas: neumoperitoneo = perforación → cirugía (Bell III). Prevención: leche materna."],
  "Bell modificado (Walsh y Kliegman); " + NELSON + "; AAP.",
  op=("¿Complicación?", ["Incompleto: hay neumatosis", "No: no da aire en la pared", "Sí: neumatosis en prematuro", "No: doble burbuja desde el 1.er día", "No: no da neumatosis"]),
  d=dict(rotulo="Lee la radiografía", img_titulo="Neumatosis intestinal",
         img=P("nec.jpg", 340, 272, credito="Hellerhoff" + CC + "CC BY-SA 4.0"), pines=[(0.22, 0.72), (0.3, 0.35)],
         pasos=[("Burbujas y líneas de aire en la pared", "Neumatosis intestinal: confirma (Bell II).", True),
                ("Gas en la vena porta (hígado)", "Más grave.", False),
                ("Asas dilatadas", "Íleo.", False),
                ("Buscar neumoperitoneo", "Perforación: cirugía.", False)],
         img_pie="Neumatosis intestinal",
         veredicto=("Prematuro + intolerancia + neumatosis = enterocolitis necrotizante", "Ayuno, sonda, antibióticos y Rx seriadas.")),
  escala=dict(nombre="Estadios de Bell (modificado)", que="Gravedad de la enterocolitis necrotizante.",
              grados=[("I", "Sospecha", ["Intolerancia, distensión", "Rx inespecífica"]), ("II", "Confirmada", ["Neumatosis ± gas portal"]),
                      ("III", "Avanzada", ["Choque, peritonitis", "Neumoperitoneo"])],
              caso=1, porque=[("Aire intramural en la Rx", True), ("Sin neumoperitoneo descrito", True)],
              conducta="Tratamiento médico; cirugía si perfora."))

# INF-091 · Brote por toxina preformada: B. cereus · CRONOLOGÍA
S("cronologia", "INF-091", "Brote escolar de vómitos, dolor abdominal y diarrea acuosa 6 horas después de comer ensalada con mayonesa: toxina preformada, Bacillus cereus",
  "Enfermedades transmitidas por alimentos",
  ("Toxinas preformadas", ["Si los síntomas aparecen en 1-6 horas, la toxina ya estaba en la comida: Staphylococcus aureus o Bacillus cereus (emético, típico del arroz recalentado).",
                           "Con incubación de 8-72 horas: gérmenes que se multiplican en el intestino (C. perfringens, Salmonella, Shigella)."]),
  ("Centro de salud", ["40 escolares con vómito, dolor abdominal y diarrea líquida sin moco ni sangre (algunos con fiebre).", "6 horas después de comer ensalada con mayonesa."]),
  ["Tratamiento de soporte: hidratación; no antibióticos.",
   "Notificar el brote, tomar muestras de alimentos y de los manipuladores.",
   "S. aureus (manipuladores, cremas, mayonesa) es igual de probable con 6 h; el banco elige B. cereus."],
  OMS + ", enfermedades transmitidas por alimentos; " + CDC + ".",
  op=("¿Agente?", ["Sí: toxina preformada (1-6 h)", "No: incubación 1-3 días, disentería", "No: 12-72 h", "No: diarrea profusa, otro contexto", "No: niños pequeños, 1-3 días"]),
  d=dict(rotulo="Tiempo entre comer y enfermar", tag="6 HORAS",
         ilu_titulo="Bacilos grampositivos (esquema)",
         ilu=CON_CREDITO(D(lambda s, x, y: I.gram(s, x + 55, y + 40, "bacilos_pos", sc=1.0), 330, 240)),
         ilu_pie="B. cereus: bacilo grampositivo con esporas.",
         claves=[("1-6 horas", ["Toxina preformada: S. aureus, B. cereus"], True), ("8-16 horas", ["C. perfringens, B. cereus diarreico"], False),
                 ("12-72 horas", ["Salmonella, Shigella, Campylobacter"], False)],
         eje_titulo="Horas desde la comida", eje=(0, 72), paso=8, marca=6, unidad="h", eje_nombre="horas",
         hitos=[(1, 6, "S. aureus / B. cereus emético", "toxina preformada", True), (8, 16, "C. perfringens / B. cereus diarreico", "toxina en el intestino", False),
                (12, 72, "Salmonella", "fiebre, diarrea", False), (24, 72, "Shigella, Campylobacter", "disentería", False)]))

# TRA-043 · Arnés de Pavlik: necrosis avascular · REGLA
S("regla", "TRA-043", "Lactante con displasia de cadera tratada con arnés de Pavlik en abducción excesiva: la complicación es la necrosis avascular de la cabeza femoral",
  "Displasia de cadera · complicaciones del tratamiento",
  ("Arnés de Pavlik", ["Mantiene las caderas en flexión (90-100°) y abducción moderada para que la cabeza femoral se centre.",
                       "Abducción forzada comprime los vasos de la cabeza femoral: necrosis avascular. Flexión excesiva: parálisis del nervio femoral."]),
  ("Lactante de 2 meses", ["Ortolani y Barlow positivos: arnés de Pavlik.", "A las 2 semanas: irritable, abducción excesiva."]),
  ["Ajustar el arnés: abducción dentro de la «zona segura» (sin forzar).",
   "Control con ecografía; si no se reduce en 3-4 semanas, suspender el arnés.",
   "Las otras opciones no ocurren a esta edad (epifisiólisis y sinovitis son de niños mayores)."],
  "AAOS, displasia de cadera (2022); POSNA.",
  op=("¿Hallazgo?", ["Sí: abducción excesiva comprime vasos", "No: adolescentes obesos", "No: adultos", "No: niños de 3-8 años", "Es un riesgo, pero no explica la urgencia"]),
  d=dict(rotulo="La abducción del arnés y la cabeza femoral",
         reglas=[dict(nombre="Abducción de la cadera en el arnés (grados)", que="Abducción moderada y suave; forzarla comprime la irrigación de la cabeza femoral.",
                      min=0, max=90, fmt="{}°", ticks=[30, 60],
                      bandas=[(0, 30, "Insuficiente: se luxa", 2), (30, 60, "Zona segura", 0), (60, 90, "Excesiva: necrosis", 3)],
                      caso=80, caso_txt="ESTE CASO: excesiva")],
         claves_titulo="Complicaciones del arnés",
         claves=[("Necrosis avascular", ["Por abducción forzada"], True), ("Parálisis del nervio femoral", ["Por flexión excesiva"], False),
                 ("Falla en reducir", ["Suspender a las 3-4 semanas"], False)]))

# SP-138 · Casos y controles apareado · ÁRBOL
S("arbol", "SP-138", "Se comparan 30 mujeres con cáncer de mama y 30 sin él, emparejadas, preguntando por su lactancia: estudio de casos y controles (apareado)",
  "Epidemiología · diseños de estudio",
  ("Casos y controles", ["Se parte del desenlace: personas con la enfermedad (casos) y sin ella (controles), y se mira hacia atrás la exposición.",
                         "El apareamiento (edad, raza, paridad…) controla variables de confusión. La medida es el odds ratio."]),
  ("Estudio planteado", ["30 mujeres con cáncer de mama y 30 con mamografía normal.", "Emparejadas; se pregunta por la lactancia materna."]),
  ["Útil en enfermedades raras y de latencia larga; rápido y barato.",
   "Sesgo de memoria y de selección; no calcula incidencia.",
   "Ojo: aparear por la misma exposición estudiada (lactancia) es un error de diseño: anula su efecto."],
  GORDIS + "; Rothman, Epidemiología moderna.",
  op=("¿Diseño?", ["No: parte de la exposición y sigue", "No: mide a la vez, sin grupos por enfermedad", "Sí: parte del desenlace", "No: no asigna intervención", "No: grupos, no personas"]),
  arbol=Q("¿Cómo se eligió a los participantes?", [
      L("Por tener o no la enfermedad (este caso)", "CASOS Y CONTROLES", ["Mira hacia atrás la exposición", "Odds ratio"], path=True),
      L("Por estar o no expuestos", "Cohorte", ["Sigue hacia adelante", "Riesgo relativo"]),
      L("El investigador asigna la exposición", "Experimental", ["Ensayo clínico"]),
      L("Todo medido en un momento", "Transversal", ["Prevalencia"])], path=True))

# TRA-044 · Ganglión poplíteo en la niña · EMBUDO
S("embudo", "TRA-044", "Niña con una masa quística firme, indolora, de 3 cm en la cara posterointerna de la rodilla, sin limitación funcional: quiste benigno (ganglión/quiste poplíteo)",
  "Masas de partes blandas en niños",
  ("Quiste poplíteo en el niño", ["En niños, el quiste poplíteo (de Baker o ganglión) suele ser aislado, sin lesión articular, y desaparece solo en meses o años.",
                                  "Indoloro, quístico (transilumina), sin signos inflamatorios ni limitación: benigno."]),
  ("Niña de 7 años", ["«Bolita» detrás de la rodilla izquierda que no duele ni limita.", "Masa quística firme de 3 cm en la región poplítea interna, sin dolor; resto normal."]),
  ["Ecografía si hay dudas (confirma que es líquido).",
   "Observación: no se opera (recidiva y suele involucionar).",
   "Consultar si crece rápido, duele, es dura o aparece fiebre."],
  "POSNA; " + NELSON + ".",
  op=("¿Qué decir a la madre?", ["Sí: quiste benigno", "No: no hay ganglios en esa zona ni infección", "No: no hay dolor ni fiebre", "No: no es quístico ni frecuente", "No: no duele ni hay edema de pantorrilla"]),
  d=dict(rotulo="Masa detrás de la rodilla: ¿qué es?", inicio="Masa poplítea en una niña",
         candidatos=["Absceso", "Quiste de Baker roto", "Adenomegalia", "Lipoma", "Ganglión / quiste poplíteo"],
         pasos=[("¿Hay dolor, calor, fiebre o edema de la pantorrilla?", ["Absceso", "Quiste de Baker roto"]),
                ("¿Es quística, firme y transilumina?", ["Adenomegalia", "Lipoma"])],
         final=("GANGLIÓN / QUISTE POPLÍTEO", ["Benigno", "Observar"]),
         nota="En niños suele desaparecer solo; no hace falta cirugía."))

# NRL-049 · Neurocisticercosis: Taenia solium · CICLO + TC
S("ciclo", "NRL-049", "Adolescente rural con cefalea recurrente, convulsiones y calcificaciones cerebrales múltiples: neurocisticercosis por Taenia solium",
  "Neurocisticercosis",
  ("Neurocisticercosis", ["La causa más frecuente de epilepsia adquirida en zonas rurales del Perú.",
                          "La persona se infecta al tragar HUEVOS de Taenia solium (heces humanas): las larvas (cisticercos) se alojan en el cerebro."]),
  ("Adolescente de 13 años, zona rural", ["6 meses de cefalea recurrente y 2 convulsiones.", "TC: calcificaciones múltiples."]),
  ["Calcificaciones = quistes muertos: antiepiléptico; los antiparasitarios no sirven en esa fase.",
   "Quistes vivos: albendazol (± praziquantel) + corticoide.",
   "Prevención: tratar al portador de la tenia, higiene, crianza adecuada de cerdos."],
  "IDSA/ASTMH, neurocisticercosis (2017); " + MINSA + ".",
  op=("¿Agente?", ["No: el de la vaca, no da cisticercosis", "No: tenia enana, intestinal", "Sí: cisticerco del cerdo", "No: quistes hidatídicos", "No: anillos con contraste en VIH"]),
  d=dict(rotulo="Ciclo de Taenia solium", tag="ESTE CASO",
         img_titulo="Calcificaciones en la TC", img=P("ncc_tc.jpg", 248, 275, [], credito="I. L. Segamwenge" + CC + "CC BY 4.0"),
         img_pie="Quistes muertos calcificados.",
         centro="Taenia solium", pasos=[("Cerdo con cisticercos", "carne mal cocida"), ("Tenia en el intestino humano", "elimina huevos en las heces"),
                                        ("Huevos ingeridos", "manos o alimentos contaminados"), ("Cisticercos en el cerebro", "convulsiones, cefalea")],
         ans=3,
         claves_titulo="Qué hacer",
         claves=[("Calcificados", ["Antiepiléptico"], True), ("Quistes vivos", ["Albendazol + corticoide"], False),
                 ("Prevención", ["Higiene y control porcino"], False)]))

# NEF-076 · Amiloidosis renal secundaria · CASCADA + histología
S("cascada", "NEF-076", "Varón con 20 años de osteomielitis que desarrolla síndrome nefrótico (proteinuria 7 g/24 h, albúmina 2,1) y falla renal: amiloidosis renal secundaria (AA)",
  "Síndrome nefrótico del adulto · amiloidosis",
  ("Amiloidosis AA", ["Inflamación crónica (osteomielitis, artritis reumatoide, TB, bronquiectasias, fiebre mediterránea) → proteína amiloide A sérica.",
                      "Se deposita en el riñón: proteinuria masiva, a menudo con riñones grandes; también hígado, bazo, intestino."]),
  ("Varón de 66 años", ["Osteomielitis de 20 años; 8 meses de edema progresivo hasta anasarca.", "PA 150/80, proteinuria 7 g/24 h, albúmina 2,1, creatinina 3,5, HbA1c 6 %."]),
  ["Biopsia (grasa abdominal, rectal o renal): rojo Congo con birrefringencia verde manzana.",
   "Tratar la causa (resolver la osteomielitis) frena el depósito.",
   "HbA1c 6 % descarta nefropatía diabética."],
  KDIGO + " (2021); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: no da proteinuria de 7 g", "Sí: inflamación crónica + nefrótico", "No: es aguda, con hematuria", "No: no es diabético (HbA1c 6 %)", "No: hematuria, no nefrótico"]),
  d=dict(rotulo="De la infección crónica al riñón", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Osteomielitis por 20 años", "Inflamación crónica", [("Proteína amiloide A alta", "Reactante de fase aguda", False)]),
                ("Fibrillas de amiloide AA", "Se depositan en los tejidos", [("Rojo Congo +", "Verde manzana con luz polarizada", False)]),
                ("Depósito en el glomérulo", "Pierde la barrera para proteínas", [("Proteinuria 7 g/24 h", "Síndrome nefrótico", True),
                                                                                   ("Albúmina 2,1 y anasarca", "Edema masivo", True)]),
                ("Daño progresivo", "Pérdida de nefronas", [("Creatinina 3,5", "Falla renal", False)])],
         veredicto=("Inflamación crónica + nefrótico = amiloidosis AA", "Biopsia con rojo Congo y tratar la osteomielitis.")),
  banda=B("Así se ve el amiloide", P("amiloide.jpg", 260, 260, [], credito="Ed Uthman" + CC + "CC BY 2.0"),
          [("Material rosado amorfo", "Depósitos de amiloide."), ("Rojo Congo", "Verde manzana con luz polarizada."),
           ("Biopsia de grasa", "Menos invasiva que la renal.")],
          pie="Depósitos de amiloide"))

# OFT-043 · OMA tras amoxicilina reciente: amoxicilina-clavulánico · DECISIÓN + otoscopia
S("decision", "OFT-043", "Niño con otitis media aguda que recibió amoxicilina hace un mes: el antibiótico de elección es amoxicilina con ácido clavulánico",
  "Otitis media aguda",
  ("Antibiótico en la otitis media aguda", ["Primera elección: amoxicilina a dosis alta (80-90 mg/kg/día).",
                                            "Si recibió amoxicilina en los últimos 30 días, tiene conjuntivitis purulenta o fracasó: amoxicilina-clavulánico (cubre Haemophilus y Moraxella productores de betalactamasa)."]),
  ("Niño de 3 años", ["2 días de otalgia y fiebre; hace un mes otro episodio tratado con amoxicilina 40 mg/kg/día.", "T 38,5 °C; tímpano abombado, congestivo e hiperémico."]),
  ["Amoxicilina-clavulánico 90 mg/kg/día de amoxicilina (en 2 dosis) por 10 días en < 2 años o grave; 5-7 días en mayores.",
   "Analgesia (paracetamol o ibuprofeno).",
   "Alergia a la penicilina: cefuroxima o cefdinir (no grave) o macrólido (si es grave)."],
  AAP + ", otitis media aguda (2013; act.); " + MINSA + ".",
  op=("¿Antibiótico?", ["No: la recibió hace < 30 días (y a dosis baja)", "Sí: cubre betalactamasas", "Alternativa en alergia leve", "Solo en alergia grave", "No: es para otitis externa o con tubos"]),
  d=dict(rotulo="Otitis media aguda: ¿qué antibiótico?", eje_y="Situación", ancho_filas=200,
         cols=["Primera elección", "Si es alérgico"],
         rows=[("Sin amoxicilina en 30 días", ""), ("Amoxicilina en los últimos 30 días", "o conjuntivitis purulenta")],
         cells=[[("Amoxicilina 80-90 mg/kg/día", []), ("Cefuroxima o macrólido", [])],
                [("AMOXICILINA-CLAVULÁNICO", ["Este caso"]), ("Cefuroxima o ceftriaxona", [])]],
         caso=(1, 0), nota="Además, 40 mg/kg/día era una dosis baja para otitis."),
  banda=B("Así se ve el tímpano", P("oma.jpg", 260, 260, [], credito="B. Welleschik" + CC + "CC BY-SA 3.0"),
          [("Tímpano abombado", "El signo más específico de otitis media aguda."), ("Rojo y opaco", "Sin el reflejo de luz."),
           ("Con fiebre y otalgia", "Indica antibiótico en < 2 años o si es grave.")],
          pie="Tímpano abombado"))

# SP-139 · Asentimiento del niño en investigación · RADIAL
S("radial", "SP-139", "Niño de 9 años elegido para un ensayo clínico: además de su asentimiento, la madre debe firmar el consentimiento informado (en un idioma que entienda)",
  "Ética de la investigación · consentimiento en menores",
  ("Asentimiento y consentimiento", ["El niño que puede entender (≈ desde los 8 años) da su asentimiento: acepta participar luego de una explicación a su nivel.",
                                     "Pero el consentimiento legal lo dan los padres o el tutor: sin la firma de la madre no es válido."]),
  ("Escolar de 9 años, bilingüe", ["Madre quechuahablante.", "Elegido para un ensayo clínico; el médico le explica en castellano."]),
  ["El consentimiento de la madre debe explicarse en quechua (con traductor si hace falta).",
   "El estudio debe estar aprobado por un comité de ética; el niño puede retirarse cuando quiera.",
   "Reglamento de ensayos clínicos del Perú (INS) y Declaración de Helsinki."],
  "Declaración de Helsinki (2024); INS, reglamento de ensayos clínicos del Perú.",
  op=("¿Condición?", ["No: no se requiere autoridad jurídica", "No: el que consiente es la madre", "Sí: el consentimiento es de la madre", "No: su firma sola no basta", "No: el investigador no firma por él"],
      {0: "Una autoridad jurídica presente", 1: "El niño firma un consentimiento en quechua", 3: "Basta la firma del niño (> 8 años)"}),
  d=dict(rotulo="Qué hace válida la participación de un niño", centro="ENSAYO CON NIÑOS", centro_sub="9 años", ans=1,
         items=[("ASENTIMIENTO DEL NIÑO", ["Explicado a su nivel"]), ("CONSENTIMIENTO DE LA MADRE", ["Firma obligatoria", "Esta pregunta"]),
                ("EN SU IDIOMA", ["Quechua para la madre"]), ("COMITÉ DE ÉTICA", ["Aprueba el estudio"]), ("LIBRE RETIRO", ["Sin consecuencias"])],
         ruta=["Explicar al niño", "Asentimiento", "Consentimiento de la madre en quechua", "Participa"]))
