"""Entrega 2 · tanda 07 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, DOS, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"

# PED-104 · Atresia de vías biliares · ÁRBOL + tarjeta de color de heces propia
S("arbol", "PED-104", "Neonato de 20 días con ictericia, heces blanquecinas, orina oscura y bilirrubina directa alta: atresia de vías biliares",
  "Colestasis neonatal · atresia biliar",
  ("Atresia de vías biliares", ["Las vías biliares extrahepáticas se inflaman y cierran: la bilis no llega al intestino.",
                                "Ictericia que sigue después de las 2 semanas, acolia, coluria y bilirrubina DIRECTA alta."]),
  ("Recién nacido de 20 días", ["Ictericia, heces blanquecinas, orina «cargada».",
                                "Buen peso, leve distensión; BT 12 con BD 8,1; TGO 68."]),
  ["Toda ictericia > 14 días: medir bilirrubina directa (> 1 mg/dL o > 20 % es colestasis).",
   "Ecografía (vesícula pequeña, signo del cordón triangular), gammagrafía y colangiografía intraoperatoria.",
   "Cirugía de Kasai antes de los 45-60 días: cuanto antes, mejor pronóstico; si falla, trasplante."],
  "NASPGHAN/ESPGHAN, colestasis del lactante (2017); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Sí: acolia + bilirrubina directa", "Posible, pero la acolia orienta a atresia", "No: hemograma normal",
                        "Daría bilirrubina indirecta", "No: es indirecta, heces normales"]),
  arbol=Q("Ictericia después de los 14 días: ¿bilirrubina directa alta con heces pálidas?", [
      L("Sí (este caso)", "ATRESIA BILIAR HASTA DESCARTARLA", ["Eco y gammagrafía", "Kasai < 60 días"], path=True),
      L("No: indirecta, heces normales", "Leche materna o hipotiroidismo", ["TSH, control"])], path=True),
  banda=B("Tarjeta de color de heces", P("dib_tarjeta_heces.jpg", 380, 236, [], credito=PROPIO, fondo="#ffffff"),
          [("Colores 1-3: anormal", "Heces pálidas (acolia): la bilis no llega."),
           ("Colores 4-7: normal", "Amarillo a verde."),
           ("Tamizaje sencillo", "La madre compara las heces con la tarjeta."),
           ("Acolia = urgencia", "La cirugía de Kasai pierde eficacia con los días.")],
          pie="Esquema basado en la tarjeta usada en el tamizaje.", ans=0))

# GIN-092 · Ligaduras vivientes de Pinard · TARJETAS
S("tarjetas", "GIN-092", "Las fibras musculares entrecruzadas del útero (ligaduras vivientes de Pinard) controlan el sangrado después del parto",
  "Fisiología del alumbramiento · hemostasia uterina",
  ("Ligaduras vivientes de Pinard", ["El miometrio tiene fibras en «ocho» que rodean los vasos del lecho placentario.",
                                     "Al contraerse tras el alumbramiento estrangulan los vasos: es la principal hemostasia del posparto."]),
  ("Pregunta de concepto", ["Entrecruzamiento de fibras musculares del útero gestante.", "¿Cuál es su función principal?"]),
  ["Globo de seguridad de Pinard: útero duro y contraído debajo del ombligo tras el alumbramiento.",
   "Si no se contraen (atonía) hay hemorragia: masaje y uterotónicos.",
   "Oxitocina en el manejo activo del tercer periodo para favorecerlo."],
  WILLIAMS + "; " + OMS + ", hemorragia posparto (2023).",
  op=("¿Función?", ["No: no tiene relación", "No: no tiene relación", "Sí: comprimen los vasos", "No: lo hace el músculo liso en el embarazo",
                    "No: lo hacen las contracciones del parto"]),
  d=dict(rotulo="¿Qué detiene el sangrado tras el parto?", ans=0,
         cards=[dict(titulo="Ligaduras de Pinard", datos=[("Qué es", "Fibras en ocho", True), ("Hace", "Cierra los vasos", True), ("Cuándo", "Tras el alumbramiento", True)],
                     pie="Este caso."),
                dict(titulo="Globo de seguridad", datos=[("Qué es", "Útero contraído", False), ("Dónde", "Bajo el ombligo", False), ("Indica", "Hemostasia", False)],
                     pie="Signo clínico."),
                dict(titulo="Coagulación", datos=[("Hace", "Trombos en el lecho", False), ("Rol", "Secundario", False), ("Falla", "CID", False)],
                     pie="Complementa."),
                dict(titulo="Atonía uterina", datos=[("Qué es", "Útero blando", False), ("Resultado", "Hemorragia", False), ("Trato", "Masaje, oxitocina", False)],
                     pie="Cuando fallan.")]))

# INF-046 · Artritis gonocócica: ceftriaxona · ÁRBOL + Gram real
S("arbol", "INF-046", "Joven sexualmente activo con monoartritis de rodilla y diplococos gramnegativos en el líquido: artritis gonocócica, ceftriaxona EV",
  "Artritis séptica · gonococo",
  ("Artritis gonocócica", ["La causa más común de artritis séptica en adultos jóvenes sexualmente activos.",
                           "Dos formas: artritis purulenta (como esta) o tríada de tenosinovitis, dermatitis pustular y poliartralgias."]),
  ("Varón de 25 años, soltero", ["4 días de dolor y aumento de volumen de la rodilla.", "Edema y eritema; líquido articular con diplococos gramnegativos."]),
  ["Ceftriaxona 1 g EV cada 24 h hasta 24-48 h de mejoría, luego oral hasta 7 días.",
   "Drenaje por artrocentesis repetida (rara vez cirugía).",
   "Descartar clamidia (doxiciclina), VIH y sífilis; tratar a la pareja."],
  CDC + ", guías de ITS (2021, act. 2024); " + IDSA + ".",
  op=("¿Tratamiento?", ["No: resistencia del gonococo", "No: primero punción y antibiótico", "No: no cubre gramnegativos", "Sí: de elección",
                        "No: es una infección"]),
  arbol=Q("Artritis séptica en un joven: ¿diplococos gramnegativos?", [
      L("Sí (este caso)", "CEFTRIAXONA EV", ["Artrocentesis", "Pruebas de ITS"], path=True),
      L("Cocos grampositivos", "S. aureus", ["Cefazolina o vancomicina", "Lavado articular"])], path=True),
  triada=TR([("Tenosinovitis", "No", False), ("Dermatitis pustular", "No", False), ("Poliartralgias migratorias", "No", False),
             ("Artritis purulenta", "Rodilla", True)],
            [("Forma diseminada (tríada)", 0, 2), ("Forma articular", 3, 3)],
            "Este caso es la forma de artritis purulenta localizada."),
  banda=B("Así se ve en el Gram", P("gonococo.jpg", 300, 241, [
            ("flecha", 0.33, 0.42, 0.62, 0.90, "diplococos dentro del neutrófilo")],
          credito="Graham Beards" + CC + "CC BY-SA 4.0"),
          [("Diplococos gramnegativos", "Rosados, en pares, con forma de grano de café."),
           ("Dentro del neutrófilo", "Intracelulares: típicos del gonococo."),
           ("En el líquido articular", "El Gram es positivo en menos de la mitad."),
           ("Cultivo y PCR", "Aumentan el diagnóstico (también uretral y faríngeo).")],
          pie="Gram de otro paciente.", ans=0))

# INF-047 · Sarcoma de Kaposi · TARJETAS + foto real
S("tarjetas", "INF-047", "Paciente con VIH y CD4 < 200 con nódulos rojo vinosos que no palidecen en piel y boca: sarcoma de Kaposi",
  "VIH · neoplasias asociadas",
  ("Sarcoma de Kaposi", ["Tumor vascular causado por el herpesvirus humano 8 (VHH-8), favorecido por la inmunosupresión.",
                         "Máculas, placas o nódulos rojo-violáceos que no palidecen; piel, boca, intestino y pulmón."]),
  ("Varón de 28 años con VIH, TAR irregular", ["CD4 < 200.", "3 meses de nódulos rojo vinosos en tórax, piernas y boca que no palidecen."]),
  ["Biopsia confirma (células fusiformes, VHH-8).",
   "TAR eficaz: muchas lesiones regresan solo con él.",
   "Enfermedad extensa o visceral: quimioterapia (doxorrubicina liposomal o paclitaxel)."],
  "NIH/CDC/IDSA, infecciones oportunistas en VIH (act. 2025); NCCN, sarcoma de Kaposi (2025).",
  op=("¿Diagnóstico?", ["Sí: nódulos violáceos en VIH", "No: pápulas umbilicadas color piel", "Parecida; es Bartonella y sangra", "No: pápulas pruriginosas",
                        "No: pápulas rojas pequeñas benignas"]),
  d=dict(rotulo="Lesión de piel en VIH: ¿cuál?", ans=0,
         cards=[dict(titulo="Sarcoma de Kaposi", datos=[("Color", "Rojo vinoso", True), ("Presión", "No palidece", True), ("Virus", "VHH-8", True)],
                     pie="Este caso."),
                dict(titulo="Angiomatosis bacilar", datos=[("Germen", "Bartonella", False), ("Lesión", "Friable, sangra", False), ("Trato", "Macrólido", False)],
                     pie="Biopsia distingue."),
                dict(titulo="Molusco contagioso", datos=[("Lesión", "Pápula umbilicada", False), ("Color", "De la piel", False), ("Virus", "Poxvirus", False)],
                     pie="Benigno."),
                dict(titulo="Foliculitis eosinofílica", datos=[("Lesión", "Pápulas foliculares", False), ("Síntoma", "Prurito intenso", False), ("CD4", "Bajos", False)],
                     pie="Inflamatoria.")]),
  banda=B("Así se ve", P("kaposi.jpg", 330, 220, [
            ("circulo", 0.45, 0.45, 0.16, "placas y nódulos violáceos", 0.50, 0.92)],
          credito="Dominio público" + CC.rstrip(" · ")),
          [("Rojo-violáceo", "Del color del vino; no palidecen al apretar."),
           ("Placas y nódulos", "Se agrandan y se juntan."),
           ("También en la boca", "Paladar y encías: buscar en la boca."),
           ("Regresan con el TAR", "Al recuperarse la inmunidad.")],
          pie="Piel de otro paciente con sida.", ans=0))

# CB-031 · QT largo por azitromicina · ÁRBOL + ECG propio
S("arbol", "CB-031", "Adulto mayor que se automedicó «para el COVID» y presenta QT largo y taquicardia ventricular: azitromicina",
  "Farmacología · QT largo adquirido",
  ("QT largo por fármacos", ["Algunos fármacos bloquean los canales de potasio del corazón y alargan el QT.",
                             "Riesgo de torsade de pointes, sobre todo con hipopotasemia, hipomagnesemia, bradicardia o mujeres mayores."]),
  ("Varón de 72 años", ["Mareos y dolor precordial hace una hora.", "ECG: QT largo y taquicardia ventricular; automedicación «para el COVID»."]),
  ["Suspender el fármaco; corregir K⁺ (> 4) y Mg²⁺.",
   "Torsade: sulfato de magnesio 2 g EV; si es inestable, desfibrilar.",
   "Otros que alargan el QT: macrólidos, quinolonas, hidroxicloroquina, ondansetrón, antipsicóticos."],
  "CredibleMeds (2025); AHA/ACC/HRS, arritmias ventriculares (2017).",
  op=("¿Medicamento?", ["No: no alarga el QT", "No: no alarga el QT", "Sí: macrólido que alarga el QT", "Rara vez; no es la causa típica",
                        "No: no alarga el QT"]),
  arbol=Q("QT largo con arritmia: ¿toma un fármaco que lo alarga?", [
      L("Sí: azitromicina (este caso)", "SUSPENDER + MAGNESIO", ["Corregir K⁺ y Mg²⁺", "Desfibrilar si es inestable"], path=True),
      L("No", "QT largo congénito o electrolitos", ["K, Mg, Ca"])], path=True),
  banda=B("QT largo y torsade de pointes", P("ecg_qt_tdp.jpg", 380, 182, [
            ("corchete", 0.27, 0.38, 0.21, "QT largo", True),
            ("texto", 0.50, 0.93, "torsade de pointes")],
          credito=ECG_PROPIO, fondo="#ffffff"),
          [("QT largo", "Del inicio del QRS al final de la T: > 470 ms en varones, > 480 en mujeres."),
           ("Torsade de pointes", "TV polimorfa que gira alrededor de la línea de base."),
           ("Puede pasar a FV", "Muerte súbita."),
           ("Magnesio EV", "Primera medida aunque el Mg sea normal.")],
          pie="Trazado de enseñanza: arriba QT largo, abajo torsade.", ans=1))

# NEU-027 · Asbestosis: cuerpos ferruginosos · TARJETAS + biopsia real
S("tarjetas", "NEU-027", "Trabajador expuesto 30 años al asbesto con disnea, placas pleurales y fibrosis reticular en panal: asbestosis, cuerpos ferruginosos en la biopsia",
  "Neumoconiosis · asbestosis",
  ("Asbestosis", ["Fibrosis pulmonar por inhalar fibras de asbesto, décadas después de la exposición.",
                  "Fibrosis basal + placas pleurales; las fibras recubiertas de hierro son los cuerpos ferruginosos."]),
  ("Varón de 76 años, 30 años con asbesto", ["4 años de disnea progresiva; FR 30.",
                                              "Rx: engrosamiento pleural y opacidades reticulares en panal de abeja."]),
  ["Riesgo de mesotelioma (pleura) y cáncer de pulmón (mayor si fuma).",
   "No hay tratamiento que revierta la fibrosis: dejar de fumar, vacunas, oxígeno; antifibrótico si es progresiva.",
   "Silicosis: nódulos en lóbulos superiores; beriliosis: granulomas no caseificantes."],
  "ATS, enfermedades por asbesto (2004, vigente); ATS/ERS, fibrosis progresiva (2022).",
  op=("¿Biopsia?", ["No es el hallazgo típico", "Son de la TB o la beriliosis", "Inespecífico", "Sí: fibras de asbesto con hierro",
                    "Son de la sarcoidosis o beriliosis"]),
  d=dict(rotulo="Neumoconiosis: ¿qué se ve?", ans=0,
         cards=[dict(titulo="Asbestosis", datos=[("Exposición", "Asbesto", True), ("Biopsia", "Cuerpos ferruginosos", True), ("Rx", "Bases + placas pleurales", True)],
                     pie="Este caso."),
                dict(titulo="Silicosis", datos=[("Exposición", "Minería, arena", False), ("Rx", "Nódulos en vértices", False), ("Ganglios", "En cáscara de huevo", False)],
                     pie="Riesgo de TB."),
                dict(titulo="Beriliosis", datos=[("Exposición", "Aeroespacial", False), ("Biopsia", "Granulomas", False), ("Parece", "Sarcoidosis", False)],
                     pie="Hipersensibilidad."),
                dict(titulo="Antracosis", datos=[("Exposición", "Carbón", False), ("Biopsia", "Pigmento negro", False), ("Grave", "Fibrosis masiva", False)],
                     pie="Minero de carbón.")]),
  banda=B("Así se ven los cuerpos ferruginosos", P("ferruginoso.jpg", 300, 256, [
            ("flecha", 0.50, 0.30, 0.20, 0.08, "cuerpo ferruginoso"),
            ("flecha", 0.68, 0.40, 0.82, 0.90, "otro")],
          credito="Nephron" + CC + "CC BY-SA 3.0"),
          [("Bastones color óxido", "Fibras de asbesto cubiertas de hierro y proteína."),
           ("Segmentados", "Forma de «palillo de tambor»."),
           ("En el intersticio fibroso", "Rodeados de fibrosis."),
           ("Marcan exposición", "No bastan solos: hace falta fibrosis.")],
          pie="Biopsia pulmonar de otro paciente.", ans=0))

# NEF-037 · Nefropatía diabética: IECA · ÁRBOL + KDIGO
S("arbol", "NEF-037", "Diabético con HTA, filtración de 45 mL/min y albuminuria de 1 g/día: el fármaco para bajar la proteinuria es un IECA (o ARA II)",
  "Enfermedad renal diabética · tratamiento",
  ("Nefroprotección en la diabetes", ["IECA o ARA II bajan la presión dentro del glomérulo y la proteinuria.",
                                      "Hoy se suman iSGLT2 y, según el caso, finerenona o agonistas GLP-1."]),
  ("Varón de 58 años con diabetes", ["PA 140/90, edema de piernas.", "Depuración 45 mL/min, albúmina en orina 1 g/24 h, K 4,5."]),
  ["IECA o ARA II a dosis máxima tolerada; control de K y creatinina a las 2-4 semanas.",
   "iSGLT2 (dapagliflozina, empagliflozina) si la FG ≥ 20; meta PA < 130/80.",
   "No combinar IECA + ARA II (más hiperpotasemia y falla renal)."],
  KDIGO + ", diabetes en la ERC (2022); " + ADA + ", cap. 11.",
  op=("¿Medicamento?", ["Protege el corazón, no baja la proteinuria", "Sí: baja la proteinuria", "Controla la glucosa, no la proteinuria",
                        "No: hipoglucemia en la ERC", "Baja la PA, no protege el riñón igual"]),
  arbol=Q("Diabetes con albuminuria: ¿K < 5,5 y FG estable?", [
      L("Sí: K 4,5 (este caso)", "IECA O ARA II", ["+ iSGLT2", "PA < 130/80"], path=True),
      L("K alto", "Corregir antes", ["Dieta, quelantes"])], path=True),
  escala=dict(nombre="Clasificación KDIGO de la ERC (FG y albuminuria)", orden=True,
              que="Se combinan la filtración (G) y la albuminuria (A) para el riesgo.",
              grados=[("G1-G2", "FG ≥ 60", ["Normal o leve"]), ("G3a", "FG 45-59", ["Leve-moderada"]),
                      ("G3b", "FG 30-44", ["Moderada-grave"]), ("G4", "FG 15-29", ["Grave"]), ("G5", "FG < 15", ["Falla renal"])],
              caso=1, porque=[("FG 45 mL/min: límite G3a", True), ("Albuminuria 1 g/día: A3", True)],
              conducta="IECA o ARA II + iSGLT2; control cada 3-6 meses."))

# SP-063 · Carta de Ottawa: habilidades personales · RADIAL
S("radial", "SP-063", "Educar a las gestantes para mejorar la lactancia materna es la acción de la Carta de Ottawa «desarrollar habilidades personales»",
  "Promoción de la salud · Carta de Ottawa",
  ("Carta de Ottawa (1986)", ["Cinco áreas de acción de la promoción de la salud.",
                              "Desarrollar habilidades personales: información y educación para que la gente decida sobre su salud."]),
  ("Centro de salud", ["Lactancia materna exclusiva < 50 % en el distrito.", "Plan de comunicación educativa para gestantes."]),
  ["Políticas públicas saludables: leyes (p. ej., lactarios obligatorios).",
   "Entornos favorables: trabajo, escuela, comunidad que facilitan la lactancia.",
   "Reorientar los servicios: hospitales «amigos del niño»."],
  OMS + ", Carta de Ottawa (1986); " + MINSA + ".",
  op=("¿Acción?", ["Cambia el entorno, no a la persona", "Es reorientar servicios", "Sí: educación a las gestantes", "No es un área de Ottawa",
                   "Son leyes o normas"]),
  d=dict(rotulo="Las 5 áreas de acción de Ottawa", centro="HABILIDADES PERSONALES", centro_sub="este caso", ans=0,
         items=[("HABILIDADES", ["Educar, informar"]), ("POLÍTICAS", ["Leyes saludables"]), ("ENTORNOS", ["Lugares que facilitan"]),
                ("COMUNIDAD", ["Acción comunitaria"]), ("SERVICIOS", ["Reorientarlos"])],
         ruta=["Diagnosticar el problema", "Elegir el área de acción", "Educar a gestantes", "Medir la lactancia"]))

# INF-048 · Cólera · ÁRBOL + foto real
S("arbol", "INF-048", "Joven con diarrea acuosa profusa «en agua de arroz», vómitos, calambres y deshidratación, sin sangre ni inflamación: cólera",
  "Enfermedad diarreica · cólera",
  ("Cólera", ["Vibrio cholerae produce una toxina que hace que el intestino secrete litros de agua y sales.",
              "Diarrea acuosa masiva, sin fiebre, sin sangre, sin leucocitos; deshidratación rápida y calambres."]),
  ("Varón de 18 años", ["24 h de vómitos y deposiciones como agua de arroz; calambres y oliguria.",
                        "PA 100/50, FC 100, mucosa seca; reacción inflamatoria en heces negativa."]),
  ["Rehidratar: SRO o lactato de Ringer EV si es grave (plan C).",
   "Antibiótico dosis única en deshidratación moderada o grave: doxiciclina (o azitromicina en niños y gestantes).",
   "Notificación inmediata; cultivo en TCBS."],
  OMS + ", cólera (2024); " + MINSA + ", NTS de cólera.",
  op=("¿Agente?", ["No: disentería con sangre", "Da diarrea acuosa, pero no así de masiva", "Sí: agua de arroz", "No: disentería", "No: esteatorrea, no masiva"]),
  arbol=Q("Diarrea acuosa masiva sin fiebre ni sangre: ¿deshidratación?", [
      L("Sí, moderada a grave (este caso)", "CÓLERA: REHIDRATAR", ["SRO o Ringer EV", "Doxiciclina dosis única"], path=True),
      L("No", "SRO y vigilar", ["Plan A"])], path=True),
  banda=B("Así se ven las heces", P("colera.jpg", 230, 259, [
            ("flecha", 0.55, 0.55, 0.40, 0.90, "«agua de arroz»")],
          credito="Ajay Kumar Chaurasiya" + CC + "CC BY-SA 4.0"),
          [("Agua de arroz", "Líquido turbio con grumos de moco, casi sin olor."),
           ("Litros por día", "Hasta 1 L por hora en adultos."),
           ("Sin sangre ni leucocitos", "Es secretora, no inflamatoria."),
           ("Calambres", "Por la pérdida de sodio y potasio.")],
          pie="Muestra de otro paciente.", ans=0))

# SP-064 · Estudio transversal · MATRIZ
S("matriz", "SP-064", "Encuestar a todos los alumnos una sola vez sobre sus características y conocimientos: estudio transversal",
  "Epidemiología · diseños de estudio",
  ("Estudio transversal", ["Mide exposición y desenlace al mismo tiempo, en un solo momento («foto»).",
                           "Da prevalencias; útil para describir y generar hipótesis."]),
  ("Colegio de secundaria", ["Aumentó el abandono escolar por embarazo.", "Encuesta a todos los alumnos: características y conocimientos de salud sexual."]),
  ["No establece causalidad porque no sabe qué vino primero.",
   "Cohorte: sigue en el tiempo; casos y controles: parte del desenlace.",
   "Serie de casos: describe pocos casos, sin comparación."],
  "Gordis, Epidemiología 6.ª ed. (2019).",
  op=("¿Tipo?", ["No: no parte del desenlace", "No: no se interviene", "Sí: una medición, todos", "No: no se sigue en el tiempo", "No: no son casos aislados"]),
  d=dict(rotulo="Diseño según el tiempo y la intervención", eje_x="¿Se interviene?", eje_y="Cuándo se mide",
         cols=["No (observacional)", "Sí (experimental)"], rows=["Una sola vez", "En el tiempo"], caso=(0, 0),
         cells=[[("TRANSVERSAL", ["Encuesta única", "Prevalencia"]), ("No aplica", ["Toda intervención se sigue"])],
                [("Cohorte / casos y controles", ["Incidencia u OR"]), ("Ensayo clínico", ["Asignación al azar"])]]))

# OFT-023 · Glaucoma primario de ángulo abierto · TARJETAS
S("tarjetas", "OFT-023", "La forma más frecuente de glaucoma es el primario de ángulo abierto",
  "Oftalmología · glaucoma",
  ("Glaucoma primario de ángulo abierto", ["Neuropatía óptica crónica con aumento de la excavación de la papila y pérdida del campo visual periférico.",
                                            "Silencioso: sin dolor ni ojo rojo; se detecta en el tamizaje (fondo de ojo, presión, campo visual)."]),
  ("Pregunta de concepto", ["¿Cuál es la forma de glaucoma más frecuente?", "En el mundo y en el Perú."]),
  ["Tamizaje desde los 40 años, antes si hay familiares o es afrodescendiente.",
   "Tratamiento: gotas (análogos de prostaglandina, timolol), láser (trabeculoplastia) o cirugía.",
   "Ángulo cerrado agudo: ojo rojo y doloroso, pupila media fija, náuseas: urgencia."],
  "AAO, Preferred Practice Pattern de glaucoma (2020, act. 2025); EGS (2020).",
  op=("¿Más frecuente?", ["No: urgencia, menos común", "No: secundario al cristalino", "No: secundario a fármacos", "Sí: el más común", "No: raro"]),
  d=dict(rotulo="Tipos de glaucoma", ans=0,
         cards=[dict(titulo="Ángulo abierto", datos=[("Frecuencia", "El más común", True), ("Síntomas", "Ninguno al inicio", True), ("Pierde", "Visión periférica", True)],
                     pie="Este caso."),
                dict(titulo="Ángulo cerrado agudo", datos=[("Clínica", "Ojo rojo, dolor", False), ("Pupila", "Media fija", False), ("Trato", "Urgencia, láser", False)],
                     pie="Urgencia."),
                dict(titulo="Congénito", datos=[("Edad", "Lactante", False), ("Signo", "Ojo grande, lagrimeo", False), ("Trato", "Cirugía", False)],
                     pie="Raro."),
                dict(titulo="Secundario", datos=[("Causas", "Corticoides, uveítis", False), ("Facogénico", "Catarata", False), ("Trato", "La causa", False)],
                     pie="Por otra causa.")]))

# GIN-093 · Vasa previa: cesárea 34-35 semanas · ÁRBOL
S("arbol", "GIN-093", "Vasa previa diagnosticada en la ecografía: cesárea programada entre las 34 y 35 semanas",
  "Anomalías de la placenta y del cordón · vasa previa",
  ("Vasa previa", ["Vasos fetales sin protección (sin gelatina de Wharton ni placenta) cruzan sobre el cuello uterino.",
                   "Si se rompen al romper las membranas, sangra el FETO: muerte fetal en minutos."]),
  ("Primigesta de 24 semanas", ["Ecografía: gestación única normal, placenta fúndica posterior.", "Vasa previa."]),
  ["Corticoides a las 28-32 semanas; hospitalizar a las 30-34 semanas según la guía.",
   "Cesárea programada a las 34-36 semanas, antes de que empiece el trabajo de parto.",
   "Nunca amniotomía ni parto vaginal."],
  "SMFM, vasa previa (2015, reafirmada 2024); RCOG Green-top 27b (2018); " + ACOG + ".",
  op=("¿Manejo?", ["No: riesgo de ruptura de membranas antes", "No: los vasos se rompen", "Sí: antes del trabajo de parto", "No: el parto rompe los vasos",
                   "No: contraindicado"]),
  arbol=Q("Vasa previa en la ecografía: ¿persiste en el tercer trimestre?", [
      L("Sí (este caso)", "CESÁREA A LAS 34-35 SEMANAS", ["Corticoides", "Hospitalizar 30-34 sem"], path=True),
      L("Se resolvió", "Manejo habitual", ["Confirmar con Doppler"])], path=True))

# PED-105 · Cáusticos con estridor: vía aérea · ÁRBOL + Zargar
S("arbol", "PED-105", "Niño que ingirió lejía hace 20 minutos con estridor, sialorrea y SatO₂ 91 %: lo primero es asegurar la vía aérea (intubación)",
  "Toxicología pediátrica · cáusticos",
  ("Ingestión de cáusticos", ["Los álcalis (lejía) causan necrosis por licuefacción: quemaduras profundas en boca, esófago y laringe.",
                              "Estridor o dificultad respiratoria = edema de la vía aérea: puede cerrarse en minutos."]),
  ("Niño de 3 años", ["Ingirió lejía hace 20 minutos; estridor, dolor abdominal, náuseas y vómitos.",
                      "FR 40, SatO₂ 91 %; mucosa oral eritematosa, sialorrea; murmullo disminuido."]),
  ["Con estridor: intubación temprana por personal experto (o vía aérea quirúrgica).",
   "NO inducir el vómito, NO lavado gástrico, NO carbón activado, NO neutralizar.",
   "Endoscopía en 12-48 h para clasificar la lesión (Zargar); nada por boca."],
  "ESGE/ESPGHAN, ingestión de cáusticos en niños (2021); Goldfrank's 11.ª ed.",
  op=("¿Inicial?", ["Sí: estridor = vía aérea en riesgo", "No: no adsorbe cáusticos", "No es lo urgente", "No: perfora y reexpone", "No: reexpone el esófago"]),
  arbol=Q("Ingestión de cáustico: ¿estridor o dificultad respiratoria?", [
      L("Sí (este caso)", "INTUBACIÓN", ["Vía aérea segura", "Luego endoscopía"], path=True),
      L("No", "Nada por boca", ["Endoscopía en 12-48 h"])], path=True),
  escala=dict(nombre="Clasificación endoscópica de Zargar", orden=True,
              que="Grado de la quemadura esofágica; predice la estenosis.",
              grados=[("Grado 0-1", "Normal o edema", ["Alta pronto"]), ("Grado 2a", "Úlceras superficiales", ["Buen pronóstico"]),
                      ("Grado 2b", "Úlceras circunferenciales", ["Riesgo de estenosis"]), ("Grado 3", "Necrosis", ["Estenosis, perforación"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Falta la endoscopía; primero la vía aérea", True)],
              conducta="Intubar, nada por boca, endoscopía en 12-48 h."))

# PSI-018 · Psicosis · ÁRBOL
S("arbol", "PSI-018", "Joven con 4 meses de ideas de daño, voces que le advierten y descuido del aseo: psicosis",
  "Trastornos psicóticos",
  ("Psicosis", ["Pérdida del juicio de realidad: delirios (creencias falsas firmes) y alucinaciones (percibir sin estímulo).",
                "Es un síndrome: luego se busca la causa (esquizofrenia, ánimo, drogas, orgánica)."]),
  ("Mujer de 24 años", ["4 meses faltando al trabajo y descuidando su aseo.", "Cree que le quieren hacer daño; escucha voces que la advierten."]),
  ["Descartar causas orgánicas y drogas (tóxicos, TSH, imagen si hay signos).",
   "Antipsicótico de segunda generación; psicoeducación a la familia.",
   "Con 1-6 meses: trastorno esquizofreniforme; ≥ 6 meses: esquizofrenia."],
  "DSM-5-TR (2022); " + NICE + " CG178 (2014, act. 2025).",
  op=("¿Diagnóstico?", ["No: agotamiento sin delirios", "Sí: delirios + alucinaciones", "No: miedo a la evaluación social", "No predomina el ánimo",
                        "No: sin delirios ni voces"]),
  arbol=Q("Delirios o alucinaciones: ¿hay causa orgánica o drogas?", [
      L("No identificada (este caso)", "PSICOSIS PRIMARIA", ["Antipsicótico", "Seguimiento"], path=True),
      L("Sí", "Psicosis secundaria", ["Tratar la causa"])], path=True),
  triada=TR([("Delirios", "Persecución", True), ("Alucinaciones", "Voces", True), ("Desorganización", "Descuido del aseo", True)],
            [("Síntomas psicóticos", 0, 2)],
            "Delirio + alucinación = psicosis."))

# NEF-038 · Uropatía obstructiva por HBP: RTU · ÁRBOL
S("arbol", "NEF-038", "Adulto mayor con síntomas prostáticos de años, gran residuo vesical, anemia y creatinina 3,5: uropatía obstructiva, tratamiento definitivo RTU",
  "Hiperplasia prostática · complicaciones",
  ("Uropatía obstructiva por HBP", ["La próstata grande no deja vaciar la vejiga: retención crónica, hidronefrosis y falla renal.",
                                    "Síntomas: chorro débil, nicturia; luego uremia (náuseas, fatiga, palidez)."]),
  ("Varón de 70 años", ["3 años de chorro débil y nicturia; 1 mes de náuseas, vómitos y fatiga.",
                        "Palidez terrosa; Hb 9, creatinina 3,5; próstata grande y gran residuo."]),
  ["Primero: sonda vesical para descomprimir (vigilar la poliuria posobstructiva).",
   "Definitivo: resección transuretral de la próstata (o enucleación láser).",
   "Indicaciones de cirugía: falla renal, retención recurrente, cálculos, infecciones o hematuria repetidas."],
  "EAU, síntomas del tracto urinario inferior masculino (2025); AUA (2023).",
  op=("¿Definitivo?", ["Sí: quita la obstrucción", "No: no trata la causa", "Temporal, no definitivo", "No trata la causa", "No basta con falla renal"]),
  arbol=Q("HBP con falla renal por retención: ¿se descomprimió la vejiga?", [
      L("Sí, con sonda", "RTU DE PRÓSTATA", ["Definitivo"], path=True),
      L("No", "Sonda vesical primero", ["Ver poliuria"])], path=True))

# NEF-039 · Pielonefritis obstructiva: derivación · ÁRBOL
S("arbol", "NEF-039", "Pielonefritis con cálculo enclavado e hidronefrosis que no mejora con antibióticos e hipotensión: derivar la orina (catéter doble J o nefrostomía)",
  "Infecciones urinarias · pielonefritis obstructiva",
  ("Pielonefritis obstructiva", ["Infección detrás de un cálculo que tapa el uréter: el antibiótico no llega bien y hay riesgo de urosepsis.",
                                 "Es una urgencia urológica: drenar la orina infectada."]),
  ("Varón de 30 años con litiasis", ["Náuseas, vómitos, 39,5 °C; PA 90/60, FC 100.",
                                     "Puño percusión derecha (++); uroTC: cálculo enclavado con hidronefrosis; no mejora con antibióticos."]),
  ["Drenaje urgente: catéter ureteral doble J (endoprótesis) o nefrostomía percutánea.",
   "Mantener antibiótico EV; tratar el cálculo DESPUÉS de controlar la infección.",
   "No fragmentar el cálculo con infección activa (riesgo de sepsis)."],
  "EAU, urolitiasis (2025); EAU, infecciones urológicas (2024).",
  op=("¿Indicación?", ["No: invasiva y con infección", "Sí: drena la vía", "Opción, pero percutánea y no laparoscópica", "No: con infección activa no",
                       "No: está en sepsis"]),
  arbol=Q("Pielonefritis con obstrucción: ¿signos de sepsis?", [
      L("Sí, sin mejoría (este caso)", "DERIVAR: CATÉTER DOBLE J", ["O nefrostomía", "Antibiótico EV"], path=True),
      L("No", "Antibiótico y vigilar", ["Drenar si no mejora"])], path=True),
  banda=B("Así se ve la obstrucción", P("hidronefrosis.jpg", 330, 199, [
            ("texto", 0.62, 0.12, "cálculo (flecha roja)")],
          credito="James Heilman" + CC + "CC BY-SA 3.0"),
          [("Cálculo enclavado", "Punto blanco en el uréter (flecha roja del autor)."),
           ("Riñón dilatado arriba", "Hidronefrosis: la orina no baja."),
           ("Orina infectada atrapada", "El antibiótico solo no basta: hay que drenar."),
           ("TC sin contraste", "El mejor estudio para cálculos.")],
          pie="TC de otro paciente.", ans=2))

# INF-049 · Fiebre amarilla: dosis única · TARJETAS
S("tarjetas", "INF-049", "Médico vacunado contra la fiebre amarilla hace 2 años que irá a zona endémica: no necesita revacunarse (una dosis protege de por vida)",
  "Inmunizaciones · fiebre amarilla",
  ("Vacuna de la fiebre amarilla", ["Virus vivo atenuado; una sola dosis da inmunidad de por vida (OMS 2013).",
                                    "El certificado internacional es válido de por vida desde 2016."]),
  ("Médico serumista", ["Irá a trabajar a la selva endémica.", "Vacunado hace 2 años."]),
  ["Excepciones que pueden necesitar refuerzo: vacunados en el embarazo, con VIH, trasplante o menores de 2 años.",
   "En el Perú se aplica a los 15 meses y a viajeros a zonas endémicas.",
   "Contraindicada en menores de 6 meses, inmunosuprimidos graves y alergia al huevo."],
  OMS + ", posición sobre la vacuna de fiebre amarilla (2013); " + MINSA + ", esquema de vacunación (2025).",
  op=("¿Medida?", ["No: no hace falta", "Sí: dosis única de por vida", "No: no hace falta", "No: no hace falta", "No: no hace falta"]),
  d=dict(rotulo="¿Cuántas dosis?", ans=0,
         cards=[dict(titulo="Fiebre amarilla", datos=[("Dosis", "Una", True), ("Protege", "De por vida", True), ("Tipo", "Viva atenuada", True)],
                     pie="Este caso."),
                dict(titulo="Tétanos (dT)", datos=[("Refuerzo", "Cada 10 años", False), ("Herida sucia", "> 5 años", False), ("Tipo", "Toxoide", False)],
                     pie="Sí refuerzo."),
                dict(titulo="Influenza", datos=[("Dosis", "Anual", False), ("Por", "Cambio de cepas", False), ("Grupo", "Personal de salud", False)],
                     pie="Cada año."),
                dict(titulo="Hepatitis B", datos=[("Dosis", "3", False), ("Refuerzo", "No si responde", False), ("Control", "Anti-HBs", False)],
                     pie="Personal de salud.")]))

# CAR-039 · IAMCEST: angioplastia primaria · ÁRBOL + ECG propio
S("arbol", "CAR-039", "Dolor opresivo de 30 minutos con ST elevado 5 mm en la cara anterolateral y troponina alta, estable: angioplastia coronaria primaria",
  "Síndrome coronario agudo · IMA con elevación del ST",
  ("IMA con elevación del ST (IAMCEST)", ["Oclusión total de una arteria coronaria: el músculo muere con cada minuto.",
                                           "Reperfusión urgente: angioplastia primaria si se hace en < 120 min del diagnóstico."]),
  ("Varón de 59 años", ["Dolor torácico opresivo 8/10 hace 30 minutos; diabético, hipertenso, fumador.",
                        "Estable; ECG: ST elevado 5 mm en cara anterolateral; troponina T 290."]),
  ["Aspirina + segundo antiagregante (ticagrelor o prasugrel) + heparina; angioplastia primaria.",
   "Si no hay sala de hemodinamia en < 120 min: trombólisis en < 10 min y traslado.",
   "Oxígeno solo si SatO₂ < 90 %; no dar betabloqueador EV si hay riesgo de choque."],
  ESC + ", síndromes coronarios agudos (2023); ACC/AHA, SCA (2025).",
  op=("¿Tratamiento?", ["Se da, pero no reperfunde", "No: es para enfermedad de varios vasos, no urgente", "No: SatO₂ 96 %", "Sí: reperfusión de elección",
                        "No reperfunde"]),
  arbol=Q("IAMCEST: ¿angioplastia disponible en < 120 minutos?", [
      L("Sí (este caso)", "ANGIOPLASTIA PRIMARIA", ["Doble antiagregación", "Heparina"], path=True),
      L("No", "Trombólisis en < 10 min", ["Y traslado"])], path=True),
  banda=B("Así se ve el ECG", P("ecg_iam_al.jpg", 380, 182, [
            ("flecha", 0.224, 0.208, 0.40, 0.08, "ST elevado (V2)"),
            ("flecha", 0.746, 0.805, 0.60, 0.62, "imagen en espejo (DIII)")],
          credito=ECG_PROPIO, fondo="#ffffff"),
          [("ST elevado en V2-V6, DI y aVL", "Cara anterolateral: arteria descendente anterior."),
           ("Imagen en espejo", "ST descendido en DIII: confirma el infarto."),
           ("Criterio", "≥ 1 mm en 2 derivaciones contiguas (≥ 2 mm en V2-V3 en varones)."),
           ("Tiempo es músculo", "Puerta-balón < 90 min.")],
          pie="Trazado de enseñanza.", ans=0))

# GIN-094 · Náuseas y vómitos del embarazo · ÁRBOL
S("arbol", "GIN-094", "Gestante de 8 semanas con náuseas y vómitos leves y estable: además de las medidas dietéticas, doxilamina + piridoxina",
  "Náuseas y vómitos del embarazo",
  ("Náuseas y vómitos del embarazo", ["Muy frecuentes en el primer trimestre por la β-hCG; ceden hacia las 16-20 semanas.",
                                      "Hiperémesis: pérdida de peso > 5 %, deshidratación, cetonuria."]),
  ("Gestante de 8 semanas", ["Náuseas, vómitos y leves mareos.", "Signos vitales estables; orina normal; eco normal."]),
  ["Primera línea farmacológica: doxilamina + piridoxina (B6).",
   "Comidas pequeñas y frecuentes, evitar olores, jengibre.",
   "Segunda línea: antihistamínicos, metoclopramida u ondansetrón; hiperémesis: hidratación EV + tiamina."],
  ACOG + ", boletín 189 (2018, reafirmado 2024); RCOG Green-top 69 (2024).",
  op=("¿Prescribir?", ["Segunda línea; tiamina si hay hiperémesis", "Segunda línea; ranitidina retirada", "No es de primera línea", "Sí: primera línea",
                       "No: no está deshidratada"]),
  arbol=Q("Náuseas y vómitos del embarazo: ¿deshidratación o pérdida de peso > 5 %?", [
      L("No: estable (este caso)", "DOXILAMINA + PIRIDOXINA", ["Medidas dietéticas"], path=True),
      L("Sí", "Hiperémesis", ["Hidratación EV + tiamina"])], path=True))

# PED-106 · Tetralogía de Fallot · TARJETAS + tétrada
S("tarjetas", "PED-106", "Lactante con cianosis al llanto, corazón en bota y eco con CIV, aorta cabalgante y estenosis subpulmonar: tetralogía de Fallot",
  "Cardiopatías congénitas · cianóticas",
  ("Tetralogía de Fallot", ["La cardiopatía cianótica más común después del primer año.",
                            "Un defecto (desvío anterior del tabique infundibular) produce las 4 alteraciones."]),
  ("Lactante de 1 mes", ["Cianosis al llanto.", "Rx: corazón en bota; eco: CIV, aorta cabalgante, estenosis subpulmonar."]),
  ["Crisis hipoxémica: posición rodillas-pecho, oxígeno, morfina, líquidos, fenilefrina, propranolol.",
   "Cirugía correctora entre los 3 y 6 meses.",
   "El soplo sistólico es por la estenosis pulmonar: en la crisis el soplo disminuye."],
  AHA + ", cardiopatías congénitas; " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: acianótica", "Sí: las 4 alteraciones", "No: acianótica, pulsos femorales débiles", "No: acianótica",
                        "No: cianosis desde el nacimiento, Rx en huevo"]),
  d=dict(rotulo="Cardiopatía cianótica: ¿cuál?", ans=0,
         cards=[dict(titulo="Tetralogía de Fallot", datos=[("Rx", "Corazón en bota", True), ("Cianosis", "Con llanto, crisis", True), ("Eco", "CIV + aorta cabalgante", True)],
                     pie="Este caso."),
                dict(titulo="Transposición", datos=[("Rx", "Huevo de lado", False), ("Cianosis", "Desde el nacimiento", False), ("Trato", "PGE1, Rashkind", False)],
                     pie="La más común al nacer."),
                dict(titulo="Atresia tricuspídea", datos=[("ECG", "Eje izquierdo", False), ("Cianosis", "Neonatal", False), ("Flujo", "Por CIA y CIV", False)],
                     pie="Rara."),
                dict(titulo="Truncus", datos=[("Vaso", "Uno solo", False), ("Asocia", "DiGeorge", False), ("Cianosis", "Leve", False)],
                     pie="Raro.")]),
  triada=TR([("CIV", "Sí", True), ("Aorta cabalgante", "Sí", True), ("Estenosis pulmonar (subpulmonar)", "Sí", True),
             ("Hipertrofia del VD", "Corazón en bota", True)],
            [("Tétrada de Fallot", 0, 3)],
            "La estenosis pulmonar define la gravedad de la cianosis."),
  banda=B("Así se ve en la Rx", P("bota.jpg", 240, 266, [
            ("flecha", 0.70, 0.55, 0.78, 0.90, "punta levantada"),
            ("flecha", 0.58, 0.32, 0.25, 0.10, "cintura cóncava")],
          credito="Medicalpal" + CC + "CC BY-SA 4.0"),
          [("Corazón en bota", "Punta levantada por la hipertrofia del VD."),
           ("Cintura cóncava", "Arteria pulmonar pequeña."),
           ("Pulmones oscuros", "Poco flujo pulmonar."),
           ("La eco confirma", "Las 4 alteraciones.")],
          pie="Rx de otro paciente.", ans=0))

# NRL-027 · Hidrocefalia aguda: medidas iniciales · ÁRBOL
S("arbol", "NRL-027", "En la hidrocefalia aguda, la medida inicial de soporte es elevar la cabecera a 30° (mientras se prepara el drenaje)",
  "Neurocirugía · hidrocefalia",
  ("Hidrocefalia aguda", ["El LCR se acumula y sube la presión intracraneal: cefalea, vómitos, somnolencia, mirada en «sol poniente» en niños.",
                          "El tratamiento definitivo es drenar el LCR (ventriculostomía o derivación)."]),
  ("Pregunta de concepto", ["Paciente con hidrocefalia aguda.", "¿Manejo inicial?"]),
  ["Medidas generales: cabecera a 30°, cuello recto, normocapnia (PaCO₂ 35-40), normotermia, sodio normal.",
   "Urgencia neuroquirúrgica: drenaje ventricular externo; luego derivación ventriculoperitoneal o ventriculostomía endoscópica.",
   "Evitar sueros hipotónicos (dextrosa en agua): aumentan el edema cerebral."],
  "Brain Trauma Foundation (2016); Greenberg, Handbook of Neurosurgery 10.ª ed.",
  op=("¿Inicial?", ["No: hipotónico, edema", "Sí: mejora el drenaje venoso", "No: edema", "No: la hipercapnia sube la PIC", "No: requiere drenaje"]),
  arbol=Q("Hidrocefalia aguda con signos de hipertensión endocraneal: ¿se puede drenar ya?", [
      L("Mientras se prepara", "CABECERA A 30°", ["Normocapnia", "Suero isotónico"], path=True),
      L("Sí", "Drenaje ventricular externo", ["Neurocirugía"])], path=True),
  banda=B("Así se ve la hidrocefalia", P("hidrocefalia.jpg", 280, 268, [
            ("flecha", 0.40, 0.45, 0.70, 0.92, "ventrículos muy dilatados")],
          credito="Hellerhoff" + CC + "CC BY-SA 4.0"),
          [("Ventrículos grandes", "Negros y redondeados: el LCR no sale."),
           ("Surcos borrados", "El cerebro está comprimido."),
           ("Aguda", "Cefalea, vómitos, somnolencia: urgencia."),
           ("Drenaje", "Ventriculostomía externa o derivación.")],
          pie="TC de otro paciente (hidrocefalia crónica).", ans=0))

# GIN-095 · Epilepsia en el embarazo: levetiracetam · TARJETAS
S("tarjetas", "GIN-095", "Gestante con epilepsia: el fármaco de elección por su seguridad fetal es el levetiracetam (o lamotrigina)",
  "Embarazo y enfermedades neurológicas · epilepsia",
  ("Antiepilépticos en el embarazo", ["Las convulsiones dañan a la madre y al feto: no suspender el tratamiento.",
                                      "Levetiracetam y lamotrigina tienen el menor riesgo de malformaciones; el valproato es el peor."]),
  ("Primigesta de 24 semanas", ["Primer control prenatal.", "Antecedente de epilepsia."]),
  ["Monoterapia a la menor dosis eficaz; medir niveles (bajan en el embarazo).",
   "Ácido fólico (0,4-5 mg) antes y durante el embarazo.",
   "Valproato: defectos del tubo neural y menor coeficiente intelectual: evitarlo en mujeres fértiles."],
  "ILAE, epilepsia en mujeres (2023); MHRA/EMA, valproato (2024); " + ACOG + ".",
  op=("¿Fármaco?", ["Malformaciones: menos usado", "Sedante, malformaciones", "No: el más teratógeno", "Sí: el más seguro", "Hidantoína fetal"]),
  d=dict(rotulo="Antiepilépticos: riesgo en el embarazo", ans=0,
         cards=[dict(titulo="Levetiracetam", datos=[("Malformaciones", "Riesgo bajo", True), ("Uso", "Elección", True), ("Ojo", "Niveles bajan", True)],
                     pie="Este caso."),
                dict(titulo="Lamotrigina", datos=[("Malformaciones", "Riesgo bajo", False), ("Uso", "Alternativa", False), ("Ojo", "Ajustar dosis", False)],
                     pie="También segura."),
                dict(titulo="Valproato", datos=[("Malformaciones", "Muy alto", False), ("Tubo neural", "Sí", False), ("Uso", "Evitar", False)],
                     pie="Prohibido si es posible."),
                dict(titulo="Fenitoína / carbamazepina", datos=[("Riesgo", "Intermedio", False), ("Fenitoína", "Hidantoína fetal", False), ("Carbamazepina", "Tubo neural", False)],
                     pie="Segunda línea.")]))

# CAR-040 · Choque cardiogénico · ÁRBOL + Killip
S("arbol", "CAR-040", "Infarto de 24 horas con PA 90/60, ingurgitación yugular y crepitantes en ambas bases: choque cardiogénico, inotrópicos",
  "Síndrome coronario agudo · choque cardiogénico",
  ("Choque cardiogénico", ["El corazón infartado no bombea: hipotensión con signos de congestión e hipoperfusión.",
                           "La orina con sodio bajo muestra que el riñón percibe poco flujo (prerrenal)."]),
  ("Varón de 52 años, infarto de 24 h", ["PA 90/60, FC 100, FR 26; yugulares ingurgitadas; crepitantes en ambas bases.",
                                         "Na urinario < 20, FeNa < 1 %."]),
  ["Soporte: noradrenalina si la PA es muy baja + inotrópico (dobutamina) para el gasto.",
   "Revascularización urgente de la arteria culpable (angioplastia) es lo que más baja la mortalidad.",
   "No dar nitratos ni diuréticos en exceso con hipotensión; asistencia mecánica en casos seleccionados."],
  ESC + ", síndromes coronarios agudos (2023); AHA, choque cardiogénico (2017); SCAI (2022).",
  op=("¿Inicial?", ["No: 24 h y en choque se prefiere angioplastia", "No: está hipotenso", "No es lo primero", "Sí: sostiene el gasto",
                    "No: baja más la presión"]),
  arbol=Q("Infarto con hipotensión y congestión: ¿choque cardiogénico?", [
      L("Sí (este caso)", "INOTRÓPICOS + REVASCULARIZAR", ["Noradrenalina si PA muy baja", "Angioplastia urgente"], path=True),
      L("No: congestión sin hipotensión", "Diurético, vasodilatador", ["Killip II-III"])], path=True),
  escala=dict(nombre="Clasificación de Killip-Kimball", orden=True,
              que="Gravedad del infarto por la insuficiencia cardiaca al examen.",
              grados=[("Killip I", "Sin insuficiencia", ["Sin crepitantes"]), ("Killip II", "Leve", ["Crepitantes en bases, S3"]),
                      ("Killip III", "Edema pulmonar", ["Crepitantes en todo el pulmón"]), ("Killip IV", "Choque cardiogénico", ["Hipotensión, hipoperfusión"])],
              caso=3, porque=[("PA 90/60 con hipoperfusión renal", True), ("Crepitantes e ingurgitación yugular", True)],
              conducta="Soporte con inotrópicos y revascularización urgente."))

# SP-065 · Prevención del VIH en adolescentes: colegio · TARJETAS
S("tarjetas", "SP-065", "Para un plan educativo de prevención del VIH en adolescentes, el ámbito priorizado es el colegio",
  "Promoción de la salud · escenarios",
  ("Escenarios de la promoción de la salud", ["Se interviene donde está la población objetivo: los adolescentes están en el colegio.",
                                              "Instituciones educativas saludables: educación sexual integral."]),
  ("Distrito con aumento de VIH en adolescentes", ["Plan de comunicación educativa.", "Prevención y control de la transmisión."]),
  ["Educación sexual integral: condón, PrEP, pruebas rápidas, retrasar el inicio sexual.",
   "Coordinar con la familia y los servicios diferenciados para adolescentes.",
   "Hospital y penal no son el ámbito para este grupo."],
  MINSA + ", programa de instituciones educativas saludables; ONUSIDA (2024).",
  op=("¿Ámbito?", ["Importa, pero el acceso masivo es la escuela", "No: ya infectado", "Sí: ahí están los adolescentes", "No: es asistencial",
                   "No: otra población"]),
  d=dict(rotulo="¿Dónde llegar a la población objetivo?", ans=0,
         cards=[dict(titulo="Colegio", datos=[("Llega a", "Casi todos los adolescentes", True), ("Programa", "Escuelas saludables", True), ("Tema", "Educación sexual", True)],
                     pie="Este caso."),
                dict(titulo="Familia", datos=[("Rol", "Apoyo", False), ("Alcance", "Desigual", False), ("Complementa", "Sí", False)],
                     pie="Aliada."),
                dict(titulo="Hospital", datos=[("Rol", "Diagnóstico, tratamiento", False), ("Llega a", "Enfermos", False), ("Prevención", "Poca", False)],
                     pie="Asistencial."),
                dict(titulo="Centro penitenciario", datos=[("Población", "Adultos privados de libertad", False), ("Riesgo", "Alto", False), ("Aquí", "No", False)],
                     pie="Otra población.")]))

# GAS-036 · Falla hepática aguda por paracetamol · ÁRBOL + criterios del King's College
S("arbol", "GAS-036", "Joven que se automedicó con paracetamol y presenta ictericia, encefalopatía con asterixis, INR 6 e hipoglucemia: falla hepática aguda, N-acetilcisteína",
  "Hígado · falla hepática aguda",
  ("Falla hepática aguda por paracetamol", ["Coagulopatía (INR ≥ 1,5) + encefalopatía en alguien sin hepatopatía previa.",
                                            "La N-acetilcisteína sirve incluso tarde: mejora la supervivencia."]),
  ("Varón de 27 años", ["5 días tomando paracetamol por «migraña».",
                        "Ictericia, desorientación, asterixis, gingivorragia; INR 6, glucosa 65, creatinina 1,9, pH 7,32."]),
  ["N-acetilcisteína EV ya; UCI; glucosa, vigilar edema cerebral.",
   "Avisar a un centro de trasplante; criterios del King's College para listar.",
   "Vitamina K no corrige (no es déficit); plasma solo si sangra o para procedimientos."],
  "EASL, falla hepática aguda (2017); AASLD (2011, act.); criterios del King's College.",
  op=("¿Tratamiento?", ["Sí: antídoto aun tarde", "No: ya no hay fármaco en el estómago", "Se evalúa, pero primero NAC", "No: no es déficit de vitamina K",
                        "Para la acidosis o la falla renal, no lo primero"]),
  arbol=Q("Hepatotoxicidad por paracetamol con encefalopatía: ¿cumple criterios del King's College?", [
      L("Aún no (este caso)", "N-ACETILCISTEÍNA + UCI", ["Contactar centro de trasplante"], path=True),
      L("Sí", "Listar para trasplante", ["Urgente"])], path=True),
  triada=TR([("pH < 7,30 tras reanimar", "7,32", False), ("INR > 6,5", "6", False), ("Creatinina > 3,4", "1,9", False),
             ("Encefalopatía grado III-IV", "Desorientado, asterixis", None)],
            [("Criterios del King's College (paracetamol)", 0, 3)],
            "pH < 7,30 solo, o los otros tres juntos: indicar trasplante."))
