"""Entrega 1 · tanda 18 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, DOS, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, AAP, AHA
from esc28 import GLASGOW_TEC

CC = " · Wikimedia Commons · "

# GIN-059 · Atonía uterina · ÁRBOL + choque obstétrico + 4 T
S("arbol", "GIN-059", "Hemorragia posparto masiva tras un feto de 4100 g con útero blando a nivel del ombligo y choque: atonía uterina",
  "Hemorragia posparto · atonía uterina",
  ("Atonía uterina", ["El útero no se contrae tras el alumbramiento: la causa más común de hemorragia posparto (70 %).",
                      "Factores: feto grande, parto prolongado, embarazo múltiple, polihidramnios, infección."]),
  ("Mujer de 30 años", ["Expulsivo prolongado; recién nacido de 4100 g; alumbramiento normal.",
                        "Sangrado abundante; PA 50/20, FC 120, sopor; útero blando a nivel del ombligo."]),
  ["Activar la clave roja: masaje uterino bimanual + oxitocina; luego ergometrina o misoprostol, ácido tranexámico 1 g EV.",
   "Si no cede: balón intrauterino, suturas compresivas (B-Lynch), ligaduras arteriales o histerectomía.",
   "Reponer volumen y sangre según el grado de choque."],
  OMS + ", hemorragia posparto (2023); " + MINSA + ", claves obstétricas; " + WILLIAMS + ".",
  op=("¿Diagnóstico?", ["No explica el útero blando", "No: trastorno plaquetario raro", "No: el alumbramiento fue normal",
                        "Sí: útero blando + feto grande", "No: sin cicatriz ni partes fetales palpables"]),
  arbol=Q("Hemorragia posparto: ¿cómo está el útero?", [
      L("Blando, sobre el ombligo (este caso)", "ATONÍA UTERINA", ["Masaje + oxitocina", "Clave roja"], path=True),
      L("Contraído", "Buscar trauma, tejido o coagulopatía", ["Revisar canal y placenta"])], path=True),
  escala=dict(nombre="Grado de choque en la hemorragia obstétrica", orden=True, que="Estima la pérdida por los signos de la madre.",
              grados=[("Compensado", "10-15 %", ["Signos normales"]), ("Leve", "16-25 %", ["Taquicardia leve, sudor"]),
                      ("Moderado", "26-35 %", ["FC > 100, PA 70-80, agitación"]), ("Grave", "> 35 %", ["PA < 70", "Sopor o coma"])],
              caso=3, porque=[("PA 50/20", True), ("Sopor", True)],
              conducta="Clave roja: dos vías, sangre, uterotónicos y control del sangrado."),
  triada=TR([("Tono", "Útero blando", True), ("Trauma", "No se informa", False), ("Tejido", "Alumbramiento normal", False),
             ("Trombina", "No se informa", False)],
            [("Las 4 T de la hemorragia posparto", 0, 3)],
            "Es el tono: atonía uterina; revisar igual el canal y la placenta.", rotulo="Causas con nombre propio"))

# PED-070 · Alimentación complementaria · RADIAL
S("radial", "PED-070", "Para prevenir la anemia al iniciar la alimentación complementaria: incluir a diario alimentos de origen animal",
  "Nutrición infantil · prevención de la anemia",
  ("Alimentación complementaria", ["Desde los 6 meses la leche materna ya no cubre el hierro: se agregan otros alimentos.",
                                   "El hierro de origen animal (sangrecita, hígado, bazo, carnes) se absorbe mejor."]),
  ("Lactante de 5 meses", ["Control de crecimiento y desarrollo.", "La madre pide orientación para iniciar la alimentación complementaria."]),
  ["Seguir con la lactancia materna; iniciar alimentos a los 6 meses.",
   "Dar cada día alimentos de origen animal ricos en hierro + frutas con vitamina C.",
   "Gotas de hierro preventivas desde los 4 meses (MINSA)."],
  MINSA + ", norma técnica de manejo de la anemia (2017, act. 2024); " + OMS + ", alimentación complementaria (2023).",
  op=("¿Indicación?", ["No: frutas y sopas tienen poco hierro", "No: la leche materna es mejor", "Sí: hierro hem, mejor absorbido",
                       "No: se continúa la lactancia", "No: causa sangrado intestinal y anemia"]),
  d=dict(rotulo="Alimentación complementaria contra la anemia", centro="ORIGEN ANIMAL", centro_sub="todos los días", ans=0,
         items=[("HIERRO HEM", ["Sangrecita, hígado, bazo, carnes"]), ("GOTAS DE HIERRO", ["Desde los 4 meses"]),
                ("LACTANCIA", ["Continuar hasta los 2 años"]), ("CONSISTENCIA", ["Papillas espesas, no sopas"]),
                ("VITAMINA C", ["Frutas con las comidas"])],
         ruta=["Seguir lactancia", "Iniciar a los 6 meses", "Hierro animal diario", "Control de hemoglobina"]))

# REU-018 · Líquido sinovial inflamatorio · ÁRBOL + clasificación
S("arbol", "REU-018", "Rodilla dolorosa y aumentada de volumen con 12 000 leucocitos en el líquido sinovial: líquido inflamatorio",
  "Reumatología · análisis del líquido sinovial",
  ("Líquido sinovial", ["Los leucocitos del líquido separan lo mecánico, lo inflamatorio y lo séptico.",
                        "Además se mira el aspecto, los cristales y el Gram y cultivo."]),
  ("Mujer de 45 años", ["Tras una larga caminata, dolor y aumento de volumen de la rodilla izquierda.", "Artrocentesis: 12 000 leucocitos/mm³."]),
  ["Inflamatorio (2000-50 000): gota, seudogota, artritis reumatoide, artritis reactiva.",
   "Buscar cristales con luz polarizada y pedir Gram y cultivo siempre.",
   "> 50 000 con predominio de neutrófilos: tratar como séptico hasta tener el cultivo."],
  HARRISON + "; EULAR, recomendaciones de líquido sinovial (2017).",
  op=("¿Clasificación?", ["No: < 50 000", "No: > 200", "Sí: 2000-50 000", "No: no es sangre", "No: > 2000"]),
  arbol=Q("Líquido sinovial: ¿cuántos leucocitos?", [
      L("2000-50 000: 12 000 (este caso)", "INFLAMATORIO", ["Buscar cristales", "Gram y cultivo"], path=True),
      L("> 50 000", "Séptico", ["Antibiótico y lavado"])], path=True),
  escala=dict(nombre="Clasificación del líquido sinovial", orden=True, que="Por los leucocitos por mm³.",
              grados=[("< 200", "Normal", ["Claro, viscoso"]), ("200-2000", "Mecánico", ["Artrosis, trauma"]),
                      ("2000-50 000", "Inflamatorio", ["Gota, artritis reumatoide"]), ("> 50 000", "Séptico", ["Turbio, neutrófilos"])],
              caso=2, porque=[("12 000 leucocitos/mm³", True), ("Falta ver cristales y cultivo", False)],
              conducta="Cristales con luz polarizada, Gram y cultivo."))

# NEF-029 · Aplastamiento: CPK · ÁRBOL
S("arbol", "NEF-029", "Ambos miembros inferiores aplastados por una pared y oligoanuria horas después: CPK total para diagnosticar rabdomiólisis",
  "Lesión renal aguda · síndrome de aplastamiento",
  ("Rabdomiólisis por aplastamiento", ["El músculo dañado libera CPK, mioglobina y potasio.",
                                       "La mioglobina daña los túbulos: oligoanuria."]),
  ("Varón de 23 años", ["Pared caída sobre ambos miembros inferiores.", "Horas después, oligoanuria."]),
  ["CPK > 5 veces el límite (en el aplastamiento suele pasar de 5000 U/L) confirma.",
   "Orina oscura con tira positiva para sangre y sin hematíes: mioglobinuria.",
   "Líquidos abundantes, controlar potasio (ECG) y síndrome compartimental; diálisis si hace falta."],
  "Renal Disaster Relief Task Force, síndrome de aplastamiento (2012); " + HARRISON + ".",
  op=("¿Examen?", ["No: no confirma la rabdomiólisis", "Ayuda, pero no confirma", "Sí: marca el daño muscular", "No es diagnóstico",
                   "No: no es una infección"]),
  arbol=Q("Aplastamiento con oligoanuria: ¿CPK?", [
      L("Muy alta (esperado)", "RABDOMIÓLISIS", ["Líquidos EV", "Vigilar potasio"], path=True),
      L("Normal", "Otra causa de oliguria", ["Hipovolemia, obstrucción"])], path=True))

# OFT-015 · Glaucoma agudo · ÁRBOL
S("arbol", "OFT-015", "Asmática alérgica a sulfas con dolor y pérdida brusca de visión, edema corneal y ángulo cerrado: glaucoma agudo, manitol",
  "Oftalmología · glaucoma de ángulo cerrado",
  ("Glaucoma agudo de ángulo cerrado", ["El iris tapa el ángulo de drenaje: la presión ocular sube muy rápido.",
                                        "Dolor intenso, visión borrosa con halos, ojo rojo, pupila media fija, náuseas."]),
  ("Mujer de 74 años", ["Pérdida brusca de visión del ojo derecho con dolor intenso; asmática y alérgica a sulfonamidas.",
                        "Edema corneal, ángulo cerrado, cámara anterior estrecha."]),
  ["Bajar la presión ya: manitol EV, pilocarpina, betabloqueador tópico y acetazolamida si no hay contraindicaciones.",
   "Aquí: timolol contraindicado por el asma; acetazolamida y dorzolamida (sulfas) por la alergia: queda el manitol.",
   "Tratamiento definitivo: iridotomía con láser en ambos ojos."],
  "AAO, Preferred Practice Pattern: glaucoma de ángulo cerrado (2020); Kanski, Oftalmología clínica 10.ª ed. (2024).",
  op=("¿Tratamiento?", ["Sí: sin conflicto con asma ni sulfas", "No: es sulfonamida", "No: betabloqueador en asmática",
                        "No: lento, no para la crisis", "No: es sulfonamida"]),
  arbol=Q("Glaucoma agudo: ¿qué fármaco puede recibir?", [
      L("Asma + alergia a sulfas (este caso)", "MANITOL EV", ["+ pilocarpina", "Luego iridotomía láser"], path=True),
      L("Sin contraindicaciones", "Acetazolamida + timolol + pilocarpina", ["Luego iridotomía"])], path=True))

# GIN-060 · Profilaxis tras pielonefritis en el embarazo · ÁRBOL
S("arbol", "GIN-060", "Gestante de 28 semanas con pielonefritis en resolución: nitrofurantoína diaria para prevenir la recurrencia",
  "Infección urinaria en el embarazo · profilaxis",
  ("Profilaxis tras pielonefritis en el embarazo", ["Hasta 1 de cada 4 recurre en el mismo embarazo.",
                                                    "Se previene con profilaxis antibiótica o vigilancia con urocultivos."]),
  ("Gestante de 28 semanas", ["Pielonefritis aguda en resolución.", "¿Cómo prevenir la reinfección?"]),
  ["Nitrofurantoína 50-100 mg cada noche hasta el parto (o 6 semanas después).",
   "Evitarla al final del embarazo si hay riesgo de hemólisis (déficit de G6PD); alternativa: cefalexina.",
   "Urocultivo de control tras el tratamiento."],
  ACOG + "; " + WILLIAMS + ".",
  op=("¿Manejo?", ["Mucha resistencia de E. coli", "Alternativa, pero menos práctica", "No detecta a tiempo", "Sí: profilaxis eficaz",
                   "No: riesgo de recurrencia"]),
  arbol=Q("Pielonefritis en resolución en una gestante", [
      L("Prevenir recurrencia (este caso)", "NITROFURANTOÍNA DIARIA", ["50-100 mg en la noche", "Hasta el parto"], path=True),
      L("Si no puede tomarla", "Cefalexina o urocultivos seriados", ["Tratar cada bacteriuria"])], path=True))

# NRL-018 · Ataque isquémico transitorio · ÁRBOL + ABCD²
S("arbol", "NRL-018", "Hipertensa con hemiplejia derecha y afasia que revierten en 15 minutos y TC normal: ataque isquémico transitorio",
  "Enfermedad cerebrovascular · AIT",
  ("Ataque isquémico transitorio (AIT)", ["Déficit neurológico focal que se resuelve en menos de 24 h (casi siempre < 1 h) sin infarto en la imagen.",
                                          "Alto riesgo de ictus en los días siguientes: es una urgencia."]),
  ("Mujer de 62 años, hipertensa", ["Hemiplejia derecha y afasia no fluente súbitas.", "Revierten por completo en 15 minutos; TC cerebral normal."]),
  ["Estudio urgente: RM con difusión, Doppler carotídeo, ECG/Holter (FA), glucosa y lípidos.",
   "Riesgo alto (ABCD² ≥ 4): aspirina + clopidogrel por 21 días; luego un antiagregante.",
   "Estenosis carotídea sintomática ≥ 50-70 %: endarterectomía en menos de 2 semanas."],
  "AHA/ASA, prevención secundaria del ictus (2021); ESO, AIT (2021).",
  op=("¿Diagnóstico?", ["No: cefalea brusca, no déficit que revierte", "No: la TC lo mostraría", "Es la causa posible, no el cuadro",
                        "Sí: déficit focal que revierte", "No: síntomas positivos que progresan, con cefalea"]),
  arbol=Q("Déficit focal que revierte por completo: ¿puntaje ABCD²?", [
      L("≥ 4 (este caso)", "AIT DE ALTO RIESGO", ["Aspirina + clopidogrel 21 días", "Estudio urgente"], path=True),
      L("< 4", "AIT de bajo riesgo", ["Antiagregante y estudio pronto"])], path=True),
  escala=dict(nombre="Puntaje ABCD²", modo="puntaje", que="Riesgo de ictus en los días que siguen a un AIT (0 a 7).",
              items=[("A", "Edad ≥ 60 (1)", "62", 1), ("B", "PA ≥ 140/90 al llegar (1)", "No se informa", None),
                     ("C", "Clínica: debilidad (2) o solo habla (1)", "Hemiplejia", 2), ("D", "Duración ≥ 60 (2) o 10-59 min (1)", "15 min", 1),
                     ("D", "Diabetes (1)", "No se informa", None)],
              total_txt="Total: 4 puntos o más",
              rangos=[("6-7", "Riesgo alto", "Hospitalizar"), ("4-5", "Moderado", "Estudio urgente + doble antiagregación"),
                      ("0-3", "Bajo", "Estudio pronto")],
              caso_rango=1, porque=[("Edad, hemiplejia y 15 minutos: 4 puntos", True), ("Si la PA está alta al llegar, suma 1", True)],
              conducta="RM, Doppler carotídeo, ECG y doble antiagregación por 21 días."))

# CIR-039 · Politraumatizado con Glasgow ≤ 8 · ÁRBOL + gravedad del TEC
S("arbol", "CIR-039", "Politraumatizado que abre los ojos al dolor, emite sonidos incomprensibles y cae en sopor: intubación orotraqueal",
  "Trauma · vía aérea (A del ABCDE)",
  ("Vía aérea en el politraumatizado", ["Glasgow ≤ 8 = no protege la vía aérea: intubar.",
                                        "La A va antes que cualquier otra cosa, con protección de la columna cervical."]),
  ("Varón de 28 años atropellado", ["PA 100/60, FC 110, FR 28, SatO₂ 92 % con FiO₂ 40 %; herida parietal; abdomen distendido; fractura de fémur.",
                                    "Abre los ojos al dolor, sonidos incomprensibles, vuelve al sopor."]),
  ["Intubación de secuencia rápida con inmovilización cervical en línea.",
   "Luego B (ventilación), C (control de sangrado: abdomen, fémur), D (TC cerebral).",
   "Evitar hipoxemia e hipotensión: duplican la mortalidad del TEC."],
  ATLS + "; Brain Trauma Foundation, 4.ª ed. (2016).",
  op=("¿Primera acción?", ["Sí: Glasgow ≤ 8, proteger la vía aérea", "Después del ABCDE", "No es la prioridad", "No se usa en el TEC",
                           "Después de asegurar la vía aérea"]),
  arbol=Q("Politraumatizado: ¿protege la vía aérea?", [
      L("No: Glasgow ≤ 8 (este caso)", "INTUBACIÓN OROTRAQUEAL", ["Secuencia rápida", "Collarín en línea"], path=True),
      L("Sí", "Oxígeno y seguir con B y C", ["Reevaluar"])], path=True),
  escala=GLASGOW_TEC(2, [("Ojos al dolor (2) y sonidos incomprensibles (2)", True), ("Con motor ≤ 4, Glasgow ≤ 8", True)],
                     "Intubar, luego TC cerebral y control del sangrado."))

# NEU-019 · Cáncer de pulmón: broncoscopia · ÁRBOL
S("arbol", "NEU-019", "Fumador con hemoptisis, baja de peso, BK negativo y masa suprahiliar de 5 cm: broncofibroscopia con biopsia",
  "Cáncer de pulmón · diagnóstico",
  ("Cáncer de pulmón", ["Fumador mayor con tos, hemoptisis y baja de peso: cáncer hasta demostrar lo contrario.",
                        "Masas centrales se biopsian por broncoscopia; periféricas por punción guiada por TC."]),
  ("Varón de 62 años", ["Fuma 2 paquetes al día; 3 meses de tos con hemoptisis y baja de 5 kg.", "BK negativo 3 veces; masa suprahiliar izquierda de 5 cm."]),
  ["Masa central: broncoscopia con biopsia (o EBUS para los ganglios).",
   "TC con contraste y PET-TC para estadificar, no para confirmar.",
   "Con el tipo histológico se piden mutaciones (EGFR, ALK) y PD-L1."],
  "NCCN, cáncer de pulmón de células no pequeñas (2025); ACCP, diagnóstico de cáncer de pulmón (2013).",
  op=("¿Confirma?", ["Sí: biopsia de una masa central", "Estadifica, no confirma", "Para lesiones periféricas", "No es de rutina",
                     "Poco sensible"]),
  arbol=Q("Masa pulmonar sospechosa: ¿central o periférica?", [
      L("Central, suprahiliar (este caso)", "BRONCOSCOPIA CON BIOPSIA", ["± EBUS"], path=True),
      L("Periférica", "Punción guiada por TC", ["Transtorácica"])], path=True))

# PSI-013 · Trastorno de adaptación · TARJETAS
S("tarjetas", "PSI-013", "Migrante a Lima hace 3 meses con insomnio, irritabilidad y desconfianza que sigue funcionando en el trabajo: trastorno de adaptación",
  "Trastornos relacionados con el estrés",
  ("Trastorno de adaptación", ["Síntomas emocionales o conductuales dentro de los 3 meses de un estresor identificable.",
                               "Malestar mayor de lo esperado, sin llegar a otro trastorno; se resuelve en menos de 6 meses."]),
  ("Mujer de 43 años", ["Llegó a Lima para trabajar hace 3 meses; insomnio, cambios de humor, irritabilidad.",
                        "Habla poco, desconfiada; trabaja bien; se alegra con noticias de su tierra."]),
  ["Psicoterapia breve y apoyo social; fármacos solo para síntomas puntuales (insomnio).",
   "Si cumple criterios de depresión mayor o ansiedad generalizada, se diagnostica eso.",
   "La desconfianza aquí es adaptativa; no hay delirios."],
  "DSM-5-TR (2022); CIE-11 (2022).",
  op=("¿Trastorno?", ["No: sin amnesia ni despersonalización", "No: sin síntomas físicos múltiples", "Sí: estresor + síntomas proporcionados",
                      "No: conserva la alegría y el trabajo", "No: sin delirios ni alucinaciones"]),
  d=dict(rotulo="Síntomas tras un cambio de vida: ¿cuál?", ans=0,
         cards=[dict(titulo="Trastorno de adaptación", datos=[("Estresor", "Migración", True), ("Inicio", "< 3 meses", True), ("Funciona", "Sí", True)],
                     pie="Este caso."),
                dict(titulo="Depresión mayor", datos=[("Ánimo", "Triste casi todo el día", False), ("Placer", "Perdido", False), ("Tiempo", "≥ 2 semanas", False)],
                     pie="Antidepresivo."),
                dict(titulo="Esquizofrenia paranoide", datos=[("Síntoma", "Delirios", False), ("Percepción", "Alucinaciones", False), ("Tiempo", "≥ 6 meses", False)],
                     pie="Antipsicótico."),
                dict(titulo="Trastorno por estrés postraumático", datos=[("Estresor", "Amenaza grave", False), ("Síntoma", "Reexperimenta", False),
                                                                         ("Tiempo", "> 1 mes", False)],
                     pie="Psicoterapia.")]))

# PED-071 · Atresia duodenal · ÁRBOL
S("arbol", "PED-071", "Neonato con síndrome de Down, vómitos biliosos y distensión en el 2.º día: atresia duodenal",
  "Cirugía neonatal · obstrucción duodenal",
  ("Atresia duodenal", ["Falta de recanalización del duodeno; 30 % tiene síndrome de Down.",
                        "Vómitos biliosos (si es distal a la ampolla) desde el 1.er-2.º día; Rx con «doble burbuja»."]),
  ("Neonato a término con trisomía 21", ["Intolerancia oral, vómitos biliosos.", "Abdomen moderadamente distendido, timpánico, sin irritación peritoneal."]),
  ["Rx de abdomen: doble burbuja (estómago y duodeno) sin aire distal.",
   "Sonda orogástrica, líquidos EV, corregir electrolitos; duodenoduodenostomía.",
   "Si hay aire distal y vómito bilioso: descartar malrotación con vólvulo (urgencia)."],
  NELSON + "; APSA, obstrucción intestinal neonatal.",
  op=("¿Diagnóstico?", ["Sí: Down + vómito bilioso precoz", "No: salivación, la sonda no pasa", "No: vómito no bilioso a las 2-8 semanas",
                        "No: distensión mayor, más tarde", "No: sin meconio, sin vómito bilioso tan precoz"]),
  arbol=Q("Vómito bilioso en el neonato: Rx de abdomen", [
      L("Doble burbuja sin aire distal (esperado)", "ATRESIA DUODENAL", ["Sonda, líquidos", "Duodenoduodenostomía"], path=True),
      L("Aire distal, deterioro", "Malrotación con vólvulo", ["Cirugía urgente"])], path=True))

# PED-072 · Sarampión · TARJETAS + fotos reales
S("tarjetas", "PED-072", "Niña con fiebre, catarro intenso, conjuntivitis, manchas en la mucosa yugal y exantema morbiliforme confluente: sarampión, preguntar por la vacuna",
  "Enfermedades exantemáticas · sarampión",
  ("Sarampión", ["Virus muy contagioso: fiebre alta con las «3 C» (tos, coriza, conjuntivitis).",
                 "Manchas de Koplik y luego exantema que baja de la cara a los pies y confluye."]),
  ("Niña de 2 años", ["5 días de fiebre, catarro intenso, conjuntivitis, fotofobia y tos seca.",
                      "Manchas en la mucosa yugal; exantema maculopapular rojo vinoso y confluente."]),
  ["Preguntar la vacuna SPR: un niño no vacunado con este cuadro es sarampión hasta demostrar lo contrario.",
   "Caso sospechoso: notificación inmediata, aislamiento respiratorio, IgM y PCR.",
   "Vitamina A (2 dosis) a todos; vacunar a los contactos en 72 h."],
  OMS + ", sarampión (2024); " + MINSA + ", vigilancia de sarampión; " + CDC + ", Pink Book (2024).",
  op=("¿Antecedente?", ["Sí: no vacunado = alta sospecha", "No: vesículas, no maculopápulas", "No: urticaria, no catarro ni Koplik",
                        "No: rickettsiosis, sin catarro", "No: exantema en lija, sin Koplik"]),
  d=dict(rotulo="Exantema con fiebre: ¿cuál?", ans=0,
         cards=[dict(titulo="Sarampión", datos=[("Antes", "3 C + Koplik", True), ("Exantema", "Confluente, baja", True), ("Vacuna", "Sin SPR", True)],
                     pie="Este caso."),
                dict(titulo="Rubéola", datos=[("Fiebre", "Leve", False), ("Ganglios", "Retroauriculares", False), ("Exantema", "No confluye", False)],
                     pie="Más leve."),
                dict(titulo="Escarlatina", datos=[("Exantema", "En lija", False), ("Lengua", "Aframbuesada", False), ("Germen", "Estreptococo", False)],
                     pie="Penicilina."),
                dict(titulo="Varicela", datos=[("Lesión", "Vesículas", False), ("Estadios", "Distintos", False), ("Prurito", "Sí", False)],
                     pie="Aciclovir si hay riesgo.")]),
  banda=B("Así se ve el sarampión", DOS(
            P("koplik.jpg", 220, 160, [("circulo", 0.555, 0.64, 0.17, "manchas de Koplik", 0.30, 0.10)],
              credito="CDC (PHIL 6111) · dominio público"),
            P("sarampion_exantema.jpg", 220, 152, [("flecha", 0.47, 0.24, 0.50, 0.88, "máculas y pápulas\nque confluyen")],
              credito="CDC (PHIL 4497) · dominio público"),
            vertical=True),
          [("Manchas de Koplik", "Puntos blancos como granos de sal en la mucosa de la mejilla, frente a los molares."),
           ("Salen antes del exantema", "1-2 días antes; si no se ven, no descartan."),
           ("Exantema que confluye", "Empieza detrás de las orejas y baja; se une en placas."),
           ("Deja descamación", "Se aclara en el mismo orden en que apareció.")],
          pie="Fotos de otros pacientes.", ans=0))

# PED-073 · Intoxicación por insecticidas · TARJETAS + signos
S("tarjetas", "PED-073", "Adolescente que ayuda en la cosecha de uvas con cólicos, vómitos, diarrea y fasciculaciones: intoxicación por insecticidas",
  "Toxicología · plaguicidas",
  ("Intoxicación por organofosforados", ["Inhiben la acetilcolinesterasa: efectos muscarínicos (cólico, diarrea, secreciones) y nicotínicos (fasciculaciones).",
                                         "En el campo, la vía cutánea y respiratoria es común."]),
  ("Adolescente de 15 años", ["Primera vez en la cosecha de uvas.", "Dolor abdominal tipo retortijón, vómitos, diarrea y fasciculaciones."]),
  ["Retirar la ropa, lavar la piel con agua y jabón (con guantes).",
   "Atropina EV hasta secar los bronquios; pralidoxima temprana.",
   "Notificar: intoxicación por plaguicidas es de vigilancia obligatoria."],
  OMS + ", manejo de intoxicaciones por plaguicidas; " + MINSA + ", guía de intoxicación por plaguicidas.",
  op=("¿Sospecha?", ["No: no da fasciculaciones", "No: sudor y temblor, no diarrea", "No: hay signos físicos objetivos",
                     "Sí: exposición agrícola + colinérgico", "No: no da fasciculaciones"]),
  d=dict(rotulo="Cólico y vómitos en el campo: ¿cuál?", ans=0,
         cards=[dict(titulo="Organofosforado", datos=[("Exposición", "Cosecha", True), ("Músculo", "Fasciculaciones", True), ("Intestino", "Cólico, diarrea", True)],
                     pie="Este caso."),
                dict(titulo="Intoxicación alimentaria", datos=[("Exposición", "Comida", False), ("Músculo", "Normal", False), ("Pupilas", "Normales", False)],
                     pie="Hidratación."),
                dict(titulo="Gastroenteritis viral", datos=[("Fiebre", "Puede", False), ("Músculo", "Normal", False), ("Contagio", "Familia", False)],
                     pie="Soporte."),
                dict(titulo="Hipoglucemia", datos=[("Síntoma", "Sudor, temblor", False), ("Glucosa", "Baja", False), ("Diarrea", "No", False)],
                     pie="Glucosa.")]),
  triada=TR([("Cólico abdominal", "Retortijón", True), ("Vómitos y diarrea", "Sí", True), ("Fasciculaciones", "Sí", True),
             ("Miosis", "No se informa", False), ("Secreciones (sudor, saliva)", "No se informa", False)],
            [("Síndrome colinérgico", 0, 4)],
            "Cólico + diarrea + fasciculaciones tras exposición agrícola: organofosforado.", rotulo="Síndrome con nombre propio"))

# SP-046 · ASIS: análisis del entorno · RADIAL
S("radial", "SP-046", "Describir cuántos adultos mayores hay, su sexo, su pobreza y su seguro: fase de análisis del entorno del ASIS",
  "Gestión en salud · análisis de situación de salud",
  ("Análisis de situación de salud (ASIS)", ["Proceso para conocer la salud de una población y decidir qué hacer.",
                                             "Empieza por el entorno: demografía, economía, educación, seguro."]),
  ("Centro de salud I-4", ["Aumentó la población adulta mayor: 60 % mujeres.", "95 % en pobreza extrema; 90 % con SIS."]),
  ["Entorno: características demográficas y socioeconómicas de la población (determinantes).",
   "Luego: estado de salud (morbilidad y mortalidad) y oferta de servicios.",
   "Después: priorizar problemas y definir líneas de acción."],
  MINSA + ", guía técnica para el análisis de situación de salud local (2015).",
  op=("¿Fase?", ["Viene después", "Es otro paso del plan", "Es la última etapa", "Sí: población y su contexto", "Es posterior a la acción"]),
  d=dict(rotulo="Etapas del ASIS", centro="ANÁLISIS DEL ENTORNO", centro_sub="este caso", ans=0,
         items=[("ENTORNO", ["Demografía, pobreza, seguro"]), ("ESTADO DE SALUD", ["Enfermedad y muerte"]),
                ("OFERTA", ["Servicios y recursos"]), ("PRIORIZACIÓN", ["Problemas más importantes"]), ("LÍNEAS DE ACCIÓN", ["Qué hacer"])],
         ruta=["Describir la población", "Medir su salud", "Priorizar", "Planificar"]))

# REU-019 · Arteritis de células gigantes · ÁRBOL + ACR/EULAR 2022
S("arbol", "REU-019", "Mayor con cefalea, dolor temporal, claudicación mandibular, amaurosis y VSG de 150: arteritis de células gigantes, corticoides",
  "Vasculitis de vasos grandes · arteritis de células gigantes",
  ("Arteritis de células gigantes (temporal)", ["Vasculitis de mayores de 50 años que afecta las ramas de la carótida externa y la oftálmica.",
                                                "Riesgo de ceguera irreversible: se trata con la sola sospecha."]),
  ("Varón de 65 años", ["5 meses de fiebre, cefalea y artralgias.",
                        "Dolor temporal a la presión, claudicación mandibular, amaurosis bilateral; Hb 8,5, VSG 150."]),
  ["Con pérdida visual: metilprednisolona EV en pulsos; luego prednisona 40-60 mg/día.",
   "Confirmar con ecografía de temporales (signo del halo) o biopsia, sin retrasar el tratamiento.",
   "Tocilizumab ahorra corticoides; aspirina no se da de rutina."],
  "ACR/EULAR, criterios de arteritis de células gigantes (2022); EULAR, vasculitis de vasos grandes (2023).",
  op=("¿Conducta?", ["No: no es de primera línea", "Ahorrador de corticoide, no inicial", "No de rutina", "Sí: evita más ceguera",
                     "No: no controlan la vasculitis"]),
  arbol=Q("Mayor de 50 con cefalea temporal y VSG alta: ¿pérdida visual?", [
      L("Sí: amaurosis (este caso)", "CORTICOIDES EV YA", ["Metilprednisolona en pulsos", "Luego biopsia o eco"], path=True),
      L("No", "Prednisona oral", ["40-60 mg/día"])], path=True),
  escala=dict(nombre="Criterios ACR/EULAR 2022 (arteritis de células gigantes)", modo="puntaje",
              que="Requisito: edad ≥ 50; con ≥ 6 puntos se clasifica como ACG.",
              items=[("V", "Pérdida visual súbita (3)", "Amaurosis bilateral", 3), ("M", "Claudicación mandibular (2)", "Sí", 2),
                     ("C", "Cefalea temporal nueva (2)", "Sí", 2), ("T", "Dolor del cuero cabelludo o temporal (2)", "Sí", 2),
                     ("S", "VSG ≥ 50 o PCR ≥ 10 (3)", "VSG 150", 3)],
              total_txt="Total: 12 puntos",
              rangos=[("≥ 6", "Arteritis de células gigantes", "Tratar"), ("< 6", "No clasifica", "Buscar otra causa")],
              caso_rango=0, porque=[("Amaurosis, mandíbula, cefalea, temporal y VSG", True)],
              conducta="Pulsos de metilprednisolona y luego prednisona; confirmar con eco o biopsia."))

# END-016 · Hipertiroidismo · TARJETAS
S("tarjetas", "END-016", "Baja de peso con apetito aumentado, intolerancia al calor, sudoración, taquicardia y PA diferencial amplia: hipertiroidismo",
  "Tiroides · hipertiroidismo",
  ("Hipertiroidismo", ["Exceso de hormona tiroidea: todo se acelera.",
                       "Baja de peso con apetito aumentado, calor, sudoración, temblor, taquicardia, PA diferencial amplia."]),
  ("Mujer de 34 años", ["Baja de 6 kg en un mes con más apetito y sed; intolerancia al calor, sudoración.",
                        "PA 120/50, FC 120, 37,5 °C, piel húmeda y caliente."]),
  ["Confirmar: TSH suprimida y T4 libre alta; luego la causa (anticuerpos TRAb, gammagrafía).",
   "Graves (la más común): metimazol; betabloqueador para los síntomas.",
   "Feocromocitoma: crisis con hipertensión y cefalea; ansiedad no da esta baja de peso."],
  "ATA, hipertiroidismo (2016); ETA, enfermedad de Graves (2018).",
  op=("¿Diagnóstico?", ["No: sin cefalea ni alteración visual", "Sí: hipermetabolismo", "No: daría hipertensión en crisis",
                        "No: daría poliuria y glucosa alta", "No: no explica tanta baja de peso"]),
  d=dict(rotulo="Baja de peso con taquicardia: ¿cuál?", ans=0,
         cards=[dict(titulo="Hipertiroidismo", datos=[("Apetito", "Aumentado", True), ("Calor", "No lo tolera", True), ("PA", "Diferencial amplia", True)],
                     pie="Este caso: TSH."),
                dict(titulo="Feocromocitoma", datos=[("PA", "Muy alta en crisis", False), ("Cefalea", "Sí", False), ("Patrón", "Paroxístico", False)],
                     pie="Metanefrinas."),
                dict(titulo="Diabetes", datos=[("Orina", "Poliuria", False), ("Glucosa", "Alta", False), ("Calor", "Normal", False)],
                     pie="Glucemia."),
                dict(titulo="Ansiedad", datos=[("Peso", "Estable o poco", False), ("Piel", "Fría, sudor", False), ("TSH", "Normal", False)],
                     pie="Diagnóstico de descarte.")]))

# GIN-061 · Mastitis puerperal · ÁRBOL
S("arbol", "GIN-061", "Puérpera de 2 semanas con fiebre y mama derecha roja, dolorosa e indurada: mastitis, antibiótico y seguimiento",
  "Puerperio · mastitis",
  ("Mastitis puerperal", ["Inflamación de la mama por mal vaciado; puede infectarse (S. aureus).",
                          "Mama roja, caliente, dolorosa, indurada, con fiebre y malestar."]),
  ("Puérpera de 2 semanas", ["Fiebre.", "Dolor, enrojecimiento e induración de la mama derecha."]),
  ["Seguir amamantando o extrayendo leche (vaciar la mama es parte del tratamiento).",
   "Antibiótico (dicloxacilina o cefalexina) si hay fiebre o no mejora en 24 h; analgesia y frío.",
   "Si no mejora en 48-72 h o hay masa fluctuante: ecografía para descartar absceso (aspiración o drenaje)."],
  "Academy of Breastfeeding Medicine, protocolo n.º 36: espectro de la mastitis (2022); " + OMS + ".",
  op=("¿Actitud?", ["Sí: fiebre e induración, sin absceso", "No: no se pide en la mastitis", "No: no hay masa sospechosa",
                    "Solo si hay absceso", "No: empeora; se sigue lactando"]),
  arbol=Q("Mama roja y dolorosa en el puerperio: ¿masa fluctuante?", [
      L("No: induración con fiebre (este caso)", "ANTIBIÓTICO Y SEGUIMIENTO", ["Seguir lactando", "Analgesia"], path=True),
      L("Sí", "Absceso", ["Ecografía y aspiración"])], path=True))

# GIN-062 · Rotura uterina · TARJETAS + signos
S("tarjetas", "GIN-062", "Cesareada anterior en trabajo de parto con dolor súbito, sangrado, partes fetales palpables y bradicardia fetal: rotura uterina",
  "Hemorragias de la segunda mitad del embarazo · rotura uterina",
  ("Rotura uterina", ["Se abre la pared del útero, casi siempre sobre una cicatriz de cesárea.",
                      "Dolor súbito, cese de contracciones, partes fetales bajo la piel, bradicardia fetal y choque."]),
  ("Tercigesta de 39 semanas", ["Cesárea previa con periodo intergenésico corto; dolor súbito y sangrado vaginal.",
                                "Partes fetales palpables; 3 cm, estación -3; líquido sanguinolento; FCF 100."]),
  ["Laparotomía de urgencia: extraer al feto y reparar el útero o hacer histerectomía.",
   "Reponer volumen y sangre; activar clave roja.",
   "Prevención: periodo intergenésico ≥ 18 meses y vigilar el parto vaginal tras cesárea."],
  ACOG + " Practice Bulletin n.º 205, parto vaginal tras cesárea (2019); " + WILLIAMS + ".",
  op=("¿Diagnóstico?", ["No: el útero estaría tenso, sin partes fetales palpables", "Sí: cicatriz + partes fetales + bradicardia",
                        "No: sangrado al romper membranas, sin dolor súbito", "No: indoloro", "No: es después del parto"]),
  d=dict(rotulo="Dolor y sangrado en el trabajo de parto: ¿cuál?", ans=0,
         cards=[dict(titulo="Rotura uterina", datos=[("Antecedente", "Cesárea", True), ("Feto", "Se palpa fuera", True), ("FCF", "Bradicardia", True)],
                     pie="Este caso: laparotomía."),
                dict(titulo="DPP", datos=[("Útero", "Tenso, contraído", False), ("Sangre", "Oscura", False), ("Feto", "Dentro", False)],
                     pie="Terminar gestación."),
                dict(titulo="Vasa previa", datos=[("Cuándo", "Al romper bolsa", False), ("Madre", "Estable", False), ("Feto", "Sangra", False)],
                     pie="Cesárea urgente."),
                dict(titulo="Placenta previa", datos=[("Dolor", "No", False), ("Útero", "Blando", False), ("Sangre", "Roja", False)],
                     pie="No tacto.")]),
  triada=TR([("Dolor súbito", "Sí", True), ("Partes fetales palpables", "Sí", True), ("Bradicardia fetal", "100", True),
             ("Ascenso de la presentación", "Estación -3", True), ("Cese de contracciones", "No se informa", False)],
            [("Signos de rotura uterina", 0, 4)],
            "Cuatro signos con cicatriz previa: laparotomía ya.", rotulo="Signos de alarma"))

# SP-047 · Determinantes sociales y TB · TARJETAS
S("tarjetas", "SP-047", "Aumento de tuberculosis con hacinamiento y desempleo en el ámbito: la mayor influencia son los determinantes sociales",
  "Salud pública · tuberculosis y determinantes sociales",
  ("Tuberculosis y determinantes sociales", ["La TB sigue a la pobreza: hacinamiento, desempleo, desnutrición, vivienda sin ventilación.",
                                             "Sin mejorar esas condiciones, los casos siguen apareciendo."]),
  ("Centro de salud", ["Aumenta la TB pulmonar con baciloscopia positiva.", "El ASIS muestra hacinamiento y más desempleo."]),
  ["Acción intersectorial: vivienda, empleo, alimentación (protección social).",
   "Además: búsqueda activa de sintomáticos respiratorios y tratamiento supervisado.",
   "La BCG no se aplica a adultos y no previene la TB pulmonar del adulto."],
  OMS + ", estrategia Fin de la TB (2015-2035); " + MINSA + ", norma técnica de tuberculosis (2023).",
  op=("¿Mayor influencia?", ["Importante, pero no explica el aumento", "Medida individual menor", "Sí: hacinamiento y desempleo",
                             "No se describe", "No: la BCG no se da a adultos"]),
  d=dict(rotulo="¿Qué explica más casos de TB?", ans=0,
         cards=[dict(titulo="Determinantes sociales", datos=[("Ejemplo", "Hacinamiento", True), ("También", "Desempleo", True), ("Acción", "Intersectorial", True)],
                     pie="Este caso."),
                dict(titulo="Captación", datos=[("Ejemplo", "Sintomáticos respiratorios", False), ("Acción", "Servicio de salud", False),
                                                ("Efecto", "Diagnóstico precoz", False)],
                     pie="Necesaria."),
                dict(titulo="TB resistente", datos=[("Causa", "Mal tratamiento", False), ("Prueba", "Sensibilidad", False), ("Aquí", "No descrita", False)],
                     pie="Tratamiento largo."),
                dict(titulo="BCG", datos=[("A quién", "Recién nacidos", False), ("Protege", "Formas graves infantiles", False), ("Adultos", "No", False)],
                     pie="No aplica.")]))

# NEF-030 · Cólico renal · TARJETAS
S("tarjetas", "NEF-030", "Dolor lumbar izquierdo súbito irradiado a la ingle, puñopercusión positiva, hematuria y cristales de oxalato: litiasis renal",
  "Urolitiasis · cólico renal",
  ("Cólico renal por litiasis", ["Un cálculo que baja por el uréter: dolor intenso en oleadas de la fosa lumbar a la ingle.",
                                 "Hematuria y, a veces, cristales en la orina."]),
  ("Mujer de 22 años", ["Dolor lumbar izquierdo súbito que va a la ingle y no calma con analgésicos.",
                        "Puñopercusión izquierda +++; hematíes 20-50, cristales de oxalato."]),
  ["Analgesia: AINE (diclofenaco o ketorolaco) primero; opioide si no cede.",
   "TC sin contraste (o ecografía) para ver tamaño y ubicación; tamsulosina si el cálculo es distal y < 10 mm.",
   "Fiebre con obstrucción: drenaje urgente (catéter doble J o nefrostomía)."],
  "EAU, guía de urolitiasis (2025).",
  op=("¿Diagnóstico?", ["No: disuria sin dolor lumbar", "No: interrumpe el chorro, dolor bajo", "Sí: cólico + hematuria + cristales",
                        "No: secreción uretral", "No: sin fiebre"]),
  d=dict(rotulo="Dolor lumbar agudo: ¿cuál?", ans=0,
         cards=[dict(titulo="Litiasis renal", datos=[("Dolor", "Cólico a la ingle", True), ("Orina", "Hematuria, cristales", True), ("Fiebre", "No", True)],
                     pie="Este caso."),
                dict(titulo="Pielonefritis", datos=[("Fiebre", "Sí", False), ("Orina", "Leucocitos", False), ("Dolor", "Continuo", False)],
                     pie="Antibiótico."),
                dict(titulo="Cistitis", datos=[("Síntoma", "Disuria", False), ("Lumbar", "No", False), ("Fiebre", "No", False)],
                     pie="Nitrofurantoína."),
                dict(titulo="Litiasis vesical", datos=[("Síntoma", "Chorro que se corta", False), ("Quién", "Varón mayor", False), ("Dolor", "Bajo", False)],
                     pie="Cistolitotomía.")]))

# PED-074 · Ganancia de peso insuficiente: visita domiciliaria · ÁRBOL
S("arbol", "PED-074", "Lactante de 5 meses con ganancia de peso insuficiente que dejó de acudir a sus controles: visita domiciliaria",
  "Crecimiento y desarrollo · seguimiento",
  ("Seguimiento del niño con ganancia inadecuada", ["Una ganancia de peso baja es una alerta temprana de desnutrición o enfermedad.",
                                                    "Si la familia no regresa, el equipo de salud va a la casa."]),
  ("Lactante de 5 meses", ["En su primer control: ganancia < 500 g al mes.", "No volvió a sus citas."]),
  ["Visita domiciliaria: ver cómo se alimenta, la lactancia, la higiene y el entorno; recuperar el control.",
   "Ganancia esperada a los 4-6 meses: unos 500-600 g/mes.",
   "Derivar solo si hay signos de alarma; denunciar solo si hay negligencia o maltrato evidente."],
  MINSA + ", norma técnica de control de crecimiento y desarrollo (NTS 137, 2017); " + OMS + ", patrones de crecimiento.",
  op=("¿Prioridad?", ["No: sin evidencia de maltrato", "Sí: recuperar el seguimiento", "No: no ha vuelto", "No: sin signos de alarma",
                      "No: sin evaluar la lactancia"]),
  arbol=Q("Niño con ganancia insuficiente que no vuelve: ¿qué hacer?", [
      L("Recuperar el seguimiento (este caso)", "VISITA DOMICILIARIA", ["Evaluar lactancia y entorno", "Reprogramar controles"], path=True),
      L("Signos de alarma o maltrato", "Referir o denunciar", ["Según el hallazgo"])], path=True))

# CB-023 · Monóxido de carbono · ÁRBOL + gravedad
S("arbol", "CB-023", "Cefalea, náuseas y confusión repetidas en una casa cerrada con estufa de gas y SatO₂ normal: monóxido de carbono, oxígeno al 100 %",
  "Toxicología · monóxido de carbono",
  ("Intoxicación por monóxido de carbono (CO)", ["El CO se une a la hemoglobina 200 veces más que el oxígeno: hipoxia de los tejidos.",
                                                 "Cefalea, náuseas, mareo, confusión; la SatO₂ del oxímetro sale normal (engaña)."]),
  ("Mujer de 54 años", ["Consultas repetidas por cefalea, náuseas y vómitos; casa cerrada con estufa de gas.",
                        "FC 120, FR 26, SatO₂ 95 %; desorientada, confusa, muy débil."]),
  ["Oxígeno al 100 % con mascarilla de no reinhalación: baja la vida media del CO de 5 h a ~1 h.",
   "Medir carboxihemoglobina (cooximetría); la SatO₂ normal no descarta.",
   "Cámara hiperbárica si hubo pérdida de conciencia, déficit neurológico, COHb > 25 % o embarazo."],
  "ACEP, política clínica de intoxicación por CO (2017); " + HARRISON + ".",
  op=("¿Terapia?", ["No: es otro gas", "Solo si no protege la vía aérea", "Sí: desplaza el CO", "No: sin oxígeno al 100 %", "No: no desplaza el CO"]),
  arbol=Q("Cefalea y confusión en ambiente cerrado: ¿sospecha de CO?", [
      L("Sí (este caso)", "OXÍGENO AL 100 %", ["Medir carboxihemoglobina", "Hiperbárica si es grave"], path=True),
      L("No", "Otras causas de cefalea", ["Evaluar"])], path=True),
  escala=dict(nombre="Gravedad de la intoxicación por CO", orden=True, que="Por los síntomas (la COHb ayuda, pero no siempre se correlaciona).",
              grados=[("Leve", "Cefalea, náuseas", ["Oxígeno al 100 %"]), ("Moderada", "Confusión, debilidad", ["Oxígeno al 100 %", "Valorar hiperbárica"]),
                      ("Grave", "Coma, convulsiones", ["Intubar", "Hiperbárica"])],
              caso=1, porque=[("Desorientada y confusa", True), ("Sin coma ni convulsiones", True)],
              conducta="Oxígeno al 100 %, cooximetría y valorar cámara hiperbárica."))

# REU-020 · Acné fulminante · TARJETAS
S("tarjetas", "REU-020", "Varón joven con acné grave y cicatricial en cara y tórax, fiebre, artralgias y leucocitosis: acné fulminante",
  "Dermatología · acné",
  ("Acné fulminante", ["Forma rara y grave: nódulos que se ulceran de golpe, con síntomas sistémicos.",
                       "Varones jóvenes; puede desencadenarse al iniciar isotretinoína."]),
  ("Varón de 24 años", ["Fiebre y artralgias.", "Acné severo con lesiones de distintos tipos, incluso cicatriciales, en cara y tórax; leucocitosis."]),
  ["Prednisona oral primero; luego isotretinoína a dosis bajas cuando la inflamación ceda.",
   "Los antibióticos solos no bastan.",
   "Acné conglobata: igual de grave en la piel, pero sin síntomas generales."],
  "AAD, guía de acné (2024); Bolognia Dermatology 5.ª ed. (2024).",
  op=("¿Tipo?", ["No: sin síntomas sistémicos", "Sí: acné grave + fiebre + artralgias", "No: sin fiebre ni artralgias",
                 "No: leve o moderado", "No: es otra enfermedad, sin comedones"]),
  d=dict(rotulo="Acné grave: ¿cuál?", ans=0,
         cards=[dict(titulo="Fulminante", datos=[("Fiebre", "Sí", True), ("Articulaciones", "Dolor", True), ("Sangre", "Leucocitosis", True)],
                     pie="Este caso."),
                dict(titulo="Conglobata", datos=[("Lesiones", "Nódulos con trayectos", False), ("Fiebre", "No", False), ("Cicatrices", "Sí", False)],
                     pie="Isotretinoína."),
                dict(titulo="Nódulo-quístico", datos=[("Lesiones", "Nódulos profundos", False), ("Fiebre", "No", False), ("Lugar", "Cara, espalda", False)],
                     pie="Isotretinoína."),
                dict(titulo="Rosácea", datos=[("Edad", "> 30", False), ("Comedones", "No", False), ("Gatillo", "Calor, alcohol", False)],
                     pie="Otra enfermedad.")]))

# GAS-021 · Pancreatitis por hipertrigliceridemia · ÁRBOL + Atlanta
S("arbol", "GAS-021", "Obeso con dolor epigástrico a la espalda, vómitos, choque, sopor, triglicéridos altos y amilasa normal: pancreatitis, hidratación EV",
  "Páncreas · pancreatitis por hipertrigliceridemia",
  ("Pancreatitis por hipertrigliceridemia", ["Triglicéridos > 1000 mg/dL causan pancreatitis; la amilasa puede salir normal (interferencia).",
                                             "Pedir lipasa y triglicéridos."]),
  ("Varón de 45 años, obeso", ["Dolor epigástrico a la espalda, vómitos biliosos incoercibles.",
                               "FC 120, PA 80/60, soporoso, dolor difuso, ictericia; triglicéridos altos, amilasa normal."]),
  ["Choque: hidratación EV con Ringer lactato en bolos guiados por metas (no excesiva: WATERFALL 2022).",
   "Insulina EV con glucosa baja los triglicéridos; plasmaféresis en casos seleccionados.",
   "UCI si hay falla de órganos; CPRE solo si hay colangitis; sin antibióticos profilácticos."],
  "ACG, pancreatitis aguda (2024); WATERFALL, NEJM (2022).",
  op=("¿Conducta inicial?", ["Sí: está en choque; guiada por metas", "Después, cuando tolere", "Solo si hay colangitis", "No: no se recomienda",
                             "Solo si la enteral falla"]),
  arbol=Q("Pancreatitis con hipotensión: ¿qué primero?", [
      L("Choque (este caso)", "HIDRATACIÓN EV", ["Ringer lactato en bolos", "Luego insulina para los TG"], path=True),
      L("Estable", "Hidratación moderada", ["1,5 mL/kg/h"])], path=True),
  escala=dict(nombre="Clasificación de Atlanta revisada (2012)", que="Se define por la falla de órganos y su duración.",
              grados=[("Leve", "Sin falla de órganos", ["Alta en días"]), ("Moderadamente grave", "Falla < 48 h", ["O complicaciones locales"]),
                      ("Grave", "Falla > 48 h", ["Mortalidad alta"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Choque y sopor: ya hay falla de órganos", True), ("Si dura más de 48 h será grave", True)],
              conducta="Reanimación con líquidos, UCI e insulina para los triglicéridos."))

# PED-075 · Estenosis pilórica · ÁRBOL + eco real
S("arbol", "PED-075", "Primogénito de un mes con vómitos en proyectil no biliosos, deshidratación y oliva epigástrica: hipertrofia del píloro",
  "Cirugía pediátrica · vómitos del lactante",
  ("Estenosis hipertrófica del píloro", ["Varón primogénito de 2-8 semanas; el músculo pilórico crece y obstruye.",
                                         "Vómitos en proyectil no biliosos y hambre después; oliva en el epigastrio."]),
  ("Primogénito de un mes", ["Vómitos en proyectil, no biliosos.", "Deshidratación moderada; tumoración pequeña en epigastrio; Rx: burbuja gástrica."]),
  ["Ecografía: músculo ≥ 3 mm y canal ≥ 15 mm.",
   "Corregir deshidratación y la alcalosis hipoclorémica e hipopotasémica antes de operar.",
   "Piloromiotomía de Ramstedt."],
  NELSON + "; APSA, estenosis pilórica (2023).",
  op=("¿Diagnóstico?", ["No: vómito bilioso", "No: vómito bilioso, doble burbuja", "Sí: vómito no bilioso + oliva",
                        "No: defecto de la pared visible al nacer", "No: regurgitación sin oliva ni deshidratación"]),
  arbol=Q("Lactante con vómitos: ¿son biliosos?", [
      L("No, en proyectil + oliva (este caso)", "HIPERTROFIA DEL PÍLORO", ["Ecografía", "Corregir alcalosis y operar"], path=True),
      L("Sí", "Obstrucción distal a la ampolla", ["Malrotación, atresia"])], path=True),
  banda=B("Ecografía real de estenosis pilórica", P("piloro.jpg", 300, 282, [
            ("circulo", 0.43, 0.72, 0.17, "músculo grueso\ny canal largo", 0.78, 0.9)],
          credito="Laughlin Dawes" + CC + "CC BY-SA 4.0"),
          [("Músculo engrosado", "Pared del píloro ≥ 3 mm (normal < 2 mm)."),
           ("Canal alargado", "El canal pilórico mide ≥ 15 mm y no se abre."),
           ("Estómago lleno", "El líquido no pasa al duodeno aunque el bebé haya comido."),
           ("La flecha roja", "Marca del autor sobre el píloro engrosado.")],
          pie="Ecografía de otro lactante (6 semanas).", ans=0))
