"""Bloque ENAM 2026 · Pediatría (parte 2)."""
from c26 import S, D, B, ILU, Q, L, NELSON, MINSA
import ilu7 as I

O = I.ORANGE
ESP = "PEDIATRÍA ENAM"
PALIDO = "#fdf3ec"
AMARILLO = "#fde68a"

# PED-257 · Hierro profiláctico inmediato en lactante con riesgo · CRONOLOGÍA
_pal = {k: PALIDO for k in ("cabeza", "torax", "abdomen", "brazo_d", "brazo_i", "pierna_d", "pierna_i")}
S("cronologia", "PED-257", "lactante-3-meses-corte-precoz-cordon-hierro-profilactico-inmediato",
  "Lactante de 3 meses con factores de riesgo de anemia: hierro profiláctico desde ahora",
  "Nutrición · suplementación de hierro en el lactante", ESP,
  ("Suplementación de hierro en el lactante", ["Las reservas de hierro del nacimiento se agotan hacia los 4-6 meses.",
                                               "Con factores de riesgo las reservas son menores y el hierro preventivo se adelanta."]),
  ("Lactante de 3 meses en CRED", ["37 semanas, madre adolescente sin controles, corte precoz del cordón.",
                                   "Lactancia exclusiva, ganancia de peso limítrofe, palidez; activa y reactiva."]),
  ["Corte precoz del cordón + gestación sin controles + madre adolescente: menos reservas de hierro.",
   "Conducta: hierro por vía oral a dosis profiláctica de inmediato, sin esperar a los 4 meses.",
   "La dosis terapéutica se reserva para la anemia confirmada con hemoglobina."],
  MINSA + ", norma técnica de prevención y control de la anemia; " + NELSON + ".",
  d=dict(rotulo="La lactante y cuándo empezar el hierro", tag="ESTE CASO",
         ilu_titulo="La lactante del caso",
         ilu=ILU(D(lambda s, x, y: I.bebe(s, x + 66, y + 4, _pal, marcas=[(1, 120, 214), (2, 150, 92)], sc=0.82), 330, 280)),
         ilu_pie="1 cordón cortado antes de tiempo; 2 palidez.",
         claves=[("Profiláctica, de inmediato", ["Tiene factores de riesgo: no se espera a los 4 meses."], True),
                 ("Esperar a los 4 meses", ["Solo para el lactante a término sin riesgo."], False),
                 ("Dosis terapéutica", ["Solo con anemia confirmada por hemoglobina."], False)],
         eje_titulo="Edad del lactante (meses)", eje=(0, 12), paso=2, marca=3, unidad="m",
         eje_nombre="meses de vida",
         hitos=[(1, 6, "Prematuro o bajo peso", "desde los 30 días", False),
                (3, 6, "Con factores de riesgo", "profiláctica desde ya", True),
                (4, 6, "A término sin riesgo", "desde los 4 meses", False),
                (6, 12, "Desde los 6 meses", "hierro y alimentos ricos en hierro", False)]),
  tabla=("Opciones de la pregunta", [("Inmediata, terapéutica", False), ("Inmediata, profiláctica", True),
                                     ("A los 4 meses, terapéutica", False), ("A los 4 meses, profiláctica", False)],
         [("¿Correcta?", ["No: sin anemia confirmada", "Sí", "No", "Tarde: tiene riesgo"])]))

# PED-258 · ITU febril en lactante con mal estado · ÁRBOL CON IMAGEN
S("arbol_imagen", "PED-258", "lactante-6-meses-itu-febril-vomitos-antibiotico-ev-ecografia-renal",
  "Lactante con infección urinaria febril, vómitos y mal estado: antibiótico EV y ecografía renal",
  "Nefrología pediátrica · infección urinaria febril", ESP,
  ("Infección urinaria febril en el lactante", ["La fiebre alta con PCR y procalcitonina elevadas indica pielonefritis.",
                                                "El riñón del lactante se cicatriza con facilidad: tratar pronto y estudiar la vía urinaria."]),
  ("Lactante de 6 meses", ["Fiebre de 39 °C por 24 h, vómitos repetidos y rechazo de la lactancia.",
                           "Irritable; leucocitosis, PCR y procalcitonina altas; orina compatible con ITU."]),
  ["No tolera la vía oral y luce enfermo: hospitalizar y dar antibiótico EV (ceftriaxona o similar) tras el urocultivo.",
   "Primera ITU febril en el lactante: ecografía renal y de vías urinarias.",
   "Esperar el cultivo para tratar retrasa el antibiótico y aumenta las cicatrices renales."],
  "AAP, guía de ITU febril (2011, reafirmada 2016); " + NELSON + ".",
  d=dict(rotulo="¿Dónde y cómo tratar?", tag="ESTE CASO",
         pregunta="Lactante con ITU febril: ¿tolera la vía oral y luce bien?",
         ramas=[("Sí: buen estado y tolera", "Antibiótico oral ambulatorio", ["Cefalosporina oral por 7-10 días.",
                                                                             "Control en 48 h."]),
                ("No: vómitos, rechazo, luce enfermo", "Antibiótico EV + ecografía renal",
                 ["Urocultivo por sonda o punción y luego ceftriaxona EV sin esperar el resultado.",
                  "Ecografía renal y de vías urinarias para buscar obstrucción o malformación."])],
         ilu=lambda s, x, y: I.rinon_vias(s, x, y, "pielonefritis", sc=0.9), IW=270, IH=256,
         ilu_pie="La infección sube al riñón (pielonefritis); la ecografía busca dilatación u obstrucción.",
         luego_titulo="Qué sigue",
         luego=[("Afebril y tolera en 48-72 h", ["Pasar a vía oral hasta completar 7-14 días."], True),
                ("Urocultivo", ["Ajustar el antibiótico al antibiograma."], False),
                ("Cistouretrografía", ["Si la ecografía es anormal o la ITU se repite."], False)]),
  tabla=("Opciones de la pregunta", [("Esperar cultivos", False), ("Antibiótico EV + ecografía", True),
                                     ("Observar con sintomáticos", False), ("Antibiótico oral ambulatorio", False)],
         [("Problema", ["Retrasa el antibiótico", "Ninguno", "Riesgo de sepsis y cicatriz", "Vomita: no tolera la vía oral"])]))

# PED-259 · Síndrome de Prader-Willi · MAPA DE SIGNOS
S("mapa_signos", "PED-259", "hipotonia-neonatal-hiperfagia-obesidad-hipogonadismo-prader-willi",
  "Hipotonía al nacer y luego hiperfagia con obesidad e hipogonadismo: síndrome de Prader-Willi",
  "Genética · síndromes con obesidad", ESP,
  ("Síndrome de Prader-Willi", ["Falta la copia paterna de la región 15q11-q13 (deleción o disomía materna).",
                                "Dos fases: lactante hipotónico que come mal; después, hambre sin freno y obesidad."]),
  ("Niño de 10 años", ["De bebé: hipotonía y dificultad para alimentarse.",
                       "Ahora: hiperfagia, obesidad central, talla baja, discapacidad leve, hipogonadismo y criptorquidia."]),
  ["Hipotonía neonatal + hiperfagia posterior + obesidad + hipogonadismo = Prader-Willi.",
   "Diagnóstico: estudio de metilación de 15q11-q13; hormona de crecimiento y control estricto de la dieta.",
   "X frágil: macroorquidia; Klinefelter: talla alta; Turner: solo en mujeres."],
  NELSON + "; Consenso de Prader-Willi (2017).",
  d=dict(rotulo="Los signos del niño", tag="ESTE CASO",
         ilu_titulo="El niño del caso",
         ilu=lambda s, x, y: I.nino(s, x + 45, y + 4, {"abdomen": "#fed7aa"}, obeso=True,
                                    marcas=[(1, 110, 200), (2, 162, 350), (3, 110, 248), (4, 110, 24)], sc=1.0),
         ilu_pie="1 obesidad central, 2 talla baja, 3 genitales pequeños, 4 discapacidad leve.",
         signos=[dict(tit="Hiperfagia y obesidad central", lines=["Hambre insaciable desde los 2-4 años."]),
                 dict(tit="Talla baja, manos y pies pequeños", lines=["Falta de hormona de crecimiento."]),
                 dict(tit="Hipogonadismo y criptorquidia", lines=["Hipogonadismo hipogonadotrófico."]),
                 dict(tit="Discapacidad intelectual leve", lines=["Con problemas de conducta."]),
                 dict(tit="Antecedente: hipotonía neonatal", lines=["Succión débil y poca ganancia de peso al inicio."]),
                 dict(tit="Causa: pérdida de 15q11-q13 paterno", on=True, lines=["Síndrome de Prader-Willi."])]),
  tabla=("Opciones de la pregunta", [("X frágil", False), ("Klinefelter", False), ("Prader-Willi", True), ("Turner", False)],
         [("Clave", ["Macroorquidia, orejas grandes", "Talla alta, ginecomastia", "Hipotonía y luego hiperfagia", "Solo en mujeres"])]))

# PED-260 · Sepsis neonatal con fontanela abombada · CRITERIOS
S("criterios", "PED-260", "sepsis-neonatal-fontanela-abombada-hemocultivo-cultivo-lcr",
  "Sepsis neonatal con fontanela abombada: hemocultivo y cultivo de líquido cefalorraquídeo",
  "Neonatología · estudio de la sepsis", ESP,
  ("Sepsis neonatal", ["El diagnóstico definitivo es el germen en un cultivo de sangre o LCR.",
                       "Hasta un tercio de las sepsis tienen meningitis: la punción lumbar no se omite."]),
  ("Recién nacido de 12 horas", ["Madre sin controles; líquido amniótico fétido.",
                                 "Hipotermia 35 °C, letargia, succión débil, palidez, llenado lento, fontanela algo abombada."]),
  ["Sepsis clínica + signos neurológicos (fontanela abombada): hemocultivo y punción lumbar con cultivo.",
   "Tomar las muestras sin retrasar el antibiótico empírico (ampicilina + aminoglucósido).",
   "PCR y procalcitonina apoyan, pero no identifican el germen ni descartan meningitis."],
  "AAP, sepsis neonatal precoz (2018-2019); " + NELSON + ".",
  d=dict(rotulo="¿Hay que cultivar sangre y LCR?", tag="ESTE CASO",
         lista_titulo="Datos que lo indican",
         items=[("Sepsis clínica: temperatura anormal, letargia, succión débil", True, "35 °C, letargia, succión débil"),
                ("Mala perfusión", True, "Palidez y llenado capilar lento"),
                ("Signos neurológicos: fontanela abombada o convulsiones", True, "Fontanela discretamente abombada"),
                ("Corioamnionitis materna", True, "Líquido amniótico fétido, sin controles"),
                ("Hemocultivo ya positivo", None, "Aún no hay resultado")],
         umbral="basta 1 criterio", veredicto="Hemocultivo y cultivo de LCR, y enseguida antibiótico empírico",
         img_titulo="El recién nacido", img=D(lambda s, x, y: I.bebe(s, x + 7, y, _pal, marcas=[(1, 120, 24), (2, 44, 182), (3, 120, 160)], sc=0.9), 230, 300),
         img_pie="1 fontanela abombada, 2 llenado lento y palidez, 3 hipotermia.",
         claves_titulo="Por qué no las otras",
         claves=[("PCR o procalcitonina", ["Apoyan la sospecha, pero no dan el germen."], False),
                 ("Urocultivo", ["Rinde poco en la sepsis de las primeras 72 h."], False),
                 ("Lo correcto", ["Hemocultivo + punción lumbar con cultivo de LCR."], True)]),
  tabla=("Opciones de la pregunta", [("Procalcitonina", False), ("PCR cuantitativa", False), ("Hemocultivo y cultivo de LCR", True),
                                     ("Urocultivo", False)],
         [("¿Da el diagnóstico?", ["No: solo orienta", "No: solo orienta", "Sí: germen y meningitis", "No en sepsis precoz"])]))

# PED-261 · Policitemia neonatal asintomática · SEMÁFORO
S("semaforo", "PED-261", "recien-nacido-41-semanas-hematocrito-68-asintomatico-hidratacion",
  "Policitemia neonatal asintomática (hematocrito 68 %): hidratación EV y control del hematocrito",
  "Neonatología · policitemia", ESP,
  ("Policitemia neonatal", ["Hematocrito venoso > 65 %: la sangre se vuelve espesa (hiperviscosidad).",
                            "La conducta depende de los síntomas y del valor, no solo del número."]),
  ("Recién nacido de 41 semanas, 4000 g", ["A las 2 h: activo, buena succión, sin dificultad respiratoria ni signos neurológicos.",
                                           "Hematocrito 68 %, glucosa 60 mg/dL."]),
  ["Asintomático con hematocrito 65-70 %: hidratación EV y control seriado del hematocrito y la glucosa.",
   "Exanguinotransfusión parcial (con salino 0,9 %): si hay síntomas de hiperviscosidad o hematocrito > 75 %.",
   "La glucosa de 60 mg/dL es normal: no necesita bolo de dextrosa."],
  "AAP; Cochrane, exanguinotransfusión parcial; SIBEN; " + NELSON + ".",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="Hematocrito del caso",
         ilu=ILU(D(lambda s, x, y: I.hematocrito(s, x + 20, y + 20, 68, sc=1.05), 270, 290)),
         ilu_pie="68 %: sobre el límite de 65 % (línea naranja).",
         check_titulo="¿Tiene síntomas?",
         check=[("Activo y con buena succión", True), ("Sin dificultad respiratoria", True),
                ("Glucosa 60 mg/dL: normal", True), ("Hematocrito venoso 68 %", False)],
         ans=0, tag="ESTE CASO",
         luces=[("Hto 65-70 % sin síntomas", "Hidratar y controlar", ["Líquidos EV; hematocrito y glucosa seriados."]),
                ("Hto 70-75 % sin síntomas", "Vigilar de cerca", ["Hidratación; decidir según la evolución."]),
                ("Síntomas o Hto > 75 %", "Exanguinotransfusión parcial", ["Con salino 0,9 %; nunca total."])]),
  tabla=("Opciones de la pregunta", [("Exanguinotransfusión total", False), ("Exanguinotransfusión parcial", False),
                                     ("Bolo de dextrosa 10 %", False), ("Hidratación EV y controles", True)],
         [("¿Indicada?", ["Nunca en policitemia", "Solo con síntomas o > 75 %", "Glucosa normal", "Sí"])]))

# PED-262 · Bebidas en escolares · RADIAL + franja
S("radial", "PED-262", "escolar-8-anos-evitar-bebidas-azucaradas-agua-simple",
  "Escolar sano: evitar las bebidas azucaradas y tomar agua simple",
  "Nutrición · alimentación del escolar", ESP,
  ("Bebidas en la infancia", ["Las bebidas azucaradas son la mayor fuente de azúcar añadida en los niños.",
                              "Se asocian a obesidad, caries y riesgo cardiometabólico."]),
  ("Escolar de 8 años, control de niño sano", ["¿Qué recomendar sobre las bebidas?"]),
  ["La recomendación con más impacto: evitar gaseosas, jugos envasados y néctares; el agua simple como bebida habitual.",
   "El jugo natural también tiene azúcar libre: mejor la fruta entera.",
   "Los edulcorantes no se recomiendan en niños: mantienen el gusto por lo dulce."],
  "OMS, azúcares libres (2015); AAP; " + MINSA + ", guías alimentarias.",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Escolar sano: ¿qué beber?",
         items=[("Agua simple, sin bebidas azucaradas", ["La medida con más evidencia contra obesidad y caries"]),
                ("Jugo natural en vez de gaseosa", ["Sigue aportando azúcar libre; mejor la fruta entera"]),
                ("Leche entera en las comidas", ["Más grasa saturada; no es la bebida para todo el día"]),
                ("Bebidas bajas en calorías", ["Edulcorantes: no se recomiendan en niños"])],
         ruta=["Control de niño sano", "Preguntar qué bebe", "Agua como bebida habitual", "Fruta entera, no jugos"]),
  banda=B("Azúcar en cada bebida", D(lambda s, x, y: I.vasos(s, x, y, caso=3, sc=0.95), 420, 164),
          ["Una gaseosa puede tener unas 8 cucharaditas de azúcar.", "El jugo envasado también tiene mucha azúcar.",
           "El agua (en naranja) no tiene azúcar ni calorías."], ans=2),
  tabla=("Opciones de la pregunta", [("Jugos naturales", False), ("Leche entera", False), ("Agua, sin bebidas azucaradas", True),
                                     ("Bebidas bajas en calorías", False)],
         [("Problema", ["Azúcar libre", "Grasa saturada", "Ninguno", "Edulcorantes"])]))


# PED-263 · Ingesta de paracetamol no tóxica · CÁLCULO
def _dosis(s, x, y):
    p = (I.E(109, 30, 46, 20, "#ffffff", "#64748b", 2) + I.P("M109 10 L109 50", "none", "#cbd5e1", 1.5)
         + I.t(109, 66, "1 tableta = 500 mg", I.INK, 11) + I.t(40, 100, "÷", I.SLATE, 22, fw=800))
    g_bar = 300
    top = 100
    fy = lambda v: g_bar - v / 250 * (g_bar - top)
    p += f'<rect x="150" y="{top}" width="28" height="{g_bar-top}" rx="6" fill="#f1f5f9" stroke="#94a3b8" stroke-width="1.5"/>'
    p += f'<rect x="150" y="{fy(250):.0f}" width="28" height="{fy(150)-fy(250):.0f}" rx="6" fill="#fecaca"/>'
    p += f'<rect x="152" y="{fy(41.7):.0f}" width="24" height="{g_bar-fy(41.7)-2:.0f}" rx="4" fill="#16a34a"/>'
    p += I.P(f"M144 {fy(150):.0f} L184 {fy(150):.0f}", "none", I.RED, 2, 'stroke-dasharray="4 3"')
    p += I.t(186, fy(150) - 4, "150", I.RED, 10.5, "start") + I.t(186, fy(150) + 10, "tóxico", I.RED, 10, "start")
    p += I.t(186, fy(41.7) + 4, "41,7", "#15803d", 11, "start") + I.t(164, g_bar + 16, "mg/kg", I.MUTED, 10)
    I.g(s, x, y, p)
    I.nino(s, x + 6, y + 120, sc=0.42)
    I.g(s, x, y, I.t(52, 290, "12 kg", I.INK, 12, fw=800) + I.t(109, 352, "500 ÷ 12 = 41,7 mg/kg", "#15803d", 12, fw=800))


S("calculo", "PED-263", "nino-12-kg-paracetamol-500-mg-dosis-no-toxica-alta",
  "Niño de 12 kg que tomó 500 mg de paracetamol: 42 mg/kg, dosis no tóxica, alta",
  "Intoxicaciones en pediatría · paracetamol", ESP,
  ("Ingesta de paracetamol", ["El riesgo se calcula en mg por kilo de peso.",
                              "En niños, la dosis única tóxica es ≥ 150-200 mg/kg."]),
  ("Niño de 2 años, 12 kg", ["Tomó 1 tableta de 500 mg hace 1 hora; ingestión única confirmada.",
                             "Asintomático; sin otros medicamentos."]),
  ["500 mg ÷ 12 kg = 41,7 mg/kg: muy por debajo del umbral tóxico.",
   "No necesita carbón activado ni N-acetilcisteína: tranquilizar, dar de alta y aconsejar guardar los medicamentos.",
   "Si la dosis fuera ≥ 150-200 mg/kg: nivel sérico a las 4 h y nomograma para decidir la N-acetilcisteína."],
  NELSON + "; AAP y centros de toxicología, ingesta pediátrica de paracetamol.",
  d=dict(rotulo="Se calcula la dosis por kilo", tag="ESTE CASO",
         ilu_titulo="La cuenta del caso",
         ilu=ILU(D(_dosis, 218, 370)),
         ilu_pie="En verde la dosis del niño; en rojo, la zona tóxica.",
         pasos=[("Peso del niño", ["12 kg."], False),
                ("Dosis ingerida", ["1 tableta = 500 mg, una sola vez."], False),
                ("Dosis por kilo", ["500 ÷ 12 = 41,7 mg/kg."], False),
                ("Umbral tóxico", ["≥ 150-200 mg/kg (≥ 1800-2400 mg en 12 kg)."], False),
                ("Resultado", ["No tóxica: tranquilizar, alta y consejería."], True)]),
  tabla=("Opciones de la pregunta", [("Tranquilizar y alta", True), ("Carbón activado", False), ("N-acetilcisteína", False),
                                     ("Bicarbonato", False)],
         [("¿Indicado?", ["Sí", "No: dosis no tóxica", "No: dosis no tóxica", "Nunca en esta intoxicación"])]))

# PED-264 · Hipotiroidismo congénito · CRONOLOGÍA
_hipot = I.E(120, 101, 11, 6, "#f472b6", "#be185d", 1.5) + I.E(120, 214, 8, 6, "#fbcfe8", "#9d174d", 1.5)
_ict = {k: AMARILLO for k in ("cabeza", "torax", "abdomen", "brazo_d", "brazo_i", "pierna_d", "pierna_i")}
S("cronologia", "PED-264", "recien-nacido-3-semanas-macroglosia-hernia-umbilical-levotiroxina",
  "Hipotiroidismo congénito a las 3 semanas: levotiroxina de inmediato",
  "Endocrinología pediátrica · hipotiroidismo congénito", ESP,
  ("Hipotiroidismo congénito", ["Sin hormona tiroidea el cerebro del recién nacido no se desarrolla bien.",
                                "Cada semana sin tratamiento resta desarrollo intelectual."]),
  ("Recién nacido de 3 semanas", ["Ictericia desde el nacimiento, come mal y gana poco peso.",
                                  "Fontanelas amplias, hernia umbilical, macroglosia, hipotonía y piel seca."]),
  ["Ictericia prolongada + macroglosia + hernia umbilical + hipotonía = hipotiroidismo congénito.",
   "Tratamiento: levotiroxina oral 10-15 µg/kg/día desde ya (idealmente antes de las 2 semanas de vida).",
   "Metimazol, propiltiouracilo y propranolol son para el hipertiroidismo."],
  "AAP y ESPE, hipotiroidismo congénito (2020-2023); " + MINSA + ", tamizaje neonatal.",
  d=dict(rotulo="El recién nacido y cuándo tratar", tag="ESTE CASO",
         ilu_titulo="El recién nacido del caso",
         ilu=ILU(D(lambda s, x, y: I.bebe(s, x + 66, y + 4, _ict, extra=_hipot,
                                          marcas=[(1, 120, 24), (2, 146, 106), (3, 146, 222), (4, 60, 280)], sc=0.82), 330, 280)),
         ilu_pie="1 fontanela amplia, 2 lengua grande, 3 hernia umbilical, 4 hipotonía; piel amarilla.",
         claves=[("Levotiroxina", ["Reemplaza la hormona que falta; se inicia ya."], True),
                 ("Metimazol o propiltiouracilo", ["Bloquean la tiroides: empeorarían el cuadro."], False),
                 ("Propranolol", ["Controla síntomas de hipertiroidismo."], False)],
         eje_titulo="Días de vida", eje=(0, 42), paso=7, marca=21, unidad="d",
         eje_nombre="días de vida",
         hitos=[(2, 7, "Tamizaje neonatal de TSH", "entre 2 y 7 días", False),
                (0, 14, "Ventana ideal para empezar", "primeras 2 semanas", False),
                (21, 28, "Este caso: levotiroxina ya", "10-15 µg/kg/día", True),
                (28, 42, "Control de T4 y TSH", "a las 1-2 semanas de iniciar", False)]),
  tabla=("Opciones de la pregunta", [("Propiltiouracilo", False), ("Metimazol", False), ("Propranolol", False), ("Levotiroxina", True)],
         [("Sirve para", ["Hipertiroidismo", "Hipertiroidismo", "Síntomas adrenérgicos", "Hipotiroidismo: este caso"])]))

# PED-265 · Malformación anorrectal: buscar VACTERL · ANATOMÍA
_vac = ("".join(f'<rect x="116" y="{132+k*12}" width="8" height="9" rx="2" fill="#e2e8f0" stroke="#64748b" stroke-width="1.2"/>' for k in range(8))
        + I.P("M136 162 C124 150 126 138 136 144 C146 138 148 150 136 162 Z", "#fca5a5", I.RED, 1.8)
        + I.P("M98 126 L98 156", "none", "#0ea5e9", 6, 'stroke-linecap="round"')
        + I.E(96, 200, 9, 13, "#fecdd3", "#9f1239", 1.6) + I.E(144, 200, 9, 13, "#fecdd3", "#9f1239", 1.6)
        + I.C(120, 234, 7, "#ffffff", O, 2.5) + I.P("M115 229 L125 239 M125 229 L115 239", "none", O, 2.5))
S("anatomia", "PED-265", "recien-nacido-sin-ano-sin-meconio-vacterl-estudios-imagen",
  "Recién nacido sin ano: antes de operar, buscar malformaciones asociadas (VACTERL)",
  "Cirugía pediátrica · malformación anorrectal", ESP,
  ("Malformación anorrectal", ["Casi la mitad tiene otras malformaciones (asociación VACTERL).",
                               "Algunas son graves y cambian el plan: se buscan antes de operar."]),
  ("Recién nacido a término de 10 horas", ["No elimina meconio.", "Sin abertura anal en el sitio habitual; sin otras malformaciones visibles."]),
  ["Siguiente paso: estudios de imagen para malformaciones asociadas (eco cardíaca, eco renal, Rx de columna y sacro).",
   "Paso de sonda orogástrica para descartar atresia de esófago; observar 24 h por si aparece una fístula perineal.",
   "La anorrectoplastia sagital posterior es el tratamiento definitivo, pero no es el primer paso."],
  NELSON + "; Asociación de Cirugía Pediátrica, malformaciones anorrectales.",
  d=dict(rotulo="Qué buscar: VACTERL", tag="ESTE CASO",
         ilu_titulo="Dónde buscar en el recién nacido",
         ilu=lambda s, x, y: I.bebe(s, x + 94, y, extra=_vac, marcas=[(1, 104, 222), (2, 120, 260), (3, 158, 144), (4, 82, 138),
                                                                       (5, 164, 202), (6, 44, 182)]),
         ilu_pie="La X naranja es el ano ausente (este caso); los números, lo que se estudia.",
         ans=2,
         puntos=[("Vertebrales", ["Rx de columna y sacro (el sacro define el pronóstico)."]),
                 ("Anorrectal", ["Sin abertura anal: este caso."]),
                 ("Cardíacas", ["Ecocardiografía."]),
                 ("Traqueoesofágicas", ["Sonda orogástrica y Rx: atresia de esófago o fístula."]),
                 ("Renales", ["Ecografía renal y de vías urinarias."]),
                 ("Extremidades", ["Radio y pulgar: examen y Rx."])]),
  tabla=("Opciones de la pregunta", [("Solo sonda orogástrica", False), ("Anorrectoplastia inmediata", False),
                                     ("Fórmula hidrolizada", False), ("Imágenes para asociadas", True)],
         [("Comentario", ["Es parte, no el plan completo", "Definitiva, no el primer paso", "Está obstruido: ayuno",
                          "Siguiente paso"])]))

# PED-266 · Reflujo vesicoureteral y cicatriz renal · RADIAL + franja
S("radial", "PED-266", "itu-febril-lactante-cicatriz-renal-reflujo-vesicoureteral",
  "ITU febril con cicatrices renales en lactantes: reflujo vesicoureteral",
  "Nefrología pediátrica · reflujo vesicoureteral", ESP,
  ("Nefropatía por reflujo", ["Si la válvula entre uréter y vejiga falla, la orina infectada sube al riñón.",
                              "Las pielonefritis repetidas dejan cicatrices: hipertensión y enfermedad renal crónica."]),
  ("Programa de vigilancia en un hospital regional", ["20 % de lactantes con primera ITU febril tiene cicatrices en la gammagrafía.",
                                                      "La cistouretrografía muestra la misma anomalía en la mayoría."]),
  ["ITU febril + cicatriz renal + hallazgo en la cistouretrografía = reflujo vesicoureteral.",
   "Detectarlo y tratarlo a tiempo (profilaxis o cirugía según grado) reduce nuevas cicatrices.",
   "Valvas uretrales: solo varones y con obstrucción; estenosis pieloureteral: hidronefrosis sin reflujo."],
  "AAP, guía de ITU febril; EAU/ESPU, reflujo vesicoureteral (2023); " + NELSON + ".",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="ITU febril + cicatriz renal",
         items=[("Reflujo vesicoureteral", ["La cistouretrografía lo muestra; es la causa más común de cicatriz"]),
                ("Estenosis pieloureteral", ["Da hidronefrosis; no se ve en la cistouretrografía"]),
                ("Valvas de uretra posterior", ["Solo en varones; obstrucción y vejiga de esfuerzo"]),
                ("Doble sistema pielocalicial", ["Variante; a veces se asocia a reflujo, pero no es la regla"])],
         ruta=["Primera ITU febril", "Ecografía renal", "Cistouretrografía: reflujo", "Profilaxis y seguimiento"]),
  banda=B("Reflujo de orina hacia el riñón", D(lambda s, x, y: I.rinon_vias(s, x, y, "rvu", sc=0.95), 290, 270),
          ["La orina sube desde la vejiga por el uréter (flechas).", "Lleva bacterias al riñón: pielonefritis.",
           "Cada pielonefritis puede dejar una cicatriz."], ans=0),
  tabla=("Opciones de la pregunta", [("Estenosis pieloureteral", False), ("Valvas uretrales", False), ("Doble sistema", False),
                                     ("Reflujo vesicoureteral", True)],
         [("¿Explica cicatrices tras ITU?", ["No", "Solo varones", "Poco frecuente", "Sí"])]))

# PED-267 · Anemia ferropénica en niño andino · EMBUDO + franja
S("embudo", "PED-267", "nino-2-anos-zona-andina-anemia-microcitica-deficiencia-hierro",
  "Anemia microcítica e hipocrómica con dieta pobre en carnes: deficiencia de hierro",
  "Hematología pediátrica · anemia", ESP,
  ("Anemia en el niño pequeño", ["El volumen corpuscular medio (VCM) separa las causas.",
                                 "Microcítica e hipocrómica con blancos y plaquetas normales: falta de hierro."]),
  ("Niño de 2 años, comunidad rural andina", ["Dieta pobre en carnes rojas y legumbres; palidez y taquicardia.",
                                              "Hb 8 g/dL, VCM 65 fL, HCM baja; leucocitos y plaquetas normales."]),
  ["Microcítica + hipocrómica + dieta pobre en hierro = anemia ferropénica.",
   "Confirmar con ferritina baja; tratar con hierro oral 3 mg/kg/día por 6 meses.",
   "La Hb se ajusta por la altitud: 8 g/dL es anemia en cualquier altura."],
  MINSA + ", norma técnica de anemia; " + NELSON + ".",
  d=dict(rotulo="De la anemia a la causa", inicio="Niño de 2 años con Hb 8 g/dL",
         candidatos=["Hemolítica autoinmune", "Enfermedad crónica", "Déficit de vitamina B12", "Deficiencia de hierro"],
         pasos=[("¿VCM alto (macrocítica)?", ["Déficit de vitamina B12"]),
                ("¿Ictericia, reticulocitos altos, Coombs (+)?", ["Hemolítica autoinmune"]),
                ("¿Inflamación o infección crónica de fondo?", ["Enfermedad crónica"])],
         final=("Deficiencia de hierro", ["VCM 65 y HCM baja con dieta pobre en hierro"]),
         nota="Glóbulos rojos pequeños y pálidos, sin otra enfermedad: falta de hierro."),
  banda=B("Frotis (esquema)", D(lambda s, x, y: I.frotis(s, x + 20, y, "microcitica", sc=1.1), 280, 180),
          ["Glóbulos rojos pequeños (microcitosis).", "Centro pálido amplio (hipocromía).", "Blancos y plaquetas normales."]),
  tabla=("Opciones de la pregunta", [("Hemolítica autoinmune", False), ("Deficiencia de hierro", True), ("Enfermedad crónica", False),
                                     ("Déficit de B12", False)],
         [("¿Encaja?", ["No: sin ictericia", "Sí", "No: sin enfermedad de fondo", "No: sería macrocítica"])]))

# PED-268 · IMC para tamizaje nutricional · TARJETAS + franja
S("tarjetas", "PED-268", "escolar-9-anos-aumento-peso-tamizaje-indice-masa-corporal",
  "Tamizaje nutricional del escolar: índice de masa corporal para la edad",
  "Nutrición · evaluación antropométrica", ESP,
  ("Tamizaje nutricional en escolares", ["Se busca una medida barata, repetible y con tablas por edad y sexo.",
                                         "El IMC para la edad (percentil o puntaje Z) cumple todo eso."]),
  ("Niño de 9 años", ["Aumento progresivo de peso en el último año.", "¿Qué medida usar para tamizar y seguir?"]),
  ["IMC = peso (kg) / talla² (m), ubicado en la curva de la OMS para la edad y el sexo.",
   "Sobrepeso: > +1 DE; obesidad: > +2 DE (OMS, 5-19 años).",
   "Cintura, pliegues y bioimpedancia complementan, pero no son el tamizaje estándar."],
  "OMS, patrones de crecimiento 5-19 años; AAP (2023); " + MINSA + ".",
  d=dict(rotulo="Cuatro medidas posibles", ans=0,
         cards=[dict(titulo="Índice de masa corporal", datos=[("Costo", "Bajo", True), ("Referencias", "OMS por edad y sexo", True),
                                                             ("¿Tamizaje?", "Sí, estándar", True)], pie="Se sigue en cada control."),
                dict(titulo="Pliegue tricipital", datos=[("Costo", "Bajo", False), ("Precisión", "Depende del operador", False),
                                                         ("¿Tamizaje?", "No, solo", False)], pie="Complemento."),
                dict(titulo="Circunferencia de cintura", datos=[("Mide", "Grasa abdominal", False), ("Referencias", "Poco uniformes", False),
                                                                ("¿Tamizaje?", "No, sola", False)], pie="Riesgo cardiometabólico."),
                dict(titulo="Bioimpedancia", datos=[("Costo", "Equipo", False), ("Varía con", "Hidratación", False),
                                                    ("¿Tamizaje?", "No", False)], pie="No estandarizada en niños.")]),
  banda=B("Curva de IMC para la edad", D(lambda s, x, y: I.curva_percentil(s, x, y, punto=(0.75, 0.69), r=5, xlab="Edad (años)",
                                                                             ylab="IMC (kg/m²)", ticks=("3", "5", "7", "9", "11"),
                                                                             etiquetas=("+2 DE", "+1 DE", "p50", "-1 DE", "-2 DE"),
                                                                             marca="ejemplo: sobrepeso"), 340, 230),
          ["Se calcula el IMC y se ubica en la curva por edad y sexo.", "Entre +1 y +2 DE: sobrepeso; sobre +2 DE: obesidad.",
           "La tendencia en controles sucesivos importa tanto como un valor."], ans=1),
  tabla=("Opciones de la pregunta", [("Pliegue tricipital", False), ("Circunferencia de cintura", False), ("Índice de masa corporal", True),
                                     ("Bioimpedancia", False)],
         [("Problema", ["Depende del operador", "Complemento, no tamizaje", "Ninguno", "No estandarizada"])]))

# PED-269 · Deshidratación con íleo · ÁRBOL + franja
S("arbol", "PED-269", "lactante-deshidratacion-ileo-rha-ausentes-solucion-polielectrolitica-ev",
  "Lactante deshidratado con íleo: solución polielectrolítica por vía EV",
  "Enfermedad diarreica aguda · planes de hidratación", ESP,
  ("Rehidratación en la diarrea", ["Plan A sin deshidratación, plan B con deshidratación (SRO), plan C con shock.",
                                   "Si el intestino no funciona (íleo), la vía digestiva no sirve: se hidrata por vena."]),
  ("Pedro, 11 meses", ["2 días de heces líquidas y 2 vómitos; irritable.",
                       "Mucosas secas, pocas lágrimas, pliegue > 2 s; abdomen distendido, doloroso, sin ruidos."]),
  ["Deshidratación + íleo (distensión, RHA ausentes): contraindicada la vía oral y la gastroclisis.",
   "Rehidratar por vía EV con solución polielectrolítica (sodio, potasio, base y glucosa).",
   "Dextrosa al 5 % sola no repone sodio; volver a SRO cuando regrese el tránsito."],
  MINSA + ", guía de enfermedad diarreica aguda en niños; OMS.",
  arbol=Q("¿Tiene signos de deshidratación?", [
      L("No", "Plan A: en casa", ["SRO después de cada deposición"]),
      Q("¿Puede usarse el intestino (sin íleo ni shock)?", [
          L("Sí", "Plan B: SRO", ["75 mL/kg en 4 h en el establecimiento", "Si vomita mucho: gastroclisis"]),
          L("No: íleo", "SPE POR VÍA EV", ["Solución polielectrolítica", "Luego SRO al volver el tránsito"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("El lactante del caso", D(lambda s, x, y: I.bebe(s, x + 30, y, {"abdomen": "#fed7aa"},
                                                            marcas=[(1, 150, 92), (2, 120, 200), (3, 156, 228)], sc=0.9), 250, 300),
          ["Mucosas secas y pocas lágrimas: deshidratado.", "Abdomen distendido, sin ruidos: íleo.",
           "Pliegue que vuelve en más de 2 segundos."], ans=1),
  tabla=("Opciones de la pregunta", [("SPE por vía EV", True), ("Suero fisiológico EV", False), ("Dextrosa 5 % EV", False),
                                     ("SRO por gastroclisis", False)],
         [("Problema", ["Ninguno", "No aporta potasio ni base", "No repone sodio", "Con íleo no se absorbe"])]))

# PED-270 · Encefalopatía hipóxico-isquémica · CRITERIOS
S("criterios", "PED-270", "neonato-apgar-3-5-convulsiones-sutiles-encefalopatia-hipoxico-isquemica",
  "Asfixia al nacer y convulsiones sutiles a las 12 horas: encefalopatía hipóxico-isquémica",
  "Neonatología · asfixia perinatal", ESP,
  ("Encefalopatía hipóxico-isquémica (EHI)", ["Daño cerebral por falta de oxígeno y sangre alrededor del parto.",
                                               "Da alteración de la conciencia y convulsiones en las primeras 24 h."]),
  ("Neonato de 41 semanas", ["Apgar 3 y 5; necesitó ventilación a presión positiva.",
                             "A las 12 h: hipoalerta, desviación ocular, pedaleo y succión anómala."]),
  ["Asfixia (Apgar bajo + reanimación) + encefalopatía + convulsiones en las primeras 24 h = EHI.",
   "Las convulsiones sutiles del neonato: mirada desviada, pedaleo, chupeteo, apneas.",
   "Hipotermia terapéutica si se inicia antes de las 6 h; tratar las convulsiones y dar soporte."],
  "AAP y ACOG, encefalopatía neonatal (2014-2019); " + NELSON + ".",
  d=dict(rotulo="¿Cumple el cuadro de EHI?", tag="ESTE CASO",
         lista_titulo="Datos de encefalopatía hipóxico-isquémica",
         items=[("Apgar ≤ 5 a los 5 minutos", True, "Apgar 3 y 5"),
                ("Necesitó reanimación al nacer", True, "Ventilación a presión positiva"),
                ("Alteración de la conciencia", True, "Hipoalerta"),
                ("Convulsiones en las primeras 24 h", True, "Sutiles a las 12 h"),
                ("Sin fiebre ni otros signos de infección", True, "No descritos: la meningitis es menos probable")],
         umbral="asfixia + encefalopatía", veredicto="Encefalopatía hipóxico-isquémica: tratar convulsiones y dar soporte en UCI neonatal",
         img_titulo="Convulsiones sutiles", img=D(lambda s, x, y: I.bebe(s, x + 7, y, marcas=[(1, 146, 50), (2, 146, 106), (3, 60, 286)], sc=0.9), 230, 300),
         img_pie="1 desviación ocular, 2 succión anómala, 3 pedaleo.",
         claves_titulo="Por qué no las otras",
         claves=[("Meningitis neonatal", ["Fiebre o hipotermia, riesgo infeccioso, LCR alterado."], False),
                 ("Hipocalcemia o error metabólico", ["Sin antecedente de asfixia; el error metabólico aparece tras comer."], False),
                 ("Lo correcto", ["Asfixia + encefalopatía temprana = EHI."], True)]),
  tabla=("Opciones de la pregunta", [("Meningitis neonatal", False), ("Encefalopatía hipóxico-isquémica", True),
                                     ("Error congénito del metabolismo", False), ("Hipocalcemia", False)],
         [("Clave", ["Infección, LCR", "Asfixia + convulsiones precoces", "Tras iniciar la alimentación", "Calcio bajo, sin asfixia"])]))

# PED-271 · Neumonía afebril por Chlamydia · ÁRBOL CON IMAGEN
S("arbol_imagen", "PED-271", "lactante-2-meses-neumonia-afebril-chlamydia-trachomatis-azitromicina",
  "Neumonía afebril del lactante de 2 meses con madre con leucorrea: Chlamydia, azitromicina",
  "Neumonía del lactante · neumonía afebril", ESP,
  ("Neumonía afebril del lactante", ["Entre las 2 semanas y los 4 meses, Chlamydia trachomatis adquirida en el parto.",
                                     "Tos que empeora de a poco, taquipnea y crépitos, sin fiebre."]),
  ("Lactante de 2 meses, parto vaginal", ["Madre con leucorrea en el III trimestre; tos progresiva de 6 días.",
                                          "Sin fiebre ni catarro; FR 70, SatO₂ 92 %, retracciones, crépitos en bases."]),
  ["Afebril + tos progresiva + infección genital materna = neumonía por Chlamydia trachomatis.",
   "Es intracelular: macrólido. Azitromicina oral 20 mg/kg/día por 3 días.",
   "Tratar también a la madre y a su pareja."],
  "CDC, guía de ITS (2021); " + NELSON + ".",
  d=dict(rotulo="¿Qué germen y qué antibiótico?", tag="ESTE CASO",
         pregunta="Lactante de 1-4 meses con neumonía: ¿tiene fiebre?",
         ramas=[("Con fiebre y aspecto tóxico", "Bacteriana típica", ["Menor de 2 meses: ampicilina + gentamicina EV.",
                                                                     "Buscar sepsis."]),
                ("Sin fiebre, madre con leucorrea", "Chlamydia trachomatis: azitromicina VO",
                 ["Tos en accesos que empeora de a poco; puede haber conjuntivitis previa.",
                  "Rx: infiltrado intersticial difuso con hiperinsuflación."])],
         ilu=lambda s, x, y: I.torax_rx(s, x, y, "intersticial", sc=0.9), IW=270, IH=252,
         ilu_pie="Rx (esquema): infiltrado intersticial en ambos pulmones, sin consolidación.",
         luego_titulo="Qué más",
         luego=[("Azitromicina VO", ["20 mg/kg/día por 3 días."], True),
                ("Soporte", ["Oxígeno según saturación y trabajo respiratorio."], False),
                ("La madre y su pareja", ["Tratar la infección genital."], False)]),
  tabla=("Opciones de la pregunta", [("Ribavirina", False), ("Ampicilina EV", False), ("Gentamicina IM", False), ("Azitromicina VO", True)],
         [("¿Cubre Chlamydia?", ["No: es para VSR", "No", "No", "Sí"])]))


# PED-272 · Pronóstico del estado epiléptico · BALANZA + franja
def _dos_cerebros(s, x, y):
    I.tc_craneo(s, x, y, "normal", sc=0.6)
    I.tc_craneo(s, x + 184, y, "edema", sc=0.6)
    I.g(s, x, y, I.t(84, 176, "Febril, niño sano", I.SLATE, 11, fw=700) + I.t(268, 176, "Encefalitis o lesión aguda", I.SLATE, 11, fw=700))


S("balanza", "PED-272", "estado-epileptico-pronostico-neurologico-etiologia-subyacente",
  "Pronóstico del estado epiléptico: lo que más pesa es la causa",
  "Estado epiléptico · pronóstico", ESP,
  ("Estado epiléptico en el niño", ["El daño final depende sobre todo de qué lo provocó.",
                                    "La duración y la rapidez del tratamiento también influyen."]),
  ("Niño de 3 años en UCI pediátrica", ["Estado convulsivo generalizado, ya estabilizado.", "¿Qué define más su pronóstico neurológico?"]),
  ["La etiología es el principal factor pronóstico: febril en niño sano, bueno; infección del SNC, lesión aguda o metabólica, peor.",
   "El tipo de anticonvulsivo influye en el control de la crisis, no tanto en el daño final.",
   "La estancia hospitalaria es una consecuencia, no una causa."],
  NELSON + "; ILAE, estado epiléptico (2015).",
  d=dict(rotulo="¿Qué pesa más en el pronóstico?", gana="izq", tag="ESTE CASO",
         pregunta="Pronóstico neurológico tras el estado epiléptico",
         izq=dict(titulo="La causa del estado epiléptico", peso="elige",
                  items=["Febril en niño sano: suele quedar bien", "Encefalitis, trauma o daño metabólico: más secuelas",
                         "Es el factor que más predice en los estudios"]),
         der=dict(titulo="Fármaco, estancia o edad", peso="no",
                  items=["El fármaco influye en el control, no en la causa", "La estancia es consecuencia del cuadro",
                         "La edad pesa menos que la causa"]),
         veredicto=("La etiología subyacente define el pronóstico",
                    ["Por eso se busca la causa (infección, trauma, tóxicos, metabólica) mientras se controla la crisis."])),
  banda=B("Misma crisis, distinta causa", D(_dos_cerebros, 360, 190),
          ["Izquierda: cerebro sano tras una crisis febril.", "Derecha: edema por encefalitis o lesión aguda.",
           "La enfermedad de fondo, no la crisis sola, deja el daño."], ans=2),
  tabla=("Opciones de la pregunta", [("Tipo de anticonvulsivo", False), ("Etiología subyacente", True), ("Duración de la hospitalización", False),
                                     ("Edad del niño", False)],
         [("¿Principal factor?", ["No", "Sí", "No: es consecuencia", "Pesa menos"])]))
