"""Entrega 3 · tanda t18 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO, GINA
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
PMC_ROP = "Fondo de ojo: Zhao et al. · Scientific Data 2024 · PMC11130119 (PubMed Central) · CC BY 4.0"
ROBBINS = "Robbins y Cotran, Patología estructural y funcional 10.ª ed."

# PED-197 · Desnutrición crónica · REGLA
S("regla", "PED-197", "Niño de 24 meses con 10 kg y 78 cm (talla muy baja para la edad con peso adecuado para la talla), prematuro y bajo peso al nacer: desnutrición crónica",
  "Estado nutricional del niño",
  ("Indicadores antropométricos (OMS)", ["Talla para la edad < −2 DE: desnutrición crónica (talla baja); refleja un problema largo.",
                                         "Peso para la talla < −2 DE: desnutrición aguda (emaciación). Marasmo = emaciación grave; kwashiorkor = edema."]),
  ("Niño de 24 meses", ["Hiporexia, irritabilidad, bajo peso; prematuro y bajo peso al nacer.", "Peso 10 kg, talla 78 cm, sin edemas; Hb 10."]),
  ["Mediana de talla a los 24 meses ~87 cm: 78 cm está por debajo de −2 DE (casi −3).",
   "Para 78 cm, 10 kg está cerca de la mediana: P/T normal (no hay desnutrición aguda).",
   "Tratar la anemia, consejería nutricional, controles CRED y estimulación."],
  OMS + ", patrones de crecimiento (2006); " + MINSA + ", NTS CRED (2017).",
  op=("¿Diagnóstico?", ["No: no hay edema", "No: P/T normal", "Sí: talla baja con P/T normal", "No: P/T normal", "No"]),
  d=dict(rotulo="Los dos indicadores del niño",
         reglas=[dict(nombre="Talla para la edad (DE)", que="78 cm a los 24 meses (mediana ~87 cm).", min=-4, max=3, fmt="{}", ticks=[-3, -2, 2],
                      bandas=[(-4, -3, "Severa", 3), (-3, -2, "Talla baja", 3), (-2, 2, "Normal", 0), (2, 3, "Alta", 1)], caso=-2.8, caso_txt="ESTE CASO: < −2"),
                 dict(nombre="Peso para la talla (DE)", que="10 kg para 78 cm.", min=-4, max=4, fmt="{}", ticks=[-2, 2],
                      bandas=[(-4, -2, "Aguda", 3), (-2, 2, "Normal", 0), (2, 4, "Sobrepeso", 2)], caso=0.3, caso_txt="Normal")],
         claves_titulo="Cómo se interpreta",
         claves=[("T/E baja + P/T normal", ["Desnutrición crónica"], True), ("P/T baja", ["Aguda"], False), ("Edema", ["Kwashiorkor"], False)]))

# SP-154 · ASIS local: determinantes · RADIAL
S("radial", "SP-154", "Un componente para elaborar el ASIS local es el análisis de los determinantes sociales de la salud",
  "Análisis de Situación de Salud (ASIS)",
  ("ASIS local", ["Describe y explica la salud de una población para priorizar problemas y planificar.",
                  "Componentes: determinantes (demográficos, socioeconómicos, ambientales, servicios), estado de salud (morbilidad, mortalidad), acción social y priorización."]),
  ("Pregunta de teoría", ["¿Cuál es un componente del ASIS local?"]),
  ["Lo elabora el equipo del establecimiento con la comunidad y el municipio.",
   "Las herramientas individuales (historia clínica, plan de atención, test de desarrollo) no son parte del ASIS.",
   "Termina en problemas priorizados y un plan de intervención."],
  MINSA + ", guía para el ASIS local (2015; act.).",
  op=("¿Componente?", ["No: medida de asociación", "No: individual", "Sí: base del ASIS", "No: individual", "No: individual"]),
  d=dict(rotulo="Componentes del ASIS local", centro="ASIS LOCAL", centro_sub="población", ans=0,
         items=[("DETERMINANTES SOCIALES", ["Pobreza, educación, agua, vivienda", "Esta pregunta"]), ("ESTADO DE SALUD", ["Morbilidad, mortalidad"]),
                ("ACCIÓN SOCIAL", ["Servicios, organización"]), ("PRIORIZACIÓN", ["Problemas y territorios"]), ("PLAN", ["Intervenciones"])],
         ruta=["Recoger datos", "Analizar determinantes", "Priorizar", "Planificar"]))

# CB-075 · Miofibroblastos: actina y miosina · FASES
S("fases", "CB-075", "Los miofibroblastos de la cicatrización se diferencian de los fibroblastos por tener más actina y miosina (contraen la herida)",
  "Patología general · reparación tisular",
  ("Fases de la cicatrización", ["Inflamatoria (0-3 días), proliferativa (3 días-3 semanas: tejido de granulación, miofibroblastos) y de remodelación (semanas a meses).",
                                 "El miofibroblasto tiene filamentos de actina de músculo liso (α-SMA) y miosina: contrae y acerca los bordes."]),
  ("Pregunta de teoría", ["¿Qué tienen más los miofibroblastos que los fibroblastos?"]),
  ["Exceso de contracción: contracturas (quemaduras).",
   "Desmina: músculo; citoqueratina: epitelios; vimentina: mesénquima.",
   "Colágeno III al inicio y luego colágeno I en la remodelación."],
  ROBBINS + ".",
  op=("¿Mayor cantidad de?", ["No: neuroendocrino y mesénquima", "No: músculo estriado", "Sí: contráctiles", "No: epitelio y músculo esquelético", "Los producen, pero no los distingue"]),
  d=dict(rotulo="Fases de la cicatrización", ans=1,
         fases=[("Inflamatoria", "0-3 días", "NEUTRÓFILOS Y MACRÓFAGOS", ["Limpieza"]),
                ("Proliferativa", "3 días-3 sem", "MIOFIBROBLASTOS (ACTINA + MIOSINA)", ["Granulación, contracción", "Esta pregunta"]),
                ("Remodelación", "Semanas-meses", "COLÁGENO I", ["Cicatriz más fuerte"])]))

# PED-198 · Trisomía 13 · TARJETAS
S("tarjetas", "PED-198", "Neonato con holoprosencefalia, hipotelorismo, labio y paladar hendido, polidactilia, onfalocele y cardiopatía: trisomía 13 (síndrome de Patau)",
  "Cromosomopatías",
  ("Trisomía 13 (Patau)", ["Defectos de la línea media: holoprosencefalia, hipotelorismo, labio y paladar hendido, onfalocele.",
                           "Polidactilia postaxial, cardiopatía, aplasia cutis; mortalidad muy alta en el primer año."]),
  ("Neonato", ["Mal estado, bajo peso; hipotelorismo, polidactilia, onfalocele, labio leporino y fisura palatina.", "Soplo importante; eco prenatal: probable holoprosencefalia."]),
  ["Cariotipo para confirmar.",
   "Cuidados paliativos y consejo genético; riesgo de recurrencia bajo salvo translocación.",
   "Tamizaje prenatal: ADN fetal libre y ecografía."],
  NELSON + "; Smith, Patrones reconocibles de malformaciones 8.ª ed.",
  op=("¿Trisomía?", ["No: mosaico, rara", "No: hipotonía y cara típica", "Sí: holoprosencefalia + polidactilia", "No: puños cerrados, pies en mecedora", "No: talla baja, linfedema"]),
  d=dict(rotulo="Las trisomías más frecuentes", ans=2,
         cards=[dict(titulo="Trisomía 21 (Down)", datos=[("Clave", "Hipotonía", False), ("Corazón", "Canal AV", False), ("Vida", "Adulta", False)], pie="La más frecuente."),
                dict(titulo="Trisomía 18 (Edwards)", datos=[("Manos", "Puños cerrados", False), ("Pies", "En mecedora", False), ("Vida", "Meses", False)], pie="Occipucio prominente."),
                dict(titulo="Trisomía 13 (Patau)", datos=[("Clave", "Holoprosencefalia", True), ("Manos", "Polidactilia", True), ("Cara", "Labio y paladar", True)], pie="Este caso."),
                dict(titulo="Monosomía X (Turner)", datos=[("Sexo", "Mujer", False), ("Clave", "Talla baja, linfedema", False), ("Corazón", "Coartación", False)], pie="45,X.")]),
  triada=TR([("Holoprosencefalia", "Probable en la eco", True), ("Labio y paladar hendido", "Sí", True), ("Polidactilia", "Sí", True)],
            [("Tríada de Patau", 0, 2)], "Con onfalocele y cardiopatía: confirmar con cariotipo."))

# GIN-210 · Corioamnionitis en fase activa avanzada · DECISIÓN
S("decision", "GIN-210", "Gestante de 35 semanas con corioamnionitis (fiebre, taquicardia fetal, líquido fétido) y 8 cm de dilatación con presentación en +1: antibióticos y parto vaginal",
  "Infección intraamniótica · vía del parto",
  ("Corioamnionitis y vía del parto", ["La infección indica terminar la gestación, pero no indica cesárea por sí sola.",
                                       "Si el trabajo de parto avanza (8 cm, +1), antibiótico y parto vaginal; la cesárea solo por indicación obstétrica."]),
  ("Segundigesta de 35 semanas", ["RPM de 15 horas y fiebre; T 38,7 °C.", "LCF 180; 8 cm, 80 %, +1; membranas rotas con mal olor."]),
  ["Ampicilina + gentamicina EV; antipirético; neonatología presente.",
   "Corticoides no sirven aquí (35 sem y parto inminente); tocólisis contraindicada.",
   "Tras cesárea (si se hiciera): añadir clindamicina o metronidazol."],
  ACOG + " n.º 712 (2017); " + MINSA + ".",
  op=("¿Manejo?", ["No: sin indicación", "Sí: parto avanzado", "No: la infección no indica cesárea", "No: sin antibiótico y no sirve", "No: contraindicada"]),
  d=dict(rotulo="Corioamnionitis: ¿cómo termina?", eje_y="Trabajo de parto", ancho_filas=180,
         cols=["Sin otra indicación de cesárea", "Con indicación obstétrica"],
         rows=[("Avanzado (8 cm, +1)", "Este caso"), ("No iniciado o lento", "")],
         cells=[[("ANTIBIÓTICO + PARTO VAGINAL", []), ("Antibiótico + cesárea", [])],
                [("Antibiótico + inducción", ["Oxitocina"]), ("Antibiótico + cesárea", [])]],
         caso=(0, 0), nota="Siempre antibiótico; la vía la decide la obstetricia."))

# CAR-066 · AESP · ÁRBOL + ECG
S("arbol", "CAR-066", "Paciente en paro con actividad eléctrica en el monitor pero ritmo no desfibrilable: actividad eléctrica sin pulso",
  "Reanimación · ritmos de paro",
  ("Actividad eléctrica sin pulso (AESP)", ["Hay un ritmo organizado en el monitor, pero el corazón no genera pulso.",
                                            "No se desfibrila: RCP + adrenalina y buscar causas reversibles (5 H y 5 T: hipovolemia, hipoxia, H⁺, K, hipotermia; taponamiento, tensión, trombosis, tóxicos)."]),
  ("Mujer de 71 años", ["Cae súbitamente; se inician compresiones.", "El DEA muestra actividad, pero no recomienda descarga."]),
  ["RCP de calidad + adrenalina 1 mg cada 3-5 min.",
   "Ecografía para buscar taponamiento, neumotórax, TEP o hipovolemia.",
   "Asistolia: línea plana (también no desfibrilable)."],
  AHA + "; ERC (2025).",
  op=("¿Diagnóstico?", ["Sí: actividad sin pulso, no desfibrilable", "No: no hay actividad", "No: es desfibrilable", "No: es desfibrilable", "No: tendría pulso"]),
  arbol=Q("Paro: ¿el ritmo es desfibrilable?", [
      L("Sí: FV o TV sin pulso", "Descarga", ["Y RCP"]),
      L("No, con actividad organizada (este caso)", "ACTIVIDAD ELÉCTRICA SIN PULSO", ["RCP + adrenalina", "Buscar 5 H y 5 T"], path=True),
      L("No, línea plana", "Asistolia", ["RCP + adrenalina"])], path=True),
  banda=B("Lo que muestra el monitor", DOS(P("ecg_normal_ii.jpg", 220, 44, [], credito="Trazado de enseñanza MedQuizPro", fondo="#ffffff"),
                                           P("ecg_asistolia.jpg", 220, 44, [], credito="Trazado de enseñanza MedQuizPro", fondo="#ffffff")),
          [("Izquierda: ritmo organizado", "Si no hay pulso, es AESP."), ("Derecha: asistolia", "Línea plana."), ("Ninguno se descarga", "RCP y adrenalina.")],
          pie="Trazados de enseñanza."))

# SP-155 · Radar de gestantes · SEMÁFORO
S("semaforo", "SP-155", "El instrumento del primer nivel para vigilar y hacer seguimiento a las gestantes es el radar de gestantes",
  "Salud materna · vigilancia de la gestante",
  ("Radar de gestantes (MINSA)", ["Padrón nominal y mapa de las gestantes del territorio, clasificadas por riesgo con colores.",
                                  "Permite saber quién no vino a su control, programar visitas domiciliarias y referir a tiempo."]),
  ("Pregunta de teoría", ["¿Qué instrumento permite la vigilancia y seguimiento de las gestantes en el primer nivel?"]),
  ["Se actualiza en cada control y visita; se usa con el plan de parto.",
   "Claves roja, azul y amarilla: kits para emergencias (hemorragia, preeclampsia, sepsis), no para seguimiento.",
   "«El camino del buen crecimiento» es para el niño."],
  MINSA + ", NTS de atención integral de la salud materna (2023).",
  op=("¿Instrumento?", ["No: es del niño", "Educan, no vigilan", "Son para emergencias", "Sí: padrón y mapa por riesgo", "No: es de emergencia"]),
  d=dict(rotulo="Cómo clasifica el radar a las gestantes", tag="RADAR",
         ilu_titulo="La gestante",
         ilu=ILU(D(lambda s, x, y: I.gestante(s, x + 100, y, sc=0.6), 330, 270)),
         ilu_pie="Cada gestante en el mapa del territorio.",
         check_titulo="Lo que hace el radar",
         check=[("Ubica a cada gestante en el mapa", True), ("Clasifica su riesgo por colores", True), ("Detecta a las que faltan al control", True)],
         luces=[("Verde · sin riesgo", "Controles al día", ["Seguimiento habitual"]),
                ("Amarillo · riesgo o falta a controles", "Factor de riesgo o inasistencia", ["Visita domiciliaria"]),
                ("Rojo · alto riesgo", "Signos de alarma o patología", ["Referir"])], ans=-1))

# OFT-047 · Epistaxis anterior: rinitis seca · EMBUDO
S("embudo", "OFT-047", "La causa más frecuente de epistaxis anterior es la rinitis seca anterior (mucosa seca y costras en el plexo de Kiesselbach)",
  "Epistaxis",
  ("Epistaxis anterior", ["90 % de las epistaxis; sale del plexo de Kiesselbach (tabique anterior).",
                          "Causa más frecuente: sequedad de la mucosa (aire seco, calefacción, rinitis) y rascado digital; luego trauma, cuerpos extraños, coagulopatías."]),
  ("Pregunta de teoría", ["¿Causa más frecuente de epistaxis anterior?"]),
  ["Presión digital 10-15 minutos inclinado hacia adelante.",
   "Si sigue: cauterización con nitrato de plata o taponamiento anterior.",
   "Prevención: humidificar, vaselina o suero en la nariz, no rascar."],
  "AAO-HNS, epistaxis (2020).",
  op=("¿Causa más frecuente?", ["Rara", "Rara", "Sí: sequedad + costras", "Frecuente, pero menos", "Rara"]),
  d=dict(rotulo="Epistaxis anterior: ¿por qué sangra?", inicio="Sangrado nasal anterior",
         candidatos=["Tumor nasal", "Coagulopatía", "Barotrauma", "Trauma nasal", "Rinitis seca anterior"],
         pasos=[("¿Hay sangrado unilateral recurrente con obstrucción o sangrados en otros sitios?", ["Tumor nasal", "Coagulopatía"]),
                ("¿Hubo un golpe o un cambio brusco de presión?", ["Trauma nasal", "Barotrauma"])],
         final=("RINITIS SECA ANTERIOR", ["Costras en el Kiesselbach", "Humidificar"]),
         nota="Es la causa más común: aire seco y rascado."))

# PED-199 · Fenotipos de sibilancias (Tucson) · GRÁFICA
S("grafica", "PED-199", "Niña de 6 años con sibilancias desde los 4 años, dermatitis atópica y sensibilización a ácaros: fenotipo de sibilancias de inicio tardío (atópico)",
  "Sibilancias en la infancia · fenotipos",
  ("Fenotipos de Tucson", ["Transitorias precoces: < 3 años, por vías aéreas pequeñas; desaparecen a los 6.",
                           "Persistentes: empiezan < 3 años y siguen > 6. Inicio tardío: después de los 3 años, ligadas a atopia: predicen asma."]),
  ("Niña de 6 años", ["Sibilancias recurrentes desde los 4 años; dermatitis atópica.", "Mejora con salbutamol; prick positivo a ácaros."]),
  ["Índice predictivo de asma: sibilancias + dermatitis atópica o padre asmático → alto riesgo de asma.",
   "Tratamiento como asma: corticoide inhalado si es persistente.",
   "Control ambiental de ácaros."],
  "Martínez et al. (Tucson, 1995); " + GINA + ".",
  op=("¿Fenotipo?", ["Sí: después de los 3 años + atopia", "No: < 3 años y desaparecen", "No: empiezan < 3 años", "No es fenotipo de Tucson clásico", "No: sin pistas de reflujo"]),
  d=dict(rotulo="Fenotipos de sibilancias según la edad", eje_x="Edad (años)", eje_y="Sibilancias (%)",
         x=(0, 12, [(0, "0"), (3, "3"), (6, "6"), (9, "9"), (12, "12")]),
         y=(0, 30, [(0, "0"), (15, "15"), (30, "30")]),
         series=[("Transitoria precoz", [(0, 20), (1.5, 24), (3, 16), (6, 3), (8, 1), (12, 1)], "#94a3b8"),
                 ("Persistente", [(0, 8), (3, 12), (6, 14), (9, 13), (12, 12)], "#2563eb"),
                 ("Inicio tardío", [(0, 0), (3, 1), (4, 6), (6, 13), (9, 15), (12, 15)], "#f97316")],
         zonas=[(3, 12, "después de los 3 años", "#ffedd5")],
         caso=(6, 13, "6 años"),
         notas=[("Empezó a los 4 años", "Después de los 3: inicio tardío.", True),
                ("Dermatitis atópica + ácaros", "Atopia: predice asma.", True),
                ("Transitorias", "Empiezan antes y desaparecen a los 6.", False)],
         veredicto=("Inicio tardío (atópico)", "Manejar como asma.")))

# GIN-211 · Sulfato de magnesio hasta 24 h posparto · RELOJ
S("reloj", "GIN-211", "Puérpera con preeclampsia severa en tratamiento con sulfato de magnesio: se mantiene hasta 24 horas después del parto",
  "Preeclampsia severa · sulfato de magnesio",
  ("Sulfato de magnesio", ["Previene la eclampsia en la preeclampsia con criterios de severidad.",
                           "Carga 4-6 g EV en 20 min y mantenimiento 1-2 g/h; se continúa 24 h después del parto (o de la última convulsión)."]),
  ("Puérpera inmediata", ["Preeclampsia con criterios de severidad.", "Recibe sulfato de magnesio."]),
  ["Vigilar reflejos rotulianos, FR ≥ 12 y diuresis ≥ 30 mL/h cada hora.",
   "Toxicidad: suspender y dar gluconato de calcio 1 g EV.",
   "Con falla renal: reducir la dosis de mantenimiento."],
  ACOG + " n.º 222 (2020); " + OMS + " (2011; act.); " + MINSA + ".",
  op=("¿Hasta cuándo?", ["No: el riesgo sigue", "No: excesivo", "Sí: 24 h posparto", "No: se cuenta desde el parto", "No: excesivo"],
      {3: "24 h tras el diagnóstico"}),
  d=dict(rotulo="El sulfato de magnesio en el tiempo", tag="HASTA AQUÍ",
         pasos=[("0 min", "Dosis de carga", "4-6 g EV en 20 min", False), ("+1 h", "Mantenimiento", "1-2 g/h; reflejos, FR, diuresis", False),
                ("Parto", "Seguir", "El riesgo persiste en el puerperio", False), ("24 h", "Suspender", "24 h tras el parto", True)],
         veredicto=("Hasta 24 horas después del parto", "Vigilando reflejos, respiración y diuresis.")))

# NEU-061 · Síndrome seudogripal por rifampicina · CUADRÍCULA
S("cuadricula", "NEU-061", "Paciente con un mes de tratamiento antituberculoso que presenta fiebre, escalofríos y mialgias: síndrome seudogripal por rifampicina",
  "Tuberculosis · efectos adversos",
  ("Efectos adversos de la rifampicina", ["Síndrome seudogripal (fiebre, escalofríos, mialgias), más con dosis intermitentes; hepatitis; trombocitopenia; orina y lágrimas naranjas.",
                                          "Induce enzimas hepáticas: baja el efecto de anticonceptivos, warfarina, antirretrovirales."]),
  ("Varón de 48 años", ["Un mes de tratamiento antituberculoso.", "Fiebre, escalofríos y mialgias."]),
  ["Descartar otras causas (TB que no responde, infección, hepatitis).",
   "Leve: sintomáticos; grave (anemia hemolítica, falla renal, choque): suspender la rifampicina definitivamente.",
   "Revisar interacciones."],
  OMS + ", guías consolidadas de TB (2025); " + MINSA + ".",
  op=("¿Fármaco?", ["No: neuritis óptica", "No: gota, hepatitis", "Sí: seudogripal", "No: neuropatía, hepatitis", "No: ototoxicidad"]),
  d=dict(rotulo="Efecto adverso típico de cada antituberculoso", alto_img=0,
         celdas=[("Rifampicina", ["Seudogripal, orina naranja, interacciones", "Este caso"], None, True),
                 ("Isoniazida", ["Neuropatía (dar B6), hepatitis"], None, False),
                 ("Pirazinamida", ["Ácido úrico alto, gota, hepatitis"], None, False),
                 ("Etambutol", ["Neuritis óptica (colores)"], None, False)],
         veredicto=("Fiebre, escalofríos y mialgias = rifampicina", "Seudogripal; suspender si es grave.")))

# PED-200 · Bronquiolitis con dificultad respiratoria: hospitalizar · ALARMA + Rx
S("alarma", "PED-200", "Lactante de 2 meses con bronquiolitis (congestión, tos, sibilantes) y aleteo nasal con tiraje: hospitalizar para monitoreo e hidratación",
  "Bronquiolitis",
  ("Bronquiolitis", ["Infección viral (VSR) de los bronquiolos en < 2 años: rinorrea, tos, sibilantes y crepitantes.",
                     "El tratamiento es de soporte: oxígeno si SatO₂ < 90-92 %, hidratación, aspiración nasal. Broncodilatadores, corticoides y antibióticos no sirven."]),
  ("Lactante de 2 meses", ["4 días de congestión nasal y tos.", "SatO₂ 97 %, FR 40; aleteo nasal, tiraje subcostal e intercostal; sibilantes."]),
  ["Hospitalizar si: < 3 meses con dificultad, tiraje marcado, apneas, SatO₂ < 92 %, no se alimenta, deshidratación.",
   "Aspiración nasal, hidratación (sonda nasogástrica si no come), oxígeno si hace falta; posición semisentada.",
   "Prevención: nirsevimab o palivizumab en grupos de riesgo."],
  AAP + ", bronquiolitis (2014; act.); NICE NG9 (2021).",
  op=("¿Actitud?", ["No: no sirven en bronquiolitis", "Sí: < 3 meses con tiraje", "No: hay signos de gravedad", "No: es viral", "No: viral y grave"],
      {0: "β2 nebulizado + corticoide oral", 2: "Alta con salbutamol y control en 24 h"}),
  d=dict(rotulo="Signos para hospitalizar en la bronquiolitis", lista_titulo="Lo que tiene el lactante",
         signos=[("Menor de 3 meses", "2 meses", True), ("Aleteo nasal y tiraje", "Sí", True), ("Apneas", "No se informa", False),
                 ("SatO₂ < 92 %", "97 %", False), ("No se alimenta o deshidratado", "No se informa", False)],
         img=P("bronquiolitis_rx.jpg", 240, 234, [], credito="Di Nardo et al." + CC + "CC BY 2.0"), img_titulo="Rx: hiperinsuflación",
         accion=("Hospitalizar: monitoreo e hidratación", "Oxígeno solo si SatO₂ < 92 %."),
         accion_rotulo="CON SIGNOS DE ALARMA",
         veredicto=("< 3 meses con tiraje y aleteo: hospitalizar", "Sin broncodilatadores, corticoides ni antibióticos.")))

# END-060 · Osteomalacia por déficit de vitamina D · LABORATORIO
S("laboratorio", "END-060", "Adulto con poco sol, dolores óseos, debilidad proximal, calcio y fósforo bajos, fosfatasa alcalina y PTH altas: osteomalacia por déficit de vitamina D",
  "Metabolismo óseo · osteomalacia",
  ("Osteomalacia", ["Hueso mal mineralizado por falta de vitamina D (poco sol, malabsorción, falla renal o hepática).",
                    "Dolor óseo difuso, debilidad proximal (marcha de pato), fracturas; Ca y P bajos, fosfatasa alcalina y PTH altas (hiperparatiroidismo secundario)."]),
  ("Enfermero de 34 años", ["Largas jornadas en UCI durante la pandemia (poca exposición al sol).", "Dolores osteoarticulares crecientes, debilidad proximal; Ca y P bajos, FA alta, PTH 100, osteopenia."]),
  ["Medir 25-OH-vitamina D.",
   "Colecalciferol en dosis de carga (p. ej. 50 000 UI/semana 8 semanas) y luego mantenimiento + calcio.",
   "Exposición solar y dieta."],
  "Endocrine Society, vitamina D (2024); " + HARRISON + ".",
  op=("¿Vitamina?", ["No: escorbuto", "No: ojos y piel", "No: neuropatía, hemólisis", "Sí: mineraliza el hueso", "No: anemia y neuropatía"]),
  d=dict(rotulo="El laboratorio del caso",
         valores=[("Calcio", "Bajo", "8,5-10,5", "↓", "Poca absorción intestinal."), ("Fósforo", "Bajo", "2,5-4,5", "↓", "La PTH alta lo elimina por la orina."),
                  ("Fosfatasa alcalina", "Alta", "40-130", "↑", "Osteoblastos trabajando sin mineralizar."),
                  ("PTH", "100 pg/mL", "15-65", "↑", "Hiperparatiroidismo secundario."), ("25-OH-vitamina D", "Por pedir", "> 30 ng/mL", "=", "Confirmará el déficit.")],
         veredicto=("Ca ↓ + P ↓ + FA ↑ + PTH ↑ = osteomalacia por falta de vitamina D", "Colecalciferol y calcio.")))

# NEU-062 · NAC con confusión: ceftriaxona + azitromicina · ÁRBOL + CURB-65
S("arbol", "NEU-062", "Mujer con neumonía, FR 28 y confusión (CURB-65 ≥ 1 con confusión): hospitalizar y tratar con ceftriaxona + azitromicina",
  "Neumonía adquirida en la comunidad · tratamiento",
  ("Antibiótico en la NAC hospitalizada", ["Debe cubrir neumococo (betalactámico: ceftriaxona) y atípicos (macrólido: azitromicina).",
                                           "Alternativa: levofloxacino solo. Antipseudomónicos y anti-SARM solo si hay factores de riesgo."]),
  ("Mujer de 53 años", ["2 días de tos amarillenta y sensación de fiebre.", "PA 120/70, FR 28, SatO₂ 94 %, confusa; opacidad basal izquierda; leucocitosis con desviación."]),
  ["Ceftriaxona 1-2 g EV/día + azitromicina 500 mg/día, 5-7 días.",
   "Hemocultivos; reevaluar a las 48-72 h.",
   "La confusión es criterio de gravedad: vigilar."],
  "ATS/IDSA, neumonía comunitaria (2019); BTS.",
  op=("¿Tratamiento?", ["No: para nosocomial/aspiración", "No: para nosocomial grave", "Sí: neumococo + atípicos", "No: no cubre bien neumococo", "No: necesita hospitalización"]),
  arbol=Q("Neumonía comunitaria: ¿dónde tratar? (CURB-65)", [
      L("0-1 sin confusión", "Ambulatorio", ["Amoxicilina"]),
      L("Confusión o ≥ 2 (este caso)", "HOSPITALIZAR: CEFTRIAXONA + AZITROMICINA", ["Neumococo + atípicos"], path=True),
      L("≥ 3 o choque", "UCI", ["Betalactámico + macrólido EV"])], path=True),
  escala=dict(nombre="CURB-65", modo="puntaje", que="Gravedad de la neumonía comunitaria (1 punto cada uno).",
              items=[("C", "Confusión", "Confusa", 1), ("U", "Urea > 7 mmol/L", "No informada", None), ("R", "FR ≥ 30", "28", 0),
                     ("B", "PA < 90/60", "120/70", 0), ("65", "Edad ≥ 65", "53", 0)],
              total_txt="Total: 1 (confusión)", total_nota="máximo 5",
              rangos=[("0", "Leve", "Ambulatorio"), ("1-2", "Moderada", "Hospitalizar si hay confusión"), ("3-5", "Grave", "UCI")],
              caso_rango=1, porque=[("La confusión sola ya obliga a hospitalizar", True)], conducta="Ceftriaxona + azitromicina EV."))

# CIR-109 · Peritonitis biliar poscolecistectomía · CASCADA
S("cascada", "CIR-109", "Paciente a las 24 horas de una colecistectomía con fiebre, hipotensión, taquicardia y abdomen con contractura y rebote: peritonitis biliar (fuga biliar)",
  "Complicaciones de la colecistectomía",
  ("Fuga biliar poscolecistectomía", ["Por clip del cístico que se suelta, lesión de la vía biliar o conductos accesorios (de Luschka).",
                                      "La bilis en el peritoneo da peritonitis química y luego infectada: dolor, fiebre, distensión, sepsis."]),
  ("Mujer de 60 años, 24 h posoperada", ["Dolor y contractura abdominal.", "T 39 °C, PA 90/60, FC 100, FR 26; rebote (+); leucocitos 14 000."]),
  ["Reanimación con líquidos, antibióticos (piperacilina-tazobactam).",
   "Eco o TC (colección) y gammagrafía HIDA o CPRE para ubicar la fuga.",
   "Peritonitis generalizada: lavado y drenaje (laparoscopía/laparotomía); CPRE con prótesis para la fuga."],
  "Guías de Tokio (2018); SAGES; Sabiston Tratado de Cirugía 21.ª ed.",
  op=("¿Diagnóstico?", ["Sí: fuga de bilis al peritoneo", "No: ictericia, sin peritonitis", "No: no explica el rebote", "No: sin datos", "No: no explica peritonitis"]),
  d=dict(rotulo="De la fuga a la sepsis", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Se suelta el clip o se lesiona la vía", "Sale bilis", [("Dolor abdominal", "En las primeras 24-72 h", False)]),
                ("Bilis en el peritoneo", "Irrita (peritonitis química)", [("Contractura y rebote", "Este caso", True)]),
                ("Se infecta", "Bacterias intestinales", [("Fiebre 39 °C, leucocitos 14 000", "Infección", True)]),
                ("Sepsis", "Vasodilatación", [("PA 90/60, FC 100", "Reanimar", True)])],
         veredicto=("Peritonitis biliar", "Reanimar, antibióticos, drenar y CPRE.")))

# PED-201 · Apendicitis aguda en el niño · LECTURA + eco
S("lectura", "PED-201", "Niño de 7 años con dolor periumbilical que migra a fosa ilíaca derecha, fiebre, vómitos, rebote y leucocitosis: apendicitis aguda",
  "Abdomen agudo en el niño",
  ("Apendicitis en el niño", ["Dolor que empieza alrededor del ombligo y migra a la fosa ilíaca derecha, anorexia, náuseas, fiebre moderada, rebote.",
                              "Puntaje pediátrico (PAS) o Alvarado; ecografía como primera imagen."]),
  ("Niño de 7 años, 8 horas", ["Dolor abdominal, fiebre, hiporexia, náuseas y vómitos.", "T 38,5 °C; dolor periumbilical que va a FID; rebote (+); leucocitos 12 000, neutrófilos 8500."]),
  ["Ecografía: apéndice > 6 mm, no compresible.",
   "Apendicectomía (laparoscópica) + antibiótico.",
   "En niños pequeños se perfora más rápido."],
  "WSES, apendicitis (2020); APSA (2022).",
  op=("¿Diagnóstico?", ["No: sin síntomas urinarios", "Sí: migración + rebote + leucocitosis", "No: dolor escrotal", "Posible, pero sin rebote ni migración", "No: sin diarrea, con rebote"]),
  d=dict(rotulo="Lee la ecografía", img_titulo="Apendicitis en la ecografía",
         img=P("apendicitis_eco.jpg", 300, 259, credito="Borbély Márton" + CC + "CC BY-SA 4.0"), pines=[(0.5, 0.5)],
         pasos=[("Apéndice engrosado (> 6 mm)", "No se comprime con el transductor.", True),
                ("Grasa alrededor brillante", "Inflamación.", False),
                ("Líquido o apendicolito", "Complicación.", False),
                ("Tratar", "Apendicectomía + antibiótico.", False)],
         img_pie="Ecografía de otra persona.",
         veredicto=("Migración a FID + rebote + leucocitosis = apendicitis", "Ecografía y cirugía.")),
  triada=TR([("Dolor que migra a FID", "Sí", True), ("Fiebre y vómitos", "Sí", True), ("Rebote (Blumberg)", "Sí", True)],
            [("Pistas de apendicitis", 0, 2)], "Leucocitos 12 000 con neutrofilia apoyan."))

# CIR-110 · Quemadura por inhalación: intubación temprana · MAPA DE SIGNOS
S("mapa_signos", "CIR-110", "Explosión en la cocina con voz ronca, esputo carbonáceo, vellos nasales quemados, edema de orofaringe y dificultad respiratoria: lesión por inhalación, intubación temprana",
  "Quemaduras · lesión por inhalación",
  ("Lesión inhalatoria", ["El calor y el humo queman la vía aérea superior: el edema crece en horas y puede cerrarla.",
                          "Signos de alarma: voz ronca, estridor, esputo carbonáceo, quemadura facial, vellos chamuscados, edema orofaríngeo: intubar temprano."]),
  ("Varón de 37 años, explosión hace 10 h", ["Voz ronca, esputo negruzco, dificultad respiratoria.", "PA 90/70, FR 34, SatO₂ 92 %; vellos nasales quemados, edema orofaríngeo con restos carbonizados."]),
  ["Intubación con tubo grueso por el más experto, antes de que el edema la impida.",
   "Oxígeno al 100 % (monóxido de carbono); sospechar cianuro (hidroxocobalamina).",
   "Broncoscopía para graduar; líquidos según la superficie quemada."],
  "ABA, guías de lesión inhalatoria; " + ATLS + " (2025).",
  op=("¿Prioridad?", ["Sí: asegurar la vía aérea", "Insuficiente: el edema cerrará la vía", "No: sin beneficio", "Necesario, pero no basta", "No: sin indicación"]),
  d=dict(rotulo="Signos de vía aérea quemada", PH=480, tag="INTUBAR",
         ilu_titulo="Vía aérea quemada (esquema)",
         ilu=lambda s, x, y: I.via_aerea_quemada(s, x + 2, y + 40, sc=0.84),
         ilu_pie="Hollín y edema en la vía aérea superior.",
         signos=[dict(tit="Voz ronca", lines=["Edema de la laringe."]),
                 dict(tit="Esputo carbonáceo", lines=["Inhaló humo y hollín."]),
                 dict(tit="Vellos nasales quemados", lines=["Calor en la cara y la vía aérea."]),
                 dict(tit="Edema orofaríngeo y FR 34", lines=["La vía se está cerrando."]),
                 dict(tit="Intubación endotraqueal ya", on=True, lines=["Antes de que el edema la impida; oxígeno al 100 %."])]))

# GIN-212 · Pelvis estrecha: cesárea · REGLA
S("regla", "GIN-212", "Gestante a término con conjugado diagonal de 10,5 cm y diámetro biisquiático de 8 cm: pelvis estrecha (superior e inferior), cesárea",
  "Distocias · pelvis estrecha",
  ("Pelvimetría clínica", ["Conjugado diagonal ≥ 11,5-12 cm: estrecho superior adecuado (conjugado obstétrico ≈ diagonal − 1,5).",
                           "Biisquiático (estrecho inferior) ≥ 10 cm; ángulo subpúbico ≥ 90°. Varios diámetros estrechos = desproporción."]),
  ("Gestante de 39 semanas", ["Contracciones c/5 min; 0 cm, 0 %, −4; LCD, LCF 140.", "Conjugado diagonal 10,5 cm; biciático 10 cm; biisquiático 8 cm; ángulo > 90°."]),
  ["Pelvis estrecha en el estrecho superior y en el inferior: cesárea.",
   "No inducir ni madurar: no hay espacio para el paso.",
   "Hoy se prefiere la prueba de trabajo de parto si la estrechez es dudosa; aquí es clara."],
  WILLIAMS + "; " + MINSA + ".",
  op=("¿Conducta?", ["No: no pasará", "No: no hay espacio", "No: no hay espacio", "Sí: desproporción", "No: presentación alta"]),
  d=dict(rotulo="Los diámetros de esta pelvis",
         reglas=[dict(nombre="Conjugado diagonal (cm)", que="Normal ≥ 11,5-12 cm.", min=8, max=14, fmt="{}", ticks=[11.5],
                      bandas=[(8, 11.5, "Estrecho", 3), (11.5, 14, "Adecuado", 0)], caso=10.5, caso_txt="ESTE CASO: 10,5"),
                 dict(nombre="Biisquiático (cm)", que="Normal ≥ 10 cm.", min=6, max=12, fmt="{}", ticks=[10],
                      bandas=[(6, 10, "Estrecho", 3), (10, 12, "Adecuado", 0)], caso=8, caso_txt="8 cm")],
         claves_titulo="Conclusión",
         claves=[("Estrecho superior e inferior", ["Desproporción"], True), ("Presentación −4", ["No encaja"], True), ("Cesárea", ["Programada o en trabajo de parto"], True)]))

# PSI-040 · Maltrato psicológico infantil · CHECKLIST
S("checklist", "PSI-040", "Niño con tristeza cuyo padre lo culpa, humilla e insulta constantemente: maltrato psicológico, informar a la autoridad competente",
  "Violencia contra niños · maltrato psicológico",
  ("Maltrato psicológico", ["Humillar, insultar, culpar, amenazar o rechazar de forma reiterada es violencia contra el niño.",
                            "El personal de salud está obligado a comunicarlo (Ley 30364, Código de los Niños y Adolescentes)."]),
  ("Niño de 8 años", ["Traído por su tía por cefalea; facies triste.", "La madre se fue hace un año; el padre lo culpa, humilla e insulta."]),
  ["Atender la salud y registrar en la historia.",
   "Comunicar a la autoridad: Policía, Fiscalía de Familia, DEMUNA o Centro Emergencia Mujer.",
   "Apoyo psicológico y social; plan de protección (la tía puede ser figura protectora)."],
  "Ley n.º 30364; Código de los Niños y Adolescentes; " + MINSA + ", guía de atención de la violencia.",
  op=("¿Conducta?", ["Sí: obligación legal", "Puede empeorar el riesgo", "Complementa, no reemplaza", "Complementa, no reemplaza", "No: deja al niño desprotegido"]),
  d=dict(rotulo="Qué hacer ante el maltrato infantil", tag="OBLIGATORIO",
         pasos=[("Informar a la autoridad competente", "Policía, Fiscalía, DEMUNA o CEM", True), ("Atender y registrar", "Historia clínica detallada", False),
                ("Psicología y servicio social", "Apoyo al niño", False), ("Plan de protección", "Familiar de confianza", False)],
         no_hacer=[("Confrontar al padre", "Aumenta el riesgo"), ("Dar de alta sin intervenir", "Deja al niño expuesto"), ("Solo derivar sin denunciar", "La comunicación es obligatoria")],
         veredicto=("Comunicar a la autoridad", "Además de atender y dar apoyo psicológico.")))

# NEF-082 · LRA posrenal: globo vesical · CUADRÍCULA
S("cuadricula", "NEF-082", "Joven con cólico renal y hematuria que luego tiene dolor suprapúbico, oliguria, masa en hipogastrio (globo vesical), creatinina 2,8 y K 5,6: lesión renal aguda posrenal",
  "Lesión renal aguda · tipos",
  ("Lesión renal aguda posrenal", ["Obstrucción del flujo de orina (cálculo, coágulo, próstata, tumor): el riñón se dilata y deja de filtrar.",
                                   "Globo vesical = obstrucción baja (uretra o cuello vesical): se resuelve con sonda vesical."]),
  ("Varón de 24 años", ["Hace 3 días cólico lumbar derecho con hematuria; hoy dolor suprapúbico y menos orina.", "Masa en hipogastrio; creatinina 2,8; K 5,6."]),
  ["Sonda vesical: alivia y confirma (sale mucha orina).",
   "Ecografía renal y vesical; buscar cálculo en la uretra o coágulo.",
   "Vigilar poliuria posobstructiva y el potasio."],
  KDIGO + ", lesión renal aguda (2012; act. 2025).",
  op=("¿Tipo?", ["No: sin hipovolemia", "No: no hay daño del parénquima", "Igual a renal", "Sí: obstrucción (globo vesical)", "No"]),
  d=dict(rotulo="Tres tipos de lesión renal aguda", alto_img=120,
         celdas=[("Posrenal (obstrucción)", ["Globo vesical, hidronefrosis", "Sonda vesical"], P("hidronefrosis.jpg", 330, 199), True),
                 ("Prerrenal", ["Deshidratación, hipotensión", "Líquidos"], None, False),
                 ("Renal (intrínseca)", ["Necrosis tubular, glomerulonefritis", "Cilindros"], None, False),
                 ("Pista de este caso", ["Masa en hipogastrio = vejiga llena", "Tras un cólico con hematuria"], None, False)],
         credito="Hidronefrosis: James Heilman · Wikimedia Commons · CC BY-SA 3.0",
         veredicto=("Globo vesical + oliguria = LRA posrenal", "Sonda vesical primero.")))

# REU-061 · Dermatomiositis: biopsia muscular · CRITERIOS + foto
S("criterios", "REU-061", "Mujer con debilidad proximal progresiva, pápulas de Gottron, dolor muscular y CPK de 34 000: dermatomiositis, la biopsia muscular confirma",
  "Miopatías inflamatorias",
  ("Dermatomiositis", ["Miopatía inflamatoria con lesiones de piel: pápulas de Gottron, heliotropo, eritema en «V» y en chal.",
                       "Debilidad proximal simétrica, CPK alta; la biopsia muscular confirma (inflamación perifascicular). Buscar cáncer en el adulto."]),
  ("Mujer de 40 años, 3 meses", ["Dificultad para levantarse de la silla y subir al micro.", "Pápulas eritematosas en el dorso de los dedos; dolor muscular de cinturas; CPK 34 000."]),
  ["Biopsia muscular (guiada por RM); anticuerpos específicos (anti-Mi-2, anti-TIF1γ, anti-MDA5).",
   "Prednisona 1 mg/kg + metotrexato o azatioprina; inmunoglobulina EV si es grave.",
   "Tamizaje de cáncer (ovario, pulmón, mama, colon) y de enfermedad pulmonar intersticial."],
  "EULAR/ACR, miopatías inflamatorias (2017); " + HARRISON + ".",
  op=("¿Examen que confirma?", ["No: es miopatía, no neuropatía", "Apoya (patrón miopático), no confirma", "Orienta la biopsia", "Sí: confirma la inflamación", "Poco específica"]),
  d=dict(rotulo="Criterios de Bohan y Peter", lista_titulo="Lo que tiene ella",
         items=[("Debilidad proximal simétrica", True, "Cinturas escapular y pélvica"), ("Enzimas musculares altas", True, "CPK 34 000"),
                ("Lesiones de piel típicas", True, "Pápulas de Gottron"), ("Electromiografía miopática", None, "Apoya"),
                ("Biopsia muscular con inflamación", None, "Confirma: por pedir")],
         umbral="Piel + 3 criterios = dermatomiositis definida",
         veredicto="Dermatomiositis: confirmar con biopsia muscular y buscar cáncer.",
         img=P("gottron.jpg", 240, 190, [], credito="Dugan et al." + CC + "CC BY-SA 3.0"), img_titulo="Pápulas de Gottron",
         img_pie="Sobre los nudillos.", conteo="3 de 5 (falta la biopsia)"))

# CIR-111 · Trauma cerrado con peritonitis y neumoperitoneo: laparotomía · MONITOR
S("monitor", "CIR-111", "Conductor con trauma abdominal cerrado, hipotensión, taquicardia, peritonitis y signo de Jobert (neumoperitoneo): laparotomía exploradora",
  "Trauma abdominal cerrado",
  ("Indicaciones de laparotomía en el trauma cerrado", ["Inestabilidad con líquido libre, peritonitis, neumoperitoneo, evisceración.",
                                                        "Signo de Jobert: timpanismo en el área hepática (aire libre por perforación de víscera hueca)."]),
  ("Chofer de 50 años, 6 horas", ["Dolor epigástrico intenso; equimosis en el hemiabdomen superior.", "PA 90/50, FC 100, FR 24; RHA disminuidos, reacción peritoneal; Jobert (+); leucocitosis."]),
  ["Reanimación con sangre y cristaloides limitados; antibiótico.",
   "Laparotomía: reparar la víscera perforada (duodeno, yeyuno), controlar el sangrado.",
   "No retrasar por más estudios con peritonitis e inestabilidad."],
  ATLS + " (2025).",
  op=("¿Conducta?", ["No: ya hay peritonitis", "No: inestable", "No: ya hay indicación clara", "Sí: peritonitis + neumoperitoneo", "No: retrasa"]),
  d=dict(rotulo="Los signos vitales del caso", ecg="taquicardia sinusal 100",
         valores=[("PA", "90/50", "mmHg", "bajo"), ("FC", "100", "lpm", "alto"), ("FR", "24", "rpm", "alto"), ("JOBERT", "positivo", "aire libre", "alto"),
                  ("ABDOMEN", "peritonitis", "", "alto"), ("Hto", "40", "%", "ok")],
         lectura=[("Hipotensión + taquicardia", "Choque.", True), ("Peritonitis + Jobert", "Víscera hueca perforada.", True),
                  ("Hto 40 %", "Al inicio no refleja el sangrado.", False), ("Conducta", "Laparotomía exploradora.", True)],
         veredicto=("Peritonitis + neumoperitoneo + choque: laparotomía", "Sin más estudios.")))

# OFT-048 · ROP: primer examen a las 4 semanas · CRONOLOGÍA
S("cronologia", "OFT-048", "Prematura de 32 semanas con ventilación y oxígeno: el primer examen de retinopatía del prematuro se hace a las 4 semanas de vida (o a las 31 semanas posmenstruales)",
  "Retinopatía del prematuro · tamizaje",
  ("Tamizaje de la ROP", ["A quién: < 32-34 semanas o < 1500-1750 g, o más grandes con curso complicado (oxígeno, ventilación).",
                          "Cuándo: a las 4 semanas de vida o a las 31 semanas posmenstruales (lo que ocurra después)."]),
  ("Recién nacida de 32 semanas", ["Ventilación mecánica con FiO₂ 40 % por varios días.", "¿Cuándo el primer examen oftalmológico?"]),
  ["Fondo de ojo con oftalmoscopio indirecto tras dilatar la pupila.",
   "Repetir cada 1-2 semanas según los hallazgos hasta que la retina madure.",
   "Tipo 1 (o enfermedad plus): láser o anti-VEGF en 72 h. Prevención: oxígeno con metas de SatO₂ 90-95 %."],
  AAP + "/AAO, tamizaje de ROP (2018); " + MINSA + ", guía de ROP.",
  op=("¿Semanas?", ["Sí: 4 semanas de vida", "Muy tarde", "Muy tarde", "Muy temprano", "Muy tarde"]),
  d=dict(rotulo="Cuándo examinar la retina", tag="4 SEMANAS",
         ilu_titulo="Retina con ROP (cresta)",
         ilu=CON_CREDITO(P("rop_c.jpg", 246, 184, [], credito="Zhao et al. 2024 · PMC11130119 · CC BY 4.0"), dx=40),
         ilu_pie="Cresta entre retina vascular y avascular.",
         claves=[("Primer examen", ["4 semanas de vida o 31 sem posmenstruales"], True), ("Seguimiento", ["Cada 1-2 semanas"], False),
                 ("Tratamiento", ["Láser o anti-VEGF si es tipo 1"], False)],
         eje_titulo="Semanas de vida", eje=(0, 12), paso=2, marca=4, unidad="sem", eje_nombre="semanas de vida",
         hitos=[(0, 4, "Nacimiento a 4 semanas", "retina aún inmadura", False), (4, 5, "Primer examen", "fondo de ojo", True),
                (5, 12, "Controles", "cada 1-2 semanas", False)]))

# PED-202 · CIA: desdoblamiento fijo del 2.º ruido · DECISIÓN
S("decision", "PED-202", "Niño acianótico y eutrófico con segundo ruido desdoblado y fijo: comunicación interauricular",
  "Cardiopatías congénitas acianóticas",
  ("Comunicación interauricular", ["Cortocircuito de izquierda a derecha en las aurículas: sobrecarga del VD; suele ser asintomática en la infancia.",
                                   "Desdoblamiento fijo del 2.º ruido (no cambia con la respiración) + soplo sistólico pulmonar suave."]),
  ("Niño de 4 años", ["Control de niño sano; peso y talla en p75.", "Acianótico; segundo ruido desdoblado y fijo."]),
  ["Ecocardiograma para confirmar el tipo (ostium secundum el más frecuente).",
   "Cierre con dispositivo o cirugía si es significativa (VD dilatado) entre los 2 y 5 años.",
   "Sin tratar: hipertensión pulmonar y arritmias en el adulto."],
  NELSON + "; AHA/ACC, cardiopatías congénitas del adulto (2018).",
  op=("¿Diagnóstico?", ["No: cianótica", "Sí: desdoblamiento fijo", "No: cianótica", "No: cianótica", "No: HTA en brazos, pulsos femorales débiles"]),
  d=dict(rotulo="Cardiopatías: ¿cianosis y qué se ausculta?", eje_y="Color", ancho_filas=150,
         cols=["Desdoblamiento fijo del 2.º ruido", "Otro hallazgo"],
         rows=[("Acianótico", "Este caso"), ("Cianótico", "")],
         cells=[[("COMUNICACIÓN INTERAURICULAR", ["Ostium secundum"]), ("CIV, ductus, coartación", ["Soplos distintos"])],
                [("—", []), ("Fallot, transposición, atresia", [])]],
         caso=(0, 0), nota="Fijo: no cambia con la respiración."))

# GIN-213 · Discordancia FUR-eco: manda la eco precoz · BALANZA
S("balanza", "GIN-213", "Gestante con 42 semanas por FUR pero 38 por ecografía del primer trimestre: manda la ecografía (38 semanas), continuar el control prenatal",
  "Datación del embarazo",
  ("FUR frente a ecografía temprana", ["Si la eco del primer trimestre difiere > 7 días de la FUR, la edad se corrige por la eco.",
                                       "Con 38 semanas reales no es un embarazo prolongado: no hay que inducir."]),
  ("Gestante", ["42 semanas por FUR.", "38 semanas por ecografía del primer trimestre."]),
  ["Corregir la fecha probable de parto en la historia.",
   "Control prenatal habitual y esperar el trabajo de parto espontáneo.",
   "Inducir desde las 41 semanas (por la eco) si no inicia."],
  ACOG + " n.º 700 (2017); ISUOG.",
  op=("¿Actitud?", ["Sí: tiene 38 semanas", "No: sin indicación", "No: no es prolongado", "No hace falta adicional", "No: no es prolongado"]),
  d=dict(rotulo="¿Qué fecha manda?", gana="der", pregunta="¿En qué confiar?",
         izq=dict(titulo="FUR", peso="FUR", items=["Depende de la memoria", "Ciclos irregulares la alteran", "Dice 42 semanas"]),
         der=dict(titulo="Eco del 1.er trimestre", peso="ECO", items=["Mide el embrión (± 5-7 días)", "La más exacta", "Dice 38 semanas"]),
         veredicto=("Manda la eco: 38 semanas", ["Continuar el control prenatal; no inducir."])))
