"""Tanda de mejora · ejemplos (8 flujogramas antiguos rehechos con imagen real y tríada oficial)."""
from c27 import S, D, P, B, Q, L, DOS, TR, ATLS, HARRISON, WILLIAMS, NELSON, MINSA

CC = " · Wikimedia Commons · "

# GAS-054 · Colangitis aguda · ÁRBOL + colangiorresonancia + Charcot/Reynolds
S("arbol", "GAS-054", "fiebre-ictericia-dolor-coledoco-15-mm-colangitis",
  "Fiebre, ictericia y dolor con colédoco de 15 mm: colangitis aguda",
  "Vía biliar · colangitis aguda", "GASTROENTEROLOGÍA ENAM",
  ("Colangitis aguda", ["Infección de la bilis estancada por un colédoco obstruido (casi siempre un cálculo).",
                        "Fiebre + ictericia + dolor en hipocondrio derecho = tríada de Charcot."]),
  ("Mujer de 32 años con ictericias previas", ["2 días de cólico en hipocondrio derecho, náuseas y vómitos.",
                                               "Fiebre de 39 °C, ictericia; ecografía: colédoco de 15 mm."]),
  ["Charcot (fiebre, ictericia, dolor) con colédoco dilatado = colangitis: antibiótico EV y drenaje biliar.",
   "Si se suman hipotensión y confusión (péntada de Reynolds), la CPRE es urgente.",
   "Colecistitis: fiebre y Murphy (+), pero sin ictericia marcada ni colédoco dilatado."],
  "Tokyo Guidelines 2018 (TG18), colangitis aguda; ASGE, coledocolitiasis (2019); " + HARRISON + ".",
  arbol=Q("¿Fiebre, ictericia y dolor en hipocondrio derecho con colédoco dilatado?", [
      L("Sí (este caso)", "COLANGITIS AGUDA", ["Antibiótico EV e hidratación",
                                               "Drenaje biliar por CPRE y extracción del cálculo"], path=True),
      Q("¿Fiebre y dolor con Murphy (+), sin ictericia y colédoco normal?", [
          L("Sí", "Colecistitis aguda", ["Vesícula de pared gruesa en la ecografía"]),
          L("No", "Buscar otra causa", ["Pancreatitis: lipasa ≥ 3 veces", "Apendicitis: dolor en fosa ilíaca derecha"])],
        edge="No")], path=True),
  banda=B("Colangiorresonancia típica", P("cprm_coledoco.jpg", 280, 335, [
            ("flecha", 0.37, 0.16, 0.30, 0.36, "vesícula\ncon cálculos"),
            ("flecha", 0.665, 0.52, 0.80, 0.36, "colédoco\ndilatado"),
            ("circulo", 0.56, 0.72, 0.075, "cálculos que\nobstruyen", 0.26, 0.66)],
          credito="Hellerhoff" + CC + "CC BY-SA 3.0"),
          ["La bilis se ve blanca: el colédoco está ancho (en el caso, 15 mm; lo normal es < 6 mm).",
           "Al final del colédoco hay cálculos (manchas oscuras dentro de lo blanco): tapan la salida.",
           "La bilis que no sale se infecta: eso es la colangitis; por eso hay que drenarla (CPRE)."],
          pie="Imagen de otro paciente con el mismo hallazgo.", ans=1),
  triada=TR([("Fiebre", "39 °C", True), ("Ictericia", "Al examen", True),
             ("Dolor en hipocondrio derecho", "Cólico de 2 días", True),
             ("Hipotensión", "No se menciona", False), ("Confusión", "No se menciona", False)],
            [("Tríada de Charcot", 0, 2), ("Péntada de Reynolds", 0, 4)],
            "Charcot completa sin hipotensión ni confusión: colangitis sin choque. Si aparecieran, sería Reynolds: CPRE urgente."),
  tabla=("Opciones de la pregunta", [("Apendicitis aguda", False), ("Colangitis aguda", True), ("Pancreatitis aguda", False),
                                     ("Colecistitis aguda", False), ("Neumonía adquirida", False)],
         [("¿Encaja?", ["No: dolor en fosa ilíaca derecha", "Sí: Charcot + colédoco ancho", "No explica el colédoco dilatado",
                        "No: no da ictericia ni colédoco ancho", "No: no hay datos respiratorios"])]))

# CAR-071 · Taponamiento cardiaco · EMBUDO + eco subcostal y ECG reales + tríada de Beck
S("embudo", "CAR-071", "herida-precordial-beck-ecocardiograma-taponamiento",
  "Herida precordial con tríada de Beck: el ecocardiograma confirma el taponamiento",
  "Trauma torácico · taponamiento cardiaco", "CARDIOLOGÍA ENAM",
  ("Taponamiento cardiaco", ["La sangre en el pericardio aprieta el corazón: no se llena y cae el gasto.",
                             "El ecocardiograma (o el FAST pericárdico) ve el líquido y el colapso de cavidades."]),
  ("Varón de 28 años asaltado hace 2 horas", ["Herida precordial pequeña; PA 90/60, FC 110.",
                                              "Ruidos cardiacos apagados, yugulares ingurgitadas, MV presente."]),
  ["Beck (hipotensión, ruidos apagados, yugulares llenas) + herida precordial = taponamiento hasta demostrar lo contrario.",
   "Confirma: ecocardiograma o FAST; trata: descompresión (pericardiocentesis o toracotomía) sin demora.",
   "El ECG puede mostrar bajo voltaje y alternancia eléctrica, pero no confirma el líquido."],
  ATLS + "; ESC, guía de miocarditis y pericarditis (2025).",
  d=dict(rotulo="Qué examen confirma", inicio="Sospecha de taponamiento",
         candidatos=["Ecocardiograma", "Electrocardiograma", "Radiografía de tórax", "Troponina I", "Atropina"],
         pasos=[("No es un examen", ["Atropina"]),
                ("No ven el líquido", ["Electrocardiograma", "Troponina I"]),
                ("Puede ser normal en el sangrado agudo", ["Radiografía de tórax"])],
         final=("Ecocardiograma", ["Líquido alrededor del corazón y colapso de las cavidades derechas"]),
         nota="En trauma, el FAST pericárdico en la sala de emergencia es la forma más rápida."),
  banda=B("Así se ve el taponamiento", DOS(
            P("derrame_subcostal.jpg", 330, 245, [("flecha", 0.44, 0.66, 0.72, 0.90, "líquido pericárdico")],
              credito="Ben Smith" + CC + "CC BY-SA 4.0"),
            P("alternancia_v1.jpg", 430, 109, [("flecha", 0.559, 0.88, 0.40, 0.20, "QRS grande"),
                                               ("flecha", 0.679, 0.69, 0.86, 0.20, "QRS pequeño")],
              credito="ECG: Jer5150" + CC + "CC BY-SA 3.0", fondo="#ffffff"),
            vertical=True),
          ["Ecocardiograma (vista subcostal): la franja negra que rodea al corazón es el líquido del pericardio.",
           "Ese líquido aprieta las cavidades derechas, que colapsan: el corazón no se llena.",
           "ECG (V1): un latido grande y uno pequeño, alternados; es el corazón que oscila dentro del líquido."],
          pie="Imágenes de otros pacientes con taponamiento.", ans=0),
  triada=TR([("Hipotensión", "PA 90/60 mmHg", True), ("Ruidos cardiacos apagados", "«RC apagados»", True),
             ("Yugulares ingurgitadas", "«IY (+)»", True)],
            [("Tríada de Beck", 0, 2)],
            "Beck completa con herida precordial: el paciente necesita confirmar con eco y descomprimir ya."),
  tabla=("Opciones de la pregunta", [("Electrocardiograma", False), ("Radiografía de tórax", False), ("Troponina I", False),
                                     ("Ecocardiograma", True), ("Atropina", False)],
         [("¿Confirma?", ["No: solo signos indirectos", "No: puede ser normal", "No: no muestra la causa",
                          "Sí: ve el líquido y el colapso", "No es un examen"])]))

# NRL-052 · Hematoma epidural · FASES + TC real + tríada de Cushing
S("fases", "NRL-052", "golpe-ladrillo-intervalo-lucido-midriasis-hematoma-epidural",
  "Golpe en la cabeza, intervalo lúcido y midriasis: hematoma epidural, pedir TC",
  "Traumatismo encefalocraneano · hematoma epidural", "NEUROLOGÍA ENAM",
  ("Hematoma epidural", ["Sangrado arterial (meníngea media) entre el hueso y la duramadre tras un golpe.",
                         "Intervalo lúcido y luego deterioro rápido por herniación."]),
  ("Varón de 16 años golpeado con un ladrillo (lado derecho)", ["Lúcido 2 horas; luego estupor.",
                                                                "PA 170/110, FC 40; midriasis derecha, paresia izquierda, edema de papila."]),
  ["TC cerebral sin contraste urgente: lente biconvexa que no cruza suturas.",
   "Midriasis del mismo lado del golpe y paresia del lado opuesto = herniación del uncus.",
   "Mientras se opera: vía aérea, cabecera a 30° y manitol o salino hipertónico."],
  "Brain Trauma Foundation, TEC grave (4.ª ed., 2016); " + ATLS + ".",
  d=dict(rotulo="Cómo evoluciona", ans=2,
         fases=[("Golpe", "Minutos", "PUEDE NO PERDER LA CONCIENCIA", ["Se rompe la arteria meníngea media"]),
                ("Intervalo lúcido", "Horas", "PARECE ESTAR BIEN", ["El hematoma crece en silencio"]),
                ("Herniación", "Súbito", "TC CEREBRAL URGENTE", ["Midriasis derecha, paresia izquierda", "HTA con bradicardia"]),
                ("Cirugía", "Inmediata", "CRANEOTOMÍA", ["Evacuar el hematoma"])],
         curvas=[("Nivel de conciencia", "#0ea5e9", [0.45, 0.9, 0.9, 0.85, 0.3, 0.15, 0.1])]),
  banda=B("TC típica de hematoma epidural", P("epidural_derecho.jpg", 290, 326, [
            ("texto", 0.10, 0.05, "DER"), ("texto", 0.90, 0.05, "IZQ"),
            ("flecha", 0.19, 0.50, 0.58, 0.88, "hematoma en lente"),
            ("flecha", 0.47, 0.30, 0.74, 0.20, "línea media\ndesplazada")],
          credito="Hellerhoff" + CC + "CC BY-SA 4.0"),
          ["Mancha blanca con forma de lente (biconvexa) pegada al hueso: es sangre fresca epidural.",
           "Está del lado derecho del paciente (a la izquierda de la imagen), como el golpe del caso.",
           "Empuja el cerebro y la línea media: por eso aparecen la midriasis y la paresia."],
          pie="Imagen de otro paciente; en la TC, la derecha del paciente se ve a la izquierda.", ans=0),
  triada=TR([("Hipertensión arterial", "PA 170/110 mmHg", True), ("Bradicardia", "FC 40 por minuto", True),
             ("Respiración irregular", "No se menciona", False)],
            [("Tríada de Cushing", 0, 2)],
            "HTA con bradicardia = presión intracraneal muy alta: herniación inminente; la TC y la cirugía no esperan."),
  tabla=("Opciones de la pregunta", [("TEM cerebral", True), ("Doppler transcraneal", False), ("Potenciales evocados", False),
                                     ("EEG", False), ("Colonoscopia", False)],
         [("¿Sirve aquí?", ["Sí: muestra el hematoma", "No: mide flujo, no sangrado", "No: no ve lesiones",
                            "No: es para crisis", "No tiene relación"])]))

# PED-211 · Tetralogía de Fallot · TARJETAS + esquema real rotulado + tétrada
S("tarjetas", "PED-211", "rn-cianosis-al-llanto-corazon-en-bota-fallot",
  "Recién nacido con cianosis al llanto y corazón en bota: tetralogía de Fallot",
  "Cardiopatías congénitas · cianóticas", "PEDIATRÍA ENAM",
  ("Tetralogía de Fallot", ["La cardiopatía congénita cianótica más frecuente después del primer mes.",
                            "Cuatro defectos; el que manda es la estenosis pulmonar."]),
  ("Recién nacido de 3 kg, madre de 37 años", ["Reingresa por cianosis al llanto.",
                                               "Rx de tórax: corazón en forma de bota."]),
  ["Cianosis que empeora con el llanto + corazón en bota = tetralogía de Fallot.",
   "Crisis hipoxémica: posición rodillas-pecho, oxígeno, morfina y líquidos; propranolol para prevenirlas.",
   "CIA y CIV no dan cianosis (cortocircuito de izquierda a derecha) y aumentan el flujo pulmonar."],
  NELSON + ".",
  d=dict(rotulo="¿Qué cardiopatía es?", ans=0,
         cards=[dict(titulo="Tetralogía de Fallot", datos=[("Cianosis", "Sí, con el llanto", True), ("Rx", "Corazón en bota", True),
                                                           ("Flujo pulmonar", "Disminuido", False)], pie="Es la de este caso."),
                dict(titulo="Estenosis pulmonar", datos=[("Cianosis", "Solo si es crítica", False), ("Rx", "Arteria pulmonar dilatada", False),
                                                         ("Flujo pulmonar", "Normal o bajo", False)], pie="Soplo eyectivo, sin bota."),
                dict(titulo="CIV", datos=[("Cianosis", "No", False), ("Rx", "Cardiomegalia", False),
                                          ("Flujo pulmonar", "Aumentado", False)], pie="Soplo holosistólico."),
                dict(titulo="CIA", datos=[("Cianosis", "No", False), ("Rx", "Crecimiento derecho", False),
                                          ("Flujo pulmonar", "Aumentado", False)], pie="Desdoblamiento fijo del 2.º ruido.")]),
  banda=B("Los cuatro defectos", P("fallot_esquema.jpg", 380, 443, credito="LadyofHats y Pitana" + CC + "CC BY-SA 4.0",
                                   fondo="#ffffff"),
          ["Esquema del corazón con Fallot: los cuatro defectos vienen rotulados en español.",
           "La salida pulmonar es estrecha: la sangre azul pasa por la CIV a la aorta y el niño se pone cianótico.",
           "Al llorar sube la resistencia y pasa más sangre azul: por eso la cianosis aparece con el llanto."],
          ans=1),
  triada=TR([("Estenosis pulmonar", "Poco flujo al pulmón: cianosis; arco pulmonar hundido en la Rx", None),
             ("Comunicación interventricular", "Deja pasar sangre azul del VD a la aorta", None),
             ("Aorta cabalgante (dextroposición)", "Recibe sangre de ambos ventrículos", None),
             ("Hipertrofia del VD", "Levanta la punta: corazón en bota", None)],
            [("Tétrada de Fallot", 0, 3)],
            "El corazón en bota sale de dos defectos: la punta levantada (hipertrofia del VD) y el arco pulmonar hundido (estenosis)."),
  tabla=("Opciones de la pregunta", [("CIA", False), ("CIV", False), ("Estenosis pulmonar", False),
                                     ("Tetralogía de Fallot", True), ("Infección urinaria", False)],
         [("¿Encaja?", ["No: sin cianosis", "No: sin cianosis", "No: sin corazón en bota", "Sí", "No: no explica nada"])]))

# NEU-018 · Tumor de Pancoast · EMBUDO + Rx real + foto de Horner + síndrome con la tríada de Horner
S("embudo", "NEU-018", "dolor-hombro-fumador-pancoast",
  "Fumador con dolor de hombro que baja por el borde cubital: tumor de Pancoast",
  "Cáncer de pulmón · tumor del vértice (Pancoast)", "NEUMOLOGÍA ENAM",
  ("Tumor de Pancoast", ["Cáncer del vértice del pulmón (surco superior) que invade el plexo braquial bajo (C8-T1).",
                         "Puede tomar la cadena simpática del cuello: síndrome de Horner."]),
  ("Varón de 60 años, fumador pesado", ["Dolor en el hombro que baja por la cara cubital del brazo.",
                                        "Parestesias en todo el brazo."]),
  ["Fumador + dolor de hombro con irradiación cubital = Pancoast hasta demostrar lo contrario: Rx y TC de tórax.",
   "Con ptosis, miosis y anhidrosis del mismo lado se suma el síndrome de Horner.",
   "Una bursitis o una artrosis no dan dolor por el trayecto del nervio cubital ni parestesias."],
  HARRISON + "; NCCN, cáncer de pulmón de células no pequeñas (2025).",
  d=dict(rotulo="Del dolor de hombro al diagnóstico", inicio="Fumador con dolor de hombro y brazo",
         candidatos=["Tumor de Pancoast", "Polineuritis por déficit de B", "Bursitis crónica", "Osteoartritis de hombro"],
         pasos=[("¿Duele al mover el hombro, sin parestesias?", ["Bursitis crónica", "Osteoartritis de hombro"]),
                ("¿Parestesias en ambos pies y manos (en guante y calcetín)?", ["Polineuritis por déficit de B"])],
         final=("Tumor de Pancoast", ["Dolor y parestesias en el territorio C8-T1 de un solo brazo en un fumador"]),
         nota="Pedir Rx y TC de tórax; la biopsia confirma el tipo de cáncer."),
  banda=B("Cómo se ve", DOS(
            P("pancoast_rx.jpg", 360, 315, [("circulo", 0.31, 0.21, 0.085, "vértice derecho\nopaco", 0.27, 0.50),
                                            ("flecha", 0.68, 0.24, 0.80, 0.50, "vértice izquierdo\nnormal")],
              credito="Jmarchn" + CC + "CC BY-SA 3.0"),
            P("horner_ojos.jpg", 360, 94, [("flecha", 0.76, 0.37, 0.92, 0.17, "ptosis"),
                                           ("flecha", 0.724, 0.515, 0.50, 0.80, "miosis"),
                                           ("texto", 0.16, 0.86, "ojo sano")],
              credito="Horner: Waster" + CC + "CC BY 2.5"),
            vertical=True),
          ["Rx: el vértice derecho está blanco (el tumor); el izquierdo se ve negro, con aire.",
           "Desde ahí el tumor alcanza las raíces C8-T1: dolor y parestesias por el borde cubital.",
           "Si toma la cadena simpática aparece Horner: párpado caído y pupila pequeña del mismo lado."],
          pie="Imágenes de otros pacientes.", ans=0),
  triada=TR([("Dolor de hombro y brazo (C8-T1)", "Hombro → borde cubital", True),
             ("Parestesias / debilidad de la mano", "Parestesias en el brazo", True),
             ("Ptosis", "No se menciona", False), ("Miosis", "No se menciona", False),
             ("Anhidrosis facial", "No se menciona", False)],
            [("Tríada de Horner", 2, 4), ("Síndrome de Pancoast", 0, 4)],
            "El caso ya tiene el dolor y las parestesias del plexo: basta para sospecharlo. Horner aparece cuando invade el simpático."),
  tabla=("Opciones de la pregunta", [("Carcinoma del vértice pulmonar", True), ("Polineuritis por déficit de B", False),
                                     ("Bursitis crónica", False), ("Osteoartritis de hombro", False), ("Omeprazol", False)],
         [("¿Encaja?", ["Sí: fumador, dolor C8-T1", "No: es simétrica y distal", "No: no irradia ni da parestesias",
                        "No: dolor articular", "No es un diagnóstico"])]))

# GIN-121 · Embarazo ectópico roto · ÁRBOL + laparoscopía real + tríada clásica
S("arbol", "GIN-121", "amenorrea-6-semanas-choque-culdocentesis-ectopico-roto",
  "Amenorrea de 6 semanas, choque y culdocentesis positiva: embarazo ectópico roto",
  "Hemorragia del primer trimestre · embarazo ectópico", "GINECO-OBSTETRICIA ENAM",
  ("Embarazo ectópico roto", ["El embarazo crece fuera del útero (casi siempre en la trompa) y la rompe.",
                              "Sangra hacia el abdomen: dolor, choque y sangre en el fondo de saco de Douglas."]),
  ("Mujer de 24 años que se desmayó", ["FUR hace 6 semanas; pálida; PA 80/50, FC 110.",
                                       "Abdomen doloroso, rebote dudoso; culdocentesis (+)."]),
  ["Mujer en edad fértil con dolor abdominal y choque: descartar ectópico roto (β-hCG y ecografía si hay tiempo).",
   "Inestable: reanimar y operar (laparotomía o laparoscopía) sin esperar más estudios.",
   "Metotrexato solo en el ectópico no roto, estable y con β-hCG baja."],
  "ACOG Practice Bulletin n.º 193, embarazo tubario (2018); " + WILLIAMS + "; " + MINSA + ".",
  arbol=Q("Mujer con amenorrea, dolor abdominal y choque: ¿hay sangre libre en el abdomen?", [
      L("Sí: culdocentesis (+) (este caso)", "EMBARAZO ECTÓPICO ROTO", ["Reanimar con cristaloides y sangre",
                                                                        "Cirugía urgente (salpingectomía)"], path=True),
      Q("¿Sangrado vaginal con restos y cuello abierto?", [
          L("Sí", "Aborto incompleto o en curso", ["El sangrado sale por la vagina"]),
          L("No", "Ecografía y β-hCG seriada", ["Buscar un ectópico aún no roto"])], edge="No")], path=True),
  banda=B("El ectópico visto por laparoscopía", P("ectopico_tubario.jpg", 330, 245, [
            ("flecha", 0.53, 0.30, 0.22, 0.12, "trompa dilatada\npor el embarazo"),
            ("flecha", 0.60, 0.64, 0.84, 0.88, "fimbrias")],
          credito="Hic et nunc" + CC + "CC BY-SA 3.0"),
          ["La trompa está hinchada y violácea: dentro crece el embarazo.",
           "La pared de la trompa es fina: hacia la 6.ª-8.ª semana se rompe y sangra al abdomen.",
           "Esa sangre baja al fondo de saco de Douglas: por eso la culdocentesis sale positiva."],
          pie="Embarazo tubario derecho aún no roto, de otra paciente.", ans=1),
  triada=TR([("Amenorrea", "FUR hace 6 semanas", True), ("Dolor abdominal", "Abdomen doloroso", True),
             ("Sangrado vaginal", "No se menciona", False)],
            [("Tríada clásica del ectópico", 0, 2)],
            "Falta el sangrado vaginal, pero hay choque y culdocentesis (+): el sangrado es interno."),
  tabla=("Opciones de la pregunta", [("Embarazo ectópico roto", True), ("Aborto incompleto", False), ("Aborto en curso", False),
                                     ("Cuerpo lúteo hemorrágico", False), ("Ninguna", False)],
         [("¿Encaja?", ["Sí", "No: sangrado vaginal, no interno", "No: sangrado vaginal y cuello abierto",
                        "Raro con amenorrea y choque así", "No"])]))

# NRL-013 · Encefalopatía de Wernicke · ÁRBOL + RM real + tríada de Wernicke
S("arbol", "NRL-013", "coma-alcoholico-tiamina-ev",
  "Alcohólico crónico en sopor: tiamina endovenosa primero",
  "Encefalopatía de Wernicke · tiamina", "NEUROLOGÍA ENAM",
  ("Encefalopatía de Wernicke", ["Falta de tiamina (vitamina B1) en alcohólicos o desnutridos.",
                                 "Es una urgencia: sin tiamina avanza al coma o a la psicosis de Korsakoff."]),
  ("Varón de 60 años, alcoholismo crónico", ["3 meses de cambios de conducta (de letargo a excitación).",
                                             "Hace 24 h cae en sopor; hace 2 h no responde."]),
  ["Alcohólico con alteración de conciencia: tiamina EV antes (o junto) de la glucosa.",
   "La glucosa sola consume la poca tiamina que queda y empeora el daño.",
   "Naloxona es para opioides; manitol para hipertensión endocraneal: no tratan la causa."],
  HARRISON + "; EFNS, encefalopatía de Wernicke (2010).",
  arbol=Q("¿Alcohólico o desnutrido con confusión, sopor o coma?", [
      L("Sí (este caso)", "TIAMINA EV YA", ["Antes o junto con la glucosa",
                                            "Dosis altas varios días"], path=True),
      L("No", "Buscar otras causas", ["Glucosa, sodio, tóxicos, TC cerebral"])], path=True),
  banda=B("Resonancia típica de Wernicke", P("wernicke_flair.jpg", 280, 324, [
            ("circulo", 0.51, 0.48, 0.10, "tálamos\nmediales blancos", 0.50, 0.90)],
          credito="Jto410" + CC + "CC BY-SA 3.0"),
          ["RM (FLAIR): a ambos lados del tercer ventrículo los tálamos se ven blancos (edema).",
           "Esas zonas consumen mucha glucosa y se dañan primero cuando falta tiamina.",
           "No hace falta la RM para tratar: la tiamina se da con la sola sospecha."],
          pie="Imagen de otro paciente con el mismo hallazgo.", ans=0),
  triada=TR([("Confusión o alteración de conciencia", "Conducta cambiante, sopor", True),
             ("Oftalmoplejía o nistagmo", "No se menciona", False), ("Ataxia", "No se menciona", False)],
            [("Tríada de Wernicke", 0, 2)],
            "La tríada completa es poco frecuente: con la sola confusión en un alcohólico ya se da tiamina."),
  tabla=("Opciones de la pregunta", [("Naloxona", False), ("Tiamina EV", True), ("ClNa 0,9 %", False),
                                     ("Manitol", False), ("Repetir examen en 24 h", False)],
         [("¿Prioritaria?", ["No: es para opioides", "Sí", "No trata la causa", "No: no hay HTE demostrada", "No: es una urgencia"])]))

# HEM-009 · Púrpura trombocitopénica trombótica · ÁRBOL + frotis real + péntada
S("arbol", "HEM-009", "microangiopatia-trombotica-ptt-plasma",
  "Puérpera con anemia, esquistocitos, fiebre, déficit neurológico y oliguria: PTT, dar plasma",
  "Microangiopatía trombótica · PTT", "HEMATOLOGÍA ENAM",
  ("Púrpura trombocitopénica trombótica (PTT)", ["Falta de ADAMTS13: se forman microtrombos de plaquetas en vasos pequeños.",
                                                 "Los glóbulos rojos se rompen al pasar (esquistocitos) y se dañan cerebro y riñón."]),
  ("Puérpera de 32 años, 24 horas posparto", ["Cefalea intensa, desorientación y hemiparesia derecha; T 38,9 °C.",
                                              "Diuresis 400 ml en 24 h; Hb 6 g/dl; esquistocitos en el frotis."]),
  ["Anemia hemolítica con esquistocitos + plaquetas bajas = microangiopatía: sospechar PTT y no esperar la péntada completa.",
   "Tratamiento de elección: plasmaféresis urgente; si no hay, plasma fresco congelado (aporta ADAMTS13).",
   "No transfundir plaquetas salvo sangrado grave: alimentan los trombos."],
  "ISTH, guía de PTT (2020); " + HARRISON + ".",
  arbol=Q("¿Anemia hemolítica con esquistocitos y daño de órganos?", [
      L("Sí (este caso)", "PTT: REPONER ADAMTS13", ["Plasmaféresis urgente",
                                                     "Si no hay: plasma fresco congelado"], path=True),
      L("No", "Otra anemia", ["Sin esquistocitos no es microangiopatía"])], path=True),
  banda=B("Frotis típico de PTT", P("esquistocitos.jpg", 330, 227, credito="Hospital Universitario de Berna" + CC + "CC BY-SA 4.0",
                                    fondo="#ffffff"),
          ["Los círculos azules marcan esquistocitos: glóbulos rojos rotos, con forma de casco o fragmento.",
           "Se rompen al chocar con los microtrombos de plaquetas en los vasos pequeños.",
           "Varios por campo con anemia y plaquetas bajas: es una microangiopatía trombótica."],
          pie="Frotis de otro paciente; los círculos azules son del autor.", ans=0),
  triada=TR([("Anemia hemolítica microangiopática", "Hb 6 con esquistocitos", True),
             ("Plaquetas bajas", "No se informa el recuento", False),
             ("Fiebre", "38,9 °C", True), ("Alteración neurológica", "Desorientación, hemiparesia", True),
             ("Falla renal", "Oliguria: 400 ml en 24 h", True)],
            [("Péntada clásica de la PTT", 0, 4)],
            "La péntada completa es rara; hoy basta la anemia con esquistocitos y las plaquetas bajas para tratar."),
  tabla=("Opciones de la pregunta", [("Eritrocitos lavados", False), ("Sangre total", False), ("Paquete globular", False),
                                     ("Plasma fresco congelado", True), ("Todas las anteriores", False)],
         [("¿Trata la causa?", ["No", "No", "No: solo sube la Hb", "Sí: aporta ADAMTS13", "No"])]))
