"""Entrega 3 · tanda t17 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO, GINA
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
GORDIS = "Gordis, Epidemiología 6.ª ed."


def GRAM(tipo):
    return D(lambda s, x, y: I.gram(s, x, y, tipo, sc=0.8), 176, 128)


# GIN-202 · RPM a término sin trabajo de parto: inducir · DECISIÓN
S("decision", "GIN-202", "Primigesta de 39 semanas con 12 horas de rotura de membranas, sin trabajo de parto, feto bien y cuello favorable: inducir el trabajo de parto",
  "Rotura prematura de membranas a término",
  ("RPM a término", ["Rotura de membranas desde las 37 semanas antes del trabajo de parto.",
                     "Inducir (oxitocina, o misoprostol si el cuello es desfavorable) reduce la corioamnionitis y la infección neonatal frente a esperar."]),
  ("Primigesta de 39 semanas", ["Pérdida de líquido claro hace 12 h; contracciones cada 10 min.", "Cefálico, LCF 144; 0 cm, 80 %, cuello anterior y blando."]),
  ["Inducción con oxitocina; profilaxis para estreptococo B si es positivo, desconocido o la RPM es ≥ 18 h.",
   "Evitar tactos innecesarios; vigilar fiebre, taquicardia y líquido fétido.",
   "Cesárea solo por indicación obstétrica."],
  ACOG + " n.º 217 (2020); NICE NG207 (2021); " + MINSA + ".",
  op=("¿Manejo?", ["Sí: reduce infección", "No: sin indicación", "No: ya está rota la bolsa", "No: retrasa", "No: está a término"]),
  d=dict(rotulo="RPM: ¿qué hacer según las semanas?", eje_y="Edad gestacional", ancho_filas=180,
         cols=["Sin infección", "Con corioamnionitis"],
         rows=[("≥ 37 semanas", "Este caso"), ("34-36 semanas", ""), ("24-33 semanas", "")],
         cells=[[("INDUCIR", ["Oxitocina (o misoprostol)"]), ("Antibiótico + terminar", [])],
                [("Inducir o expectante corto", []), ("Antibiótico + terminar", [])],
                [("Expectante: corticoide + antibiótico", []), ("Antibiótico + terminar", [])]],
         caso=(0, 0), nota="Cuello blando, anterior, 80 %: favorable para oxitocina."))

# GAS-066 · Anemia con sangre oculta en heces: colonoscopía · EMBUDO + foto
S("embudo", "GAS-066", "Varón de 68 años con anemia leve y sangre oculta en heces positiva: colonoscopía completa (descartar cáncer colorrectal)",
  "Cáncer colorrectal · estudio de la anemia",
  ("Sangre oculta en heces positiva", ["En mayores de 45-50 años, una prueba de sangre oculta positiva o una anemia ferropénica obliga a mirar todo el colon.",
                                       "La colonoscopía ve, toma biopsias y extirpa pólipos; la sigmoidoscopía no llega al colon derecho (donde los cánceres sangran sin síntomas)."]),
  ("Varón de 68 años, asintomático", ["Hb 11 g/dL en un control.", "Thevenon seriado positivo; leve palidez."]),
  ["Colonoscopía completa con biopsias.",
   "Si es normal y hay ferropenia: endoscopía alta (y en algunos casos cápsula).",
   "Tamizaje: test inmunoquímico anual o colonoscopía cada 10 años desde los 45 años."],
  "USMSTF (2021; act.); ACG, cáncer colorrectal (2021); NCCN (2026).",
  op=("¿Siguiente paso?", ["No: no ve el colon derecho", "Sí: ve todo el colon", "No: no ve la mucosa", "No: para sangrado activo", "Después, si la colonoscopía es normal"]),
  d=dict(rotulo="Sangre oculta + anemia: ¿dónde buscar?", inicio="Sangre oculta (+) y anemia en > 50 años",
         candidatos=["Úlcera o esofagitis", "Hemorroides", "Angiodisplasia", "Pólipo", "Cáncer de colon"],
         pasos=[("¿Hay síntomas altos (dispepsia, AINE) o la colonoscopía sale normal?", ["Úlcera o esofagitis"]),
                ("¿Explica la anemia algo trivial?", ["Hemorroides", "Angiodisplasia"])],
         final=("CÁNCER O PÓLIPO DE COLON", ["Colonoscopía completa", "Biopsia o polipectomía"]),
         nota="Las hemorroides no explican una anemia: nunca asumirlas."),
  banda=B("Lo que puede verse", P("ca_colon.jpg", 260, 257, [], credito="G. Narasimha Murthy" + CC + "CC0"),
          [("Masa que estrecha la luz", "Cáncer de colon."), ("Colon derecho", "Sangra en silencio: anemia ferropénica."),
           ("Biopsia", "Confirma; luego TC y CEA.")],
          pie="Cáncer de colon"))

# GIN-203 · Corioamnionitis en el primer nivel · CRITERIOS
S("criterios", "GIN-203", "Gestante de 37 semanas con 2 días de rotura de membranas, fiebre de 39 °C, taquicardia fetal, útero doloroso y líquido purulento: corioamnionitis, antibiótico y traslado al hospital",
  "Infección intraamniótica (corioamnionitis)",
  ("Corioamnionitis", ["Infección del líquido y las membranas, sobre todo tras RPM prolongada.",
                       "Fiebre materna ≥ 38 °C + uno más: taquicardia fetal > 160, leucocitosis, líquido purulento o fétido, útero doloroso."]),
  ("Primigesta de 37 semanas, centro materno infantil", ["Pérdida de líquido hace 2 días.", "T 39 °C, FC 104; LCF 190; útero doloroso; líquido purulento y fétido; 0 cm."]),
  ["Ampicilina 2 g EV c/6 h + gentamicina 5 mg/kg/día EV; antipirético.",
   "Referir al hospital para terminar la gestación (la vía la decide la obstetricia; la infección no indica cesárea por sí sola).",
   "Neonatología lista: riesgo de sepsis neonatal."],
  ACOG + " n.º 712 (2017); " + MINSA + ".",
  op=("¿Manejo?", ["Falta el antibiótico y no es el nivel adecuado", "Sí: antibiótico + referencia", "No: hay infección", "No: contraindicado con infección", "No: es grave"]),
  d=dict(rotulo="Criterios de corioamnionitis", lista_titulo="Lo que tiene ella",
         items=[("Fiebre materna ≥ 38 °C", True, "39 °C"), ("Taquicardia fetal > 160", True, "LCF 190"),
                ("Líquido purulento o fétido", True, "Purulento, mal olor"), ("Útero doloroso", True, "Dolor a la palpación"),
                ("Leucocitosis materna", None, "Por pedir")],
         umbral="Fiebre + 1 criterio = corioamnionitis",
         veredicto="Corioamnionitis: ampicilina + gentamicina y traslado para terminar la gestación.",
         img=D(lambda s, x, y: I.gestante(s, x + 10, y, sc=0.55), 200, 270), img_titulo="Gestante febril", img_pie="RPM de 2 días.", conteo="4 de 5"))

# GIN-204 · Edad gestacional sin FUR: eco TV · TARJETAS
S("tarjetas", "GIN-204", "Gestante que no recuerda su FUR: el método más exacto para saber la edad gestacional es la ecografía transvaginal temprana",
  "Datación del embarazo",
  ("Cómo saber la edad gestacional", ["La ecografía temprana mide el embrión (longitud cráneo-caudal) con un error de ± 5-7 días.",
                                      "La beta-hCG confirma el embarazo pero no lo fecha; la altura uterina y el examen pélvico son aproximados."]),
  ("Mujer de 24 años", ["Prueba de embarazo positiva; no recuerda la FUR.", "Útero de 8 cm, globuloso; sin sangrado."]),
  ["Eco transvaginal: saco gestacional desde ~5 semanas, embrión con latido desde ~6.",
   "La eco del primer trimestre es la que define la fecha probable de parto.",
   "Además confirma que el embarazo es intrauterino."],
  ACOG + " n.º 700 (2017); ISUOG (2013).",
  op=("¿Método más exacto?", ["Aproximado", "No fecha el embarazo", "Sí: mide el embrión", "Solo confirma", "Aproximado"]),
  d=dict(rotulo="¿Qué método fecha mejor?", ans=0,
         cards=[dict(titulo="Eco transvaginal", datos=[("Mide", "Longitud cráneo-caudal", True), ("Error", "± 5-7 días", True), ("Además", "Embarazo intrauterino", True)], pie="Esta pregunta."),
                dict(titulo="Beta-hCG", datos=[("Mide", "Hormona", False), ("Sirve", "Confirmar, seguir ectópico", False), ("Fecha", "No", False)], pie="No fecha."),
                dict(titulo="Altura uterina", datos=[("Mide", "Tamaño del útero", False), ("Desde", "20 semanas", False), ("Error", "± 2-3 sem", False)], pie="Aproximada."),
                dict(titulo="Examen pélvico", datos=[("Mide", "Tamaño al tacto", False), ("Error", "Grande", False), ("Uso", "Orientativo", False)], pie="Subjetivo.")]))

# PED-194 · Obesidad en < 5 años: P/T > +3 DE · REGLA
S("regla", "PED-194", "En menores de 5 años, la obesidad se define por un peso para la talla por encima de +3 desviaciones estándar (OMS)",
  "Estado nutricional del niño",
  ("Peso para la talla (OMS, < 5 años)", ["> +3 DE: obesidad. > +2 DE: sobrepeso. > +1 DE: riesgo de sobrepeso.",
                                          "< −2 DE: desnutrición aguda (emaciación); < −3 DE: grave. En ≥ 5 años se usa el IMC para la edad."]),
  ("Pregunta de teoría", ["¿Desde cuántas desviaciones estándar de P/T se define obesidad en < 5 años?"]),
  ["Control CRED: graficar peso, talla y P/T en cada visita.",
   "Obesidad: alimentación saludable para toda la familia, actividad física, menos pantallas y bebidas azucaradas.",
   "Buscar causas endocrinas si hay talla baja asociada."],
  OMS + ", patrones de crecimiento (2006); " + MINSA + ", NTS CRED (2017).",
  op=("¿DE?", ["Es sobrepeso", "No existe ese corte", "Es riesgo de sobrepeso", "Sí: obesidad", "No existe ese corte"]),
  d=dict(rotulo="Peso para la talla (desviaciones estándar)",
         reglas=[dict(nombre="P/T en DE (puntaje Z)", que="Patrones OMS para menores de 5 años.",
                      min=-4, max=4, fmt="{}", ticks=[-3, -2, 1, 2, 3],
                      bandas=[(-4, -3, "Grave", 3), (-3, -2, "Desnutrición", 2), (-2, 1, "Normal", 0), (1, 2, "Riesgo", 1),
                              (2, 3, "Sobrepeso", 2), (3, 4, "Obesidad", 3)],
                      caso=3.3, caso_txt="OBESIDAD: > +3")],
         claves_titulo="Recuerda",
         claves=[("> +3 DE", ["Obesidad"], True), ("> +2 DE", ["Sobrepeso"], False), ("≥ 5 años", ["IMC para la edad"], False)]))

# INF-097 · Brucelosis: doxiciclina + rifampicina · TRANSMISIÓN
S("transmision", "INF-097", "Trabajador ganadero con 8 meses de poliartralgias, fiebre ondulante y sudoración, con Rosa de Bengala positivo: brucelosis, doxiciclina + rifampicina por 6 semanas",
  "Zoonosis · brucelosis",
  ("Brucelosis", ["Zoonosis por Brucella (cabras, vacas): leche y quesos frescos sin pasteurizar o contacto con animales.",
                  "Fiebre ondulante, sudoración profusa (olor a paja), artralgias y sacroileítis, hepatoesplenomegalia; Rosa de Bengala es el tamizaje."]),
  ("Varón de 40 años, zona ganadera", ["8 meses de poliartralgias; 4 meses de fiebre ondulante y sudoración.", "ANA y FR negativos; VSG 60; Rosa de Bengala positivo."]),
  ["Doxiciclina 100 mg c/12 h + rifampicina 600-900 mg/día por 6 semanas (o doxiciclina + estreptomicina/gentamicina).",
   "Confirmar con aglutinación (SAT) o hemocultivo; espondilitis: 3 meses o más.",
   "Notificar; consumir lácteos pasteurizados; control del ganado."],
  OMS + ", brucelosis; " + MINSA + ", NTS de brucelosis; Consenso de Ioannina (2007).",
  op=("¿Tratamiento?", ["No es el esquema de elección", "Para niños o gestantes", "Sí: esquema de elección", "No es de elección", "No sirve"],
      {0: "Ciprofloxacino + doxiciclina", 1: "Cotrimoxazol + rifampicina", 2: "Rifampicina + doxiciclina", 3: "Ciprofloxacino + rifampicina"}),
  d=dict(rotulo="Cómo llega la brucelosis y dónde se corta", tag="TRATAR",
         eslabones=[("Brucella", "Bacteria", "Doxiciclina + rifampicina 6 sem", True), ("Cabras y vacas", "Reservorio", "Vacunar y sacrificar ganado", False),
                    ("Leche y queso fresco", "Vehículo", "Pasteurizar", False), ("Contacto con fetos y placentas", "Vía", "Guantes", False),
                    ("Ganadero", "Huésped", "Educación", False)],
         veredicto=("Ganadero + fiebre ondulante + Rosa de Bengala = brucelosis", "Doxiciclina + rifampicina por 6 semanas.")))

# PSI-039 · Intoxicación por cocaína: benzodiacepinas · CASCADA
S("cascada", "PSI-039", "Adolescente con agitación, taquicardia, palpitaciones y sensación de muerte tras consumir cocaína: intoxicación simpaticomimética, diazepam",
  "Toxicología · cocaína",
  ("Intoxicación por cocaína", ["Bloquea la recaptación de noradrenalina, dopamina y serotonina: exceso simpático (taquicardia, HTA, midriasis, hipertermia, agitación).",
                                "Las benzodiacepinas calman el cerebro y bajan la frecuencia cardíaca y la PA: primera línea."]),
  ("Adolescente de 17 años", ["Primer consumo de cocaína.", "Agitación, taquicardia, palpitaciones, sensación de muerte."]),
  ["Diazepam o lorazepam EV en dosis repetidas hasta calmarlo.",
   "Enfriar si hay hipertermia; ECG y troponina si hay dolor torácico (vasoespasmo coronario).",
   "Evitar betabloqueadores (alfa sin oposición: más HTA y vasoespasmo); haloperidol empeora la hipertermia."],
  "Goldfrank, toxicología 11.ª ed.; AHA, cocaína y SCA.",
  op=("¿Tratamiento inmediato?", ["No: digitálico", "No: es para arritmias", "No: riesgo de alfa sin oposición", "Sí: calma y baja el tono simpático", "No: empeora la hipertermia"]),
  d=dict(rotulo="De la cocaína a los síntomas", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Bloquea la recaptación", "Noradrenalina, dopamina, serotonina", [("Agitación, sensación de muerte", "Este caso", True)]),
                ("Exceso de noradrenalina", "Estímulo alfa y beta", [("Taquicardia, palpitaciones", "Este caso", True), ("HTA, vasoespasmo coronario", "Dolor torácico", False)]),
                ("Más actividad muscular", "Calor", [("Hipertermia, rabdomiólisis", "Vigilar", False)])],
         veredicto=("Benzodiacepina (diazepam)", "Nada de betabloqueadores en la intoxicación aguda.")))

# INF-098 · Neumonía nosocomial con catéter: S. aureus · CUADRÍCULA
S("cuadricula", "INF-098", "Paciente en diálisis por catéter central, en el 6.º día posoperatorio, con fiebre, infiltrado alveolar y leucocitosis: neumonía nosocomial, germen más probable S. aureus",
  "Neumonía intrahospitalaria · etiología",
  ("Neumonía nosocomial", ["Aparece ≥ 48 h tras el ingreso; gérmenes hospitalarios: S. aureus (incluido SARM), Pseudomonas, enterobacterias.",
                           "Catéter de diálisis: bacteriemia por S. aureus que puede sembrar el pulmón (émbolos sépticos)."]),
  ("Varón de 48 años en hemodiálisis por catéter", ["6.º día después de una colecistectomía.", "Fiebre, infiltrado en base derecha, leucocitosis con desviación, PCR 96; antígeno COVID negativo."]),
  ["Hemocultivos (del catéter y periféricos), cultivo de secreción respiratoria.",
   "Empírico: vancomicina o linezolid (SARM) + antipseudomónico (piperacilina-tazobactam o cefepime).",
   "Si el catéter es el foco: retirarlo."],
  IDSA + "/ATS, neumonía intrahospitalaria (2016).",
  op=("¿Agente?", ["Sí: hospitalario + catéter", "No: atípico, comunitario", "Comunitario", "Comunitario", "Atípico, menos probable"]),
  d=dict(rotulo="Neumonía: ¿comunitaria u hospitalaria?", alto_img=128,
         celdas=[("S. aureus (hospitalaria)", ["Catéter, diálisis, posoperatorio", "Cocos G+ en racimos"], GRAM("cocos_racimo"), True),
                 ("Neumococo (comunitaria)", ["El más frecuente fuera del hospital", "Diplococos G+"], GRAM("cocos_cadena"), False),
                 ("Pseudomonas (hospitalaria)", ["Ventilador, estructural", "Bacilo G−"], GRAM("bacilos_neg"), False),
                 ("Mycoplasma / Legionella", ["Atípicos, comunitarios", "No se ven en el Gram"], D(lambda s, x, y: I.torax_rx(s, x, y, "intersticial", sc=0.45), 135, 126), False)],
         credito="Esquemas MedQuizPro (dibujo propio)",
         veredicto=("Catéter + hospitalizado = S. aureus", "Vancomicina empírica y retirar el catéter si es el foco.")))

# HEM-039 · Hemofilia A · DECISIÓN
S("decision", "HEM-039", "Adolescente varón con hemartrosis tras un trauma, TTPa prolongado, plaquetas y agregación normales: hemofilia A (la más frecuente)",
  "Coagulopatías hereditarias",
  ("Hemofilias", ["Ligadas al X (varones): A = déficit de factor VIII (85 %), B = factor IX.",
                  "Sangrados profundos (hemartrosis, hematomas musculares); TTPa prolongado con TP y plaquetas normales."]),
  ("Varón de 16 años", ["Trauma de rodilla con dolor intenso; gran aumento de volumen.", "Hb 11, TTPa 58 s, plaquetas 230 000, agregación normal; eco: gran hematoma."]),
  ["Dosar factor VIII y IX para confirmar y graduar (grave < 1 %).",
   "Reponer factor VIII (o emicizumab en profilaxis); hielo, reposo; no AINE ni inyecciones IM.",
   "Von Willebrand: sangrado de mucosas y agregación con ristocetina alterada."],
  "WFH, guías de hemofilia (2020); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["Igual de laboratorio, pero menos frecuente", "No: trombosis", "No: mucosas, agregación alterada", "Sí: la más frecuente", "No: plaquetas normales"]),
  d=dict(rotulo="Pruebas de coagulación: ¿dónde está la falla?", eje_y="TTPa", ancho_filas=150,
         cols=["TP normal", "TP prolongado"],
         rows=[("Prolongado", "Vía intrínseca"), ("Normal", "")],
         cells=[[("HEMOFILIA A o B (o von Willebrand)", ["Varón + hemartrosis: A"]), ("Vía común, hepatopatía, CID", [])],
                [("Plaquetas o vasos", ["Si sangra"]), ("Factor VII, warfarina", [])]],
         caso=(0, 0), nota="Agregación normal: no es von Willebrand ni trombopatía."))

# PED-195 · Hierro preventivo a los 5 meses: 2 mg/kg/día · DOSIS
S("dosis", "PED-195", "Lactante de 5 meses con lactancia exclusiva y Hb 11,5 (sin anemia): suplementación preventiva con hierro a 2 mg/kg/día",
  "Prevención de la anemia infantil",
  ("Hierro preventivo (MINSA)", ["Nacidos a término con peso adecuado: desde los 4 meses, 2 mg/kg/día de hierro elemental en gotas (sulfato ferroso o complejo polimaltosado).",
                                 "Con anemia la dosis es de tratamiento (3 mg/kg/día); los prematuros empiezan al mes."]),
  ("Lactante de 5 meses", ["Lactancia materna exclusiva; asintomático.", "Hb 11,5 g/dL (sin anemia)."]),
  ["2 mg/kg/día hasta los 6 meses; luego micronutrientes o hierro hasta los 12-35 meses según la norma.",
   "Darlo lejos de la leche si es posible; las heces pueden ponerse oscuras.",
   "Control de Hb a los 6 meses."],
  MINSA + ", NTS de prevención y control de la anemia (RM 251-2024-MINSA).",
  op=("¿Dosis?", ["No: muy alta", "No: alta", "Sí: preventiva", "No: insuficiente", "No: tóxica"]),
  d=dict(rotulo="Calcula la dosis de hierro", peso=("~7 kg", "Lactante de 5 meses"),
         pasos=[("Dosis preventiva", "2 mg/kg/día", "Sin anemia"), ("Peso", "~7 kg", "Estimado"), ("Total", "≈ 14 mg/día", "Hierro elemental")],
         alternativas=[("2 mg/kg/día", "Preventiva", True), ("3 mg/kg/día", "Si hubiera anemia", False), ("4-6 mg/kg/día", "Muy alta", False), ("1 mg/kg/día", "Insuficiente", False)],
         veredicto=("2 mg/kg/día", "Es prevención: Hb 11,5 no es anemia.")))

# GIN-205 · Ectópico no roto: metotrexato · CRITERIOS + eco
S("criterios", "GIN-205", "Mujer estable con amenorrea, útero vacío, masa anexial de 25 mm y beta-hCG de 3500 sin rotura: embarazo ectópico no roto, metotrexato",
  "Embarazo ectópico · tratamiento médico",
  ("Metotrexato en el ectópico", ["Antagonista del folato: detiene el trofoblasto. Evita la cirugía y conserva la trompa (clave si ya le falta la otra).",
                                  "Requisitos: estable, sin rotura, masa < 35-40 mm, sin latido embrionario, beta-hCG < 5000 y capaz de seguir controles."]),
  ("Mujer de 25 años", ["Amenorrea de 6 semanas; salpinguectomía derecha previa por ectópico.", "Cérvix cerrado con restos de sangre; útero 7 cm no doloroso; beta-hCG 3500; eco: útero vacío, masa anexial izquierda de 25 mm."]),
  ["Metotrexato 50 mg/m² IM; beta-hCG los días 4 y 7 (debe bajar ≥ 15 %).",
   "Evitar AINE, ácido fólico, alcohol y relaciones; anticoncepción 3 meses.",
   "Cirugía si se rompe, está inestable o falla el tratamiento."],
  ACOG + " n.º 193 (2018); RCOG Green-top n.º 21 (2016).",
  op=("¿Manejo?", ["No: es para aborto intrauterino", "No: el embarazo no está en el útero", "Sí: cumple criterios", "No: perdería la única trompa", "No: riesgo de rotura"],
      {2: "Metotrexato"}),
  d=dict(rotulo="¿Cumple criterios para metotrexato?", lista_titulo="Requisitos",
         items=[("Hemodinámicamente estable, sin rotura", True, "Sin dolor ni sangrado intenso"), ("Masa < 35-40 mm", True, "25 mm"),
                ("Beta-hCG < 5000", True, "3500"), ("Sin latido embrionario", None, "No se informa"), ("Puede volver a controles", None, "Asegurar")],
         umbral="Todos = metotrexato",
         veredicto="Metotrexato: conserva su única trompa.",
         img=P("ectopico_tubario.jpg", 240, 178, [], credito="Hic et nunc" + CC + "CC BY-SA 3.0"), img_titulo="Ectópico tubárico",
         img_pie="Embarazo ectópico tubárico", conteo="3 seguros de 5"))

# NEF-081 · Hipermagnesemia grave con falla renal: hemodiálisis · REGLA + ECG
S("regla", "NEF-081", "Diabética con nefropatía que toma magnesio y presenta debilidad, hiporreflexia, somnolencia, hipotensión, bradicardia y Mg 4,2 mmol/L: hipermagnesemia grave, hemodiálisis",
  "Trastornos del magnesio",
  ("Hipermagnesemia", ["Casi siempre por aporte de magnesio (laxantes, antiácidos, suplementos) con falla renal.",
                       "Por niveles: hiporreflexia → somnolencia, hipotensión, bradicardia → parálisis respiratoria y paro."]),
  ("Mujer de 48 años, nefropatía diabética", ["Magnesio indicado por un naturista hace 1 mes.", "Debilidad, PA 80/50, FC 68, FR 28, SatO₂ 91 %; somnolienta, ROT hipoactivos; Mg 4,2 mmol/L (~10 mg/dL)."]),
  ["Suspender el magnesio; gluconato de calcio EV como antagonista inmediato.",
   "Con falla renal y nivel grave: hemodiálisis (elimina el magnesio).",
   "Soporte ventilatorio si hay depresión respiratoria."],
  KDIGO + "; " + HARRISON + ".",
  op=("¿Tratamiento inmediato?", ["No: empeora la hipotensión", "Sí: lo elimina con falla renal", "No sirve sin riñón", "No: lento", "Ayuda, pero no basta"],
      {4: "Solo gluconato de calcio y observar"}),
  d=dict(rotulo="Nivel de magnesio y lo que produce",
         reglas=[dict(nombre="Magnesio sérico (mg/dL)", que="4,2 mmol/L ≈ 10 mg/dL.", min=1, max=14, fmt="{}", ticks=[2.5, 5, 7, 10, 12],
                      bandas=[(1, 2.5, "Normal", 0), (2.5, 5, "Náuseas", 1), (5, 7, "Hiporreflexia", 2), (7, 12, "Hipotensión, somnolencia", 3), (12, 14, "Paro", 3)],
                      caso=10.2, caso_txt="ESTE CASO: ~10")],
         claves_titulo="Qué hacer",
         claves=[("Hemodiálisis", ["Falla renal + nivel grave"], True), ("Gluconato de calcio", ["Antagonista mientras tanto"], False),
                 ("Suspender el magnesio", ["Y no automedicarse"], False)]),
  banda=B("El ECG en la hipermagnesemia", P("ecg_hipermag.jpg", 380, 182, [], credito=ECG_PROPIO, fondo="#ffffff"),
          [("PR largo", "Conducción AV lenta."), ("QRS ancho", "Conducción ventricular lenta."), ("Bradicardia", "Puede llegar al paro.")],
          pie="Hipermagnesemia en el ECG"))

# PED-196 · Anafilaxia con edema laríngeo: adrenalina · ALARMA + foto
S("alarma", "PED-196", "Niño con urticaria que en 30 minutos presenta ronquera, dificultad respiratoria y cianosis: anafilaxia con edema laríngeo, adrenalina IM",
  "Anafilaxia",
  ("Anafilaxia", ["Reacción alérgica grave y rápida: piel (urticaria, angioedema) + vía aérea (ronquera, estridor, sibilancias) o caída de la PA.",
                  "La adrenalina IM es el único tratamiento que salva la vida; antihistamínicos y corticoides son complementarios."]),
  ("Niño de 4 años", ["Hace 2 días habones pruriginosos en tórax y abdomen.", "Hace 30 min voz ronca, dificultad respiratoria y cianosis."]),
  ["Adrenalina 1 mg/mL: 0,01 mg/kg IM (máx. 0,3 mg en niños) en la cara lateral del muslo; repetir cada 5-15 min.",
   "Oxígeno, posición cómoda, líquidos si hay hipotensión; preparar vía aérea avanzada.",
   "Después: antihistamínico y corticoide; observar 6-24 h; autoinyector y estudio de la causa."],
  "WAO, anafilaxia (2020); EAACI (2021); " + AAP + ".",
  op=("¿Tratamiento inicial?", ["Sí: salva la vida", "Complementario", "Complementario, tardío", "Solo para el broncoespasmo", "No: lento e insuficiente"]),
  d=dict(rotulo="Signos de anafilaxia", lista_titulo="Lo que tiene el niño",
         signos=[("Urticaria (habones)", "Tórax y abdomen", True), ("Ronquera (edema laríngeo)", "Sí", True), ("Dificultad respiratoria", "Sí", True),
                 ("Cianosis", "Sí", True), ("Hipotensión", "No se informa", False)],
         img=P("urticaria.jpg", 180, 240, [], credito="Psixtras" + CC + "CC0"), img_titulo="Habones",
         accion=("Adrenalina IM 0,01 mg/kg ya", "Muslo, repetir cada 5-15 min."),
         accion_rotulo="ANAFILAXIA",
         veredicto=("Piel + vía aérea = anafilaxia", "Adrenalina IM primero; lo demás después.")))

# GIN-206 · DIU no visible en la eco: Rx de abdomen · ÁRBOL
S("arbol", "GIN-206", "Usuaria de T de cobre sin hilos visibles y sin DIU en la ecografía transvaginal: Rx simple de abdomen (descartar migración)",
  "Anticoncepción · DIU no localizado",
  ("Hilos del DIU no visibles", ["Puede estar dentro del útero (hilos retraídos), haber sido expulsado o haber perforado el útero hacia el abdomen.",
                                 "Primero eco; si no está en el útero: Rx de abdomen (el DIU es radiopaco). Si aparece en el abdomen: retiro por laparoscopía."]),
  ("Usuaria de T de cobre", ["En el control no se ven los hilos.", "Eco TV: no se ve el DIU."]),
  ["Prueba de embarazo y anticoncepción de respaldo mientras tanto.",
   "Rx de abdomen: si no aparece, fue expulsado → colocar otro.",
   "En el abdomen: laparoscopía para retirarlo (el cobre causa adherencias)."],
  OMS + ", manual de planificación familiar (2022); ACOG.",
  op=("¿Siguiente paso?", ["Después, si hace falta", "No sin confirmarlo", "Sí: el DIU es radiopaco", "No: laparoscopía si se ubica", "Si estuviera en el útero"]),
  arbol=Q("Hilos no visibles: ¿dónde está el DIU?", [
      L("En el útero (eco)", "Dejarlo", ["Hilos retraídos"]),
      L("No se ve en la eco (este caso)", "RX DE ABDOMEN", ["Abdomen: laparoscopía", "No aparece: expulsado"], path=True)], path=True),
  banda=B("El dispositivo", P("diu.jpg", 170, 240, [], credito="Hic et nunc" + CC + "dominio público", fondo="#ffffff"),
          [("Radiopaco", "Se ve en la Rx aunque esté fuera del útero."), ("Perforación", "Suele ocurrir al colocarlo."),
           ("Expulsión", "Más en los primeros meses.")],
          pie="DIU de cobre"))

# NEU-060 · Crisis asmática: tórax silente · SEMÁFORO
S("semaforo", "NEU-060", "Asmático con disnea grave y murmullo vesicular ausente en ambos hemitórax: el tórax silente es criterio de crisis con riesgo vital",
  "Asma · crisis grave",
  ("Gravedad de la crisis asmática (GINA)", ["Leve-moderada: habla en frases, FR < 30, FC 100-120, SatO₂ 90-95 %.",
                                             "Grave: habla en palabras, FR > 30, FC > 120, SatO₂ < 90 %, músculos accesorios. Riesgo vital: tórax silente, cianosis, confusión, bradicardia."]),
  ("Varón de 27 años, asmático", ["Disnea severa a pequeños esfuerzos.", "PA 130/90, FC 110, FR 22; murmullo vesicular ausente bilateral; SatO₂ 91 %."]),
  ["Oxígeno (meta 93-95 %), salbutamol + ipratropio repetidos, corticoide sistémico.",
   "Sulfato de magnesio EV; UCI y preparar intubación.",
   "El tórax silente significa que casi no entra aire: no confundirlo con mejoría."],
  GINA + ".",
  op=("¿Criterio de gravedad?", ["No: rango moderado", "Sí: riesgo vital", "No: rango moderado", "No: < 30", "No: normal"]),
  d=dict(rotulo="¿Qué tan grave es la crisis?", tag="ESTE CASO",
         ilu_titulo="El tórax",
         ilu=ILU(D(lambda s, x, y: I.cuerpo(s, x + 50, y, {"torax": "#fecaca"}, sc=0.7), 330, 330)),
         ilu_pie="Murmullo vesicular ausente en ambos pulmones.",
         check_titulo="Signos de este paciente",
         check=[("Tórax silente (MV ausente bilateral)", True), ("FC 110, FR 22, SatO₂ 91 %", False), ("Disnea grave", True)],
         luces=[("Leve-moderada", "Habla en frases, FR < 30, SatO₂ 90-95 %", ["Salbutamol y corticoide"]),
                ("Grave", "Habla en palabras, FR > 30, SatO₂ < 90 %", ["+ ipratropio, magnesio"]),
                ("Riesgo vital", "Tórax silente, cianosis, confusión", ["UCI, preparar intubación"])], ans=2))

# GIN-207 · Contracciones con cérvix largo y fibronectina negativa: observar · REGLA
S("regla", "GIN-207", "Gestante de 31 semanas con contracciones pero cérvix cerrado, cervicometría de 35 mm y fibronectina negativa: bajo riesgo de parto pretérmino, observación",
  "Amenaza de parto pretérmino · predicción",
  ("Cervicometría y fibronectina", ["Cuello ≥ 30 mm y fibronectina negativa: riesgo de parto en 7 días < 1 % (alto valor predictivo negativo).",
                                    "Cuello < 15-20 mm o fibronectina positiva: alto riesgo → corticoides y tocólisis."]),
  ("Gestante de 31 semanas", ["Contracciones cada 5 minutos.", "Cérvix cerrado, borramiento 20 %, −4; cervicometría 35 mm; fibronectina negativa."]),
  ["Observar unas horas, hidratar, descartar infección urinaria; alta con signos de alarma.",
   "No dar tocolíticos ni corticoides si el riesgo es bajo.",
   "Progesterona y cerclaje son para prevención en cérvix corto, no para este cuadro."],
  ACOG + " n.º 171 (2016; act.); FIGO (2021).",
  op=("¿Manejo?", ["No: es para cérvix corto", "Sí: riesgo muy bajo", "No: no hay parto pretérmino", "No: cérvix largo", "No: no hay indicación"]),
  d=dict(rotulo="Longitud del cuello y riesgo",
         reglas=[dict(nombre="Cervicometría (mm)", que="< 15-20 mm alto riesgo; ≥ 30 mm bajo riesgo.", min=0, max=45, fmt="{}", ticks=[15, 25, 30],
                      bandas=[(0, 15, "Alto riesgo", 3), (15, 25, "Intermedio", 2), (25, 30, "Bajo", 1), (30, 45, "Muy bajo", 0)],
                      caso=35, caso_txt="ESTE CASO: 35 mm")],
         claves_titulo="Además",
         claves=[("Fibronectina negativa", ["Riesgo < 1 % en 7 días"], True), ("Cérvix cerrado, −4", ["No hay trabajo de parto"], True),
                 ("Observar", ["Y alta con alarma"], True)]))

# CIR-107 · Hematoma duodenal traumático: observación · TERMÓMETRO (AAST)
S("termometro", "CIR-107", "Conductor con golpe en el epigastrio contra el timón, estable, con hematoma de 3 cm en la pared duodenal en la TC: manejo conservador con observación",
  "Trauma duodenal",
  ("Hematoma duodenal", ["Golpe en el epigastrio (timón, manubrio): el duodeno se aplasta contra la columna.",
                         "Sin perforación, el hematoma intramural se maneja sin cirugía: sonda nasogástrica, ayuno y nutrición; se resuelve en 1-3 semanas."]),
  ("Chofer de 24 años", ["Golpe con el timón hace 1 hora.", "PA 110/70, FC 84; dolor epigástrico; TC: hematoma de 3 cm en la pared de D1."]),
  ["Sonda nasogástrica, ayuno, nutrición parenteral si dura; TC seriada.",
   "Buscar lesión de páncreas (amilasa, lipasa).",
   "Cirugía si hay perforación (aire o contraste fuera), no se resuelve en 2-3 semanas o empeora."],
  "AAST, escala de lesión duodenal; EAST (2019).",
  op=("¿Indicación inicial?", ["No: no hay colección", "No: estable", "Sí: hematoma sin perforación", "No: estable, sin perforación", "No: excesivo"]),
  d=dict(rotulo="Lesión duodenal (AAST)", caso_nivel=0, ruta_titulo="Qué hacer en el grado I", paso_label="ESTE CASO",
         niveles=[("I", "Hematoma de un segmento", ["O laceración parcial"]), ("II", "Hematoma de > 1 segmento", ["O rotura < 50 %"]),
                  ("III", "Rotura 50-100 % de D2", ["O 50-75 % de otros"]), ("IV-V", "Rotura extensa", ["Ampolla, páncreas"])],
         pasos=[(1, "Sonda nasogástrica y ayuno", ["Descomprimir"], True),
                (2, "TC seriada y amilasa", ["Vigilar perforación y páncreas"], False),
                (3, "Cirugía", ["Si perfora o no se resuelve"], False)]))

# SP-152 · Muerte masiva de roedores: epizootia · RADIAL
S("radial", "SP-152", "Gran cantidad de roedores muertos en zonas agrícolas durante una alerta de peste: se notifica como epizootia",
  "Vigilancia epidemiológica · zoonosis",
  ("Términos epidemiológicos", ["Epizootia: aumento inusual de una enfermedad en animales. Epidemia/brote: en personas. Endemia: presencia habitual. Pandemia: varios continentes.",
                                "En la peste, la muerte de roedores precede a los casos humanos: es una alerta temprana."]),
  ("Centro de salud en Piura", ["Alerta epidemiológica por aumento de casos de peste.", "Un agente comunitario informa muchos roedores muertos."]),
  ["Notificar de inmediato la epizootia (vigilancia de peste).",
   "Control de pulgas antes que de ratas (si se matan ratas primero, las pulgas buscan humanos).",
   "Búsqueda de casos humanos (bubones, fiebre) y profilaxis a contactos."],
  MINSA + ", NTS de vigilancia de peste; " + OMS + ".",
  op=("¿Cómo notificar?", ["Sí: enfermedad en animales", "No: en personas", "No: en personas", "No: habitual", "No: mundial"]),
  d=dict(rotulo="¿Qué término corresponde?", centro="AUMENTO DE CASOS", centro_sub="¿en quién y dónde?", ans=0,
         items=[("EPIZOOTIA", ["En animales", "Esta pregunta"]), ("EPIDEMIA", ["Más casos de lo esperado en personas"]),
                ("BROTE", ["Casos relacionados, lugar y tiempo"]), ("ENDEMIA", ["Presencia habitual"]), ("PANDEMIA", ["Varios continentes"])],
         ruta=["Roedores muertos", "Epizootia", "Control de pulgas", "Vigilar casos humanos"]))

# GIN-208 · Edad gestacional por altura uterina · GRÁFICA
S("grafica", "GIN-208", "Gestante con altura uterina de 21 cm y movimientos fetales recién percibidos: por el examen clínico tiene unas 21 semanas (la FUR de 27 semanas no coincide)",
  "Control prenatal · altura uterina",
  ("Altura uterina y edad gestacional", ["Entre las 20 y 36 semanas la altura uterina en cm ≈ semanas de gestación (± 2 cm). A las 20 semanas llega al ombligo.",
                                         "Movimientos fetales: primigestas los notan a las 18-20 semanas, multíparas a las 16-18."]),
  ("Mujer de 32 años, G1 P1001", ["Primer control; por FUR tendría 27 semanas.", "Sintió movimientos la semana pasada; AU 21 cm; LCF 140."]),
  ["Si la AU no coincide con la FUR (> 3 cm): ecografía para fechar y descartar restricción del crecimiento.",
   "Clínicamente: ~21 semanas.",
   "Causas de AU baja para la FUR: FUR errónea, restricción, oligohidramnios."],
  WILLIAMS + "; " + MINSA + ".",
  op=("¿Semanas?", ["No: no coincide con la AU", "Sí: AU 21 ≈ 21 sem", "No: muy poco", "Es la FUR, no el examen", "No: muy alto"]),
  d=dict(rotulo="Altura uterina según las semanas", eje_x="Semanas de gestación", eje_y="Altura uterina (cm)",
         x=(16, 40, [(16, "16"), (20, "20"), (24, "24"), (27, "27"), (32, "32"), (36, "36"), (40, "40")]),
         y=(14, 38, [(14, "14"), (20, "20"), (26, "26"), (32, "32"), (38, "38")]),
         series=[("Esperado (cm ≈ semanas)", [(16, 16), (20, 20), (24, 24), (28, 28), (32, 32), (36, 35), (40, 34)], "#0f766e")],
         zonas=[(20, 36, "cm ≈ semanas", "#ccfbf1")],
         caso=(21, 21, "AU 21 cm"),
         notas=[("AU 21 cm ≈ 21 semanas", "El examen clínico.", True),
                ("FUR: 27 semanas", "No coincide: pedir eco para fechar.", False),
                ("Movimientos recién percibidos", "Apoya ~20 semanas.", False)],
         veredicto=("Por el examen: ~21 semanas", "La discordancia con la FUR obliga a una ecografía.")))

# GIN-209 · Prolongado con Bishop desfavorable: misoprostol · ÁRBOL + Bishop
S("arbol", "GIN-209", "Primigesta de 41+3 semanas con menos movimientos fetales, oligohidramnios, test estresante negativo y cuello desfavorable: madurar el cuello con misoprostol e inducir",
  "Embarazo prolongado · inducción",
  ("Inducción con cuello desfavorable", ["Con oligohidramnios y 41 semanas se termina la gestación; si el feto tolera las contracciones (test estresante negativo), puede ser vaginal.",
                                         "Bishop ≤ 6: primero madurar (misoprostol 25 µg vaginal c/4-6 h o sonda de Foley) y luego oxitocina."]),
  ("Primigesta de 41 semanas 3 días", ["Menos movimientos fetales y oligohidramnios; test estresante negativo.", "AU 32 cm, LCI; 0 cm, 20 %, −2, cuello posterior e intermedio."]),
  ["Misoprostol 25 µg vaginal cada 4-6 h con monitoreo fetal.",
   "Oxitocina cuando Bishop > 6 (al menos 4 h después del último misoprostol).",
   "Cesárea si el monitoreo se altera."],
  ACOG + " n.º 146 (2014; act.); " + OMS + ", inducción (2022).",
  op=("¿Conducta?", ["No: con Bishop 2 falla", "No: con oligohidramnios no se espera", "Sí: Bishop desfavorable", "No: hay oligohidramnios", "No: riesgo fetal"]),
  arbol=Q("41 semanas con oligohidramnios: ¿tolera el feto y cómo está el cuello?", [
      L("Tolera; Bishop ≤ 6 (este caso)", "MADURAR CON MISOPROSTOL", ["Luego oxitocina"], path=True),
      L("Tolera; Bishop > 6", "Oxitocina", []),
      L("No tolera (test positivo)", "Cesárea", [])], path=True),
  escala=dict(nombre="Puntaje de Bishop", modo="puntaje", que="Madurez del cuello: > 6 favorable para oxitocina.",
              items=[("Dil", "Dilatación (0 cm = 0)", "0 cm", 0), ("Borr", "Borramiento (0-30 % = 0)", "20 %", 0), ("Est", "Estación (−2 = 1)", "−2", 1),
                     ("Cons", "Consistencia (intermedia = 1)", "Intermedia", 1), ("Pos", "Posición (posterior = 0)", "Posterior", 0)],
              total_txt="Total: 2 puntos", total_nota="de 0 a 13",
              rangos=[("≤ 6", "Desfavorable", "Madurar"), ("> 6", "Favorable", "Oxitocina")], caso_rango=0,
              porque=[("Cuello cerrado, posterior, poco borrado", True)], conducta="Misoprostol y luego oxitocina."))

# HEM-040 · Sangrado con INR alto por warfarina · MATRIZ
S("matriz", "HEM-040", "Anticoagulado con warfarina, INR 7 y hematemesis (sangrado mayor): revertir de inmediato reponiendo factores (plasma fresco o, mejor, concentrado de complejo protrombínico) más vitamina K EV",
  "Anticoagulación · reversión de la warfarina",
  ("Reversión de la warfarina", ["La vitamina K tarda 6-24 h: sola no basta en un sangrado mayor.",
                                 "Con sangrado mayor: reponer factores ya (concentrado de complejo protrombínico de elección; plasma fresco si no hay) + vitamina K 5-10 mg EV."]),
  ("Varón de 67 años con warfarina por FA", ["Hematemesis desde ayer, hoy más.", "PA 120/80, FC 86; equimosis; INR 7, Hb 10."]),
  ["Suspender la warfarina; plasma fresco 10-15 mL/kg (o CCP 25-50 UI/kg) + vitamina K EV.",
   "Endoscopía alta para el sitio de sangrado; IBP EV.",
   "Sin sangrado e INR 4,5-10: solo suspender ± vitamina K oral."],
  "ACC, reversión de anticoagulantes (2020); CHEST (2012; act.).",
  op=("¿Conducta inmediata?", ["Si la Hb cae más", "Necesaria, pero tarda", "No: plaquetas normales", "Sí: repone factores ya", "No: sangrado mayor"]),
  d=dict(rotulo="Warfarina con INR alto: ¿qué hacer?", eje_x="INR", eje_y="Sangrado",
         cols=["INR alto (> 4,5)", "INR en rango o poco alto"], rows=["Mayor (hematemesis)", "Sin sangrado"], caso=(0, 0),
         cells=[[("PLASMA FRESCO (o CCP) + VITAMINA K EV", ["Revertir ya", "Este caso"]), ("Igual revertir", ["Si el sangrado es grave"])],
                [("Suspender ± vitamina K oral", ["Controlar INR"]), ("Seguir y controlar", [])]]))

# REU-059 · Pitiriasis versicolor · LECTURA + foto
S("lectura", "REU-059", "Niño con máculas hipo e hiperpigmentadas descamativas en el tronco y KOH con hifas cortas y levaduras («espaguetis con albóndigas»): pitiriasis versicolor por Malassezia globosa",
  "Micosis superficiales",
  ("Pitiriasis versicolor", ["Levadura de la piel (Malassezia) que crece con calor, humedad y sudor; máculas de color variable con descamación fina («signo de la uñada»).",
                             "KOH: hifas cortas y levaduras redondas («espaguetis con albóndigas»); luz de Wood amarillo-verdosa."]),
  ("Niño de 8 años", ["Máculas hipo e hiperpigmentadas, bien delimitadas, descamativas en el tronco.", "KOH: hifas anguladas y levaduras («espaguetis y albóndigas»)."]),
  ["Tópico: ketoconazol champú 2 % o sulfuro de selenio como jabón 5-10 min por 1-2 semanas; clotrimazol en lesiones pequeñas.",
   "Extensa o recurrente: itraconazol o fluconazol oral.",
   "La hipopigmentación tarda meses en volver; recurre con el calor."],
  "AAD; " + NELSON + ".",
  op=("¿Agente?", ["No: tiña de la cabeza", "Sí: espaguetis con albóndigas", "No: tiña negra palmar", "No: levaduras y seudohifas en pliegues", "No: tiña de la cabeza o del cuerpo"]),
  d=dict(rotulo="Lee la piel", img_titulo="Pitiriasis versicolor",
         img=PA("pitiriasis.jpg", 320, credito="CDC" + CC + "dominio público"), pines=[(0.3, 0.45)],
         pasos=[("Máculas de distinto color", "Claras u oscuras, en el tronco.", True),
                ("Descamación fina al rascar", "Signo de la uñada.", False),
                ("KOH: espaguetis y albóndigas", "Hifas cortas + levaduras.", False),
                ("Tratar", "Ketoconazol o sulfuro de selenio tópico.", False)],
         img_pie="Pitiriasis versicolor",
         veredicto=("Máculas versicolores + espaguetis y albóndigas = Malassezia", "Antifúngico tópico.")))

# SP-153 · APS: cobertura · CUADRÍCULA
S("cuadricula", "SP-153", "En una epidemia de dengue muchos pacientes no pudieron ser atendidos y subió la letalidad: el elemento de la APS que debe mejorar es la cobertura (y el acceso) universal",
  "Atención primaria · elementos esenciales",
  ("Elementos de un sistema basado en APS (OPS)", ["Cobertura y acceso universal, primer contacto, atención integral, longitudinalidad, orientación familiar y comunitaria, sostenibilidad, solidaridad.",
                                                   "Si la gente no logra ser atendida, falla la cobertura."]),
  ("Brote de dengue del año", ["Muchos pacientes no lograban ser atendidos.", "Aumentó la letalidad."]),
  ["Ampliar la oferta en el brote: unidades febriles, triaje, horarios extendidos.",
   "Fortalecer el primer nivel para detectar signos de alarma y referir.",
   "Longitudinalidad: seguir al paciente en el tiempo (no es el problema aquí)."],
  "OPS, APS renovada (2007); OPS, dengue (2024).",
  op=("¿Elemento a mejorar?", ["No: financiamiento a largo plazo", "Sí: no alcanzó a atender", "No: financiamiento equitativo", "No: seguimiento en el tiempo", "No: no es elemento de APS"]),
  d=dict(rotulo="¿Qué elemento de la APS falló?", alto_img=0,
         celdas=[("Cobertura y acceso", ["Que todos puedan ser atendidos", "Este caso"], None, True),
                 ("Longitudinalidad", ["Seguimiento en el tiempo"], None, False),
                 ("Sostenibilidad y solidaridad", ["Financiamiento"], None, False),
                 ("Especialización", ["No es elemento de la APS"], None, False)],
         veredicto=("Falló la cobertura", "Los pacientes no lograron ser atendidos.")))

# CIR-108 · Infección de herida operatoria · CHECKLIST
S("checklist", "CIR-108", "Apendicectomizado al 5.º día con fiebre y dolor en la herida: infección de herida operatoria, abrir, drenar y cultivar",
  "Infección del sitio quirúrgico",
  ("Infección de la herida operatoria", ["Aparece entre el 4.º y 7.º día: eritema, calor, dolor, induración, secreción purulenta, fiebre.",
                                         "El tratamiento es abrir la herida (retirar puntos), drenar el pus, cultivar y dejar que cierre por segunda intención."]),
  ("Varón de 25 años", ["Apendicectomía abierta hace 5 días (incisión transversa).", "Fiebre y dolor en la herida."]),
  ["Retirar puntos, drenar y lavar; curaciones diarias.",
   "Cultivo de la secreción; antibiótico solo si hay celulitis extensa o signos sistémicos.",
   "Descartar absceso intraabdominal (eco o TC) si la fiebre persiste."],
  "CDC, infección del sitio quirúrgico (2017); " + IDSA + " (2014).",
  op=("¿Conducta inicial?", ["Sí: drenar y cultivar", "No: el pus no sale solo", "No: sin drenar no cura", "Falta el cultivo", "No: encierra el pus"]),
  d=dict(rotulo="Qué hacer con la herida infectada", tag="PRIMERO",
         pasos=[("Abrir la herida (retirar puntos)", "Liberar el pus", True), ("Drenar y lavar", "Con suero", True),
                ("Cultivo de la secreción", "Ajustar antibiótico si hace falta", True), ("Curaciones diarias", "Cierre por segunda intención", False)],
         no_hacer=[("Cerrar con nuevos puntos", "Encierra la infección"), ("Solo antibióticos", "No llegan al pus"), ("Solo observar", "Empeora")],
         veredicto=("Drenaje + cultivo", "El pus se drena; el antibiótico es complementario.")))

# REU-060 · Artritis reumatoide · PUNTAJE (ACR/EULAR 2010)
S("puntaje", "REU-060", "Mujer de 35 años con 4 meses de poliartritis de manos y muñecas, rigidez matutina, anti-CCP positivo y erosiones: artritis reumatoide",
  "Artritis reumatoide",
  ("Criterios ACR/EULAR 2010", ["Articulaciones (0-5) + serología FR/anti-CCP (0-3) + reactantes (0-1) + duración ≥ 6 semanas (0-1): ≥ 6 = artritis reumatoide.",
                                "Las erosiones típicas en la Rx bastan por sí solas para clasificarla."]),
  ("Mujer de 35 años, 4 meses", ["Dolor de pequeñas y medianas articulaciones con rigidez matutina; tumefacción de manos y muñecas.", "Anti-CCP (+), ANA (+); Rx: osteopenia periarticular y erosiones."]),
  ["Metotrexato precoz (+ ácido fólico); corticoide a dosis baja por poco tiempo.",
   "Si no mejora en 3-6 meses: biológico (anti-TNF) o inhibidor de JAK.",
   "ANA positivo puede verse en AR; descartar lupus si hay otros datos."],
  "ACR/EULAR (2010); EULAR, manejo de AR (2022).",
  op=("¿Diagnóstico?", ["Sí: ≥ 6 puntos + erosiones", "No: no hay erosiones ni anti-CCP", "No: sin otros dominios de lupus", "No: requiere anti-RNP", "No: niños tras estreptococo"]),
  d=dict(rotulo="ACR/EULAR 2010 punto por punto", escala="ACR/EULAR 2010", total=9, max=10,
         interpreta="≥ 6: artritis reumatoide",
         items=[("Articulaciones: > 10 con al menos una pequeña", 5, True), ("Anti-CCP positivo (alto)", 3, True),
                ("Duración ≥ 6 semanas (4 meses)", 1, True), ("PCR o VSG altas (no informadas)", 1, False)],
         bandas=[("< 6", "No clasifica", "Seguir y reevaluar.", False), ("≥ 6", "Artritis reumatoide", "Metotrexato precoz.", True)]),
  triada=TR([("Rigidez matutina > 1 h", "Sí", True), ("Poliartritis simétrica de manos", "Manos y muñecas", True), ("Erosiones en la Rx", "Sí", True)],
            [("Pistas clásicas de AR", 0, 2)], "Las erosiones típicas bastan para clasificarla."))
