"""Entrega 3 · tanda t19 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, AHA, AAP, NICE
from c26 import D, ILU, SABISTON
from c27 import DOS, CON_CREDITO
from esc28 import ABORTO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
PMC_HEMO = "Abdalrahman et al. · Cureus 2026 · PMC13536977 (PubMed Central) · CC BY 4.0"
GUYTON = "Guyton y Hall, Tratado de fisiología médica 14.ª ed."

# SP-156 · Planificación: primero el diagnóstico · FASES
S("fases", "SP-156", "Nuevo director con más presupuesto para los problemas sanitarios: la primera etapa de la planificación es elaborar el diagnóstico",
  "Gestión sanitaria · planificación",
  ("Etapas de la planificación", ["Diagnóstico → programación (prioridades, objetivos, estrategias) → ejecución → evaluación, y vuelta a empezar.",
                                  "Sin diagnóstico no se sabe qué problemas atender ni dónde poner el dinero."]),
  ("Director nuevo", ["El presupuesto podría subir 50 % en 2025.", "Debe atender los principales problemas sanitarios."]),
  ["El diagnóstico usa el ASIS: problemas, causas, recursos y brechas.",
   "Después se priorizan problemas y se fijan objetivos medibles.",
   "Responsables, estrategias, presupuesto y personal vienen después."],
  OMS + ", planificación sanitaria; " + MINSA + ", Plan Operativo Institucional (CEPLAN).",
  op=("¿Etapa inicial?", ["Sí: base de todo el plan", "No: es de la programación", "No: necesita el diagnóstico antes", "No: es la ejecución", "No: es la ejecución"]),
  d=dict(rotulo="Las etapas de la planificación", ans=0,
         fases=[("Diagnóstico", "Primero", "ELABORAR EL DIAGNÓSTICO", ["Problemas, causas, recursos", "Esta pregunta"]),
                ("Programación", "Segundo", "Priorizar y fijar objetivos", ["Estrategias y responsables"]),
                ("Ejecución", "Tercero", "Hacer lo planeado", ["Presupuesto y personal"]),
                ("Evaluación", "Cuarto", "Medir resultados", ["Corregir el plan"])]))

# SP-157 · Embarazo adolescente: educación sexual · MATRIZ
S("matriz", "SP-157", "Aumento de la muerte materna en adolescentes de 13 a 17 años: para reducir el embarazo adolescente se prioriza la educación en salud sexual y reproductiva en los colegios",
  "Salud del adolescente · prevención del embarazo",
  ("Prevenir el embarazo adolescente", ["Lo que reduce el número de embarazos actúa antes de que ocurran: educación sexual integral y acceso a métodos.",
                                        "Atención prenatal, partos seguros y hospitales reducen la muerte materna, pero no evitan el embarazo."]),
  ("Ámbito sanitario regional", ["Más muertes maternas entre los 13 y 17 años.", "Pregunta: ¿qué baja el embarazo adolescente?"]),
  ["Educación en colegios: anticoncepción, ITS y decisiones informadas.",
   "Servicios diferenciados para adolescentes con consejería y métodos.",
   "La atención del embarazo y del parto sigue siendo necesaria, pero llega tarde."],
  OMS + ", embarazo en la adolescencia (2024); " + MINSA + ", Plan multisectorial de prevención del embarazo en adolescentes.",
  op=("¿Prioridad?", ["No: el embarazo ya ocurrió", "Sí: evita el embarazo", "No: atiende complicaciones", "No: atiende el parto", "No: no evita el embarazo"],
      {1: "Capacitación en salud sexual en colegios", 2: "Funciones obstétricas y neonatales (I-1, I-2)", 3: "Quitar barreras para la atención del parto"}),
  d=dict(rotulo="¿Qué evita el embarazo y qué atiende sus riesgos?", eje_x="Efecto", eje_y="Dónde",
         cols=["Evita el embarazo", "Atiende el embarazo"], rows=["Colegio y comunidad", "Establecimiento"], caso=(0, 0),
         cells=[[("EDUCACIÓN SEXUAL EN COLEGIOS", ["Antes del embarazo", "Este caso"]), ("Agentes y visitas", ["Captar gestantes"])],
                [("Consejería y métodos", ["Servicio diferenciado"]), ("Control prenatal y parto", ["Bajan la muerte materna"])]]))

# PED-203 · Bronquitis aguda · EMBUDO
S("embudo", "PED-203", "Niño de 3 años con resfrío, fiebre, tos productiva y roncantes difusos sin taquipnea ni crepitantes: bronquitis aguda",
  "Infecciones respiratorias bajas",
  ("Bronquitis aguda", ["Inflamación viral de los bronquios: tos (a veces con flema), fiebre baja y roncantes que cambian con la tos.",
                        "No hay taquipnea, crepitantes ni tiraje (eso orienta a neumonía)."]),
  ("Niño de 3 años, 4 días", ["Congestión nasal, tos productiva; vómitos desde hace 2 días.", "T 38,2 °C, FR 24 (normal), MV pasa bien, roncantes difusos."]),
  ["Tratamiento sintomático: líquidos, antipirético; sin antibiótico.",
   "La tos puede durar 2-3 semanas.",
   "Signos de alarma: respiración rápida, tiraje, no come: reevaluar."],
  NELSON + "; OMS, AIEPI.",
  op=("¿Diagnóstico?", ["No: sin sibilancias recurrentes", "No: FR normal, sin crepitantes", "No: es de < 2 años con sibilancias", "Sí: tos + roncantes, FR normal", "No: sin estridor ni tos perruna"]),
  d=dict(rotulo="Tos con fiebre en un niño de 3 años", inicio="Tos, fiebre y roncantes",
         candidatos=["Laringotraqueítis", "Bronquiolitis", "Asma", "Neumonía", "Bronquitis aguda"],
         pasos=[("¿Tiene estridor y tos perruna?", ["Laringotraqueítis"]),
                ("¿Sibilancias (primer episodio < 2 años o recurrentes)?", ["Bronquiolitis", "Asma"]),
                ("¿Respira rápido (≥ 40 a esta edad) o tiene crepitantes?", ["Neumonía"])],
         final=("BRONQUITIS AGUDA", ["Roncantes, FR normal", "Tratamiento sintomático"]),
         nota="FR 24 es normal a los 3 años: no es neumonía."))

# NEF-083 · Hipopotasemia por laxantes · CASCADA + ECG
S("cascada", "NEF-083", "Mujer delgada con debilidad, calambres, hipotensión, ROT disminuidos y ondas U con T aplanada: hipopotasemia por mal uso de laxantes (polietilenglicol)",
  "Trastornos del potasio",
  ("Hipopotasemia", ["K⁺ < 3,5 mEq/L: debilidad, calambres, hiporreflexia, íleo; en el ECG, T aplanada, ondas U y QT largo.",
                     "Causas: pérdidas digestivas (diarrea, laxantes, vómitos), diuréticos de asa o tiazidas, exceso de mineralocorticoides."]),
  ("Mujer de 29 años", ["Pierde 8 kg en 3 semanas; cansancio y calambres.", "PA 90/60, FC 100, mucosas secas, ROT ↓. ECG: ondas U."]),
  ["Medir K⁺, Mg²⁺ y bicarbonato; pensar en trastorno alimentario.",
   "Reponer KCl (oral si es leve; EV sin pasar de 10-20 mEq/h por vía periférica).",
   "Corregir el magnesio: sin él, el potasio no sube."],
  HARRISON + "; " + NICE + ".",
  op=("¿Explicación?", ["No: no baja el potasio", "Sí: pierde K por heces", "No: tiroides sin pérdida de K", "No: retiene potasio", "No: no explica la deshidratación"]),
  d=dict(rotulo="Del laxante al ECG", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Abuso de laxante", "Diarrea osmótica", [("Pérdida de peso", "8 kg", True)]),
                ("Pierde agua y sal", "Se activa la aldosterona", [("PA 90/60, mucosas secas", "Deshidratada", True)]),
                ("Pierde potasio", "Por heces y orina", [("Debilidad, calambres, ROT ↓", "Músculo", True)]),
                ("Corazón con K⁺ bajo", "Repolarización lenta", [("Ondas U, T aplanada", "ECG", True)])],
         veredicto=("Hipopotasemia por mal uso de laxantes", "Reponer potasio y magnesio; buscar trastorno alimentario.")),
  banda=B("El ECG de la hipopotasemia", P("ecg_hipok.jpg", 380, 228, [("flecha", 0.39, 0.25, 0.6, 0.06, "onda U")], credito=ECG_PROPIO, fondo="#ffffff"),
          [("T aplanada", "La onda T pierde altura."), ("Onda U", "Joroba después de la T."), ("Si empeora", "QT largo y arritmias.")],
          pie="Trazado de enseñanza."))

# GIN-214 · Vacunas en la gestante · SEMÁFORO
S("semaforo", "GIN-214", "En la gestante no se indica la vacuna contra el sarampión porque es de virus vivos atenuados",
  "Inmunizaciones en el embarazo",
  ("Vacunas en el embarazo", ["Inactivadas y toxoides: sí (influenza, Tdap, dT, COVID-19).",
                              "Vivas atenuadas: no (sarampión-paperas-rubéola, varicela, BCG); riesgo teórico para el feto."]),
  ("Gestante de 20 semanas", ["Acude a control prenatal.", "¿Qué vacuna no se indica?"]),
  ["Tdap entre las 20 y 36 semanas (mejor 27-36): protege al bebé de la tosferina.",
   "Influenza en cualquier trimestre durante la temporada.",
   "SPR: vacunar antes del embarazo o en el puerperio; evitar embarazo 1 mes tras recibirla."],
  CDC + ", vacunas en el embarazo (2025); " + MINSA + ", esquema nacional de vacunación.",
  op=("¿No indicada?", ["Sí se indica", "Sí: es viva atenuada", "Sí se indica (Tdap)", "Sí se indica", "Sí se indica"]),
  d=dict(rotulo="Vacunas en la gestante por colores", tag="SEMÁFORO",
         ilu_titulo="La gestante",
         ilu=ILU(D(lambda s, x, y: I.gestante(s, x + 100, y, sc=0.6), 330, 270)),
         ilu_pie="20 semanas de gestación.",
         check_titulo="La vacuna del sarampión",
         check=[("Es de virus vivos atenuados", True), ("Riesgo teórico para el feto", True), ("Se da antes o después del embarazo", True)],
         luces=[("Verde · se indican", "Inactivadas y toxoides", ["Influenza, Tdap, dT, COVID-19"]),
                ("Amarillo · si hay riesgo", "Según exposición", ["Hepatitis A y B, neumococo"]),
                ("Rojo · no se indican", "Vivas atenuadas", ["Sarampión (SPR), varicela, BCG"])], ans=2))

# OFT-049 · Quemadura ocular por álcali · RELOJ + Roper-Hall
S("reloj", "OFT-049", "Niño con quemadura ocular por lejía (álcali) y queratitis: lo primero es la irrigación abundante con suero fisiológico",
  "Urgencias oftalmológicas · quemaduras químicas",
  ("Quemadura química del ojo", ["Los álcalis (lejía, cal, cemento) penetran y destruyen más que los ácidos.",
                                 "Lo que más salva el ojo es lavar de inmediato y mucho tiempo, antes de cualquier examen."]),
  ("Niño de 12 años", ["Le cayó lejía en el ojo.", "Tiene queratitis."]),
  ["Irrigar 15-30 min (o más) con suero o Ringer hasta pH 7; revisar fondos de saco.",
   "Nunca neutralizar con ácido: la reacción produce calor.",
   "Luego: antibiótico tópico, ciclopléjico, lubricante; corticoide solo indicado por el oftalmólogo."],
  "AAO, Preferred Practice Pattern (2024); Dua y Roper-Hall.",
  op=("¿Tratamiento inicial?", ["No: después, por el oftalmólogo", "No: primero lavar", "Sí: diluye y arrastra el álcali", "Ayuda a lavar, no trata", "No: reacción con calor"]),
  d=dict(rotulo="Qué hacer y cuándo", tag="YA",
         pasos=[("0 min", "Irrigar", "Suero fisiológico abundante", True), ("+15 min", "Medir pH", "Seguir hasta pH 7", False),
                ("Luego", "Examinar", "Fluoresceína y limbo", False), ("Días", "Tratar", "Antibiótico, ciclopléjico", False)],
         veredicto=("Irrigación abundante, de inmediato", "Antes de examinar; sin neutralizar.")),
  escala=dict(nombre="Gravedad de la quemadura química (Roper-Hall)", que="Se gradúa después de lavar, por la córnea y la isquemia del limbo.", orden=True,
              grados=[("Grado I", "Buen pronóstico", ["Daño del epitelio corneal", "Sin isquemia del limbo"]),
                      ("Grado II", "Bueno", ["Córnea algo opaca", "Isquemia < 1/3 del limbo"]),
                      ("Grado III", "Reservado", ["Pérdida total del epitelio", "Isquemia 1/3-1/2"]),
                      ("Grado IV", "Malo", ["Córnea opaca", "Isquemia > 1/2 del limbo"])],
              caso=0, porque=[("Queratitis: daño del epitelio", True), ("No se describe isquemia del limbo", True)],
              conducta="Lavar primero; el grado se define al examinar."),
  banda=B("Cómo se lava", D(lambda s, x, y: I.ojo_lavado(s, x - 10, y + 40, sc=0.95), 270, 260),
          [("Suero a chorro", "Del lado de la nariz hacia afuera."), ("Párpados abiertos", "Con anestésico tópico si hace falta."), ("Hasta pH 7", "Medir con tira.")],
          pie="Esquema."))

# GAS-067 · Hepatitis C: la histología define la gravedad · TARJETAS
S("tarjetas", "GAS-067", "Enfermera con hepatitis C (anti-VHC y ARN positivos): la gravedad de la enfermedad hepática se identifica con el estudio histológico (inflamación y fibrosis)",
  "Hepatitis C",
  ("Gravedad en la hepatitis C", ["La gravedad es el daño del hígado: inflamación y, sobre todo, fibrosis (METAVIR F0-F4).",
                                  "La biopsia es el patrón clásico; hoy se usa primero elastografía o índices (APRI, FIB-4)."]),
  ("Enfermera de 32 años", ["Pinchazo hace 7 meses; ictericia, TGP 3360.", "Anti-VHC y ARN-VHC positivos; biopsia pendiente."]),
  ["Tratar a todos con antivirales de acción directa pangenotípicos (sofosbuvir/velpatasvir 12 semanas).",
   "F4 (cirrosis): ecografía cada 6 meses para cáncer de hígado.",
   "Carga viral: confirma infección activa y la curación (RVS 12)."],
  "AASLD-IDSA, hepatitis C (2023); EASL (2020); OMS (2022).",
  op=("¿Severidad?", ["No: guía el tratamiento", "No: muestra forma, no fibrosis", "No: muestra forma, no fibrosis", "Sí: inflamación y fibrosis", "No: no se relaciona con el daño"]),
  d=dict(rotulo="Qué dice cada prueba en la hepatitis C", ans=3,
         cards=[dict(titulo="Genotipo", datos=[("Dice", "Qué virus es", False), ("Sirve", "Elegir fármaco", False)], pie="Hoy casi no se pide."),
                dict(titulo="Carga viral (ARN)", datos=[("Dice", "Virus activo", False), ("Sirve", "Confirmar y curar", False)], pie="No mide el daño."),
                dict(titulo="TC o resonancia", datos=[("Dice", "Forma del hígado", False), ("Sirve", "Tumor, cirrosis avanzada", False)], pie="No gradúa fibrosis."),
                dict(titulo="Estudio histológico", datos=[("Dice", "Inflamación", True), ("Y", "Fibrosis F0-F4", True)], pie="Gravedad: este caso.")]),
  escala=dict(nombre="Fibrosis hepática (METAVIR)", que="Se mide en la biopsia (o se estima con elastografía).", orden=True,
              grados=[("F0", "Sin fibrosis", ["Hígado sano"]), ("F1", "Portal", ["Leve"]), ("F2", "Con septos", ["Significativa"]),
                      ("F3", "Puentes", ["Avanzada"]), ("F4", "Cirrosis", ["Vigilar cáncer"])],
              caso=-1, porque=[("Biopsia pendiente", True), ("Aguda (7 meses): puede no tener fibrosis aún", True)],
              conducta="Tratar con antivirales; el grado decide el seguimiento."))

# PED-204 · Hernia diafragmática congénita · ALARMA + Rx
S("alarma", "PED-204", "Neonato a término con abdomen excavado que empeora con la ventilación a presión positiva: hernia diafragmática congénita, intubación endotraqueal inmediata",
  "Reanimación neonatal · hernia diafragmática",
  ("Hernia diafragmática congénita", ["Defecto del diafragma (casi siempre izquierdo, de Bochdalek): las asas suben al tórax y el pulmón no se desarrolla.",
                                      "La bolsa y mascarilla llena de aire el intestino del tórax y comprime más el pulmón."]),
  ("Neonato a término", ["Abdomen excavado.", "Empeora pese a la ventilación con bolsa."]),
  ["Intubar y poner sonda orogástrica para descomprimir el intestino.",
   "Ventilación suave (evitar barotrauma); metas de SatO₂ preductal 85-95 %.",
   "Cirugía cuando se estabilice (no es urgente)."],
  AAP + "/" + AHA + ", reanimación neonatal (2025); CDH EURO Consortium (2024).",
  op=("¿Intervención?", ["No: no es lo primero", "No: no hay bradicardia descrita", "Sí: vía aérea sin llenar el intestino", "No: no corrige el problema", "No: no hay indicación"]),
  d=dict(rotulo="Pistas de hernia diafragmática en sala de partos", lista_titulo="Lo que tiene el neonato",
         signos=[("Abdomen excavado", "Sí", True), ("Empeora con bolsa y mascarilla", "Sí", True), ("Dificultad respiratoria", "Sí", True),
                 ("Ruidos intestinales en el tórax", "No se informa", False), ("Latido desplazado a la derecha", "No se informa", False)],
         img=P("hdc.jpg", 220, 263, [], credito="Hellerhoff" + CC + "CC BY-SA 3.0"), img_titulo="Rx: asas en el tórax izquierdo",
         accion=("Intubar + sonda orogástrica", "Nada de bolsa y mascarilla."),
         accion_rotulo="EN SALA DE PARTOS",
         veredicto=("Abdomen excavado + empeora con VPP = hernia diafragmática", "Intubación endotraqueal inmediata.")))

# SP-158 · Salud ocupacional: control de infecciones TB · PIRÁMIDE
S("piramide", "SP-158", "Profesionales recién incorporados a un hospital: la actividad prioritaria es capacitarlos en el control de infecciones respiratorias por tuberculosis",
  "Salud ocupacional · tuberculosis",
  ("Control de infecciones por TB", ["Tres niveles: administrativo (el más importante), ambiental y protección respiratoria.",
                                     "La capacitación del personal es una medida administrativa: va primero."]),
  ("Personal nuevo de un hospital", ["Programa de Salud Ocupacional.", "¿Qué actividad es prioritaria?"]),
  ["Administrativo: capacitación, triaje del tosedor, aislamiento rápido, tamizaje del personal.",
   "Ambiental: ventilación, luz ultravioleta.",
   "Respirador N95 en áreas de riesgo; la mascarilla quirúrgica es para el paciente."],
  OMS + ", control de infecciones por TB (2019); " + MINSA + ", NTS de control de infecciones de TB.",
  op=("¿Prioritaria?", ["No: no se indica a todos", "No: solo si hay infección latente", "No: es para pacientes tratados", "Sí: medida administrativa", "No: no tiene relación"],
      {0: "Prueba molecular con sondas en línea", 1: "Terapia preventiva de TB", 2: "Evaluar reacciones adversas al tratamiento", 3: "Capacitación en control de infecciones TB"}),
  d=dict(rotulo="Jerarquía del control de infecciones por TB", caso=0, tag="ESTE CASO", ancho=400,
         niveles=[("Administrativo", "Lo más eficaz", "Capacitar, triaje, aislar, tamizar."),
                  ("Ambiental", "Diluir el aire", "Ventilación, luz UV."),
                  ("Protección respiratoria", "Última barrera", "Respirador N95.")],
         pie="De lo más a lo menos eficaz",
         veredicto=("Capacitar al personal nuevo en control de infecciones TB", "Es la base de las medidas administrativas.")))

# GIN-215 · Pielonefritis previa en la gestación · CALENDARIO
S("calendario", "GIN-215", "Gestante de 24 semanas con pielonefritis hace 15 días y urocultivo actual negativo: urocultivo mensual hasta el final del embarazo",
  "Infección urinaria en el embarazo",
  ("Seguimiento tras pielonefritis", ["En el embarazo la pielonefritis recurre en 6-8 %: se vigila con urocultivos.",
                                      "Se hace urocultivo de control tras el tratamiento y luego cada mes hasta el parto."]),
  ("Gestante de 24 semanas", ["Hospitalizada por pielonefritis hace 15 días.", "Urocultivo actual negativo."]),
  ["Si un urocultivo sale positivo: tratar y considerar profilaxis nocturna (nitrofurantoína o cefalexina).",
   "Fluoroquinolonas: evitar en la gestación.",
   "Bacteriuria asintomática: siempre se trata en la gestante."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ".",
  op=("¿Conducta?", ["No: no previenen", "Sí: detecta la recurrencia", "No: se evita en la gestación", "No: necesita control urinario", "No: no hay infección que tratar"]),
  d=dict(rotulo="Cuándo pedir urocultivo", tag="CADA MES",
         edades=["24 sem (hoy)", "28 sem", "32 sem", "36 sem", "Parto"], caso_col=0, titulo_filas="Seguimiento",
         filas=[("Urocultivo", {0: ("Negativo", "dada"), 1: ("Repetir", "prog"), 2: ("Repetir", "prog"), 3: ("Repetir", "prog")}, "Detecta la recurrencia antes de los síntomas."),
                ("Profilaxis", {1: ("Si recurre", "prog")}, "Nitrofurantoína o cefalexina nocturna.")],
         leyenda="✓ hecho · ○ programado",
         veredicto=("Urocultivo mensual hasta el parto", "Y tratar cualquier bacteriuria.")))

# PED-205 · Síntesis de surfactante · BALANZA
S("balanza", "PED-205", "Prematuro de 28 semanas con enfermedad de membrana hialina: la hipovolemia inhibe la síntesis de surfactante",
  "Neonatología · surfactante",
  ("Surfactante pulmonar", ["Lo fabrican los neumocitos tipo II desde la semana 24; madura hacia las 34-36.",
                            "Su producción baja con hipovolemia, hipoxia, acidosis e hipotermia, y con la hiperinsulinemia (madre diabética)."]),
  ("Prematuro de 28 semanas", ["Enfermedad de membrana hialina.", "¿Qué inhibe el surfactante?"]),
  ["Corticoides prenatales (24-34 sem): aceleran la maduración pulmonar.",
   "Mantener volemia, temperatura y oxigenación cuida la producción de surfactante.",
   "Surfactante exógeno y CPAP en la membrana hialina."],
  NELSON + "; consenso europeo de distrés respiratorio (2022).",
  op=("¿Qué la inhibe?", ["No: la estimulan", "Sí: mala perfusión pulmonar", "No: el frío la inhibe", "No: no tiene relación", "No: no tiene relación"]),
  d=dict(rotulo="Qué sube y qué baja el surfactante", gana="der", pregunta="¿Qué lo inhibe?",
         izq=dict(titulo="Lo estimulan", peso="+", items=["Corticoides prenatales", "Estrés crónico (HTA, RPM)", "Hormona tiroidea"]),
         der=dict(titulo="Lo inhiben", peso="−", items=["Hipovolemia (este caso)", "Hipoxia y acidosis", "Hipotermia; hiperinsulinemia"]),
         veredicto=("La hipovolemia inhibe la síntesis", ["Mantener volemia, temperatura y oxígeno."])))

# CIR-112 · Hemotórax traumático · ÁRBOL + Rx antes y después
S("arbol", "CIR-112", "Accidente con fracturas costales derechas, MV abolido y Rx con opacidad de 2/3 del hemitórax derecho: hemotórax, drenaje pleural",
  "Trauma torácico · hemotórax",
  ("Hemotórax traumático", ["Sangre en la pleura: MV abolido, matidez y opacidad en la Rx (o líquido en la eco FAST).",
                            "Tratamiento inicial: tubo de tórax; mide cuánto sangra y decide si hace falta cirugía."]),
  ("Mujer de 25 años, accidente", ["PA 90/60, FC 112, SatO₂ 90 %, pálida.", "Crujido en 5.º-6.º arcos derechos; Rx: opacidad de 2/3 del HTD."]),
  ["Tubo de tórax 28-32 Fr en el 5.º espacio, línea axilar media (ATLS 11: tubos más finos también sirven).",
   "Toracotomía si sale > 1500 mL al inicio o > 200 mL/h por 2-4 h.",
   "Reanimar en paralelo; la toracocentesis con aguja no evacua la sangre."],
  ATLS + "; EAST, hemotórax (2024).",
  op=("¿Tratamiento?", ["No: no drena", "No: no hay taponamiento", "Sí: evacua y mide el sangrado", "No: solo si es masivo", "No: no evacua la sangre"]),
  arbol=Q("Trauma torácico con MV abolido: ¿qué muestra la Rx?", [
      L("Opacidad (este caso)", "HEMOTÓRAX: DRENAJE PLEURAL", ["Tubo de tórax", "Medir lo que sale"], path=True),
      L("Hiperclaridad y desviación", "Neumotórax a tensión", ["Descompresión y tubo"]),
      L("> 1500 mL o > 200 mL/h", "Hemotórax masivo", ["Toracotomía"])], path=True),
  escala=dict(nombre="Tamaño del hemotórax (uso clínico, ATLS)", que="Por la Rx y por lo que drena el tubo.", orden=True,
              grados=[("< 300 mL", "Pequeño", ["Borra el ángulo costofrénico", "Puede observarse"]),
                      ("300-1500 mL", "Moderado", ["Opacidad de parte del hemitórax", "Tubo de tórax"]),
                      ("> 1500 mL", "Masivo", ["O > 200 mL/h", "Toracotomía"])],
              caso=1, porque=[("Opacidad de 2/3 inferiores", True), ("Inestable: drenar ya y medir", True)],
              conducta="Drenaje pleural; si sale > 1500 mL, toracotomía."),
  banda=B("Hemotórax antes y después del tubo", DOS(P("hemotorax_a.jpg", 220, 219, [], credito="Abdalrahman et al. · PMC13536977 · CC BY 4.0"),
                                                    P("hemotorax_b.jpg", 220, 220, [], credito="Abdalrahman et al. · PMC13536977 · CC BY 4.0")),
          [("Izquierda: nivel de líquido", "Sangre y aire en el lado derecho."), ("Derecha: con el tubo", "El pulmón vuelve a expandirse."),
           ("Otra paciente", "Mismo tratamiento.")],
          pie="Hemoneumotórax traumático (PubMed Central)."))

# GIN-216 · VIH en el parto: suprimir la lactancia · CHECKLIST
S("checklist", "GIN-216", "Puérpera por cesárea con VIH diagnosticado en esta gestación (escenario 3): suprimir la lactancia con cabergolina y vendaje de mamas inmediatamente",
  "VIH y embarazo · lactancia",
  ("VIH en el parto (Perú)", ["La transmisión por la leche es real: en el Perú se indica no amamantar y dar fórmula gratuita.",
                              "La lactancia se inhibe apenas nace el bebé, antes de que suba la leche."]),
  ("Puérpera inmediata", ["Cesárea; VIH en escenario 3 en esta gestación.", "¿Qué hacer con la lactancia?"]),
  ["Cabergolina (MINSA: 0,5 mg c/12 h, 2 dosis; OMS: 1 mg única) en el posparto inmediato.",
   "Vendaje de mamas ~15 días; fórmula para el bebé.",
   "Profilaxis antirretroviral al recién nacido y TAR a la madre de por vida."],
  MINSA + ", NTS de prevención de la transmisión materno-infantil del VIH (2019; act.); " + OMS + ".",
  op=("¿Conducta?", ["No: transmite el VIH", "Sí: suprime la leche ya", "No: no suprime la lactancia", "No: no se usa y es tarde", "No: en el Perú se suprime"],
      {0: "Sin contraindicación para la lactancia", 1: "Cabergolina + vendaje inmediato", 2: "Medroxiprogesterona a las 72 h", 3: "Mifepristona + vendaje a las 48 h"}),
  d=dict(rotulo="Qué hacer tras el parto", tag="INMEDIATO",
         pasos=[("Cabergolina en el posparto inmediato", "Inhibe la prolactina", True), ("Vendaje compresivo de mamas", "Ayuda a suprimir", True),
                ("Fórmula para el bebé", "Lactancia artificial", False), ("Profilaxis al RN y TAR a la madre", "Según riesgo", False)],
         no_hacer=[("Lactancia materna", "Transmite el VIH"), ("Lactancia mixta", "El mayor riesgo"), ("Esperar 48-72 h", "La leche ya bajó")],
         veredicto=("Cabergolina y vendaje de mamas de inmediato", "Y fórmula para el recién nacido.")))

# NEU-063 · Neumonía adquirida en la comunidad · GRADOS CON FOTO (Rx que se confunden)
S("grados_foto", "NEU-063", "Fiebre, tos y disnea de 6 días con crepitantes y opacidad en el hemitórax izquierdo: neumonía adquirida en la comunidad",
  "Neumonía · diagnóstico",
  ("Neumonía adquirida en la comunidad", ["Infección del parénquima: fiebre, tos, disnea y crepitantes con una opacidad nueva en la Rx.",
                                          "Lo agudo (días) y la fiebre la separan de la atelectasia, el edema y la tuberculosis."]),
  ("Mujer de 45 años, 6 días", ["Fiebre, tos y dificultad respiratoria.", "PA 100/60, FR 28; crepitantes y opacidad en el HTI."]),
  ["Gravedad con CURB-65 y juicio clínico; la FR 28 y la disnea se vigilan.",
   "Ambulatoria sin comorbilidad: amoxicilina (o macrólido/doxiciclina).",
   "Control clínico en 48-72 h."],
  "ATS/IDSA, neumonía de la comunidad (2019; act. 2025); BTS.",
  op=("¿Diagnóstico?", ["No: necesita derrame infectado", "No: es crónica (semanas)", "Sí: aguda con fiebre y crepitantes", "No: sin fiebre; volumen pequeño", "No: bilateral, con cardiopatía"]),
  d=dict(rotulo="Opacidades que se confunden",
         criterio="Las cuatro dan blanco en la Rx; la clínica del caso (fiebre aguda + crepitantes) apunta a la primera.",
         grados=[("1", "Neumonía", "Fiebre aguda, crepitantes", P("neumonia_lii.jpg", 288, 258), True),
                 ("2", "Atelectasia", "Pierde volumen, sin fiebre", P("atelectasia_rx.jpg", 300, 246), False),
                 ("3", "Edema agudo", "Bilateral, cardiópata", P("edema_ap.jpg", 300, 240), False),
                 ("4", "Tuberculosis", "Semanas, cavidad apical", P("tb_cavitaria.jpg", 300, 275), False)],
         credito="Heilman · CC BY 3.0 | Pabloes · CC BY-SA 3.0 | Gaillard y Jones · CC BY-SA 3.0 | CDC · dominio público (Commons)",
         veredicto=("Fiebre + crepitantes + opacidad nueva = neumonía", "Calcular CURB-65 y tratar.")),
  escala=dict(nombre="Gravedad de la neumonía (CURB-65)", que="1 punto: confusión, urea > 42 mg/dL, FR ≥ 30, PA < 90/≤ 60, edad ≥ 65.", orden=True,
              grados=[("0-1", "Leve", ["Ambulatorio"]), ("2", "Moderada", ["Hospitalizar"]), ("3-5", "Grave", ["UCI"])],
              caso=0, porque=[("PA diastólica 60: 1 punto", True), ("FR 28, 45 años, sin confusión; urea por pedir", True)],
              conducta="Si la urea es normal, ambulatorio con control en 48-72 h."))

# PED-206 · Plan C en el menor de 12 meses · DOSIS
S("dosis", "PED-206", "Lactante de 7 meses con deshidratación grave por diarrea, después de tratar el shock: Lactato de Ringer 30 mL/kg en 1 hora y 70 mL/kg en 5 horas",
  "Diarrea aguda · plan C",
  ("Plan C (OMS/MINSA)", ["Deshidratación grave: 100 mL/kg EV de Lactato de Ringer (o salino) en dos partes.",
                          "< 12 meses: 30 mL/kg en 1 h y 70 mL/kg en 5 h. ≥ 12 meses: 30 mL/kg en 30 min y 70 mL/kg en 2½ h."]),
  ("Lactante de 7 meses", ["Diarrea y vómitos; letárgico, no succiona.", "Ojos muy hundidos, pliegue lento. Ya se trató el shock."]),
  ["Reevaluar cada 1-2 h; si no mejora, acelerar el goteo.",
   "Apenas pueda beber, SRO 5 mL/kg/h.",
   "Desnutrido grave: otro esquema, más lento."],
  OMS + ", tratamiento de la diarrea; " + MINSA + ", guía de EDA en niños (2017).",
  op=("¿Indicación?", ["No: orden y tiempos al revés", "No: son bolos del shock", "No: tiempo de ≥ 12 meses", "Sí: < 12 meses", "No: está letárgico"],
      {0: "NaCl 70 mL/kg en 1 h + 30 mL/kg en 3 h", 1: "NaCl 10 mL/kg, repetir 2 veces", 2: "Ringer 30 mL/kg en 0,5 h + 70 mL/kg en 2,5 h", 3: "Ringer 30 mL/kg en 1 h + 70 mL/kg en 5 h"}),
  d=dict(rotulo="Calcula el plan C", peso=("8 kg", "Lactante de 7 meses"), peso_titulo="PESO DE EJEMPLO",
         pasos=[("1.ª hora", "30 mL/kg", "= 240 mL"), ("Siguientes 5 h", "70 mL/kg", "= 560 mL"), ("Total en 6 h", "100 mL/kg", "= 800 mL")],
         ops=["+", "="],
         alt_titulo="Esquemas del plan C",
         alternativas=[("30 en 1 h + 70 en 5 h", "< 12 meses: este caso", True), ("30 en 30 min + 70 en 2½ h", "≥ 12 meses", False),
                       ("Bolos de 10-20 mL/kg", "Para el shock", False), ("70 en 1 h + 30 en 3 h", "Al revés", False)],
         veredicto=("Ringer 30 mL/kg en 1 h y 70 mL/kg en 5 h", "Por ser menor de 12 meses.")),
  escala=dict(nombre="Clasificación de la deshidratación (AIEPI)", que="Dos o más signos de la fila deciden el plan.", orden=True,
              grados=[("Plan A", "Sin deshidratación", ["Alerta, bebe normal"]),
                      ("Plan B", "Algún grado", ["Inquieto, ojos hundidos", "Bebe ávido, pliegue lento"]),
                      ("Plan C", "Grave", ["Letárgico, ojos muy hundidos", "No puede beber, pliegue muy lento"])],
              caso=2, porque=[("Letárgico, mala succión", True), ("Ojos muy hundidos", True)],
              conducta="Fluidos EV del plan C según la edad."))

# GIN-217 · Pérdida gestacional temprana · REGLA + formas del aborto
S("regla", "GIN-217", "Ecografía con embrión de 8 mm sin latido y saco de 29 mm: pérdida gestacional temprana (aborto retenido), tratamiento con misoprostol",
  "Aborto · pérdida gestacional temprana",
  ("Criterios de pérdida gestacional", ["Embrión con LCC ≥ 7 mm sin latido, o saco gestacional medio ≥ 25 mm sin embrión: diagnóstico seguro.",
                                        "Por debajo de esos cortes es dudoso: se repite la ecografía en 7-14 días."]),
  ("Gestante de 35 años, 7 semanas", ["Dolor pélvico y sangrado escaso; cuello cerrado.", "Eco: saco 29 mm, embrión de 8 mm sin latido."]),
  ["Opciones: misoprostol, aspiración (AMEU) o esperar; con la paciente estable, misoprostol.",
   "Mifepristona + misoprostol funciona mejor donde está disponible.",
   "Rh negativo: valorar anti-D."],
  "SRU (Doubilet, 2013); " + ACOG + " n.º 200 (2018; act.); " + MINSA + ".",
  op=("¿Conducta?", ["Sí: pérdida confirmada", "No: el diagnóstico ya es seguro", "Es opción, no la mejor", "No: ya cumple criterios", "No: no hay embrión vivo"]),
  d=dict(rotulo="Las dos medidas de la ecografía",
         reglas=[dict(nombre="Longitud del embrión (LCC, mm)", que="Embrión de 8 mm sin latido.", min=0, max=12, fmt="{}", ticks=[7],
                      bandas=[(0, 7, "Dudoso: repetir eco", 1), (7, 12, "Sin latido = pérdida", 3)], caso=8, caso_txt="8 mm"),
                 dict(nombre="Saco gestacional medio (mm)", que="29 mm (aquí sí hay embrión).", min=0, max=35, fmt="{}", ticks=[16, 25],
                      bandas=[(0, 16, "Temprano", 0), (16, 25, "Dudoso", 1), (25, 35, "Sin embrión = pérdida", 3)], caso=29, caso_txt="29 mm")],
         claves_titulo="Qué se hace",
         claves=[("LCC ≥ 7 mm sin latido", ["Pérdida confirmada"], True), ("Misoprostol o AMEU", ["Según preferencia y sangrado"], True),
                 ("Repetir eco", ["Solo si es dudoso"], False)]),
  escala=ABORTO(4, [("Cuello cerrado", True), ("Embrión sin latido", True), ("Sin expulsión", True)],
                "Misoprostol (o AMEU si sangra mucho o lo prefiere)."))

# CIR-113 · Colecistitis aguda · CRITERIOS DE TOKIO + eco
S("criterios", "CIR-113", "Joven con dolor en HCD de 48 h, Murphy positivo, leucocitosis y eco con pared gruesa y cálculo en el bacinete: colecistitis aguda, colecistectomía laparoscópica",
  "Patología biliar · colecistitis",
  ("Colecistitis aguda (Tokio 2018)", ["Diagnóstico: un signo local (A) + uno sistémico (B) + imagen típica (C).",
                                       "Tratamiento de elección: colecistectomía laparoscópica temprana (idealmente < 72 h)."]),
  ("Mujer de 25 años", ["Dolor en HCD 48 h tras comer; manga gástrica hace 2 años.", "Murphy (+), leucocitos 12 000; eco: pared gruesa, cálculo en el bacinete."]),
  ["Antibiótico y analgesia mientras se programa la cirugía.",
   "Colecistostomía percutánea: solo si es muy grave o no tolera la cirugía.",
   "La pérdida rápida de peso (cirugía bariátrica) favorece los cálculos."],
  "Guías de Tokio 2018 (TG18); WSES (2020); " + SABISTON + ".",
  op=("¿Tratamiento?", ["No: solo si no tolera cirugía", "No: no se usa", "Sí: temprana y menos invasiva", "No: más dolor y estancia", "No: es para el colédoco"]),
  d=dict(rotulo="Criterios diagnósticos de Tokio 2018", lista_titulo="Lo que tiene ella",
         items=[("A. Signo local: Murphy o dolor en HCD", True, "Murphy (+)"), ("B. Signo sistémico: fiebre, PCR o leucocitos", True, "12 000"),
                ("C. Imagen: pared gruesa, cálculo, líquido", True, "Eco típica")],
         umbral="A + B + C = colecistitis aguda definida",
         veredicto="Colecistitis aguda: colecistectomía laparoscópica temprana.",
         img=P("colecistitis_eco.jpg", 210, 262, [], credito="Cerevisae" + CC + "CC BY-SA 4.0"), img_titulo="Ecografía de colecistitis",
         img_pie="Las líneas señalan la pared y el cálculo.", conteo="3 de 3"),
  escala=dict(nombre="Gravedad (Tokio 2018)", que="Decide el momento y el tipo de cirugía.", orden=True,
              grados=[("Grado I", "Leve", ["Sin criterios de II ni III"]),
                      ("Grado II", "Moderada", ["Masa palpable, > 72 h", "Leucocitos > 18 000"]),
                      ("Grado III", "Grave", ["Falla de un órgano"])],
              caso=0, porque=[("48 h, leucocitos 12 000", True), ("Sin masa ni falla de órganos", True)],
              conducta="Colecistectomía laparoscópica temprana."))

# TRA-046 · Luxación anterior de hombro · LECTURA + Rx
S("lectura", "TRA-046", "Joven con caída sobre la mano, dolor, impotencia funcional y signo de la charretera: luxación anterior de hombro, reducción cerrada por tracción",
  "Traumatología · hombro",
  ("Luxación anterior de hombro", ["La más frecuente (> 95 %): la cabeza del húmero sale hacia adelante y abajo de la glenoide.",
                                   "Signo de la charretera: el acromion queda saliente porque falta la cabeza humeral debajo."]),
  ("Varón de 20 años", ["Caída sobre la mano derecha en extensión.", "Dolor, impotencia funcional, signo de la charretera."]),
  ["Rx antes (y después) de reducir: descartar fractura.",
   "Revisar el nervio axilar (sensibilidad del deltoides) antes y después.",
   "Cabestrillo corto y rehabilitación; en jóvenes recidiva mucho."],
  "AAOS; Rockwood y Green, Fracturas en el adulto 9.ª ed.",
  op=("¿Tratamiento?", ["No: no hay fractura", "Sí: reducción cerrada", "No: es para la clavícula", "No: no hay fractura", "No: no hay fractura"]),
  d=dict(rotulo="Lee la radiografía", img_titulo="Luxación anterior (otra persona)",
         img=P("luxacion_hombro.jpg", 230, 294, credito="Mikael Häggström" + CC + "CC0"), pines=[(0.6, 0.48)],
         pasos=[("Cabeza humeral fuera de la glenoide", "Abajo del coracoides.", True),
                ("Sin fractura asociada", "Si la hay, puede cambiar el manejo.", False),
                ("Reducción por tracción-contratracción", "Con analgesia o sedación.", True),
                ("Inmovilizar y rehabilitar", "Cabestrillo 1-3 semanas.", False)],
         img_pie="Hombro izquierdo, antes de reducir.",
         veredicto=("Charretera tras caída = luxación anterior", "Reducción cerrada por tracción.")),
  triada=TR([("Signo de la charretera", "Sí", True), ("Impotencia funcional", "Sí", True), ("Brazo en abducción y rotación externa", "No se informa", False)],
            [("Signos de luxación anterior", 0, 2)], "Revisar el nervio axilar antes y después."))

# CAR-067 · RCP de calidad · REGLA
S("regla", "CAR-067", "Paciente en paro sin pulso: las compresiones de calidad son de al menos 5 cm (sin pasar de 6) y a 100-120 por minuto",
  "Reanimación · RCP de calidad",
  ("RCP de alta calidad (adulto)", ["Profundidad 5-6 cm y frecuencia 100-120/min, dejando que el tórax vuelva a subir.",
                                    "Interrupciones < 10 s; 30:2 sin vía aérea avanzada; cambiar de reanimador cada 2 min."]),
  ("Varón de 50 años", ["Dolor torácico; deja de respirar y no tiene pulso carotídeo.", "Se inicia RCP de inmediato."]),
  ["Manos en la mitad inferior del esternón, brazos rectos.",
   "No apoyarse en el tórax entre compresiones.",
   "Desfibrilar apenas haya DEA si el ritmo es FV o TV sin pulso."],
  AHA + "; ERC (2025).",
  op=("¿Calidad?", ["No: poco profundas", "No: muy profundas y lentas", "No: muy lentas", "Sí: 5 cm y 100-120/min", "No: poco profundas y muy rápidas"],
      {0: "4 cm · 100-120/min", 1: "6 cm · 80-90/min", 2: "5 cm · 80-100/min", 3: "5 cm · 100-120/min", 4: "3 cm · 120-140/min"}),
  d=dict(rotulo="Las dos medidas de la compresión",
         reglas=[dict(nombre="Profundidad (cm)", que="Al menos 5 cm, sin pasar de 6.", min=2, max=8, fmt="{}", ticks=[5, 6],
                      bandas=[(2, 5, "Poco profunda", 2), (5, 6, "5-6 cm", 0), (6, 8, "Excesiva", 2)], caso=5.5, caso_txt="Meta"),
                 dict(nombre="Frecuencia (por minuto)", que="100 a 120 compresiones por minuto.", min=60, max=150, fmt="{}", ticks=[100, 120],
                      bandas=[(60, 100, "Lenta", 2), (100, 120, "100-120", 0), (120, 150, "Rápida", 2)], caso=110, caso_txt="Meta")],
         claves_titulo="Además",
         claves=[("Reexpansión completa", ["No apoyarse"], True), ("Pausas < 10 s", ["Solo para descargar"], True), ("30:2", ["Sin vía aérea avanzada"], False)]))

# GIN-218 · Mecanismo del parto · FASES + estaciones
S("fases", "GIN-218", "Dilatación completa, presentación en +3 y occipucio ya anterior: la rotación interna ocurrió y el siguiente movimiento cardinal es la extensión",
  "Parto · mecanismo del parto",
  ("Movimientos cardinales del parto", ["Encajamiento → descenso → flexión → rotación interna → extensión → rotación externa (restitución) → expulsión.",
                                        "La extensión ocurre cuando el occipucio llega bajo la sínfisis del pubis."]),
  ("Primigesta de 39 semanas", ["10 cm, 100 %, estación +3, membranas rotas.", "Presentación occipitoanterior: ya rotó."]),
  ["La cabeza sale por extensión: occipucio, frente, cara y mentón.",
   "Luego restitución y rotación externa para que salgan los hombros.",
   "Protección del periné durante la extensión."],
  WILLIAMS + ".",
  op=("¿Siguiente?", ["No: es tras la extensión", "No: es tras la extensión", "No: ya ocurrió (OA)", "Sí: bajo la sínfisis", "No: es al inicio"]),
  d=dict(rotulo="Movimientos cardinales del parto", ans=3,
         fases=[("Encaja y desciende", "1-2", "ENCAJAMIENTO Y DESCENSO", ["Entra en la pelvis"]),
                ("Flexión", "3", "FLEXIÓN", ["Mentón al pecho"]),
                ("Rotación interna", "4", "ROTACIÓN INTERNA", ["Occipucio al pubis", "Ya ocurrió"]),
                ("Extensión", "5", "EXTENSIÓN", ["Bajo la sínfisis", "Lo siguiente"]),
                ("Rotación externa", "6-7", "RESTITUCIÓN Y EXPULSIÓN", ["Salen los hombros"])]),
  escala=dict(nombre="Altura de la presentación (estaciones de DeLee)", que="En cm respecto a las espinas ciáticas.", orden=True,
              grados=[("−3 a −1", "Alta", ["Sobre las espinas"]), ("0", "Encajada", ["A nivel de las espinas"]), ("+1 a +3", "Baja", ["Bajo las espinas; +3 en el periné"])],
              caso=2, porque=[("Estación +3", True), ("Occipucio ya anterior: rotó", True)],
              conducta="Sigue la extensión: pujo dirigido y protección del periné."))

# NRL-053 · Escala de Glasgow · PUNTAJE + posturas
S("puntaje", "NRL-053", "Caída de un 4.º piso: abre los ojos al dolor (2), sonidos incomprensibles (2) y flexión anormal (3): Glasgow 7, TEC grave",
  "Trauma craneoencefálico · Glasgow",
  ("Escala de Glasgow", ["Suma de ocular (1-4), verbal (1-5) y motor (1-6): de 3 a 15.",
                         "Motor: obedece 6, localiza 5, retira 4, flexión anormal (decorticación) 3, extensión 2, nada 1."]),
  ("Varón de 33 años", ["Caída de un 4.º piso; PA 90/50, FC 120.", "Abre al dolor, sonidos incomprensibles, postura en flexión."]),
  ["Glasgow ≤ 8: asegurar la vía aérea (intubar).",
   "Evitar hipotensión e hipoxia: empeoran el daño cerebral.",
   "TC de cráneo urgente y neurocirugía."],
  ATLS + "; Brain Trauma Foundation (2016).",
  op=("¿Glasgow?", ["No: suma 7", "No: suma 7", "No: suma 7", "Sí: 2 + 2 + 3", "No: la flexión anormal vale 3"]),
  d=dict(rotulo="Glasgow punto por punto", escala="Glasgow", total=7, max=15,
         interpreta="≤ 8: TEC grave",
         items=[("Ocular: abre al dolor", 2, True), ("Verbal: sonidos incomprensibles", 2, True), ("Motor: flexión anormal", 3, True)],
         bandas=[("13-15", "Leve", "Observar; TC si hay riesgo.", False), ("9-12", "Moderado", "TC y hospitalizar.", False),
                 ("3-8", "Grave", "Intubar, TC, neurocirugía.", True)]),
  banda=B("Las posturas anormales", P("dib_posturas.jpg", 330, 264, [], credito=PROPIO, fondo="#ffffff"),
          [("Decorticación = 3", "Brazos doblados sobre el pecho: este caso."),
           ("Descerebración = 2", "Brazos extendidos y rotados."),
           ("Retirada = 4", "Aparta el miembro del dolor (no es postura).")],
          pie="Esquema."))

# SP-159 · Mala praxis: impericia · RADIAL
S("radial", "SP-159", "Médico no especialista que en una cesárea electiva perfora la vejiga: mala praxis por impericia",
  "Responsabilidad médica · mala praxis",
  ("Formas de la culpa médica", ["Impericia: falta de saber o destreza. Imprudencia: hacer de más sin cautela.",
                                 "Negligencia: dejar de hacer lo debido. Inobservancia: no cumplir normas o reglamentos."]),
  ("Primigesta de 32 años", ["Cesárea electiva hecha por un médico no especialista.", "Perforación de la vejiga en la operación."]),
  ["Actuar fuera de la propia competencia es la imagen típica de la impericia.",
   "Caso fortuito: daño imprevisible pese a hacer todo bien (no hay culpa).",
   "La historia clínica y el consentimiento informado son la defensa del médico."],
  "Código Penal peruano (art. 111 y 124); Ley General de Salud 26842; Colegio Médico del Perú, Código de ética.",
  op=("¿Tipo?", ["No: es hacer de más", "No: es no cumplir normas", "Sí: falta de destreza", "No: es omitir", "No: había culpa"]),
  d=dict(rotulo="Las formas de la mala praxis", centro="MALA PRAXIS", centro_sub="culpa", ans=0,
         items=[("IMPERICIA", ["Falta de saber o destreza", "Este caso"]), ("IMPRUDENCIA", ["Hacer de más sin cautela"]),
                ("NEGLIGENCIA", ["Omitir lo debido"]), ("INOBSERVANCIA", ["No cumplir normas"])],
         ruta=["No especialista", "Opera una cesárea", "Perfora la vejiga", "Impericia"]))

# CB-076 · Ejercicio prolongado: gluconeogénesis · GRÁFICA
S("grafica", "CB-076", "Maratonista en ejercicio aeróbico prolongado: en el hígado se activa la gluconeogénesis cuando se agota el glucógeno",
  "Bioquímica · metabolismo en el ejercicio",
  ("Glucosa en el ejercicio prolongado", ["Al inicio el hígado libera glucosa desde su glucógeno (glucogenólisis).",
                                          "Al agotarse, la fabrica desde lactato, alanina y glicerol (gluconeogénesis), impulsada por glucagón alto e insulina baja."]),
  ("Maratonista", ["Ejercicio aeróbico prolongado.", "¿Qué pasa en el hígado?"]),
  ["Ciclo de Cori: lactato del músculo → glucosa en el hígado.",
   "Ciclo glucosa-alanina: aminoácidos del músculo como fuente.",
   "Se apagan la síntesis de glucógeno y la lipogénesis (insulina baja)."],
  GUYTON + "; Lehninger, Principios de bioquímica 8.ª ed.",
  op=("¿Efecto en el hígado?", ["Sí: fabrica glucosa", "No: el músculo la aumenta", "No: al inicio aumenta", "No: la insulina está baja", "No: la insulina está baja"]),
  d=dict(rotulo="De dónde sale la glucosa del hígado", eje_x="Tiempo de ejercicio (min)", eje_y="Aporte (%)",
         x=(0, 180, [(0, "0"), (60, "60"), (120, "120"), (180, "180")]),
         y=(0, 100, [(0, "0"), (50, "50"), (100, "100")]),
         series=[("Glucogenólisis", [(0, 80), (40, 70), (80, 50), (120, 35), (180, 20)], "#94a3b8"),
                 ("Gluconeogénesis", [(0, 20), (40, 30), (80, 50), (120, 65), (180, 80)], "#f97316")],
         zonas=[(90, 180, "ejercicio prolongado", "#ffedd5")],
         caso=(120, 65, "maratón"),
         notas=[("Glucagón ↑, insulina ↓", "Encienden la gluconeogénesis.", True),
                ("Lactato, alanina, glicerol", "Materia prima.", True),
                ("Glucogenogénesis y lipogénesis", "Se apagan.", False)],
         veredicto=("Activación de la gluconeogénesis", "Mantiene la glucosa cuando falta glucógeno.")))

# TRA-047 · Hemorragia aguda: primero taquicardia · TERMÓMETRO (clases ATLS)
S("termometro", "TRA-047", "Politraumatizado con sangrado activo en las piernas: la primera alteración fisiológica de la hemorragia es el aumento de la frecuencia cardiaca",
  "Shock hemorrágico",
  ("Clases de hemorragia (ATLS)", ["Lo primero que cambia es la frecuencia cardiaca (catecolaminas); la PA sistólica baja tarde (clase III).",
                                   "La presión de pulso se estrecha, no se amplía."]),
  ("Varón de 33 años, accidente", ["Confuso; laceraciones y hematomas.", "Sangrado en las piernas pese a la presión firme."]),
  ["Torniquete si la presión directa no controla el sangrado de un miembro.",
   "Ácido tranexámico en < 3 h; transfusión 1:1:1 si es masiva.",
   "No esperar la hipotensión para reanimar."],
  ATLS + ".",
  op=("¿Primera?", ["No: se estrecha", "Sí: lo primero", "Ocurre, pero después", "Es más tardía", "No: baja (tarde)"]),
  d=dict(rotulo="Clases de hemorragia (ATLS)", caso_nivel=1, ruta_titulo="Cómo compensa el cuerpo", paso_label="PRIMERO",
         niveles=[("I", "< 15 %", ["Signos casi normales"]), ("II", "15-30 %", ["FC ↑, presión de pulso ↓"]),
                  ("III", "31-40 %", ["PA sistólica ↓, confuso"]), ("IV", "> 40 %", ["Hipotensión grave, letargo"])],
         pasos=[(1, "Sube la frecuencia cardiaca", ["Catecolaminas"], True),
                (2, "Vasoconstricción", ["Piel fría, llenado lento"], False),
                (3, "Baja la diuresis", ["Riñón ahorra agua"], False),
                (4, "Cae la PA sistólica", ["Signo tardío"], False)]))

# PED-207 · Lactante con VIH: TAR precoz · CRONOLOGÍA
S("cronologia", "PED-207", "Lactante de 2 meses con VIH recién diagnosticado: iniciar terapia antirretroviral de inmediato, sin esperar síntomas ni CD4",
  "VIH pediátrico",
  ("VIH en el lactante", ["Diagnóstico con prueba virológica (PCR) desde el nacimiento; los anticuerpos maternos duran hasta los 18 meses.",
                          "Todo niño con VIH inicia TAR apenas se diagnostica: el lactante progresa muy rápido."]),
  ("Lactante de 2 meses", ["VIH diagnosticado.", "Se deriva al infectólogo pediatra."]),
  ["TAR inicial del lactante: basado en dolutegravir (dosis por peso) según OMS 2021.",
   "CD4 y carga viral sirven para el seguimiento, no para decidir el inicio.",
   "Profilaxis con cotrimoxazol desde las 6 semanas."],
  OMS + ", guías consolidadas de VIH (2021; act. 2025); " + MINSA + ", NTS de VIH pediátrico.",
  op=("¿Para?", ["Sí: todos los lactantes", "No: no decide el inicio", "No: progresa rápido", "No: demasiado tarde", "No: ya está diagnosticado"]),
  d=dict(rotulo="El lactante con VIH en el tiempo", tag="2 MESES",
         ilu_titulo="El lactante",
         ilu=ILU(D(lambda s, x, y: I.bebe(s, x + 60, y, sc=0.85), 330, 285)),
         ilu_pie="2 meses con VIH confirmado.",
         claves=[("TAR ya", ["Sin esperar síntomas ni CD4"], True), ("PCR para diagnosticar", ["No ELISA antes de 18 meses"], False),
                 ("Cotrimoxazol", ["Desde las 6 semanas"], False)],
         eje_titulo="Meses de vida", eje=(0, 18), paso=3, marca=2, unidad="m", eje_nombre="meses de edad",
         hitos=[(0, 2, "PCR al nacer y al mes", "diagnóstico", False), (2, 3, "TAR", "de inmediato", True),
                (3, 18, "TAR y controles", "carga viral, CD4", False)]))
