"""Bloque 6 · parte M."""
from c6 import F6, Q, L, A, V, NELSON, ATLS, ROSE, VIOLET, SKY, AMBER

WILLIAMS = "Williams Obstetrics 26.ª ed. (2022)"
HARRISON = "Harrison's Principles of Internal Medicine 22.ª ed. (2025)"
GOODMAN = "Goodman & Gilman – Las bases farmacológicas de la terapéutica 14.ª ed. (2023)"

# SP-099 · radial
V("radial", "SP-099", "parasitosis-sin-saneamiento-solo-medicamento-biomedico", "Modelos de intervención en salud",
  "SALUD PÚBLICA ENAM: MODELO BIOMÉDICO", "SALUD PÚBLICA",
  ("Modelo biomédico", ["Se centra en la enfermedad y su tratamiento farmacológico",
   "No actúa sobre los determinantes (agua, desagüe)"]),
  ("Población sin agua ni desagüe", ["Más enteroparasitosis en menores de 3 años", "Solo se indica el medicamento, no el saneamiento"]),
  {"rotulo": "Mapa del tema", "centro": "MODELOS", "centro_sub": "De intervención", "ans": 0,
   "items": [("BIOMÉDICO", ["Enfermedad y fármaco", "Ignora el entorno"]),
             ("Conductual", ["Cambiar hábitos"]),
             ("Participativo", ["La comunidad decide"]),
             ("Comunitario", ["Acción colectiva"]),
             ("Determinantes", ["Agua, desagüe, vivienda"])],
   "ruta": ["Parasitosis sin saneamiento", "Se da el antiparasitario", "No se toca el entorno", "BIOMÉDICO"]},
  ["Sin agua segura, la reinfección es casi segura.",
   "El enfoque de determinantes sociales es el más eficaz a largo plazo.",
   "Desparasitación masiva: complemento, no solución."],
  "OMS – Comisión sobre determinantes sociales de la salud (2008) · MINSA – Modelo de Cuidado Integral (2020)")

# SP-100 · fases
V("fases", "SP-100", "victima-violencia-sexual-atencion-medica-primero", "Atención a víctima de violencia sexual",
  "SALUD PÚBLICA ENAM: VIOLENCIA SEXUAL", "SALUD PÚBLICA",
  ("Atención de la violencia sexual", ["Lo primero es la atención médica y la estabilización",
   "Luego kit de emergencia, registro y denuncia"]),
  ("Mujer de 32 años víctima de violencia sexual", ["Lesiones genitales", "Afectación emocional severa"]),
  {"rotulo": "Secuencia de atención", "ans": 0,
   "fases": [("Llegada", "Inmediato", "ATENCIÓN MÉDICA", ["Estabilizar y curar"]),
             ("< 72 h", "Kit", "Profilaxis", ["AE, PEP VIH, ITS, hepatitis B"]),
             ("Registro", "Mismo día", "Evidencias", ["Y denuncia"]),
             ("Seguimiento", "Semanas", "Salud mental", ["Y controles"])],
   "curvas": [],
   "chips_titulo": "Primera obligación · marcada la correcta",
   "chips": [("Atención y estabilización", True), ("Notificar primero", False), ("Autorización judicial", False), ("Avisar a familiares", False)]},
  ["No se requiere autorización judicial para atender.",
   "Anticoncepción de emergencia dentro de las 72-120 horas.",
   "Respetar la confidencialidad y el consentimiento."],
  "MINSA – NT N.° 179-2021 (Atención integral a víctimas de violencia sexual) · OMS – Guía clínica sobre violencia sexual (2013)")

# INF-070 · termómetro
V("termometro", "INF-070", "mordedura-perro-mano-desgarrante-lavado", "Mordedura de perro",
  "INFECTOLOGÍA ENAM: MORDEDURA DE PERRO", "INFECTOLOGÍA",
  ("Mordedura de perro", ["Lo primero y más eficaz: lavado profuso con agua y jabón",
   "Luego profilaxis antirrábica según el riesgo"]),
  ("Varón de 35 años mordido hace 2 horas", ["Herida profunda y desgarrante en la mano", "Primer nivel de atención"]),
  {"rotulo": "Categoría de exposición (OMS)",
   "niveles": [("I", "Contacto", ["Piel intacta"]),
               ("II", "Leve", ["Arañazo sin sangrado"]),
               ("III", "Grave", ["Mordedura transdérmica"])],
   "caso_nivel": 2, "ruta_titulo": "Manejo", "paso_label": "PASO",
   "pasos": [(1, "LAVADO PROFUSO 15 MIN", ["Agua, jabón y suero"], True),
             (2, "Vacuna ± inmunoglobulina", ["Según el animal y la categoría"], False),
             (3, "Antibiótico, sin suturar", ["Amoxicilina-clavulánico"], False)]},
  ["Heridas de mano: no cerrar (alto riesgo de infección).",
   "Observar al perro 10 días si es posible.",
   "Antitetánica según antecedente."],
  "MINSA – NTS N.° 131-MINSA/2016/DGIESP (Prevención y control de la rabia) · OMS – Rabies vaccines position paper (2018)")

# CB-051 · puntaje
V("puntaje", "CB-051", "discoteca-agitacion-diaforesis-midriasis-benzodiacepinas", "Toxíndrome simpaticomimético",
  "CIENCIAS BÁSICAS ENAM: TOXÍNDROME SIMPATICOMIMÉTICO", "CIENCIAS BÁSICAS",
  ("Toxíndrome simpaticomimético", ["Cocaína, anfetaminas, éxtasis",
   "Tratamiento inicial: benzodiacepinas (controlan agitación, PA y temperatura)"]),
  ("Varón de 28 años frente a una discoteca", ["Agitación y diaforesis · PA 190/100, FC 132", "T 38.8 °C · pupilas de 7.5 mm"]),
  {"rotulo": "Signos en el caso", "escala": "Simpaticomimético", "total": 6, "max": 6,
   "total_label": "Signos presentes",
   "interpreta": "Toxíndrome simpaticomimético",
   "items": [("Agitación", "1", True), ("Diaforesis", "1", True), ("Midriasis", "1", True),
             ("Hipertensión", "1", True), ("Taquicardia", "1", True), ("Hipertermia", "1", True)],
   "bandas": [("0-2", "Poco probable", "Buscar otra causa", False),
              ("≥ 3", "Simpaticomimético", "BENZODIACEPINAS; enfriar", True)]},
  ["Betabloqueantes: evitarlos (estimulación alfa sin oposición).",
   "Los neurolépticos bajan el umbral convulsivo y empeoran la hipertermia.",
   "Naloxona es para opioides."],
  "Goldfrank's Toxicologic Emergencies 11.ª ed. (2019)")

# SP-101 · fases
V("fases", "SP-101", "uno-de-cada-3-inicio-azar-muestreo-sistematico", "Muestreo sistemático",
  "SALUD PÚBLICA ENAM: MUESTREO SISTEMÁTICO", "SALUD PÚBLICA",
  ("Muestreo sistemático", ["Probabilístico: arranque al azar y luego cada k-ésimo elemento",
   "k = tamaño de la población / tamaño de la muestra"]),
  ("Estudio de calidad de atención", ["Se calcula la muestra y se elige uno al azar", "Luego se toma 1 de cada 3 pacientes"]),
  {"rotulo": "Pasos", "ans": 3,
   "fases": [("Marco", "Paso 1", "Lista de pacientes", ["Población N"]),
             ("Intervalo", "Paso 2", "k = N / n", ["Aquí k = 3"]),
             ("Arranque", "Paso 3", "Primero al azar", ["Entre 1 y k"]),
             ("Selección", "Paso 4", "1 DE CADA 3", ["Sistemático"])],
   "curvas": [],
   "chips_titulo": "Tipo · marcado el correcto",
   "chips": [("Sistemático", True), ("Aleatorio simple", False), ("Estratificado", False), ("No probabilístico", False)]},
  ["Riesgo: si la lista tiene un patrón periódico, se sesga.",
   "Aleatorio simple: cada uno sorteado de forma independiente.",
   "Estratificado: se sortea dentro de grupos."],
  "Hernández-Sampieri – Metodología de la investigación 7.ª ed. (2023)")

# TRA-028 · puntaje
V("puntaje", "TRA-028", "fractura-vertebral-caida-menopausia-precoz-densitometria", "Osteoporosis: ¿pedir densitometría?",
  "TRAUMATOLOGÍA ENAM: FRACTURA POR FRAGILIDAD", "TRAUMATOLOGÍA",
  ("Fractura por fragilidad", ["Fractura con trauma de baja energía (caída de su altura)",
   "Confirmar y medir la osteoporosis con densitometría (DXA)"]),
  ("Mujer de 60 años", ["Caída de su propia altura · menopausia precoz", "Rx: fractura en acuñamiento de L4"]),
  {"rotulo": "Indicaciones de DXA en el caso", "escala": "Riesgo de osteoporosis", "total": 2, "max": 5,
   "total_label": "Factores presentes",
   "interpreta": "Indicación de densitometría",
   "items": [("Fractura por fragilidad", "1", True), ("Menopausia precoz", "1", True),
             ("Mujer ≥ 65 años", "1", False), ("Corticoides crónicos", "1", False),
             ("IMC bajo", "1", False)],
   "bandas": [("0", "Sin indicación", "Prevención general", False),
              ("≥ 1", "Indicación", "DENSITOMETRÍA ÓSEA (DXA)", True)]},
  ["T-score ≤ −2.5: osteoporosis; −1 a −2.5: osteopenia.",
   "Fractura vertebral por fragilidad ya es osteoporosis clínica.",
   "Tratamiento: calcio, vitamina D y bisfosfonato."],
  "Bone Health & Osteoporosis Foundation – Clinician's guide (2022) · AACE – Postmenopausal osteoporosis (2020)")

# INF-071 · árbol
A("INF-071", "vih-rpr-lcr-vdrl-neurosifilis-penicilina-g-sodica", "Neurosífilis",
  "INFECTOLOGÍA ENAM: NEUROSÍFILIS", "INFECTOLOGÍA",
  ("Neurosífilis", ["VDRL positivo en LCR con pleocitosis linfocítica",
   "La penicilina benzatínica no alcanza niveles en el SNC: penicilina G sódica EV"]),
  ("Varón de 28 años con VIH sin TAR", ["Cefalea, Glasgow 11, rigidez de nuca", "RPR (+) · LCR: linfocitos y VDRL (+)"]),
  Q("¿Compromiso del SNC?", [
      L("Sí: VDRL en LCR +", "PENICILINA G SÓDICA EV", ["10-14 días"], path=True),
      L("No: sífilis temprana", "Penicilina benzatínica", ["2.4 millones UI IM"])], path=True),
  ("Tratamiento de la sífilis", [("Esquema", True)], [
      ("Primaria o secundaria", ["Benzatínica 1 dosis"]),
      ("Latente tardía", ["Benzatínica 3 dosis semanales"]),
      ("Neurosífilis", ["Penicilina G sódica EV"])]),
  ["En alérgicos: desensibilizar (ceftriaxona como alternativa).",
   "Controlar el LCR a los 6 meses.",
   "Reiniciar el TAR."],
  "CDC – STI treatment guidelines: Neurosyphilis (2021) · MINSA – Guía nacional de manejo de ITS (2018)")

# CIR-080 · termómetro
V("termometro", "CIR-080", "diverticulitis-absceso-pericolico-5-cm-drenaje-percutaneo", "Diverticulitis complicada",
  "CIRUGÍA ENAM: DIVERTICULITIS CON ABSCESO", "CIRUGÍA",
  ("Diverticulitis con absceso", ["Absceso pericólico ≥ 4-5 cm: drenaje percutáneo + antibióticos",
   "Peritonitis: cirugía"]),
  ("Mujer de 70 años", ["Dolor, fiebre y masa en fosa ilíaca izquierda", "TC: absceso pericólico de 5 cm"]),
  {"rotulo": "Clasificación de Hinchey",
   "niveles": [("Hinchey I", "Absceso pericólico", ["Drenaje si es ≥ 4-5 cm"]),
               ("Hinchey II", "Absceso a distancia", ["Pélvico o retroperitoneal"]),
               ("Hinchey III", "Peritonitis purulenta", ["Cirugía"]),
               ("Hinchey IV", "Peritonitis fecal", ["Hartmann"])],
   "caso_nivel": 0, "ruta_titulo": "Tratamiento", "paso_label": "PASO",
   "pasos": [(1, "Solo antibiótico", ["Absceso < 4 cm"], False),
             (2, "DRENAJE PERCUTÁNEO", ["+ antibióticos"], True),
             (3, "Cirugía", ["Hinchey III-IV o falla del drenaje"], False)]},
  ["Colonoscopía 6-8 semanas después para descartar cáncer.",
   "No hacer colonoscopía en la fase aguda.",
   "Sigmoidectomía electiva según recurrencia y riesgo."],
  "ASCRS – Clinical practice guidelines for left-sided colonic diverticulitis (2020) · WSES – Acute left colonic diverticulitis (2020)")

# CIR-081 · árbol
A("CIR-081", "anciano-dolor-distension-neumoperitoneo-laparotomia", "Neumoperitoneo",
  "CIRUGÍA ENAM: PERFORACIÓN DE VÍSCERA HUECA", "CIRUGÍA",
  ("Neumoperitoneo", ["Aire libre bajo el diafragma: perforación de víscera hueca",
   "Con cuadro abdominal agudo: laparotomía exploratoria"]),
  ("Varón de 74 años", ["Dolor y distensión de 2 días, vómitos, estreñimiento", "Rx de pie: neumoperitoneo"]),
  Q("¿Neumoperitoneo con abdomen agudo?", [
      L("Sí", "LAPAROTOMÍA EXPLORATORIA", ["Reparar la perforación"], path=True),
      L("Cirugía reciente o sin peritonitis", "Evaluar con TEM", ["Neumoperitoneo posquirúrgico"])], path=True),
  ("Causas de perforación", [("Frecuencia", True)], [
      ("Úlcera péptica", ["La más frecuente"]),
      ("Diverticulitis", ["Colon sigmoides"]),
      ("Cáncer colorrectal", ["Anciano con estreñimiento"])]),
  ["Reanimar y dar antibióticos antes de operar.",
   "La TEM no debe retrasar la cirugía si el diagnóstico es claro.",
   "La Rx de tórax de pie detecta aire subdiafragmático."],
  "WSES – Guidelines for management of intra-abdominal infections (2017) · Sabiston Textbook of Surgery 21.ª ed. (2021)")

# SP-102 · fases
V("fases", "SP-102", "protocolo-sustento-hipotesis-marco-teorico", "Partes del protocolo de investigación",
  "SALUD PÚBLICA ENAM: MARCO TEÓRICO", "SALUD PÚBLICA",
  ("Marco teórico", ["Revisión de conocimientos que sustenta la hipótesis",
   "Da la plausibilidad biológica o teórica"]),
  ("Pregunta de concepto", ["Sección del protocolo que sustenta la hipótesis", "con argumentos de plausibilidad"]),
  {"rotulo": "Estructura del protocolo", "ans": 2,
   "fases": [("Problema", "Sección 1", "Descripción", ["Qué se investiga"]),
             ("Justificación", "Sección 2", "Por qué importa", ["Relevancia"]),
             ("Marco teórico", "Sección 3", "SUSTENTO", ["Plausibilidad de la hipótesis"]),
             ("Métodos", "Sección 4", "Diseño y ética", ["Muestra, análisis"])],
   "curvas": [],
   "chips_titulo": "Sección · marcada la correcta",
   "chips": [("Marco teórico", True), ("Justificación", False), ("Descripción del problema", False), ("Aspectos éticos", False)]},
  ["Justificación: responde por qué y para qué hacer el estudio.",
   "Aspectos éticos: consentimiento y comité de ética.",
   "La hipótesis debe ser contrastable."],
  "Hernández-Sampieri – Metodología de la investigación 7.ª ed. (2023) · INS – Guía para protocolos de investigación")

# PSI-029 · radial
V("radial", "PSI-029", "isrs-depresion-retiro-gradual", "Uso de los ISRS",
  "PSIQUIATRÍA ENAM: USO DE ISRS", "PSIQUIATRÍA",
  ("Inhibidores selectivos de la recaptación de serotonina", ["Iniciar con dosis baja y subir; efecto en 2-4 semanas",
   "Suspender de forma gradual para evitar el síndrome de discontinuación"]),
  ("Paciente con síntomas depresivos", ["Llanto fácil, minusvalía, bradipsiquia", "Se prescribirá un ISRS"]),
  {"rotulo": "Mapa del tema", "centro": "ISRS", "centro_sub": "Prescripción", "ans": 0,
   "items": [("RETIRO GRADUAL", ["Evita la discontinuación", "Bajo supervisión médica"]),
             ("Inicio", ["Dosis baja y subir"]),
             ("Latencia", ["2-4 semanas"]),
             ("Ansiedad", ["También primera línea"]),
             ("Efectos", ["Sexuales, digestivos"])],
   "ruta": ["Depresión", "Inicia ISRS", "Mantener 6-12 meses", "RETIRO GRADUAL"]},
  ["No generan tolerancia ni adicción.",
   "Discontinuación: mareo, «descargas», irritabilidad.",
   "Vigilar ideación suicida al inicio en jóvenes."],
  "NICE – Depression in adults (2022) · " + GOODMAN)

# TRA-029 · puntaje
V("puntaje", "TRA-029", "rodillas-crepitacion-rigidez-breve-gonartrosis", "Gonartrosis: criterios",
  "TRAUMATOLOGÍA ENAM: GONARTROSIS", "TRAUMATOLOGÍA",
  ("Artrosis de rodilla", ["Dolor mecánico, rigidez matinal breve (< 30 min) y crepitación",
   "Sin inflamación importante"]),
  ("Varón de 66 años", ["Dolor en ambas rodillas; mejora tras unos minutos de actividad", "Crepitación, sin aumento de volumen"]),
  {"rotulo": "Criterios clínicos ACR en el caso", "escala": "ACR (rodilla)", "total": 4, "max": 6,
   "total_label": "Criterios presentes",
   "interpreta": "Gonartrosis (dolor + ≥ 3)",
   "items": [("Edad > 50 años", "1", True), ("Rigidez < 30 minutos", "1", True),
             ("Crepitación", "1", True), ("Sin calor local", "1", True),
             ("Dolor óseo a la palpación", "1", False), ("Ensanchamiento óseo", "1", False)],
   "bandas": [("< 3", "No cumple", "Buscar otra causa", False),
              ("≥ 3", "Gonartrosis", "Ejercicio, bajar de peso, AINE tópico", True)]},
  ["Rx: pinzamiento, osteofitos, esclerosis subcondral.",
   "Artritis reumatoide: rigidez > 1 h y sinovitis.",
   "Gota: monoartritis aguda con calor y rubor."],
  "ACR – Classification criteria for knee osteoarthritis (1986) · OARSI – Guidelines for knee OA (2019)")

# SP-103 · tarjetas
V("tarjetas", "SP-103", "documento-estructura-organica-funciones-rof", "Documentos de gestión",
  "SALUD PÚBLICA ENAM: DOCUMENTOS DE GESTIÓN", "SALUD PÚBLICA",
  ("Reglamento de Organización y Funciones (ROF)", ["Define la estructura orgánica y las funciones de cada unidad",
   "Documento técnico normativo de gestión"]),
  ("Pregunta de concepto", ["Documento que establece la estructura orgánica", "y las competencias de cada área"]),
  {"rotulo": "¿Qué documento es?", "ans": 0, "cards": [
      {"titulo": "ROF", "datos": [
          ("Define", "Estructura y funciones", True), ("Nivel", "Institución", True),
          ("Ejemplo", "Organigrama y competencias", True)],
       "pie": "Organización y funciones"},
      {"titulo": "Reglamento interno de trabajo", "datos": [
          ("Define", "Deberes del personal", False), ("Nivel", "Trabajadores", False),
          ("Ejemplo", "Horarios, faltas", False)],
       "pie": "Relación laboral"},
      {"titulo": "Manual de procedimientos", "datos": [
          ("Define", "Cómo se hace cada proceso", False), ("Nivel", "Procesos", False),
          ("Ejemplo", "Pasos de una atención", False)],
       "pie": "MAPRO"},
      {"titulo": "Plan estratégico", "datos": [
          ("Define", "Objetivos a mediano plazo", False), ("Nivel", "Institución", False),
          ("Ejemplo", "Metas a 3-5 años", False)],
       "pie": "Planificación"}]},
  ["El MOF (manual de funciones) detallaba cargos; hoy lo integra el ROF.",
   "El POI es el plan operativo anual.",
   "El ROF se aprueba por norma de la institución."],
  "PCM – Lineamientos de organización del Estado (DS N.° 054-2018-PCM) · MINSA – Documentos de gestión")

# CB-052 · matriz
V("matriz", "CB-052", "antraciclinas-cardiotoxicidad", "Toxicidad de la quimioterapia",
  "CIENCIAS BÁSICAS ENAM: TOXICIDAD DE QUIMIOTERÁPICOS", "CIENCIAS BÁSICAS",
  ("Antraciclinas (doxorrubicina)", ["Cardiotoxicidad dosis-dependiente: miocardiopatía dilatada",
   "Ecocardiograma antes y durante el tratamiento"]),
  ("Pregunta de concepto", ["Relación correcta", "quimioterápico / toxicidad"]),
  {"rotulo": "Toxicidad característica", "eje_x": "Aspecto", "eje_y": "Fármaco",
   "cols": ["Toxicidad", "Prevención"], "rows": ["Antraciclinas", "Ciclofosfamida", "Bleomicina", "L-asparaginasa"], "caso": (0, 0),
   "cells": [[("CARDIOTOXICIDAD", ["Miocardiopatía"]), ("Dosis acumulada", ["Dexrazoxano"])],
             [("Cistitis hemorrágica", []), ("Mesna, hidratación", [])],
             [("Fibrosis pulmonar", []), ("Limitar la dosis", [])],
             [("Pancreatitis", ["Trombosis"]), ("Vigilar", [])]]},
  ["Cisplatino: nefrotoxicidad y ototoxicidad.",
   "Vincristina: neuropatía periférica.",
   "Metotrexato: mucositis, mielosupresión (rescate con leucovorina)."],
  GOODMAN)

# NEF-062 · tarjetas
V("tarjetas", "NEF-062", "chorro-debil-esfuerzo-miccional-tacto-rectal", "Síntomas prostáticos: primer paso",
  "NEFROLOGÍA ENAM: EVALUACIÓN PROSTÁTICA", "NEFROLOGÍA",
  ("Síntomas urinarios obstructivos", ["Dificultad para iniciar, chorro débil y pujo",
   "Primer paso: tacto rectal (tamaño, consistencia, nódulos)"]),
  ("Varón de 63 años", ["Dificultad para iniciar la micción", "Chorro débil y necesidad de pujar"]),
  {"rotulo": "¿Qué hacer primero?", "ans": 0, "cards": [
      {"titulo": "TACTO RECTAL", "datos": [
          ("Evalúa", "Tamaño y consistencia", True), ("Orden", "Primero", True),
          ("Ventaja", "Rápido y barato", True)],
       "pie": "Detecta nódulos sospechosos"},
      {"titulo": "PSA", "datos": [
          ("Evalúa", "Riesgo de cáncer", False), ("Orden", "Junto o después", False),
          ("Ventaja", "Ayuda a decidir biopsia", False)],
       "pie": "Sube también en HBP"},
      {"titulo": "Examen de orina", "datos": [
          ("Evalúa", "Infección, hematuria", False), ("Orden", "Complementario", False),
          ("Ventaja", "Descarta ITU", False)],
       "pie": "No evalúa la próstata"},
      {"titulo": "Cistoscopía", "datos": [
          ("Evalúa", "Uretra y vejiga", False), ("Orden", "No inicial", False),
          ("Ventaja", "Invasiva", False)],
       "pie": "Si hay hematuria"}]},
  ["Cuestionario IPSS para medir la gravedad.",
   "Ecografía con residuo posmiccional.",
   "Alfa-bloqueante si los síntomas molestan."],
  "EAU – Management of non-neurogenic male LUTS (2024) · AUA – BPH guideline (2023)")

# GIN-141 · matriz
V("matriz", "GIN-141", "flujo-maloliente-cervix-petequial-tricomonas", "Tipos de vaginitis",
  "GINECOLOGÍA ENAM: TRICOMONIASIS", "GINECOLOGÍA",
  ("Tricomoniasis", ["Flujo abundante, espumoso y maloliente con prurito",
   "Cérvix con petequias («en fresa»); es una ITS"]),
  ("Mujer de 30 años", ["Flujo abundante y maloliente, prurito, edema vulvar", "Cérvix con múltiples lesiones petequiales"]),
  {"rotulo": "Según el flujo", "eje_x": "Aspecto", "eje_y": "Causa",
   "cols": ["Flujo", "Clave"], "rows": ["Tricomoniasis", "Vaginosis", "Candidiasis"], "caso": (0, 1),
   "cells": [[("Espumoso, amarillo-verde", ["pH > 4.5"]), ("CÉRVIX EN FRESA", ["Protozoo móvil"])],
             [("Gris, homogéneo", ["Olor a pescado"]), ("Células clave", [])],
             [("Blanco, grumoso", ["pH normal"]), ("Prurito intenso", ["Hifas"])]]},
  ["Tratamiento: metronidazol 500 mg c/12 h por 7 días.",
   "Tratar a la pareja: es de transmisión sexual.",
   "Descartar otras ITS (VIH, sífilis)."],
  "CDC – STI treatment guidelines: Trichomoniasis (2021)")

# INF-072 · embudo
V("embudo", "INF-072", "loreto-ulcera-indolora-bordes-indurados-leishmaniasis", "Úlcera crónica de la selva",
  "INFECTOLOGÍA ENAM: LEISHMANIASIS CUTÁNEA", "INFECTOLOGÍA",
  ("Leishmaniasis cutánea", ["Picadura del mosquito Lutzomyia en zonas selváticas y andinas",
   "Úlcera indolora con bordes elevados e indurados, fondo granuloso"]),
  ("Varón de 25 años de Loreto", ["Úlcera única de 3 meses en la pierna", "Bordes indurados, indolora, sin fiebre"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Úlcera crónica en la pierna",
   "candidatos": ["Leishmaniasis cutánea", "Úlcera tropical", "Pioderma gangrenoso", "Esporotricosis", "TB cutánea"],
   "pasos": [("Indolora, bordes en «marco»", ["Úlcera tropical", "Pioderma gangrenoso"]),
             ("Sin nódulos en la vía linfática", ["Esporotricosis"]),
             ("Procede de la selva, sin foco de TB", ["TB cutánea"])],
   "final": ("LEISHMANIASIS CUTÁNEA", ["Frotis, cultivo o PCR", "Antimoniales pentavalentes"]),
   "nota": "Examinar mucosa nasal: riesgo de forma mucocutánea (espundia)."},
  ["Forma andina «uta»: úlceras pequeñas en cara.",
   "Antimoniato de meglumina 20 mg/kg/día.",
   "Miltefosina oral como alternativa."],
  "MINSA – NTS de atención de la leishmaniasis · OPS – Manual de procedimientos para leishmaniasis (2019)")

# GIN-142 · matriz
V("matriz", "GIN-142", "falta-cotiledon-sangrado-revision-uterina", "Causas de hemorragia posparto",
  "OBSTETRICIA ENAM: ALUMBRAMIENTO INCOMPLETO", "OBSTETRICIA",
  ("Alumbramiento incompleto", ["Restos placentarios (falta un cotiledón)",
   "Impiden la contracción: revisión uterina"]),
  ("Puérpera inmediata", ["A la placenta le falta un cotiledón", "Sangrado activo"]),
  {"rotulo": "Las «4 T»", "eje_x": "Aspecto", "eje_y": "Causa",
   "cols": ["Mecanismo", "Clave"], "rows": ["Tono", "Trauma", "Tejido", "Trombina"], "caso": (2, 1),
   "cells": [[("Atonía", ["La más frecuente"]), ("Útero blando", [])],
             [("Desgarros", ["Cérvix, vagina, periné"]), ("Útero contraído", [])],
             [("Restos", ["Placenta, membranas"]), ("FALTA UN COTILEDÓN", ["Revisión uterina"])],
             [("Coagulopatía", []), ("CID, anticoagulantes", [])]]},
  ["Revisar siempre la placenta tras el alumbramiento.",
   "Revisión manual o instrumental con analgesia.",
   "Acretismo si la placenta no se desprende."],
  "OMS – Prevención y tratamiento de la HPP (2023) · " + WILLIAMS)

# CAR-052 · embudo
V("embudo", "CAR-052", "hipertensa-tos-rosada-crepitantes-edema-agudo-pulmon", "Disnea con tos rosada",
  "CARDIOLOGÍA ENAM: EDEMA AGUDO DE PULMÓN", "CARDIOLOGÍA",
  ("Edema agudo de pulmón hipertensivo", ["PA muy alta con disnea, tos rosada y crepitantes difusos",
   "Nitroglicerina, diurético y VNI"]),
  ("Mujer de 56 años con HTA mal tratada", ["Disnea, tos rosada, diaforesis", "PA 195/105, FR 28, cianosis, crepitantes bilaterales"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Disnea aguda con PA muy alta",
   "candidatos": ["Edema agudo de pulmón", "Choque cardiogénico", "TEP", "Neumonía atípica", "Asma"],
   "pasos": [("PA 195/105: no hay choque", ["Choque cardiogénico"]),
             ("Crepitantes difusos y tos rosada", ["TEP", "Asma"]),
             ("Sin fiebre ni curso subagudo", ["Neumonía atípica"])],
   "final": ("EDEMA AGUDO DE PULMÓN", ["Hipertensivo", "Nitroglicerina + furosemida + VNI"]),
   "nota": "Sentar al paciente y dar oxígeno si SatO₂ < 90%."},
  ["Nitratos a dosis altas bajan la poscarga rápidamente.",
   "Buscar isquemia con ECG y troponina.",
   "Ecocardiograma para la función ventricular."],
  "ESC – Heart failure guidelines (2021, act. 2023)")

# NEF-063 · puntaje
V("puntaje", "NEF-063", "nefrotico-membranosa-albumina-18-disnea-tep", "Síndrome nefrótico con disnea súbita",
  "NEFROLOGÍA ENAM: TROMBOSIS EN SÍNDROME NEFRÓTICO", "NEFROLOGÍA",
  ("Hipercoagulabilidad nefrótica", ["Pérdida de antitrombina III; mayor riesgo con albúmina < 2.5",
   "Nefropatía membranosa: la más trombogénica (vena renal, TEP)"]),
  ("Varón de 45 años con nefropatía membranosa", ["Proteinuria 8 g/día, albúmina 1.8", "Disnea, dolor pleurítico, SatO₂ 88% · taquicardia"]),
  {"rotulo": "Wells (dos niveles) en el caso", "escala": "Wells", "total": 4.5, "max": 12.5,
   "total_label": "Puntaje del caso",
   "interpreta": "TEP probable",
   "items": [("TEP es el diagnóstico más probable", "3", True), ("FC > 100", "1.5", True),
             ("Signos de TVP", "3", False), ("Inmovilización o cirugía", "1.5", False),
             ("TVP o TEP previos", "1.5", False), ("Hemoptisis", "1", False),
             ("Cáncer activo", "1", False)],
   "bandas": [("≤ 4", "Improbable", "Dímero D", False),
              ("> 4", "Probable", "ANGIO-TC; anticoagular", True)]},
  ["Buscar también trombosis de la vena renal.",
   "Anticoagulación profiláctica si albúmina < 2-2.5 y riesgo alto.",
   "El dímero D no descarta si la probabilidad es alta."],
  "KDIGO – Glomerular diseases guideline (2021) · ESC – Acute pulmonary embolism (2019)")

# INF-073 · matriz
V("matriz", "INF-073", "lcr-linfocitos-glucosa-normal-meningitis-viral", "Meningitis: LCR y tratamiento",
  "INFECTOLOGÍA ENAM: MENINGITIS VIRAL", "INFECTOLOGÍA",
  ("Meningitis viral (aséptica)", ["LCR con linfocitos, glucosa normal y proteínas algo altas",
   "Autolimitada: tratamiento sintomático"]),
  ("Mujer de 34 años con 3 días de cefalea y fiebre", ["Rigidez de nuca, sin déficit focal", "LCR: 90 linfocitos, glucosa normal, Gram negativo"]),
  {"rotulo": "Según el LCR", "eje_x": "Aspecto", "eje_y": "Tipo",
   "cols": ["LCR", "Tratamiento"], "rows": ["Viral", "Bacteriana", "Tuberculosa", "Herpética"], "caso": (0, 1),
   "cells": [[("Linfocitos, glucosa normal", []), ("SINTOMÁTICO", ["Analgésico, antipirético"])],
             [("Neutrófilos, glucosa baja", []), ("Ceftriaxona + vancomicina", [])],
             [("Linfocitos, glucosa baja", ["ADA alto"]), ("Antituberculosos", [])],
             [("Linfocitos, hematíes", ["Encefalitis"]), ("Aciclovir EV", [])]]},
  ["Enterovirus: causa más frecuente.",
   "Aciclovir solo si hay encefalitis (alteración mental, convulsiones, foco).",
   "Si hay duda, iniciar antibiótico hasta tener cultivos."],
  "IDSA – Practice guidelines for bacterial meningitis (2004) · " + HARRISON)

# TRA-030 · radial
V("radial", "TRA-030", "trauma-muneca-4-5-dedo-canal-guyon", "Nervios de la mano",
  "TRAUMATOLOGÍA ENAM: CANAL DE GUYON", "TRAUMATOLOGÍA",
  ("Canal de Guyon (canal ulnar)", ["Por él pasa el nervio cubital en la muñeca",
   "Compresión: adormecimiento del 4.º y 5.º dedo"]),
  ("Varón de 48 años", ["Trauma de muñeca hace 3 meses", "Adormecimiento del 4.º y 5.º dedo"]),
  {"rotulo": "Mapa del tema", "centro": "MUÑECA", "centro_sub": "Nervios", "ans": 0,
   "items": [("CANAL DE GUYON", ["Nervio cubital", "4.º y 5.º dedo"]),
             ("Túnel carpiano", ["Nervio mediano: 1.º a 3.º"]),
             ("Túnel cubital", ["Cubital en el codo"]),
             ("Radial superficial", ["Dorso del pulgar"]),
             ("Tabaquera", ["Escafoides"])],
   "ruta": ["Trauma de muñeca", "Compresión del cubital", "Dedos 4.º y 5.º", "CANAL DE GUYON"]},
  ["Signo de Froment: debilidad del aductor del pulgar.",
   "Mano en garra en lesiones avanzadas del cubital.",
   "Causas: ganglión, fractura del ganchoso, ciclistas."],
  "Moore – Anatomía con orientación clínica 9.ª ed. (2022) · Green's Operative Hand Surgery 8.ª ed. (2022)")

# SP-104 · embudo
V("embudo", "SP-104", "comedor-200-comensales-80-enfermos-tasa-ataque", "Tasa de ataque",
  "SALUD PÚBLICA ENAM: TASA DE ATAQUE", "SALUD PÚBLICA",
  ("Tasa de ataque", ["Incidencia acumulada durante un brote",
   "Enfermos / expuestos = 80 / 200 = 40%"]),
  ("Comedor universitario", ["200 personas almorzaron", "80 enfermaron de gastroenteritis"]),
  {"rotulo": "Embudo de conceptos",
   "inicio": "80 de 200 comensales enferman",
   "candidatos": ["Riesgo del expuesto", "Letalidad", "Mortalidad", "Prevalencia", "Velocidad de contagio"],
   "pasos": [("Mide enfermos, no muertos", ["Letalidad", "Mortalidad"]),
             ("Casos nuevos entre expuestos del brote", ["Prevalencia"]),
             ("Es una proporción, no una velocidad", ["Velocidad de contagio"])],
   "final": ("RIESGO DE ENFERMAR DEL EXPUESTO", ["80 / 200 = 40%", "Incidencia acumulada"]),
   "nota": "Tasa de ataque secundaria: casos entre contactos del caso primario."},
  ["Comparar tasas de ataque entre quienes comieron y no comieron cada plato.",
   "El alimento con mayor diferencia es el sospechoso.",
   "Estudio de brote: definir caso, curva epidémica, hipótesis."],
  "OPS – MOPECE · Gordis – Epidemiology 6.ª ed. (2019)")

# SP-105 · radial
V("radial", "SP-105", "conjunto-organizaciones-articulacion-redes-integradas", "Redes Integradas de Salud",
  "SALUD PÚBLICA ENAM: REDES INTEGRADAS DE SALUD", "SALUD PÚBLICA",
  ("Redes Integradas de Salud (RIS)", ["Organizaciones articuladas que atienden a una población definida",
   "Rinden cuentas por los resultados sanitarios"]),
  ("Pregunta de concepto", ["Atención equitativa e integral", "mediante articulación y complementariedad"]),
  {"rotulo": "Mapa del tema", "centro": "RIS", "centro_sub": "Ley N.° 30885", "ans": 0,
   "items": [("ARTICULACIÓN", ["Coordinación y complementariedad", "Entre niveles"]),
             ("Población", ["Definida, en un territorio"]),
             ("Primer nivel", ["Resolutivo, puerta de entrada"]),
             ("Rendición", ["De cuentas por resultados"]),
             ("Equidad", ["Atención integral"])],
   "ruta": ["Varias organizaciones", "Se articulan", "Atienden a una población", "REDES INTEGRADAS"]},
  ["El SIS es un seguro (financia), no una red.",
   "Basadas en la propuesta de la OPS (2010).",
   "El primer nivel coordina la referencia y contrarreferencia."],
  "Ley N.° 30885 (Conformación de las RIS, 2018) · OPS – Redes integradas de servicios de salud (2010)")

# END-041 · termómetro
V("termometro", "END-041", "adolescente-imc-3-de-acantosis-resistencia-insulina", "Obesidad infantil y acantosis",
  "ENDOCRINOLOGÍA ENAM: RESISTENCIA A LA INSULINA", "ENDOCRINOLOGÍA",
  ("Acantosis nigricans", ["Piel oscura y aterciopelada en cuello y axilas",
   "Marcador de resistencia a la insulina en la obesidad"]),
  ("Adolescente de 12 años", ["IMC +3 DE (OMS)", "Manchas oscuras en cuello y axilas"]),
  {"rotulo": "IMC para la edad (OMS)",
   "niveles": [("+1 a +2 DE", "Sobrepeso", ["Riesgo"]),
               ("+2 a +3 DE", "Obesidad", ["Evaluar comorbilidad"]),
               ("≥ +3 DE", "Obesidad severa", ["Acantosis, prediabetes"])],
   "caso_nivel": 2, "ruta_titulo": "Conducta", "paso_label": "PASO",
   "pasos": [(1, "Glucosa, lípidos, transaminasas", ["Tamizaje de comorbilidad"], False),
             (2, "ESTILO DE VIDA", ["Dieta, actividad física, familia"], True),
             (3, "Metformina", ["Si hay prediabetes o DM2"], False)]},
  ["La acantosis mejora al bajar de peso.",
   "Cushing: estrías violáceas, talla baja.",
   "Hipotiroidismo: talla baja con aumento de peso."],
  "AAP – Clinical practice guideline for pediatric obesity (2023) · OMS – Patrones de crecimiento (2007)")

# CIR-082 · fases
V("fases", "CIR-082", "posoperatorio-dia-3-distension-sin-rha-opioides", "Íleo posoperatorio",
  "CIRUGÍA ENAM: ÍLEO POSOPERATORIO", "CIRUGÍA",
  ("Íleo posoperatorio", ["La motilidad se recupera en 3 días (delgado, estómago, colon)",
   "Causa iatrogénica más frecuente de íleo prolongado: opioides"]),
  ("Varón de 68 años, día 3 tras resección yeyunal", ["Distensión y ausencia de ruidos", "Drenaje seroso escaso"]),
  {"rotulo": "Recuperación de la motilidad", "ans": 3,
   "fases": [("Delgado", "0-24 h", "Recupera primero", []),
             ("Estómago", "24-48 h", "Vaciamiento", []),
             ("Colon", "48-72 h", "Flatos", []),
             ("Prolongado", "> 3 días", "OPIOIDES", ["Causa iatrogénica"])],
   "curvas": [("Motil.", SKY, [0.1, 0.3, 0.5, 0.7, 0.6, 0.5, 0.45])],
   "chips_titulo": "Causa · marcada la correcta",
   "chips": [("Opioides", True), ("IBP", False), ("Anestésicos inhalados", False), ("Atelectasia", False)]},
  ["Analgesia multimodal y epidural reducen el íleo.",
   "Movilización precoz y alimentación temprana.",
   "Descartar obstrucción mecánica o fuga anastomótica."],
  "ERAS Society – Guidelines for perioperative care (2019) · Sabiston Textbook of Surgery 21.ª ed. (2021)")

# GAS-052 · tarjetas
V("tarjetas", "GAS-052", "adenocarcinoma-pancreas-ca-19-9", "Marcadores tumorales",
  "GASTROENTEROLOGÍA ENAM: CÁNCER DE PÁNCREAS", "GASTROENTEROLOGÍA",
  ("CA 19-9", ["Marcador más sensible y específico del adenocarcinoma de páncreas",
   "Útil para seguimiento y pronóstico, no para tamizaje"]),
  ("Pregunta de concepto", ["Marcador tumoral más útil", "en el adenocarcinoma de páncreas"]),
  {"rotulo": "¿Qué marcador?", "ans": 0, "cards": [
      {"titulo": "CA 19-9", "datos": [
          ("Tumor", "Páncreas, vía biliar", True), ("Uso", "Seguimiento, pronóstico", True),
          ("Limitación", "Sube en colestasis", True)],
       "pie": "No sirve si es Lewis negativo"},
      {"titulo": "CEA", "datos": [
          ("Tumor", "Colorrectal", False), ("Uso", "Seguimiento", False),
          ("Limitación", "Sube en fumadores", False)],
       "pie": "Antígeno carcinoembrionario"},
      {"titulo": "Alfafetoproteína", "datos": [
          ("Tumor", "Hepatocarcinoma, germinales", False), ("Uso", "Diagnóstico y control", False),
          ("Limitación", "Sube en hepatitis", False)],
       "pie": "AFP"},
      {"titulo": "CA 15-3", "datos": [
          ("Tumor", "Mama", False), ("Uso", "Enfermedad metastásica", False),
          ("Limitación", "Poco sensible", False)],
       "pie": "No para tamizaje"}]},
  ["Ningún marcador sirve para tamizar a la población general.",
   "TC con contraste: estudio de imagen inicial en sospecha.",
   "CA-125: ovario."],
  "NCCN – Pancreatic adenocarcinoma (2024) · ASCO – Tumor markers guideline")

# CIR-083 · embudo
V("embudo", "CIR-083", "apendicectomia-previa-dolor-fid-munon-inflamado", "Dolor en FID tras apendicectomía",
  "CIRUGÍA ENAM: APENDICITIS DEL MUÑÓN", "CIRUGÍA",
  ("Apendicitis del muñón", ["Inflamación del remanente apendicular tras una apendicectomía",
   "Más frecuente si quedó un muñón largo (> 5 mm)"]),
  ("Varón de 35 años operado hace 6 meses", ["Dolor en FID de 24 horas", "Blumberg (+) · TC: estructura tubular inflamada en el ciego"]),
  {"rotulo": "Embudo diagnóstico",
   "inicio": "Dolor en FID con apendicectomía previa",
   "candidatos": ["Apendicitis del muñón", "Divertículo de Meckel", "Oblito", "Íleo biliar", "Crohn"],
   "pasos": [("Estructura tubular en el ciego", ["Divertículo de Meckel", "Oblito"]),
             ("Sin obstrucción ni aerobilia", ["Íleo biliar"]),
             ("Cuadro agudo sin historia crónica", ["Crohn"])],
   "final": ("APENDICITIS DEL MUÑÓN", ["TC: muñón inflamado", "Cirugía (completar apendicectomía)"]),
   "nota": "Una apendicectomía previa no descarta apendicitis."},
  ["Dejar un muñón < 5 mm la previene.",
   "Meckel: íleon a 60 cm de la válvula ileocecal.",
   "Oblito: cuerpo extraño olvidado en cirugía."],
  "WSES – Jerusalem guidelines for acute appendicitis (2020)")

# INF-074 · fases
V("fases", "INF-074", "vesiculas-labio-mayor-herpes-genital-pcr-lesion", "Herpes genital: diagnóstico",
  "INFECTOLOGÍA ENAM: HERPES GENITAL", "INFECTOLOGÍA",
  ("Herpes genital", ["Vesículas dolorosas agrupadas que se ulceran",
   "Confirmar con PCR (o cultivo) de la lesión"]),
  ("Mujer de 25 años", ["Vesículas dolorosas en labio mayor derecho", "Hace 2 días"]),
  {"rotulo": "Evolución de la lesión", "ans": 0,
   "fases": [("Vesícula", "Días 1-3", "PCR DE LA LESIÓN", ["Máxima sensibilidad"]),
             ("Úlcera", "Días 3-7", "PCR aún útil", ["Menor carga viral"]),
             ("Costra", "Días 7-14", "Poco rendimiento", ["Cicatriza"]),
             ("Latencia", "Meses", "Serología", ["Solo antecedente"])],
   "curvas": [("Virus", ROSE, [0.2, 0.95, 0.8, 0.5, 0.2, 0.05, 0.0])],
   "chips_titulo": "Prueba · marcada la correcta",
   "chips": [("Virológica de la lesión", True), ("Serología", False), ("Citología", False), ("Hemograma", False)]},
  ["Tratamiento: aciclovir o valaciclovir 7-10 días en el primer episodio.",
   "La serología no distingue una infección actual.",
   "Descartar sífilis y VIH."],
  "CDC – STI treatment guidelines: Genital herpes (2021)")

# NEF-064 · tarjetas
V("tarjetas", "NEF-064", "prostatectomia-radical-preservar-nervios-cavernosos", "Nervios pélvicos y función sexual",
  "NEFROLOGÍA ENAM: NERVIOS CAVERNOSOS", "NEFROLOGÍA",
  ("Nervios cavernosos", ["Fibras parasimpáticas que corren por las bandeletas neurovasculares",
   "Preservarlos evita la disfunción eréctil tras la prostatectomía"]),
  ("Varón de 55 años", ["Prostatectomía radical robótica", "Se quiere evitar la disfunción eréctil"]),
  {"rotulo": "¿Qué nervio preservar?", "ans": 0, "cards": [
      {"titulo": "CAVERNOSOS", "datos": [
          ("Tipo", "Parasimpático", True), ("Función", "Erección", True),
          ("Ubicación", "Posterolateral a la próstata", True)],
       "pie": "Cirugía con preservación nerviosa"},
      {"titulo": "Pudendo", "datos": [
          ("Tipo", "Somático", False), ("Función", "Sensibilidad, eyaculación", False),
          ("Ubicación", "Canal de Alcock", False)],
       "pie": "Músculos del periné"},
      {"titulo": "Hipogástrico", "datos": [
          ("Tipo", "Simpático", False), ("Función", "Emisión seminal", False),
          ("Ubicación", "Plexo presacro", False)],
       "pie": "Eyaculación retrógrada si se daña"},
      {"titulo": "Genitofemoral", "datos": [
          ("Tipo", "Mixto", False), ("Función", "Cremáster", False),
          ("Ubicación", "Sobre el psoas", False)],
       "pie": "Reflejo cremastérico"}]},
  ["«Point and shoot»: parasimpático = erección; simpático = eyaculación.",
   "La preservación depende de la extensión del tumor.",
   "Rehabilitación peneana con inhibidores de PDE5."],
  "EAU – Guidelines on prostate cancer (2024) · Campbell-Walsh-Wein Urology 12.ª ed. (2020)")

# END-042 · termómetro
V("termometro", "END-042", "dm2-10-anos-cociente-albumina-creatinina", "Nefropatía diabética: detección precoz",
  "ENDOCRINOLOGÍA ENAM: NEFROPATÍA DIABÉTICA", "ENDOCRINOLOGÍA",
  ("Detección de nefropatía diabética", ["Cociente albúmina/creatinina en orina aislada",
   "Detecta daño antes de que suba la creatinina"]),
  ("Mujer de 55 años con DM2 de 10 años", ["HbA1c 7%", "Urea y creatinina normales"]),
  {"rotulo": "Albuminuria (mg/g)",
   "niveles": [("< 30", "A1 normal", ["Sin daño"]),
               ("30-300", "A2 moderada", ["Daño precoz"]),
               ("> 300", "A3 severa", ["Nefropatía establecida"])],
   "caso_nivel": 1, "ruta_titulo": "Conducta", "paso_label": "PASO",
   "pasos": [(1, "COCIENTE ALBÚMINA/CREATININA", ["Orina aislada, anual"], True),
             (2, "Confirmar en 2 de 3 muestras", ["En 3-6 meses"], False),
             (3, "IECA o ARA II + iSGLT2", ["Si hay albuminuria"], False)]},
  ["Tamizaje anual desde el diagnóstico de DM2.",
   "Calcular también la TFG con creatinina.",
   "Ejercicio intenso, fiebre o ITU dan falsos positivos."],
  "ADA – Standards of Care in Diabetes: CKD (2025) · KDIGO – Diabetes in CKD (2022)")

# CB-053 · matriz
V("matriz", "CB-053", "anestesico-liposoluble-barrera-hematoencefalica", "Paso por la barrera hematoencefálica",
  "CIENCIAS BÁSICAS ENAM: FARMACOCINÉTICA", "CIENCIAS BÁSICAS",
  ("Barrera hematoencefálica", ["Endotelio con uniones estrechas: pasan las moléculas lipofílicas",
   "Por eso los anestésicos generales son muy liposolubles"]),
  ("Pregunta de concepto", ["Característica que permite al anestésico", "atravesar la barrera hematoencefálica"]),
  {"rotulo": "Propiedades del fármaco", "eje_x": "Aspecto", "eje_y": "Propiedad",
   "cols": ["Efecto en la BHE", "Ejemplo"], "rows": ["Alta liposolubilidad", "Hidrosolubilidad", "Unión a proteínas", "Ionización"], "caso": (0, 0),
   "cells": [[("ATRAVIESA", ["Rápido inicio"]), ("Propofol, tiopental", [])],
             [("No atraviesa", []), ("Neostigmina", [])],
             [("Menos fármaco libre", []), ("Menor paso", [])],
             [("Ionizado no pasa", []), ("Depende del pH", [])]]},
  ["Tamaño pequeño y baja ionización también ayudan.",
   "La redistribución explica el despertar rápido del tiopental.",
   "Neostigmina (amonio cuaternario) no entra al SNC."],
  GOODMAN)

# GAS-053 · radial
V("radial", "GAS-053", "pancreatitis-disnea-hipoxemia-alteracion-vq", "Hipoxemia en la pancreatitis",
  "GASTROENTEROLOGÍA ENAM: COMPLICACIONES PULMONARES DE LA PANCREATITIS", "GASTROENTEROLOGÍA",
  ("Hipoxemia en la pancreatitis aguda", ["Atelectasias basales y derrame pleural",
   "Zonas perfundidas mal ventiladas: alteración V/Q"]),
  ("Varón de 48 años con pancreatitis moderada", ["Disnea leve y taquipnea", "SatO₂ 92%"]),
  {"rotulo": "Mapa del tema", "centro": "PANCREATITIS", "centro_sub": "Pulmón", "ans": 0,
   "items": [("ALTERACIÓN V/Q", ["Atelectasias y derrame", "Hipoxemia"]),
             ("Derrame pleural", ["Izquierdo, rico en amilasa"]),
             ("Dolor", ["Limita la respiración"]),
             ("SDRA", ["Forma grave"]),
             ("Distensión", ["Eleva el diafragma"])],
   "ruta": ["Inflamación pancreática", "Atelectasias y derrame", "Mala ventilación", "ALTERACIÓN V/Q"]},
  ["La hipoxemia temprana es marcador de gravedad.",
   "SDRA: infiltrados bilaterales e hipoxemia refractaria.",
   "Oxígeno para SatO₂ > 95% en la fase inicial."],
  "ACG – Management of acute pancreatitis (2024) · " + HARRISON)

# INF-075 · embudo
V("embudo", "INF-075", "sida-cd4-30-ulceras-esofagicas-inclusiones-cmv-ganciclovir", "Esofagitis en SIDA",
  "INFECTOLOGÍA ENAM: ESOFAGITIS POR CITOMEGALOVIRUS", "INFECTOLOGÍA",
  ("Esofagitis por citomegalovirus", ["CD4 < 50: úlceras grandes y serpiginosas en el esófago distal",
   "Biopsia: inclusiones intranucleares («ojo de búho»)"]),
  ("Varón de 32 años con SIDA, CD4 30", ["Odinofagia y disfagia progresiva", "Úlceras serpiginosas · biopsia con inclusiones"]),
  {"rotulo": "Embudo de tratamiento",
   "inicio": "Esofagitis ulcerosa en SIDA",
   "candidatos": ["Ganciclovir", "Fluconazol", "Aciclovir", "Corticoides", "Foscarnet"],
   "pasos": [("Úlceras, no placas blancas", ["Fluconazol"]),
             ("Inclusiones de CMV, no vesículas", ["Aciclovir", "Corticoides"]),
             ("Foscarnet: segunda línea (nefrotóxico)", ["Foscarnet"])],
   "final": ("GANCICLOVIR", ["O valganciclovir oral", "Iniciar o ajustar el TAR"]),
   "nota": "Úlceras aftosas idiopáticas del VIH: responden a corticoides."},
  ["Candida: la causa más frecuente de esofagitis en SIDA.",
   "Herpes: úlceras pequeñas y superficiales.",
   "Ganciclovir: vigilar neutropenia."],
  "NIH/CDC/IDSA – Guidelines for opportunistic infections in HIV: CMV (2024)")

# NEU-039 · puntaje
V("puntaje", "NEU-039", "gestante-tos-perdida-peso-abuela-tos-tuberculosis", "Sospecha de TB en la gestante",
  "NEUMOLOGÍA ENAM: TUBERCULOSIS EN EL EMBARAZO", "NEUMOLOGÍA",
  ("Tuberculosis pulmonar en el embarazo", ["Tos > 2 semanas, fiebre, baja de peso y contacto",
   "Confirmar con baciloscopia y prueba molecular"]),
  ("Gestante de 20 semanas", ["Tos > 2 semanas, sensación febril, baja de peso", "Abuela fallecida por «tos» · crepitantes bilaterales"]),
  {"rotulo": "Datos de sospecha en el caso", "escala": "Sospecha de TB", "total": 4, "max": 5,
   "total_label": "Datos presentes",
   "interpreta": "Tuberculosis pulmonar probable",
   "items": [("Tos > 2 semanas", "1", True), ("Fiebre", "1", True),
             ("Pérdida de peso", "1", True), ("Contacto con TB", "1", True),
             ("Sudoración nocturna", "1", False)],
   "bandas": [("0-1", "Poco probable", "Otras causas", False),
              ("≥ 2", "Probable", "Baciloscopia y prueba molecular; Rx con protección", True)]},
  ["El esquema HRZE es seguro en el embarazo (+ piridoxina).",
   "Evitar estreptomicina: ototóxica fetal.",
   "Las contracciones leves pueden deberse a la fiebre y la tos."],
  "MINSA – NTS N.° 200-MINSA/DGIESP-2023 (Tuberculosis) · OMS – TB and pregnancy (2022)")

# GIN-143 · termómetro
V("termometro", "GIN-143", "bolo-oxitocina-bradicardia-fetal-hipertonia", "Oxitocina e hipertonía uterina",
  "OBSTETRICIA ENAM: HIPERTONÍA UTERINA", "OBSTETRICIA",
  ("Hipertonía uterina por oxitocina", ["El útero no se relaja: baja el flujo al feto",
   "Taquicardia y luego bradicardia fetal"]),
  ("Gestante en expulsivo agotada", ["Recibe bolo de oxitocina", "Taquicardia fetal y luego bradicardia"]),
  {"rotulo": "Actividad uterina",
   "niveles": [("3-5 / 10 min", "Normal", ["Relaja entre contracciones"]),
               ("> 5 / 10 min", "Taquisistolia", ["Vigilar la FCF"]),
               ("Tono alto", "Hipertonía", ["Sin relajación"])],
   "caso_nivel": 2, "ruta_titulo": "Conducta", "paso_label": "PASO",
   "pasos": [(1, "SUSPENDER LA OXITOCINA", ["Nunca en bolo"], True),
             (2, "Decúbito lateral + O₂ + fluidos", ["Reanimación intrauterina"], False),
             (3, "Tocolítico agudo", ["Terbutalina si persiste"], False)]},
  ["La oxitocina se da en infusión con bomba, no en bolo.",
   "Bolo EV también puede causar hipotensión materna.",
   "Si no mejora: parto por la vía más rápida."],
  "ACOG – Practice Bulletin N.° 107: Induction of labor (2009, reafirmado 2022) · " + WILLIAMS)
