"""Bloque ENAM 2026 · Ginecología y Obstetricia (parte 3)."""
from c26 import S, D, P, B, ILU, Q, L, WILLIAMS, MINSA
import ilu7 as I

O = I.ORANGE
ESP = "GINECO-OBSTETRICIA ENAM"
ACOG = "ACOG Practice Bulletins"

# GIN-267 · Prolapso de cúpula · BALANZA + franja
S("balanza", "GIN-267", "prolapso-cupula-vaginal-sexualmente-activa-colposacropexia",
  "Prolapso de cúpula vaginal en mujer sexualmente activa: colposacropexia",
  "Prolapso de órganos pélvicos · prolapso apical", ESP,
  ("Prolapso de cúpula vaginal", ["Tras una histerectomía, el fondo de la vagina desciende.",
                                  "La técnica depende de si la paciente quiere conservar la vagina funcional."]),
  ("Mujer de 60 años, sexualmente activa", ["Histerectomía abdominal hace 15 años.", "Prolapso estadio IV: cúpula a +7 cm."]),
  ["Prolapso de cúpula grave en mujer sexualmente activa: colposacropexia (malla del ápice vaginal al promontorio).",
   "Conserva la longitud y el eje de la vagina.",
   "Colpocleisis: solo en mujeres sin deseo de vida sexual (cierra la vagina)."],
  "ACOG n.º 214 (2019); Te Linde Ginecología Quirúrgica 12.ª ed.",
  d=dict(rotulo="¿Qué técnica pesa más en esta paciente?", gana="izq", tag="ESTE CASO",
         pregunta="Prolapso de cúpula estadio IV, vida sexual activa",
         izq=dict(titulo="Colposacropexia laparoscópica", peso="elige",
                  items=["Fija el ápice vaginal al promontorio con malla", "Conserva la vagina funcional", "Muy duradera para el prolapso apical"]),
         der=dict(titulo="Colpocleisis total", peso="no",
                  items=["Cierra el canal vaginal", "Impide las relaciones sexuales", "Ideal en mujeres mayores sin vida sexual"]),
         veredicto=("Colposacropexia laparoscópica", ["La colporrafia sola no corrige el defecto apical."])),
  banda=B("Qué corrige la malla", D(lambda s, x, y: I.pelvis_sagital(s, x, y, "cupula_malla"), 320, 306),
          ["Sin útero, la cúpula vaginal se evierte fuera del introito.", "La malla (azul) sube el ápice y lo fija al promontorio sacro.",
           "Así la vagina conserva longitud y eje."]),
  tabla=("Opciones de la pregunta", [("Colpocleisis", False), ("Colpoperineoplastía anterior", False), ("Colposacropexia", True),
                                     ("Colporrafia ant. y post.", False)],
         [("¿Corrige el ápice y conserva la vagina?", ["No: la cierra", "No: no corrige el ápice", "Sí", "No: no corrige el ápice"])]))

# GIN-268 · Prolapso con úlcera cervical · ÁRBOL + franja
S("arbol", "GIN-268", "prolapso-uterino-estadio-4-ulcera-cervical-biopsia-colpocleisis",
  "Prolapso uterino con úlcera cervical: primero biopsia, luego colpocleisis",
  "Prolapso de órganos pélvicos · lesión cervical", ESP,
  ("Lesión sospechosa en un prolapso", ["Una úlcera friable que sangra puede ser un cáncer de cuello.",
                                        "Primero se sabe qué es y después se opera."]),
  ("Mujer de 85 años sin vida sexual hace > 10 años", ["Prolapso uterino estadio IV de larga evolución.",
                                                       "Sangrado reciente; cérvix expuesto con lesión ulcerada y friable."]),
  ["Lesión cervical sospechosa: biopsia dirigida antes de cualquier cirugía.",
   "Benigna (úlcera de decúbito) + sin vida sexual + edad avanzada: colpocleisis (cirugía corta y eficaz).",
   "Maligna: tratar el cáncer de cuello según su estadio."],
  "ACOG n.º 214; guía NCCN de cáncer de cuello uterino.",
  arbol=Q("¿Hay una lesión cervical sospechosa (úlcera friable que sangra)?", [
      Q("Resultado de la biopsia dirigida", [
          L("Benigna", "COLPOCLEISIS", ["85 años y sin vida sexual", "Estrógeno local previo para la úlcera"], path=True),
          L("Maligna", "Tratar el cáncer", ["Estadificación y manejo oncológico"])], edge="Sí: biopsia", path=True),
      L("No", "Pesario o cirugía del prolapso", ["Según deseo y estado general"])], path=True),
  banda=B("Lo que se ve", D(lambda s, x, y: I.pelvis_sagital(s, x, y, "uterino"), 320, 306),
          ["Útero descendido: el cérvix queda fuera de la vulva.", "Úlcera friable en el cérvix expuesto: puede ser decúbito o cáncer.",
           "Por eso la biopsia va primero."], ans=1),
  tabla=("Opciones de la pregunta", [("Histerectomía sin biopsia", False), ("Biopsia y colpocleisis si benigna", True),
                                     ("Colporrafia con cierre", False), ("Estrógenos y pesario", False)],
         [("Problema", ["Opera sin saber si es cáncer", "Ninguno", "No estudia la lesión", "Retrasa el diagnóstico"])]))

# GIN-269 · Fórmula obstétrica · CÁLCULO
S("calculo", "GIN-269", "formula-obstetrica-mola-cesarea-36-semanas-g3-p1112",
  "Fórmula obstétrica con mola y cesárea pretérmino: G3 P1112",
  "Historia obstétrica · fórmula G P", ESP,
  ("Fórmula obstétrica", ["G = total de gestaciones, sin importar cómo terminaron.",
                          "P = cuatro números: a término, pretérmino, abortos, hijos vivos."]),
  ("Mujer de 34 años", ["Hijo de 6 años por parto eutócico a las 38 semanas; mola evacuada hace 2 años.",
                        "Hoy: cesárea a las 36 semanas por eclampsia, recién nacido vivo."]),
  ["La mola cuenta como gestación y como aborto (termina antes de las 20-22 semanas).",
   "A término = 37 semanas o más; pretérmino = antes de las 37.",
   "El último número son los hijos vivos actualmente (2)."],
  "Williams Obstetricia; " + MINSA + ", historia clínica perinatal.",
  d=dict(rotulo="Se cuenta casilla por casilla", tag="ESTE CASO",
         ilu_titulo="Sus embarazos",
         ilu=ILU(D(lambda s, x, y: I.embarazos_linea(s, x, y + 6, [("Parto a las 38 sem", "hijo de 6 años", "a término + vivo", "#16a34a"),
                                                                    ("Mola hace 2 años", "evacuación", "aborto", "#7c3aed"),
                                                                    ("Cesárea a las 36 sem", "recién nacido vivo", "pretérmino + vivo", O)]), 218, 400)),
         ilu_pie="Tres gestaciones: dos hijos vivos y un aborto (la mola).",
         pasos=[("G: gestaciones", ["Parto, mola y la actual = 3."], False),
                ("T: a término", ["Solo el parto de 38 semanas = 1."], False),
                ("P: pretérmino", ["La cesárea de 36 semanas = 1."], False),
                ("A: abortos", ["La mola = 1."], False),
                ("V: hijos vivos", ["El de 6 años y el recién nacido = 2."], False),
                ("Resultado", ["G3 P1112"], True)]),
  tabla=("Opciones de la pregunta", [("G3 P2012", False), ("G3 P1112", True), ("G2 P1112", False), ("G2 P2012", False)],
         [("Error", ["Cuenta las 36 sem como término", "Ninguno", "No cuenta la mola como gestación", "Dos errores juntos"])]))

# GIN-270 · Torsión en fase folicular · CRONOLOGÍA del ciclo
S("cronologia", "GIN-270", "dolor-subito-fosa-iliaca-izquierda-dia-7-ciclo-quiste-torcido",
  "Dolor súbito con masa anexial al día 7 del ciclo: quiste a pedículo torcido",
  "Dolor pélvico agudo · torsión anexial", ESP,
  ("Dolor pélvico y día del ciclo", ["El cuerpo lúteo hemorrágico aparece en la fase lútea (después de ovular).",
                                     "La torsión puede ocurrir en cualquier momento, con dolor brusco y masa dolorosa."]),
  ("Mujer de 25 años, FUR hace 7 días", ["Dolor súbito e intenso en FII de 4 h que empeora al moverse.",
                                         "Masa anexial izquierda muy dolorosa; sin sangrado."]),
  ["Dolor brusco que empeora con el movimiento + masa anexial dolorosa = quiste a pedículo torcido.",
   "Día 7 del ciclo (fase folicular): aún no hay cuerpo lúteo y el embarazo es improbable.",
   "Urgencia quirúrgica: laparoscopía para destorcer y conservar el ovario."],
  ACOG + " n.º 783; " + WILLIAMS + ".",
  d=dict(rotulo="En qué momento del ciclo está", tag="ESTE CASO",
         ilu_titulo="Anexo izquierdo torcido",
         ilu=ILU(D(lambda s, x, y: I.anexo_torsion(s, x, y + 20, "izq"), 330, 240)),
         ilu_pie="El ovario izquierdo girado sobre su pedículo: isquemia y dolor.",
         claves=[("Quiste a pedículo torcido", ["Dolor súbito + masa dolorosa: cualquier fase."], True),
                 ("Cuerpo lúteo hemorrágico", ["Fase lútea (después del día 14)."], False),
                 ("Ectópico o aborto", ["Requieren embarazo: FUR hace 7 días, poco probable."], False)],
         eje_titulo="Días del ciclo menstrual", eje=(0, 28), paso=7, marca=7, unidad="d", eje_nombre="días del ciclo",
         hitos=[(1, 5, "Menstruación", "FUR", False), (1, 14, "Fase folicular", "este caso: día 7", True),
                (13, 15, "Ovulación", "", False), (15, 28, "Fase lútea", "cuerpo lúteo hemorrágico", False)]),
  tabla=("Opciones de la pregunta", [("Ectópico tubárico", False), ("Quiste torcido", True), ("Cuerpo lúteo hemorrágico", False),
                                     ("Aborto incompleto", False)],
         [("¿Encaja con el día 7?", ["No: menstruó hace 7 días", "Sí", "No: aparece en fase lútea", "No: sin embarazo ni sangrado"])]))

# GIN-271 · Adenomiosis · EMBUDO + franja
S("embudo", "GIN-271", "utero-globuloso-blando-menorragia-dismenorrea-progresiva-adenomiosis",
  "Útero grande, globuloso y blando con dismenorrea progresiva: adenomiosis",
  "Sangrado uterino y dolor pélvico · adenomiosis", ESP,
  ("Útero aumentado de tamaño", ["Miomas: útero grande, irregular y duro.",
                                 "Adenomiosis: útero grande, regular, globuloso y blando, con dismenorrea."]),
  ("Mujer de 42 años, G3 P3003, 3 cesáreas", ["Menstruaciones abundantes (6 toallas/día por 8 días).",
                                               "Dismenorrea progresiva; útero de 12 cm, regular, globuloso y blando."]),
  ["Multípara > 40 años con menorragia + dismenorrea progresiva + útero globuloso blando = adenomiosis.",
   "Cesáreas y legrados previos aumentan el riesgo.",
   "Confirmación por eco TV o resonancia; tratamiento: DIU de levonorgestrel o histerectomía si ya no desea hijos."],
  "ACOG; Williams Ginecología 4.ª ed.",
  d=dict(rotulo="Del útero grande al diagnóstico", inicio="Útero de 12 cm con menorragia y dismenorrea",
         candidatos=["Miomatosis", "Pólipo endometrial", "Adenomiosis", "Cáncer de endometrio"],
         pasos=[("¿Útero irregular, duro, con nódulos?", ["Miomatosis"]),
                ("¿Sangrado intermenstrual con útero normal?", ["Pólipo endometrial"]),
                ("¿Posmenopausia o sangrado posmenopáusico?", ["Cáncer de endometrio"])],
         final=("Adenomiosis", ["Útero globuloso, regular y blando; dismenorrea progresiva"]),
         nota="El útero es grande pero simétrico y blando: el endometrio infiltra todo el miometrio."),
  banda=B("El útero del caso", D(lambda s, x, y: I.utero_frontal(s, x, y, "adenomiosis"), 300, 240),
          ["Miometrio engrosado de forma difusa, con islotes de endometrio (puntos).", "Sangra más y duele más con cada menstruación.",
           "No forma nódulos como los miomas."], ans=0),
  tabla=("Opciones de la pregunta", [("Leiomiomatosis", False), ("Pólipo endometrial", False), ("Adenomiosis", True), ("Cáncer de endometrio", False)],
         [("Útero", ["Irregular y duro", "Normal", "Globuloso y blando", "Sangrado posmenopáusico"])]))

# GIN-272 · Implante subdérmico · TARJETAS + franja
_impl = I.P("M186 150 L180 176", "none", "#1d4ed8", 5, 'stroke-linecap="round"') + I.t(196, 140, "implante", "#1d4ed8", 10, "start")
S("tarjetas", "GIN-272", "anticoncepcion-no-puede-tomar-pastillas-riesgo-its-implante",
  "Anticoncepción para quien olvida pastillas y tiene riesgo de ITS: implante + condón",
  "Planificación familiar · elección del método", ESP,
  ("Elección del método anticonceptivo", ["Se cruza lo que la persona necesita con lo que su historia permite (criterios OMS).",
                                          "Los métodos de larga duración no dependen de la memoria diaria."]),
  ("Mujer de 22 años, nuligesta", ["Tres parejas en el último año, clamidia previa, condón intermitente.",
                                   "Dos abortos inducidos; no logra tomar pastillas a diario."]),
  ["Implante subdérmico: muy eficaz (> 99 %), dura 3 años y no depende de la usuaria.",
   "Con riesgo alto de ITS o infección cervical actual, el DIU no se inserta hasta tratar (riesgo de EPI).",
   "Siempre sumar condón: ningún método hormonal protege de las ITS (doble protección)."],
  "OMS, criterios médicos de elegibilidad 5.ª ed.; " + MINSA + ", norma de planificación familiar.",
  d=dict(rotulo="Cuatro métodos frente al caso", ans=3,
         cards=[dict(titulo="Píldora de progestágeno", datos=[("Uso", "Diario, horario estricto", False),
                                                             ("Eficacia típica", "Baja si olvida", False), ("Protege de ITS", "No", False)],
                     pie="Falla con olvidos."),
                dict(titulo="Dispositivo intrauterino", datos=[("Uso", "Larga duración", True), ("Riesgo de ITS", "Precaución", False),
                                                               ("Protege de ITS", "No", False)], pie="Con ITS reciente: tratar antes."),
                dict(titulo="Diafragma", datos=[("Uso", "En cada relación", False), ("Eficacia típica", "Baja", False),
                                                ("Protege de ITS", "No", False)], pie="Poco eficaz."),
                dict(titulo="Implante subdérmico", datos=[("Uso", "Nada diario: 3 años", True), ("Eficacia", "> 99 %", True),
                                                          ("Con riesgo de ITS", "Sí se puede", True)], pie="Más condón (doble protección).")]),
  banda=B("Dónde va el implante", D(lambda s, x, y: I.cuerpo(s, x + 30, y, {"brazo_i": "#dbeafe"}, extra=_impl, sc=0.75), 240, 334),
          ["Varilla en la cara interna del brazo no dominante.", "Libera etonogestrel por 3 años.", "Se inserta y retira en consultorio."]),
  tabla=("Opciones de la pregunta", [("Píldora de progestágeno", False), ("DIU", False), ("Diafragma", False), ("Implante", True)],
         [("Problema", ["Olvida pastillas", "Riesgo de ITS/EPI reciente", "Poco eficaz", "Ninguno (+ condón)"])]))

# GIN-273 · Diástasis de sínfisis · RADIAL + franja
S("radial", "GIN-273", "puerpera-parto-macrosomico-dolor-pubico-diastasis-sinfisis",
  "Dolor púbico intenso tras parto de 4 200 g: diástasis de la sínfisis del pubis",
  "Puerperio · lesiones del parto", ESP,
  ("Diástasis de la sínfisis del pubis", ["Las hormonas del embarazo relajan los ligamentos de la pelvis.",
                                          "Un feto grande puede separar la sínfisis más de lo normal (> 10 mm)."]),
  ("Puérpera de 24 h, parto vaginal de 4 200 g", ["Dolor intenso en el pubis y la región lumbar irradiado a los muslos.",
                                                  "No puede caminar; dolor muy intenso a la palpación de la sínfisis."]),
  ["Dolor exactamente sobre la sínfisis que impide caminar tras un parto macrosómico = diástasis de la sínfisis.",
   "Confirmación con Rx o eco (separación > 10 mm).",
   "Tratamiento: reposo, analgesia, faja pélvica y fisioterapia; cirugía solo en separaciones grandes."],
  WILLIAMS + "; ACOG.",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Dolor sobre la sínfisis tras parto grande",
         items=[("Diástasis de la sínfisis", ["Dolor localizado en el pubis, no puede caminar"]),
                ("Luxación sacrococcígea", ["Dolor en el cóccix al sentarse"]),
                ("Fractura del acetábulo", ["Rara sin trauma de alta energía"]),
                ("Bloqueo motor epidural", ["Debilidad sin dolor; cede en horas"])],
         ruta=["Feto de 4 200 g", "Dolor púbico a las 24 h", "Dolor a la palpación de la sínfisis", "Diástasis"]),
  banda=B("La pelvis del caso", D(lambda s, x, y: I.pelvis_sinfisis(s, x, y), 330, 250),
          ["La unión de los dos pubis se separa.", "Duele al caminar, al pararse en un pie y al palpar la sínfisis.",
           "Se confirma con imagen: > 10 mm."]),
  tabla=("Opciones de la pregunta", [("Luxación sacrococcígea", False), ("Fractura de acetábulo", False), ("Diástasis de sínfisis", True),
                                     ("Bloqueo epidural", False)],
         [("¿Encaja?", ["No: el dolor sería en el cóccix", "No", "Sí", "No: no duele"])]))

# GIN-275 · Sífilis congénita · MAPA DE SIGNOS (lactante)
S("mapa_signos", "GIN-275", "chancro-materno-no-tratado-sifilis-congenita-nariz-silla-montar",
  "Úlcera genital indolora no tratada en la madre: sífilis congénita en el niño",
  "Infecciones congénitas · sífilis", ESP,
  ("Sífilis congénita", ["El Treponema pallidum cruza la placenta si la madre no se trata.",
                         "Deja lesiones óseas, hepáticas, nasales, cutáneas y del oído."]),
  ("Gestante de 24 años sin controles", ["Úlcera genital indolora 8 meses antes, no tratada.",
                                         "Eco: lesiones metafisarias y placenta gruesa; el bebé: hipoacusia, hepatomegalia y nariz en silla de montar."]),
  ["Úlcera genital indolora = chancro sifilítico; sin tratamiento se transmite al feto.",
   "Tamizar sífilis en el primer control, a las 28 semanas y en el parto; tratar con penicilina benzatínica.",
   "Rubeola, CMV y toxoplasma dan otros hallazgos (cataratas, calcificaciones, coriorretinitis)."],
  "CDC, guía de ITS (2021); " + MINSA + ", norma de eliminación de la transmisión materno-infantil.",
  d=dict(rotulo="Los signos del niño", PH=430, tag="ESTE CASO",
         ilu_titulo="El recién nacido del caso",
         ilu=lambda s, x, y: I.bebe(s, x + 30, y + 10, {"higado": "#fdba74"}, sc=0.95,
                                    marcas=[(1, 120, 80), (2, 60, 70), (3, 150, 196), (4, 72, 290)]),
         ilu_pie="1 nariz, 2 oído, 3 hígado, 4 huesos largos.",
         signos=[dict(tit="Nariz en silla de montar", lines=["Destrucción del cartílago nasal (rinitis sifilítica previa)."]),
                 dict(tit="Hipoacusia neurosensorial", lines=["Daño del octavo par (tardío)."]),
                 dict(tit="Hepatomegalia", lines=["Hepatitis por el treponema; puede haber ictericia."]),
                 dict(tit="Lesiones metafisarias de huesos largos", lines=["Osteocondritis y periostitis; se vio en la eco."]),
                 dict(tit="Causa: Treponema pallidum", on=True, lines=["Madre con chancro (úlcera indolora) no tratado."])]),
  tabla=("Opciones de la pregunta", [("Citomegalovirus", False), ("Rubeola", False), ("Treponema pallidum", True), ("Toxoplasma", False)],
         [("Clave", ["Calcificaciones periventriculares", "Cataratas y cardiopatía", "Chancro, nariz en silla de montar", "Coriorretinitis, hidrocefalia"])]))

# GIN-276 · Detención de la fase activa · MATRIZ + franja partograma
S("matriz", "GIN-276", "trabajo-parto-6-cm-4-horas-sin-cambio-detencion-fase-activa",
  "6 cm durante 4 horas con buenas contracciones: detención de la fase activa",
  "Trabajo de parto · alteraciones del progreso", ESP,
  ("Fases del trabajo de parto", ["Latente: hasta los 6 cm. Activa: desde los 6 cm hasta la dilatación completa.",
                                  "En fase activa se espera avance; si no avanza con buena dinámica, hay detención."]),
  ("Primigesta de 39 semanas", ["6 cm, AP -2, contracciones moderadas cada 3 minutos.",
                                "4 horas después: sigue en 6 cm y AP -2; LCF normales."]),
  ["≥ 6 cm sin cambio por ≥ 4 h con contracciones adecuadas (o ≥ 6 h si son inadecuadas) = detención de la fase activa.",
   "Con membranas íntegras suele intentarse amniotomía y oxitocina antes de indicar cesárea.",
   "Fase latente prolongada: > 20 h en nulíparas antes de los 6 cm."],
  "ACOG/SMFM, prevención de la primera cesárea (2014); " + WILLIAMS + ".",
  d=dict(rotulo="Fase y progreso", eje_x="Progreso", eje_y="Fase", caso=(1, 1),
         cols=["Progresa", "No progresa"], rows=["Latente (< 6 cm)", "Activa (≥ 6 cm)", "Expulsivo"],
         cells=[[("Normal", ["Puede durar muchas horas"]), ("Fase latente prolongada", ["> 20 h en nulíparas"])],
                [("Normal", ["≥ 1 cm/h aprox."]), ("Detención de la fase activa", ["≥ 4 h sin cambio con buena dinámica"])],
                [("Normal", ["El feto desciende"]), ("Expulsivo prolongado", ["> 3 h en nulíparas (con epidural, más)"])]]),
  banda=B("Partograma del caso", D(lambda s, x, y: I.partograma(s, x, y, sc=0.9), 414, 225),
          ["A las 0 h: 6 cm, AP -2.", "A las 4 h: 6 cm, AP -2, con 1 contracción cada 3 min.",
           "La línea verde muestra el avance esperado: no lo hay."], ans=1),
  tabla=("Opciones de la pregunta", [("Falso trabajo de parto", False), ("Detención de fase activa", True), ("Latente prolongada", False),
                                     ("Expulsivo prolongado", False)],
         [("Por qué", ["Ya tiene 6 cm y contracciones regulares", "6 cm, 4 h sin cambio", "Ya pasó los 6 cm", "No está en expulsivo"])]))

# GIN-277 · Hierro desde las 14 semanas · CRONOLOGÍA
S("cronologia", "GIN-277", "suplementacion-hierro-gestante-desde-14-semanas-minsa",
  "Hierro profiláctico en la gestante: desde las 14 semanas",
  "Atención prenatal · suplementación con micronutrientes", ESP,
  ("Suplementación en la gestación (MINSA)", ["Ácido fólico desde antes del embarazo y en el primer trimestre.",
                                              "Hierro + ácido fólico desde las 14 semanas hasta el posparto; calcio desde las 20."]),
  ("Gestante de bajo riesgo sin anemia", ["Control prenatal oportuno.", "¿Desde qué semana se inicia el hierro profiláctico?"]),
  ["Hierro profiláctico: 60 mg de hierro elemental + 400 µg de ácido fólico al día desde las 14 semanas.",
   "Esperar al 2.º trimestre evita empeorar las náuseas del primero; la demanda de hierro sube desde entonces.",
   "Si hay anemia, la dosis es de tratamiento (120 mg) desde el diagnóstico."],
  MINSA + ", norma de suplementación con micronutrientes; RM 251-2024-MINSA (anemia).",
  d=dict(rotulo="Qué se da y desde cuándo", tag="ESTE CASO",
         ilu_titulo="La gestante",
         ilu=ILU(D(lambda s, x, y: I.gestante(s, x + 100, y, sc=0.6), 330, 270)),
         ilu_pie="Hierro profiláctico desde el segundo trimestre.",
         claves=[("Hierro + ácido fólico", ["Desde las 14 semanas hasta 30 días posparto."], True),
                 ("Ácido fólico solo", ["Desde antes de embarazarse hasta las 13 semanas."], False),
                 ("Calcio", ["Desde las 20 semanas (prevención de preeclampsia)."], False)],
         eje_titulo="Semanas de gestación", eje=(0, 40), paso=4, marca=14, unidad="sem",
         hitos=[(0, 13, "Ácido fólico", "desde antes y hasta las 13 sem", False), (14, 40, "Hierro + ácido fólico", "profilaxis diaria", True),
                (20, 40, "Calcio", "desde las 20 semanas", False)]),
  tabla=("Opciones de la pregunta", [("14", True), ("28", False), ("10", False), ("20", False)],
         [("¿Es la norma?", ["Sí", "Demasiado tarde", "Demasiado temprano", "Es cuando se inicia el calcio"])]))
