"""Bloque ENAM 2026 · Pediatría (parte 1)."""
from c26 import S, D, P, B, ILU, Q, L, NELSON, MINSA
import ilu7 as I

O = I.ORANGE
ESP = "PEDIATRÍA ENAM"

# PED-242 · Tamizaje de cardiopatía crítica en la altura · SEMÁFORO
_sondas = (I.C(40, 180, 9, "#1d4ed8", "#ffffff", 2) + I.t(40, 206, "pre 87 %", "#1d4ed8", 10.5)
           + I.C(160, 308, 9, "#1d4ed8", "#ffffff", 2) + I.t(186, 326, "post 86 %", "#1d4ed8", 10.5))
S("semaforo", "PED-242", "tamizaje-cardiopatia-critica-altura-la-oroya-repetir-oximetria",
  "Tamizaje de cardiopatía congénita crítica en la altura: zona intermedia, repetir en 1 hora",
  "Neonatología · tamizaje con oximetría de pulso", ESP,
  ("Tamizaje de cardiopatía congénita crítica", ["Oximetría en la mano derecha (preductal) y un pie (postductal).",
                                                 "En la altura la saturación normal es menor: el algoritmo peruano ajusta los puntos de corte."]),
  ("Neonato de 4 días en La Oroya (3745 msnm)", ["Estable, sin quejido ni tiraje, buena perfusión.",
                                                 "SatO₂ preductal 87 % y postductal 86 %, bien medidas y repetidas."]),
  ["En la altura, valores en zona intermedia (85-90 % en La Oroya) sin síntomas: repetir la oximetría en 1 hora.",
   "Si sigue en zona intermedia (hasta 3 mediciones) o baja del umbral: referir para ecocardiografía.",
   "Si hay cianosis, dificultad respiratoria o mala perfusión, no se espera: se estabiliza y se refiere."],
  MINSA + " y Sociedad Peruana de Pediatría, tamizaje de cardiopatía congénita crítica en la altura; " + NELSON + ".",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="Dónde se mide",
         ilu=ILU(D(lambda s, x, y: I.bebe(s, x + 14, y + 4, extra=_sondas, sc=0.95), 270, 320)),
         ilu_pie="Mano derecha (preductal) y pie (postductal): diferencia de 1 %.",
         check_titulo="Datos del caso",
         check=[("Estable, sin quejido ni tiraje", True), ("Buena perfusión periférica", True),
                ("SatO₂ 87 % y 86 %: zona intermedia a 3745 msnm", False), ("Medición confiable y repetida", True)],
         ans=1, tag="ESTE CASO",
         luces=[("Sobre el umbral de la altitud", "Pasa el tamizaje", ["Alta con controles habituales."]),
                ("Zona intermedia, sin síntomas", "Repetir en 1 hora", ["Hasta 3 veces; si persiste: referir."]),
                ("Bajo el umbral o con síntomas", "Referir ya", ["Ecocardiografía; prostaglandina si hay cardiopatía ductus dependiente."])]),
  tabla=("Opciones de la pregunta", [("Rx de tórax y luego decidir", False), ("Referir para prostaglandina", False),
                                     ("Repetir en 1 hora", True), ("Referir para eco urgente", False)],
         [("¿Adecuada ahora?", ["No: no define cardiopatía", "No: sin sospecha clara", "Sí", "Aún no: zona intermedia"])]))

# PED-243 · Tamizaje auditivo · ÁRBOL + franja
_ondas = "".join(I.P(f"M{36-k*8} {70-k*6} q-8 {12+k*6} 0 {24+k*12}", "none", "#1d4ed8", 2) for k in range(3))
S("arbol", "PED-243", "lactante-2-meses-sifilis-materna-sin-tamizaje-auditivo-otoemisiones",
  "Lactante con riesgo y sin tamizaje auditivo: referir para otoemisiones o potenciales",
  "Tamizaje neonatal · audición", ESP,
  ("Tamizaje auditivo", ["Universal: antes del mes de vida, con otoemisiones acústicas (OEA) o potenciales evocados (PEATC).",
                         "Con factores de riesgo o sin tamizaje: evaluación audiológica sin esperar."]),
  ("Lactante de 2 meses en CRED", ["Madre con sífilis al parto (bebé tratado); nunca tuvo tamizaje auditivo.",
                                   "«A veces no se despierta con ruidos fuertes»; parpadea con ruidos intensos."]),
  ["Sin tamizaje neonatal + factor de riesgo (infección congénita) + preocupación materna: referir a audiología ya.",
   "Meta 1-3-6: tamizar al mes, diagnosticar a los 3 meses, intervenir antes de los 6.",
   "El parpadeo ante ruidos intensos no descarta una hipoacusia moderada."],
  "JCIH (2019); " + MINSA + ", tamizaje auditivo neonatal.",
  arbol=Q("¿Tiene tamizaje auditivo neonatal normal?", [
      L("Sí y sin riesgo", "Vigilancia en CRED", ["Hitos de audición y lenguaje"]),
      L("No, o hay riesgo o preocupación", "REFERIR A AUDIOLOGÍA", ["Otoemisiones o potenciales evocados", "Antes de los 3 meses"], path=True)], path=True),
  banda=B("Por qué preocupa", D(lambda s, x, y: I.bebe(s, x + 30, y, extra=_ondas, marcas=[(1, 64, 70)], sc=0.9), 250, 300),
          ["Oído: nunca se evaluó con un equipo.", "La sífilis congénita puede dar hipoacusia neurosensorial aun tratada.",
           "Los padres notan que reacciona poco a los sonidos."], ans=0),
  tabla=("Opciones de la pregunta", [("Reevaluar a los 3 meses", False), ("Evitar ruidos", False), ("Referir para OEA o PEATC", True),
                                     ("Solo estimulación en casa", False)],
         [("Problema", ["Retrasa el diagnóstico", "No evalúa", "Ninguno", "No evalúa"])]))

# PED-244 · Compromiso alveolointersticial · ANATOMÍA
S("anatomia", "PED-244", "lactante-quejido-crepitantes-finos-compromiso-alveolointersticial",
  "Quejido y crepitantes finos difusos: compromiso alveolointersticial",
  "Dificultad respiratoria del lactante · localizar el nivel", ESP,
  ("Dónde está el problema respiratorio", ["Cada nivel tiene su signo: estridor (extratorácico), sibilancias (intratorácico),",
                                          "crepitantes y quejido (alveolointersticial), respiración irregular (central)."]),
  ("Lactante de 4 meses con 24 h de dificultad", ["FR 68, retracciones subcostales, quejido espiratorio.",
                                                  "Crepitantes finos difusos; sin sibilancias ni estridor."]),
  ["Quejido espiratorio + crepitantes finos + taquipnea = compromiso alveolointersticial (neumonía, edema).",
   "El quejido cierra la glotis al final de la espiración para mantener los alveolos abiertos (PEEP propia).",
   "Sin estridor ni sibilancias: no es obstrucción de la vía aérea."],
  NELSON + "; OMS, AIEPI.",
  d=dict(rotulo="Cuatro niveles, cuatro signos", tag="ESTE CASO",
         ilu_titulo="Niveles de la vía respiratoria",
         ilu=lambda s, x, y: I.via_aerea_niveles(s, x + 40, y, caso=2),
         ilu_pie="En naranja, los alveolos: nivel del caso.",
         ans=3,
         puntos=[("Obstrucción extratorácica", ["Estridor inspiratorio (laringitis, cuerpo extraño alto)."]),
                 ("Obstrucción intratorácica", ["Sibilancias y espiración prolongada (bronquiolitis, asma)."]),
                 ("Compromiso alveolointersticial", ["Crepitantes finos, quejido, taquipnea: este caso."]),
                 ("Insuficiencia de origen central", ["Respiración irregular o apneas sin esfuerzo respiratorio."])]),
  tabla=("Opciones de la pregunta", [("Extratorácica", False), ("Alveolointersticial", True), ("Intratorácica", False), ("Central", False)],
         [("Signo típico", ["Estridor", "Crepitantes y quejido", "Sibilancias", "Respiración irregular"])]))

# PED-245 · Raquitismo carencial · CICLO (vitamina D)
S("ciclo", "PED-245", "raquitismo-carencial-deficit-calcitriol-mineralizacion-osea",
  "Raquitismo carencial: sin calcitriol no se absorbe calcio ni fósforo",
  "Nutrición · raquitismo por déficit de vitamina D", ESP,
  ("Raquitismo nutricional", ["Falta vitamina D: el intestino no absorbe calcio ni fósforo.",
                              "El cartílago de crecimiento no se mineraliza: muñecas anchas, rosario costal, piernas arqueadas."]),
  ("Lactante de 15 meses, poca exposición solar", ["Lactancia exclusiva hasta los 10 meses; retraso de la marcha.",
                                                   "Muñecas anchas, rosario costal, genu varo; Rx: metáfisis en copa."]),
  ["Mecanismo: poco calcitriol (1,25-(OH)₂ vitamina D) → menos absorción intestinal de calcio y fósforo → mala mineralización.",
   "La PTH sube para mantener el calcio (calcio normal o bajo, fósforo bajo, fosfatasa alcalina alta).",
   "Prevención: vitamina D 400 UI/día en lactantes con lactancia exclusiva."],
  NELSON + "; Consenso global de raquitismo nutricional (2016).",
  d=dict(rotulo="Qué falla en la vía de la vitamina D", tag="ESTE CASO",
         img_titulo="El niño del caso",
         img=D(lambda s, x, y: I.nino(s, x + 40, y, genu_varo=True, marcas=[(1, 40, 222), (2, 110, 136), (3, 64, 300)], sc=0.86), 280, 330),
         img_pie="1 muñecas anchas, 2 rosario costal, 3 genu varo.",
         centro="Vitamina D", ans=3,
         pasos=[("Sol en la piel", "forma vitamina D3"), ("Hígado", "25-OH vitamina D"), ("Riñón", "1,25-(OH)₂ D: calcitriol"),
                ("Intestino", "absorbe calcio y fósforo"), ("Hueso", "mineraliza el cartílago")],
         claves_titulo="Por qué no las otras",
         claves=[("Toxicidad por vitamina D", ["Daría hipercalcemia, no raquitismo."], False),
                 ("Más reabsorción renal de fósforo", ["Al revés: el fósforo se pierde."], False),
                 ("PTH alta con hipercalcemia", ["La PTH sube, pero el calcio no está alto."], False)]),
  tabla=("Opciones de la pregunta", [("Toxicidad por 25-OH D", False), ("Más reabsorción de fósforo", False), ("PTH con hipercalcemia", False),
                                     ("Mala mineralización por poco calcitriol", True)],
         [("¿Explica el cuadro?", ["No", "No", "No", "Sí"])]))

# PED-246 · Bierman y Pierson · PUNTAJE + franja
S("puntaje", "PED-246", "escala-bierman-pierson-8-puntos-obstruccion-bronquial-moderada",
  "Escala de Bierman y Pierson: este lactante suma 8 (moderada)",
  "Obstrucción bronquial del lactante · gravedad", ESP,
  ("Escala de Bierman y Pierson", ["4 datos (FR, sibilancias, cianosis, tiraje), cada uno de 0 a 3 puntos.",
                                   "Leve 0-4, moderada 5-8, grave 9-12."]),
  ("Lactante de 8 meses", ["FR 58, tiraje subcostal e intercostal.", "Sibilancias audibles sin estetoscopio; cianosis perioral al llorar."]),
  ["A partir de los 6 meses: FR 46-60 = 2 puntos.",
   "Sibilancias audibles sin estetoscopio = 3; tiraje subcostal + intercostal = 2; cianosis perioral con el llanto = 1.",
   "Total 8: obstrucción moderada (tratamiento en emergencia y reevaluar)."],
  "Bierman CW, Pierson WE (1974), modificada; MINSA, guía de síndrome obstructivo bronquial.",
  d=dict(rotulo="Punto por punto", escala="Bierman y Pierson", total=8, max=12, interpreta="Obstrucción moderada",
         items=[("FR 58 (≥ 6 meses: 46-60)", 2, True), ("Sibilancias audibles sin estetoscopio", 3, True),
                ("Cianosis perioral solo con el llanto", 1, True), ("Tiraje subcostal e intercostal", 2, True)],
         bandas=[("0-4", "Leve", "Manejo ambulatorio, broncodilatador.", False), ("5-8", "Moderada", "Nebulizaciones en emergencia y reevaluar.", True),
                 ("9-12", "Grave", "Oxígeno, hospitalizar.", False)]),
  banda=B("Lo que se ve en el lactante", D(lambda s, x, y: I.bebe(s, x + 30, y, marcas=[(1, 120, 100), (2, 120, 170), (3, 120, 214)], sc=0.9), 250, 300),
          ["Cianosis alrededor de la boca solo al llorar: 1 punto.", "Tiraje subcostal e intercostal: 2 puntos.",
           "Sibilancias que se oyen a distancia y FR 58: 3 + 2 puntos."]),
  tabla=("Opciones de la pregunta", [("6", False), ("8", True), ("7", False), ("9", False)],
         [("Por qué", ["Subestima sibilancias o FR", "Suma correcta", "Cuenta 1 en FR o tiraje", "Cuenta 2 en cianosis"])]))

# PED-248 · Sepsis neonatal precoz por SGB · TARJETAS + franja
S("tarjetas", "PED-248", "sepsis-neonatal-precoz-rpm-20-horas-estreptococo-grupo-b",
  "Sepsis neonatal precoz con RPM > 18 h: estreptococo del grupo B",
  "Neonatología · sepsis neonatal", ESP,
  ("Sepsis neonatal precoz (< 72 h)", ["Gérmenes del canal del parto: estreptococo del grupo B y E. coli.",
                                        "En el recién nacido a término, el más frecuente es el estreptococo del grupo B (SGB)."]),
  ("Recién nacido de 38 semanas, parto vaginal", ["Madre sin controles con RPM de 20 horas.",
                                                   "A las 8 h: taquipnea, tiraje, quejido, SatO₂ 88 %; Rx con infiltrados bilaterales."]),
  ["RPM ≥ 18 h + madre sin tamizaje de SGB + dificultad respiratoria en las primeras horas = sepsis por SGB.",
   "Tratamiento empírico: ampicilina + gentamicina.",
   "Prevención: cultivo vaginorrectal a las 36-37 semanas y profilaxis intraparto con penicilina."],
  "AAP, sepsis neonatal precoz (2019); " + NELSON + ".",
  d=dict(rotulo="Cuatro gérmenes posibles", ans=0,
         cards=[dict(titulo="Estreptococo del grupo B", datos=[("Momento", "Precoz (< 72 h)", True), ("Riesgo", "RPM, sin tamizaje", True),
                                                               ("Forma", "Neumonía y sepsis", True)], pie="El más frecuente a término."),
                dict(titulo="Listeria", datos=[("Momento", "Precoz", False), ("Riesgo", "Alimentos contaminados", False),
                                               ("Forma", "Granulomatosis", False)], pie="Poco frecuente."),
                dict(titulo="Escherichia coli", datos=[("Momento", "Precoz y tardía", False), ("Riesgo", "Prematuros, bajo peso", False),
                                                       ("Forma", "Sepsis y meningitis", False)], pie="Primera en prematuros."),
                dict(titulo="Neumococo", datos=[("Momento", "Lactante mayor", False), ("Riesgo", "Comunidad", False),
                                                ("Forma", "Neumonía, meningitis", False)], pie="No es germen del canal del parto.")]),
  banda=B("Tinción de Gram (esquema)", D(lambda s, x, y: I.gram(s, x + 20, y, "cocos_cadena", sc=1.1), 280, 180),
          ["Cocos grampositivos en cadenas: estreptococo.", "El grupo B (S. agalactiae) coloniza el canal del parto.",
           "Con la RPM larga el bebé se infecta antes de nacer."]),
  tabla=("Opciones de la pregunta", [("Estreptococo del grupo B", True), ("Listeria", False), ("E. coli", False), ("Neumococo", False)],
         [("¿Más probable aquí?", ["Sí", "No", "Segundo, más en prematuros", "No"])]))

# PED-249 · Hipernatremia por lactancia ineficaz · EMBUDO + franja
S("embudo", "PED-249", "lactante-sodio-162-tomas-espaciadas-lactancia-ineficaz",
  "Sodio de 162 en lactante con tomas espaciadas: deshidratación por lactancia ineficaz",
  "Trastornos del sodio · hipernatremia en lactantes", ESP,
  ("Hipernatremia en el lactante", ["Casi siempre por pérdida de agua libre mayor que la de sodio o por poco aporte de agua.",
                                    "La lactancia ineficaz es una causa frecuente y prevenible."]),
  ("Lactante de 4 meses con leche materna exclusiva", ["Tomas muy espaciadas; 24 h de vómitos, somnolencia, mucosas secas.",
                                                       "Pliegue (+); sodio 162 mEq/L, glucosa normal."]),
  ["Hipernatremia + deshidratación + tomas espaciadas = lactancia materna ineficaz.",
   "Corregir despacio: bajar el sodio ≤ 10-12 mEq/L en 24 h para evitar edema cerebral.",
   "Revisar la técnica de lactancia y la frecuencia de tomas."],
  NELSON + "; AAP, lactancia materna.",
  d=dict(rotulo="Del sodio alto a la causa", inicio="Lactante con sodio de 162 mEq/L y deshidratación",
         candidatos=["Hiperaldosteronismo", "Diabetes insípida central", "Diabetes insípida nefrogénica", "Lactancia ineficaz"],
         pasos=[("¿Hipertensión e hipopotasemia?", ["Hiperaldosteronismo"]),
                ("¿Poliuria con orina diluida desde antes?", ["Diabetes insípida central", "Diabetes insípida nefrogénica"])],
         final=("Lactancia materna ineficaz", ["Poco aporte de agua libre con tomas espaciadas"]),
         nota="No hay poliuria ni hipertensión: el bebé recibe poca leche y pierde agua con los vómitos."),
  banda=B("Laboratorio del caso", D(lambda s, x, y: I.lab_barras(s, x, y, [("Sodio", "162 mEq/L", 162, True), ("Límite normal", "145", 145, False)],
                                                              W=330, xmax=170, titulo="Sodio sérico (mEq/L)", ref=None), 330, 100),
          ["Sodio de 162: hipernatremia marcada.", "La deshidratación hipertónica engaña: el pliegue se nota menos.", "Corregir en 48 h."]),
  tabla=("Opciones de la pregunta", [("Hiperaldosteronismo", False), ("Lactancia ineficaz", True), ("DI nefrogénica", False), ("DI central", False)],
         [("¿Encaja?", ["No: sin HTA ni hipopotasemia", "Sí", "No: sin poliuria previa", "No: sin poliuria"])]))

# PED-250 · Vasculitis por IgA · SEMÁFORO
_purp = I.puntos_piel((80, 250, 140, 360), 70, "#be123c", (2, 4), 5) + I.E(94, 300, 14, 10, "#fecaca", I.RED, 2, extra='opacity="0.7"') + I.E(128, 300, 14, 10, "#fecaca", I.RED, 2, extra='opacity="0.7"')
S("semaforo", "PED-250", "purpura-palpable-piernas-artritis-rodillas-vasculitis-iga-sintomatico",
  "Vasculitis por IgA sin compromiso renal ni abdominal grave: reposo y AINE",
  "Vasculitis de la infancia · púrpura de Schönlein-Henoch", ESP,
  ("Vasculitis por IgA (Schönlein-Henoch)", ["Púrpura palpable en piernas y glúteos, artritis y dolor abdominal; puede dañar el riñón.",
                                             "Casi siempre se autolimita: el manejo es de soporte."]),
  ("Niña de 5 años", ["3 días de púrpura palpable en piernas y dolor e hinchazón de ambas rodillas.",
                      "Sin fiebre, sin dolor abdominal intenso, estable, sin edemas."]),
  ["Forma leve (piel y articulaciones): reposo relativo, elevar las piernas y AINE o paracetamol.",
   "Vigilar orina y PA por 6-12 meses: la nefritis puede aparecer después.",
   "Corticoides: dolor abdominal intenso, orquitis o compromiso renal importante."],
  "SHARE, recomendaciones de vasculitis por IgA (2019); " + NELSON + ".",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="La niña del caso",
         ilu=ILU(D(lambda s, x, y: I.nino(s, x + 24, y, extra=_purp, marcas=[(1, 60, 290), (2, 162, 300)], sc=0.84), 270, 320)),
         ilu_pie="1 púrpura palpable en las piernas; 2 rodillas hinchadas.",
         check_titulo="¿Hay compromiso grave?",
         check=[("Sin dolor abdominal intenso ni sangrado digestivo", True), ("Sin edema ni hipertensión", True),
                ("Estable, sin fiebre", True), ("Artritis de rodillas: dolor", False)],
         ans=0, tag="ESTE CASO",
         luces=[("Piel y articulaciones", "Soporte", ["Reposo relativo, elevar piernas, AINE; control de orina y PA."]),
                ("Dolor abdominal intenso u orquitis", "Corticoide oral", ["Prednisona; descartar invaginación."]),
                ("Nefritis importante o síndrome nefrótico", "Nefrología", ["Biopsia y tratamiento inmunosupresor."])]),
  tabla=("Opciones de la pregunta", [("ANA y anti-DNA", False), ("Seguimiento de orina y PA", False), ("Reposo y AINE", True),
                                     ("Pulsos de metilprednisolona", False)],
         [("Comentario", ["No hay sospecha de lupus", "Se hace, pero no es el manejo del cuadro agudo", "Manejo del cuadro actual",
                          "Excesivo"])]))

# PED-251 · CMV congénito · COMPARADOR (dibujos)
S("comparador", "PED-251", "calcificaciones-periventriculares-microcefalia-citomegalovirus-congenito",
  "Calcificaciones periventriculares con microcefalia: citomegalovirus congénito",
  "Infecciones congénitas · CMV y toxoplasmosis", ESP,
  ("Infecciones congénitas (TORCH)", ["La ubicación de las calcificaciones orienta el germen.",
                                      "CMV: alrededor de los ventrículos. Toxoplasma: dispersas en el cerebro."]),
  ("Recién nacido a término", ["Madre con cuadro seudogripal en el primer trimestre.", "Microcefalia; eco: ventriculomegalia y calcificaciones periventriculares."]),
  ["CMV congénito: calcificaciones periventriculares + microcefalia + hipoacusia neurosensorial.",
   "Toxoplasmosis: calcificaciones difusas, hidrocefalia y coriorretinitis.",
   "Confirmar con PCR para CMV en orina o saliva en las primeras 3 semanas; valganciclovir si es sintomático."],
  NELSON + "; Consenso internacional de CMV congénito (2017).",
  d=dict(rotulo="Dónde están las calcificaciones", IH=260, tag="ESTE CASO",
         imgs=[dict(titulo="Citomegalovirus", on=True, ilu=lambda s, x, y: I.tc_craneo(s, x + 67, y, "cmv", "eco"),
                    pie="Ventrículos grandes con calcificaciones pegadas a sus paredes (esquema de eco transfontanelar)."),
               dict(titulo="Toxoplasmosis", ilu=lambda s, x, y: I.tc_craneo(s, x + 67, y, "toxo", "eco"),
                    pie="Calcificaciones dispersas por todo el cerebro.")],
         lectura_titulo="Otras pistas",
         lectura=[("CMV", ["Hipoacusia, petequias, hepatoesplenomegalia."], True), ("Toxoplasma", ["Coriorretinitis, hidrocefalia."], False),
                  ("Rubeola", ["Cataratas, cardiopatía, sordera."], False)]),
  tabla=("Opciones de la pregunta", [("Herpes simple", False), ("Citomegalovirus", True), ("Toxoplasmosis", False), ("Rubeola", False)],
         [("Clave", ["Vesículas, encefalitis", "Periventriculares", "Difusas", "Cataratas y cardiopatía"])]))

# PED-252 · Ingesta de álcali · COMPARADOR (dibujos)
S("comparador", "PED-252", "ingesta-hidroxido-sodio-alcali-necrosis-licuefaccion",
  "Ingesta de álcali: necrosis de licuefacción del esófago y el estómago",
  "Intoxicaciones en pediatría · cáusticos", ESP,
  ("Cáusticos", ["Álcali (soda cáustica, lejía concentrada): necrosis de licuefacción, penetra profundo.",
                 "Ácido: necrosis de coagulación; la escara limita la profundidad."]),
  ("Niño de 1 año", ["Ingirió líquido desatorador con hidróxido de sodio (álcali fuerte).", "¿Qué lesión produce?"]),
  ["Álcali fuerte: saponifica grasas y disuelve proteínas → licuefacción transmural con riesgo de perforación y estenosis.",
   "No inducir vómito, no neutralizar, no carbón activado; ayuno y endoscopía en 12-24 h.",
   "Los ácidos dañan más el estómago; los álcalis, más el esófago."],
  NELSON + "; ESPGHAN, ingesta de cáusticos (2021).",
  d=dict(rotulo="Álcali frente a ácido", IH=270, tag="ESTE CASO",
         imgs=[dict(titulo="Álcali: licuefacción", on=True, ilu=lambda s, x, y: I.esofago_caustico(s, x + 97, y, "alcali"),
                    pie="La pared del esófago se «derrite»: la lesión llega hondo y puede perforar."),
               dict(titulo="Ácido: coagulación", ilu=lambda s, x, y: I.esofago_caustico(s, x + 97, y, "acido"),
                    pie="Forma una escara que limita la profundidad; daña más el estómago.")],
         lectura_titulo="Qué hacer",
         lectura=[("No hacer", ["Inducir vómito, neutralizar ni dar carbón activado."], False),
                  ("Endoscopía", ["En 12-24 h para graduar la lesión."], True), ("Después", ["Vigilar estenosis esofágica."], False)]),
  tabla=("Opciones de la pregunta", [("Superficial", False), ("Sin riesgo de perforación", False), ("Coagulación", False), ("Licuefacción", True)],
         [("¿Correcto para álcali?", ["No", "No", "No: es de ácidos", "Sí"])]))

# PED-253 · Dificultad respiratoria en primer nivel · RED + franja
_o2 = I.P("M104 90 C80 92 60 100 40 120", "none", "#0ea5e9", 3) + I.t(20, 136, "O₂", "#0369a1", 11, "start")
S("red", "PED-253", "lactante-dificultad-respiratoria-grave-primer-nivel-oxigeno-referencia",
  "Lactante con dificultad respiratoria grave en el primer nivel: oxígeno y referencia asistida",
  "Dificultad respiratoria · niveles de atención", ESP,
  ("Dificultad respiratoria grave en el primer nivel", ["Primero estabilizar lo que el establecimiento puede: oxígeno y posición.",
                                                        "Luego referencia asistida en ambulancia con personal."]),
  ("Lactante de 8 meses en centro de salud", ["Irritable, tiraje subcostal marcado, quejido, FR 70, SatO₂ 86 %.",
                                              "Sin pediatra ni UCI."]),
  ["Hipoxemia (SatO₂ < 90 %) con signos de gravedad: oxígeno y referencia asistida inmediata.",
   "No intentar intubar sin experiencia ni equipo; no trasladar en auto particular.",
   "Los fluidos EV no corrigen la hipoxemia."],
  MINSA + ", AIEPI y norma de referencia.",
  d=dict(rotulo="Dónde está el lactante y a dónde va", caso="I-3", destino="II-2", flecha="Referencia asistida", tag="ESTE CASO",
         claves=[("Oxígeno ya", ["Cánula o mascarilla hasta SatO₂ ≥ 92 %."], True),
                 ("Referencia asistida", ["Ambulancia con personal y oxígeno."], False),
                 ("No hacer", ["Intubar sin experiencia ni trasladar en auto particular."], False)]),
  banda=B("El lactante", D(lambda s, x, y: I.bebe(s, x + 30, y, extra=_o2, marcas=[(1, 120, 176)], sc=0.9), 250, 300),
          ["Tiraje subcostal marcado y quejido: dificultad grave.", "SatO₂ 86 %: hipoxemia.", "El oxígeno es lo que cambia el pronóstico mientras llega la ambulancia."],
          ans=2),
  tabla=("Opciones de la pregunta", [("Intubar", False), ("Oxígeno y referencia asistida", True), ("Fluidos y esperar", False),
                                     ("Auto particular", False)],
         [("Problema", ["Sin recursos ni experiencia", "Ninguno", "No corrige la hipoxemia", "Traslado inseguro"])]))

# PED-254 · FQ con hiponatremia hipovolémica · ÁRBOL + franja
S("arbol", "PED-254", "fibrosis-quistica-sudor-hiponatremia-hipovolemica-salino-09",
  "Fibrosis quística que pierde sal por el sudor: salino 0,9 % en bolo",
  "Trastornos del sodio · hiponatremia hipovolémica", ESP,
  ("Hiponatremia hipovolémica", ["Se pierde sal y agua; el riñón retiene sodio (sodio urinario bajo).",
                                 "El tratamiento es reponer volumen y sodio con solución isotónica."]),
  ("Niño de 8 años con fibrosis quística", ["Mucho sudor al jugar en zona cálida; debilidad, mareos, vómitos.",
                                            "PA 85/50, FC 120; Na 124, Na urinario 8; recibe salino 0,45 %."]),
  ["Fibrosis quística + calor: el sudor tiene mucha sal → hiponatremia hipovolémica.",
   "Shock o hipoperfusión: salino 0,9 % 20 mL/kg en bolo, luego infusión; corregir el sodio ≤ 8-10 mEq/L en 24 h.",
   "Las soluciones hipotónicas (0,45 %, dextrosa sola) empeoran la hiponatremia."],
  NELSON + "; CF Foundation, reposición de sal.",
  arbol=Q("¿Hipovolemia con hipoperfusión (PA baja, llenado lento)?", [
      L("Sí", "SALINO 0,9 % EN BOLO", ["20 mL/kg y luego infusión isotónica", "Controlar el sodio cada 4-6 h"], path=True),
      L("No", "Reposición oral o EV isotónica", ["Suplementos de sal en la dieta"])], path=True),
  banda=B("Laboratorio del caso", D(lambda s, x, y: I.lab_barras(s, x, y, [("Na sérico", "124 mEq/L", 124, True), ("Normal mínimo", "135", 135, False),
                                                                          ("Na urinario", "8 mEq/L", 8, False)],
                                                              W=330, xmax=150, titulo="Sodio (mEq/L)", ref=None), 330, 130),
          ["Sodio sérico bajo: 124.", "Sodio urinario de 8: el riñón ahorra sal (la pérdida es por el sudor).",
           "PA 85/50 y FC 120: hipovolemia."], ans=0),
  tabla=("Opciones de la pregunta", [("Suspender líquidos EV", False), ("Seguir con 0,45 %", False), ("Salino 0,9 % en bolo", True),
                                     ("Dextrosa 5 % sola", False)],
         [("Problema", ["Deja la hipovolemia", "Es hipotónico", "Ninguno", "Empeora la hiponatremia"])]))

# PED-255 · Estado epiléptico: consecuencias sistémicas · CICLO
S("ciclo", "PED-255", "estado-epileptico-hipoxemia-acidosis-lactica-consumo-oxigeno",
  "Estado epiléptico: más consumo de oxígeno y peor ventilación",
  "Estado epiléptico · repercusión sistémica", ESP,
  ("Estado epiléptico", ["Crisis de más de 5 minutos o varias sin recuperar la conciencia.",
                         "Las contracciones musculares y la actividad cerebral disparan la demanda de oxígeno."]),
  ("Niño de 6 años en estado epiléptico", ["Hipotensión, hipoxemia y acidosis láctica."]),
  ["Mecanismo común: aumento del consumo de oxígeno (músculo y neuronas) + alteración de la ventilación.",
   "El oxígeno no alcanza → metabolismo anaerobio → acidosis láctica → vasodilatación e hipotensión.",
   "Por eso el ABC (oxígeno, vía aérea) va junto con la benzodiacepina."],
  NELSON + "; Neurocritical Care Society, estado epiléptico (2012).",
  d=dict(rotulo="Cómo se encadenan los problemas", tag="ESTE CASO",
         img_titulo="Qué falla en el niño",
         img=D(lambda s, x, y: I.nino(s, x + 40, y, {"cabeza": "#fed7aa", "torax": "#fed7aa"}, marcas=[(1, 110, 50), (2, 50, 180), (3, 110, 136)], sc=0.86), 280, 330),
         img_pie="1 neuronas y 2 músculos consumen O₂; 3 la respiración se altera.",
         centro="Estado epiléptico", ans=0,
         pasos=[("Más consumo de O₂", "neuronas y músculos"), ("Ventilación alterada", "contracciones y apneas"),
                ("Hipoxemia", "menos O₂ en la sangre"), ("Acidosis láctica", "metabolismo anaerobio"), ("Hipotensión", "acidosis y vasodilatación")],
         claves_titulo="Por qué no las otras",
         claves=[("Sepsis", ["No hay foco ni fiebre descrita."], False), ("Hipoglucemia", ["No explica la hipoxemia."], False),
                 ("Reacción a fármacos", ["No explica todo el conjunto."], False)]),
  tabla=("Opciones de la pregunta", [("Sepsis", False), ("Hipoglucemia", False), ("Reacción a anticonvulsivos", False),
                                     ("Más consumo de O₂ + mala ventilación", True)],
         [("¿Explica todo?", ["No", "No", "No", "Sí"])]))

# PED-256 · Displasia broncopulmonar: nutrición · TARJETAS + franja
S("tarjetas", "PED-256", "prematuro-28-semanas-cpap-displasia-broncopulmonar-aporte-calorico",
  "Displasia broncopulmonar en evolución: lo fundamental es un buen aporte calórico-proteico",
  "Neonatología · displasia broncopulmonar", ESP,
  ("Displasia broncopulmonar (DBP)", ["Enfermedad pulmonar crónica del prematuro que necesita oxígeno a las 36 semanas.",
                                      "El pulmón crece y se repara solo si el niño crece bien."]),
  ("Lactante de 2 meses, nacido a las 28 semanas", ["En CPAP con FiO₂ 35 %, SatO₂ 92 %.", "Gana peso bien, sin infección."]),
  ["El gasto energético está aumentado: aporte calórico-proteico alto (leche materna fortificada).",
   "Meta de SatO₂ 90-95 %: no llevar al 100 % (el exceso de oxígeno daña el pulmón y la retina).",
   "Ventilación mecánica solo si fracasa la no invasiva; la vitamina A tiene beneficio modesto y se da en las primeras semanas."],
  NELSON + "; AAP, displasia broncopulmonar.",
  d=dict(rotulo="Cuatro intervenciones", ans=2,
         cards=[dict(titulo="Vitamina A", datos=[("Cuándo", "Primeras semanas", False), ("Beneficio", "Modesto", False),
                                                 ("¿Fundamental ahora?", "No", False)], pie="Prevención temprana, no el eje actual."),
                dict(titulo="SatO₂ al 100 %", datos=[("Riesgo", "Toxicidad por O₂", False), ("Retina", "Retinopatía", False),
                                                     ("Meta correcta", "90-95 %", False)], pie="Dañino."),
                dict(titulo="Aporte calórico-proteico", datos=[("Gasto", "Aumentado", True), ("Crecimiento", "Repara el pulmón", True),
                                                               ("¿Fundamental?", "Sí", True)], pie="Leche materna fortificada."),
                dict(titulo="Ventilación mecánica", datos=[("Indicación", "Falla del CPAP", False), ("Riesgo", "Más daño pulmonar", False),
                                                           ("¿En este caso?", "No", False)], pie="Está estable en CPAP.")]),
  banda=B("Pulmón con displasia (Rx esquemática)", D(lambda s, x, y: I.torax_rx(s, x, y, "dbp", sc=0.95), 285, 266),
          ["Tractos fibrosos y zonas quísticas por el daño crónico.", "El pulmón sigue formando alveolos si hay buena nutrición.",
           "Oxígeno justo lo necesario: SatO₂ 90-95 %."]),
  tabla=("Opciones de la pregunta", [("Vitamina A", False), ("SatO₂ al 100 %", False), ("Aporte calórico-proteico", True),
                                     ("Ventilación mecánica", False)],
         [("¿Fundamental ahora?", ["No", "Dañino", "Sí", "No indicada"])]))
