"""Entrega 2 · tanda 06 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, DOS, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from esc28 import GLASGOW_TEC

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"

# SP-061 · Enfoque intercultural · TARJETAS
S("tarjetas", "SP-061", "Capacitar al personal para respetar las culturas y adecuar los servicios con pertinencia cultural es el enfoque intercultural",
  "Salud pública · enfoques del modelo de cuidado integral",
  ("Enfoque intercultural", ["Reconoce y respeta las culturas de la población y adapta los servicios para que sean aceptables para ella.",
                             "Ejemplos: parto vertical, casa de espera, uso de la lengua materna, diálogo con la medicina tradicional."]),
  ("Capacitación al equipo de salud", ["Respeto a las culturas; servicios diseñados con pertinencia cultural.",
                                        "Comunicación que derribe barreras sociales y culturales; inclusión social."]),
  ["Derechos humanos: la salud como derecho de todos sin discriminación.",
   "Género: reconoce las diferencias de poder entre hombres y mujeres.",
   "Territorialidad: organiza los servicios según el territorio y sus redes."],
  MINSA + ", Modelo de Cuidado Integral de Salud por Curso de Vida (MCI, 2020); Política sectorial de salud intercultural (2016).",
  op=("¿Enfoque?", ["No es un enfoque del modelo", "Más amplio; aquí se trata de culturas", "No: es por territorio", "Sí: respeto y pertinencia cultural",
                    "No: diferencias entre sexos"]),
  d=dict(rotulo="Enfoques del modelo: ¿cuál?", ans=0,
         cards=[dict(titulo="Interculturalidad", datos=[("Mira", "Las culturas", True), ("Hace", "Adapta el servicio", True), ("Ej.", "Parto vertical", True)],
                     pie="Este caso."),
                dict(titulo="Derechos humanos", datos=[("Mira", "Dignidad, no discriminación", False), ("Hace", "Garantiza acceso", False), ("Ej.", "Ley 29414", False)],
                     pie="Base de todos."),
                dict(titulo="Género", datos=[("Mira", "Hombres y mujeres", False), ("Hace", "Reduce brechas", False), ("Ej.", "Violencia de género", False)],
                     pie="Otro enfoque."),
                dict(titulo="Territorialidad", datos=[("Mira", "El territorio", False), ("Hace", "Organiza redes", False), ("Ej.", "Redes integradas", False)],
                     pie="Otro enfoque.")]))

# PED-100 · Malformación anorrectal en niñas · TARJETAS + clasificación
S("tarjetas", "PED-100", "En la recién nacida con ano imperforado, el defecto más frecuente es la fístula rectovestibular",
  "Cirugía pediátrica · malformaciones anorrectales",
  ("Malformación anorrectal", ["El recto no llega al ano normal y suele abrirse por una fístula.",
                               "En las niñas lo más común es la fístula rectovestibular (al vestíbulo, detrás del himen); en los varones, la rectouretral."]),
  ("Pregunta de concepto", ["Recién nacida con ano imperforado.", "¿Qué defecto se asocia con más frecuencia?"]),
  ["Examinar el periné en las primeras 24 h: ver por dónde sale el meconio.",
   "Fístula rectovestibular: anorrectoplastia sagital posterior (Peña), a veces con colostomía previa.",
   "Buscar VACTERL: columna, corazón, riñones, extremidades."],
  "Clasificación de Krickenbeck (2005); Peña y Levitt; " + NELSON + ".",
  op=("¿Defecto?", ["Sí: el más frecuente en niñas", "Rara y compleja", "Existe, pero menos frecuente", "Es del varón", "Es del varón"]),
  d=dict(rotulo="Malformación anorrectal: ¿niña o niño?", ans=0,
         cards=[dict(titulo="Fístula rectovestibular", datos=[("Sexo", "Niña", True), ("Frecuencia", "La más común", True), ("Abre en", "Vestíbulo", True)],
                     pie="Este caso."),
                dict(titulo="Cloaca", datos=[("Sexo", "Niña", False), ("Defecto", "Un solo orificio", False), ("Complejidad", "Alta", False)],
                     pie="Rara."),
                dict(titulo="Fístula perineal", datos=[("Sexo", "Ambos", False), ("Abre en", "Periné", False), ("Pronóstico", "Bueno", False)],
                     pie="Baja."),
                dict(titulo="Rectouretral / rectovesical", datos=[("Sexo", "Niño", False), ("Signo", "Meconio en la orina", False), ("Trato", "Colostomía", False)],
                     pie="Varón.")]))

# PED-101 · Hemorragia intraventricular del prematuro · ÁRBOL + Papile
S("arbol", "PED-101", "Prematuro de 32 semanas con letargia, apneas, bradicardia, fontanela llena y perímetro cefálico que crece: hemorragia intraventricular",
  "Neonatología · hemorragia intraventricular",
  ("Hemorragia intraventricular (HIV)", ["Sangrado de la matriz germinal frágil del prematuro, en los primeros 3 días.",
                                         "Puede ser silenciosa; si es grande: letargia, apneas, fontanela abombada, caída del hematocrito."]),
  ("Prematuro de 32 semanas, 1400 g", ["Segundo día de vida; letárgico e hipoactivo.",
                                        "FC 114, fontanela llena, apneas; perímetro cefálico de 30 a 31,5 cm."]),
  ["Ecografía transfontanelar: tamizaje en < 32 semanas o < 1500 g (días 3-7 y luego seriada).",
   "Soporte: ventilación si hace falta, PA y glucosa estables, evitar cambios bruscos de volumen.",
   "Vigilar la hidrocefalia posthemorrágica (perímetro cefálico y ecografías)."],
  "AAP, tamizaje con ecografía craneal en prematuros (2020); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Es el grado IV; aquí no hay datos de parénquima", "Es complicación posterior", "Rara en el prematuro",
                        "Sí: prematuro + fontanela llena + apneas", "No: no explica la fontanela llena"]),
  arbol=Q("Prematuro con letargia, apneas y fontanela llena: ¿ecografía transfontanelar con sangre?", [
      L("Sí (este caso)", "HEMORRAGIA INTRAVENTRICULAR", ["Clasificar (Papile)", "Vigilar hidrocefalia"], path=True),
      L("No", "Sepsis, hipoglucemia", ["Cultivos, glucosa"])], path=True),
  escala=dict(nombre="Clasificación de Papile (HIV)", orden=True,
              que="Por la ecografía transfontanelar; los grados III-IV tienen peor pronóstico.",
              grados=[("Grado I", "Matriz germinal", ["Solo subependimaria"]), ("Grado II", "Intraventricular", ["< 50 % del ventrículo, sin dilatación"]),
                      ("Grado III", "Con dilatación", ["> 50 % y ventrículo dilatado"]), ("Grado IV", "Parenquimatosa", ["Infarto venoso periventricular"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Fontanela llena y PC que crece: sugiere grado III", True), ("Falta la ecografía", True)],
              conducta="Ecografía transfontanelar y soporte."))

# GAS-034 · Hepatitis A: IgM anti-VHA · ÁRBOL + ictericia real
S("arbol", "GAS-034", "Adolescente con pródromo, ictericia y hepatomegalia: la IgM anti-VHA confirma la hepatitis A aguda",
  "Hepatitis aguda · serología",
  ("Hepatitis A", ["Transmisión fecal-oral (agua y alimentos); muy frecuente en niños y adolescentes en el Perú.",
                   "La IgM anti-VHA aparece con los síntomas y confirma la infección aguda."]),
  ("Adolescente", ["5 días de malestar, fiebre, inapetencia, prurito, náuseas y vómitos.", "Mucosas secas, ictericia, hepatomegalia."]),
  ["IgG anti-VHA indica infección pasada o vacuna (inmunidad).",
   "Manejo de soporte; no hay antiviral; se cura sin cronicidad.",
   "Vacuna contra la hepatitis A en el esquema nacional (a los 15 meses)."],
  CDC + ", hepatitis A (2024); " + MINSA + ", esquema nacional de vacunación (2025).",
  op=("¿Examen?", ["Sí: infección aguda", "No: infección pasada o vacuna", "No: es la B, pasada", "Es para la hepatitis B aguda", "Es para la hepatitis C"]),
  arbol=Q("Hepatitis aguda en un joven: ¿IgM anti-VHA positiva?", [
      L("Sí (este caso)", "HEPATITIS A AGUDA", ["Soporte", "Avisar a contactos"], path=True),
      L("No", "Pedir HBsAg y IgM anti-HBc", ["Y anti-VHC"])], path=True),
  escala=dict(nombre="Serología de las hepatitis virales", orden=False,
              que="Qué marcador indica infección aguda.",
              grados=[("IgM anti-VHA", "Hepatitis A aguda", ["Este caso"]), ("IgG anti-VHA", "A pasada o vacuna", ["Inmunidad"]),
                      ("HBsAg + IgM anti-HBc", "Hepatitis B aguda", ["Seguir 6 meses"]), ("Anti-VHC + ARN", "Hepatitis C", ["Antivirales"])],
              caso=0, porque=[("Joven con ictericia aguda tras pródromo", True)],
              conducta="Pedir IgM anti-VHA y transaminasas."),
  banda=B("Así se ve la ictericia", P("ictericia.jpg", 400, 125, [
            ("flecha", 0.66, 0.42, 0.50, 0.85, "escleras amarillas")],
          credito="Dominio público" + CC.rstrip(" · ")),
          [("Escleras amarillas", "Primer lugar donde se nota."),
           ("Prurito", "Por la colestasis."),
           ("Orina oscura", "Coluria."),
           ("Hepatomegalia dolorosa", "El hígado inflamado.")],
          pie="Foto de otro paciente con hepatitis A.", ans=0))

# OFT-021 · Maculopatía por hidroxicloroquina · TARJETAS
S("tarjetas", "OFT-021", "Lúpica en tratamiento crónico con hidroxicloroquina con pérdida visual progresiva y maculopatía bilateral: toxicidad por hidroxicloroquina",
  "Toxicidad ocular por fármacos",
  ("Retinopatía por hidroxicloroquina", ["Daño de la retina por acumulación del fármaco: maculopatía «en ojo de buey».",
                                         "Riesgo mayor con dosis > 5 mg/kg/día, más de 5 años de uso y falla renal (como la nefritis lúpica)."]),
  ("Mujer de 27 años con LES y nefritis grave", ["Corticoides e hidroxicloroquina permanentes.",
                                                  "Pérdida visual progresiva, sobre todo nocturna; maculopatía bilateral severa."]),
  ["Tamizaje: fondo de ojo basal y luego anual tras 5 años (antes si hay riesgo): campo visual 10-2 y OCT.",
   "Suspender el fármaco al ver toxicidad: el daño suele ser irreversible.",
   "Los corticoides dan cataratas y glaucoma, no maculopatía."],
  "AAO, tamizaje de retinopatía por hidroxicloroquina (2016, act. 2024); EULAR, LES (2023).",
  op=("¿Etiología?", ["No: dan catarata y glaucoma", "Daría hemorragias y exudados", "Posible, pero el patrón es tóxico", "Sí: uso crónico + falla renal",
                      "No: no es diabética"]),
  d=dict(rotulo="Ojo y fármacos: ¿qué daño da cada uno?", ans=0,
         cards=[dict(titulo="Hidroxicloroquina", datos=[("Daño", "Maculopatía", True), ("Forma", "Ojo de buey", True), ("Riesgo", "Falla renal", True)],
                     pie="Este caso."),
                dict(titulo="Corticoides", datos=[("Daño", "Catarata subcapsular", False), ("Además", "Glaucoma", False), ("Mácula", "Normal", False)],
                     pie="Otro fármaco."),
                dict(titulo="Etambutol", datos=[("Daño", "Neuritis óptica", False), ("Color", "Verde-rojo", False), ("Reversible", "Si se suspende", False)],
                     pie="TB."),
                dict(titulo="HTA grave", datos=[("Daño", "Retinopatía", False), ("Ve", "Hemorragias, exudados", False), ("Grave", "Edema de papila", False)],
                     pie="Vascular.")]))

# INF-044 · Peritonitis tuberculosa · TARJETAS
S("tarjetas", "INF-044", "Joven con 3 semanas de fiebre, sudoración nocturna, baja de peso, ascitis y abdomen «en tablero de ajedrez» con exudado linfocítico: peritonitis tuberculosa",
  "Tuberculosis extrapulmonar · peritonitis",
  ("Peritonitis tuberculosa", ["TB del peritoneo: ascitis exudativa con linfocitos, síntomas constitucionales.",
                               "Abdomen pastoso «en tablero de ajedrez» por zonas de engrosamiento y líquido."]),
  ("Varón de 25 años", ["3 semanas de fiebre, dolor abdominal, sudoración nocturna, baja de peso y anorexia.",
                        "Signo de la oleada (+); líquido libre; exudado rico en proteínas con linfocitos."]),
  ["ADA en líquido ascítico > 39 U/L apoya fuertemente; GeneXpert y cultivo (baja sensibilidad).",
   "Laparoscopía con biopsia si hay duda (granulomas caseosos).",
   "Esquema para TB sensible 6 meses (2HRZE/4HR)."],
  MINSA + ", NTS de atención integral de la tuberculosis (2023); " + OMS + " (2025).",
  op=("¿Diagnóstico?", ["No: diarrea, sin ascitis linfocítica", "No: diarrea con sangre", "Sí: exudado linfocítico + síntomas B",
                        "No: trasudado con neutrófilos", "Posible en mayores; citología maligna"]),
  d=dict(rotulo="Líquido ascítico: ¿qué dice?", ans=0,
         cards=[dict(titulo="TB peritoneal", datos=[("Tipo", "Exudado", True), ("Células", "Linfocitos", True), ("ADA", "> 39 U/L", True)],
                     pie="Este caso."),
                dict(titulo="Cirrosis", datos=[("Tipo", "Trasudado", False), ("GASA", "≥ 1,1", False), ("Células", "Pocas", False)],
                     pie="Hipertensión portal."),
                dict(titulo="Peritonitis bacteriana", datos=[("Células", "Neutrófilos > 250", False), ("Paciente", "Cirrótico", False), ("Trato", "Cefotaxima", False)],
                     pie="Espontánea."),
                dict(titulo="Carcinomatosis", datos=[("Tipo", "Exudado", False), ("Citología", "Maligna", False), ("Edad", "Mayor", False)],
                     pie="Ovario, estómago.")]))

# GIN-090 · Mola hidatiforme: evacuación · ÁRBOL + eco real
S("arbol", "GIN-090", "Sangrado a las 8 semanas con útero grande para la edad y ecografía «en tormenta de nieve»: mola hidatiforme, evacuación por aspiración",
  "Enfermedad trofoblástica gestacional · mola",
  ("Mola hidatiforme", ["Proliferación anormal del trofoblasto: vellosidades hinchadas en racimo y β-hCG muy alta.",
                        "Útero más grande que la edad, sangrado, hiperémesis, preeclampsia precoz, hipertiroidismo."]),
  ("Mujer de 32 años, nulípara", ["8 semanas de amenorrea; sangrado moderado.", "Útero de 12 cm; eco transvaginal «en tormenta de nieve»."]),
  ["Evacuación por aspiración (AMEU o vacío) con oxitocina después de iniciar la evacuación; histología.",
   "β-hCG semanal hasta negativa 3 veces, luego mensual; anticoncepción eficaz en el seguimiento.",
   "Si la β-hCG se estanca o sube: neoplasia trofoblástica (quimioterapia)."],
  "FIGO, enfermedad trofoblástica (2021); ACOG; RCOG Green-top 38 (2020).",
  op=("¿Manejo?", ["Solo si no desea más hijos y > 40 años", "Sí: evacuación por aspiración", "No: riesgo de sangrado y neoplasia",
                   "Solo si persiste la β-hCG", "No: profilaxis no se da a todas"]),
  arbol=Q("Eco en tormenta de nieve: ¿desea conservar la fertilidad?", [
      L("Sí (este caso)", "EVACUACIÓN POR ASPIRACIÓN", ["Histología", "β-hCG seriada"], path=True),
      L("No, edad avanzada", "Histerectomía", ["Opción"])], path=True),
  escala=dict(nombre="Tipos de mola hidatiforme", orden=False,
              que="Se distinguen por la genética y la histología.",
              grados=[("Completa", "46,XX paterna", ["Sin feto", "β-hCG muy alta", "15-20 % neoplasia"]),
                      ("Parcial", "Triploide 69,XXY", ["Feto anormal", "1-5 % neoplasia"])],
              caso=0, porque=[("Tormenta de nieve sin embrión descrito", True), ("Útero grande para la edad", True)],
              conducta="Evacuación por aspiración y seguimiento con β-hCG."),
  banda=B("Así se ve en la ecografía", P("mola.jpg", 330, 251, [
            ("circulo", 0.55, 0.6, 0.25, "«tormenta de nieve»", 0.5, 0.08)],
          credito="Mikael Häggström" + CC + "CC0"),
          [("Muchas vesículas", "Pequeños quistes que llenan el útero."),
           ("Sin embrión", "En la mola completa."),
           ("Quistes tecaluteínicos", "Por la β-hCG muy alta."),
           ("Útero grande", "Más que lo esperado por la amenorrea.")],
          pie="Ecografía de otra paciente.", ans=0))

# TRA-016 · Displasia del desarrollo de la cadera: ecografía · ÁRBOL + Graf + esquema real
S("arbol", "TRA-016", "Para el tamizaje de la displasia del desarrollo de la cadera en el recién nacido, el estudio de elección es la ecografía",
  "Ortopedia pediátrica · displasia de cadera",
  ("Displasia del desarrollo de la cadera (DDC)", ["El acetábulo no cubre bien la cabeza femoral: puede subluxarse o luxarse.",
                                                    "Hasta los 4-6 meses la cabeza es cartílago: no se ve en la Rx, sí en la ecografía."]),
  ("Pregunta de concepto", ["Recién nacido.", "¿Estudio de elección para el tamizaje?"]),
  ["Examen clínico (Ortolani y Barlow) a todos; ecografía a las 4-6 semanas si hay riesgo (podálica, familiar) o examen anormal.",
   "Rx de pelvis después de los 4-6 meses (cuando osifica la cabeza).",
   "Tratamiento: arnés de Pavlik en los primeros meses."],
  AAP + ", DDC (2016); AAOS (2022); método de Graf.",
  op=("¿Estudio?", ["No: radiación, no de tamizaje", "Útil tras los 4-6 meses", "No: no es de tamizaje", "Sí: ve el cartílago", "No: no aporta"]),
  arbol=Q("Recién nacido con riesgo o examen de cadera anormal: ¿menor de 4-6 meses?", [
      L("Sí", "ECOGRAFÍA (Graf)", ["Ángulos α y β"], path=True),
      L("No: mayor", "Radiografía de pelvis", ["Índice acetabular"])], path=True),
  escala=dict(nombre="Clasificación ecográfica de Graf", orden=True,
              que="Por el ángulo α (techo óseo) en la ecografía coronal.",
              grados=[("Tipo I", "Normal", ["α ≥ 60°"]), ("Tipo II", "Inmadura o displásica", ["α 43-59°", "Control o arnés"]),
                      ("Tipo III", "Descentrada", ["α < 43°", "Arnés de Pavlik"]), ("Tipo IV", "Luxada", ["Cabeza fuera", "Tratamiento urgente"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Pregunta de tamizaje: la eco da el tipo", True)],
              conducta="Ecografía a las 4-6 semanas si hay riesgo o examen anormal."),
  banda=B("Cómo se mide en la ecografía", P("graf.jpg", 330, 232, [
            ("texto", 0.20, 0.10, "techo del acetábulo")],
          credito="Nevit Dilmen" + CC + "CC BY-SA 3.0", fondo="#ffffff"),
          [("Línea de base", "Sobre el ilion, en el corte coronal."),
           ("Ángulo α", "Techo óseo: ≥ 60° es normal."),
           ("Ángulo β", "Techo cartilaginoso: < 55° es normal."),
           ("Cabeza de cartílago", "Visible en la eco, no en la Rx.")],
          pie="Esquema de los ángulos de Graf.", ans=1))

# SP-062 · Principio de eficiencia · TARJETAS
S("tarjetas", "SP-062", "Usar racionalmente los recursos disponibles para alcanzar metas predeterminadas es el principio de eficiencia",
  "Gestión en salud · principios",
  ("Eficiencia", ["Lograr los objetivos con el menor uso de recursos (relación resultado/costo).",
                  "Eficacia: lograr el objetivo en condiciones ideales; efectividad: en condiciones reales."]),
  ("Jefe de un establecimiento", ["Usa el ASIS para priorizar; promueve AIEPI.", "Planifica y usa racionalmente los recursos para sus metas."]),
  ["Integralidad: atender a la persona en todas sus dimensiones.",
   "Equidad: más a quien más necesita.",
   "Universalidad: para todos."],
  MINSA + "; OPS, funciones esenciales de salud pública (2020).",
  op=("¿Principio?", ["No: atención completa", "No: reparto según necesidad", "Lograr el objetivo, sin mirar el costo", "Sí: recursos racionales para la meta",
                      "No: cobertura para todos"]),
  d=dict(rotulo="¿Qué mide cada principio?", ans=0,
         cards=[dict(titulo="Eficiencia", datos=[("Mide", "Resultado / recursos", True), ("Aquí", "Uso racional", True), ("Pregunta", "¿A qué costo?", True)],
                     pie="Este caso."),
                dict(titulo="Eficacia", datos=[("Mide", "Lograr el objetivo", False), ("Condición", "Ideal", False), ("Pregunta", "¿Funciona?", False)],
                     pie="Sin costo."),
                dict(titulo="Equidad", datos=[("Mide", "Justicia", False), ("Idea", "Más a quien necesita", False), ("Pregunta", "¿Para quién?", False)],
                     pie="Distribución."),
                dict(titulo="Integralidad", datos=[("Mide", "Atención completa", False), ("Idea", "Persona, familia", False), ("Pregunta", "¿Todo?", False)],
                     pie="Enfoque.")]))

# PED-102 · Sepsis neonatal tardía · ÁRBOL + Kramer propio
S("arbol", "PED-102", "Neonato de 9 días con ictericia hasta el abdomen (Kramer 3), succión débil, poca orina, hipoactivo y bradicárdico: sepsis neonatal tardía, referir",
  "Infecciones neonatales · sepsis tardía",
  ("Sepsis neonatal tardía", ["Aparece después de las 72 horas (hasta los 28 días); gérmenes del ambiente o de la comunidad.",
                              "Signos sutiles: succión débil, hipoactividad, ictericia que reaparece, poca orina, alteración de la temperatura o FC."]),
  ("Neonato de 9 días", ["Amarillo, moja poco el pañal (2 al día), succión débil.", "FC 110, hipoactivo; ictericia zona 3 de Kramer."]),
  ["Referir al hospital: hemocultivo, hemograma, PCR, punción lumbar, urocultivo.",
   "Antibiótico EV empírico (ampicilina + gentamicina o cefotaxima según el foco).",
   "Ictericia después de la 1.ª semana con mal estado: siempre descartar sepsis."],
  AAP + "; " + MINSA + ", guía de atención del recién nacido (2023); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Puede ocurrir, pero por la sepsis", "No: es antes de las 72 h", "Es un signo; el cuadro es sepsis", "Sí: después de 72 h + mal estado",
                        "No: el bebé estaría bien"]),
  arbol=Q("Neonato de más de 3 días con ictericia y mal estado (succión débil, hipoactivo): ¿sepsis?", [
      L("Sí (este caso)", "SEPSIS TARDÍA: REFERIR", ["Cultivos y antibiótico EV"], path=True),
      L("No: activo, come bien", "Ictericia fisiológica o por leche", ["Control de bilirrubina"])], path=True),
  banda=B("Zonas de Kramer", P("dib_kramer.jpg", 300, 240, [], credito=PROPIO, fondo="#ffffff"),
          [("Avanza de la cabeza a los pies", "A más zonas, más bilirrubina."),
           ("Zona 3: este caso", "Abdomen bajo y muslos (≈ 12 mg/dL)."),
           ("Solo orienta", "Confirmar con bilirrubina sérica o transcutánea."),
           ("Ictericia + mal estado", "Pensar en sepsis, no solo en la bilirrubina.")],
          pie="Esquema.", ans=1))

# PSI-017 · Episodio depresivo con ideación suicida · ÁRBOL + criterios
S("arbol", "PSI-017", "Varón con 6 semanas de tristeza, vacío, insomnio, falta de energía, poca atención e ideas suicidas recurrentes: episodio depresivo",
  "Trastornos del ánimo · depresión",
  ("Episodio depresivo mayor", ["≥ 5 síntomas durante ≥ 2 semanas, con ánimo deprimido o anhedonia, que alteran la vida diaria.",
                                "La ideación suicida es un signo de gravedad: evaluar el riesgo siempre."]),
  ("Varón de 58 años", ["6 semanas de tristeza, vacío, insomnio, sin ganas de levantarse.", "Problemas de atención; en la última semana ideas suicidas recurrentes."]),
  ["Evaluar riesgo suicida (plan, medios, intentos previos); si es alto, hospitalizar.",
   "ISRS (sertralina, escitalopram) + psicoterapia; control cercano al inicio.",
   "Descartar hipotiroidismo, consumo de alcohol y trastorno bipolar."],
  "DSM-5-TR (2022); " + NICE + " NG222, depresión en adultos (2022); " + MINSA + ", guía de depresión.",
  op=("¿Diagnóstico?", ["No: dolor difuso, no ánimo", "No predomina la ansiedad", "Sí: ánimo + síntomas + ideación", "La depresión puede parecer demencia; aquí es depresión",
                        "Descartarlo, pero no explica la ideación"]),
  arbol=Q("Ánimo deprimido ≥ 2 semanas con ≥ 5 síntomas: ¿ideación suicida?", [
      L("Sí, recurrente (este caso)", "DEPRESIÓN CON RIESGO", ["Evaluar riesgo, ¿hospitalizar?", "ISRS + psicoterapia"], path=True),
      L("No", "Depresión", ["Tratamiento ambulatorio"])], path=True),
  triada=TR([("Ánimo deprimido", "Triste, vacío", True), ("Anhedonia / energía baja", "Sin ganas de levantarse", True), ("Insomnio", "Sí", True),
             ("Poca concentración", "Problemas de atención", True), ("Ideas de muerte", "Ideación suicida", True)],
            [("Criterios del DSM-5-TR (≥ 5 de 9)", 0, 4)],
            "5 de 9 durante 6 semanas: episodio depresivo mayor."))

# CB-029 · Biotransformación hepática · MATRIZ
S("matriz", "CB-029", "La principal función del hígado con los xenobióticos es transformarlos, empezando por la hidroxilación enzimática (fase I, citocromo P450)",
  "Bioquímica · biotransformación",
  ("Biotransformación hepática", ["Convierte sustancias extrañas liposolubles en hidrosolubles para eliminarlas por orina o bilis.",
                                  "Fase I: oxidación (hidroxilación por el citocromo P450); fase II: conjugación (glucurónido, sulfato, glutatión)."]),
  ("Pregunta de concepto", ["Xenobióticos de los alimentos.", "¿Función principal del hígado?"]),
  ["El P450 se induce (rifampicina, carbamazepina) o se inhibe (ketoconazol, macrólidos): interacciones.",
   "Algunas fases I generan metabolitos tóxicos (NAPQI del paracetamol).",
   "Conjugación con ácido glucurónico: la más común en fase II."],
  "Lehninger 8.ª ed.; Goodman & Gilman 14.ª ed.",
  op=("¿Función?", ["No: la meta es volverlos polares", "No: se conjuga con glucurónido, no nucleótidos", "Sí: fase I, P450", "No: es para lípidos",
                    "No: se transforman"]),
  d=dict(rotulo="Fases de la biotransformación", eje_x="Fase", eje_y="Qué hace",
         cols=["Fase I", "Fase II"], rows=["Reacción", "Enzimas", "Resultado"], caso=(0, 0),
         cells=[[("HIDROXILACIÓN", ["Oxidación, reducción, hidrólisis"]), ("Conjugación", ["Glucurónido, sulfato, glutatión"])],
                [("Citocromo P450", ["Retículo endoplásmico"]), ("Transferasas", ["UGT, SULT, GST"])],
                [("Más polar", ["A veces más tóxico"]), ("Hidrosoluble", ["Sale por orina o bilis"])]]))

# CIR-055 · Obstrucción por cáncer de colon: colostomía · ÁRBOL
S("arbol", "CIR-055", "Adulto mayor con baja de peso, hematoquecia y obstrucción intestinal baja con masa rectal y fiebre: cáncer obstructivo, colostomía",
  "Obstrucción intestinal · cáncer colorrectal",
  ("Obstrucción por cáncer colorrectal", ["El cáncer de colon izquierdo o recto es la causa más común de obstrucción del colon en el adulto mayor.",
                                          "Con fiebre y dolor: riesgo de isquemia o perforación del ciego (válvula ileocecal competente)."]),
  ("Varón de 80 años", ["2 días de distensión, vómitos, sin gases ni heces; baja de 8 kg y hematoquecia.",
                        "PA 100/60, FC 100, 39 °C; RHA metálicos; tacto rectal: masa dura y sangre."]),
  ["Reanimar, sonda nasogástrica, antibiótico; TC para ubicar y ver perforación.",
   "Cáncer de recto obstructivo: colostomía derivativa (luego neoadyuvancia y cirugía).",
   "Colon izquierdo estable: stent como puente o resección; inestable o perforado: Hartmann."],
  "WSES, obstrucción por cáncer colorrectal (2018); ASCRS (2022).",
  op=("¿Indicación?", ["No: la obstrucción es del colon", "Sí: deriva por encima del tumor", "No: no pasa el tumor y riesgo de perforar",
                       "Se hará, pero no resuelve la urgencia", "No: riesgo de perforación"]),
  arbol=Q("Obstrucción baja con masa rectal: ¿hay perforación o isquemia?", [
      L("Fiebre, dolor: riesgo alto (este caso)", "COLOSTOMÍA DERIVATIVA", ["Reanimar", "Antibiótico"], path=True),
      L("Estable, colon izquierdo", "Stent o resección", ["Según el equipo"])], path=True))

# CAR-037 · Chagas crónico · ÁRBOL + ECG propio + Rx real
S("arbol", "CAR-037", "Mujer de Arequipa rural con insuficiencia cardiaca, fibrilación auricular, cardiomegalia, megaesófago y megacolon: enfermedad de Chagas crónica",
  "Enfermedad de Chagas · fase crónica",
  ("Chagas crónico", ["Años después de la infección, 30 % hace daño cardiaco y 10 % digestivo.",
                      "Miocardiopatía dilatada con arritmias y bloqueos; megaesófago y megacolon por destrucción de neuronas."]),
  ("Mujer de 36 años, área rural de Arequipa", ["2 años de disnea progresiva; pirosis, disfagia y estreñimiento.",
                                                "Galope, crépitos; ECG: FA con extrasístoles; Rx: gran cardiomegalia; TC: megacolon y megaesófago."]),
  ["Confirmar con 2 serologías distintas (ELISA, IFI).",
   "Tratar la insuficiencia cardiaca y las arritmias (anticoagular la FA); desfibrilador si hay TV.",
   "Benznidazol en adultos con forma crónica temprana sin daño avanzado (discutido)."],
  "OPS, guía de Chagas (2019); AHA, miocardiopatía chagásica (2018); " + MINSA + ".",
  op=("¿Diagnóstico?", ["No: no da megavísceras", "Sí: corazón + megavísceras + zona endémica", "No: no da megavísceras", "No: no da megavísceras",
                        "No: aguda, sin megavísceras"]),
  arbol=Q("Insuficiencia cardiaca en zona endémica: ¿megaesófago o megacolon?", [
      L("Sí (este caso)", "CHAGAS CRÓNICO", ["Serología", "Tratar IC y arritmias"], path=True),
      L("No", "Otra miocardiopatía", ["Eco, coronariografía"])], path=True),
  banda=B("ECG y Rx del Chagas crónico", P("chagas_ecg_rx.jpg", 420, 145, [
            ("flecha", 0.252, 0.231, 0.40, 0.58, "sin ondas P"),
            ("flecha", 0.853, 0.70, 0.80, 0.10, "esófago dilatado")],
          credito="ECG de enseñanza MedQuizPro y Rx de dominio público" + CC.rstrip(" · "), fondo="#ffffff"),
          [("Fibrilación auricular", "Sin ondas P y QRS irregulares, como este caso."),
           ("Bloqueos", "El bloqueo de rama derecha + hemibloqueo anterior es típico."),
           ("Megaesófago", "Esófago muy dilatado que termina en punta: disfagia."),
           ("Megacolon", "Estreñimiento pertinaz y vólvulo.")],
          pie="Trazado de enseñanza y Rx de otro paciente.", ans=0))

# CIR-056 · Trauma con Glasgow 8: intubación · ÁRBOL + Glasgow
S("arbol", "CIR-056", "Motociclista sin casco con Glasgow 8, SatO₂ 90 % e hipotensión: lo primero es asegurar la vía aérea con intubación orotraqueal",
  "Trauma · revisión primaria (ABCDE)",
  ("Revisión primaria del trauma", ["Orden: A (vía aérea con control cervical), B, C, D, E.",
                                    "Glasgow ≤ 8 = no protege la vía aérea: intubar (secuencia rápida con restricción cervical)."]),
  ("Varón de 35 años, motociclista sin casco", ["Impacto y lanzamiento.", "PA 80/60, FC 110, FR 20, SatO₂ 90 %, Glasgow 8."]),
  ["Intubación con control de la columna cervical; luego ventilación y reanimación del choque.",
   "Evitar hipotensión e hipoxia: duplican la mortalidad en el TEC.",
   "TC de cráneo y columna después de estabilizar; manitol solo si hay herniación y el paciente no está hipotenso."],
  ATLS + "; Brain Trauma Foundation (2016).",
  op=("¿Medida inicial?", ["Sí: A primero", "No: no es lo urgente", "No: está hipotenso", "Después de estabilizar", "Después de la vía aérea"]),
  arbol=Q("Trauma: ¿protege la vía aérea?", [
      L("No: Glasgow 8 (este caso)", "INTUBACIÓN OROTRAQUEAL", ["Control cervical", "Luego B y C"], path=True),
      L("Sí", "Oxígeno y seguir el ABCDE", ["Vigilar"])], path=True),
  escala=GLASGOW_TEC(2, [("Glasgow 8", True), ("SatO₂ 90 % e hipotensión: lesión secundaria", True)],
                     "Intubar, oxigenar, reanimar y TC urgente."))

# NRL-026 · Demencia con cuerpos de Lewy · TARJETAS + criterios McKeith
S("tarjetas", "NRL-026", "Deterioro cognitivo con fallas de atención, alucinaciones visuales bien formadas y parkinsonismo: demencia con cuerpos de Lewy",
  "Demencias · cuerpos de Lewy",
  ("Demencia con cuerpos de Lewy", ["Demencia con fluctuaciones de la atención, alucinaciones visuales y parkinsonismo.",
                                    "El parkinsonismo aparece antes o en el primer año de la demencia (si es después, es demencia de Parkinson)."]),
  ("Varón de 62 años", ["Deterioro progresivo con fallas de atención y lentitud.",
                        "Ve personas que lo vigilan; facies inexpresiva, temblor «de contar monedas», rigidez, bradicinesia."]),
  ["Muy sensible a los antipsicóticos típicos (haloperidol): rigidez grave, síndrome neuroléptico.",
   "Inhibidores de colinesterasa (rivastigmina, donepezilo) mejoran la cognición y las alucinaciones.",
   "Levodopa a dosis bajas para el parkinsonismo."],
  "Consorcio DLB, criterios de McKeith (2017); " + NICE + " NG97 (2018).",
  op=("¿Diagnóstico?", ["No: hay signos neurológicos", "Inicia con memoria, sin alucinaciones tempranas", "Sí: alucinaciones + parkinsonismo",
                        "Inicia con conducta, sin parkinsonismo", "Escalonada, con infartos"]),
  d=dict(rotulo="Demencia: ¿qué la distingue?", ans=0,
         cards=[dict(titulo="Cuerpos de Lewy", datos=[("Temprano", "Alucinaciones visuales", True), ("Motor", "Parkinsonismo", True), ("Curso", "Fluctúa", True)],
                     pie="Este caso."),
                dict(titulo="Alzheimer", datos=[("Temprano", "Memoria", False), ("Motor", "Normal al inicio", False), ("Curso", "Lento, continuo", False)],
                     pie="La más común."),
                dict(titulo="Frontotemporal", datos=[("Temprano", "Conducta, lenguaje", False), ("Edad", "< 65", False), ("Memoria", "Preservada al inicio", False)],
                     pie="Desinhibición."),
                dict(titulo="Vascular", datos=[("Curso", "Escalonado", False), ("Signos", "Focales", False), ("Imagen", "Infartos", False)],
                     pie="Factores de riesgo.")]),
  triada=TR([("Fluctuaciones de la atención", "Pérdida de atención", True), ("Alucinaciones visuales", "Ve personas", True), ("Parkinsonismo", "Rigidez, bradicinesia, temblor", True),
             ("Trastorno de conducta del sueño REM", "No se menciona", None)],
            [("Criterios centrales de McKeith", 0, 3)],
            "2 criterios centrales = demencia con cuerpos de Lewy probable."))

# OFT-022 · Hematoma subpericóndrico auricular · ÁRBOL + foto real
S("arbol", "OFT-022", "Golpe en la oreja hace 2 horas con aumento de volumen fluctuante del pabellón: hematoma subpericóndrico, drenar",
  "Otorrinolaringología · trauma del pabellón auricular",
  ("Hematoma auricular", ["La sangre se acumula entre el pericondrio y el cartílago y lo separa de su nutrición.",
                          "Sin drenaje, el cartílago se necrosa y queda la «oreja en coliflor»."]),
  ("Niño de 10 años", ["Golpe en el pabellón auricular hace 2 horas.", "Edema y nódulo en el pabellón."]),
  ["Drenaje (aspiración o incisión) en las primeras horas y vendaje compresivo o puntos de colchonero.",
   "Antibiótico con cobertura de Pseudomonas si hay herida (riesgo de pericondritis).",
   "Controlar a las 24-48 h: se reacumula con frecuencia."],
  "AAFP, trauma auricular (2017); Cummings Otolaryngology 7.ª ed.",
  op=("¿Diagnóstico?", ["Sí: golpe + bulto agudo", "Más tardío y seroso", "No: infección, con dolor y fiebre", "No: con fiebre y pus",
                        "Puede acompañar, pero el bulto es sangre"]),
  arbol=Q("Bulto en el pabellón tras un golpe: ¿es reciente y fluctuante?", [
      L("Sí (este caso)", "HEMATOMA: DRENAR", ["Vendaje compresivo", "Control 24-48 h"], path=True),
      L("Con fiebre y dolor", "Pericondritis o absceso", ["Antibiótico, drenaje"])], path=True),
  banda=B("Así se ve", P("hematoma_oreja.jpg", 230, 296, [
            ("flecha", 0.45, 0.40, 0.70, 0.90, "sangre bajo el pericondrio")],
          credito="Klaus D. Peter" + CC + "CC BY 3.0 DE"),
          [("Bulto violáceo", "Borra los relieves del pabellón."),
           ("Separa el pericondrio", "El cartílago queda sin irrigación."),
           ("Drenar en horas", "Evita la necrosis del cartílago."),
           ("Si no: oreja en coliflor", "Deformidad permanente (luchadores).")],
          pie="Oreja de otro paciente.", ans=0))

# PED-103 · Síndrome nefrótico: proteinuria ≥ 40 mg/m²/h · ÁRBOL + definiciones IPNA
S("arbol", "PED-103", "Niño con edema palpebral y de piernas y proteinuria: el síndrome nefrótico se confirma con proteinuria ≥ 40 mg/m²/h",
  "Síndrome nefrótico · diagnóstico en el niño",
  ("Síndrome nefrótico en el niño", ["Proteinuria masiva + hipoalbuminemia (< 3 g/dL) + edema; en niños casi siempre por lesiones mínimas.",
                                     "En niños la proteinuria se mide por superficie corporal o con el cociente proteína/creatinina."]),
  ("Niño de 5 años", ["3 días de palidez y edema de piernas.", "Edema palpebral y de miembros inferiores; proteínas ++/+++ en orina."]),
  ["Proteinuria nefrótica: ≥ 40 mg/m²/h en orina de 24 h, o cociente proteína/creatinina ≥ 2 mg/mg (200 mg/mmol).",
   "En adultos el umbral es > 3,5 g/día.",
   "Prednisona 60 mg/m²/día (máx. 60 mg) por 4-6 semanas y luego en días alternos."],
  "IPNA, síndrome nefrótico sensible a esteroides (2023); " + KDIGO + " (2021).",
  op=("¿Valor?", ["Es el umbral del adulto", "No es el umbral estándar", "Sí: umbral pediátrico", "No es el umbral", "Lo supera, pero el corte es 40"]),
  arbol=Q("Edema con proteinuria en un niño: ¿≥ 40 mg/m²/h?", [
      L("Sí", "SÍNDROME NEFRÓTICO", ["+ albúmina < 3 g/dL", "Prednisona"], path=True),
      L("4-40 mg/m²/h", "Proteinuria no nefrótica", ["Estudiar"])], path=True),
  escala=dict(nombre="Proteinuria en el niño (IPNA)", orden=True,
              que="Por superficie corporal en 24 h o por el cociente proteína/creatinina.",
              grados=[("< 4 mg/m²/h", "Normal", ["Cociente < 0,2 mg/mg"]), ("4-40 mg/m²/h", "Proteinuria", ["Cociente 0,2-2"]),
                      ("≥ 40 mg/m²/h", "Rango nefrótico", ["Cociente ≥ 2 mg/mg"])],
              caso=2, porque=[("Edema generalizado y proteínas +++", True), ("Falta la cifra exacta", True)],
              conducta="Cuantificar la proteinuria, albúmina y lípidos; iniciar prednisona."))

# HEM-020 · Trombocitopenia inducida por heparina · ÁRBOL + 4T
S("arbol", "HEM-020", "Al 8.º día de heparina no fraccionada, las plaquetas caen a 27 000 con petequias: trombocitopenia inducida por heparina",
  "Hemostasia · trombocitopenia por fármacos",
  ("Trombocitopenia inducida por heparina (TIH)", ["Anticuerpos contra el complejo heparina-factor plaquetario 4 activan las plaquetas.",
                                                   "Caída > 50 % a los 5-10 días; paradójicamente da TROMBOSIS más que sangrado."]),
  ("Mujer de 71 años, posoperada de cadera", ["Probable TEP tratado con heparina no fraccionada.",
                                               "Día 8: petequias y equimosis; plaquetas 27 200; TP y TTPa normales."]),
  ["Suspender TODA heparina (incluida la de lavado de vías).",
   "Anticoagular con un no heparínico: argatrobán, fondaparinux o un DOAC.",
   "Confirmar con anticuerpos anti-PF4 y prueba funcional; no transfundir plaquetas salvo sangrado grave."],
  "ASH, trombocitopenia inducida por heparina (2018).",
  op=("¿Causa?", ["No: sin foco ni fiebre", "Sí: día 8 + caída de plaquetas", "No: TP y TTPa normales", "No: TTPa normal", "No: TP normal"]),
  arbol=Q("Plaquetas que caen > 50 % a los 5-10 días de heparina: ¿4T intermedio o alto?", [
      L("Sí: 4T alto (este caso)", "TIH", ["Suspender heparina", "Argatrobán o fondaparinux"], path=True),
      L("No", "Otra causa", ["Sepsis, fármacos, CID"])], path=True),
  escala=dict(nombre="Puntaje 4T", modo="puntaje",
              que="Probabilidad clínica de TIH (0-8 puntos).",
              items=[("T", "Trombocitopenia: caída > 50 % y nadir ≥ 20 000", "27 200 (caída grande)", 2),
                     ("T", "Tiempo: día 5-10 de heparina", "Día 8", 2),
                     ("T", "Trombosis nueva", "No se describe", 0),
                     ("T", "Otras causas: ninguna aparente", "TP, TTPa normales, sin sepsis", 2)],
              total_txt="Total: 6 puntos", total_nota="máximo 8",
              rangos=[("0-3", "Baja", "Buscar otra causa"), ("4-5", "Intermedia", "Pedir anticuerpos"), ("6-8", "Alta", "Suspender heparina ya")],
              caso_rango=2, porque=[("Caída grande en el día 8, sin otra explicación", True)],
              conducta="Suspender la heparina y anticoagular con argatrobán o fondaparinux."))

# GAS-035 · Síndrome de Gilbert · ÁRBOL
S("arbol", "GAS-035", "Joven con ictericia leve que aparece con el ayuno, bilirrubina indirecta alta y todo lo demás normal (sin hemólisis): síndrome de Gilbert",
  "Ictericia · hiperbilirrubinemias hereditarias",
  ("Síndrome de Gilbert", ["Menor actividad de la enzima UGT1A1 que conjuga la bilirrubina (5-10 % de la población).",
                           "Bilirrubina indirecta levemente alta que sube con el ayuno, el estrés o la infección; hígado normal."]),
  ("Varón de 23 años", ["Ictericia de escleras con el ayuno que cede en 2 días; sin otros síntomas.",
                        "Bilirrubina total 3,1, directa 0,3; transaminasas, FA, DHL, haptoglobina y hematocrito normales."]),
  ["Diagnóstico por exclusión: sin hemólisis y con enzimas hepáticas normales.",
   "No requiere tratamiento; es benigno.",
   "Dubin-Johnson: bilirrubina DIRECTA alta, hígado negro."],
  HARRISON + "; AASLD.",
  op=("¿Diagnóstico?", ["No: DHL y haptoglobina normales", "Sí: indirecta alta con ayuno", "No: transaminasas normales", "No: hígado normal",
                        "No: daría bilirrubina directa"]),
  arbol=Q("Bilirrubina indirecta alta: ¿hay hemólisis (DHL alta, haptoglobina baja)?", [
      L("No: todo normal (este caso)", "SÍNDROME DE GILBERT", ["Benigno", "Sin tratamiento"], path=True),
      L("Sí", "Anemia hemolítica", ["Frotis, Coombs"])], path=True),
  escala=dict(nombre="Hiperbilirrubinemias hereditarias", orden=False,
              que="Según el tipo de bilirrubina y la gravedad.",
              grados=[("Indirecta leve", "Gilbert", ["Sube con ayuno", "Benigno"]),
                      ("Indirecta grave", "Crigler-Najjar", ["Neonatal, kernícterus"]),
                      ("Directa", "Dubin-Johnson", ["Hígado negro"]), ("Directa", "Rotor", ["Hígado normal"])],
              caso=0, porque=[("Bilirrubina directa 0,3: es indirecta", True), ("Aparece con el ayuno", True)],
              conducta="Tranquilizar; no requiere tratamiento."))

# HEM-021 · PTI en el niño · ÁRBOL + foto real
S("arbol", "HEM-021", "Niña de 3 años con petequias y gingivorragia 2 semanas después de un resfrío, plaquetas 8500 y el resto normal: trombocitopenia inmune primaria",
  "Hematología pediátrica · PTI",
  ("Trombocitopenia inmune primaria (PTI)", ["Anticuerpos contra las plaquetas tras una infección viral: plaquetas aisladamente bajas.",
                                             "Niño sano con petequias; sin hepatoesplenomegalia ni otras citopenias."]),
  ("Niña de 3 años", ["Rinofaringitis hace 2 semanas; petequias y sangrado al lavarse los dientes.",
                      "Plaquetas 8500; leucocitos y Hb casi normales; orina y creatinina normales."]),
  ["Sin sangrado importante: observar aunque las plaquetas estén bajas (se resuelve en semanas o meses).",
   "Sangrado de mucosas o riesgo: prednisona corta o inmunoglobulina EV.",
   "Si hay otras citopenias, adenopatías o bazo: médula ósea (descartar leucemia)."],
  "ASH, PTI (2019); consenso internacional de PTI (2019).",
  op=("¿Diagnóstico?", ["No: bajan las 3 series", "No: plaquetas normales", "No: orina y creatinina normales", "Sí: plaquetas aisladas tras un virus",
                        "No: sin bazo ni otras citopenias"]),
  arbol=Q("Plaquetas bajas aisladas en un niño sano tras un virus: ¿sangrado importante?", [
      L("Leve, de mucosas (este caso)", "PTI: OBSERVAR O TRATAR", ["Prednisona o IgIV si sangra"], path=True),
      L("Con otras citopenias o bazo", "Médula ósea", ["Descartar leucemia"])], path=True),
  banda=B("Así se ven las petequias", P("petequias.jpg", 330, 248, [
            ("circulo", 0.55, 0.45, 0.18, "petequias", 0.30, 0.88)],
          credito="James Heilman" + CC + "CC BY-SA 4.0"),
          [("Puntos rojos pequeños", "No desaparecen al presionar: sangre fuera del vaso."),
           ("En las piernas", "Donde la presión venosa es mayor."),
           ("Plaquetas muy bajas", "Esta foto: 3000 plaquetas."),
           ("Púrpura húmeda", "Sangrado de boca o nariz: más riesgo.")],
          pie="Pierna de otro paciente con PTI.", ans=0))

# CB-030 · Sildenafilo y visión de colores · TARJETAS
S("tarjetas", "CB-030", "Hombre tratado por disfunción eréctil con cefalea, rubor y visión azulada transitoria: efecto del sildenafilo",
  "Farmacología · inhibidores de la fosfodiesterasa 5",
  ("Sildenafilo", ["Inhibe la PDE5 del pene (vasodilatación) y en menor grado la PDE6 de la retina: visión azulada (cianopsia).",
                   "Otros efectos: cefalea, rubor facial, congestión nasal, dispepsia."]),
  ("Varón de 42 años", ["Cefalea y percepción pasajera de color azul-verdoso.", "Eritema facial; tratamiento para disfunción eréctil."]),
  ["Contraindicado con nitratos (hipotensión grave).",
   "La alteración visual es transitoria y depende de la dosis.",
   "Tadalafilo afecta menos la PDE6 (menos cianopsia)."],
  "FDA, ficha de sildenafilo (2024); Goodman & Gilman 14.ª ed.",
  op=("¿Medicamento?", ["No: alfa-2 antagonista", "No: no da cianopsia", "Sí: inhibe PDE6 de la retina", "No: es local", "Menos efecto sobre la PDE6"]),
  d=dict(rotulo="Fármacos para la disfunción eréctil", ans=0,
         cards=[dict(titulo="Sildenafilo", datos=[("Mecanismo", "PDE5 (y PDE6)", True), ("Ojo", "Visión azulada", True), ("Además", "Rubor, cefalea", True)],
                     pie="Este caso."),
                dict(titulo="Tadalafilo", datos=[("Mecanismo", "PDE5", False), ("Dura", "36 horas", False), ("Ojo", "Poco efecto", False)],
                     pie="Más selectivo."),
                dict(titulo="Alprostadilo", datos=[("Vía", "Intracavernosa", False), ("Mecanismo", "PGE1", False), ("Riesgo", "Priapismo", False)],
                     pie="Local."),
                dict(titulo="Testosterona", datos=[("Uso", "Hipogonadismo", False), ("Efecto", "Libido", False), ("Ojo", "No", False)],
                     pie="Hormonal.")]))

# GIN-091 · Falso trabajo de parto pretérmino · ÁRBOL
S("arbol", "GIN-091", "Gestante de 32 semanas con contracciones, cuello de 35 mm y fibronectina negativa: falso trabajo de parto, manejo expectante",
  "Parto pretérmino · amenaza",
  ("Amenaza de parto pretérmino", ["Contracciones sin cambios cervicales; muchas mujeres no llegan a parir.",
                                   "Cuello largo (≥ 30 mm) y fibronectina negativa: riesgo de parto en 7 días < 1 %."]),
  ("Primigesta de 32 semanas", ["2 horas de dolor tipo contracción; 2 contracciones en 20 minutos.",
                                "Longitud cervical 35 mm; fibronectina fetal negativa."]),
  ["Observar 2-6 horas, descartar infección urinaria o vaginal; alta con signos de alarma.",
   "Si el cuello < 15-20 mm o cambia: corticoide, tocólisis 48 h (nifedipino) y sulfato de magnesio si < 32 semanas.",
   "No tocolizar a todas: no mejora el resultado si no hay riesgo real."],
  ACOG + ", boletín 171, parto pretérmino (2016, reafirmado 2024); " + NICE + " NG25 (2022).",
  op=("¿Conducta?", ["No: bajo riesgo", "No: < 32 semanas y con parto inminente", "No: sin indicación", "Sí: cuello largo + fibronectina negativa",
                     "No: es por cuello corto sin contracciones"]),
  arbol=Q("Contracciones pretérmino: ¿cuello < 20 mm o fibronectina positiva?", [
      L("No: 35 mm y negativa (este caso)", "MANEJO EXPECTANTE", ["Observar", "Alta con alarmas"], path=True),
      L("Sí", "Riesgo real", ["Corticoide, tocólisis, MgSO₄"])], path=True))

# INF-045 · Neuritis óptica por etambutol · TARJETAS + Ishihara
S("tarjetas", "INF-045", "Paciente con TB en esquema 1 que al mes pierde agudeza visual y no distingue el verde: neuritis óptica por etambutol",
  "Tuberculosis · reacciones adversas",
  ("Neuritis óptica por etambutol", ["Daño del nervio óptico dependiente de la dosis (sobre todo > 15-25 mg/kg o falla renal).",
                                     "Primero se pierde la visión del rojo-verde; luego la agudeza visual."]),
  ("Paciente con TB pulmonar BK +", ["Esquema 1 (HRZE).", "Al mes: disminución de la agudeza visual y no ve el verde."]),
  ["Suspender el etambutol de inmediato: suele revertir si se detecta temprano.",
   "Agudeza visual y visión de colores (Ishihara) al inicio y cada mes.",
   "Ajustar la dosis si hay insuficiencia renal."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + ", manual de reacciones adversas (2025).",
  op=("¿Fármaco?", ["No: hepatitis, gota", "No: orina naranja, hepatitis", "Sí: vista y colores", "No: neuropatía periférica, hepatitis",
                    "No: sordera y vértigo"]),
  d=dict(rotulo="Antituberculosos: ¿qué efecto adverso?", ans=0,
         cards=[dict(titulo="Etambutol", datos=[("Daño", "Nervio óptico", True), ("Primero", "Rojo-verde", True), ("Control", "Ishihara", True)],
                     pie="Este caso."),
                dict(titulo="Isoniazida", datos=[("Daño", "Neuropatía, hígado", False), ("Previene", "Piridoxina", False), ("Ojo", "Raro", False)],
                     pie="Vitamina B6."),
                dict(titulo="Rifampicina", datos=[("Señal", "Orina naranja", False), ("Daño", "Hígado", False), ("Además", "Interacciones", False)],
                     pie="Inductor."),
                dict(titulo="Pirazinamida", datos=[("Daño", "Hígado", False), ("Además", "Ácido úrico alto", False), ("Síntoma", "Artralgias", False)],
                     pie="Gota.")]),
  banda=B("Así se controla la visión de colores", P("ishihara.jpg", 240, 240, [
            ("texto", 0.50, 0.94, "se lee «74»")],
          credito="Shinobu Ishihara" + CC + "dominio público", fondo="#ffffff"),
          [("Lámina de Ishihara", "Con buena visión de colores se lee el número."),
           ("Si no lo lee", "Alteración rojo-verde: primer signo de la toxicidad."),
           ("Cada mes", "Mientras se usa etambutol."),
           ("Suspender a tiempo", "La toxicidad suele revertir.")],
          pie="Lámina de la prueba.", ans=1))

# CAR-038 · Insuficiencia aórtica: Austin Flint · ÁRBOL + signos
S("arbol", "CAR-038", "Soplo diastólico decreciente en el borde esternal izquierdo, pulso saltón y soplo mesodiastólico mitral de Austin Flint: insuficiencia aórtica",
  "Valvulopatías · insuficiencia aórtica",
  ("Insuficiencia aórtica", ["La sangre regresa de la aorta al ventrículo izquierdo en la diástole.",
                             "Presión de pulso amplia: pulso saltón y muchos signos periféricos; el chorro hace vibrar la valva mitral (Austin Flint)."]),
  ("Varón de 60 años", ["Disnea de pequeños esfuerzos, palpitaciones, dolor precordial y edema.",
                        "Pulso saltón; soplo protodiastólico decreciente en borde esternal superior izquierdo; soplo de Austin Flint."]),
  ["Ecocardiograma: gravedad, tamaño y función del ventrículo izquierdo.",
   "Cirugía (reemplazo valvular) si es grave con síntomas, FEVI ≤ 55 % o VI muy dilatado.",
   "Vasodilatadores (IECA, nifedipino) solo para síntomas si no se puede operar."],
  "ACC/AHA, valvulopatías (2020); " + ESC + ", valvulopatías (2025).",
  op=("¿Diagnóstico?", ["No: soplo sistólico eyectivo", "No: holosistólico apical", "Sí: diastólico + pulso saltón + Austin Flint",
                        "Austin Flint la imita; aquí es aórtica", "No: sin pulso saltón"]),
  arbol=Q("Soplo diastólico decreciente con pulso saltón: ¿eco con regurgitación aórtica?", [
      L("Sí (este caso)", "INSUFICIENCIA AÓRTICA", ["Eco", "Cirugía si es grave y sintomática"], path=True),
      L("Retumbo mitral sin pulso saltón", "Estenosis mitral", ["Eco"])], path=True),
  triada=TR([("Pulso saltón (Corrigan)", "Sí", True), ("Soplo de Austin Flint", "Sí", True), ("Cabeceo (de Musset)", "No se describe", None),
             ("Pulso capilar (Quincke)", "No se describe", None), ("Disparo femoral (Traube)", "No se describe", None)],
            [("Signos de la insuficiencia aórtica", 0, 4)],
            "Todos se deben a la presión de pulso amplia."))
