"""Entrega 1 · tanda 16 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, AHA, IDSA
from esc28 import PAGE, ITU

CC = " · Wikimedia Commons · "

# CIR-033 · Apendicitis en el adolescente · ÁRBOL + Alvarado
S("arbol", "CIR-033", "Adolescente con 2 días de dolor, anorexia, vómitos, fiebre de 39 °C y contractura en fosa ilíaca derecha: apendicitis aguda",
  "Abdomen agudo · apendicitis",
  ("Apendicitis aguda", ["Obstrucción del apéndice con inflamación e infección; la urgencia quirúrgica abdominal más común.",
                         "Dolor que migra a la fosa ilíaca derecha, anorexia, náuseas, fiebre."]),
  ("Varón de 13 años", ["2 días de dolor abdominal, náuseas, vómitos, anorexia y estreñimiento.",
                        "39 °C, deshidratado; abdomen distendido, dolor y contractura en FID."]),
  ["Puntaje (Alvarado o AIR) para decidir: alto → cirugía; intermedio → ecografía o TC.",
   "Fiebre alta, 2 días y distensión: sospechar apendicitis complicada (perforada).",
   "Apendicectomía laparoscópica + antibiótico; hidratar antes de operar."],
  "WSES, guías de Jerusalén de apendicitis (2020); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: más leve, sin contractura", "No: dolor en cinturón, no FID", "Sí: dolor + contractura en FID + fiebre",
                        "Posible complicación; el foco es la FID", "Raro; da sangrado o diverticulitis"]),
  arbol=Q("Dolor en FID: ¿puntaje de Alvarado?", [
      L("≥ 7: probable", "APENDICITIS AGUDA", ["Apendicectomía", "Antibiótico"], path=True),
      L("5-6: posible", "Ecografía o TC", ["Observar"])], path=True),
  escala=dict(nombre="Puntaje de Alvarado", modo="puntaje", que="Estima la probabilidad de apendicitis (0 a 10).",
              items=[("M", "Dolor que migra a la FID (1)", "No se describe", 0), ("A", "Anorexia (1)", "Sí", 1), ("N", "Náuseas o vómitos (1)", "Sí", 1),
                     ("T", "Dolor en FID (2)", "Sí", 2), ("R", "Rebote o defensa (1)", "Contractura", 1), ("E", "Fiebre ≥ 37,3 °C (1)", "39 °C", 1),
                     ("L", "Leucocitosis (2)", "Sin dato", None), ("S", "Desviación izquierda (1)", "Sin dato", None)],
              total_txt="Total: 6 puntos (sin laboratorio)", total_nota="con leucocitosis llegaría a 8-9",
              rangos=[("≥ 7", "Probable", "Cirugía"), ("5-6", "Posible", "Ecografía o TC"), ("≤ 4", "Improbable", "Alta con control")],
              caso_rango=1, porque=[("Seis puntos solo con la clínica", True), ("Con el hemograma pasaría a probable", True)],
              conducta="Hemograma, hidratación y apendicectomía; antibiótico por sospecha de perforación."))

# CIR-034 · Fístula arteriovenosa traumática · TARJETAS + signos
S("tarjetas", "CIR-034", "Herida de bala en el muslo hace un año con hinchazón, frémito y soplo en la cicatriz y pulsos distales bajos: fístula arteriovenosa",
  "Trauma vascular · fístula arteriovenosa",
  ("Fístula arteriovenosa traumática", ["Una herida penetrante comunica una arteria con su vena: la sangre pasa directo a la vena.",
                                        "Frémito, soplo, venas dilatadas y edema; los pulsos distales bajan (robo)."]),
  ("Varón de 24 años", ["Herida de bala en el muslo izquierdo hace 1 año.", "Hinchazón, dolor al caminar; frémito y soplo sobre la cicatriz; pulsos poplíteo y pedio bajos."]),
  ["AngioTC o arteriografía para ver la comunicación.",
   "Reparación endovascular (stent cubierto) o cirugía; si es grande puede causar insuficiencia cardiaca de alto gasto.",
   "Seudoaneurisma: masa pulsátil con soplo sistólico, sin vena dilatada."],
  "ESVS, trauma vascular (2025); " + ATLS + ".",
  op=("¿Diagnóstico?", ["Sí: frémito + soplo tras herida", "No: no da frémito ni soplo", "No: pulsos ausentes, sin frémito",
                        "No: sin fiebre ni fluctuación", "No: sin frémito ni soplo"]),
  d=dict(rotulo="Pierna hinchada tras una herida: ¿cuál?", ans=0,
         cards=[dict(titulo="Fístula AV", datos=[("Tacto", "Frémito", True), ("Auscultación", "Soplo", True), ("Antes", "Herida penetrante", True)],
                     pie="Este caso."),
                dict(titulo="Seudoaneurisma", datos=[("Tacto", "Masa pulsátil", False), ("Soplo", "Solo sistólico", False), ("Venas", "Normales", False)],
                     pie="Stent o cirugía."),
                dict(titulo="TVP", datos=[("Tacto", "Sin frémito", False), ("Edema", "Con fóvea", False), ("Eco", "Vena no compresible", False)],
                     pie="Anticoagular."),
                dict(titulo="Linfedema", datos=[("Edema", "Duro, sin fóvea", False), ("Soplo", "No", False), ("Piel", "Engrosada", False)],
                     pie="Compresión.")]),
  triada=TR([("Frémito", "Sí", True), ("Soplo continuo o holosistólico", "Sí", True), ("Pulsos distales bajos", "Poplíteo y pedio", True),
             ("Signo de Nicoladoni-Branham", "No se informa", False)],
            [("Signos de fístula arteriovenosa", 0, 3)],
            "Al comprimir la fístula baja la FC (Branham): confirma un cortocircuito grande.", rotulo="Signos con nombre propio"))

# CIR-035 · Insuficiencia venosa crónica · TARJETAS + CEAP
S("tarjetas", "CIR-035", "Pesadez vespertina de ambas piernas con hiperpigmentación de la pantorrilla y pulsos presentes: insuficiencia venosa crónica",
  "Enfermedad venosa · insuficiencia venosa crónica",
  ("Insuficiencia venosa crónica", ["Las válvulas de las venas fallan: la sangre se estanca y sube la presión venosa.",
                                    "Pesadez y cansancio al final del día, várices, edema, piel oscura y úlceras."]),
  ("Mujer de 60 años", ["Pesadez y cansancio en ambas piernas, peor en la tarde.", "Hiperpigmentación de la parte baja de la pantorrilla; pulsos presentes; sin edema."]),
  ["Eco Doppler venoso: confirma el reflujo y planifica el tratamiento.",
   "Medias de compresión, elevar las piernas, ejercicio; flebotónicos para los síntomas.",
   "Ablación térmica (láser o radiofrecuencia) de la safena si hay reflujo y síntomas o cambios de piel."],
  "ESVS, enfermedad venosa crónica (2022); clasificación CEAP (act. 2020).",
  op=("¿Diagnóstico?", ["No: edema duro, sin pigmento", "No: aguda, dolorosa, con edema", "No: pulsos presentes",
                        "Sí: pesadez + hiperpigmentación", "No: sería bilateral con edema y disnea"]),
  d=dict(rotulo="Piernas pesadas: ¿cuál?", ans=0,
         cards=[dict(titulo="Insuficiencia venosa", datos=[("Síntoma", "Pesadez vespertina", True), ("Piel", "Oscura", True), ("Pulsos", "Presentes", True)],
                     pie="Este caso."),
                dict(titulo="Isquemia arterial", datos=[("Síntoma", "Claudicación", False), ("Piel", "Pálida, fría", False), ("Pulsos", "Bajos", False)],
                     pie="ITB."),
                dict(titulo="TVP", datos=[("Inicio", "Agudo", False), ("Edema", "Unilateral", False), ("Dolor", "Sí", False)],
                     pie="Eco Doppler."),
                dict(titulo="Linfedema", datos=[("Edema", "Duro", False), ("Dedos", "Afectados", False), ("Piel", "Gruesa", False)],
                     pie="Compresión.")]),
  escala=dict(nombre="Clasificación CEAP (clínica)", orden=True, que="Gradúa la enfermedad venosa crónica por lo que se ve en la pierna.",
              grados=[("C0", "Sin signos", ["Solo síntomas"]), ("C1", "Telangiectasias", ["Arañitas"]), ("C2", "Várices", ["≥ 3 mm"]),
                      ("C3", "Edema", ["Sin cambios de piel"]), ("C4", "Cambios de piel", ["Pigmento, eccema, lipodermatoesclerosis"]),
                      ("C5", "Úlcera cicatrizada", ["Cicatriz"]), ("C6", "Úlcera activa", ["Abierta"])],
              caso=4, porque=[("Hiperpigmentación de la pantorrilla", True), ("Sin úlcera", True)],
              conducta="Compresión, Doppler venoso y ablación si hay reflujo."))

# CIR-036 · Hemotórax masivo · ÁRBOL + volumen
S("arbol", "CIR-036", "Hemotórax con más de 1500 mL al colocar el tubo y PA < 60 pese a transfundir: toracotomía",
  "Trauma torácico · hemotórax masivo",
  ("Hemotórax masivo", ["Sangrado de grandes vasos o de la pared en el tórax: choque hemorrágico.",
                        "Matidez, murmullo ausente, yugulares planas."]),
  ("Varón de 44 años", ["Choque contra un muro; hemotórax de 2/3 del hemitórax izquierdo.", "Tubo: > 1500 mL en una hora; PA < 60 pese a reponer sangre."]),
  ["Toracotomía si drena > 1500 mL al colocar el tubo, > 200 mL/h por 2-4 horas, o sigue inestable.",
   "Mientras tanto: transfusión masiva 1:1:1 y ácido tranexámico.",
   "Un segundo tubo no detiene el sangrado; la toracoscopia es para pacientes estables."],
  ATLS + ".",
  op=("¿Conducta?", ["Sí: sangrado activo con choque", "No: es para hemotórax coagulado o empiema", "Necesaria, pero no detiene el sangrado",
                     "Solo en estables", "No detiene el sangrado"]),
  arbol=Q("Hemotórax con tubo: ¿> 1500 mL al inicio o inestable?", [
      L("Sí (este caso)", "TORACOTOMÍA", ["Controlar el vaso", "Transfusión masiva"], path=True),
      L("No", "Tubo de tórax y vigilar", ["Toracotomía si > 200 mL/h"])], path=True),
  escala=dict(nombre="Tamaño del hemotórax", orden=True, que="Por el volumen de sangre en el tórax.",
              grados=[("Pequeño", "< 500 mL", ["Observar o tubo"]), ("Moderado", "500-1500 mL", ["Tubo de tórax"]),
                      ("Masivo", "> 1500 mL", ["O > 200 mL/h", "Toracotomía"])],
              caso=2, porque=[("> 1500 mL en una hora", True), ("PA < 60 pese a transfundir", True)],
              conducta="Toracotomía urgente con transfusión masiva."))

# OFT-010 · Fractura del piso de la órbita · ÁRBOL + signos + TC real
S("arbol", "OFT-010", "Golpe con una piedra en el ojo con diplopía y enoftalmos: fractura del piso (pared inferior) de la órbita",
  "Traumatismo ocular · fractura de la órbita",
  ("Fractura del piso de la órbita («blow-out»)", ["El golpe aumenta la presión dentro de la órbita y rompe su pared más delgada: el piso.",
                                                   "La grasa y el recto inferior caen al seno maxilar: diplopía y enoftalmos."]),
  ("Varón de 18 años", ["Golpe con una piedra en el ojo derecho hace 2 horas.", "Diplopía, enoftalmos derecho; fractura de órbita."]),
  ["TC de órbitas (cortes coronales); revisar la agudeza visual y descartar lesión del globo.",
   "Cirugía urgente si el músculo está atrapado con náuseas y bradicardia (reflejo oculocardiaco), sobre todo en niños.",
   "Si no: reparar en 1-2 semanas si el enoftalmos es > 2 mm o la diplopía persiste; no sonarse la nariz."],
  "AAO, trauma orbitario; Kanski, Oftalmología clínica 10.ª ed. (2024).",
  op=("¿Pared?", ["No: es gruesa y rara", "Sí: el piso es la más delgada", "No: es la más gruesa", "Segunda en frecuencia (lámina papirácea)",
                  "No: raras y por golpes muy fuertes"]),
  arbol=Q("Golpe en la órbita con diplopía: ¿hay atrapamiento con reflejo oculocardiaco?", [
      L("No (este caso)", "FRACTURA DEL PISO", ["TC coronal", "Cirugía en 1-2 semanas si hace falta"], path=True),
      L("Sí", "Cirugía urgente", ["Liberar el recto inferior"])], path=True),
  triada=TR([("Diplopía (mirada vertical)", "Sí", True), ("Enoftalmos", "Sí", True), ("Hipoestesia de la mejilla", "No se informa", False),
             ("Limitación de la mirada hacia arriba", "No se informa", False)],
            [("Signos de fractura del piso", 0, 3)],
            "Diplopía + enoftalmos tras un golpe directo: fractura del piso.", rotulo="Signos con nombre propio"),
  banda=B("TC coronal real de fractura del piso de la órbita", P("orbita_piso.jpg", 340, 224, [
            ("texto", 0.08, 0.05, "DER"), ("texto", 0.92, 0.05, "IZQ"),
            ("flecha", 0.72, 0.65, 0.5, 0.93, "piso roto: grasa\nque cae al seno")],
          credito="James Heilman" + CC + "CC BY-SA 4.0"),
          [("Piso hundido", "El hueso bajo el ojo está roto y desplazado hacia el seno maxilar."),
           ("Signo de la «gota»", "Grasa y músculo cuelgan dentro del seno como una gota."),
           ("Seno con sangre", "El seno maxilar se ocupa de sangre (nivel o velamiento)."),
           ("Cortes coronales", "Son los que mejor muestran el piso de la órbita.")],
          pie="TC de otro paciente (fractura izquierda).", ans=0))

# OFT-011 · Queratoconjuntivitis por adenovirus · TARJETAS + foto real
S("tarjetas", "OFT-011", "Ojo rojo bilateral con lagrimeo, hemorragias conjuntivales, opacidades corneales y ganglio preauricular doloroso: adenovirus",
  "Oftalmología · conjuntivitis",
  ("Queratoconjuntivitis epidémica (adenovirus)", ["La conjuntivitis viral más contagiosa; brotes en familias y consultorios.",
                                                    "Ojo rojo con lagrimeo, folículos, hemorragias, ganglio preauricular e infiltrados corneales."]),
  ("Varón de 22 años", ["Ojo rojo y lagrimeo.", "Hemorragias conjuntivales en ambos ojos, opacidades corneales redondas; ganglio preauricular doloroso."]),
  ["Tratamiento de soporte: compresas frías, lágrimas artificiales; dura 2-3 semanas.",
   "Muy contagiosa: lavado de manos, no compartir toallas, desinfectar instrumentos.",
   "Los antibióticos no sirven; los corticoides tópicos solo los indica el oftalmólogo (infiltrados que bajan la visión)."],
  "AAO, Preferred Practice Pattern: conjuntivitis (2023).",
  op=("¿Agente?", ["Sí: ganglio preauricular + infiltrados", "No: folicular crónica, sexual", "No: unilateral, dendritas",
                   "No: vesículas en la piel", "No: pus abundante e hiperagudo"]),
  d=dict(rotulo="Ojo rojo con secreción: ¿qué germen?", ans=0,
         cards=[dict(titulo="Adenovirus", datos=[("Secreción", "Acuosa", True), ("Ganglio", "Preauricular", True), ("Córnea", "Infiltrados", True)],
                     pie="Este caso."),
                dict(titulo="Clamidia", datos=[("Curso", "Crónico", False), ("Folículos", "Grandes", False), ("Antecedente", "Sexual", False)],
                     pie="Azitromicina."),
                dict(titulo="Herpes", datos=[("Lado", "Unilateral", False), ("Córnea", "Dendritas", False), ("Piel", "Vesículas", False)],
                     pie="Aciclovir."),
                dict(titulo="Gonococo", datos=[("Secreción", "Pus abundante", False), ("Curso", "Hiperagudo", False), ("Riesgo", "Perforar córnea", False)],
                     pie="Ceftriaxona.")]),
  banda=B("Queratoconjuntivitis por adenovirus (foto real)", P("queratoconj.jpg", 360, 201, [
            ("flecha", 0.15, 0.55, 0.12, 0.92, "hemorragia\nconjuntival"),
            ("flecha", 0.65, 0.4, 0.8, 0.1, "ojo muy rojo")],
          credito="Marco Mayer" + CC + "CC BY-SA 4.0"),
          [("Ojo muy rojo", "Inyección difusa de toda la conjuntiva."),
           ("Hemorragias", "Manchas de sangre bajo la conjuntiva, típicas del adenovirus."),
           ("Lagrimeo", "Secreción acuosa, no purulenta."),
           ("Córnea", "A la semana aparecen infiltrados redondos que pueden nublar la visión.")],
          pie="Ojo de otro paciente.", ans=0))

# NEF-027 · Cáncer testicular en el adolescente · TARJETAS + tipos
S("tarjetas", "NEF-027", "Adolescente con testículo aumentado, duro, indoloro y transiluminación negativa: cáncer de testículo",
  "Urología oncológica · cáncer de testículo",
  ("Cáncer testicular", ["Masa sólida, dura e indolora del testículo en un varón joven.",
                         "No transilumina (no es líquido)."]),
  ("Varón de 15 años", ["Aumento de volumen y de consistencia del testículo derecho.", "Indoloro; transiluminación negativa."]),
  ["Ecografía escrotal: masa sólida intratesticular.",
   "Marcadores (AFP, β-hCG, LDH) antes de la orquiectomía inguinal; nunca biopsia por el escroto.",
   "Muy curable incluso con metástasis (quimioterapia con platino)."],
  "EAU, tumores de células germinales del testículo (2025); NCCN Testicular Cancer (2025).",
  op=("¿Diagnóstico?", ["No: dolor y fiebre", "No: transiluminaría", "Sí: sólido, duro, indoloro", "No: dolor brusco intenso",
                        "No: bolsa de gusanos, blando"]),
  d=dict(rotulo="Testículo aumentado: ¿cuál?", ans=0,
         cards=[dict(titulo="Cáncer", datos=[("Dolor", "No", True), ("Consistencia", "Dura", True), ("Transilumina", "No", True)],
                     pie="Este caso."),
                dict(titulo="Hidrocele", datos=[("Dolor", "No", False), ("Consistencia", "Quística", False), ("Transilumina", "Sí", False)],
                     pie="Observar."),
                dict(titulo="Torsión", datos=[("Dolor", "Brusco", False), ("Reflejo cremastérico", "Ausente", False), ("Urgencia", "< 6 h", False)],
                     pie="Cirugía."),
                dict(titulo="Orquiepididimitis", datos=[("Dolor", "Gradual", False), ("Fiebre", "Sí", False), ("Prehn", "Alivia", False)],
                     pie="Antibiótico.")]),
  escala=dict(nombre="Tipos de tumor de células germinales", orden=False, que="Cambia el marcador y el tratamiento.",
              grados=[("Seminoma", "30-40 años", ["AFP normal", "Muy sensible a radio y quimioterapia"]),
                      ("No seminoma", "15-30 años", ["AFP o β-hCG altas", "Embrionario, saco vitelino, coriocarcinoma, teratoma"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("A los 15 años son más comunes los no seminomas", True), ("Los marcadores y la histología lo definen", True)],
              conducta="Ecografía, marcadores y orquiectomía inguinal."))

# NEF-028 · Litiasis: TC sin contraste · ÁRBOL + tamaño
S("arbol", "NEF-028", "Cólico lumbar derecho irradiado a genitales con puñopercusión positiva: tomografía helicoidal sin contraste",
  "Urolitiasis · diagnóstico por imágenes",
  ("Cólico renal por litiasis", ["Un cálculo obstruye el uréter: dolor lumbar en oleadas que baja a la ingle y genitales.",
                                 "La TC sin contraste es la prueba más exacta."]),
  ("Varón de 40 años", ["2 meses de dolor lumbar derecho tipo cólico, a veces intenso, irradiado a genitales.",
                        "Puñopercusión y puntos ureterales derechos positivos."]),
  ["TC sin contraste de baja dosis: ve casi todos los cálculos, su tamaño y la obstrucción.",
   "Ecografía primero en gestantes y niños; la Rx simple no ve los cálculos de ácido úrico.",
   "< 5-10 mm: analgesia (AINE) y tamsulosina; fiebre con obstrucción: drenar urgente."],
  "EAU, guía de urolitiasis (2025); ACR Appropriateness Criteria (2023).",
  op=("¿Imagen de elección?", ["Sí: la más exacta", "No ve los radiolúcidos", "Primera en gestantes y niños; menos exacta",
                               "Obsoleta: contraste y radiación", "No: ve función, no el cálculo"]),
  arbol=Q("Sospecha de cólico renal: ¿gestante o niño?", [
      L("No: adulto (este caso)", "TC SIN CONTRASTE", ["Baja dosis"], path=True),
      L("Sí", "Ecografía", ["Sin radiación"])], path=True),
  escala=dict(nombre="Tamaño del cálculo y expulsión espontánea", orden=True, que="Orienta si esperar o intervenir.",
              grados=[("< 5 mm", "Muy probable", ["~ 70-90 % salen solos"]), ("5-10 mm", "Posible", ["Tamsulosina ayuda"]),
                      ("> 10 mm", "Poco probable", ["Ureteroscopia o litotricia"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("La TC dará el tamaño y la ubicación", True), ("2 meses de dolor: probable cálculo que no pasa", True)],
              conducta="TC sin contraste y decidir según tamaño, ubicación y síntomas."))

# TRA-010 · Síndrome compartimental · ÁRBOL + signos
S("arbol", "TRA-010", "Fractura de tibia con pierna tensa, brillante y pulso pedio ausente: síndrome compartimental, fasciotomía",
  "Complicaciones de las fracturas · síndrome compartimental",
  ("Síndrome compartimental agudo", ["La presión dentro de un compartimento muscular supera la de los capilares: isquemia.",
                                     "Fractura de tibia es la causa más común; se pierden músculo y nervio en horas."]),
  ("Mujer de 30 años atropellada", ["Dolor, deformidad e inmovilidad de la pierna derecha; fractura de tibia.",
                                    "Pierna aumentada de volumen, piel tensa y brillante, pulso pedio ausente."]),
  ["Retirar vendajes o yesos y no elevar la pierna por encima del corazón.",
   "Fasciotomía urgente (diagnóstico clínico; o presión diastólica − compartimental < 30 mmHg).",
   "El pulso ausente es tardío: con pulso ausente pensar también en lesión arterial (angioTC)."],
  "BOA/BOAST, síndrome compartimental (2016); " + ATLS + ".",
  op=("¿Indicación?", ["No: no descomprime", "Sí: libera la presión", "Va después, no resuelve la presión", "Va después, no resuelve la presión",
                       "No: aumenta la presión"]),
  arbol=Q("Fractura con dolor intenso y pierna tensa: ¿compartimental?", [
      L("Sí (este caso)", "FASCIOTOMÍA DESCOMPRESIVA", ["Urgente", "Luego fijar la fractura"], path=True),
      L("Dudoso", "Medir la presión", ["Diferencia < 30 mmHg: operar"])], path=True),
  triada=TR([("Dolor desproporcionado", "Dolor intenso", True), ("Dolor al estirar pasivamente", "No se informa", False),
             ("Compartimento tenso", "Piel tensa y brillante", True), ("Parestesias", "No se informa", False), ("Pulso ausente (tardío)", "Pedio ausente", True)],
            [("Signos del síndrome compartimental", 0, 4)],
            "El dolor y la tensión bastan; no esperar a que falte el pulso.", rotulo="Signos con nombre propio"))

# TRA-011 · Embolia grasa · TARJETAS + Gurd
S("tarjetas", "TRA-011", "Tres días después de una fractura de fémur: confusión, disnea, petequias en el pecho y PaO₂ 50 con pulmón normal: embolia grasa",
  "Complicaciones de las fracturas · embolia grasa",
  ("Síndrome de embolia grasa", ["Gotas de grasa de la médula ósea pasan a la sangre tras fracturas de huesos largos.",
                                 "24-72 horas después: hipoxemia, confusión y petequias."]),
  ("Varón de 30 años", ["Fractura de fémur en moto; 3 días después confusión, disnea y petequias en el pecho.",
                        "Pulmones normales al examen; PaO₂ 50, PaCO₂ 28, pH 7,49."]),
  ["Tratamiento de soporte: oxígeno, ventilación si hace falta, líquidos.",
   "Prevención: fijar pronto las fracturas de huesos largos.",
   "TEP: sin petequias ni confusión al inicio; la angioTC lo diferencia."],
  ATLS + "; Rockwood and Green's Fractures in Adults 10.ª ed. (2024).",
  op=("¿Diagnóstico?", ["Sí: tríada tras fractura de fémur", "No: aparece enseguida, con opacidades", "No: tras aspirar, con opacidades",
                        "No: fiebre y dolor óseo, no hipoxemia", "No explica petequias ni confusión"]),
  d=dict(rotulo="Hipoxemia tras una fractura: ¿cuál?", ans=0,
         cards=[dict(titulo="Embolia grasa", datos=[("Cuándo", "24-72 h", True), ("Piel", "Petequias", True), ("Mente", "Confusión", True)],
                     pie="Este caso."),
                dict(titulo="TEP", datos=[("Cuándo", "Días o semanas", False), ("Piel", "Sin petequias", False), ("Pierna", "Puede haber TVP", False)],
                     pie="Anticoagular."),
                dict(titulo="Contusión pulmonar", datos=[("Cuándo", "Horas", False), ("Rx", "Opacidades", False), ("Causa", "Golpe en el tórax", False)],
                     pie="Soporte."),
                dict(titulo="Neumonitis química", datos=[("Antes", "Aspiración", False), ("Rx", "Opacidades", False), ("Piel", "Normal", False)],
                     pie="Soporte.")]),
  triada=TR([("Insuficiencia respiratoria", "PaO₂ 50", True), ("Alteración neurológica", "Confusión", True), ("Petequias", "En el pecho", True)],
            [("Criterios mayores de Gurd", 0, 2)],
            "Tres criterios mayores tras una fractura de fémur: embolia grasa.", rotulo="Criterios con nombre propio"))

# CIR-037 · Absceso perianal · ÁRBOL + clasificación
S("arbol", "CIR-037", "Diabético con dolor perianal, fiebre y tumefacción con flogosis: absceso perianal",
  "Patología anorrectal · absceso",
  ("Absceso anorrectal", ["Infección de una glándula anal que forma pus en los espacios alrededor del ano.",
                          "Dolor constante, tumefacción roja y caliente, fiebre."]),
  ("Varón de 50 años, diabético", ["Dolor perianal, fiebre y tumefacción.", "Aumento de volumen del periné posterior con flogosis."]),
  ["Drenaje quirúrgico urgente: no esperar a que «madure» ni tratar solo con antibióticos.",
   "Antibiótico además en diabéticos, inmunodeprimidos o con celulitis extensa.",
   "En diabéticos vigilar gangrena de Fournier; 30-50 % quedan con fístula."],
  "ASCRS, abscesos y fístulas anorrectales (2022).",
  op=("¿Diagnóstico?", ["Sí: dolor + fiebre + flogosis", "No: nódulo azulado sin fiebre", "No: dolor al defecar, sin fiebre",
                        "No: sangrado, sin fiebre aguda", "No: en el pliegue sacro, no perianal"]),
  arbol=Q("Dolor perianal con fiebre: ¿masa fluctuante y roja?", [
      L("Sí (este caso)", "ABSCESO PERIANAL", ["Drenaje urgente", "Antibiótico: diabético"], path=True),
      L("Crepitación o necrosis", "Gangrena de Fournier", ["Desbridamiento urgente"])], path=True),
  escala=dict(nombre="Tipos de absceso anorrectal", orden=False, que="Según el espacio donde se acumula el pus.",
              grados=[("Perianal", "El más común", ["Junto al ano, visible"]), ("Isquiorrectal", "Más profundo", ["Nalga dolorosa"]),
                      ("Interesfintérico", "Entre esfínteres", ["Dolor sin masa visible"]), ("Supraelevador", "Raro", ["Dolor pélvico, fiebre"])],
              caso=0, porque=[("Tumefacción visible del periné con flogosis", True), ("Fiebre y dolor perianal", True)],
              conducta="Drenaje quirúrgico y antibiótico por la diabetes."))

# CIR-038 · Prolapso rectal · TARJETAS + dibujo clásico
S("tarjetas", "CIR-038", "Mujer de 65 años con estreñimiento crónico y una masa que sale por el ano al pujar y se reintroduce: prolapso rectal",
  "Patología anorrectal · prolapso rectal",
  ("Prolapso rectal", ["El recto sale por el ano en todo su espesor (procidencia) o solo la mucosa.",
                       "Mujeres mayores con estreñimiento y pujo crónico; a veces incontinencia."]),
  ("Mujer de 65 años", ["Estreñimiento crónico.", "Desde hace 10 años sale una masa por el ano al pujar que ella reintroduce."]),
  ["Prolapso completo: pliegues concéntricos (circulares); hemorroides y prolapso mucoso: pliegues radiales.",
   "Tratamiento quirúrgico: rectopexia (ventral laparoscópica) si puede operarse; perineal (Delorme, Altemeier) en frágiles.",
   "Tratar el estreñimiento; colonoscopia para descartar tumor."],
  "ASCRS, prolapso rectal (2023).",
  op=("¿Diagnóstico?", ["Sí: masa que sale al pujar y se reduce", "Pliegues radiales, sangrado", "Masa fija, sangrado, pérdida de peso",
                        "Dolor, moco y sangre", "No salen al pujar; dolor si se trombosan"]),
  d=dict(rotulo="Masa que sale por el ano: ¿cuál?", ans=0,
         cards=[dict(titulo="Prolapso rectal", datos=[("Pliegues", "Circulares", True), ("Quién", "Mujer mayor", True), ("Se reduce", "Sí", True)],
                     pie="Este caso: rectopexia."),
                dict(titulo="Hemorroide interna", datos=[("Pliegues", "Radiales", False), ("Síntoma", "Sangrado rojo", False), ("Grado", "III-IV si sale", False)],
                     pie="Ligadura o cirugía."),
                dict(titulo="Cáncer de recto", datos=[("Masa", "Fija, dura", False), ("Sangre", "Sí", False), ("Peso", "Baja", False)],
                     pie="Colonoscopia."),
                dict(titulo="Úlcera rectal solitaria", datos=[("Síntoma", "Moco y sangre", False), ("Pujo", "Mucho", False), ("Biopsia", "Fibrosis", False)],
                     pie="Biorretroalimentación.")]),
  escala=dict(nombre="Tipos de prolapso rectal", orden=True, que="Según el espesor que sale.",
              grados=[("Interno", "Intususcepción", ["No sale por el ano"]), ("Mucoso", "Solo mucosa", ["Pliegues radiales"]),
                      ("Completo", "Todo el espesor (procidencia)", ["Pliegues circulares", "Cirugía"])],
              caso=2, porque=[("Masa que sale al pujar desde hace 10 años", True), ("Se reintroduce: confirmar pliegues circulares al examen", True)],
              conducta="Colonoscopia, tratar el estreñimiento y rectopexia."),
  banda=B("Prolapso completo frente a mucoso (dibujo clásico)", P("prolapso.jpg", 330, 212, [
            ("texto", 0.12, 0.08, "completo"), ("texto", 0.73, 0.08, "mucoso")],
          credito="Autor desconocido" + CC + "dominio público"),
          [("A: prolapso completo", "Sale todo el espesor del recto: pliegues en anillos concéntricos."),
           ("B: prolapso mucoso", "Sale solo la mucosa: pliegues radiales, como las hemorroides."),
           ("Cómo verlo", "Pedir que puje sentada (en el inodoro) durante el examen."),
           ("Tamaño", "El completo suele medir más de 5 cm.")],
          pie="Dibujo didáctico, no del paciente.", ans=0))

# OFT-012 · Rinitis alérgica · ÁRBOL
S("arbol", "OFT-012", "Rinorrea acuosa, estornudos en salva, mucosa pálida y cornetes edematosos con IgE nasal alta: rinitis alérgica",
  "Otorrinolaringología · rinitis", esp="OTORRINOLARINGOLOGÍA",
  tema=("Rinitis alérgica", ["Inflamación mediada por IgE: estornudos en salva, rinorrea acuosa, prurito, obstrucción.",
                             "Mucosa pálida y edematosa con secreción clara."]),
  caso=("Mujer de 20 años", ["Secreción nasal acuosa, estornudos en salva y obstrucción.",
                             "Mucosa pálida, cornetes engrosados y edematosos; IgE en secreción nasal alta."]),
  perlas=["Corticoide intranasal es el tratamiento más eficaz; antihistamínico de 2.ª generación si es leve.",
          "Rinitis eosinofílica no alérgica (NARES): eosinófilos sin IgE ni pruebas positivas.",
          "Inmunoterapia con alérgenos si no se controla o para prevenir asma."],
  fuente="ARIA, guía de rinitis alérgica (2024); Cummings Otolaryngology 7.ª ed. (2021).",
  op=("¿Diagnóstico?", ["No: secreción purulenta, dolor facial", "No: fiebre, malestar general", "Sí: IgE alta + mucosa pálida",
                        "No: sin IgE elevada", "No: sin IgE, gatillo físico"]),
  arbol=Q("Rinitis crónica: ¿IgE alta o pruebas cutáneas positivas?", [
      L("Sí: IgE nasal alta (este caso)", "RINITIS ALÉRGICA", ["Corticoide intranasal"], path=True),
      Q("No", [L("Eosinófilos en moco", "Rinitis eosinofílica (NARES)", ["Corticoide nasal"]),
               L("Sin eosinófilos", "Rinitis vasomotora", ["Ipratropio nasal"])], edge="No")], path=True))

# OFT-013 · Epistaxis traumática · ÁRBOL
S("arbol", "OFT-013", "Sangrado nasal por traumatismo: taponamiento nasal anterior como acción inmediata",
  "Otorrinolaringología · epistaxis", esp="OTORRINOLARINGOLOGÍA",
  tema=("Epistaxis traumática", ["Casi siempre anterior (área de Kiesselbach).",
                                 "Tras un golpe, buscar fractura nasal y hematoma del tabique."]),
  caso=("Pregunta de concepto", ["Paciente con sangrado nasal tras un traumatismo.", "¿Acción inmediata?"]),
  perlas=["Compresión de las alas nasales 10-15 min con la cabeza hacia adelante; si sigue: taponamiento anterior.",
          "Hematoma del tabique (masa roja y blanda): drenar el mismo día para evitar la nariz en silla de montar.",
          "No dar anticoagulantes; la ligadura arterial es para sangrados posteriores que no ceden."],
  fuente="AAO-HNS, Clinical Practice Guideline: Nosebleed (Epistaxis) (2020).",
  op=("¿Acción inmediata?", ["Solo si sangra por detrás", "Sí: controla el sangrado anterior", "Si se ve el punto y no cede",
                             "No: aumenta el sangrado", "Para sangrado posterior refractario"]),
  arbol=Q("Epistaxis tras un golpe: ¿cede con compresión?", [
      L("No (este caso)", "TAPONAMIENTO NASAL ANTERIOR", ["Gasa o material reabsorbible", "Revisar el tabique"], path=True),
      L("Sangra por detrás", "Taponamiento posterior", ["Especialista"])], path=True))

# NRL-015 · Tumor cerebral con realce en anillo · ÁRBOL + OMS + RM real
S("arbol", "NRL-015", "Cefalea, convulsiones, hemiplejia, cambios de personalidad y papiledema de 6 meses: tumor con realce en anillo, edema y efecto de masa",
  "Tumores del sistema nervioso · glioma de alto grado",
  ("Tumor cerebral maligno", ["Glioblastoma o metástasis: centro necrótico con anillo que capta contraste, edema alrededor.",
                              "Síntomas progresivos: cefalea, convulsiones, déficit focal, cambios de conducta, papiledema."]),
  ("Mujer de 30 años", ["6 meses de cefalea, convulsiones, debilidad izquierda y cambios de personalidad.", "Hemiplejia izquierda; Glasgow 15; papiledema."]),
  ["TC o RM con contraste: lesión en anillo con edema y efecto de masa.",
   "Diagnóstico de anillo: tumor, absceso, toxoplasma (VIH), neurocisticercosis, linfoma, desmielinización.",
   "Dexametasona para el edema, anticonvulsivante, biopsia o resección; luego radioterapia + temozolomida."],
  OMS + ", clasificación de tumores del SNC (CNS5, 2021); EANO, gliomas difusos del adulto (2021).",
  op=("¿Hallazgo?", ["Sí: tumor de alto grado", "Más propio de quiste o cisticerco", "No: atrofia, no masa", "No: atrofia sin masa",
                     "No: calcificación sin masa"]),
  arbol=Q("Déficit focal progresivo con papiledema: TC/RM con contraste", [
      L("Anillo + edema + efecto de masa (este caso)", "TUMOR DE ALTO GRADO", ["Dexametasona", "Biopsia o resección"], path=True),
      L("Quiste con punto (escólex)", "Neurocisticercosis", ["Albendazol + corticoide"])], path=True),
  escala=dict(nombre="Grados de los tumores del SNC (OMS 2021)", orden=True, que="Del 1 (benigno) al 4 (más agresivo).",
              grados=[("Grado 1", "Benigno", ["Astrocitoma pilocítico"]), ("Grado 2", "Bajo grado", ["Crecimiento lento"]),
                      ("Grado 3", "Anaplásico", ["Mitosis"]), ("Grado 4", "Alto grado", ["Necrosis o proliferación vascular", "Glioblastoma"])],
              caso=3, porque=[("Anillo = necrosis central", True), ("Edema y efecto de masa", True)],
              conducta="Dexametasona, anticonvulsivante y resección o biopsia."),
  banda=B("RM real de glioblastoma con realce en anillo", P("glioblastoma.jpg", 300, 309, [
            ("circulo", 0.75, 0.52, 0.15, "anillo que capta\ny centro necrótico", 0.32, 0.92)],
          credito="AFIP" + CC + "dominio público"),
          [("Anillo grueso e irregular", "El tumor vivo capta el contraste en la periferia."),
           ("Centro oscuro", "Necrosis: señal de alto grado."),
           ("Edema alrededor", "Zona más oscura que empuja las estructuras vecinas."),
           ("Efecto de masa", "Comprime el ventrículo y desplaza la línea media.")],
          pie="RM de otro paciente.", ans=0))

# NRL-016 · Hematoma epidural · FASES + TC real
S("fases", "NRL-016", "Caída con pérdida de conciencia, intervalo lúcido, midriasis derecha y hemiparesia izquierda: hematoma epidural",
  "Traumatismo craneoencefálico · hematoma epidural",
  ("Hematoma epidural", ["Sangrado arterial (arteria meníngea media) entre el hueso y la duramadre, por fractura temporal.",
                         "Intervalo lúcido y luego deterioro rápido: midriasis del mismo lado y hemiparesia contraria."]),
  ("Albañil de 22 años", ["Caída de escalera con pérdida inmediata de la conciencia.",
                          "Alterna lucidez con depresión del sensorio; midriasis derecha, hemiparesia izquierda."]),
  ["TC sin contraste: lente biconvexa que no cruza las suturas.",
   "Cirugía urgente (craneotomía) si > 30 mL, desviación de línea media > 5 mm o deterioro.",
   "Buen pronóstico si se opera antes de la herniación."],
  "Brain Trauma Foundation, manejo quirúrgico del TEC; " + ATLS + ".",
  op=("¿Diagnóstico?", ["No: sin trauma, hemorragia espontánea", "No: venoso, curso más lento", "No: sin intervalo lúcido típico",
                        "Sí: intervalo lúcido + midriasis", "No: sin intervalo lúcido"]),
  d=dict(rotulo="Curso típico del hematoma epidural", ans=2,
         fases=[("Golpe", "Pérdida de conciencia", "CONMOCIÓN", ["Breve"]),
                ("Intervalo lúcido", "Minutos a horas", "PARECE ESTAR BIEN", ["El hematoma crece"]),
                ("Deterioro", "Rápido", "HERNIACIÓN", ["Midriasis derecha, hemiparesia izquierda", "Este caso: operar ya"])]),
  banda=B("TC típica de hematoma epidural", P("epidural_derecho.jpg", 290, 326, [
            ("texto", 0.10, 0.05, "DER"), ("texto", 0.90, 0.05, "IZQ"),
            ("flecha", 0.19, 0.50, 0.58, 0.88, "hematoma en lente"),
            ("flecha", 0.47, 0.30, 0.74, 0.20, "línea media\ndesplazada")],
          credito="Hellerhoff" + CC + "CC BY-SA 4.0"),
          [("Lente biconvexa", "Mancha blanca pegada al hueso: sangre fresca entre hueso y duramadre."),
           ("No cruza las suturas", "La duramadre está pegada en las suturas y limita el hematoma."),
           ("Del mismo lado de la midriasis", "Comprime el III par derecho; la hemiparesia es izquierda."),
           ("Línea media desplazada", "Si es > 5 mm, cirugía urgente.")],
          pie="TC de otro paciente; en la TC, la derecha del paciente se ve a la izquierda.", ans=0))

# PED-065 · Hernia diafragmática: clínica · ÁRBOL + pistas
S("arbol", "PED-065", "Recién nacido con dificultad respiratoria, murmullo bajo a la izquierda, ruidos cardiacos a la derecha y abdomen escafoide: hernia diafragmática",
  "Cirugía neonatal · hernia diafragmática congénita",
  ("Hernia diafragmática congénita (Bochdalek)", ["Defecto posterolateral izquierdo: el intestino sube al tórax y empuja el corazón.",
                                                  "El pulmón queda pequeño (hipoplasia) e hipertenso."]),
  ("Recién nacido", ["Quejido, retracciones, disnea y cianosis.", "Murmullo bajo a la izquierda, ruidos cardiacos a la derecha, abdomen escafoide."]),
  ["Rx de tórax confirma: asas con aire en el tórax izquierdo.",
   "Intubar de inmediato (nunca bolsa y mascarilla) y sonda orogástrica para descomprimir.",
   "Cirugía diferida tras estabilizar; manejo de la hipertensión pulmonar."],
  "CDH EURO Consortium, consenso (2015, act. 2024); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Sí: abdomen excavado + corazón desplazado", "No: no vacía el abdomen", "No: masa, no abdomen excavado",
                        "No: hipersonoridad, abdomen normal", "No: no desplaza el corazón ni vacía el abdomen"]),
  arbol=Q("Dificultad respiratoria al nacer: ¿abdomen escafoide y corazón desplazado?", [
      L("Sí (este caso)", "HERNIA DIAFRAGMÁTICA", ["Intubar + sonda orogástrica", "Rx de tórax"], path=True),
      L("No", "Otras causas", ["Membrana hialina, neumonía, neumotórax"])], path=True),
  triada=TR([("Abdomen escafoide", "Sí", True), ("Ruidos cardiacos a la derecha", "Sí", True), ("Murmullo bajo a la izquierda", "Sí", True),
             ("Dificultad respiratoria y cianosis", "Sí", True)],
            [("Pistas de la hernia de Bochdalek", 0, 3)],
            "Las cuatro pistas presentes: intubar y confirmar con Rx.", rotulo="Pistas clínicas"))

# SP-039 · Autonomía: anticoncepción de emergencia · TARJETAS
S("tarjetas", "SP-039", "Víctima de violación a la que el médico, por motivos religiosos, niega la anticoncepción de emergencia: se vulnera su autonomía",
  "Bioética · autonomía y objeción de conciencia",
  ("Autonomía", ["La paciente capaz decide sobre su cuerpo con información.",
                 "La objeción de conciencia del médico no permite negar la atención: debe derivar sin demora."]),
  ("Mujer víctima de violación", ["Acude de inmediato pidiendo protección frente a un embarazo.", "El médico se niega por motivos religiosos."]),
  ["La anticoncepción oral de emergencia (levonorgestrel) es parte del kit de atención de violencia sexual del MINSA.",
   "Funciona mejor en las primeras 72 horas; no es abortiva.",
   "Además: profilaxis de ITS y VIH, apoyo psicológico y denuncia."],
  MINSA + ", kit para la atención de casos de violencia sexual (RM 227-2019); " + OMS + ", anticoncepción de emergencia (2021).",
  op=("¿Principio negado?", ["Afecta, pero lo central es su decisión", "Afecta, pero lo central es su decisión", "Afecta, pero lo central es su decisión",
                             "Sí: decide sobre su cuerpo", "No: no se divulgó nada"]),
  d=dict(rotulo="¿Qué principio se vulnera?", ans=0,
         cards=[dict(titulo="Autonomía", datos=[("Quién decide", "La paciente", True), ("Aquí", "Se le negó", True), ("Correcto", "Atender o derivar", True)],
                     pie="Este caso."),
                dict(titulo="Justicia", datos=[("Idea", "Acceso equitativo", False), ("Aquí", "También afectada", False), ("Mira a", "La sociedad", False)],
                     pie="Secundario."),
                dict(titulo="Beneficencia", datos=[("Idea", "Hacer el bien", False), ("Aquí", "No se protegió", False), ("Mira a", "El acto médico", False)],
                     pie="Secundario."),
                dict(titulo="Confidencialidad", datos=[("Idea", "Guardar secreto", False), ("Aquí", "No aplica", False), ("Falta", "Divulgar", False)],
                     pie="No aplica.")]))

# GIN-048 · DPP con óbito · TARJETAS + Page + pieza real
S("tarjetas", "GIN-048", "34 semanas con dolor intenso, útero en contracción sostenida, sangrado oscuro escaso y sin latidos fetales: desprendimiento prematuro de placenta",
  "Hemorragias de la segunda mitad del embarazo · DPP",
  ("Desprendimiento prematuro de placenta (DPP)", ["La placenta se despega antes del parto: sangre detrás de ella, útero duro y doloroso.",
                                                   "Con feto muerto, riesgo alto de coagulopatía."]),
  ("Gestante de 34 semanas", ["Trastorno del sensorio, dolor abdominal intenso; soporosa, PA 120/70, FC 100.",
                              "Útero en contracción sostenida, sin latidos fetales; sangrado oscuro escaso."]),
  ["Feto muerto: preferir parto vaginal (amniotomía + oxitocina) si la madre está estable.",
   "Pedir coagulación y fibrinógeno; reponer sangre y plasma; cesárea si la madre se descompensa.",
   "Sensorio alterado: buscar preeclampsia o eclampsia y choque oculto."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ".",
  op=("¿Diagnóstico?", ["Sí: útero tenso + feto muerto + sangre oscura", "No: indoloro, útero blando", "No: al romper membranas",
                        "No: sin cicatriz; el útero no se ablanda", "No: indoloro, sangrado escaso"]),
  d=dict(rotulo="Sangrado en el tercer trimestre", ans=0,
         cards=[dict(titulo="DPP", datos=[("Dolor", "Intenso", True), ("Útero", "Contracción sostenida", True), ("Feto", "Muerto", True)],
                     pie="Este caso."),
                dict(titulo="Placenta previa", datos=[("Dolor", "No", False), ("Útero", "Blando", False), ("Sangre", "Roja", False)],
                     pie="No tacto."),
                dict(titulo="Rotura uterina", datos=[("Antecedente", "Cicatriz", False), ("Dolor", "Súbito, cede", False), ("Feto", "Se palpa fuera", False)],
                     pie="Laparotomía."),
                dict(titulo="Vasa previa", datos=[("Cuándo", "Al romper bolsa", False), ("Sangre", "Fetal", False), ("Útero", "Blando", False)],
                     pie="Cesárea urgente.")]),
  escala=PAGE(3, [("Feto muerto", True), ("Madre con sensorio alterado: medir coagulación (IIIa o IIIb)", True)],
              "Corregir la coagulación, reponer sangre y terminar el embarazo (vía vaginal si está estable)."),
  banda=B("Pieza real de un DPP", P("dpp_pieza.jpg", 330, 208, [
            ("flecha", 0.66, 0.22, 0.88, 0.10, "placenta"),
            ("flecha", 0.50, 0.57, 0.22, 0.12, "coágulo\nretroplacentario"),
            ("flecha", 0.36, 0.80, 0.74, 0.90, "pared del útero")], credito="Mikael Häggström" + CC + "CC0", fondo="#1d4ed8"),
          [("Coágulo detrás de la placenta", "La sangre queda atrapada: el sangrado externo es escaso y oscuro."),
           ("Útero «de madera»", "La sangre infiltra el miometrio y lo contrae sin relajar."),
           ("Riesgo de coagulopatía", "Consume fibrinógeno y plaquetas: pedir coagulación."),
           ("Útero de Couvelaire", "Útero violáceo por la sangre infiltrada; puede no contraer tras el parto.")],
          pie="Pieza quirúrgica de otra paciente.", ans=0))

# GIN-049 · Endometritis puerperal · ÁRBOL
S("arbol", "GIN-049", "Puérpera de un parto complicado con fiebre y loquios fétidos a las 36 horas y endometrio de 7 mm: endometritis puerperal",
  "Infecciones del puerperio · endometritis",
  ("Endometritis puerperal", ["Infección polimicrobiana del endometrio tras el parto; más frecuente tras parto complicado o cesárea.",
                              "Fiebre, útero doloroso y loquios fétidos en los primeros días."]),
  ("Puérpera de 36 horas", ["Parto complicado; malestar general, fiebre y loquios de mal olor.", "Funciones vitales estables; endometrio de 7 mm."]),
  ["Clindamicina + gentamicina EV hasta 24-48 h sin fiebre.",
   "Endometrio delgado (7 mm) sin masa: no sugiere restos; restos dan endometrio grueso con masa y vascularización.",
   "Si no mejora en 48-72 h: absceso, restos o tromboflebitis pélvica séptica."],
  ACOG + "; " + WILLIAMS + "; " + OMS + ", infecciones maternas en el periparto (2015).",
  op=("¿Diagnóstico?", ["No: endometrio de 7 mm, sin masa", "Sí: fiebre + loquios fétidos", "No: ya no hay embarazo",
                        "No: herida perineal no descrita", "No: mama no descrita y aparece más tarde"]),
  arbol=Q("Fiebre puerperal con loquios fétidos: ¿hay restos en la ecografía?", [
      L("No: endometrio de 7 mm (este caso)", "ENDOMETRITIS PUERPERAL", ["Clindamicina + gentamicina EV"], path=True),
      L("Sí: masa en la cavidad", "Restos placentarios", ["Aspiración + antibiótico"])], path=True))

# GIN-050 · Corioamnionitis · TARJETAS + Triple I
S("tarjetas", "GIN-050", "34 semanas con fiebre de 39 °C, taquicardia fetal de 165 y nitrazina y helecho positivos: corioamnionitis",
  "Infecciones intraamnióticas · corioamnionitis",
  ("Corioamnionitis (infección intraamniótica, «Triple I»)", ["Infección de las membranas y el líquido, casi siempre por rotura de membranas.",
                                                              "Fiebre materna con taquicardia fetal, leucocitosis o secreción purulenta."]),
  ("Gestante de 34 semanas", ["Sensación de alza térmica; 39 °C, FC 100.", "FCF 165; nitrazina y helecho positivos (rotura de membranas)."]),
  ["Ampicilina + gentamicina EV y terminar el embarazo (la vía según indicación obstétrica).",
   "No es indicación de cesárea por sí sola.",
   "Avisar al neonatólogo: el recién nacido tiene riesgo de sepsis."],
  ACOG + " Committee Opinion n.º 712 (2017, reafirmado 2024); " + WILLIAMS + ".",
  op=("¿Impresión diagnóstica?", ["Sí: RPM + fiebre + taquicardia fetal", "No: no ocurre en el embarazo avanzado", "No: sin dolor lumbar",
                                  "No: es puerperal", "No: sin disuria y con fiebre alta"]),
  d=dict(rotulo="Fiebre en la gestante: ¿de dónde viene?", ans=0,
         cards=[dict(titulo="Corioamnionitis", datos=[("Membranas", "Rotas", True), ("FCF", "Taquicardia", True), ("Fiebre", "Alta", True)],
                     pie="Este caso."),
                dict(titulo="Pielonefritis", datos=[("Dolor", "Lumbar", False), ("Puñopercusión", "Positiva", False), ("Orina", "Alterada", False)],
                     pie="Ceftriaxona."),
                dict(titulo="Endometritis", datos=[("Cuándo", "Puerperio", False), ("Loquios", "Fétidos", False), ("Útero", "Doloroso", False)],
                     pie="Tras el parto."),
                dict(titulo="Cistitis", datos=[("Síntoma", "Disuria", False), ("Fiebre", "No", False), ("Lumbar", "No", False)],
                     pie="Nitrofurantoína.")]),
  triada=TR([("Fiebre materna ≥ 39 °C", "39 °C", True), ("Taquicardia fetal > 160", "165", True), ("Leucocitosis materna", "No se informa", False),
             ("Secreción cervical purulenta", "No se informa", False)],
            [("Criterios de Triple I (ACOG)", 0, 3)],
            "Fiebre ≥ 39 °C + taquicardia fetal: infección intraamniótica sospechada; tratar ya.", rotulo="Criterios con nombre propio"))

# GIN-051 · Pielonefritis en el embarazo · ÁRBOL + clasificación ITU
S("arbol", "GIN-051", "Gestante de 36 semanas con fiebre de 39 °C y puñopercusión lumbar derecha muy positiva: pielonefritis, ceftriaxona",
  "Infección urinaria en el embarazo · pielonefritis",
  ("Pielonefritis en el embarazo", ["El útero y la progesterona dilatan los uréteres: la infección sube más fácil, sobre todo a la derecha.",
                                    "Riesgo de sepsis, SDRA y parto pretérmino: se hospitaliza."]),
  ("Gestante de 36 semanas", ["Alza térmica y malestar general.", "39 °C; puñopercusión lumbar derecha +++."]),
  ["Hospitalizar, urocultivo y ceftriaxona EV hasta 48 h sin fiebre; completar 10-14 días por boca.",
   "Nitrofurantoína no llega al riñón; cotrimoxazol al final del embarazo se evita; tetraciclinas están contraindicadas.",
   "Luego profilaxis o urocultivos de control hasta el parto."],
  ACOG + "; EAU, infecciones urológicas (2024); " + WILLIAMS + ".",
  op=("¿Antibiótico?", ["No: se evita al final del embarazo", "No: no llega al riñón", "Sí: EV, cubre gramnegativos",
                        "No: contraindicada en el embarazo", "No: mucha resistencia de E. coli"]),
  arbol=Q("Gestante con fiebre y puñopercusión positiva", [
      L("Pielonefritis (este caso)", "CEFTRIAXONA EV", ["Hospitalizar", "Urocultivo"], path=True),
      L("Solo disuria, sin fiebre", "Cistitis", ["Nitrofurantoína o cefalexina"])], path=True),
  escala=ITU(2, [("Fiebre de 39 °C", True), ("Puñopercusión lumbar +++", True)],
             "Hospitalizar, urocultivo y ceftriaxona EV."))

# GIN-052 · Inducción con Bishop favorable · ÁRBOL + Bishop
S("arbol", "GIN-052", "42 semanas con bienestar fetal normal y cuello blando, anterior, borrado 80 %, 1 cm y estación 0: inducción con oxitocina",
  "Embarazo prolongado · inducción del parto",
  ("Inducción del parto", ["Desde las 41 semanas se ofrece inducir; a las 42 está indicado (más muerte fetal).",
                           "Si el cuello está maduro (Bishop alto), se induce directo con oxitocina."]),
  ("Gestante de 42 semanas", ["Perfil biofísico y prueba no estresante normales.",
                              "Cuello blando, anterior, borrado 80 %, 1 cm de dilatación, estación 0."]),
  ["Bishop ≥ 8: oxitocina (± amniotomía); Bishop ≤ 6: madurar antes.",
   "Esperar más allá de las 42 semanas no es aceptable.",
   "Cesárea solo con otra indicación obstétrica."],
  ACOG + ", inducción a las 41 semanas (2024); " + OMS + ", inducción del trabajo de parto (2022); " + WILLIAMS + ".",
  op=("¿Manejo?", ["Sí: Bishop 10, cuello favorable", "No: el cuello ya está maduro", "No: ya están bien; hay que terminar",
                   "No: a las 42 semanas no se espera", "No: sin indicación"]),
  arbol=Q("42 semanas con feto bien: ¿Bishop?", [
      L("≥ 8: 10 puntos (este caso)", "INDUCCIÓN CON OXITOCINA", ["± amniotomía"], path=True),
      L("≤ 6", "Maduración cervical", ["Misoprostol o sonda Foley"])], path=True),
  escala=dict(nombre="Puntaje de Bishop", modo="puntaje", que="Mide qué tan listo está el cuello (0 a 13 puntos).",
              items=[("D", "Dilatación (0 a 3)", "1 cm", 1), ("B", "Borramiento (0 a 3)", "80 %", 3), ("E", "Estación (0 a 3)", "0", 2),
                     ("C", "Consistencia (0 a 2)", "Blando", 2), ("P", "Posición (0 a 2)", "Anterior", 2)],
              total_txt="Total: 10 puntos",
              rangos=[("≤ 6", "Desfavorable", "Maduración primero"), ("7", "Intermedio", "Individualizar"), ("≥ 8", "Favorable", "Oxitocina")],
              caso_rango=2, porque=[("Cuello blando, anterior y casi borrado", True)],
              conducta="Oxitocina con monitoreo fetal continuo."))

# GIN-053 · Distocia de hombros: McRoberts · ÁRBOL + maniobras
S("arbol", "GIN-053", "Distocia de hombros en un feto grande: hiperflexión de los muslos de la madre (maniobra de McRoberts)",
  "Distocias del parto · distocia de hombros",
  ("Distocia de hombros", ["Sale la cabeza pero el hombro anterior se traba en el pubis («signo de la tortuga»).",
                           "Factores: macrosomía, diabetes, obesidad, parto prolongado."]),
  ("Gestante de 39 semanas", ["Sin control prenatal; altura uterina 37 cm (feto grande).", "Expulsivo con dilatación completa; distocia de hombros."]),
  ["Pedir ayuda y empezar con McRoberts (hiperflexionar los muslos) + presión suprapúbica: resuelve la mayoría.",
   "Si no: maniobras internas (Rubin II, Woods), extraer el brazo posterior, posición en cuatro patas (Gaskin).",
   "Nunca tracción fuerte de la cabeza ni presión en el fondo uterino (lesión del plexo braquial, rotura uterina)."],
  "RCOG Green-top n.º 42, distocia de hombros (2012, act. 2017); " + ACOG + " Practice Bulletin n.º 178 (2017).",
  op=("¿Maniobra inmediata?", ["Sí: McRoberts, la primera", "Va después (maniobra interna)", "No: lesiona el plexo braquial",
                               "No: empeora el atasco", "No sola: no libera el hombro"]),
  arbol=Q("Distocia de hombros: pedir ayuda", [
      L("Primero (este caso)", "MCROBERTS + PRESIÓN SUPRAPÚBICA", ["Hiperflexionar los muslos"], path=True),
      L("Si no sale", "Maniobras internas", ["Rubin II, Woods, brazo posterior"])], path=True),
  triada=TR([("McRoberts", "Hiperflexión de muslos", None), ("Presión suprapúbica (Rubin I)", "Sobre el hombro anterior", None),
             ("Rubin II y Woods", "Rotar los hombros", None), ("Brazo posterior", "Extraerlo", None), ("Gaskin", "Cuatro patas", None)],
            [("Maniobras con nombre propio (en orden)", 0, 4)],
            "Se avanza de una a otra cada 30-60 segundos.", rotulo="Maniobras con nombre propio"))

# GIN-054 · Sangrado posmenopáusico · ÁRBOL + umbral endometrial
S("arbol", "GIN-054", "Posmenopáusica nulípara, hipertensa y diabética con ginecorragia y endometrio de 12 mm: biopsia de endometrio",
  "Ginecología oncológica · sangrado posmenopáusico",
  ("Sangrado posmenopáusico", ["Todo sangrado tras la menopausia se estudia: 10 % es cáncer de endometrio.",
                               "Factores: obesidad, nuliparidad, diabetes, HTA, estrógenos sin progestágeno."]),
  ("Mujer de 52 años", ["Nulípara, menopausia hace 10 años; HTA y diabetes.", "Ginecorragia de 48 h; ecografía: endometrio de 12 mm."]),
  ["Endometrio > 4 mm con sangrado: biopsia (Pipelle o histeroscopia).",
   "≤ 4 mm: riesgo bajo; biopsiar igual si el sangrado persiste.",
   "Cáncer confirmado: estadificación FIGO (2023) y cirugía (histerectomía + salpingooforectomía)."],
  ACOG + " Committee Opinion n.º 734 (2018, reafirmado); FIGO, estadificación del cáncer de endometrio (2023).",
  op=("¿Procedimiento?", ["Sí: da el diagnóstico", "No: sin diagnóstico aún", "Complementa, no da histología",
                          "No: sin diagnóstico aún", "No: puede estimular el endometrio"]),
  arbol=Q("Sangrado posmenopáusico: ¿grosor endometrial?", [
      L("> 4 mm: 12 mm (este caso)", "BIOPSIA DE ENDOMETRIO", ["Pipelle o histeroscopia"], path=True),
      L("≤ 4 mm", "Riesgo bajo", ["Biopsia si persiste"])], path=True),
  escala=dict(nombre="Grosor endometrial en la posmenopausia", orden=True, que="Ecografía transvaginal con sangrado.",
              grados=[("≤ 4 mm", "Riesgo bajo", ["Cáncer muy improbable"]), ("> 4 mm", "Estudiar", ["Biopsia de endometrio"])],
              caso=1, porque=[("Endometrio de 12 mm", True), ("Nulípara, diabética, hipertensa: riesgo alto", True)],
              conducta="Biopsia de endometrio."))
