"""Bloque ENAM 2026 · Nefrología y Urología."""
from c26 import S, D, B, ILU, Q, L, HARRISON, MINSA, ATLS
import ilu7 as I

O = I.ORANGE
ESP = "NEFROLOGÍA ENAM"
KDIGO = "KDIGO"
EAU = "EAU, guías de urología (2024)"

# NEF-094 · Criptorquidia operada y riesgo de cáncer · RADIAL + franja
S("radial", "NEF-094", "criptorquidia-orquidopexia-5-anos-riesgo-cancer-testicular-autoexamen",
  "Criptorquidia operada en la infancia: el riesgo de cáncer testicular sigue siendo mayor",
  "Urología · cáncer testicular", ESP,
  ("Criptorquidia y cáncer testicular", ["Es el principal factor de riesgo de tumor germinal del testículo.",
                                         "La orquidopexia permite examinarlo y reduce algo el riesgo, pero no lo elimina."]),
  ("Varón de 22 años, control preventivo", ["Testículo izquierdo no descendido; orquidopexia a los 5 años.",
                                            "Sin síntomas ni antecedentes familiares."]),
  ["Explicar que su riesgo de cáncer testicular es mayor (varias veces el de la población).",
   "Enseñar el autoexamen testicular mensual y consultar ante cualquier masa.",
   "No se recomiendan ecografías ni marcadores periódicos en un varón sin síntomas."],
  EAU + "; AUA, criptorquidia (2014, reafirmada).",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Criptorquidia operada: ¿qué decirle?",
         items=[("Explicar que el riesgo aumenta", ["Y enseñar el autoexamen mensual"]),
                ("La orquidopexia elimina el riesgo", ["Falso: solo lo reduce algo"]),
                ("Ecografía cada 6 meses", ["Sin beneficio en un varón asintomático"]),
                ("Marcadores cada 6 meses", ["No sirven para tamizar"])],
         ruta=["Criptorquidia al nacer", "Orquidopexia a los 5 años", "Riesgo sigue mayor", "Autoexamen mensual"]),
  banda=B("Testículos del paciente (esquema)", D(lambda s, x, y: I.testiculo(s, x + 10, y, "criptorquidia"), 270, 232),
          ["El testículo izquierdo bajó con cirugía a los 5 años.", "Ese testículo (y algo el otro) tiene más riesgo de tumor.",
           "Autoexamen: buscar una masa dura e indolora."], ans=0),
  tabla=("Opciones de la pregunta", [("Eco cada 6 meses", False), ("La cirugía elimina el riesgo", False), ("Marcadores cada 6 meses", False),
                                     ("Explicar que el riesgo aumenta", True)],
         [("Problema", ["Sin beneficio", "Falso", "No tamizan", "Ninguno"])]))

# NEF-095 · Trauma renal: TC con contraste · ÁRBOL CON IMAGEN
S("arbol_imagen", "NEF-095", "atropello-dolor-flanco-hematuria-macroscopica-estable-tc-contraste",
  "Trauma lumbar con hematuria macroscópica en paciente estable: TC con contraste",
  "Trauma renal · estudio por imágenes", ESP,
  ("Trauma renal", ["Sospechar con golpe en el flanco, equimosis lumbar y hematuria.",
                    "En el paciente estable, la TC con contraste (con fase tardía) clasifica la lesión."]),
  ("Varón de 35 años atropellado hace 2 h", ["Dolor en el flanco izquierdo, equimosis lumbar, orina rojiza.",
                                             "PA 105/70, FC 92; abdomen blando sin irritación peritoneal."]),
  ["Trauma cerrado + hematuria macroscópica + estable = TC con contraste EV (fase excretora tardía).",
   "Gradúa la lesión (AAST I-V) y muestra fuga de orina o daño del pedículo.",
   "FAST no ve bien el riñón; la cistografía es para la vejiga; la Rx simple no aporta."],
  "AAST; " + ATLS + "; " + EAU + ".",
  d=dict(rotulo="¿Qué estudio pedir?", tag="ESTE CASO",
         pregunta="Trauma con sospecha de lesión renal: ¿el paciente está estable?",
         ramas=[("No: inestable", "FAST y quirófano", ["Si hay líquido libre o no responde a fluidos.",
                                                       "Exploración quirúrgica."]),
                ("Sí: PA 105/70, hematuria", "TC con contraste EV",
                 ["Con fase tardía (excretora) para ver fuga de orina.", "Clasifica la lesión de I a V."])],
         ilu=lambda s, x, y: I.rinon_vias(s, x, y, "trauma", lado="izq", sc=0.9), IW=270, IH=256,
         ilu_pie="Riñón izquierdo lesionado (esquema): la TC muestra la laceración y el hematoma alrededor.",
         luego_titulo="Qué sigue",
         luego=[("Grados I-III", ["Casi siempre manejo conservador."], True),
                ("Grados IV-V", ["Según estabilidad: angioembolización o cirugía."], False),
                ("Control", ["Hematocrito y orina seriados; reposo."], False)]),
  tabla=("Opciones de la pregunta", [("TC con contraste", True), ("Rx simple", False), ("Cistografía retrógrada", False), ("FAST", False)],
         [("Para qué sirve", ["Riñón: este caso", "No ve el riñón", "Vejiga", "Líquido libre en el inestable"])]))

# NEF-096 · Litiasis ureteral · EMBUDO + franja
_colico = (I.P("M80 150 C70 190 90 230 106 262 C112 280 114 300 112 330", "none", O, 3, 'stroke-dasharray="7 4"')
           + I.flecha(112, 316, 112, 336, O, 3))
S("embudo", "NEF-096", "dolor-colico-flanco-irradiado-muslo-hematuria-litiasis-ureteral",
  "Dolor cólico del flanco que baja al muslo con hematuria microscópica: litiasis ureteral",
  "Urología · cólico renal", ESP,
  ("Cólico renoureteral", ["Un cálculo que baja por el uréter: dolor súbito, cólico, del flanco a la ingle o al muslo.",
                           "Suele haber hematuria microscópica y puñopercusión positiva."]),
  ("Varón de 50 años", ["Dolor súbito 8/10 en el flanco derecho que irradia al muslo; náuseas, sin fiebre.",
                        "Puñopercusión derecha (+); hematuria microscópica; Thevenon (–); pH 6."]),
  ["Dolor cólico de flanco irradiado + hematuria microscópica sin fiebre = litiasis ureteral.",
   "Confirmar con ecografía o TC sin contraste; analgesia con AINE.",
   "Fiebre o leucocituria cambiarían el cuadro (riñón obstruido e infectado)."],
  EAU + "; " + HARRISON + ".",
  d=dict(rotulo="Del dolor a la causa", inicio="Dolor cólico del flanco derecho con hematuria microscópica",
         candidatos=["Pielonefritis", "Poliquistosis renal", "Tumor vesical", "Litiasis ureteral"],
         pasos=[("¿Fiebre y leucocituria?", ["Pielonefritis"]),
                ("¿Riñones grandes con quistes, HTA, familia?", ["Poliquistosis renal"]),
                ("¿Hematuria macroscópica sin dolor?", ["Tumor vesical"])],
         final=("Litiasis ureteral derecha", ["Cólico que baja del flanco al muslo"]),
         nota="El dolor sigue el trayecto del uréter: el cálculo va bajando."),
  banda=B("Trayecto del dolor", D(lambda s, x, y: I.cuerpo(s, x + 40, y, {"abdomen": "#fff7ed"}, extra=_colico,
                                                           marcas=[(1, 80, 150), (2, 112, 300)], sc=0.7), 250, 312),
          ["Empieza en el flanco derecho (1).", "Baja por el trayecto del uréter hacia la ingle y la cara interna del muslo (2).",
           "Hematuria microscópica: el cálculo irrita la mucosa."], ans=0),
  tabla=("Opciones de la pregunta", [("Pielonefritis", False), ("Poliquistosis", False), ("Tumor vesical", False), ("Litiasis ureteral", True)],
         [("¿Encaja?", ["No: sin fiebre", "No: sin masas ni HTA", "No: es indoloro", "Sí"])]))

# NEF-097 · Tamizaje de cáncer de próstata · CICLO
S("ciclo", "NEF-097", "varon-55-anos-padre-cancer-prostata-decision-compartida-psa",
  "Varón de 55 años que pide «todos los exámenes» de próstata: decisión compartida",
  "Urología · tamizaje de cáncer de próstata", ESP,
  ("Tamizaje de cáncer de próstata", ["El PSA puede detectar cánceres agresivos, pero también da falsos positivos y sobrediagnóstico.",
                                      "Entre 55 y 69 años se decide junto con el paciente."]),
  ("Varón de 55 años en el primer nivel", ["Sin síntomas; padre fallecido por cáncer de próstata.",
                                           "Pide «todos los exámenes posibles»."]),
  ["Explicar beneficios y riesgos del PSA (y del tacto rectal) y decidir junto con él.",
   "El antecedente familiar aumenta su riesgo: es buen candidato a considerar el tamizaje.",
   "No: PSA sin consejería, prohibirlo en el primer nivel ni resonancia de entrada."],
  "USPSTF (2018); AUA (2023); " + EAU + ".",
  d=dict(rotulo="Cómo se decide", tag="ESTE CASO",
         img_titulo="Próstata (esquema)",
         img=D(lambda s, x, y: I.rinon_vias(s, x - 6, y + 10, "prostata", sc=0.95), 280, 300),
         img_pie="El PSA sale de la próstata; también sube en la hiperplasia benigna.",
         centro="Decisión compartida", ans=0,
         pasos=[("Explicar beneficios", "detectar cáncer agresivo"), ("Explicar riesgos", "falsos positivos, biopsias"),
                ("Conocer sus valores", "qué prefiere él"), ("Decidir juntos", "PSA ± tacto rectal"),
                ("Seguimiento", "repetir según resultado")],
         claves_titulo="Por qué no las otras",
         claves=[("«Contraindicado en el primer nivel»", ["Falso: la consejería es del primer nivel."], False),
                 ("PSA anual sin consejería", ["Expone a sobrediagnóstico sin que él lo sepa."], False),
                 ("Resonancia de entrada", ["Solo tras un PSA alterado."], False)]),
  tabla=("Opciones de la pregunta", [("Explicar riesgos y beneficios", True), ("Contraindicado en el primer nivel", False),
                                     ("PSA anual sin consejería", False), ("Resonancia inmediata", False)],
         [("Problema", ["Ninguno", "Falso", "Sin decisión informada", "No es tamizaje"])]))

# NEF-098 · ERC por nefropatía diabética · MAPA DE SIGNOS
S("mapa_signos", "NEF-098", "diabetico-15-anos-creatinina-5-8-albuminuria-erc-retinopatia-diabetica",
  "Diabético de larga data con uremia y albuminuria alta: ERC por nefropatía diabética; buscar retinopatía",
  "Enfermedad renal crónica · nefropatía diabética", ESP,
  ("Nefropatía diabética", ["La causa más frecuente de enfermedad renal crónica.",
                            "Daño microvascular: casi siempre va junto con retinopatía diabética."]),
  ("Varón de 48 años con DM2 de 15 años", ["Semanas de fatiga, náuseas y prurito; pálido, piel seca, edema leve.",
                                           "Creatinina 5,8 (1,2 hace un año), urea 160, Hb 9, albúmina/creatinina 500 mg/g."]),
  ["DM2 mal controlada + albuminuria A3 + uremia + anemia = ERC avanzada por nefropatía diabética.",
   "Buscar retinopatía diabética en el fondo de ojo: comparten el daño de los pequeños vasos.",
   "Si no hubiera retinopatía, pensar en otra causa y considerar biopsia."],
  KDIGO + ", diabetes en ERC (2022); ADA (2025).",
  d=dict(rotulo="Los signos del paciente", PH=500, tag="ESTE CASO",
         ilu_titulo="El paciente del caso",
         ilu=lambda s, x, y: I.cuerpo(s, x + 39, y + 4, {"cara": "#fdf3ec", "pie_d": "#dbeafe", "pie_i": "#dbeafe"},
                                      marcas=[(1, 132, 30), (2, 40, 200), (3, 200, 200), (4, 98, 420), (5, 120, 200)], sc=0.9),
         ilu_pie="1 ojos (retina), 2 prurito, 3 piel pálida, 4 edema, 5 náuseas.",
         signos=[dict(tit="Buscar retinopatía diabética", lines=["Fondo de ojo: acompaña a la nefropatía."]),
                 dict(tit="Prurito y náuseas", lines=["Síntomas urémicos (urea 160)."]),
                 dict(tit="Palidez", lines=["Anemia de la ERC (Hb 9)."]),
                 dict(tit="Edema", lines=["Retención de sodio y agua."]),
                 dict(tit="Albuminuria 500 mg/g", lines=["Categoría A3: daño glomerular."]),
                 dict(tit="Causa: ERC por nefropatía diabética", on=True, lines=["Creatinina 1,2 → 5,8 en un año."])]),
  tabla=("Opciones de la pregunta", [("IRA prerrenal; retinopatía hipertensiva", False), ("Nefritis intersticial; catarata", False),
                                     ("NTA; glaucoma", False), ("ERC diabética; retinopatía diabética", True)],
         [("Problema", ["No está deshidratado; anemia y albuminuria", "Sin fármacos ni albuminuria así", "Sin causa aguda", "Ninguno"])]))

# NEF-099 · Nefritis lúpica en diabética: biopsia · CRITERIOS
S("criterios", "NEF-099", "diabetica-proteinuria-nefrotica-complemento-bajo-sin-retinopatia-biopsia-renal",
  "Diabética con proteinuria nefrótica, complemento bajo y sin retinopatía: biopsia renal",
  "Glomerulopatías · ¿nefropatía diabética o lupus?", ESP,
  ("No toda proteinuria del diabético es diabética", ["La nefropatía diabética tiene complemento normal y casi siempre retinopatía.",
                                                      "Si algo no encaja, la biopsia define el diagnóstico y el tratamiento."]),
  ("Mujer de 60 años con DM2 de 15 años", ["2 meses de edema; PA 150/90; alopecia y sinovitis.",
                                           "Sin retinopatía; proteinuria 5,4 g/24 h; C3 y C4 bajos."]),
  ["Complemento bajo + alopecia + sinovitis + sin retinopatía: sospechar nefritis lúpica.",
   "Biopsia renal: la clase de nefritis lúpica decide la inmunosupresión.",
   "No tratar a ciegas: ni solo IECA como si fuera diabética, ni pulsos sin diagnóstico."],
  KDIGO + ", glomerulopatías (2021) y nefritis lúpica (2024); EULAR (2023).",
  d=dict(rotulo="¿Es solo nefropatía diabética?", tag="ESTE CASO",
         lista_titulo="Datos que no encajan con la diabetes",
         items=[("C3 y C4 bajos", True, "La nefropatía diabética tiene complemento normal"),
                ("Sin retinopatía diabética", True, "Fondo de ojo normal"),
                ("Síntomas sistémicos", True, "Alopecia y sinovitis"),
                ("Proteinuria nefrótica de inicio rápido", True, "5,4 g/24 h en 2 meses"),
                ("Anticuerpos antinucleares y anti-DNA", None, "Pedirlos junto con la biopsia")],
         umbral="basta 1 dato discordante", veredicto="Biopsia renal: el resultado cambiará el tratamiento",
         img_titulo="Lo que puede mostrar la biopsia", img=D(lambda s, x, y: I.glomerulo(s, x - 15, y, "proliferativo", sc=0.9), 230, 210),
         img_pie="Glomérulo con proliferación (nefritis lúpica) en lugar de la esclerosis diabética.",
         claves_titulo="Por qué no las otras",
         claves=[("Solo oftalmología y esperar", ["Retrasa el diagnóstico de una nefritis activa."], False),
                 ("Tratar como diabética", ["Ignora el complemento bajo y el lupus."], False),
                 ("Pulsos y ciclofosfamida ya", ["Sin biopsia no se sabe la clase."], False)]),
  tabla=("Opciones de la pregunta", [("Oftalmología y repetir proteinuria", False), ("Biopsia renal", True),
                                     ("IECA/ARA II y estatina", False), ("Pulsos + ciclofosfamida ya", False)],
         [("Problema", ["Retrasa", "Ninguno", "No trata la causa", "Sin diagnóstico"])]))

# NEF-100 · Síndrome post-RTU · CICLO
S("ciclo", "NEF-100", "postoperatorio-rtu-prostata-irrigacion-hipotonica-convulsion-hiponatremia",
  "Convulsión tras una RTU de próstata con irrigación hipotónica: hiponatremia",
  "Urología · complicaciones de la RTU", ESP,
  ("Síndrome post-RTU", ["La solución de irrigación (glicina, sorbitol, agua) se absorbe por los vasos abiertos de la próstata.",
                         "Diluye el sodio de la sangre: hiponatremia aguda y edema cerebral."]),
  ("Varón de 87 años, 1 h después de una RTU", ["Irrigación continua con solución hipotónica, anestesia raquídea.",
                                                "Agitación, desorientación y convulsión tónico-clónica; PA estable."]),
  ["Agitación y convulsión tras RTU con irrigación hipotónica = hiponatremia aguda dilucional.",
   "Con síntomas graves: salino hipertónico al 3 % en bolo; detener la irrigación.",
   "Prevención: irrigación con salino (resección bipolar) y tiempos de resección cortos."],
  EAU + "; " + HARRISON + ".",
  d=dict(rotulo="Cómo se produce", tag="ESTE CASO",
         img_titulo="De la irrigación al cerebro",
         img=D(lambda s, x, y: I.rtu(s, x - 8, y + 50, sc=0.84), 280, 300),
         img_pie="La solución sin sodio se absorbe, diluye la sangre y el agua entra a las neuronas.",
         centro="Síndrome post-RTU", ans=2,
         pasos=[("Irrigación hipotónica", "glicina, sin sodio"), ("Absorción", "por los senos venosos"),
                ("Hiponatremia", "dilución aguda"), ("Edema cerebral", "agua entra a la neurona"),
                ("Convulsión", "agitación, confusión")],
         claves_titulo="Por qué no las otras",
         claves=[("Hipomagnesemia", ["No es lo que produce la irrigación."], False),
                 ("Hipopotasemia", ["Da arritmias y debilidad, no este cuadro."], False),
                 ("Hipocalcemia", ["No se relaciona con la RTU."], False)]),
  tabla=("Opciones de la pregunta", [("Hipomagnesemia", False), ("Hipokalemia", False), ("Hiponatremia", True), ("Hipocalcemia", False)],
         [("¿Explica el cuadro?", ["No", "No", "Sí", "No"])]))

# NEF-101 · Hipopotasemia con alcalosis por diuréticos · MATRIZ + franja
S("matriz", "NEF-101", "preparado-para-bajar-peso-potasio-2-6-alcalosis-diuretico-de-asa",
  "Hipopotasemia con alcalosis y sodio y potasio urinarios altos en quien toma «pastillas para adelgazar»: diurético de asa",
  "Trastornos del potasio · hipopotasemia", ESP,
  ("Hipopotasemia con alcalosis metabólica", ["Se separa por la PA y el cloro/sodio en la orina.",
                                               "Si se pierde potasio por el riñón (K urinario > 20) y la PA no está alta: vómitos o diuréticos."]),
  ("Mujer de 22 años", ["6 meses de un preparado magistral «para bajar de peso» (−16 kg).",
                        "K 2,6, alcalosis metabólica; orina: Na 40, K 30; PA 100/70; ECG con ondas U."]),
  ["Hipopotasemia + alcalosis + Na y K urinarios altos + PA normal-baja + preparado para adelgazar = diurético de asa (furosemida).",
   "Los vómitos darían cloro urinario bajo; el hiperaldosteronismo daría hipertensión.",
   "Reponer potasio (ECG alterado: vía EV con monitoreo) y suspender el preparado."],
  HARRISON + "; " + KDIGO + ".",
  d=dict(rotulo="Causas de hipopotasemia con alcalosis", eje_x="Dato", eje_y="Causa", caso=(1, 2),
         cols=["Presión arterial", "Na/Cl en orina", "Pista del caso"],
         rows=["Vómitos o bulimia", "Diuréticos", "Hiperaldosteronismo", "Bartter o Gitelman"],
         cells=[[("Normal o baja", ["Por contracción"]), ("Cl bajo", ["< 20 mEq/L"]), ("Vomita", ["Erosión dental"])],
                [("Normal o baja", ["PA 100/70"]), ("Na y Cl altos", ["Na 40, K 30"]), ("Preparado para adelgazar", ["Este caso"])],
                [("Alta", ["Retiene sodio"]), ("Na alto", ["K alto"]), ("HTA + hipopotasemia", ["Renina baja"])],
                [("Normal", ["Desde la infancia"]), ("Na y Cl altos", ["Como un diurético"]), ("Sin fármacos", ["Descartar diurético oculto"])]]),
  banda=B("ECG del caso (esquema)", D(lambda s, x, y: I.ecg_tira(s, x, y, "hipok", W=620), 620, 100),
          ["ST descendido y onda T aplanada.", "Onda U grande después de la T.", "Riesgo de arritmias: pulso irregular."], ans=1),
  tabla=("Opciones de la pregunta", [("Anorexígenos simpaticomiméticos", False), ("T3 a dosis altas", False), ("Polivitamínico", False),
                                     ("Diurético de asa", True)],
         [("¿Explica K bajo + alcalosis + Na/K urinarios altos?", ["No", "No", "No", "Sí"])]))

# NEF-102 · Nefritis lúpica clase IV · ESCALERA
S("escalera", "NEF-102", "lupus-creatinina-3-1-cilindros-hematicos-nefritis-clase-iv-ciclofosfamida",
  "Nefritis lúpica clase IV con creatinina alta que no mejora con corticoide: ciclofosfamida",
  "Glomerulopatías · nefritis lúpica", ESP,
  ("Nefritis lúpica clase IV", ["Proliferativa difusa: la forma más grave y frecuente.",
                                "Inducción: corticoide en pulsos + inmunosupresor; luego mantenimiento."]),
  ("Mujer de 25 años con LES", ["Corticoide irregular; creatinina 3,1, proteinuria 2,5 g/24 h, cilindros hemáticos.",
                                "Biopsia: clase IV; no mejora al subir el corticoide."]),
  ["Clase IV activa con creatinina alta: inducción con ciclofosfamida EV (NIH o Euro-Lupus) + pulsos de corticoide.",
   "El micofenolato es alternativa de inducción; mantenimiento con micofenolato o azatioprina.",
   "Siempre hidroxicloroquina y bloqueo del sistema renina-angiotensina."],
  KDIGO + ", nefritis lúpica (2024); EULAR (2023).",
  d=dict(rotulo="La biopsia y la escalera de tratamiento",
         img=dict(titulo="Glomérulo en la clase IV (esquema)", IH=200,
                  ilu=lambda s, x, y: I.glomerulo(s, x + 320, y, "proliferativo", sc=0.9),
                  pie="Proliferación de células y depósitos inmunes en casi todos los glomérulos: daño activo."),
         check_titulo="¿Qué tan grave es?",
         check=[("Creatinina 3,1 mg/dL", True), ("Cilindros hemáticos y hematuria dismórfica", True), ("Sin mejoría al subir el corticoide", True)],
         veredicto="CLASE IV ACTIVA: inmunosupresor de inducción",
         peldanos=[("Base", ["Hidroxicloroquina, IECA o ARA II."]),
                   ("Pulsos de corticoide", ["Metilprednisolona y luego prednisona."]),
                   ("Ciclofosfamida EV", ["Inducción; alternativa: micofenolato."]),
                   ("Mantenimiento", ["Micofenolato o azatioprina."])],
         ans=2, tag="ESTE CASO", salto="Clase IV grave",
         leyenda_estable="Toda nefritis lúpica: base + corticoide; luego se escala según la clase.",
         leyenda_inestable="Este caso: clase IV con creatinina alta → ciclofosfamida de inducción."),
  tabla=("Opciones de la pregunta", [("Ciclofosfamida", True), ("Rituximab", False), ("Azatioprina", False), ("Metotrexato", False)],
         [("Comentario", ["Inducción de elección aquí", "Refractarios", "Mantenimiento", "No para nefritis"])]))

# NEF-103 · Masa testicular sólida · ÁRBOL + franja
S("arbol", "NEF-103", "masa-testicular-solida-indolora-marcadores-orquiectomia-radical-inguinal",
  "Masa testicular sólida e indolora: marcadores tumorales y orquiectomía radical inguinal",
  "Urología · cáncer testicular", ESP,
  ("Masa testicular", ["En un varón joven, una masa sólida intratesticular es cáncer germinal hasta demostrar lo contrario.",
                       "Se diagnostica y trata a la vez con la orquiectomía radical por vía inguinal."]),
  ("Varón de 25 años", ["1 mes de aumento del testículo derecho, indoloro.",
                        "Masa firme que no transilumina; eco: masa sólida intratesticular."]),
  ["Masa sólida intratesticular: marcadores (AFP, β-hCG, LDH) y orquiectomía radical inguinal.",
   "Nunca biopsia ni cirugía por el escroto: se siembra el tumor en otras vías linfáticas.",
   "Los antibióticos o la serología no tienen lugar sin signos de infección."],
  EAU + ", cáncer testicular; NCCN.",
  arbol=Q("¿La ecografía muestra una masa sólida dentro del testículo?", [
      L("No: quística o fuera del testículo", "Benigna probable", ["Hidrocele, espermatocele, quiste"]),
      L("Sí", "MARCADORES + ORQUIECTOMÍA RADICAL INGUINAL", ["AFP, β-hCG y LDH antes de operar", "Nunca biopsia ni vía escrotal"], path=True)],
    path=True),
  banda=B("Testículos del paciente (esquema)", D(lambda s, x, y: I.testiculo(s, x + 10, y, "masa"), 270, 232),
          ["Masa sólida en el testículo derecho (en el dibujo, a la izquierda).", "Firme, indolora, no transilumina.",
           "Se saca todo el testículo con su cordón por la ingle."], ans=0),
  tabla=("Opciones de la pregunta", [("Marcadores + orquiectomía inguinal", True), ("Biopsia con aguja fina", False),
                                     ("Serología para Brucella", False), ("Antibióticos y reevaluar", False)],
         [("Problema", ["Ninguno", "Siembra el tumor", "No hay infección", "Retrasa el diagnóstico"])]))

# NEF-104 · Membranosa secundaria · BALANZA + franja
S("balanza", "NEF-104", "fumador-64-anos-baja-peso-nefropatia-membranosa-buscar-neoplasia",
  "Nefropatía membranosa en fumador de 64 años que baja de peso: buscar un cáncer oculto",
  "Glomerulopatías · nefropatía membranosa", ESP,
  ("Nefropatía membranosa", ["Primaria (anticuerpos anti-PLA2R) o secundaria a cáncer, infecciones, lupus o fármacos.",
                             "En el adulto mayor, sobre todo fumador, hay que buscar un tumor sólido."]),
  ("Varón de 64 años, fumador", ["2 meses de edema, astenia y baja de 4 kg.",
                                 "Proteinuria > 3,5 g/24 h, albúmina 2,2, colesterol 310; biopsia: membranosa."]),
  ["Membranosa + edad > 60 + tabaco + baja de peso = buscar neoplasia sólida oculta (pulmón, colon, próstata).",
   "Si se trata el cáncer, la proteinuria suele mejorar.",
   "El anti-PLA2R negativo apoya que sea secundaria."],
  KDIGO + ", glomerulopatías (2021); " + HARRISON + ".",
  d=dict(rotulo="¿Qué pesa más ahora?", gana="izq", tag="ESTE CASO",
         pregunta="Membranosa en fumador mayor que baja de peso",
         izq=dict(titulo="Buscar una neoplasia oculta", peso="elige",
                  items=["Edad > 60 y tabaco", "Baja de peso sin explicación", "La membranosa puede ser la primera señal del cáncer"]),
         der=dict(titulo="Tratar como primaria", peso="no",
                  items=["Corticoides sin saber la causa", "Retrasa el diagnóstico del tumor", "No corrige la causa"]),
         veredicto=("Buscar neoplasia sólida oculta",
                    ["Rx o TC de tórax, colon, próstata según edad; anti-PLA2R."])),
  banda=B("Glomérulo en la membranosa (esquema)", D(lambda s, x, y: I.glomerulo(s, x + 10, y, "membranosa", sc=0.95), 270, 220),
          ["Membrana basal engrosada por depósitos inmunes.", "Deja escapar mucha proteína: síndrome nefrótico.",
           "Los antígenos del tumor pueden formar esos depósitos."], ans=2),
  tabla=("Opciones de la pregunta", [("Glucocorticoides a dosis altas", False), ("Manejo conservador", False), ("Buscar neoplasia oculta", True),
                                     ("Tratar como posinfecciosa", False)],
         [("Problema", ["Sin buscar la causa", "Deja pasar el tumor", "Ninguno", "Otra enfermedad"])]))

# NEF-105 · Anemia de la ERC · COMPARADOR (dibujos)
S("comparador", "NEF-105", "erc-estadio-4-anemia-normocitica-ferritina-normal-deficit-eritropoyetina",
  "ERC estadio 4 con anemia normocítica y hierro normal: falta de eritropoyetina",
  "Enfermedad renal crónica · anemia", ESP,
  ("Anemia de la enfermedad renal crónica", ["El riñón produce eritropoyetina (EPO), que ordena a la médula fabricar glóbulos rojos.",
                                             "Con pocas nefronas hay poca EPO: anemia normocítica."]),
  ("Mujer de 45 años, HTA y ERC estadio 4", ["Cansancio progresivo.", "Hb 9, VCM 90; ferritina, saturación, albúmina y TSH normales."]),
  ["Anemia normocítica + ERC avanzada + hierro normal = déficit de eritropoyetina.",
   "Tratamiento: agentes estimulantes de la eritropoyesis, con hierro si hace falta; meta Hb 10-11,5.",
   "No hay hemólisis aguda; el fósforo alto no da anemia ni hipercalcemia."],
  KDIGO + ", anemia en ERC (2012, actualización 2025).",
  d=dict(rotulo="Riñón sano frente a riñón con ERC", IH=270, tag="ESTE CASO",
         imgs=[dict(titulo="Riñón sano", ilu=lambda s, x, y: I.rinon_vias(s, x + 57, y, "normal", sc=0.95),
                    pie="Muchas nefronas: produce eritropoyetina suficiente."),
               dict(titulo="ERC estadio 4", on=True, ilu=lambda s, x, y: I.rinon_vias(s, x + 57, y, "rinones_pequenos", sc=0.95),
                    pie="Riñones pequeños: poca eritropoyetina, la médula fabrica menos glóbulos rojos.")],
         lectura_titulo="Cómo se llega",
         lectura=[("Normocítica (VCM 90)", ["No es ferropénica ni por B12."], False),
                  ("Hierro y TSH normales", ["Se descartan otras causas."], False),
                  ("Falta EPO", ["Mecanismo propio del riñón enfermo."], True)]),
  tabla=("Opciones de la pregunta", [("Pérdida de proteínas", False), ("Hemólisis aguda", False), ("Menos eritropoyetina", True),
                                     ("Hiperfosfatemia", False)],
         [("¿Explica la anemia?", ["No: albúmina normal", "No hay datos", "Sí", "No"])]))

# NEF-106 · Contraste en diabético con metformina · SEMÁFORO
S("semaforo", "NEF-106", "diabetico-metformina-tfge-40-tc-contraste-salino-suspender-metformina",
  "Diabético con metformina y TFGe 40 que recibirá contraste: hidratar con salino y suspender metformina",
  "Lesión renal · prevención con contraste yodado", ESP,
  ("Contraste yodado y riñón", ["Con TFG reducida aumenta el riesgo de lesión renal por contraste.",
                                "La medida que la previene es la hidratación EV con salino isotónico."]),
  ("Varón de 65 años con DM2 y metformina", ["Sospecha de tumor renal: TC con contraste.", "PA 130/80, hidratado, TFGe 40."]),
  ["TFGe reducida: salino 0,9 % EV antes y después del contraste.",
   "Suspender la metformina el día del estudio y reanudarla a las 48 h si la creatinina está estable (riesgo de acidosis láctica).",
   "Diuréticos, N-acetilcisteína y hemodiálisis profiláctica no previenen la lesión."],
  "ACR, manual de contraste (2024); ESUR (2018); " + KDIGO + ".",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="Función renal del caso",
         ilu=ILU(D(lambda s, x, y: I.lab_barras(s, x - 10, y + 40, [("TFGe", "40", 40, True), ("Precaución", "< 45", 45, False),
                                                                    ("Alto riesgo", "< 30", 30, False)],
                                                 W=280, xmax=90, titulo="mL/min/1,73 m²", ref=None), 270, 200)),
         ilu_pie="TFGe de 40: zona de precaución.",
         check_titulo="Datos del caso",
         check=[("Diabético con metformina", False), ("TFGe 40", False), ("Hidratado, PA normal", True),
                ("Necesita TC con contraste", True)],
         ans=1, tag="ESTE CASO",
         luces=[("TFGe ≥ 45", "Sin medidas especiales", ["Hidratación oral; mantener la metformina."]),
                ("TFGe 30-44", "Hidratar y suspender metformina", ["Salino 0,9 % EV antes y después; reanudar a las 48 h."]),
                ("TFGe < 30 o lesión aguda", "Reconsiderar el contraste", ["Estudio alternativo o dosis mínima con hidratación."])]),
  tabla=("Opciones de la pregunta", [("Diuréticos y restringir líquidos", False), ("Suspender metformina + salino EV", True),
                                     ("N-acetilcisteína", False), ("Hemodiálisis profiláctica", False)],
         [("¿Previene?", ["Empeora", "Sí", "Sin beneficio", "Sin beneficio"])]))

# NEF-107 · Cólico nefrítico: AINE y ecografía · ÁRBOL + franja
S("arbol", "NEF-107", "dolor-lumbar-irradiado-testiculo-hematuria-sin-infeccion-aine-ev-ecografia",
  "Cólico nefrítico sin signos de infección: AINE EV y ecografía renal",
  "Urología · manejo del cólico renal", ESP,
  ("Cólico nefrítico", ["Calmar el dolor y confirmar el cálculo.",
                        "Los AINE son los mejores analgésicos: bajan la presión dentro del uréter."]),
  ("Varón de 34 años", ["10 h de dolor lumbar derecho irradiado al testículo, náuseas y vómitos.",
                        "Signos vitales normales; puñopercusión (+); creatinina 0,9; hematuria sin leucocitos ni bacterias."]),
  ["Cólico sin fiebre ni infección: AINE EV de acción rápida (ketorolaco, diclofenaco) + ecografía renal.",
   "Fiebre o infección con obstrucción: drenaje urgente (catéter o nefrostomía) + antibiótico.",
   "Los antiespasmódicos no superan a los AINE; los corticoides no tienen papel."],
  EAU + ", urolitiasis (2024).",
  arbol=Q("¿Hay fiebre, leucocitosis o infección urinaria?", [
      L("Sí", "Riñón obstruido e infectado", ["Antibiótico + drenaje urgente"]),
      L("No", "AINE EV + ECOGRAFÍA RENAL", ["Ketorolaco o diclofenaco", "Eco: dilatación y cálculo"], path=True)], path=True),
  banda=B("Vía urinaria (esquema)", D(lambda s, x, y: I.rinon_vias(s, x, y, "litiasis", sc=0.95), 290, 270),
          ["Cálculo en el uréter derecho.", "El riñón se dilata por encima del cálculo (lo muestra la ecografía).",
           "El AINE baja la presión y la inflamación del uréter."], ans=0),
  tabla=("Opciones de la pregunta", [("Antibióticos previo urocultivo", False), ("Corticoides y reposo", False), ("AINE EV + ecografía", True),
                                     ("Solo antiespasmódicos", False)],
         [("Problema", ["No hay infección", "Sin papel", "Ninguno", "Menos eficaces que el AINE"])]))

# NEF-108 · Aplastamiento: NTA por mioglobina · CRONOLOGÍA
_bloque = '<rect x="66" y="282" width="62" height="34" rx="4" fill="#9ca3af" stroke="#4b5563" stroke-width="2"/>'
S("cronologia", "NEF-108", "aplastamiento-8-horas-orina-oscura-rabdomiolisis-necrosis-tubular-mioglobina",
  "Atrapado 8 horas bajo un muro con orina oscura: necrosis tubular aguda por mioglobina",
  "Lesión renal aguda · rabdomiólisis", ESP,
  ("Síndrome de aplastamiento", ["El músculo comprimido se destruye (rabdomiólisis) y libera mioglobina y potasio.",
                                 "La mioglobina obstruye y daña los túbulos: necrosis tubular aguda."]),
  ("Varón de 35 años", ["8 h atrapado por una pared; muslo derecho tenso, doloroso y adormecido.",
                        "Orina escasa y muy oscura; creatinina 4,1, urea 210."]),
  ["Aplastamiento prolongado + orina oscura + falla renal = necrosis tubular aguda por mioglobinuria.",
   "Hidratar con salino de forma agresiva, idealmente desde antes de liberar al atrapado; meta diuresis alta.",
   "Vigilar potasio (arritmias) y síndrome compartimental."],
  "Renal Disaster Relief Task Force (ISN); " + HARRISON + ".",
  d=dict(rotulo="Del aplastamiento al riñón", tag="ESTE CASO",
         ilu_titulo="El paciente atrapado",
         ilu=ILU(D(lambda s, x, y: I.cuerpo(s, x + 90, y, {"muslo_d": "#fca5a5"}, extra=_bloque, marcas=[(1, 98, 336)], sc=0.62), 330, 280)),
         ilu_pie="Muslo derecho aplastado 8 horas (1).",
         claves=[("Necrosis tubular por mioglobina", ["Orina oscura tras liberar el músculo."], True),
                 ("Prerrenal por deshidratación", ["Puede sumarse, pero no explica la orina oscura."], False),
                 ("Obstrucción o hemorragia", ["Sin datos de coágulos ni sangrado."], False)],
         eje_titulo="Horas desde el atrapamiento", eje=(0, 24), paso=4, marca=8, unidad="h",
         eje_nombre="horas",
         hitos=[(0, 8, "Atrapado", "músculo comprimido", False),
                (0, 8, "Hidratación ideal", "antes de liberarlo", False),
                (8, 12, "Liberación", "mioglobina y potasio a la sangre", True),
                (10, 24, "Orina oscura y NTA", "creatinina 4,1", False)]),
  tabla=("Opciones de la pregunta", [("Obstrucción por coágulos", False), ("Deshidratación", False), ("NTA por mioglobinuria", True),
                                     ("Hemorragia interna", False)],
         [("¿Explica la orina oscura?", ["No", "No", "Sí", "No"])]))


# NEF-109 · Lesión renal prerrenal · CÁLCULO
def _prerrenal(s, x, y):
    I.lab_barras(s, x - 4, y, [("BUN/creat.", "24", 24, True), ("Corte", "20", 20, False)], W=220, xmax=30, titulo="Relación BUN/creatinina", ref=None)
    I.cuerpo(s, x + 50, y + 100, {"cara": "#fdf3ec"}, marcas=[(1, 120, 54), (2, 120, 250)], sc=0.55)


S("calculo", "NEF-109", "diarrea-vomitos-anuria-urea-130-creatinina-2-5-prerrenal-salino",
  "Diarrea y vómitos con anuria, urea 130 y creatinina 2,5: lesión renal prerrenal, solución salina",
  "Lesión renal aguda · prerrenal", ESP,
  ("Lesión renal aguda prerrenal", ["El riñón está sano pero le llega poca sangre por falta de volumen.",
                                    "Si se repone a tiempo, la función vuelve."]),
  ("Mujer de 25 años", ["3 días de diarrea abundante y vómitos; no tolera líquidos; no orina hace 12 h.",
                        "Deshidratada; urea 130 mg/dL, creatinina 2,5 mg/dL."]),
  ["Pérdidas digestivas + deshidratación + BUN/creatinina > 20 = lesión renal prerrenal.",
   "Conducta inicial: solución salina 0,9 % EV y vigilar la diuresis.",
   "La diálisis, los diuréticos o derivar sin hidratar no corrigen la causa."],
  KDIGO + ", lesión renal aguda (2012); " + HARRISON + ".",
  d=dict(rotulo="Se calcula y se razona", tag="ESTE CASO",
         ilu_titulo="La paciente y su laboratorio",
         ilu=ILU(D(_prerrenal, 218, 360)),
         ilu_pie="1 mucosas secas; 2 no orina. BUN/creatinina 24.",
         pasos=[("Urea a BUN", ["130 ÷ 2,14 ≈ 61 mg/dL."], False),
                ("BUN/creatinina", ["61 ÷ 2,5 ≈ 24 (> 20)."], False),
                ("Clínica", ["Diarrea, vómitos, deshidratada, sin orinar."], False),
                ("Tipo de lesión", ["Prerrenal: falta volumen."], False),
                ("Resultado", ["Solución salina 0,9 % EV."], True)]),
  tabla=("Opciones de la pregunta", [("Diálisis de emergencia", False), ("Diuréticos EV", False), ("Solución salina EV", True),
                                     ("Derivar a nefrología", False)],
         [("Problema", ["Sin indicación", "Empeoran la volemia", "Ninguno", "Retrasa la hidratación"])]))
