"""Bloque ENAM 2026 · Salud Pública (parte 2)."""
from c26 import S, D, B, ILU, Q, L, MINSA
import ilu7 as I
import ilu8 as J

O = I.ORANGE
ESP = "SALUD PÚBLICA ENAM"
GORDIS = "Gordis, Epidemiología 6.ª ed."
OTTAWA = "OMS, Carta de Ottawa (1986)"


def _sectores(s, x, y):
    it = ["Educación", "Municipio", "Vivienda", "Transporte", "Agricultura", "Trabajo"]
    import math
    p = I.C(160, 104, 34, I.TEAL, "none", 0) + I.t(160, 108, "Salud", "#ffffff", 11, halo=False)
    for k, nom in enumerate(it):
        a = -math.pi / 2 + k * 2 * math.pi / 6
        cx, cy = 160 + 120 * math.cos(a), 104 + 76 * math.sin(a)
        p += I.P(f"M{160 + 36 * math.cos(a):.0f} {104 + 36 * math.sin(a):.0f} L{cx - 40 * math.cos(a):.0f} {cy - 14 * math.sin(a):.0f}", "none", I.ORANGE, 2)
        p += J.caja(cx - 44, cy - 14, 88, 28, nom, "#ffffff", "#94a3b8", fs=10)
    p += I.t(160, 204, "coordinar sectores = acción intersectorial", I.ORANGE, 10.5)
    I.g(s, x, y, p)


# SP-212 · Comunicación intersectorial · RADIAL + franja
S("radial", "SP-212", "carta-ottawa-articulacion-coordinacion-sectores-comunicacion-intersectorial",
  "Coordinar a distintos sectores para mejorar los determinantes de la salud: acción intersectorial",
  "Promoción de la salud · Carta de Ottawa", ESP,
  ("Intersectorialidad", ["La salud depende de educación, vivienda, trabajo, transporte y más.",
                          "Articular a esos sectores es la acción (comunicación) intersectorial."]),
  ("Pregunta de concepto", ["«Facilitar la articulación y coordinación entre sectores para mejorar los determinantes de la salud»."]),
  ["Eso corresponde a la comunicación o acción intersectorial.",
   "Participación ciudadana: la comunidad decide y actúa; promoción de la salud: el marco general.",
   "«Prevención de la salud» no es un término correcto."],
  OTTAWA + "; OPS, salud en todas las políticas.",
  d=dict(rotulo="Las cuatro opciones frente al concepto", ans=0, centro="Articular sectores",
         items=[("Comunicación intersectorial", ["Coordina sectores distintos al de salud"]),
                ("Participación ciudadana", ["La comunidad toma parte en las decisiones"]),
                ("Promoción de la salud", ["Es el marco general, no esta acción"]),
                ("«Prevención de la salud»", ["Término incorrecto"])],
         ruta=["Problema con muchas causas", "Varios sectores implicados", "Mesa de coordinación", "Acción intersectorial"]),
  banda=B("Sectores que se articulan", D(_sectores, 320, 214),
          ["Salud en el centro.", "Educación, municipio, vivienda y otros sectores alrededor.", "Coordinarlos mejora los determinantes."], ans=2),
  tabla=("Opciones de la pregunta", [("Participación ciudadana", False), ("«Prevención de la salud»", False), ("Promoción de la salud", False),
                                     ("Comunicación intersectorial", True)],
         [("¿Es la definición?", ["No", "Término incorrecto", "Muy general", "Sí"])]))

# SP-213 · Seguridad del paciente proactiva · COMPARADOR
S("comparador", "SP-213", "doble-chequeo-alertas-informaticas-medicacion-seguridad-paciente-proactiva",
  "Doble chequeo y alertas antes de dispensar: estrategia proactiva de seguridad del paciente",
  "Calidad · seguridad del paciente", ESP,
  ("Seguridad del paciente", ["Reactiva: se actúa después del evento adverso.",
                              "Proactiva: se ponen barreras para que el error no llegue al paciente."]),
  ("Centro de salud I-4", ["Enfermería hace doble chequeo de las recetas antes de dispensar.",
                           "El sistema informático alerta interacciones o dosis erróneas."]),
  ["Barreras antes del error (doble chequeo, alertas) = actitud proactiva en seguridad clínica.",
   "El enfoque moderno mira el sistema, no culpa a la persona.",
   "Reactiva sería analizar el error después de que ocurrió."],
  "OMS, Plan de acción mundial para la seguridad del paciente 2021-2030; Reason (2000).",
  d=dict(rotulo="Proactiva frente a reactiva", IH=226, tag="ESTE CASO",
         imgs=[dict(titulo="Proactiva: barreras", on=True, ilu=lambda s, x, y: J.queso(s, x + 27, y, sc=0.95),
                    pie="Varias barreras: el error se detiene antes de llegar al paciente."),
               dict(titulo="Reactiva", ilu=lambda s, x, y: J.flujo_bloques(s, x + 37, y + 20,
                    [("Ocurre el error", "llega al paciente"), ("Se notifica", "evento adverso"), ("Se analiza después", "y se corrige")], W=300),
                    pie="Se actúa cuando el daño ya ocurrió.")],
         lectura_titulo="Otras opciones",
         lectura=[("Proactiva", ["Barreras antes del error."], True),
                  ("Responsabilidad individual", ["Ignora el sistema."], False),
                  ("Búsqueda de culpables", ["Desalienta reportar errores."], False)]),
  tabla=("Opciones de la pregunta", [("Responsabilidad individual", False), ("Conducta reactiva", False), ("Búsqueda punitiva", False),
                                     ("Actitud proactiva", True)],
         [("¿Describe la medida?", ["No", "No: es antes del error", "No", "Sí"])]))

# SP-214 · Enfoque intercultural · ÁRBOL CON IMAGEN
S("arbol_imagen", "SP-214", "comunidad-quechua-anemia-barreras-culturales-lideres-comunitarios-promotores",
  "Anemia alta en una comunidad quechua con barreras culturales: capacitar líderes comunitarios como promotores",
  "Promoción de la salud · interculturalidad", ESP,
  ("Enfoque intercultural", ["Se trabaja con los saberes, el idioma y los líderes de la propia comunidad.",
                             "Así se superan la desconfianza y las barreras de idioma."]),
  ("Comunidad quechua del Cusco", ["Anemia en 48 % de gestantes y 44 % de menores de 5 años.",
                                   "Desconfianza a la medicina occidental, transporte difícil, poco español."]),
  ["Capacitar a autoridades y agentes de medicina tradicional como promotores de salud.",
   "Ellos llevan los mensajes en quechua y generan confianza; luego mejora el uso de suplementos y servicios.",
   "Folletos en español o repartir hierro sin acompañamiento chocan con las barreras."],
  "MINSA, política sectorial de salud intercultural; OPS.",
  d=dict(rotulo="¿Qué estrategia llega mejor?", tag="ESTE CASO",
         pregunta="¿Hay barreras culturales y de idioma con los servicios?",
         ramas=[("No", "Intervención habitual", ["Suplementos y consejería en el establecimiento."]),
                ("Sí: comunidad quechua", "Líderes comunitarios como promotores",
                 ["Autoridades y agentes de medicina tradicional capacitados.", "Hablan quechua y tienen la confianza de la comunidad."])],
         ilu=lambda s, x, y: J.comunidad(s, x, y, sc=0.95), IW=323, IH=190,
         ilu_pie="El promotor de la comunidad lleva la información casa por casa.",
         luego_titulo="Por qué no las otras",
         luego=[("Promotores comunitarios", ["Superan idioma y desconfianza."], True),
                ("Folletos en español", ["No se leen ni se entienden."], False),
                ("Solo repartir hierro", ["Sin confianza, no se consume."], False)]),
  tabla=("Opciones de la pregunta", [("Folletos en español", False), ("Repartir hierro y ácido fólico", False), ("Capacitar líderes como promotores", True),
                                     ("Vacunación intensiva", False)],
         [("Problema", ["Barrera de idioma", "No vence la desconfianza", "Ninguno", "No trata la anemia"])]))

# SP-215 · Rendimiento hora médico · CÁLCULO
S("calculo", "SP-215", "productividad-consulta-externa-atenciones-por-hora-rendimiento-hora-medico",
  "Atenciones por hora de trabajo médico: rendimiento hora médico",
  "Gestión · indicadores de consulta externa", ESP,
  ("Indicadores de consulta externa", ["Rendimiento hora médico = atenciones ÷ horas médico programadas o trabajadas.",
                                       "Mide productividad del recurso médico."]),
  ("Clínica", ["El administrador quiere medir atenciones por recurso médico por unidad de tiempo."]),
  ["Rendimiento hora médico: número de atenciones ÷ horas de médico (norma: alrededor de 4 por hora).",
   "Consultas/egresos y % de internamiento por consulta son otros indicadores.",
   "% de consultas programadas atendidas mide cumplimiento, no productividad por hora."],
  MINSA + ", indicadores de gestión hospitalaria.",
  d=dict(rotulo="Cómo se calcula", tag="ESTE CASO",
         ilu_titulo="Una hora de consulta",
         ilu=ILU(D(lambda s, x, y: J.reloj(s, x + 2, y + 30, 4, sc=0.7), 218, 170)),
         ilu_pie="Ejemplo: 4 atenciones en 1 hora.",
         pasos=[("Numerador", ["Atenciones realizadas."], False),
                ("Denominador", ["Horas de médico en consulta."], False),
                ("Ejemplo", ["120 atenciones ÷ 30 horas = 4."], False),
                ("Se interpreta", ["4 atenciones por hora médico."], False),
                ("Resultado", ["Rendimiento hora médico."], True)]),
  tabla=("Opciones de la pregunta", [("Consultas/egresos", False), ("% internamiento por consulta", False), ("% consultas programadas atendidas", False),
                                     ("Rendimiento hora médico", True)],
         [("Mide", ["Otra relación", "Derivación", "Cumplimiento", "Atenciones por hora: este caso"])]))

# SP-216 · Brote por agua · ÁRBOL + franja
S("arbol", "SP-216", "aumento-diarreas-7-dias-brote-agua-notificar-muestras-agua-heces",
  "Aumento inusual de diarreas por posible agua contaminada: notificar y tomar muestras de agua y heces",
  "Vigilancia epidemiológica · estudio de brote", ESP,
  ("Brote", ["Más casos de los esperados en un lugar y tiempo, con una fuente común probable.",
             "Lo primero: notificar y confirmar la causa."]),
  ("Médico de una zona rural", ["Aumento inusual de diarreas en 7 días.", "Sospecha de transmisión por el agua."]),
  ["Acción inmediata: notificar al sistema de vigilancia y coordinar muestras de agua y de heces.",
   "Luego: definición de caso, búsqueda activa, curva epidémica y medidas de control (agua segura, cloración).",
   "Charlas, pozos nuevos o antidiarreicos masivos no son lo primero."],
  "CDC, investigación de brotes; " + MINSA + ", vigilancia epidemiológica.",
  arbol=Q("¿Hay más casos de lo esperado (posible brote)?", [
      L("No", "Vigilancia habitual", ["Atender y registrar"]),
      L("Sí: diarreas en aumento", "NOTIFICAR Y TOMAR MUESTRAS", ["Agua y heces para el laboratorio", "Pone en marcha al sistema"], path=True)], path=True),
  banda=B("Curva de casos (esquema)", D(lambda s, x, y: I.linea_xy(s, x, y, [(1, 2), (2, 2), (3, 3), (4, 6), (5, 12), (6, 18), (7, 22)], (1, 7), (0, 25),
                                                                    "Días", "Casos de diarrea", bandas=[(0, 4, "#bbf7d0", "lo esperado")],
                                                                    marca=(7, 22, "hoy"), W=270, H=150), 330, 200),
          ["Lo habitual son 2-3 casos al día.", "En una semana subieron mucho: posible brote.", "Hay que confirmar la fuente: el agua."], ans=1),
  tabla=("Opciones de la pregunta", [("Notificar y tomar muestras", True), ("Charlas en escuelas", False), ("Antidiarreicos masivos", False),
                                     ("Construir pozos", False)],
         [("¿Inmediata?", ["Sí", "Después", "No", "Largo plazo"])]))

# SP-217 · Revisión sistemática: fuente secundaria · RADIAL + franja
S("radial", "SP-217", "busqueda-antecedentes-revisiones-sistematicas-fuente-secundaria",
  "Revisiones sistemáticas como antecedentes: fuente secundaria",
  "Investigación · fuentes de información", ESP,
  ("Fuentes de información", ["Primaria: el estudio original con datos nuevos.",
                              "Secundaria: reúne y sintetiza estudios primarios. Terciaria: resume las secundarias (libros, guías)."]),
  ("Estudiante investigador", ["Busca antecedentes en revisiones sistemáticas."]),
  ["La revisión sistemática no genera datos nuevos: sintetiza estudios primarios → fuente secundaria.",
   "El ensayo clínico o la cohorte original son fuentes primarias.",
   "Libros de texto, enciclopedias y muchos manuales son terciarios."],
  "Hernández Sampieri, Metodología de la investigación 7.ª ed.",
  d=dict(rotulo="Las cuatro opciones", ans=0, centro="Revisión sistemática",
         items=[("Secundaria", ["Sintetiza estudios primarios"]),
                ("Primaria", ["Genera datos originales"]),
                ("Terciaria", ["Resume fuentes secundarias"]),
                ("Cuaternaria", ["No es una categoría usada"])],
         ruta=["Estudios originales", "Revisión sistemática", "Guía o libro", "Lector"]),
  banda=B("Niveles de fuentes (esquema)", D(lambda s, x, y: J.fuentes(s, x, y, caso=1, sc=0.95), 323, 200),
          ["Primaria: el estudio original.", "Secundaria (naranja): revisión sistemática.", "Terciaria: libro o guía."], ans=1),
  tabla=("Opciones de la pregunta", [("Secundaria", True), ("Primaria", False), ("Terciaria", False), ("Cuaternaria", False)],
         [("¿Correcto?", ["Sí", "No: no genera datos", "No", "No existe"])]))

# SP-218 · Mantenimiento preventivo · BALANZA + franja
S("balanza", "SP-218", "monitoreo-mantenimiento-preventivo-equipos-biomedicos-menos-fallas",
  "Monitorear el mantenimiento preventivo de equipos: menos fallas, menos tiempo inactivo, sin interrupciones",
  "Gestión · equipamiento biomédico", ESP,
  ("Mantenimiento preventivo", ["Se revisa el equipo antes de que falle, según un programa.",
                                "Monitorear sus indicadores permite corregir a tiempo."]),
  ("Comité de gestión de riesgos", ["Revisa cada trimestre los indicadores del mantenimiento preventivo."]),
  ["Principal aporte: prevenir fallas recurrentes, reducir tiempos de inactividad y evitar interrupciones de la atención.",
   "No elimina por completo el riesgo.",
   "No se limita a costos ni a registrar eventos sin cambiar la programación."],
  "OMS, introducción a la gestión del mantenimiento de equipos médicos (2012).",
  d=dict(rotulo="¿Qué conviene?", gana="izq", tag="ESTE CASO",
         pregunta="Equipos biomédicos",
         izq=dict(titulo="Preventivo con monitoreo", peso="elige",
                  items=["Detecta fallas antes de que ocurran", "Menos tiempo con el equipo parado", "La atención no se interrumpe"]),
         der=dict(titulo="Solo correctivo", peso="no",
                  items=["Se repara cuando ya falló", "Equipo parado más tiempo", "Riesgo para el paciente"]),
         veredicto=("Prevenir fallas, menos inactividad, sin interrupciones", ["Ningún programa elimina el riesgo por completo."])),
  banda=B("Fallas en el tiempo (esquema)", D(lambda s, x, y: I.linea_xy(s, x, y, [(1, 9), (2, 8), (3, 6), (4, 4), (5, 3), (6, 2), (7, 2), (8, 1.5)], (1, 8), (0, 10),
                                                                         "Trimestres", "Fallas", marca=(4, 4, "monitoreo"), W=270, H=150), 330, 200),
          ["Al monitorear, las fallas bajan.", "Se ajusta la programación según lo que se ve.", "Menos interrupciones de la atención."], ans=0),
  tabla=("Opciones de la pregunta", [("Solo costos", False), ("Registrar sin cambiar", False), ("Eliminar todo riesgo", False), ("Prevenir fallas e interrupciones", True)],
         [("¿Principal aporte?", ["No", "No", "Imposible", "Sí"])]))

# SP-219 · Tamizaje de hemoglobina: prevención · TERMÓMETRO + franja
S("termometro", "SP-219", "cred-lactante-4-meses-tamizaje-hemoglobina-accion-prevencion",
  "Tamizaje de hemoglobina en el CRED: acción de prevención (detección temprana)",
  "Salud pública · niveles de prevención", ESP,
  ("Tipos de acción en salud", ["Promoción, prevención, recuperación y rehabilitación.",
                                "El tamizaje busca la enfermedad antes de los síntomas: es prevención (secundaria)."]),
  ("Lactante de 4 meses en CRED", ["Se le hace tamizaje de hemoglobina para descartar anemia."]),
  ["Tamizaje = detectar temprano en personas sin síntomas → prevención secundaria.",
   "Promoción: estilos de vida y entornos; recuperación: tratar la enfermedad; rehabilitación: recuperar funciones.",
   "La suplementación con hierro sería prevención primaria."],
  MINSA + ", modelo de cuidado integral; Leavell y Clark.",
  d=dict(rotulo="Tipo de acción",
         niveles=[("Promoción", "Antes del riesgo", ["Estilos de vida"]),
                  ("Prevención", "Antes o al inicio del daño", ["Vacunas, tamizaje"]),
                  ("Recuperación", "Con la enfermedad", ["Tratamiento"]),
                  ("Rehabilitación", "Con secuelas", ["Recuperar funciones"])],
         caso_nivel=1, ruta_titulo="Qué incluye la prevención", paso_label="ESTE CASO",
         pasos=[(1, "Tamizaje de hemoglobina", ["Detección temprana"], True),
                (2, "Suplemento de hierro", ["Prevención primaria"], False),
                (3, "Si hay anemia", ["Pasa a recuperación: tratar"], False)]),
  banda=B("Niveles de prevención (esquema)", D(lambda s, x, y: J.prevencion(s, x, y, caso=2, sc=0.85), 323, 150),
          ["El tamizaje está en la prevención secundaria.", "Busca la anemia antes de que dé síntomas.", "Si se detecta, se trata."], ans=0),
  tabla=("Opciones de la pregunta", [("Promoción", False), ("Rehabilitación", False), ("Recuperación", False), ("Prevención", True)],
         [("¿Es el tamizaje?", ["No", "No", "No: aún no se trata", "Sí"])]))

# SP-220 · ASIS · CICLO
S("ciclo", "SP-220", "describir-explicar-estado-salud-determinantes-analisis-situacion-salud",
  "Describir y explicar la salud de una población y sus determinantes: análisis de situación de salud (ASIS)",
  "Salud pública · planificación", ESP,
  ("Análisis de situación de salud (ASIS)", ["Diagnóstico integral de la salud de una población y de sus determinantes.",
                                             "Sirve para priorizar problemas y planificar."]),
  ("Pregunta de concepto", ["¿Qué proceso describe y explica el estado de salud y sus determinantes en una población definida?"]),
  ["ASIS: describe (cuánto, dónde, quiénes) y explica (por qué: determinantes sociales).",
   "Con el ASIS se priorizan los problemas y luego se hacen los planes (POI, PGI).",
   "Los planes institucionales vienen después del análisis."],
  MINSA + ", guía para el ASIS; OPS.",
  d=dict(rotulo="El ciclo del ASIS", tag="ESTE CASO",
         img_titulo="Lo que analiza",
         img=D(lambda s, x, y: J.determinantes(s, x - 30, y + 30, sc=0.95), 280, 260),
         img_pie="Determinantes estructurales e intermedios de la salud de la población.",
         centro="ASIS", ans=1,
         pasos=[("Recoger datos", "población, morbilidad"), ("Describir y explicar", "determinantes"),
                ("Priorizar", "problemas"), ("Planificar", "POI, intervenciones"), ("Evaluar", "y actualizar")],
         claves_titulo="Por qué no las otras",
         claves=[("Plan de gestión institucional", ["Organiza la institución."], False),
                 ("Plan operativo", ["Actividades del año."], False),
                 ("Análisis multisectorial", ["No es el nombre del proceso."], False)]),
  tabla=("Opciones de la pregunta", [("Plan de gestión institucional", False), ("Análisis situacional de salud", True), ("Plan operativo", False),
                                     ("Análisis estratégico multisectorial", False)],
         [("¿Describe y explica la salud?", ["No", "Sí", "No", "No"])]))

# SP-221 · Vigilancia activa · COMPARADOR
S("comparador", "SP-221", "red-salud-visita-establecimientos-revisa-registros-vigilancia-activa",
  "El equipo sale a buscar casos revisando registros y llamando: vigilancia activa",
  "Vigilancia epidemiológica · tipos", ESP,
  ("Tipos de vigilancia", ["Pasiva: se espera que los establecimientos notifiquen.",
                           "Activa: el equipo va a buscar los casos. Centinela: sitios elegidos. Sindrómica: por síndromes."]),
  ("Distrito con más diarreas", ["El equipo visita establecimientos, revisa registros y llama a estadística.",
                                 "Notifica los casos nuevos de inmediato."]),
  ["Ir a buscar los casos = vigilancia activa (más completa, más costosa).",
   "Pasiva: depende de que otros reporten.",
   "Centinela: solo en lugares seleccionados; sindrómica: agrupa por síntomas."],
  GORDIS + "; " + MINSA + ", vigilancia epidemiológica.",
  d=dict(rotulo="Activa frente a pasiva", IH=210, tag="ESTE CASO",
         imgs=[dict(titulo="Activa", on=True, ilu=lambda s, x, y: J.vigilancia(s, x + 27, y, sc=0.95),
                    pie="El equipo va a los establecimientos y busca los casos."),
               dict(titulo="Pasiva", ilu=lambda s, x, y: J.flujo_bloques(s, x + 37, y + 10,
                    [("Establecimiento", "atiende casos"), ("Notifica cuando puede", "por su cuenta"), ("La red espera", "y consolida")], W=300),
                    pie="La red espera que le reporten.")],
         lectura_titulo="Otros tipos",
         lectura=[("Activa", ["Búsqueda directa: este caso."], True),
                  ("Centinela", ["Lugares seleccionados."], False),
                  ("Sindrómica", ["Agrupa por síntomas."], False)]),
  tabla=("Opciones de la pregunta", [("Centinela", False), ("Activa", True), ("Pasiva", False), ("Sindrómica", False)],
         [("¿Describe el caso?", ["No", "Sí", "No: aquí se busca", "No"])]))

# SP-222 · Inequidad · CRITERIOS
S("criterios", "SP-222", "mortalidad-infantil-rural-40-urbana-15-determinantes-inequidad-salud",
  "Mortalidad infantil de 40 rural frente a 15 urbana por pobreza y falta de servicios: inequidad en salud",
  "Determinantes sociales · equidad", ESP,
  ("Desigualdad e inequidad", ["Desigualdad: cualquier diferencia medible.",
                               "Inequidad: diferencia evitable, injusta y de origen social."]),
  ("Región de la selva", ["Mortalidad infantil 40 por mil en zonas rurales pobres sin agua segura ni servicios.",
                          "15 por mil en zonas urbanas con mejores servicios."]),
  ["Diferencia de origen social, evitable e injusta = inequidad en salud.",
   "«Desigualdad» solo describe la diferencia, sin juicio de justicia.",
   "No es variación biológica: los niños no difieren biológicamente."],
  "OMS, Comisión sobre Determinantes Sociales de la Salud (2008); Whitehead (1990).",
  d=dict(rotulo="¿Es una inequidad?", tag="ESTE CASO",
         lista_titulo="Criterios",
         items=[("Diferencia medible", True, "40 frente a 15 por mil"),
                ("Origen social", True, "Pobreza, agua, servicios"),
                ("Evitable", True, "Con agua y servicios se reduce"),
                ("Injusta", True, "Depende de dónde se nace"),
                ("Explicada por la biología", False, "No hay diferencia biológica")],
         umbral="evitable + injusta + social", veredicto="Inequidad en salud",
         img_titulo="Mortalidad infantil", img=D(lambda s, x, y: I.lab_barras(s, x - 20, y + 30, [("Rural pobre", "40 por mil", 40, True),
                                                                                                ("Urbana", "15 por mil", 15, False)],
                                                                             W=250, xmax=45, titulo="por 1000 nacidos vivos", ref=None), 230, 120),
         img_pie="Casi tres veces más en zonas rurales pobres.",
         claves_titulo="Por qué no las otras",
         claves=[("Desigualdad", ["Describe pero no juzga la injusticia."], False),
                 ("Variación biológica", ["No explica la diferencia."], False),
                 ("Lo correcto", ["Inequidad."], True)]),
  tabla=("Opciones de la pregunta", [("Inequidad", True), ("Variación biológica", False), ("Desigualdad", False), ("Diferencia", False)],
         [("¿Correcto?", ["Sí", "No", "Incompleto", "Muy general"])]))

# SP-223 · Determinantes estructurales · TARJETAS + franja
S("tarjetas", "SP-223", "marco-oms-determinantes-estructurales-posicion-economica-genero-etnia",
  "Posición económica, género y etnia: determinantes estructurales de la salud",
  "Determinantes sociales · marco de la OMS", ESP,
  ("Marco de la OMS", ["Estructurales: definen la posición social (ingresos, educación, ocupación, género, etnia).",
                       "Intermedios: condiciones de vida, conductas, factores psicosociales y sistema de salud."]),
  ("Pregunta de concepto", ["¿Qué ejemplo es un determinante social estructural?"]),
  ["Posición económica, género y pertenencia étnica = estructurales.",
   "Servicios de salud, ambiente, alimentación y actividad física = intermedios.",
   "Los estructurales generan las desigualdades de fondo."],
  "OMS, marco conceptual de los determinantes sociales (Solar e Irwin, 2010).",
  d=dict(rotulo="Cuatro ejemplos", ans=0,
         cards=[dict(titulo="Posición económica, género, etnia", datos=[("Nivel", "Estructural", True), ("Define", "Posición social", True),
                                                                     ("Actúa", "En el fondo", True)], pie="Este caso."),
                dict(titulo="Servicios de salud y vacunas", datos=[("Nivel", "Intermedio", False), ("Tipo", "Sistema de salud", False),
                                                                   ("Actúa", "Cercano", False)], pie="Intermedio."),
                dict(titulo="Aire, agua, tóxicos", datos=[("Nivel", "Intermedio", False), ("Tipo", "Condiciones materiales", False),
                                                          ("Actúa", "Cercano", False)], pie="Intermedio."),
                dict(titulo="Alimentación y actividad física", datos=[("Nivel", "Intermedio", False), ("Tipo", "Conductas", False),
                                                                      ("Actúa", "Individual", False)], pie="Intermedio.")]),
  banda=B("Niveles de determinantes (esquema)", D(lambda s, x, y: J.determinantes(s, x, y, sc=0.95), 323, 214),
          ["Arriba: estructurales (posición social).", "En medio: intermedios (condiciones de vida).", "Abajo: el resultado en salud."], ans=0),
  tabla=("Opciones de la pregunta", [("Servicios y vacunas", False), ("Contaminación y agua", False), ("Alimentación y actividad", False),
                                     ("Posición económica, género, etnia", True)],
         [("Nivel", ["Intermedio", "Intermedio", "Intermedio", "Estructural"])]))

# SP-224 · Categoría mínima con internamiento general: II-1 · RED + franja
S("red", "SP-224", "norma-tecnica-categoria-minima-internamiento-general-ii-1",
  "Categoría mínima con camas de internamiento general: II-1",
  "Sistema de salud · categorización de establecimientos", ESP,
  ("Internamiento por categoría", ["El primer nivel (I-1 a I-4) es ambulatorio; el I-4 solo tiene internamiento de corta estancia (materno-perinatal).",
                                   "El internamiento general empieza en el segundo nivel: II-1."]),
  ("Pregunta de norma", ["¿Cuál es la categoría mínima autorizada para camas de internamiento general?"]),
  ["II-1: hospital con las cuatro especialidades básicas e internamiento general.",
   "El I-4 tiene camas, pero de internamiento limitado (parto, observación).",
   "I-2 e I-3 no tienen internamiento."],
  MINSA + ", NTS de categorías de establecimientos del sector salud.",
  d=dict(rotulo="Dónde empieza el internamiento general", caso="II-1", tag="ESTE CASO",
         claves=[("II-1", ["Primer nivel con internamiento general."], True),
                 ("I-4", ["Internamiento limitado (parto, corta estancia)."], False),
                 ("I-2 e I-3", ["Sin internamiento."], False)]),
  banda=B("Qué tiene cada categoría", D(lambda s, x, y: J.flujo_bloques(s, x, y, [("I-2 / I-3", "ambulatorio, sin camas"),
                                                                                ("I-4", "camas de corta estancia"),
                                                                                ("II-1", "internamiento general")], W=320, caso=2), 320, 166),
          ["El primer nivel atiende ambulatorio.", "El I-4 tiene camas limitadas.", "El II-1 ya hospitaliza de forma general."], ans=2),
  tabla=("Opciones de la pregunta", [("I-2", False), ("II-1", True), ("I-4", False), ("I-3", False)],
         [("¿Internamiento general?", ["No", "Sí", "Limitado", "No"])]))

# SP-225 · Mala conducta científica · CRITERIOS
S("criterios", "SP-225", "investigador-modifica-resultados-financiador-mala-conducta-cientifica",
  "Modificar a propósito los resultados para complacer al financiador: mala conducta científica",
  "Ética de la investigación · integridad científica", ESP,
  ("Integridad científica", ["Mala conducta: fabricación, falsificación o plagio (FFP).",
                             "Prácticas cuestionables: errores menos graves (p. ej., mal registro)."]),
  ("Médico investigador", ["Cambia deliberadamente los resultados de su estudio para cumplir las expectativas del financiador."]),
  ["Falsificar datos de forma deliberada = mala conducta científica (falta grave).",
   "El conflicto de intereses es la situación de riesgo; aquí ya se consumó la falta.",
   "No es una práctica cuestionable menor ni algo aceptable."],
  "CONCYTEC, código nacional de integridad científica; ORI (EE. UU.).",
  d=dict(rotulo="¿Es mala conducta científica?", tag="ESTE CASO",
         lista_titulo="Lo que hizo",
         items=[("Alteró los resultados", True, "Falsificación"),
                ("Lo hizo a propósito", True, "«Deliberadamente»"),
                ("Para un beneficio externo", True, "Complacer al financiador"),
                ("Fue un error sin intención", False, "No: fue deliberado"),
                ("Solo había un interés en juego", False, "Ya actuó en contra de la verdad")],
         umbral="falsificar a propósito", veredicto="Mala conducta científica (falsificación)",
         img_titulo="Las faltas graves (FFP)", img=D(lambda s, x, y: J.flujo_bloques(s, x - 25, y + 10, [("Fabricación", "inventar datos"),
                                                                                                        ("Falsificación", "alterar resultados"),
                                                                                                        ("Plagio", "copiar sin citar")], W=260, caso=1), 230, 180),
         img_pie="Este caso es falsificación.",
         claves_titulo="Por qué no las otras",
         claves=[("Conflicto de intereses", ["Es el riesgo, no el acto."], False),
                 ("Práctica cuestionable", ["Es menos grave y sin intención clara."], False),
                 ("Lo correcto", ["Mala conducta científica."], True)]),
  tabla=("Opciones de la pregunta", [("Práctica aceptable", False), ("Mala conducta científica", True), ("Conflicto de intereses", False),
                                     ("Práctica cuestionable", False)],
         [("¿Correcto?", ["Nunca", "Sí", "Es el contexto", "Menos grave"])]))

# SP-226 · Cartera de servicios · EMBUDO + franja
S("embudo", "SP-226", "definicion-cartera-servicios-prestaciones-necesidades-poblacion",
  "Cartera de servicios: prestaciones que ofrece el establecimiento según las necesidades y prioridades de su población",
  "Gestión · organización de servicios", ESP,
  ("Cartera de servicios", ["Conjunto de prestaciones de salud que brinda un establecimiento.",
                            "Se define según las necesidades de la población y las prioridades sanitarias."]),
  ("Pregunta de norma", ["¿Qué definición describe mejor la cartera de servicios?"]),
  ["Cartera de servicios = conjunto de prestaciones que responde a necesidades y prioridades.",
   "No es el registro de atenciones, ni el listado diario de insumos, ni el horario del personal.",
   "Depende de la categoría del establecimiento."],
  MINSA + ", NTS de cartera de servicios de salud.",
  d=dict(rotulo="De la pregunta a la definición", inicio="¿Qué es la cartera de servicios?",
         candidatos=["Registro de atenciones", "Listado de insumos diarios", "Documento de horarios", "Conjunto de prestaciones"],
         pasos=[("¿Mide lo que ya se hizo?", ["Registro de atenciones"]),
                ("¿Es lo disponible para el día?", ["Listado de insumos diarios"]),
                ("¿Organiza al personal?", ["Documento de horarios"])],
         final=("Conjunto de prestaciones", ["Según necesidades y prioridades"]),
         nota="La cartera dice qué ofrece el establecimiento y por qué."),
  banda=B("Cómo se construye", D(lambda s, x, y: J.flujo_bloques(s, x, y, [("Necesidades de la población", "ASIS, demanda"),
                                                                         ("Prioridades sanitarias", "nacionales y regionales"),
                                                                         ("Cartera de servicios", "prestaciones que se ofrecen")], W=320, caso=2), 320, 166),
          ["Se parte de lo que necesita la población.", "Se suman las prioridades sanitarias.", "Resulta la cartera de prestaciones."]),
  tabla=("Opciones de la pregunta", [("Registro de atenciones", False), ("Conjunto de prestaciones", True), ("Listado diario", False),
                                     ("Horarios y personal", False)],
         [("¿Es la cartera?", ["No", "Sí", "No", "No"])]))

# SP-227 · Serie de casos · ÁRBOL + franja
S("arbol", "SP-227", "pacientes-enfermedad-rara-descripcion-sin-grupo-comparacion-serie-casos",
  "Describir a todos los pacientes con una enfermedad rara sin grupo de comparación: serie de casos",
  "Investigación · diseños de estudio", ESP,
  ("Diseños de estudio", ["Descriptivos: reporte o serie de casos, transversal descriptivo.",
                          "Analíticos: tienen grupo de comparación (cohorte, casos y controles, ensayo)."]),
  ("Hospital de referencia", ["Registra durante un año a todos los pacientes con una enfermedad rara.",
                              "Describe clínica, evolución y tratamientos; sin intervención asignada ni grupo de comparación."]),
  ["Varios pacientes descritos sin grupo de comparación = serie de casos.",
   "Si el investigador asignara el tratamiento: ensayo clínico.",
   "Si comparara expuestos y no expuestos: cohorte o transversal analítico."],
  GORDIS + ".",
  arbol=Q("¿El investigador asigna la intervención?", [
      L("Sí", "Ensayo clínico", ["Experimental"]),
      Q("¿Hay grupo de comparación?", [
          L("Sí", "Estudio analítico", ["Cohorte, casos y controles, transversal analítico"]),
          L("No", "SERIE DE CASOS", ["Descriptivo", "Varios pacientes con la misma enfermedad"], path=True)],
        edge="No", path=True)], path=True),
  banda=B("Qué hace el estudio", D(lambda s, x, y: J.flujo_bloques(s, x, y, [("Pacientes con la enfermedad rara", "todos los del año"),
                                                                           ("Se describen", "clínica, evolución, tratamiento"),
                                                                           ("Sin grupo control", "no se compara")], W=320, caso=2), 320, 166),
          ["Solo un grupo: los enfermos.", "Se describe lo que pasó.", "Sin comparación no hay asociación causal."], ans=2),
  tabla=("Opciones de la pregunta", [("Serie de casos", True), ("Clínico controlado", False), ("Cohorte analítico", False), ("Transversal analítico", False)],
         [("¿Encaja?", ["Sí", "No: no asigna", "No: sin comparación", "No: sin comparación"])]))

# SP-228 · Dotación de un I-3 · MATRIZ + franja
S("matriz", "SP-228", "norma-tecnica-establecimiento-i-3-dotacion-minima-dos-medicos-generales",
  "Dotación mínima de médicos en un establecimiento I-3: dos médicos generales",
  "Sistema de salud · recursos humanos por categoría", ESP,
  ("Recursos humanos por categoría", ["El primer nivel trabaja con médicos generales; los especialistas están en el segundo y tercero.",
                                      "La dotación crece con la categoría."]),
  ("Pregunta de norma", ["¿Cuál es la dotación mínima de médicos de un I-3?"]),
  ["I-3 (centro de salud sin internamiento): dos médicos generales.",
   "I-2: un médico general; I-1: sin médico.",
   "Internistas, gineco-obstetras o pediatras corresponden a niveles mayores."],
  MINSA + ", NTS de categorías de establecimientos del sector salud.",
  d=dict(rotulo="Categoría y médicos", eje_x="Recurso", eje_y="Categoría", caso=(2, 0),
         cols=["Médicos", "Internamiento"],
         rows=["I-1", "I-2", "I-3", "I-4"],
         cells=[[("Sin médico", ["Técnico o profesional no médico"]), ("No", ["Ambulatorio"])],
                [("1 médico general", ["Puesto con médico"]), ("No", ["Ambulatorio"])],
                [("2 médicos generales", ["Este caso"]), ("No", ["Ambulatorio"])],
                [("Generales y algún especialista", ["Según norma"]), ("Corta estancia", ["Parto, observación"])]]),
  banda=B("Primer nivel: médicos generales", D(lambda s, x, y: J.flujo_bloques(s, x, y, [("I-1: puesto de salud", "sin médico"),
                                                                                     ("I-2: puesto con médico", "1 médico general"),
                                                                                     ("I-3: centro de salud", "2 médicos generales")], W=320, caso=2), 320, 166),
          ["La dotación sube con la categoría.", "El I-3 necesita al menos 2 médicos generales.", "Los especialistas están en hospitales."], ans=1),
  tabla=("Opciones de la pregunta", [("Internista + general", False), ("Dos médicos generales", True), ("General + gineco-obstetra", False),
                                     ("General + pediatra", False)],
         [("¿Correcto para I-3?", ["No", "Sí", "No", "No"])]))

# SP-229 · Proceso salud-enfermedad · RADIAL + franja
S("radial", "SP-229", "proceso-salud-enfermedad-dinamico-continuo-biopsicosocial",
  "El proceso salud-enfermedad es dinámico, continuo y biopsicosocial",
  "Salud pública · conceptos", ESP,
  ("Proceso salud-enfermedad", ["No es un estado fijo: la persona se mueve entre salud y enfermedad durante la vida.",
                                "Depende de factores biológicos, psicológicos y sociales y del entorno."]),
  ("Pregunta de concepto", ["¿Qué opción define mejor el proceso salud-enfermedad como fenómeno dinámico?"]),
  ["Proceso cambiante y continuo, resultado de la interacción biológica, psicológica y social con el entorno.",
   "La definición de la OMS (1948) habla de un «estado» de completo bienestar: es estática.",
   "«Ausencia de enfermedad» es una visión biomédica reducida."],
  "OMS (1948); Engel, modelo biopsicosocial (1977).",
  d=dict(rotulo="Las cuatro definiciones frente al concepto", ans=0, centro="¿Qué es el proceso salud-enfermedad?",
         items=[("Cambiante, continuo y biopsicosocial", ["Proceso dinámico: este caso"]),
                ("Sentirse bien sin alteraciones", ["Visión subjetiva y estática"]),
                ("Completo bienestar (OMS 1948)", ["Habla de un «estado»"]),
                ("Ausencia de enfermedad", ["Visión biomédica"])],
         ruta=["Salud", "Factores biológicos", "Psicológicos y sociales", "Se mueve en un continuo"]),
  banda=B("Continuo salud-enfermedad (esquema)", D(lambda s, x, y: J.continuo(s, x, y, sc=0.9), 324, 135),
          ["La persona se mueve entre salud y enfermedad.", "No es un punto fijo.", "Influyen lo biológico, lo psicológico y lo social."], ans=0),
  tabla=("Opciones de la pregunta", [("Sentirse bien", False), ("Cambiante y biopsicosocial", True), ("Completo bienestar", False), ("Ausencia de enfermedad", False)],
         [("¿Es dinámico?", ["No", "Sí", "No: es un estado", "No"])]))

# SP-230 · t de Student · ÁRBOL + franja
S("arbol", "SP-230", "comparar-imc-dos-centros-salud-normal-homocedasticidad-t-student-independientes",
  "Comparar el IMC promedio de dos grupos independientes con datos normales: t de Student",
  "Bioestadística · elección de la prueba", ESP,
  ("Elegir la prueba estadística", ["Tipo de variable, número de grupos, si son independientes y si la distribución es normal.",
                                    "Numérica + 2 grupos independientes + normal = t de Student."]),
  ("Centros de salud A y B", ["IMC de 30 personas en cada centro.", "Distribución normal y varianzas iguales."]),
  ["IMC numérico, 2 grupos independientes, normalidad y homocedasticidad: t de Student para muestras independientes.",
   "Kolmogorov-Smirnov solo prueba si los datos son normales.",
   "Chi cuadrado compara proporciones (variables categóricas)."],
  GORDIS + "; Dawson-Trapp, Bioestadística médica.",
  arbol=Q("¿La variable es numérica (como el IMC)?", [
      L("No: categórica", "Chi cuadrado", ["Compara proporciones"]),
      Q("¿Dos grupos independientes con distribución normal?", [
          L("No normal", "U de Mann-Whitney", ["No paramétrica"]),
          L("Sí", "T DE STUDENT INDEPENDIENTE", ["Compara las medias de A y B"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("Dos grupos (esquema)", D(lambda s, x, y: J.campanas(s, x, y, sc=0.9), 324, 172),
          ["Dos curvas normales: centros A y B.", "Se comparan sus medias.", "Grupos distintos de personas: independientes."], ans=1),
  tabla=("Opciones de la pregunta", [("Kolmogorov-Smirnov", False), ("t de Student independiente", True), ("Chi cuadrado", False),
                                     ("Análisis multivariado", False)],
         [("Sirve para", ["Probar normalidad", "Comparar 2 medias", "Proporciones", "Muchas variables"])]))
