"""Bloque ENAM 2026 · Endocrinología, Hematología e Infectología."""
from c26 import S, D, P, B, ILU, Q, L, HARRISON, MINSA
from engine7 import _img_draw
import ilu7 as I

O = I.ORANGE
EE, EH, EI = "ENDOCRINOLOGÍA ENAM", "HEMATOLOGÍA ENAM", "INFECTOLOGÍA ENAM"
ATA = "ATA, hipertiroidismo (2016)"
CDC = "CDC, guía de ITS (2021)"
OPS = "OPS, guía de dengue (2016)"

# END-069 · Graves: TRAb · RADIAL + franja
_graves = I.E(120, 72, 20, 8, "#fda4af", "#be123c", 2)
S("radial", "END-069", "mujer-25-anos-tirotoxicosis-bocio-difuso-exoftalmos-trab-graves",
  "Tirotoxicosis con bocio difuso y exoftalmos: los TRAb confirman la enfermedad de Graves",
  "Tiroides · hipertiroidismo", EE,
  ("Enfermedad de Graves", ["Anticuerpos que estimulan el receptor de TSH (TRAb): la tiroides trabaja sin freno.",
                            "Bocio difuso y oftalmopatía la distinguen de otras causas de hipertiroidismo."]),
  ("Mujer de 25 años", ["3 meses de baja de peso, palpitaciones, intolerancia al calor y nerviosismo.",
                        "FC 110, temblor fino, bocio difuso blando y exoftalmos bilateral."]),
  ["TSH y T4 libre confirman el hipertiroidismo; los TRAb confirman que la causa es Graves.",
   "La gammagrafía queda para cuando la causa no está clara o no hay TRAb disponibles.",
   "La eco Doppler muestra mucho flujo, pero no es específica."],
  ATA + "; ETA (2018).",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="¿Qué confirma que es Graves?",
         items=[("Anticuerpos TRAb", ["Específicos: confirman la causa"]),
                ("TSH y T4 libre", ["Confirman hipertiroidismo, no la causa"]),
                ("Gammagrafía con yodo", ["Si la causa no es clara"]),
                ("Eco Doppler", ["Apoya, pero no es específica"])],
         ruta=["Síntomas de tirotoxicosis", "TSH baja, T4L alta", "Bocio difuso + exoftalmos", "TRAb positivos: Graves"]),
  banda=B("La paciente", D(lambda s, x, y: I.cuerpo(s, x + 40, y, extra=_graves, marcas=[(1, 136, 30), (2, 146, 74), (3, 37, 250)], sc=0.7), 250, 312),
          ["Exoftalmos: propio de Graves.", "Bocio difuso blando (todo el tiroides crece).", "Temblor fino distal."], ans=0),
  tabla=("Opciones de la pregunta", [("TRAb", True), ("TSH y T4 libre", False), ("Gammagrafía", False), ("Eco Doppler", False)],
         [("¿Confirma Graves?", ["Sí", "Solo el hipertiroidismo", "Si hay dudas", "No específica"])]))

# END-070 · Graves refractario con bocio compresivo · MATRIZ + franja
S("matriz", "END-070", "graves-refractario-bocio-compresivo-oftalmopatia-tiroidectomia-total",
  "Graves que no cede con metimazol, bocio que comprime la tráquea y oftalmopatía activa: tiroidectomía total",
  "Tiroides · tratamiento definitivo del Graves", EE,
  ("Tratamiento definitivo del Graves", ["Opciones: antitiroideos, yodo radiactivo o cirugía.",
                                         "Bocio grande compresivo u oftalmopatía activa favorecen la cirugía."]),
  ("Mujer de 40 años con Graves de 12 meses", ["Metimazol 30 mg y propranolol bien tomados; sigue hipertiroidea.",
                                               "Ahogo al acostarse, bocio grado III con compresión traqueal, oftalmopatía activa."]),
  ["Refractario + bocio compresivo + oftalmopatía activa = tiroidectomía total.",
   "Antes: llevar a eutiroidismo con metimazol y dar yoduro (Lugol) unos días.",
   "El yodo radiactivo puede empeorar la oftalmopatía activa y no alivia rápido la compresión."],
  ATA + "; ETA (2018); EUGOGO (2021).",
  d=dict(rotulo="Situación y tratamiento", eje_x="Tratamiento", eje_y="Situación", caso=(3, 2),
         cols=["Antitiroideo", "Yodo radiactivo", "Tiroidectomía total"],
         rows=["Primer episodio, bocio pequeño", "Recaída sin oftalmopatía", "Oftalmopatía activa", "Bocio compresivo o refractario"],
         cells=[[("Elección", ["12-18 meses de metimazol"]), ("Alternativa", ["Si prefiere algo definitivo"]), ("No de entrada", ["Salvo otra indicación"])],
                [("Puede repetirse", ["Recae con frecuencia"]), ("Buena opción", ["Definitivo y simple"]), ("Alternativa", ["Según preferencia"])],
                [("Mientras tanto", ["Controla la función"]), ("Evitar", ["Puede empeorar los ojos"]), ("Preferida", ["No empeora la oftalmopatía"])],
                [("No basta", ["No quita la compresión"]), ("Lento", ["El bocio grande responde mal"]), ("Elección", ["Este caso"])]]),
  banda=B("Cuello de la paciente (esquema)", D(lambda s, x, y: I.cuello_bocio(s, x, y, True, sc=0.95), 290, 220),
          ["Bocio grado III que rodea la tráquea.", "La tráquea se aplasta: ahogo al acostarse.", "Ninguna pastilla quita esa compresión."], ans=1),
  tabla=("Opciones de la pregunta", [("Agregar propiltiouracilo", False), ("Subir metimazol", False), ("Tiroidectomía total", True),
                                     ("Yodo radiactivo", False)],
         [("Problema", ["No se combinan dos antitiroideos", "No quita la compresión", "Ninguno", "Empeora la oftalmopatía activa"])]))

# END-071 · Hipotiroidismo por Hashimoto en adulto mayor · SEMÁFORO
S("semaforo", "END-071", "varon-70-anos-tsh-22-t4-baja-anti-tpo-hashimoto-levotiroxina",
  "Adulto mayor con TSH 22, T4 libre baja y anti-TPO positivos: levotiroxina a dosis ajustada",
  "Tiroides · hipotiroidismo", EE,
  ("Hipotiroidismo primario", ["La tiroides falla: T4 libre baja y TSH alta.",
                               "La causa más frecuente es la tiroiditis de Hashimoto (anti-TPO positivos)."]),
  ("Varón de 70 años del altiplano", ["9 meses de cansancio, aumento de peso, frío y estreñimiento.",
                                      "FC 50, reflejos con relajación lenta; TSH 22, T4 libre 0,2, anti-TPO altos."]),
  ["Hipotiroidismo franco por Hashimoto: tratar con levotiroxina.",
   "En el adulto mayor (o con cardiopatía) se empieza bajo, 25-50 µg/día, y se sube cada 4-6 semanas según la TSH.",
   "No atribuirlo a la edad; la bradicardia se corrige al tratar la causa."],
  "ATA, hipotiroidismo (2014); " + HARRISON + ".",
  d=dict(rotulo="Laboratorio del caso y semáforo de conducta",
         ilu_titulo="Laboratorio (veces el límite normal)",
         ilu=ILU(D(lambda s, x, y: I.lab_barras(s, x - 6, y + 50, [("TSH", "22: casi 5 veces", 4.9, True), ("T4 libre", "0,2: un cuarto", 0.25, True)],
                                                 W=280, xmax=6, titulo="Veces el límite normal"), 270, 200)),
         ilu_pie="TSH muy alta y T4 libre muy baja: falla de la tiroides.",
         check_titulo="Datos del caso",
         check=[("TSH 22 y T4 libre baja", False), ("Anti-TPO positivos: Hashimoto", False),
                ("Bradicardia y reflejos lentos", False), ("Consciente, sin hipotermia ni coma", True)],
         ans=1, tag="ESTE CASO",
         luces=[("TSH alta con T4 normal", "Subclínico", ["Vigilar o tratar según la TSH y los síntomas."]),
                ("Hipotiroidismo franco", "Levotiroxina a dosis baja", ["Adulto mayor: 25-50 µg/día y subir cada 4-6 semanas."]),
                ("Coma mixedematoso", "Emergencia", ["Levotiroxina EV + hidrocortisona en UCI."])]),
  tabla=("Opciones de la pregunta", [("Orciprenalina", False), ("Es la edad", False), ("Levotiroxina ajustada", True), ("Eco y postergar", False)],
         [("Problema", ["No trata la causa", "Falso", "Ninguno", "Retrasa un tratamiento indicado"])]))

# END-072 · Cetoacidosis diabética · CRITERIOS
_kuss = I.P("M120 92 C96 104 96 126 120 136 C144 126 144 104 120 92", "none", "#0284c7", 2, 'stroke-dasharray="4 3"')
S("criterios", "END-072", "glucosa-360-ph-7-02-bicarbonato-9-cetonas-cetoacidosis-diabetica",
  "Glucosa 360, pH 7,02, bicarbonato 9 y cetonas: cetoacidosis diabética con anión gap alto",
  "Diabetes · emergencias hiperglucémicas", EE,
  ("Cetoacidosis diabética (CAD)", ["Falta insulina: se queman grasas y se forman cetoácidos.",
                                    "Hiperglucemia + cetosis + acidosis metabólica con anión gap elevado."]),
  ("Varón de 48 años", ["24 h de dolor abdominal, náuseas, poliuria y polidipsia; respiración profunda y rápida.",
                        "Glucosa 360, pH 7,02, HCO₃ 9, Na 135, K 4,5; cetonas en orina ++."]),
  ["Glucosa > 250 + pH < 7,30 + HCO₃ < 18 + cetonas = CAD; con HCO₃ < 10 es grave.",
   "Los cetoácidos elevan el anión gap (para calcularlo hace falta el cloro).",
   "Tratamiento: fluidos, insulina EV y potasio (con K 4,5 se repone junto con la insulina)."],
  "ADA, crisis hiperglucémicas (2024); " + HARRISON + ".",
  d=dict(rotulo="¿Cumple criterios de cetoacidosis?", tag="ESTE CASO",
         lista_titulo="Criterios (ADA)",
         items=[("Glucosa > 250 mg/dL", True, "360"),
                ("pH < 7,30", True, "7,02"),
                ("Bicarbonato < 18 mEq/L", True, "9 (< 10: grave)"),
                ("Cetonas positivas", True, "Orina ++"),
                ("Osmolaridad > 320 sin cetosis (hiperosmolar)", False, "≈ 2 × 135 + 360/18 = 290")],
         umbral="los 4 primeros", veredicto="Cetoacidosis diabética grave con anión gap alto",
         img_titulo="El paciente", img=D(lambda s, x, y: I.cuerpo(s, x + 18, y, {"abdomen": "#fed7aa"}, extra=_kuss,
                                                                  marcas=[(1, 150, 112), (2, 120, 210)], sc=0.7), 230, 312),
         img_pie="1 respiración de Kussmaul; 2 dolor abdominal.",
         claves_titulo="Por qué no las otras",
         claves=[("Estado hiperosmolar", ["Osmolaridad 290 y hay cetosis: no."], False),
                 ("Acidosis láctica o renal", ["Normotenso, sin falla renal descrita; hay cetonas."], False),
                 ("Lo correcto", ["Cetoacidosis diabética."], True)]),
  tabla=("Opciones de la pregunta", [("Acidosis por ERC", False), ("Acidosis láctica", False), ("Hiperosmolar", False), ("Cetoacidosis diabética", True)],
         [("¿Encaja?", ["No: sin ERC", "No: sin hipoperfusión", "No: osmolaridad 290", "Sí"])]))

# HEM-042 · Crisis vasooclusiva · CICLO
S("ciclo", "HEM-042", "adolescente-drepanocitosis-dolor-oseo-tras-ejercicio-crisis-vasooclusiva",
  "Drepanocitosis con dolor óseo intenso tras ejercicio: crisis vasooclusiva",
  "Hemoglobinopatías · anemia falciforme", EH,
  ("Crisis vasooclusiva", ["La hemoglobina S se polimeriza con poco oxígeno o deshidratación.",
                           "Los glóbulos en hoz tapan los capilares: isquemia y dolor en huesos, tórax o abdomen."]),
  ("Adolescente de 13 años con anemia falciforme", ["24 h de dolor intenso en extremidades y espalda tras ejercicio fuerte.",
                                                    "Pálido, ictérico; Hb 8, reticulocitos 5 %, bilirrubina indirecta 3."]),
  ["Dolor óseo agudo tras un desencadenante en drepanocitosis = crisis vasooclusiva.",
   "Tratamiento: analgesia potente (opioides), hidratación, oxígeno si hay hipoxemia.",
   "Reticulocitos de 5 %: no es crisis aplásica (ahí estarían muy bajos)."],
  "NHLBI, enfermedad de células falciformes (2014); ASH (2020).",
  d=dict(rotulo="Cómo se produce el dolor", tag="ESTE CASO",
         img_titulo="Frotis (esquema)",
         img=D(lambda s, x, y: I.frotis(s, x - 10, y + 30, "drepanocitos", sc=0.95), 280, 260),
         img_pie="Glóbulos rojos en forma de hoz (drepanocitos).",
         centro="Crisis vasooclusiva", ans=3,
         pasos=[("Desencadenante", "ejercicio, deshidratación"), ("HbS se polimeriza", "con poco oxígeno"),
                ("Glóbulo en hoz", "rígido"), ("Obstruye microvasos", "isquemia ósea"), ("Dolor intenso", "huesos y espalda")],
         claves_titulo="Por qué no las otras",
         claves=[("Crisis aplásica", ["Reticulocitos casi en cero; aquí 5 %."], False),
                 ("Hemofagocítico", ["Fiebre, citopenias, ferritina alta."], False),
                 ("Rabdomiólisis", ["Dolor muscular y orina oscura; CK alta."], False)]),
  tabla=("Opciones de la pregunta", [("Crisis aplásica", False), ("Hemofagocítico", False), ("Rabdomiólisis", False), ("Crisis vasooclusiva", True)],
         [("¿Explica el cuadro?", ["No: reticulocitos altos", "No", "No", "Sí"])]))

# HEM-043 · LMC: BCR-ABL1 · TARJETAS + franja
S("tarjetas", "HEM-043", "leucocitosis-130000-mielocitos-esplenomegalia-leucemia-mieloide-cronica-bcr-abl1",
  "Leucocitosis con todas las etapas mieloides y esplenomegalia: leucemia mieloide crónica, BCR-ABL1",
  "Neoplasias mieloides · leucemia mieloide crónica", EH,
  ("Leucemia mieloide crónica (LMC)", ["Neoplasia por la translocación t(9;22): cromosoma Filadelfia y gen BCR-ABL1.",
                                       "La proteína BCR-ABL es una tirosina cinasa siempre activa: blanco del imatinib."]),
  ("Varón de 45 años", ["Fatiga y plenitud abdominal; bazo 6 cm bajo el reborde.",
                        "Leucocitos 130 000 con neutrófilos y mielocitos, plaquetas 600 000, pocos blastos."]),
  ["Leucocitosis con todas las etapas de maduración + esplenomegalia + pocos blastos = LMC en fase crónica.",
   "Se confirma con t(9;22) en el cariotipo o BCR-ABL1 por PCR.",
   "Tratamiento: inhibidor de tirosina cinasa (imatinib y otros)."],
  "ELN, leucemia mieloide crónica (2020); NCCN (2025).",
  d=dict(rotulo="Cuatro alteraciones posibles", ans=0,
         cards=[dict(titulo="t(9;22) BCR-ABL1", datos=[("Sangre", "Todas las etapas", True), ("Bazo", "Grande", True),
                                                       ("Tratamiento", "Imatinib (ITK)", True)], pie="Leucemia mieloide crónica."),
                dict(titulo="Deleción 5q", datos=[("Sangre", "Anemia macrocítica", False), ("Leucocitos", "Normales o bajos", False),
                                                  ("Enfermedad", "Mielodisplasia", False)], pie="Más en mujeres mayores."),
                dict(titulo="t(15;17) PML-RARA", datos=[("Sangre", "Promielocitos", False), ("Curso", "Agudo, con CID", False),
                                                        ("Tratamiento", "ATRA", False)], pie="Leucemia promielocítica."),
                dict(titulo="JAK2 V617F", datos=[("Clave", "Policitemia o trombocitemia", False), ("Leucocitos", "Aumento leve", False),
                                                 ("BCR-ABL1", "Negativo", False)], pie="Otras neoplasias mieloproliferativas.")]),
  banda=B("Translocación t(9;22) (esquema)", D(lambda s, x, y: I.filadelfia(s, x, y, sc=0.95), 345, 192),
          ["El ABL del cromosoma 9 pasa al 22.", "El 22 que queda corto es el cromosoma Filadelfia.", "Allí se forma el gen de fusión BCR-ABL1."], ans=2),
  tabla=("Opciones de la pregunta", [("Deleción 5q", False), ("t(9;22) BCR-ABL1", True), ("t(15;17) PML-RARA", False), ("JAK2 V617F", False)],
         [("Enfermedad", ["Mielodisplasia", "LMC: este caso", "Promielocítica", "Policitemia, trombocitemia"])]))

# HEM-044 · von Willebrand · ÁRBOL + franja
S("arbol", "HEM-044", "sangrado-dental-menorragia-familia-plaquetas-tp-ttpa-normales-cofactor-ristocetina",
  "Sangrado mucoso con plaquetas, TP y TTPa normales e historia familiar: cofactor de ristocetina",
  "Trastornos de la hemostasia · enfermedad de von Willebrand", EH,
  ("Enfermedad de von Willebrand", ["El trastorno hemorrágico hereditario más frecuente; autosómico (hombres y mujeres).",
                                    "Sangrado de mucosas: encías, nariz, menstruación, tras extracciones."]),
  ("Adolescente de 17 años", ["Sangrado del alvéolo dental 7 días tras extracción; menorragia desde la menarquia.",
                              "Familiares maternos (mujeres y varones) sangran; plaquetas 400 000, TP y TTPa normales."]),
  ["Sangrado mucocutáneo + familia afectada de ambos sexos + plaquetas y TP normales = sospechar von Willebrand.",
   "El TTPa puede ser normal en la forma leve: pedir actividad del cofactor de ristocetina, antígeno vWF y FVIII.",
   "Los factores VII y IX y los inhibidores no explican este patrón."],
  "ASH/ISTH/NHF/WFH, von Willebrand (2021).",
  arbol=Q("¿Plaquetas normales?", [
      L("No", "Trombocitopenia", ["Estudiar la causa"]),
      Q("¿TP y TTPa normales?", [
          L("No: TTPa largo", "Hemofilia o vW grave", ["Dosar FVIII y FIX"]),
          L("Sí: este caso", "PENSAR EN VON WILLEBRAND", ["Cofactor de ristocetina", "Antígeno vWF y FVIII"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("Qué hace el factor de von Willebrand", D(lambda s, x, y: I.vwf(s, x, y, sc=0.9), 324, 180),
          ["Une la plaqueta al colágeno del vaso lesionado.", "Si falta, la plaqueta no se pega: sangrado de mucosas.",
           "La ristocetina mide esa función en el laboratorio."], ans=2),
  tabla=("Opciones de la pregunta", [("Factor VII", False), ("Cofactor de ristocetina", True), ("Factor IX", False), ("Inhibidor del FVIII", False)],
         [("Problema", ["Daría TP largo", "Ninguno", "Hemofilia B: varones y TTPa largo", "TTPa largo"])]))

# HEM-045 · Anemia hemolítica autoinmune · ESCALERA
S("escalera", "HEM-045", "hb-7-reticulocitos-coombs-directo-positivo-anemia-hemolitica-autoinmune-corticoide",
  "Anemia hemolítica con Coombs directo positivo: corticoide como tratamiento inicial",
  "Anemias hemolíticas · autoinmune", EH,
  ("Anemia hemolítica autoinmune (AHAI) por anticuerpos calientes", ["Anticuerpos IgG cubren los glóbulos rojos y el bazo los destruye.",
                                                                     "Coombs directo positivo; esferocitos en el frotis."]),
  ("Mujer de 21 años", ["8 meses de disnea y cansancio; palidez; signos vitales estables.",
                        "Hb 7, reticulocitos 5 %, bilirrubina 5 (directa 0,5), Coombs directo (+)."]),
  ["AHAI caliente: primera línea corticoide (metilprednisolona EV o prednisona 1 mg/kg/día).",
   "Segunda línea: rituximab; luego otros inmunosupresores o esplenectomía.",
   "Inmunoglobulina y plasmaféresis no son de primera línea; transfundir solo si hay riesgo vital."],
  "BSH / Primer consenso internacional de AHAI (2020).",
  d=dict(rotulo="El frotis y la escalera de tratamiento",
         img=dict(titulo="Frotis (esquema)", IH=190,
                  ilu=lambda s, x, y: I.frotis(s, x + 288, y, "esferocitos", sc=0.92),
                  pie="Esferocitos: glóbulos rojos redondos, sin centro pálido, por la acción de los anticuerpos."),
         check_titulo="¿Qué tiene?",
         check=[("Hb 7 con reticulocitos 5 %", True), ("Bilirrubina indirecta alta", True), ("Coombs directo positivo", True)],
         veredicto="AHAI CALIENTE: empezar corticoide",
         peldanos=[("Corticoide", ["Metilprednisolona EV o prednisona."]),
                   ("Rituximab", ["Si no responde o recae."]),
                   ("Esplenectomía u otros", ["Inmunosupresores."])],
         ans=0, tag="ESTE CASO", salto="Ya",
         leyenda_estable="Se sube un peldaño si no responde en 3 semanas o si recae.",
         leyenda_inestable="Este caso: AHAI recién diagnosticada → corticoide."),
  tabla=("Opciones de la pregunta", [("Plasmaféresis", False), ("Metilprednisolona EV", True), ("Inmunoglobulina EV", False), ("Rituximab", False)],
         [("Línea", ["No es de rutina", "Primera", "Poco eficaz", "Segunda"])]))

# HEM-046 · Esferocitosis hereditaria · TERMÓMETRO + franja
S("termometro", "HEM-046", "esferocitos-coombs-negativo-fragilidad-osmotica-esferocitosis-esplenectomia",
  "Esferocitos con Coombs negativo y fragilidad osmótica positiva: esferocitosis hereditaria, esplenectomía",
  "Anemias hemolíticas · esferocitosis hereditaria", EH,
  ("Esferocitosis hereditaria", ["Defecto de la membrana del glóbulo rojo: se vuelve esfera y el bazo lo destruye.",
                                 "Coombs negativo (no es autoinmune); CHCM alta; fragilidad osmótica positiva."]),
  ("Mujer de 28 años", ["Fatiga progresiva, ictericia y esplenomegalia.",
                        "Hb 8, esferocitos, CHCM 38, Coombs directo (–), fragilidad osmótica (+)."]),
  ["Esferocitosis moderada-grave sintomática: esplenectomía (el bazo es donde se destruyen).",
   "Vacunar contra neumococo, meningococo y Haemophilus al menos 2 semanas antes.",
   "El ácido fólico es complemento; los corticoides no sirven (no es inmune)."],
  "BSH, esferocitosis hereditaria (2011, actualización); " + HARRISON + ".",
  d=dict(rotulo="Gravedad y tratamiento",
         niveles=[("Portador", "Sin anemia", ["Nada"]),
                  ("Leve", "Hb > 11", ["Ácido fólico, vigilar"]),
                  ("Moderada", "Hb 8-11", ["Esplenectomía si hay síntomas"]),
                  ("Grave", "Hb < 8, transfusiones", ["Esplenectomía"])],
         caso_nivel=2, ruta_titulo="Qué se hace", paso_label="ESTE CASO",
         pasos=[(1, "Esplenectomía", ["Vacunas 2 semanas antes"], True),
                (2, "Ácido fólico", ["Complemento"], False),
                (3, "Buscar cálculos biliares", ["Colecistectomía si los hay"], False)]),
  banda=B("Frotis (esquema)", D(lambda s, x, y: I.frotis(s, x, y, "esferocitos", sc=1.1), 330, 220),
          ["Esferocitos: pequeños, densos, sin centro pálido.", "Coombs negativo: no hay anticuerpos.", "El bazo los atrapa: esplenomegalia."], ans=0),
  tabla=("Opciones de la pregunta", [("Esplenectomía", True), ("Transfusiones", False), ("Solo ácido fólico", False), ("Glucocorticoides", False)],
         [("Comentario", ["Elección", "Solo en crisis", "No corrige", "No es autoinmune"])]))

# HEM-047 · LMA: bastones de Auer · TARJETAS + franja (foto real)
S("tarjetas", "HEM-047", "blastos-granulos-azurofilos-medula-leucemia-mieloide-aguda-bastones-auer",
  "Blastos con gránulos azurófilos: los bastones de Auer confirman el linaje mieloide",
  "Leucemias agudas · morfología", EH,
  ("Leucemia mieloide aguda (LMA)", ["Blastos mieloides llenan la médula: anemia, plaquetas bajas, infecciones.",
                                     "Los bastones de Auer (gránulos azurófilos fusionados) son propios del linaje mieloide."]),
  ("Varón de 45 años", ["Astenia, equimosis y palidez.", "Anemia, trombocitopenia, blastos en sangre; en médula, blastos con gránulos azurófilos."]),
  ["Bastones de Auer en blastos = leucemia mieloide aguda (también en la promielocítica, en haces).",
   "Se confirma con citometría de flujo (CD13, CD33, MPO).",
   "Reed-Sternberg: Hodgkin; linfocitos atípicos: mononucleosis; plasmocitos: mieloma."],
  "OMS, clasificación de neoplasias hematológicas (2022); ELN (2022).",
  d=dict(rotulo="Cuatro hallazgos al microscopio", ans=0,
         cards=[dict(titulo="Bastones de Auer", datos=[("Célula", "Blasto mieloide", True), ("Aspecto", "Aguja rojiza", True),
                                                       ("Indica", "Leucemia mieloide", True)], pie="Este caso."),
                dict(titulo="Reed-Sternberg", datos=[("Célula", "Binucleada, «ojos de búho»", False), ("Dónde", "Ganglio", False),
                                                     ("Indica", "Linfoma de Hodgkin", False)], pie="No es leucemia."),
                dict(titulo="Linfocitos atípicos", datos=[("Célula", "Grande, citoplasma azul", False), ("Contexto", "Fiebre, faringitis", False),
                                                          ("Indica", "Mononucleosis", False)], pie="Reactivos, no malignos."),
                dict(titulo="Plasmocitos", datos=[("Célula", "Núcleo excéntrico", False), ("Cromatina", "En rueda de carro", False),
                                                  ("Indica", "Mieloma", False)], pie="Adulto mayor, dolor óseo.")]),
  escala=dict(nombre="Clasificación FAB de la LMA", orden=False,
              que="Ordena la leucemia mieloide aguda (M0 a M7) por cómo se ven los blastos; la OMS 2022 suma la genética.",
              grados=[("M0", "Mínimamente diferenciada", ["Sin bastones de Auer", "MPO negativa al microscopio", "Se reconoce por citometría (CD13, CD33)"]),
                      ("M1", "Sin maduración", ["Blastos con pocos gránulos", "Bastones de Auer a veces"], "AUER"),
                      ("M2", "Con maduración", ["Gránulos azurófilos", "Bastones de Auer frecuentes", "t(8;21)"], "AUER"),
                      ("M3", "Promielocítica", ["Bastones de Auer en haces", "Riesgo de CID", "t(15;17): ácido transretinoico"], "AUER EN HACES"),
                      ("M4", "Mielomonocítica", ["Línea mieloide y monocítica", "Bastones de Auer a veces", "Con eosinófilos: inv(16)"], "AUER"),
                      ("M5", "Monocítica", ["Infiltra encías y piel", "Esterasa inespecífica positiva"]),
                      ("M6", "Eritroide", ["Precursores rojos anormales"]),
                      ("M7", "Megacarioblástica", ["Fibrosis de la médula", "Más frecuente en el síndrome de Down"])],
              caso=[1, 2, 3, 4],
              porque_titulo="Dónde cae este caso",
              porque=[("Blastos con gránulos azurófilos y bastones de Auer: linaje mieloide (M1 a M4)", True),
                      ("No es M0: en la M0 no hay bastones de Auer", False),
                      ("El subtipo exacto se define con citometría de flujo y genética (OMS 2022)", True)],
              conducta="Bastones de Auer = LMA: confirmar con citometría de flujo (MPO, CD13, CD33) y estudio genético."),
  banda=B("Bastón de Auer (foto real)", P("auer.jpg", 200, 317, [("flecha", 0.31, 0.22, 0.04, 0.50, "bastón de Auer")],
                                          credito="AFIP · Wikimedia Commons · dominio público"),
          [("Bastón de Auer (flecha)", "Una aguja rojiza dentro del citoplasma del blasto: son gránulos azurófilos que se fusionaron."),
           ("Solo existe en el linaje mieloide", "Ningún blasto linfoide lo tiene: por eso confirma que es una leucemia mieloide aguda."),
           ("Muchos bastones en haces", "Células «en astillero»: piensa en la promielocítica (M3), que se complica con CID."),
           ("Lo que no es", "Reed-Sternberg (Hodgkin), linfocitos atípicos (mononucleosis) y plasmocitos (mieloma) no tienen bastones.")],
          ans=0),
  tabla=("Opciones de la pregunta", [("Reed-Sternberg", False), ("Linfocitos atípicos", False), ("Plasmocitos", False), ("Bastones de Auer", True)],
         [("Indica", ["Hodgkin", "Mononucleosis", "Mieloma", "LMA: este caso"])]))

# INF-115 · Shigelosis · EMBUDO + franja
S("embudo", "INF-115", "disenteria-fiebre-leucocitos-mas-100-campo-shigella",
  "Diarrea con moco y sangre, fiebre y más de 100 leucocitos por campo: Shigella",
  "Enfermedad diarreica · diarrea inflamatoria", EI,
  ("Diarrea inflamatoria (disentería)", ["Gérmenes que invaden el colon: moco, sangre, fiebre y leucocitos en heces.",
                                         "En el adulto con fiebre alta y disentería aguda, Shigella es la más probable."]),
  ("Varón de 30 años", ["2 días de cólicos en fosa ilíaca izquierda y 6 deposiciones con moco y sangre; T 38,5 °C.",
                        "Heces: leucocitos > 100/campo y hematíes; sin parásitos."]),
  ["Disentería aguda + fiebre alta + muchos leucocitos en heces = diarrea inflamatoria por Shigella.",
   "Coprocultivo y antibiótico (azitromicina o ciprofloxacino según sensibilidad), hidratación.",
   "La amebiasis es más lenta, con menos fiebre y trofozoítos; ETEC y norovirus dan diarrea acuosa."],
  MINSA + ", guía de enfermedad diarreica; IDSA (2017).",
  d=dict(rotulo="De la disentería al germen", inicio="Diarrea con moco, sangre y fiebre de 38,5 °C",
         candidatos=["E. coli enterotoxigénica", "Norovirus", "Amebiasis", "Shigella"],
         pasos=[("¿Diarrea acuosa, sin sangre ni leucocitos?", ["E. coli enterotoxigénica", "Norovirus"]),
                ("¿Trofozoítos en heces, curso de semanas, poca fiebre?", ["Amebiasis"])],
         final=("Shigella", ["Fiebre alta + disentería + leucocitos > 100"]),
         nota="Muchos leucocitos y fiebre alta: bacteria que invade el colon."),
  banda=B("Germen (Gram, esquema)", D(lambda s, x, y: I.gram(s, x + 20, y, "bacilos_neg", sc=1.1), 280, 180),
          ["Bacilos gramnegativos.", "Shigella invade la mucosa del colon.", "Basta un inóculo muy pequeño para contagiar."]),
  tabla=("Opciones de la pregunta", [("E. coli enterotoxigénica", False), ("Shigella", True), ("Amebiasis", False), ("Norovirus", False)],
         [("¿Encaja?", ["No: acuosa", "Sí", "No: sin trofozoítos", "No: acuosa"])]))

# INF-116 · Absceso hepático amebiano · ANATOMÍA
_absc = I.E(66, 70, 20, 15, "#fde68a", "#b45309", 2.5)
S("anatomia", "INF-116", "fiebre-dolor-hipocondrio-derecho-disenteria-previa-absceso-hepatico-amebiano",
  "Fiebre y dolor en hipocondrio derecho tras una disentería: absceso hepático amebiano",
  "Parasitosis · amebiasis extraintestinal", EI,
  ("Amebiasis extraintestinal", ["Entamoeba histolytica cruza la pared del colon y sube por la vena porta.",
                                 "El hígado es el sitio más frecuente: absceso único en el lóbulo derecho."]),
  ("Varón de 32 años, zona rural", ["10 días de fiebre y dolor en hipocondrio derecho que empeora con la tos.",
                                    "Disentería hace 2 meses que se autolimitó."]),
  ["Disentería previa + fiebre + dolor en hipocondrio derecho = absceso hepático amebiano.",
   "Ecografía: lesión única en el lóbulo derecho; contenido «pasta de anchoas».",
   "Metronidazol y luego un amebicida luminal; drenaje si es grande o no mejora."],
  "IDSA; " + HARRISON + ".",
  d=dict(rotulo="Dónde se va la ameba", tag="ESTE CASO",
         ilu_titulo="Abdomen (esquema)",
         ilu=lambda s, x, y: I.abdomen(s, x + 60, y, on={"higado"}, extra=_absc,
                                       marcas=[(1, 66, 70), (2, 40, 22), (3, 150, 250), (4, 266, 78)], sc=1.0),
         ilu_pie="1 hígado (absceso en amarillo), 2 hacia el pulmón derecho, 3 peritoneo, 4 bazo.",
         ans=1,
         puntos=[("Hígado", ["El más frecuente: llega por la vena porta. Este caso."]),
                 ("Pulmón y pleura derecha", ["Por extensión de un absceso hepático."]),
                 ("Peritoneo", ["Si el absceso se rompe."]),
                 ("Bazo", ["Muy raro."])],
         signo=dict(titulo="Qué hacer", lines=["Ecografía del hígado; serología para ameba.",
                                               "Metronidazol 10 días y luego paromomicina; drenar si es grande o no mejora."])),
  tabla=("Opciones de la pregunta", [("Bazo", False), ("Pulmones", False), ("Peritoneo", False), ("Hígado", True)],
         [("Frecuencia", ["Rara", "Por extensión", "Por ruptura", "La más frecuente"])]))


# INF-117 · Molusco contagioso en VIH · ÁRBOL CON IMAGEN (foto real)
def _molusco(s, x, y):
    _img_draw(s, x, y, P("molusco.jpg", 230, 301, [("circulo", 0.383, 0.781, 0.07, "umbilicada", 0.45, 0.93)],
                         credito="Gzzz · Wikimedia Commons · CC BY-SA 4.0"))


S("arbol_imagen", "INF-117", "mujer-vih-papulas-umbilicadas-vulva-muslos-molusco-crioterapia-tar",
  "Pápulas umbilicadas múltiples en una mujer con VIH: molusco contagioso, crioterapia y reforzar el TAR",
  "VIH · manifestaciones cutáneas", EI,
  ("Molusco contagioso", ["Poxvirus: pápulas lisas, brillantes, con umbilicación central.",
                          "En el VIH son más numerosas, grandes y persistentes."]),
  ("Mujer de 29 años con VIH", ["6 meses de lesiones en vulva, suprapúbico y muslos; crecen en número y tamaño.",
                                "Pápulas de 5-10 mm, rosadas, lisas, umbilicadas, sin inflamación."]),
  ["Pápulas umbilicadas = molusco contagioso; en el VIH: tratamiento local + mejorar la inmunidad.",
   "Crioterapia, curetaje o cantaridina; revisar adherencia, carga viral y CD4.",
   "No responden a aciclovir ni antibióticos; no es sífilis."],
  "CDC/NIH/IDSA, infecciones oportunistas (2024); " + HARRISON + ".",
  d=dict(rotulo="¿Qué hacer con el molusco?", tag="ESTE CASO",
         pregunta="Pápulas umbilicadas: ¿hay inmunosupresión?",
         ramas=[("No: inmunocompetente", "Observar o tratar local", ["Suelen desaparecer solas en meses."]),
                ("Sí: VIH, lesiones múltiples", "Crioterapia + reforzar TAR",
                 ["Nitrógeno líquido o curetaje.", "Al subir los CD4, las lesiones desaparecen."])],
         ilu=_molusco, IW=230, IH=319,
         ilu_pie="Foto real: pápulas pequeñas, lisas y umbilicadas (círculo).",
         luego_titulo="Qué más",
         luego=[("Carga viral y CD4", ["Ver si el TAR está funcionando."], True),
                ("No sirven", ["Aciclovir ni antibióticos."], False),
                ("Contagio", ["Por contacto y vía sexual: evitar rascado."], False)]),
  tabla=("Opciones de la pregunta", [("Crioterapia + reforzar TAR", True), ("Aciclovir", False), ("Serología para sífilis", False),
                                     ("Antibióticos", False)],
         [("Problema", ["Ninguno", "Es para herpes", "No es sífilis", "No es bacteriano"])]))

# INF-118 · VIH agudo: NAT · ÁRBOL + franja
S("arbol", "INF-118", "eia-cuarta-generacion-reactivo-diferenciacion-negativa-vih-agudo-nat",
  "EIA de 4.ª generación reactivo con prueba de diferenciación negativa: ARN de VIH (NAT)",
  "VIH · diagnóstico de la infección aguda", EI,
  ("Diagnóstico de VIH (algoritmo CDC)", ["1.º EIA de 4.ª generación (antígeno p24 + anticuerpos); 2.º prueba de diferenciación VIH-1/VIH-2.",
                                          "Si el 1.º es reactivo y el 2.º negativo: puede ser infección aguda (aún sin anticuerpos)."]),
  ("Varón de 28 años", ["2 semanas de fiebre, odinofagia y adenopatías; relación sin condón hace 4 semanas.",
                        "EIA 4.ª generación reactivo; diferenciación VIH-1/VIH-2 negativa."]),
  ["EIA reactivo + diferenciación negativa: hacer prueba de ácido nucleico (ARN de VIH).",
   "NAT positivo = infección aguda (síndrome retroviral agudo); negativo = EIA falso positivo.",
   "El Western blot ya no se usa; esperar 3 meses deja sin diagnóstico la etapa más contagiosa."],
  "CDC, algoritmo de diagnóstico de VIH (2014, actualizado 2018); " + MINSA + ".",
  arbol=Q("¿EIA de 4.ª generación reactivo?", [
      L("No", "Sin infección", ["Repetir si la exposición es muy reciente"]),
      Q("¿Diferenciación VIH-1/VIH-2 positiva?", [
          L("Sí", "VIH confirmado", ["Iniciar TAR"]),
          L("No: este caso", "ARN DE VIH (NAT)", ["Positivo: infección aguda", "Negativo: falso positivo"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("Qué se detecta y cuándo", D(lambda s, x, y: I.vih_marcadores(s, x, y, semana=4, sc=0.95), 360, 220),
          ["A las 4 semanas hay mucho ARN y antígeno p24.", "Los anticuerpos aún no aparecen: la diferenciación sale negativa.",
           "El NAT detecta el ARN del virus."], ans=1),
  tabla=("Opciones de la pregunta", [("Repetir EIA en 3 meses", False), ("NAT para ARN de VIH-1", True), ("Serología para VEB", False),
                                     ("Western blot", False)],
         [("Problema", ["Retrasa el diagnóstico", "Ninguno", "No resuelve el EIA reactivo", "Ya no se usa; negativo al inicio"])]))

# INF-119 · Dengue con choque · ÁRBOL + franja
_pet = I.puntos_piel((78, 88, 162, 160), 40, "#be123c", (1.6, 2.6), 9)
S("arbol", "INF-119", "dengue-dia-5-pa-80-40-derrame-bilateral-choque-bolo-cristaloides",
  "Dengue con choque por fuga capilar: bolo rápido de cristaloides",
  "Enfermedades metaxénicas · dengue grave", EI,
  ("Dengue grave con choque", ["En la fase crítica el plasma se escapa de los vasos: derrames, hemoconcentración y choque.",
                               "Lo que salva es reponer volumen rápido con cristaloides isotónicos."]),
  ("Mujer de 22 años, día 5 de fiebre", ["Cansancio, disnea y cefalea; PA 80/40, FC 115, FR 28.",
                                         "Derrame en ambas bases y petequias en el tórax."]),
  ["Choque por fuga capilar: salino 0,9 % o Ringer 20 mL/kg en 15-30 minutos y reevaluar.",
   "Repetir según cómo responda y el hematocrito; luego bajar el ritmo para no sobrecargar.",
   "Dopamina, plaquetas o dextrosa no corrigen el choque."],
  OPS + "; " + MINSA + ", norma técnica de dengue.",
  arbol=Q("¿Hay choque (PA baja, pulso débil, llenado lento)?", [
      L("No", "Signos de alarma: hospitalizar", ["Cristaloides EV controlados"]),
      L("Sí: PA 80/40", "BOLO DE CRISTALOIDE", ["Salino 0,9 % o Ringer 20 mL/kg en 15-30 min", "Reevaluar y repetir; hematocrito"],
        path=True)], path=True),
  banda=B("La paciente", D(lambda s, x, y: I.cuerpo(s, x + 40, y, {"torax": "#fde2e2"}, extra=_pet, marcas=[(1, 120, 130), (2, 84, 160)], sc=0.7), 250, 312),
          ["Petequias en el tórax.", "Derrame pleural en ambas bases: fuga de plasma.", "PA 80/40: choque."], ans=2),
  tabla=("Opciones de la pregunta", [("Bolo de salino 0,9 %", True), ("Dopamina", False), ("Plaquetas", False), ("Dextrosa 5 %", False)],
         [("Problema", ["Ninguno", "No repone el volumen perdido", "No tratan el choque", "No expande el volumen"])]))

# INF-120 · Chancroide · COMPARADOR (dibujos)
S("comparador", "INF-120", "ulceras-genitales-dolorosas-base-blanda-adenitis-supurada-chancroide-azitromicina",
  "Úlceras genitales dolorosas, blandas, con ganglio inguinal doloroso: chancroide, azitromicina",
  "Infecciones de transmisión sexual · úlcera genital", EI,
  ("Úlcera genital", ["Dolorosa y blanda: chancroide (Haemophilus ducreyi) o herpes.",
                      "Indolora y dura: sífilis primaria."]),
  ("Varón de 29 años", ["Múltiples parejas, condón irregular.", "Úlceras dolorosas, base blanda, bordes irregulares; adenitis inguinal dolorosa."]),
  ["Úlcera dolorosa blanda + bubón inguinal doloroso = chancroide.",
   "Tratamiento: azitromicina 1 g VO dosis única (alternativa ceftriaxona 250 mg IM o ciprofloxacino).",
   "Descartar sífilis y VIH; tratar a las parejas."],
  CDC + "; " + MINSA + ", manejo sindrómico de ITS.",
  d=dict(rotulo="Chancroide frente a sífilis", IH=210, tag="ESTE CASO",
         imgs=[dict(titulo="Chancroide", on=True, ilu=lambda s, x, y: I.ulcera_genital(s, x + 97, y, "chancroide"),
                    pie="Dolorosa, blanda, fondo sucio, bordes irregulares; ganglio que supura."),
               dict(titulo="Sífilis primaria", ilu=lambda s, x, y: I.ulcera_genital(s, x + 97, y, "sifilis"),
                    pie="Indolora, dura, limpia; ganglio duro que no supura.")],
         lectura_titulo="Tratamiento según la úlcera",
         lectura=[("Chancroide", ["Azitromicina 1 g dosis única."], True),
                  ("Sífilis", ["Penicilina benzatínica."], False),
                  ("Herpes", ["Vesículas agrupadas; aciclovir."], False)]),
  tabla=("Opciones de la pregunta", [("Ampicilina", False), ("Tetraciclina", False), ("Cotrimoxazol", False), ("Azitromicina", True)],
         [("¿De elección?", ["No", "No", "No (resistencias)", "Sí"])]))

# INF-121 · Leishmaniasis visceral · MAPA DE SIGNOS
_hepesp = I.E(96, 186, 26, 16, "#fdba74", "#9a3412", 2, 'opacity="0.85"') + I.E(150, 200, 24, 30, "#c4b5fd", "#6d28d9", 2, 'opacity="0.85"')
S("mapa_signos", "INF-121", "vih-loreto-fiebre-hepatoesplenomegalia-pancitopenia-rk39-leishmaniasis-visceral",
  "Fiebre prolongada, hepatoesplenomegalia y pancitopenia con rK39 positiva: leishmaniasis visceral",
  "Parasitosis · leishmaniasis", EI,
  ("Leishmaniasis visceral (kala-azar)", ["Leishmania infecta los macrófagos del bazo, el hígado y la médula ósea.",
                                          "Fiebre prolongada, bazo muy grande, pancitopenia y desnutrición; más grave con VIH."]),
  ("Mujer de 28 años de Loreto con VIH (CD4 180)", ["4 semanas de fiebre, astenia y baja de 8 kg.",
                                                    "Palidez, hepatoesplenomegalia, adenopatías; pancitopenia; rK39 positiva."]),
  ["Fiebre + hepatoesplenomegalia + pancitopenia + rK39 (+) = leishmaniasis visceral.",
   "Confirmar con amastigotes en médula ósea; tratar con anfotericina B liposomal.",
   "La TB miliar y el linfoma son diferenciales, pero la rK39 positiva orienta a Leishmania."],
  "OMS, leishmaniasis (2022); " + MINSA + ".",
  d=dict(rotulo="Los signos de la paciente", PH=500, tag="ESTE CASO",
         ilu_titulo="La paciente del caso",
         ilu=lambda s, x, y: I.cuerpo(s, x + 39, y + 4, {"cara": "#fdf3ec"}, extra=_hepesp,
                                      marcas=[(1, 96, 186), (2, 150, 200), (3, 108, 46), (4, 120, 250)], sc=0.9),
         ilu_pie="1 hígado grande, 2 bazo grande, 3 palidez, 4 baja de peso.",
         signos=[dict(tit="Hepatomegalia", lines=["Macrófagos del hígado infectados."]),
                 dict(tit="Esplenomegalia", lines=["El bazo puede llegar a la pelvis."]),
                 dict(tit="Pancitopenia y palidez", lines=["Médula ósea invadida."]),
                 dict(tit="Fiebre y baja de peso", lines=["4 semanas, −8 kg."]),
                 dict(tit="rK39 positiva", lines=["Prueba rápida de anticuerpos."]),
                 dict(tit="Causa: leishmaniasis visceral", on=True, lines=["Más grave en el VIH."])]),
  tabla=("Opciones de la pregunta", [("TB miliar", False), ("Linfoma de Hodgkin", False), ("Leishmaniasis visceral", True), ("Esquistosomiasis", False)],
         [("Clave", ["Patrón miliar en la Rx", "Biopsia de ganglio", "rK39 + bazo grande", "No es endémica en Perú"])]))

# INF-122 · Primaquina y G6PD · CRONOLOGÍA
S("cronologia", "INF-122", "malaria-vivax-cloroquina-cura-radical-primaquina-descartar-deficit-g6pd",
  "Malaria vivax tratada: antes de la primaquina, descartar déficit de G6PD",
  "Malaria · cura radical", EI,
  ("Cura radical de P. vivax", ["La cloroquina mata los parásitos de la sangre, pero no los hipnozoítos del hígado.",
                                "La primaquina elimina los hipnozoítos y evita recaídas."]),
  ("Varón de 60 años, zona endémica", ["Malaria vivax tratada con cloroquina, buena evolución.", "Se indicará la cura radical."]),
  ["La primaquina es oxidante: con déficit de G6PD produce hemólisis grave.",
   "Antes de darla: prueba de G6PD; si es deficiente, ajustar el esquema (semanal, con control).",
   "La retinopatía por cloroquina requiere dosis acumuladas altas; la quinina no se usa aquí."],
  MINSA + ", norma técnica de malaria; OMS (2023).",
  d=dict(rotulo="Del tratamiento a la cura radical", tag="ESTE CASO",
         ilu_titulo="Frotis (esquema)",
         ilu=ILU(D(lambda s, x, y: I.frotis(s, x + 15, y + 20, "vivax", sc=1.0), 330, 240)),
         ilu_pie="P. vivax dentro de los glóbulos rojos (fase de la sangre).",
         claves=[("Déficit de G6PD", ["La primaquina causaría hemólisis."], True),
                 ("Retinopatía por cloroquina", ["Solo con dosis acumuladas altas."], False),
                 ("Hipoglucemia por quinina", ["No recibe quinina."], False)],
         eje_titulo="Días de tratamiento", eje=(0, 18), paso=3, marca=3, unidad="d",
         eje_nombre="días",
         hitos=[(0, 3, "Cloroquina", "formas de la sangre", False),
                (3, 4, "Prueba de G6PD", "antes de la primaquina", True),
                (3, 10, "Primaquina 7 días", "esquema peruano", False),
                (3, 17, "o primaquina 14 días", "dosis menor", False)]),
  tabla=("Opciones de la pregunta", [("Retinopatía por cloroquina", False), ("Hipoglucemia por quinina", False), ("Hemólisis por déficit de G6PD", True),
                                     ("Hepatotoxicidad", False)],
         [("¿Principal riesgo?", ["No con 3 días", "No usa quinina", "Sí", "No es lo principal"])]))

# INF-123 · TB-VIH: rifampicina y TAR · RADIAL + franja
S("radial", "INF-123", "tb-vih-carga-viral-alta-pese-adherencia-rifampicina-induccion-enzimatica",
  "TB y VIH con carga viral alta pese a buena adherencia: la rifampicina baja el antirretroviral",
  "Coinfección TB-VIH · interacciones", EI,
  ("Rifampicina y antirretrovirales", ["La rifampicina es un inductor enzimático potente (CYP3A4, UGT1A1).",
                                       "Baja los niveles de inhibidores de proteasa, dolutegravir y otros."]),
  ("Varón de 38 años con sida y TB bacilífera", ["CD4 120; inició TAR y antituberculosos.",
                                                 "A los 2 meses: carga viral alta y CD4 bajos pese a buena adherencia."]),
  ["Falla con buena adherencia en quien recibe rifampicina: pensar en la interacción.",
   "Ajustar el TAR a uno compatible: dolutegravir 50 mg cada 12 h o efavirenz.",
   "No quitar la rifampicina (es la base del tratamiento) ni retrasar el TAR."],
  "OMS, TB-VIH (2022); " + MINSA + ".",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Carga viral alta con rifampicina",
         items=[("Cambiar a TAR compatible", ["Dolutegravir cada 12 h o efavirenz"]),
                ("Quitar la rifampicina", ["Debilita el tratamiento de la TB"]),
                ("Retrasar el TAR", ["Con CD4 bajos aumenta la mortalidad"]),
                ("No cambiar nada", ["La interacción sigue"])],
         ruta=["TB + VIH", "Rifampicina + TAR", "Carga viral alta", "Ajustar el TAR"]),
  banda=B("Nivel del antirretroviral", D(lambda s, x, y: I.lab_barras(s, x, y, [("Sin rifampicina", "nivel eficaz", 100, False),
                                                                              ("Con rifampicina", "muy bajo", 30, True)],
                                                                   W=330, xmax=110, titulo="Nivel en sangre (%)", ref=None), 330, 100),
          ["La rifampicina acelera su metabolismo en el hígado.", "El nivel cae por debajo del eficaz.", "Por eso falla aunque lo tome bien."], ans=1),
  tabla=("Opciones de la pregunta", [("Cambiar rifampicina por etambutol", False), ("Retrasar el TAR", False), ("TAR compatible", True),
                                     ("Profilaxis a contactos, sin cambios", False)],
         [("Problema", ["Debilita el esquema de TB", "Más mortalidad", "Ninguno", "No corrige la interacción"])]))

# INF-124 · Dengue en recuperación: sobrecarga · FASES + franja
S("fases", "INF-124", "dengue-grave-48-horas-defervescencia-disnea-crepitantes-sobrecarga-fluidos",
  "Disnea con crepitantes 48 h después de la defervescencia: edema pulmonar por sobrecarga de fluidos",
  "Enfermedades metaxénicas · dengue: fases", EI,
  ("Las fases del dengue", ["Febril (días 1-3), crítica con fuga capilar (días 4-6) y recuperación.",
                            "En la recuperación el líquido vuelve a los vasos: si se dio de más, sobrecarga."]),
  ("Varón de 60 años con dengue grave", ["Recibió cristaloides en la fase crítica.",
                                         "48 h tras la defervescencia: disnea, taquipnea, SatO₂ 88 %, crepitantes; hemodinamia estable."]),
  ["Fase de recuperación + crepitantes + hipoxemia sin choque = edema pulmonar por reabsorción y sobrecarga.",
   "Suspender o reducir los fluidos; furosemida si la PA está estable; oxígeno.",
   "No es hemorragia alveolar ni SDRA: el momento y la estabilidad apuntan a sobrecarga."],
  OPS + "; " + MINSA + ".",
  d=dict(rotulo="Las fases del dengue", ans=2,
         fases=[("Febril", "Días 1-3", "FIEBRE", ["Viremia, mialgias"]),
                ("Crítica", "Días 4-6", "FUGA CAPILAR", ["Se reponen fluidos"]),
                ("Recuperación", "Días 7-10", "REABSORCIÓN", ["El líquido vuelve: sobrecarga"])],
         curvas=[("Líquido fuera de los vasos", "#0284c7", [0.1, 0.15, 0.6, 0.9, 0.7, 0.3, 0.1]),
                 ("Volumen dentro de los vasos", "#dc2626", [0.5, 0.5, 0.3, 0.25, 0.5, 0.9, 0.95])]),
  escala=dict(nombre="Clasificación del dengue (OPS/OMS)",
              que="Ordena el dengue por gravedad; el MINSA la usa para decidir dónde tratar (grupos A, B1, B2 y C).",
              grados=[("Grupos A y B1", "Dengue sin signos de alarma",
                       ["Fiebre + 2 de: náuseas, exantema, mialgias, cefalea o dolor retroocular, petequias, leucopenia",
                        "A: en casa · B1: observar si hay comorbilidad o riesgo social"]),
                      ("Grupo B2", "Dengue con signos de alarma",
                       ["Dolor abdominal intenso y continuo", "Vómitos persistentes", "Líquido acumulado o sangrado de mucosas",
                        "Letargia, hepatomegalia o hematocrito que sube"]),
                      ("Grupo C", "Dengue grave",
                       ["Choque o dificultad respiratoria por fuga de plasma", "Sangrado grave", "Daño grave de órganos"])],
              caso=2,
              porque_titulo="Por qué el caso es grupo C y qué cambió ahora",
              porque=[("Ya era dengue grave: necesitó expansión con cristaloides en la fase crítica", True),
                      ("Ahora: disnea, SatO₂ 88 % y crepitantes en ambos pulmones", True),
                      ("No es fuga de plasma: aparece 48 h después de la fiebre, con PA estable (fase de recuperación)", False)],
              conducta="Grupo C en recuperación con sobrecarga: suspender o reducir los fluidos, oxígeno y furosemida si la PA está estable."),
  banda=B("Rx real de edema pulmonar", P("edema_ap.jpg", 330, 264, [("flechas", [(0.24, 0.62), (0.77, 0.52)], 0.5, 0.9,
                                                                   "líquido en ambos pulmones")],
                                         credito="F. Gaillard y J. Jones (Radiopaedia) · Wikimedia Commons · CC BY-SA 3.0"),
          [("Manchas blancas en ambos pulmones", "Algodonosas y alrededor de los hilios: es líquido dentro de los alvéolos."),
           ("Por qué aparece en la recuperación", "La fuga capilar se cierra y el plasma que había salido vuelve de golpe a los vasos."),
           ("Más el suero que se infundió", "Si en la fase crítica se dio mucho cristaloide, el volumen desborda al pulmón: sobrecarga.")],
          pie="Rx de otro paciente con edema pulmonar agudo.", ans=2),
  tabla=("Opciones de la pregunta", [("Edema por reabsorción y sobrecarga", True), ("Hemorragia alveolar", False), ("Neumonía atípica", False),
                                     ("SDRA viral", False)],
         [("¿Encaja?", ["Sí", "No: sin sangrado", "No: sin fiebre nueva", "No: en recuperación"])]))


# INF-125 · Retinitis por CMV · COMPARADOR (foto real + dibujo)
def _cmv(s, x, y):
    _img_draw(s, x, y, P("retinitis_cmv.jpg", 300, 242, [("circulo", 0.42, 0.46, 0.13, "necrosis blanca", 0.02, 0.06),
                                                         ("flecha", 0.46, 0.71, 0.66, 0.9, "hemorragias")],
                         credito="National Eye Institute · Wikimedia Commons · dominio público"))


S("comparador", "INF-125", "sida-cd4-menor-50-retinitis-necrosante-hemorragias-pizza-citomegalovirus",
  "Sida con CD4 < 50 y retinitis necrosante con hemorragias («pizza»): citomegalovirus",
  "VIH · infecciones oportunistas del ojo", EI,
  ("Retinitis por CMV", ["La infección oportunista ocular más frecuente del sida con CD4 < 50.",
                         "Necrosis blanco-amarillenta que sigue los vasos con hemorragias: «queso con tomate»."]),
  ("Mujer de 34 años con sida (CD4 < 50)", ["Fotopsias y pérdida progresiva de visión.",
                                            "Fondo de ojo: retinitis necrosante perivascular con hemorragias en llama."]),
  ["CD4 < 50 + retinitis necrosante con hemorragias = citomegalovirus.",
   "Tratamiento: valganciclovir oral o ganciclovir (intravítreo si amenaza la visión) e iniciar o ajustar el TAR.",
   "Toxoplasma: foco blanco sin tantas hemorragias, junto a una cicatriz («faro en la niebla»)."],
  "CDC/NIH/IDSA, infecciones oportunistas (2024).",
  d=dict(rotulo="CMV frente a toxoplasma", IH=280, tag="ESTE CASO",
         imgs=[dict(titulo="Retinitis por CMV (foto real)", on=True, ilu=lambda s, x, y: _cmv(s, x + 57, y),
                    pie="Necrosis blanca a lo largo de los vasos con hemorragias."),
               dict(titulo="Toxoplasma (esquema)", ilu=lambda s, x, y: I.fondo_ojo(s, x + 87, y + 10, "toxo"),
                    pie="Foco blanco junto a una cicatriz oscura; poca hemorragia.")],
         lectura_titulo="Otras opciones",
         lectura=[("CMV", ["CD4 < 50, «pizza»: este caso."], True),
                  ("Pneumocystis", ["Coroiditis rara, sin necrosis así."], False),
                  ("Aspergillus", ["Endoftalmitis con vítreo turbio."], False)]),
  tabla=("Opciones de la pregunta", [("Pneumocystis", False), ("Toxoplasma", False), ("Aspergillus", False), ("Citomegalovirus", True)],
         [("Clave", ["Coroiditis rara", "Faro en la niebla", "Vítreo turbio", "Necrosis + hemorragias"])]))
