"""Bloque ENAM 2026 · Cirugía (parte 3)."""
from c26 import S, D, P, B, ILU, Q, L, SCHWARTZ, SABISTON, ATLS
import ilu7 as I

O = I.ORANGE
ESP = "CIRUGÍA ENAM"

# CIR-147 · Hemorroides grado III · MATRIZ + franja
S("matriz", "CIR-147", "hemorroides-grado-3-reduccion-manual-ligadura-banda-elastica",
  "Hemorroides que hay que reducir con la mano: ligadura con banda",
  "Patología anal · enfermedad hemorroidal", ESP,
  ("Hemorroides internas", ["Se gradúan por el prolapso: I no sale, II sale y vuelve sola, III hay que meterla, IV no entra.",
                            "El tratamiento sube de intensidad con el grado y con el fracaso de la dieta."]),
  ("Mujer de 55 años", ["Prolapso que requiere reducción manual, sangrado ocasional.",
                        "No mejoró con fibra y medidas higiénicas; pide algo mínimamente invasivo."]),
  ["Grado III que falla al manejo médico: ligadura con banda elástica en el consultorio.",
   "Escleroterapia: grados I-II; hemorroidectomía: grado IV, fallo de la banda o componente externo grande.",
   "La esfinterotomía es para la fisura, no para hemorroides."],
  "ASCRS, guía de hemorroides (2024); " + SCHWARTZ + ".",
  d=dict(rotulo="Grado y tratamiento", eje_x="Tratamiento", eje_y="Grado", caso=(2, 1),
         cols=["Medidas higiénico-dietéticas", "Procedimiento de consultorio", "Cirugía"],
         rows=["Grado I", "Grado II", "Grado III", "Grado IV"],
         cells=[[("Siempre", ["Fibra, agua, no pujar"]), ("Escleroterapia", ["Si sangra pese a la dieta"]), ("No", ["No se necesita"])],
                [("Siempre", ["Base del tratamiento"]), ("Banda o escleroterapia", ["Si falla la dieta"]), ("Rara vez", ["Solo si fallan"])],
                [("Siempre", ["Pero no basta"]), ("Ligadura con banda", ["Mínimamente invasiva: elección"]), ("Si falla la banda", ["Hemorroidectomía"])],
                [("Siempre", ["Como complemento"]), ("Poco útil", ["El prolapso no se reduce"]), ("Hemorroidectomía", ["Tratamiento de elección"])]]),
  banda=B("Grados de prolapso", D(lambda s, x, y: I.hemorroides_grados(s, x, y, caso=3, sc=0.9), 423, 153),
          ["Grado III (este caso): se prolapsa y hay que reducirla con la mano.",
           "La banda se coloca en la base de la hemorroide, por encima de la línea dentada (sin dolor).",
           "El tejido sin sangre se necrosa y cae en 5-7 días."], ans=0),
  tabla=("Opciones de la pregunta", [("Esfinterotomía", False), ("Escleroterapia", False), ("Hemorroidectomía", False),
                                     ("Ligadura con banda", True)],
         [("¿Cuándo?", ["Fisura anal", "Grados I-II", "Grado IV o fracaso", "Grado III: este caso"])]))

# CIR-148 · Trombosis hemorroidal externa · EMBUDO + franja
S("embudo", "CIR-148", "nodulo-violaceo-perianal-doloroso-trombosis-hemorroidal-externa",
  "Nódulo perianal violáceo y muy doloroso: trombosis hemorroidal externa",
  "Patología anal · dolor perianal agudo", ESP,
  ("Dolor perianal agudo", ["Cuatro causas frecuentes: fisura, absceso, fístula y trombosis hemorroidal.",
                            "Lo que se ve y cómo empezó el dolor las separa."]),
  ("Mujer de 30 años tras un esfuerzo", ["Dolor continuo e intenso con bulto que no la deja sentarse.",
                                         "Nódulo violáceo, tenso y doloroso en el margen anal."]),
  ["Nódulo azulado-violáceo, tenso y doloroso de inicio brusco tras esfuerzo = trombosis hemorroidal externa.",
   "< 72 h: escisión del trombo con anestesia local; > 72 h: manejo médico (baños, analgésicos, fibra).",
   "No se incide solo el trombo: se reseca el nódulo para evitar recurrencia."],
  "ASCRS, guía de hemorroides (2024); " + SCHWARTZ + ".",
  d=dict(rotulo="Del dolor al diagnóstico", inicio="Dolor perianal agudo con bulto",
         candidatos=["Fisura anal", "Absceso perianal", "Fístula perianal", "Trombosis hemorroidal"],
         pasos=[("¿Dolor solo al defecar con úlcera lineal?", ["Fisura anal"]),
                ("¿Fiebre y masa roja, caliente y fluctuante?", ["Absceso perianal"]),
                ("¿Orificio que supura desde hace meses?", ["Fístula perianal"])],
         final=("Trombosis hemorroidal externa", ["Nódulo violáceo, tenso y doloroso tras un esfuerzo"]),
         nota="Color violáceo = coágulo dentro de una vena hemorroidal externa, bajo la piel."),
  banda=B("Lo que se ve al examen", D(lambda s, x, y: I.ano_frontal(s, x, y, "trombosis"), 300, 250),
          ["Nódulo violáceo y tenso en el borde del ano: es el coágulo.", "Inicio brusco tras pujar: sube la presión venosa y se trombosa.",
           "Si tiene < 72 h, la escisión alivia rápido el dolor."], ans=0),
  tabla=("Opciones de la pregunta", [("Fisura anal", False), ("Absceso perianal", False), ("Trombosis hemorroidal", True),
                                     ("Fístula perianal", False)],
         [("Clave", ["Úlcera lineal, dolor al defecar", "Fiebre, fluctuación", "Nódulo violáceo tras esfuerzo",
                     "Supuración crónica"])]))

# CIR-149 · XABCDE: torniquete · ANATOMÍA (cuerpo con prioridades)
_torn = (I.P("M74 290 H122", "none", "#1f2937", 9) + I.P("M84 316 L90 334", "none", I.RED, 5)
         + "".join(I.C(92 + k * 5, 338 + k * 6, 2.5, I.RED, "none", 0) for k in range(3)))
S("anatomia", "CIR-149", "politrauma-hemorragia-exanguinante-muslo-xabcde-torniquete",
  "XABCDE: la hemorragia que desangra va antes que la vía aérea",
  "Trauma · evaluación primaria XABCDE", ESP,
  ("Evaluación primaria XABCDE", ["X = hemorragia exanguinante externa: se controla antes que todo lo demás.",
                                  "Luego A, B, C, D y E en ese orden."]),
  ("Varón de 50 años, accidente de tránsito", ["PA 75/60, FC 120, SatO₂ 90 %, pálido y desorientado.",
                                               "Sangrado rutilante activo por herida en el muslo derecho."]),
  ["Sangrado arterial de un miembro que no se controla con presión: torniquete por encima de la herida.",
   "Anotar la hora de colocación; no aflojarlo hasta el quirófano.",
   "Después: vía aérea con control cervical, respiración, circulación (2 vías, sangre), neurológico y exposición."],
  ATLS + "; PHTLS 10.ª ed.",
  d=dict(rotulo="Qué se revisa y en qué orden", tag="ESTE CASO",
         ilu_titulo="Prioridades en el cuerpo",
         ilu=lambda s, x, y: I.cuerpo(s, x + 110, y - 2, {"muslo_d": "#fecaca"}, extra=_torn,
                                        marcas=[("X", 60, 300), ("A", 150, 58), ("B", 150, 120), ("C", 150, 200), ("D", 96, 26), ("E", 200, 400)], sc=0.78),
         ilu_pie="Banda negra: torniquete 5-7 cm por encima de la herida del muslo derecho.",
         ans=1,
         puntos=[("X: hemorragia exanguinante", ["Torniquete o compresión directa ya."]),
                 ("A: vía aérea con control cervical", ["Permeable: habla, aunque desorientado."]),
                 ("B: respiración", ["Oxígeno; buscar neumotórax."]),
                 ("C: circulación", ["2 vías, cristaloides tibios y sangre."]),
                 ("D y E: neurológico y exposición", ["Glasgow, pupilas; desvestir y evitar hipotermia."])],
         signo=dict(titulo="Cómo se coloca el torniquete",
                    lines=["5-7 cm por encima de la herida, nunca sobre una articulación; ajustar hasta que pare el sangrado.",
                           "Anotar la hora. Puede mantenerse hasta 2 h con poco riesgo."])),
  tabla=("Opciones de la pregunta", [("Cristaloides", False), ("Glasgow y collarín", False), ("Torniquete", True), ("Vía aérea", False)],
         [("Letra", ["C", "D y A", "X: primero", "A"])]))

# CIR-151 · Absceso perianal en diabética · ÁRBOL + franja
S("arbol", "CIR-151", "absceso-perianal-diabetica-fluctuante-drenaje-quirurgico-inmediato",
  "Absceso perianal en diabética: drenaje quirúrgico inmediato",
  "Patología anal · absceso anorrectal", ESP,
  ("Absceso perianal", ["Infección de una glándula anal que forma pus junto al ano.",
                        "Si hay pus (fluctuación), el tratamiento es drenar; el antibiótico solo no basta."]),
  ("Mujer de 52 años con diabetes mal controlada", ["3 días de dolor anal intenso y fiebre de 38,5 °C.",
                                                    "Tumefacción roja, fluctuante y dolorosa en el margen anal posterior."]),
  ["Absceso perianal fluctuante: incisión y drenaje de inmediato, sin esperar imágenes.",
   "Diabética o inmunosuprimida: hospitalizar, controlar la glucosa y dar antibiótico (riesgo de Fournier).",
   "Crepitación o celulitis extensa: pensar en infección necrotizante y desbridar."],
  "ASCRS, guía de abscesos y fístulas anorrectales (2022).",
  arbol=Q("¿La tumoración perianal es fluctuante (hay pus)?", [
      Q("¿Diabetes, inmunosupresión o signos sistémicos?", [
          L("Sí", "DRENAJE INMEDIATO + HOSPITALIZAR", ["Antibiótico EV y control de la glucemia", "Vigilar necrosis (Fournier)"], path=True),
          L("No", "Drenaje en consultorio", ["Alta con analgesia y baños de asiento"])], edge="Sí", path=True),
      L("No", "Celulitis sin colección", ["Antibiótico y control en 24-48 h", "Eco si hay duda"])], path=True),
  banda=B("Lo que se ve al examen", D(lambda s, x, y: I.ano_frontal(s, x, y, "absceso"), 300, 250),
          ["Tumoración roja, caliente y fluctuante en el margen posterior: es pus.",
           "Línea discontinua: la incisión de drenaje.", "La diabetes mal controlada puede hacer que la infección se extienda rápido."], ans=0),
  tabla=("Opciones de la pregunta", [("Ecografía primero", False), ("ATB EV y glucemia", False), ("Observar 48-72 h", False),
                                     ("Drenaje + hospitalizar", True)],
         [("Problema", ["Retrasa el drenaje", "El pus no se cura sin drenar", "Peligroso en diabética", "Ninguno"])]))

# CIR-152 · Maniobra de Pringle · TARJETAS + franja
S("tarjetas", "CIR-152", "herida-bala-sangrado-hepatico-incontrolable-maniobra-pringle",
  "Sangrado hepático incontrolable: maniobra de Pringle",
  "Trauma abdominal · control de daños en hígado", ESP,
  ("Hemorragia hepática en cirugía de trauma", ["Primero se comprime con compresas (packing).",
                                                 "Si sigue sangrando, se ocluye el flujo que entra al hígado."]),
  ("Varón de 40 años con herida de bala", ["PA 60/40, FC 100; abdomen distendido con rebote.",
                                           "En sala: lesión hepática que sangra sin control."]),
  ["Pringle: pinzar el ligamento hepatoduodenal (arteria hepática + vena porta) para cortar el flujo de entrada.",
   "Si sigue sangrando con Pringle, la sangre viene de las venas hepáticas o la cava retrohepática.",
   "Mattox: rotación visceral medial izquierda para llegar a la aorta; exclusión pilórica: lesiones duodenales complejas."],
  ATLS + "; " + SABISTON + ".",
  d=dict(rotulo="Qué hace cada maniobra", ans=0,
         cards=[dict(titulo="Pringle", datos=[("Dónde", "Ligamento hepatoduodenal", True), ("Qué corta", "Arteria hepática y porta", True),
                                              ("Para qué", "Sangrado hepático", True)], pie="Es la de este caso."),
                dict(titulo="Mattox", datos=[("Dónde", "Colon izquierdo, bazo, riñón", False), ("Qué expone", "Aorta y ramas", False),
                                             ("Para qué", "Lesión vascular retroperitoneal", False)], pie="Rotación visceral medial izquierda."),
                dict(titulo="Exclusión duodenal", datos=[("Dónde", "Píloro y duodeno", False), ("Qué hace", "Desvía el tránsito", False),
                                                         ("Para qué", "Lesión duodenal compleja", False)], pie="No controla el hígado."),
                dict(titulo="Chutro", datos=[("Controla el hígado", "No", False), ("Pedículo hepático", "No", False),
                                             ("En esta pregunta", "Distractor", False)], pie="No es la maniobra del sangrado hepático.")]),
  banda=B("Dónde va la pinza", D(lambda s, x, y: I.higado_pringle(s, x, y), 330, 230),
          ["Laceración hepática que sangra.", "La pinza ocluye el ligamento hepatoduodenal: porta, arteria hepática y colédoco.",
           "Con el flujo detenido se ve la lesión y se repara."], ans=1),
  tabla=("Opciones de la pregunta", [("Chutro", False), ("Pringle", True), ("Mattox", False), ("Exclusión duodenal", False)],
         [("¿Detiene el flujo hepático?", ["No", "Sí", "No", "No"])]))

# CIR-153 · Quemadura de espesor total · TARJETAS + franja
S("tarjetas", "CIR-153", "quemadura-espesor-total-coriacea-indolora-desbridamiento-temprano",
  "Quemadura seca, coriácea e indolora: espesor total y desbridamiento temprano",
  "Quemaduras · profundidad", ESP,
  ("Profundidad de la quemadura", ["Se juzga por el aspecto, el dolor, el llenado capilar y si sangra al pinchar.",
                                   "El espesor total destruye nervios y vasos de la dermis: no duele ni sangra."]),
  ("Varón de 35 años, explosión de gas hace 6 h", ["Muslo derecho: lesión seca, dura, coriácea, blanco-grisácea.",
                                                   "Sin ampollas, no sangra al pinchar y no duele."]),
  ["Seca + coriácea + blanca + sin ampollas + indolora + no sangra = espesor total (3.er grado).",
   "No cicatriza sola: escarectomía temprana (primeros días) e injerto de piel.",
   "Si es circunferencial en un miembro o el tórax: escarotomía para liberar."],
  "American Burn Association; " + ATLS + ".",
  d=dict(rotulo="Cuatro profundidades", ans=3,
         cards=[dict(titulo="Superficial (1.er grado)", datos=[("Aspecto", "Eritema", False), ("Dolor", "Sí", False),
                                                                ("Sangra al pinchar", "Sí", False)], pie="Cura en 3-6 días."),
                dict(titulo="Parcial superficial", datos=[("Aspecto", "Ampollas, rosado húmedo", False), ("Dolor", "Mucho", False),
                                                          ("Sangra al pinchar", "Sí", False)], pie="Cura en 2-3 semanas."),
                dict(titulo="Parcial profunda", datos=[("Aspecto", "Rojo-blanco moteado", False), ("Dolor", "Poco", False),
                                                       ("Sangra al pinchar", "Poco", False)], pie="Suele necesitar injerto."),
                dict(titulo="Espesor total (3.er grado)", datos=[("Aspecto", "Seca, coriácea, blanca", True), ("Dolor", "No", True),
                                                                 ("Sangra al pinchar", "No", True)],
                     pie="Escarectomía temprana e injerto.")]),
  banda=B("Hasta dónde llega el daño", D(lambda s, x, y: I.piel_capas(s, x, y, "3"), 330, 235),
          ["La escara destruyó epidermis y toda la dermis.", "Sin nervios ni vasos: por eso no duele ni sangra.",
           "No hay células para regenerar: hay que retirar la escara e injertar."], ans=0),
  tabla=("Opciones de la pregunta", [("Parcial profunda y esperar", False), ("Espesor total y desbridar", True),
                                     ("Superficial", False), ("Parcial superficial", False)],
         [("¿Coincide?", ["No: esa duele poco y sangra", "Sí", "No", "No: tendría ampollas y dolor"])]))

# CIR-154 · Apendicitis en primer nivel · RED DE ATENCIÓN + franja
S("red", "CIR-154", "apendicitis-aguda-primer-nivel-hidratacion-antibiotico-referencia",
  "Apendicitis en un establecimiento del primer nivel: estabilizar y referir",
  "Apendicitis aguda · niveles de atención", ESP,
  ("Apendicitis aguda", ["El diagnóstico es clínico; el tratamiento es quirúrgico.",
                         "Si el establecimiento no opera, se prepara y se refiere sin demora."]),
  ("Varón de 22 años en el primer nivel", ["24 h de dolor periumbilical, náuseas y vómitos.",
                                           "T 38,7 °C, dolor en FID y Blumberg (+)."]),
  ["Apendicitis clínica en el primer nivel: hidratación EV, antibiótico EV, analgesia y referencia inmediata.",
   "No esperar exámenes para referir: no cambian la conducta y retrasan la cirugía.",
   "La analgesia no enmascara el diagnóstico: se puede dar."],
  "MINSA, norma de referencia y contrarreferencia; WSES (2020).",
  d=dict(rotulo="Dónde está el paciente y a dónde va", caso="I-3", destino="II-1", flecha="Referir ya", tag="ESTE CASO",
         claves=[("En el primer nivel", ["Vía EV, hidratación, antibiótico EV y analgesia."], True),
                 ("Referencia inmediata", ["A un hospital con cirugía (II-1 o más)."], False),
                 ("No retrasar", ["Ni observar ni esperar exámenes: el riesgo es la perforación."], False)]),
  banda=B("Por qué es apendicitis", D(lambda s, x, y: I.abdomen(s, x, y, on={"apendice"}, marcas=[(1, 84, 268)],
                                                                 extra=I.flecha(150, 200, 90, 262, O, 2.4, "5 4")), 300, 330),
          ["Dolor que empezó alrededor del ombligo y se fue a la FID.", "Fiebre y Blumberg (+): irritación del peritoneo.",
           "Diagnóstico clínico: se refiere para apendicectomía."]),
  tabla=("Opciones de la pregunta", [("Observar en el establecimiento", False), ("Hidratar, ATB y referir", True),
                                     ("Exámenes y luego referir", False), ("Referencia diferida", False)],
         [("Problema", ["No hay cirugía ahí", "Ninguno", "Retrasa sin cambiar la conducta", "Riesgo de perforación"])]))

# CIR-155 · Fístula transesfinteriana baja · ÁRBOL + franja
S("arbol", "CIR-155", "fistula-perianal-transesfinteriana-baja-fistulotomia",
  "Fístula perianal transesfinteriana baja: fistulotomía",
  "Patología anal · fístula anorrectal", ESP,
  ("Fístula perianal", ["Trayecto que une el canal anal con la piel, casi siempre tras un absceso.",
                        "La técnica depende de cuánto esfínter atraviesa el trayecto."]),
  ("Mujer de 45 años con abscesos previos", ["6 meses de supuración intermitente; orificio externo a 2 cm del ano.",
                                             "Transesfinteriana baja, trayecto único, < 30 % del esfínter externo; continente."]),
  ["Fístula simple (interesfinteriana o transesfinteriana baja, < 30 % del EAE) sin incontinencia: fistulotomía.",
   "Fístula alta o compleja: sedal, colgajo de avance o LIFT para proteger la continencia.",
   "Mujeres con fístula anterior: cuidado, su esfínter anterior es corto."],
  "ASCRS, guía de abscesos y fístulas anorrectales (2022).",
  arbol=Q("¿Fístula simple: baja, < 30 % del esfínter externo y sin incontinencia?", [
      L("Sí", "FISTULOTOMÍA", ["Abrir todo el trayecto y dejar que cicatrice", "Curación > 90 %"], path=True),
      L("No: alta o compleja", "Técnicas que preservan el esfínter", ["Sedal, colgajo de avance o LIFT"])], path=True),
  banda=B("Trayecto de la fístula", D(lambda s, x, y: I.ano_coronal(s, x, y, "fistula"), 320, 272),
          ["Orificio interno en la línea dentada.", "El trayecto cruza solo la parte baja del esfínter externo (EAE).",
           "Cortar esa porción pequeña no altera la continencia: se puede abrir el trayecto."], ans=1),
  tabla=("Opciones de la pregunta", [("Fistulectomía", False), ("Fistulotomía", True), ("Solo drenajes", False),
                                     ("Resección amplia del esfínter", False)],
         [("Por qué", ["Deja una herida mayor sin ventaja", "Elección en fístula simple", "No cura el trayecto", "Causa incontinencia"])]))

# CIR-156 · Politrauma en shock lejos del hospital · RED + franja
_femur = I.P("M80 300 L104 316 L96 340", "none", I.RED, 5) + I.t(40, 330, "deformidad", I.RED, 10.5, "start")
S("red", "CIR-156", "politrauma-shock-hemorragico-fractura-femur-reanimar-antes-de-referir",
  "Politrauma en shock lejos del hospital: reanimar y controlar el sangrado antes de trasladar",
  "Trauma · shock hemorrágico en el primer nivel", ESP,
  ("Shock hemorrágico en el politraumatizado", ["La prioridad es oxigenar, reponer volumen y parar el sangrado.",
                                                "Un traslado largo con el paciente sin reanimar puede ser mortal."]),
  ("Varón de 27 años, accidente de tránsito", ["Centro de salud a 3 h del hospital; PA 80/50, FC 132, SatO₂ 86 %.",
                                               "Múltiples heridas y deformidad del fémur derecho."]),
  ["Primero: oxígeno, dos vías con cristaloides tibios y control del sangrado (compresión, férula del fémur).",
   "Una fractura de fémur puede sangrar 1-1,5 L: alinearla y ferularla reduce la pérdida.",
   "Referir acompañado una vez iniciada la reanimación; no esperar exámenes."],
  ATLS + "; MINSA, norma de referencia.",
  d=dict(rotulo="Qué se hace antes de referir", caso="I-3", destino="II-2", flecha="Referir reanimado", tag="ESTE CASO",
         claves=[("Oxígeno + cristaloides + control del sangrado", ["Es la conducta inicial en el establecimiento."], True),
                 ("Férula del fémur", ["Parte del control del sangrado, no lo único."], False),
                 ("Observar o solo exámenes", ["Pierde tiempo mientras el paciente se desangra."], False)]),
  banda=B("Fuentes de sangrado", D(lambda s, x, y: I.cuerpo(s, x + 30, y, {"muslo_d": "#fecaca"}, extra=_femur,
                                                            marcas=[(1, 100, 300), (2, 120, 190)], sc=0.75), 240, 334),
          ["Fractura del fémur derecho: puede perder 1-1,5 L en el muslo.", "Heridas múltiples y posible sangrado interno.",
           "Shock (PA 80/50, FC 132): reanimar antes y durante el traslado."], ans=0),
  tabla=("Opciones de la pregunta", [("O₂ + cristaloides + control", True), ("Férula y referir", False),
                                     ("Collarín, férula y exámenes", False), ("Observar", False)],
         [("Problema", ["Ninguno", "No reanima el shock", "No reanima y retrasa", "Deja morir"])]))

# CIR-157 · Cáncer gástrico T4a · ANATOMÍA (capas)
S("anatomia", "CIR-157", "cancer-gastrico-t4a-serosa-pronostico-adyuvancia",
  "Cáncer gástrico: la invasión hasta la serosa (T4a) es lo que más pesa",
  "Cáncer gástrico · estadificación TNM", ESP,
  ("Estadificación del cáncer gástrico", ["La T (profundidad en la pared) es el factor que más pesa en el pronóstico.",
                                          "Más profundidad = más riesgo de ganglios y de siembra peritoneal."]),
  ("Varón de 55 años, gastrectomía subtotal", ["Borrmann III de 4,5 cm, invade hasta la serosa (T4a).",
                                               "Ganglios 2/20 (N1), borde libre, metaplasia intestinal vecina."]),
  ["T4a (serosa) = enfermedad localmente avanzada: peor pronóstico e indicación de adyuvancia.",
   "El tamaño, la localización y la metaplasia vecina no cambian el estadio.",
   "Lo ideal en T ≥ 2 o N+ es la quimioterapia perioperatoria (FLOT)."],
  "AJCC 8.ª ed.; NCCN, cáncer gástrico (2024).",
  d=dict(rotulo="Hasta dónde llega el tumor en la pared", tag="ESTE CASO",
         ilu_titulo="Pared del estómago",
         ilu=lambda s, x, y: I.pared_capas(s, x + 20, y + 10, invade=5,
                                             etiquetas_t=[(0, "T1a"), (2, "T1b"), (3, "T2"), (4, "T3"), (5, "T4a")], sc=1.15),
         ilu_pie="El tumor (naranja) atraviesa todas las capas y llega a la serosa: T4a.",
         ans=5,
         puntos=[("T1a", ["Mucosa."]), ("T1b", ["Submucosa."]), ("T2", ["Muscular propia."]), ("T3", ["Subserosa."]),
                 ("T4a", ["Serosa: este caso; riesgo de siembra peritoneal."])],
         signo=dict(titulo="Por qué la T manda",
                    lines=["Cada capa que atraviesa el tumor aumenta el riesgo de ganglios y de metástasis peritoneales.",
                           "Con T4a y N1 se indica quimioterapia (idealmente perioperatoria) además de la cirugía."])),
  tabla=("Opciones de la pregunta", [("Metaplasia intestinal", False), ("Localización en cuerpo", False),
                                     ("Invasión hasta serosa", True), ("Tamaño > 4 cm", False)],
         [("¿Cambia el estadio TNM?", ["No", "No", "Sí: T4a", "No"])]))
