"""Entrega 1 · tanda 01 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, AAP, OMS, IDSA, ADA

CC = " · Wikimedia Commons · "


def ITU(caso, porque, conducta):
    """Clasificación clínica de la infección urinaria (EAU 2024)."""
    return dict(nombre="Clasificación de la infección urinaria", orden=True,
                que="Guía EAU 2024: separa la infección baja, la alta y la complicada para elegir dónde y cómo tratar.",
                grados=[("Sin síntomas", "Bacteriuria asintomática", ["Urocultivo positivo sin síntomas", "Tratar solo en gestantes y antes de cirugía urológica"]),
                        ("ITU baja", "Cistitis", ["Disuria, polaquiuria, urgencia", "Sin fiebre ni dolor lumbar"]),
                        ("ITU alta", "Pielonefritis", ["Fiebre, escalofríos", "Dolor lumbar, puño percusión (+)", "Náuseas y vómitos"]),
                        ("Grave", "Urosepsis", ["Hipotensión o falla de órganos", "Obstrucción o absceso"])],
                caso=caso, porque=porque, conducta=conducta)


# GIN-007 · Pielonefritis en la gestante · ÁRBOL + clasificación de la ITU
S("arbol", "GIN-007", "Gestante de 30 semanas con fiebre, vómitos y puño percusión lumbar positiva: pielonefritis aguda",
  "Infección urinaria en el embarazo",
  ("Pielonefritis aguda en el embarazo", ["La complicación médica grave más frecuente del embarazo: la progesterona dilata los uréteres.",
                                          "Riesgo de parto pretérmino, sepsis y SDRA."]),
  ("Gestante de 30 semanas", ["Dolor lumbar bilateral súbito, fiebre, anorexia, náuseas y vómitos.", "Puño percusión lumbar positiva."]),
  ["Hospitalizar: urocultivo, hemograma, función renal; ceftriaxona EV hasta 48 h afebril y completar 10-14 días por vía oral.",
   "Después, profilaxis (nitrofurantoína o cefalexina) hasta el parto y urocultivos mensuales.",
   "En toda gestante se busca y trata la bacteriuria asintomática para prevenir la pielonefritis."],
  ACOG + ", Urinary tract infections in pregnant individuals (2023); " + MINSA + "; " + WILLIAMS + ".",
  op=("¿Encaja?", ["No: dolor pélvico súbito, sin fiebre urinaria", "No: sin fiebre ni dolor lumbar", "No: dolor en fosa ilíaca derecha",
                   "Sí: fiebre + dolor lumbar + puño percusión", "No: cólico sin fiebre"],
      {0: "Quiste de ovario torcido"}),
  arbol=Q("Gestante con síntomas urinarios: ¿fiebre, dolor lumbar o puño percusión (+)?", [
      L("Sí (este caso)", "PIELONEFRITIS AGUDA", ["Hospitalizar; ceftriaxona EV", "Vigilar contracciones y sepsis"], path=True),
      Q("¿Disuria y polaquiuria?", [
          L("Sí", "Cistitis", ["Nitrofurantoína o cefalexina 7 días", "Urocultivo de control"]),
          L("No, solo urocultivo +", "Bacteriuria asintomática", ["Tratar siempre en la gestante"])], edge="No")], path=True),
  escala=ITU(2, [("Fiebre, vómitos y dolor lumbar bilateral", True), ("Puño percusión lumbar positiva", True),
                 ("Sin hipotensión ni falla de órganos descrita: aún no es urosepsis", False)],
             "Gestante con pielonefritis: hospitalizar, ceftriaxona EV y profilaxis hasta el parto."))

# OFT-003 · Glaucoma congénito · TARJETAS + tríada
S("tarjetas", "OFT-003", "Recién nacido con epífora, fotofobia, córnea opaca y presión ocular alta: glaucoma congénito, goniotomía",
  "Oftalmología pediátrica · glaucoma congénito",
  ("Glaucoma congénito primario", ["Mal desarrollo del ángulo (trabéculo): el humor acuoso no sale y sube la presión.",
                                   "El ojo del bebé se estira: córnea grande y opaca (buftalmos)."]),
  ("Recién nacido de 2 semanas", ["Epífora, fotofobia y córnea sin brillo.", "Presión intraocular alta; nervio óptico muy excavado."]),
  ["El tratamiento es quirúrgico: goniotomía o trabeculotomía; los colirios solo bajan la presión mientras se opera.",
   "Toda córnea grande u opaca con lagrimeo en un lactante se deriva urgente a oftalmología.",
   "La obstrucción del conducto lagrimal da epífora sin fotofobia ni córnea opaca."],
  "Childhood Glaucoma Research Network / World Glaucoma Association, consenso de glaucoma infantil (2013, act.); AAO, EyeWiki (2024).",
  op=("¿Indicado?", ["No: es para glaucoma del adulto", "Sí: abre el ángulo mal formado", "No: es para obstrucción lagrimal",
                     "No: es para cierre angular", "No: solo ayuda hasta operar"],
      {2: "Cirugía de la vía lagrimal", 4: "Timolol de por vida como único tratamiento"}),
  d=dict(rotulo="Ojo que lagrimea en un recién nacido", ans=0,
         cards=[dict(titulo="Glaucoma congénito", datos=[("Córnea", "Grande y opaca", True), ("Fotofobia", "Sí", True),
                                                       ("Presión", "Alta", True)], pie="Este caso: goniotomía."),
                dict(titulo="Obstrucción lagrimal", datos=[("Córnea", "Normal", False), ("Fotofobia", "No", False),
                                                         ("Signo", "Secreción al presionar el saco", False)], pie="Masaje; sondaje si persiste."),
                dict(titulo="Conjuntivitis neonatal", datos=[("Ojo", "Rojo con secreción", False), ("Inicio", "Primeros días", False),
                                                           ("Causa", "Clamidia, gonococo", False)], pie="Tratar con antibiótico."),
                dict(titulo="Queratitis o trauma", datos=[("Córnea", "Úlcera o lesión", False), ("Presión", "Normal", False),
                                                        ("Antes", "Trauma del parto", False)], pie="Fluoresceína.")]),
  triada=TR([("Epífora", "Lagrimeo", True), ("Fotofobia", "Presente", True), ("Blefaroespasmo", "No se menciona", False)],
            [("Tríada del glaucoma congénito", 0, 2)],
            "Con córnea opaca y presión alta, no hace falta el tercer signo: es glaucoma congénito."))

# INF-004 · Chancro sifilítico con RPR negativo · ÁRBOL + estadios de la sífilis
S("arbol", "INF-004", "Úlcera genital única e indolora de 7 días con RPR negativo: chancro sifilítico",
  "Infecciones de transmisión sexual · úlcera genital",
  ("Sífilis primaria (chancro)", ["Treponema pallidum: úlcera única, indolora, de bordes duros y fondo limpio, a las 3 semanas del contagio.",
                                  "Las pruebas no treponémicas (RPR, VDRL) pueden salir negativas en las primeras semanas."]),
  ("Mujer de 30 años, trabajadora sexual", ["Úlcera indolora en el labio menor izquierdo desde hace 7 días; flujo amarillento.",
                                            "RPR negativo; control de hace 3 meses normal."]),
  ["RPR negativo no descarta el chancro: prueba treponémica rápida y repetir el RPR en 2-4 semanas.",
   "Tratar ya (manejo sindrómico): penicilina G benzatina 2,4 millones UI IM dosis única; tratar a las parejas.",
   "Herpes: varias vesículas dolorosas; chancroide: úlceras dolorosas con bubón supurado."],
  "CDC, Sexually transmitted infections treatment guidelines (2021, act. 2024); " + MINSA + ", guía de manejo de ITS (2024); " + OMS + ".",
  op=("¿Encaja?", ["No: vesículas dolorosas múltiples", "Sí: úlcera única indolora", "No: es un quiste, no una úlcera",
                   "No: no produce úlcera", "No: úlcera dolorosa con bubón"]),
  arbol=Q("Úlcera genital: ¿es dolorosa?", [
      L("No: única e indolora (este caso)", "CHANCRO SIFILÍTICO", ["Prueba treponémica rápida", "Penicilina benzatina 2,4 M UI"], path=True),
      Q("¿Vesículas agrupadas?", [L("Sí", "Herpes genital", ["Aciclovir o valaciclovir"]),
                                  L("No: úlcera sucia y bubón", "Chancroide", ["Azitromicina o ceftriaxona"])], edge="Sí")], path=True),
  escala=dict(nombre="Estadios de la sífilis", orden=True,
              que="Clasificación clínica (CDC 2021): define el tratamiento y el seguimiento.",
              grados=[("Temprana", "Primaria", ["Chancro indoloro", "3 semanas tras el contagio", "RPR puede ser negativo"]),
                      ("Temprana", "Secundaria", ["Exantema en palmas y plantas", "Condilomas planos", "RPR alto"]),
                      ("Latente", "Sin síntomas", ["Solo serología", "Temprana < 1 año; tardía > 1 año"]),
                      ("Tardía", "Terciaria", ["Gomas, aortitis", "Neurosífilis (en cualquier etapa)"])],
              caso=0, porque=[("Úlcera única e indolora de 7 días: chancro", True),
                              ("RPR negativo: aún no seroconvierte (ventana), no descarta", False)],
              conducta="Sífilis primaria: penicilina G benzatina 2,4 M UI IM dosis única; RPR a los 6 y 12 meses."))

# END-003 · Tormenta tiroidea · EMBUDO + escala de Burch-Wartofsky
S("embudo", "END-003", "Hipertiroidea con fiebre de 39,5 °C, FC 130 y confusión: tormenta tiroidea",
  "Emergencias tiroideas · tormenta tiroidea",
  ("Tormenta tiroidea", ["Tirotoxicosis descompensada con falla de órganos: fiebre, taquicardia, agitación o confusión.",
                         "Mortalidad de 10-30 %: se trata sin esperar el laboratorio."]),
  ("Mujer de 35 años", ["6 meses de nerviosismo y palpitaciones; hoy, confusión intensa.",
                        "PA 160/80, FC 130, 39,5 °C, exoftalmos y bocio (Graves)."]),
  ["Tratar ya: propranolol, tionamida (metimazol o propiltiouracilo), luego yodo (1 hora después) e hidrocortisona.",
   "Enfriar con medios físicos y paracetamol (no aspirina: libera hormona de su proteína).",
   "Buscar el desencadenante: infección, cirugía, abandono del tratamiento, yodo."],
  "American Thyroid Association, guía de hipertiroidismo (2016); Japan Thyroid Association, guía de crisis tirotóxica (2016); " + HARRISON + ".",
  op=("¿Encaja?", ["No: da hipotiroidismo", "Sí: hipertiroidismo + fiebre + confusión", "No: anciano sin síntomas adrenérgicos",
                   "Es la base, pero hay falla de órganos", "No: no da exoftalmos ni bocio"]),
  d=dict(rotulo="Hipertiroidea grave: ¿qué es?", inicio="Hipertiroidea con fiebre, taquicardia y confusión",
         candidatos=["Tiroiditis de Hashimoto", "Feocromocitoma", "Tirotoxicosis apática", "Hipertiroidismo", "Tormenta tiroidea"],
         pasos=[("¿Hipotiroidismo o sin exoftalmos ni bocio?", ["Tiroiditis de Hashimoto", "Feocromocitoma"]),
                ("¿Sin fiebre ni alteración del sensorio?", ["Tirotoxicosis apática", "Hipertiroidismo"])],
         final=("TORMENTA TIROIDEA", ["Burch-Wartofsky ≥ 45"]),
         nota="Fiebre + confusión en un hipertiroideo: tormenta."),
  escala=dict(nombre="Escala de Burch-Wartofsky", modo="puntaje",
              que="Suma puntos por fiebre, sistema nervioso, aparato digestivo, frecuencia cardiaca, falla cardiaca y desencadenante.",
              items=[("T°", "Temperatura (5 a 30)", "39,5 °C → rango 39,4-39,9", 25),
                     ("SNC", "Sistema nervioso (10 a 30)", "Confusión intensa: delirio", 20),
                     ("FC", "Frecuencia cardiaca (5 a 25)", "130 lpm → rango 130-139", 20),
                     ("GI", "Digestivo o hepático (10 a 20)", "No se mencionan vómitos ni ictericia", None),
                     ("IC", "Insuficiencia cardiaca o FA (5 a 25)", "No se describen", None),
                     ("Des", "Desencadenante (0 o 10)", "No se menciona", None)],
              total_txt="Total: 65 puntos",
              rangos=[("< 25", "Tormenta improbable", "Tratar el hipertiroidismo"), ("25-44", "Tormenta inminente", "Vigilar y tratar"),
                      ("≥ 45", "Tormenta tiroidea", "Tratamiento de emergencia")],
              caso_rango=2, porque=[("Con solo 3 datos ya supera los 45 puntos", True)],
              conducta="Propranolol, metimazol o PTU, yodo 1 h después, hidrocortisona y medios físicos; buscar el desencadenante."))

# GAS-003 · Dolor de pancreatitis crónica · TERMÓMETRO (escalera)
S("termometro", "GAS-003", "Pancreatitis crónica con dolor continuo que no cede a analgésicos: bloqueo del plexo celíaco",
  "Páncreas · pancreatitis crónica",
  ("Dolor en la pancreatitis crónica", ["Es el síntoma principal: por inflamación de nervios y aumento de presión en el conducto.",
                                        "Se maneja en escalones: dejar el alcohol y el tabaco, analgésicos, y luego técnicas invasivas."]),
  ("Varón de 56 años, alcohólico", ["Pancreatitis crónica con dolor intenso y continuo de 6 meses.", "No cede con analgésicos."]),
  ["Dolor refractario sin obstrucción tratable del conducto: bloqueo del plexo celíaco (guiado por ecoendoscopía).",
   "Si el conducto de Wirsung está dilatado u obstruido por cálculos: litotricia y endoscopia, o cirugía de drenaje temprana.",
   "Los opioides crónicos generan dependencia; la pancreatectomía total es el último recurso."],
  "HaPanEU/UEG, guía de pancreatitis crónica (2017); ESGE, tratamiento endoscópico de la pancreatitis crónica (2019, act. 2024); " + HARRISON + ".",
  op=("¿Indicado ahora?", ["Sí: dolor refractario a analgésicos", "No: ya fallaron los analgésicos", "No: dependencia; último recurso",
                           "Solo si hay estenosis del conducto", "No: último recurso"],
      {0: "Bloqueo neuronal visceral", 1: "Inhibidores de la COX-2", 2: "Opioides de larga duración", 3: "Endoprótesis",
       4: "Pancreatectomía total"}),
  d=dict(rotulo="Escalera del dolor en la pancreatitis crónica", caso_nivel=2, ruta_titulo="En este caso", paso_label="ESTE CASO",
         niveles=[("Medidas base", "Siempre", ["Dejar alcohol y tabaco", "Enzimas pancreáticas"]),
                  ("Analgésicos", "Paracetamol, AINE", ["Opioide débil (tramadol)"]),
                  ("Bloqueo celíaco", "Dolor refractario", ["Sin obstrucción del conducto"]),
                  ("Endoscopia", "Conducto obstruido", ["O cirugía de drenaje"])],
         pasos=[(1, "Fallaron los analgésicos", ["Dolor continuo 6 meses"], False),
                (2, "Bloqueo del plexo celíaco", ["Guiado por ecoendoscopía"], True),
                (3, "Estudiar el conducto", ["Si hay cálculos o estenosis: endoscopia"], False)]))

# PED-007 · Vacunas del recién nacido · ÁRBOL
S("arbol", "PED-007", "Recién nacido sano de 2700 g nacido en casa: vacunas BCG y hepatitis B",
  "Inmunizaciones · esquema nacional de vacunación",
  ("Vacunas del recién nacido", ["El esquema nacional indica dos vacunas al nacer: BCG y hepatitis B (HvB).",
                                 "La HvB idealmente en las primeras 12 horas (máximo 7 días); evita la transmisión vertical."]),
  ("Recién nacido de 8 horas", ["Parto domiciliario; 2700 g, examen normal.", "En alojamiento conjunto con la madre."]),
  ["BCG intradérmica en el deltoides derecho + HvB intramuscular en el muslo, en la primera atención.",
   "Con peso < 2000 g: la HvB se pone igual (si está estable); la BCG espera a que llegue a 2000 g.",
   "A los 2 meses empiezan pentavalente, polio, neumococo y rotavirus."],
  MINSA + ", NTS de esquema nacional de vacunación (2024); " + OMS + ", posición sobre BCG (2018) y hepatitis B (2017).",
  op=("¿Corresponde al RN?", ["Sí: al nacer", "No: desde los 2 meses", "No: polio oral ya no se usa; SPR al año",
                              "No: DPT de refuerzo y VPH en escolares", "No: desde los 2 meses"]),
  arbol=Q("Recién nacido: ¿pesa 2000 g o más y está estable?", [
      L("Sí: 2700 g, sano (este caso)", "BCG + HEPATITIS B", ["En la primera atención, antes del alta",
                                                               "HvB ideal < 12 horas"], path=True),
      L("No: < 2000 g", "HvB si está estable", ["BCG cuando llegue a 2000 g"])], path=True))

# PSI-002 · Trastorno de pánico · EMBUDO + criterios DSM-5-TR
S("embudo", "PSI-002", "Seis crisis súbitas en 2 meses de palpitaciones, disnea, temblor y miedo a morir con ECG normal: trastorno de pánico",
  "Trastornos de ansiedad · trastorno de pánico",
  ("Trastorno de pánico", ["Crisis de miedo intenso que llegan a su máximo en minutos, inesperadas y repetidas.",
                           "Luego, preocupación por tener otra crisis o cambios de conducta por más de 1 mes."]),
  ("Mujer de 25 años", ["Palpitaciones, falta de aire, temblor, miedo a morir, parestesias y dolor en el pecho.",
                        "6 episodios en 2 meses; gases arteriales y ECG normales."]),
  ["Descartar causas médicas (ECG, glucosa, TSH) antes de etiquetar.",
   "Tratamiento: terapia cognitivo-conductual e ISRS (sertralina, escitalopram); benzodiacepinas solo por poco tiempo.",
   "El hipertiroidismo da síntomas continuos, no crisis con ECG y análisis normales entre episodios."],
  "APA, DSM-5-TR (2022); NICE, Generalised anxiety disorder and panic disorder in adults (CG113, act. 2020); " + HARRISON + ".",
  op=("¿Encaja?", ["No: síntomas psicóticos negativos", "No: episodios de manía o depresión", "Sí: crisis recurrentes con miedo a morir",
                   "No: no es un diagnóstico; es un síntoma", "No: síntomas continuos, no en crisis"]),
  d=dict(rotulo="Crisis de síntomas físicos con miedo", inicio="Crisis de palpitaciones, disnea y miedo a morir",
         candidatos=["Hipertiroidismo", "Esquizofrenia simple", "Trastorno bipolar", "Agitación psicomotriz", "Trastorno de pánico"],
         pasos=[("¿Causa médica en ECG o análisis?", ["Hipertiroidismo"]),
                ("¿Psicosis, manía o solo un síntoma?", ["Esquizofrenia simple", "Trastorno bipolar", "Agitación psicomotriz"])],
         final=("TRASTORNO DE PÁNICO", ["Crisis inesperadas y repetidas"]),
         nota="Crisis repetidas con exámenes normales: pánico."),
  escala=dict(nombre="Ataque de pánico (DSM-5-TR)", modo="puntaje",
              que="Hacen falta 4 o más de 13 síntomas que lleguen a su máximo en minutos.",
              items=[("1", "Palpitaciones o taquicardia", "Sí", 1), ("2", "Sensación de falta de aire", "Sí", 1),
                     ("3", "Temblor", "Sí", 1), ("4", "Miedo a morir", "Sí", 1), ("5", "Parestesias", "Sí", 1),
                     ("6", "Dolor o molestia en el pecho", "Sí", 1),
                     ("+7", "Sudor, náuseas, mareo, escalofríos, ahogo, desrealización, miedo a enloquecer", "No se mencionan", None)],
              total_txt="Total: 6 de 13 síntomas",
              rangos=[("< 4 síntomas", "Ataque limitado", "No cumple ataque de pánico"),
                      ("≥ 4 síntomas", "Ataque de pánico", "Si se repiten y hay preocupación ≥ 1 mes: trastorno de pánico")],
              caso_rango=1, porque=[("6 crisis en 2 meses con exámenes normales: trastorno de pánico", True)],
              conducta="Terapia cognitivo-conductual + ISRS; benzodiacepina solo como puente corto."))

# PED-008 · Tapón meconial · ÁRBOL
S("arbol", "PED-008", "Recién nacido de 24 horas sin meconio, distensión leve y ano permeable: tapón meconial",
  "Obstrucción intestinal neonatal",
  ("Retraso en la eliminación de meconio", ["El 99 % de los recién nacidos a término elimina meconio en las primeras 48 horas.",
                                            "Primero se mira el ano; si es permeable, el enema de contraste orienta la causa."]),
  ("Recién nacido de 24 horas", ["No ha eliminado meconio.", "Distensión abdominal discreta; ano permeable."]),
  ["Tapón meconial: el enema de contraste muestra el tapón y además lo expulsa (diagnóstico y tratamiento).",
   "Si persiste el estreñimiento tras el tapón: biopsia rectal para descartar Hirschsprung; considerar fibrosis quística.",
   "Íleo meconial (fibrosis quística): microcolon y obstrucción en el íleon."],
  "APSA, enfermedad de Hirschsprung (2020); " + NELSON + ".",
  op=("¿Más probable a las 24 h?", ["Posible: si persiste, biopsia rectal", "Posible: íleo meconial con microcolon",
                                    "No: no se presenta así en el primer día", "Sí: lo más frecuente con ano permeable",
                                    "No: el ano es permeable"]),
  arbol=Q("RN sin meconio: ¿el ano es permeable?", [
      L("No", "Malformación anorrectal", ["Cirugía pediátrica"]),
      Q("¿Enema de contraste?", [
          L("Tapón que sale (este caso)", "TAPÓN MECONIAL", ["El enema lo expulsa", "Vigilar deposiciones"], path=True),
          L("Zona de transición", "Hirschsprung", ["Biopsia rectal"]),
          L("Microcolon", "Íleo meconial", ["Buscar fibrosis quística"])], edge="Sí", path=True)], path=True))

# NEF-003 · Pielonefritis aguda · TARJETAS + clasificación
S("tarjetas", "NEF-003", "Fiebre, escalofríos, dolor lumbar derecho y nitritos positivos: pielonefritis aguda",
  "Infecciones del tracto urinario",
  ("Pielonefritis aguda", ["Infección del riñón por bacterias que suben desde la vejiga (E. coli en el 80 %).",
                           "Fiebre y dolor lumbar la separan de la cistitis."]),
  ("Mujer de 36 años", ["6 días de escalofríos, alza térmica, náuseas y dolor lumbar derecho.", "T 38,5 °C; orina con nitritos."]),
  ["Urocultivo antes del antibiótico; ceftriaxona o ciprofloxacino (si resistencia local < 10 %) por 7 días (o 10-14 con betalactámico).",
   "Hospitalizar si vomita, está séptica, embarazada o no mejora en 48-72 h; ecografía si no mejora (obstrucción, absceso).",
   "Nitritos (+): enterobacterias que convierten nitratos; la leucocituria apoya la infección."],
  "EAU, guía de infecciones urológicas (2024); IDSA, pielonefritis no complicada (2011, act.); " + HARRISON + ".",
  op=("¿Encaja?", ["No: sin fiebre ni dolor lumbar", "No: flujo vaginal", "Sí: fiebre + dolor lumbar + nitritos",
                   "No: secreción uretral, disuria", "No: dolor en fosa ilíaca derecha"]),
  d=dict(rotulo="Infección urinaria: ¿alta o baja?", ans=0,
         cards=[dict(titulo="Pielonefritis", datos=[("Fiebre", "38,5 °C, escalofríos", True), ("Dolor", "Lumbar derecho", True),
                                                  ("Orina", "Nitritos (+)", True)], pie="Este caso."),
                dict(titulo="Cistitis", datos=[("Fiebre", "No", False), ("Dolor", "Suprapúbico", False),
                                             ("Síntomas", "Disuria, polaquiuria", False)], pie="Nitrofurantoína 5 días."),
                dict(titulo="Uretritis", datos=[("Secreción", "Uretral", False), ("Germen", "Gonococo, clamidia", False),
                                              ("Fiebre", "No", False)], pie="ITS: tratar a la pareja."),
                dict(titulo="Vaginitis", datos=[("Flujo", "Anormal", False), ("Prurito", "Vulvar", False),
                                              ("Orina", "Normal", False)], pie="Examen con espéculo.")]),
  escala=ITU(2, [("Fiebre de 38,5 °C con escalofríos", True), ("Dolor lumbar derecho y nitritos (+)", True),
                 ("Sin hipotensión ni falla de órganos: no es urosepsis", False)],
             "Pielonefritis no complicada: urocultivo y antibiótico 7 días; hospitalizar si vomita o empeora."))

# END-004 · Diagnóstico de diabetes: PTOG · MATRIZ + criterios ADA
S("matriz", "END-004", "Obesa con poliuria, polifagia y padres diabéticos: la prueba de tolerancia oral a la glucosa evalúa la secreción de insulina",
  "Diabetes mellitus · pruebas diagnósticas",
  ("Pruebas para diagnosticar diabetes", ["Glucosa en ayunas, PTOG (75 g), HbA1c o glucosa al azar con síntomas.",
                                          "La PTOG mide cómo responde el páncreas a una carga de glucosa."]),
  ("Mujer de 48 años, obesa", ["2 meses de poliuria y polifagia.", "Padres diabéticos."]),
  ["La PTOG es dinámica: obliga a la célula beta a secretar insulina al máximo; detecta más casos tempranos.",
   "El péptido C y la insulina en ayunas miden la secreción basal, no la máxima.",
   "Con síntomas clásicos, una glucosa al azar ≥ 200 mg/dL ya diagnostica."],
  ADA + "; " + MINSA + ", guía de diabetes tipo 2 (2024).",
  op=("¿Valora la secreción máxima?", ["No: es un valor basal", "No: secreción basal", "Sí: estímulo con 75 g de glucosa",
                                       "No: promedio de 3 meses", "No: valor basal"]),
  d=dict(rotulo="¿Qué mide cada prueba?", eje_x="Momento", eje_y="Prueba",
         cols=["En ayunas (basal)", "Tras un estímulo"], rows=["Glucosa", "Insulina / péptido C", "HbA1c"], caso=(0, 1),
         cells=[[("Glucosa en ayunas", ["≥ 126: diabetes"]), ("PTOG 75 g", ["2 h ≥ 200: diabetes", "Secreción máxima"])],
                [("Insulina, péptido C", ["Reserva basal", "Útil en tipo 1"]), ("Péptido C estimulado", ["Uso en investigación"])],
                [("HbA1c", ["≥ 6,5 %: diabetes", "Promedio de 3 meses"]), ("No aplica", ["No se estimula"])]]),
  escala=dict(nombre="Criterios diagnósticos ADA 2026", orden=True, que="Cualquiera de las pruebas, confirmada en otra muestra salvo síntomas claros.",
              grados=[("Normal", "Sin alteración", ["Ayunas < 100 mg/dL", "PTOG 2 h < 140", "HbA1c < 5,7 %"]),
                      ("Prediabetes", "Riesgo alto", ["Ayunas 100-125", "PTOG 2 h 140-199", "HbA1c 5,7-6,4 %"]),
                      ("Diabetes", "Diagnóstico", ["Ayunas ≥ 126", "PTOG 2 h ≥ 200", "HbA1c ≥ 6,5 %", "Al azar ≥ 200 con síntomas"])],
              caso=None, porque_titulo="En este caso",
              porque=[("Síntomas, obesidad y padres diabéticos: riesgo muy alto", True),
                      ("Faltan los valores: se clasifica cuando llegue la glucosa, la PTOG o la HbA1c", False)],
              conducta="Pedir glucosa en ayunas o PTOG con 75 g y HbA1c; con síntomas, una glucosa al azar ≥ 200 basta."))

# PED-009 · Otitis media aguda · ÁRBOL + otoscopia real
S("arbol", "PED-009", "Lactante con resfrío que a los 3 días llora, está irritable y se coge la oreja: otitis media aguda",
  "Infecciones de vías respiratorias altas · otitis media",
  ("Otitis media aguda (OMA)", ["Infección del oído medio que suele seguir a un resfrío (la trompa de Eustaquio se tapa).",
                                "Neumococo, H. influenzae no tipificable y Moraxella."]),
  ("Lactante con rinorrea y tos", ["3 días después: irritable, llanto persistente.", "Se coge la oreja derecha por dolor."]),
  ["Diagnóstico: tímpano abombado (o otorrea) + inflamación; la otoscopia es obligatoria.",
   "Amoxicilina 80-90 mg/kg/día en menores de 2 años o si es grave; en mayores, sin gravedad, se puede observar 48-72 h.",
   "Analgesia siempre (paracetamol o ibuprofeno)."],
  AAP + ", Diagnosis and management of acute otitis media (2013, reafirmada); " + MINSA + "; " + NELSON + ".",
  op=("¿Encaja?", ["No: ganglio inflamado en el cuello", "No: dolor al mover el pabellón, sin resfrío previo",
                   "Sí: resfrío y luego otalgia e irritabilidad", "No: tumor óseo benigno", "Es la causa previa, no explica la otalgia"]),
  arbol=Q("Otalgia tras un resfrío: ¿tímpano abombado o con otorrea?", [
      Q("¿Menor de 2 años, bilateral o grave (fiebre ≥ 39 °C)?", [
          L("Sí: lactante (este caso)", "OMA: AMOXICILINA", ["80-90 mg/kg/día por 10 días", "Analgesia"], path=True),
          L("No", "Observar 48-72 h", ["Antibiótico si no mejora"])], edge="Sí", path=True),
      L("No", "Otitis media con efusión", ["Control; no antibiótico"])], path=True),
  banda=B("Otoscopia real de otitis media aguda", P("oma.jpg", 260, 260, [
            ("circulo", 0.6, 0.38, 0.2, "tímpano rojo,\nopaco y abombado", 0.5, 0.9)],
          credito="B. Welleschik" + CC + "CC BY-SA 3.0"),
          [("Tímpano rojo y abombado", "El pus empuja la membrana hacia afuera: es el signo que confirma la OMA."),
           ("Sin reflejo luminoso", "El tímpano sano es gris perla y brillante; aquí está opaco."),
           ("No basta con que esté rojo", "El llanto enrojece el tímpano: hace falta el abombamiento o la otorrea."),
           ("Si no mejora en 48-72 h", "Revisar el diagnóstico o cambiar a amoxicilina-clavulánico.")],
          pie="Otoscopia de otro paciente.", ans=0))

# NEU-002 · TEP de alto riesgo · ÁRBOL + estratificación ESC + ECG real
S("arbol", "NEU-002", "Obeso tras un viaje largo con disnea súbita, hipotensión y Homans positivo: TEP de alto riesgo, trombólisis con alteplasa",
  "Tromboembolismo pulmonar",
  ("Tromboembolismo pulmonar (TEP)", ["Un trombo de las venas de la pierna viaja y tapa la arteria pulmonar.",
                                      "Con hipotensión (choque) es de alto riesgo: hay que destaparla ya."]),
  ("Varón de 70 años, obeso mórbido", ["Viaje interprovincial; disnea súbita de 1 hora.", "Hipotenso; Homans (+) (trombosis de la pierna)."]),
  ["TEP de alto riesgo (hipotensión): trombólisis sistémica con alteplasa 100 mg en 2 horas, más heparina no fraccionada.",
   "Si la trombólisis está contraindicada o falla: embolectomía quirúrgica o por catéter.",
   "Sin hipotensión: anticoagular (HBPM o anticoagulante oral directo) y estratificar con PESIs, troponina y eco."],
  "ESC, guía de embolia pulmonar aguda (2019); AHA, scientific statement on PE (2025); " + HARRISON + ".",
  op=("¿Adecuada con hipotensión?", ["Sí: destapa la arteria", "No: antiagregante", "No: antiagregante",
                                     "No: tarda días en actuar", "No basta con hipotensión"],
      {4: "HBPM sola"}),
  arbol=Q("Sospecha de TEP: ¿hipotensión o choque?", [
      L("Sí (este caso)", "TEP DE ALTO RIESGO", ["Alteplasa 100 mg EV en 2 h + heparina", "Embolectomía si no se puede"], path=True),
      L("No", "Estratificar", ["PESIs, troponina, eco del VD", "Anticoagular"])], path=True),
  escala=dict(nombre="Riesgo de muerte precoz en el TEP (ESC)", orden=True,
              que="Guía ESC 2019: define quién recibe trombólisis.",
              grados=[("Bajo", "Riesgo bajo", ["PESIs 0", "VD normal, troponina normal", "Alta precoz posible"]),
                      ("Intermedio-bajo", "Intermedio-bajo", ["PESIs ≥ 1", "VD o troponina alterados (uno)"]),
                      ("Intermedio-alto", "Intermedio-alto", ["VD dilatado y troponina alta", "Vigilar: trombólisis si empeora"]),
                      ("Alto", "Alto riesgo", ["Hipotensión o choque", "Trombólisis"])],
              caso=3, porque=[("Hipotensión con disnea súbita: inestable", True), ("Factores de riesgo: viaje largo, obesidad, TVP (Homans +)", True)],
              conducta="Alteplasa EV + heparina no fraccionada; si está contraindicada, embolectomía."),
  banda=B("ECG real en un TEP", P("tep_ecg.jpg", 380, 188, [
            ("corchete", 0.06, 0.94, 0.12, "taquicardia regular ~150 por minuto")],
          credito="W. Serra et al." + CC + "CC BY 2.0"),
          [("Taquicardia sinusal", "Es el hallazgo más frecuente del TEP en el ECG."),
           ("Bloqueo de rama derecha", "El ventrículo derecho se sobrecarga al empujar contra la arteria tapada."),
           ("S1Q3T3", "Onda S en DI, Q y T negativa en DIII: clásico pero poco frecuente; un ECG normal no lo descarta.")],
          pie="ECG de otro paciente con TEP.", ans=0))

# SP-004 · Confidencialidad y autonomía · TARJETAS
S("tarjetas", "SP-004", "Publicar la foto de un paciente sin su consentimiento vulnera la autonomía (confidencialidad)",
  "Ética médica · principios bioéticos",
  ("Principios de la bioética", ["Autonomía, beneficencia, no maleficencia y justicia (Beauchamp y Childress).",
                                 "La confidencialidad y la intimidad derivan del respeto a la autonomía."]),
  ("Personaje público en emergencia", ["Llega grave tras un intento de suicidio.", "Un trabajador le toma una foto y la publica."]),
  ["El secreto profesional protege a todos los pacientes, también a los famosos (Ley General de Salud, art. 25; Código de Ética del CMP).",
   "Difundir datos o imágenes sin consentimiento es falta ética y puede ser delito.",
   "Beneficencia: hacer el bien; no maleficencia: no dañar; justicia: repartir los recursos con equidad."],
  "Ley General de Salud n.º 26842 (Perú), art. 15 y 25; Código de Ética y Deontología del Colegio Médico del Perú (2023).",
  op=("¿Es el principal?", ["También hay daño, pero no es el central", "Sí: decidir sobre su información e imagen",
                            "No: no se trata de hacer el bien", "No: no es reparto de recursos", "Falso: aplica a todos"],
      {4: "La confidencialidad no aplica a famosos"}),
  d=dict(rotulo="Los cuatro principios de la bioética", ans=0,
         cards=[dict(titulo="Autonomía", datos=[("Protege", "Decisiones e información", True), ("Incluye", "Confidencialidad", True),
                                              ("Aquí", "Foto sin permiso", True)], pie="Este caso."),
                dict(titulo="No maleficencia", datos=[("Protege", "No causar daño", False), ("Ejemplo", "Evitar iatrogenia", False),
                                                    ("Aquí", "Hay daño, es secundario", False)], pie="Primum non nocere."),
                dict(titulo="Beneficencia", datos=[("Protege", "Hacer el bien", False), ("Ejemplo", "Mejor tratamiento", False),
                                                 ("Aquí", "No aplica", False)], pie="Actuar en su beneficio."),
                dict(titulo="Justicia", datos=[("Protege", "Equidad", False), ("Ejemplo", "Reparto de recursos", False),
                                             ("Aquí", "No aplica", False)], pie="Igual trato.")]))

# PED-010 · Bronquitis aguda · EMBUDO
S("embudo", "PED-010", "Escolar con tos y fiebre de 4 días, roncantes difusos y sin dificultad respiratoria: bronquitis aguda",
  "Infecciones respiratorias agudas en pediatría",
  ("Bronquitis aguda", ["Inflamación de los bronquios grandes, casi siempre viral.",
                        "Tos con roncantes que cambian con la tos; sin taquipnea ni signos de neumonía."]),
  ("Escolar de 6 años", ["4 días de tos y fiebre; T 38,3 °C, FR 22.", "Roncantes en ambos campos, sin dificultad respiratoria."]),
  ["Tratamiento sintomático: líquidos, paracetamol; no antibióticos ni antitusígenos en niños.",
   "Neumonía: taquipnea (FR ≥ 40 en 1-5 años; ≥ 30 en mayores), crepitantes o tiraje.",
   "Bronquiolitis: menores de 2 años con sibilancias y crepitantes tras un resfrío."],
  OMS + ", AIEPI; " + MINSA + ", guía de infecciones respiratorias agudas; " + NELSON + ".",
  op=("¿Encaja?", ["Sí: roncantes, sin taquipnea", "No: sin hallazgos en el pulmón", "No: menores de 2 años",
                   "No: crepitantes y taquipnea", "No: soplo tubárico, taquipnea"]),
  d=dict(rotulo="Tos y fiebre en el escolar", inicio="Tos y fiebre de 4 días, FR 22",
         candidatos=["Bronquiolitis", "Rinofaringitis aguda", "Bronconeumonía", "Neumonía lobar", "Bronquitis aguda"],
         pasos=[("¿Menor de 2 años o solo síntomas de nariz y garganta?", ["Bronquiolitis", "Rinofaringitis aguda"]),
                ("¿Taquipnea, crepitantes o soplo tubárico?", ["Bronconeumonía", "Neumonía lobar"])],
         final=("BRONQUITIS AGUDA", ["Roncantes sin taquipnea"]),
         nota="FR normal y sin crepitantes: no es neumonía."))

# REU-004 · Urticaria aguda con angioedema · TARJETAS + clasificación + foto real
S("tarjetas", "REU-004", "Primera vez con ronchas fugaces que pican en todo el cuerpo y edema de cara: urticaria aguda",
  "Dermatología · urticaria y angioedema",
  ("Urticaria aguda", ["Habones (ronchas) que pican y desaparecen en menos de 24 horas sin dejar marca.",
                       "Puede acompañarse de angioedema (edema profundo de cara, labios o párpados)."]),
  ("Varón de 52 años", ["Primera vez: habones pruriginosos fugaces en todo el cuerpo.", "Placa edematosa amplia en la cara."]),
  ["Tratamiento: antihistamínico H1 de segunda generación (cetirizina, loratadina); se puede subir hasta 4 veces la dosis.",
   "Corticoide oral por pocos días solo si es intensa; adrenalina IM si hay compromiso de vía aérea o hipotensión (anafilaxia).",
   "Buscar el desencadenante: fármacos (AINE, antibióticos), alimentos, infecciones."],
  "EAACI/GA²LEN/EuroGuiDerm/APAAACI, guía internacional de urticaria (2022); " + HARRISON + ".",
  op=("¿Encaja?", ["No: lesiones > 24 h, dolorosas, dejan mancha", "No: lesiones en diana", "No: angioedema sin habones, desde joven",
                   "Sí: habones fugaces + angioedema", "No: eccema en la zona de contacto"]),
  d=dict(rotulo="Ronchas que pican: ¿qué es?", ans=0,
         cards=[dict(titulo="Urticaria aguda", datos=[("Lesión", "Habón fugaz < 24 h", True), ("Prurito", "Intenso", True),
                                                    ("Tiempo", "< 6 semanas", True)], pie="Este caso."),
                dict(titulo="Vasculitis urticarial", datos=[("Lesión", "> 24 h", False), ("Síntoma", "Dolor o ardor", False),
                                                          ("Deja", "Mancha violácea", False)], pie="Biopsia."),
                dict(titulo="Eritema multiforme", datos=[("Lesión", "En diana", False), ("Dónde", "Palmas, plantas", False),
                                                       ("Causa", "Herpes", False)], pie="Fijo, no fugaz."),
                dict(titulo="Angioedema hereditario", datos=[("Habones", "No", False), ("Antihistamínico", "No responde", False),
                                                           ("Laboratorio", "C4 y C1-INH bajos", False)], pie="Familiar.")]),
  escala=dict(nombre="Clasificación de la urticaria", orden=False, que="Guía internacional 2022: por el tiempo de evolución.",
              grados=[("< 6 semanas", "Urticaria aguda", ["Suele tener desencadenante", "Fármacos, alimentos, infecciones"]),
                      ("≥ 6 semanas", "Urticaria crónica espontánea", ["Sin desencadenante claro", "Autoinmune en muchos casos"]),
                      ("≥ 6 semanas", "Urticaria crónica inducible", ["Por frío, presión, calor", "Dermografismo"])],
              caso=0, porque=[("Primera vez, lesiones fugaces de inicio reciente", True)],
              conducta="Antihistamínico H1 de segunda generación; adrenalina IM si hay compromiso de vía aérea o hipotensión."),
  banda=B("Habones de urticaria (foto real)", P("urticaria.jpg", 210, 280, [("circulo", 0.5, 0.45, 0.12, "habones", 0.05, 0.06)],
                                                 credito="Psixtras" + CC + "CC0"),
          [("Habón", "Pápula o placa roja y edematosa, de centro pálido, que cambia de forma."),
           ("Fugaz", "Cada lesión dura menos de 24 horas y no deja marca: si dura más, pensar en vasculitis."),
           ("Angioedema", "Si el edema es profundo (cara, labios, lengua), vigilar la vía aérea."),
           ("Prueba del vidrio", "El habón palidece al presionarlo; la púrpura de una vasculitis no.")],
          pie="Lesiones de otro paciente.", ans=0))

# SP-005 · Embarazo adolescente: intervención educativa continua · RADIAL
S("radial", "SP-005", "Deserción escolar por embarazo adolescente: intervención educativa continua en el colegio",
  "Salud pública · promoción de la salud en adolescentes",
  ("Promoción de la salud sexual del adolescente", ["La educación sexual integral sostenida reduce el embarazo adolescente.",
                                                    "Las charlas únicas no cambian conductas."]),
  ("Colegio junto al centro de salud", ["Más del 5 % de estudiantes de secundaria deja el colegio por embarazo cada año."]),
  ["Prioridad: intervención educativa continua (educación sexual integral) con los estudiantes, articulada con el colegio.",
   "Se complementa con servicios diferenciados para adolescentes en el centro de salud (orientación y anticonceptivos).",
   "Una charla única o capacitar solo a docentes no basta."],
  MINSA + ", norma técnica de atención integral de salud en la etapa de vida adolescente; UNESCO, orientaciones técnicas de educación sexual integral (2018).",
  op=("¿Es lo prioritario?", ["Útil, pero no llega a los alumnos", "No: no actúa sobre los adolescentes", "Complementa; no basta sola",
                              "Sí: sostenida en el tiempo", "No: no cambia conductas"],
      {0: "Capacitar a docentes en anticonceptivos"}),
  d=dict(rotulo="Intervención educativa continua", centro="EDUCACIÓN", centro_sub="continua", ans=0,
         items=[("CONTINUA", ["Todo el año, no una charla"]), ("INTEGRAL", ["Afectos, derechos, prevención"]),
                ("PARTICIPATIVA", ["Con estudiantes y padres"]), ("ARTICULADA", ["Colegio + centro de salud"]),
                ("SERVICIOS", ["Orientación y métodos en el EESS"])],
         ruta=["Diagnóstico en el colegio", "Plan educativo anual", "Servicios diferenciados", "Menos embarazos y deserción"]))

# GAS-004 · ERGE · ÁRBOL + clasificación de Los Ángeles
S("arbol", "GAS-004", "Pirosis y regurgitación que empeoran con café en un obeso, sin disfagia ni baja de peso: ERGE",
  "Esófago · enfermedad por reflujo gastroesofágico",
  ("Enfermedad por reflujo gastroesofágico (ERGE)", ["El contenido del estómago sube al esófago y causa síntomas o lesiones.",
                                                      "Pirosis y regurgitación son los síntomas típicos."]),
  ("Varón de 35 años, IMC 35", ["Un mes de pirosis, regurgitación ácida y tos nocturna; empeora con café.", "Sin disfagia ni baja de peso."]),
  ["Síntomas típicos sin alarma: IBP 8 semanas a prueba + bajar de peso, no comer tarde, elevar la cabecera.",
   "Signos de alarma (disfagia, baja de peso, sangrado, anemia, > 60 años): endoscopia primero.",
   "La endoscopia gradúa la esofagitis con Los Ángeles; Lyon 2.0 define la ERGE (grado C/D, Barrett, estenosis)."],
  "ACG, guía de ERGE (2022); Consenso de Lyon 2.0 (2023); " + HARRISON + ".",
  op=("¿Encaja?", ["No: disfagia y dolor torácico", "No: disfagia, halitosis, regurgitación de comida", "Sí: pirosis + regurgitación",
                   "No: disfagia a sólidos y líquidos", "No: disfagia e impactación, atopia"]),
  arbol=Q("Pirosis y regurgitación: ¿hay signos de alarma?", [
      L("No (este caso)", "ERGE: IBP 8 SEMANAS", ["Bajar de peso, evitar café", "Elevar la cabecera"], path=True),
      L("Sí", "Endoscopia", ["Disfagia, baja de peso, sangrado"])], path=True),
  escala=dict(nombre="Clasificación de Los Ángeles", orden=True, que="Gradúa la esofagitis por reflujo vista en la endoscopia.",
              grados=[("Grado A", "Leve", ["Erosiones < 5 mm"]), ("Grado B", "Leve", ["Erosiones > 5 mm", "Sin unirse entre pliegues"]),
                      ("Grado C", "Grave", ["Erosiones que se unen entre pliegues", "< 75 % de la circunferencia"]),
                      ("Grado D", "Grave", ["≥ 75 % de la circunferencia"])],
              caso=None, porque_titulo="En este caso",
              porque=[("Sin signos de alarma: no necesita endoscopia para empezar el tratamiento", True),
                      ("Por eso no tiene grado: se gradúa solo si se hace la endoscopia", False)],
              conducta="IBP 8 semanas + medidas de estilo de vida; endoscopia si no responde o aparece una alarma."))

# INF-005 · Neumocistosis en VIH · TARJETAS + infecciones por CD4 + Rx real
S("tarjetas", "INF-005", "VIH sin tratamiento con disnea progresiva, tos seca, infiltrado intersticial y DHL alta: neumonía por Pneumocystis",
  "VIH · infecciones oportunistas",
  ("Neumonía por Pneumocystis jirovecii (PCP)", ["Infección oportunista con CD4 < 200: disnea progresiva de semanas, tos seca y fiebre.",
                                                 "Rx con infiltrado intersticial bilateral (vidrio esmerilado) y DHL alta."]),
  ("Varón de 42 años con VIH", ["Abandonó el TAR; 2 semanas de disnea, fiebre y tos seca.", "Infiltrado intersticial en las bases; DHL elevada."]),
  ["Tratamiento: cotrimoxazol 21 días; prednisona si PaO₂ < 70 mmHg o gradiente A-a ≥ 35.",
   "Reiniciar el TAR en las primeras 2 semanas; profilaxis con cotrimoxazol mientras CD4 < 200.",
   "Diagnóstico: tinción o PCR en esputo inducido o lavado broncoalveolar."],
  "NIH/CDC/IDSA, guía de infecciones oportunistas en VIH (2024); " + MINSA + ", NTS de atención integral del adulto con VIH (2024).",
  op=("¿Encaja?", ["No: cuadro agudo de días, no de semanas", "Sí: disnea progresiva + intersticial + DHL", "No: cavitación o infiltrado apical",
                   "No: nódulos o cavidades", "No: lesiones de piel y derrame"]),
  d=dict(rotulo="Neumonía en el paciente con VIH", ans=0,
         cards=[dict(titulo="Pneumocystis", datos=[("CD4", "< 200", True), ("Rx", "Intersticial bilateral", True),
                                                 ("Labs", "DHL alta", True)], pie="Este caso: cotrimoxazol."),
                dict(titulo="Tuberculosis", datos=[("CD4", "Cualquiera", False), ("Rx", "Apical o miliar", False),
                                                 ("Síntomas", "Sudor, baja de peso", False)], pie="GeneXpert."),
                dict(titulo="Neumonía bacteriana", datos=[("Inicio", "Agudo", False), ("Rx", "Consolidación lobar", False),
                                                        ("Esputo", "Purulento", False)], pie="Neumococo."),
                dict(titulo="Sarcoma de Kaposi", datos=[("Piel", "Lesiones violáceas", False), ("Rx", "Nódulos, derrame", False),
                                                      ("Virus", "Herpes 8", False)], pie="TAR + quimioterapia.")]),
  escala=dict(nombre="Infecciones oportunistas según CD4", orden=True,
              que="Cuanto más bajan los CD4, aparecen infecciones más raras y graves.",
              grados=[("CD4 < 500", "Inmunidad algo baja", ["Tuberculosis", "Herpes zóster", "Candidiasis oral"]),
                      ("CD4 < 200", "Sida", ["Pneumocystis", "Profilaxis con cotrimoxazol"]),
                      ("CD4 < 100", "Muy baja", ["Toxoplasmosis cerebral", "Criptococosis"]),
                      ("CD4 < 50", "Extrema", ["Citomegalovirus", "Micobacterias atípicas (MAC)"])],
              caso=1, porque=[("Pneumocystis aparece con CD4 < 200: abandonó el TAR", True),
                              ("El cuadro de semanas con DHL alta apoya Pneumocystis", True)],
              conducta="Cotrimoxazol 21 días (+ prednisona si hay hipoxemia) y reiniciar el TAR en 2 semanas."),
  banda=B("Rx real de neumonía por Pneumocystis", P("pcp_rx.jpg", 300, 281, [
            ("flechas", [(0.27, 0.6), (0.75, 0.6)], 0.5, 0.94, "vidrio esmerilado en ambos pulmones")],
          credito="C. M. Allen et al." + CC + "CC BY 4.0"),
          [("Velo difuso en ambos pulmones", "Opacidad en vidrio esmerilado, sobre todo alrededor de los hilios y en las bases."),
           ("Sin consolidación ni derrame", "A diferencia de la neumonía bacteriana o el Kaposi."),
           ("Puede ser casi normal", "Al inicio la Rx engaña: si la sospecha es alta, TC de tórax."),
           ("Riesgo de neumotórax", "Puede formar quistes que se rompen.")],
          pie="Rx de otro paciente con el mismo diagnóstico.", ans=0))

# CIR-004 · Neumotórax a tensión · ÁRBOL + Rx real
S("arbol", "CIR-004", "Puñalada infraclavicular con hipotensión, yugulares llenas, timpanismo y murmullo ausente: neumotórax a tensión",
  "Trauma torácico · neumotórax a tensión",
  ("Neumotórax a tensión", ["El aire entra al pleural y no sale (válvula): colapsa el pulmón y empuja el mediastino.",
                            "Se dobla la vena cava y cae el retorno venoso: choque obstructivo."]),
  ("Varón de 18 años acuchillado", ["Disnea súbita y dolor torácico derecho; PA 80/40, FC 110, yugulares ingurgitadas.",
                                    "Hemitórax derecho timpánico, sin murmullo vesicular."]),
  ["El diagnóstico es clínico: no esperar la Rx.",
   "Descompresión inmediata con aguja o toracostomía con el dedo en el 4.º-5.º espacio intercostal, línea axilar media (ATLS 11.ª).",
   "Luego tubo de tórax. Taponamiento: yugulares llenas también, pero con murmullo conservado y sin timpanismo."],
  ATLS + ".",
  op=("¿Encaja?", ["No: no da choque", "Sí: timpanismo + choque + yugulares llenas", "No: matidez, no timpanismo",
                   "No: matidez y yugulares planas", "No: murmullo conservado"]),
  arbol=Q("Trauma de tórax con choque: ¿timpanismo y murmullo ausente?", [
      L("Sí (este caso)", "NEUMOTÓRAX A TENSIÓN", ["Descompresión ya (4.º-5.º EIC, línea axilar media)", "Luego tubo de tórax"], path=True),
      Q("¿Matidez?", [L("Sí", "Hemotórax masivo", ["Tubo de tórax y reponer sangre"]),
                      L("No: ruidos apagados", "Taponamiento", ["Pericardiocentesis o toracotomía"])], edge="No")], path=True),
  banda=B("Rx real de un neumotórax grande", P("rx_neumotorax_grande.jpg", 280, 280, [
            ("texto", 0.17, 0.22, "aire sin trama\npulmonar"),
            ("flecha", 0.37, 0.4, 0.2, 0.7, "pulmón\ncolapsado")],
          credito="James Heilman" + CC + "CC BY 3.0"),
          [("Sin trama pulmonar", "El lado afectado se ve negro hasta la pared: es aire libre en la pleura."),
           ("Pulmón colapsado", "Se ve como una masa pequeña junto al hilio."),
           ("En la tensión no se espera la Rx", "Si hay choque, primero se descomprime; la Rx se toma después."),
           ("Desviación del mediastino", "La tráquea se va al lado sano cuando hay tensión.")],
          pie="Rx de otro paciente con neumotórax (sin tensión).", ans=2))

# GIN-008 · Puntaje de Bishop desfavorable · PUNTAJE (escala de Bishop)
S("arbol", "GIN-008", "41 semanas con cuello posterior, largo, cerrado y duro (Bishop desfavorable): maduración cervical",
  "Embarazo prolongado · inducción del parto",
  ("Inducción del parto", ["Desde las 41 semanas se ofrece inducir: baja la muerte fetal y la cesárea.",
                           "Si el cuello no está maduro (Bishop bajo), primero se madura."]),
  ("Primigesta de 41 semanas", ["Feto cefálico con bienestar conservado.", "Cuello posterior, largo, cerrado, duro; altura -4."]),
  ["Bishop ≤ 6: madurar el cuello con misoprostol (25 µg vaginal) o sonda Foley; luego oxitocina.",
   "Bishop ≥ 8: el cuello está listo; se induce con oxitocina y amniotomía.",
   "Cesárea solo si hay otra indicación; esperar más allá de las 42 semanas aumenta los riesgos."],
  ACOG + ", Clinical Practice Update: inducción a las 41 semanas (2024); " + OMS + ", inducción del trabajo de parto (2022); " + WILLIAMS + ".",
  op=("¿Adecuada?", ["No: no hay indicación", "No: a las 41 semanas se ofrece inducir", "Sí: Bishop 0",
                     "Todavía no: el cuello no está maduro", "No: cuello cerrado y presentación alta"]),
  arbol=Q("41 semanas con feto bien: ¿Bishop?", [
      L("≤ 6: 0 puntos (este caso)", "MADURACIÓN CERVICAL", ["Misoprostol o sonda Foley", "Luego oxitocina"], path=True),
      L("≥ 8", "Inducción", ["Oxitocina y amniotomía"])], path=True),
  escala=dict(nombre="Puntaje de Bishop", modo="puntaje", que="Mide qué tan listo está el cuello (0 a 13 puntos).",
              items=[("D", "Dilatación (0 a 3)", "Cerrado", 0), ("B", "Borramiento (0 a 3)", "0 % (largo)", 0),
                     ("E", "Estación o altura (0 a 3)", "-4 (por encima de -3)", 0), ("C", "Consistencia (0 a 2)", "Dura", 0),
                     ("P", "Posición (0 a 2)", "Posterior", 0)],
              total_txt="Total: 0 puntos",
              rangos=[("≤ 6", "Cuello desfavorable", "Maduración cervical primero"), ("7", "Intermedio", "Individualizar"),
                      ("≥ 8", "Cuello favorable", "Inducir con oxitocina")],
              caso_rango=0, porque=[("Todo el cuello está «cerrado»: ningún ítem suma", True)],
              conducta="Misoprostol vaginal o sonda Foley para madurar el cuello y después oxitocina."))

# SP-006 · Conflicto de intereses · TARJETAS
S("tarjetas", "SP-006", "Expertos que recomiendan un fármaco sin declarar que el laboratorio los financió: conflicto de intereses",
  "Ética de la investigación · integridad científica",
  ("Conflicto de intereses", ["Un interés secundario (dinero, prestigio) puede sesgar el juicio sobre un interés primario (la salud).",
                              "No es una falta tenerlo: es una falta ocultarlo."]),
  ("Epidemia de H1N1", ["Expertos dijeron que el oseltamivir era la mejor opción.", "No declararon el financiamiento del fabricante."]),
  ["Toda guía, artículo o charla debe declarar los conflictos de intereses (ICMJE, OMS).",
   "Los expertos con conflictos no deben decidir solos las recomendaciones.",
   "Principio de precaución: actuar ante un riesgo sin certeza completa; no es lo que pasó aquí."],
  "ICMJE, recomendaciones de declaración de intereses (2024); " + OMS + ", Guidelines for declaration of interests (2014, act.).",
  op=("¿Es lo ocurrido?", ["No: es otra cosa", "Sí: interés económico oculto", "No: es otra cosa", "No: no se decidió por el paciente",
                           "No: no hubo error de medición"]),
  d=dict(rotulo="Problemas éticos en la ciencia", ans=0,
         cards=[dict(titulo="Conflicto de intereses", datos=[("Qué", "Interés económico", True), ("Falta", "Ocultarlo", True),
                                                           ("Aquí", "Financiados por el laboratorio", True)], pie="Este caso."),
                dict(titulo="Principio de precaución", datos=[("Qué", "Actuar ante un riesgo", False), ("Cuándo", "Sin certeza", False),
                                                            ("Aquí", "No aplica", False)], pie="Prudencia."),
                dict(titulo="Error de medición", datos=[("Qué", "Dato mal medido", False), ("Tipo", "Sesgo de información", False),
                                                      ("Aquí", "No aplica", False)], pie="Metodología."),
                dict(titulo="Falta de autocrítica", datos=[("Qué", "No reconocer límites", False), ("Tipo", "Actitud", False),
                                                         ("Aquí", "No es lo central", False)], pie="Humildad científica.")]))

# GIN-009 · Embarazo con antecedente de ectópico · ÁRBOL
S("arbol", "GIN-009", "Atraso de 2 días con β-hCG positiva y ectópico previo: ecografía transvaginal",
  "Embarazo ectópico · localización del embarazo",
  ("Embarazo de localización a precisar", ["Con un ectópico previo, el riesgo de repetir es de 10-15 %: hay que ubicar el saco pronto.",
                                           "La ecografía transvaginal es el examen de elección."]),
  ("Mujer con ectópico previo", ["Atraso menstrual de 2 días.", "β-hCG positiva."]),
  ["Saco intrauterino visible: embarazo intrauterino (descarta ectópico casi siempre).",
   "Sin saco con β-hCG sobre la zona discriminatoria (~3500 mUI/mL): sospecha de ectópico.",
   "Con β-hCG baja y sin saco: repetir β-hCG en 48 h y ecografía (en un embarazo normal sube ≥ 35-50 %)."],
  ACOG + " Practice Bulletin n.º 193, Tubal ectopic pregnancy (2018, reafirmado); NICE NG126 (2023); " + WILLIAMS + ".",
  op=("¿Primera prueba?", ["No: invasiva; si hay inestabilidad", "No: obsoleta", "Complementa, no localiza", "Sí: localiza el saco",
                           "No: contraindicada en el embarazo"]),
  arbol=Q("β-hCG positiva con ectópico previo: ecografía transvaginal", [
      L("Saco en el útero", "Embarazo intrauterino", ["Control prenatal"]),
      L("Masa anexial o líquido libre", "Embarazo ectópico", ["Metotrexato o cirugía"]),
      L("No se ve nada (este caso, muy precoz)", "Repetir β-hCG en 48 h", ["Y ecografía", "Zona discriminatoria ~3500"], path=True)],
    path=True))

# REU-005 · Escabiosis · TARJETAS + foto real
S("tarjetas", "REU-005", "Lactante con prurito nocturno, pápulas y vesículas en palmas y plantas y madre igual: escabiosis",
  "Dermatología · infestaciones parasitarias",
  ("Escabiosis (sarna)", ["Infestación por Sarcoptes scabiei: el ácaro cava túneles en la capa córnea.",
                          "Prurito peor de noche y convivientes afectados."]),
  ("Lactante de 8 meses", ["Irritable, prurito nocturno.", "Pápulas, vesículas y pústulas en cara, tronco, palmas y plantas; madre igual."]),
  ["En lactantes afecta palmas, plantas y cara (en adultos respeta la cabeza).",
   "Tratamiento: permetrina 5 % (desde los 2 meses) de cuello a pies (incluida la cabeza en lactantes), repetir a la semana.",
   "Tratar a todos los convivientes a la vez y lavar la ropa con agua caliente."],
  "IACS, criterios de consenso para escabiosis (2020); " + OMS + ", escabiosis (2023); " + NELSON + ".",
  op=("¿Encaja?", ["No: úlceras con costra", "Sí: prurito nocturno + familia + palmas y plantas", "Inespecífico",
                   "No: costras mielicéricas", "No: vesículas en distintos estadios, con fiebre"],
      {1: "Acarosis (escabiosis)"}),
  d=dict(rotulo="Prurito y lesiones en el lactante", ans=0,
         cards=[dict(titulo="Escabiosis", datos=[("Prurito", "Nocturno", True), ("Dónde", "Palmas y plantas", True),
                                               ("Familia", "Madre igual", True)], pie="Este caso: permetrina."),
                dict(titulo="Impétigo", datos=[("Lesión", "Costra amarillenta", False), ("Germen", "S. aureus", False),
                                             ("Prurito", "Leve", False)], pie="Mupirocina."),
                dict(titulo="Varicela", datos=[("Fiebre", "Sí", False), ("Lesión", "Vesículas en varios estadios", False),
                                             ("Palmas", "Respetadas", False)], pie="Cielo estrellado."),
                dict(titulo="Dermatitis atópica", datos=[("Dónde", "Mejillas, pliegues", False), ("Familia", "Atopia", False),
                                                       ("Curso", "Crónico", False)], pie="Emolientes.")]),
  banda=B("Surco de escabiosis (foto real)", P("escabiosis.jpg", 300, 233, [
            ("flecha", 0.845, 0.14, 0.55, 0.1, "ácaro al final\ndel surco"),
            ("flecha", 0.78, 0.3, 0.82, 0.72, "surco"),
            ("flecha", 0.35, 0.55, 0.18, 0.9, "rascado")],
          credito="Michael Geary" + CC + "dominio público"),
          [("Surco acarino", "Línea fina gris o blanca de pocos milímetros: el túnel donde la hembra pone huevos."),
           ("El ácaro", "Punto al final del surco; se puede sacar con aguja y verlo al microscopio."),
           ("Lesiones por rascado", "Costras y excoriaciones; pueden infectarse (impétigo).")],
          pie="Piel de otro paciente (vista de cerca).", ans=0))

# GAS-005 · Cáncer colorrectal con antecedente de PAF · ÁRBOL + riesgo de CCR
S("arbol", "GAS-005", "Mujer de 52 años con cambio del ritmo defecatorio y madre con poliposis adenomatosa familiar: colonoscopia",
  "Colon · cáncer colorrectal",
  ("Cáncer colorrectal", ["Casi siempre nace de un pólipo adenomatoso; la colonoscopia lo detecta y lo extrae.",
                          "La poliposis adenomatosa familiar (gen APC) lleva al cáncer casi en el 100 % sin tratamiento."]),
  ("Mujer de 52 años", ["6 meses de dolor abdominal y cambio del ritmo defecatorio.", "Madre con poliposis adenomatosa familiar; Thevenon y parásitos negativos."]),
  ["Síntomas + antecedente familiar de alto riesgo: colonoscopia completa con biopsia.",
   "En familias con PAF: estudio genético (APC) y colonoscopia desde los 10-12 años.",
   "La endoscopia alta y la cápsula no ven bien el colon; la TC estadifica, no diagnostica."],
  "US Multi-Society Task Force on CRC, tamizaje (2022); NCCN, Genetic/familial high-risk assessment: colorectal (2025); " + HARRISON + ".",
  op=("¿Es el examen?", ["Sí: ve y biopsia todo el colon", "No: no ve el colon", "No: para intestino delgado", "No: estadifica",
                         "No: no ve el colon"]),
  arbol=Q("Síntomas de colon: ¿signos de alarma o riesgo familiar alto?", [
      L("Sí: madre con PAF (este caso)", "COLONOSCOPIA", ["Completa, con biopsia", "Estudio genético APC"], path=True),
      L("No", "Tamizaje desde los 45 años", ["Sangre oculta o colonoscopia"])], path=True),
  escala=dict(nombre="Riesgo de cáncer colorrectal", orden=True, que="Define desde cuándo y cómo vigilar el colon.",
              grados=[("Promedio", "Sin antecedentes", ["Tamizaje desde los 45 años", "Sangre oculta anual o colonoscopia cada 10 años"]),
                      ("Aumentado", "Familiar de 1.er grado con CCR", ["Colonoscopia desde los 40 años", "Cada 5 años"]),
                      ("Alto", "Síndromes hereditarios", ["PAF: colonoscopia desde los 10-12 años", "Lynch: desde los 20-25 años",
                                                          "Estudio genético"])],
              caso=2, porque=[("Madre con poliposis adenomatosa familiar: síndrome hereditario", True),
                              ("Además tiene síntomas: la colonoscopia ya no es tamizaje, es diagnóstica", True)],
              conducta="Colonoscopia completa con biopsia y consejería genética (gen APC)."))

# CIR-005 · Primeros auxilios en quemaduras · ÁRBOL + profundidad
S("arbol", "CIR-005", "Quemadura en los primeros minutos: enfriar con agua a temperatura ambiente para frenar la profundidad",
  "Quemaduras · primeros auxilios",
  ("Primeros auxilios en quemaduras", ["El calor sigue dañando la piel unos minutos después del contacto.",
                                       "Enfriar con agua corriente frena esa progresión y alivia el dolor."]),
  ("Pregunta de concepto", ["¿Qué hacer en los primeros minutos para que la quemadura no se haga más profunda?"]),
  ["Agua corriente fresca (15-25 °C) por 20 minutos, dentro de las primeras 3 horas; retirar ropa y anillos.",
   "Nunca hielo: produce vasoconstricción y más necrosis; tampoco pasta, aceite ni remedios caseros.",
   "Cubrir con film o paño limpio, abrigar al paciente (evitar la hipotermia) y derivar según extensión y profundidad."],
  "International Society for Burn Injuries (ISBI), guía de cuidado de quemaduras (2018); ABA, Advanced Burn Life Support (2023); " + ATLS + ".",
  op=("¿Frena la profundidad?", ["No: es para quemaduras extensas", "Sí: enfría el tejido", "No: no tienen papel",
                                 "Alivian el dolor, no frenan el daño", "No: el hielo profundiza la lesión"]),
  arbol=Q("Quemadura térmica reciente: primeros minutos", [
      L("Enfriar (este caso)", "AGUA A TEMPERATURA AMBIENTE", ["20 minutos de agua corriente", "Retirar ropa y anillos"], path=True),
      L("Evitar", "Hielo y remedios caseros", ["Más necrosis e hipotermia"]),
      L("Después", "Cubrir y valorar", ["Extensión (regla de los 9)", "Profundidad"])], path=True),
  escala=dict(nombre="Profundidad de las quemaduras", orden=True, que="Se define por la capa de piel dañada.",
              grados=[("Epidérmica", "Primer grado", ["Roja, seca, dolorosa", "Sin ampollas", "Sana en 3-7 días"]),
                      ("Dérmica superficial", "Segundo grado superficial", ["Ampollas, rosada, húmeda", "Muy dolorosa", "Sana en 2 semanas"]),
                      ("Dérmica profunda", "Segundo grado profundo", ["Blanca o moteada", "Menos dolor", "Suele necesitar injerto"]),
                      ("Espesor total", "Tercer grado", ["Blanca, acartonada o negra", "Indolora", "Injerto"])],
              caso=None, porque_titulo="Por qué enfriar importa",
              porque=[("El agua en los primeros minutos puede evitar que una quemadura superficial se haga profunda", True),
                      ("El hielo daña más: convierte zonas recuperables en profundas", False)],
              conducta="Agua corriente fresca 20 minutos, cubrir con material limpio, abrigar y derivar según extensión y profundidad."))
