"""Entrega 3 · tanda t14 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
SABISTON = "Sabiston Tratado de Cirugía 21.ª ed."

# SP-140 · Suplementación no administrada: efectividad · RADIAL
S("radial", "SP-140", "Se entregó sulfato ferroso pero 1 de cada 10 madres no lo da: el indicador comprometido es la efectividad (el resultado en condiciones reales)",
  "Gestión en salud · indicadores de desempeño",
  ("Eficacia, efectividad y eficiencia", ["Eficacia: funciona en condiciones ideales (ensayo). Efectividad: logra el resultado en la vida real. Eficiencia: con el menor costo.",
                                          "Si el suplemento llega pero no se toma, la intervención no logra su efecto: falla la efectividad."]),
  ("Visita domiciliaria", ["Se entregó sulfato ferroso para prevenir la anemia.", "En 1 de 10 hogares la madre no lo administra."]),
  ["Mejorar la adherencia: consejería, explicar efectos (heces oscuras, estreñimiento), seguimiento.",
   "Indicadores del programa: cobertura, adherencia (consumo ≥ 75 %), hemoglobina a los 6 y 12 meses.",
   "Accesibilidad: llegar al servicio; equidad: igual acceso según necesidad."],
  MINSA + ", plan multisectorial de lucha contra la anemia (2024); " + OMS + ".",
  op=("¿Indicador?", ["No: igual acceso según necesidad", "Sí: no se logra el resultado real", "No: percepción del usuario", "No: concepto amplio", "No: el suplemento sí llegó"]),
  d=dict(rotulo="Qué mide cada indicador", centro="SUPLEMENTO DE HIERRO", centro_sub="programa", ans=1,
         items=[("ACCESIBILIDAD", ["¿Le llegó el suplemento?"]), ("EFECTIVIDAD", ["¿Se logra el resultado real?", "Esta pregunta"]),
                ("EQUIDAD", ["Según la necesidad"]), ("SATISFACCIÓN", ["Opinión del usuario"]), ("CALIDAD", ["Suma de dimensiones"])],
         ruta=["Entrega del hierro", "¿Se toma?", "1 de 10 no", "Falla la efectividad"]))

# SP-141 · Discapacidad sin acceso: UPSS de rehabilitación · ÁRBOL
S("arbol", "SP-141", "Un centro de salud I-4 identifica población con discapacidad sin acceso: la solución que garantiza la atención es implementar una UPSS de medicina de rehabilitación",
  "Gestión de servicios · rehabilitación basada en la comunidad",
  ("Oferta de servicios para discapacidad", ["El I-4 puede tener la unidad productora de servicios (UPSS) de medicina de rehabilitación.",
                                             "Si la población no tiene acceso, hay que acercar la oferta (servicio + rehabilitación basada en la comunidad), no solo identificar o referir."]),
  ("Centro de salud I-4", ["Análisis de situación de salud: población con discapacidad sin acceso.", "¿Qué garantiza su atención?"]),
  ["Implementar la UPSS de medicina de rehabilitación con el personal y equipo necesarios.",
   "Certificar la discapacidad y articular con la municipalidad (OMAPED) y CONADIS.",
   "Rehabilitación basada en la comunidad para quienes no pueden desplazarse."],
  MINSA + ", NTS de categorías de establecimientos (2011; act.); Ley n.º 29973.",
  op=("¿Solución?", ["Identifica, pero no da acceso", "No: es para casos complejos", "Sí: crea la oferta cercana", "No: no depende del centro", "No: no hay acceso"],
      {0: "Censar y referir al hospital", 1: "Hospitalizar en el INR", 2: "Implementar la UPSS de rehabilitación", 3: "Pedir recategorización a nivel 2", 4: "Esperar que acudan"}),
  arbol=Q("Población sin acceso: ¿cuál es la barrera?", [
      L("No hay el servicio (este caso)", "IMPLEMENTAR UPSS DE REHABILITACIÓN", ["En el I-4", "+ rehabilitación en la comunidad"], path=True),
      L("Hay servicio pero no llegan", "Búsqueda activa y visita domiciliaria", ["Transporte, horarios"]),
      L("Caso complejo", "Referencia", ["Hospital o Instituto Nacional de Rehabilitación"])], path=True))

# PED-187 · Neumonía en el preescolar: Rx de tórax · ALARMA + Rx
S("alarma", "PED-187", "Niña de 4 años con 3 días de rinitis, tos y fiebre que luego presenta aleteo nasal, polipnea, tiraje y crepitantes: neumonía grave, Rx de tórax para confirmar",
  "Neumonía adquirida en la comunidad en niños",
  ("Neumonía en el niño", ["Fiebre, tos y taquipnea (≥ 40 rpm de 1 a 5 años) son la base; tiraje, aleteo, quejido o hipoxemia indican gravedad.",
                           "La Rx confirma y busca complicaciones (derrame) en el niño que se hospitaliza."]),
  ("Niña de 4 años", ["3 días de rinitis, tos y fiebre; al 4.º día dificultad respiratoria.", "Aleteo nasal, polipnea, tiraje; crepitantes y sibilantes."]),
  ["Hospitalizar: oxígeno si SatO₂ < 92 %, Rx de tórax.",
   "Antibiótico: amoxicilina oral si tolera; ampicilina o penicilina EV si es grave.",
   "Sibilantes con fiebre baja: considerar etiología viral o Mycoplasma (≥ 5 años)."],
  OMS + ", AIEPI; BTS, neumonía en niños (2011; act.); " + MINSA + ".",
  op=("¿Examen inicial?", ["No: radiación y no es inicial", "Sí: confirma y ve complicaciones", "Apoya, no confirma", "Útil, no confirma el diagnóstico", "Útil, pero no de rutina"]),
  d=dict(rotulo="Signos de neumonía grave en el niño", lista_titulo="Lo que tiene ella",
         signos=[("Taquipnea (≥ 40 rpm a los 1-5 años)", "Polipnea", True), ("Tiraje subcostal", "Sí", True), ("Aleteo nasal", "Sí", True),
                 ("Crepitantes", "Sí, con sibilantes", True), ("No puede beber o convulsiona", "No se informa", False), ("SatO₂ < 92 %", "No se informa", False)],
         img=P("neumonia_lm.jpg", 260, 201, [], credito="James Heilman" + CC + "CC BY-SA 4.0"), img_titulo="Rx: consolidación",
         accion=("Hospitalizar y Rx de tórax", "Oxígeno y antibiótico."),
         accion_rotulo="NEUMONÍA GRAVE",
         veredicto=("Tiraje + aleteo + crepitantes = neumonía grave", "Rx de tórax para confirmar y descartar derrame.")))

# GIN-189 · Hematoma pequeño de episiotomía · REGLA
S("regla", "GIN-189", "Puérpera de 6 días con una tumoración de 3 cm en la episiotomía, sin signos de inflamación: hematoma pequeño estable, analgésicos y observación",
  "Puerperio · hematoma perineal",
  ("Hematoma vulvar o perineal", ["Pequeño (< 3-5 cm), estable y sin infección: se reabsorbe; analgesia y hielo.",
                                  "Grande (> 5 cm), que crece, con dolor intenso o caída de la Hb: drenaje en sala de operaciones y hemostasia."]),
  ("Puérpera de 6 días", ["Dolor vulvar.", "Tumoración de 3 cm en la episiotomía, sin flogosis."]),
  ["Analgésico (AINE), hielo local las primeras 24-48 h, baños de asiento después.",
   "Control en 24-48 h: tamaño, dolor y signos de infección.",
   "Si hay fiebre, eritema o pus: absceso → abrir, drenar y antibiótico."],
  WILLIAMS + "; RCOG (2015).",
  op=("¿Conducta?", ["No: no hay infección", "No: no drena el coágulo y puede infectar", "No: no es grande ni crece", "Sí: pequeño y estable", "No: no hay dehiscencia"]),
  d=dict(rotulo="El tamaño decide",
         reglas=[dict(nombre="Diámetro del hematoma (cm)", que="Pequeño y estable: observar. Grande o en crecimiento: drenar.",
                      min=0, max=10, fmt="{}", ticks=[3, 5],
                      bandas=[(0, 5, "Observar", 0), (5, 10, "Drenar en sala", 3)], caso=3, caso_txt="ESTE CASO: 3 cm")],
         claves_titulo="Lo que lo hace benigno",
         claves=[("Sin flogosis", ["No hay infección"], True), ("Pequeño", ["3 cm"], True), ("Vigilar", ["Que no crezca"], False)]))

# END-055 · Hipoglucemia por glibenclamida · MATRIZ
S("matriz", "END-055", "Anciano diabético con confusión, conducta bizarra y glucosa de 50 con creatinina de 1,8: hipoglucemia por glibenclamida (se acumula en la falla renal)",
  "Diabetes · hipoglucemia por fármacos",
  ("Sulfonilureas e hipoglucemia", ["La glibenclamida estimula la insulina sin importar la glucosa y tiene metabolitos activos que elimina el riñón.",
                                    "En ancianos con falla renal se acumula: hipoglucemias graves y prolongadas (pueden recurrir 24-72 h)."]),
  ("Diabético de 78 años", ["Conducta bizarra, ideas paranoides, cefalea, confusión, debilidad, visión borrosa.", "Creatinina 1,8; glucosa 50."]),
  ["Dextrosa al 33-50 % EV y luego infusión de dextrosa al 10 %; hospitalizar 24-72 h (recurre).",
   "Octreotida si la hipoglucemia recurre por sulfonilurea.",
   "Suspender la glibenclamida: en ancianos o con TFG baja preferir iDPP-4, iSGLT2 o arGLP-1."],
  ADA + " (sección adultos mayores); " + KDIGO + ", diabetes en ERC (2022).",
  op=("¿Responsable?", ["No: no causa hipoglucemia sola", "Sí: sulfonilurea que se acumula", "No: no causa hipoglucemia sola", "No: no causa hipoglucemia (sí acidosis láctica)",
                        "Puede, pero la clásica en falla renal es la glibenclamida"]),
  d=dict(rotulo="¿Qué antidiabético da hipoglucemia y se acumula en la falla renal?", eje_x="En la falla renal", eje_y="¿Da hipoglucemia?",
         cols=["Se acumula", "No se acumula o se ajusta"], rows=["Sí", "No (sola)"], caso=(0, 0),
         cells=[[("GLIBENCLAMIDA", ["Metabolitos activos renales", "Este caso"]), ("Insulina (glargina)", ["Ajustar dosis"])],
                [("Metformina", ["Acidosis láctica si TFG < 30"]), ("Pioglitazona, acarbosa", ["No dan hipoglucemia solas"])]]))

# NEF-077 · Nefropatía por IgA · CRONOLOGÍA
S("cronologia", "NEF-077", "Joven con hematuria macroscópica recurrente a los pocos días de infecciones respiratorias, hematíes dismórficos y proteinuria leve: nefropatía por IgA",
  "Glomerulopatías · nefropatía por IgA",
  ("Nefropatía por IgA (Berger)", ["La glomerulonefritis primaria más frecuente del mundo; depósitos de IgA en el mesangio.",
                                   "Hematuria macroscópica 1-3 días después de una infección respiratoria (sinfaringítica), con C3 normal."]),
  ("Varón de 24 años", ["Orina roja; episodios de hematuria tras infecciones respiratorias desde hace 5 años.", "89 hematíes/campo (80 % dismórficos), creatinina 1, proteinuria 0,8 g/24 h."]),
  ["Biopsia renal para confirmar y clasificar (Oxford MEST-C).",
   "IECA o ARA II si la proteinuria es > 0,5 g/día; control de PA (< 130/80); iSGLT2.",
   "Corticoides o budesonida entérica si persiste la proteinuria > 1 g pese al tratamiento óptimo."],
  KDIGO + ", nefropatía por IgA (2025).",
  op=("¿Diagnóstico?", ["No: nefrótico en adultos, sin hematuria macroscópica", "No: nefrótico", "Sí: hematuria a los pocos días de la infección", "No: niños, nefrótico, sin hematuria",
                        "No: 1-3 semanas después y C3 bajo"]),
  d=dict(rotulo="¿Cuántos días después de la infección aparece la hematuria?", tag="IgA",
         ilu_titulo="Cilindro hemático (otro paciente)",
         ilu=CON_CREDITO(P("cilindro_hematico.jpg", 330, 210, [], credito="Mohsenin V." + CC + "CC BY 4.0"), dx=0),
         ilu_pie="Sangre de origen glomerular.",
         claves=[("Nefropatía por IgA", ["1-3 días después (mientras dura la infección)"], True), ("GN postestreptocócica", ["1-3 semanas (faringe), 3-6 (piel); C3 bajo"], False),
                 ("Ambas", ["Hematuria glomerular: hematíes dismórficos"], False)],
         eje_titulo="Días desde la infección respiratoria", eje=(0, 28), paso=4, marca=2, unidad="d", eje_nombre="días",
         hitos=[(1, 3, "Nefropatía por IgA", "sinfaringítica", True), (7, 21, "GN postestreptocócica (faringe)", "latencia", False),
                (21, 28, "GN postestreptocócica (piel)", "3-6 semanas", False)]))

# CAR-063 · Estenosis aórtica · TERMÓMETRO + tríada
S("termometro", "CAR-063", "Varón de 60 años con angina, síncope de esfuerzo y disnea, pulso parvus y soplo sistólico eyectivo: estenosis aórtica grave",
  "Valvulopatías · estenosis aórtica",
  ("Estenosis aórtica", ["Válvula calcificada que obstruye la salida del VI: soplo sistólico eyectivo en foco aórtico irradiado al cuello, pulso parvus et tardus.",
                         "Cuando aparecen síntomas el pronóstico cae: angina (~5 años), síncope (~3 años), insuficiencia cardíaca (~2 años)."]),
  ("Varón de 60 años", ["Dolor torácico, síncopes fugaces de esfuerzo y disnea.", "Pulso parvus, choque de punta desplazado, soplo sistólico eyectivo paraesternal izquierdo."]),
  ["Ecocardiograma: área < 1 cm², gradiente medio ≥ 40 mmHg o velocidad ≥ 4 m/s = grave.",
   "Grave sintomática: reemplazo valvular (quirúrgico o TAVI según edad y riesgo).",
   "Evitar vasodilatadores potentes y el ejercicio intenso hasta corregirla."],
  ESC + "/EACTS, valvulopatías (2025); AHA/ACC (2020).",
  op=("¿Diagnóstico?", ["No: soplo diastólico, FA", "No: soplo diastólico, pulso saltón", "No: soplo holosistólico en ápex", "Sí: tríada + soplo eyectivo + parvus", "No: HTA en brazos, pulsos femorales débiles"]),
  d=dict(rotulo="Supervivencia sin cirugía según el síntoma", caso_nivel=2, ruta_titulo="Qué hacer", paso_label="ESTE CASO",
         niveles=[("Asintomática", "Buen pronóstico", ["Control con eco"]), ("Angina", "~5 años", ["Primer síntoma"]),
                  ("Síncope", "~3 años", ["De esfuerzo"]), ("IC (disnea)", "~2 años", ["Insuficiencia cardíaca"])],
         pasos=[(1, "Ecocardiograma", ["Área, gradiente, velocidad"], False),
                (2, "Reemplazo valvular", ["Cirugía o TAVI"], True),
                (3, "Evitar esfuerzos intensos", ["Hasta operar"], False)]),
  triada=TR([("Angina", "Dolor torácico", True), ("Síncope de esfuerzo", "Sí", True), ("Disnea (insuficiencia cardíaca)", "Sí", True)],
            [("Tríada de la estenosis aórtica", 0, 2)], "Con los tres síntomas: reemplazo valvular urgente."))

# END-056 · Diabetes en el primer nivel: referir por albuminuria · ALARMA
S("alarma", "END-056", "Diabético atendido en un I-4: la albuminuria mayor de 300 mg/24 h (nefropatía establecida) es criterio para referirlo al siguiente nivel",
  "Diabetes · referencia",
  ("Criterios de referencia del diabético", ["El primer nivel maneja la diabetes no complicada; se refiere ante daño de órganos o falta de control pese a tratamiento.",
                                             "Albuminuria > 300 mg/24 h o TFG < 30-45, retinopatía, pie diabético complicado, crisis hiperglucémicas, cardiopatía."]),
  ("Varón de 45 años con DM2", ["Diagnosticado en un I-4.", "Consulta por más sed."]),
  ["En el I-4: educación, metformina, control de PA y lípidos, tamizaje anual (orina, creatinina, fondo de ojo, pies).",
   "Glucosa 180 o falta de adherencia: ajustar y educar, no son motivo de referencia por sí solas.",
   "Con nefropatía: IECA/ARA II e iSGLT2 y seguimiento por nefrología o medicina interna."],
  MINSA + ", guía de diabetes tipo 2 en el primer nivel (2016; act.); " + ADA + ".",
  op=("¿Criterio de referencia?", ["No: leve, vigilar", "Sí: nefropatía establecida", "No: el diagnóstico lo hace el primer nivel", "No: se educa en el primer nivel", "No: se ajusta el tratamiento"]),
  d=dict(rotulo="Cuándo referir al diabético", lista_titulo="Criterios de referencia",
         signos=[("Albuminuria > 300 mg/24 h", "Esta pregunta", True), ("TFG < 30-45 mL/min", "No se informa", False),
                 ("Retinopatía", "No se informa", False), ("Pie diabético complicado", "No", False), ("Crisis hiperglucémica", "No", False)],
         accion=("Referir al siguiente nivel", "Nefropatía diabética establecida."),
         accion_rotulo="CON 1 CRITERIO",
         veredicto=("Albuminuria > 300 mg/24 h: referir", "Lo demás se ajusta en el primer nivel.")))

# GIN-190 · Incontinencia de urgencia con residuo alto: urodinamia · EMBUDO
S("embudo", "GIN-190", "Mujer con incontinencia de urgencia, sin escape al Valsalva, cistocele leve y residuo posmiccional de 150 mL: pedir urodinamia",
  "Incontinencia urinaria",
  ("Tipos de incontinencia", ["De esfuerzo: escapa al toser o con Valsalva. De urgencia: deseo súbito que no se puede contener (vejiga hiperactiva). Por rebosamiento: vejiga que no vacía.",
                              "Residuo posmiccional > 100-150 mL: vaciamiento alterado; antes de tratar se estudia con urodinamia."]),
  ("Mujer de 35 años", ["Pérdida de orina intermitente: no llega al baño con la urgencia.", "Sin escape con Valsalva; cistocele grado I; residuo 150 mL."]),
  ["La urodinamia distingue hiperactividad del detrusor, obstrucción y hipocontractilidad.",
   "Urgencia pura con residuo normal: medidas conductuales, ejercicios de Kegel y antimuscarínicos o mirabegrón.",
   "Antimuscarínicos con residuo alto pueden causar retención: por eso primero urodinamia."],
  "AUA/SUFU, vejiga hiperactiva (2024); EAU, incontinencia (2025).",
  op=("¿Siguiente paso?", ["No: no aporta", "No: no aporta", "Después de estudiar", "Sí: residuo alto + urgencia", "No: cistocele leve no explica la urgencia"]),
  d=dict(rotulo="Incontinencia: ¿de qué tipo?", inicio="Pérdida involuntaria de orina",
         candidatos=["Esfuerzo", "Mixta", "Urgencia simple", "Rebosamiento", "Urgencia con residuo alto"],
         pasos=[("¿Escapa al toser o con Valsalva?", ["Esfuerzo", "Mixta"]),
                ("¿El residuo posmiccional es normal (< 100 mL)?", ["Urgencia simple", "Rebosamiento"])],
         final=("URGENCIA CON RESIDUO ALTO", ["Urodinamia antes de tratar"]),
         nota="Con residuo de 150 mL, un antimuscarínico podría causar retención."))

# SP-142 · Seguimiento de casos y contactos: equipos · RELOJ
S("reloj", "SP-142", "Para implementar el seguimiento de pacientes y contactos en un centro I-3, la prioridad 1 (MINSA) es organizar los equipos de intervención integral",
  "Gestión del primer nivel · seguimiento comunitario",
  ("Seguimiento de casos y contactos", ["El primer nivel trabaja con equipos multidisciplinarios que salen a la comunidad: identifican, visitan, siguen y refieren.",
                                        "Sin equipos organizados no hay seguimiento posible: por eso es la prioridad 1."]),
  ("Centro de salud I-3", ["Le piden un sistema de seguimiento de pacientes y contactos.", "¿Qué es prioridad 1 según el MINSA?"]),
  ["Conformar equipos de intervención integral (médico, enfermera, obstetra, técnico, agentes comunitarios).",
   "Sectorizar el territorio, padrón nominal y visitas domiciliarias programadas.",
   "Luego: insumos (oxímetros), referencia y contrarreferencia con hospitales."],
  MINSA + ", lineamientos de equipos de seguimiento en el primer nivel (COVID-19, 2020-2021); MCI (Modelo de Cuidado Integral).",
  op=("¿Prioridad 1?", ["No: el I-3 no hospitaliza", "Sí: sin equipos no hay seguimiento", "Después", "Después: insumo", "No: no es inmediato"]),
  d=dict(rotulo="El orden para montar el seguimiento", tag="PRIORIDAD 1",
         pasos=[("1", "Equipos de intervención integral", "Multidisciplinarios", True), ("2", "Sectorizar y padrón", "Quién vive dónde", False),
                ("3", "Visitas y telemonitoreo", "Casos y contactos", False), ("4", "Insumos", "Oxímetros, medicamentos", False),
                ("5", "Referencia", "Coordinar con hospitales y clínicas", False)],
         veredicto=("Primero los equipos de intervención integral", "Son los que hacen el seguimiento en la comunidad.")))

# INF-092 · Tricocefalosis: prolapso rectal y anemia · CUADRÍCULA
S("cuadricula", "INF-092", "Niño con hematoquecia, tenesmo, prolapso rectal y anemia grave (Hb 5): tricocefalosis masiva por Trichuris trichiura",
  "Parasitosis intestinal · helmintos",
  ("Trichuris trichiura", ["Gusano «látigo» que se fija en la mucosa del colon y el recto; se adquiere comiendo huevos de la tierra.",
                           "Infección masiva en niños: disentería crónica, tenesmo, prolapso rectal (con gusanos visibles) y anemia ferropénica."]),
  ("Niño de 4 años", ["Hematoquecia y tenesmo; prolapso rectal.", "Leucocitos 12 300, Hb 5 g/dL."]),
  ["Examen de heces (Kato-Katz): huevos «en barril» o «limón» con tapones polares.",
   "Albendazol 400 mg por 3 días (o mebendazol 100 mg c/12 h 3 días); hierro para la anemia (transfundir si Hb 5 con descompensación).",
   "Desparasitación periódica en escolares, higiene y saneamiento."],
  OMS + ", geohelmintiasis (2023); " + MINSA + "; " + NELSON + ".",
  op=("¿Etiología?", ["Sí: prolapso + anemia + tenesmo", "No: anemia sin prolapso ni disentería", "No: diarrea tras antibióticos", "No: hígado y vía biliar", "No: diarrea grasosa sin sangre"]),
  d=dict(rotulo="Helmintos y su pista clínica", alto_img=120,
         celdas=[("Trichuris trichiura", ["Prolapso rectal, tenesmo, anemia", "Huevo en barril"], P("trichuris.jpg", 250, 240), True),
                 ("Uncinarias", ["Anemia ferropénica marcada", "Sin prolapso ni disentería"], None, False),
                 ("Enterobius (oxiuro)", ["Prurito anal nocturno", "Test de Graham"], P("oxiuro.jpg", 330, 210), False),
                 ("Ascaris", ["Obstrucción, síndrome de Löffler", "Gusano grande"], None, False)],
         credito="Huevos: K. Fischer et al. (dominio público) y Ajay Kumar Chaurasiya (CC BY 4.0), Wikimedia Commons",
         veredicto=("Prolapso rectal + anemia + tenesmo = tricocefalosis", "Albendazol 3 días y hierro.")))

# GIN-191 · Podálica en expulsivo en la multípara · DECISIÓN
S("decision", "GIN-191", "Multípara de 39 semanas en expulsivo (dilatación completa) con presentación de nalgas puras y partos vaginales previos: atención del parto vaginal",
  "Presentación podálica",
  ("Parto en podálica", ["Lo ideal: versión cefálica externa a las 36-37 semanas o cesárea programada.",
                         "Pero en expulsivo (dilatación completa), multípara con pelvis probada y feto no grande, el parto vaginal asistido es lo seguro: la cesárea en ese momento no da ventaja."]),
  ("Multigesta de 39 semanas", ["En trabajo de parto: dilatación completa, nalgas puras.", "AU 29 cm (feto pequeño); 2 partos vaginales previos de 3200 g."]),
  ["Parto vaginal asistido por personal entrenado: no traccionar hasta ver la punta de las escápulas (maniobra de Bracht o Mauriceau).",
   "Preparado para cesárea de urgencia y con neonatología presente.",
   "Contraindicaciones del vaginal: feto > 3800 g, hiperextensión de la cabeza, pelvis estrecha, podálica completa/de pie."],
  ACOG + " n.º 745 (2018); RCOG Green-top n.º 20b (2017).",
  op=("¿Conducta?", ["No: no se usa fórceps en la nalga", "No: ya está en expulsivo", "Sí: expulsivo + multípara con pelvis probada", "No: ya está en expulsivo",
                     "No: contraindicada en trabajo de parto"]),
  d=dict(rotulo="Podálica: ¿parto vaginal o cesárea?", eje_y="Momento", ancho_filas=180,
         cols=["Multípara, pelvis probada, feto no grande", "Primigesta o feto grande"],
         rows=[("Expulsivo (dilatación completa)", "Este caso"), ("Antes del trabajo de parto", "36-37 semanas")],
         cells=[[("PARTO VAGINAL ASISTIDO", ["Bracht, Mauriceau"]), ("Cesárea", ["Si no hay contraindicación de tiempo"])],
                [("Versión cefálica externa", ["O cesárea programada"]), ("Cesárea programada", [])]],
         caso=(0, 0), nota="AU de 29 cm sugiere feto pequeño: favorece el parto vaginal."))

# NEU-053 · COVID-19 con PaFi > 300: oxígeno convencional · REGLA
S("regla", "NEU-053", "Obeso con COVID-19, SatO₂ 90 %, PaO₂ 64, FR 26 y PaO₂/FiO₂ de 305: falla respiratoria leve, oxigenoterapia convencional no invasiva (cánula o mascarilla)",
  "COVID-19 · soporte respiratorio",
  ("Escalera de soporte respiratorio", ["Oxígeno convencional (cánula, mascarilla) → cánula nasal de alto flujo → ventilación no invasiva → ventilación mecánica.",
                                        "Se sube de escalón según la oxigenación (PaO₂/FiO₂, SatO₂) y el trabajo respiratorio."]),
  ("Varón obeso de 55 años, COVID-19", ["SatO₂ baja; afebril, FR 26, FC 100.", "PaO₂/FiO₂ 305, PaO₂ 64, SatO₂ 90 %."]),
  ["Meta SatO₂ 92-96 %; posición prona despierto si tolera.",
   "Dexametasona 6 mg/día si necesita oxígeno.",
   "Subir a alto flujo si la SatO₂ no mejora o aumenta el trabajo respiratorio; intubar si falla."],
  OMS + ", manejo clínico de COVID-19 (2023); NIH (2024).",
  op=("¿Terapia?", ["No: aún no", "No: aún no", "Sí: oxígeno convencional", "No: no hay criterios", "No: no hay criterios"],
      {2: "Oxigenoterapia convencional (cánula/mascarilla)"}),
  d=dict(rotulo="¿Qué tan mal oxigena?",
         reglas=[dict(nombre="PaO₂/FiO₂", que="> 300 normal o leve; 200-300 leve-moderado (SDRA leve); 100-200 moderado; < 100 grave.",
                      min=0, max=450, fmt="{}", ticks=[100, 200, 300],
                      bandas=[(0, 100, "Grave", 3), (100, 200, "Moderado", 3), (200, 300, "Leve", 2), (300, 450, "Límite", 1)],
                      caso=305, caso_txt="ESTE CASO: 305"),
                 dict(nombre="SatO₂ (%)", que="Meta 92-96 %.", min=80, max=100, fmt="{}", ticks=[92],
                      bandas=[(80, 92, "Baja: dar oxígeno", 2), (92, 100, "Meta", 0)], caso=90, caso_txt="90 %")],
         claves_titulo="La escalera del oxígeno",
         claves=[("1. Cánula o mascarilla", ["Este caso"], True), ("2. Alto flujo / VNI", ["Si no mejora"], False), ("3. Ventilación mecánica", ["Si falla o se agota"], False)]))

# CAR-064 · Asistolia: adrenalina y RCP · CUADRÍCULA (ritmos de paro)
S("cuadricula", "CAR-064", "Paciente monitorizada que pierde la conciencia con asistolia en el monitor: ritmo no desfibrilable, RCP y adrenalina lo antes posible",
  "Reanimación cardiopulmonar · ritmos de paro",
  ("Ritmos de paro", ["Desfibrilables: fibrilación ventricular y TV sin pulso → descarga.",
                      "No desfibrilables: asistolia y actividad eléctrica sin pulso → RCP + adrenalina 1 mg cada 3-5 min lo antes posible y buscar causas (H y T)."]),
  ("Mujer de 58 años con IMA sin ST elevado", ["Monitorizada en shock trauma.", "Pierde la conciencia; el monitor muestra asistolia."]),
  ["Confirmar asistolia en 2 derivaciones y revisar cables (que no sea FV fina).",
   "RCP de alta calidad + adrenalina 1 mg EV/IO ya; repetir cada 3-5 min.",
   "Nunca descargar una asistolia; la amiodarona es para FV/TV refractaria."],
  AHA + "; ERC (2025).",
  op=("¿Primer paso?", ["No: la asistolia no se descarga", "Sí: no desfibrilable (con RCP)", "No: ya no se recomienda", "No: no antes de RCP y adrenalina", "No: es para FV/TV"]),
  d=dict(rotulo="¿Qué ritmo de paro es?", alto_img=90,
         celdas=[("Asistolia", ["Línea plana: no desfibrilable", "RCP + adrenalina ya"], P("ecg_asistolia.jpg", 450, 90, [], credito=ECG_PROPIO, fondo="#ffffff"), True),
                 ("Fibrilación ventricular", ["Caótica: desfibrilable", "Descarga + RCP"], P("ecg_fv.jpg", 188, 90, [], credito=ECG_PROPIO, fondo="#ffffff"), False),
                 ("TV sin pulso", ["QRS ancho rápido: desfibrilable", "Descarga + RCP"], P("ecg_tv.jpg", 450, 90, [], credito=ECG_PROPIO, fondo="#ffffff"), False),
                 ("Actividad eléctrica sin pulso", ["Ritmo organizado sin pulso", "RCP + adrenalina; buscar H y T"], None, False)],
         credito="Trazados de enseñanza MedQuizPro (no son de pacientes)",
         veredicto=("Asistolia = RCP + adrenalina", "No se descarga.")))

# HEM-036 · Drepanocitosis · LECTURA (frotis)
S("lectura", "HEM-036", "Joven afrodescendiente con anemia, ictericia indirecta, reticulocitos en 0 % y banda anormal en la electroforesis: drepanocitosis (con crisis aplásica); en el frotis hay drepanocitos",
  "Hemoglobinopatías · anemia falciforme",
  ("Anemia falciforme", ["Hemoglobina S: con hipoxia o deshidratación los glóbulos rojos toman forma de hoz (drepanocitos), se rompen y tapan vasos.",
                         "Reticulocitos en 0 % en un hemolítico = crisis aplásica (casi siempre por parvovirus B19)."]),
  ("Varón de 25 años, afropanameño", ["Anemia e ictericia.", "Hb 8, reticulocitos 0 %, BT 6 (BD 1); banda anormal en la electroforesis."]),
  ["Crisis aplásica: transfusión y soporte; se recupera en 7-10 días.",
   "Prevención: hidroxiurea, ácido fólico, vacunas (neumococo, meningococo, Hib), penicilina profiláctica en niños.",
   "Crisis dolorosa: hidratación, oxígeno si falta, analgesia con opioides."],
  "NHLBI, enfermedad de células falciformes (2014; act.); ASH (2020).",
  op=("¿Eritrocitos?", ["Pueden aparecer, pero el típico es otro", "No: son de la ferropenia", "No: eliptocitosis hereditaria", "Sí: forma de hoz", "No: esferocitosis o autoinmune"]),
  d=dict(rotulo="Lee el frotis", img_titulo="Frotis de anemia falciforme",
         img=PA("drepano.jpg", 330, credito="Paulo Henrique Orlandi Mourao" + CC + "CC BY-SA 4.0"), pines=[(0.83, 0.36)],
         pasos=[("Glóbulos en forma de hoz", "Drepanocitos (Hb S polimerizada).", True),
                ("Dianocitos acompañantes", "Frecuentes, pero no son los típicos.", False),
                ("Electroforesis: banda de Hb S", "Confirma.", False),
                ("Reticulocitos 0 %", "Crisis aplásica por parvovirus B19.", False)],
         img_pie="Frotis de otro paciente.",
         veredicto=("Hb S + hemólisis = drepanocitos en el frotis", "Reticulocitos en 0: crisis aplásica; transfundir.")))

# PED-188 · Hierro en el bajo peso al nacer: desde el mes · CALENDARIO
S("calendario", "PED-188", "Niño con peso al nacer de 2100 g (bajo peso): la suplementación preventiva con hierro empieza al mes de vida",
  "Prevención de anemia infantil",
  ("Suplementación preventiva de hierro (MINSA)", ["Prematuros y bajo peso al nacer (< 2500 g): hierro en gotas 2 mg/kg/día desde los 30 días hasta los 6 meses.",
                                                    "Nacidos a término con peso adecuado: desde los 4 meses hasta los 6; luego micronutrientes o hierro hasta los 12-35 meses."]),
  ("Pregunta de teoría", ["Niño con peso al nacer de 2100 g.", "¿A qué edad inicia el hierro preventivo?"]),
  ["Bajo peso: 2 mg/kg/día de hierro elemental desde el mes hasta los 6 meses.",
   "Tamizaje de hemoglobina a los 6 meses (antes si es prematuro o bajo peso).",
   "Pinzamiento tardío del cordón y lactancia materna exclusiva también previenen la anemia."],
  MINSA + ", NTS de prevención y control de la anemia (RM 251-2024-MINSA).",
  op=("¿Edad de inicio?", ["No: es tarde para bajo peso", "Sí: bajo peso, desde el mes", "No: es tarde", "Es para nacidos a término con peso normal", "No: muy tarde"]),
  d=dict(rotulo="Cuándo empieza el hierro preventivo", tag="BAJO PESO",
         edades=["1 mes", "2 meses", "4 meses", "6 meses"], caso_col=0, titulo_filas="Recién nacido",
         filas=[("Bajo peso o prematuro (< 2500 g)", {0: ("Inicia", "falta"), 1: ("Sigue", "prog"), 2: ("Sigue", "prog"), 3: ("Hb", "prog")}, "2 mg/kg/día desde el mes; Hb a los 6 meses."),
                ("Término con peso adecuado", {2: ("Inicia", "prog"), 3: ("Hb", "prog")}, "Desde los 4 meses; Hb a los 6 meses.")],
         leyenda="! inicia aquí (este caso) · ○ programado",
         veredicto=("Bajo peso al nacer: hierro desde el primer mes", "Los nacidos a término con peso adecuado empiezan a los 4 meses.")))

# CIR-104 · Isquemia mesentérica aguda · CASCADA + Rx
S("cascada", "CIR-104", "Anciano hipertenso con dolor abdominal desproporcionado que se generaliza, melena, irritación peritoneal, leucocitosis, LDH alta y neumatosis: isquemia mesentérica aguda",
  "Abdomen agudo vascular",
  ("Isquemia mesentérica aguda", ["Embolia (FA) o trombosis de la arteria mesentérica superior; también no oclusiva o venosa.",
                                  "Primero dolor desproporcionado al examen; luego, al necrosarse, peritonitis, sangrado, acidosis láctica, LDH alta y neumatosis."]),
  ("Hipertenso de 81 años", ["Deposiciones negras y dolor epigástrico que se hace difuso.", "Distensión, irritación peritoneal; neumatosis; leucocitos 17 000, LDH 1082."]),
  ["Angio-TC es el estudio de elección (no esperar si hay peritonitis).",
   "Heparina, líquidos, antibiótico; con peritonitis: laparotomía (resección del intestino necrótico) ± revascularización.",
   "Mortalidad 50-70 %: el tiempo es intestino."],
  "ESVS, enfermedad mesentérica (2017; act.); WSES (2022).",
  op=("¿Diagnóstico?", ["No: dolor en FII, sin neumatosis", "Sí: neumatosis + LDH alta + peritonitis", "No: no da neumatosis ni melena", "No explica la neumatosis", "No: neumoperitoneo, no neumatosis"]),
  d=dict(rotulo="Del vaso tapado al intestino muerto", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Se tapa la mesentérica superior", "Embolia (FA) o trombosis", [("Dolor desproporcionado", "Abdomen blando al inicio", False)]),
                ("La mucosa sufre primero", "Se desprende y sangra", [("Melena", "Sangre en las heces", True)]),
                ("Necrosis de toda la pared", "Gas que entra en la pared", [("Neumatosis", "En la Rx", True), ("LDH y lactato altos", "LDH 1082", True)]),
                ("Peritonitis", "Bacterias atraviesan la pared necrosada", [("Irritación peritoneal, leucocitosis", "17 000", False)])],
         veredicto=("Isquemia mesentérica aguda con necrosis", "Laparotomía urgente.")))

# GIN-192 · Perforación uterina con histerómetro sin sangrado · ÁRBOL
S("arbol", "GIN-192", "Perforación uterina con el histerómetro durante un legrado, sin sangrado activo: observación con control de funciones vitales",
  "Complicaciones del legrado · perforación uterina",
  ("Perforación uterina", ["Con un instrumento romo y fino (histerómetro, dilatador) en el fondo uterino suele cerrar sola.",
                           "Con cánula de succión o legra, con sangrado, en la pared lateral (vasos uterinos) o si se sospecha lesión de intestino: laparoscopia o laparotomía."]),
  ("Legrado por aborto incompleto", ["Se produce una perforación con el histerómetro.", "Sin sangrado activo externo."]),
  ["Suspender el procedimiento (completarlo después bajo guía ecográfica o laparoscópica).",
   "Hospitalizar: funciones vitales, dolor, hemoglobina; uterotónico y antibiótico profiláctico.",
   "Si hay inestabilidad, dolor creciente o sangrado: laparoscopia o laparotomía."],
  WILLIAMS + "; RCOG (2010; act.); OMS, atención del aborto (2022).",
  op=("¿Conducta?", ["Insuficiente sin vigilar", "No: no hay sangrado ni inestabilidad", "Sí: perforación pequeña y estable", "No: no hay sangrado", "No: excesivo"]),
  arbol=Q("Perforación uterina: ¿con qué y cómo está la paciente?", [
      L("Histerómetro, sin sangrado, estable (este caso)", "OBSERVAR Y CONTROLAR FUNCIONES VITALES", ["Uterotónico y antibiótico", "Hb seriada"], path=True),
      L("Succión, sangrado o inestable", "Laparoscopia o laparotomía", ["Revisar intestino y vasos"])], path=True))

# NEU-054 · Madre con TB en tratamiento: lactar con mascarilla · BALANZA
S("balanza", "NEU-054", "Puérpera con tuberculosis sensible en tratamiento desde el tercer trimestre: puede dar de lactar usando mascarilla",
  "Tuberculosis y lactancia",
  ("TB en la madre que amamanta", ["Los antituberculosos de primera línea son compatibles con la lactancia y la leche no transmite la TB.",
                                   "Con tratamiento de varias semanas la madre ya no contagia (o muy poco): mascarilla mientras amamanta y buena ventilación."]),
  ("Puérpera inmediata", ["En tratamiento de TB sensible desde el tercer trimestre.", "¿Puede alimentar a su recién nacido?"]),
  ["Lactancia directa con mascarilla quirúrgica o de tela.",
   "RN: descartar TB congénita/activa y dar terapia preventiva con isoniazida (6 meses) si no tiene enfermedad; BCG después según la norma.",
   "Piridoxina a la madre (isoniazida)."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + ", TB en niños y lactancia (2022).",
  op=("¿Qué indicar?", ["Sí: lactar con mascarilla", "No: puede lactar directo", "No: pierde los beneficios de la leche materna", "No: la mascarilla quirúrgica basta",
                               "No: no está contraindicada"],
      {0: "Lactar usando mascarilla de tela o quirúrgica", 1: "Darle leche extraída manualmente", 2: "Alimentar con sucedáneos"}),
  d=dict(rotulo="¿Lactar o no lactar?", gana="izq", pregunta="¿Qué pesa más?",
         izq=dict(titulo="A favor de lactar", peso="LACTAR", items=["Ya lleva semanas de tratamiento", "La leche no transmite la TB", "Fármacos compatibles",
                                                                    "Beneficios de la leche materna"]),
         der=dict(titulo="Riesgos a cuidar", peso="CUIDAR", items=["Contagio por gotitas", "Con mascarilla y ventilación se controla", "Terapia preventiva al RN"]),
         veredicto=("Dar de lactar con mascarilla", ["Isoniazida preventiva al bebé si no está enfermo."])))

# PED-189 · Enfermedad hemorrágica tardía por déficit de vitamina K · TARJETAS
S("tarjetas", "PED-189", "Lactante de 1 mes, nacida en casa (sin vitamina K) y con lactancia exclusiva, con sangrado de mucosas, hematemesis, palidez e irritabilidad: enfermedad hemorrágica tardía por déficit de vitamina K",
  "Enfermedad hemorrágica del recién nacido",
  ("Déficit de vitamina K en el lactante", ["La leche materna tiene poca vitamina K y el intestino del bebé aún no la fabrica: sin profilaxis al nacer pueden sangrar.",
                                            "Forma tardía (2-12 semanas): la más grave, con hemorragia intracraneal frecuente (llanto persistente, irritabilidad)."]),
  ("Lactante de 1 mes", ["Parto domiciliario; lactancia materna exclusiva.", "2 días de sangrado oral y vómitos con sangre; hoy palidez y llanto que no calma."]),
  ["Vitamina K 1-2 mg EV/SC de inmediato; plasma fresco si hay sangrado grave.",
   "TC cerebral urgente (llanto inconsolable: posible hemorragia intracraneal).",
   "TP y TTPa prolongados con plaquetas normales. Prevención: vitamina K 1 mg IM a todo RN."],
  AAP + ", vitamina K neonatal (2022); " + MINSA + ".",
  op=("¿Sospecha?", ["Sí: sin vitamina K + lactancia exclusiva", "No: niño grave con sepsis y plaquetas bajas", "No: varón, sangrado articular", "No: trombosis, no sangrado",
                     "No: petequias, plaquetas bajas"]),
  d=dict(rotulo="Las tres formas de la enfermedad hemorrágica", ans=2,
         cards=[dict(titulo="Precoz", datos=[("Cuándo", "< 24 horas", False), ("Causa", "Fármacos maternos", False), ("Ej.", "Anticonvulsivantes", False)], pie="Rara."),
                dict(titulo="Clásica", datos=[("Cuándo", "2-7 días", False), ("Sangra", "Ombligo, intestino", False), ("Previene", "Vitamina K al nacer", False)], pie="La más frecuente sin profilaxis."),
                dict(titulo="Tardía", datos=[("Cuándo", "2-12 semanas", True), ("Sangra", "Cerebro, mucosas", True), ("Riesgo", "Lactancia exclusiva", True)], pie="Este caso.")]),
  triada=TR([("Sin vitamina K al nacer", "Parto domiciliario", True), ("Lactancia materna exclusiva", "Sí", True), ("Sangrado + llanto persistente", "Posible hemorragia intracraneal", True)],
            [("Pistas de la forma tardía", 0, 2)], "TC cerebral urgente y vitamina K sin esperar."))

# NRL-050 · Temblor parkinsoniano · TARJETAS
S("tarjetas", "NRL-050", "Anciano con temblor de manos que desaparece al iniciar el movimiento y reaparece al llegar a la boca, con bradicinesia: temblor parkinsoniano (de reposo)",
  "Trastornos del movimiento · temblor",
  ("Tipos de temblor", ["De reposo: aparece con la mano quieta y cede al moverse (Parkinson); puede reaparecer al mantener una postura («reemergente»).",
                        "Postural y de acción: esencial (bilateral, mejora con alcohol). De intención: empeora al acercarse al objetivo (cerebelo)."]),
  ("Varón de 78 años", ["Temblor de manos que se detiene al levantar la taza y reaparece al llegar a la boca.", "Bradicinesia."]),
  ["Parkinson: bradicinesia + temblor de reposo y/o rigidez (criterios MDS).",
   "Tratamiento: levodopa/carbidopa; agonistas dopaminérgicos en jóvenes.",
   "Temblor esencial: propranolol o primidona."],
  "MDS, criterios de enfermedad de Parkinson (2015); " + HARRISON + ".",
  op=("¿Tipo de temblor?", ["Sí: reposo + bradicinesia", "No: postural, sin bradicinesia", "No: no es una categoría", "No: empeora al acercarse al objetivo", "No: con postura distónica"]),
  d=dict(rotulo="¿Cuándo tiembla?", ans=0,
         cards=[dict(titulo="Parkinsoniano", datos=[("Cuándo", "En reposo", True), ("Al moverse", "Cede (reaparece luego)", True), ("Además", "Bradicinesia, rigidez", True)], pie="Este caso."),
                dict(titulo="Esencial", datos=[("Cuándo", "Postura y acción", False), ("Familia", "Antecedente frecuente", False), ("Mejora", "Con alcohol", False)], pie="Bilateral."),
                dict(titulo="Cerebeloso", datos=[("Cuándo", "Al acercarse al objetivo", False), ("Además", "Dismetría, ataxia", False), ("Lesión", "Cerebelo", False)], pie="De intención."),
                dict(titulo="Distónico", datos=[("Cuándo", "Con postura anormal", False), ("Además", "Distonía", False), ("Ej.", "Tortícolis", False)], pie="Irregular.")]))

# SP-143 · Cuidado comunitario de la salud · PIRÁMIDE
S("piramide", "SP-143", "Ante el aumento de obesidad en escolares por falta de actividad física, promover un campo deportivo en el distrito es cuidado comunitario de la salud",
  "Modelo de Cuidado Integral · niveles de cuidado",
  ("Cuidado integral de la salud (MINSA)", ["El cuidado se da en varios ámbitos: individual, familiar y comunitario.",
                                            "Comunitario: acciones sobre los determinantes del entorno (espacios, servicios, organización) que benefician a toda la población."]),
  ("Centro de salud", ["Aumentó el sobrepeso y la obesidad en escolares de 5-9 años.", "Factor: falta de actividad física → se promueve un campo deportivo en el distrito."]),
  ["Trabajar con la municipalidad, escuelas y organizaciones (acción intersectorial).",
   "Complementar con cuidado individual (consejería nutricional) y familiar (hábitos en casa).",
   "Es promoción de la salud (entornos saludables, Carta de Ottawa)."],
  MINSA + ", Modelo de Cuidado Integral de Salud por Curso de Vida (MCI, 2020).",
  op=("¿Tipo de cuidado?", ["No: atención de la enfermedad", "Sí: cambia el entorno de todos", "No: hábitos en el hogar", "No: una persona", "No: hospital"]),
  d=dict(rotulo="Del cuidado individual al comunitario", caso=2, tag="ESTE CASO", ancho=400,
         niveles=[("1", "Individual", "Consejería al niño obeso."),
                  ("2", "Familiar", "Hábitos de comida y juego en casa."),
                  ("3", "Comunitario", "Campo deportivo para todo el distrito.")],
         pie="De una persona a toda la comunidad",
         veredicto=("Campo deportivo en el distrito = cuidado comunitario", "Actúa sobre el entorno que comparten todos los niños.")))

# OFT-044 · Tapón de cerumen por hisopos · LECTURA (esquema)
S("lectura", "OFT-044", "Adulto mayor que se limpia los oídos con hisopo y presenta hipoacusia y tinnitus de inicio reciente: tapón de cerumen",
  "Oído externo · tapón de cerumen",
  ("Tapón de cerumen", ["El cerumen sale solo; el hisopo lo empuja hacia adentro y lo compacta contra el tímpano.",
                        "Hipoacusia de conducción súbita (a menudo tras bañarse, el agua lo hincha), plenitud, tinnitus."]),
  ("Varón de 65 años", ["2 días de hipoacusia y tinnitus en el oído derecho.", "Se limpia los oídos con hisopo tras el baño diario."]),
  ["Otoscopia confirma: masa marrón que tapa el conducto.",
   "Ceruminolíticos (agua oxigenada diluida, gotas de aceite) y luego lavado o extracción instrumental.",
   "No lavar si hay perforación timpánica conocida; dejar de usar hisopos."],
  "AAO-HNS, impactación de cerumen (2017).",
  op=("¿Diagnóstico?", ["No: niños, fiebre, tímpano abombado", "No: no tiene inicio tan brusco con hisopo", "No: dolor al mover el pabellón", "Sí: hisopo + hipoacusia brusca",
                        "No: progresiva y bilateral"]),
  d=dict(rotulo="Lee el esquema", img_titulo="Tapón de cerumen (esquema)",
         img=P("dib_cerumen.jpg", 330, 238, credito=PROPIO, fondo="#ffffff"), pines=[(0.5, 0.5)],
         pasos=[("Cerumen compactado en el conducto", "El hisopo lo empuja hacia adentro.", True),
                ("Tapa el paso del sonido", "Hipoacusia de conducción.", False),
                ("Toca el tímpano", "Tinnitus y plenitud.", False),
                ("Tratamiento", "Ceruminolítico y lavado.", False)],
         img_pie="Esquema.",
         veredicto=("Hisopo + hipoacusia súbita = tapón de cerumen", "Ablandar y retirar; no usar hisopos.")))

# INF-093 · Gestante con VIH y PPD positivo: isoniazida · DECISIÓN
S("decision", "INF-093", "Gestante de 14 semanas con VIH, asintomática y PPD de más de 5 mm: infección tuberculosa latente, terapia preventiva con isoniazida por 6 meses",
  "Tuberculosis latente · VIH y embarazo",
  ("Infección tuberculosa latente en VIH", ["En personas con VIH un PPD ≥ 5 mm es positivo (≥ 10 mm en la población general).",
                                            "Sin TB activa (sin síntomas, Rx normal), se da terapia preventiva: isoniazida 6 meses + piridoxina (segura en el embarazo)."]),
  ("Gestante de 14 semanas", ["VIH positivo, asintomática.", "Tuberculina > 6 mm."]),
  ["Descartar TB activa: síntomas, Rx de tórax con protección abdominal.",
   "Isoniazida 300 mg/día por 6 meses + piridoxina; vigilar hepatotoxicidad (más en el embarazo y el puerperio).",
   "Continuar el TARGA; el esquema 3HP no se recomienda en el embarazo."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + ", TB preventiva (2024).",
  op=("¿Manejo?", ["No: alto riesgo de TB activa", "No: no tiene TB activa", "No: no tiene TB activa", "Sí: terapia preventiva", "No: esquema no recomendado aquí"]),
  d=dict(rotulo="PPD: ¿cuándo es positivo y qué hacer?", eje_y="Paciente", ancho_filas=180,
         cols=["PPD 5-9 mm", "PPD ≥ 10 mm"],
         rows=[("VIH o inmunosuprimido", "Este caso"), ("Población general", "")],
         cells=[[("POSITIVO: ISONIAZIDA 6 MESES", ["Tras descartar TB activa"]), ("Positivo: isoniazida", [])],
                [("Negativo", ["No requiere"]), ("Positivo: evaluar profilaxis", ["Contactos, riesgo"])]],
         caso=(0, 0), nota="Siempre descartar TB activa antes (síntomas y Rx)."))

# HEM-037 · Déficit de vitamina B12 · LABORATORIO + frotis
S("laboratorio", "HEM-037", "Anciana con deterioro cognitivo, anorexia, palidez y pancitopenia con macrocitosis (VCM 105): anemia megaloblástica por déficit de B12, tratar con cianocobalamina",
  "Anemias megaloblásticas",
  ("Déficit de vitamina B12", ["Falla la síntesis de ADN: células grandes (macrocitosis) y a veces pancitopenia; neutrófilos hipersegmentados.",
                               "Además daña el sistema nervioso: demencia, neuropatía, degeneración combinada subaguda (el folato no lo corrige)."]),
  ("Mujer de 71 años, 2 meses", ["Deterioro de capacidades mentales y anorexia severa; palidez, orientada solo en persona.", "Hb 8,5, VCM 105, leucocitos 3500, plaquetas 80 000."]),
  ["Dosar B12 y folato (± ácido metilmalónico); anticuerpos anti-factor intrínseco (anemia perniciosa).",
   "Cianocobalamina 1000 µg IM diaria por 1 semana, luego semanal y después mensual (de por vida si es perniciosa).",
   "No dar ácido fólico solo: corrige la anemia pero empeora el daño neurológico."],
  "BSH, déficit de B12 y folato (2014; act.); " + HARRISON + ".",
  op=("¿Tratamiento?", ["No: anemia sideroblástica", "Sí: anemia megaloblástica con demencia", "No: queilitis", "No: beriberi, Wernicke", "No: la ferropenia es microcítica"]),
  d=dict(rotulo="El hemograma de la paciente",
         valores=[("VCM", "105 fL", "80-100", "↑", "Macrocitosis: B12 o folato."),
                  ("Hemoglobina", "8,5 g/dL", "12-16", "↓", "Anemia."),
                  ("Leucocitos", "3500", "4000-10 000", "↓", "Pancitopenia: médula megaloblástica."),
                  ("Plaquetas", "80 000", "150 000-450 000", "↓", "Pancitopenia."),
                  ("Vitamina B12", "Por pedir", "> 200-300 pg/mL", "=", "Baja confirma; con demencia, B12 más que folato.")],
         veredicto=("Macrocitosis + pancitopenia + demencia = déficit de B12", "Cianocobalamina IM.")),
  banda=B("Lo que muestra el frotis", P("hiperseg2.jpg", 300, 251, [], credito="Ed Uthman" + CC + "CC BY 2.0", fondo="#ffffff"),
          [("Neutrófilo hipersegmentado", "≥ 6 lóbulos: típico de la anemia megaloblástica."), ("Macroovalocitos", "Glóbulos rojos grandes y ovalados."),
           ("Demencia reversible", "Por eso se pide B12 en todo deterioro cognitivo.")],
          pie="Frotis de otro paciente."))
