"""Entrega 1 · tanda 08 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, AAP, OMS, IDSA, CDC, ADA, AHA, FIGO, ESC, NICE, KDIGO, SSC, GOLD, GINA, SCHWARTZ, SABISTON
from esc28 import PAGE, ABORTO, MONIF

CC = " · Wikimedia Commons · "

# GIN-031 · Endometritis puerperal · TARJETAS
S("tarjetas", "GIN-031", "Puérpera de 3 días con fiebre, útero subinvolucionado y doloroso y loquios fétidos: endometritis puerperal",
  "Infecciones del puerperio · endometritis",
  ("Endometritis puerperal", ["Infección polimicrobiana del endometrio tras el parto; más frecuente tras cesárea.",
                              "Fiebre, útero blando y doloroso, loquios fétidos en los primeros días."]),
  ("Puérpera de 3 días", ["Fiebre de 38,5 °C y malestar general.", "Útero subinvolucionado y doloroso; loquios fétidos."]),
  ["Tratamiento EV: clindamicina + gentamicina hasta 24-48 h sin fiebre; no hace falta seguir por vía oral.",
   "Si no mejora en 48-72 h: buscar restos (ecografía), absceso o tromboflebitis pélvica séptica.",
   "Fiebre puerperal: pensar en útero, mama, herida, orina, pulmón y piernas (trombosis)."],
  ACOG + "; " + WILLIAMS + "; " + OMS + ", prevención y tratamiento de infecciones maternas en el periparto (2015).",
  op=("¿Encaja?", ["No: es antes del parto", "Sí: útero doloroso + loquios fétidos", "No: herida roja con secreción", "No: tras cesárea, dolor de herida",
                   "No: mama roja y dolorosa"]),
  d=dict(rotulo="Fiebre en el puerperio: ¿de dónde viene?", ans=0,
         cards=[dict(titulo="Endometritis", datos=[("Útero", "Doloroso, blando", True), ("Loquios", "Fétidos", True), ("Día", "2-5", True)],
                     pie="Este caso: clindamicina + gentamicina."),
                dict(titulo="Mastitis", datos=[("Mama", "Roja, dura", False), ("Día", "2-6 semanas", False), ("Lactancia", "Seguir", False)],
                     pie="Dicloxacilina."),
                dict(titulo="Infección de herida", datos=[("Herida", "Roja, secreción", False), ("Día", "4-7", False), ("Útero", "Normal", False)],
                     pie="Drenar, antibiótico."),
                dict(titulo="Pielonefritis", datos=[("Dolor", "Lumbar", False), ("Orina", "Leucocitos", False), ("Útero", "Normal", False)],
                     pie="Urocultivo.")]))

# CB-009 · Implantación: blastocisto · FASES
S("fases", "CB-009", "La implantación en el endometrio ocurre en la etapa de blastocisto (días 6-7)",
  "Embriología · primera semana del desarrollo",
  ("Primera semana del desarrollo", ["Fecundación en la ampolla de la trompa, segmentación mientras baja al útero.",
                                     "Al día 6-7 el blastocisto sale de la zona pelúcida y se implanta."]),
  ("Pregunta de concepto", ["¿En qué etapa se implanta el embrión?"]),
  ["Cigoto (día 1) → mórula de 16 células (día 3-4) → blastocisto con cavidad (día 5) → implantación (día 6-7).",
   "El trofoblasto invade el endometrio y empieza a producir hCG.",
   "La implantación fuera del útero (trompa) es el embarazo ectópico."],
  "Langman, Embriología médica 15.ª ed. (2023); Moore, Embriología clínica 11.ª ed. (2019).",
  op=("¿Se implanta?", ["Sí: día 6-7", "No: aún en la trompa", "No: recién fecundado", "No: es una célula", "No: es posterior (3.ª semana)"]),
  d=dict(rotulo="Del cigoto a la implantación", ans=2,
         fases=[("Fecundación", "Día 1", "CIGOTO", ["En la ampolla de la trompa"]),
                ("Segmentación", "Días 2-4", "MÓRULA", ["Baja por la trompa"]),
                ("Implantación", "Días 5-7", "BLASTOCISTO", ["Sale de la zona pelúcida", "Se adhiere al endometrio"])]))

# GIN-032 · Corioamnionitis · ÁRBOL + Triple I
S("arbol", "GIN-032", "Fiebre de 39 °C en el parto con taquicardia fetal de 165: corioamnionitis",
  "Infecciones intraamnióticas · corioamnionitis",
  ("Corioamnionitis (infección intraamniótica, «Triple I»)", ["Infección de las membranas y el líquido amniótico, casi siempre ascendente.",
                                                              "Fiebre materna + taquicardia fetal, leucocitosis o secreción purulenta."]),
  ("Gestante de 39 semanas", ["Fase latente; recibió misoprostol 4 h antes y peridural.", "Fiebre de 39 °C; FCF 165."]),
  ["Antibióticos EV ya (ampicilina + gentamicina) y terminar el parto; la cesárea solo por indicación obstétrica.",
   "La peridural o el misoprostol pueden dar febrícula, pero no explican 39 °C con taquicardia fetal: se trata como infección.",
   "Avisar al neonatólogo: el recién nacido tiene riesgo de sepsis."],
  ACOG + " Committee Opinion n.º 712, intrapartum management of intraamniotic infection (2017, reafirmado 2024).",
  op=("¿Más probable?", ["Es consecuencia, no la causa", "Posible febrícula, no 39 °C con taquicardia fetal", "Suele ser febrícula",
                         "Sí: fiebre ≥ 39 °C + taquicardia fetal", "No: sin síntomas urinarios"]),
  arbol=Q("Fiebre intraparto: ¿≥ 39 °C (o ≥ 38 °C repetida) con otro signo?", [
      L("Sí: FCF 165 (este caso)", "CORIOAMNIONITIS", ["Ampicilina + gentamicina EV", "Terminar el parto"], path=True),
      L("No, febrícula aislada", "Vigilar", ["Peridural, misoprostol, deshidratación"])], path=True),
  triada=TR([("Fiebre materna ≥ 39 °C", "39 °C", True), ("Taquicardia fetal > 160", "165 lpm", True), ("Leucocitosis materna", "No se informa", False),
             ("Secreción cervical purulenta", "No se informa", False)],
            [("Criterios de Triple I (ACOG)", 0, 3)], "Fiebre ≥ 39 °C + un criterio más: infección intraamniótica sospechada; tratar ya.",
            rotulo="Criterios con nombre propio"))

# GIN-033 · DPP con feto bien · TARJETAS + Page
S("tarjetas", "GIN-033", "38 semanas con dolor epigástrico, sangrado rojo vinoso, PA 140/90 y útero contraído: desprendimiento prematuro de placenta",
  "Hemorragias de la segunda mitad del embarazo",
  ("Desprendimiento prematuro de placenta (DPP)", ["Dolor, útero contraído y sangrado oscuro; la hipertensión es su principal factor de riesgo.",
                                                   "El dolor puede referirse al epigastrio o la espalda."]),
  ("Gestante de 38 semanas", ["Dolor epigástrico y sangrado vaginal rojo vinoso.", "PA 140/90, FCF 128, útero contraído."]),
  ["A término con feto vivo: terminar la gestación (parto vaginal si avanza rápido y el feto está bien; si no, cesárea).",
   "Vigilar coagulación y preeclampsia (PA 140/90: pedir proteinuria y laboratorio).",
   "Placenta previa y vasa previa sangran sin dolor; la rotura uterina da dolor súbito con cicatriz previa."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ".",
  op=("¿Más probable?", ["No: sin cicatriz ni partes fetales palpables", "Sí: dolor + útero contraído + sangre oscura", "No: al romper membranas, feto afectado",
                         "No: indoloro", "No: indoloro, sangrado escaso"]),
  d=dict(rotulo="Sangrado en el tercer trimestre", ans=0,
         cards=[dict(titulo="DPP", datos=[("Dolor", "Sí", True), ("Útero", "Contraído", True), ("Sangre", "Oscura", True)], pie="Este caso."),
                dict(titulo="Placenta previa", datos=[("Dolor", "No", False), ("Útero", "Blando", False), ("Sangre", "Roja brillante", False)],
                     pie="No hacer tacto."),
                dict(titulo="Rotura uterina", datos=[("Antecedente", "Cesárea", False), ("Dolor", "Súbito", False), ("Feto", "Bradicardia", False)],
                     pie="Laparotomía."),
                dict(titulo="Seno marginal", datos=[("Dolor", "No", False), ("Sangrado", "Escaso", False), ("Feto", "Bien", False)],
                     pie="Diagnóstico tras el parto.")]),
  escala=PAGE(1, [("Feto vivo con FCF normal (128)", True), ("Madre estable; útero contraído y sangrado moderado", True),
                  ("Sin sufrimiento fetal: no es grado II", False)],
              "Grado I a término: terminar la gestación con vigilancia de la coagulación y de la PA."))

# GIN-034 · Placenta previa · ÁRBOL
S("arbol", "GIN-034", "35 semanas con sangrado vaginal escaso, indoloro y sin contracciones: hospitalizar y pedir ecografía",
  "Hemorragias de la segunda mitad del embarazo · placenta previa",
  ("Placenta previa", ["La placenta cubre o está a menos de 2 cm del orificio cervical interno.",
                       "Sangrado rojo, indoloro y recurrente en el tercer trimestre."]),
  ("Gestante de 35 semanas", ["Pérdida de sangre vaginal escasa.", "Sin dolor ni contracciones."]),
  ["Nunca tacto vaginal ni rectal ni taponamiento: puede desencadenar una hemorragia masiva.",
   "Hospitalizar, ecografía (transvaginal es segura y la más exacta), monitoreo fetal, corticoides si < 34 semanas.",
   "Placenta previa: cesárea programada a las 36-37 semanas; si sangra mucho, cesárea urgente."],
  ACOG + "; RCOG Green-top n.º 27a (2018); " + WILLIAMS + ".",
  op=("¿Más apropiada?", ["No: puede desencadenar hemorragia", "No: contraindicado", "Sí: vigilar y ubicar la placenta", "No: no detiene el sangrado",
                          "No: primero ubicar la placenta"]),
  arbol=Q("Sangrado indoloro del tercer trimestre", [
      L("No hacer tacto (este caso)", "HOSPITALIZAR + ECOGRAFÍA", ["Ubicar la placenta", "Monitoreo materno-fetal"], path=True),
      L("Sangrado masivo", "Cesárea urgente", ["Reponer sangre"])], path=True))

# CIR-017 · Quemado extenso: cubrir con apósitos secos · ÁRBOL
S("arbol", "CIR-017", "Quemadura extensa y profunda antes de llegar al hospital: cubrir con apósitos secos y limpios",
  "Quemaduras · manejo prehospitalario",
  ("Manejo prehospitalario del quemado extenso", ["Detener la quemadura, enfriar poco tiempo y luego cubrir y abrigar.",
                                                  "En quemaduras extensas el gran riesgo es la hipotermia."]),
  ("Pregunta de concepto", ["Lesiones térmicas extensas y profundas: ¿qué hacer antes del hospital?"]),
  ["Retirar la ropa no adherida; agua fresca solo unos minutos en quemaduras pequeñas; en las extensas, no prolongar el enfriamiento.",
   "Cubrir con apósitos secos y limpios o film plástico; abrigar con mantas.",
   "Nada de cremas (sulfadiazina) ni hielo antes de la evaluación en el hospital."],
  "ISBI, guía de cuidado de quemaduras (2018); ABA, Advanced Burn Life Support (2023); " + ATLS + ".",
  op=("¿Indicado?", ["Sí: protege sin enfriar", "No: en extensas causa hipotermia", "No: dificulta evaluar la herida", "No: contaminación e hipotermia",
                     "No: más daño e hipotermia"]),
  arbol=Q("Quemadura: ¿es extensa y profunda?", [
      L("Sí (este caso)", "APÓSITOS SECOS Y ABRIGAR", ["Evitar hipotermia", "Trasladar a un centro de quemados"], path=True),
      L("No, pequeña", "Agua fresca 20 minutos", ["Luego cubrir"])], path=True))

# CAR-012 · QT largo por cloroquina · TARJETAS
S("tarjetas", "CAR-012", "Paciente con COVID-19 automedicado, palpitaciones, QT prolongado y potasio de 3: sobredosis de cloroquina",
  "Arritmias · QT largo por fármacos",
  ("QT largo por fármacos", ["Fármacos que bloquean canales de potasio alargan el QT: riesgo de torsade de pointes.",
                             "La hipopotasemia y la hipomagnesemia lo empeoran."]),
  ("Varón de 57 años con COVID-19", ["Automedicación por 8 días; palpitaciones.", "ECG con QT prolongado; K⁺ 3 mEq/L."]),
  ["Suspender el fármaco; corregir potasio (meta > 4) y magnesio.",
   "Torsade de pointes: sulfato de magnesio 2 g EV; desfibrilar si no hay pulso.",
   "La cloroquina y la hidroxicloroquina no se recomiendan para la COVID-19 (OMS)."],
  "CredibleMeds, lista de fármacos con riesgo de QT (2025); " + OMS + ", tratamientos de COVID-19 (2025); " + HARRISON + ".",
  op=("¿Sobredosis probable?", ["Alarga el QT, pero no fue lo usado en automedicación", "Sí: automedicación frecuente en COVID", "No: no alarga el QT",
                                "No: no alarga el QT", "No: taquicardia, no QT largo"]),
  d=dict(rotulo="Fármacos que alargan el QT", ans=0,
         cards=[dict(titulo="Cloroquina", datos=[("QT", "Muy largo", True), ("Uso", "Automedicación COVID", True), ("Riesgo", "Torsade", True)],
                     pie="Este caso."),
                dict(titulo="Levofloxacino", datos=[("QT", "Alarga", False), ("Uso", "Antibiótico", False), ("Riesgo", "Moderado", False)],
                     pie="También en COVID."),
                dict(titulo="Antipsicóticos", datos=[("Ej.", "Haloperidol", False), ("QT", "Alarga", False), ("Vía", "EV más riesgo", False)],
                     pie="Vigilar ECG."),
                dict(titulo="Macrólidos", datos=[("Ej.", "Azitromicina", False), ("QT", "Alarga", False), ("Junto a", "Cloroquina: peor", False)],
                     pie="Combinación peligrosa.")]))

# CB-010 · Anafilaxia por picadura · ÁRBOL
S("arbol", "CB-010", "Disnea, prurito generalizado, sibilancias y SatO₂ 90 % tras una picadura: anafilaxia, adrenalina",
  "Inmunología · anafilaxia",
  ("Anafilaxia", ["Reacción alérgica grave y rápida que compromete la respiración o la circulación.",
                  "Piel (prurito, urticaria) + respiratorio (sibilancias, hipoxemia) tras un alérgeno = anafilaxia."]),
  ("Varón de 21 años", ["Picadura en el brazo en un parque hace 2 horas.", "Falta de aire, prurito generalizado, sibilancias, SatO₂ 90 %."]),
  ["Adrenalina IM 0,5 mg (1 mg/mL) en la cara lateral del muslo; repetir cada 5-15 minutos si no mejora.",
   "Oxígeno, posición supina (sentado si hay disnea), fluidos si hay hipotensión; salbutamol para el broncoespasmo.",
   "Antihistamínicos y corticoides son coadyuvantes: no reemplazan a la adrenalina. Indicar autoinyector al alta."],
  "WAO, anaphylaxis guidance (2020); EAACI (2021); Resuscitation Council UK (2021).",
  op=("¿Inmediato?", ["Sí: primera línea", "No: no es de primera línea", "Coadyuvante, no basta", "No: no trata la anafilaxia", "Coadyuvante, tarda horas"]),
  arbol=Q("Alérgeno + piel + respiración o circulación comprometidas", [
      L("Sí: sibilancias, SatO₂ 90 % (este caso)", "ADRENALINA IM", ["0,5 mg en el muslo", "Repetir cada 5-15 min"], path=True),
      L("Solo piel", "Antihistamínico", ["Observar"])], path=True))

# NEF-013 · Metanol · EMBUDO (anión gap alto)
S("embudo", "NEF-013", "Tras una fiesta con licor: visión borrosa, coma, respiración profunda y pH 6,8 con HCO₃ 7: intoxicación por metanol",
  "Trastornos ácido-base · acidosis metabólica con anión gap alto",
  ("Acidosis metabólica con anión gap alto", ["Ácidos que se acumulan: cetonas, lactato, toxinas (metanol, etilenglicol, salicilatos), uremia.",
                                              "El metanol (licor adulterado) da además daño visual."]),
  ("Varón de 39 años", ["Bebió mucho licor en una fiesta patronal; al mediodía, visión borrosa.", "No despierta; respiración profunda; pH 6,8, HCO₃ 7."]),
  ["Calcular anión gap (Na - Cl - HCO₃) y gap osmolar: ambos altos al inicio en el metanol.",
   "Fomepizol o etanol, bicarbonato, ácido fólico y hemodiálisis (acidosis grave, coma o daño visual).",
   "Avisar a salud pública: suele haber brotes por licor adulterado."],
  "EXTRIP (2015); Goldfrank's Toxicologic Emergencies 11.ª ed. (2019).",
  op=("¿Sospecha?", ["No: no da acidosis ni ceguera", "No: grado II no da coma ni acidosis así", "Acidosis láctica, sin visión borrosa típica",
                     "Sí: licor + visión + acidosis grave", "No: sin diabetes"], {1: "Encefalopatía hepática II"}),
  d=dict(rotulo="Acidosis con anión gap alto: ¿cuál?", inicio="Coma, Kussmaul, pH 6,8, visión borrosa",
         candidatos=["Benzodiacepinas", "Encefalopatía hepática", "Cetoacidosis diabética", "Monóxido de carbono", "Metanol"],
         pasos=[("¿No explica la acidosis grave?", ["Benzodiacepinas", "Encefalopatía hepática"]),
                ("¿Glucosa alta o exposición a humo, sin visión borrosa?", ["Cetoacidosis diabética", "Monóxido de carbono"])],
         final=("METANOL", ["Licor adulterado + ojos + acidosis"]),
         nota="Fomepizol y hemodiálisis."))

# TRA-006 · Latigazo cervical · ÁRBOL + clasificación de Quebec
S("arbol", "TRA-006", "Conductor de un auto chocado por detrás: sospechar lesión cervical (latigazo)",
  "Trauma raquimedular · esguince cervical",
  ("Lesión por latigazo (whiplash)", ["En el choque posterior el cuello se hiperextiende y luego se flexiona.",
                                      "Va desde dolor cervical hasta fracturas o lesión medular: se inmoviliza hasta descartar."]),
  ("Varón de 34 años", ["Su auto fue chocado en la parte posterior.", "Recién ingresado a emergencia."]),
  ["Mantener el collarín y aplicar la regla canadiense o NEXUS para decidir si necesita imagen (TC cervical).",
   "Sin dolor en la línea media, sin déficit, sin intoxicación ni lesión distractora: se puede retirar el collarín sin imagen.",
   "La mayoría son esguinces: analgesia y movilización temprana."],
  ATLS + "; Canadian C-spine rule (Stiell 2001, validada); NICE NG41 (2016, act. 2022).",
  op=("¿Qué sospechar?", ["Sí: hiperextensión del cuello", "Posible en choques frontales con cinturón", "Sin datos que lo sugieran",
                          "Más en choques frontales a alta velocidad", "Más por el cinturón en choques frontales"]),
  arbol=Q("Choque posterior: ¿dolor en la línea media, déficit o factores de riesgo?", [
      L("Sí o no evaluable", "TC CERVICAL", ["Mantener el collarín"], path=True),
      L("No (criterios NEXUS negativos)", "Retirar el collarín", ["Analgesia, movilización"])], path=True),
  escala=dict(nombre="Clasificación de Quebec (latigazo)", orden=True, que="Gravedad del trastorno asociado a latigazo cervical.",
              grados=[("Grado 0", "Sin síntomas", ["Sin signos"]), ("Grado I", "Dolor o rigidez", ["Sin signos al examen"]),
                      ("Grado II", "Dolor + signos musculoesqueléticos", ["Menos movilidad, puntos dolorosos"]),
                      ("Grado III", "Signos neurológicos", ["Reflejos o fuerza alterados"]), ("Grado IV", "Fractura o luxación", ["Inestabilidad"])],
              caso=None, porque_titulo="En este caso",
              porque=[("Mecanismo de latigazo: sospechar lesión cervical", True), ("Sin examen todavía: el grado se define al evaluarlo", False)],
              conducta="Collarín, examen neurológico y reglas NEXUS o canadiense para decidir la TC."))

# GIN-035 · Tamizaje de diabetes gestacional · ÁRBOL
S("arbol", "GIN-035", "Gestante de 12 semanas con IMC 30 y glucemia en ayunas de 90: prueba de tolerancia oral a la glucosa a las 24-28 semanas",
  "Diabetes gestacional · tamizaje",
  ("Tamizaje de diabetes gestacional", ["Con factores de riesgo (obesidad) se busca diabetes previa en el primer control.",
                                        "Si sale normal, igual se hace la PTOG de 75 g entre las 24 y 28 semanas."]),
  ("Gestante de 12 semanas", ["IMC 30.", "Glucemia en ayunas de 90 mg/dL en el primer control."]),
  ["Primer control: glucemia en ayunas ≥ 126 (o HbA1c ≥ 6,5 %) = diabetes previa; 92-125 = diabetes gestacional (IADPSG).",
   "Aquí 90 es normal: PTOG 75 g a las 24-28 semanas (ayunas ≥ 92, 1 h ≥ 180 o 2 h ≥ 153 = diabetes gestacional).",
   "No dar metformina sin diagnóstico; control prenatal con dieta y actividad física."],
  ADA + " (sección 15, embarazo); IADPSG; " + ACOG + " Practice Bulletin n.º 190 (2018); " + MINSA + ".",
  op=("¿Recomendación?", ["Sí: tamizaje oficial", "Necesario, pero no basta", "No: ya es normal", "No: no hay diagnóstico", "No: no se usa así"],
      {0: "PTOG a las 24-28 semanas"}),
  arbol=Q("Primer control con riesgo: glucemia en ayunas", [
      L("≥ 126", "Diabetes previa", ["Tratar"]),
      L("92-125", "Diabetes gestacional", ["Dieta, control"]),
      L("< 92: 90 (este caso)", "PTOG A LAS 24-28 SEMANAS", ["75 g, 3 tomas"], path=True)], path=True))

# INF-012 · Lactancia con tratamiento antituberculoso · ÁRBOL
S("arbol", "INF-012", "Puérpera en la segunda fase del tratamiento antituberculoso: continuar la lactancia sin restricción",
  "Tuberculosis · lactancia materna",
  ("Tuberculosis y lactancia", ["Los antituberculosos pasan poco a la leche y no dañan al bebé.",
                                "En la segunda fase la madre ya no contagia si el tratamiento va bien."]),
  ("Puérpera inmediata", ["En la segunda fase del tratamiento antituberculoso."]),
  ["Lactancia materna exclusiva sin restricciones; dar piridoxina al bebé si la madre toma isoniacida (según norma).",
   "Si la madre aún es bacilífera (primeras semanas): lactar con mascarilla y dar terapia preventiva al bebé tras descartar TB.",
   "Nunca suspender la lactancia por la tuberculosis."],
  OMS + ", TB y lactancia (2024); " + MINSA + ", NTS de tuberculosis (2023).",
  op=("¿Recomendación?", ["No: pierde los beneficios", "Solo si aún contagia", "Sí: no hay riesgo", "No: retrasaría la lactancia",
                          "No: no hace falta"], {4: "Suspender hasta terminar"}),
  arbol=Q("Madre con TB que da de lactar: ¿todavía contagia?", [
      L("No: segunda fase (este caso)", "LACTANCIA SIN RESTRICCIÓN", ["Lactancia exclusiva"], path=True),
      L("Sí: bacilífera", "Lactar con mascarilla", ["Terapia preventiva al bebé"])], path=True))

# PED-034 · Displasia broncopulmonar · TARJETAS + grados
S("tarjetas", "PED-034", "Prematuro de 34 semanas, ventilado 30 días, que a los 2 meses sigue con oxígeno 3 L/min: displasia broncopulmonar",
  "Neonatología · displasia broncopulmonar",
  ("Displasia broncopulmonar", ["Enfermedad pulmonar crónica del prematuro por ventilación, oxígeno e inflamación.",
                                "Se define por la necesidad de oxígeno o soporte respiratorio a las 36 semanas de edad posmenstrual (o 56 días si nació ≥ 32 semanas)."]),
  ("Lactante de 2 meses, nacido a las 34 semanas", ["Ventilación mecánica 30 días.", "Hoy necesita oxígeno 3 L/min por cánula nasal."]),
  ["Prevención: ventilación protectora, CPAP temprano, surfactante, cafeína y evitar el exceso de oxígeno.",
   "Manejo: oxígeno para SatO₂ 92-95 %, nutrición alta en calorías, vacunas y nirsevimab o palivizumab contra el VSR.",
   "Buscar hipertensión pulmonar con ecocardiograma."],
  "Jensen et al., grados de displasia broncopulmonar (AJRCCM 2019); NICHD; " + NELSON + ".",
  op=("¿Encaja?", ["Sí: prematuro ventilado que sigue con oxígeno", "No: rara en lactantes", "No: es aguda, de los primeros días",
                   "No: suele ser secundaria", "No: cuadro agudo"]),
  d=dict(rotulo="Prematuro que no deja el oxígeno", ans=0,
         cards=[dict(titulo="Displasia broncopulmonar", datos=[("Antecedente", "Ventilación 30 días", True), ("Hoy", "Oxígeno a los 2 meses", True),
                                                             ("Curso", "Crónico", True)], pie="Este caso."),
                dict(titulo="Membrana hialina", datos=[("Cuándo", "Primeras horas", False), ("Causa", "Falta de surfactante", False),
                                                     ("Curso", "Agudo", False)], pie="Puede llevar a displasia."),
                dict(titulo="Neumonía aspirativa", datos=[("Inicio", "Agudo", False), ("Rx", "Infiltrado nuevo", False), ("Fiebre", "Posible", False)],
                     pie="Antibióticos."),
                dict(titulo="Hipertensión pulmonar", datos=[("Origen", "Suele ser secundaria", False), ("Eco", "VD sobrecargado", False),
                                                          ("Aquí", "Buscarla", False)], pie="Complicación.")]),
  escala=dict(nombre="Grados de displasia broncopulmonar (Jensen 2019)", orden=True, que="Por el soporte respiratorio a las 36 semanas de edad posmenstrual.",
              grados=[("Grado 1", "Leve", ["Cánula nasal ≤ 2 L/min"]), ("Grado 2", "Moderada", ["Cánula nasal > 2 L/min", "CPAP o ventilación no invasiva"]),
                      ("Grado 3", "Grave", ["Ventilación mecánica invasiva"])],
              caso=1, porque=[("Oxígeno 3 L/min por cánula: más de 2 L/min", True)],
              conducta="Oxígeno para SatO₂ 92-95 %, nutrición, prevención del VSR y eco para hipertensión pulmonar."))

# GIN-036 · Anti-D: cuándo no sirve · ÁRBOL
S("arbol", "GIN-036", "Puérpera Rh negativa: la inmunoprofilaxis anti-D no sirve si ya tiene anticuerpos anti-D",
  "Isoinmunización Rh · inmunoprofilaxis",
  ("Inmunoprofilaxis anti-D", ["La gammaglobulina anti-D destruye los glóbulos Rh+ del bebé antes de que la madre los reconozca.",
                               "Si la madre ya fabricó anti-D (sensibilizada), la profilaxis llega tarde."]),
  ("Puérpera inmediata Rh negativa", ["¿Qué impediría indicarle la gammaglobulina anti-D?"]),
  ["Se indica en las primeras 72 horas tras el parto si el bebé es Rh+ y la madre no está sensibilizada (Coombs indirecto negativo).",
   "También a las 28 semanas y tras aborto, ectópico, sangrado o procedimientos.",
   "Madre ya sensibilizada: no se da; el próximo embarazo se vigila con Doppler de la cerebral media fetal."],
  ACOG + " Practice Bulletin n.º 181 (2017, reafirmado); " + WILLIAMS + ".",
  op=("¿Impide la profilaxis?", ["Sí: ya está sensibilizada", "No: es la indicación", "No: hay que ver al bebé", "No: es la condición para darla",
                                 "No: se da en cualquier parto"]),
  arbol=Q("Puérpera Rh negativa: ¿Coombs indirecto (anticuerpos anti-D)?", [
      L("Negativo y bebé Rh+", "Anti-D en < 72 h", ["300 µg IM"]),
      L("Positivo: anti-D presentes (este caso)", "NO SIRVE LA PROFILAXIS", ["Ya está sensibilizada", "Vigilar futuros embarazos"], path=True)],
    path=True))

# GAS-008 · Encefalopatía hepática grado II · TARJETAS + West Haven
S("tarjetas", "GAS-008", "Alcohólico con ascitis, eritema palmar, temblor, desorientación y lentitud al hablar: encefalopatía hepática grado II",
  "Hígado · encefalopatía hepática",
  ("Encefalopatía hepática", ["El hígado no limpia el amonio y otras toxinas: alteración mental reversible.",
                              "Desencadenantes: sangrado, infección, estreñimiento, alcohol, sedantes, deshidratación."]),
  ("Varón de 49 años, alcohólico", ["Tras una reunión familiar: 2 días de desorientación y habla lenta.", "Temblor, eritema palmar, ascitis; glucosa 75."]),
  ["Tratar el desencadenante y dar lactulosa (2-3 deposiciones blandas al día); rifaximina para prevenir recaídas.",
   "Descartar hipoglucemia, infección (paracentesis por peritonitis bacteriana) y sangrado.",
   "No restringir proteínas."],
  "AASLD/EASL, encefalopatía hepática (2014, act. 2022); " + HARRISON + ".",
  op=("¿Más probable?", ["No: colestasis, sin encefalopatía", "No: falla renal", "No: sin acidosis ni visión borrosa", "Sí: desorientación + asterixis",
                         "No: glucosa 75"], {3: "Encefalopatía hepática grado II"}),
  d=dict(rotulo="Confusión en el cirrótico", ans=0,
         cards=[dict(titulo="Encefalopatía hepática", datos=[("Mente", "Desorientado", True), ("Manos", "Asterixis", True), ("Fondo", "Cirrosis", True)],
                     pie="Este caso: lactulosa."),
                dict(titulo="Hipoglucemia", datos=[("Glucosa", "< 70", False), ("Inicio", "Súbito", False), ("Mejora", "Con glucosa", False)],
                     pie="Aquí 75."),
                dict(titulo="Síndrome hepatorrenal", datos=[("Riñón", "Creatinina sube", False), ("Orina", "Escasa", False), ("Mente", "Puede estar normal", False)],
                     pie="Terlipresina + albúmina."),
                dict(titulo="Metanol", datos=[("Ojos", "Visión borrosa", False), ("Sangre", "Acidosis grave", False), ("Respiración", "Kussmaul", False)],
                     pie="Fomepizol.")]),
  escala=dict(nombre="Criterios de West Haven", orden=True, que="Gravedad de la encefalopatía hepática.",
              grados=[("Grado I", "Leve", ["Falta de atención, euforia o ansiedad", "Sueño alterado"]),
                      ("Grado II", "Moderada", ["Letargia, desorientación en tiempo", "Asterixis", "Habla lenta"]),
                      ("Grado III", "Grave", ["Somnolencia, confusión marcada", "Desorientación en espacio"]),
                      ("Grado IV", "Coma", ["No responde"])],
              caso=1, porque=[("Desorientación con habla lenta y temblor (asterixis)", True), ("Aún despierto: no es grado III", False)],
              conducta="Lactulosa, tratar el desencadenante (alcohol, infección, sangrado) y vigilar la vía aérea si empeora."))

# CAR-013 · RCP básica · ÁRBOL
S("arbol", "CAR-013", "Adulto que colapsa en un centro comercial sin riesgo para el reanimador: reconocer el paro, pedir ayuda y empezar 30 compresiones",
  "Reanimación cardiopulmonar básica",
  ("Soporte vital básico del adulto", ["Reconocer el paro: no responde y no respira o solo boquea.",
                                       "Pedir ayuda y un DEA, y empezar compresiones de inmediato (C-A-B)."]),
  ("Adulto mayor en un centro comercial", ["Pierde súbitamente la conciencia.", "No hay riesgo para el reanimador."]),
  ["Compresiones de 5-6 cm, 100-120 por minuto, dejando que el tórax vuelva; 30:2 con ventilaciones si está entrenado.",
   "Usar el DEA apenas llegue, sin parar las compresiones más de 10 segundos.",
   "No se usa el golpe precordial; en el Perú la emergencia es el 106 (SAMU) o el 116 (bomberos)."],
  AHA + "; ERC (2025).",
  op=("¿Secuencia correcta?", ["Sí: C-A-B", "No: el golpe precordial no se usa", "No: retrasa las compresiones", "No: secuencia antigua, 30:2",
                               "No: retrasa las compresiones"],
      {0: "Reconocer, pedir ayuda y 30 compresiones", 1: "2 respiraciones y golpe precordial", 2: "Pulso, llamar y girar la cabeza",
       3: "Golpe, 2 respiraciones y 15 compresiones", 4: "Buscar el DEA antes de comprimir"}),
  arbol=Q("Colapso súbito, escena segura: ¿responde y respira normal?", [
      L("No (este caso)", "PARO: PEDIR AYUDA Y COMPRIMIR", ["30 compresiones : 2 ventilaciones", "DEA apenas llegue"], path=True),
      L("Sí", "Posición lateral de seguridad", ["Llamar y vigilar"])], path=True))

# GIN-037 · Gestante Rh negativa: Coombs indirecto · ÁRBOL
S("arbol", "GIN-037", "Primigesta Rh negativa de 27 semanas en su primer control: pedir Coombs indirecto",
  "Isoinmunización Rh · control prenatal",
  ("Gestante Rh negativa", ["Primero se averigua si ya tiene anticuerpos anti-D (Coombs indirecto).",
                            "Si no los tiene, se previene con gammaglobulina anti-D a las 28 semanas."]),
  ("Primigesta de 27 semanas", ["Primer control prenatal.", "Refiere ser Rh negativa."]),
  ["Coombs indirecto negativo: anti-D 300 µg IM a las 28 semanas y dentro de las 72 h tras el parto si el bebé es Rh+.",
   "Coombs indirecto positivo: ya está sensibilizada; seguir títulos y Doppler de la arteria cerebral media fetal.",
   "Tipificar al padre puede ayudar, pero no reemplaza el Coombs."],
  ACOG + " Practice Bulletin n.º 181 (2017, reafirmado); " + MINSA + "; " + WILLIAMS + ".",
  op=("¿Primera medida?", ["Útil, no es lo primero", "Sí: ver si está sensibilizada", "Después de conocer el Coombs", "No: es para el bebé",
                           "No: invasiva, no es el primer paso"]),
  arbol=Q("Gestante Rh negativa: Coombs indirecto", [
      L("Negativo", "Anti-D a las 28 semanas", ["Y tras el parto si el bebé es Rh+"]),
      L("Positivo", "Sensibilizada", ["Títulos y Doppler fetal"]),
      L("Primero pedirlo (este caso)", "COOMBS INDIRECTO", ["Define la conducta"], path=True)], path=True))

# GIN-038 · RCIU: Doppler · ÁRBOL + estadios
S("arbol", "GIN-038", "34 semanas con altura uterina baja y circunferencia abdominal de 29 semanas: Doppler fetal",
  "Restricción del crecimiento intrauterino",
  ("Restricción del crecimiento fetal (RCF)", ["El feto no alcanza su potencial de crecimiento, casi siempre por insuficiencia placentaria.",
                                               "La circunferencia abdominal es la primera medida que cae (el hígado se achica)."]),
  ("Gestante de 34 semanas", ["Altura uterina 28 cm.", "Biometría: 33 semanas por DBP y fémur, 29 por circunferencia abdominal."]),
  ["Confirmar con peso fetal < p10 o circunferencia abdominal < p10 (o < p3 sola) y estudiar con Doppler.",
   "Doppler de arterias umbilical, cerebral media y uterinas; ductus venoso en las precoces.",
   "El Doppler decide la vigilancia y el momento del parto."],
  "ISUOG, guía de restricción del crecimiento fetal (2020); FIGO (2021); " + ACOG + " (2021).",
  op=("¿Más adecuado?", ["Complementa, no clasifica", "No: primero estadificar", "Sí: estadifica la restricción", "Complementa", "No: ya no se usa"]),
  arbol=Q("Circunferencia abdominal pequeña: ¿restricción de crecimiento?", [
      L("Sí (este caso)", "ECOGRAFÍA DOPPLER", ["Umbilical, cerebral media, uterinas", "Define el estadio"], path=True),
      L("No, feto pequeño constitucional", "Control de crecimiento", [])], path=True),
  escala=dict(nombre="Estadios de la restricción del crecimiento (Barcelona)", orden=True,
              que="Figueras y Gratacós: según el Doppler; define cuándo terminar la gestación.",
              grados=[("Estadio I", "Insuficiencia leve", ["Peso < p3 o Doppler umbilical/cerebral alterado", "Parto a las 37 semanas"]),
                      ("Estadio II", "Diástole ausente", ["Flujo diastólico ausente en la umbilical", "Parto a las 34 semanas"]),
                      ("Estadio III", "Flujo reverso", ["Reverso umbilical o ductus alterado", "Parto a las 30 semanas"]),
                      ("Estadio IV", "Riesgo de muerte", ["Onda a reversa del ductus o registro patológico", "Cesárea a las 26 semanas o más"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Circunferencia abdominal 5 semanas por debajo: sospecha de restricción", True), ("El estadio se define con el Doppler", False)],
              conducta="Doppler fetal completo y seguimiento según el estadio."))

# SP-021 · COVID-19 asintomático en el trabajo · ÁRBOL
S("arbol", "SP-021", "Trabajador asintomático con prueba positiva para COVID-19 y familiares enfermos: aislamiento y monitoreo",
  "Salud ocupacional · COVID-19",
  ("Aislamiento por COVID-19", ["El asintomático con prueba positiva contagia: se aísla para cortar la transmisión.",
                                "La duración cambió con el tiempo: 14 días en 2020; hoy es más corta."]),
  ("Trabajador de 34 años", ["Tres familiares con COVID-19 desde hace 2 días.", "Asintomático, prueba positiva."]),
  ["En la norma de 2020 (año de la pregunta) se aislaba 14 días con monitoreo de síntomas.",
   "Hoy (OMS 2023-2025): aislamiento de unos 5 días si es asintomático y mascarilla al volver; más si aparecen síntomas o es inmunodeprimido.",
   "Hospitalizar solo si hay signos de alarma (disnea, SatO₂ < 94 %)."],
  OMS + ", manejo clínico de la COVID-19 (2025); " + MINSA + ", RM 448-2020 (2020) y lineamientos posteriores.",
  op=("¿Indicación?", ["Sí: aislar y vigilar", "No: ya está confirmado", "No: contagia", "No: contagia mientras tanto", "No: asintomático"]),
  arbol=Q("Trabajador con prueba positiva: ¿síntomas o signos de alarma?", [
      L("No: asintomático (este caso)", "AISLAMIENTO Y MONITOREO", ["2020: 14 días; hoy más corto", "Volver con mascarilla"], path=True),
      L("Signos de alarma", "Evaluación médica", ["Hospitalizar si hay hipoxemia"])], path=True))

# INF-013 · VIH: vía del parto · ÁRBOL
S("arbol", "INF-013", "Gestante con VIH en tratamiento y en trabajo de parto: el parto vaginal depende de que la carga viral sea < 1000 copias/mL",
  "VIH y embarazo · vía del parto",
  ("Vía del parto en la gestante con VIH", ["Lo que decide es la carga viral cerca del parto, no la dilatación ni las membranas.",
                                            "Con carga viral baja el riesgo de transmisión es muy bajo."]),
  ("Gestante de 38 semanas con VIH en TAR", ["Contracciones uterinas frecuentes.", "¿Qué condición permite el parto vaginal?"]),
  ["Carga viral ≤ 1000 copias/mL (idealmente indetectable) con TAR: parto vaginal, sin zidovudina intraparto si es < 50.",
   "Carga viral > 1000 o desconocida: cesárea programada a las 38 semanas + zidovudina EV.",
   "Evitar rotura artificial de membranas, monitoreo invasivo e instrumentación innecesarios."],
  "DHHS, Perinatal HIV clinical guidelines (2024); " + ACOG + "; " + MINSA + ", NTS de transmisión materno-infantil (2024).",
  op=("¿Condición?", ["No: no decide la vía", "Sí: decide la vía", "No es el criterio", "No es el criterio", "No es el criterio"]),
  arbol=Q("Gestante con VIH cerca del parto: carga viral", [
      L("≤ 1000 copias/mL (lo que pregunta)", "PARTO VAGINAL", ["Continuar TAR", "Profilaxis al recién nacido"], path=True),
      L("> 1000 o desconocida", "Cesárea programada", ["Zidovudina EV"])], path=True))

# GIN-039 · EPI tras hidrosonografía · TARJETAS + Monif
S("tarjetas", "GIN-039", "Dolor en ambas fosas ilíacas 4 días después de una hidrosonografía con dolor a la movilización cervical y anexial: EPI",
  "Infecciones ginecológicas · enfermedad pélvica inflamatoria",
  ("Enfermedad pélvica inflamatoria (EPI)", ["Infección ascendente del tracto genital superior.",
                                             "Los procedimientos uterinos (hidrosonografía, DIU, legrado) pueden llevar gérmenes hacia arriba."]),
  ("Mujer de 28 años", ["Dolor en ambas fosas ilíacas; hidrosonografía hace 4 días.", "Dolor a la movilización del cuello y a la palpación de anexos."]),
  ["Criterios mínimos (CDC): dolor a la movilización cervical, uterino o anexial.",
   "Ceftriaxona IM + doxiciclina + metronidazol 14 días; descartar embarazo y absceso.",
   "Control a las 72 h: si no mejora, hospitalizar."],
  CDC + ", STI treatment guidelines (2021); " + MINSA + ", guía de ITS (2024).",
  op=("¿Más adecuado?", ["Sí: dolor cervical y anexial tras un procedimiento", "No: dolor inmediato tras el procedimiento, peritonitis",
                         "No: es agudo", "No: dolor cíclico de meses", "No: descartar con β-hCG"]),
  d=dict(rotulo="Dolor pélvico tras un procedimiento", ans=0,
         cards=[dict(titulo="EPI", datos=[("Movilización cervical", "Dolorosa", True), ("Anexos", "Dolorosos", True), ("Antes", "Hidrosonografía", True)],
                     pie="Este caso."),
                dict(titulo="Perforación uterina", datos=[("Cuándo", "Durante el procedimiento", False), ("Signo", "Peritonitis", False),
                                                        ("Imagen", "Aire o líquido", False)], pie="Cirugía."),
                dict(titulo="Endometriosis", datos=[("Dolor", "Cíclico, crónico", False), ("Asociado", "Dismenorrea", False),
                                                  ("Fiebre", "No", False)], pie="Laparoscopia."),
                dict(titulo="Embarazo ectópico", datos=[("β-hCG", "Positiva", False), ("Atraso", "Sí", False), ("Dolor", "Unilateral", False)],
                     pie="Descartar siempre.")]),
  escala=MONIF(0, [("Dolor cervical y anexial sin masa ni peritonitis descritas", True), ("Confirmar sin absceso con ecografía", False)],
               "Ceftriaxona + doxiciclina + metronidazol; control a las 72 horas."))

# HEM-004 · Anemia perniciosa · TARJETAS
S("tarjetas", "HEM-004", "Anemia macrocítica con B12 baja, folato normal y gastritis atrófica fúndica: falta factor intrínseco (anemia perniciosa)",
  "Anemias · anemia perniciosa",
  ("Anemia perniciosa", ["Gastritis autoinmune que destruye las células parietales del fondo gástrico.",
                         "Sin factor intrínseco no se absorbe la vitamina B12 en el íleon."]),
  ("Varón de 40 años, alcohólico y obeso", ["Pálido; Hb 9, macrocitosis.", "B12 baja, ácido fólico normal; gastritis crónica atrófica fúndica."]),
  ["Confirmar con anticuerpos anti-factor intrínseco y anti-célula parietal; gastrina alta.",
   "Tratamiento: B12 IM de por vida (o dosis orales altas).",
   "Vigilar cáncer gástrico y tumores carcinoides (endoscopia periódica)."],
  "British Society for Haematology (2014, act.); " + HARRISON + ".",
  op=("¿Deficiente?", ["Sí: lo producen las células parietales", "No: sube (aclorhidria)", "No: no se relaciona", "No: no se relaciona",
                       "No: la anemia es macrocítica"]),
  d=dict(rotulo="Anemia macrocítica con B12 baja", ans=0,
         cards=[dict(titulo="Anemia perniciosa", datos=[("Estómago", "Atrofia del fondo", True), ("Falta", "Factor intrínseco", True),
                                                      ("Anticuerpos", "Anti-FI", True)], pie="Este caso."),
                dict(titulo="Resección de íleon", datos=[("Antecedente", "Cirugía, Crohn", False), ("Estómago", "Normal", False),
                                                       ("Falta", "Sitio de absorción", False)], pie="B12 IM."),
                dict(titulo="Déficit de folato", datos=[("Folato", "Bajo", False), ("Causa", "Alcohol, dieta", False), ("Neuro", "Sin daño", False)],
                     pie="Aquí normal."),
                dict(titulo="Dieta vegana", datos=[("Dieta", "Sin carne", False), ("Estómago", "Normal", False), ("Falta", "Aporte de B12", False)],
                     pie="Suplemento oral.")]))

# GIN-040 · Mola hidatiforme · TARJETAS + ecografía real
S("tarjetas", "GIN-040", "15 semanas con sangrado, vómitos excesivos, útero de 19 cm y sin latidos fetales: mola hidatiforme",
  "Enfermedad trofoblástica gestacional",
  ("Mola hidatiforme", ["Proliferación anormal del trofoblasto con vellosidades hinchadas; β-hCG muy alta.",
                        "Útero más grande que la edad, hiperemesis, sangrado y ausencia de feto (mola completa)."]),
  ("Mujer de 16 años, 15 semanas", ["Sangrado escaso, náuseas y vómitos excesivos.", "Altura uterina 19 cm; sin latidos fetales."]),
  ["Ecografía (patrón en «copos de nieve» o «racimo de uvas») y β-hCG cuantitativa (muy alta).",
   "Evacuación por aspiración; seguimiento semanal de β-hCG hasta negativizar, con anticoncepción.",
   "Si la β-hCG se estanca o sube: neoplasia trofoblástica (metotrexato)."],
  FIGO + " Cancer Report, enfermedad trofoblástica gestacional (2021); ACOG; " + WILLIAMS + ".",
  op=("¿Más probable?", ["No: útero pequeño", "Sí: útero grande + hiperemesis + sin feto", "No: útero pequeño", "No: hay latido",
                         "Útero grande, pero con latidos"]),
  d=dict(rotulo="Útero grande sin latido fetal", ans=0,
         cards=[dict(titulo="Mola completa", datos=[("Útero", "Más grande", True), ("Feto", "No hay", True), ("β-hCG", "Muy alta", True)],
                     pie="Este caso: aspiración."),
                dict(titulo="Mola parcial", datos=[("Útero", "Normal o pequeño", False), ("Feto", "Anormal", False), ("Cariotipo", "Triploide", False)],
                     pie="Menos riesgo."),
                dict(titulo="Aborto retenido", datos=[("Útero", "Pequeño", False), ("Feto", "Sin latido", False), ("β-hCG", "Baja", False)],
                     pie="Misoprostol."),
                dict(titulo="Gemelar", datos=[("Útero", "Grande", False), ("Fetos", "Dos con latido", False), ("β-hCG", "Alta", False)],
                     pie="Ecografía.")]),
  banda=B("Ecografía real de embarazo molar", P("mola.jpg", 330, 251, [
            ("circulo", 0.55, 0.6, 0.25, "vesículas en\n«racimo de uvas»", 0.5, 0.08)],
          credito="Mikael Häggström" + CC + "CC0"),
          [("Muchas vesículas", "Pequeños quistes que llenan el útero: vellosidades hinchadas con líquido."),
           ("Sin embrión ni latido", "En la mola completa no hay feto."),
           ("Quistes tecaluteínicos", "La β-hCG tan alta puede agrandar los ovarios con quistes."),
           ("Hipertiroidismo y preeclampsia precoz", "Otras pistas de β-hCG muy alta.")],
          pie="Ecografía de otra paciente.", ans=0))

# GIN-041 · Aborto inevitable · ÁRBOL + formas
S("arbol", "GIN-041", "15 semanas con dolor, sangrado, pérdida de líquido amniótico y orificios abiertos: aborto inevitable",
  "Hemorragias de la primera mitad del embarazo · aborto",
  ("Aborto inevitable", ["El embarazo ya no puede continuar: cuello abierto y membranas rotas, sin expulsión aún.",
                         "La pérdida de líquido amniótico lo distingue de la amenaza."]),
  ("Gestante de 15 semanas", ["Dolor en hipogastrio, sangrado y pérdida de líquido amniótico.", "Orificios cervicales abiertos."]),
  ["Evacuar el útero: misoprostol (o mifepristona + misoprostol) o aspiración; antibiótico si hay signos de infección.",
   "Anti-D si es Rh negativa; analgesia y apoyo emocional.",
   "Vigilar sangrado e infección (aborto séptico)."],
  OMS + ", Abortion care guideline (2022); " + ACOG + "; " + MINSA + ".",
  op=("¿Diagnóstico?", ["No: cuello cerrado, sin expulsión", "No: aún no salieron restos", "Sí: cuello abierto + líquido", "No es un término oficial",
                        "No: cuello cerrado"], {3: "Aborto inminente"}),
  arbol=Q("Sangrado antes de las 22 semanas: ¿el cuello está abierto?", [
      L("Sí + pérdida de líquido (este caso)", "ABORTO INEVITABLE", ["Misoprostol o aspiración", "Anti-D si es Rh negativa"], path=True),
      L("No", "Amenaza o retenido", ["Ecografía"])], path=True),
  escala=ABORTO(1, [("Cuello abierto con pérdida de líquido amniótico", True), ("Aún no expulsó restos: no es incompleto", False)],
                "Evacuación uterina con misoprostol o aspiración; anti-D si corresponde."))

# PED-035 · Invaginación intestinal · ÁRBOL + tríada
S("arbol", "PED-035", "Niño de 2 años con dolor cólico, vómitos, deposiciones con moco y sangre y masa alargada: intususcepción",
  "Abdomen agudo pediátrico · invaginación intestinal",
  ("Invaginación intestinal", ["Un segmento de intestino entra en el siguiente (íleon en colon): obstrucción e isquemia.",
                               "La masa «en morcilla» y las heces en jalea de grosella son muy sugestivas."]),
  ("Niño de 2 años", ["Dolor abdominal cólico en crisis con vómitos intermitentes.", "Deposiciones con moco y sangre; masa alargada en el cuadrante superior derecho."]),
  ["Ecografía: signo de la diana; si está estable, reducción con enema de aire o suero guiado por imagen.",
   "Cirugía si hay peritonitis, perforación o falla del enema.",
   "En mayores de 3-5 años buscar un punto guía (Meckel, pólipo, linfoma)."],
  "ACR Appropriateness Criteria, intussusception (2023); " + NELSON + ".",
  op=("¿Diagnóstico probable?", ["No: niños mayores, sin cuadro agudo así", "Sí: tríada clásica", "No: sangrado indoloro sin masa",
                                 "No: estreñimiento crónico desde el nacimiento", "No: sin heces con sangre ni masa alargada"]),
  arbol=Q("Lactante con cólico, vómitos y heces con sangre: ecografía", [
      L("Signo de la diana (este caso)", "INTUSUSCEPCIÓN", ["Enema reductor si está estable"], path=True),
      L("Peritonitis o perforación", "Cirugía urgente", [])], path=True),
  triada=TR([("Dolor cólico", "En crisis", True), ("Masa abdominal", "Alargada, cuadrante superior derecho", True),
             ("Heces en jalea de grosella", "Moco y sangre", True)],
            [("Tríada clásica de la invaginación", 0, 2)], "Tríada completa: ecografía y reducción urgente.",
            rotulo="Signos con nombre propio"))
