"""Entrega 2 · tanda 09 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"

# NRL-029 · Hemorragia pontina · TARJETAS + ICH score + dibujo propio de pupilas
S("tarjetas", "NRL-029", "Hipertenso en coma súbito con Glasgow 4, respiración irregular y pupilas puntiformes: hemorragia en la protuberancia",
  "Enfermedad cerebrovascular · hemorragia intracerebral",
  ("Hemorragia pontina", ["Sangrado hipertensivo en la protuberancia (puente) del tronco cerebral.",
                          "Coma súbito, pupilas puntiformes que reaccionan, tetraplejía, respiración irregular e hipertermia."]),
  ("Varón de 54 años, hipertenso irregular", ["Caída súbita hace 3 horas; no responde a la voz ni al dolor.",
                                              "Glasgow 4, respiración irregular, pupilas mióticas."]),
  ["TC sin contraste confirma; asegurar la vía aérea (Glasgow ≤ 8: intubar).",
   "Bajar la PA sistólica a 140 mmHg (sin bajar de 110) y revertir anticoagulantes.",
   "Pronóstico muy malo; la cirugía no ayuda en el tronco (sí en el cerebelo > 3 cm)."],
  "AHA/ASA, hemorragia intracerebral espontánea (2022).",
  op=("¿Localización?", ["Sí: coma + pupilas puntiformes", "Mióticas pero sin reacción, mirada abajo", "Hemiplejía con mirada hacia la lesión",
                         "Vértigo, vómitos, ataxia; sin coma inicial", "Hemiparesia y conducta; pupilas normales"]),
  d=dict(rotulo="Hemorragia hipertensiva: ¿dónde está?", ans=0,
         cards=[dict(titulo="Protuberancia", datos=[("Pupilas", "Puntiformes", True), ("Conciencia", "Coma súbito", True), ("Motor", "Tetraplejía", True)],
                     pie="Este caso."),
                dict(titulo="Tálamo", datos=[("Pupilas", "Pequeñas, sin reacción", False), ("Ojos", "Miran abajo", False), ("Motor", "Hemiparesia", False)],
                     pie="Hemisensitivo."),
                dict(titulo="Putamen / cápsula", datos=[("Pupilas", "Normales", False), ("Ojos", "Miran la lesión", False), ("Motor", "Hemiplejía", False)],
                     pie="La más común."),
                dict(titulo="Cerebelo", datos=[("Clínica", "Vértigo, vómitos", False), ("Marcha", "Ataxia", False), ("Trato", "Cirugía si > 3 cm", False)],
                     pie="Se opera.")]),
  escala=dict(nombre="Puntaje ICH (hemorragia intracerebral)", modo="puntaje",
              que="Predice la mortalidad a 30 días.",
              items=[("GCS", "Glasgow 3-4 (2) o 5-12 (1)", "Glasgow 4", 2), ("Vol", "Volumen ≥ 30 mL", "Falta la TC", None),
                     ("HIV", "Sangre en los ventrículos", "Falta la TC", None), ("Infra", "Origen infratentorial", "Protuberancia", 1),
                     ("Edad", "≥ 80 años", "54 años", 0)],
              total_txt="Total: 3 puntos o más", total_nota="faltan datos de la TC",
              rangos=[("0-1", "Mortalidad baja", "0-13 %"), ("2", "Intermedia", "26 %"), ("3", "Alta", "72 %"), ("4-6", "Muy alta", "97-100 %")],
              caso_rango=2, porque=[("Glasgow 4 (2) e infratentorial (1)", True)],
              conducta="Intubar, controlar la PA y UCI."),
  banda=B("Las pupilas orientan la lesión", P("dib_pupilas.jpg", 420, 159, [], credito=PROPIO, fondo="#ffffff"),
          [("Puntiformes", "Protuberancia (o intoxicación por opioides)."),
           ("Reaccionan", "Con lupa se ve que se contraen a la luz."),
           ("Midriasis de un lado", "Compresión del III par: herniación."),
           ("Coma + puntiformes", "En un hipertenso: piensa en el puente.")],
          pie="Esquema.", ans=0))

# END-027 · Síndrome de Sheehan · TARJETAS + tríada
S("tarjetas", "END-027", "Mujer con amenorrea y que no pudo dar de lactar tras una hemorragia posparto con choque: síndrome de Sheehan",
  "Hipófisis · hipopituitarismo",
  ("Síndrome de Sheehan", ["Necrosis de la hipófisis (agrandada en el embarazo) por hipotensión grave en el parto.",
                           "El primer signo suele ser no poder lactar (falta prolactina); luego amenorrea, hipotiroidismo e insuficiencia suprarrenal."]),
  ("Mujer de 28 años", ["Amenorrea.", "Hemorragia posparto con hipotensión grave; no pudo dar de lactar."]),
  ["Medir cortisol, ACTH, TSH y T4 libre, FSH/LH, estradiol, prolactina e IGF-1; RM de hipófisis (silla vacía).",
   "Reponer primero el cortisol y después la levotiroxina (si no, crisis suprarrenal).",
   "Luego estrógenos con progestágeno; fertilidad con gonadotropinas."],
  "Endocrine Society, reemplazo hormonal en el hipopituitarismo (2016); " + WILLIAMS + ".",
  op=("¿Diagnóstico?", ["No: estrés o peso; sin hemorragia", "Sí: hemorragia + agalactia", "No: FSH alta, lactancia normal",
                        "Tras legrado; sí lacta", "No: hay galactorrea, no agalactia"]),
  d=dict(rotulo="Amenorrea después de un parto: ¿cuál?", ans=0,
         cards=[dict(titulo="Sheehan", datos=[("Antecedente", "Hemorragia, choque", True), ("Lactancia", "No hay leche", True), ("Hormonas", "Todas bajas", True)],
                     pie="Este caso."),
                dict(titulo="Asherman", datos=[("Antecedente", "Legrado", False), ("Lactancia", "Normal", False), ("Útero", "Sinequias", False)],
                     pie="Histeroscopía."),
                dict(titulo="Falla ovárica", datos=[("FSH", "Alta", False), ("Edad", "< 40 años", False), ("Clínica", "Bochornos", False)],
                     pie="Menopausia precoz."),
                dict(titulo="Prolactinoma", datos=[("Prolactina", "Alta", False), ("Mama", "Galactorrea", False), ("RM", "Adenoma", False)],
                     pie="Cabergolina.")]),
  triada=TR([("Hemorragia posparto grave", "Con hipotensión", True), ("Agalactia", "No pudo lactar", True), ("Amenorrea", "Sí", True),
             ("Hipotiroidismo", "No se describe", None), ("Insuficiencia suprarrenal", "No se describe", None)],
            [("Forma clásica", 0, 2), ("Buscar en todas", 3, 4)],
            "La insuficiencia suprarrenal es la que mata: cortisol antes que tiroides."))

# INF-053 · Leptospirosis · ÁRBOL + formas clínicas + tríada de Weil + foto real
S("arbol", "INF-053", "Vecino de la ribera de un río con fiebre súbita, dolor de pantorrillas, ictericia y sufusión conjuntival: leptospirosis",
  "Zoonosis · leptospirosis",
  ("Leptospirosis", ["Zoonosis por Leptospira: la orina de ratas contamina agua y barro, y entra por piel lastimada o mucosas.",
                     "Fiebre súbita, mialgias en pantorrillas y sufusión conjuntival; la forma grave (Weil) da ictericia, falla renal y sangrado."]),
  ("Varón de 36 años, ribera del río Rímac", ["3 días de fiebre y dolor en las pantorrillas.",
                                             "Ictericia, exantema, hepatoesplenomegalia, adenopatías y sufusión conjuntival."]),
  ["Confirmar con ELISA IgM, PCR (primera semana) o microaglutinación (MAT).",
   "Leve: doxiciclina 100 mg cada 12 h por 7 días.",
   "Grave (Weil): penicilina G o ceftriaxona EV; vigilar riñón, plaquetas y hemorragia pulmonar."],
  MINSA + ", NTS de leptospirosis (2022); " + OMS + ", leptospirosis humana.",
  op=("¿Diagnóstico?", ["No: úlceras en cadena, sin ictericia", "Sí: agua contaminada + sufusión", "No: crónica, abscesos",
                        "No: crónica, fístulas con gránulos", "No: sin mialgias ni sufusión"]),
  arbol=Q("Fiebre súbita con mialgias de pantorrillas tras contacto con agua o barro: ¿sufusión conjuntival?", [
      L("Sí, con ictericia (este caso)", "LEPTOSPIROSIS GRAVE (WEIL)", ["Penicilina o ceftriaxona", "Riñón y plaquetas"], path=True),
      L("Sí, sin ictericia", "Leptospirosis leve", ["Doxiciclina 7 días"])], path=True),
  escala=dict(nombre="Formas clínicas de la leptospirosis", orden=True,
              que="La mayoría es leve; una minoría hace la forma ictérica grave.",
              grados=[("Anictérica", "90 %", ["Fiebre, mialgias", "Sufusión conjuntival"]),
                      ("Ictérica (Weil)", "5-10 %", ["Ictericia, falla renal", "Hemorragias"]),
                      ("Pulmonar", "Hemorrágica", ["Hemoptisis", "La más letal"])],
              caso=1, porque=[("Ictericia de piel y escleras", True), ("Hepatoesplenomegalia", True)],
              conducta="Hospitalizar y antibiótico EV."),
  triada=TR([("Ictericia", "Sí", True), ("Falla renal", "No se describe", None), ("Hemorragias", "No se describe", None)],
            [("Tríada de Weil", 0, 2)],
            "Con ictericia, buscar la falla renal (creatinina, potasio) desde el ingreso."),
  banda=B("Así se ve la sufusión conjuntival", P("lepto.jpg", 300, 212, [
            ("flecha", 0.66, 0.45, 0.30, 0.90, "ojo rojo sin pus")],
          credito="Daniel Ostermayer" + CC + "CC BY 4.0"),
          [("Ojo rojo sin pus", "Vasos dilatados, sin secreción."),
           ("Casi exclusiva", "Muy sugestiva de leptospirosis."),
           ("Con ictericia", "Ojos rojos y amarillos a la vez."),
           ("Más mialgias", "Dolor intenso de pantorrillas.")],
          pie="Ojos de otro paciente.", ans=0))

# SP-071 · Obesidad escolar: sedentarismo · RADIAL
S("radial", "SP-071", "Colegio urbano con 35 % de escolares con sobrepeso y 8 % con obesidad: el factor modificable principal es el sedentarismo",
  "Salud pública · obesidad infantil",
  ("Obesidad en escolares", ["Resulta de comer más energía de la que se gasta, por largo tiempo.",
                             "Factores modificables principales: poca actividad física, pantallas y comida ultraprocesada."]),
  ("Colegio secundario de Lima", ["35 % con IMC > 25.", "8 % con IMC > 30."]),
  ["En menores de 19 años se usa el IMC para la edad (OMS): sobrepeso > +1 DE, obesidad > +2 DE.",
   "Meta: 60 minutos de actividad física diaria y menos de 2 horas de pantallas recreativas.",
   "Ley 30021 de alimentación saludable: octógonos y quioscos saludables."],
  OMS + ", actividad física (2020) y obesidad infantil (2024); " + MINSA + ".",
  op=("¿Factor modificable?", ["Poco frecuente en escolares", "No explica el exceso de peso", "Sí: poca actividad física",
                               "Influye, pero no es el principal", "No causa obesidad"]),
  d=dict(rotulo="¿Qué lleva al exceso de peso escolar?", centro="SEDENTARISMO", centro_sub="este caso", ans=0,
         items=[("PANTALLAS", ["Celular, videojuegos"]), ("POCA ACTIVIDAD", ["< 60 min al día"]),
                ("ULTRAPROCESADOS", ["Bebidas azucaradas"]), ("SUEÑO CORTO", ["Más apetito"]),
                ("ENTORNO", ["Pocos parques"])],
         ruta=["Medir IMC para la edad", "60 min de actividad", "Quiosco saludable", "Involucrar a la familia"]))

# CB-032 · Vena femoral medial a la arteria · TARJETAS + dibujo propio
S("tarjetas", "CB-032", "Para canalizar la vena femoral se palpa el pulso de la arteria: la vena está justo medial a ella",
  "Anatomía · triángulo femoral",
  ("Triángulo femoral (de Scarpa)", ["Límites: ligamento inguinal arriba, sartorio por fuera y aductor largo por dentro.",
                                     "De lateral a medial: Nervio, Arteria, Vena, Espacio (conducto femoral) y Linfáticos (N-A-V-E-L)."]),
  ("Varón de 42 años", ["Consumidor de drogas EV con venas de brazos con cicatrices.", "Solo quedan accesibles las venas femorales."]),
  ["Palpar el pulso femoral 2 cm debajo del ligamento inguinal y punzar 1 cm medial.",
   "Mejor guiado por ecografía (la vena se colapsa al apretar; la arteria late).",
   "El conducto femoral (medial a la vena) es por donde sale la hernia crural."],
  "Gray, Anatomía para estudiantes (5.ª ed.); guías de acceso vascular con ecografía (2024).",
  op=("¿Referencia?", ["Sí: medial al pulso femoral", "No: allí hay linfáticos", "Lejos: la arteria está en medio",
                       "No: lateral está el nervio", "No: fuera del triángulo"]),
  d=dict(rotulo="De lateral a medial en la ingle", ans=2,
         cards=[dict(titulo="Nervio femoral", datos=[("Posición", "La más lateral", False), ("Vaina", "Fuera", False), ("Riesgo", "Parestesias", False)],
                     pie="Lateral."),
                dict(titulo="Arteria femoral", datos=[("Posición", "Central", False), ("Se palpa", "Pulso", False), ("Uso", "Referencia", False)],
                     pie="El punto guía."),
                dict(titulo="Vena femoral", datos=[("Posición", "Medial a la arteria", True), ("Se punza", "1 cm medial", True), ("Eco", "Se colapsa", True)],
                     pie="Este caso."),
                dict(titulo="Conducto femoral", datos=[("Posición", "La más medial", False), ("Contiene", "Linfáticos", False), ("Hernia", "Crural", False)],
                     pie="Medial.")]),
  banda=B("El triángulo femoral", P("dib_triangulo_femoral.jpg", 380, 281, [], credito=PROPIO, fondo="#ffffff"),
          [("Nervio", "El más lateral, fuera de la vaina."),
           ("Arteria", "Se palpa el pulso: es la guía."),
           ("Vena", "Justo medial al pulso: aquí se punza."),
           ("Linfáticos", "Lo más medial (conducto femoral).")],
          pie="Esquema del lado derecho, vista de frente.", ans=2))

# CIR-058 · Hemotórax traumático: tubo de tórax · ÁRBOL + clasificación
S("arbol", "CIR-058", "Trauma de tórax con choque, murmullo ausente y matidez en la mitad inferior derecha: hemotórax, tubo de drenaje torácico",
  "Trauma torácico · hemotórax",
  ("Hemotórax traumático", ["Sangre en la pleura por lesión de vasos intercostales, mamaria interna o pulmón.",
                            "Murmullo ausente con MATIDEZ (el neumotórax da timpanismo); si es grande, choque."]),
  ("Varón de 48 años, choque contra un poste", ["Golpe del pecho con el timón; dolor que no lo deja respirar.",
                                                "PA 80/60, FC 120, FR 28, SatO₂ 88 %; murmullo ausente y matidez en ½ inferior derecha."]),
  ["Tubo de tórax (28-32 Fr) en el 5.º espacio intercostal, línea axilar media, con dos vías y sangre lista.",
   "Toracotomía si sale ≥ 1500 mL de entrada o > 200 mL/h por 2-4 horas, o si sigue inestable.",
   "eFAST y Rx de tórax portátil; ácido tranexámico en < 3 h si hay hemorragia."],
  ATLS + ".",
  op=("¿Conducta inmediata?", ["No: no hay taponamiento", "No: está inestable", "Si falla; primero el tubo", "Sí: drena y mide el sangrado",
                               "No: no hay taponamiento"]),
  arbol=Q("Trauma de tórax con murmullo ausente: ¿matidez o timpanismo?", [
      L("Matidez + choque (este caso)", "HEMOTÓRAX: TUBO DE TÓRAX", ["≥ 1500 mL: toracotomía", "Reponer sangre"], path=True),
      L("Timpanismo + choque", "Neumotórax a tensión", ["Descompresión con aguja"])], path=True),
  escala=dict(nombre="Tamaño del hemotórax", orden=True,
              que="Por la Rx y por lo que drena el tubo.",
              grados=[("Pequeño", "< 300 mL", ["Borra el ángulo costofrénico"]), ("Moderado", "300-1500 mL", ["Hasta la escápula"]),
                      ("Masivo", "≥ 1500 mL", ["O > 200 mL/h", "Toracotomía"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Matidez en la mitad inferior + choque: moderado o masivo", True), ("Lo define lo que salga por el tubo", True)],
              conducta="Tubo de tórax ya y medir el débito."))

# GAS-039 · Pancreatitis biliar: colangiorresonancia · ÁRBOL + Atlanta + tríada de Charcot + imagen real
S("arbol", "GAS-039", "Pancreatitis aguda con ictericia de bilirrubina directa: sospecha de causa biliar, colangiorresonancia para buscar cálculos en el colédoco",
  "Pancreatitis aguda · etiología",
  ("Pancreatitis aguda biliar", ["Los cálculos de la vesícula pasan al colédoco y obstruyen la salida del páncreas.",
                                 "Ictericia con bilirrubina directa y transaminasas altas apuntan a cálculo en el colédoco."]),
  ("Mujer de 34 años", ["2 días de dolor abdominal, vómitos, ictericia y fiebre.", "Amilasa 2400; BT 4, BD 3,5; abdomen distendido sin ruidos."]),
  ["Ecografía abdominal en todos: busca cálculos en la vesícula.",
   "Colangiorresonancia (o ecoendoscopía) si hay riesgo intermedio de cálculo en el colédoco.",
   "Si hay colangitis (fiebre + ictericia + dolor): CPRE en 24 horas. Colecistectomía en la misma hospitalización."],
  "ACG, pancreatitis aguda (2024); ASGE, coledocolitiasis (2019).",
  op=("¿Estudio para la causa?", ["Sí: ve cálculos en el colédoco", "No: no dice la causa", "Para gravedad o complicaciones (> 72 h)",
                                  "No: poco útil", "Alternativa invasiva; si la RM no aclara"]),
  arbol=Q("Pancreatitis con ictericia de bilirrubina directa: ¿buscar cálculo en el colédoco?", [
      L("Sí (este caso)", "COLANGIORRESONANCIA", ["Si confirma: CPRE", "Colecistectomía"], path=True),
      L("Colangitis franca", "CPRE en 24 h", ["Diagnostica y trata"])], path=True),
  escala=dict(nombre="Clasificación de Atlanta revisada", orden=True,
              que="Gravedad de la pancreatitis aguda según la falla de órganos.",
              grados=[("Leve", "Sin falla", ["Sin complicaciones"]), ("Moderada", "Falla < 48 h", ["O complicación local"]),
                      ("Grave", "Falla > 48 h", ["Persistente"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Faltan creatinina, PA y oxigenación", True), ("Deshidratada: hidratar y reevaluar a las 48 h", True)],
              conducta="Ringer lactato y colangiorresonancia."),
  triada=TR([("Dolor abdominal", "Sí", True), ("Fiebre", "Sí", True), ("Ictericia", "BD 3,5", True)],
            [("Tríada de Charcot", 0, 2)],
            "Charcot completa sugiere colangitis: si se confirma, CPRE urgente."),
  banda=B("Así se ve en la colangiorresonancia", P("cprm.jpg", 240, 304, [
            ("flecha", 0.40, 0.73, 0.70, 0.93, "cálculos en el colédoco")],
          credito="Hellerhoff" + CC + "CC BY-SA 3.0"),
          [("Bilis blanca", "La RM muestra la bilis brillante."),
           ("Cálculos negros", "Huecos oscuros dentro del colédoco."),
           ("Sin contraste ni radiación", "No invasiva."),
           ("Si hay cálculo", "CPRE para sacarlo.")],
          pie="Colangiorresonancia de otro paciente.", ans=1))

# REU-027 · Artritis séptica: líquido sinovial · ÁRBOL + clasificación del líquido
S("arbol", "REU-027", "Monoartritis aguda de rodilla con líquido sinovial de más de 80 000 leucocitos y 80 % de neutrófilos: artritis séptica",
  "Monoartritis aguda · líquido sinovial",
  ("Artritis séptica (infecciosa)", ["Infección bacteriana de la articulación; la rodilla es la más afectada.",
                                     "Urgencia: destruye el cartílago en días. Líquido sinovial con > 50 000 leucocitos y > 75-90 % de neutrófilos."]),
  ("Varón de 20 años", ["2 días de dolor intenso y aumento de volumen de la rodilla derecha; signo del témpano (+).",
                        "Líquido sinovial: > 80 000 leucocitos, 80 % neutrófilos."]),
  ["Gram, cultivo del líquido y hemocultivos ANTES del antibiótico; buscar cristales.",
   "Antibiótico EV empírico: vancomicina + ceftriaxona (según Gram).",
   "Drenaje: artrocentesis repetidas o lavado artroscópico."],
  "EULAR/British Society for Rheumatology, artritis séptica (2023); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: líquido no inflamatorio", "Puede dar > 50 000; descartar cristales", "Sí: líquido séptico",
                        "Inflamatorio, poliarticular", "Estéril, tras una infección"]),
  arbol=Q("Monoartritis aguda: ¿leucocitos > 50 000 con > 75 % de neutrófilos?", [
      L("Sí (este caso)", "ARTRITIS SÉPTICA", ["Cultivos y antibiótico EV", "Drenaje"], path=True),
      L("2000-50 000", "Inflamatoria", ["Cristales: gota, pseudogota"])], path=True),
  escala=dict(nombre="Clasificación del líquido sinovial", orden=True,
              que="Por el aspecto, los leucocitos y el porcentaje de neutrófilos.",
              grados=[("Normal", "< 200", ["Claro"]), ("No inflamatorio", "200-2000", ["Artrosis"]),
                      ("Inflamatorio", "2000-50 000", ["Gota, AR"]), ("Séptico", "> 50 000", ["> 75 % PMN"])],
              caso=3, porque=[("Más de 80 000 leucocitos", True), ("80 % de neutrófilos", True)],
              conducta="Cultivos, antibiótico EV y drenaje."))

# TRA-019 · Fractura expuesta conminuta de tibia · ÁRBOL + Gustilo-Anderson + foto real
S("arbol", "TRA-019", "Joven atropellado con herida abierta y fractura conminuta de tibia: fractura expuesta, fijación externa",
  "Fracturas expuestas · tibia",
  ("Fractura expuesta de tibia", ["El hueso roto comunica con el exterior: alto riesgo de infección.",
                                  "La tibia tiene poca piel encima: es el hueso largo que más se expone."]),
  ("Varón de 20 años atropellado por una moto", ["Herida abierta en la pierna.", "Fractura conminuta de la tibia derecha."]),
  ["Antibiótico en la primera hora: cefazolina (+ gentamicina en tipo III); vacuna antitetánica.",
   "Lavado y desbridamiento en quirófano.",
   "Fijación externa temporal; luego clavo endomedular cuando la herida esté limpia."],
  "BOAST, fracturas expuestas (2017, act. 2023); " + ATLS + ".",
  op=("¿Tratamiento?", ["No: no estabiliza", "No: impide curar la herida", "Sí: estabiliza y deja ver la herida",
                        "Después, con la herida limpia", "No: no inmoviliza"]),
  arbol=Q("Fractura expuesta con herida contaminada o conminución: ¿se puede fijar por dentro ya?", [
      L("No (este caso)", "FIJACIÓN EXTERNA", ["Antibiótico < 1 h", "Lavado y desbridamiento"], path=True),
      L("Sí: tipo I-II limpia", "Clavo endomedular", ["Tras el lavado"])], path=True),
  escala=dict(nombre="Clasificación de Gustilo-Anderson", orden=True,
              que="Gravedad de la fractura expuesta: guía el antibiótico y el pronóstico.",
              grados=[("Tipo I", "Herida < 1 cm", ["Limpia"]), ("Tipo II", "Herida 1-10 cm", ["Poco daño"]),
                      ("Tipo IIIA", "Alta energía", ["Conminuta, se cubre"]), ("Tipo IIIB", "Sin piel", ["Necesita colgajo"]),
                      ("Tipo IIIC", "Lesión arterial", ["Reparar la arteria"])],
              caso=2, porque=[("Conminuta por alta energía: tipo III", True), ("No se describe pérdida de piel ni de pulso", True)],
              conducta="Cefazolina + gentamicina, lavado y fijación externa."),
  banda=B("Así se ve un fijador externo", P("fijador.jpg", 280, 245, [
            ("flecha", 0.40, 0.42, 0.55, 0.92, "barras fuera de la piel")],
          credito="Ortopedikus" + CC + "CC BY-SA 4.0"),
          [("Clavos en el hueso", "Atraviesan la piel arriba y abajo de la fractura."),
           ("Barras por fuera", "Unen los clavos y sostienen el hueso."),
           ("Herida libre", "Se puede limpiar y cubrir."),
           ("Temporal", "Luego se cambia a clavo endomedular.")],
          pie="Pierna de otro paciente.", ans=2))

# SP-072 · Tríada epidemiológica: el ambiente · TARJETAS
S("tarjetas", "SP-072", "Caso de malaria en Lima, donde no hay Anopheles: el ambiente no favorece la transmisión",
  "Epidemiología · tríada ecológica",
  ("Tríada epidemiológica", ["Agente, huésped y ambiente deben coincidir para que la enfermedad se transmita.",
                             "En las metaxénicas, el vector forma parte del ambiente."]),
  ("Distrito de Lima", ["Caso de malaria por P. vivax, que viene de zona endémica.", "En Lima no hay el vector (Anopheles)."]),
  ["Sin vector no hay transmisión local: el caso es importado.",
   "Tratar al paciente (cloroquina + primaquina) y vigilar si aparece el vector.",
   "Notificar: la malaria es de notificación obligatoria."],
  OMS + ", malaria (2025); " + MINSA + ", NTS de malaria.",
  op=("¿Elemento que no favorece?", ["Sí: no hay vector", "No: el parásito está presente", "No: el paciente infectado está",
                                     "No es parte de la tríada", "No es parte de la tríada"]),
  d=dict(rotulo="Tríada epidemiológica en este caso", ans=0,
         cards=[dict(titulo="Ambiente", datos=[("Incluye", "Vector, clima", True), ("Aquí", "Sin Anopheles", True), ("Efecto", "No transmite", True)],
                     pie="Este caso."),
                dict(titulo="Agente", datos=[("Qué es", "El parásito", False), ("Aquí", "P. vivax", False), ("Estado", "Presente", False)],
                     pie="Sí está."),
                dict(titulo="Huésped", datos=[("Qué es", "La persona", False), ("Aquí", "Paciente infectado", False), ("Estado", "Presente", False)],
                     pie="Sí está."),
                dict(titulo="Vector", datos=[("Qué es", "Anopheles", False), ("Lugar", "Selva, costa norte", False), ("En Lima", "No hay", False)],
                     pie="Parte del ambiente.")]))

# SP-073 · Población y muestra · TARJETAS
S("tarjetas", "SP-073", "Encuesta aplicada al 100 % de los integrantes del club: los participantes son la población, no una muestra",
  "Investigación · población y muestra",
  ("Población", ["Conjunto completo de personas que comparten una característica y sobre las que se quiere concluir.",
                 "Si se estudia a todos, es un censo de la población; la muestra es solo una parte."]),
  ("Club del adulto mayor", ["Estudio de características sociodemográficas.", "Encuesta al 100 % de los integrantes."]),
  ["Muestra: parte de la población elegida (ideal al azar) para inferir a todos.",
   "Estrato: subgrupo según una característica (edad, sexo) para muestrear.",
   "Cohorte: grupo seguido en el tiempo para ver quién enferma."],
  "Hernández-Sampieri, Metodología de la investigación (7.ª ed.); OPS, epidemiología.",
  op=("¿Denominación?", ["Sí: se estudia a todos", "No: sería solo una parte", "No: es una técnica de muestreo",
                         "No: es un subgrupo", "No: es seguir en el tiempo"]),
  d=dict(rotulo="¿A quién se estudia?", ans=0,
         cards=[dict(titulo="Población", datos=[("Quiénes", "Todos", True), ("Aquí", "100 % del club", True), ("Resultado", "Sin inferir", True)],
                     pie="Este caso."),
                dict(titulo="Muestra", datos=[("Quiénes", "Una parte", False), ("Cómo", "Al azar", False), ("Resultado", "Se infiere", False)],
                     pie="Parcial."),
                dict(titulo="Estrato", datos=[("Quiénes", "Subgrupo", False), ("Ejemplo", "Por edad", False), ("Uso", "Muestreo", False)],
                     pie="Parte."),
                dict(titulo="Cohorte", datos=[("Quiénes", "Grupo expuesto", False), ("Cómo", "Seguido", False), ("Mide", "Incidencia", False)],
                     pie="Diseño.")]))

# CAR-043 · Trauma precordial con inestabilidad: ECG y ecocardiograma · ÁRBOL + Beck + ECG propio
S("arbol", "CAR-043", "Golpe en el precordio con hipotensión, ruidos apagados, yugulares ingurgitadas y troponina alta: ECG y ecocardiograma inmediatos",
  "Trauma cardíaco cerrado · contusión y taponamiento",
  ("Trauma cardíaco cerrado", ["Un golpe en el pecho puede causar contusión miocárdica (arritmias, troponina alta) o derrame que tapona el corazón.",
                               "Tríada de Beck (hipotensión, ruidos apagados, yugulares ingurgitadas) = taponamiento."]),
  ("Varón de 52 años", ["Golpe de puño en el precordio hace 6 horas; dolor, palpitaciones y mareo.",
                        "FC 100, PA 90/60, ruidos apagados, yugulares ingurgitadas; CPK y troponina altas."]),
  ["ECG: arritmias, bloqueos o alternancia eléctrica; monitoreo continuo 24-48 h.",
   "Ecocardiograma (o FAST pericárdico): derrame y colapso de cavidades derechas.",
   "Taponamiento: pericardiocentesis o ventana pericárdica; evitar diuréticos."],
  ATLS + "; EAST, contusión cardíaca cerrada (2012, vigente).",
  op=("¿Medida inmediata?", ["Insuficiente: hay inestabilidad", "No: el diurético empeora el taponamiento", "Sí: ve arritmia y derrame",
                             "No: está inestable", "Poco útil; la eco es más rápida"]),
  arbol=Q("Trauma precordial con hipotensión y yugulares llenas: ¿derrame en la eco?", [
      L("Buscarlo ya (este caso)", "ECG + ECOCARDIOGRAMA", ["Taponamiento: drenar", "Contusión: monitoreo"], path=True),
      L("Sin derrame, ECG normal", "Observación", ["Troponina seriada"])], path=True),
  triada=TR([("Hipotensión", "90/60", True), ("Ruidos apagados", "Disminuidos", True), ("Yugulares ingurgitadas", "Sí", True),
             ("Pulso paradójico", "No se describe", None)],
            [("Tríada de Beck", 0, 2), ("Además", 3, 3)],
            "Beck completa: taponamiento hasta demostrar lo contrario."),
  banda=B("ECG del taponamiento", P("ecg_taponamiento.jpg", 380, 182, [
            ("corchete", 0.077, 0.377, 0.16, "QRS alto y bajo alternados"),
            ("flecha", 0.177, 0.24, 0.30, 0.42, "QRS pequeño")],
          credito=ECG_PROPIO, fondo="#ffffff"),
          [("Bajo voltaje", "QRS pequeños: el líquido aísla."),
           ("Alternancia eléctrica", "Un QRS alto y otro bajo."),
           ("Taquicardia sinusal", "Compensa la caída del gasto."),
           ("La eco confirma", "Derrame con colapso derecho.")],
          pie="Trazado de enseñanza.", ans=1))

# PED-110 · Deshidratación grave con choque · ÁRBOL + planes OMS + foto real
S("arbol", "PED-110", "Lactante con diarrea y vómitos, soporoso, ojos muy hundidos, pliegue (+), piel fría y llenado de 5 s: choque hipovolémico, bolo de SSN 20 mL/kg",
  "Enfermedad diarreica aguda · deshidratación grave",
  ("Deshidratación grave con choque", ["Pérdida de agua y sales que ya compromete la circulación.",
                                       "Signos de choque: piel fría, llenado capilar > 2 s, pulso débil, alteración de la conciencia."]),
  ("Lactante de 10 meses", ["3 días de vómitos y 8 deposiciones líquidas al día.",
                            "Soporoso, ojos muy hundidos, pliegue (+), piel fría, llenado capilar 5 s."]),
  ["Bolo de SSN 0,9 % (o Ringer) 20 mL/kg en 15-20 min; repetir hasta 60 mL/kg reevaluando.",
   "Luego plan C (< 12 meses): 30 mL/kg en 1 h y 70 mL/kg en 5 h.",
   "Sales de rehidratación oral apenas pueda beber; zinc 10-14 días."],
  OMS + "/AIEPI, tratamiento de la diarrea; " + MINSA + ", guía de EDA en niños (2017).",
  op=("¿Manejo inicial?", ["Sí: el choque necesita bolo", "No: no expande volumen", "No: muy lento para el choque",
                           "No: plan B; está en choque", "No: plan A"]),
  arbol=Q("Diarrea con deshidratación grave: ¿signos de choque?", [
      L("Sí: frío, llenado 5 s (este caso)", "SSN 20 mL/kg EN BOLO", ["Repetir hasta 60 mL/kg", "Luego plan C"], path=True),
      L("No: grave sin choque", "Plan C", ["100 mL/kg en 6 h"])], path=True),
  escala=dict(nombre="Planes de hidratación (OMS/AIEPI)", orden=True,
              que="Según los signos de deshidratación.",
              grados=[("Plan A", "Sin deshidratación", ["Más líquidos en casa"]), ("Plan B", "Algún grado", ["Inquieto, ojos hundidos", "SRO 50-100 mL/kg en 4 h"]),
                      ("Plan C", "Grave", ["Letárgico, pliegue muy lento", "Líquidos EV"])],
              caso=2, porque=[("Soporoso, ojos muy hundidos, pliegue (+)", True), ("Además choque: bolo antes del plan C", True)],
              conducta="Bolo de SSN 20 mL/kg y reevaluar."),
  banda=B("El signo del pliegue", P("pliegue.jpg", 260, 271, [
            ("flecha", 0.50, 0.28, 0.50, 0.92, "la piel tarda en volver")],
          credito="DRobert" + CC + "CC BY-SA 4.0"),
          [("Se pellizca la piel", "Del abdomen, entre dos dedos."),
           ("Tarda en volver", "Más de 2 segundos: grave."),
           ("Ojos hundidos", "Otro signo de deshidratación."),
           ("Llenado capilar", "> 2 s con piel fría: choque.")],
          pie="Foto de otra persona deshidratada.", ans=1))

# HEM-022 · Anemia megaloblástica por B12 · ÁRBOL + VCM + frotis real y propio
S("arbol", "HEM-022", "Anciano con anemia macrocítica, parestesias, pérdida de la sensibilidad vibratoria y neutrófilos hipersegmentados: anemia megaloblástica por déficit de B12",
  "Anemias macrocíticas · déficit de vitamina B12",
  ("Anemia megaloblástica", ["Falta B12 o ácido fólico: el ADN no se sintetiza bien y las células crecen sin dividirse.",
                             "Macrocitosis (VCM > 100), macroovalocitos y neutrófilos con 6 o más lóbulos; la B12 además daña los nervios."]),
  ("Varón de 75 años", ["6 meses de fatiga y parestesias en brazos y piernas.",
                        "Palidez, vibración disminuida; Hb 9, VCM 110; neutrófilos hipersegmentados."]),
  ["Medir B12 y folato (y ácido metilmalónico si la B12 es dudosa); anticuerpos anti-factor intrínseco.",
   "Con síntomas neurológicos: B12 IM 1000 µg (días alternos) y luego mensual de por vida si es anemia perniciosa.",
   "No dar solo ácido fólico: corrige la anemia pero empeora el daño de los nervios."],
  "British Society for Haematology, déficit de B12 y folato (2014, act. 2024); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["Sí: macrocitosis + hipersegmentación", "No: microcítica", "No: sideroblastos en anillo",
                        "No: microcítica", "No: normocítica"]),
  arbol=Q("Anemia con VCM > 100: ¿neutrófilos hipersegmentados o macroovalocitos?", [
      L("Sí (este caso)", "MEGALOBLÁSTICA", ["B12 y folato", "Con daño neurológico: B12"], path=True),
      L("No", "Macrocitosis no megaloblástica", ["Alcohol, hígado, tiroides"])], path=True),
  escala=dict(nombre="Clasificación de la anemia por el VCM", orden=True,
              que="El tamaño del glóbulo rojo orienta la causa.",
              grados=[("Microcítica", "< 80 fL", ["Hierro, talasemia"]), ("Normocítica", "80-100 fL", ["Crónica, renal, hemólisis"]),
                      ("Macrocítica", "> 100 fL", ["B12, folato, alcohol"])],
              caso=2, porque=[("VCM 110 fL", True), ("Parestesias y vibración baja: falta B12", True)],
              conducta="B12 IM y buscar anemia perniciosa."),
  triada=TR([("Parestesias", "Brazos y piernas", True), ("Vibración disminuida", "Sí", True), ("Ataxia o Romberg (+)", "No se describe", None)],
            [("Degeneración combinada subaguda", 0, 2)],
            "Daña cordones posteriores y laterales: solo la B12 lo produce, no el folato."),
  banda=B("Así se ve en el frotis", P("megalo_mont.jpg", 420, 170, [
            ("flecha", 0.18, 0.45, 0.30, 0.92, "neutrófilo de 6 lóbulos"),
            ("flecha", 0.86, 0.25, 0.70, 0.92, "macroovalocito")],
          credito="Foto: Ed Uthman" + CC + "CC BY 2.0; esquema propio"),
          [("Neutrófilo hipersegmentado", "6 o más lóbulos (normal 3-5)."),
           ("Macroovalocitos", "Glóbulos rojos grandes y ovalados."),
           ("Sin palidez central", "Se ven llenos de hemoglobina."),
           ("Foto y esquema", "Izquierda: frotis real; derecha: dibujo.")],
          pie="Frotis de otro paciente y esquema de enseñanza.", ans=0))

# REU-028 · Escabiosis · TARJETAS + foto real
S("tarjetas", "REU-028", "Niño con prurito intenso nocturno y pápulas en espacios interdigitales, muñecas, axilas, glúteos y genitales, sin tocar la cara: escabiosis",
  "Dermatología pediátrica · ectoparasitosis",
  ("Escabiosis (sarna)", ["Ácaro Sarcoptes scabiei que cava túneles en la capa córnea; contagio por contacto directo.",
                          "Prurito que empeora de noche y afecta a varios en la familia; respeta la cabeza en mayores de 2 años."]),
  ("Niño de 9 años", ["1 mes de prurito intenso generalizado, peor de noche, sin tocar cara ni cuello.",
                      "Pápulas en interdigitales, muñecas, codos, axilas, glúteos y genitales."]),
  ["Permetrina 5 % de cuello a pies por la noche; repetir a los 7 días.",
   "Tratar a toda la familia el mismo día; lavar ropa y sábanas en agua caliente.",
   "Ivermectina oral (> 15 kg) en brotes o sarna costrosa; el prurito puede seguir 2-4 semanas."],
  "IUSTI, guía europea de escabiosis (2017, act. 2024); " + CDC + ", escabiosis (2024).",
  op=("¿Diagnóstico?", ["No: picaduras en zonas expuestas", "No: agudo, con fiebre", "Sí: pliegues + prurito nocturno",
                        "No: vesículas en codos y rodillas, celiaquía", "No: piojos en la ropa"]),
  d=dict(rotulo="Pápulas que pican: ¿cuál?", ans=0,
         cards=[dict(titulo="Escabiosis", datos=[("Dónde", "Pliegues, manos", True), ("Cuándo", "Peor de noche", True), ("Signo", "Surco", True)],
                     pie="Este caso."),
                dict(titulo="Prurigo por insectos", datos=[("Dónde", "Zonas expuestas", False), ("Lesión", "Pápula con punto", False), ("Causa", "Pulgas, zancudos", False)],
                     pie="Urticaria papulosa."),
                dict(titulo="Dermatitis herpetiforme", datos=[("Dónde", "Codos, rodillas", False), ("Lesión", "Vesículas", False), ("Causa", "Celiaquía", False)],
                     pie="IgA."),
                dict(titulo="Pediculosis corporal", datos=[("Dónde", "Tronco", False), ("Piojo", "En la ropa", False), ("Contexto", "Poca higiene", False)],
                     pie="Lavar la ropa.")]),
  banda=B("Así se ve el surco de la sarna", P("sarna_surco.jpg", 300, 233, [
            ("flecha", 0.80, 0.20, 0.55, 0.92, "surco: túnel del ácaro")],
          credito="Michael Geary" + CC + "dominio público"),
          [("Surco", "Línea fina, gris, de pocos milímetros."),
           ("Ácaro al final", "Un punto en el extremo del túnel."),
           ("Rascado", "Costras y escoriaciones alrededor."),
           ("Dónde buscar", "Entre los dedos y en las muñecas.")],
          pie="Piel de otro paciente.", ans=0))

# OFT-024 · Otitis externa · TARJETAS + foto real
S("tarjetas", "OFT-024", "Adolescente con prurito en el conducto auditivo, otorrea purulenta, hipoacusia, fiebre y adenopatía retroauricular: otitis externa",
  "Otorrinolaringología · oído externo",
  ("Otitis externa aguda", ["Infección de la piel del conducto auditivo externo (Pseudomonas, S. aureus), favorecida por agua y rascado.",
                            "Prurito, dolor al traccionar el pabellón o presionar el trago, conducto edematoso y otorrea."]),
  ("Varón de 15 años", ["Prurito intenso en el conducto derecho e hipoacusia.", "T 39 °C, otorrea purulenta y adenopatía retroauricular."]),
  ["Gotas de antibiótico (ciprofloxacino ± corticoide) 7 días; limpiar el conducto.",
   "Si el conducto está muy cerrado: mecha para que entren las gotas.",
   "Diabético o inmunosuprimido con dolor intenso: descartar otitis externa maligna (necrotizante)."],
  "AAO-HNS, otitis externa aguda (2014, act. 2024).",
  op=("¿Sospecha?", ["No: sin pus ni fiebre", "Afecta el pabellón, no el conducto", "No: vértigo, sin otorrea",
                     "Sí: conducto infectado", "No: pabellón despegado, dolor mastoideo"]),
  d=dict(rotulo="Oído que supura: ¿dónde está la infección?", ans=0,
         cards=[dict(titulo="Otitis externa", datos=[("Signo", "Trago doloroso", True), ("Conducto", "Hinchado", True), ("Síntoma", "Prurito", True)],
                     pie="Este caso."),
                dict(titulo="Otitis media", datos=[("Signo", "Tímpano abombado", False), ("Trago", "No duele", False), ("Edad", "Niños pequeños", False)],
                     pie="Amoxicilina."),
                dict(titulo="Mastoiditis", datos=[("Signo", "Pabellón despegado", False), ("Dolor", "Detrás de la oreja", False), ("Origen", "Otitis media", False)],
                     pie="Hospitalizar."),
                dict(titulo="Otomicosis", datos=[("Signo", "Hifas, «papel mojado»", False), ("Síntoma", "Prurito", False), ("Trato", "Antifúngico", False)],
                     pie="Hongos.")]),
  banda=B("Así se ve la otitis externa", P("otitis_ext.jpg", 280, 280, [
            ("flecha", 0.41, 0.42, 0.60, 0.92, "conducto hinchado y con pus")],
          credito="James Heilman" + CC + "CC BY 3.0"),
          [("Conducto hinchado", "Rojo y estrecho."),
           ("Secreción", "Pus en la entrada del conducto."),
           ("Trago doloroso", "Duele al presionarlo o tirar la oreja."),
           ("Tímpano", "Suele estar sano detrás.")],
          pie="Oído de otro paciente (caso grave).", ans=0))

# NEF-040 · Hiponatremia por tiazidas · ÁRBOL + gravedad
S("arbol", "NEF-040", "Anciana que toma hidroclorotiazida con desorientación y sopor, y sodio de 115: hiponatremia grave por tiazida",
  "Trastornos del sodio · hiponatremia",
  ("Hiponatremia por tiazidas", ["Las tiazidas hacen perder sodio en el túbulo distal y favorecen la retención de agua.",
                                 "Más riesgo en mujeres mayores, de bajo peso y en las primeras semanas."]),
  ("Mujer de 78 años con ICC", ["Desorientada hace 2 días, ahora soporosa.", "Losartán, digoxina, atorvastatina e hidroclorotiazida; Na 115."]),
  ["Síntomas graves: NaCl 3 % 150 mL en 20 min (hasta 2-3 veces) hasta mejorar o subir 5 mEq/L.",
   "No subir más de 8-10 mEq/L en 24 h (mielinólisis pontina).",
   "Suspender la tiazida para siempre; vigilar el potasio y la diuresis."],
  "Guía europea de hiponatremia (2014, act. 2024); " + KDIGO + ".",
  op=("¿Fármaco causante?", ["No: miopatía, no baja el sodio", "Sí: tiazida en anciana", "Sube el potasio; rara vez el sodio",
                             "No: náuseas, visión amarilla", "No la toma"]),
  arbol=Q("Hiponatremia con síntomas: ¿grave (sopor, convulsión)?", [
      L("Sí (este caso)", "NaCl 3 % EN BOLO", ["150 mL en 20 min", "Máx. 8-10 mEq/L en 24 h"], path=True),
      L("Leve o crónica sin síntomas", "Suspender la tiazida", ["Restringir agua"])], path=True),
  escala=dict(nombre="Gravedad de la hiponatremia", orden=True,
              que="Por la cifra de sodio y, sobre todo, por los síntomas.",
              grados=[("Leve", "130-135", ["Náuseas, fatiga"]), ("Moderada", "125-129", ["Confusión, cefalea"]),
                      ("Profunda", "< 125", ["Sopor, convulsiones, coma"])],
              caso=2, porque=[("Na 115 mEq/L", True), ("Soporosa: síntomas graves", True)],
              conducta="NaCl 3 % en bolo y UCI."))

# CB-033 · Aldosterona: células principales · TARJETAS
S("tarjetas", "CB-033", "La aldosterona actúa sobre las células principales del túbulo colector para reabsorber sodio y secretar potasio",
  "Fisiología renal · túbulo colector",
  ("Células principales", ["Tienen canales de sodio (ENaC) y de potasio (ROMK) que la aldosterona multiplica.",
                           "Reabsorben Na⁺ y agua y secretan K⁺; también responden a la ADH (acuaporina 2)."]),
  ("Pregunta de concepto", ["¿Dónde actúa directamente la aldosterona?", "Opciones: principales, yuxtaglomerulares, mesangiales, intersticiales, intercaladas."]),
  ["Espironolactona bloquea su receptor; amilorida bloquea el ENaC: ambos retienen potasio.",
   "Intercaladas α secretan H⁺ (la aldosterona las estimula de forma indirecta).",
   "Yuxtaglomerulares producen renina."],
  "Guyton y Hall, Tratado de fisiología médica (14.ª ed.).",
  op=("¿Células?", ["Sí: ENaC y ROMK", "No: producen renina", "No: sostén del glomérulo", "No: producen eritropoyetina", "No: manejan H⁺ y bicarbonato"]),
  d=dict(rotulo="Células del riñón: ¿qué hace cada una?", ans=0,
         cards=[dict(titulo="Principales", datos=[("Hormona", "Aldosterona, ADH", True), ("Hace", "Absorbe Na⁺", True), ("Secreta", "K⁺", True)],
                     pie="Este caso."),
                dict(titulo="Intercaladas", datos=[("Tipo α", "Secreta H⁺", False), ("Tipo β", "Secreta HCO₃⁻", False), ("Rol", "Ácido-base", False)],
                     pie="Colector."),
                dict(titulo="Yuxtaglomerulares", datos=[("Dónde", "Arteriola aferente", False), ("Hace", "Renina", False), ("Estímulo", "Baja presión", False)],
                     pie="Inicia el SRAA."),
                dict(titulo="Mesangiales", datos=[("Dónde", "Glomérulo", False), ("Hace", "Sostén", False), ("Enfermedad", "Nefropatía IgA", False)],
                     pie="Glomérulo.")]))

# SP-074 · Asentimiento informado · TARJETAS
S("tarjetas", "SP-074", "Un niño de 10 años expresa su aceptación o rechazo a un procedimiento o estudio mediante el asentimiento informado",
  "Bioética · consentimiento en menores",
  ("Asentimiento informado", ["Acuerdo del menor, después de explicarle con palabras de su edad.",
                              "Se suma al consentimiento de los padres o tutores, que son quienes firman legalmente."]),
  ("Pregunta de concepto", ["Niño de 10 años.", "Procedimiento, ensayo clínico terapéutico o sin beneficio directo."]),
  ["En investigación sin beneficio directo, la negativa del niño se respeta.",
   "En tratamientos necesarios su opinión se escucha, pero deciden los padres.",
   "Se pide según la madurez del niño (en general desde los 7-8 años)."],
  "CIOMS, pautas éticas de investigación (2016); Declaración de Helsinki (2024).",
  op=("¿Proceso?", ["Sí: el acuerdo del menor", "Lo da el adulto capaz o el representante", "Es la firma de los padres, no del niño",
                    "No es un término aceptado", "Solo en emergencias sin nadie que decida"]),
  d=dict(rotulo="¿Quién acepta y cómo?", ans=0,
         cards=[dict(titulo="Asentimiento", datos=[("Quién", "El niño", True), ("Cómo", "Con palabras simples", True), ("Valor", "Se respeta", True)],
                     pie="Este caso."),
                dict(titulo="Consentimiento", datos=[("Quién", "Adulto capaz", False), ("Cómo", "Informado, firmado", False), ("Valor", "Legal", False)],
                     pie="Mayores de edad."),
                dict(titulo="Consentimiento paterno", datos=[("Quién", "Padres o tutor", False), ("Para", "El menor", False), ("Valor", "Legal", False)],
                     pie="Junto al asentimiento."),
                dict(titulo="Presunto", datos=[("Cuándo", "Emergencia", False), ("Quién", "Nadie disponible", False), ("Base", "Salvar la vida", False)],
                     pie="Excepción.")]))

# CB-034 · Hidróxido de aluminio: hipofosfatemia · TARJETAS
S("tarjetas", "CB-034", "El uso crónico de antiácidos con hidróxido de aluminio atrapa el fosfato en el intestino: hipofosfatemia",
  "Farmacología · antiácidos",
  ("Hidróxido de aluminio", ["Neutraliza el ácido y se une al fosfato de la dieta formando sales que no se absorben.",
                             "Uso crónico: fósforo bajo, debilidad muscular, osteomalacia; además estreñimiento."]),
  ("Mujer de 65 años", ["Ardor epigástrico de mucho tiempo.", "Se automedica con un antiácido de hidróxido de aluminio."]),
  ["Hipofosfatemia grave (< 1 mg/dL): debilidad, rabdomiólisis, falla respiratoria, hemólisis.",
   "En la insuficiencia renal además puede acumular aluminio (encefalopatía, osteomalacia).",
   "Evaluar la dispepsia: H. pylori, IBP y endoscopía si hay alarma o edad > 60 años."],
  "Goodman & Gilman, Bases farmacológicas de la terapéutica (14.ª ed.).",
  op=("¿Resultado?", ["No: no cambia el sodio", "No: no cambia la glucosa", "No: no da hipercloremia", "Sí: atrapa el fosfato",
                      "Es el carbonato de calcio"]),
  d=dict(rotulo="Antiácidos: ¿qué efecto adverso?", ans=0,
         cards=[dict(titulo="Hidróxido de aluminio", datos=[("Laboratorio", "Fósforo bajo", True), ("Intestino", "Estreñimiento", True), ("Hueso", "Osteomalacia", True)],
                     pie="Este caso."),
                dict(titulo="Hidróxido de magnesio", datos=[("Laboratorio", "Mg alto en IRC", False), ("Intestino", "Diarrea", False), ("Riesgo", "Hiporreflexia", False)],
                     pie="Se combina con aluminio."),
                dict(titulo="Carbonato de calcio", datos=[("Laboratorio", "Calcio alto", False), ("Síndrome", "Leche-álcali", False), ("Otro", "Rebote ácido", False)],
                     pie="Hipercalcemia."),
                dict(titulo="Bicarbonato de sodio", datos=[("Laboratorio", "Alcalosis", False), ("Riesgo", "Retiene sodio", False), ("Otro", "Gases", False)],
                     pie="Evitar en IC.")]))

# SP-075 · Prevención de dengue autóctono: participación comunitaria · RADIAL + foto real
S("radial", "SP-075", "Casos importados de dengue y presencia de Aedes aegypti: para evitar casos autóctonos se prioriza la participación comunitaria contra los criaderos",
  "Metaxénicas · prevención del dengue",
  ("Prevención del dengue", ["Si hay Aedes y llega un caso importado, el zancudo puede picarlo y transmitir a otros (casos autóctonos).",
                             "La medida más eficaz y sostenible es eliminar criaderos con la comunidad."]),
  ("Centro de salud I-4", ["Casos importados de dengue.", "Presencia de Aedes aegypti en la zona."]),
  ["Eliminar, tapar o voltear recipientes con agua (floreros, llantas, baldes) cada semana.",
   "Vigilancia de febriles, control focal de larvas y fumigación si hay transmisión.",
   "La vacuna (TAK-003) tiene uso limitado a grupos y zonas definidas; no es la medida principal."],
  OMS + ", dengue (2024); " + MINSA + ", NTS de vigilancia y control del Aedes aegypti (2024).",
  op=("¿Qué priorizar?", ["Sí: eliminar criaderos", "No: no evita la transmisión", "No: trata síntomas, no previene",
                          "No: uso limitado, no es lo principal", "No: el dengue es viral"]),
  d=dict(rotulo="Cortar la transmisión del dengue", centro="COMUNIDAD", centro_sub="este caso", ans=0,
         items=[("CRIADEROS", ["Tapar, voltear, botar"]), ("EDUCACIÓN", ["Signos de alarma"]),
                ("FEBRILES", ["Vigilancia"]), ("LARVICIDA", ["Control focal"]),
                ("REPELENTE", ["Mosquiteros"])],
         ruta=["Organizar a los vecinos", "Recorrer las viviendas", "Eliminar criaderos", "Vigilar febriles"]),
  banda=B("El zancudo que transmite el dengue", P("aedes.jpg", 340, 258, [
            ("flecha", 0.38, 0.31, 0.12, 0.10, "manchas blancas\nen el tórax"),
            ("flecha", 0.72, 0.78, 0.40, 0.90, "patas con anillos\nblancos")],
          credito="John Ragai" + CC + "CC BY 2.0"),
          [("Negro con manchas blancas", "Dibujo de lira en el tórax."),
           ("Patas con anillos", "Lo distingue de otros zancudos."),
           ("Pica de día", "Mañana y tarde."),
           ("Cría en agua limpia", "Recipientes de la casa: ahí actúa la comunidad.")],
          pie="Hembra alimentándose.", ans=3))

# REU-029 · Acné comedoniano leve · ÁRBOL + clasificación + foto real
S("arbol", "REU-029", "Niña de 12 años con acné formado solo por comedones, sin lesiones inflamatorias: acné comedoniano, leve",
  "Dermatología · acné",
  ("Acné comedoniano", ["El poro se tapa con sebo y queratina: comedón abierto (punto negro) o cerrado (punto blanco).",
                        "Sin pápulas, pústulas ni nódulos: es la forma más leve."]),
  ("Niña de 12 años", ["Acné en la cara.", "Unos 30 comedones, sin lesiones inflamatorias descritas."]),
  ["Retinoide tópico (adapaleno 0,1 %) por la noche; puede sumarse peróxido de benzoilo.",
   "Lavado suave dos veces al día; no exprimir.",
   "Resultados en 8-12 semanas; mantener el retinoide para que no vuelva."],
  "AAD, guía de acné (2024); GILA, consenso latinoamericano de acné.",
  op=("¿Gravedad?", ["Sí: solo comedones", "No: conglobata o fulminante", "No: pápulas y pústulas", "No: nódulos y quistes",
                     "No: muchos nódulos"]),
  arbol=Q("Acné: ¿hay pápulas, pústulas o nódulos?", [
      L("No: solo comedones (este caso)", "ACNÉ LEVE COMEDONIANO", ["Retinoide tópico"], path=True),
      L("Sí", "Inflamatorio", ["Peróxido + antibiótico tópico", "Oral si es extenso"])], path=True),
  escala=dict(nombre="Clasificación del acné por tipo de lesión (GILA)", orden=True,
              que="Grado según la lesión que predomina.",
              grados=[("Grado I", "Comedoniano", ["Leve"]), ("Grado II", "Pápulo-pustular leve", ["Pocas lesiones"]),
                      ("Grado III", "Pápulo-pustular moderado", ["Muchas lesiones"]), ("Grado IV", "Nódulo-quístico", ["Grave"]),
                      ("Grado V", "Conglobata", ["Muy grave"])],
              caso=0, porque=[("Solo comedones, sin inflamación", True), ("Por número (30) algunas escalas la llamarían moderada", False)],
              conducta="Adapaleno tópico y control en 3 meses."),
  banda=B("Así se ven los comedones", P("acne.jpg", 300, 231, [
            ("circulo", 0.50, 0.50, 0.20, "comedones cerrados", 0.50, 0.92)],
          credito="Thomas Brinkmeier" + CC + "CC BY 4.0"),
          [("Comedón cerrado", "Punto blanco, pequeño, bajo la piel: los de la foto."),
           ("Comedón abierto", "Punto negro: el sebo se oscurece al aire."),
           ("Frente, nariz, mentón", "Zonas con más glándulas sebáceas."),
           ("Sin pus", "Si aparecen pústulas, ya es inflamatorio.")],
          pie="Piel de otra persona.", ans=0))

# OFT-025 · Conjuntivitis bacteriana · TARJETAS + foto real
S("tarjetas", "OFT-025", "Adolescente con secreción mucopurulenta y legañas en ambos ojos, sin dolor ni baja visual: conjuntivitis bacteriana",
  "Ojo rojo · conjuntivitis",
  ("Conjuntivitis bacteriana", ["Infección de la conjuntiva (S. aureus, neumococo, Haemophilus).",
                                "Secreción purulenta, párpados pegados al despertar, sensación de arenilla; visión normal y sin dolor."]),
  ("Adolescente de 15 años", ["3 días de secreción mucopurulenta y legañas en ambos ojos.", "Hiperemia marcada, sin dolor ni pérdida visual."]),
  ["Lavado con suero y antibiótico tópico (tobramicina o moxifloxacino) 5-7 días.",
   "Higiene de manos; no compartir toallas.",
   "Signos de alarma (derivar): dolor, fotofobia, baja visual, uso de lentes de contacto o secreción hiperaguda (gonococo)."],
  "AAO, Preferred Practice Pattern de conjuntivitis (2023).",
  op=("¿Diagnóstico?", ["No: masa dolorosa en el ángulo interno", "No: dolor y baja visual", "Sí: pus, sin dolor ni baja visual",
                        "Término no preciso; afectaría la córnea", "No: dolor, fotofobia, pupila pequeña"]),
  d=dict(rotulo="Ojo rojo: ¿cuál?", ans=0,
         cards=[dict(titulo="Bacteriana", datos=[("Secreción", "Purulenta", True), ("Dolor", "No", True), ("Visión", "Normal", True)],
                     pie="Este caso."),
                dict(titulo="Viral", datos=[("Secreción", "Acuosa", False), ("Ganglio", "Preauricular", False), ("Contagio", "Muy alto", False)],
                     pie="Adenovirus."),
                dict(titulo="Alérgica", datos=[("Síntoma", "Prurito", False), ("Secreción", "Mucosa", False), ("Bilateral", "Sí", False)],
                     pie="Antihistamínico."),
                dict(titulo="Queratitis / uveítis", datos=[("Dolor", "Sí", False), ("Visión", "Baja", False), ("Luz", "Fotofobia", False)],
                     pie="Derivar.")]),
  banda=B("Así se ve la conjuntivitis bacteriana", P("conjuntivitis.jpg", 330, 202, [
            ("flecha", 0.58, 0.55, 0.40, 0.92, "secreción purulenta")],
          credito="Gzzz" + CC + "CC BY-SA 4.0"),
          [("Ojo rojo difuso", "Toda la conjuntiva enrojecida."),
           ("Secreción purulenta", "Amarilla, pega los párpados."),
           ("Pupila y córnea normales", "Si la córnea se ve turbia, no es solo conjuntivitis."),
           ("Visión normal", "La baja visual es alarma.")],
          pie="Ojo de otro paciente.", ans=1))

# INF-054 · Meningitis bacteriana del adulto: neumococo · EMBUDO
S("embudo", "INF-054", "Mujer joven con fiebre, cefalea, vómitos, somnolencia y rigidez de nuca tras un resfriado: meningitis bacteriana por neumococo",
  "Meningitis bacteriana · etiología por edad",
  ("Meningitis bacteriana del adulto", ["El neumococo es la causa más común en adultos (a menudo tras otitis, sinusitis o neumonía).",
                                        "Fiebre, cefalea, rigidez de nuca y alteración de la conciencia; LCR turbio con neutrófilos."]),
  ("Mujer de 25 años", ["Cefalea, vómitos y somnolencia; resfriado previo.", "Glasgow 12, T 39 °C, FC 100, rigidez de nuca."]),
  ["Hemocultivos y, si no hay contraindicación, punción lumbar; TC antes si hay déficit focal, convulsión o inmunosupresión.",
   "Dexametasona 10 mg EV justo antes o con la primera dosis de antibiótico.",
   "Ceftriaxona 2 g cada 12 h + vancomicina; ampicilina si > 50 años, gestante o inmunosuprimido (Listeria)."],
  IDSA + ", meningitis bacteriana (2004, act. 2024); ESCMID (2016).",
  op=("¿Agente?", ["No: > 50 años, gestantes, inmunosuprimidos", "No: curso de semanas", "No: niños no vacunados", "Sí: el más común en adultos",
                   "No: encefalitis con conducta extraña"]),
  d=dict(rotulo="Meningitis en un adulto joven: ¿qué germen?", inicio="Fiebre, cefalea, vómitos, somnolencia y rigidez de nuca",
         candidatos=["S. pneumoniae", "Listeria", "M. tuberculosis", "H. influenzae", "Herpes simple"],
         pasos=[("¿Mayor de 50 años, gestante o inmunosuprimida?", ["Listeria"]),
                ("¿Curso de semanas, LCR con linfocitos y glucosa baja?", ["M. tuberculosis"]),
                ("¿Conducta extraña, convulsiones, lesión temporal?", ["Herpes simple"]),
                ("¿Niño no vacunado?", ["H. influenzae"])],
         final=("NEUMOCOCO", ["Más común en adultos", "Tras infección respiratoria"]),
         nota="Meningococo también es frecuente en jóvenes: suele dar púrpura."),
  escala=dict(nombre="Germen probable según la edad", orden=True,
              que="Base del tratamiento empírico.",
              grados=[("< 1 mes", "Neonato", ["S. agalactiae, E. coli, Listeria"]), ("1 mes-50 años", "Niños y adultos", ["Neumococo, meningococo"]),
                      ("> 50 años", "Mayores", ["Neumococo, Listeria"])],
              caso=1, porque=[("Tiene 25 años", True), ("Antecedente de infección respiratoria", True)],
              conducta="Dexametasona, ceftriaxona y vancomicina."))

# GAS-040 · ERGE con síntomas extraesofágicos: IBP · ÁRBOL + Montreal + signos de alarma
S("arbol", "GAS-040", "Obeso con pirosis, dolor retroesternal y síntomas respiratorios nocturnos: ERGE con manifestaciones extraesofágicas, iniciar IBP",
  "Esófago · enfermedad por reflujo",
  ("Enfermedad por reflujo gastroesofágico (ERGE)", ["El contenido del estómago sube al esófago y causa síntomas o lesiones.",
                                                     "Además de pirosis puede dar dolor torácico, tos, disfonía o sibilancias nocturnas (extraesofágicos)."]),
  ("Obeso de 45 años", ["1 año de dolor retroesternal atípico, disfagia y pirosis.", "De noche «le ronca el pecho» y cree que es asma."]),
  ["IBP 8 semanas antes del desayuno; bajar de peso, cabecera elevada, no cenar tarde.",
   "La disfagia es signo de alarma: pedir endoscopía (no solo IBP).",
   "pH-impedanciometría si no responde o antes de cirugía antirreflujo."],
  "ACG, ERGE (2022); Consenso de Lyon 2.0 (2024).",
  op=("¿Conducta?", ["No: no hay sospecha vascular", "Sí: prueba con IBP", "Si no responde al IBP", "Solo si persiste la sospecha de asma",
                     "Si persiste el dolor torácico"]),
  arbol=Q("Pirosis con síntomas extraesofágicos: ¿hay signos de alarma?", [
      L("Disfagia (este caso)", "IBP + ENDOSCOPÍA", ["IBP 8 semanas", "Endoscopía por la disfagia"], path=True),
      L("Sin alarma", "Prueba con IBP", ["8 semanas"])], path=True),
  escala=dict(nombre="Clasificación de Montreal de la ERGE", orden=False,
              que="Agrupa los síntomas del reflujo.",
              grados=[("Esofágico típico", "Pirosis, regurgitación", ["Síntoma clásico"]), ("Dolor torácico", "No cardíaco", ["Descartar corazón"]),
                      ("Extraesofágico", "Tos, asma, disfonía", ["Asociación posible"]), ("Con lesión", "Esofagitis, Barrett", ["Por endoscopía"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Pirosis, dolor torácico y sibilancias nocturnas: varios grupos a la vez", True)],
              conducta="IBP 8 semanas y endoscopía por la disfagia."),
  triada=TR([("Disfagia", "Sí", True), ("Pérdida de peso", "No se describe", None), ("Sangrado o anemia", "No se describe", None),
             ("Vómitos persistentes", "No se describe", None)],
            [("Signos de alarma", 0, 3)],
            "Cualquier signo de alarma pide endoscopía, aun si mejora con el IBP."))
