"""Entrega 1 · tanda 17 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, DOS, NELSON, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ESC, AAP, NICE

CC = " · Wikimedia Commons · "

# GIN-055 · Vaginitis mixta · TARJETAS + Amsel
S("tarjetas", "GIN-055", "Flujo maloliente que empeora tras el coito y el jabón, más prurito y eritema vulvar: vaginitis mixta, metronidazol + clotrimazol",
  "Vulvovaginitis · infección mixta",
  ("Vaginitis mixta", ["Vaginosis bacteriana (olor a pescado) y candidiasis (prurito, eritema) a la vez.",
                       "Se tratan las dos causas al mismo tiempo."]),
  ("Mujer de 26 años", ["Flujo maloliente que empeora con el coito y el lavado con jabón.", "Desde hace 24 h, prurito intenso y vulva roja."]),
  ["Vaginosis: metronidazol 500 mg cada 12 h por 7 días; candidiasis: clotrimazol vaginal o fluconazol 150 mg.",
   "El olor tras el coito o el jabón es la prueba de aminas (el pH alcalino libera aminas).",
   "La vaginosis no es una ITS: no hace falta tratar a la pareja."],
  CDC + ", guías de ITS (2021); " + ACOG + " Practice Bulletin n.º 215, vaginitis (2020).",
  op=("¿Terapia?", ["Sí: cubre vaginosis y Candida", "No: para cervicitis", "No: para cervicitis",
                    "Trata la vaginosis, no la Candida; la pareja no", "Trata solo la Candida"]),
  d=dict(rotulo="Flujo vaginal: ¿qué causa?", ans=0,
         cards=[dict(titulo="Vaginosis bacteriana", datos=[("Olor", "A pescado", True), ("Empeora", "Coito, jabón", True), ("pH", "> 4,5", True)],
                     pie="Este caso: metronidazol."),
                dict(titulo="Candidiasis", datos=[("Flujo", "Grumoso", True), ("Síntoma", "Prurito", True), ("pH", "< 4,5", False)],
                     pie="Este caso: clotrimazol."),
                dict(titulo="Tricomoniasis", datos=[("Flujo", "Espumoso, amarillo", False), ("Cérvix", "En fresa", False), ("Es ITS", "Sí", False)],
                     pie="Tratar a la pareja."),
                dict(titulo="Cervicitis", datos=[("Flujo", "Mucopurulento", False), ("Cérvix", "Friable", False), ("Germen", "Gonococo, clamidia", False)],
                     pie="Ceftriaxona + doxiciclina.")]),
  triada=TR([("Flujo blanco-grisáceo homogéneo", "No se describe", False), ("pH vaginal > 4,5", "No se midió", False),
             ("Prueba de aminas (olor)", "Olor tras coito y jabón", True), ("Células clave", "No se buscaron", False)],
            [("Criterios de Amsel (≥ 3 de 4)", 0, 3)],
            "Sospecha clínica de vaginosis; confirmar con pH y examen en fresco.", rotulo="Criterios con nombre propio"))

# GIN-056 · Tumor de ovario en la niña · TARJETAS
S("tarjetas", "GIN-056", "Niña de 7 años con dolor en fosa ilíaca y neoplasia ovárica: tumor de células germinales",
  "Ginecología pediátrica · tumores de ovario",
  ("Tumores de ovario en niñas y adolescentes", ["Los de células germinales son la mayoría (60-70 %) antes de los 20 años.",
                                                 "El más común es el teratoma maduro (quiste dermoide); malignos: disgerminoma, saco vitelino."]),
  ("Niña de 7 años", ["Dolor en el cuadrante inferior izquierdo.", "Neoplasia ovárica en la ecografía."]),
  ["Marcadores: AFP (saco vitelino), β-hCG (coriocarcinoma), LDH (disgerminoma).",
   "Cirugía conservadora del ovario siempre que sea posible (preservar fertilidad).",
   "Dolor brusco: descartar torsión (los tumores la favorecen)."],
  "FIGO Cancer Report (2021); " + NELSON + ".",
  op=("¿Tipo esperado?", ["No: muy raro", "No: de mujeres mayores", "Sí: los más comunes en niñas", "No: de adultas, raro", "No: de adultas"]),
  d=dict(rotulo="Tumor de ovario según la edad", ans=0,
         cards=[dict(titulo="Células germinales", datos=[("Edad", "Niñas, jóvenes", True), ("Ejemplo", "Teratoma, disgerminoma", True),
                                                         ("Marcadores", "AFP, β-hCG, LDH", True)],
                     pie="Este caso."),
                dict(titulo="Epiteliales", datos=[("Edad", "> 50 años", False), ("Ejemplo", "Seroso", False), ("Marcador", "CA-125", False)],
                     pie="Los más comunes en adultas."),
                dict(titulo="Cordones sexuales", datos=[("Ejemplo", "Granulosa juvenil", False), ("Efecto", "Estrógenos", False),
                                                       ("Clínica", "Pubertad precoz", False)],
                     pie="Inhibina."),
                dict(titulo="Metastásicos", datos=[("Origen", "Estómago, mama", False), ("Ejemplo", "Krukenberg", False), ("Lado", "Bilateral", False)],
                     pie="Buscar el primario.")]))

# PED-066 · Vacunación tardía: Hib · TARJETAS
S("tarjetas", "PED-066", "Niño de 6 años sin ninguna vacuna: la vacuna contra Haemophilus influenzae tipo b ya no es necesaria",
  "Inmunizaciones · esquema de recuperación",
  ("Vacunación de recuperación", ["Se completan las vacunas que faltan según la edad actual.",
                                  "Hib no se indica después de los 5 años en niños sanos: el riesgo es muy bajo."]),
  ("Niño de 6 años", ["Llevado por primera vez a control.", "No ha recibido ninguna vacuna."]),
  ["Sí necesita: difteria-tétanos-tos convulsiva (DPT o dT según edad), polio, hepatitis B, SPR (sarampión), varicela.",
   "Hib y neumococo conjugado: solo en mayores de 5 años con riesgo (asplenia, VIH, inmunodeficiencia).",
   "No reiniciar esquemas: se continúa donde quedó."],
  MINSA + ", esquema nacional de vacunación (NTS 196, 2022); " + CDC + ", esquema de recuperación (2025).",
  op=("¿NO es necesaria?", ["Sí: después de 5 años no se indica", "No: sí la necesita", "No: sí la necesita", "No: sí la necesita", "No: sí la necesita"]),
  d=dict(rotulo="Niño de 6 años sin vacunas: ¿qué necesita?", ans=0,
         cards=[dict(titulo="Hib", datos=[("A los 6 años", "No necesaria", True), ("Riesgo", "Muy bajo", True), ("Excepción", "Asplenia, VIH", True)],
                     pie="Este caso."),
                dict(titulo="Difteria-tétanos", datos=[("A los 6 años", "Sí", False), ("Dosis", "Esquema de 3", False), ("Luego", "Refuerzos", False)],
                     pie="DPT o dT."),
                dict(titulo="Hepatitis B", datos=[("A los 6 años", "Sí", False), ("Dosis", "3", False), ("Protege", "De por vida", False)],
                     pie="Indicada."),
                dict(titulo="Polio", datos=[("A los 6 años", "Sí", False), ("Tipo", "IPV/bOPV", False), ("Dosis", "Completar", False)],
                     pie="Indicada.")]))

# CB-017 · Apoptosis · TARJETAS
S("tarjetas", "CB-017", "La apoptosis se desencadena cuando la célula sufre un daño irreversible de su ADN",
  "Patología general · muerte celular",
  ("Apoptosis", ["Muerte celular programada: la célula se encoge y se fragmenta sin inflamar.",
                 "El daño irreparable del ADN activa p53 y las caspasas."]),
  ("Pregunta de concepto", ["¿Qué daño desencadena la apoptosis?", "Muerte celular ordenada."]),
  ["Vía intrínseca (mitocondrial): daño del ADN, falta de factores de crecimiento; BCL-2 la frena.",
   "Vía extrínseca: receptores de muerte (Fas, TNF).",
   "El cáncer evade la apoptosis (p53 mutado, BCL-2 alto)."],
  "Robbins y Cotran, Patología estructural y funcional 11.ª ed. (2025).",
  op=("¿Daño determinante?", ["Sí: activa p53 y caspasas", "Lleva a cáncer si evade la apoptosis", "Favorece el cáncer, no la apoptosis",
                              "No es el desencadenante", "Es lesión reversible o necrosis"]),
  d=dict(rotulo="¿Cómo muere o cambia la célula?", ans=0,
         cards=[dict(titulo="Apoptosis", datos=[("Gatillo", "ADN dañado sin arreglo", True), ("Célula", "Se encoge", True), ("Inflamación", "No", True)],
                     pie="Este caso."),
                dict(titulo="Necrosis", datos=[("Gatillo", "Isquemia, toxinas", False), ("Célula", "Se hincha y estalla", False),
                                               ("Inflamación", "Sí", False)],
                     pie="Siempre patológica."),
                dict(titulo="Lesión reversible", datos=[("Cambio", "Edema celular", False), ("ADN", "Íntegro", False), ("Final", "Se recupera", False)],
                     pie="Si cesa la causa."),
                dict(titulo="Transformación", datos=[("Cambio", "Mutaciones", False), ("Control", "Perdido", False), ("Apoptosis", "Evadida", False)],
                     pie="Cáncer.")]))

# CB-018 · Eficacia · TARJETAS
S("tarjetas", "CB-018", "Capacidad de un medicamento de producir el efecto deseado en condiciones ideales: eficacia",
  "Farmacología · conceptos",
  ("Eficacia, efectividad y eficiencia", ["Eficacia: efecto en condiciones ideales (ensayo clínico).",
                                          "Efectividad: en condiciones reales; eficiencia: en relación con el costo."]),
  ("Pregunta de concepto", ["Efecto deseado en condiciones ideales de uso.", "¿Cómo se llama?"]),
  ["Eficacia máxima (Emax): el mayor efecto que logra el fármaco.",
   "Potencia: la dosis necesaria para un efecto (un fármaco potente actúa a dosis bajas).",
   "Actividad intrínseca: capacidad de activar el receptor una vez unido (agonista total o parcial)."],
  "Goodman & Gilman, Las bases farmacológicas de la terapéutica 14.ª ed. (2023).",
  op=("¿Concepto?", ["No: capacidad de activar el receptor", "No: es en condiciones reales", "No: dosis para el efecto",
                     "Sí: condiciones ideales", "No: relación con el costo"]),
  d=dict(rotulo="Conceptos que se confunden", ans=0,
         cards=[dict(titulo="Eficacia", datos=[("Condiciones", "Ideales", True), ("Dónde", "Ensayo clínico", True), ("Mide", "¿Funciona?", True)],
                     pie="Este caso."),
                dict(titulo="Efectividad", datos=[("Condiciones", "Reales", False), ("Dónde", "Práctica diaria", False), ("Mide", "¿Funciona aquí?", False)],
                     pie="Mundo real."),
                dict(titulo="Eficiencia", datos=[("Compara", "Resultado y costo", False), ("Pregunta", "¿Vale lo que cuesta?", False),
                                                 ("Uso", "Gestión", False)],
                     pie="Economía."),
                dict(titulo="Potencia", datos=[("Mide", "Dosis necesaria", False), ("Más potente", "Menos dosis", False), ("Medida", "CE50", False)],
                     pie="No es eficacia.")]))

# CB-019 · Miopatía por estatinas · TARJETAS + clasificación
S("tarjetas", "CB-019", "Hipotiroidea que inicia tratamiento de dislipidemia y a la semana tiene mialgias: atorvastatina",
  "Farmacología · efectos adversos de estatinas",
  ("Síntomas musculares por estatinas", ["Mialgias, miositis o rara vez rabdomiólisis; empiezan en semanas.",
                                         "Más riesgo con hipotiroidismo, edad, falla renal, fibratos (gemfibrozilo) y fármacos que inhiben el CYP3A4."]),
  ("Mujer de 58 años con hipotiroidismo", ["Inicia tratamiento de dislipidemia.", "Una semana después: mialgias; no recuerda qué toma."]),
  ["Medir CK y TSH (el hipotiroidismo no controlado causa miopatía y la potencia).",
   "CK < 4 veces y síntomas tolerables: bajar dosis o cambiar de estatina; CK > 10 veces: suspender.",
   "Volver a intentar con otra estatina o dosis alterna; ezetimiba o iPCSK9 si no tolera."],
  "NLA, intolerancia a estatinas (2022); " + ESC + "/EAS, dislipidemias (2019, act. 2025).",
  op=("¿Causante?", ["No: no da mialgias", "Rara vez", "Sí: estatina, mialgias en semanas", "No: corrige el hipotiroidismo",
                     "Puede, sobre todo con estatina"]),
  d=dict(rotulo="Mialgias tras iniciar hipolipemiantes: ¿cuál?", ans=0,
         cards=[dict(titulo="Atorvastatina", datos=[("Mialgias", "Frecuentes", True), ("Cuándo", "Semanas", True), ("Riesgo", "Hipotiroidismo", True)],
                     pie="Este caso."),
                dict(titulo="Fenofibrato", datos=[("Mialgias", "Posibles", False), ("Mayor riesgo", "Con estatina", False), ("Uso", "Triglicéridos", False)],
                     pie="Gemfibrozilo peor."),
                dict(titulo="Ezetimiba", datos=[("Mialgias", "Raras", False), ("Mecanismo", "Absorción", False), ("Uso", "Con estatina", False)],
                     pie="Bien tolerada."),
                dict(titulo="Omega 3", datos=[("Mialgias", "No", False), ("Efecto", "Triglicéridos", False), ("Molestia", "Digestiva", False)],
                     pie="Segura.")]),
  escala=dict(nombre="Síntomas musculares por estatinas", orden=True, que="Según la CK y la función renal.",
              grados=[("Mialgia", "CK normal", ["Dolor sin daño muscular"]), ("Miositis", "CK > 10 veces", ["Suspender"]),
                      ("Rabdomiólisis", "CK > 40 veces", ["Mioglobinuria, falla renal"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Mialgias a la semana: medir la CK", True), ("Hipotiroidismo: medir TSH", True)],
              conducta="CK y TSH; ajustar o cambiar la estatina según el resultado."))

# CB-020 · Cricoaritenoideo posterior · TARJETAS
S("tarjetas", "CB-020", "Tras cirugía de una fístula traqueal, la glotis no se abre bien: lesión del músculo cricoaritenoideo posterior",
  "Anatomía · laringe",
  ("Músculos de la laringe", ["El cricoaritenoideo posterior es el único que abre la glotis (abductor).",
                              "Todos los intrínsecos los inerva el nervio laríngeo recurrente, menos el cricotiroideo (laríngeo superior)."]),
  ("Posoperatorio", ["Cirugía de fístula traqueal por intubación prolongada.", "Dificultad grave para abrir la glotis."]),
  ["Su parálisis bilateral (o la del recurrente) deja las cuerdas en la línea media: estridor y asfixia.",
   "Lesión unilateral del recurrente: voz ronca o bitonal.",
   "Tiroidectomía y cirugía de tráquea son las causas quirúrgicas más comunes."],
  "Moore, Anatomía con orientación clínica 9.ª ed. (2022); Netter, Atlas de anatomía humana 8.ª ed. (2023).",
  op=("¿Músculo?", ["Sí: único que abre la glotis", "No: relaja y acorta las cuerdas", "No: cierra la glotis", "No: es de la faringe",
                    "No: tensa las cuerdas"], {2: "Aritenoideo (interaritenoideo)"}),
  d=dict(rotulo="Músculos de la laringe: ¿qué hacen?", ans=0,
         cards=[dict(titulo="Cricoaritenoideo posterior", datos=[("Acción", "Abre la glotis", True), ("Nervio", "Recurrente", True),
                                                                 ("Si falla", "Asfixia", True)],
                     pie="Este caso."),
                dict(titulo="Cricoaritenoideo lateral", datos=[("Acción", "Cierra", False), ("Nervio", "Recurrente", False), ("Si falla", "Voz débil", False)],
                     pie="Aductor."),
                dict(titulo="Tiroaritenoideo", datos=[("Acción", "Relaja, acorta", False), ("Nervio", "Recurrente", False), ("Si falla", "Voz grave", False)],
                     pie="Vocal."),
                dict(titulo="Cricotiroideo", datos=[("Acción", "Tensa", False), ("Nervio", "Laríngeo superior", False), ("Si falla", "Sin agudos", False)],
                     pie="El único externo.")]))

# GIN-057 · Clave roja · RADIAL + 4 T
S("radial", "GIN-057", "La clave roja de las emergencias obstétricas se activa en las hemorragias",
  "Emergencias obstétricas · claves",
  ("Claves obstétricas (MINSA)", ["Roja: hemorragia; azul: trastornos hipertensivos graves; amarilla: sepsis.",
                                  "Cada clave asigna roles y pasos fijos al equipo."]),
  ("Pregunta de concepto", ["Sistema de claves en la emergencia obstétrica.", "¿Cuándo se activa la clave roja?"]),
  ["Roja: activar, dos vías gruesas, cristaloides, sangre, oxitocina y buscar la causa (4 T).",
   "Ácido tranexámico 1 g EV en las primeras 3 horas de la hemorragia posparto.",
   "Azul: sulfato de magnesio y control de la PA; amarilla: antibiótico y líquidos en la primera hora."],
  MINSA + ", guía de manejo de emergencias obstétricas (claves); " + OMS + ", hemorragia posparto (2023).",
  op=("¿Clave roja?", ["No: es la amarilla", "No: es la azul", "Sí: hemorragia obstétrica", "No tiene clave propia", "No tiene clave propia"]),
  d=dict(rotulo="Clave roja: qué hace cada miembro", centro="CLAVE ROJA", centro_sub="hemorragia obstétrica", ans=0,
         items=[("ACTIVAR", ["Avisar a todo el equipo"]), ("VÍAS", ["Dos vías gruesas, cristaloides"]), ("SANGRE", ["Pedir y transfundir"]),
                ("ÚTERO", ["Masaje + oxitocina"]), ("CAUSA", ["Tono, trauma, tejido, trombina"])],
         ruta=["Activar la clave", "Asignar roles", "Reponer volumen", "Tratar la causa"]),
  triada=TR([("Tono", "Atonía uterina (70 %)", None), ("Trauma", "Desgarros, rotura", None), ("Tejido", "Restos placentarios", None),
             ("Trombina", "Coagulopatía", None)],
            [("Las 4 T de la hemorragia posparto", 0, 3)],
            "Buscar las 4 T mientras se repone volumen.", rotulo="Causas con nombre propio"))

# NEU-018 · Tumor de Pancoast · EMBUDO + Rx y Horner reales + síndrome
S("embudo", "NEU-018", "Fumador con dolor de hombro que baja por el borde cubital: tumor de Pancoast",
  "Cáncer de pulmón · tumor del vértice (Pancoast)",
  ("Tumor de Pancoast", ["Cáncer del vértice del pulmón (surco superior) que invade el plexo braquial bajo (C8-T1).",
                         "Puede tomar la cadena simpática del cuello: síndrome de Horner."]),
  ("Varón de 60 años, fumador pesado", ["Dolor en el hombro que baja por la cara cubital del brazo.", "Parestesias en todo el brazo."]),
  ["Fumador + dolor de hombro con irradiación cubital = Pancoast hasta demostrar lo contrario: Rx, TC y RM del vértice.",
   "Con ptosis, miosis y anhidrosis del mismo lado se suma el síndrome de Horner.",
   "Tratamiento: quimiorradioterapia y luego cirugía si es resecable."],
  HARRISON + "; NCCN, cáncer de pulmón de células no pequeñas (2025).",
  op=("¿Sospecha?", ["Sí: fumador, dolor C8-T1", "No: es simétrica y distal", "No: no irradia ni da parestesias", "No: dolor articular",
                     "No: mediano, no cubital ni hombro"]),
  d=dict(rotulo="Del dolor de hombro al diagnóstico", inicio="Fumador con dolor de hombro y brazo",
         candidatos=["Tumor de Pancoast", "Polineuritis por déficit de B", "Bursitis crónica", "Osteoartritis de hombro"],
         pasos=[("¿Duele al mover el hombro, sin parestesias?", ["Bursitis crónica", "Osteoartritis de hombro"]),
                ("¿Parestesias en ambos pies y manos (en guante y calcetín)?", ["Polineuritis por déficit de B"])],
         final=("Tumor de Pancoast", ["Dolor y parestesias C8-T1 de un brazo en un fumador"]),
         nota="Rx y TC de tórax; la biopsia confirma el tipo."),
  banda=B("Cómo se ve", DOS(
            P("pancoast_rx.jpg", 360, 315, [("circulo", 0.31, 0.21, 0.085, "vértice derecho\nopaco", 0.27, 0.50),
                                            ("flecha", 0.68, 0.24, 0.80, 0.50, "vértice izquierdo\nnormal")],
              credito="Jmarchn" + CC + "CC BY-SA 3.0"),
            P("horner_ojos.jpg", 360, 94, [("flecha", 0.76, 0.37, 0.92, 0.17, "ptosis"),
                                           ("flecha", 0.724, 0.515, 0.50, 0.80, "miosis"),
                                           ("texto", 0.16, 0.86, "ojo sano")],
              credito="Horner: Waster" + CC + "CC BY 2.5"),
            vertical=True),
          [("Vértice blanco", "En la Rx el vértice derecho está opaco (el tumor); el izquierdo se ve negro, con aire."),
           ("Invade C8-T1", "Desde ahí alcanza las raíces del plexo: dolor y parestesias por el borde cubital."),
           ("Síndrome de Horner", "Si toma la cadena simpática: párpado caído y pupila pequeña del mismo lado."),
           ("Se ve mejor en TC o RM", "El vértice queda tapado por la clavícula en la Rx.")],
          pie="Imágenes de otros pacientes.", ans=0),
  triada=TR([("Dolor de hombro y brazo (C8-T1)", "Hombro → borde cubital", True), ("Parestesias o debilidad de la mano", "Parestesias en el brazo", True),
             ("Ptosis", "No se menciona", False), ("Miosis", "No se menciona", False), ("Anhidrosis facial", "No se menciona", False)],
            [("Tríada de Horner", 2, 4), ("Síndrome de Pancoast", 0, 4)],
            "El dolor y las parestesias del plexo bastan para sospecharlo; Horner aparece si invade el simpático."))

# SP-040 · Determinantes estructurales · TARJETAS
S("tarjetas", "SP-040", "Determinantes sociales de la salud: la etnia o raza es un determinante estructural",
  "Salud pública · determinantes sociales",
  ("Determinantes sociales (modelo de la OMS)", ["Estructurales: contexto y posición social (clase, ingresos, educación, género, etnia).",
                                                 "Intermedios: condiciones de vida y trabajo, conductas, factores psicosociales y el sistema de salud."]),
  ("Pregunta de concepto", ["Circunstancias en que las personas nacen, crecen, trabajan, viven y envejecen.", "¿Cuál es estructural?"]),
  ["Los estructurales generan la estratificación social; los intermedios son su consecuencia más cercana.",
   "Actuar sobre los estructurales reduce las inequidades en salud.",
   "El sistema de salud es un determinante intermedio."],
  OMS + ", Comisión sobre Determinantes Sociales de la Salud; Solar e Irwin (2010).",
  op=("¿Estructural?", ["No: intermedio", "No: intermedio", "Sí: posición social", "No: intermedio", "No: intermedio (conducta)"]),
  d=dict(rotulo="Determinantes sociales: ¿estructural o intermedio?", ans=0,
         cards=[dict(titulo="Estructural: posición social", datos=[("Ejemplos", "Etnia, género, clase", True), ("Nivel", "Origen de la inequidad", True),
                                                                   ("Aquí", "Etnia o raza", True)],
                     pie="Este caso."),
                dict(titulo="Estructural: contexto", datos=[("Ejemplos", "Políticas, cultura", False), ("Nivel", "Sociedad", False), ("Actúa", "Sobre todos", False)],
                     pie="Gobierno."),
                dict(titulo="Intermedio: condiciones", datos=[("Ejemplos", "Vida, trabajo", False), ("Nivel", "Material", False), ("Ejemplo", "Vivienda", False)],
                     pie="Consecuencia."),
                dict(titulo="Intermedio: conductas y sistema", datos=[("Ejemplos", "Dieta, salud", False), ("Nivel", "Individual", False),
                                                                      ("Ejemplo", "Hábitos", False)],
                     pie="Más cercanos.")]))

# SP-041 · Estudio de cohortes · TARJETAS
S("tarjetas", "SP-041", "Para determinar qué factores preceden a la aparición de casos de Zika: estudio de cohorte",
  "Epidemiología · diseños de estudio",
  ("Estudio de cohorte", ["Sigue a personas expuestas y no expuestas en el tiempo y ve quién enferma.",
                          "La exposición se mide antes del efecto: establece la secuencia temporal."]),
  ("Pregunta de investigación", ["Casos de Zika en una localidad.", "¿Qué factores preceden a la aparición de los casos?"]),
  ["Mide incidencia y riesgo relativo.",
   "Casos y controles va del efecto a la causa (más rápido, más sesgos).",
   "Ecológico y serie de casos no permiten saber qué fue primero en cada persona."],
  "Gordis, Epidemiología 6.ª ed. (2019).",
  op=("¿Diseño?", ["No es un diseño", "No: datos de grupos", "No: no mide asociación", "Sí: la exposición precede al efecto",
                   "No: solo describe casos"]),
  d=dict(rotulo="¿Qué diseño responde la pregunta?", ans=0,
         cards=[dict(titulo="Cohorte", datos=[("Dirección", "Exposición → efecto", True), ("Tiempo", "Seguimiento", True), ("Da", "Incidencia, RR", True)],
                     pie="Este caso."),
                dict(titulo="Casos y controles", datos=[("Dirección", "Efecto → exposición", False), ("Útil", "Enfermedades raras", False),
                                                       ("Da", "Odds ratio", False)],
                     pie="Más rápido."),
                dict(titulo="Ecológico", datos=[("Unidad", "Grupos", False), ("Datos", "Agregados", False), ("Riesgo", "Falacia ecológica", False)],
                     pie="Hipótesis."),
                dict(titulo="Serie de casos", datos=[("Grupo control", "No", False), ("Da", "Descripción", False), ("Causalidad", "No", False)],
                     pie="Describe.")]))

# CB-021 · Sarín: atropina · ÁRBOL + efectos muscarínicos
S("arbol", "CB-021", "Ataque con gas sarín (inhibidor de la colinesterasa) con sobreestimulación colinérgica: atropina EV",
  "Toxicología · agentes nerviosos",
  ("Agentes nerviosos (sarín)", ["Organofosforados de guerra: bloquean la acetilcolinesterasa y la acetilcolina se acumula.",
                                 "Muerte por broncorrea, broncoespasmo y parálisis respiratoria."]),
  ("Atentado del metro de Tokio (1995)", ["14 muertos.", "Sobreestimulación colinérgica."]),
  ["Atropina EV en dosis crecientes hasta secar los bronquios (no por las pupilas).",
   "Pralidoxima pronto (antes de que la unión se vuelva permanente); diazepam para las convulsiones.",
   "Descontaminar con protección: el personal también se intoxica."],
  OMS + ", manejo de intoxicaciones por plaguicidas; Goldfrank's Toxicologic Emergencies 11.ª ed. (2019).",
  op=("¿Antídoto?", ["Sí: bloquea el receptor muscarínico", "No: es para benzodiacepinas", "No: es para cianuro",
                     "No: es para metales pesados", "No: es para opioides"]),
  arbol=Q("Exceso colinérgico (sarín, organofosforado)", [
      L("Antídoto (este caso)", "ATROPINA EV", ["Hasta secar los bronquios", "+ pralidoxima, diazepam"], path=True),
      L("Exposición a cianuro", "Hidroxocobalamina", ["Nitritos como alternativa"])], path=True),
  triada=TR([("Miosis", "Pupila puntiforme", None), ("Broncorrea y broncoespasmo", "Causa de muerte", None), ("Bradicardia", "Vagal", None),
             ("Salivación y lagrimeo", "Secreciones", None), ("Diarrea y vómitos", "Digestivo", None)],
            [("Efectos muscarínicos (DUMBELS)", 0, 4)],
            "La atropina revierte estos efectos; la pralidoxima trata la debilidad muscular (nicotínica).", rotulo="Síndrome con nombre propio"))

# SP-042 · Declaración de Helsinki · TARJETAS
S("tarjetas", "SP-042", "Estudio en pacientes hospitalizados iniciado en secreto, sin consentimiento ni aprobación ética: incumple la Declaración de Helsinki",
  "Ética de la investigación",
  ("Declaración de Helsinki", ["Principios éticos para la investigación médica con seres humanos (AMM, revisada en 2024).",
                               "Exige consentimiento informado y aprobación previa de un comité de ética."]),
  ("Estudiantes de último año", ["Comparan alimentación usual frente a 20 % más de proteínas en hospitalizados.",
                                 "Inician el estudio en secreto; el comité de ética lo detiene."]),
  ["Nadie participa sin consentimiento informado, libre y por escrito.",
   "El protocolo se aprueba antes de empezar; el bienestar del participante está sobre la ciencia.",
   "En el Perú: reglamento de ensayos clínicos y comités de ética acreditados (INS)."],
  "AMM, Declaración de Helsinki (rev. 2024); CIOMS, pautas éticas (2016).",
  op=("¿Por qué se detuvo?", ["Sí: sin consentimiento ni aprobación", "Riesgo bajo; no es el motivo", "Riesgo bajo; no es el motivo",
                              "No es el motivo ético", "No es un motivo ético"]),
  d=dict(rotulo="Faltas en la investigación", ans=0,
         cards=[dict(titulo="Sin consentimiento", datos=[("Norma", "Helsinki", True), ("Aquí", "Estudio en secreto", True), ("Resultado", "Se detiene", True)],
                     pie="Este caso."),
                dict(titulo="Sin comité de ética", datos=[("Norma", "Helsinki, CIOMS", False), ("Debe", "Aprobar antes", False), ("Aquí", "También", False)],
                     pie="Falta asociada."),
                dict(titulo="Riesgo desproporcionado", datos=[("Cuándo", "Daño probable", False), ("Aquí", "Bajo", False), ("Norma", "Beneficencia", False)],
                     pie="No es el caso."),
                dict(titulo="Conflicto de intereses", datos=[("Cuándo", "Dinero o prestigio", False), ("Aquí", "No descrito", False), ("Norma", "Declararlo", False)],
                     pie="No es el caso.")]))

# PED-067 · Bronquiolitis · ÁRBOL + gravedad
S("arbol", "PED-067", "Lactante de 6 meses con catarro y fiebre que al tercer día tiene taquipnea, tiraje y sibilancias: bronquiolitis",
  "Infecciones respiratorias bajas · bronquiolitis",
  ("Bronquiolitis", ["Primer episodio de sibilancias en menores de 2 años por un virus (VSR).",
                     "Empieza como catarro y al 2.º-3.er día aparece dificultad respiratoria."]),
  ("Lactante de 6 meses", ["Alimentado con fórmula; fiebre, rinorrea y tos de 2 días.", "Al tercer día: taquipnea, tirajes y sibilancias espiratorias."]),
  ["Tratamiento de soporte: aspirar secreciones, hidratación, oxígeno si SatO₂ < 90-92 %.",
   "No se recomiendan salbutamol, corticoides, antibióticos ni fisioterapia respiratoria.",
   "Prevención: lactancia materna, nirsevimab o palivizumab en grupos de riesgo, vacuna materna contra el VSR."],
  AAP + ", bronquiolitis (2014, reafirmada); " + NICE + " NG9 (2015, act. 2021).",
  op=("¿Diagnóstico?", ["No: no da tiraje ni sibilancias", "No: inicio súbito con atoro, sin catarro", "No: mayores, sin tiraje",
                        "Sí: catarro + sibilancias < 2 años", "No: crepitantes focales, fiebre alta"]),
  arbol=Q("Lactante < 2 años con catarro y luego sibilancias", [
      L("Primer episodio (este caso)", "BRONQUIOLITIS", ["Soporte, oxígeno si hace falta"], path=True),
      L("Episodios repetidos", "Sibilancias recurrentes o asma", ["Broncodilatador de prueba"])], path=True),
  escala=dict(nombre="Gravedad de la bronquiolitis (NICE)", orden=True, que="Decide si se trata en casa o en el hospital.",
              grados=[("Leve", "Come bien", ["Sin tiraje, SatO₂ normal"]), ("Moderada", "Tiraje", ["Come < 50-75 %", "SatO₂ 90-92 %"]),
                      ("Grave", "Apnea o cianosis", ["SatO₂ < 90 %, quejido", "No come"])],
              caso=1, porque=[("Taquipnea y tirajes", True), ("Falta SatO₂ y cuánto come", False)],
              conducta="Soporte, aspiración nasal y oxígeno si la SatO₂ baja."))

# END-015 · Hipercolesterolemia familiar · ÁRBOL + Dutch Lipid Clinic
S("arbol", "END-015", "Joven con LDL 320, xantomas tendinosos y padre y hermana con colesterol muy alto: hipercolesterolemia familiar",
  "Dislipidemias · hipercolesterolemia familiar",
  ("Hipercolesterolemia familiar (HF)", ["Mutación del receptor de LDL (o APOB, PCSK9), autosómica dominante: LDL muy alto desde el nacimiento.",
                                         "Xantomas tendinosos y enfermedad coronaria precoz."]),
  ("Mujer de 21 años", ["Colesterol 390, LDL 320, TG 125, HDL 45.", "Xantomas en el Aquiles y extensores de las manos; padre y hermana con colesterol muy alto."]),
  ["Estatina de alta intensidad + ezetimiba; iPCSK9 si no llega a la meta.",
   "Estudiar a todos los familiares de primer grado (cribado en cascada), incluidos los niños.",
   "Estudio genético confirma y ayuda al cribado familiar."],
  ESC + "/EAS, dislipidemias (2019, act. 2025); EAS, consenso de hipercolesterolemia familiar (2023).",
  op=("¿Trastorno?", ["No: sin xantomas ni LDL tan alto", "No: subirían también los TG", "Sí: LDL muy alto + xantomas + herencia",
                      "No: TG normales", "No: TG y colesterol altos a la vez"], {4: "Disbeta- lipoproteinemia"}),
  arbol=Q("LDL muy alto: ¿puntaje de la Dutch Lipid Clinic?", [
      L("> 8: definida (este caso)", "HIPERCOLESTEROLEMIA FAMILIAR", ["Estatina + ezetimiba", "Cribado familiar"], path=True),
      L("3-8", "Posible o probable", ["Estudio genético"])], path=True),
  escala=dict(nombre="Criterios de la Dutch Lipid Clinic Network", modo="puntaje", que="Suma familia, clínica, examen y LDL.",
              items=[("F", "Familiar de 1.er grado con LDL alto", "Padre, hermana", 1), ("C", "Enfermedad coronaria precoz", "No", 0),
                     ("X", "Xantomas tendinosos", "Aquiles y manos", 6), ("L", "LDL 250-329 mg/dL", "320", 5), ("G", "Mutación conocida", "No estudiada", None)],
              total_txt="Total: 12 puntos",
              rangos=[("> 8", "HF definida", "Tratar y cribar a la familia"), ("6-8", "Probable", "Estudio genético"),
                      ("3-5", "Posible", "Estudio genético"), ("< 3", "Improbable", "Otra causa")],
              caso_rango=0, porque=[("Xantomas tendinosos (6) + LDL 320 (5)", True), ("Padre y hermana con colesterol alto", True)],
              conducta="Estatina de alta intensidad + ezetimiba y cribado en cascada."))

# GIN-058 · Tricomoniasis · TARJETAS
S("tarjetas", "GIN-058", "Flujo amarillento, espumoso y maloliente con prurito y cérvix en fresa: Trichomonas vaginalis",
  "Infecciones de transmisión sexual · tricomoniasis",
  ("Tricomoniasis", ["Protozoario de transmisión sexual; la ITS no viral más común.",
                     "Flujo amarillo-verdoso espumoso, mal olor, prurito, cérvix en fresa (colpitis macular)."]),
  ("Mujer de 22 años", ["Flujo amarillento, espumoso, maloliente, con prurito vaginal.", "Colpitis en fresa."]),
  ["Diagnóstico: examen en fresco (protozoarios móviles) o prueba molecular (más sensible).",
   "Metronidazol 500 mg cada 12 h por 7 días en mujeres; tratar a la pareja.",
   "Sin alcohol hasta 72 h después del metronidazol; descartar otras ITS."],
  CDC + ", guías de ITS (2021).",
  op=("¿Agente?", ["No: flujo gris, sin colpitis en fresa", "Sí: espumoso + cérvix en fresa", "No: úlceras dolorosas",
                   "No: flujo grumoso, sin mal olor", "No: cervicitis mucopurulenta"]),
  d=dict(rotulo="Flujo vaginal: ¿qué germen?", ans=0,
         cards=[dict(titulo="Trichomonas", datos=[("Flujo", "Espumoso, amarillo", True), ("Cérvix", "En fresa", True), ("Olor", "Malo", True)],
                     pie="Este caso."),
                dict(titulo="Gardnerella", datos=[("Flujo", "Gris, homogéneo", False), ("Olor", "A pescado", False), ("Células", "Clave", False)],
                     pie="Metronidazol."),
                dict(titulo="Candida", datos=[("Flujo", "Grumoso", False), ("Síntoma", "Prurito", False), ("pH", "Normal", False)],
                     pie="Azoles."),
                dict(titulo="Clamidia", datos=[("Cérvix", "Mucopus, friable", False), ("Síntomas", "A menudo ninguno", False), ("Riesgo", "EPI", False)],
                     pie="Doxiciclina.")]))

# CB-022 · Benzodiacepinas: flumazenil · TARJETAS
S("tarjetas", "CB-022", "Paciente soporoso, con FR 12, pupilas reactivas e hipotermia leve que despierta con flumazenil: benzodiacepinas",
  "Toxicología · síndromes tóxicos",
  ("Intoxicación por benzodiacepinas", ["Toxíndrome sedante-hipnótico: somnolencia o coma con signos vitales casi normales.",
                                        "Pupilas normales; la depresión respiratoria es leve si están solas."]),
  ("Varón de 28 años", ["Encontrado tirado en la calle; soporoso.", "FC 62, FR 12, SatO₂ 90 %, 35,6 °C, PA 100/60; pupilas reactivas; despierta con flumazenil."]),
  ["El tratamiento es de soporte (vía aérea, oxígeno); el flumazenil revierte, pero puede causar convulsiones.",
   "No usar flumazenil en consumidores crónicos ni si tomó tricíclicos o hay convulsiones.",
   "Miosis puntiforme y FR muy baja orientan a opioides: naloxona."],
  "Goldfrank's Toxicologic Emergencies 11.ª ed. (2019); " + HARRISON + ".",
  op=("¿Sustancia?", ["No: el flumazenil no lo revierte", "No: el flumazenil no los revierte", "No: daría miosis y responde a naloxona",
                      "Sí: revierte con flumazenil", "No: agitación y midriasis"]),
  d=dict(rotulo="Paciente estuporoso: ¿qué tóxico?", ans=0,
         cards=[dict(titulo="Benzodiacepinas", datos=[("Pupilas", "Normales", True), ("Respiración", "Poco deprimida", True), ("Antídoto", "Flumazenil", True)],
                     pie="Este caso."),
                dict(titulo="Opioides", datos=[("Pupilas", "Puntiformes", False), ("Respiración", "Muy deprimida", False), ("Antídoto", "Naloxona", False)],
                     pie="Naloxona."),
                dict(titulo="Tricíclicos", datos=[("Pupilas", "Midriasis", False), ("ECG", "QRS ancho", False), ("Antídoto", "Bicarbonato", False)],
                     pie="No flumazenil."),
                dict(titulo="Alcohol", datos=[("Aliento", "Etílico", False), ("Glucosa", "Puede bajar", False), ("Antídoto", "No", False)],
                     pie="Tiamina, glucosa.")]))

# HEM-013 · Linfoma: biopsia escisional · ÁRBOL + Lugano
S("arbol", "HEM-013", "Adenopatías cervicales y axilares indoloras, elásticas, con fiebre: biopsia escisional de un ganglio",
  "Linfomas · diagnóstico",
  ("Sospecha de linfoma", ["Ganglios grandes, indoloros, de consistencia elástica, en más de una región.",
                           "Síntomas B: fiebre, sudoración nocturna, pérdida de peso > 10 %."]),
  ("Varón de 60 años", ["Tumoraciones cervicales y axilares indoloras.", "38,9 °C; adenopatías elásticas cervicales y axilares."]),
  ["El diagnóstico exige la arquitectura del ganglio: biopsia escisional (o con aguja gruesa si no se puede).",
   "La PAAF no basta para clasificar un linfoma.",
   "Después: PET-TC para estadificar (Lugano) y médula ósea si hace falta."],
  "Clasificación de Lugano (2014); ESMO, linfomas (2023); " + HARRISON + ".",
  op=("¿Procedimiento?", ["Sí: da la arquitectura del ganglio", "Para estadificar después", "Para estadificar, no diagnostica",
                          "No: sin síntomas de esos órganos", "No: no da la arquitectura"],
      {0: "Biopsia escisional de ganglio cervical", 3: "Endoscopia y broncoscopia"}),
  arbol=Q("Adenopatías indoloras persistentes: ¿cómo diagnosticar?", [
      L("Sospecha de linfoma (este caso)", "BIOPSIA ESCISIONAL DEL GANGLIO", ["Anatomía patológica + inmunohistoquímica"], path=True),
      L("Después", "PET-TC", ["Estadificación de Lugano"])], path=True),
  escala=dict(nombre="Estadificación de Lugano (Ann Arbor modificada)", orden=True, que="Por las regiones afectadas.",
              grados=[("I", "Una región", ["Un grupo de ganglios"]), ("II", "Dos o más, mismo lado del diafragma", ["Cervical + axilar"]),
                      ("III", "Ambos lados del diafragma", ["Arriba y abajo"]), ("IV", "Fuera de los ganglios", ["Hígado, médula, pulmón"])],
              caso=1, porque=[("Cervical y axilar: mismo lado del diafragma", True), ("Falta la PET-TC para confirmar", False)],
              conducta="Biopsia escisional; luego PET-TC y tratamiento según el tipo."))

# SP-043 · Estudio experimental · TARJETAS
S("tarjetas", "SP-043", "Comparar el efecto de preguntas de 3 frente a 5 alternativas asignadas por el investigador: estudio experimental",
  "Epidemiología · diseños de estudio",
  ("Estudio experimental", ["El investigador asigna la intervención (idealmente al azar) y compara los resultados.",
                            "Es el diseño que mejor prueba causa y efecto."]),
  ("Pregunta de investigación", ["Impacto de usar 3 o 5 alternativas en preguntas de opción múltiple.", "¿Qué diseño usar?"]),
  ["Aquí el investigador decide quién recibe cada formato: experimental.",
   "Si se asigna al azar es un ensayo aleatorizado; mejor si los evaluadores no saben el grupo.",
   "En los observacionales (cohorte, casos y controles) el investigador no asigna nada."],
  "Gordis, Epidemiología 6.ª ed. (2019); CONSORT (2025).",
  op=("¿Diseño?", ["Sí: el investigador asigna", "No: observacional, desde el efecto", "No: no compara intervenciones",
                   "No: observacional, no asigna", "No: datos de grupos"]),
  d=dict(rotulo="¿Quién decide la exposición?", ans=0,
         cards=[dict(titulo="Experimental", datos=[("Exposición", "La asigna el investigador", True), ("Ideal", "Al azar", True), ("Prueba", "Causalidad", True)],
                     pie="Este caso."),
                dict(titulo="Cohorte", datos=[("Exposición", "Ya existe", False), ("Dirección", "Hacia adelante", False), ("Da", "RR", False)],
                     pie="Observacional."),
                dict(titulo="Casos y controles", datos=[("Parte de", "El efecto", False), ("Dirección", "Hacia atrás", False), ("Da", "OR", False)],
                     pie="Observacional."),
                dict(titulo="Descriptivo", datos=[("Compara", "No", False), ("Da", "Frecuencias", False), ("Prueba", "Nada causal", False)],
                     pie="Describe.")]))

# OFT-014 · OMA en el lactante: otoscopia · ÁRBOL + otoscopia real
S("arbol", "OFT-014", "Lactante con catarro que llora, rechaza el alimento y se golpea las orejas: otoscopia para confirmar otitis media aguda",
  "Otorrinolaringología · otitis media aguda", esp="OTORRINOLARINGOLOGÍA",
  tema=("Otitis media aguda en el lactante", ["Complicación frecuente del resfrío entre los 6 y 24 meses.",
                                              "El lactante no dice «me duele el oído»: llanto, irritabilidad, se toca las orejas, rechaza comer."]),
  caso=("Lactante de 8 meses", ["5 días de fiebre, rinorrea y tos.", "Hoy llanto constante, rechazo al alimento y se golpea las orejas."]),
  perlas=["La otoscopia confirma: tímpano abombado (con o sin otorrea).",
          "Menores de 2 años con OMA: amoxicilina 80-90 mg/kg/día por 10 días.",
          "Analgesia siempre (paracetamol o ibuprofeno)."],
  fuente=AAP + ", otitis media aguda (2013, reafirmada); " + NICE + " NG91 (2018, act. 2022).",
  op=("¿Examen?", ["Sí: ve el tímpano abombado", "No: no ve el oído", "No: no ve el oído", "No: es para catarata y retinoblastoma",
                   "No: no aplica en lactantes"]),
  arbol=Q("Lactante irritable que se toca las orejas tras un catarro", [
      L("Confirmar (este caso)", "OTOSCOPIA", ["Tímpano abombado = OMA", "Amoxicilina < 2 años"], path=True),
      L("Tímpano normal", "Buscar otra causa", ["Dentición, faringe, orina"])], path=True),
  banda=B("Otoscopia real de otitis media aguda", P("oma.jpg", 260, 260, [
            ("circulo", 0.6, 0.38, 0.2, "tímpano rojo,\nopaco y abombado", 0.5, 0.9)],
          credito="B. Welleschik" + CC + "CC BY-SA 3.0"),
          [("Tímpano rojo y abombado", "El pus empuja la membrana hacia afuera: confirma la OMA."),
           ("Sin reflejo luminoso", "El tímpano sano es gris perla y brillante; aquí está opaco."),
           ("El llanto enrojece", "Solo el rojo no basta: hace falta el abombamiento."),
           ("Tracción del pabellón", "En el lactante, hacia atrás y abajo para ver el tímpano.")],
          pie="Otoscopia de otro paciente.", ans=0))

# NRL-017 · Brown-Séquard · ÁRBOL + signos + ASIA
S("arbol", "NRL-017", "Herida por arma blanca en la nuca con parálisis del hemicuerpo derecho y alteración sensitiva del lado opuesto: Brown-Séquard, RM cervical",
  "Trauma raquimedular · síndromes medulares",
  ("Síndrome de Brown-Séquard", ["Hemisección de la médula, típica de heridas penetrantes.",
                                 "Mismo lado: parálisis y pérdida de posición y vibración; lado opuesto: pérdida de dolor y temperatura."]),
  ("Varón de 22 años", ["Herida profunda por arma blanca en la nuca.", "No mueve el hemicuerpo derecho; sensibilidad alterada en el lado contralateral."]),
  ["RM cervical: ve la médula, el hematoma y el edema (sin metal retenido).",
   "TC: hueso y fragmentos; angioTC si se sospecha lesión de las arterias vertebrales.",
   "Es el síndrome medular incompleto con mejor pronóstico de marcha."],
  "ASIA/ISNCSCI (2019); ATLS 11.ª ed. (2025).",
  op=("¿Estudio?", ["No: no ve la médula", "No: no aplica", "Hueso y vasos; la médula se ve en RM", "Sí: ve la médula lesionada",
                    "No: no ve la médula"]),
  arbol=Q("Herida penetrante con déficit medular: ¿qué estudio?", [
      L("Ver la médula (este caso)", "RM CERVICAL", ["Hematoma, edema, sección"], path=True),
      L("Hueso o vasos", "TC / angioTC", ["Fragmentos, arterias vertebrales"])], path=True),
  triada=TR([("Parálisis del mismo lado", "Hemicuerpo derecho", True), ("Pierde posición y vibración del mismo lado", "No se detalla", False),
             ("Pierde dolor y temperatura del lado opuesto", "Sensibilidad contralateral", True)],
            [("Síndrome de Brown-Séquard", 0, 2)],
            "Motor de un lado, dolor del otro: hemisección medular.", rotulo="Síndrome con nombre propio"),
  escala=dict(nombre="Escala ASIA (lesión medular)", orden=True, que="Gradúa la lesión medular por lo que se conserva bajo la lesión.",
              grados=[("A", "Completa", ["Sin motor ni sensibilidad sacra"]), ("B", "Sensitiva incompleta", ["Sensibilidad, sin motor"]),
                      ("C", "Motora incompleta", ["Fuerza < 3 en la mitad de músculos"]), ("D", "Motora incompleta", ["Fuerza ≥ 3 en la mitad"]),
                      ("E", "Normal", ["Recuperado"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Brown-Séquard es una lesión incompleta (B a D)", True), ("Se gradúa con el examen sacro completo", True)],
              conducta="RM, inmovilización y neurocirugía."))

# PED-068 · Maltrato infantil · TARJETAS + señales
S("tarjetas", "PED-068", "Lactante desnutrido con cefalohematoma, marcas curvas en las piernas y equimosis en muslos y escroto: maltrato infantil",
  "Pediatría social · maltrato infantil",
  ("Maltrato infantil", ["Lesiones en zonas poco expuestas, con forma de objeto o de distinta antigüedad.",
                         "En lactantes, cualquier equimosis o fractura sin explicación es sospechosa."]),
  ("Lactante de 1 año", ["Rechazo al alimento de 1 mes; desnutrido y pálido.",
                         "Cefalohematoma parietal; marcas curvas en las piernas; equimosis redondas en muslos y escroto."]),
  ["Hospitalizar para proteger; serie ósea completa y TC de cráneo (cefalohematoma).",
   "Fondo de ojo (hemorragias retinianas en el trauma craneal abusivo).",
   "Denunciar a la fiscalía o la policía y avisar a la DEMUNA; es obligación del personal de salud."],
  AAP + ", evaluación del maltrato físico (2015); Ley n.º 30364; " + MINSA + ".",
  op=("¿Diagnóstico?", ["No: sin fiebre ni choque", "Sí: lesiones con forma y en zonas ocultas", "No: sin fiebre ni conjuntivitis",
                        "No: daría trombosis, no equimosis", "No: púrpura palpable, no marcas con forma"]),
  d=dict(rotulo="Lactante con equimosis: ¿cuál?", ans=0,
         cards=[dict(titulo="Maltrato", datos=[("Lesiones", "Con forma de objeto", True), ("Lugar", "Escroto, muslos", True), ("Niño", "Desnutrido", True)],
                     pie="Este caso: proteger."),
                dict(titulo="Henoch-Schönlein", datos=[("Lesión", "Púrpura palpable", False), ("Lugar", "Glúteos, piernas", False), ("Edad", "3-10 años", False)],
                     pie="Plaquetas normales."),
                dict(titulo="Sepsis", datos=[("Fiebre", "Sí", False), ("Estado", "Grave, agudo", False), ("Piel", "Petequias", False)],
                     pie="Antibiótico."),
                dict(titulo="Kawasaki", datos=[("Fiebre", "≥ 5 días", False), ("Ojos", "Conjuntivitis", False), ("Boca", "Labios rojos", False)],
                     pie="Inmunoglobulina.")]),
  triada=TR([("Lesión sin explicación", "Cefalohematoma", True), ("Marcas con forma de objeto", "Curvas en las piernas", True),
             ("Zonas poco expuestas", "Escroto, muslos", True), ("Desnutrición", "Sí", True)],
            [("Señales de alarma de maltrato", 0, 3)],
            "Cuatro señales: proteger, estudiar y denunciar.", rotulo="Señales de alarma"))

# PED-069 · Sepsis neonatal: ampicilina + aminoglucósido · ÁRBOL + índice I/T
S("arbol", "PED-069", "Recién nacido con hipotermia, mala succión, dificultad respiratoria, leucopenia e índice I/T de 0,3: sepsis, ampicilina + amikacina",
  "Infecciones neonatales · sepsis",
  ("Sepsis neonatal temprana", ["Estreptococo B y E. coli son los gérmenes principales; Listeria es rara pero necesita ampicilina.",
                                "Signos sutiles: hipotermia, hipoactividad, rechazo al alimento, dificultad respiratoria."]),
  ("Recién nacido de 3500 g", ["Hipotermia, débil succión, hipoactividad; polipnea y tiraje.", "Leucocitos 3000; abastonados/neutrófilos 0,3."]),
  ["Hemocultivo y luego ampicilina + aminoglucósido (gentamicina o amikacina) EV.",
   "Cefotaxima si hay meningitis o gramnegativo resistente; la ceftriaxona se evita en neonatos.",
   "Leucopenia (< 5000) e I/T > 0,2 apoyan la sepsis, pero el hemocultivo confirma."],
  AAP + ", sepsis neonatal temprana (2018, act. 2024); " + NICE + " NG195 (2021, act. 2024).",
  op=("¿Primera elección?", ["No: ceftriaxona se evita en neonatos", "Sí: cubre estreptococo B, Listeria y E. coli", "No: es para infección hospitalaria",
                             "Si hay meningitis; no de rutina", "No: es grave, va EV"]),
  arbol=Q("Recién nacido con signos de sepsis: tomar hemocultivo", [
      L("Sepsis temprana (este caso)", "AMPICILINA + AMINOGLUCÓSIDO", ["Gentamicina o amikacina"], path=True),
      L("Sospecha de meningitis", "Ampicilina + cefotaxima", ["Punción lumbar"])], path=True),
  escala=dict(nombre="Índice I/T (inmaduros/totales)", orden=True, que="Neutrófilos inmaduros sobre neutrófilos totales.",
              grados=[("≤ 0,2", "Normal", ["Infección menos probable"]), ("> 0,2", "Sugiere infección", ["Con clínica, tratar"])],
              caso=1, porque=[("I/T 0,3", True), ("Leucopenia de 3000", True)],
              conducta="Hemocultivo y ampicilina + aminoglucósido EV."))

# SP-044 · Liderazgo · TARJETAS
S("tarjetas", "SP-044", "El médico jefe moviliza al personal en brigadas a domicilio y logra la cobertura de la tercera dosis: liderazgo",
  "Gestión en salud · habilidades directivas",
  ("Liderazgo", ["Capacidad de motivar y movilizar al equipo hacia una meta común.",
                 "El líder analiza el problema, propone una salida y compromete a todos."]),
  ("Médico jefe", ["90 % con dos dosis, solo 30 % con la tercera; la enfermera quiere devolver vacunas.",
                   "Convoca al personal, forma brigadas a domicilio y logra la cobertura."]),
  ["Liderazgo: dirección + motivación + resultado.",
   "Comunicación: transmitir información; negociación: acuerdos entre partes con intereses distintos.",
   "Adaptación al cambio: ajustar procesos ante algo nuevo."],
  MINSA + ", competencias de gestión en el primer nivel; Kotter, Liderar el cambio (2012).",
  op=("¿Habilidad?", ["Parte del liderazgo, no lo central", "Valor general, no la habilidad", "Ayuda, pero lo central es movilizar",
                      "Sí: moviliza al equipo hacia la meta", "No hubo partes en conflicto"]),
  d=dict(rotulo="Habilidades de gestión", ans=0,
         cards=[dict(titulo="Liderazgo", datos=[("Hace", "Moviliza al equipo", True), ("Aquí", "Brigadas", True), ("Logra", "La meta", True)],
                     pie="Este caso."),
                dict(titulo="Comunicación", datos=[("Hace", "Informa y escucha", False), ("Aquí", "Necesaria", False), ("Logra", "Entendimiento", False)],
                     pie="Herramienta."),
                dict(titulo="Negociación", datos=[("Hace", "Acuerdos", False), ("Cuando", "Intereses opuestos", False), ("Aquí", "No aplica", False)],
                     pie="No es el caso."),
                dict(titulo="Adaptación al cambio", datos=[("Hace", "Ajusta procesos", False), ("Cuando", "Algo nuevo", False), ("Aquí", "Secundaria", False)],
                     pie="Complementa.")]))

# SP-045 · Mordeduras de perro: municipalidad · ÁRBOL + exposición a rabia
S("arbol", "SP-045", "Varias mordeduras por perros callejeros que no se pueden capturar: coordinar con la municipalidad",
  "Salud pública · zoonosis y rabia",
  ("Control de perros callejeros", ["El control de canes en la vía pública es función de los gobiernos locales.",
                                    "Salud atiende a las personas; la municipalidad captura, observa y controla a los animales."]),
  ("Centro de salud", ["Varias personas mordidas por perros callejeros.", "No es posible capturarlos."]),
  ["Coordinar con la municipalidad (Ley 27596 de tenencia de canes) para captura, observación y vacunación canina.",
   "Cada mordido: lavar con agua y jabón 15 min y vacuna antirrábica según la categoría; perro no observable = esquema completo.",
   "Notificar a epidemiología (rabia: vigilancia obligatoria)."],
  MINSA + ", norma técnica de prevención y control de la rabia humana (2017); Ley n.º 27596.",
  op=("¿Institución?", ["Sí: controla a los perros callejeros", "No: no es su función", "Apoya, no lidera",
                        "No: solo educación", "No: animales de producción"]),
  arbol=Q("Mordeduras por perros callejeros: ¿quién controla a los animales?", [
      L("Captura y control (este caso)", "MUNICIPALIDAD", ["Observación 10 días", "Vacunación canina"], path=True),
      L("Atención de las personas", "Centro de salud", ["Lavado y vacuna antirrábica"])], path=True),
  escala=dict(nombre="Categorías de exposición a la rabia (OMS)", orden=True, que="Deciden la profilaxis de cada mordido.",
              grados=[("I", "Contacto sin lesión", ["Tocar o lamer piel sana", "Nada"]),
                      ("II", "Mordisco leve", ["Rasguño sin sangrar", "Vacuna"]),
                      ("III", "Mordedura que sangra", ["O lamido de mucosas", "Vacuna + inmunoglobulina"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Cada mordido se clasifica según su herida", True), ("Perro callejero no observable: completar el esquema", True)],
              conducta="Municipalidad para los perros; lavado y vacuna para las personas."))
