"""Bloque ENAM 2026 · Ginecología y Obstetricia (parte 2)."""
from c26 import S, D, P, B, ILU, Q, L, WILLIAMS, MINSA
import ilu7 as I

O = I.ORANGE
ESP = "GINECO-OBSTETRICIA ENAM"
ACOG = "ACOG Practice Bulletins"

# GIN-255 · DPP con compromiso · CRITERIOS
S("criterios", "GIN-255", "desprendimiento-placenta-utero-hipertonico-coagulopatia-cesarea",
  "Desprendimiento prematuro de placenta grave: cesárea de emergencia",
  "Hemorragias del tercer trimestre · desprendimiento de placenta", ESP,
  ("Desprendimiento prematuro de placenta (DPP)", ["La placenta se separa antes del parto: sangra por detrás y el útero se contrae sin relajar.",
                                                   "Con compromiso fetal o materno, el parto es inmediato."]),
  ("Secundigesta de 34 semanas, cesárea previa", ["Dolor súbito, intenso y continuo con sangrado oscuro escaso; PA 170/100.",
                                                  "Útero hipertónico; FCF 160 con desaceleraciones tardías; Hb 7,5; plaquetas 110 000."]),
  ["DPP con feto vivo comprometido o madre inestable: cesárea de emergencia.",
   "El sangrado externo escaso engaña: la sangre queda detrás de la placenta.",
   "Vigilar coagulopatía (fibrinógeno, plaquetas) y reponer sangre y derivados."],
  ACOG + "; " + WILLIAMS + "; " + MINSA + ", guía de hemorragia obstétrica.",
  d=dict(rotulo="¿Es un desprendimiento grave?", tag="ESTE CASO", lista_titulo="Signos del caso",
         items=[("Dolor súbito, intenso y continuo", True, "No cede entre contracciones"),
                ("Sangrado vaginal oscuro y escaso", True, "La sangre se acumula detrás"),
                ("Útero hipertónico y doloroso", True, "«Útero de madera»"),
                ("Compromiso fetal", True, "Variabilidad mínima y desaceleraciones tardías"),
                ("Anemia o coagulopatía", True, "Hb 7,5; plaquetas y fibrinógeno bajando")],
         umbral="feto comprometido o madre inestable",
         veredicto="DPP grave: cesárea de emergencia con reposición de sangre y derivados",
         img_titulo="Pieza real de un DPP",
         img=P("dpp_pieza.jpg", 360, 227, [("flecha", 0.66, 0.22, 0.88, 0.10, "placenta"),
                                           ("flecha", 0.50, 0.57, 0.22, 0.12, "coágulo\nretroplacentario"),
                                           ("flecha", 0.36, 0.80, 0.74, 0.90, "pared del útero")],
               credito="Mikael Häggström · Wikimedia Commons · CC0", fondo="#1d4ed8"),
         img_pie="El coágulo queda atrapado entre la placenta y el útero: por eso sangra poco afuera. Pieza de otra paciente.",
         claves_titulo="Por qué no las otras",
         claves=[("Magnesio como tocolítico", ["Contraindicado: no se frena un DPP."], False),
                 ("Inducción con oxitocina", ["El feto no tolera esperar el parto vaginal."], False),
                 ("Manejo expectante", ["Solo en DPP leve, lejos del término y con todo estable."], False)]),
  tabla=("Opciones de la pregunta", [("Magnesio tocolítico", False), ("Cesárea de emergencia", True), ("Inducción", False), ("Expectante", False)],
         [("¿Adecuada?", ["No", "Sí", "No: feto comprometido", "No"])]))

# GIN-256 · Insuficiencia cervical · ÁRBOL CON IMAGEN
S("arbol_imagen", "GIN-256", "insuficiencia-cervical-dos-perdidas-indoloras-cerclaje",
  "Insuficiencia cervical por historia: cerclaje profiláctico",
  "Parto pretérmino · insuficiencia cervical", ESP,
  ("Insuficiencia cervical", ["El cuello se dilata sin contracciones en el segundo trimestre.",
                              "Se sospecha por pérdidas indoloras repetidas antes de las 28 semanas."]),
  ("Tercigesta de 10 semanas", ["Dos partos pretérmino indoloros a las 22 y 25 semanas.",
                                "Asintomática, cérvix cerrado; longitud cervical 25 mm."]),
  ["Historia de ≥ 1-2 pérdidas del segundo trimestre indoloras: cerclaje profiláctico a las 12-14 semanas.",
   "Sin esa historia pero con cérvix ≤ 25 mm antes de las 24 semanas y parto pretérmino previo: cerclaje o progesterona.",
   "La tocólisis (ritodrina) y el magnesio no tratan la insuficiencia cervical."],
  ACOG + " n.º 142 (cerclaje); " + WILLIAMS + ".",
  d=dict(rotulo="¿Qué dice la historia obstétrica?", tag="ESTE CASO",
         pregunta="¿Tiene pérdidas previas del segundo trimestre sin dolor ni contracciones?",
         ramas=[("No", "Medir el cuello entre las 16 y 24 semanas", ["Si ≤ 25 mm con parto pretérmino previo:", "cerclaje o progesterona vaginal."]),
                ("Sí: 22 y 25 semanas (este caso)", "Cerclaje profiláctico a las 12-14 semanas",
                 ["Sutura en bolsa de tabaco en el cuello (McDonald o Shirodkar)."])],
         ilu=lambda s, x, y: I.cervix(s, x + 130, y, 25), IW=560, IH=230,
         ilu_pie="Cuello de 25 mm y la sutura del cerclaje (azul) que lo mantiene cerrado.",
         luego_titulo="Después del cerclaje",
         luego=[("Retiro", ["A las 36-37 semanas o antes si inicia el parto."], False),
                ("Control", ["Ecografía de la longitud cervical."], False),
                ("Evitar", ["Tocólisis o magnesio no tratan esta causa."], False)]),
  tabla=("Opciones de la pregunta", [("Expectante", False), ("Cerclaje", True), ("Ritodrina", False), ("Magnesio", False)],
         [("¿Trata la causa?", ["No: repetiría la pérdida", "Sí", "No: no hay contracciones", "No"])]))

# GIN-257 · Patrón sinusoidal · ESCALERA (CTG dibujado)
S("escalera", "GIN-257", "rpm-24-horas-fiebre-patron-sinusoidal-bradicardia-terminar",
  "Patrón sinusoidal con bradicardia y fiebre: terminar la gestación",
  "Monitoreo fetal intraparto · categorías NICHD", ESP,
  ("Monitoreo fetal intraparto (NICHD)", ["Categoría I normal, II indeterminada, III anormal.",
                                          "La categoría III (sinusoidal, bradicardia, ausencia de variabilidad con desaceleraciones) exige parto rápido."]),
  ("Primigesta de 36 semanas en fase latente", ["RPM de 24 h y fiebre de 38,5 °C (sospecha de corioamnionitis).",
                                                "CTG: patrón sinusoidal > 20 min y bradicardia fetal."]),
  ["Patrón sinusoidal sostenido = categoría III: anemia o hipoxia fetal grave.",
   "Con corioamnionitis y bradicardia: terminar la gestación por la vía más rápida (casi siempre cesárea).",
   "La tocólisis y el manejo expectante están contraindicados."],
  "NICHD, clasificación del monitoreo fetal (2008); " + ACOG + " n.º 106 y 116.",
  d=dict(rotulo="El registro del caso y la conducta",
         img=dict(titulo="Cardiotocografía (esquema)", IH=236, ilu=lambda s, x, y: I.ctg(s, x + 80, y + 2, "sinusoidal", W=740),
                  pie="Arriba: onda regular como una sinusoide, sin variabilidad, y luego caída a bradicardia. Abajo: pocas contracciones (fase latente)."),
         check_titulo="¿Es categoría III?",
         check=[("Patrón sinusoidal > 20 minutos", True), ("Bradicardia fetal", True), ("Fiebre + RPM de 24 h: corioamnionitis", True)],
         veredicto="CATEGORÍA III: terminar ya",
         peldanos=[("Categoría I", ["Vigilancia habitual."]), ("Categoría II", ["Reanimación intrauterina y reevaluar."]),
                   ("Categoría II que no mejora", ["Acelerar el parto."]), ("Categoría III", ["Terminar la gestación de inmediato."])],
         ans=3, tag="ESTE CASO", salto="Categoría III",
         leyenda_estable="Registro normal o dudoso: se sube de nivel solo si el registro empeora.",
         leyenda_inestable="Categoría III (este caso): directo a terminar la gestación, por la vía más rápida."),
  tabla=("Opciones de la pregunta", [("Terminar la gestación", True), ("Tocólisis", False), ("Expectante", False), ("Sulfato de magnesio", False)],
         [("¿Adecuada?", ["Sí", "Contraindicada", "Peligroso", "No resuelve la hipoxia"])]))

# GIN-258 · Cistocele y rectocele · CRITERIOS
S("criterios", "GIN-258", "cistocele-rectocele-perine-amplio-colporrafia-perineorrafia",
  "Cistocele y rectocele con periné amplio: colporrafia anterior, posterior y perineorrafia",
  "Prolapso de órganos pélvicos · cirugía por compartimento", ESP,
  ("Prolapso de órganos pélvicos", ["Se corrige cada compartimento dañado: anterior, posterior, apical y periné.",
                                    "En mujeres con vida sexual se evitan las técnicas que cierran la vagina."]),
  ("Multípara de 68 años, sexualmente activa", ["Bulto vaginal, presión pélvica y disfunción miccional.",
                                                "Cistocele II, rectocele III, introito laxo y periné amplio."]),
  ["Cistocele → colporrafia anterior; rectocele → colporrafia posterior; introito laxo → perineorrafia.",
   "La suspensión uterosacra o la sacropexia son para el prolapso apical.",
   "La colpocleisis solo si no desea vida sexual."],
  "ACOG n.º 214 (prolapso); Te Linde Ginecología Quirúrgica 12.ª ed.",
  d=dict(rotulo="Qué compartimentos están dañados", tag="ESTE CASO", lista_titulo="Hallazgo → procedimiento",
         items=[("Cistocele grado II → colporrafia anterior", True, "Compartimento anterior"),
                ("Rectocele grado III → colporrafia posterior", True, "Compartimento posterior"),
                ("Introito laxo y periné amplio → perineorrafia", True, "Reconstruye el cuerpo perineal"),
                ("Prolapso apical (útero o cúpula)", False, "No descrito: no hace falta suspensión apical"),
                ("Sin vida sexual (permitiría colpocleisis)", False, "Es sexualmente activa")],
         umbral="se repara cada compartimento dañado",
         veredicto="Colporrafia anterior + posterior + perineorrafia",
         img_titulo="Corte sagital", img=D(lambda s, x, y: I.pelvis_sagital(s, x, y, "cisto_recto"), 320, 306)),
  tabla=("Opciones de la pregunta", [("Suspensión uterosacra", False), ("Histerectomía sin colporrafia", False),
                                     ("Colpocleisis", False), ("Colporrafia ant. + post. + perineorrafia", True)],
         [("Problema", ["Trata el ápice, no estos defectos", "Deja cistocele y rectocele", "Cierra la vagina", "Ninguno"])]))

# GIN-259 · Control prenatal tardío · CRONOLOGÍA
S("cronologia", "GIN-259", "primigesta-19-anos-primer-control-22-semanas-inicio-tardio",
  "Primer control prenatal a las 22 semanas: el inicio tardío es el principal riesgo",
  "Atención prenatal · factores de riesgo obstétrico", ESP,
  ("Atención prenatal (MINSA)", ["Primer control antes de las 14 semanas y al menos 6 controles.",
                                 "Captar tarde deja sin tamizajes ni suplementos oportunos."]),
  ("Primigesta de 19 años", ["Primer control a las 22 semanas.", "Anemia moderada; vive en zona rural con poco acceso."]),
  ["Control prenatal tardío (≥ 14 semanas) es un factor de riesgo obstétrico modificable.",
   "Tener 19 años (adolescencia tardía) también suma riesgo, pero lo que la norma señala como principal aquí es el inicio tardío.",
   "Ruralidad y pobreza son determinantes que explican el retraso, no el factor de riesgo obstétrico principal."],
  MINSA + ", NTS 105 atención integral de la salud materna.",
  d=dict(rotulo="Qué se pierde al empezar tarde", tag="ESTE CASO",
         ilu_titulo="La gestante del caso",
         ilu=ILU(D(lambda s, x, y: I.gestante(s, x + 100, y, marcas=[(1, 120, 205)], sc=0.6), 330, 270)),
         ilu_pie="22 semanas y recién llega al primer control.",
         claves=[("Inicio tardío del control", ["Principal factor de riesgo modificable del caso."], True),
                 ("Anemia moderada", ["Hallazgo que el control temprano habría tratado antes."], False),
                 ("Ruralidad y pobreza", ["Explican el retraso; se abordan con captación activa."], False)],
         eje_titulo="Semanas de gestación", eje=(0, 40), paso=4, marca=22, unidad="sem",
         hitos=[(0, 14, "Primer control ideal", "antes de 14 semanas", True),
                (0, 12, "Ácido fólico", "desde antes y en el 1.er trimestre", False),
                (11, 14, "Tamizaje del 1.er trimestre", "ecografía y análisis", False),
                (14, 40, "Hierro y ácido fólico", "desde las 14 semanas", False)]),
  tabla=("Opciones de la pregunta", [("Zona rural", False), ("Nivel socioeconómico", False), ("Control tardío", True), ("Edad de 19 años", False)],
         [("¿Factor obstétrico principal?", ["Determinante social", "Determinante social", "Sí", "Suma riesgo, pero no es el principal"])]))

# GIN-260 · Clomifeno · CICLO (eje hormonal)
S("ciclo", "GIN-260", "infertilidad-embarazo-con-clomifeno-factor-ovulatorio",
  "Embarazo logrado con clomifeno: la causa era ovulatoria",
  "Infertilidad · factor ovulatorio", ESP,
  ("Factores de infertilidad", ["Ovulatorio, tubárico, uterino, cervical y masculino.",
                                "El clomifeno solo corrige la falta de ovulación."]),
  ("Mujer de 34 años con infertilidad de 2 años", ["Recibe citrato de clomifeno por vía oral.", "Tras varios ciclos logra gestar."]),
  ["Clomifeno (SERM): bloquea los receptores de estrógeno del hipotálamo → más GnRH → más FSH/LH → ovulación.",
   "Si funcionó, el problema era la anovulación (p. ej., ovario poliquístico).",
   "Letrozol es hoy la primera línea en ovario poliquístico; el factor tubárico necesita FIV."],
  "ASRM, infertilidad (2021); Speroff Endocrinología Ginecológica 9.ª ed.",
  d=dict(rotulo="Qué corrige el clomifeno", tag="ESTE CASO",
         img_titulo="Eje hipotálamo-hipófisis-ovario", img=D(lambda s, x, y: I.eje_hho(s, x, y), 300, 296),
         centro="Inducción de la ovulación", ans=3,
         pasos=[("Clomifeno", "bloquea el receptor de estrógeno"), ("Hipotálamo", "sube la GnRH"),
                ("Hipófisis", "más FSH y LH"), ("Ovario", "madura el folículo y ovula")],
         claves_titulo="Otros factores y su tratamiento",
         claves=[("Tubárico", ["Fecundación in vitro."], False), ("Uterino", ["Cirugía (miomas, pólipos, septos)."], False),
                 ("Cervical", ["Inseminación intrauterina."], False)]),
  tabla=("Opciones de la pregunta", [("Cervical", False), ("Ovulatorio", True), ("Uterino", False), ("Tubárico", False)],
         [("¿Lo corrige el clomifeno?", ["No", "Sí", "No", "No"])]))

# GIN-261 · Tamoxifeno y sangrado · RADIAL + franja
S("radial", "GIN-261", "tamoxifeno-sangrado-posmenopausico-ecografia-transvaginal",
  "Sangrado posmenopáusico en usuaria de tamoxifeno: primero ecografía transvaginal",
  "Sangrado posmenopáusico · endometrio y tamoxifeno", ESP,
  ("Sangrado posmenopáusico", ["Siempre se estudia: puede ser cáncer de endometrio.",
                               "El tamoxifeno estimula el endometrio: más pólipos, hiperplasia y cáncer."]),
  ("Mujer de 56 años con cáncer de mama RH (+)", ["Tamoxifeno desde hace 4 años.", "Sangrado uterino escaso e intermitente; examen normal."]),
  ["Primer paso: ecografía transvaginal para medir el endometrio.",
   "Endometrio ≤ 4 mm: bajo riesgo; > 4 mm o irregular: biopsia (o histeroscopía).",
   "Con tamoxifeno el endometrio puede verse grueso por cambios subendometriales: ante sangrado, se biopsia."],
  "ACOG n.º 734 (2018) y n.º 601 (tamoxifeno); NCCN.",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Sangrado + tamoxifeno",
         items=[("Ecografía transvaginal", ["Mide el endometrio: primer estudio"]),
                ("Resonancia magnética", ["Para estadificar un cáncer ya diagnosticado"]),
                ("Laparoscopía", ["Invasiva; no evalúa la cavidad uterina"]),
                ("Histerectomía profiláctica", ["Excesiva sin diagnóstico"])],
         ruta=["Tamoxifeno 4 años", "Sangrado posmenopáusico", "Eco TV: grosor", "Biopsia si > 4 mm"]),
  banda=B("Endometrio con tamoxifeno", D(lambda s, x, y: I.utero_frontal(s, x, y, "tamoxifeno"), 300, 240),
          ["El tamoxifeno actúa como estrógeno en el endometrio.", "Puede causar pólipos, hiperplasia y cáncer.",
           "La eco mide el grosor y guía la biopsia."]),
  tabla=("Opciones de la pregunta", [("Eco transvaginal", True), ("Resonancia", False), ("Laparoscopía", False), ("Histerectomía", False)],
         [("¿Primer paso?", ["Sí", "No", "No", "No"])]))

# GIN-262 · Signo de la T · COMPARADOR (foto real + dibujo)
S("comparador", "GIN-262", "gemelar-una-placenta-membrana-fina-signo-t-monocorial-biamniotica",
  "Signo de la T: gestación monocoriónica biamniótica",
  "Embarazo gemelar · corionicidad por ecografía", ESP,
  ("Corionicidad en gemelos", ["Se define mejor en el primer trimestre (11-14 semanas).",
                               "Lambda (λ): dos placentas, membrana gruesa. T: una placenta, membrana fina."]),
  ("Primigesta de 14 semanas, gemelar", ["Una sola placenta.", "Membrana fina que llega perpendicular a la placenta: signo de la T."]),
  ["Signo de la T = monocoriónica biamniótica: una placenta y dos sacos.",
   "Riesgos propios: transfusión feto-fetal, restricción selectiva, anemia-policitemia: eco cada 2 semanas desde las 16.",
   "Monoamniótica: no hay membrana entre los fetos (riesgo de enredo de cordones)."],
  "ISUOG, gemelares (2016); " + WILLIAMS + ".",
  d=dict(rotulo="Lambda frente a T", IH=250, tag="ESTE CASO",
         imgs=[dict(titulo="Bicoriónica (ecografía real)", archivo="gemelar_lambda.jpg",
                    marcas=[("flecha", 0.387, 0.614, 0.70, 0.12, "Tabique grueso\nentre dos sacos")],
                    pie="Dos sacos separados por tejido grueso (dos coriones): bicoriónica, signo lambda.",
                    credito="Eco: Nevit Dilmen · Wikimedia Commons · CC BY-SA 3.0 · recorte"),
               dict(titulo="Monocoriónica: signo de la T", on=True, ilu=lambda s, x, y: I.gemelar_t(s, x + 42, y, sc=0.96),
                    pie="Una placenta y una membrana fina que llega en ángulo recto: forma una «T».")],
         lectura_titulo="Cómo se clasifica",
         lectura=[("Bicoriónica biamniótica", ["Signo lambda; menor riesgo."], False),
                  ("Monocoriónica biamniótica", ["Signo de la T: este caso."], True),
                  ("Monocoriónica monoamniótica", ["Sin membrana: riesgo de enredo de cordones."], False)]),
  tabla=("Opciones de la pregunta", [("MC monoamniótica", False), ("BC biamniótica", False), ("MC biamniótica", True), ("BC monoamniótica", False)],
         [("Signo", ["Sin membrana", "Lambda", "T", "No existe"])]))

# GIN-263 · Fiebre en las primeras horas del puerperio · CRONOLOGÍA (días)
S("cronologia", "GIN-263", "puerpera-9-horas-fiebre-sin-foco-pirogenos-endogenos",
  "Fiebre a las 9 horas del parto sin foco: pirógenos endógenos",
  "Puerperio · fiebre puerperal", ESP,
  ("Fiebre en el puerperio", ["Cada causa aparece en un momento distinto después del parto.",
                              "En las primeras 24 h, sin foco, suele ser fisiológica."]),
  ("Puérpera de 9 horas, parto con episiotomía", ["T 38,2 °C, FC 96, PA 100/70.",
                                                   "Mamas, útero, loquios y episiorrafia normales; hemograma y orina normales."]),
  ["Fiebre < 24 h posparto sin foco y con examen normal: pirógenos endógenos (trauma del parto, deshidratación).",
   "Hidratar, analgesia y reevaluar; cede en 12-24 h.",
   "Fiebre puerperal verdadera: ≥ 38 °C en 2 días entre el 2.º y 10.º día."],
  WILLIAMS + "; " + MINSA + ", guía de atención del puerperio.",
  d=dict(rotulo="Qué causa la fiebre según el día", tag="ESTE CASO",
         ilu_titulo="Examen de la puérpera",
         ilu=ILU(D(lambda s, x, y: I.cuerpo(s, x + 100, y, marcas=[(1, 96, 110), (2, 144, 110), (3, 120, 214), (4, 120, 262)], sc=0.6), 330, 270)),
         ilu_pie="1-2 mamas blandas, 3 útero involucionado, 4 episiorrafia sin signos: sin foco.",
         claves=[("Pirógenos endógenos", ["Primeras 24 h, sin foco, examen normal: este caso."], True),
                 ("Endometritis", ["Día 2-10: útero doloroso y loquios fétidos."], False),
                 ("Infección de la episiorrafia", ["Día 3-7: eritema, dolor y secreción."], False),
                 ("Mastitis", ["Semanas 2-4: mama roja y dolorosa."], False)],
         eje_titulo="Días después del parto", eje=(0, 28), paso=7, marca=0.4, unidad="d", eje_nombre="días posparto",
         hitos=[(0, 1, "Pirógenos endógenos", "primeras 24 h", True), (2, 10, "Endometritis", "más frecuente tras cesárea", False),
                (3, 7, "Infección de herida", "episiorrafia o cesárea", False), (10, 28, "Mastitis", "2.ª a 4.ª semana", False)]),
  tabla=("Opciones de la pregunta", [("Infección de episiorrafia", False), ("Pirógenos endógenos", True), ("Mastitis", False), ("Endometritis", False)],
         [("¿Encaja con 9 h y examen normal?", ["No: herida normal", "Sí", "No: mamas normales", "No: útero y loquios normales"])]))

# GIN-264 · RPM 29 semanas · SEMÁFORO
S("semaforo", "GIN-264", "rpm-pretermino-29-semanas-sin-infeccion-manejo-expectante",
  "RPM pretérmino a las 29 semanas sin infección: manejo expectante",
  "Rotura prematura de membranas pretérmino", ESP,
  ("RPM pretérmino", ["La edad gestacional y la infección deciden: esperar o terminar.",
                      "Antes de las 34 semanas, sin infección ni compromiso fetal, se gana tiempo."]),
  ("Secundigesta de 29 semanas", ["Pérdida de líquido claro desde hace 3 días.", "Afebril, útero indoloro, sin dinámica, LCF 150."]),
  ["RPM < 34 semanas sin corioamnionitis ni sufrimiento fetal: manejo expectante hospitalizado.",
   "Antibiótico (prolonga la latencia), corticoides y sulfato de magnesio si < 32 semanas.",
   "Terminar si aparece infección, desprendimiento, compromiso fetal o al llegar a las 34 semanas."],
  ACOG + " n.º 217 (2020); " + MINSA + ".",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="Membranas rotas",
         ilu=ILU(D(lambda s, x, y: I.utero_gestante(s, x + 2, y, "rpm", sc=0.88), 270, 300)),
         ilu_pie="Líquido claro que sale por el cuello; sin signos de infección.",
         check_titulo="¿Hay motivo para terminar?",
         check=[("Sin fiebre ni taquicardia materna o fetal", True), ("Útero indoloro, líquido claro", True),
                ("Sin trabajo de parto", True), ("29 semanas: prematuro extremo si nace", True)],
         ans=0, tag="ESTE CASO",
         luces=[("< 34 semanas sin infección", "Expectante", ["Antibiótico, corticoides, magnesio si < 32 sem; vigilar."]),
                ("≥ 34 semanas", "Terminar la gestación", ["Inducción si no hay contraindicación."]),
                ("Corioamnionitis, DPP o compromiso fetal", "Terminar ya", ["Con antibiótico; vía según condiciones."])]),
  tabla=("Opciones de la pregunta", [("Cesárea de emergencia", False), ("Cesárea a las 35 sem", False), ("Inducir", False), ("Expectante", True)],
         [("Problema", ["Sin indicación", "Se termina a las 34", "Prematurez innecesaria", "Ninguno"])]))

# GIN-265 · Proteinuria transitoria · ÁRBOL + franja tira reactiva
S("arbol", "GIN-265", "gestante-febril-proteinuria-1-cruz-transitoria-repetir-examen",
  "Proteinuria de 1+ en gestante con fiebre: probablemente transitoria, repetir",
  "Embarazo · interpretación de la proteinuria", ESP,
  ("Proteinuria en la gestante", ["La fiebre, el ejercicio o la orina concentrada dan proteinuria transitoria.",
                                  "Preocupa si es persistente o se acompaña de hipertensión después de las 20 semanas."]),
  ("Gestante de 24 años con infección respiratoria", ["T 38,5 °C, PA 110/70, sin edemas.", "Tira reactiva: proteínas 1+, sedimento normal."]),
  ["Proteinuria 1+ aislada con fiebre y PA normal: explicar que suele ser transitoria y repetir el examen al mejorar.",
   "Si persiste: cuantificar (proteína/creatinina en muestra aislada o orina de 24 h).",
   "No restricción proteica, reposo ni inmunosupresores sin diagnóstico."],
  "KDIGO; ACOG n.º 222 (hipertensión en el embarazo).",
  arbol=Q("¿Hay hipertensión, edemas o sedimento anormal?", [
      L("Sí", "Estudiar preeclampsia o nefropatía", ["Cociente proteína/creatinina", "PA, laboratorio"]),
      Q("¿Persiste la proteinuria al repetir sin fiebre?", [
          L("Sí", "Cuantificar y estudiar", ["Proteína/creatinina u orina de 24 h"]),
          L("No", "PROTEINURIA TRANSITORIA", ["Tranquilizar y explicar", "Control prenatal habitual"], path=True)], edge="No", path=True)], path=True),
  banda=B("La tira reactiva", D(lambda s, x, y: I.tira_orina(s, x, y, [("Leucocitos", "#fef9c3", "neg", False), ("Nitritos", "#fef9c3", "neg", False),
                                                                        ("Proteínas", "#a3e635", "1+", True), ("Sangre", "#fef3c7", "neg", False),
                                                                        ("Glucosa", "#bfdbfe", "neg", False)]), 360, 90),
          ["Proteínas 1+ y el resto negativo.", "La fiebre puede hacer que la tira marque proteínas.", "Repetir cuando esté afebril."], ans=0),
  tabla=("Opciones de la pregunta", [("Repetir y explicar", True), ("Restricción proteica y reposo", False), ("Inmunosupresor", False),
                                     ("Hospitalizar por nefrótico", False)],
         [("¿Adecuada?", ["Sí", "No: sin base", "No: no hay diagnóstico", "No: no hay síndrome nefrótico"])]))

# GIN-266 · PEG con oligohidramnios a término · ÁRBOL CON IMAGEN
S("arbol_imagen", "GIN-266", "feto-pequeno-percentil-8-oligohidramnios-39-semanas-induccion",
  "Feto pequeño con oligohidramnios a las 39 semanas: inducir el parto",
  "Restricción del crecimiento · feto pequeño a término", ESP,
  ("Feto pequeño para la edad gestacional", ["Peso fetal < p10. El Doppler y el líquido amniótico dicen si está comprometido.",
                                             "A término, un feto pequeño con oligohidramnios no gana nada quedándose."]),
  ("Primigesta de 39 semanas", ["AU 30 cm; peso fetal en p8; líquido amniótico disminuido.",
                                "Doppler umbilical y cerebral media normales."]),
  ["Feto < p10 + oligohidramnios a término (≥ 37 semanas): terminar la gestación.",
   "Con Doppler normal el feto tolera el trabajo de parto: inducción (vía vaginal).",
   "Doppler umbilical con flujo ausente o reverso: cesárea."],
  "ACOG n.º 227 (restricción del crecimiento, 2021); " + WILLIAMS + ".",
  d=dict(rotulo="¿Seguir o terminar?", tag="ESTE CASO",
         pregunta="¿Feto < p10 con oligohidramnios y ya a término?",
         ramas=[("No (pretérmino, líquido normal)", "Vigilancia con Doppler", ["Crecimiento cada 2-3 semanas", "Terminar a las 37-39 según el caso"]),
                ("Sí: 39 semanas (este caso)", "Terminar la gestación: inducción",
                 ["Doppler normal: tolera el parto; se intenta la vía vaginal con monitoreo."])],
         ilu=lambda s, x, y: I.curva_percentil(s, x + 90, y, (0.94, 0.28), ylab="Peso fetal", ticks=("24", "28", "32", "36", "40"),
                                                marca="p8 a las 39 sem", sc=1.1),
         IW=560, IH=258,
         ilu_pie="El peso fetal está debajo del percentil 10: pequeño para la edad gestacional.",
         luego_titulo="Cómo terminar",
         luego=[("Doppler normal", ["Inducción del parto: este caso."], True), ("Flujo umbilical ausente o reverso", ["Cesárea."], False),
                ("Durante el parto", ["Monitoreo fetal continuo."], False)]),
  tabla=("Opciones de la pregunta", [("Inducción", True), ("Esperar a 41 sem", False), ("Cesárea inmediata", False), ("Eco semanal", False)],
         [("Problema", ["Ninguno", "Riesgo fetal", "Sin indicación de cesárea", "Prolonga sin beneficio"])]))
