"""Bloque ENAM 2026 · Cirugía (parte 2)."""
from c26 import S, D, P, B, ILU, Q, L, SCHWARTZ, SABISTON, ATLS
import ilu7 as I

O = I.ORANGE
ESP = "CIRUGÍA ENAM"

# CIR-137 · Cierre primario · ÁRBOL + franja
S("arbol", "CIR-137", "mordedura-perro-propio-herida-limpia-cierre-primario",
  "Mordedura de perro en el muslo, limpia y reciente: cierre primario",
  "Heridas · tipos de cierre", ESP,
  ("Cómo se cierra una herida", ["Depende del tiempo, la contaminación, el sitio y el riesgo de infección.",
                                 "Limpia y reciente: primario. Contaminada o de mano: abierta o diferida."]),
  ("Mujer de 35 años, mordida por su perro", ["Hace 2 h; herida de 6 cm en el muslo, bordes netos.",
                                              "Sin necrosis ni cuerpos extraños; ya irrigada y limpia."]),
  ["Mordedura < 6-8 h, bien irrigada, de bordes netos y fuera de la mano: cierre primario.",
   "Profilaxis con amoxicilina-clavulánico (cubre Pasteurella multocida).",
   "Revisar vacuna antitetánica y el riesgo de rabia (perro propio: observarlo 10 días)."],
  "IDSA, infecciones de piel y partes blandas; MINSA, norma de rabia; " + SCHWARTZ + ".",
  arbol=Q("¿Herida < 6-8 h, irrigada, de bordes netos y fuera de la mano?", [
      L("Sí", "CIERRE PRIMARIO", ["Sutura tras irrigar y limpiar", "Amoxicilina-clavulánico profiláctico"], path=True),
      Q("¿Muy contaminada, necrótica o en la mano?", [
          L("Sí", "Dejar abierta", ["Segunda intención o cierre terciario a los 3-5 días"]),
          L("No, solo tardía", "Valorar cierre diferido", ["Cara: se puede suturar hasta 24 h"])], edge="No")], path=True),
  banda=B("Tres formas de cerrar", D(lambda s, x, y: I.herida_cierre(s, x, y, caso=0, sc=0.9), 414, 154),
          ["Primario (este caso): se sutura en las primeras horas si la herida quedó limpia.",
           "Segunda intención: la herida queda abierta y granula sola.",
           "Terciario: se deja abierta unos días y luego se sutura si no se infectó."], ans=0),
  tabla=("Opciones de la pregunta", [("Primario", True), ("Secundario", False), ("Terciario", False), ("Desbridamiento", False)],
         [("¿Cuándo?", ["Limpia y reciente: este caso", "Muy contaminada o infectada", "Dudosa: se espera 3-5 días",
                        "Si hay tejido necrótico (no aquí)"])]))

# CIR-138 · Cáncer de colon localizado · RADIAL + franja
_hemi = I.P("M28 128 H134 V316 H28 Z", "none", O, 2.5, 'stroke-dasharray="7 4"') + I.E(52, 214, 11, 16, "#7c2d12", "#431407", 2)
S("radial", "CIR-138", "adenocarcinoma-colon-ascendente-sin-metastasis-hemicolectomia",
  "Cáncer de colon ascendente sin metástasis: resección oncológica",
  "Cáncer colorrectal · tratamiento del cáncer de colon", ESP,
  ("Cáncer de colon localizado", ["Si no hay metástasis, la cirugía con sus ganglios es la que cura.",
                                  "La quimioterapia se decide después, con el estadio de la pieza (pTNM)."]),
  ("Varón de 63 años con anemia y cambio del ritmo", ["Colonoscopía: adenocarcinoma de colon ascendente.",
                                                      "TC: sin ganglios ni metástasis a distancia."]),
  ["Colon ascendente sin metástasis: hemicolectomía derecha con linfadenectomía (≥ 12 ganglios).",
   "Quimioterapia adyuvante (FOLFOX o CAPOX) si el estadio final es III o II de alto riesgo.",
   "La radioterapia pélvica es del cáncer de recto, no del de colon."],
  "NCCN, cáncer de colon (2024); AJCC 8.ª ed.",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Colon ascendente sin metástasis",
         items=[("Resección oncológica", ["Hemicolectomía derecha con ≥ 12 ganglios: intención curativa"]),
                ("Inmunoterapia", ["Solo en enfermedad metastásica con inestabilidad de microsatélites"]),
                ("Radioterapia pélvica", ["Se usa en el cáncer de recto, no en el de colon"]),
                ("Quimioterapia inmediata", ["Va después de la cirugía y según el estadio"])],
         ruta=["Anemia y cambio del ritmo", "Colonoscopía y biopsia", "TC sin metástasis", "Hemicolectomía derecha"]),
  banda=B("Qué se reseca", D(lambda s, x, y: I.abdomen(s, x, y, on={"colon_asc", "ciego", "ileon"}, extra=_hemi,
                                                         marcas=[(1, 52, 214)]), 300, 330),
          ["Tumor en el colon ascendente.", "Línea naranja: se saca el íleon terminal, el ciego, el colon ascendente y la "
                                            "parte inicial del transverso con su mesenterio y ganglios.",
           "Se une el íleon con el colon transverso (anastomosis ileocólica)."], ans=0),
  tabla=("Opciones de la pregunta", [("Resección oncológica", True), ("Inmunoterapia", False), ("Radioterapia pélvica", False),
                                     ("QT adyuvante inmediata", False)],
         [("¿Primera conducta aquí?", ["Sí", "No", "No", "No: va después de operar"])]))

# CIR-139 · Lesión inhalatoria · ÁRBOL CON IMAGEN
S("arbol_imagen", "CIR-139", "quemadura-incendio-cerrado-estridor-hollin-intubacion-precoz",
  "Quemado con lesión inhalatoria: primero asegurar la vía aérea",
  "Quemaduras · lesión por inhalación", ESP,
  ("Lesión inhalatoria", ["Incendio en lugar cerrado: el calor y el humo edematizan la laringe en pocas horas.",
                          "Si hay signos de obstrucción, se intuba antes de que el edema lo impida."]),
  ("Mujer de 40 años rescatada de un incendio", ["Quemaduras del 35 %; PA 80/50, FR 30, SatO₂ 86 %.",
                                                 "Estridor, quemaduras faciales y hollín en la orofaringe."]),
  ["Estridor, ronquera, hollín, quemadura facial o de cuello en incendio cerrado: intubación precoz.",
   "Luego: oxígeno al 100 % (monóxido de carbono), reposición con Parkland y analgesia.",
   "Esperar puede cerrar la vía aérea y obligar a una cricotiroidotomía."],
  ATLS + "; American Burn Association.",
  d=dict(rotulo="Primero la vía aérea", tag="ESTE CASO",
         pregunta="¿Hay signos de que la vía aérea se está cerrando por la inhalación?",
         ramas=[("No", "Oxígeno al 100 % con reservorio", ["Vigilar de cerca; reevaluar la vía aérea.", "Luego líquidos y analgesia."]),
                ("Sí: estridor y hollín (este caso)", "Intubación orotraqueal precoz",
                 ["Con el tubo más grueso posible, antes de que el edema progrese."])],
         ilu=lambda s, x, y: I.via_aerea_quemada(s, x + 90, y, sc=1.1), IW=560, IH=276,
         ilu_pie="La mucosa de la laringe se hincha en horas; el tubo (azul) mantiene abierta la vía aérea.",
         luego_titulo="Después de asegurar la vía aérea",
         luego=[("Oxígeno al 100 %", ["Desplaza el monóxido de carbono."], False),
                ("Líquidos: Parkland", ["4 mL × kg × % SCQ en 24 h."], False),
                ("Analgesia y referencia", ["A unidad de quemados."], False)]),
  tabla=("Opciones de la pregunta", [("O₂ con reservorio", False), ("Intubación precoz", True), ("Opioide EV", False),
                                     ("Parkland", False)],
         [("¿Es lo primero?", ["No: no protege la vía aérea", "Sí: A del ABCDE", "No", "No: va después de la A"])]))

# CIR-140 · Alvarado · PUNTAJE + franja
_migra = (I.flecha(150, 118, 84, 262, O, 3, "6 4") + I.C(84, 268, 7, O, "#7c2d12", 2)
          + I.t(160, 112, "epigastrio", "#7c2d12", 10, "start") + I.t(96, 290, "McBurney", "#7c2d12", 10, "start"))
S("puntaje", "CIR-140", "escala-alvarado-8-puntos-apendicitis-probable",
  "Escala de Alvarado: este caso suma 8 puntos",
  "Apendicitis aguda · escala de Alvarado", ESP,
  ("Escala de Alvarado", ["Ocho datos de clínica y laboratorio; máximo 10 puntos.",
                          "Dos datos valen 2: dolor en FID y leucocitosis > 10 000."]),
  ("Mujer de 62 años, 12 h de dolor que migró a FID", ["Anorexia, 2 vómitos, T 38,5 °C; McBurney y Blumberg (+).",
                                                       "Leucocitos 9 890 y neutrófilos 77 %."]),
  ["Leucocitos 9 890 no llegan a 10 000: no suman; los neutrófilos 77 % sí suman 1.",
   "7-8 puntos = apendicitis probable: evaluación quirúrgica.",
   "Mnemotecnia MANTRELS: Migración, Anorexia, Náuseas, Tenderness (dolor FID), Rebote, Elevación de T°, Leucocitosis, Shift (desviación)."],
  "Alvarado A. Ann Emerg Med 1986; WSES, guía de apendicitis (2020).",
  d=dict(rotulo="Punto por punto", escala="Escala de Alvarado", total=8, max=10,
         interpreta="Apendicitis probable: evaluación por cirugía",
         items=[("Dolor que migra a FID", 1, True), ("Anorexia", 1, True), ("Náuseas o vómitos", 1, True),
                ("Dolor en FID (McBurney)", 2, True), ("Rebote (Blumberg)", 1, True), ("Temperatura > 37,3 °C", 1, True),
                ("Leucocitos > 10 000 (tiene 9 890)", 2, False), ("Neutrófilos > 75 % (tiene 77 %)", 1, True)],
         bandas=[("0-4", "Poco probable", "Observar o alta con control.", False),
                 ("5-6", "Posible", "Observación e imagen (eco o TC).", False),
                 ("7-8", "Probable", "Evaluación por cirugía.", True),
                 ("9-10", "Muy probable", "Apendicectomía.", False)]),
  banda=B("Dónde está el dolor", D(lambda s, x, y: I.abdomen(s, x, y, on={"apendice", "ciego"}, extra=_migra), 300, 330),
          ["El dolor empezó en el epigastrio y migró a la fosa ilíaca derecha (1 punto).",
           "Punto de McBurney doloroso (2 puntos) y rebote (1 punto).",
           "Con 9 890 leucocitos ese ítem no suma: por eso son 8 y no 10."]),
  tabla=("Opciones de la pregunta", [("8", True), ("6", False), ("9", False), ("7", False)],
         [("Por qué", ["Suma correcta", "Olvida McBurney o rebote", "Cuenta leucocitos como 1", "Omite un ítem"])]))

# CIR-141 · Hernia incisional estrangulada · CRITERIOS
S("criterios", "CIR-141", "hernia-incisional-estrangulada-obstruccion-laparotomia-urgente",
  "Hernia incisional estrangulada: laparotomía de urgencia",
  "Hernias de la pared abdominal · estrangulación", ESP,
  ("Hernia estrangulada", ["El contenido queda atrapado y se corta su irrigación: se necrosa en horas.",
                           "Irreductible + dolor intenso + piel roja u obstrucción = operar ya."]),
  ("Mujer de 50 años con laparotomía previa", ["18 h de dolor constante, vómitos, sin gases ni heces.",
                                               "Masa tensa, roja e irreductible sobre la cicatriz; RHA abolidos."]),
  ["Hernia irreductible dolorosa con eritema y obstrucción: estrangulada hasta demostrar lo contrario.",
   "Reanimar, sonda nasogástrica y antibiótico mientras se prepara la laparotomía urgente.",
   "Esperar (electiva, solo SNG o más imágenes) aumenta la necrosis y la sepsis."],
  SCHWARTZ + "; guía de la European Hernia Society.",
  d=dict(rotulo="¿Está estrangulada?", tag="ESTE CASO", lista_titulo="Signos de estrangulación",
         items=[("Masa irreductible y tensa", True, "Sobre la cicatriz mediana"),
                ("Dolor intenso y constante que empeora", True, "18 h, peor en la última hora"),
                ("Piel roja sobre la hernia", True, "Enrojecimiento"),
                ("Obstrucción intestinal", True, "Vómitos, sin gases ni heces, RHA abolidos"),
                ("Fiebre, taquicardia o leucocitosis", None, "No se describen")],
         umbral="irreductible + dolor o eritema u obstrucción",
         veredicto="Estrangulada: estabilizar y laparotomía exploradora de urgencia",
         img_titulo="Hernia del caso", img=D(lambda s, x, y: I.hernia_incisional(s, x, y, sc=0.95), 304, 219),
         img_pie="Recuadro: el asa queda atrapada en el cuello estrecho del defecto.",
         claves_titulo="Por qué no las otras",
         claves=[("Laparoscopía electiva", ["Es para hernias no complicadas."], False),
                 ("Solo SNG y antibióticos", ["No libera el asa atrapada."], False),
                 ("Rx de abdomen primero", ["No cambia la conducta: retrasa la cirugía."], False)]),
  tabla=("Opciones de la pregunta", [("Estabilizar + laparotomía", True), ("Laparoscopía electiva", False),
                                     ("ATB + SNG", False), ("Rx de abdomen", False)],
         [("¿Reduce la necrosis?", ["Sí", "No: la retrasa", "No: solo acompaña", "No"])]))

# CIR-142 · Cáncer gástrico IV · BALANZA + franja
_mets = (I.E(200, 90, 40, 30, "#7c2d12", "#431407", 2, extra='opacity="0.85"')
         + "".join(I.C(cx, cy, r, "#57534e", "#1c1917", 1.2) for cx, cy, r in [(60, 60, 8), (96, 76, 6), (130, 56, 7), (80, 92, 5), (150, 80, 6)]))
S("balanza", "CIR-142", "cancer-gastrico-estadio-iv-metastasis-hepaticas-quimioterapia",
  "Cáncer gástrico con metástasis hepáticas: quimioterapia sistémica",
  "Cáncer gástrico · enfermedad metastásica", ESP,
  ("Cáncer gástrico estadio IV", ["Con metástasis a distancia la cirugía ya no cura.",
                                  "El objetivo pasa a ser vivir más y con menos síntomas."]),
  ("Varón de 70 años, adenocarcinoma cuerpo-antral", ["Metástasis hepáticas múltiples; baja de peso y anorexia.",
                                                      "Estable, sin sangrado ni obstrucción; cirugía descarta resecar."]),
  ["Estadio IV sin complicaciones: quimioterapia sistémica paliativa (fluoropirimidina + platino).",
   "Añadir trastuzumab si HER2 (+); inmunoterapia combinada si PD-L1 alto.",
   "Cirugía o stent solo para complicaciones: sangrado u obstrucción."],
  "NCCN, cáncer gástrico (2024); ESMO (2022).",
  d=dict(rotulo="¿Qué pesa más en este paciente?", gana="izq", tag="ESTE CASO",
         pregunta="Estadio IV por metástasis hepáticas",
         izq=dict(titulo="Quimioterapia sistémica", peso="elige",
                  items=["Actúa en el estómago y en el hígado a la vez", "Prolonga la supervivencia y alivia síntomas",
                         "Paciente estable y sin complicaciones"]),
         der=dict(titulo="Cirugía (gastrectomía o resección)", peso="no",
                  items=["No cura: las metástasis quedan", "Mucha morbilidad sin ganar supervivencia",
                         "Se reserva para sangrado u obstrucción"]),
         veredicto=("Quimioterapia sistémica paliativa de primera línea",
                    ["Con apoyo nutricional y control de síntomas; la cirugía queda para las complicaciones."])),
  banda=B("Extensión de la enfermedad", D(lambda s, x, y: I.abdomen(s, x, y, extra=_mets, marcas=[(1, 200, 90), (2, 96, 44)]), 300, 330),
          ["Tumor en el estómago (cuerpo y antro).", "Metástasis múltiples en el hígado: estadio IV.",
           "Operar el estómago no elimina las lesiones del hígado."]),
  tabla=("Opciones de la pregunta", [("Quimioterapia sistémica", True), ("Gastrectomía total", False),
                                     ("Inmunoterapia sola", False), ("Resección + bypass", False)],
         [("¿Cuándo?", ["Este caso", "No en estadio IV", "No como monoterapia inicial", "Solo si hay obstrucción"])]))

# CIR-143 · Quemadura eléctrica · COMPARADOR (dibujos)
_ruta = (I.P("M37 252 L56 170 L84 112 L120 150 L140 250 L146 360 L142 426", "none", "#facc15", 5, 'stroke-dasharray="8 5"')
         + I.num(37, 252, "E", I.RED, 11) + I.num(142, 426, "S", I.RED, 11))
S("comparador", "CIR-143", "quemadura-electrica-alto-voltaje-necrosis-muscular-perioseo",
  "Quemadura eléctrica: el daño mayor está en el músculo pegado al hueso",
  "Quemaduras · lesión eléctrica", ESP,
  ("Quemadura eléctrica de alto voltaje", ["La piel de entrada y salida puede verse casi normal (lesión en iceberg).",
                                           "El hueso resiste más la corriente, se calienta y cocina el músculo que lo rodea."]),
  ("Técnico electricista de 34 años", ["Alto voltaje: entrada en la mano derecha y salida en el pie izquierdo.",
                                       "Piel con lesiones superficiales en ambos sitios."]),
  ["El músculo profundo en contacto con el hueso sufre la mayor necrosis a lo largo del trayecto.",
   "Riesgos: síndrome compartimental, rabdomiólisis (mioglobinuria → falla renal) y arritmias.",
   "Por eso se reponen más líquidos que en una quemadura térmica y se busca diuresis de 1-1,5 mL/kg/h."],
  ATLS + "; American Burn Association.",
  d=dict(rotulo="Por fuera y por dentro", IH=340, tag="ESTE CASO",
         imgs=[dict(titulo="Trayecto de la corriente",
                    ilu=lambda s, x, y: I.cuerpo(s, x + 131, y + 4, {"mano_d": "#fde68a", "pie_i": "#fde68a"}, extra=_ruta, sc=0.75),
                    pie="E = entrada (mano derecha), S = salida (pie izquierdo). La corriente atraviesa brazo, tórax y pierna."),
               dict(titulo="Corte a lo largo del trayecto", on=True,
                    ilu=lambda s, x, y: I.piel_capas(s, x + 10, y + 30, "electrica", sc=1.2),
                    pie="El hueso se calienta y el músculo que lo toca se necrosa, aunque la piel se vea casi intacta.")],
         lectura_titulo="Consecuencias que hay que buscar",
         lectura=[("Rabdomiólisis", ["CPK alta y mioglobinuria: riesgo de falla renal; más líquidos."], False),
                  ("Síndrome compartimental", ["Dolor y tensión del miembro: fasciotomía."], False),
                  ("Arritmias", ["ECG y monitoreo cardiaco."], False)]),
  tabla=("Opciones de la pregunta", [("Hueso cortical", False), ("Músculo junto al hueso", True), ("Piel de la mano", False),
                                     ("Grasa subcutánea", False)],
         [("¿Mayor daño profundo?", ["No: se calienta pero es el que transmite el calor", "Sí", "No: lesión superficial",
                                     "No"])]))

# CIR-144 · Neumotórax abierto · CICLO (válvula de 3 lados)
S("ciclo", "CIR-144", "neumotorax-abierto-aposito-oclusivo-tres-lados-valvula",
  "Neumotórax abierto: apósito oclusivo fijado en tres lados",
  "Trauma de tórax · neumotórax abierto", ESP,
  ("Neumotórax abierto (herida soplante)", ["El aire entra por la herida en cada inspiración y colapsa el pulmón.",
                                            "Con pocos recursos se improvisa una válvula de un solo sentido."]),
  ("Varón de 25 años con puñalada en el hemitórax derecho", ["Entrada y salida de aire por la herida; SatO₂ 88 %, FR 32.",
                                                             "Sin tubos de tórax ni ventilador; hay que referir."]),
  ["Apósito cuadrado fijado en tres lados: sella al inspirar y deja salir el aire al espirar.",
   "Sellar los cuatro lados puede convertirlo en un neumotórax a tensión.",
   "Oxígeno, referencia urgente y tubo de tórax (en otro sitio, no por la herida) en el hospital."],
  ATLS + ".",
  d=dict(rotulo="Cómo funciona el parche de tres lados", tag="ESTE CASO",
         img_titulo="Parche en la herida",
         img=D(lambda s, x, y: I.torax_valvula(s, x, y), 450, 210),
         img_pie="Cinta en tres lados (naranja); el cuarto lado queda libre.",
         centro="Válvula de un solo sentido",
         pasos=[("Inspira", "el tórax aspira aire"), ("El parche se pega", "sella la herida: no entra aire"),
                ("Espira", "sube la presión en la pleura"), ("Sale el aire", "por el lado libre del parche")],
         ans=1,
         claves_titulo="Lo que no se debe hacer",
         claves=[("Sellar los 4 lados", ["El aire no sale: neumotórax a tensión."], False),
                 ("Gasa suelta o nada", ["Sigue entrando aire."], False),
                 ("Lo correcto", ["O₂ + parche de 3 lados + referencia urgente."], True)]),
  tabla=("Opciones de la pregunta", [("O₂ sin tocar la herida", False), ("AMBU + sellar 4 lados", False),
                                     ("O₂ + parche de 3 lados", True), ("AMBU + gasas sueltas", False)],
         [("Problema", ["Sigue entrando aire", "Riesgo de tensión", "Ninguno", "No corrige la entrada de aire"])]))

# CIR-145 · Úlcera perforada sellada · BALANZA + franja foto
S("balanza", "CIR-145", "ulcera-perforada-sellada-anciana-alto-riesgo-manejo-conservador",
  "Úlcera perforada sellada en paciente de alto riesgo: manejo no operatorio",
  "Úlcera péptica · perforación", ESP,
  ("Úlcera péptica perforada", ["Lo habitual es operar (parche de epiplón).",
                                "Si la perforación ya se selló y no hay peritonitis, se puede manejar sin cirugía (Taylor)."]),
  ("Mujer de 88 años con EPOC con O₂ e insuficiencia cardiaca", ["Toma AINE; 12 h de dolor abdominal intenso, sin peritonitis.",
                                                                 "TC: neumoperitoneo escaso, sin colección."]),
  ["Perforación sellada (poco aire, sin colección, sin peritonitis) + riesgo quirúrgico alto: manejo conservador.",
   "Ayuno, sonda nasogástrica, IBP EV y antibiótico; vigilar de cerca.",
   "Si empeora en 12-24 h o aparece peritonitis: cirugía."],
  "WSES, guía de úlcera péptica perforada (2020); " + SCHWARTZ + ".",
  d=dict(rotulo="Cirugía o manejo conservador en esta paciente", gana="izq", tag="ESTE CASO",
         pregunta="Perforación sellada en paciente frágil",
         izq=dict(titulo="Manejo conservador (Taylor)", peso="sí",
                  items=["Poco aire libre y sin colección", "Sin signos de peritonitis",
                         "Riesgo quirúrgico altísimo: 88 años, EPOC con O₂, IC"]),
         der=dict(titulo="Cirugía (parche de epiplón)", peso="si falla",
                  items=["Estándar si hay peritonitis o colección", "Mortalidad muy alta en esta paciente",
                         "Se indica si empeora en 12-24 h"]),
         veredicto=("Sonda nasogástrica, IBP, antibiótico y vigilancia estrecha",
                    ["Suspender el AINE y buscar H. pylori; si aparece peritonitis, operar."])),
  banda=B("Neumoperitoneo en Rx (imagen real de referencia)",
          P("neumoperitoneo.jpg", 380, 318, [("flecha", 0.36, 0.43, 0.30, 0.12, "Aire libre bajo\nel diafragma")],
            "Rx: Bill Rhodes · Wikimedia Commons · CC BY 2.0 · recorte"),
          ["Aire libre bajo el diafragma derecho: hay una víscera hueca perforada.",
           "En este caso la TC mostró muy poco aire y ninguna colección: la perforación se selló.",
           "Sin peritonitis, se puede intentar el manejo no operatorio."]),
  tabla=("Opciones de la pregunta", [("Gastroyeyunostomía", False), ("ATB + IBP + SNG", True), ("Observación sin tratamiento", False),
                                     ("Gastrectomía total", False)],
         [("¿Adecuada?", ["No", "Sí", "No: necesita tratamiento", "No: excesiva y letal aquí"])]))

# CIR-146 · Shock hemorrágico clase III · TERMÓMETRO + franja
S("termometro", "CIR-146", "shock-hemorragico-clase-3-trauma-esplenico-transfusion",
  "Shock hemorrágico clase III por trauma de bazo: cristaloides y sangre",
  "Trauma · shock hemorrágico", ESP,
  ("Clasificación del shock hemorrágico (ATLS)", ["Se estima cuánta sangre perdió por la FC, la PA, la diuresis y la conciencia.",
                                                  "Desde la clase III ya hace falta transfundir."]),
  ("Varón de 32 años, caída de moto", ["FC 130, PA 70/50, FR 26, diuresis 15 mL/h, llenado > 2 s.",
                                       "Dolor y defensa en hipocondrio izquierdo."]),
  ["Hipotensión + FC > 120 + oliguria = clase III (pérdida 31-40 %): cristaloides y concentrado de hematíes.",
   "No reponer solo con cristaloides hasta normalizar la PA: diluye y empeora la coagulación.",
   "Dolor en hipocondrio izquierdo tras trauma: pensar en bazo; si sigue inestable, laparotomía."],
  ATLS + ".",
  d=dict(rotulo="¿Qué clase de shock?",
         niveles=[("Clase I", "< 15 %", ["FC y PA normales"]), ("Clase II", "15-30 %", ["Taquicardia, PA normal"]),
                  ("Clase III", "31-40 %", ["FC > 120, PA baja,", "diuresis 5-15 mL/h"]),
                  ("Clase IV", "> 40 %", ["FC > 140, PA muy baja,", "sin diuresis"])],
         caso_nivel=2, ruta_titulo="Qué se hace en la clase III", paso_label="ESTE CASO",
         pasos=[(1, "Cristaloides balanceados tibios", ["1 L inicial, sin excederse"], False),
                (2, "Concentrado de hematíes", ["Ya se necesita sangre"], True),
                (3, "Controlar el sangrado", ["Bazo: laparotomía si sigue inestable"], False)]),
  banda=B("Fuente del sangrado", D(lambda s, x, y: I.abdomen(s, x, y, on={"bazo"}, marcas=[(1, 266, 78)]), 300, 330),
          ["Dolor y defensa en el hipocondrio izquierdo: lesión del bazo.", "No hay sangrado externo: la sangre está en el abdomen.",
           "La ecografía FAST confirma líquido libre."], ans=0),
  tabla=("Opciones de la pregunta", [("II + cristaloides", False), ("I + dextrosa", False), ("IV + coloides", False),
                                     ("III + sangre", True)],
         [("Error", ["Hay hipotensión y oliguria: es III", "La dextrosa no expande", "No es IV; los coloides no se usan", "Ninguno"])]))
