"""Entrega 2 · tanda 16 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from esc28 import HTA_EMB, ITU

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"

# CB-044 · Estrés agudo: noradrenalina y adrenalina · TARJETAS
S("tarjetas", "CB-044", "Tras una discusión aparecen taquicardia y presión alta: reacción simpática de lucha o huida mediada por noradrenalina y adrenalina",
  "Fisiología · sistema nervioso autónomo",
  ("Reacción simpática al estrés", ["Los nervios simpáticos liberan noradrenalina y la médula suprarrenal libera adrenalina.",
                                     "Suben la frecuencia cardíaca, la fuerza del corazón y la presión (receptores β1 y α1)."]),
  ("Varón de 60 años", ["Discusión familiar.", "Taquicardia y presión arterial elevada."]),
  ["El cortisol (eje hipotálamo-hipófisis-suprarrenal) se suma en horas.",
   "La acetilcolina es del parasimpático (baja la FC).",
   "En hipertensos y coronarios, el estrés agudo puede desencadenar crisis o infarto."],
  "Guyton y Hall, Tratado de fisiología médica (14.ª ed.).",
  op=("¿Mediadores?", ["La acetilcolina baja la FC", "La acetilcolina baja la FC", "Sí: simpático + suprarrenal", "No: no aceleran el corazón en el estrés",
                       "No: vasodilatan, alergia"]),
  d=dict(rotulo="Neurotransmisores del sistema autónomo", ans=0,
         cards=[dict(titulo="Noradrenalina + adrenalina", datos=[("Sistema", "Simpático", True), ("Corazón", "Acelera", True), ("PA", "Sube", True)],
                     pie="Este caso."),
                dict(titulo="Acetilcolina", datos=[("Sistema", "Parasimpático", False), ("Corazón", "Frena", False), ("Nervio", "Vago", False)],
                     pie="Reposo."),
                dict(titulo="Dopamina", datos=[("Dónde", "Cerebro, riñón", False), ("Rol", "Movimiento, recompensa", False), ("Dosis alta", "Vasoconstricción", False)],
                     pie="Central."),
                dict(titulo="Histamina", datos=[("Dónde", "Mastocitos", False), ("Rol", "Alergia", False), ("Efecto", "Vasodilatación", False)],
                     pie="Inflamación.")]))

# NEU-034 · TB: perfil hepático antes del tratamiento · ÁRBOL
S("arbol", "NEU-034", "Paciente con TB pulmonar BK (+++) que va a iniciar tratamiento: pedir perfil hepático basal (además del tamizaje de VIH)",
  "Tuberculosis · inicio del tratamiento",
  ("Antes de iniciar el esquema para TB", ["Isoniazida, rifampicina y pirazinamida son hepatotóxicas.",
                                           "Se pide perfil hepático basal para comparar si luego aparecen síntomas."]),
  ("Varón de 28 años", ["TB pulmonar diagnosticada.", "BK en esputo (+++)."]),
  ["Exámenes basales: perfil hepático, glucosa, creatinina, prueba de VIH (ofrecida, no impide iniciar), prueba de sensibilidad (GeneXpert).",
   "Si las transaminasas suben > 5 veces (o > 3 con síntomas): suspender y reintroducir.",
   "Iniciar 2HRZE + 4HR sin demora; estudio de contactos."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + " (2025).",
  op=("¿Examen previo?", ["No: ya está confirmado", "Sí: los fármacos son hepatotóxicos", "No aporta en el enfermo", "No necesaria para empezar",
                          "Se ofrece, pero no retrasa el inicio"],
      {4: "VIH obligatorio antes de todo"}),
  arbol=Q("TB confirmada: ¿qué pedir antes del primer día?", [
      L("Basales (este caso)", "PERFIL HEPÁTICO", ["+ VIH, glucosa, creatinina", "Sensibilidad a fármacos"], path=True),
      L("Transaminasas > 5 veces", "Suspender y reintroducir", ["Uno por uno"])], path=True))

# SP-091 · Caso índice · TARJETAS
S("tarjetas", "SP-091", "El primer caso de un problema bajo vigilancia que identifica el servicio de salud se llama caso índice",
  "Vigilancia epidemiológica · definiciones",
  ("Caso índice", ["El primero que llama la atención del sistema de salud y dispara la investigación.",
                   "No siempre es el primero en enfermar (ese es el caso primario)."]),
  ("Pregunta de concepto", ["Sistema de vigilancia epidemiológica.", "Primer caso identificado en el servicio."]),
  ["Caso primario: el que introduce la enfermedad en el grupo (puede descubrirse después).",
   "Casos secundarios: los contagiados por el primario.",
   "Sospechoso, probable y confirmado: según la evidencia de laboratorio."],
  "OPS, Módulos de principios de epidemiología (MOPECE, 2011).",
  op=("¿Nombre?", ["Por clínica, no por orden", "Sí: el primero detectado", "Es el que inicia la transmisión", "Por clínica y nexo", "Por laboratorio"]),
  d=dict(rotulo="Casos en un brote", ans=0,
         cards=[dict(titulo="Caso índice", datos=[("Qué", "Primero detectado", True), ("Quién", "El servicio de salud", True), ("Inicia", "La investigación", True)],
                     pie="Este caso."),
                dict(titulo="Caso primario", datos=[("Qué", "Primero en enfermar", False), ("Rol", "Introduce el agente", False), ("Puede", "Hallarse después", False)],
                     pie="Origen."),
                dict(titulo="Caso secundario", datos=[("Qué", "Contagiado por otro", False), ("Cuándo", "Tras la incubación", False), ("Mide", "Tasa de ataque", False)],
                     pie="Transmisión."),
                dict(titulo="Confirmado", datos=[("Qué", "Laboratorio positivo", False), ("Antes", "Sospechoso, probable", False), ("Uso", "Clasificación", False)],
                     pie="Por pruebas.")]))

# OFT-032 · Leucocoria: retinoblastoma · TARJETAS
S("tarjetas", "OFT-032", "Lactante de 18 meses con reflejo pupilar blanco (leucocoria) y estrabismo: retinoblastoma hasta demostrar lo contrario",
  "Oftalmología pediátrica · tumores",
  ("Retinoblastoma", ["El tumor maligno ocular más frecuente en niños (casi siempre < 5 años); gen RB1.",
                      "Leucocoria (reflejo blanco en fotos o con la luz) y estrabismo son los signos iniciales."]),
  ("Lactante de 18 meses", ["Estrabismo y dolor ocular.", "Ojo derecho con hiperemia y reflejo pupilar blanco."]),
  ["Referir de urgencia a oftalmología oncológica: fondo de ojo bajo anestesia, ecografía y RM (no TC: radiación).",
   "Examinar a hermanos y padres (forma hereditaria, bilateral).",
   "Tamizaje: reflejo rojo en cada control del niño."],
  "AAP, reflejo rojo (2023); Children's Oncology Group.",
  op=("¿Sospecha?", ["No: dolor y opacidad corneal", "No: ojo rojo y fotofobia", "No: secreción, sin reflejo blanco", "Sí: leucocoria + estrabismo",
                     "También da leucocoria, pero se descarta primero el tumor"]),
  d=dict(rotulo="Reflejo pupilar blanco: ¿qué pensar?", ans=0,
         cards=[dict(titulo="Retinoblastoma", datos=[("Edad", "< 5 años", True), ("Signos", "Leucocoria, estrabismo", True), ("Urgencia", "Sí", True)],
                     pie="Este caso."),
                dict(titulo="Catarata congénita", datos=[("Dónde", "Cristalino opaco", False), ("Desde", "Nacimiento", False), ("Trato", "Cirugía temprana", False)],
                     pie="Ambliopía."),
                dict(titulo="Retinopatía del prematuro", datos=[("Quién", "Prematuros", False), ("Grave", "Desprendimiento", False), ("Tamizaje", "Fondo de ojo", False)],
                     pie="ROP."),
                dict(titulo="Enfermedad de Coats", datos=[("Quién", "Varones", False), ("Qué", "Exudados", False), ("Lado", "Uno", False)],
                     pie="Vascular.")]))

# GIN-126 · Síndrome HELLP · ÁRBOL + trastornos hipertensivos
S("arbol", "GIN-126", "Gestante a término con PA 160/110, dolor en hipocondrio derecho, plaquetas 90 000, transaminasas y DHL altas: síndrome HELLP",
  "Trastornos hipertensivos del embarazo · HELLP",
  ("Síndrome HELLP", ["Hemólisis (H), enzimas hepáticas elevadas (EL) y plaquetas bajas (LP): forma grave de preeclampsia.",
                      "Dolor en epigastrio o hipocondrio derecho por distensión de la cápsula del hígado."]),
  ("Primigesta de 38 semanas", ["Dolor en hipocondrio derecho; PA 160/110.", "Plaquetas 90 000, TGO 160, TGP 130, DHL 700."]),
  ["Sulfato de magnesio, antihipertensivo (labetalol, nifedipino o hidralazina) y terminar la gestación.",
   "A término: parto (vaginal o cesárea según condiciones); plaquetas si < 50 000 para cesárea.",
   "Vigilar hematoma o rotura hepática, CID y falla renal."],
  ACOG + ", hipertensión gestacional y preeclampsia (2020); ISSHP (2021).",
  op=("¿Diagnóstico?", ["No: hay daño de órganos", "Sí: hemólisis + enzimas + plaquetas", "No: hay HTA y daño hepático", "No: tiene criterios de severidad",
                        "Hipoglucemia y coagulopatía, sin HTA marcada"]),
  arbol=Q("Preeclampsia: ¿plaquetas < 100 000, transaminasas ≥ 2 veces y DHL ≥ 600?", [
      L("Sí (este caso)", "SÍNDROME HELLP", ["Sulfato de Mg", "Terminar la gestación"], path=True),
      L("No", "Preeclampsia con severidad", ["Sulfato de Mg", "Terminar ≥ 34 sem"])], path=True),
  escala=HTA_EMB(4, [("Plaquetas 90 000, TGO 160, DHL 700", True), ("PA 160/110 y dolor en hipocondrio derecho", True)],
                 "Sulfato de magnesio, antihipertensivo y parto."))

# INF-063 · PCP con hipoxemia: corticoides · ÁRBOL
S("arbol", "INF-063", "Paciente con VIH, CD4 100 y neumonía por Pneumocystis con PaO₂ 60 mmHg: además del cotrimoxazol, prednisona",
  "VIH · neumonía por Pneumocystis",
  ("Corticoides en la neumonía por Pneumocystis", ["Al morir el hongo se inflama el pulmón y empeora la oxigenación.",
                                                   "Con PaO₂ < 70 mmHg o gradiente A-a ≥ 35, la prednisona reduce la mortalidad."]),
  ("Varón de 27 años con VIH sin TAR", ["2 semanas de disnea, fiebre y tos seca; FR 30, SatO₂ 87 %, no completa oraciones.",
                                       "PaO₂ 60, LDH alta, CD4 100; infiltrados intersticiales difusos."]),
  ["Prednisona 40 mg c/12 h × 5 días, 40 mg/día × 5 días, 20 mg/día × 11 días (iniciar en las primeras 72 h).",
   "Cotrimoxazol 21 días; luego profilaxis.",
   "Iniciar TAR dentro de las 2 semanas."],
  "NIH/CDC/IDSA, infecciones oportunistas en VIH (act. 2025).",
  op=("¿Coadyuvante?", ["No: es para hongos como criptococo", "No: histoplasma", "Sí: PaO₂ < 70", "No: antirretroviral, no coadyuvante",
                        "No: es para citomegalovirus"]),
  arbol=Q("Neumonía por Pneumocystis: ¿PaO₂ < 70 mmHg o gradiente A-a ≥ 35?", [
      L("Sí: PaO₂ 60 (este caso)", "PREDNISONA + COTRIMOXAZOL", ["21 días de prednisona en descenso"], path=True),
      L("No", "Solo cotrimoxazol", ["21 días"])], path=True))

# PED-130 · Vacunas en el lactante con VIH · TARJETAS
S("tarjetas", "PED-130", "Lactante con VIH sintomático: las vacunas inactivadas se aplican normalmente; las de virus vivos (como rotavirus) requieren evaluación médica, y la BCG no se aplica",
  "Inmunizaciones · niño con VIH",
  ("Vacunas en el niño con VIH", ["Las inactivadas (pentavalente, IPV, neumococo, influenza) son seguras y se ponen siempre.",
                                  "Las vivas atenuadas dependen de la inmunosupresión: rotavirus con indicación médica; BCG contraindicada si hay VIH sintomático."]),
  ("Lactante de 4 meses con VIH sintomático", ["Esquema Nacional de Vacunación del MINSA 2024.", "¿Cuál se aplica bajo prescripción médica?"]),
  ["SPR y varicela: solo si CD4 ≥ 15 %; fiebre amarilla igual.",
   "La BCG puede causar enfermedad diseminada en el niño con VIH.",
   "TAR temprano hace que las vacunas protejan mejor."],
  MINSA + ", esquema nacional de vacunación (2024); " + OMS + " (2024).",
  op=("¿Bajo prescripción médica?", ["No: inactivada, se aplica siempre", "No: inactivada, se aplica siempre", "No: inactivada, se aplica siempre",
                                     "Sí: viva, evaluar el caso", "No: contraindicada en VIH sintomático"]),
  d=dict(rotulo="Vacuna y VIH en el lactante", ans=0,
         cards=[dict(titulo="Rotavirus", datos=[("Tipo", "Viva atenuada", True), ("Con VIH", "Evaluación médica", True), ("Vía", "Oral", True)],
                     pie="Este caso."),
                dict(titulo="BCG", datos=[("Tipo", "Viva", False), ("VIH sintomático", "Contraindicada", False), ("Riesgo", "BCGitis diseminada", False)],
                     pie="No poner."),
                dict(titulo="Pentavalente / IPV", datos=[("Tipo", "Inactivadas", False), ("Con VIH", "Sí", False), ("Esquema", "Normal", False)],
                     pie="Seguras."),
                dict(titulo="Neumococo", datos=[("Tipo", "Conjugada", False), ("Con VIH", "Sí, prioritaria", False), ("Esquema", "Normal", False)],
                     pie="Segura.")]))

# CIR-067 · Tumor de la base apendicular: hemicolectomía · ÁRBOL
S("arbol", "CIR-067", "Hallazgo en apendicectomía de un tumor de 2 cm en la base del apéndice que compromete el mesenterio: hemicolectomía derecha",
  "Tumores del apéndice · neuroendocrino",
  ("Tumor neuroendocrino del apéndice", ["El tumor más común del apéndice; suele hallarse por casualidad en una apendicectomía.",
                                         "Hasta 2 cm en la punta: basta la apendicectomía; > 2 cm, en la base o con invasión del mesoapéndice: hemicolectomía derecha."]),
  ("Varón de 27 años", ["Laparotomía por probable apendicitis.", "Masa de 2 cm en la base que afecta el mesenterio, con lesiones similares."]),
  ["Hemicolectomía derecha con linfadenectomía.",
   "Estudio de patología: grado (Ki-67) y márgenes.",
   "Cromogranina A y TC/PET con DOTATATE para extensión."],
  "ENETS, neoplasias neuroendocrinas del apéndice (2023); NCCN (2025).",
  op=("¿Conducta?", ["Término menos preciso; no saca ganglios", "Sí: base + mesenterio", "No: no reseca el tumor", "Insuficiente: base y mesenterio",
                     "No: no saca los ganglios"]),
  arbol=Q("Tumor neuroendocrino apendicular: ¿> 2 cm, en la base o con invasión del meso?", [
      L("Sí (este caso)", "HEMICOLECTOMÍA DERECHA", ["Con ganglios"], path=True),
      L("No: < 2 cm en la punta", "Apendicectomía basta", ["Control"])], path=True))

# PSI-024 · Acatisia: propranolol · TARJETAS
S("tarjetas", "PSI-024", "Paciente con haloperidol que no puede quedarse quieto y camina todo el tiempo: acatisia, tratar con propranolol",
  "Efectos extrapiramidales de los antipsicóticos",
  ("Acatisia", ["Inquietud interna con necesidad de moverse (no puede estar sentado), por bloqueo dopaminérgico.",
                "Aparece en días a semanas; puede confundirse con agitación psicótica."]),
  ("Varón de 24 años con esquizofrenia", ["Bien controlado con haloperidol.", "No puede estar quieto; camina por toda la casa."]),
  ["Bajar la dosis o cambiar a un antipsicótico de menor riesgo (quetiapina, clozapina).",
   "Propranolol 10-40 mg c/8-12 h; alternativas: mirtazapina a dosis baja o benzodiacepina.",
   "Nunca subir el antipsicótico (empeora)."],
  "APA, esquizofrenia (2020); Maudsley Prescribing Guidelines (15.ª ed.).",
  op=("¿Tratamiento?", ["Sí: de elección", "Para el neuroléptico maligno", "Alternativa, no la primera", "Para el neuroléptico maligno", "No: empeora"]),
  d=dict(rotulo="Efectos extrapiramidales y su tratamiento", ans=0,
         cards=[dict(titulo="Acatisia", datos=[("Clínica", "Inquietud", True), ("Cuándo", "Días-semanas", True), ("Trato", "Propranolol", True)],
                     pie="Este caso."),
                dict(titulo="Distonía aguda", datos=[("Clínica", "Tortícolis, crisis oculógira", False), ("Cuándo", "Horas-días", False), ("Trato", "Biperideno", False)],
                     pie="Aguda."),
                dict(titulo="Parkinsonismo", datos=[("Clínica", "Rigidez, temblor", False), ("Cuándo", "Semanas", False), ("Trato", "Anticolinérgico", False)],
                     pie="Subagudo."),
                dict(titulo="Discinesia tardía", datos=[("Clínica", "Movimientos bucales", False), ("Cuándo", "Meses-años", False), ("Trato", "Valbenazina", False)],
                     pie="Crónica.")]))

# CIR-068 · Hemorroides grado I: coagulación infrarroja · ÁRBOL + grados
S("arbol", "CIR-068", "Sangrado al defecar por hemorroides internas que no salen del ano (grado I), que no mejoran con el manejo médico: coagulación infrarroja",
  "Patología anal · hemorroides",
  ("Hemorroides internas", ["Almohadillas vasculares del canal anal que sangran rojo brillante al defecar, sin dolor.",
                            "Se gradúan por cuánto prolapsan (Goligher)."]),
  ("Mujer de 40 años, multípara", ["2 meses de sangrado al defecar; no mejora con tratamiento médico.", "Anoscopía: almohadillas que no rebasan el ano."]),
  ["Primero: fibra, agua y no pujar (tratamiento médico).",
   "Grado I-II que no responde: coagulación infrarroja, escleroterapia o ligadura con banda.",
   "Grado III-IV o mixtas grandes: hemorroidectomía."],
  "ASCRS, hemorroides (2024).",
  op=("¿Tratamiento?", ["Para grados III-IV", "No: es para cáncer de recto", "Para grados III-IV", "Sí: grado I que no responde", "Para grados III"]),
  arbol=Q("Hemorroides internas que sangran: ¿prolapsan?", [
      L("No: grado I (este caso)", "COAGULACIÓN INFRARROJA", ["O escleroterapia", "Si falla el manejo médico"], path=True),
      L("Sí y no se reducen", "Hemorroidectomía", ["Grados III-IV"])], path=True),
  escala=dict(nombre="Grados de las hemorroides internas (Goligher)", orden=True,
              que="Según el prolapso al pujar.",
              grados=[("I", "No prolapsan", ["Solo sangran"]), ("II", "Prolapsan y vuelven solas", ["Al pujar"]),
                      ("III", "Hay que meterlas con la mano", ["Reducción manual"]), ("IV", "Siempre afuera", ["No se reducen"])],
              caso=0, porque=[("Almohadillas que no rebasan el orificio anal", True)],
              conducta="Coagulación infrarroja o banda."))

# END-036 · Choque séptico refractario por insuficiencia suprarrenal primaria · ÁRBOL
S("arbol", "END-036", "Choque séptico que no responde a líquidos ni vasopresores, con cortisol bajo, ACTH alta e hiponatremia: insuficiencia suprarrenal primaria",
  "Sepsis · insuficiencia suprarrenal",
  ("Insuficiencia suprarrenal en el choque", ["Sin cortisol los vasos no responden a la noradrenalina: el choque se vuelve refractario.",
                                              "Cortisol bajo con ACTH alta = falla de la glándula suprarrenal (primaria)."]),
  ("Mujer de 64 años, diabética e hipertensa", ["3 días de antibiótico por ITU; hipotensa pese a líquidos y vasopresores.",
                                                "Na 130, lactato 4,5; cortisol bajo y ACTH elevada."]),
  ["Hidrocortisona 200 mg/día EV (50 mg c/6 h) si necesita vasopresor (SSC 2021).",
   "Seguir antibiótico, fuente de infección controlada y noradrenalina.",
   "Luego evaluar causa (hemorragia suprarrenal, autoinmune, TB) y reemplazo crónico."],
  "Surviving Sepsis Campaign (2021, act. 2024); Endocrine Society (2016).",
  op=("¿Causa?", ["Sí: cortisol bajo y ACTH alta", "Consecuencia del choque, no la causa", "No: glucosa 150, sin cetosis", "No: la ACTH estaría baja",
                  "No explica el choque refractario"]),
  arbol=Q("Choque séptico que no cede con vasopresores: ¿falta cortisol?", [
      L("Sí: cortisol bajo, ACTH alta (este caso)", "INSUFICIENCIA SUPRARRENAL PRIMARIA", ["Hidrocortisona 200 mg/día"], path=True),
      L("No", "Revisar foco y antibiótico", ["Drenar, ampliar cobertura"])], path=True))

# CIR-069 · Fisura anal aguda · ÁRBOL
S("arbol", "CIR-069", "Dolor anal intenso al defecar con sangrado, espasmo y desgarro en la línea media posterior: fisura anal aguda, ablandadores y baños de asiento",
  "Patología anal · fisura",
  ("Fisura anal aguda", ["Desgarro del anodermo, casi siempre en la línea media posterior, por heces duras.",
                         "Dolor muy intenso al defecar que dura minutos u horas, sangrado rojo y espasmo del esfínter."]),
  ("Mujer de 30 años", ["Hematoquecia y dolor muy intenso tras defecar; espasmo anal.", "Hipertonía del esfínter; desgarro en la línea media posterior."]),
  ["Fibra, agua, ablandadores de heces y baños de asiento tibios: curan la mayoría en 4-6 semanas.",
   "Si persiste: nifedipino o diltiazem tópico, o nitroglicerina; luego toxina botulínica.",
   "Crónica que no responde: esfinterotomía lateral interna. Fisura lateral: buscar Crohn, VIH, sífilis."],
  "ASCRS, fisura anal (2023).",
  op=("¿Tratamiento inicial?", ["Segunda línea", "Para la crónica refractaria", "Sí: medidas conservadoras", "Segunda línea", "No: es para fístula"]),
  arbol=Q("Fisura anal: ¿aguda (< 6-8 semanas)?", [
      L("Sí (este caso)", "ABLANDADORES + BAÑOS DE ASIENTO", ["Fibra y agua"], path=True),
      L("Crónica o no responde", "Calcioantagonista tópico", ["Luego toxina o esfinterotomía"])], path=True))

# NRL-036 · Rigidez de decorticación · TARJETAS + dibujo propio
S("tarjetas", "NRL-036", "TEC grave en coma con rigidez de decorticación (brazos flexionados, piernas extendidas): lesión por encima del mesencéfalo (hemisferios cerebrales)",
  "Neurología · posturas anormales",
  ("Postura de decorticación", ["Flexión de brazos y extensión de piernas: daño de la vía corticoespinal por encima del núcleo rojo.",
                                "Lesión en hemisferios, cápsula interna o tálamo; mejor pronóstico que la descerebración."]),
  ("Varón de 20 años con TEC grave", ["Caída de un tercer piso.", "Intubado, coma profundo, rigidez de decorticación."]),
  ["Glasgow motor: decorticación = 3; descerebración = 2.",
   "Pasar de decorticación a descerebración indica herniación que progresa.",
   "TC, control de la presión intracraneal y neurocirugía."],
  ATLS + "; Brain Trauma Foundation (2016).",
  op=("¿Localización?", ["No: ataxia, no posturas", "Sí: por encima del mesencéfalo", "Daría descerebración", "Puede contribuir; la clave es supramesencefálica",
                         "No: tetraplejía flácida"]),
  d=dict(rotulo="Postura anormal: ¿dónde está la lesión?", ans=0,
         cards=[dict(titulo="Decorticación", datos=[("Brazos", "Flexionados", True), ("Lesión", "Sobre el mesencéfalo", True), ("Glasgow M", "3", True)],
                     pie="Este caso."),
                dict(titulo="Descerebración", datos=[("Brazos", "Extendidos", False), ("Lesión", "Tronco (mesencéfalo, puente)", False), ("Glasgow M", "2", False)],
                     pie="Peor pronóstico."),
                dict(titulo="Flacidez", datos=[("Tono", "Ausente", False), ("Lesión", "Bulbo o médula", False), ("Glasgow M", "1", False)],
                     pie="Muy grave."),
                dict(titulo="Lesión cerebelosa", datos=[("Clínica", "Ataxia", False), ("Postura", "Normal", False), ("Ojo", "Nistagmo", False)],
                     pie="Otra cosa.")]),
  banda=B("Decorticación y descerebración", P("dib_posturas.jpg", 330, 264, [], credito=PROPIO, fondo="#ffffff"),
          [("Decorticación", "Brazos doblados sobre el pecho: lesión alta."),
           ("Descerebración", "Brazos extendidos y rotados: tronco."),
           ("Piernas", "Extendidas en ambas."),
           ("Empeora", "Si pasa de una a otra: herniación.")],
          pie="Esquema.", ans=0))

# PED-131 · ITU por E. coli BLEE: meropenem · ÁRBOL + ITU
S("arbol", "PED-131", "Preescolar con fiebre, disuria y polaquiuria con urocultivo de E. coli BLEE: el antibiótico indicado es un carbapenem (meropenem)",
  "Infección urinaria · resistencia",
  ("E. coli BLEE", ["Produce betalactamasas de espectro extendido: destruye penicilinas y cefalosporinas (incluida la ceftriaxona).",
                    "En infección febril (pielonefritis) el tratamiento seguro es un carbapenem."]),
  ("Preescolar de 4 años", ["4 días de fiebre, disuria y polaquiuria.", "Urocultivo: E. coli BLEE (+)."]),
  ["Meropenem (o ertapenem) EV; pasar a oral según antibiograma (a veces nitrofurantoína o fosfomicina sirven en cistitis).",
   "Amikacina es otra opción si es sensible.",
   "Ecografía renal tras la primera ITU febril; uso prudente de antibióticos."],
  "IDSA, gramnegativos resistentes (2024); " + AAP + ".",
  op=("¿Tratamiento?", ["Sí: estable frente a BLEE", "No: la BLEE la destruye", "Alta resistencia; no en fiebre", "No: la BLEE la destruye",
                        "No: no sirve en pielonefritis"]),
  arbol=Q("ITU febril con E. coli: ¿productor de BLEE?", [
      L("Sí (este caso)", "MEROPENEM", ["O ertapenem", "Según antibiograma"], path=True),
      L("No", "Cefalosporina", ["Ceftriaxona o cefuroxima"])], path=True),
  escala=ITU(2, [("Fiebre con disuria y polaquiuria", True), ("En el niño febril se trata como pielonefritis", True)],
             "Carbapenem EV y ecografía renal."))

# INF-064 · Malaria: fiebre cuartana · ÁRBOL + especies + frotis real
S("arbol", "INF-064", "Adolescente de la selva con fiebre paroxística cuartana, escalofríos, sudoración, anemia y hepatoesplenomegalia: malaria",
  "Metaxénicas · malaria",
  ("Malaria", ["Plasmodium transmitido por el Anopheles; destruye glóbulos rojos: anemia y bazo grande.",
               "El ritmo de la fiebre orienta: terciana (cada 48 h: vivax, ovale) o cuartana (cada 72 h: P. malariae)."]),
  ("Adolescente de 12 años, de la selva", ["Escalofríos, cefalea, sudoración y fiebre paroxística cuartana.", "T 38,8 °C, palidez, hepatoesplenomegalia; Hb 8."]),
  ["Gota gruesa y frotis (o prueba rápida) confirman y dicen la especie.",
   "Vivax/malariae: cloroquina (+ primaquina en vivax); falciparum: artesunato + mefloquina (MINSA).",
   "Signos de gravedad: alteración de conciencia, anemia grave, ictericia, falla renal: artesunato EV."],
  MINSA + ", NTS de malaria (2023); " + OMS + " (2025).",
  op=("¿Diagnóstico?", ["No: no da fiebre paroxística", "Sí: paroxismos + bazo + anemia", "Ondulante, ganado", "Continua, bradicardia relativa",
                        "Agua contaminada, mialgias"]),
  arbol=Q("Fiebre con escalofríos y sudor en paroxismos, en zona endémica: ¿gota gruesa positiva?", [
      L("Sí (este caso)", "MALARIA", ["Especie en el frotis", "Cloroquina ± primaquina"], path=True),
      L("No", "Repetir y buscar otra causa", ["Dengue, tifoidea"])], path=True),
  escala=dict(nombre="Especie según el ritmo de la fiebre", orden=False,
              que="Periodicidad clásica de los paroxismos.",
              grados=[("Terciana benigna", "Cada 48 h", ["P. vivax, P. ovale"]), ("Terciana maligna", "Irregular", ["P. falciparum", "Grave"]),
                      ("Cuartana", "Cada 72 h", ["P. malariae"])],
              caso=2, porque=[("Fiebre de tipo cuartana", True)],
              conducta="Confirmar la especie y tratar."),
  banda=B("Así se ve en el frotis", P("vivax_troz.jpg", 330, 220, [
            ("flecha", 0.52, 0.30, 0.80, 0.14, "parásito dentro\ndel glóbulo rojo")],
          credito="CDC/PHIL 2720" + CC + "dominio público"),
          [("Parásito en el hematíe", "Teñido de morado."),
           ("Gota gruesa", "Detecta el parásito."),
           ("Frotis fino", "Dice la especie."),
           ("Anemia", "El parásito rompe los glóbulos rojos.")],
          pie="Frotis de otro paciente (P. vivax).", ans=0))

# CAR-050 · Pericarditis aguda · ÁRBOL + criterios + ECG propio
S("arbol", "CAR-050", "Joven con dolor torácico que aumenta al inspirar, mejora inclinado hacia adelante, irradia al trapecio, con frote y ST elevado difuso: pericarditis aguda",
  "Enfermedades del pericardio",
  ("Pericarditis aguda", ["Inflamación del pericardio, casi siempre viral o idiopática.",
                          "Dolor pleurítico que mejora sentado e inclinado; frote; ST elevado difuso cóncavo con PR deprimido."]),
  ("Varón de 26 años, fumador", ["Dolor retroesternal irradiado al trapecio, peor al inspirar, mejor en posición genupectoral.",
                                 "Frote pericárdico; ST elevado en varias derivaciones."]),
  ["AINE (ibuprofeno o aspirina) + colchicina 3 meses; reposo deportivo.",
   "Ecocardiograma (derrame); troponina (miopericarditis).",
   "Hospitalizar si hay fiebre > 38 °C, derrame grande, taponamiento o no responde."],
  ESC + ", enfermedades del pericardio (2025).",
  op=("¿Diagnóstico?", ["No: no cambia con la postura", "No: disnea súbita, sin frote", "No: dolor desgarrante, pulsos asimétricos",
                        "Sí: postural + frote + ST difuso", "No: ST en un territorio, con imagen en espejo"]),
  arbol=Q("Dolor torácico: ¿cumple 2 de 4 criterios de pericarditis?", [
      L("Sí (este caso)", "PERICARDITIS AGUDA", ["AINE + colchicina", "Eco"], path=True),
      L("No: ST en un territorio", "Síndrome coronario", ["Cateterismo"])], path=True),
  triada=TR([("Dolor pleurítico postural", "Mejora inclinado", True), ("Frote pericárdico", "Sí", True), ("ST elevado difuso", "Varias derivaciones", True),
             ("Derrame pericárdico", "Falta el eco", None)],
            [("Criterios ESC (2 de 4)", 0, 3)],
            "Con 3 criterios ya se confirma."),
  banda=B("ECG de la pericarditis", P("ecg_pericarditis.jpg", 380, 182, [
            ("texto", 0.50, 0.08, "ST elevado difuso y PR deprimido")],
          credito=ECG_PROPIO, fondo="#ffffff"),
          [("ST elevado cóncavo", "En casi todas las derivaciones."),
           ("PR deprimido", "Muy típico de la pericarditis."),
           ("Sin imagen en espejo", "A diferencia del infarto."),
           ("Evoluciona", "Luego T invertidas y se normaliza.")],
          pie="Trazado de enseñanza.", ans=0))

# HEM-023 · Neutropenia grave: aislamiento inverso · TARJETAS
S("tarjetas", "HEM-023", "Paciente con leucocitos 400, Hb 5 y plaquetas 3000 (neutropenia profunda): aislamiento inverso (protector) para no contagiarla",
  "Hematología · paciente neutropénico",
  ("Aislamiento inverso (protector)", ["Protege al paciente inmunodeprimido de los gérmenes de los demás.",
                                       "Habitación individual, lavado de manos, mascarilla del personal, sin flores ni alimentos crudos."]),
  ("Mujer de 23 años", ["7 días hospitalizada por fiebre; T 39 °C.", "Leucocitos 400, Hb 5, plaquetas 3000 (pancitopenia)."]),
  ["Neutropenia febril: antibiótico de amplio espectro antipseudomonas en la primera hora (cefepime o piperacilina-tazobactam).",
   "Transfundir plaquetas y glóbulos rojos según umbrales.",
   "Estudiar la pancitopenia: frotis y médula ósea (aplasia, leucemia)."],
  "IDSA, neutropenia febril (2010, act. 2023); CDC, aislamiento (2007, act. 2023).",
  op=("¿Aislamiento?", ["No: para diarreas infecciosas", "Sí: protege al paciente", "No: protege a los demás", "No: protege a los demás",
                        "No: protege a los demás"]),
  d=dict(rotulo="Tipos de aislamiento", ans=0,
         cards=[dict(titulo="Inverso", datos=[("Protege", "Al paciente", True), ("Quién", "Neutropénicos", True), ("Medida", "Cuarto individual", True)],
                     pie="Este caso."),
                dict(titulo="Contacto", datos=[("Protege", "A los demás", False), ("Ejemplo", "SAMR, C. difficile", False), ("Medida", "Bata y guantes", False)],
                     pie="Gérmenes en piel."),
                dict(titulo="Gotas", datos=[("Protege", "A los demás", False), ("Ejemplo", "Influenza, meningococo", False), ("Medida", "Mascarilla", False)],
                     pie="< 1 metro."),
                dict(titulo="Respiratorio (aéreo)", datos=[("Protege", "A los demás", False), ("Ejemplo", "TB, sarampión", False), ("Medida", "N95, presión negativa", False)],
                     pie="Aerosoles.")]))

# NEF-053 · Sospecha de cáncer de próstata: biopsia · ÁRBOL
S("arbol", "NEF-053", "Anciano fumador con síntomas urinarios, dolor óseo en caderas, próstata indurada e irregular y PSA 8: sospecha de cáncer de próstata, biopsia",
  "Urología oncológica · cáncer de próstata",
  ("Sospecha de cáncer de próstata", ["Tacto con próstata dura, irregular o con nódulo obliga a biopsia, sea cual sea el PSA.",
                                      "Dolor óseo (caderas, columna) sugiere metástasis óseas."]),
  ("Varón de 70 años, fumador", ["6 meses de dificultad para iniciar la micción, polaquiuria y nicturia; dolor progresivo en caderas.",
                                 "Tacto: próstata indurada e irregular; PSA 8."]),
  ["RM multiparamétrica antes de la biopsia (guía la toma; EAU 2024) y biopsia (transperineal o transrectal).",
   "Si se confirma: gammagrafía ósea o PET-PSMA para estadificar.",
   "Dolor óseo con metástasis: bloqueo androgénico."],
  "EAU, cáncer de próstata (2024); NCCN (2025).",
  op=("¿Indicación?", ["Para estadificar, no para diagnosticar", "Ayuda a guiar; la biopsia confirma", "No: no evalúa la próstata", "Sí: confirma el cáncer",
                       "No: tacto sospechoso no espera"]),
  arbol=Q("Tacto rectal sospechoso o PSA alto: ¿confirmar con histología?", [
      L("Sí (este caso)", "BIOPSIA DE PRÓSTATA", ["RM multiparamétrica antes", "Gleason/ISUP"], path=True),
      L("Tacto normal, PSA en el límite", "Repetir PSA y RM", ["Según riesgo"])], path=True))

# CB-045 · Hipertiroidismo: metabolismo basal alto · TARJETAS
S("tarjetas", "CB-045", "En el hipertiroidismo sube el metabolismo basal: más consumo de oxígeno y de calorías, calor, taquicardia y pérdida de peso",
  "Fisiología · hormona tiroidea",
  ("Efectos de la hormona tiroidea", ["Aumenta el consumo de oxígeno y la producción de calor en casi todos los tejidos.",
                                      "Más receptores β en el corazón: taquicardia y gasto cardíaco alto."]),
  ("Mujer de 35 años", ["Intolerancia al calor, taquicardia, pérdida de peso.", "Diagnóstico: hipertiroidismo."]),
  ["Baja el colesterol (más receptores LDL y más degradación).",
   "Aumenta la motilidad intestinal (más deposiciones).",
   "Aumenta el gasto cardíaco y baja la resistencia vascular."],
  "Guyton y Hall (14.ª ed.); " + HARRISON + ".",
  op=("¿Cambio?", ["No: el colesterol baja", "No: la motilidad sube", "Sí: el metabolismo sube", "No: el gasto sube", "No: el consumo sube"]),
  d=dict(rotulo="Hipertiroidismo: ¿qué sube y qué baja?", ans=0,
         cards=[dict(titulo="Metabolismo basal", datos=[("Cambio", "Sube", True), ("O₂", "Más consumo", True), ("Calor", "Intolerancia", True)],
                     pie="Este caso."),
                dict(titulo="Corazón", datos=[("FC", "Sube", False), ("Gasto", "Sube", False), ("Riesgo", "FA", False)],
                     pie="Sube."),
                dict(titulo="Intestino", datos=[("Motilidad", "Sube", False), ("Heces", "Más frecuentes", False), ("Peso", "Baja", False)],
                     pie="Sube."),
                dict(titulo="Colesterol", datos=[("Nivel", "Baja", False), ("Por", "Más receptores LDL", False), ("En hipotiroidismo", "Sube", False)],
                     pie="Baja.")]))

# NRL-037 · Dolor neuropático: alodinia · TARJETAS
S("tarjetas", "NRL-037", "Dolor al roce de la ropa (alodinia), sensación eléctrica y adormecimiento: dolor neuropático",
  "Dolor · tipos",
  ("Dolor neuropático", ["Causado por lesión o enfermedad del sistema nervioso (nervio periférico o central).",
                         "Quemante, eléctrico, en descargas; alodinia (duele lo que no debería) e hipoestesia en la misma zona."]),
  ("Mujer de 62 años", ["Semanas de dolor al roce de la ropa en la pierna derecha, electricidad y adormecimiento.",
                        "«Como si le arrancaran» el dedo del pie; limita la marcha."]),
  ["Buscar la causa: diabetes, radiculopatía, herpes zóster, alcohol, B12.",
   "Primera línea: pregabalina o gabapentina, duloxetina o amitriptilina.",
   "Tópicos: lidocaína o capsaicina; los AINE ayudan poco."],
  "NeuPSIG/IASP, dolor neuropático (2015, act. 2024); " + NICE + " CG173.",
  op=("¿Tipo de dolor?", ["No: órganos internos, mal localizado", "Es la otra gran categoría; aquí hay daño nervioso", "Sí: alodinia + electricidad",
                          "No: piel, músculo, hueso", "No hay datos de causa psicológica"]),
  d=dict(rotulo="¿Qué tipo de dolor?", ans=0,
         cards=[dict(titulo="Neuropático", datos=[("Causa", "Nervio dañado", True), ("Cómo", "Quemante, eléctrico", True), ("Signo", "Alodinia", True)],
                     pie="Este caso."),
                dict(titulo="Nociceptivo somático", datos=[("Causa", "Piel, hueso, músculo", False), ("Cómo", "Bien localizado", False), ("Trato", "AINE, opioides", False)],
                     pie="Lesión tisular."),
                dict(titulo="Nociceptivo visceral", datos=[("Causa", "Órganos", False), ("Cómo", "Sordo, difuso", False), ("Signo", "Dolor referido", False)],
                     pie="Vísceras."),
                dict(titulo="Nociplástico", datos=[("Causa", "Sensibilización central", False), ("Ejemplo", "Fibromialgia", False), ("Sin", "Lesión visible", False)],
                     pie="Central.")]))

# GIN-127 · Ganancia de peso excesiva en gestante obesa · ÁRBOL + IOM
S("arbol", "GIN-127", "Gestante con IMC previo de 32 (obesidad) que ganó 12,5 kg: ganancia de peso excesiva (lo recomendado es 5 a 9 kg)",
  "Nutrición en el embarazo",
  ("Ganancia de peso en la gestante obesa", ["Con IMC ≥ 30 antes del embarazo se recomienda subir solo 5 a 9 kg.",
                                             "El exceso aumenta diabetes gestacional, preeclampsia, macrosomía y cesárea."]),
  ("Segundigesta de 40 semanas", ["IMC al inicio: 32.", "Ganó 12,5 kg en todo el embarazo."]),
  ["Consejería nutricional desde el primer control.",
   "Actividad física moderada si no hay contraindicación.",
   "En el posparto: lactancia y control del peso."],
  "IOM/NAM (2009); " + MINSA + ", guía técnica de atención integral materna.",
  op=("¿Ganancia?", ["No: supera lo recomendado", "No: subió de más", "Sí: más de 9 kg", "No: subió de más", "No: para su IMC es alta"]),
  arbol=Q("IMC previo ≥ 30: ¿subió más de 9 kg?", [
      L("Sí: 12,5 kg (este caso)", "GANANCIA EXCESIVA", ["Consejería", "Vigilar complicaciones"], path=True),
      L("No: 5-9 kg", "Adecuada", ["Seguir controles"])], path=True),
  escala=dict(nombre="Ganancia de peso recomendada (IOM 2009)", orden=True,
              que="Según el IMC antes del embarazo (gestación única).",
              grados=[("Bajo peso", "IMC < 18,5", ["12,5 a 18 kg"]), ("Normal", "18,5-24,9", ["11,5 a 16 kg"]),
                      ("Sobrepeso", "25-29,9", ["7 a 11,5 kg"]), ("Obesidad", "≥ 30", ["5 a 9 kg"])],
              caso=3, porque=[("IMC 32: obesidad", True), ("12,5 kg supera los 9 kg", True)],
              conducta="Consejería y vigilancia de complicaciones."))

# GAS-047 · Ictericia por reabsorción de hematoma · ÁRBOL
S("arbol", "GAS-047", "Posoperado con 7 transfusiones y hematoma retroperitoneal en resolución que hace ictericia con bilirrubina indirecta: reabsorción del hematoma",
  "Ictericia · hiperbilirrubinemia indirecta",
  ("Ictericia por exceso de producción de bilirrubina", ["La hemoglobina de un hematoma grande o de muchas transfusiones se degrada a bilirrubina indirecta.",
                                                        "El hígado sano no alcanza a conjugarla toda: sube la indirecta con transaminasas casi normales."]),
  ("Varón de 36 años", ["Operado hace 10 días por trauma; 7 paquetes globulares.", "BT 3,9 (indirecta 3,7); AST 55, ALT 89; hematoma retroperitoneal en resolución."]),
  ["Se resuelve sola al reabsorberse el hematoma.",
   "Descartar hemólisis transfusional tardía (Coombs) y Gilbert.",
   "Hepatitis postransfusional: incubación más larga y bilirrubina directa con transaminasas muy altas."],
  HARRISON + ".",
  op=("¿Causa?", ["Sí: mucha hemoglobina que degradar", "Eso es Gilbert o Crigler-Najjar", "Eso es Gilbert", "Daría bilirrubina directa",
                  "Incubación más larga y transaminasas muy altas"]),
  arbol=Q("Ictericia: ¿predomina la bilirrubina indirecta?", [
      L("Sí, con hematoma (este caso)", "REABSORCIÓN DEL HEMATOMA", ["Se resuelve sola"], path=True),
      L("No: directa", "Colestasis o hepatitis", ["Eco, serologías"])], path=True))

# GIN-128 · Tdap en la gestación · ÁRBOL
S("arbol", "GIN-128", "La vacuna Tdap se aplica en cada embarazo, de preferencia entre las semanas 27 y 36",
  "Inmunización en el embarazo",
  ("Tdap en el embarazo", ["Los anticuerpos de la madre pasan al feto y protegen al recién nacido de la tos ferina antes de que se vacune.",
                           "Se aplica en cada embarazo, idealmente al inicio del período 27-36 semanas."]),
  ("Primigesta de 8 semanas", ["Primer control prenatal.", "Pregunta por la Tdap."]),
  ["También en el embarazo: influenza (cualquier trimestre) y VSR (32-36 semanas, según disponibilidad).",
   "Si no se aplicó: dar en el posparto inmediato (protege menos al bebé).",
   "No están indicadas las vacunas vivas (SPR, varicela) en el embarazo."],
  CDC + "/ACIP (2024); " + ACOG + " (2022); " + MINSA + ".",
  op=("¿Semanas?", ["Antes de lo ideal", "Tarde: no alcanza a pasar anticuerpos", "Muy temprano", "Sí: óptimo para el bebé", "Protege menos al recién nacido"]),
  arbol=Q("Gestante: ¿cuándo aplicar la Tdap?", [
      L("Semanas 27-36 (este caso)", "TDAP EN CADA EMBARAZO", ["Mejor al inicio del período"], path=True),
      L("No se aplicó", "Posparto inmediato", ["Y vacunar a los contactos"])], path=True))

# PED-132 · Displasia broncopulmonar: hipertensión pulmonar · TARJETAS
S("tarjetas", "PED-132", "La complicación más frecuente de la displasia broncopulmonar del prematuro es la hipertensión pulmonar",
  "Neonatología · displasia broncopulmonar",
  ("Displasia broncopulmonar (DBP)", ["Enfermedad pulmonar crónica del prematuro que necesitó oxígeno o ventilación (≥ 28 días o a las 36 semanas).",
                                      "El daño de los vasos pulmonares lleva a hipertensión pulmonar y, a la larga, a falla del corazón derecho."]),
  ("Pregunta de concepto", ["Recién nacido prematuro con DBP.", "¿Complicación más frecuente?"]),
  ["Tamizaje de hipertensión pulmonar con ecocardiograma a las 36 semanas.",
   "Oxígeno para SatO₂ 92-95 %, buena nutrición, evitar sobrecarga de líquidos.",
   "Prevención: corticoides prenatales, CPAP precoz, cafeína, ventilación protectora."],
  "AHA/ATS, hipertensión pulmonar pediátrica (2015, act. 2024); " + NELSON + ".",
  op=("¿Complicación?", ["Consecuencia tardía de la HTP", "No es típica", "Sí: la más frecuente", "Se asocia, pero no es la principal", "Es de los primeros días"]),
  d=dict(rotulo="Complicaciones de la displasia broncopulmonar", ans=0,
         cards=[dict(titulo="Hipertensión pulmonar", datos=[("Frecuencia", "La más común", True), ("Prueba", "Ecocardiograma", True), ("Trato", "Oxígeno", True)],
                     pie="Este caso."),
                dict(titulo="Cor pulmonale", datos=[("Qué", "Falla del VD", False), ("Origen", "HTP avanzada", False), ("Signo", "Hepatomegalia", False)],
                     pie="Tardía."),
                dict(titulo="Retraso del crecimiento", datos=[("Por", "Gasto calórico alto", False), ("Trato", "Nutrición", False), ("Común", "Sí", False)],
                     pie="Asociado."),
                dict(titulo="Infecciones respiratorias", datos=[("Riesgo", "VSR grave", False), ("Prevención", "Nirsevimab", False), ("Consecuencia", "Reingresos", False)],
                     pie="Prevenir.")]))

# NEF-054 · Poliquistosis renal autosómica dominante · TARJETAS
S("tarjetas", "NEF-054", "Adulto con dolor en flanco, masa palpable, creatinina alta y hermano con ERC: poliquistosis renal autosómica dominante",
  "Riñón · enfermedades quísticas",
  ("Poliquistosis renal autosómica dominante", ["Mutación en PKD1 o PKD2: ambos riñones se llenan de quistes y crecen.",
                                                "Dolor en flanco, hematuria, HTA, litiasis, infecciones de quistes y ERC progresiva; quistes hepáticos y aneurismas cerebrales."]),
  ("Varón de 38 años", ["Dolor en flanco que empeora de pie; hermano con ERC.", "Masa dolorosa en flanco derecho; creatinina 2,85; orina normal."]),
  ["Ecografía renal (criterios de Pei por edad y número de quistes).",
   "Controlar la PA (IECA/ARA II); tolvaptán si progresa rápido; mucha agua.",
   "AngioRM cerebral si hay antecedente familiar de aneurisma o hemorragia."],
  "KDIGO, poliquistosis renal (2025).",
  op=("¿Diagnóstico?", ["Sí: riñones grandes + herencia", "No: orina normal, sin hematuria", "No: sin fiebre", "No: proteinuria, sin masas", "No: riñón normal de tamaño"]),
  d=dict(rotulo="Masa en flanco con falla renal", ans=0,
         cards=[dict(titulo="Poliquistosis (AD)", datos=[("Herencia", "Dominante", True), ("Riñón", "Grande, quistes", True), ("Extra", "Hígado, aneurismas", True)],
                     pie="Este caso."),
                dict(titulo="Absceso renal", datos=[("Clínica", "Fiebre", False), ("Curso", "Agudo", False), ("Trato", "Drenaje", False)],
                     pie="Infección."),
                dict(titulo="Riñón en esponja", datos=[("Riñón", "Tamaño normal", False), ("Problema", "Cálculos", False), ("Función", "Normal", False)],
                     pie="Benigno."),
                dict(titulo="Amiloidosis", datos=[("Riñón", "Grande", False), ("Orina", "Proteinuria", False), ("Causa", "Mieloma, crónicas", False)],
                     pie="Depósitos.")]))
