"""Entrega 3 · ejemplos con los diseños nuevos (21 lectura, 22 zonas, 23 regla, 24 decisión) e imágenes de
PubMed Central (NCBI) y Wikimedia Commons."""
from c28 import S, P, B, Q, L, TR, NELSON, ATLS, HARRISON, MINSA, OMS, AAP
from c27 import DOS

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
PMC_HINCHEY = "TC: Papaoikonomou et al. · Cureus 2025 · PMC12857236 (PubMed Central) · CC BY 4.0"
PMC_ROP = "Fondo de ojo: Zhao et al. · Scientific Data 2024 · PMC11130119 (PubMed Central) · CC BY 4.0"
PMC_PLUS = "Plus: Sharafi et al. · Int J Retina Vitreous 2025 · PMC12639888 (PubMed Central) · CC BY 4.0"

# CIR-080 · Diverticulitis con absceso pericólico de 5 cm: drenaje percutáneo · 21 LECTURA (TC real) + Hinchey
S("lectura", "CIR-080", "Anciana con fiebre, masa en fosa ilíaca izquierda y absceso pericólico de 5 cm en la TC: Hinchey Ib, drenaje percutáneo + antibióticos",
  "Diverticulitis aguda complicada · absceso",
  ("Diverticulitis con absceso", ["Un divertículo del colon sigmoides se perfora en pequeño y el pus queda encerrado junto al colon.",
                                 "La TC con contraste confirma, mide el absceso y ubica el grado de Hinchey."]),
  ("Mujer de 70 años", ["Dolor abdominal, fiebre y masa palpable en la fosa ilíaca izquierda.", "TC: absceso pericólico de 5 cm."]),
  ["Absceso ≥ 4-5 cm: drenaje percutáneo guiado por TC + antibiótico EV (p. ej. ceftriaxona + metronidazol).",
   "Absceso < 4 cm: antibiótico solo. Peritonitis difusa (Hinchey III-IV): cirugía de urgencia.",
   "Colonoscopía a las 6-8 semanas, ya sin inflamación, para descartar cáncer de colon."],
  "WSES, diverticulitis aguda del colon izquierdo (2020); ASCRS, diverticulitis del colon izquierdo (2020); " + HARRISON + ".",
  op=("¿Tratamiento?", ["No: un absceso de 5 cm no se cura solo con antibiótico", "Sí: absceso ≥ 4-5 cm sin peritonitis",
                        "No: no hay peritonitis difusa ni aire libre", "No: está contraindicada en la fase aguda (perfora)",
                        "No: cirugía urgente solo si falla el drenaje o hay peritonitis"]),
  d=dict(rotulo="Lee la TC en este orden", img_titulo="TC de pelvis con contraste (corte axial)",
         img=P("hinchey1b_tc.jpg", 430, 312, credito=PMC_HINCHEY),
         pines=[(0.33, 0.27), (0.75, 0.38)],
         pasos=[("Colecciones redondas con borde blanco", "Los círculos amarillos: pus encapsulado pegado al colon = absceso pericólico.", False),
                ("Grasa alrededor del colon «sucia»", "Gris y con hilos en vez de negra: inflamación de la grasa (sigmoides, lado izquierdo del paciente).", False),
                ("Mide el absceso: 5 cm en este caso", "≥ 4-5 cm → drenaje percutáneo guiado por TC + antibiótico. < 4 cm → solo antibiótico.", True),
                ("Busca aire libre o líquido en todo el abdomen", "No hay: no es peritonitis difusa (Hinchey III-IV), no hace falta operar de urgencia.", False)],
         img_pie="Imagen de otra paciente con abscesos pericólicos (Hinchey Ib).",
         tira_titulo="Compara con los otros grados (TC de la misma serie)",
         tira=[(P("hinchey0_tc.jpg", 360, 274), "Hinchey 0", "Pared engrosada y divertículos; sin pus", False),
               (P("hinchey1a_tc.jpg", 348, 278), "Hinchey Ia", "Flemón: grasa inflamada, sin colección", False),
               (P("hinchey2_tc.jpg", 315, 254), "Hinchey II", "Absceso pélvico de 9 cm (línea de medida)", False)],
         tira_credito=PMC_HINCHEY,
         veredicto=("Absceso pericólico de 5 cm, sin peritonitis = Hinchey Ib grande",
                    "Drenaje percutáneo + antibióticos; cirugía (Hartmann o resección con anastomosis) solo si el drenaje falla o aparece peritonitis.")),
  escala=dict(nombre="Clasificación de Hinchey modificada (Wasvary)", que="Gravedad de la diverticulitis según la TC: decide antibiótico, drenaje o cirugía.",
              grados=[("0", "Diverticulitis leve", ["Pared engrosada, sin colección"]),
                      ("Ia", "Flemón pericólico", ["Grasa inflamada, sin pus organizado"]),
                      ("Ib", "Absceso pericólico", ["Pus encerrado junto al colon"], "5 cm"),
                      ("II", "Absceso a distancia", ["Pélvico, intraabdominal o retroperitoneal"]),
                      ("III", "Peritonitis purulenta", ["Pus libre en la cavidad"]),
                      ("IV", "Peritonitis fecal", ["Heces libres: perforación abierta"])],
              caso=2, porque=[("Colección junto al colon (pericólica), no en la pelvis lejana", True),
                              ("Sin pus ni heces libres: no es peritonitis", True)],
              conducta="Ib ≥ 4-5 cm: drenaje percutáneo + antibiótico EV; colonoscopía a las 6-8 semanas."))

# PED-142 · Retinopatía del prematuro: SatO₂ 90-95 % y controles · 22 ZONAS (ICROP3) + ETROP + fotos de fondo de ojo
S("zonas", "PED-142", "Prematuro de 28 semanas y 1200 g con retinopatía del prematuro que progresa: SatO₂ estable en 90-95 % y no cortar los exámenes de fondo de ojo",
  "Neonatología · retinopatía del prematuro (ROP)",
  ("Retinopatía del prematuro", ["La retina del prematuro aún no tiene vasos hasta la periferia; el oxígeno alto frena su crecimiento.",
                                 "Después, la retina sin vasos libera VEGF: crecen vasos anormales que pueden desprenderla y dejar ciego al niño."]),
  ("Prematuro de 28 semanas, 1200 g", ["Ventilación mecánica prolongada y oxígeno intermitente.", "A las 35 semanas corregidas: ROP con signos de progresión."]),
  ["Tamizaje: ≤ 30 semanas o ≤ 1500 g (y otros inestables); primer examen a las 31 semanas corregidas o a las 4 semanas de vida.",
   "Evitar oxígeno alto y los vaivenes: metas de SatO₂ 90-95 % con alarmas.",
   "Tipo 1: tratar en 72 h con anti-VEGF intravítreo o láser; seguir controles hasta que la retina madure."],
  "ICROP3 (2021); AAP/AAO, tamizaje de ROP (2018); consenso europeo de distrés respiratorio (2022); " + NELSON + ".",
  op=("¿Manejo integral?", ["No: SatO₂ > 98 % empeora la ROP", "No: no trata la retina y daña el neurodesarrollo",
                            "No: la eritropoyetina puede empeorar la ROP", "Sí: oxígeno controlado + exámenes seriados",
                            "No: la ROP progresa aunque mejore el pulmón"],
      {0: "SatO₂ > 98 %", 1: "Corticoide sistémico prolongado", 2: "Eritropoyetina", 3: "SatO₂ 90-95 % + controles de fondo de ojo",
       4: "Suspender controles si mejora"}),
  d=dict(rotulo="Dónde y qué tan avanzada está la ROP (ICROP3)", dibujo_titulo="Zonas de la retina (centradas en la papila)",
         anillos=[("Zona I", ""), ("Zona II", "hasta la ora serrata nasal"), ("Zona III", "media luna temporal")],
         radios=[0.34, 0.74, 1.0], desplaza=0.3, caso_anillo=-1,
         puntos=[(0, 0, "papila", "#be123c"), (0.17, 0.12, "fóvea", "#7c2d12")],
         nota="Zona I: radio = 2 veces la distancia papila-fóvea. Más central = más grave. El enunciado no dice la zona ni el estadio: por eso hay que seguir examinando.",
         escalones_titulo="Estadios (y la enfermedad plus)",
         escalones=[("E1", "Línea de demarcación", "Línea blanca plana entre la retina con vasos y la que no tiene.", None, False),
                    ("E2", "Cresta", "La línea se engruesa y se eleva.", P("rop_c.jpg", 246, 184), False),
                    ("E3", "Vasos nuevos sobre la cresta", "Crecen hacia el vítreo: proliferación fibrovascular.", P("rop_d.jpg", 244, 182), False),
                    ("E4-5", "Desprendimiento de retina", "4: parcial · 5: total (ceguera).", None, False),
                    ("PLUS", "Enfermedad plus", "Vasos dilatados y tortuosos en el polo posterior: la ROP está activa.", P("rop_plus.jpg", 382, 296), False)],
         credito=PMC_ROP + " · " + PMC_PLUS),
  escala=dict(nombre="Cuándo tratar: Tipo 1 y Tipo 2 (ETROP, vigente en ICROP3)",
              que="Ordena la conducta según la zona, el estadio y la presencia de plus.",
              grados=[("Inmadura", "Sin ROP", ["Retina aún sin vasos completos", "Control cada 2-3 semanas"]),
                      ("Leve", "E1-E2 en zona II-III sin plus", ["Control cada 1-2 semanas"]),
                      ("Tipo 2", "Vigilancia estrecha", ["Zona I E1-2 sin plus", "Zona II E3 sin plus", "Control semanal"]),
                      ("Tipo 1", "Tratar en 72 h", ["Zona I con plus o E3", "Zona II E2-3 con plus", "Anti-VEGF o láser"])],
              caso=[1, 2], porque_titulo="Para ubicar este caso",
              porque=[("28 semanas y 1200 g: entra al tamizaje (≤ 30 sem o ≤ 1500 g)", True),
                      ("«Progresión» sin zona, estadio ni plus descritos", True),
                      ("Aún no cumple Tipo 1 descrito: no hay indicación de tratar hoy", True)],
              conducta="SatO₂ estable 90-95 % y fondo de ojo seriado (semanal si progresa); tratar si llega a Tipo 1."),
  banda=B("Si llega a Tipo 1: retina tras el láser", P("rop_e.jpg", 242, 182, credito=PMC_ROP),
          [("Manchas claras en la periferia", "Cicatrices del láser sobre la retina sin vasos."),
           ("Por qué funciona", "Esa retina sin vasos produce el VEGF que causa los vasos anormales."),
           ("Alternativa", "Anti-VEGF intravítreo (bevacizumab o ranibizumab), sobre todo en zona I."),
           ("Después", "Controles hasta la madurez de la retina: puede reactivarse.")],
          pie="Fondo de ojo de otro prematuro.", rotulo="Lo que sigue si empeora"))

# TRA-028 · Fractura vertebral por fragilidad: densitometría · 23 REGLA (T-score OMS y Genant) + Rx y DXA reales
S("regla", "TRA-028", "Mujer de 60 años con menopausia precoz y fractura en cuña de L4 tras caer de su propia altura: confirmar osteoporosis con densitometría (DXA)",
  "Osteoporosis · fractura por fragilidad",
  ("Fractura por fragilidad", ["Fractura por una caída desde la propia altura o menos: el hueso ya está débil.",
                              "La densitometría (DXA) mide la densidad del hueso y da el T-score."]),
  ("Mujer de 60 años, menopausia precoz", ["Dolor lumbar 2 semanas después de caer desde su propia altura.", "Rx: fractura vertebral en cuña de L4."]),
  ["DXA de columna lumbar y cadera: T ≤ −2,5 = osteoporosis; con fractura por fragilidad, osteoporosis grave (establecida).",
   "Tratar: bisfosfonato (alendronato) + calcio y vitamina D + ejercicio y prevención de caídas.",
   "RM solo si hay signos de alarma (déficit neurológico, sospecha de tumor o infección)."],
  "OMS (criterios de densitometría); Bone Health & Osteoporosis Foundation (2022); AACE (2020); " + HARRISON + ".",
  op=("¿Para confirmar osteoporosis?", ["No: busca compresión medular o tumor", "Sí: mide densidad ósea (T-score)",
                                         "No: solo en casos atípicos", "No: ve actividad ósea, no densidad", "No: suele ser normal en osteoporosis"]),
  d=dict(rotulo="Dos reglas: densidad del hueso y aplastamiento de la vértebra",
         reglas=[dict(nombre="T-score de la DXA (OMS)", que="Compara la densidad con la de un adulto joven sano. Se mide en columna lumbar y cadera.",
                      min=-4.5, max=1.5, fmt="{}", ticks=[-4, -3, -2.5, -2, -1, 0, 1],
                      bandas=[(-4.5, -2.5, "Osteoporosis (≤ −2,5)", 3), (-2.5, -1, "Osteopenia", 1), (-1, 1.5, "Normal (≥ −1)", 0)],
                      caso=None, pie="Este caso: falta el T-score → pedir DXA (columna lumbar y cadera)", pie_on=True),
                 dict(nombre="Grado de Genant (Rx lateral)", que="Cuánta altura perdió la vértebra fracturada comparada con su altura normal.",
                      min=0, max=60, fmt="{} %", ticks=[0, 20, 25, 40, 60],
                      bandas=[(0, 20, "Sin fractura", 0), (20, 25, "G1", 1), (25, 40, "G2 moderada", 2), (40, 60, "G3 grave", 3)],
                      caso=None, pie="Este caso: cuña en L4 → medir la pérdida de altura anterior en la Rx lateral")],
         banda=B("De dónde sale el T-score: así se ve una DXA", P("dxa_grafico.jpg", 344, 333, [("circulo", 0.564, 0.43, 0.05)],
                 credito="Jmarchn" + CC + "CC BY-SA 3.0", fondo="#ffffff"),
                 [("Mide L1-L4 y la cadera", "Rayos X de muy baja dosis; el equipo calcula la densidad de cada vértebra."),
                  ("Gráfico de colores", "Verde normal, amarillo osteopenia, rojo osteoporosis; el punto (círculo) es la paciente."),
                  ("Tabla: columna «Adulto-Joven»", "«Puntuación» es el T-score: aquí −3,3 en L1-L4 = osteoporosis."),
                  ("«Ajustado a edad» es el Z-score", "Se usa en menores de 50 años y antes de la menopausia.")],
                 pie="DXA de otra paciente de 70 años.")),
  escala=dict(nombre="Criterios diagnósticos de osteoporosis (BHOF 2022 / AACE 2020)", orden=False,
              que="Basta uno de los tres para diagnosticar osteoporosis.",
              grados=[("DXA", "T-score ≤ −2,5", ["Columna, cuello femoral o cadera total"]),
                      ("Fractura", "Por fragilidad", ["Vertebral o de cadera", "Aunque la DXA no llegue a −2,5"]),
                      ("Osteopenia +", "Riesgo alto (FRAX)", ["T −1 a −2,5 con FRAX ≥ 20 % (mayor) o ≥ 3 % (cadera)"])],
              caso=1, porque=[("Caída desde su propia altura = baja energía", True),
                              ("Menopausia precoz: falta de estrógenos acelera la pérdida de hueso", True)],
              conducta="Ya es osteoporosis clínica: la DXA confirma la densidad, sirve de base para el control y se trata."),
  banda=B("Así se ve una fractura en cuña de L4", P("cuna_l4.jpg", 300, 352, [
            ("flecha", 0.61, 0.56, 0.8, 0.86, "L4 en cuña:\npierde altura\ndelante"),
            ("flecha", 0.61, 0.33, 0.82, 0.12, "L3 de altura\nnormal")],
          credito="James Heilman, MD" + CC + "CC BY-SA 3.0"),
          [("Vista lateral", "El frente de la columna queda a la derecha de la imagen."),
           ("Borde anterior más bajo", "La vértebra se aplasta por delante: forma de cuña."),
           ("Compara con la de arriba", "L3 conserva su altura: el cambio es solo en L4."),
           ("Muro posterior entero", "Si se rompe o hay déficit neurológico: TC o RM.")],
          pie="Rx de otro paciente con fractura por compresión de L4."))

# INF-070 · Mordedura de perro en la mano: lavado profuso primero · 24 DECISIÓN (OMS) + foto real + calendario propio
S("decision", "INF-070", "Mordedura de perro en la mano hace 2 horas, herida desgarrante profunda: lo primero en el primer nivel es el lavado profuso con agua, jabón y suero",
  "Rabia · profilaxis después de una mordedura",
  ("Profilaxis de la rabia", ["El virus entra por la herida y sube por los nervios hasta el cerebro: una vez con síntomas, casi siempre es mortal.",
                             "Lavar enseguida baja mucho el virus; luego se decide vacuna e inmunoglobulina según el tipo de exposición."]),
  ("Varón de 35 años, hace 2 horas", ["Mordedura de perro en la mano izquierda.", "Herida profunda y desgarrante de 1 × 5 cm; estable."]),
  ["Lavar 15 minutos con agua a chorro y jabón (o suero) y luego antiséptico (povidona yodada).",
   "No suturar de entrada; si hace falta (cara), después de infiltrar la inmunoglobulina.",
   "Herida profunda en la mano: amoxicilina-clavulánico 3-5 días y vacuna antitetánica si corresponde."],
  OMS + ", vacunas antirrábicas: posición de la OMS (2018); " + MINSA + ", NTS n.º 131 de rabia humana; IDSA, infecciones de piel (2014).",
  op=("¿Conducta inicial?", ["No: se difiere en mordeduras (riesgo de infección)", "Sí: lo primero en toda mordedura",
                             "Va después: en heridas profundas de la mano sí se indica", "Va después del lavado, según la categoría",
                             "No: ni cerrar ni dar de alta sin profilaxis"],
      {1: "Lavado profuso con SF y jabón"}),
  d=dict(rotulo="Qué hacer según el tipo de exposición y el perro (OMS)",
         previo=("Lavar la herida 15 minutos con agua a chorro y jabón (o suero)",
                 "Es lo primero en TODA mordedura y en cualquier nivel de atención: reduce mucho el virus y las bacterias."),
         eje_y="Tipo de exposición", ancho_filas=230,
         cols=["Perro ubicable y sano (se observa 10 días)", "Perro sospechoso, perdido o silvestre"],
         rows=[("Categoría I", "Tocarlo o que lama piel sana"), ("Categoría II", "Mordisco leve o rasguño sin sangrado"),
               ("Categoría III", "Mordedura que atraviesa la piel, varias, o lamida de mucosa")],
         cells=[[("No vacunar", ["Lavar y educar"]), ("No vacunar", ["La piel sana no deja pasar el virus"])],
                [("Vacuna", ["Se suspende si el perro sigue sano a los 10 días"]), ("Vacuna", ["Esquema completo"])],
                [("Vacuna + inmunoglobulina", ["Se suspende si el perro sigue sano a los 10 días"]),
                 ("Vacuna + inmunoglobulina", ["Esquema completo: días 0, 3, 7 y 14"])]],
         caso=(2, None),
         nota="El enunciado no dice cómo está el perro: la fila del caso es la III. En la norma del MINSA, la categoría III equivale a la exposición «grave».",
         claves_titulo="Por qué este caso es categoría III",
         claves=[("Atraviesa la piel", ["Herida profunda y desgarrante"], True),
                 ("Está en la mano", ["Zona con muchos nervios: el virus llega antes"], True),
                 ("No es la primera acción", ["Vacuna, inmunoglobulina y antibiótico van después del lavado"], False)]),
  banda=B("La herida y lo que viene después", DOS(
            P("mordida_perro.jpg", 260, 291, [("flecha", 0.57, 0.46, 0.78, 0.1, "herida\ndesgarrante")],
              credito="Assianir" + CC + "CC BY-SA 3.0"),
            P("dib_calendario_rabia.jpg", 390, 257, credito=PROPIO, fondo="#ffffff"), vertical=True),
          [("Herida abierta en el dorso de la mano", "Atraviesa la piel: categoría III de la OMS."),
           ("Primero: lavar 15 minutos", "Agua a chorro y jabón; luego povidona yodada."),
           ("No cerrar con puntos de entrada", "Se infecta más; se deja abierta o se aproxima después."),
           ("Vacuna: días 0, 3, 7 y 14", "Intramuscular en el deltoides (esquema de la OMS)."),
           ("Inmunoglobulina el día 0", "Infiltrada dentro y alrededor de la herida, en exposición grave."),
           ("Observar al perro 10 días", "Si sigue sano, se puede suspender la vacuna.")],
          pie="Foto de otra mordedura de perro; abajo, esquema."))
