"""Entrega 2 · tanda 03 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, DOS, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO, GINA
from esc28 import HTA_EMB, DENGUE, ABORTO

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"

# GAS-029 · Hepatitis viral aguda · FASES + ictericia real
S("fases", "GAS-029", "Joven con pródromo de fiebre, náuseas y astenia que luego hace ictericia y dolor en hipocondrio derecho mientras cede la fiebre: hepatitis viral aguda",
  "Hepatitis aguda · hepatitis viral",
  ("Hepatitis viral aguda", ["Virus que inflaman el hígado (A, B, C, D, E); en el joven, la hepatitis A es la más común.",
                             "Pródromo «gripal» y luego fase ictérica: al aparecer la ictericia, la fiebre cede."]),
  ("Varón de 18 años", ["8 días de inapetencia, fiebre, náuseas, vómitos y astenia.",
                        "3 días después: malestar en el hipocondrio derecho e ictericia; ya sin fiebre."]),
  ["Transaminasas muy altas (a menudo > 1000); pedir IgM anti-VHA, HBsAg, IgM anti-HBc y anti-VHC.",
   "Manejo de soporte: reposo relativo, hidratación, evitar alcohol y fármacos hepatotóxicos.",
   "Alarma: INR > 1,5 con confusión = falla hepática aguda (hospitalizar, centro de trasplante)."],
  "AASLD/IDSA, hepatitis virales; EASL, falla hepática aguda (2017); " + CDC + ", hepatitis A (2024).",
  op=("¿Diagnóstico?", ["Sí: pródromo → ictericia", "No: sin anemia ni pródromo infeccioso", "No: sin fármaco ni tóxico",
                        "No: mujer, curso crónico", "No: sin cólico; pródromo gripal"]),
  d=dict(rotulo="Fases de la hepatitis viral aguda", ans=1,
         fases=[("Incubación", "2-6 semanas (A)", "SIN SÍNTOMAS", ["Ya contagia"]),
                ("Pródromo", "Días 1-7", "GRIPAL", ["Fiebre, náuseas, astenia", "Inapetencia"]),
                ("Ictérica", "1-4 semanas", "ICTERICIA", ["Coluria, acolia", "La fiebre cede", "Este caso"]),
                ("Convalecencia", "Semanas", "RECUPERACIÓN", ["Transaminasas bajan"])]),
  banda=B("Así se ve la ictericia", P("ictericia.jpg", 400, 125, [
            ("flecha", 0.66, 0.42, 0.50, 0.85, "escleras amarillas")],
          credito="Dominio público" + CC.rstrip(" · ")),
          [("Escleras amarillas", "El primer lugar donde se nota: bilirrubina > 2,5-3 mg/dL."),
           ("Piel amarilla", "Aparece cuando sube más la bilirrubina."),
           ("Orina oscura", "Coluria: bilirrubina directa en la orina."),
           ("Heces claras", "Acolia: no llega bilis al intestino.")],
          pie="Foto de otro paciente con hepatitis A.", ans=0))

# GIN-079 · Preeclampsia con signos de severidad · ÁRBOL + clasificación
S("arbol", "GIN-079", "Gestante de 36 semanas con cefalea, escotomas, epigastralgia, PA 170/110 y proteinuria: preeclampsia con signos de severidad, sulfato de magnesio y terminar la gestación",
  "Trastornos hipertensivos del embarazo · preeclampsia",
  ("Preeclampsia con signos de severidad", ["Hipertensión desde las 20 semanas con proteinuria o daño de órganos.",
                                            "Severidad: PA ≥ 160/110, cefalea, alteración visual, epigastralgia, plaquetas bajas, transaminasas altas."]),
  ("Primigesta de 36 semanas", ["Cefalea global, escotomas y epigastralgia.", "PA 170/110; proteinuria +++; feto cefálico, FCF 140."]),
  ["Sulfato de magnesio: 4-6 g EV en 20 min y luego 1-2 g/h (previene la eclampsia).",
   "Bajar la PA en 30-60 min si ≥ 160/110: labetalol, nifedipino o hidralazina.",
   "A partir de las 34 semanas, terminar la gestación tras estabilizar (vía según condiciones obstétricas)."],
  ACOG + ", boletín 222 (2020); ISSHP (2021); " + MINSA + ", guía de emergencias obstétricas.",
  op=("¿Conducta?", ["Sí: prevenir eclampsia y terminar", "No: con severidad a las 36 sem no se espera", "No: no se espera con severidad",
                     "No: es para hipertensión crónica", "No: empeora el volumen"],
      {0: "Sulfato de Mg y finalizar la gestación", 2: "Nifedipina y expectante hasta 40 sem", 3: "Metildopa y cesárea a las 38 sem"}),
  arbol=Q("Preeclampsia: ¿signos de severidad?", [
      L("Sí: PA 170/110, cefalea, escotomas (este caso)", "SULFATO DE Mg + TERMINAR", ["Antihipertensivo", "≥ 34 semanas"], path=True),
      L("No", "Vigilar", ["Parto a las 37 semanas"])], path=True),
  escala=HTA_EMB(3, [("PA 170/110 (≥ 160/110)", True), ("Cefalea, escotomas y epigastralgia", True), ("Proteinuria +++", True)],
                 "Sulfato de magnesio, antihipertensivo y terminar la gestación."),
  triada=TR([("PA ≥ 160/110", "170/110", True), ("Cefalea", "Global", True), ("Alteración visual", "Escotomas", True),
             ("Epigastralgia", "Sí", True)],
            [("Signos de severidad", 0, 3)],
            "Epigastralgia y escotomas anuncian eclampsia o HELLP."))

# INF-037 · Dengue con signos de alarma · ÁRBOL + clasificación OPS/OMS
S("arbol", "INF-037", "Paciente de zona endémica con fiebre, dolor retroocular, dolor abdominal intenso y vómitos: probable dengue con signos de alarma",
  "Enfermedades metaxénicas · dengue",
  ("Dengue con signos de alarma", ["Al bajar la fiebre (días 3-7) aumenta la fuga de plasma.",
                                   "Dolor abdominal intenso y vómitos persistentes anuncian el choque: es el grupo B2."]),
  ("Paciente de 45 años, distrito endémico", ["Fiebre persistente y dolor retroocular.", "Dolor abdominal intenso y vómitos."]),
  ["«Probable»: cuadro compatible + zona con transmisión; «confirmado»: NS1, PCR o IgM.",
   "Grupo B2: hospitalizar, cristaloides EV y hematocrito seriado.",
   "No dar AINE ni corticoides; paracetamol para la fiebre."],
  "OPS, guía de dengue (2016, act. 2022); " + MINSA + ", NTS de atención del dengue (2024).",
  op=("¿Clasificación?", ["No: es para grupos de casos", "No: término antiguo; hay alarma", "No: no hay choque",
                          "Sí: con signos de alarma", "No: sin choque ni sangrado grave"]),
  arbol=Q("Dengue probable: ¿dolor abdominal intenso o vómitos persistentes?", [
      L("Sí (este caso)", "CON SIGNOS DE ALARMA", ["Hospitalizar", "Cristaloides EV"], path=True),
      L("No", "Sin signos de alarma", ["En casa, hidratación oral"])], path=True),
  escala=DENGUE(1, [("Dolor abdominal intenso", True), ("Vómitos", True), ("Sin choque ni sangrado grave", True)],
                "Grupo B2: hospitalizar, cristaloides y control de hematocrito."))

# NEU-023 · Crisis asmática: silencio auscultatorio · ÁRBOL + gravedad GINA
S("arbol", "NEU-023", "Asmático en crisis con taquicardia, polipnea, tirajes y silencio auscultatorio: el silencio indica riesgo vital",
  "Asma · crisis asmática",
  ("Crisis asmática con riesgo vital", ["El «tórax silente» significa que casi no pasa aire: obstrucción extrema.",
                                        "Ya no hay sibilantes porque el flujo es mínimo; puede seguir paro respiratorio."]),
  ("Paciente de 23 años, asmático", ["Crisis de 3 horas.", "FC 130, FR 32, politirajes, silencio en ambos hemitórax; despierto."]),
  ["Oxígeno a SatO₂ 93-95 %, salbutamol + ipratropio nebulizados continuos, corticoide sistémico.",
   "Sulfato de magnesio EV; avisar a UCI (intubación si se agota o baja la conciencia).",
   "Gases arteriales: una PaCO₂ normal o alta en plena crisis es mala señal (agotamiento)."],
  GINA + "; BTS/SIGN, asma (2024).",
  op=("¿Peor evolución?", ["Indica crisis grave, no riesgo vital", "Indica crisis grave", "Sí: tórax silente = riesgo vital",
                           "Importa, pero no define la gravedad", "Grave, pero no tanto como el silencio"]),
  arbol=Q("Crisis asmática: ¿tórax silente, confusión o cianosis?", [
      L("Sí: silencio auscultatorio (este caso)", "RIESGO VITAL", ["UCI", "Broncodilatador continuo, Mg EV"], path=True),
      L("No: sibilantes, habla en frases", "Leve o moderada", ["Salbutamol, corticoide oral"])], path=True),
  escala=dict(nombre="Gravedad de la crisis asmática (GINA 2025)", orden=True,
              que="Se clasifica por el peor signo presente.",
              grados=[("Leve o moderada", "Habla en frases", ["FC 100-120", "SatO₂ 90-95 %", "PEF > 50 %"]),
                      ("Grave", "Habla en palabras", ["FR > 30, músculos accesorios", "FC > 120", "SatO₂ < 90 %"]),
                      ("Riesgo vital", "Somnoliento o tórax silente", ["Silencio auscultatorio", "Confusión, cianosis"])],
              caso=2, porque=[("Silencio auscultatorio bilateral", True), ("FC 130, FR 32 y tirajes: ya era grave", True)],
              conducta="UCI, oxígeno, broncodilatador continuo, corticoide y magnesio EV."))

# GAS-030 · Úlcera péptica: fisiopatología · RADIAL + balanza propia
S("radial", "GAS-030", "Úlcera en la curvatura menor cerca del antro: se produce por el desequilibrio entre la agresión ácido-péptica y la defensa de la mucosa",
  "Enfermedad ácido-péptica · úlcera gástrica",
  ("Úlcera péptica", ["Pérdida de mucosa que pasa la muscular de la mucosa.",
                      "Aparece cuando la agresión (ácido, pepsina, H. pylori, AINE) supera a la defensa (moco, bicarbonato, flujo, prostaglandinas)."]),
  ("Varón de 44 años", ["Endoscopía.", "Excoriación de la mucosa en la curvatura menor, cerca del antro y el píloro."]),
  ["Las dos causas principales: H. pylori y AINE.",
   "En la úlcera gástrica el ácido suele ser normal o bajo: falla la defensa.",
   "Toda úlcera gástrica se biopsia (descartar cáncer) y se controla con endoscopía."],
  "ACG, H. pylori (2024); Maastricht VI/Florencia (2022); " + HARRISON + ".",
  op=("¿Causa básica?", ["No: el moco protege", "Sí: agresión > defensa", "No: la bilis no neutraliza el ácido", "No: el bicarbonato protege",
                         "Contribuye, pero no es la causa básica"],
      {0: "Aumento de la producción de moco", 1: "Desequilibrio agresión-defensa", 2: "Falla de la bilis para neutralizar",
       4: "Hipersecreción de pepsinógeno"}),
  d=dict(rotulo="La úlcera: cuando la agresión le gana a la defensa", centro="DESEQUILIBRIO", centro_sub="este caso", ans=0,
         items=[("H. PYLORI", ["Inflama y debilita la mucosa"]), ("AINE", ["Quitan prostaglandinas"]),
                ("ÁCIDO Y PEPSINA", ["Agresión química"]), ("MOCO Y BICARBONATO", ["Barrera protectora"]),
                ("FLUJO DE SANGRE", ["Repara la mucosa"])],
         ruta=["Biopsia y H. pylori", "Suspender AINE", "IBP 8 semanas", "Erradicar y controlar"]),
  banda=B("La balanza de la úlcera", P("dib_balanza_ulcera.jpg", 380, 289, [], credito=PROPIO, fondo="#ffffff"),
          [("Agresión", "Ácido, pepsina, H. pylori, AINE y tabaco."),
           ("Defensa", "Moco, bicarbonato, flujo de sangre y prostaglandinas."),
           ("Úlcera gástrica", "Más por falla de la defensa (H. pylori, AINE)."),
           ("Úlcera duodenal", "Más por exceso de ácido (H. pylori del antro).")],
          pie="Esquema.", ans=0))

# CIR-052 · Apendicitis aguda en el escolar · ÁRBOL + PAS
S("arbol", "CIR-052", "Escolar con anorexia, dolor periumbilical que pasa a la fosa ilíaca derecha y vómitos, sin diarrea: apendicitis aguda",
  "Abdomen agudo en el niño · apendicitis",
  ("Apendicitis aguda", ["La causa quirúrgica más común de abdomen agudo en niños.",
                         "Secuencia típica: anorexia → dolor periumbilical → vómitos → dolor en la fosa ilíaca derecha."]),
  ("Escolar de 6 años", ["12 horas de malestar, anorexia y dolor periumbilical.", "Vómitos sin alimento, sin diarrea; dolor en la FID."]),
  ["Hemograma y PCR; ecografía como primer estudio de imagen.",
   "Confirmada: apendicectomía (laparoscópica) y antibiótico.",
   "Antes de los 5 años se perfora con más frecuencia: no demorar."],
  "APSA, apendicitis en niños (2024); WSES, guías de Jerusalén (2020).",
  op=("¿Diagnóstico?", ["Sí: secuencia típica", "No: es del lactante, con sangre", "No: sin diarrea", "No: es del adulto mayor",
                        "No: sin síntomas urinarios"]),
  arbol=Q("Dolor que empieza periumbilical y pasa a la FID: ¿hay signos peritoneales?", [
      L("Dolor en FID con anorexia y vómitos (este caso)", "APENDICITIS AGUDA", ["Eco y hemograma", "Cirugía"], path=True),
      L("Diarrea abundante, dolor difuso", "Gastroenteritis", ["Hidratación"])], path=True),
  escala=dict(nombre="Escala pediátrica de apendicitis (PAS)", modo="puntaje",
              que="Samuel 2002: suma 8 datos (máximo 10) para decidir entre observar, ecografía o cirugía.",
              items=[("M", "Migración del dolor a la FID", "Periumbilical → FID", 1), ("A", "Anorexia", "Sí", 1),
                     ("N", "Náuseas o vómitos", "Vómitos", 1), ("D", "Dolor en la FID", "Sí", 2),
                     ("T", "Dolor al toser, saltar o percutir", "No se describe", None), ("F", "Fiebre ≥ 38 °C", "No se describe", None),
                     ("L", "Leucocitos > 10 000", "Sin hemograma", None), ("N", "Neutrófilos > 75 %", "Sin hemograma", None)],
              total_txt="Total: 5 puntos con los datos dados", total_nota="faltan fiebre y hemograma",
              rangos=[("≤ 3", "Poco probable", "Observar"), ("4-6", "Intermedio", "Ecografía y hemograma"), ("≥ 7", "Alto", "Cirugía")],
              caso_rango=1, porque=[("Con fiebre o leucocitosis pasaría a riesgo alto", True)],
              conducta="Hemograma, PCR y ecografía; evaluación por cirugía."),
  banda=B("Así se ve en la ecografía", P("apendicitis_eco.jpg", 300, 259, [
            ("flecha", 0.45, 0.38, 0.30, 0.88, "apéndice engrosado")],
          credito="Borbély Márton" + CC + "CC BY-SA 4.0"),
          [("Apéndice > 6 mm", "Tubo ciego engrosado que no se comprime."),
           ("Grasa brillante alrededor", "Inflamación vecina."),
           ("Primera imagen en niños", "Sin radiación."),
           ("Si no se ve", "Observar y repetir, o RM; la TC queda al final.")],
          pie="Ecografía de otro paciente.", ans=0))

# INF-038 · Estrongiloidiasis: ivermectina · TARJETAS + larva real
S("tarjetas", "INF-038", "Strongyloides stercoralis en las heces: el tratamiento de elección es la ivermectina",
  "Parasitosis intestinales · estrongiloidiasis",
  ("Estrongiloidiasis", ["Nematodo que entra por la piel y vive en el duodeno; puede reinfectar al mismo huésped (autoinfección).",
                         "En las heces se ven LARVAS rabditoides (los huevos eclosionan dentro del intestino)."]),
  ("Análisis de heces de rutina", ["Hallazgo de Strongyloides stercoralis.", "Sin otros datos."]),
  ["Ivermectina 200 µg/kg/día por 1-2 días (repetir a las 2 semanas en inmunosuprimidos).",
   "Riesgo de hiperinfección con corticoides o HTLV-1 (endémico en el Perú): tratar antes de inmunosuprimir.",
   "Albendazol es alternativa menos eficaz."],
  CDC + ", estrongiloidiasis (2024); " + OMS + ", geohelmintiasis.",
  op=("¿Tratamiento?", ["No: es para protozoos", "Poco eficaz contra Strongyloides", "Sí: el más eficaz", "Alternativa, menos eficaz",
                        "No: es para tenias y trematodos"]),
  d=dict(rotulo="Parásito: ¿qué fármaco?", ans=0,
         cards=[dict(titulo="Strongyloides", datos=[("Fármaco", "Ivermectina", True), ("En heces", "Larvas", True), ("Riesgo", "Hiperinfección", True)],
                     pie="Este caso."),
                dict(titulo="Áscaris, uncinarias", datos=[("Fármaco", "Albendazol", False), ("En heces", "Huevos", False), ("Dosis", "Única", False)],
                     pie="Geohelmintos."),
                dict(titulo="Tenias", datos=[("Fármaco", "Praziquantel", False), ("En heces", "Proglótides", False), ("Neurocisticercosis", "Albendazol", False)],
                     pie="Cestodos."),
                dict(titulo="Giardia, ameba", datos=[("Fármaco", "Metronidazol", False), ("Tipo", "Protozoos", False), ("En heces", "Quistes", False)],
                     pie="Protozoos.")]),
  banda=B("Así se ve en las heces", P("strongy.jpg", 400, 204, [
            ("flecha", 0.40, 0.68, 0.70, 0.88, "larva rabditoide")],
          credito="CDC" + CC + "dominio público"),
          [("Larva, no huevo", "En heces frescas se ven larvas rabditoides móviles."),
           ("Esófago corto", "Con bulbo: la distingue de la uncinaria."),
           ("Pocas larvas", "Se necesitan varias muestras o cultivo en agar."),
           ("Serología", "Útil si las heces salen negativas.")],
          pie="Microscopía de heces.", ans=0))

# NEU-024 · Neumotórax espontáneo secundario en EPOC · ÁRBOL + Rx real
S("arbol", "NEU-024", "EPOC con dolor torácico y disnea súbitos, SatO₂ 86 % e hiperresonancia en un hemitórax: neumotórax espontáneo secundario",
  "Enfermedades de la pleura · neumotórax",
  ("Neumotórax espontáneo secundario", ["Aire en la pleura en un pulmón ya enfermo (EPOC, bullas, TB, fibrosis).",
                                        "Lo tolera mal: aunque sea pequeño, da mucha disnea e hipoxemia."]),
  ("Varón de 68 años con EPOC", ["Dolor torácico y disnea súbitos que no mejoran con O₂ ni broncodilatadores.",
                                 "PA 110/60, FC 110, FR 30, SatO₂ 86 %; hiperresonancia en el hemitórax derecho."]),
  ["Rx de tórax: línea pleural sin trama por fuera.",
   "Secundario con síntomas: tubo de drenaje fino (no solo observar) y hospitalizar.",
   "Si hay hipotensión y desviación traqueal: tensión, descomprimir ya."],
  "BTS, neumotórax (2023); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["Sí: súbito + hiperresonancia", "No: sin hiperresonancia", "No: sería gradual y con sibilantes", "No: matidez, no hiperresonancia",
                        "No: no da hiperresonancia"]),
  arbol=Q("Disnea súbita con hiperresonancia de un lado: ¿hipotensión y tráquea desviada?", [
      L("No (este caso, PA 110/60)", "NEUMOTÓRAX: DRENAJE", ["Rx de tórax", "Tubo fino"], path=True),
      L("Sí", "Neumotórax a tensión", ["Descompresión con aguja"])], path=True),
  escala=dict(nombre="Tipos de neumotórax", orden=False,
              que="Según la causa; cambia el manejo.",
              grados=[("Espontáneo", "Primario", ["Joven alto, fumador", "Sin enfermedad pulmonar"]),
                      ("Espontáneo", "Secundario", ["EPOC, TB, fibrosis", "Siempre más grave"]),
                      ("Traumático", "Penetrante o cerrado", ["Arma, costillas rotas"]),
                      ("Iatrogénico", "Por procedimiento", ["Vía central, biopsia, ventilación"])],
              caso=1, porque=[("Tiene EPOC", True), ("SatO₂ 86 %: mala tolerancia", True)],
              conducta="Tubo de drenaje fino y hospitalización."),
  banda=B("Así se ve un neumotórax", P("rx_neumotorax_grande.jpg", 280, 280, [
            ("texto", 0.17, 0.22, "aire sin trama\npulmonar"),
            ("flecha", 0.37, 0.4, 0.2, 0.7, "pulmón\ncolapsado")],
          credito="James Heilman" + CC + "CC BY 3.0"),
          [("Sin trama pulmonar", "Negro hasta la pared: aire libre en la pleura."),
           ("Pulmón colapsado", "Se ve como una masa pequeña junto al hilio."),
           ("En la EPOC", "Cuidado: una bulla grande puede parecer neumotórax (TC si hay duda)."),
           ("Tensión", "Mediastino hacia el lado sano: no esperar la Rx.")],
          pie="Rx de otro paciente.", ans=0))

# SP-055 · Violencia familiar: Centro de Salud Mental Comunitario · TARJETAS
S("tarjetas", "SP-055", "Víctimas de violencia familiar detectadas en el tamizaje que necesitan atención integral especializada: Centro de Salud Mental Comunitario",
  "Salud mental comunitaria · violencia familiar",
  ("Centro de Salud Mental Comunitario (CSMC)", ["Establecimiento del primer nivel especializado en salud mental, cerca de la comunidad.",
                                                  "Atiende a víctimas de violencia con psicología, psiquiatría y trabajo social."]),
  ("Consultorio de salud de la mujer", ["Tamizaje de violencia familiar con incidencia alta.", "Las víctimas requieren atención integral especializada."]),
  ["Ley 30364: el sector salud detecta, atiende y deriva; la denuncia puede hacerse en la comisaría o la fiscalía.",
   "El Centro Emergencia Mujer (MIMP) da apoyo legal y social; la atención de salud mental especializada la da el CSMC.",
   "Hospitales e institutos especializados quedan para casos graves o complejos."],
  "Ley n.º 30364; " + MINSA + ", lineamientos de salud mental comunitaria (2018, act. 2023).",
  op=("¿A dónde referir?", ["Sí: atención especializada cercana", "Apoyo legal y social, no atención de salud", "No: es para casos complejos",
                            "No: es el último nivel", "Para la denuncia, no para la atención"]),
  d=dict(rotulo="¿Qué hace cada institución?", ans=0,
         cards=[dict(titulo="CSMC", datos=[("Da", "Atención de salud mental", True), ("Nivel", "Primero, especializado", True), ("Cerca de", "La comunidad", True)],
                     pie="Este caso."),
                dict(titulo="Centro Emergencia Mujer", datos=[("Da", "Apoyo legal y social", False), ("Sector", "MIMP", False), ("Salud mental", "Deriva", False)],
                     pie="Complementa."),
                dict(titulo="Comisaría / fiscalía", datos=[("Da", "Denuncia", False), ("Medidas", "De protección", False), ("Salud", "No", False)],
                     pie="Vía legal."),
                dict(titulo="Instituto especializado", datos=[("Da", "Casos complejos", False), ("Nivel", "III", False), ("Acceso", "Por referencia", False)],
                     pie="Último nivel.")]))

# GAS-031 · Pancreatitis aguda: lipasa · ÁRBOL + Atlanta + TC real
S("arbol", "GAS-031", "Alcohólico con dolor epigástrico en cinturón de 7 días: para confirmar la pancreatitis aguda se pide lipasa (sigue alta más días que la amilasa)",
  "Páncreas · pancreatitis aguda",
  ("Pancreatitis aguda", ["Inflamación del páncreas; en el Perú, sobre todo biliar y alcohólica.",
                          "Diagnóstico con 2 de 3: dolor típico, lipasa o amilasa ≥ 3 veces lo normal, imagen compatible."]),
  ("Varón de 50 años, alcohólico", ["7 días de dolor epigástrico intenso que va a la región lumbar.", "Hace 2 días: náuseas e hiporexia."]),
  ["La amilasa vuelve a lo normal en 3-5 días; la lipasa dura 8-14: tras una semana, pedir lipasa.",
   "Hidratación guiada por metas (no agresiva), analgesia y dieta oral temprana.",
   "TC con contraste solo si hay duda o no mejora a las 72 h (busca necrosis)."],
  "ACG, pancreatitis aguda (2024); Atlanta revisada (2012); WATERFALL (2022).",
  op=("¿Examen?", ["No: es de la vía biliar", "Ya pudo normalizarse a los 7 días", "Sí: más específica y dura más", "No: no confirma pancreatitis",
                   "No: solo habla de alcohol o colestasis"]),
  arbol=Q("Dolor epigástrico en cinturón: ¿lipasa ≥ 3 veces lo normal?", [
      L("Pedirla (este caso)", "LIPASA", ["Confirma con el dolor"], path=True),
      L("Normal y duda", "TC con contraste", ["Busca otra causa"])], path=True),
  escala=dict(nombre="Gravedad de la pancreatitis (Atlanta revisada 2012)", orden=True,
              que="Según la falla de órganos y las complicaciones locales.",
              grados=[("Leve", "Sin falla", ["Sin complicaciones", "Alta en días"]),
                      ("Moderadamente grave", "Falla < 48 h", ["O complicación local (colección)"]),
                      ("Grave", "Falla > 48 h", ["Persistente, de uno o más órganos", "Mortalidad 30 %"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("Falta evaluar órganos (PA, creatinina, oxigenación)", True)],
              conducta="Lipasa, hidratación por metas y analgesia; medir falla de órganos."),
  triada=TR([("Dolor típico", "Epigástrico a la espalda", True), ("Lipasa o amilasa ≥ 3 veces", "Pendiente", None),
             ("Imagen compatible", "Pendiente", None)],
            [("Criterios diagnósticos (2 de 3)", 0, 2)],
            "Con el dolor típico basta la lipasa alta para diagnosticarla."),
  banda=B("Así se ve en la TC", P("pancreatitis_tc.jpg", 300, 234, [
            ("flecha", 0.62, 0.32, 0.80, 0.10, "páncreas inflamado"),
            ("flecha", 0.40, 0.30, 0.20, 0.10, "líquido alrededor")],
          credito="Hellerhoff" + CC + "CC BY-SA 3.0"),
          [("Páncreas aumentado", "Bordes borrosos por el edema."),
           ("Líquido alrededor", "Exudado peripancreático."),
           ("Si no capta contraste", "Necrosis: pancreatitis más grave."),
           ("No es de rutina", "Solo si hay duda o no mejora.")],
          pie="TC de otro paciente.", ans=0))

# CIR-053 · Hernia inguinal indirecta · ÁRBOL + EHS + esquema propio
S("arbol", "CIR-053", "Albañil con hernia inguinoescrotal izquierda blanda y reductible que aumenta con Valsalva: hernia inguinal indirecta",
  "Hernias de la pared abdominal · hernia inguinal",
  ("Hernia inguinal indirecta", ["Sale por el anillo inguinal profundo, lateral a los vasos epigástricos, y sigue el cordón hasta el escroto.",
                                 "La más común en ambos sexos; la que más baja al escroto."]),
  ("Albañil de 48 años", ["Tumoración inguinoescrotal izquierda reductible y asintomática de 5 cm.",
                          "Blanda, indolora; aumenta con Valsalva."]),
  ["Tratamiento: reparación con malla (Lichtenstein o laparoscópica TEP/TAPP).",
   "Directa: sale por el triángulo de Hesselbach, medial a los vasos; rara vez baja al escroto.",
   "Hidrocele: no se reduce, transilumina y se palpa el cordón por encima."],
  "HerniaSurge, guía internacional de hernia inguinal (2018, act. 2023).",
  op=("¿Diagnóstico?", ["No: debajo del ligamento, no baja al escroto", "No: sobre una cicatriz", "Rara vez llega al escroto",
                        "Sí: inguinoescrotal y reductible", "No: no se reduce y transilumina"]),
  arbol=Q("Bulto inguinal: ¿baja al escroto siguiendo el cordón?", [
      L("Sí, inguinoescrotal (este caso)", "INDIRECTA", ["Anillo profundo", "Malla"], path=True),
      L("No, bulto redondo medial", "Directa", ["Triángulo de Hesselbach"])], path=True),
  escala=dict(nombre="Clasificación de la Sociedad Europea de Hernia (EHS)", orden=False,
              que="Por el sitio del defecto (y su tamaño en dedos al operar).",
              grados=[("L", "Lateral = indirecta", ["Anillo profundo", "Baja al escroto"]),
                      ("M", "Medial = directa", ["Triángulo de Hesselbach", "Adultos mayores"]),
                      ("F", "Femoral", ["Debajo del ligamento", "Mujeres mayores"])],
              caso=0, porque=[("Inguinoescrotal: sigue el cordón", True), ("El tamaño del defecto se mide al operar", True)],
              conducta="Reparación electiva con malla."),
  banda=B("Por dónde sale cada hernia", P("dib_hernia_inguinal.jpg", 380, 266, [], credito=PROPIO, fondo="#ffffff"),
          [("Vasos epigástricos", "La referencia: separan la hernia indirecta de la directa."),
           ("Indirecta", "Lateral a los vasos, por el anillo profundo, hacia el escroto."),
           ("Directa", "Medial a los vasos, por el triángulo de Hesselbach (pared débil)."),
           ("Ambas", "Por encima del ligamento inguinal.")],
          pie="Vista desde dentro del abdomen.", ans=1))

# INF-039 · Dengue: prueba del lazo · ÁRBOL + clasificación + foto real
S("arbol", "INF-039", "Fiebre, cefalea y mialgias 9 días después de visitar Iquitos, con petequias al tomar la presión: dengue (prueba del lazo positiva)",
  "Enfermedades metaxénicas · dengue",
  ("Dengue", ["Virus transmitido por Aedes aegypti; incubación de 4-10 días.",
              "Fiebre alta, cefalea, dolor retroocular, mialgias; la fragilidad capilar da petequias."]),
  ("Varón de 28 años", ["3 días de fiebre, cefalea y mialgias intensas.", "Visitó Iquitos hace 9 días; petequias al inflar el manguito."]),
  ["Prueba del lazo: manguito entre la PA sistólica y diastólica 5 minutos; ≥ 20 petequias por 2,5 cm² = positiva.",
   "Confirmar: NS1 o PCR en los primeros 5 días; IgM después.",
   "Sin signos de alarma: casa, hidratación oral, paracetamol; evitar AINE."],
  "OPS, guía de dengue (2016, act. 2022); " + MINSA + ", NTS de atención del dengue (2024).",
  op=("¿Diagnóstico?", ["No: sin petequias, con paroxismos", "No: ictericia y sangrado, vacuna", "Sí: fiebre + mialgias + lazo positivo",
                        "No: contacto con agua, dolor de pantorrillas", "No: fiebre continua y dolor abdominal"]),
  arbol=Q("Fiebre aguda tras visitar zona endémica: ¿signos de alarma?", [
      L("No: petequias por el lazo (este caso)", "DENGUE SIN ALARMA", ["NS1", "Hidratación oral, paracetamol"], path=True),
      L("Sí: dolor abdominal, vómitos", "Con signos de alarma", ["Hospitalizar"])], path=True),
  escala=DENGUE(0, [("Fiebre, cefalea y mialgias", True), ("Petequias con el lazo, sin sangrado de mucosas", True),
                    ("Sin dolor abdominal ni vómitos", True)],
                "Manejo en casa con hidratación oral, paracetamol y control diario."),
  banda=B("Así se ve la prueba del lazo", P("lazo.jpg", 300, 224, [
            ("circulo", 0.25, 0.45, 0.16, "petequias", 0.30, 0.90)],
          credito="CDC" + CC + "dominio público"),
          [("Petequias", "Puntos rojos por debajo del manguito: capilares frágiles."),
           ("Positiva", "≥ 20 petequias en un cuadrado de 2,5 cm."),
           ("No es diagnóstica sola", "Apoya el dengue; también sale en otras fiebres."),
           ("Brazo de comparación", "A la derecha, el brazo sin manguito.")],
          pie="Foto de otro paciente.", ans=0))

# OFT-018 · Sinusitis subaguda · ÁRBOL + clasificación por duración
S("arbol", "OFT-018", "Adolescente con 1 mes de cefalea, tos nocturna, rinorrea y goteo posnasal purulento: sinusitis subaguda",
  "Otorrinolaringología · rinosinusitis en el niño",
  ("Rinosinusitis bacteriana", ["Infección de los senos paranasales tras un resfriado que no mejora.",
                                "La tos de noche viene del moco que baja por la faringe (goteo posnasal)."]),
  ("Adolescente de 12 años", ["Cefalea desde hace 1 mes.", "Tos de predominio nocturno, rinorrea intermitente; secreción purulenta en la pared posterior de la faringe."]),
  ["Se clasifica por la duración: aguda < 30 días, subaguda 30-90, crónica > 90.",
   "Tratamiento: amoxicilina (o amoxicilina-clavulánico) 10-14 días; lavados nasales.",
   "Imagen solo si hay complicación (órbita, cerebro) o se piensa en cirugía."],
  AAP + ", sinusitis bacteriana aguda en niños (2013); EPOS (2020).",
  op=("¿Diagnóstico?", ["Sí: 1 mes de síntomas purulentos", "No: estornudos y prurito, sin pus", "No: más de 3 meses",
                        "No: menos de 4 semanas", "Más en preescolares, curso corto"]),
  arbol=Q("Síntomas nasales con goteo posnasal purulento: ¿cuánto duran?", [
      L("30-90 días (este caso: 1 mes)", "SUBAGUDA", ["Amoxicilina 10-14 días"], path=True),
      L("Menos de 30 días", "Aguda", ["Observar o antibiótico"])], path=True),
  escala=dict(nombre="Rinosinusitis por duración (AAP)", orden=True,
              que="Clasificación pediátrica por el tiempo de los síntomas.",
              grados=[("< 30 días", "Aguda", ["Tras un resfriado", "Persistente > 10 días o grave"]),
                      ("30-90 días", "Subaguda", ["Síntomas leves y persistentes"]),
                      ("> 90 días", "Crónica", ["Pólipos, alergia, adenoides", "Otorrino"])],
              caso=1, porque=[("1 mes de cefalea, tos y rinorrea", True), ("Goteo posnasal purulento", True)],
              conducta="Amoxicilina 10-14 días y lavados nasales."))

# REU-024 · Herpes zóster en VIH · TARJETAS + fotos reales
S("tarjetas", "REU-024", "Paciente con VIH con dolor urente y luego vesículas en un dermatoma del tórax, Tzanck con células gigantes: herpes zóster",
  "Infecciones virales de la piel · herpes zóster",
  ("Herpes zóster", ["Reactivación del virus varicela-zóster dormido en un ganglio sensitivo.",
                     "Dolor urente y luego vesículas agrupadas sobre piel roja, en un solo dermatoma, sin cruzar la línea media."]),
  ("Mujer de 64 años con VIH", ["3 días de dolor urente en el lado izquierdo del tórax.", "Eritema y vesículas a lo largo del dermatoma; Tzanck con células gigantes."]),
  ["Antiviral en las primeras 72 h: valaciclovir o aciclovir 7 días (EV si está diseminado o muy inmunosuprimido).",
   "Analgesia; vigilar la neuralgia posherpética.",
   "Vacuna recombinante contra el zóster para ≥ 50 años y adultos inmunosuprimidos."],
  CDC + ", herpes zóster y vacuna recombinante (2024); IDSA, infecciones oportunistas en VIH.",
  op=("¿Diagnóstico?", ["Sí: dermatoma + vesículas", "No: sigue al contacto, no a un dermatoma", "No: úlcera, no vesículas",
                        "No: sin vesículas en dermatoma", "No: lesiones en todo el cuerpo"]),
  d=dict(rotulo="Vesículas: ¿dónde están?", ans=0,
         cards=[dict(titulo="Herpes zóster", datos=[("Lugar", "Un dermatoma", True), ("Antes", "Dolor urente", True), ("Tzanck", "Células gigantes", True)],
                     pie="Este caso."),
                dict(titulo="Varicela", datos=[("Lugar", "Todo el cuerpo", False), ("Lesiones", "En distintas etapas", False), ("Edad", "Niños", False)],
                     pie="Primoinfección."),
                dict(titulo="Herpes simple", datos=[("Lugar", "Labios, genitales", False), ("Recurre", "En el mismo sitio", False), ("Tzanck", "También +", False)],
                     pie="VHS."),
                dict(titulo="Dermatitis de contacto", datos=[("Lugar", "Donde tocó", False), ("Síntoma", "Prurito", False), ("Forma", "Lineal o geométrica", False)],
                     pie="Alérgica.")]),
  banda=B("Así se ven la piel y el Tzanck", P("zoster_tzanck.jpg", 400, 161, [
            ("flecha", 0.20, 0.40, 0.18, 0.88, "vesículas"),
            ("flecha", 0.70, 0.30, 0.86, 0.88, "célula gigante")],
          credito="Fixi/Cremer (CC BY-SA 3.0) y NIAID (dominio público)" + CC.rstrip(" · "), fondo="#ffffff"),
          [("Vesículas agrupadas", "Sobre piel roja, en banda: siguen el dermatoma."),
           ("No cruza la línea media", "Afecta un solo lado."),
           ("Células gigantes multinucleadas", "En el Tzanck: efecto del virus (VHS o VVZ)."),
           ("Confirmación hoy", "PCR del líquido de la vesícula.")],
          pie="Imágenes de otros pacientes.", ans=0))

# GIN-080 · Endometritis puerperal · ÁRBOL + signos
S("arbol", "GIN-080", "Puérpera de 3 días poscesárea con fiebre de 38,5 °C, útero doloroso y secreción purulenta: endometritis, iniciar antibióticos",
  "Infección puerperal · endometritis",
  ("Endometritis puerperal", ["Infección polimicrobiana del endometrio; la cesárea es el mayor factor de riesgo.",
                              "Fiebre, útero blando y doloroso, loquios fétidos o purulentos, en los primeros días."]),
  ("Puérpera de 3 días por cesárea", ["Fiebre de 38,5 °C en 2 tomas separadas.", "Útero doloroso a 2 cm del ombligo; secreción purulenta."]),
  ["Clindamicina + gentamicina EV hasta 24-48 h sin fiebre; no hace falta seguir por vía oral.",
   "Si no mejora en 48-72 h: eco (restos, absceso, hematoma), tromboflebitis pélvica séptica.",
   "Legrado solo si hay restos placentarios."],
  ACOG + "; " + WILLIAMS + "; OMS, infecciones maternas periparto (2015).",
  op=("¿Conducta?", ["No: el foco es el útero", "Si no mejora con antibióticos", "Solo si hay restos", "Sí: endometritis",
                     "Solo si es refractaria o hay necrosis"]),
  arbol=Q("Fiebre puerperal: ¿útero doloroso y loquios purulentos?", [
      L("Sí (este caso)", "ENDOMETRITIS: ANTIBIÓTICOS", ["Clindamicina + gentamicina EV"], path=True),
      L("No: mama, herida u orina", "Otro foco", ["Mastitis, herida, ITU, TVP"])], path=True),
  triada=TR([("Fiebre ≥ 38 °C", "38,5 °C", True), ("Útero doloroso", "Sí", True), ("Loquios purulentos o fétidos", "Secreción purulenta", True),
             ("Subinvolución uterina", "A 2 cm del ombligo", True)],
            [("Endometritis puerperal", 0, 3)],
            "Fiebre al 3.er día poscesárea con útero doloroso: endometritis hasta demostrar lo contrario."))

# SP-056 · Plan operativo anual · FASES
S("fases", "SP-056", "Para elaborar el plan operativo anual de un establecimiento I-4 se empieza por identificar los problemas sanitarios",
  "Gestión en salud · planificación",
  ("Plan operativo anual (POA)", ["Herramienta de corto plazo que traduce los problemas de salud en metas y actividades con presupuesto.",
                                  "Todo parte del diagnóstico: sin problemas definidos no hay objetivos que medir."]),
  ("Jefe de un establecimiento I-4", ["Médico serumista.", "Debe presentar el plan operativo anual."]),
  ["Orden: diagnóstico (problemas) → objetivos y metas → actividades → recursos y presupuesto → monitoreo y evaluación.",
   "El ASIS local es la fuente para identificar y priorizar problemas.",
   "Las metas deben ser medibles (indicadores) y alcanzables con los recursos."],
  MINSA + ", directivas de planeamiento y presupuesto por resultados; CEPLAN (2024).",
  op=("¿Con qué se inicia?", ["Viene después del diagnóstico", "Sí: el primer paso", "Viene después de las metas", "Va al final, con el presupuesto",
                              "No es parte del plan"]),
  d=dict(rotulo="Pasos del plan operativo", ans=0,
         fases=[("1.º", "Diagnóstico", "PROBLEMAS", ["Identificar y priorizar", "Este caso"]),
                ("2.º", "Objetivos", "METAS", ["Medibles"]),
                ("3.º", "Programación", "ACTIVIDADES", ["Quién, cuándo"]),
                ("4.º", "Presupuesto", "RECURSOS", ["Personal, insumos"])]))

# PSI-015 · Conducta purgativa: alcalosis hipoclorémica · TARJETAS + DSM + foto real
S("tarjetas", "PSI-015", "Adolescente con IMC 15 que se provoca vómitos: alcalosis metabólica hipoclorémica",
  "Trastornos de la conducta alimentaria · complicaciones",
  ("Vómitos autoinducidos", ["Al vomitar se pierde HCl: sube el bicarbonato y baja el cloro (alcalosis hipoclorémica).",
                             "El riñón intenta ahorrar volumen y pierde potasio: hipopotasemia (riesgo de arritmia)."]),
  ("Adolescente de 13 años", ["Hospitalizada por deshidratación y desnutrición; IMC 15.", "Se provoca vómitos con frecuencia."]),
  ["IMC bajo + purgas = anorexia nerviosa tipo purgativo (no bulimia, que tiene peso normal).",
   "Corregir con suero salino y potasio; vigilar el síndrome de realimentación (fósforo).",
   "Laxantes dan lo contrario: acidosis metabólica hipopotasémica."],
  "DSM-5-TR (2022); " + NICE + " NG69, trastornos alimentarios (2020); APA (2023).",
  op=("¿Trastorno?", ["Daría el abuso de laxantes, no el vómito", "No: el vómito alcaliniza", "No: el cloro baja", "Sí: pierde HCl",
                      "No: no hay hipoventilación"]),
  d=dict(rotulo="Conducta de purga: ¿qué trastorno ácido-base?", ans=0,
         cards=[dict(titulo="Vómitos", datos=[("pH", "Alcalosis", True), ("Cloro", "Bajo", True), ("Potasio", "Bajo", True)],
                     pie="Este caso."),
                dict(titulo="Laxantes", datos=[("pH", "Acidosis", False), ("Pierde", "Bicarbonato en heces", False), ("Potasio", "Bajo", False)],
                     pie="Diarrea."),
                dict(titulo="Diuréticos", datos=[("pH", "Alcalosis", False), ("Cloro urinario", "Alto", False), ("Potasio", "Bajo", False)],
                     pie="Contracción."),
                dict(titulo="Ayuno extremo", datos=[("pH", "Acidosis", False), ("Por", "Cetonas", False), ("Riesgo", "Realimentación", False)],
                     pie="Cetosis.")]),
  escala=dict(nombre="Gravedad de la anorexia nerviosa por IMC (DSM-5-TR)", orden=True,
              que="En adultos; en adolescentes se usan percentiles, pero sirve de guía.",
              grados=[("IMC ≥ 17", "Leve", ["Ambulatorio"]), ("IMC 16-16,99", "Moderada", ["Ambulatorio intensivo"]),
                      ("IMC 15-15,99", "Grave", ["Hospitalizar si hay inestabilidad"]), ("IMC < 15", "Extrema", ["Hospitalizar"])],
              caso=2, porque=[("IMC 15", True), ("Deshidratación y vómitos: inestable", True)],
              conducta="Hospitalizar, corregir líquidos y potasio, realimentar con cuidado."),
  banda=B("Signo de los vómitos provocados", P("russell.jpg", 300, 225, [
            ("texto", 0.50, 0.92, "callos en los nudillos")],
          credito="Kyukyusha" + CC + "dominio público"),
          [("Signo de Russell", "Callos y erosiones en el dorso de los nudillos por meter la mano a la boca."),
           ("Parótidas grandes", "Hipertrofia por los vómitos repetidos."),
           ("Erosión dental", "El ácido daña el esmalte por dentro."),
           ("Laboratorio", "Alcalosis, cloro y potasio bajos.")],
          pie="Foto de otra persona.", ans=0))

# PED-092 · Cardiopatía congénita cianótica · ÁRBOL + tamizaje con oximetría
S("arbol", "PED-092", "Recién nacido con cianosis a las 3 horas que no mejora con oxígeno: cardiopatía cianótica (de las opciones, la estenosis pulmonar)",
  "Cardiopatías congénitas · cianosis neonatal",
  ("Cianosis central del recién nacido", ["Si no mejora con oxígeno al 100 %, la sangre no pasa por los pulmones: causa cardiaca.",
                                          "Las cardiopatías cianóticas dependen del ductus: al cerrarse empeoran."]),
  ("Recién nacido a término", ["Cianosis perioral y ungueal a las 3 horas de vida.", "El oxígeno no mejora el color ni la saturación."]),
  ["Prueba de hiperoxia: PaO₂ < 100 mmHg con O₂ al 100 % = cardiopatía.",
   "Prostaglandina E1 EV para mantener el ductus abierto; ecocardiograma urgente.",
   "CIA, CIV y ductus son acianóticas (cortocircuito izquierda-derecha)."],
  AAP + ", tamizaje de cardiopatía congénita crítica (2018, act. 2023); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: acianótica", "No: acianótica", "Sí: cianótica; la crítica depende del ductus", "No: acianótica",
                        "No: mejoraría con oxígeno"]),
  arbol=Q("Cianosis en el recién nacido: ¿mejora con oxígeno al 100 %?", [
      L("No (este caso)", "CARDIOPATÍA CIANÓTICA", ["Prostaglandina E1", "Ecocardiograma"], path=True),
      L("Sí", "Causa pulmonar", ["Neumonía, membrana hialina"])], path=True),
  escala=dict(nombre="Tamizaje de cardiopatía crítica con oximetría (AAP)", orden=True,
              que="Mano derecha y un pie, después de las 24 h (o antes si hay síntomas).",
              grados=[("≥ 95 % y diferencia ≤ 3 %", "Negativo", ["Alta"]),
                      ("90-94 % o diferencia > 3 %", "Repetir", ["Hasta 2 veces, en 1 h"]),
                      ("< 90 %", "Positivo", ["Ecocardiograma urgente"])],
              caso=2, porque=[("Cianosis visible: saturación muy baja", True), ("No mejora con oxígeno", True)],
              conducta="Prostaglandina E1 y ecocardiograma urgente."))

# PSI-016 · Esquizofrenia paranoide · ÁRBOL + duración
S("arbol", "PSI-016", "Médico con 3 meses de aislamiento, ideas delirantes de grandeza y persecución y desaseo: esquizofrenia (tipo paranoide)",
  "Trastornos psicóticos · esquizofrenia",
  ("Esquizofrenia con predominio de delirios", ["Psicosis con delirios de persecución o grandeza, a veces alucinaciones, sin un trastorno del ánimo que los explique.",
                                               "El DSM-5-TR ya no usa subtipos («paranoide»), pero el término sigue en la CIE-10 y en los exámenes."]),
  ("Médico de 45 años", ["3 meses de aislamiento; cree haber inventado una vacuna por la que le darán el Nobel.",
                         "Cree que lo quieren matar y que tiene micrófonos y cámaras en casa; desaseado y ansioso."]),
  ["Descartar causas orgánicas y drogas (TC o RM, laboratorio, tóxicos).",
   "Antipsicótico de segunda generación (risperidona, olanzapina, aripiprazol) + psicoterapia y apoyo familiar.",
   "Con menos de 6 meses de evolución, el DSM-5-TR lo llama trastorno esquizofreniforme."],
  "DSM-5-TR (2022); CIE-11; APA, esquizofrenia (2020).",
  op=("¿Diagnóstico?", ["No: agotamiento, sin delirios", "No: sin ánimo deprimido", "Sí: delirios de persecución y grandeza",
                        "No: sin manía ni depresión", "No: sin cambio de conducta social desinhibida"]),
  arbol=Q("Delirios sin trastorno del ánimo ni causa orgánica: ¿cuánto tiempo?", [
      L("Meses, con aislamiento (este caso)", "ESQUIZOFRENIA", ["Antipsicótico", "Psicoterapia"], path=True),
      L("Con manía o depresión", "Trastorno del ánimo con psicosis", ["Estabilizador o antidepresivo"])], path=True),
  escala=dict(nombre="Psicosis según la duración (DSM-5-TR)", orden=True,
              que="Mismo tipo de síntomas; el nombre cambia con el tiempo.",
              grados=[("< 1 mes", "Trastorno psicótico breve", ["Recupera por completo"]),
                      ("1-6 meses", "Trastorno esquizofreniforme", ["Puede evolucionar a esquizofrenia"]),
                      ("≥ 6 meses", "Esquizofrenia", ["Incluye pródromo y residual"])],
              caso=1, porque=[("3 meses de síntomas", True), ("Entre las opciones, la que corresponde es esquizofrenia", True)],
              conducta="Antipsicótico de segunda generación y seguimiento."),
  triada=TR([("Delirios", "Grandeza y persecución", True), ("Alucinaciones", "No se describen", None), ("Discurso desorganizado", "No se describe", None),
             ("Conducta desorganizada", "Desaseado", True), ("Síntomas negativos", "Aislamiento", True)],
            [("Criterio A del DSM-5-TR (2 o más)", 0, 4)],
            "Al menos uno debe ser delirios, alucinaciones o discurso desorganizado."))

# OFT-019 · Midriasis farmacológica · TARJETAS + foto real
S("tarjetas", "OFT-019", "Midriasis bilateral arreactiva con fotofobia tras un examen de retina, sin otros signos: midriasis farmacológica",
  "Neurooftalmología · anisocoria y midriasis",
  ("Midriasis farmacológica", ["Gotas para el fondo de ojo (tropicamida, fenilefrina) dilatan la pupila por horas.",
                               "Pupilas grandes que no responden a la luz, sin ptosis ni alteración de los movimientos oculares."]),
  ("Varón de 45 años", ["Examen de retina; luego fotofobia y visión borrosa.", "Midriasis bilateral arreactiva; sin otro trastorno oculomotor."]),
  ["Prueba de pilocarpina 1 %: si NO se contrae, es farmacológica; si se contrae, es nerviosa (III par).",
   "Desaparece en 4-24 horas; lentes oscuros y no conducir.",
   "III par: midriasis con ptosis y ojo «abajo y afuera»; si duele, descartar aneurisma."],
  "AAO, neurooftalmología (2024); Kanski, oftalmología clínica 10.ª ed.",
  op=("¿Diagnóstico?", ["Sí: gotas del examen de retina", "No: tendría ptosis y estrabismo", "No: pupilas pequeñas que acomodan",
                        "No: pupila pequeña con ptosis", "No: ojo rojo y doloroso"]),
  d=dict(rotulo="Pupila anormal: ¿cuál?", ans=0,
         cards=[dict(titulo="Farmacológica", datos=[("Pupila", "Grande, ambas", True), ("Antes", "Gotas", True), ("Pilocarpina 1 %", "No contrae", True)],
                     pie="Este caso."),
                dict(titulo="Parálisis del III par", datos=[("Pupila", "Grande, un ojo", False), ("Además", "Ptosis, ojo afuera", False), ("Pilocarpina", "Contrae", False)],
                     pie="Aneurisma."),
                dict(titulo="Horner", datos=[("Pupila", "Pequeña", False), ("Además", "Ptosis leve", False), ("Sudor", "Anhidrosis", False)],
                     pie="Simpático."),
                dict(titulo="Argyll Robertson", datos=[("Pupila", "Pequeña, irregular", False), ("Luz", "No reacciona", False), ("Acomodación", "Sí", False)],
                     pie="Neurosífilis.")]),
  banda=B("Así se ve la midriasis", P("midriasis.jpg", 400, 115, [
            ("flechas", [(0.19, 0.52), (0.80, 0.52)], 0.50, 0.50, "pupilas dilatadas")],
          credito="Soldier of Wasteland" + CC + "CC BY-SA 4.0"),
          [("Pupilas grandes en ambos ojos", "Casi no se ve el iris."),
           ("No reaccionan a la luz", "Por eso molesta la luz (fotofobia)."),
           ("Visión borrosa de cerca", "Las gotas también paralizan la acomodación."),
           ("Sin ptosis ni estrabismo", "Lo que descarta el III par.")],
          pie="Foto de otra persona.", ans=0))

# GAS-032 · Úlcera duodenal · ÁRBOL + signos de alarma + endoscopía real
S("arbol", "GAS-032", "Dolor urente en el epigastrio 5-6 horas después de comer que lo despierta de noche, sin baja de peso ni disfagia: úlcera péptica (duodenal)",
  "Enfermedad ácido-péptica · úlcera duodenal",
  ("Úlcera duodenal", ["Dolor urente que aparece con el estómago vacío (2-5 h tras comer) y de madrugada; mejora al comer.",
                       "Casi siempre por H. pylori o AINE."]),
  ("Varón de 45 años", ["1 mes de dolor urente epigástrico 5-6 h después de comer; a veces lo despierta.",
                        "Sin baja de peso ni disfagia; examen normal."]),
  ["Sin signos de alarma y < 60 años: buscar H. pylori (prueba de aliento o antígeno en heces) y tratar.",
   "Con alarma o ≥ 60 años: endoscopía.",
   "Erradicación: cuádruple con bismuto 14 días; confirmar la curación 4 semanas después."],
  "ACG/CAG, dispepsia (2017); ACG, H. pylori (2024); Maastricht VI (2022).",
  op=("¿Diagnóstico?", ["No: dolor más difuso y breve", "No: pirosis y regurgitación", "Sí: dolor que despierta, mejora al comer",
                        "No: sin alarma (peso, disfagia)", "No: sin alcohol ni esteatorrea"]),
  arbol=Q("Dispepsia: ¿signos de alarma o ≥ 60 años?", [
      L("No (este caso)", "BUSCAR Y TRATAR H. PYLORI", ["Aliento o antígeno", "IBP"], path=True),
      L("Sí", "Endoscopía", ["Biopsias"])], path=True),
  triada=TR([("Baja de peso", "No", False), ("Disfagia", "No", False), ("Vómitos persistentes", "No", False),
             ("Sangrado o anemia", "No", False), ("Edad ≥ 60 años", "45 años", False)],
            [("Signos de alarma", 0, 4)],
            "Ninguno presente: no requiere endoscopía de entrada."),
  banda=B("Así se ve una úlcera", P("ulcera_endo.jpg", 260, 260, [
            ("flecha", 0.55, 0.40, 0.30, 0.88, "fondo de la úlcera")],
          credito="Samir" + CC + "CC BY-SA 3.0"),
          [("Pérdida de la mucosa", "Fondo blanquecino de fibrina."),
           ("Bordes netos", "Elevados por el edema."),
           ("Duodenal: casi nunca maligna", "La gástrica sí se biopsia."),
           ("Cicatriza", "Con IBP y erradicación de H. pylori.")],
          pie="Úlcera gástrica de otro paciente.", ans=0))

# PED-093 · Neumonía neonatal: RPM prolongada · TARJETAS
S("tarjetas", "PED-093", "Recién nacido de 36 semanas con dificultad respiratoria leve e hipotermia, madre con RPM > 18 horas: neumonía neonatal (sepsis precoz)",
  "Infecciones neonatales · neumonía y sepsis precoz",
  ("Neumonía neonatal precoz", ["Se adquiere al nacer por gérmenes del canal (estreptococo B, E. coli, Listeria).",
                                "La RPM > 18 horas, la fiebre materna y la prematuridad aumentan el riesgo."]),
  ("Recién nacido de 36 semanas, 12 horas de vida", ["Dificultad respiratoria leve e hipotermia.", "Madre con RPM de más de 18 horas."]),
  ["Hemocultivo, hemograma, PCR y Rx de tórax.",
   "Ampicilina + gentamicina EV de inmediato; ajustar con cultivos.",
   "La hipotermia o la inestabilidad térmica en el recién nacido son signos de sepsis."],
  AAP + ", sepsis bacteriana de inicio precoz (2018, act. 2024); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Más en < 34 semanas, sin RPM", "Tras cesárea; sin hipotermia", "Más en < 32 semanas; neurológica",
                        "Sí: RPM > 18 h + hipotermia", "Puede acompañar, no explica el cuadro"]),
  d=dict(rotulo="Dificultad respiratoria en el recién nacido", ans=0,
         cards=[dict(titulo="Neumonía / sepsis", datos=[("Antes", "RPM > 18 h", True), ("Signo", "Hipotermia", True), ("Trato", "Ampicilina + gentamicina", True)],
                     pie="Este caso."),
                dict(titulo="Membrana hialina", datos=[("Edad", "< 34 semanas", False), ("Rx", "Vidrio esmerilado", False), ("Trato", "Surfactante", False)],
                     pie="Prematuro."),
                dict(titulo="Taquipnea transitoria", datos=[("Antes", "Cesárea", False), ("Curso", "< 72 h", False), ("Fiebre", "No", False)],
                     pie="Benigna."),
                dict(titulo="Hipoglucemia", datos=[("Riesgo", "Madre diabética", False), ("Signos", "Temblor, apneas", False), ("Prueba", "Glucosa < 45", False)],
                     pie="Medir glucosa.")]))

# NEU-025 · TB latente en la gestante · ÁRBOL
S("arbol", "NEU-025", "Gestante asintomática con PPD positivo y Rx normal cuyo esposo tiene TB bacilífera: terapia preventiva con isoniacida",
  "Tuberculosis · infección latente en el embarazo",
  ("Infección tuberculosa latente en la gestante", ["Contacto de un caso bacilífero con PPD positivo, sin síntomas y con Rx normal (con protección abdominal).",
                                                    "La isoniacida es segura en el embarazo; el riesgo de enfermar es alto tras un contacto reciente."]),
  ("Gestante de 24 semanas", ["Asintomática; PPD positivo; Rx de tórax normal.", "Esposo con TB pulmonar BK positivo."]),
  ["Isoniacida 6 meses + piridoxina (vitamina B6).",
   "El esquema 3HP (rifapentina) no se recomienda en el embarazo.",
   "Vigilar hepatotoxicidad (transaminasas) sobre todo en el embarazo y el puerperio."],
  MINSA + ", NTS de atención integral de la tuberculosis (2023); " + OMS + ", tratamiento preventivo (2024); " + CDC + ".",
  op=("¿Conducta?", ["No: no previene la enfermedad", "No: Rx normal, sin síntomas", "Sí: previene la TB activa", "No: no tiene tos ni esputo",
                     "No: no se vacuna a adultos ni gestantes"]),
  arbol=Q("Contacto con PPD positivo: ¿síntomas o Rx anormal?", [
      L("No (este caso)", "ISONIACIDA + B6", ["6 meses"], path=True),
      L("Sí", "Estudiar TB activa", ["Baciloscopía, Xpert"])], path=True))

# END-021 · Síndrome del eutiroideo enfermo · TARJETAS
S("tarjetas", "END-021", "Paciente con colitis ulcerosa grave con T3 baja y T4 libre y TSH normales: síndrome del eutiroideo enfermo",
  "Tiroides · alteraciones en la enfermedad grave",
  ("Síndrome del eutiroideo enfermo", ["En una enfermedad grave el cuerpo convierte menos T4 en T3 y más en T3 inversa (rT3).",
                                       "Es una adaptación para ahorrar energía, no una enfermedad tiroidea."]),
  ("Varón de 45 años con colitis ulcerosa", ["Hospitalizado por exacerbación, consunción, dolor abdominal y apatía.",
                                             "T3 total y libre bajas; T4 libre y TSH normales."]),
  ["No se trata con hormona tiroidea: se trata la enfermedad de base.",
   "Repetir el perfil 4-6 semanas después de la recuperación.",
   "En los casos muy graves también baja la T4 (peor pronóstico)."],
  "ATA; " + HARRISON + "; Endotext, eutiroideo enfermo (2024).",
  op=("¿Diagnóstico?", ["No: TSH alta", "Sí: solo T3 baja en enfermo grave", "No: TSH alta y T4 normal", "No: TSH baja", "No: T4 libre baja"]),
  d=dict(rotulo="¿Qué perfil tiroideo es?", ans=0,
         cards=[dict(titulo="Eutiroideo enfermo", datos=[("TSH", "Normal", True), ("T4 libre", "Normal", True), ("T3", "Baja (rT3 alta)", True)],
                     pie="Este caso."),
                dict(titulo="Hipotiroidismo primario", datos=[("TSH", "Alta", False), ("T4 libre", "Baja", False), ("Trato", "Levotiroxina", False)],
                     pie="Tiroides."),
                dict(titulo="Hipotiroidismo subclínico", datos=[("TSH", "Alta", False), ("T4 libre", "Normal", False), ("Trato", "Según TSH", False)],
                     pie="Leve."),
                dict(titulo="Hipotiroidismo central", datos=[("TSH", "Baja o normal", False), ("T4 libre", "Baja", False), ("Causa", "Hipófisis", False)],
                     pie="RM.")]))

# GIN-081 · Amenaza de aborto: ecografía · ÁRBOL + formas clínicas + eco real
S("arbol", "GIN-081", "Amenorrea de 9 semanas con cólico y sangrado escaso, cuello cerrado y estable: amenaza de aborto, pedir ecografía transvaginal",
  "Hemorragias de la primera mitad · amenaza de aborto",
  ("Amenaza de aborto", ["Sangrado del primer trimestre con cuello cerrado y embrión vivo.",
                         "La ecografía transvaginal confirma que el embarazo está en el útero y es viable (y descarta un ectópico)."]),
  ("Mujer de 25 años", ["Amenorrea de 9 semanas; 24 h de cólico en hipogastrio y sangrado escaso.",
                        "Estable; cuello blando, cerrado, violáceo, con escaso sangrado."]),
  ["Eco transvaginal: saco en el útero, embrión con latido (visible desde ~6 semanas).",
   "Con latido: control, evitar esfuerzos; la progesterona solo si tuvo abortos previos (evidencia limitada).",
   "Sin saco en el útero con β-hCG > 3500: pensar en embarazo ectópico."],
  ACOG + ", pérdida temprana del embarazo (2018, reafirmada 2024); " + NICE + " NG126 (2023).",
  op=("¿Procedimiento?", ["No: técnica abandonada", "Sí: ubica y ve el latido", "Útil junto a la eco, no sola", "No: el cuello está cerrado",
                          "No sin confirmar viabilidad"]),
  arbol=Q("Sangrado en el primer trimestre con cuello cerrado: ¿eco con embrión vivo en el útero?", [
      L("Pedir la eco (este caso)", "ECOGRAFÍA TRANSVAGINAL", ["Latido = amenaza de aborto"], path=True),
      L("Útero vacío", "Descartar ectópico", ["β-hCG seriada"])], path=True),
  escala=ABORTO(0, [("Cuello cerrado", True), ("Sangrado escaso", True), ("Falta confirmar embrión vivo con la eco", True)],
                "Ecografía transvaginal y control."),
  banda=B("Así se ve en la ecografía", P("saco.jpg", 330, 216, [
            ("flecha", 0.44, 0.36, 0.20, 0.10, "saco gestacional")],
          credito="Nevit Dilmen" + CC + "CC BY-SA 3.0"),
          [("Saco dentro del útero", "Descarta el embarazo ectópico."),
           ("Embrión con latido", "Desde las 6-7 semanas; confirma la viabilidad."),
           ("Hematoma", "Una zona oscura al lado del saco explica el sangrado."),
           ("Sin latido con LCN ≥ 7 mm", "Aborto retenido.")],
          pie="Ecografía temprana de otra gestante.", ans=0))
