"""Entrega 3 · tanda t04 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from esc28 import HTA_EMB

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
SABISTON = "Sabiston Tratado de Cirugía 21.ª ed."
PMC_BARRETT = "Leonard et al. · Dis Esophagus 2026 · PMC13313527 (PubMed Central) · CC BY 4.0"

# GIN-150 · Obesidad pregestacional · CASCADA
S("cascada", "GIN-150", "La obesidad previa al embarazo no corregida se asocia a diabetes gestacional y a feto macrosómico",
  "Embarazo y obesidad",
  ("Obesidad pregestacional", ["IMC ≥ 30 antes del embarazo: más resistencia a la insulina, diabetes gestacional, preeclampsia y cesárea.",
                               "La glucosa materna alta pasa al feto; su insulina alta lo hace crecer de más (macrosomía > 4000 g)."]),
  ("Pregunta de teoría", ["¿Con qué se asocia la obesidad no corregida", "antes del embarazo?"]),
  ["Consejería preconcepcional: bajar de peso antes de embarazarse y ácido fólico 5 mg (más riesgo de defectos del tubo neural).",
   "Tamizar diabetes desde el primer control (glucosa o HbA1c) y repetir con PTOG 75 g a las 24-28 semanas.",
   "Ganancia de peso recomendada con IMC ≥ 30: 5-9 kg (IOM)."],
  ACOG + ", obesidad y embarazo (2021); IOM, ganancia de peso en el embarazo (2009); " + WILLIAMS + ".",
  op=("¿Con qué se asocia?", ["Sí: más resistencia a la insulina", "No: la obesidad no causa hipotiroidismo", "No: no se asocia",
                              "No: con diabetes el feto suele crecer de más", "No: no es lo típico"]),
  d=dict(rotulo="De la obesidad al bebé grande", cabeceras=("Mecanismo", "Resultado"),
         pasos=[("Tejido graso en exceso", "Libera ácidos grasos y citocinas", [("Resistencia a la insulina", "", False)]),
                ("La placenta suma hormonas antiinsulina", "Lactógeno placentario, cortisol", [("Diabetes gestacional", "Riesgo 2-4 veces mayor", True)]),
                ("La glucosa materna pasa al feto", "La insulina materna no cruza", [("Hiperinsulinemia fetal", "", False)]),
                ("La insulina fetal actúa como hormona de crecimiento", "Grasa y órganos grandes", [("Feto macrosómico", "> 4000 g; distocia de hombros", True)])],
         veredicto=("Obesidad pregestacional → diabetes gestacional → macrosomía", "Por eso se tamiza la diabetes desde el primer control.")))

# GIN-151 · LES con antifosfolípidos: DIU de cobre · TARJETAS + criterios OMS
S("tarjetas", "GIN-151", "Mujer con lupus y anticuerpos antifosfolípidos que pide anticoncepción: DIU de cobre (los estrógenos están contraindicados por riesgo de trombosis)",
  "Anticoncepción en mujeres con enfermedades",
  ("Criterios médicos de elegibilidad (OMS)", ["Clasifican cada método de 1 (sin restricción) a 4 (no usar) según la enfermedad.",
                                              "LES con antifosfolípidos positivos: estrógeno = categoría 4 (trombosis)."]),
  ("Mujer de 27 años, nulípara", ["Lupus eritematoso con anticuerpos antifosfolípidos.", "Desea un método de planificación familiar."]),
  ["DIU de cobre: categoría 1 en LES con antifosfolípidos; muy eficaz y sin hormonas.",
   "Progestágenos solos (minipíldora, implante, DIU de levonorgestrel): categoría 3 con antifosfolípidos.",
   "Ligadura: válida pero definitiva; en una nulípara de 27 años se prefiere un método reversible."],
  OMS + ", criterios médicos de elegibilidad (5.ª ed., 2015; act.); " + CDC + ", US MEC (2024); EULAR, salud reproductiva en LES (2017).",
  op=("¿Método?", ["Categoría 3 con antifosfolípidos", "Definitivo: no ideal en nulípara joven", "No: estrógeno = categoría 4",
                   "Sí: categoría 1, sin hormonas", "No: también lleva estrógeno"]),
  d=dict(rotulo="Métodos en LES con antifosfolípidos (OMS)", ans=0,
         cards=[dict(titulo="DIU de cobre", datos=[("Categoría", "1 (usar)", True), ("Hormonas", "No", True), ("Eficacia", "> 99 %", True)], pie="Este caso."),
                dict(titulo="Solo progestágeno", datos=[("Categoría", "3", False), ("Riesgo", "Trombosis posible", False), ("Ej.", "Minipíldora, implante", False)], pie="Con cautela."),
                dict(titulo="Combinados (AOC, anillo)", datos=[("Categoría", "4 (no usar)", False), ("Riesgo", "Trombosis", False), ("Por", "Estrógeno", False)], pie="Contraindicados."),
                dict(titulo="Ligadura tubárica", datos=[("Categoría", "1", False), ("Tipo", "Definitivo", False), ("Ideal", "Paridad completa", False)], pie="No reversible.")]),
  banda=B("El DIU de cobre", P("diu.jpg", 210, 297, [], credito="Hic et nunc" + CC + "dominio público"),
          [("Sin hormonas", "El cobre altera los espermatozoides."),
           ("Dura 10-12 años", "Reversible al retirarlo."),
           ("Efecto adverso", "Más sangrado menstrual y cólicos.")],
          pie="Dispositivo real."))

# CB-057 · Células gustativas neuroepiteliales · CASCADA + botón gustativo rotulado
S("cascada", "CB-057", "Los receptores del sabor están en las células neuroepiteliales (células receptoras) de los botones gustativos de la lengua",
  "Fisiología sensorial · gusto",
  ("Botón gustativo", ["Grupo de 50-150 células receptoras (neuroepiteliales) con microvellosidades en el poro gustativo.",
                       "Viven ~10 días y se renuevan desde las células basales (por eso el gusto se recupera tras la COVID-19)."]),
  ("Pregunta de teoría", ["Pérdida del gusto en la COVID-19.", "¿Qué células tienen los receptores del sabor?"]),
  ["Dulce, amargo y umami: receptores acoplados a proteína G; salado y ácido: canales iónicos.",
   "Dos tercios anteriores de la lengua: nervio facial (cuerda del tímpano); tercio posterior: glosofaríngeo.",
   "Todo llega al núcleo del tracto solitario (bulbo) → tálamo → corteza gustativa (ínsula)."],
  "Guyton y Hall, Tratado de fisiología médica 14.ª ed.; Ross, Histología 8.ª ed.",
  op=("¿Tipo de células?", ["No: células del músculo en formación", "No: precursoras de neuronas", "No: células madre (las basales lo son)",
                            "Sí: tienen los receptores del sabor", "No: tejido conectivo"]),
  d=dict(rotulo="Del sabor a la corteza", cabeceras=("Paso", "Dónde ocurre"),
         pasos=[("La molécula entra por el poro", "Disuelta en la saliva", [("Poro gustativo", "", False)]),
                ("Se une al receptor", "En las microvellosidades", [("Célula neuroepitelial (receptora)", "Este caso", True)]),
                ("La célula libera neurotransmisor", "ATP o serotonina", [("Nervio aferente: VII, IX o X", "", False)]),
                ("Viaja al bulbo y a la corteza", "Núcleo solitario → tálamo → ínsula", [("Percepción del sabor", "", False)])],
         veredicto=("Las células receptoras (neuroepiteliales) tienen los receptores del sabor", "Se renuevan desde las células basales.")),
  banda=B("Así es un botón gustativo", PA("boton_gustativo.jpg", 400, [], credito="NEUROtiker" + CC + "CC BY-SA 3.0", fondo="#ffffff"),
          [("Célula receptora", "Neuroepitelial: tiene los receptores."),
           ("Poro gustativo", "Por donde entra la molécula disuelta."),
           ("Célula basal", "Célula madre que repone las receptoras."),
           ("Nervio aferente", "Lleva el impulso al cerebro.")],
          pie="Esquema rotulado en español."))

# NRL-042 · Miastenia gravis · CUADRÍCULA de enfermedades de la placa + dibujo
S("cuadricula", "NRL-042", "Mujer con ptosis y diplopía que empeoran con el esfuerzo por una enfermedad autoinmune de la placa: miastenia gravis, destrucción de los receptores de acetilcolina",
  "Unión neuromuscular · miastenia gravis",
  ("Miastenia gravis", ["Anticuerpos contra el receptor nicotínico de acetilcolina (85 %) o contra MuSK: hay menos receptores útiles.",
                        "Debilidad que empeora al usar el músculo y mejora con el reposo; empieza en ojos (ptosis, diplopía)."]),
  ("Mujer de 56 años", ["Caída paulatina de párpados y visión doble.", "Enfermedad autoinmune de la placa mioneural."]),
  ["Confirmar: anticuerpos anti-AChR, estimulación repetitiva o fibra única; prueba del hielo en la ptosis.",
   "TC de tórax: timoma o hiperplasia del timo (timectomía).",
   "Tratamiento: piridostigmina + inmunosupresión (prednisona, azatioprina); crisis: IgIV o plasmaféresis."],
  "MGFA, consenso internacional de miastenia (2020; act. 2025); " + HARRISON + ".",
  op=("¿Defecto molecular?", ["No: lo inhiben los fármacos que la tratan", "No: es el botulismo", "Sí: anticuerpos contra el receptor",
                              "No: los canales de calcio son presinápticos (Lambert-Eaton)", "No: no es el mecanismo"],
      {3: "Destrucción de canales de calcio postsinápticos"}),
  d=dict(rotulo="Enfermedades de la unión neuromuscular: dónde falla",
         celdas=[("Miastenia gravis", ["Anticuerpos contra el receptor de ACh", "Empeora con el esfuerzo; ojos primero"], None, True),
                 ("Lambert-Eaton", ["Anticuerpos contra canales de calcio presinápticos", "Mejora con el esfuerzo; cáncer de pulmón"], None, False),
                 ("Botulismo", ["La toxina impide liberar ACh", "Descendente, pupilas dilatadas"], None, False),
                 ("Organofosforados", ["Inhiben la acetilcolinesterasa", "Exceso de ACh: miosis, secreciones"], None, False)],
         veredicto=("Ptosis + diplopía fluctuantes por autoinmunidad = miastenia gravis", "Defecto: destrucción y bloqueo de los receptores de acetilcolina.")),
  banda=B("Dónde actúa cada enfermedad", PA("dib_placa_motora.jpg", 400, [], credito=PROPIO, fondo="#ffffff"),
          [("Receptores (verde)", "Los anticuerpos de la miastenia los destruyen."),
           ("Canales de calcio", "Los ataca el Lambert-Eaton (presináptico)."),
           ("Acetilcolinesterasa", "La piridostigmina la inhibe y deja más ACh.")],
          pie="Esquema."))

# GIN-152 · HTA crónica con IECA: metildopa · TARJETAS + clasificación
S("tarjetas", "GIN-152", "Gestante de 10 semanas con hipertensión crónica que usa captopril: suspender el IECA y cambiar a metildopa (seguro en el embarazo)",
  "Hipertensión en el embarazo · fármacos",
  ("Antihipertensivos en el embarazo", ["Seguros: metildopa, labetalol y nifedipino de acción prolongada.",
                                        "Prohibidos: IECA y ARA II (dañan el riñón fetal: oligohidramnios, hipoplasia pulmonar, anuria)."]),
  ("Mujer de 39 años, multigesta", ["Usa captopril; primer control a las 10 semanas.", "PA 150/95, asintomática."]),
  ["Suspender el captopril de inmediato y explicar; ecografía para controlar el crecimiento.",
   "Meta de PA < 140/90 (CHAP 2022); aspirina 100-150 mg nocturna desde las 12-16 semanas (riesgo de preeclampsia).",
   "Hidralazina EV o labetalol EV: para la crisis (≥ 160/110), no para el control crónico."],
  ACOG + ", hipertensión crónica en el embarazo (2019; act. 2022); ISSHP (2021); " + MINSA + ".",
  op=("¿Más seguro?", ["Sí: el más usado y estudiado", "No: IECA prohibido", "No: es para la crisis, no para el control crónico",
                       "También es seguro (acción prolongada); la clave pedida es metildopa", "No: IECA prohibido"]),
  d=dict(rotulo="Antihipertensivos y embarazo", ans=0,
         cards=[dict(titulo="Metildopa", datos=[("Seguridad", "Muy estudiada", True), ("Uso", "Control crónico", True), ("Efecto", "Somnolencia", True)], pie="Este caso."),
                dict(titulo="Labetalol", datos=[("Seguridad", "Segura", False), ("Uso", "Crónico y crisis EV", False), ("Evitar", "Asma", False)], pie="Alternativa."),
                dict(titulo="Nifedipino AP", datos=[("Seguridad", "Segura", False), ("Uso", "Crónico; crisis VO", False), ("Efecto", "Cefalea, edema", False)], pie="Alternativa."),
                dict(titulo="IECA / ARA II", datos=[("Seguridad", "PROHIBIDOS", False), ("Daño", "Riñón fetal", False), ("Ej.", "Captopril, enalapril", False)], pie="Suspender ya.")]),
  escala=HTA_EMB(0, [("PA 150/95 a las 10 semanas (antes de las 20)", True), ("Ya usaba antihipertensivo", True)],
                 "Cambiar a metildopa, aspirina en dosis baja y vigilar preeclampsia sobreagregada."))

# GIN-153 · Embarazo adolescente: menor riesgo de diabetes · BALANZA
S("balanza", "GIN-153", "La gestante adolescente tiene más riesgo de anemia, preeclampsia y parto pretérmino; la complicación a la que está menos expuesta por su edad es la diabetes",
  "Embarazo adolescente",
  ("Riesgos del embarazo adolescente", ["Inmadurez biológica, nutrición pobre y control prenatal tardío.",
                                        "La diabetes gestacional aumenta con la edad y el peso: es menos frecuente en adolescentes."]),
  ("Gestante de 16 años, 15 semanas", ["Pregunta a qué complicación está menos expuesta.", ""]),
  ["Más riesgo: anemia, preeclampsia, parto pretérmino, bajo peso al nacer, desproporción y depresión.",
   "Control prenatal temprano, hierro y ácido fólico, consejería y apoyo psicosocial.",
   "Investigar violencia sexual en menores de 14 años (obligación de notificar)."],
  OMS + ", embarazo adolescente (2024); " + MINSA + ", atención integral del adolescente.",
  op=("¿Menos expuesta?", ["No: más anemia", "No: más preeclampsia", "No: más pretérmino", "Sí: la diabetes es menos frecuente en jóvenes", "No: más preeclampsia"]),
  d=dict(rotulo="Riesgos de la gestante adolescente", gana="izq", pregunta="¿A qué está más expuesta?",
         izq=dict(titulo="Más riesgo", peso="MÁS", items=["Anemia", "Preeclampsia", "Parto pretérmino y bajo peso", "Desproporción cefalopélvica"]),
         der=dict(titulo="Menos riesgo", peso="MENOS", items=["Diabetes gestacional", "Malformaciones cromosómicas (Down)", "Miomas"]),
         veredicto=("La diabetes es a lo que menos está expuesta", ["La diabetes gestacional aumenta con la edad y la obesidad."])))

# CIR-087 · Claudicación intermitente · REGLA (ITB) + Fontaine
S("regla", "CIR-087", "Diabético e hipertenso de 74 años con dolor de pantorrillas al caminar que cede al reposo y pulso pedio disminuido: claudicación intermitente por enfermedad arterial periférica",
  "Enfermedad arterial periférica",
  ("Claudicación intermitente", ["Las arterias estrechadas no dan más sangre al caminar: dolor en la pantorrilla que cede en minutos al detenerse.",
                                 "Se confirma con el índice tobillo-brazo (ITB) < 0,9."]),
  ("Varón de 74 años, diabético e hipertenso", ["Dolor de pantorrillas al caminar que calma al reposo; pulso pedio disminuido.",
                                                "Angio-TC: tibial posterior calcificada con estenosis < 50 %."]),
  ["ITB en todos; en diabéticos con arterias calcificadas (ITB > 1,3) usar el índice dedo-brazo.",
   "Dejar de fumar, caminar supervisado 30-45 min 3 veces/semana, estatina de alta intensidad y antiagregante.",
   "Revascularizar si limita la vida pese al ejercicio, o si hay dolor en reposo o úlceras (isquemia crítica)."],
  ESC + ", enfermedad arterial periférica (2024); AHA/ACC, EAP (2024).",
  op=("¿Diagnóstico?", ["Sí: dolor al caminar que cede al reposo + pulso bajo", "No: deportistas jóvenes, sin pulso disminuido",
                        "No: mejora al elevar la pierna, no al detenerse", "No: masa en la fosa poplítea", "No: no cede al reposo"]),
  d=dict(rotulo="Índice tobillo-brazo (ITB)",
         reglas=[dict(nombre="ITB = PA sistólica del tobillo / PA sistólica del brazo", que="Se mide con Doppler en reposo.",
                      min=0.2, max=1.6, fmt="{}", ticks=[0.4, 0.7, 0.9, 1.3],
                      bandas=[(0.2, 0.4, "< 0,4 grave", 3), (0.4, 0.9, "0,4-0,9 EAP", 2), (0.9, 1.3, "Normal", 0), (1.3, 1.6, "> 1,3 rígidas", 1)],
                      caso=None, pie="Este caso: diabético con arterias calcificadas → el ITB puede salir falsamente normal o > 1,3", pie_on=True)],
         claves_titulo="Tratamiento",
         claves=[("Caminar supervisado", ["30-45 min, 3 veces por semana"], True), ("Estatina + antiagregante", ["Protege corazón y cerebro"], True),
                 ("Revascularizar", ["Si limita mucho o hay isquemia crítica"], False)]),
  escala=dict(nombre="Clasificación de Fontaine", que="Gravedad clínica de la isquemia crónica de las piernas.",
              grados=[("I", "Asintomático", ["Pulso bajo sin síntomas"]), ("IIa", "Claudicación > 200 m", ["Leve"]), ("IIb", "Claudicación < 200 m", ["Moderada a grave"]),
                      ("III", "Dolor en reposo", ["Isquemia crítica"]), ("IV", "Úlcera o gangrena", ["Pérdida de tejido"])],
              caso=[1, 2], porque=[("Dolor al caminar que cede al reposo", True), ("No dice a cuántos metros", True)],
              conducta="Ejercicio, estatina, antiagregante y control de diabetes y PA."))

# NEF-068 · Cáncer de próstata localizado · DECISIÓN (riesgo)
S("decision", "NEF-068", "Varón de 65 años con antecedente familiar, próstata indurada, PSA 11,5, Gleason bajo y sin extensión: cáncer de próstata localizado, prostatectomía radical",
  "Cáncer de próstata · tratamiento",
  ("Cáncer de próstata localizado", ["Se clasifica por riesgo (PSA, Gleason/ISUP y estadio T) y la expectativa de vida.",
                                     "Con > 10 años de vida esperados, el riesgo intermedio se trata con intención curativa: cirugía o radioterapia."]),
  ("Varón de 65 años", ["Nicturia y hemospermia; padre fallecido por cáncer de próstata.", "Próstata indurada, PSA 11,5, Gleason «< 6», sin extensión en la TC."]),
  ["Precisión: hoy el Gleason mínimo en biopsia es 6 (ISUP 1); con PSA 10-20 es riesgo intermedio favorable.",
   "Opciones curativas: prostatectomía radical o radioterapia (± 4-6 meses de hormonoterapia).",
   "Vigilancia activa: solo riesgo muy bajo o bajo (PSA < 10, ISUP 1, T1-T2a)."],
  "NCCN, cáncer de próstata (2025); EAU-EANM-ESTRO-ESUR-ISUP-SIOG (2024).",
  op=("¿Tratamiento?", ["Sí: curativo en enfermedad localizada", "Es la alternativa curativa (con hormonoterapia corta)", "No: es para enfermedad metastásica",
                        "No: es para enfermedad avanzada", "No: con PSA 11,5 no es de muy bajo riesgo"]),
  d=dict(rotulo="Cáncer de próstata localizado: tratamiento según el riesgo", eje_y="Riesgo (NCCN)", ancho_filas=220,
         cols=["Expectativa de vida ≥ 10 años", "Expectativa de vida < 10 años"],
         rows=[("Bajo", "PSA < 10, ISUP 1, T1-T2a"), ("Intermedio", "PSA 10-20, ISUP 2-3 o T2b-c"), ("Alto", "PSA > 20, ISUP 4-5 o T3a")],
         cells=[[("Vigilancia activa", ["PSA, tacto y RM periódicos"]), ("Observación", ["Tratar si da síntomas"])],
                [("Prostatectomía radical", ["o radioterapia ± hormonoterapia corta"]), ("Radioterapia u observación", [])],
                [("Radioterapia + hormonoterapia", ["o prostatectomía con linfadenectomía"]), ("Hormonoterapia o RT", [])]],
         caso=(1, 0), nota="65 años y sano: expectativa > 10 años; PSA 11,5 lo pone en riesgo intermedio."))

# CIR-088 · Hernia crural reducida bajo anestesia: laparotomía mediana · ÁRBOL + dibujo
S("arbol", "CIR-088", "Hernia crural con probable estrangulación que se reduce sola al inducir la anestesia: explorar el intestino por laparotomía mediana",
  "Hernias · hernia crural complicada",
  ("Hernia crural estrangulada", ["Sale por debajo del ligamento inguinal (anillo crural estrecho): se estrangula con facilidad.",
                                  "Si se reduce con anestesia, el asa posiblemente necrosada queda dentro del abdomen sin que se vea."]),
  ("Mujer de 38 años", ["Hernia crural derecha con probable estrangulación.", "Se reduce sin querer al dar la anestesia general."]),
  ["Explorar la cavidad para ver la viabilidad del asa: laparotomía mediana (o laparoscopía si hay experiencia y la paciente está estable).",
   "Resecar el asa si no es viable; reparar el defecto crural.",
   "No basta con el abordaje inguinal: no permite revisar bien el intestino reducido."],
  "HerniaSurge, guía internacional de hernias de la ingle (2018; act. 2023); WSES, hernias complicadas (2017); " + SABISTON + ".",
  op=("¿Abordaje?", ["No: menos acceso a todo el intestino", "Sí: permite revisar todo el intestino", "No: no deja ver el asa reducida",
                     "No: no es un abordaje para esto", "No: diferir arriesga la perforación"]),
  arbol=Q("Hernia estrangulada: ¿se redujo antes de ver el asa?", [
      L("Sí, con la anestesia (este caso)", "LAPAROTOMÍA MEDIANA", ["Ver la viabilidad del asa", "Resecar si está muerta"], path=True),
      L("No, sigue atrapada", "Abordaje inguinal o crural", ["Abrir el saco y ver el asa"])], path=True),
  banda=B("Por dónde sale la hernia crural", P("dib_hernia_crural.jpg", 380, 266, [], credito=PROPIO, fondo="#ffffff"),
          [("Debajo del ligamento inguinal", "Medial a la vena femoral."),
           ("Anillo estrecho", "La que más se estrangula."),
           ("Más en mujeres", "Tras embarazos.")],
          pie="Esquema."))

# CIR-089 · Taponamiento cardíaco · CUADRÍCULA de lesiones torácicas letales + Beck + ECG
S("cuadricula", "CIR-089", "Herida punzopenetrante precordial con hipotensión, ingurgitación yugular y ruidos cardíacos apagados (tríada de Beck): taponamiento cardíaco",
  "Trauma de tórax · lesiones que matan rápido",
  ("Taponamiento cardíaco", ["La sangre en el pericardio comprime el corazón: no se llena y cae el gasto.",
                             "Tríada de Beck: hipotensión, yugulares ingurgitadas y ruidos apagados; FAST con líquido pericárdico."]),
  ("Varón de 27 años", ["Herida punzopenetrante en la región precordial.", "Pálido, disneico, hipotenso, yugulares ingurgitadas, ruidos apagados."]),
  ["FAST: líquido en el pericardio confirma.",
   "Toracotomía o esternotomía urgente para reparar la herida; pericardiocentesis solo como puente si no hay cirujano.",
   "Líquidos solo para mantener; no retrasar el quirófano."],
  ATLS + "; EAST, trauma cardíaco penetrante (2023).",
  op=("¿Diagnóstico?", ["No: murmullo abolido y timpanismo", "Sí: tríada de Beck tras herida precordial", "No: sin hipotensión ni ingurgitación",
                        "No: yugulares planas y matidez", "No: trauma cerrado, arritmias"]),
  d=dict(rotulo="Trauma de tórax con choque: ¿cuál es?", alto_img=120,
         celdas=[("Taponamiento", ["Yugulares llenas, ruidos apagados", "Pulmón normal → pericardio"], P("ecg_taponamiento.jpg", 380, 182), True),
                 ("Neumotórax a tensión", ["Yugulares llenas, murmullo abolido", "Timpanismo, tráquea desviada"], P("rx_neumotorax_grande.jpg", 280, 280), False),
                 ("Hemotórax masivo", ["Yugulares planas", "Matidez, > 1500 mL al drenar"], None, False),
                 ("Tórax inestable", ["Segmento que se hunde al inspirar", "Contusión pulmonar"], None, False)],
         credito="ECG de enseñanza MedQuizPro (alternancia eléctrica) y James Heilman (CC BY 3.0, Commons)",
         veredicto=("Hipotensión + yugulares + ruidos apagados = taponamiento", "FAST y cirugía urgente.")),
  triada=TR([("Hipotensión", "Sí", True), ("Ingurgitación yugular", "Sí", True), ("Ruidos cardíacos apagados", "Sí", True)],
            [("Tríada de Beck", 0, 2)], "Completa: taponamiento hasta que se demuestre lo contrario."))

# NRL-043 · Hemorragia de fosa posterior: cirugía · ALARMA (indicaciones)
S("alarma", "NRL-043", "Hemorragia de fosa posterior que comprime el tronco con obnubilación progresiva e hipertensión endocraneana: ventriculostomía y craniectomía suboccipital",
  "Hemorragia cerebral · cerebelo",
  ("Hemorragia cerebelosa", ["En la fosa posterior hay poco espacio: el hematoma aplasta el tronco y tapa el IV ventrículo (hidrocefalia).",
                             "Puede deteriorarse en horas: es una de las pocas hemorragias que se operan de urgencia."]),
  ("Varón de 65 años", ["Compresión del tallo encefálico por hemorragia de fosa posterior.", "Agitación, obnubilación progresiva, hipertensión endocraneana."]),
  ["Descompresión quirúrgica: craniectomía suboccipital y evacuación del hematoma.",
   "Ventriculostomía (drenaje ventricular externo) si hay hidrocefalia.",
   "Manitol e hiperventilación solo como puente; nunca punción lumbar (herniación)."],
  "AHA/ASA, hemorragia intracerebral espontánea (2022); " + HARRISON + ".",
  op=("¿Conducta?", ["No: no es un aneurisma por lo que se sabe", "Sí: descomprime el tronco y drena el LCR", "Solo como puente",
                     "Solo como puente", "No: provoca herniación"]),
  d=dict(rotulo="Hemorragia cerebelosa: ¿hay que operar?", lista_titulo="Indicaciones de cirugía (AHA/ASA)",
         signos=[("Deterioro neurológico", "Obnubilación progresiva", True), ("Compresión del tronco", "Sí", True),
                 ("Hidrocefalia por obstrucción", "Hipertensión endocraneana", True), ("Hematoma > 3 cm (15 mL)", "No informado", None)],
         accion=("Craniectomía suboccipital + ventriculostomía", "Lo antes posible."), accion_rotulo="Si hay una o más",
         veredicto=("Fosa posterior con compresión del tronco = cirugía de urgencia", "El manitol solo gana tiempo.")))

# CB-058 · Barbitúricos · EMBUDO
S("embudo", "CB-058", "Joven en coma profundo con piel fría, miosis, bradipnea y cianosis que no responde al flumazenilo: intoxicación por barbitúricos",
  "Toxicología · depresores del sistema nervioso",
  ("Intoxicación por barbitúricos", ["Deprimen mucho más que las benzodiacepinas: coma, respiración lenta, hipotermia, hipotensión.",
                                     "No tienen antídoto; el flumazenilo no los revierte."]),
  ("Mujer de 19 años", ["Encontrada en su cama tras una discusión: piel fría, respiración poco perceptible.", "Coma profundo, pupilas puntiformes, bradipnea y cianosis; flumazenilo sin efecto."]),
  ["Soporte: intubar y ventilar, líquidos y vasopresor si hay hipotensión, calentar.",
   "Fenobarbital: carbón activado en dosis repetidas y alcalinizar la orina; hemodiálisis si es grave.",
   "Evaluación psiquiátrica (intento de suicidio)."],
  "Goldfrank's Toxicologic Emergencies 11.ª ed.; " + HARRISON + ".",
  op=("¿Causa?", ["Sí: coma profundo que el flumazenilo no revierte", "No: daría secreciones, bradicardia, fasciculaciones", "No: el flumazenilo la revertiría",
                  "No: da ataxia y nistagmo, rara vez coma así", "No: al inicio casi sin síntomas; luego hígado"]),
  d=dict(rotulo="Coma con miosis y respiración lenta: ¿qué tóxico?", inicio="Coma + miosis + bradipnea",
         candidatos=["Barbitúricos", "Benzodiacepinas", "Opioides", "Carbamatos", "Fenitoína"],
         pasos=[("¿Revierte con flumazenilo?", ["Benzodiacepinas"]),
                ("¿Hay secreciones, fasciculaciones o ataxia con nistagmo?", ["Carbamatos", "Fenitoína"])],
         final=("BARBITÚRICOS", ["Coma profundo, hipotermia", "Sin antídoto: soporte"]),
         nota="La naloxona también debe probarse ante coma con miosis (opioides); aquí la pregunta lleva a barbitúricos."))

# NEU-041 · Disnea súbita con hipoxemia y Rx normal · DECISIÓN
S("decision", "NEU-041", "Paciente hospitalizado con disnea súbita e hipoxemia, sin causa coronaria y con Rx de tórax normal: tromboembolismo pulmonar",
  "Disnea aguda · diagnóstico diferencial",
  ("Disnea con Rx normal", ["Si un paciente tiene hipoxemia y la Rx está «limpia», el problema suele estar en los vasos del pulmón: TEP.",
                            "Hospitalizado e inmovilizado = riesgo alto de trombosis."]),
  ("Paciente hospitalizado", ["Disnea súbita con hipoxemia.", "Se descarta problema coronario; Rx normal."]),
  ["Calcular la probabilidad (Wells): si es probable, angio-TC; si no, dímero D.",
   "Anticoagular mientras se confirma si la probabilidad es alta y no hay riesgo de sangrado.",
   "Profilaxis en hospitalizados: heparina de bajo peso si hay riesgo (Padua ≥ 4)."],
  ESC + ", embolia pulmonar (2019); ACCP (2021).",
  op=("¿Diagnóstico?", ["No: sin hipoxemia real", "No: tendría infiltrado", "No: tendría infiltrado nuevo", "Sí: hipoxemia con Rx normal", "No: tendría edema en la Rx"]),
  d=dict(rotulo="Disnea súbita: ¿qué dice la Rx y la oxigenación?", eje_y="Rx de tórax", ancho_filas=200,
         cols=["Con hipoxemia", "Sin hipoxemia"],
         rows=[("Normal", "Pulmones limpios"), ("Con infiltrado", "Opacidad nueva"), ("Con edema", "Alas de mariposa, Kerley")],
         cells=[[("Tromboembolismo pulmonar", ["Angio-TC"]), ("Ansiedad, anemia", ["Diagnóstico de exclusión"])],
                [("Neumonía (intrahospitalaria)", ["Cultivos y antibiótico"]), ("Neumonía leve", [])],
                [("Edema agudo de pulmón", ["Diurético, vasodilatador"]), ("Congestión leve", [])]],
         caso=(0, 0), nota="Rx normal + hipoxemia en un hospitalizado: pensar primero en TEP."))

# CAR-054 · Coartación de aorta · CUADRÍCULA de HTA secundaria + dibujo
S("cuadricula", "CAR-054", "Joven de 28 años con PA 200/135 en brazos, soplo sistólico que se irradia a la espalda y pulsos femorales pequeños: coartación de aorta",
  "Hipertensión secundaria · coartación de aorta",
  ("Coartación de aorta", ["Estrechez de la aorta cerca del ligamento arterioso: HTA en brazos y PA baja en piernas.",
                           "Soplo sistólico en la espalda, pulso femoral débil y retrasado; Rx: muescas costales y signo del «3»."]),
  ("Varón de 28 años, evaluación prequirúrgica", ["PA 200/135 en miembros superiores, FC 60.", "Soplo sistólico II/VI irradiado a la espalda; pulso femoral pequeño."]),
  ["Medir la PA en brazos y piernas: diferencia > 20 mmHg.",
   "Ecocardiograma y angio-TC o RM de aorta; buscar válvula aórtica bicúspide.",
   "Tratamiento: angioplastia con stent o cirugía; postergar la cirugía programada."],
  ESC + ", cardiopatías congénitas del adulto (2020); AHA/ACC (2018).",
  op=("¿Diagnóstico?", ["Sí: HTA en brazos + pulso femoral débil", "No: soplo en el foco aórtico, PA no tan alta", "No: soplo diastólico",
                        "No: mujer joven, pulsos de brazos débiles", "No: crisis paroxísticas"]),
  d=dict(rotulo="Hipertensión en un joven: causas secundarias",
         celdas=[("Coartación de aorta", ["PA alta en brazos, baja en piernas", "Soplo en la espalda"], None, True),
                 ("Feocromocitoma", ["Crisis de cefalea, sudor, palpitaciones", "Metanefrinas"], None, False),
                 ("Hiperaldosteronismo", ["HTA con potasio bajo", "Aldosterona/renina"], None, False),
                 ("Estenosis de arteria renal", ["Displasia fibromuscular en mujer joven", "Soplo abdominal"], None, False)],
         veredicto=("HTA en brazos + pulso femoral débil + soplo en la espalda = coartación", "Medir PA en las 4 extremidades e imagen de aorta.")),
  banda=B("Qué pasa en la coartación", P("dib_coartacion.jpg", 340, 238, [], credito=PROPIO, fondo="#ffffff"),
          [("Estrechez de la aorta", "Después de la subclavia izquierda."),
           ("Arriba: PA alta", "Brazos y cabeza."),
           ("Abajo: PA baja", "Pulsos femorales débiles y retrasados."),
           ("Colaterales", "Las intercostales crecen: muescas en las costillas.")],
          pie="Esquema."))

# HEM-031 · TVP por inmovilización · ÁRBOL + Virchow + Wells + foto
S("arbol", "HEM-031", "Mujer de 69 años en cama 2 semanas por neumonía con edema y dolor de la pierna derecha: trombosis venosa profunda",
  "Enfermedad tromboembólica venosa",
  ("Trombosis venosa profunda", ["Trombo en las venas profundas de la pierna; la inmovilización es un factor de riesgo clásico.",
                                 "Edema unilateral, dolor, calor; puede embolizar al pulmón."]),
  ("Mujer de 69 años", ["2 semanas en cama por neumonía viral y bacteriana.", "Edema y dolor a la palpación en la pierna derecha que aumenta al moverla."]),
  ["Probabilidad con Wells: si es probable, eco Doppler de compresión; si es improbable, dímero D.",
   "Anticoagular: anticoagulante oral directo (apixabán, rivaroxabán) o heparina de bajo peso → warfarina; 3 meses si el factor fue transitorio.",
   "Profilaxis en hospitalizados de riesgo (heparina de bajo peso) y movilización temprana."],
  "ASH, tromboembolia venosa (2020); ACCP/CHEST (2021); " + HARRISON + ".",
  op=("¿Término?", ["No: sangrado y consumo sistémico", "No: crónicas, no aparecen en días", "No: indoloro, crónico", "Sí: inmovilización + edema unilateral doloroso",
                    "No: piel roja y caliente con fiebre (puede confundirse)"]),
  arbol=Q("Pierna hinchada y dolorosa: ¿probabilidad de Wells?", [
      L("Probable (este caso)", "ECO DOPPLER", ["Confirmar la TVP", "Anticoagular"], path=True),
      L("Improbable", "Dímero D", ["Si es normal, se descarta"])], path=True),
  escala=dict(nombre="Escala de Wells para TVP", modo="puntaje", que="Probabilidad clínica antes de la ecografía.",
              items=[("Inm", "Encamado > 3 días o cirugía reciente (1)", "2 semanas en cama", 1), ("Dol", "Dolor en el trayecto venoso (1)", "Dolor a la palpación", 1),
                     ("Edema", "Edema de toda la pierna o > 3 cm (1)", "Edema", 1), ("Alt", "Otro diagnóstico igual de probable (−2)", "No", 0)],
              total_txt="Total: ≥ 3 puntos", total_nota="TVP probable si ≥ 2",
              rangos=[("< 2", "Improbable", "Dímero D"), ("≥ 2", "Probable", "Eco Doppler")], caso_rango=1,
              porque=[("Encamada + dolor + edema", True)], conducta="Eco Doppler y anticoagulación."),
  triada=TR([("Estasis", "2 semanas en cama", True), ("Daño endotelial", "No descrito", None), ("Hipercoagulabilidad", "Infección aguda, 69 años", True)],
            [("Tríada de Virchow", 0, 2)], "Inmovilización + infección: riesgo alto de trombosis."),
  banda=B("Así se ve una TVP", P("tvp.jpg", 200, 319, [("flecha", 0.28, 0.35, 0.50, 0.94, "pierna hinchada")],
          credito="James Heilman" + CC + "CC BY-SA 3.0"),
          [("Una pierna más gruesa", "Edema unilateral."),
           ("Dolor y calor", "En la pantorrilla."),
           ("Riesgo", "Embolia pulmonar.")],
          pie="Foto de otro paciente."))

# CAR-055 · Tos por IECA · TARJETAS
S("tarjetas", "CAR-055", "Hipertenso con captopril y amlodipino que tiene tos seca sin causa respiratoria ni de ORL: retirar el captopril (tos por IECA)",
  "Antihipertensivos · efectos adversos",
  ("Tos por IECA", ["Los IECA impiden degradar la bradicinina: se acumula en el bronquio y da tos seca (5-35 %).",
                    "Aparece en semanas o meses y desaparece 1-4 semanas después de suspender el IECA."]),
  ("Varón de 62 años, hipertenso", ["Captopril y amlodipino.", "Tos seca intermitente; neumología y ORL sin hallazgos."]),
  ["Retirar el IECA y cambiar a un ARA II (losartán), que no aumenta la bradicinina.",
   "Los antitusígenos y mucolíticos no la quitan.",
   "Otro efecto por bradicinina: angioedema (suspender y nunca volver a usar IECA)."],
  ESC + "/ESH, hipertensión (2023/2024); " + HARRISON + ".",
  op=("¿Conducta?", ["No: no actúa sobre la causa", "Sí: la tos es por el IECA", "No: el amlodipino da edema, no tos", "No: tapa el síntoma", "No: no es alérgica"]),
  d=dict(rotulo="Efecto adverso típico de cada antihipertensivo", ans=0,
         cards=[dict(titulo="IECA (captopril)", datos=[("Típico", "Tos seca", True), ("Grave", "Angioedema", True), ("Por", "Bradicinina", True)], pie="Este caso."),
                dict(titulo="ARA II (losartán)", datos=[("Tos", "No", False), ("Otro", "Hiperpotasemia", False), ("Uso", "Si el IECA da tos", False)], pie="El reemplazo."),
                dict(titulo="Calcioantagonista", datos=[("Típico", "Edema de tobillos", False), ("Otro", "Rubor, cefalea", False), ("Ej.", "Amlodipino", False)], pie="No da tos."),
                dict(titulo="Tiazida", datos=[("Típico", "Hipopotasemia", False), ("Otro", "Hiperuricemia", False), ("Ej.", "Hidroclorotiazida", False)], pie="Gota.")]))

# HEM-032 · Pancitopenia: fármacos · RADIAL de causas
S("radial", "HEM-032", "Mujer con equimosis, fiebre y neumonía con leucocitos 1400, Hb 7,2 y plaquetas 35 000: pancitopenia, lo primero es preguntar por medicamentos mielotóxicos",
  "Citopenias · pancitopenia",
  ("Pancitopenia", ["Bajan las tres series: anemia (cansancio), leucopenia (infecciones) y plaquetopenia (sangrados).",
                    "Una causa adquirida frecuente y reversible son los fármacos: siempre preguntarlo primero."]),
  ("Mujer de 44 años", ["Equimosis, debilidad, tos con esputo amarillo; T 38,4 °C, crepitantes.", "Leucocitos 1400, Hb 7,2, plaquetas 35 000."]),
  ["Fármacos: cloranfenicol, metamizol, metotrexato, quimioterapia, carbamazepina, antitiroideos, AZT.",
   "Suspender el sospechoso; neutropenia febril → antibiótico de amplio espectro de inmediato.",
   "Frotis, reticulocitos, B12/folato, VIH y biopsia de médula si no se aclara."],
  "ASH; " + HARRISON + ".",
  op=("¿Qué buscar?", ["Sí: la causa adquirida más frecuente y reversible", "Útil en jóvenes; menos aquí", "Pensar en B12 si es megaloblástica",
                       "Puede bajar series, pero no explica todo", "Útil si hay fiebre de viaje (malaria, leishmaniasis)"]),
  d=dict(rotulo="Causas de pancitopenia", centro="FÁRMACOS", centro_sub="preguntar primero", ans=0,
         items=[("FÁRMACOS", ["Metamizol, cloranfenicol, quimio"]), ("APLASIA MEDULAR", ["Médula vacía"]), ("INFILTRACIÓN", ["Leucemia, metástasis, fibrosis"]),
                ("MEGALOBLÁSTICA", ["Falta B12 o folato"]), ("HIPERESPLENISMO", ["Bazo grande secuestra"])],
         ruta=["Preguntar fármacos", "Frotis y reticulocitos", "B12, folato, VIH", "Biopsia de médula"]))

# CAR-056 · Endocarditis con embolia cerebral · CRITERIOS de Duke + Janeway
S("criterios", "CAR-056", "Joven con fiebre de 2 meses, baja de peso, soplo de insuficiencia mitral por fiebre reumática y hemiparesia súbita: endocarditis infecciosa con embolia cerebral",
  "Endocarditis infecciosa",
  ("Endocarditis infecciosa", ["Infección de una válvula (más si ya está dañada, como en la fiebre reumática): vegetaciones.",
                               "Las vegetaciones se desprenden y embolizan: cerebro, bazo, riñón, piel."]),
  ("Varón de 35 años", ["Fiebre de 2 meses y baja de peso; fiebre reumática en la infancia.", "Déficit motor izquierdo agudo; soplo de insuficiencia mitral."]),
  ["3 hemocultivos antes del antibiótico y ecocardiograma (transesofágico si el transtorácico es negativo).",
   "Antibiótico EV 4-6 semanas según germen (estreptococo, estafilococo, enterococo).",
   "Cirugía si hay insuficiencia cardíaca, absceso, vegetación > 10 mm con embolia o infección no controlada."],
  ESC + ", endocarditis (2023); criterios de Duke-ISCVID (2023).",
  op=("¿Causa?", ["No: sin abortos ni trombosis previas", "No: no causa embolia", "No: ritmo regular", "Sí: fiebre + soplo + embolia", "No: no explica la fiebre de 2 meses"]),
  d=dict(rotulo="Criterios de Duke (2023)", lista_titulo="Criterios del caso",
         items=[("Mayor: hemocultivos típicos", None, "Por tomar (3 sets)"), ("Mayor: vegetación o regurgitación nueva en la eco", True, "Insuficiencia mitral"),
                ("Menor: predisposición (valvulopatía)", True, "Fiebre reumática"), ("Menor: fiebre > 38 °C", True, "2 meses"),
                ("Menor: fenómeno vascular (embolia)", True, "Déficit motor agudo")],
         umbral="Definida: 2 mayores, o 1 mayor + 3 menores, o 5 menores",
         veredicto="1 mayor + 3 menores: endocarditis definida; la hemiparesia es una embolia cerebral.",
         img=P("janeway.jpg", 260, 195, [], credito="Warfieldian" + CC + "CC BY-SA 4.0"), img_titulo="Lesiones de Janeway",
         img_pie="Otro fenómeno vascular (embolias sépticas en la planta).", conteo="1 mayor + 3 menores"))

# INF-079 · Mononucleosis: transmisión por saliva · TRANSMISIÓN
S("transmision", "INF-079", "Joven con febrícula, odinofagia, adenopatías generalizadas y linfocitos atípicos: mononucleosis, el factor de riesgo es el contacto estrecho por saliva (besos)",
  "Virus de Epstein-Barr · transmisión",
  ("Mononucleosis infecciosa", ["El virus de Epstein-Barr se elimina por la saliva semanas o meses después de la infección.",
                                "En adolescentes y jóvenes se contagia con los besos («enfermedad del beso»)."]),
  ("Varón de 23 años, 2 semanas", ["Malestar, febrícula, odinofagia; faringe roja sin exudado.", "Adenopatías cervicales, axilares e inguinales; linfocitosis con cambios virales."]),
  ["Incubación larga: 4-6 semanas.",
   "No compartir vasos ni cubiertos; no hace falta aislar.",
   "Rara vez por transfusión o trasplante (no es lo habitual)."],
  CDC + ", Epstein-Barr (2024); " + HARRISON + ".",
  op=("¿Factor de riesgo?", ["No: leptospirosis", "No: dengue", "No: hepatitis A o vibrios", "Sí: saliva por besos", "Posible pero raro"]),
  d=dict(rotulo="Cómo se contagia el virus de Epstein-Barr",
         eslabones=[("Reservorio", "Solo el ser humano", "Identificar al enfermo", False),
                    ("Salida", "Saliva (meses)", "No compartir cubiertos", False),
                    ("Vía", "Contacto estrecho: besos", "Evitar besos en la fase aguda", True),
                    ("Entrada", "Boca: epitelio y linfocitos B", "Higiene de manos", False),
                    ("Huésped", "Adolescente o joven", "Educación", False)],
         veredicto=("La mononucleosis se transmite por la saliva (besos)", "Incubación de 4-6 semanas.")))

# GAS-055 · Esófago de Barrett: adenocarcinoma · GRADOS CON FOTO (progresión histológica)
S("grados_foto", "GAS-055", "Disfagia con mucosa roja 3 cm por encima de la línea Z y biopsia con epitelio cilíndrico con células caliciformes: esófago de Barrett, su complicación es el adenocarcinoma",
  "Reflujo gastroesofágico · esófago de Barrett",
  ("Esófago de Barrett", ["El reflujo crónico cambia el epitelio escamoso del esófago por uno intestinal (metaplasia con células caliciformes).",
                          "Es la lesión previa al adenocarcinoma de esófago distal."]),
  ("Varón de 55 años", ["Disfagia progresiva de 6 meses.", "Mucosa roja 3 cm sobre la línea Z; biopsia: epitelio cilíndrico con células caliciformes."]),
  ["Vigilancia endoscópica con biopsias (protocolo de Seattle): cada 3-5 años sin displasia.",
   "Displasia: ablación por radiofrecuencia o resección endoscópica.",
   "IBP de por vida; la disfagia progresiva obliga a descartar cáncer ya."],
  "ACG, esófago de Barrett (2022); ESGE (2023).",
  op=("¿Complicación?", ["Sí: metaplasia → displasia → adenocarcinoma", "No: no la causa el reflujo", "No: es del esófago escamoso (alcohol y tabaco)",
                         "No: no es la complicación típica", "Puede ocurrir, pero la grave es el cáncer"]),
  d=dict(rotulo="Del epitelio normal al cáncer: la progresión del Barrett",
         criterio="Cada paso se ve en la biopsia; el Barrett (2) es la metaplasia intestinal del caso.",
         grados=[("1", "Normal", "Escamoso estratificado", P("barrett_a.jpg", 330, 299), False),
                 ("2", "Barrett", "Metaplasia intestinal con caliciformes", P("barrett_b.jpg", 330, 296), True),
                 ("3", "Displasia", "Células atípicas", P("barrett_c.jpg", 330, 300), False),
                 ("4", "Adenocarcinoma", "Invade la pared", P("barrett_d.jpg", 330, 297), False)],
         credito=PMC_BARRETT,
         veredicto=("Barrett = metaplasia intestinal; su complicación es el adenocarcinoma", "Vigilancia con biopsias y tratar la displasia.")))

# NEU-042 · Sospecha de TEP con dímero D alto: angio-TC · ÁRBOL + angio-TC
S("arbol", "NEU-042", "Hospitalizada tras un infarto cerebral que al caminar presenta disnea súbita grave, dolor torácico y dímero D alto: el siguiente examen es la angio-TC pulmonar",
  "Tromboembolismo pulmonar · diagnóstico",
  ("Algoritmo del TEP estable", ["Probabilidad clínica (Wells o Ginebra) → si es improbable, dímero D; si es probable o el dímero D sale alto, angio-TC.",
                                 "El dímero D solo sirve para descartar: alto no confirma."]),
  ("Mujer de 68 años, infarto cerebral", ["2 semanas hospitalizada; al empezar a caminar: disnea súbita grave, dolor torácico, diaforesis.", "Dímero D > 500 ng/mL."]),
  ["Angio-TC de tórax: confirma el TEP; si hay alergia al contraste o falla renal, gammagrafía V/Q.",
   "Inestable (hipotensión): ecocardiograma a la cabecera y trombólisis si hay disfunción del VD.",
   "Anticoagular; en el infarto cerebral reciente, valorar el momento por riesgo de sangrado."],
  ESC + ", embolia pulmonar (2019); " + AHA + ".",
  op=("¿Siguiente examen?", ["No: no confirma", "Sí: confirma el TEP", "Busca TVP; no confirma TEP", "No: no está indicado", "No: no tiene relación"]),
  arbol=Q("Sospecha de TEP: ¿cómo está la paciente?", [
      L("Estable + dímero D alto (este caso)", "ANGIO-TC PULMONAR", ["Confirma el trombo"], path=True),
      L("Inestable (choque)", "Ecocardiograma a la cama", ["VD dilatado → trombólisis"]),
      L("Estable + dímero D normal", "Se descarta", ["Si la probabilidad era baja"])], path=True),
  banda=B("Así se ve el TEP en la angio-TC", P("tep_tc.jpg", 340, 227, [("flecha", 0.45, 0.33, 0.2, 0.12, "trombo")],
          credito="Aung Myat y Arif Ahsan" + CC + "CC BY 2.0"),
          [("Arterias blancas por el contraste", "Las pulmonares se rellenan."),
           ("Defecto oscuro", "El trombo no deja pasar el contraste."),
           ("Más trombo = más grave", "Buscar dilatación del VD.")],
          pie="Angio-TC de otro paciente."))

# PED-149 · TB primaria en el niño · CUADRÍCULA de patrones de TB
S("cuadricula", "PED-149", "Escolar con padre bacilífero, fiebre, tos seca, estridor, PPD positivo y auscultación normal: TB primaria, la Rx mostrará adenopatías hiliares",
  "Tuberculosis en el niño",
  ("Tuberculosis primaria del niño", ["El bacilo llega al pulmón y a los ganglios del hilio: complejo primario (de Ghon).",
                                      "Los ganglios grandes pueden comprimir el bronquio: tos, sibilancias o estridor con auscultación normal."]),
  ("Niño de 12 años", ["Padre en tratamiento antituberculoso hace 1 mes; fiebre, estridor y tos seca.", "PPD positivo; auscultación normal."]),
  ["Rx de tórax (frontal y lateral): adenopatías hiliares o mediastinales.",
   "Muestras: aspirado gástrico o esputo inducido para Xpert y cultivo.",
   "Tratar como TB activa (2HRZ(E)/4HR); estudiar a todos los contactos."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + ", TB en niños (2022); " + NELSON + ".",
  op=("¿Hallazgo esperado?", ["Sí: el patrón típico del niño", "No: TB diseminada, en lactantes o inmunodeprimidos", "No: auscultación normal",
                              "No: es la TB del adulto (reactivación)", "No: no habría auscultación normal"]),
  d=dict(rotulo="Patrones de tuberculosis en la Rx", alto_img=130,
         celdas=[("Primaria (niño)", ["Adenopatías hiliares y mediastinales", "Puede comprimir el bronquio: estridor"], None, True),
                 ("Miliar", ["Micronódulos en todo el pulmón", "Lactantes e inmunodeprimidos"], P("tb_miliar.jpg", 300, 262), False),
                 ("Reactivación (adulto)", ["Cavidades en los vértices", "Muy contagiosa"], P("tb_cavitaria.jpg", 300, 275), False),
                 ("Pleural", ["Derrame unilateral", "Adolescentes y adultos jóvenes"], None, False)],
         credito="Herreros y col. (CC BY 4.0) y CDC (dominio público) · Wikimedia Commons",
         veredicto=("Niño con contacto, PPD (+), tos y estridor con auscultación normal = TB primaria", "Rx: adenopatías hiliares.")))

# NEU-043 · Neumotórax espontáneo primario · LECTURA (Rx)
S("lectura", "NEU-043", "Joven sano con disnea súbita, murmullo abolido en el hemitórax derecho y desviación del mediastino que mejora con tubo: neumotórax espontáneo por rotura de bullas (enfisema acinar distal)",
  "Neumotórax espontáneo primario",
  ("Neumotórax espontáneo primario", ["Se rompen pequeñas bullas subpleurales de los vértices (enfisema acinar distal o paraseptal).",
                                      "Varones jóvenes, altos y delgados, fumadores; aparece en reposo o con esfuerzo leve."]),
  ("Varón de 20 años, previamente sano", ["Disnea súbita intensa tras caer corriendo.", "Murmullo abolido a la derecha; mediastino desviado a la izquierda; sale aire por el tubo."]),
  ["Con desviación del mediastino e inestabilidad: neumotórax a tensión → descompresión con aguja (4.º-5.º espacio, línea axilar media) y tubo.",
   "Primer episodio estable y pequeño: observar u oxígeno; grande o con síntomas: aspiración o tubo fino.",
   "Recurrencia o fuga persistente: videotoracoscopía con resección de bullas y pleurodesis."],
  "BTS, neumotórax (2023); ACCP; " + ATLS + ".",
  op=("¿Patología de fondo?", ["No: tras fractura de huesos largos", "No: no da neumotórax así en joven sano", "No: sale aire, no sangre",
                               "Sí: bullas subpleurales que se rompen", "No: no hay fiebre ni consolidación"],
      {3: "Enfisema acinar distal (bullas)"}),
  d=dict(rotulo="Lee la Rx en este orden", img_titulo="Rx de tórax: neumotórax derecho grande",
         img=P("rx_neumotorax_grande.jpg", 320, 320, credito="James Heilman" + CC + "CC BY 3.0"),
         pines=[(0.25, 0.3), (0.42, 0.5)],
         pasos=[("Zona negra sin trama vascular", "Aire en la pleura: neumotórax.", False),
                ("Borde del pulmón colapsado", "La línea pleural visceral.", False),
                ("¿Se desvía el mediastino?", "Al lado contrario = a tensión: descomprimir ya.", True),
                ("Causa en el joven sano", "Bullas subpleurales apicales (enfisema acinar distal).", False)],
         img_pie="Rx de otro paciente.",
         veredicto=("Joven sano con neumotórax: rotura de bullas subpleurales", "Con desviación del mediastino: tubo de tórax urgente.")))

# INF-080 · Hiperinfección por Strongyloides en HTLV-1 · CICLO + foto
S("ciclo", "INF-080", "Portadora de HTLV-1 con diarrea profusa, tos, eosinofilia y larvas rabditoides en heces y esputo: estrongiloidosis (hiperinfección)",
  "Parasitosis · Strongyloides stercoralis",
  ("Estrongiloidosis", ["La larva entra por la piel; el parásito vive en el intestino y puede reinfectar sin salir (autoinfección).",
                        "Con HTLV-1 o corticoides la autoinfección se descontrola: hiperinfección con larvas en pulmón y otros órganos."]),
  ("Mujer de 28 años, HTLV-1", ["Diarrea líquida profusa y tos.", "Leucocitos 12 900, eosinófilos 14 %; larvas rabditoides en heces y esputo."]),
  ["Ivermectina 200 µg/kg/día hasta 2 semanas sin larvas (en hiperinfección, diaria).",
   "Antes de dar corticoides en zonas endémicas: buscar o tratar empíricamente Strongyloides.",
   "Vigilar sepsis por gramnegativos (las larvas arrastran bacterias del intestino)."],
  CDC + ", estrongiloidosis (2024); " + MINSA + "; " + HARRISON + ".",
  op=("¿Infección?", ["No: filaria de la piel y el ojo", "No: se ven huevos, no larvas", "Sí: larvas rabditoides + HTLV-1", "No: huevos con espolón", "No: huevos, no larvas"]),
  d=dict(rotulo="Ciclo de Strongyloides y la autoinfección", tag="ESTE CASO",
         img_titulo="Larva rabditoide en heces",
         img=P("strongy.jpg", 300, 153, [("flecha", 0.40, 0.68, 0.70, 0.88, "larva rabditoide")], credito="CDC" + CC + "dominio público"),
         img_pie="Se ven larvas, no huevos.",
         centro="Autoinfección", pasos=[("Larva entra por la piel", "suelo contaminado"), ("Pasa por el pulmón", "tos, eosinofilia"),
                                        ("Adulto en el intestino", "pone huevos que dan larvas"), ("Larva reinfecta", "sin salir: HTLV-1 la multiplica")],
         ans=3,
         claves_titulo="Por qué es grave aquí",
         claves=[("HTLV-1", ["Desvía la inmunidad: hiperinfección"], True), ("Corticoides", ["También la desencadenan"], False),
                 ("Tratamiento", ["Ivermectina diaria"], True)]))

# INF-081 · Leptospirosis grave: penicilina EV · FASES + foto
S("fases", "INF-081", "Campesino de Lurín con 7 días de fiebre, cefalea, mialgias intensas, ictericia e inyección conjuntival: leptospirosis (forma ictérica), penicilina EV",
  "Zoonosis · leptospirosis",
  ("Leptospirosis", ["Fase 1 (leptospirémica, ~7 días): fiebre, mialgias en pantorrillas, sufusión conjuntival.",
                     "Fase 2 (inmune): meningitis aséptica o, en la forma grave (Weil), ictericia, falla renal y hemorragia pulmonar."]),
  ("Varón de 55 años, campesino de Lurín", ["7 días de fiebre, cefalea, mialgias intensas e ictericia.", "Inyección conjuntival, exantema; transaminasas < 5 veces lo normal."]),
  ["Grave (ictericia): penicilina G sódica EV 1,5 millones UI c/6 h, o ceftriaxona 1 g/día, por 7 días.",
   "Leve: doxiciclina 100 mg c/12 h por 7 días (o amoxicilina).",
   "Vigilar riñón (creatinina, potasio) y pulmón; transaminasas solo moderadas (diferencia con hepatitis)."],
  MINSA + ", NTS de leptospirosis; " + OMS + "; " + HARRISON + ".",
  op=("¿Tratamiento?", ["No: no cubre bien Leptospira", "Alternativa posible, no la de elección", "Sí: forma grave", "No: innecesariamente amplio", "No: no actúa sobre Leptospira"]),
  d=dict(rotulo="Las dos fases de la leptospirosis", ans=1,
         fases=[("Leptospirémica", "Días 1-7", "FIEBRE Y MIALGIAS", ["Sufusión conjuntival", "Hemocultivo, PCR"]),
                ("Inmune", "Desde el día 7", "ICTERICIA (WEIL)", ["Riñón, pulmón, hemorragias", "Este caso"]),
                ("Recuperación", "Semanas", "CURA", ["Si se trata a tiempo"])]),
  banda=B("Un signo típico", P("lepto.jpg", 300, 212, [], credito="Daniel Ostermayer" + CC + "CC BY 4.0"),
          [("Sufusión conjuntival", "Ojo rojo sin secreción."),
           ("Con ictericia", "Forma de Weil: tratar EV."),
           ("Antecedente", "Agua o barro de chacras y canales.")],
          pie="Foto de otro paciente (solo el ojo)."))
