"""Entrega 3 · tanda t10 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO
from c26 import D, ILU
from c27 import DOS, CON_CREDITO
import ilu7 as I

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
GUYTON = "Guyton y Hall, Tratado de Fisiología Médica 14.ª ed."
MOORE = "Moore, Anatomía con orientación clínica 9.ª ed."
GORDIS = "Gordis, Epidemiología 6.ª ed."


def CTG(patron):
    return D(lambda s, x, y: I.ctg(s, x, y, patron, W=400, sc=0.55), 220, 134)


# GIN-167 · Abortos y macrosomía previa: descartar diabetes · ALARMA
S("alarma", "GIN-167", "Gestante con dos abortos y un hijo macrosómico: en el próximo control hay que descartar diabetes mellitus",
  "Diabetes y embarazo · tamizaje temprano",
  ("Antecedentes que hacen sospechar diabetes", ["La hiperglucemia al inicio del embarazo aumenta los abortos y las malformaciones; al final, hace fetos grandes (macrosomía).",
                                                 "Con factores de riesgo se busca diabetes desde la primera consulta, no se espera a las 24-28 semanas."]),
  ("Gestante joven", ["Antecedente de dos abortos.", "Un hijo macrosómico (≥ 4000 g)."]),
  ["Primera consulta: glucosa en ayunas (≥ 126 = diabetes franca; 92-125 = gestacional) o HbA1c.",
   "Si es normal: curva de 75 g a las 24-28 semanas.",
   "Control preconcepcional en diabéticas: HbA1c < 6,5 % y ácido fólico reducen abortos y malformaciones."],
  ADA + "; ACOG n.º 190 (2018; act.); " + MINSA + ".",
  op=("¿Descartar?", ["No: da abortos, no macrosomía", "No: no da macrosomía", "Sí: explica abortos y macrosomía", "No: no explica la macrosomía", "No: no explica la macrosomía"]),
  d=dict(rotulo="Antecedentes que obligan a buscar diabetes", lista_titulo="Factores de riesgo de diabetes en la gestante",
         signos=[("Hijo macrosómico (≥ 4000 g)", "Sí", True), ("Abortos o muerte fetal sin causa", "Dos abortos", True),
                 ("Obesidad (IMC ≥ 30)", "No se informa", False), ("Diabetes en familiares de 1.er grado", "No se informa", False),
                 ("Diabetes gestacional previa", "No se informa", False), ("Malformación fetal previa", "No se informa", False)],
         accion=("Glucosa en ayunas en el primer control", "Si es normal: curva de 75 g a las 24-28 semanas."),
         accion_rotulo="CON FACTORES DE RIESGO",
         veredicto=("Abortos + macrosomía = descartar diabetes", "La hiperglucemia explica ambos.")))

# GIN-168 · Desaceleraciones variables: cordón · CUADRÍCULA (CTG)
S("cuadricula", "GIN-168", "Desaceleraciones variables de la frecuencia cardiaca fetal, sin relación con las contracciones: compresión del cordón umbilical",
  "Monitoreo fetal intraparto",
  ("Desaceleraciones de la FCF", ["Se clasifican por su forma y su relación con la contracción.",
                                  "Variables: caídas bruscas en «V» o «U», de forma y momento distintos, sin relación fija con la contracción = compresión del cordón."]),
  ("Gestante en trabajo de parto", ["Desaceleraciones variables.", "No relacionadas con las contracciones."]),
  ["Cambiar de posición (decúbito lateral), suspender oxitocina, hidratar, tacto para descartar prolapso de cordón.",
   "Si son complicadas (profundas, largas, sin variabilidad): acelerar el parto.",
   "Causas: circular de cordón, oligohidramnios, prolapso de cordón."],
  ACOG + " n.º 106 (2009; act.); FIGO, monitoreo fetal intraparto (2015).",
  op=("¿Primera sospecha?", ["No: distocia de presentación", "No: da desaceleraciones precoces", "No: es término impreciso; aquí hay una causa",
                             "Sí: el cordón se comprime", "No: da desaceleraciones tardías"]),
  d=dict(rotulo="Las desaceleraciones y su causa", alto_img=134,
         celdas=[("Variables", ["Caídas bruscas, sin relación con la contracción", "Compresión del CORDÓN"], CTG("variables"), True),
                 ("Precoces", ["Espejo de la contracción", "Compresión de la cabeza: benignas"], CTG("precoces"), False),
                 ("Tardías", ["Empiezan después del pico de la contracción", "Insuficiencia placentaria"], CTG("tardias"), False),
                 ("Normal", ["Línea de base 110-160, variabilidad 5-25", "Sin desaceleraciones"], CTG("normal"), False)],
         credito="Trazados de enseñanza MedQuizPro (dibujo propio): arriba FCF, abajo contracciones",
         veredicto=("Variables = cordón", "Cambiar de posición y buscar prolapso de cordón.")))

# GIN-169 · Conducción del parto: 10 UI de oxitocina en 1 L · DOSIS
S("dosis", "GIN-169", "Para estimular un trabajo de parto con dinámica inadecuada se diluyen 10 UI de oxitocina en 1 litro de solución salina (10 mUI/mL)",
  "Conducción del trabajo de parto · oxitocina",
  ("Oxitocina en infusión", ["La dilución estándar permite dosificar en miliunidades por minuto: 10 UI en 1000 mL = 10 mUI/mL.",
                             "Se empieza bajo y se sube de a poco hasta 3-5 contracciones en 10 minutos."]),
  ("Centro de salud rural", ["Trabajo de parto con dinámica uterina inadecuada.", "¿Cuántas UI se diluyen en 1 litro?"]),
  ["Inicio 1-2 mUI/min (6-12 mL/h ≈ 2-4 gotas/min con macrogotero) y subir 1-2 mUI/min cada 30-40 min; máximo ~20-40 mUI/min.",
   "Antes: descartar desproporción, presentación anómala y sufrimiento fetal; monitorear la FCF.",
   "Suspender si hay taquisistolia (> 5 contracciones en 10 min) o alteración de la FCF."],
  OMS + ", conducción del trabajo de parto (2014; act.); " + MINSA + ", guía de atención del parto.",
  op=("¿UI en 1 L?", ["No: el doble (20 mUI/mL)", "Sí: 10 mUI/mL, estándar", "No: muy concentrada", "No: muy concentrada", "No: la mitad (5 mUI/mL)"]),
  d=dict(rotulo="Del frasco a la gota", peso_titulo="DILUCIÓN", peso=("10 UI", "en 1000 mL de solución salina"),
         pasos=[("Concentración", "10 mUI/mL", "10 000 mUI ÷ 1000 mL"), ("Inicio", "2 mUI/min", "= 12 mL/h ≈ 4 gotas/min"),
                ("Subir", "+2 mUI/min", "Cada 30-40 min hasta 3-5 contracciones/10 min")],
         ops=["→", "→"], tag="ESQUEMA",
         alternativas=[("10 UI", "10 mUI/mL", True), ("5 UI", "La mitad", False), ("20 UI", "El doble", False), ("30-40 UI", "Muy concentrada", False)],
         alt_titulo="Las alternativas",
         veredicto=("10 UI en 1 litro", "Así 1 mL tiene 10 miliunidades: fácil de calcular en mUI/min.")))

# GIN-170 · Feto pequeño con Doppler normal: control en dos semanas · REGLA
S("regla", "GIN-170", "Gestante de 32 semanas con feto bajo el percentil 10, líquido amniótico y Doppler umbilical normales: feto pequeño para la edad, control en dos semanas",
  "Restricción del crecimiento fetal",
  ("Feto pequeño frente a restricción del crecimiento", ["Peso < p10 con Doppler y líquido normales (y > p3): feto pequeño para la edad (constitucional), bajo riesgo.",
                                                         "Restricción (RCIU): < p3, o < p10 con Doppler alterado. Esa sí obliga a vigilancia estrecha y a veces a terminar."]),
  ("Gestante de 32 semanas", ["Altura uterina menor a la esperada.", "Eco: peso < p10, líquido normal, Doppler de la arteria umbilical normal."]),
  ["Control ecográfico de crecimiento y Doppler cada 2 semanas.",
   "Si aparece Doppler alterado o cae bajo p3: RCIU → vigilancia intensiva, corticoides según la edad y decidir la terminación.",
   "Terminar a las 37-38 semanas si sigue como pequeño para la edad."],
  "ISUOG, restricción del crecimiento fetal (2020); FIGO (2021); ACOG n.º 227 (2021).",
  op=("¿Manejo?", ["No: no hay indicación urgente", "No: no hay parto inminente", "No: el feto está bien", "Sí: pequeño con Doppler normal", "No: no es < 32 sem ni hay parto"]),
  d=dict(rotulo="¿Dónde cae el peso de este feto?",
         reglas=[dict(nombre="Percentil del peso fetal", que="< p3, o < p10 con Doppler alterado = restricción; p3-p10 con Doppler normal = pequeño.",
                      min=0, max=50, fmt="p{}", ticks=[3, 10],
                      bandas=[(0, 3, "< p3", 3), (3, 10, "Pequeño (PEG)", 2), (10, 50, "Normal", 0)],
                      caso=7, caso_txt="ESTE CASO: < p10")],
         claves_titulo="Lo que decide",
         claves=[("Doppler umbilical normal", ["La placenta funciona"], True), ("Líquido normal", ["No hay redistribución"], True),
                 ("Control en 2 semanas", ["Crecimiento y Doppler"], True)]))

# GIN-171 · FUR incierta: ecografía del primer trimestre · PIRÁMIDE
S("piramide", "GIN-171", "Gestante «de 42 semanas» que no recuerda bien su FUR: la edad gestacional se confirma con la ecografía del primer trimestre",
  "Datación del embarazo · embarazo prolongado",
  ("Cómo se fecha un embarazo", ["La ecografía del primer trimestre (longitud cráneo-caudal) es el método más exacto (± 5-7 días).",
                                 "Las ecografías tardías tienen más error (± 2-3 semanas al final) y no sirven para corregir la fecha."]),
  ("Gestante referida «de 42 semanas»", ["No recuerda bien su FUR.", "¿Qué debe evaluar el especialista antes de hospitalizarla?"]),
  ["Si la FUR y la eco del 1.er trimestre difieren > 7 días, manda la eco.",
   "Embarazo prolongado confirmado (≥ 42 sem): terminar la gestación; desde las 41 sem se ofrece inducción.",
   "Sin eco temprana, la edad es incierta: vigilar bienestar fetal y decidir con el especialista."],
  ACOG + " n.º 700 (2017; datación); ISUOG (2013).",
  op=("¿Qué evaluar?", ["No: bienestar, no la edad", "No: tardía, error de semanas", "No: bienestar, no la edad", "Sí: la más exacta", "No: muy inexacta"]),
  d=dict(rotulo="Métodos para saber la edad gestacional (del más exacto al menos)", caso=0, tag="ESTE CASO", ancho=400,
         niveles=[("1", "Eco del 1.er trimestre", "Longitud cráneo-caudal: ± 5-7 días."),
                  ("2", "FUR segura y ciclos regulares", "Útil si coincide con la eco."),
                  ("3", "Eco del 2.º trimestre", "± 10-14 días."),
                  ("4", "Eco del 3.er trimestre", "± 2-3 semanas: no sirve para fechar."),
                  ("5", "Altura uterina", "Orienta, no fecha.")],
         pie="Arriba el más exacto",
         veredicto=("FUR incierta: manda la eco del primer trimestre", "Con ella se confirma si de verdad tiene 42 semanas.")))

# GIN-172 · Primer control prenatal: exámenes basales · LISTA DE VERIFICACIÓN
S("checklist", "GIN-172", "En el primer control a las 8 semanas, si solo se pueden pedir tres exámenes, el que se descarta es la tolerancia a la glucosa (se hace a las 24-28 semanas)",
  "Control prenatal · exámenes del primer control",
  ("Exámenes del primer control prenatal", ["Hemograma (anemia), grupo y Rh (isoinmunización), orina y urocultivo (bacteriuria), glucosa en ayunas, VIH, sífilis, hepatitis B.",
                                            "La curva de tolerancia a la glucosa (75 g) es para las 24-28 semanas, no para las 8."]),
  ("Gestante de 8 semanas", ["Primer control prenatal.", "Solo puede pedir 3 análisis: ¿cuál descarta?"]),
  ["Primer control: hemograma, grupo y Rh, examen de orina/urocultivo, glucosa en ayunas, tamizaje de VIH, sífilis y hepatitis B.",
   "24-28 semanas: curva de 75 g (o antes si hay factores de riesgo).",
   "Rh negativo: Coombs indirecto y anti-D a las 28 semanas."],
  MINSA + ", NTS de atención integral de la salud materna (2023); " + OMS + ", control prenatal (2016).",
  op=("¿Cuál descarta?", ["Sí: es para las 24-28 semanas", "No: función renal basal", "No: anemia", "No: bacteriuria asintomática", "No: isoinmunización Rh"],
      {0: "Test de tolerancia a la glucosa", 3: "Urocultivo (antibiograma opcional)"}),
  d=dict(rotulo="Qué pedir a las 8 semanas", tag="PEDIR",
         pasos=[("Hemograma", "Anemia, plaquetas", True),
                ("Grupo sanguíneo y factor Rh", "Isoinmunización", True),
                ("Orina y urocultivo", "Bacteriuria asintomática", True),
                ("Glucosa en ayunas, VIH, sífilis, hepatitis B", "También del primer control", False)],
         no_hacer=[("Curva de tolerancia a la glucosa a las 8 semanas", "Se hace a las 24-28 semanas"),
                   ("Repetir la beta-hCG si la eco ya confirmó", "No cambia nada")],
         veredicto=("Se descarta la tolerancia a la glucosa", "Su momento es la semana 24-28.")))

# GIN-173 · Alumbramiento: signo de Küstner · BALANZA
S("balanza", "GIN-173", "Diez minutos después del parto la placenta no se ha desprendido: al presionar sobre el pubis el cordón sube (signo de Küstner positivo)",
  "Alumbramiento · signos de desprendimiento placentario",
  ("Signos de desprendimiento de la placenta", ["Desprendida: el cordón desciende (Ahlfeld), el útero se vuelve globuloso y sube (Schröder), sale un chorro de sangre.",
                                                "Küstner: al presionar sobre el pubis, si el cordón sube, la placenta aún está adherida; si no se mueve, ya se desprendió."]),
  ("Puérpera inmediata", ["Retraso del alumbramiento.", "A los 10 minutos la placenta no se ha desprendido: ¿qué signo lo sustenta?"]),
  ["Manejo activo: oxitocina 10 UI IM al nacer, tracción controlada del cordón y masaje uterino.",
   "Placenta retenida > 30 min (con manejo activo): extracción manual en sala.",
   "Nunca traccionar fuerte sin contratracción: inversión uterina."],
  OMS + ", hemorragia posparto (2023); " + WILLIAMS + ".",
  op=("¿Signo de NO desprendida?", ["Sí: Küstner positivo", "No: indica desprendida (Ahlfeld)", "No: indica desprendida", "No: indica desprendida (Schröder)", "No: indica desprendida"],
      {0: "Cordón sube con presión suprapúbica", 1: "Desciende la pinza del cordón", 2: "Pérdida de sangre transitoria"}),
  d=dict(rotulo="¿La placenta se desprendió?", gana="izq", pregunta="¿Qué dice el signo de este caso?",
         izq=dict(titulo="Aún adherida", peso="ADHERIDA", items=["Presión suprapúbica: el cordón SUBE (Küstner +)", "La pinza del cordón no baja",
                                                                 "Útero discoide, a nivel del ombligo"]),
         der=dict(titulo="Ya desprendida", peso="LISTA", items=["El cordón ya no sube (Küstner −)", "Desciende la pinza (Ahlfeld)",
                                                                "Útero globuloso que asciende (Schröder)", "Chorro de sangre oscura"]),
         veredicto=("Cordón que sube al presionar el pubis = no desprendida", ["Seguir con manejo activo; si pasa de 30 min, extracción manual."])))

# GIN-174 · Gemelos dicigóticos: sin transfusión feto-fetal · TARJETAS + eco
S("tarjetas", "GIN-174", "En un embarazo gemelar dicigótico (bicorial) la complicación menos esperable es la transfusión feto-fetal, propia de los monocoriales",
  "Embarazo gemelar · corionicidad",
  ("Corionicidad", ["Los dicigóticos siempre son bicoriales: cada uno tiene su placenta. Los monocigóticos pueden ser bi o monocoriales.",
                    "La transfusión feto-fetal necesita vasos compartidos en una sola placenta: solo en monocoriales (10-15 %)."]),
  ("Gestante añosa, gemelar dicigótico", ["Planea controles mensuales.", "¿Qué complicación espera menos?"]),
  ["Todo gemelar: más preeclampsia, parto pretérmino, anemia, diabetes y hemorragia posparto.",
   "Corionicidad por eco a las 11-14 semanas: signo lambda (bicorial) frente a signo T (monocorial).",
   "Monocoriales: eco cada 2 semanas desde las 16 semanas para buscar transfusión feto-fetal."],
  "ISUOG, embarazo gemelar (2025); " + WILLIAMS + ".",
  op=("¿Menos esperada?", ["Esperable", "Sí: necesita placenta compartida", "Esperable", "Esperable", "Esperable"]),
  d=dict(rotulo="Tipo de placentación y transfusión feto-fetal", ans=0,
         cards=[dict(titulo="Bicorial biamniótico", datos=[("Placentas", "Dos", True), ("Dicigóticos", "Siempre", True), ("Transfusión feto-fetal", "NO", True)], pie="Este caso."),
                dict(titulo="Monocorial biamniótico", datos=[("Placentas", "Una", False), ("Vasos", "Compartidos", False), ("Transfusión feto-fetal", "10-15 %", False)], pie="Eco cada 2 semanas."),
                dict(titulo="Monocorial monoamniótico", datos=[("Placentas", "Una", False), ("Bolsa", "Una sola", False), ("Riesgo", "Cordones enredados", False)], pie="El de más riesgo.")]),
  banda=B("Así se ve un gemelar bicorial", P("gemelar_lambda.jpg", 300, 230, [("flecha", 0.387, 0.614, 0.70, 0.12, "signo lambda")],
                                             credito="Eco: Nevit Dilmen" + CC + "CC BY-SA 3.0 · recorte"),
          [("Signo lambda", "Tabique grueso con tejido de placenta: bicorial."),
           ("Signo T", "Tabique fino: monocorial (riesgo de transfusión)."),
           ("Mejor momento", "Eco de 11-14 semanas.")],
          pie="Ecografía de otra gestante."))

# GIN-175 · Gestación de 10 semanas confirmada: β-hCG innecesaria · CUADRÍCULA
S("cuadricula", "GIN-175", "Gestante de 10 semanas con útero acorde y sin dolor ni masas: la beta-hCG no es necesaria, el embarazo ya está confirmado",
  "Control prenatal · uso de la beta-hCG",
  ("Para qué sirve la beta-hCG", ["Confirma el embarazo temprano, sigue el ectópico o el aborto (curva cada 48 h) y vigila la mola.",
                                  "Con 10 semanas y útero acorde, la eco transvaginal muestra el embrión: la beta-hCG no agrega nada."]),
  ("Gestante de 10 semanas", ["Náuseas y vómitos; PA 100/60, FC 100.", "Útero de ~9 cm, anexos libres, sin dolor."]),
  ["Pedir: hemograma, orina, VIH/sífilis y ecografía transvaginal (vitalidad y número de embriones).",
   "Náuseas y vómitos leves: fraccionar comidas, jengibre, piridoxina ± doxilamina.",
   "Hiperémesis o útero muy grande: eco (gemelar o mola) y electrolitos."],
  ACOG + " n.º 189 (náuseas y vómitos, 2018); " + MINSA + ".",
  op=("¿NO necesario?", ["Necesario: anemia", "Necesario: confirma vitalidad", "Necesario: bacteriuria", "Sí: el embarazo ya está claro", "Necesario: tamizaje obligatorio"],
      {3: "Dosaje de beta-hCG"}),
  d=dict(rotulo="¿Cuándo sí y cuándo no la beta-hCG?", alto_img=0,
         celdas=[("NO hace falta", ["Embarazo de 10 semanas con útero acorde", "La eco transvaginal confirma (este caso)"], None, True),
                 ("Sí: ¿hay embarazo?", ["Retraso menstrual reciente", "Antes de ver el saco por eco"], None, False),
                 ("Sí: ¿ectópico o aborto?", ["Dolor, sangrado, saco no visible", "Curva cada 48 h"], None, False),
                 ("Sí: ¿mola?", ["Útero muy grande, hiperémesis", "Seguimiento tras evacuar"], None, False)],
         veredicto=("Con 10 semanas confirmadas, la beta-hCG sobra", "La ecografía transvaginal da más información.")))

# GIN-176 · RPM a las 31 semanas · ÁRBOL + helecho
S("arbol", "GIN-176", "Gestante de 31 semanas con pérdida de líquido claro y cuello sin cambios: rotura prematura de membranas pretérmino, hospitalizar con corticoides y antibióticos",
  "Rotura prematura de membranas",
  ("RPM pretérmino", ["Entre las 24 y 33+6 semanas, sin infección ni sufrimiento fetal: manejo expectante hospitalizado hasta las 34 semanas.",
                      "Corticoides (madurez pulmonar) y antibióticos (prolongan la latencia y reducen la infección)."]),
  ("Gestante de 31 semanas", ["Dolor tipo contracción y pérdida de líquido claro.", "AU 25 cm, LCF 139; especuloscopía: líquido claro, cérvix sin cambios."]),
  ["Betametasona 12 mg IM, 2 dosis cada 24 h; sulfato de magnesio si el parto es inminente antes de las 32 semanas (neuroprotección).",
   "Ampicilina + eritromicina (o azitromicina) 7 días.",
   "Vigilar fiebre, taquicardia materna o fetal, leucocitos: corioamnionitis = terminar la gestación."],
  ACOG + " n.º 217 (2020); RCOG (2019); " + MINSA + ".",
  op=("¿Manejo?", ["Sí: expectante con corticoide y antibiótico", "No: a las 31 sem sin infección no se termina", "No: requiere hospitalización",
                   "No: no hay indicación de terminar ni de cesárea", "No: no se da tocólisis y alta en la RPM"],
      {0: "Hospitalizar, corticoides y antibióticos", 1: "Hospitalizar, antibióticos y terminar", 2: "Ambulatorio con antibiótico y corticoides",
       3: "Hospitalizar y cesárea"}),
  arbol=Q("RPM: ¿cuántas semanas tiene y hay infección?", [
      L("24-33+6 sem sin infección (este caso)", "HOSPITALIZAR: CORTICOIDE + ANTIBIÓTICO", ["Expectante hasta las 34 sem", "Mg si < 32 sem y parto inminente"], path=True),
      L("≥ 34 semanas", "Terminar la gestación", ["Inducción si no hay contraindicación"]),
      L("Corioamnionitis a cualquier edad", "Antibiótico y terminar", ["Fiebre, taquicardia, líquido fétido"])], path=True),
  banda=B("Cómo se confirma la rotura", P("helecho.jpg", 260, 260, [], credito="Paul_012" + CC + "CC BY-SA 2.0"),
          [("Cristalización en helecho", "El líquido amniótico seco en un portaobjetos forma «hojas de helecho»."),
           ("Especuloscopía", "Líquido que sale por el cuello (con Valsalva)."),
           ("Otros", "Papel de nitrazina (pH alcalino), pruebas de proteínas del líquido.")],
          pie="Muestra de otra persona."))

# GIN-177 · Amenorrea secundaria: descartar embarazo · RELOJ (orden de estudio)
S("reloj", "GIN-177", "Mujer joven con 7 semanas de amenorrea secundaria: lo primero es descartar embarazo con beta-hCG y ecografía transvaginal",
  "Amenorrea secundaria",
  ("Amenorrea secundaria", ["Ausencia de regla por ≥ 3 meses (o 3 ciclos) en quien ya menstruaba; en la práctica se estudia antes si hay sospecha.",
                            "La causa más frecuente en edad fértil es el embarazo: siempre se descarta primero."]),
  ("Mujer de 21 años", ["Amenorrea secundaria de 7 semanas.", "¿Qué va primero en el plan de trabajo?"]),
  ["Si la beta-hCG es negativa: TSH y prolactina; luego prueba de progestágeno.",
   "Sin sangrado con progestágeno: prueba con estrógeno + progestágeno y FSH/LH (falla ovárica o hipotalámica).",
   "Buscar síndrome de ovario poliquístico (hirsutismo, acné, ovarios), estrés, baja de peso, ejercicio."],
  "ASRM, amenorrea (2008; act.); ACOG; " + MINSA + ".",
  op=("¿Primer paso?", ["No: después de descartar embarazo", "Sí: el embarazo es la causa más frecuente", "No: poco útil al inicio", "No: después del embarazo",
                        "No: solo si la prolactina es alta"],
      {0: "FSH, prolactina y TSH", 1: "Beta-hCG y ecografía transvaginal", 3: "Prolactina si hubiera galactorrea"}),
  d=dict(rotulo="El orden de estudio de la amenorrea secundaria", tag="PRIMERO",
         pasos=[("1", "Beta-hCG + eco", "Descartar embarazo", True), ("2", "TSH y prolactina", "Tiroides e hiperprolactinemia", False),
                ("3", "Prueba de progestágeno", "¿Hay estrógeno y útero sano?", False), ("4", "Estrógeno + progestágeno", "Si no sangró", False),
                ("5", "FSH y LH", "Ovario o hipotálamo", False)],
         veredicto=("Primero beta-hCG y ecografía transvaginal", "En una mujer de 21 años con 7 semanas de atraso, el embarazo va primero.")))

# GIN-178 · Cistocele: colporrafia anterior · ÁRBOL (compartimentos)
S("arbol", "GIN-178", "Mujer de 52 años con polaquiuria y bulto vaginal por prolapso del compartimento anterior (cistocele): colporrafia anterior",
  "Prolapso de órganos pélvicos",
  ("Compartimentos del prolapso", ["Anterior: vejiga (cistocele). Apical: útero o cúpula (histerocele). Posterior: recto (rectocele).",
                                   "La cirugía repara el compartimento que falla: en el anterior, plicatura de la fascia (colporrafia anterior)."]),
  ("Mujer de 52 años", ["2 años de polaquiuria y sensación de bulto en la vagina.", "Alteración del compartimento anterior."]),
  ["Prolapso sintomático: pesario (si no desea cirugía) o cirugía según el compartimento.",
   "Antes: estudiar incontinencia de esfuerzo oculta (puede aparecer al corregir el cistocele).",
   "Ejercicios de piso pélvico en prolapsos leves."],
  "ACOG n.º 214 (2019; prolapso); IUGA/ICS, POP-Q.",
  op=("¿Tratamiento?", ["Sí: repara la pared anterior", "No: es para el apical (útero)", "No: es para la incontinencia de esfuerzo",
                        "No: es para el apical (cúpula)", "No: es alternativa, no definitivo"],
      {3: "Suspensión colposacra", 4: "Pesario como definitivo"}),
  arbol=Q("Prolapso: ¿qué compartimento cae?", [
      L("Anterior (vejiga) · este caso", "COLPORRAFIA ANTERIOR", ["Cistocele", "Polaquiuria, bulto"], path=True),
      L("Apical (útero o cúpula)", "Histerectomía vaginal o colposacropexia", ["Histerocele"]),
      L("Posterior (recto)", "Colporrafia posterior", ["Rectocele", "Dificultad para defecar"])], path=True))

# INF-086 · Meningitis tuberculosa: esquema · FASES
S("fases", "INF-086", "El tratamiento inicial de la meningitis tuberculosa es isoniazida, rifampicina, pirazinamida y etambutol (fase intensiva), con corticoide",
  "Tuberculosis extrapulmonar · meningitis tuberculosa",
  ("Meningitis tuberculosa", ["La forma más grave de TB: se trata con el mismo esquema de 4 fármacos, pero la fase de continuación se alarga.",
                              "Se añade corticoide (dexametasona o prednisona) para reducir la mortalidad y las secuelas."]),
  ("Pregunta de teoría", ["¿Esquema inicial de la meningitis tuberculosa?"]),
  ["MINSA: 2 meses HRZE + 10 meses HR (12 meses en total) para TB del sistema nervioso central y osteoarticular.",
   "Dexametasona 0,3-0,4 mg/kg/día con reducción en 6-8 semanas.",
   "La estreptomicina ya no forma parte del esquema de primera línea."],
  MINSA + ", NTS de tuberculosis (2023); " + OMS + ", guías consolidadas (2025).",
  op=("¿Esquema inicial?", ["Sí: HRZE", "No: la estreptomicina salió del esquema", "No: falta rifampicina y sobra estreptomicina", "No: falta pirazinamida",
                            "No: insuficiente"],
      {0: "Isoniazida, rifampicina, pirazinamida, etambutol", 1: "Estreptomicina + H + R + Z",
       2: "Estreptomicina + H + E + Z"}),
  d=dict(rotulo="Las fases del tratamiento en la meningitis tuberculosa", ans=0,
         fases=[("Intensiva", "2 meses", "HRZE DIARIO", ["Isoniazida, rifampicina, pirazinamida, etambutol", "Esta pregunta"]),
                ("Continuación", "10 meses", "HR", ["Isoniazida + rifampicina", "Más larga que en la TB pulmonar"]),
                ("Corticoide", "6-8 semanas", "DEXAMETASONA", ["Desde el inicio, con reducción"])]))

# PSI-035 · Dislexia: lectura · RADIAL
S("radial", "PSI-035", "La dislexia es un trastorno del neurodesarrollo que afecta el aprendizaje de la lectura",
  "Trastornos específicos del aprendizaje",
  ("Trastorno específico del aprendizaje", ["Dificultad persistente en una habilidad académica pese a inteligencia normal y buena enseñanza.",
                                            "Dislexia (lectura), disgrafía/disortografía (escritura) y discalculia (matemáticas)."]),
  ("Pregunta de teoría", ["La dislexia afecta la capacidad para…"]),
  ["Dislexia: lectura lenta, con errores al decodificar palabras y mala comprensión; base fonológica.",
   "Descartar problemas de visión y audición.",
   "Tratamiento: intervención psicopedagógica temprana y adaptaciones escolares."],
  "APA, DSM-5-TR (2022); AAP.",
  op=("¿Qué afecta?", ["No: es la discalculia", "No: lenguaje expresivo", "No: es la disgrafía", "Sí: lectura", "No: es la tartamudez (disfemia)"]),
  d=dict(rotulo="Cada trastorno, su habilidad", centro="APRENDIZAJE", centro_sub="inteligencia normal", ans=0,
         items=[("DISLEXIA", ["LEER", "Esta pregunta"]), ("DISGRAFÍA", ["Escribir (trazo)"]), ("DISORTOGRAFÍA", ["Escribir sin faltas"]),
                ("DISCALCULIA", ["Calcular"]), ("TARTAMUDEZ", ["Fluidez del habla (no es del aprendizaje)"])],
         ruta=["Bajo rendimiento", "Descartar visión y audición", "Evaluación psicopedagógica", "Intervención temprana"]))

# NEU-052 · Muerte por TEP masivo · CASCADA + ECG
S("cascada", "NEU-052", "La muerte por embolia pulmonar masiva se debe a la falla aguda del ventrículo derecho con choque (cardiogénico/obstructivo)",
  "Tromboembolismo pulmonar · fisiopatología",
  ("TEP masivo", ["El émbolo tapa la arteria pulmonar: el ventrículo derecho no puede vaciarse, se dilata y falla.",
                  "El VD dilatado empuja el tabique y llena mal al izquierdo: cae el gasto y la presión. Es choque obstructivo con falla de bomba del VD."]),
  ("Pregunta de teoría", ["¿Por qué muere el paciente con embolia pulmonar?"]),
  ["TEP de alto riesgo (choque o PAS < 90): trombólisis sistémica (alteplasa) si no hay contraindicación.",
   "Evitar sobrecargar de líquidos; noradrenalina si hay hipotensión.",
   "Signos: VD dilatado en la eco, troponina y BNP altos."],
  ESC + ", embolia pulmonar (2019); AHA (2025).",
  op=("¿Mecanismo de muerte?", ["No: no hay pérdida de volumen", "Sí: falla aguda del VD", "Contribuye, pero no mata sola", "No: no es lo típico", "No: no hay infección"]),
  d=dict(rotulo="Del émbolo a la muerte", cabeceras=("Qué pasa", "Qué se ve"),
         pasos=[("Émbolo en la arteria pulmonar", "Sube la poscarga del VD", [("Disnea súbita", "Taquicardia", False)]),
                ("El VD se dilata", "No puede vaciarse", [("Ingurgitación yugular", "S1Q3T3, BRD en el ECG", False)]),
                ("El tabique empuja al VI", "Llena mal el ventrículo izquierdo", [("Gasto cardíaco bajo", "Hipotensión", True)]),
                ("Isquemia del VD", "Menos flujo coronario con más trabajo", [("Choque y paro (AESP)", "Mecanismo de la muerte", True)])],
         veredicto=("Muere por falla aguda del VD: choque", "No por la hipoxemia sola.")),
  banda=B("Lo que muestra el ECG", P("tep_ecg.jpg", 380, 188, [], credito="W. Serra et al." + CC + "CC BY 2.0"),
          [("S1Q3T3", "S en DI, Q y T negativa en DIII: sobrecarga del VD."),
           ("Taquicardia sinusal", "Lo más frecuente."),
           ("Bloqueo de rama derecha", "VD dilatado.")],
          pie="ECG de otra persona."))

# SP-127 · Media y mediana · GRÁFICA (distribución asimétrica)
S("grafica", "SP-127", "Si la glucemia tiene media 95 y mediana 90, la mitad de los sujetos tiene valores menores de 90 mg/dL (distribución con cola a la derecha)",
  "Bioestadística · medidas de tendencia central",
  ("Media, mediana y moda", ["Mediana: el valor del medio al ordenar los datos (el 50 % queda por debajo).",
                             "Si la media es mayor que la mediana, hay valores altos que la «jalan»: asimetría positiva (cola a la derecha)."]),
  ("Muestra de glucemias", ["Media aritmética: 95 mg/dL.", "Mediana: 90 mg/dL."]),
  ["Moda: el valor más frecuente (no se puede saber con estos datos).",
   "La desviación estándar mide la dispersión: no se calcula con media y mediana.",
   "En datos asimétricos se prefiere informar la mediana."],
  "Daniel, Bioestadística 4.ª ed.; " + GORDIS + ".",
  op=("¿Verdadera?", ["Sí: definición de mediana", "No: 95 es la media, no la mitad", "No: eso es la moda (desconocida)", "No: no se deduce", "No: la moda no se conoce"],
      {0: "La mitad tiene < 90 mg/dL", 1: "La mitad tiene < 95 mg/dL", 2: "El valor más frecuente es 90", 3: "La DE es 5 mg/dL"}),
  d=dict(rotulo="Distribución con cola a la derecha", eje_x="Glucemia (mg/dL)", eje_y="Número de personas",
         x=(60, 160, [(60, "60"), (80, "80"), (90, "90"), (95, "95"), (120, "120"), (140, "140"), (160, "160")]),
         y=(0, 100, [(0, "0"), (50, "50"), (100, "100")]),
         series=[("Glucemia", [(60, 2), (66, 10), (72, 30), (78, 62), (84, 88), (87, 92), (90, 88), (95, 76), (100, 60), (108, 42), (118, 26),
                               (130, 14), (145, 6), (160, 2)], "#0f766e")],
         zonas=[(60, 90, "50 %", "#ccfbf1"), (90, 160, "50 %", "#f8fafc")],
         caso=(90, 88, "Mediana 90"),
         notas=[("Mediana 90: la mitad está por debajo", "Por definición (percentil 50).", True),
                ("Media 95: jalada por valores altos", "Cola a la derecha (asimetría positiva).", False),
                ("Moda: el pico", "Aquí ~87, pero el enunciado no la da.", False)],
         veredicto=("La mitad de los sujetos tiene < 90 mg/dL", "Media > mediana = asimetría positiva.")))

# SP-128 · Tasa específica de mortalidad · DOSIS (cálculo)
S("dosis", "SP-128", "Tasa específica de mortalidad por COVID = 300 muertes ÷ 20 000 habitantes × 1000 = 15 por mil",
  "Epidemiología · tasas de mortalidad",
  ("Tasa específica de mortalidad", ["Muertes por una causa ÷ población total (a mitad de año) × 1000.",
                                     "No confundir con la letalidad: muertes por la causa ÷ enfermos de esa causa × 100."]),
  ("Distrito de Lima, 2020", ["2000 defunciones; 300 por COVID.", "Población: 20 000; 1000 contagiados en la encuesta."]),
  ["Mortalidad general: 2000 ÷ 20 000 × 1000 = 100 por mil.",
   "Letalidad del COVID: 300 ÷ 1000 × 100 = 30 %.",
   "Mortalidad proporcional por COVID: 300 ÷ 2000 × 100 = 15 % (o 150 por mil de las muertes)."],
  GORDIS + "; OPS, indicadores de salud (2018).",
  op=("¿Tasa por mil?", ["No: no sale con estos datos", "No: es la letalidad (%)", "Sí: 300 ÷ 20 000 × 1000", "No: no sale con estos datos", "No: es la mortalidad proporcional (× 1000)"]),
  d=dict(rotulo="Calcula la tasa", peso_titulo="POBLACIÓN", peso=("20 000", "habitantes del distrito"),
         pasos=[("Muertes por COVID", "300", "Numerador"), ("Población total", "20 000", "Denominador"), ("Tasa × 1000", "15 ‰", "300 ÷ 20 000 × 1000")],
         ops=["÷", "="], tag="RESULTADO",
         alternativas=[("15 por mil", "Mortalidad específica", True), ("30", "Letalidad: ÷ 1000 enfermos", False),
                       ("150", "Mortalidad proporcional", False), ("33 o 66", "No salen con estos datos", False)],
         alt_titulo="De dónde salen las otras alternativas",
         veredicto=("15 por 1000 habitantes", "El denominador es la población, no los enfermos ni los muertos.")))

# SP-129 · Razón: hombres/mujeres · DECISIÓN
S("decision", "SP-129", "Número de hombres dividido entre número de mujeres es una razón (el numerador no está incluido en el denominador)",
  "Epidemiología · razón, proporción y tasa",
  ("Razón, proporción y tasa", ["Razón: divide dos grupos distintos (el numerador NO está en el denominador): hombres/mujeres.",
                                "Proporción: una parte sobre el total (sí está incluido), va de 0 a 1 (porcentaje). Tasa: añade el tiempo."]),
  ("Pregunta de teoría", ["N.º de hombres / N.º de mujeres: ¿qué medida es?"]),
  ["Ejemplo de razón: índice de masculinidad (100 hombres por cada 100 mujeres), razón de mortalidad materna.",
   "Proporción: prevalencia (casos/población).",
   "Tasa: incidencia (casos nuevos/población en riesgo en un tiempo)."],
  GORDIS + "; OPS, módulos de epidemiología.",
  op=("¿Medida?", ["No: es proporción × 100", "Sí: grupos distintos", "No: necesita tiempo y población en riesgo", "No: casos nuevos en un tiempo", "No: el numerador estaría en el total"]),
  d=dict(rotulo="¿Qué medida es?", eje_y="¿Numerador dentro?", ancho_filas=200,
         cols=["Sin tiempo", "Con tiempo"],
         rows=[("No", "Dos grupos distintos"), ("Sí", "Parte del total")],
         cells=[[("RAZÓN", ["Hombres / mujeres"]), ("—", ["No se usa"])],
                [("Proporción (%)", ["Prevalencia"]), ("Tasa", ["Incidencia"])]],
         caso=(0, 0), nota="Hombres no están dentro de «mujeres»: por eso es razón."))

# CB-062 · Anatomía del hilio pulmonar · LECTURA (esquema)
S("lectura", "CB-062", "En el hilio derecho el bronquio está detrás de la arteria pulmonar y en el izquierdo está debajo de ella",
  "Anatomía · hilio pulmonar",
  ("Hilio pulmonar", ["Por el hilio entran y salen el bronquio, la arteria pulmonar, las dos venas pulmonares, vasos bronquiales, linfáticos y nervios.",
                      "Derecha: bronquio posterior y alto (epiarterial). Izquierda: la arteria cruza por encima del bronquio. Las venas siempre abajo y adelante."]),
  ("Pregunta de teoría", ["Hilio derecho: bronquio ___ de la arteria.", "Hilio izquierdo: bronquio ___ de la arteria."]),
  ["Regla: «RALS» (Right Anterior, Left Superior): la arteria es anterior a la derecha y superior a la izquierda.",
   "Venas pulmonares: las más anteriores e inferiores en ambos lados.",
   "Importa en la cirugía (lobectomía) y para leer la TC del mediastino."],
  MOORE + "; Gray, Anatomía para estudiantes 5.ª ed.",
  op=("¿Posición del bronquio?", ["Sí: detrás (der.) y debajo (izq.)", "No: invertido", "No: a la derecha es detrás y arriba, pero a la izquierda debajo",
                                  "No: invertido", "No: a la derecha va detrás, no adelante"]),
  d=dict(rotulo="Lee el hilio de cada pulmón", img_titulo="Cara mediastínica de ambos pulmones (esquema)",
         img=PA("dib_hilio_pulmonar.jpg", 360, credito=PROPIO, fondo="#ffffff"), pines=[(0.19, 0.27), (0.76, 0.56)],
         pasos=[("Derecho: bronquio DETRÁS de la arteria", "Y algo más alto (epiarterial).", True),
                ("Izquierdo: bronquio DEBAJO de la arteria", "La arteria lo cruza por encima.", True),
                ("Venas: abajo y adelante", "En ambos lados.", False),
                ("Regla RALS", "Arteria: anterior a la derecha, superior a la izquierda.", False)],
         img_pie="Esquema: venas en rojo, arteria en azul.",
         veredicto=("Detrás (derecho) y debajo (izquierdo)", "La arteria es anterior a la derecha y superior a la izquierda.")))

# CB-063 · Língula: pulmón izquierdo · LECTURA (esquema)
S("lectura", "CB-063", "La língula es parte del lóbulo superior del pulmón izquierdo (equivale al lóbulo medio derecho)",
  "Anatomía · lóbulos pulmonares",
  ("Lóbulos pulmonares", ["Pulmón derecho: 3 lóbulos (superior, medio, inferior) y 2 cisuras. Pulmón izquierdo: 2 lóbulos (superior e inferior) y 1 cisura.",
                          "La língula es la «lengüeta» del lóbulo superior izquierdo, junto al corazón: es el equivalente del lóbulo medio derecho."]),
  ("Trabajador en control", ["Rx de tórax: tumoración en la língula.", "¿Dónde está la lesión?"]),
  ["La neumonía de la língula borra el borde izquierdo del corazón (signo de la silueta), como la del lóbulo medio borra el derecho.",
   "Un nódulo nuevo en un fumador: TC de tórax y seguimiento según Fleischner.",
   "Segmentos de la língula: superior (4) e inferior (5)."],
  MOORE + "; Fleischner Society (2017).",
  op=("¿Ubicación?", ["No: es una vía aérea", "Sí: lóbulo superior izquierdo", "No: el derecho no tiene língula", "No: es la bifurcación traqueal", "No: es su equivalente derecho"]),
  d=dict(rotulo="Ubica la língula", img_titulo="Pulmones de frente (esquema)",
         img=PA("dib_lobulos_pulmon.jpg", 360, credito=PROPIO, fondo="#ffffff"), pines=[(0.67, 0.67), (0.35, 0.6)],
         pasos=[("Língula: lóbulo superior izquierdo", "Junto al borde izquierdo del corazón.", True),
                ("Su equivalente: lóbulo medio derecho", "Solo el derecho tiene lóbulo medio.", False),
                ("Izquierdo: 2 lóbulos", "Deja espacio al corazón (escotadura cardíaca).", False),
                ("Signo de la silueta", "Língula borra el borde izquierdo del corazón.", False)],
         img_pie="Derecha del paciente = izquierda del dibujo.",
         veredicto=("La língula está en el pulmón izquierdo", "Es parte de su lóbulo superior.")))

# CB-064 · Quimiorreceptores centrales: CO2 · MATRIZ
S("matriz", "CB-064", "El aumento de la PaCO₂ estimula la respiración sobre todo a través de los quimiorreceptores centrales del bulbo raquídeo",
  "Fisiología respiratoria · control de la ventilación",
  ("Quimiorreceptores", ["Centrales (bulbo, cara ventral): sienten el H⁺ del LCR que produce el CO₂ al cruzar la barrera hematoencefálica; ~70-80 % del efecto del CO₂.",
                         "Periféricos (cuerpos carotídeos y aórticos): sienten sobre todo la hipoxemia (PaO₂ < 60) y la acidosis de la sangre."]),
  ("Pregunta de teoría", ["El CO₂ alto estimula la respiración: ¿dónde están los receptores?"]),
  ["El CO₂ cruza la barrera; el H⁺ no: por eso el LCR refleja el CO₂ y no la acidosis metabólica.",
   "En el EPOC retenedor, el estímulo pasa a depender de la hipoxemia: oxígeno controlado (SatO₂ 88-92 %).",
   "El centro respiratorio está en el bulbo y la protuberancia."],
  GUYTON + ".",
  op=("¿Dónde?", ["Responden sobre todo a la hipoxemia", "No: no hay quimiorreceptores", "No: no tiene esa función", "Sí: quimiorreceptores centrales", "No: controla la temperatura"],
      {0: "Cuerpos carotídeos y aórticos"}),
  d=dict(rotulo="¿Qué receptor responde a qué?", eje_x="Receptor", eje_y="Estímulo",
         cols=["Central (bulbo raquídeo)", "Periférico (carotídeo y aórtico)"], rows=["CO₂ alto (H⁺ en el LCR)", "O₂ bajo (PaO₂ < 60)"], caso=(0, 0),
         cells=[[("ESTÍMULO PRINCIPAL", ["~70-80 % del efecto del CO₂", "Este caso"]), ("Efecto menor", ["Rápido, ~20-30 %"])],
                [("No responde", ["No siente el O₂"]), ("ESTÍMULO PRINCIPAL", ["Hipoxemia: cuerpos carotídeos"])]]))

# CB-065 · Espacio muerto · DECISIÓN
S("decision", "CB-065", "El aire inspirado que no participa en la hematosis es el espacio muerto (vías de conducción y alvéolos sin sangre)",
  "Fisiología respiratoria · espacio muerto",
  ("Espacio muerto", ["Anatómico: el aire que queda en nariz, tráquea y bronquios (~150 mL o 2 mL/kg): ventila, pero no intercambia gases.",
                      "Alveolar: alvéolos ventilados sin flujo sanguíneo (como en el TEP). Anatómico + alveolar = fisiológico."]),
  ("Pregunta de teoría", ["El aire inspirado que NO participa en la hematosis es…"]),
  ["Ventilación alveolar = (volumen corriente − espacio muerto) × FR.",
   "Respirar rápido y superficial aumenta la proporción de espacio muerto (menos ventilación útil).",
   "El espacio muerto alveolar sube en el TEP y en el EPOC."],
  GUYTON + ".",
  op=("¿Concepto?", ["No: es lo que queda tras espirar al máximo", "No: incluye el espacio muerto, pero sí intercambia", "No: incluye aire que intercambia",
                     "Sí: no participa en la hematosis", "No: puede llegar a los alvéolos"]),
  d=dict(rotulo="¿Dónde se intercambian gases?", eje_y="Dónde está el aire", ancho_filas=200,
         cols=["Con sangre (perfundido)", "Sin sangre (no perfundido)"],
         rows=[("Vías de conducción", "Nariz → bronquiolos terminales"), ("Alvéolos", "Zona respiratoria")],
         cells=[[("ESPACIO MUERTO ANATÓMICO", ["~150 mL: no hay alvéolos"]), ("Espacio muerto anatómico", ["Igual: no intercambia"])],
                [("Hematosis", ["Ventilación alveolar útil"]), ("Espacio muerto alveolar", ["Ej.: TEP"])]],
         caso=(0, 0), nota="Espacio muerto fisiológico = anatómico + alveolar."))

# CB-066 · Capacidad vital · LECTURA (espirograma)
S("lectura", "CB-066", "La capacidad vital es el volumen corriente más el volumen de reserva inspiratoria y el de reserva espiratoria (no incluye el volumen residual)",
  "Fisiología respiratoria · volúmenes pulmonares",
  ("Volúmenes y capacidades", ["Volúmenes: corriente (~500 mL), reserva inspiratoria (~3 L), reserva espiratoria (~1,1 L) y residual (~1,2 L).",
                               "Capacidades = suma de volúmenes. Capacidad vital = VC + VRI + VRE (~4,6 L)."]),
  ("Pregunta de teoría", ["Capacidad vital = volumen corriente + ______"]),
  ["Capacidad pulmonar total = capacidad vital + volumen residual.",
   "Capacidad residual funcional = reserva espiratoria + residual (lo que queda tras una espiración normal).",
   "El volumen residual no se mide con espirometría (pletismografía o dilución de helio)."],
  GUYTON + ".",
  op=("¿Qué falta sumar?", ["Sí: VRE + VRI", "No: el residual no es parte de la CV", "No: el residual no es parte de la CV", "No: el residual no entra", "No: incluye el residual"],
      {2: "Volumen residual + reserva inspiratoria"}),
  d=dict(rotulo="Lee el espirograma", img_titulo="Espirograma (esquema)",
         img=PA("dib_espirograma.jpg", 380, credito=PROPIO, fondo="#ffffff"), pines=[(0.86, 0.1)],
         pasos=[("Capacidad vital", "Desde la inspiración máxima hasta la espiración máxima.", True),
                ("= corriente + reserva inspiratoria + reserva espiratoria", "Lo que se mueve en una maniobra máxima.", True),
                ("El residual queda siempre", "No se puede expulsar.", False),
                ("Capacidad pulmonar total", "= capacidad vital + residual.", False)],
         img_pie="Esquema.",
         veredicto=("Capacidad vital = VC + VRI + VRE", "El volumen residual no forma parte de ella.")))

# CB-067 · Difusión del O2 frente al CO2 · LABORATORIO (tabla comparativa)
S("laboratorio", "CB-067", "El oxígeno difunde unas 20 veces menos que el CO₂ porque es mucho menos soluble en agua",
  "Fisiología respiratoria · difusión de gases",
  ("Difusión alveolocapilar", ["La velocidad de difusión depende del gradiente de presión, el área, el grosor de la membrana y el coeficiente de difusión.",
                               "El coeficiente es proporcional a la solubilidad e inversamente a la raíz del peso molecular: el CO₂ es ~24 veces más soluble."]),
  ("Pregunta de teoría", ["Coeficiente de difusión del O₂ comparado con el del CO₂."]),
  ["Por eso en la enfermedad intersticial primero baja el O₂ (hipoxemia) y el CO₂ se mantiene o baja.",
   "La DLCO (difusión de CO) mide la capacidad de difusión de la membrana.",
   "El gradiente del O₂ (~60 mmHg) es mayor que el del CO₂ (~5 mmHg), pero no compensa su baja solubilidad."],
  GUYTON + "; West, Fisiología respiratoria 11.ª ed.",
  op=("¿Coeficiente del O₂?", ["No: unirse a la Hb no cambia la difusión", "Sí: menos soluble", "No: el gradiente no es el coeficiente", "No: el CO₂ difunde ~20 veces más",
                               "No: es menos soluble"],
      {0: "Mayor: se une a la hemoglobina", 2: "Mayor: su gradiente es alto"}),
  d=dict(rotulo="Oxígeno frente a CO₂",
         valores=[("Solubilidad en agua (relativa)", "O₂ = 1", "CO₂ ≈ 24", "↓", "El O₂ es mucho menos soluble."),
                  ("Coeficiente de difusión", "O₂ = 1", "CO₂ ≈ 20", "↓", "El CO₂ difunde ~20 veces más."),
                  ("Gradiente alvéolo-capilar", "~60 mmHg", "CO₂ ≈ 5 mmHg", "↑", "Ayuda al O₂, pero no compensa del todo."),
                  ("En la fibrosis pulmonar", "Baja primero", "CO₂ normal o bajo", "↓", "Hipoxemia antes que hipercapnia.")],
         veredicto=("El O₂ difunde menos porque es menos soluble", "Por eso la hipoxemia aparece antes que la hipercapnia en los problemas de difusión.")))

# INF-087 · Quantiferon · TARJETAS
S("tarjetas", "INF-087", "El Quantiferon (IGRA) detecta infección tuberculosa sin dar falsos positivos por la vacuna BCG",
  "Tuberculosis · pruebas de infección",
  ("Pruebas de infección tuberculosa", ["PPD (tuberculina) e IGRA (Quantiferon) detectan infección (memoria inmune), no enfermedad activa.",
                                        "El IGRA usa antígenos (ESAT-6, CFP-10) que no tiene la BCG: no se altera por la vacuna."]),
  ("Pregunta de teoría", ["¿Para qué sirve el Quantiferon?"]),
  ["Útil en vacunados con BCG, en quien no volverá a leer el PPD y para tamizaje de contactos y antes de biológicos.",
   "Ni el PPD ni el IGRA distinguen infección latente de TB activa.",
   "TB activa: baciloscopía, cultivo y prueba molecular (Xpert MTB/RIF) que además detecta resistencia a rifampicina."],
  OMS + ", infección tuberculosa latente (2024); CDC (2024); " + MINSA + ".",
  op=("¿Utilidad?", ["Sí: no se altera por la BCG", "No: mide memoria inmune contra TB", "No: no mide dosis", "No: lo hace Xpert o el cultivo", "No: no diferencia activa de latente"],
      {0: "Detectar infección sin falsos (+) por BCG", 1: "Medir la inmunidad del infectado", 3: "Detectar resistencia"}),
  d=dict(rotulo="Qué responde cada prueba", ans=1,
         cards=[dict(titulo="PPD", datos=[("Detecta", "Infección", False), ("BCG", "Puede dar (+)", False), ("Lectura", "48-72 h, induración", False)], pie="Barato."),
                dict(titulo="Quantiferon (IGRA)", datos=[("Detecta", "Infección", True), ("BCG", "No lo altera", True), ("Muestra", "Sangre, 1 visita", True)], pie="Esta pregunta."),
                dict(titulo="Baciloscopía y cultivo", datos=[("Detecta", "TB activa", False), ("Muestra", "Esputo", False), ("Cultivo", "Sensibilidad", False)], pie="Confirma enfermedad."),
                dict(titulo="Xpert MTB/RIF", datos=[("Detecta", "TB activa", False), ("Además", "Resistencia a R", False), ("Tiempo", "2 horas", False)], pie="Molecular.")]))
