"""Entrega 1 · tanda 10 (25 flujogramas)."""
from c28 import S, P, B, Q, L, TR, NELSON, HARRISON, MINSA, OMS, CDC, AAP, AHA, NICE

CC = " · Wikimedia Commons · "

# SP-022 · Cuidados paliativos · ÁRBOL
S("arbol", "SP-022", "Paciente en ventilación mecánica tras una hemorragia cerebral, con sepsis que no mejora y pronóstico muy malo: cuidados paliativos",
  "Bioética · adecuación del esfuerzo terapéutico",
  ("Cuidados paliativos y futilidad", ["Cuando un tratamiento ya no puede cambiar el pronóstico, insistir solo prolonga el sufrimiento.",
                                       "Paliar no es abandonar: se trata el dolor, la disnea y se acompaña a la familia."]),
  ("Varón de 31 años", ["Hemorragia cerebral casi fatal; craneotomía descompresiva; en ventilación mecánica.",
                        "Sepsis con poca mejoría; pronóstico muy malo."]),
  ["Decidir en equipo y con la familia, respetando la voluntad previa del paciente si se conoce.",
   "Adecuar el esfuerzo: no iniciar ni mantener medidas fútiles; priorizar confort y dignidad.",
   "En el Perú, la Ley 30846 crea el Plan Nacional de Cuidados Paliativos."],
  OMS + ", cuidados paliativos (2020); Ley n.º 30846 (2018); " + MINSA + ", plan nacional de cuidados paliativos.",
  op=("¿Conducta adecuada?", ["No: no cambia el pronóstico", "No: no hay tratamiento que cambie el desenlace", "No: medida fútil",
                              "Sí: confort, dignidad, acompañar a la familia", "No: sin indicación"]),
  arbol=Q("¿Algún tratamiento puede cambiar el pronóstico?", [
      L("Sí", "Seguir tratando", ["Con metas claras"]),
      L("No: pronóstico muy malo (este caso)", "CUIDADOS PALIATIVOS", ["Decidir con la familia", "Confort y dignidad"], path=True)], path=True))

# SP-023 · Muerte violenta · ÁRBOL
S("arbol", "SP-023", "Muerte por caída de un árbol sin testigos: no dar el certificado, comunicar al Ministerio Público",
  "Medicina legal · certificado de defunción",
  ("Muerte violenta o sospechosa", ["Accidente, homicidio, suicidio o causa dudosa: la investiga el fiscal.",
                                    "El médico no certifica: se hace levantamiento del cadáver y necropsia de ley."]),
  ("Hombre adulto en su comunidad", ["Los pobladores dicen que cayó de un árbol alto; estaba solo.", "Le piden el certificado de defunción."]),
  ["Solo se certifica la muerte natural de causa conocida.",
   "Muerte violenta o sin testigos: comunicar al Ministerio Público (fiscal) o a la policía.",
   "La necropsia la ordena el fiscal y la hace el médico legista; el médico del lugar no la decide por su cuenta."],
  "Ley General de Salud n.º 26842; Código Procesal Penal (levantamiento de cadáver y necropsia); " + MINSA + ", certificado de defunción.",
  op=("¿Actitud correcta?", ["Sí: muerte violenta, la investiga el fiscal", "No: no es muerte natural", "No: la ordena el fiscal",
                             "No: no le corresponde investigar", "No: sería falsear el documento"]),
  arbol=Q("¿Muerte natural con causa conocida?", [
      L("Sí", "Certificado de defunción", ["Lo firma el médico"]),
      L("No: caída sin testigos (este caso)", "MINISTERIO PÚBLICO", ["Levantamiento del cadáver", "Necropsia de ley"], path=True)], path=True))

# END-007 · Tormenta tiroidea · ÁRBOL + Burch-Wartofsky
S("arbol", "END-007", "Hipertiroidea con fiebre de 39 °C, taquiarritmia, desorientación e insuficiencia cardiaca: tormenta tiroidea",
  "Hipertiroidismo · tormenta tiroidea",
  ("Tormenta tiroidea", ["Tirotoxicosis extrema que falla órganos: fiebre, taquicardia, delirio, insuficiencia cardiaca.",
                         "Mortalidad alta: se trata en UCI sin esperar las hormonas."]),
  ("Mujer de 26 años", ["Baja de peso, temblor, piel caliente, hiperfagia, diarreas.",
                        "39 °C, taquiarritmia, desorientada, insuficiencia cardiaca; gammagrafía con captación alta."]),
  ["Propranolol, propiltiouracilo o metimazol y, 1 hora después, yodo (lugol).",
   "Hidrocortisona, enfriar con paracetamol (no aspirina) y tratar el desencadenante.",
   "Captación alta = Graves o bocio tóxico; captación baja = tiroiditis o hormona tomada (facticia)."],
  "ATA, guía de hipertiroidismo (2016); JTA/JES, tormenta tiroidea (2016); " + HARRISON + ".",
  op=("¿Diagnóstico?", ["No: la captación estaría baja", "No: sin crisis de PA; captación normal", "Sí: fiebre + delirio + falla cardiaca",
                        "Es la causa posible, no el cuadro", "No: no da fiebre ni captación alta"]),
  arbol=Q("Tirotoxicosis: ¿fiebre, delirio o insuficiencia cardiaca?", [
      L("Sí (este caso)", "TORMENTA TIROIDEA", ["UCI: propranolol + PTU", "Yodo, hidrocortisona"], path=True),
      L("No", "Hipertiroidismo", ["Metimazol + betabloqueador"])], path=True),
  escala=dict(nombre="Escala de Burch-Wartofsky", modo="puntaje", que="Suma la gravedad de cada órgano afectado por la tirotoxicosis.",
              items=[("T", "Temperatura (5 a 30)", "39 °C", 20), ("SNC", "Sistema nervioso (10 a 30)", "Desorientada", 20),
                     ("GI", "Digestivo-hepático (10 a 20)", "Diarreas frecuentes", 10),
                     ("ICC", "Insuficiencia cardiaca (5 a 15)", "Presente (al menos leve)", 5),
                     ("FC", "Frecuencia cardiaca (5 a 25)", "No se informa el valor", None),
                     ("FA", "Fibrilación auricular (10)", "Taquiarritmia: ver ECG", None)],
              total_txt="Total: 55 puntos o más", total_nota="sin contar la FC ni la FA",
              rangos=[("≥ 45", "Tormenta probable", "Tratar ya en UCI"), ("25-44", "Tormenta inminente", "Según el juicio clínico"),
                      ("< 25", "Improbable", "Buscar otra causa")],
              caso_rango=0, porque=[("Fiebre de 39 °C y desorientación suman 40", True), ("Diarrea e insuficiencia cardiaca superan los 45", True)],
              conducta="UCI: propranolol, PTU, yodo 1 h después, hidrocortisona y enfriamiento."))

# PED-036 · RVU · ÁRBOL + grados de reflujo
S("arbol", "PED-036", "Niño de 2 años con ITU febril recurrente, ecografía alterada y antecedente familiar de reflujo: cistouretrografía miccional",
  "Infección urinaria pediátrica · reflujo vesicoureteral",
  ("Reflujo vesicoureteral (RVU)", ["La orina sube de la vejiga al uréter y al riñón: favorece pielonefritis y cicatrices.",
                                    "Se diagnostica y gradúa con la cistouretrografía miccional seriada (CUMS)."]),
  ("Niño de 2 años", ["ITU febriles recurrentes; ecografía renal alterada.", "Disfunción vesical e intestinal; antecedente familiar de RVU."]),
  ["CUMS tras la 2.ª ITU febril, o tras la primera si la ecografía es anormal.",
   "Gammagrafía DMSA: busca cicatrices renales, no gradúa el reflujo.",
   "Tratar la disfunción vesical e intestinal; profilaxis antibiótica en grados altos; cirugía si hay infecciones pese a todo."],
  "EAU/ESPU, guía de urología pediátrica (2025); " + AAP + ", ITU febril de 2 a 24 meses (2011, reafirmada).",
  op=("¿Examen de elección?", ["Útil para empezar; no ve el reflujo", "Sí: ve y gradúa el reflujo", "Ve cicatrices, no gradúa el reflujo",
                               "Sin la fase miccional pierde reflujos", "No: obsoleta, mucha radiación"]),
  arbol=Q("ITU febril en niño: ¿recurrente o con ecografía anormal?", [
      L("Sí (este caso)", "CISTOURETROGRAFÍA MICCIONAL", ["Confirma y gradúa el RVU"], path=True),
      L("No, primera y eco normal", "Vigilar", ["Ecografía basta"])], path=True),
  escala=dict(nombre="Grados del reflujo vesicoureteral (Estudio Internacional)", que="Se definen en la CUMS según hasta dónde sube y cuánto dilata.",
              grados=[("I", "Solo uréter", ["Sin dilatación"]), ("II", "Hasta la pelvis", ["Sin dilatación"]),
                      ("III", "Dilatación leve", ["Cálices poco romos"]), ("IV", "Dilatación moderada", ["Cálices romos", "Uréter tortuoso"]),
                      ("V", "Dilatación grave", ["Pérdida de papilas", "Uréter muy tortuoso"])],
              caso=None, porque_titulo="Para ubicar este caso",
              porque=[("La CUMS define el grado", True), ("ITU febril + disfunción vesical: más riesgo de cicatriz", True)],
              conducta="CUMS; según el grado, profilaxis o cirugía; siempre tratar la disfunción vesical."))

# PED-037 · Neumonía grave del lactante · ÁRBOL + clasificación OMS
S("arbol", "PED-037", "Lactante de 6 meses con FR 60, tiraje subcostal, cianosis y crepitantes bilaterales: neumonía grave, ceftriaxona",
  "Infecciones respiratorias agudas · neumonía en el niño",
  ("Neumonía en el lactante", ["Respiración rápida (≥ 50 de 2 a 11 meses) y tiraje: neumonía.",
                               "La cianosis o la SatO₂ < 90 % la convierten en grave: hospitalizar."]),
  ("Lactante de 6 meses", ["5 días de tos y fiebre; FR 60, 38,5 °C.", "Tiraje subcostal, cianosis discreta, crepitantes bilaterales; leucocitosis con desviación izquierda."]),
  ["Neumonía grave: hospitalizar, oxígeno y antibiótico EV.",
   "OMS: ampicilina o penicilina + gentamicina; la ceftriaxona es la alternativa EV de muchas guías.",
   "Neumonía sin signos de gravedad: amoxicilina oral en casa."],
  OMS + ", manejo de la neumonía y la diarrea infantil (2024); " + MINSA + ", AIEPI; " + NELSON + ".",
  op=("¿Antibiótico?", ["No: es antiviral", "No: solo estafilococo", "Útil, pero no cubre bien H. influenzae", "Sí: EV, amplio espectro",
                        "No: es grave, necesita vía EV"]),
  arbol=Q("Tos con respiración rápida: ¿cianosis, SatO₂ < 90 % o signos de peligro?", [
      L("Sí: cianosis (este caso)", "NEUMONÍA GRAVE", ["Hospitalizar, oxígeno", "Antibiótico EV"], path=True),
      L("No: solo tiraje o FR alta", "Neumonía", ["Amoxicilina oral"])], path=True),
  escala=dict(nombre="Clasificación de la neumonía en el niño (OMS)", que="Clasifica por signos clínicos para decidir dónde tratar.",
              grados=[("Sin neumonía", "Tos o resfriado", ["FR normal, sin tiraje", "Casa"]),
                      ("Neumonía", "FR alta o tiraje", ["Amoxicilina oral", "Casa con control"]),
                      ("Neumonía grave", "Signos de peligro", ["Cianosis o SatO₂ < 90 %", "No puede lactar, convulsiona", "Hospitalizar"])],
              caso=2, porque=[("Cianosis discreta: signo de gravedad", True), ("FR 60 y tiraje subcostal", True)],
              conducta="Hospitalizar, oxígeno y antibiótico EV."))

# PED-038 · Reanimación neonatal · ÁRBOL
S("arbol", "PED-038", "Recién nacido en apnea con FC 90 que no mejora con secar, aspirar y estimular: ventilación a presión positiva",
  "Reanimación neonatal",
  ("Reanimación neonatal", ["La gran mayoría de recién nacidos que no respiran se recuperan solo con ventilar.",
                            "La FC es el mejor indicador de que la ventilación funciona."]),
  ("Recién nacido de término", ["Apgar 3 al minuto.", "Apnea con FC 90; no mejora tras aspirar ni estimular."]),
  ["Apnea, boqueo o FC < 100 tras los pasos iniciales: ventilación a presión positiva en el primer minuto (el «minuto de oro»).",
   "FC < 60 tras 30 segundos de ventilación efectiva: compresiones 3:1 con oxígeno al 100 %.",
   "FC < 60 pese a compresiones: adrenalina EV (0,02 mg/kg)."],
  AHA + "; AAP, Programa de Reanimación Neonatal (2025).",
  op=("¿Conducta?", ["Sí: apnea + FC < 100", "No: en apnea el oxígeno libre no ventila", "No: solo si FC < 60 tras compresiones",
                     "No: solo si FC < 60 tras ventilar", "No: pierde el minuto de oro"]),
  arbol=Q("Tras secar, abrigar y estimular: ¿respira y FC ≥ 100?", [
      L("Sí", "Cuidados de rutina", ["Piel a piel"]),
      Q("No: apnea con FC 90 (este caso)", [
          L("Ahora", "VENTILACIÓN A PRESIÓN POSITIVA", ["Máscara, 40-60 por minuto"], path=True),
          L("FC < 60 tras 30 s de VPP", "Compresiones + adrenalina", ["3:1, oxígeno al 100 %"])], edge="No", path=True)], path=True))

# SP-024 · Estudio ecológico · MATRIZ
S("matriz", "SP-024", "Relacionar la calidad del agua con la diarrea usando solo datos por localidad: estudio ecológico",
  "Epidemiología · diseños de estudio",
  ("Estudio ecológico", ["La unidad de análisis es un grupo (localidad, región, país), no la persona.",
                         "Útil para generar hipótesis con datos que ya existen; barato y rápido."]),
  ("Pregunta de investigación", ["¿Se relaciona la calidad del agua con la diarrea aguda?", "Solo hay casos por localidad."]),
  ["Datos agregados por grupo = ecológico.",
   "Su error típico es la falacia ecológica: lo que pasa en el grupo puede no pasar en cada persona.",
   "Para confirmar la relación hace falta un estudio con datos individuales (cohorte o casos y controles)."],
  "Gordis, Epidemiología 6.ª ed. (2019); Rothman, Modern Epidemiology 4.ª ed. (2021).",
  op=("¿Estudio adecuado?", ["No: requiere seguir personas", "No: requiere datos individuales", "Sí: datos por localidad",
                             "No: requiere datos individuales", "No: no se interviene"]),
  d=dict(rotulo="Diseño según la unidad de análisis", eje_x="Unidad de análisis", eje_y="Qué se hace",
         cols=["Personas", "Grupos (localidades)"], rows=["Se observa una vez", "Se sigue en el tiempo", "Se interviene"], caso=(0, 1),
         cells=[[("Transversal", ["Prevalencia", "Exposición y efecto juntos"]), ("ECOLÓGICO", ["Datos por localidad", "Riesgo: falacia ecológica"])],
                [("Cohorte o casos y controles", ["Exposición individual", "Riesgo relativo u OR"]), ("Ecológico de series", ["Tasas en el tiempo"])],
                [("Ensayo clínico", ["Asignación al azar"]), ("Ensayo comunitario", ["Se interviene la comunidad"])]]))

# OFT-007 · Rinitis vasomotora · TARJETAS
S("tarjetas", "OFT-007", "Rinorrea y congestión con los cambios de temperatura, pruebas cutáneas negativas y sin IgE ni eosinofilia: rinitis vasomotora",
  "Otorrinolaringología · rinitis", esp="OTORRINOLARINGOLOGÍA",
  tema=("Rinitis vasomotora (no alérgica)", ["Reacción nerviosa exagerada de la mucosa a cambios de temperatura, olores o humo.",
                                             "No hay alergia: pruebas cutáneas, IgE y eosinófilos normales."]),
  caso=("Mujer de 38 años", ["Rinorrea y congestión con los cambios de temperatura.",
                             "Cornetes hipertróficos; pruebas cutáneas negativas, sin IgE ni eosinofilia."]),
  perlas=["Tratamiento: corticoide nasal, azelastina nasal; ipratropio nasal si predomina la rinorrea.",
          "Evitar descongestionantes nasales más de 5 días: causan rinitis medicamentosa.",
          "Alérgica: prurito, estornudos en salva, prueba cutánea o IgE específica positiva."],
  fuente="ARIA, guía de rinitis (2024); EAACI, rinitis no alérgica (2017); Cummings Otolaryngology 7.ª ed. (2021).",
  op=("¿Tipo de rinitis?", ["Sí: desencadenante físico sin alergia", "No: pruebas e IgE negativas", "Describe la duración, no el tipo",
                            "No: sin costras ni mal olor", "No: no usa descongestionantes"]),
  d=dict(rotulo="Rinitis: ¿cuál?", ans=0,
         cards=[dict(titulo="Vasomotora", datos=[("Gatillo", "Frío, olores", True), ("Prueba cutánea", "Negativa", True), ("Eosinófilos", "Normales", True)],
                     pie="Este caso."),
                dict(titulo="Alérgica", datos=[("Gatillo", "Polvo, polen", False), ("Prueba cutánea", "Positiva", False), ("Prurito", "Sí", False)],
                     pie="Corticoide nasal."),
                dict(titulo="Medicamentosa", datos=[("Antecedente", "Oximetazolina", False), ("Tiempo", "> 5 días", False), ("Efecto", "Rebote", False)],
                     pie="Suspender."),
                dict(titulo="Atrófica", datos=[("Mucosa", "Seca, delgada", False), ("Costras", "Sí", False), ("Olor", "Fétido", False)],
                     pie="Lavados nasales.")]))

# SP-025 · Niveles de prevención · TARJETAS
S("tarjetas", "SP-025", "Mascarilla y cubrirse al toser para no transmitir la tuberculosis: prevención primaria",
  "Salud pública · niveles de prevención",
  ("Niveles de prevención (Leavell y Clark)", ["Primaria: evita que la enfermedad aparezca (promoción y protección específica).",
                                               "Secundaria: diagnóstico y tratamiento precoz; terciaria: limita secuelas."]),
  ("Pregunta de concepto", ["Mascarilla, cubrirse boca y nariz al toser, estornudar o reír.", "¿Qué nivel de prevención es?"]),
  ["Actúa antes de que el sano se infecte: es prevención primaria (protección específica).",
   "En TB, otras medidas primarias: BCG, ventilación, terapia preventiva a contactos.",
   "Pesquisa del sintomático respiratorio y tratamiento precoz: prevención secundaria."],
  "Leavell y Clark (1965); " + MINSA + ", norma técnica de tuberculosis (2023); " + OMS + ", control de infecciones en TB (2019).",
  op=("¿Nivel?", ["No existe ese nivel", "No: es diagnóstico precoz", "No: es rehabilitación", "Sí: evita el contagio del sano",
                  "No: evita daño por exceso médico"]),
  d=dict(rotulo="Los niveles de prevención", ans=0,
         cards=[dict(titulo="Primaria", datos=[("Cuándo", "Antes de enfermar", True), ("Meta", "Evitar el contagio", True), ("Ejemplo", "Mascarilla, BCG", True)],
                     pie="Este caso."),
                dict(titulo="Secundaria", datos=[("Cuándo", "Enfermedad inicial", False), ("Meta", "Detectar a tiempo", False),
                                                 ("Ejemplo", "Baciloscopia", False)],
                     pie="Tratar pronto."),
                dict(titulo="Terciaria", datos=[("Cuándo", "Enfermedad establecida", False), ("Meta", "Limitar secuelas", False),
                                                ("Ejemplo", "Rehabilitación", False)],
                     pie="Reinsertar."),
                dict(titulo="Cuaternaria", datos=[("Cuándo", "Cualquier momento", False), ("Meta", "Evitar sobretratar", False),
                                                  ("Ejemplo", "Pruebas innecesarias", False)],
                     pie="No dañar.")]))

# SP-026 · Peste neumónica: contacto cercano · ÁRBOL
S("arbol", "SP-026", "Peste neumónica en el norte del Perú: contacto cercano es quien estuvo a menos de 2 metros del enfermo",
  "Enfermedades metaxénicas y zoonosis · peste",
  ("Peste neumónica", ["Yersinia pestis; la forma neumónica se contagia de persona a persona por gotas.",
                       "En el Perú persiste en zonas rurales del norte (La Libertad, Lambayeque, Cajamarca, Piura)."]),
  ("Pregunta de concepto", ["Vigilancia de contactos de un caso de peste neumónica.", "¿Quién es contacto cercano?"]),
  ["Contacto cercano: estuvo a menos de 2 metros de un enfermo de peste neumónica.",
   "Quimioprofilaxis 7 días (doxiciclina o ciprofloxacino) y vigilancia de fiebre por 7 días.",
   "Personal de salud con protección respiratoria adecuada no es contacto; sin protección, sí."],
  OMS + ", guía de manejo de la peste (2021); " + MINSA + ", norma técnica de vigilancia y control de la peste.",
  op=("¿Contacto cercano?", ["Sí: a menos de 2 m, alcance de las gotas", "No: antes de enfermar no contagia", "Solo si estuvo a < 2 m",
                             "Solo sin protección y a < 2 m", "No: no es una exposición"],
      {0: "Estuvo a < 2 m del enfermo", 1: "Lo visitó 7 días antes de enfermar"}),
  arbol=Q("Exposición a peste neumónica: ¿a menos de 2 metros del enfermo?", [
      L("Sí (este caso)", "CONTACTO CERCANO", ["Quimioprofilaxis 7 días", "Vigilar fiebre 7 días"], path=True),
      L("No", "No es contacto cercano", ["Educación y vigilancia"])], path=True))

# PED-040 · Sepsis neonatal temprana · ÁRBOL + clasificación
S("arbol", "PED-040", "Recién nacido de 2 horas, madre sin control y RPM de 20 horas, con intolerancia oral y distensión: sepsis neonatal temprana",
  "Infecciones neonatales · sepsis",
  ("Sepsis neonatal temprana", ["Aparece en las primeras 72 horas; los gérmenes vienen del canal de parto (estreptococo B, E. coli).",
                                "Los signos son sutiles: rechazo al alimento, distensión, temperatura inestable, dificultad respiratoria."]),
  ("Recién nacido de 2 horas", ["Madre sin control prenatal; rotura de membranas de 20 horas.", "Intolerancia oral y distensión abdominal."]),
  ["Factores: RPM ≥ 18 horas, fiebre o corioamnionitis materna, estreptococo B, prematuridad.",
   "Hemocultivo y luego ampicilina + gentamicina EV de inmediato.",
   "Suspender a las 36-48 horas si el cultivo es negativo y el bebé está bien."],
  AAP + ", sepsis neonatal temprana (2018, act. 2024); " + NICE + " NG195 (2021, act. 2024); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: aparece con días de leche de vaca", "No: vómitos biliosos, sin factores", "No: no da distensión",
                        "Sí: RPM 20 h + signos sutiles", "No: salivación, no pasa la sonda"]),
  arbol=Q("Recién nacido con signos sutiles: ¿factores de riesgo infeccioso?", [
      L("RPM ≥ 18 h, sin control (este caso)", "SEPSIS NEONATAL TEMPRANA", ["Hemocultivo", "Ampicilina + gentamicina"], path=True),
      L("Sin factores", "Buscar otra causa", ["Vigilar"])], path=True),
  escala=dict(nombre="Sepsis neonatal según el momento", orden=False, que="El momento orienta el germen y el antibiótico.",
              grados=[("< 72 horas", "Temprana", ["Canal de parto: estreptococo B, E. coli", "Ampicilina + gentamicina"]),
                      ("> 72 horas", "Tardía", ["Hospital o comunidad: estafilococo, gramnegativos", "Según la flora del servicio"])],
              caso=0, porque=[("2 horas de vida", True), ("RPM de 20 horas y madre sin control", True)],
              conducta="Hemocultivo y ampicilina + gentamicina EV ya."))

# PED-041 · IC del lactante · ÁRBOL + Ross
S("arbol", "PED-041", "Lactante de 10 meses que suda al lactar, con taquipnea, retracciones, hepatomegalia y soplo sistólico: insuficiencia cardiaca, furosemida",
  "Cardiopatías congénitas · insuficiencia cardiaca en el lactante",
  ("Insuficiencia cardiaca del lactante", ["Lo más común: cortocircuito de izquierda a derecha (CIV) que congestiona los pulmones.",
                                           "Se cansa y suda al lactar, respira rápido, no gana peso; hígado grande."]),
  ("Varón de 10 meses", ["Lactancia entrecortada, taquipnea, sudoración de cabeza.",
                         "Polipnea, retracción subcostal, FC 160, hepatomegalia, soplo sistólico III/VI."]),
  ["Primero el diurético (furosemida) para la congestión; luego IECA para bajar la poscarga.",
   "Alimentación hipercalórica; ecocardiograma para el defecto; cirugía si no mejora o no crece.",
   "La digoxina queda como segunda línea; el propranolol no se usa en la congestión aguda."],
  "Park's Pediatric Cardiology 7.ª ed. (2020); " + NELSON + ".",
  op=("¿Fármaco inicial?", ["Después del diurético, no primero", "Segunda línea", "Solo en choque", "Sí: alivia la congestión",
                            "No: empeora la falla aguda"]),
  arbol=Q("Lactante con congestión por cortocircuito: ¿qué primero?", [
      L("Taquipnea + hepatomegalia (este caso)", "FUROSEMIDA", ["Quita la congestión"], path=True),
      L("Después", "IECA (captopril)", ["Baja la poscarga", "Ecocardiograma y cirugía"])], path=True),
  escala=dict(nombre="Clasificación de Ross (IC pediátrica)", que="Gradúa la insuficiencia cardiaca del lactante por los síntomas.",
              grados=[("I", "Sin síntomas", ["Asintomático"]), ("II", "Leve", ["Taquipnea o sudor leve al lactar"]),
                      ("III", "Moderada", ["Mucho sudor y taquipnea al lactar", "Mamadas largas, no gana peso"]),
                      ("IV", "Grave", ["Síntomas en reposo", "Retracciones, quejido"])],
              caso=3, porque=[("Taquipnea y retracciones en el examen, en reposo", True), ("Además lactancia entrecortada y sudor", True)],
              conducta="Furosemida, luego IECA; ecocardiograma y cirugía del defecto."))

# SP-027 · Calidad: aspectos tangibles · RADIAL
S("radial", "SP-027", "Instalaciones, equipos, personal y materiales de comunicación: dimensión de aspectos tangibles",
  "Gestión en salud · calidad de atención",
  ("Calidad percibida (SERVQUAL)", ["Compara lo que el usuario esperaba con lo que percibió, en 5 dimensiones.",
                                    "El MINSA la usa para medir la satisfacción del usuario externo."]),
  ("Pregunta de concepto", ["Instalaciones, equipos, personal y materiales de comunicación.", "¿Qué dimensión de la calidad es?"]),
  ["Tangibles: lo que se ve (limpieza, equipos, señalización, apariencia del personal).",
   "Fiabilidad: cumplir lo prometido; seguridad: confianza y competencia; empatía: atención personalizada.",
   "La quinta dimensión es la prontitud de la atención."],
  MINSA + ", guía técnica de evaluación de la satisfacción del usuario externo (RM 527-2011); Parasuraman, Zeithaml y Berry (1988).",
  op=("¿Dimensión?", ["No: es atender a tiempo", "No: es cumplir lo prometido", "Sí: lo que se ve y se usa",
                      "No: confianza y competencia", "No: atención personalizada"], {0: "Rapidez en la atención"}),
  d=dict(rotulo="Las 5 dimensiones de la calidad (SERVQUAL)", centro="CALIDAD PERCIBIDA", centro_sub="por el usuario", ans=0,
         items=[("TANGIBLES", ["Instalaciones, equipos, personal, materiales"]), ("FIABILIDAD", ["Cumplir lo prometido sin errores"]),
                ("PRONTITUD", ["Atender a tiempo y con disposición"]), ("SEGURIDAD", ["Confianza, competencia, cortesía"]),
                ("EMPATÍA", ["Atención individual"])],
         ruta=["Encuesta SERVQUAL", "Expectativa vs percepción", "Brecha por dimensión", "Plan de mejora"]))

# REU-010 · Dermatitis atópica del lactante · TARJETAS + criterios
S("tarjetas", "REU-010", "Lactante con prurito nocturno y eccema exudativo en cuero cabelludo, cara y extensoras: dermatitis atópica",
  "Dermatología pediátrica · dermatitis atópica",
  ("Dermatitis atópica", ["Eccema crónico con prurito; la piel pierde su barrera.",
                          "Cambia de lugar con la edad: cara y extensoras en el lactante, flexuras en el niño."]),
  ("Lactante", ["Prurito nocturno; lesiones recurrentes.", "Pápulas eritematosas, descamativas, exudativas en cuero cabelludo, cara y extensoras."]),
  ["Base del tratamiento: emolientes a diario y baño corto.",
   "Brotes: corticoide tópico; en cara y pliegues, tacrolimus o pimecrolimus.",
   "Casos graves: dupilumab desde los 6 meses."],
  "AAD, guía de dermatitis atópica (2023); EuroGuiDerm, dermatitis atópica (2022); " + NELSON + ".",
  op=("¿Sospecha?", ["No: surcos, familia con prurito", "No: placas con escama gruesa", "No: lesión donde tocó el alérgeno",
                     "Sí: prurito + cara y extensoras", "No: costras melicéricas"]),
  d=dict(rotulo="Dermatitis atópica según la edad", ans=0,
         cards=[dict(titulo="Lactante", datos=[("Lugar", "Cara, extensoras", True), ("Lesión", "Exudativa", True), ("Prurito", "Sí", True)],
                     pie="Este caso."),
                dict(titulo="Niño", datos=[("Lugar", "Flexuras", False), ("Lesión", "Seca", False), ("Piel", "Liquenificada", False)],
                     pie="Codos y rodillas."),
                dict(titulo="Adulto", datos=[("Lugar", "Manos, cuello", False), ("Lesión", "Liquenificada", False), ("Curso", "Crónico", False)],
                     pie="Párpados también."),
                dict(titulo="Dermatitis seborreica", datos=[("Edad", "< 3 meses", False), ("Escama", "Amarilla, grasa", False),
                                                           ("Prurito", "Poco", False)],
                     pie="Costra láctea.")]),
  triada=TR([("Prurito (obligatorio)", "Nocturno", True), ("Eccema en mejillas o extensoras", "Cara y extensoras", True),
             ("Antecedente en mejillas o flexuras", "Recurrente en cara", True), ("Inicio antes de los 2 años", "Lactante", True),
             ("Piel seca generalizada", "No se describe", False), ("Atopia personal o familiar", "No se describe", False)],
            [("Obligatorio", 0, 0), ("Criterios del UK Working Party (≥ 3)", 1, 5)],
            "Prurito + 3 criterios: dermatitis atópica.", rotulo="Criterios con nombre propio"))

# PED-042 · Neumonía típica · TARJETAS
S("tarjetas", "PED-042", "Lactante con fiebre de 39 °C, polipnea, tiraje, crepitantes focales, neutrofilia e infiltrado en base derecha: neumonía típica",
  "Infecciones respiratorias agudas · neumonía en el niño",
  ("Neumonía típica (bacteriana)", ["Neumococo sobre todo: fiebre alta, mal estado, crepitantes localizados.",
                                    "Rx con consolidación lobar o segmentaria; leucocitosis con neutrofilia."]),
  ("Lactante de 9 meses", ["Rinorrea y tos de 5 días; luego fiebre de 39 °C; mal estado general.",
                           "Polipnea, tiraje, crepitantes focales; neutrofilia; infiltrado en base derecha."]),
  ["Sin signos de gravedad: amoxicilina oral en dosis altas.",
   "Con tiraje y mal estado: hospitalizar y antibiótico EV; oxígeno si SatO₂ < 90-92 %.",
   "Atípica: mayores de 5 años, curso gradual, infiltrado intersticial; se trata con macrólido."],
  OMS + ", manejo de la neumonía infantil (2024); BTS, neumonía en niños (2011); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: mayor de 5 años, intersticial", "Sí: fiebre alta + foco + neutrofilia", "No: parches en ambos pulmones",
                        "No: sin infiltrado ni tiraje", "No: sin aspiración ni alteración neurológica"]),
  d=dict(rotulo="Neumonía en el niño: ¿cuál?", ans=0,
         cards=[dict(titulo="Típica", datos=[("Fiebre", "Alta, brusca", True), ("Rx", "Foco consolidado", True), ("Hemograma", "Neutrofilia", True)],
                     pie="Este caso."),
                dict(titulo="Atípica", datos=[("Edad", "> 5 años", False), ("Rx", "Intersticial", False), ("Curso", "Gradual", False)],
                     pie="Macrólido."),
                dict(titulo="Bronconeumonía", datos=[("Rx", "Parches bilaterales", False), ("Germen", "S. aureus, otros", False),
                                                     ("Estado", "Grave", False)],
                     pie="Hospitalizar."),
                dict(titulo="Bronquiolitis", datos=[("Edad", "< 2 años", False), ("Ruidos", "Sibilancias difusas", False), ("Fiebre", "Baja", False)],
                     pie="Soporte.")]))

# TRA-008 · Osteosarcoma · TARJETAS
S("tarjetas", "TRA-008", "Adolescente con dolor nocturno en el fémur distal que no cede con analgésicos y Rx con destrucción esclerótica: osteosarcoma",
  "Tumores óseos · osteosarcoma",
  ("Osteosarcoma", ["El tumor óseo maligno primario más común en adolescentes; nace en la metáfisis (fémur distal, tibia proximal).",
                    "Dolor nocturno que no cede, luego masa; la Rx muestra hueso destruido que forma hueso."]),
  ("Adolescente", ["Dolor en el tercio distal del muslo izquierdo que lo despierta de noche y no cede con analgésicos.",
                   "Luego aumento de volumen y marcha inestable; Rx: destrucción esclerótica del fémur distal."]),
  ["Rx: lesión mixta, triángulo de Codman y «rayos de sol»; RM de todo el hueso y TC de tórax (metástasis).",
   "Biopsia en un centro especializado, planificada con el cirujano que operará.",
   "Quimioterapia, cirugía con márgenes (salvamento del miembro) y otra vez quimioterapia."],
  "ESMO, sarcomas óseos (2025); NCCN Bone Cancer (2025).",
  op=("¿Diagnóstico?", ["Sí: metáfisis distal + hueso esclerótico", "No: fiebre y lesión lítica", "No: diáfisis, capas de cebolla",
                        "No: raro a esta edad", "No: benigno, sin destrucción"]),
  d=dict(rotulo="Tumor óseo en un adolescente: ¿cuál?", ans=0,
         cards=[dict(titulo="Osteosarcoma", datos=[("Lugar", "Metáfisis (rodilla)", True), ("Rx", "Esclerótico, rayos de sol", True),
                                                   ("Dolor", "Nocturno", True)],
                     pie="Este caso: biopsia."),
                dict(titulo="Sarcoma de Ewing", datos=[("Lugar", "Diáfisis, pelvis", False), ("Rx", "Capas de cebolla", False), ("Fiebre", "Puede", False)],
                     pie="t(11;22)."),
                dict(titulo="Osteomielitis", datos=[("Fiebre", "Sí", False), ("Rx", "Lítica, tardía", False), ("PCR", "Alta", False)],
                     pie="Antibióticos."),
                dict(titulo="Osteocondroma", datos=[("Tipo", "Benigno", False), ("Rx", "Exostosis", False), ("Dolor", "Poco", False)],
                     pie="Vigilar.")]))

# NRL-010 · Mielitis transversa · EMBUDO
S("embudo", "NRL-010", "Niño con debilidad flácida de las piernas y nivel sensitivo torácico tras una virosis: mielitis transversa",
  "Enfermedades de la médula espinal · mielitis transversa",
  ("Mielitis transversa", ["Inflamación de la médula, a menudo días o semanas después de una infección viral.",
                           "Debilidad de piernas, nivel sensitivo y trastorno de esfínteres; al inicio, flacidez (choque medular)."]),
  ("Niño", ["Infección viral previa.", "Debilidad brusca y progresiva de las piernas, flácida; nivel sensitivo torácico medio."]),
  ["RM de columna urgente: descartar compresión medular (tumor, absceso, hematoma).",
   "Metilprednisolona EV en dosis altas; plasmaféresis si no mejora.",
   "Buscar NMO (anti-AQP4) y anti-MOG: cambian el tratamiento y el pronóstico."],
  "Transverse Myelitis Consortium Working Group, criterios diagnósticos (2002); AAN, mielitis transversa (2011); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: sin nivel sensitivo", "Sí: nivel sensitivo + paraparesia", "No: puramente motora, asimétrica",
                        "No: conciencia normal", "No: rara en niños, recurrente"]),
  d=dict(rotulo="Debilidad aguda de piernas en un niño: ¿dónde está la lesión?", inicio="Paraparesia flácida + nivel sensitivo torácico",
         candidatos=["Meningoencefalitis", "Esclerosis múltiple", "Poliomielitis", "Polineuropatía infecciosa", "Mielitis transversa"],
         pasos=[("¿Conciencia normal, primer episodio?", ["Meningoencefalitis", "Esclerosis múltiple"]),
                ("¿Hay nivel sensitivo (no es solo motora ni periférica)?", ["Poliomielitis", "Polineuropatía infecciosa"])],
         final=("MIELITIS TRANSVERSA", ["Nivel sensitivo = médula"]),
         nota="RM urgente + corticoides EV."))

# PED-043 · GNPE · ÁRBOL + síndrome nefrítico
S("arbol", "PED-043", "Niño con hematuria, edema y PA elevada 7 días después de una faringoamigdalitis: glomerulonefritis postestreptocócica",
  "Enfermedades glomerulares · síndrome nefrítico",
  ("Glomerulonefritis postestreptocócica (GNPE)", ["Complejos inmunes tras una faringitis (1-3 semanas) o piodermitis (3-6 semanas).",
                                                   "Síndrome nefrítico: hematuria, edema, hipertensión, oliguria."]),
  ("Niño de 7 años", ["Faringoamigdalitis bacteriana hace 7 días.", "Edema, cefalea, PA en el percentil 90, hematuria."]),
  ["Laboratorio: C3 bajo (se normaliza en 6-8 semanas), ASO o anti-DNasa B altos.",
   "Tratamiento: restringir sal y líquidos, furosemida para el edema y la hipertensión.",
   "C3 bajo más de 8 semanas o hematuria persistente: biopsia (pensar en otra glomerulopatía)."],
  "KDIGO, enfermedades glomerulares (2021); " + NELSON + ".",
  op=("¿Diagnóstico?", ["Sí: nefrítico tras faringitis", "No: sin lupus ni otros órganos", "No: púrpura y dolor abdominal",
                        "No: hemoptisis + anti-MBG", "No: proteinuria masiva, sin hematuria ni HTA"]),
  arbol=Q("Síndrome nefrítico tras faringitis: ¿cuándo empezó?", [
      L("1-3 semanas después (este caso)", "GN POSESTREPTOCÓCICA", ["C3 bajo, ASO alta", "Sal, furosemida"], path=True),
      L("1-2 días después", "Nefropatía por IgA", ["C3 normal"])], path=True),
  triada=TR([("Hematuria", "Sí", True), ("Edema", "Sí", True), ("Hipertensión", "PA en p90, cefalea", True), ("Oliguria", "No se informa", False)],
            [("Síndrome nefrítico", 0, 3)],
            "Hematuria + edema + hipertensión tras faringitis: síndrome nefrítico por GNPE.", rotulo="Síndrome con nombre propio"))

# INF-017 · Uretritis gonocócica · ÁRBOL
S("arbol", "INF-017", "Secreción uretral purulenta y disuria 5 días después de una relación casual: ceftriaxona + azitromicina",
  "Infecciones de transmisión sexual · uretritis",
  ("Uretritis", ["Secreción purulenta abundante: gonococo; escasa y clara: clamidia u otros.",
                 "Se tratan ambos juntos porque coinciden con frecuencia."]),
  ("Varón de 18 años", ["Secreción purulenta por el meato y disuria.", "Relación sexual casual 5 días antes."]),
  ["Gonococo: ceftriaxona IM dosis única (500 mg a 1 g según la guía).",
   "Clamidia: hoy se prefiere doxiciclina 100 mg cada 12 h por 7 días; la azitromicina 1 g única sigue como alternativa.",
   "Tratar a las parejas, ofrecer VIH y sífilis, y usar preservativo."],
  CDC + ", guías de ITS (2021); " + OMS + ", tratamiento de gonorrea y clamidia (2024); " + MINSA + ", manejo sindrómico de ITS.",
  op=("¿Tratamiento?", ["Cefotaxima no es la de elección", "No: alta resistencia del gonococo", "No: para tricomonas",
                        "Sí: gonococo + clamidia", "No: para sífilis"]),
  arbol=Q("Uretritis: ¿secreción purulenta?", [
      L("Sí (este caso)", "CEFTRIAXONA + AZITROMICINA", ["O + doxiciclina 7 días", "Tratar a la pareja"], path=True),
      L("Escasa, clara", "Doxiciclina", ["Cubrir gonococo si no se descarta"])], path=True))

# INF-018 · Meningitis meningocócica · TARJETAS + signos + foto real
S("tarjetas", "INF-018", "Escolar con fiebre, cefalea, vómitos, rigidez de nuca, Brudzinski y petequias y equimosis: Neisseria meningitidis",
  "Infecciones del sistema nervioso · meningitis bacteriana",
  ("Meningitis meningocócica", ["Neisseria meningitidis: niños, adolescentes y adultos jóvenes; brotes en lugares cerrados.",
                                "Petequias y púrpura que no desaparecen a la presión: meningococcemia."]),
  ("Escolar", ["2 días de fiebre de 39-40 °C, cefalea que empeora al moverse, vómitos; somnoliento.",
               "Rigidez de nuca, Brudzinski positivo, petequias y equimosis en flexuras."]),
  ["Ceftriaxona EV de inmediato (no esperar la punción si hay púrpura o choque); hemocultivos.",
   "Aislamiento por gotas las primeras 24 horas de antibiótico.",
   "Contactos cercanos: profilaxis con ciprofloxacino, rifampicina o ceftriaxona."],
  NICE + " NG240, meningitis bacteriana y enfermedad meningocócica (2024); " + OMS + ", guía de meningitis (2025).",
  op=("¿Etiología?", ["Sí: meningitis + púrpura", "No: menores de 5 sin vacuna; sin púrpura", "No: no da meningitis así",
                      "No: hospitalaria o neutropénicos", "No: neonatos, ancianos, inmunodeprimidos"]),
  d=dict(rotulo="Meningitis bacteriana: ¿qué germen?", ans=0,
         cards=[dict(titulo="N. meningitidis", datos=[("Edad", "Escolar, joven", True), ("Piel", "Petequias, púrpura", True),
                                                      ("Curso", "Rápido", True)],
                     pie="Este caso: ceftriaxona."),
                dict(titulo="S. pneumoniae", datos=[("Edad", "Toda edad", False), ("Antes", "Otitis, neumonía", False), ("Piel", "Normal", False)],
                     pie="El más común."),
                dict(titulo="H. influenzae b", datos=[("Edad", "< 5 años", False), ("Vacuna", "No vacunado", False), ("Piel", "Normal", False)],
                     pie="Raro con vacuna."),
                dict(titulo="Listeria", datos=[("Edad", "Neonato, > 50", False), ("Riesgo", "Inmunodepresión", False), ("Piel", "Normal", False)],
                     pie="Agregar ampicilina.")]),
  triada=TR([("Rigidez de nuca", "Sí", True), ("Signo de Brudzinski", "Positivo", True), ("Signo de Kernig", "No se informa", False),
             ("Petequias y equimosis", "En flexuras", True)],
            [("Signos meníngeos", 0, 2), ("Pista del germen", 3, 3)],
            "Signos meníngeos + púrpura: meningococo hasta demostrar lo contrario."),
  banda=B("Púrpura de meningococcemia (foto real)", P("meningococo.jpg", 340, 219, [
            ("flechas", [(0.14, 0.33), (0.45, 0.45)], 0.3, 0.9, "manchas hemorrágicas\nestrelladas")],
          credito="A. I. Glei y A. V. Shkurba" + CC + "dominio público"),
          [("No desaparecen al presionar", "Prueba del vaso: si se ven a través del vidrio, es púrpura."),
           ("Forma estrellada", "Bordes irregulares con centro oscuro."),
           ("Crecen en horas", "Si se extienden, riesgo de choque y púrpura fulminante."),
           ("Antibiótico ya", "Ceftriaxona antes de cualquier examen.")],
          pie="Mano de otra paciente con meningococcemia.", ans=0))

# GAS-012 · Hepatitis A · TARJETAS
S("tarjetas", "GAS-012", "Niño de 3 años con fiebre, vómitos, coluria, acolia, ictericia y hepatomegalia: IgM anti-VHA confirma hepatitis A",
  "Hepatitis virales · hepatitis A",
  ("Hepatitis A", ["Transmisión fecal-oral; en niños suele ser leve y no se cronifica.",
                   "Pródromo (fiebre, vómitos) y luego ictericia, coluria y acolia."]),
  ("Niño de 3 años", ["5 días de malestar, hiporexia, vómitos, dolor abdominal, fiebre, coluria y acolia.", "Ictericia y hepatomegalia."]),
  ["IgM anti-VHA = infección aguda; IgG anti-VHA = infección pasada o vacuna.",
   "Tratamiento de soporte; vigilar el tiempo de protrombina (hepatitis fulminante, rara).",
   "Vacuna contra la hepatitis A en el calendario del MINSA; lavado de manos y agua segura."],
  "AAP, Red Book (2024); " + OMS + ", hepatitis A (2023); " + MINSA + ", esquema nacional de vacunación.",
  op=("¿Confirma?", ["No: hepatitis B", "No: hepatitis C, crónica", "Sí: infección aguda por VHA", "No: hepatitis E, rara en niños",
                     "No: infección pasada o vacuna"]),
  d=dict(rotulo="¿Qué marcador confirma una hepatitis A aguda?", ans=0,
         cards=[dict(titulo="IgM anti-VHA", datos=[("Indica", "Infección aguda", True), ("Aparece", "Con los síntomas", True), ("Dura", "3-6 meses", True)],
                     pie="Este caso."),
                dict(titulo="IgG anti-VHA", datos=[("Indica", "Pasada o vacuna", False), ("Protege", "De por vida", False), ("Agudo", "No sirve", False)],
                     pie="Inmunidad."),
                dict(titulo="HBsAg", datos=[("Indica", "Hepatitis B", False), ("Vía", "Sangre, sexual", False), ("Crónica", "Puede", False)],
                     pie="Otra hepatitis."),
                dict(titulo="Anti-VHC", datos=[("Indica", "Hepatitis C", False), ("Edad", "Adultos", False), ("Crónica", "Frecuente", False)],
                     pie="Otra hepatitis.")]))

# NEF-017 · Torsión testicular · ÁRBOL + TWIST
S("arbol", "NEF-017", "Escolar con dolor testicular brusco, tumefacción y reflejo cremastérico ausente: torsión testicular",
  "Urología · escroto agudo",
  ("Torsión testicular", ["El cordón gira y corta la sangre al testículo: se pierde en 6-8 horas.",
                          "Dolor brusco e intenso, testículo alto y horizontal, reflejo cremastérico ausente."]),
  ("Escolar", ["Dolor brusco en el testículo derecho.", "Tumefacción, dolor a la palpación y reflejo cremastérico ausente."]),
  ["Sospecha alta: cirugía inmediata (detorsión y fijación de ambos testículos); no retrasar por estudios.",
   "Duda: ecografía Doppler urgente, solo si no retrasa la cirugía.",
   "Epididimitis: inicio gradual, fiebre, reflejo cremastérico presente, Prehn positivo."],
  "EAU/ESPU, guía de urología pediátrica (2025); AUA, escroto agudo; Barbosa et al., puntaje TWIST (J Urol, 2013).",
  op=("¿Diagnóstico?", ["No: gradual, con fiebre y reflejo presente", "Sí: dolor brusco + cremastérico ausente", "No: gradual, con parotiditis",
                        "No: indoloro, bolsa de gusanos", "No: indoloro, transilumina"]),
  arbol=Q("Escroto agudo: ¿dolor brusco con reflejo cremastérico ausente?", [
      L("Sí (este caso)", "TORSIÓN TESTICULAR", ["Cirugía en < 6 h", "Doppler solo si no retrasa"], path=True),
      L("No: gradual, con fiebre", "Epididimitis", ["Prehn positivo", "Antibiótico"])], path=True),
  escala=dict(nombre="Puntaje TWIST", modo="puntaje", que="Estima el riesgo de torsión en el escroto agudo (0 a 7).",
              items=[("H", "Testículo hinchado (2)", "Tumefacción", 2), ("D", "Testículo duro (2)", "No se describe", 0),
                     ("C", "Reflejo cremastérico ausente (1)", "Ausente", 1), ("N", "Náuseas o vómitos (1)", "No se informa", 0),
                     ("A", "Testículo alto (1)", "No se informa", 0)],
              total_txt="Total: 3 puntos o más",
              rangos=[("5-7", "Riesgo alto", "Cirugía sin esperar la eco"), ("3-4", "Riesgo intermedio", "Doppler urgente"),
                      ("0-2", "Riesgo bajo", "Otra causa probable")],
              caso_rango=1, porque=[("Hinchazón + reflejo ausente: 3 puntos", True),
                                    ("Si además el testículo está duro o alto, pasa a riesgo alto", True)],
              conducta="Doppler urgente o cirugía directa si la clínica es clara; nunca esperar más de 6 horas."))

# PED-044 · Parálisis de Erb-Duchenne · TARJETAS + Narakas
S("tarjetas", "PED-044", "Recién nacido macrosómico con brazo en aducción, rotación interna y antebrazo en pronación: parálisis de Erb-Duchenne",
  "Traumatismo obstétrico · parálisis braquial",
  ("Parálisis de Erb-Duchenne", ["Lesión de las raíces C5-C6 por tracción del cuello en un parto difícil (distocia de hombros).",
                                 "Brazo en «propina de mesero»: aducción, rotación interna, pronación; la mano se mueve."]),
  ("Recién nacido macrosómico", ["Parto vaginal traumático.", "Brazo en aducción y rotación interna con antebrazo en pronación."]),
  ["Moro asimétrico, prensión palmar conservada.",
   "Fisioterapia desde las 1-3 semanas; la mayoría se recupera en meses.",
   "Si no recupera el bíceps a los 3-6 meses: cirugía del plexo."],
  NELSON + "; ACOG, distocia de hombros (2017, reafirmado).",
  op=("¿Diagnóstico?", ["No: crepitación, brazo sin postura fija", "No: mano en garra (C8-T1)", "No: dolor y crepitación",
                        "Sí: propina de mesero (C5-C6)", "No: brazo y mano flácidos"]),
  d=dict(rotulo="Brazo que no mueve tras el parto: ¿cuál?", ans=0,
         cards=[dict(titulo="Erb-Duchenne", datos=[("Raíces", "C5-C6", True), ("Postura", "Propina de mesero", True), ("Mano", "Se mueve", True)],
                     pie="Este caso."),
                dict(titulo="Klumpke", datos=[("Raíces", "C8-T1", False), ("Mano", "En garra", False), ("Ojo", "Horner posible", False)],
                     pie="Rara."),
                dict(titulo="Parálisis total", datos=[("Raíces", "C5-T1", False), ("Brazo", "Flácido", False), ("Mano", "No se mueve", False)],
                     pie="Peor pronóstico."),
                dict(titulo="Fractura de clavícula", datos=[("Tacto", "Crepitación", False), ("Brazo", "No lo mueve por dolor", False),
                                                           ("Rx", "Fractura", False)],
                     pie="Consolida sola.")]),
  escala=dict(nombre="Clasificación de Narakas", que="Ordena la parálisis braquial obstétrica por las raíces afectadas.",
              grados=[("Grupo I", "C5-C6", ["Erb clásica", "Mejor pronóstico"]), ("Grupo II", "C5-C7", ["Además no extiende el codo"]),
                      ("Grupo III", "C5-T1", ["Brazo flácido", "Sin Horner"]), ("Grupo IV", "C5-T1 + Horner", ["Peor pronóstico"])],
              caso=0, porque=[("Aducción, rotación interna y pronación: C5-C6", True), ("No se describe mano en garra ni Horner", True)],
              conducta="Fisioterapia temprana y control del bíceps a los 3-6 meses."))

# PED-045 · Convulsiones neonatales sutiles · TARJETAS
S("tarjetas", "PED-045", "Prematuro con asfixia que a la hora presenta mirada fija y masticación con protrusión de la lengua: convulsiones sutiles",
  "Neurología neonatal · convulsiones",
  ("Convulsiones neonatales", ["El cerebro inmaduro convulsiona de forma poco organizada: muchas son sutiles.",
                               "La causa más frecuente es la encefalopatía hipóxico-isquémica."]),
  ("Recién nacido prematuro", ["Apgar 3 al minuto y 7 a los 10 minutos.", "A la hora: mirada fija y movimientos bucolinguales."]),
  ["Confirmar con EEG (idealmente continuo): muchas convulsiones no se ven y otros movimientos no son convulsiones.",
   "Primero corregir glucosa, calcio, magnesio; fenobarbital es el de primera línea (ILAE 2023).",
   "La ILAE (2021) las llama hoy automatismos, apnea u otras según el signo; «sutiles» es el término clásico."],
  "ILAE, clasificación de crisis neonatales (2021) y guía de tratamiento (2023); Volpe's Neurology of the Newborn 7.ª ed. (2024).",
  op=("¿Tipo?", ["Sí: movimientos de boca y ojos", "No: sacudidas rítmicas", "No: postura rígida", "No: sacudidas bruscas aisladas",
                 "No: después del período neonatal"]),
  d=dict(rotulo="Convulsiones neonatales: ¿cuál?", ans=0,
         cards=[dict(titulo="Sutiles", datos=[("Boca", "Masticación, lengua", True), ("Ojos", "Mirada fija", True), ("Otros", "Pedaleo, apnea", True)],
                     pie="Este caso: EEG."),
                dict(titulo="Clónicas", datos=[("Movimiento", "Sacudidas rítmicas", False), ("Lugar", "Un miembro o cara", False),
                                               ("EEG", "Suele confirmar", False)],
                     pie="Pensar en infarto cerebral."),
                dict(titulo="Tónicas", datos=[("Postura", "Rígida, extensión", False), ("Quién", "Prematuros", False), ("Pronóstico", "Malo", False)],
                     pie="Hemorragia ventricular."),
                dict(titulo="Mioclónicas", datos=[("Movimiento", "Sacudida brusca", False), ("Ritmo", "No rítmico", False), ("Pronóstico", "Malo", False)],
                     pie="Errores del metabolismo.")]))

# PED-046 · Ictericia por policitemia · EMBUDO
S("embudo", "PED-046", "Ictericia neonatal por aumento de producción con reticulocitos normales: policitemia",
  "Ictericia neonatal · causas",
  ("Ictericia neonatal por producción aumentada", ["Más glóbulos rojos que se rompen = más bilirrubina indirecta.",
                                                   "Con hemólisis los reticulocitos suben; sin hemólisis (policitemia, cefalohematoma) son normales."]),
  ("Pregunta de concepto", ["Ictericia por aumento de producción.", "Reticulocitos normales."]),
  ["Policitemia: hematocrito venoso > 65 %; hijo de madre diabética, retardo de crecimiento, pinzamiento tardío del cordón.",
   "Hemólisis inmune (Rh, ABO): Coombs directo positivo y reticulocitos altos.",
   "Leche materna: no aumenta la producción, disminuye la eliminación."],
  AAP + ", hiperbilirrubinemia en el recién nacido ≥ 35 semanas (2022); " + NELSON + ".",
  op=("¿Condición?", ["Sí: más glóbulos sin hemólisis", "No: hemólisis, reticulocitos altos", "No: hemólisis, reticulocitos altos",
                      "No: hemólisis, reticulocitos altos", "No: menor eliminación, no más producción"]),
  d=dict(rotulo="Ictericia por más producción: ¿cuál con reticulocitos normales?", inicio="Ictericia por producción, reticulocitos normales",
         candidatos=["Ictericia por leche materna", "Incompatibilidad Rh", "Incompatibilidad ABO", "Esferocitosis", "Policitemia"],
         pasos=[("¿Hemólisis inmune (Coombs +, reticulocitos altos)?", ["Incompatibilidad Rh", "Incompatibilidad ABO"]),
                ("¿Hemólisis de membrana o no es de producción?", ["Esferocitosis", "Ictericia por leche materna"])],
         final=("POLICITEMIA", ["Hematocrito venoso > 65 %"]),
         nota="Más glóbulos que se rompen, sin hemólisis."))
