"""Bloque ENAM 2026 · Cirugía (parte 1)."""
from c26 import S, D, P, B, ILU, Q, L, SCHWARTZ, SABISTON, ATLS, MINSA
import ilu7 as I

O = I.ORANGE
ESP = "CIRUGÍA ENAM"

# CIR-125 · Íleo biliar · COMPARADOR (Rx y TC reales)
S("comparador", "CIR-125", "ileo-biliar-triada-rigler-rx-tc-enterolitotomia",
  "Íleo biliar: la tríada de Rigler en la Rx y la TC",
  "Obstrucción intestinal en el anciano · íleo biliar", ESP,
  ("Íleo biliar", ["Un cálculo grande pasa de la vesícula al duodeno por una fístula y tapa el íleon terminal.",
                   "Tríada de Rigler: obstrucción con niveles, aire en la vía biliar y cálculo fuera de la vesícula."]),
  ("Varón de 72 años, 48 h de cólico y vómitos", ["Distensión, timpanismo, RHA disminuidos.",
                                                  "Rx: niveles, aire en la vía biliar e imagen radiopaca en FID."]),
  ["Anciano con obstrucción de delgado + aerobilia + cálculo en FID = íleo biliar (tríada de Rigler).",
   "El tratamiento es quirúrgico: enterolitotomía para sacar el cálculo impactado.",
   "La colecistectomía y el cierre de la fístula se difieren si el paciente es frágil."],
  SABISTON + "; " + SCHWARTZ + ". Imágenes: Wikimedia Commons (licencia en la imagen).",
  d=dict(rotulo="El mismo paciente en Rx y TC (imágenes reales de referencia)", IH=374, tag="ESTE CASO",
         imgs=[dict(titulo="Rx simple de abdomen", archivo="ib_rx.jpg", on=True,
                    marcas=[("flecha", 0.479, 0.884, 0.74, 0.60, "Cálculo con borde\ncalcificado"),
                            ("flecha", 0.25, 0.885, 0.26, 0.56, "Asas con niveles\nhidroaéreos")],
                    pie="Asas de delgado dilatadas con niveles y, abajo, el cálculo en anillo fuera de la vesícula.",
                    credito="Rx y TC: Hellerhoff · Wikimedia Commons · CC BY-SA 4.0 · recorte"),
               dict(titulo="TC coronal", archivo="ib_tc.jpg",
                    marcas=[("flecha", 0.602, 0.747, 0.30, 0.90, "Cálculo impactado\nen el intestino"),
                            ("flecha", 0.33, 0.474, 0.30, 0.10, "Estómago y duodeno\ndistendidos")],
                    pie="La TC confirma el cálculo dentro del intestino; por encima, el tubo digestivo está distendido con líquido.",
                    credito="Hellerhoff · Wikimedia Commons · CC BY-SA 4.0 · recorte")],
         lectura_titulo="Cómo se lee y qué se hace",
         lectura=[("Tríada de Rigler", ["1. Obstrucción de delgado con niveles.", "2. Aire en la vía biliar.",
                                        "3. Cálculo fuera de la vesícula, casi siempre en FID."], False),
                  ("Cómo llega el cálculo", ["Colecistitis crónica → fístula entre vesícula y duodeno → el cálculo "
                                             "grande migra y se atasca en el íleon terminal."], False),
                  ("Tratamiento: cirugía", ["Reanimar, sonda nasogástrica y enterolitotomía (abrir el intestino "
                                            "por encima del cálculo y sacarlo)."], True)]),
  tabla=("Opciones de la pregunta",
         [("Colecistitis aguda", False), ("Coledocolitiasis", False), ("Colangitis", False), ("Íleo biliar", True)],
         [("Clave clínica", ["Murphy (+) y dolor en HD", "Ictericia y colestasis", "Fiebre, ictericia y dolor (Charcot)",
                             "Obstrucción + aerobilia + cálculo en FID"]),
          ("¿Encaja?", ["No: no da niveles ni cálculo en FID", "No: no hay ictericia", "No", "Sí"])]))

# CIR-126 · Evisceración · ÁRBOL + franja abdomen
S("arbol", "CIR-126", "herida-arma-blanca-evisceracion-epiplon-laparotomia",
  "Herida abdominal por arma blanca con evisceración: laparotomía",
  "Trauma abdominal penetrante · evisceración", ESP,
  ("Trauma abdominal penetrante por arma blanca", ["Lo que decide es si el peritoneo fue violado y si hay signos de lesión.",
                                                    "Evisceración, peritonitis o inestabilidad = laparotomía."]),
  ("Varón de 32 años, herida en hipogastrio", ["Estable: PA 120/75, FC 92, Glasgow 15.",
                                               "Herida de 3 cm con salida parcial del epiplón; abdomen blando."]),
  ["Evisceración = el peritoneo está abierto: laparotomía exploratoria urgente aunque esté estable.",
   "No se reintroduce el epiplón: se cubre con gasa húmeda estéril y se va a sala.",
   "El lavado peritoneal diagnóstico sirve en el trauma cerrado, no aquí."],
  ATLS + "; " + SCHWARTZ + ".",
  arbol=Q("¿Hay evisceración, peritonitis o inestabilidad?", [
      L("Sí", "LAPAROTOMÍA EXPLORATORIA URGENTE", ["Cubrir el epiplón con gasa húmeda estéril",
                                                  "Antibiótico y profilaxis antitetánica"], path=True),
      Q("¿La herida penetró el peritoneo?", [
          L("Sí o dudoso", "Observación seriada o laparoscopía", ["En paciente estable, sin signos"]),
          L("No", "Lavado y cierre de la herida", ["Alta con control"])], edge="No")], path=True),
  banda=B("Abdomen del caso", D(lambda s, x, y: I.abdomen(s, x, y, marcas=[(1, 196, 250)],
                                                          extra=I.E(150, 248, 24, 14, "#fde047", "#a16207", 2.5)
                                                          + I.P("M128 248 L172 248", "none", "#7f1d1d", 3)
                                                          + I.t(150, 232, "epiplón afuera", "#713f12", 10.5)),
                                  300, 330),
          ["Herida de 3 cm en el hipogastrio por la que sale el epiplón (evisceración).",
           "Si el epiplón está afuera, las tres capas de la pared y el peritoneo están abiertos.",
           "Aunque el paciente esté estable, puede haber lesión de víscera hueca sin dolor todavía: se explora."], ans=1),
  tabla=("Opciones de la pregunta", [("Laparotomía", True), ("Lavado peritoneal", False), ("Reintroducir epiplón", False),
                                     ("Laparoscopía", False)],
         [("¿Sirve aquí?", ["Sí: indicación absoluta", "No: es para trauma cerrado", "No: contamina y oculta lesiones",
                            "No: la evisceración ya indica explorar abierto"])]))

# CIR-127 · Quemadura de 2.º grado en manos · CRITERIOS de referencia
S("criterios", "CIR-127", "quemadura-segundo-grado-manos-adulto-mayor-lavar-referir",
  "Quemadura de 2.º grado en manos en un adulto mayor: primeros cuidados y referencia",
  "Quemaduras · manejo inicial en el primer nivel", ESP,
  ("Quemadura de espesor parcial", ["Ampollas y dolor: dañan la epidermis y parte de la dermis.",
                                    "En el primer nivel: enfriar y lavar, cubrir, calmar el dolor y decidir si se refiere."]),
  ("Varón de 73 años, puesto de salud", ["Fuego al cocinar hace 1 hora; dolor moderado.",
                                         "Ampollas en ambas manos y antebrazos: 16 % de superficie."]),
  ["Lavar con agua a temperatura ambiente; no romper las ampollas (son un apósito natural).",
   "No hay antibióticos profilácticos en quemaduras.",
   "Quemadura mayor en > 60 años (> 10 %) o en manos: referir a hospital con servicio de quemados."],
  "American Burn Association, criterios de referencia; " + ATLS + ".",
  d=dict(rotulo="¿Es una quemadura que se refiere?", tag="ESTE CASO",
         lista_titulo="Criterios de referencia (ABA)",
         items=[("Espesor parcial > 10 % en mayores de 60 años", True, "Tiene 16 % y 73 años"),
                ("Manos, cara, pies, genitales o articulaciones mayores", True, "Ambas manos y antebrazos"),
                ("Espesor total (3.er grado) en cualquier extensión", False, "Hay ampollas: es de espesor parcial"),
                ("Quemadura eléctrica, química o por inhalación", False, "Fue por fuego, sin lesión inhalatoria"),
                ("Enfermedades previas que compliquen la evolución", None, "No se menciona")],
         umbral="basta 1 criterio", veredicto="Se refiere tras lavar con agua, cubrir con apósito estéril sin romper las ampollas y dar analgesia",
         img_titulo="Zonas quemadas", img=D(lambda s, x, y: I.cuerpo(s, x + 20, y, {"mano_d": O, "mano_i": O, "antebrazo_d": O,
                                                                               "antebrazo_i": O}, sc=0.78), 230, 344),
         img_pie="Naranja: manos y antebrazos con ampollas (2.º grado, 16 %).",
         claves_titulo="Qué no hacer en el primer nivel",
         claves=[("Romper las ampollas", ["Expone la dermis: más dolor e infección; el desbridamiento es en sala."], False),
                 ("Antibiótico profiláctico", ["No previene la infección y selecciona resistencias."], False),
                 ("Lo correcto", ["Agua, apósito estéril, analgesia y referencia."], True)]),
  tabla=("Opciones de la pregunta", [("Desbridar + sulfadiazina", False), ("Lavar, cubrir y referir", True),
                                     ("Desbridar y ambulatorio", False), ("Antibiótico EV y control", False)],
         [("Error", ["Rompe ampollas y da antibiótico", "Ninguno", "No refiere una quemadura mayor", "Antibiótico sin indicación"])]))

# CIR-128 · Fisura anal crónica · ESCALERA (dibujos)
def _fisura(s, x, y):
    I.ano_frontal(s, x + 150, y + 4, "fisura", sc=0.95)
    I.ano_coronal(s, x + 500, y + 2, "esfinterotomia", sc=0.9)
S("escalera", "CIR-128", "fisura-anal-cronica-hipertonia-esfinterotomia-lateral-interna",
  "Fisura anal crónica: por qué la esfinterotomía lateral interna",
  "Patología anal · fisura anal", ESP,
  ("Fisura anal", ["Úlcera lineal del canal anal, casi siempre en la línea media posterior.",
                   "Crónica: más de 6-8 semanas, bordes elevados, hemorroide centinela y esfínter hipertónico."]),
  ("Mujer de 25 años, 8 semanas de dolor al defecar", ["Sangre roja en el papel; 4 semanas de fibra, laxantes y baños sin mejoría.",
                                                        "Fisura posterior con hemorroide centinela, papila hipertrófica y esfínter hipertónico."]),
  ["Fisura crónica = el esfínter interno hipertónico deja isquémica la zona y no cicatriza.",
   "Esfinterotomía lateral interna: cura > 90 % con poca incontinencia.",
   "Toxina botulínica o nitratos/diltiazem tópicos: alternativas si se quiere evitar cirugía."],
  "ASCRS, guía de fisura anal (2023); " + SCHWARTZ + ".",
  d=dict(rotulo="Lo que se ve y la escalera de tratamiento",
         img=dict(titulo="Fisura posterior y dónde se corta el esfínter", IH=250,
                  ilu=_fisura, pie="Izquierda: fisura en la línea media posterior con hemorroide centinela. Derecha: la "
                                   "esfinterotomía corta solo el esfínter interno (EAI), en el lado, lejos de la fisura."),
         check_titulo="¿Es una fisura crónica?",
         check=[("8 semanas de evolución", True), ("Hemorroide centinela y papila hipertrófica", True),
                ("Esfínter hipertónico y fracaso del manejo inicial", True)],
         veredicto="CRÓNICA: tratamiento de elección",
         peldanos=[("Fibra, laxante y baños de asiento", ["Base de todo tratamiento; cura muchas agudas."]),
                   ("Nitratos o diltiazem tópicos", ["«Esfinterotomía química» por 6-8 semanas."]),
                   ("Toxina botulínica", ["Alternativa para evitar el corte; recurre más."]),
                   ("Esfinterotomía lateral interna", ["Corta parte del esfínter interno: relaja y cicatriza."])],
         ans=3, tag="ESTE CASO", salto="Crónica con hipertonía: elección",
         leyenda_estable="Fisura aguda: se empieza abajo y se sube si no cicatriza.",
         leyenda_inestable="Fisura crónica (este caso): la esfinterotomía lateral interna es el tratamiento de elección."),
  tabla=("Opciones de la pregunta", [("Fistulectomía", False), ("Toxina botulínica", False), ("Fisurectomía sola", False),
                                     ("Esfinterotomía lateral interna", True)],
         [("Para qué sirve", ["Fístulas, no fisuras", "Segunda línea", "No corrige la hipertonía", "Corrige la hipertonía: elección"])]))

# CIR-129 · Diverticulitis no complicada · SEMÁFORO
S("semaforo", "CIR-129", "diverticulitis-sigmoidea-no-complicada-manejo-ambulatorio",
  "Diverticulitis no complicada: cuándo se trata en casa",
  "Enfermedad diverticular · diverticulitis aguda", ESP,
  ("Diverticulitis aguda", ["Inflamación de un divertículo, casi siempre del sigmoides: dolor en FII y fiebre.",
                            "La TC dice si es complicada (absceso, perforación, fístula, obstrucción)."]),
  ("Varón de 48 años, dolor en FII de 2 días", ["T 38 °C, estable, tolera la vía oral, sin comorbilidades.",
                                                "TC: diverticulitis sigmoidea no complicada."]),
  ["No complicada + tolera la vía oral + inmunocompetente + estable = manejo ambulatorio.",
   "Dieta líquida progresiva; antibiótico oral en el Perú (o sin antibiótico en casos seleccionados).",
   "Hospitalizar si no tolera la vía oral, hay comorbilidad, inmunosupresión o dolor intenso."],
  "ASCRS, guía de diverticulitis (2020); WSES (2020).",
  d=dict(rotulo="Imagen del caso y semáforo de conducta",
         ilu_titulo="Dónde está la inflamación",
         ilu=ILU(D(lambda s, x, y: I.abdomen(s, x, y + 6, on={"sigmoides", "colon_desc"}, marcas=[(1, 206, 262)], sc=0.9), 270, 300)),
         ilu_pie="Naranja: colon descendente y sigmoides; 1 = divertículo inflamado en la FII.",
         check_titulo="Datos que permiten tratar en casa",
         check=[("TC: no complicada (sin absceso ni perforación)", True), ("Tolera la vía oral", True),
                ("Hemodinámicamente estable", True), ("Sin comorbilidad ni inmunosupresión", True)],
         ans=0, tag="ESTE CASO",
         luces=[("No complicada, tolera la vía oral", "Ambulatorio", ["Dieta líquida, antibiótico oral y control en 48-72 h."]),
                ("No tolera, comorbilidad o absceso < 3 cm", "Hospitalizar", ["Antibiótico EV; absceso grande: drenaje percutáneo."]),
                ("Peritonitis purulenta o fecal", "Cirugía urgente", ["Lavado o resección (Hartmann)."])]),
  tabla=("Opciones de la pregunta", [("Hospitalizar con ATB EV", False), ("Sigmoidectomía inmediata", False),
                                     ("Colectomía tras 7 días", False), ("Ambulatorio", True)],
         [("¿Cuándo?", ["Si no tolera o hay comorbilidad", "Peritonitis generalizada", "No se indica de rutina", "Este caso"])]))

# CIR-130 · Absceso apendicular · ÁRBOL CON IMAGEN
S("arbol_imagen", "CIR-130", "absceso-apendicular-3-cm-drenaje-percutaneo-antibiotico",
  "Absceso apendicular: drenaje percutáneo más antibiótico",
  "Apendicitis complicada · absceso", ESP,
  ("Apendicitis complicada con absceso", ["Tras varios días de evolución el apéndice perforado queda rodeado y forma un absceso.",
                                          "En el paciente estable se trata sin cirugía urgente."]),
  ("Varón de 25 años, 6 días de dolor en FID", ["Estable, masa dolorosa en FID, sin peritonitis; leucocitos 23 000.",
                                                "Ecografía: absceso de 3 cm bien delimitado."]),
  ["Absceso apendicular ≥ 3 cm, accesible y paciente estable: drenaje percutáneo guiado por imagen + antibiótico EV.",
   "Absceso pequeño (< 3 cm) o no drenable: antibiótico solo.",
   "Operar en plena inflamación aumenta las complicaciones; la apendicectomía de intervalo es opcional."],
  "SAGES / EAES; WSES, guía de apendicitis (2020).",
  d=dict(rotulo="¿Qué hacer con el absceso?", tag="ESTE CASO",
         pregunta="Paciente estable con absceso apendicular: ¿se puede drenar por punción?",
         ramas=[("< 3 cm o sin acceso", "Antibiótico EV solo", ["Vigilar la evolución.", "Si no mejora: drenaje o cirugía."]),
                ("≥ 3 cm y accesible: este caso", "Drenaje percutáneo + antibiótico EV",
                 ["Guiado por ecografía o TC; se deja un catéter hasta que la cavidad se seque."])],
         ilu=lambda s, x, y: I.abdomen(s, x + 120, y, on={"apendice", "ciego"}, marcas=[(1, 84, 262)], sc=0.92,
                                         extra=I.E(84, 262, 20, 16, "#fde68a", "#b45309", 2.5)
                                         + I.P("M-14 300 L70 266", "none", "#1e3a8a", 3) + I.t(-16, 318, "catéter", "#1e3a8a", 10, "start")),
         IW=560, IH=305,
         ilu_pie="1 = absceso junto al ciego y el apéndice; en azul, el catéter de drenaje introducido por la piel.",
         luego_titulo="Qué sigue",
         luego=[("Mejora en 48-72 h", ["Completar antibiótico y retirar el catéter."], True),
                ("No mejora o peritonitis", ["Cirugía: apendicectomía y drenaje."], False),
                ("Después", ["Apendicectomía de intervalo (6-8 semanas) según el caso."], False)]),
  tabla=("Opciones de la pregunta", [("ATB EV solo", False), ("Referir", False), ("Drenaje + ATB", True), ("Cirugía inmediata", False)],
         [("¿Cuándo?", ["Absceso < 3 cm", "Si no hay imagen guiada", "Este caso", "Peritonitis o inestabilidad"])]))

# CIR-131 · Colecistitis aguda · CRONOLOGÍA en días
S("cronologia", "CIR-131", "colecistitis-aguda-tokio-colecistectomia-temprana-72-horas",
  "Colecistitis aguda: colecistectomía laparoscópica temprana",
  "Patología biliar · colecistitis aguda", ESP,
  ("Colecistitis aguda litiásica", ["Un cálculo tapa el cístico: dolor en HD, fiebre, Murphy (+) y leucocitosis.",
                                    "Grado I de Tokio (leve) en paciente sano: operar pronto."]),
  ("Mujer de 45 años, 24 h de dolor en HD", ["Fiebre 38,5 °C, Murphy (+), leucocitos 14 000.",
                                             "Eco: vesícula distendida, pared de 5 mm, litiasis; vía biliar normal."]),
  ["Colecistitis aguda leve o moderada en paciente apto: colecistectomía laparoscópica temprana (idealmente ≤ 72 h).",
   "La cirugía diferida (6 semanas) expone a nuevas crisis y complicaciones.",
   "Colecistostomía percutánea: solo en paciente de alto riesgo que no tolera cirugía."],
  "Guías de Tokio TG18; WSES (2020).",
  d=dict(rotulo="Vesícula del caso y cuándo operar", tag="ESTE CASO",
         ilu_titulo="Vesícula inflamada",
         ilu=ILU(D(lambda s, x, y: I.via_biliar(s, x, y + 8, calculos=["vesicula", "cistico"], vesicula="inflamada",
                                                 marcas=[(1, 128, 128)], sc=1.0), 330, 270)),
         ilu_pie="Pared roja y gruesa; 1 = cálculo enclavado en el cístico.",
         claves=[("Colecistectomía temprana", ["Dentro de las 72 h (hasta 7-10 días del inicio).",
                                               "Menos estancia y menos complicaciones."], True),
                 ("Colecistectomía diferida", ["A las 6 semanas: riesgo de nuevo cuadro mientras espera."], False),
                 ("Colecistostomía percutánea", ["Solo si el riesgo quirúrgico es muy alto."], False)],
         eje_titulo="Días desde el inicio del dolor", eje=(0, 56), paso=7, marca=1, unidad="d",
         eje_nombre="días desde el inicio",
         hitos=[(0, 3, "Colecistectomía temprana", "ventana ideal", True),
                (0, 10, "Límite para operar temprano", "hasta 7-10 días", False),
                (0, 7, "Antibiótico", "mientras se opera", False),
                (42, 56, "Colecistectomía diferida", "6-8 semanas", False)]),
  tabla=("Opciones de la pregunta", [("Diferida a 6 semanas", False), ("Colecistostomía", False), ("Temprana ≤ 72 h", True),
                                     ("Solo antibióticos", False)],
         [("¿Cuándo?", ["Ya no es la regla", "Alto riesgo quirúrgico", "Este caso", "No resuelve la causa"])]))

# CIR-132 · Hernia estrangulada · SEMÁFORO de viabilidad
S("semaforo", "CIR-132", "hernia-estrangulada-asa-negra-sin-pulso-reseccion-intestinal",
  "Hernia estrangulada: cuándo el asa ya no es viable",
  "Hernias · estrangulación intestinal", ESP,
  ("Viabilidad del asa en la hernia estrangulada", ["Tras liberar el anillo se mira color, brillo, peristalsis y pulso del mesenterio.",
                                                    "Si no se recupera con calor y tiempo, el asa está necrótica y se reseca."]),
  ("Varón de 70 años en cirugía de urgencia", ["Hernia inguinal estrangulada con fiebre y leucocitosis.",
                                               "Se expone el asa herniada: ¿qué obliga a resecar?"]),
  ["Asa negra que no recupera el color + sin pulso mesentérico + sin peristalsis = necrosis: resecar.",
   "Edema violáceo que mejora al liberar y calentar = asa viable: no se reseca.",
   "Tras la resección: anastomosis primaria si el paciente lo permite."],
  SCHWARTZ + "; " + SABISTON + ".",
  d=dict(rotulo="Cómo se juzga el asa en la cirugía",
         ilu_titulo="Tres aspectos del asa",
         ilu=ILU(D(lambda s, x, y: I.asa_viabilidad(s, x, y, caso=2, vertical=True), 270, 320)),
         ilu_pie="El caso (enmarcado): asa negra, sin brillo y sin pulso en el mesenterio.",
         check_titulo="Lo que se ve en el asa",
         check=[("Coloración negruzca que no cambia", False), ("Sin pulso en los vasos del mesenterio", False),
                ("Sin peristalsis ni brillo seroso", False), ("Probado tras liberar el anillo y calentar", True)],
         ans=2, tag="ESTE CASO",
         luces=[("Rosada, brillante, con pulso", "Viable", ["Solo reducir y reparar la hernia."]),
                ("Violácea que mejora al liberar", "Recuperable", ["Compresas tibias y esperar: si vuelve el color, no se reseca."]),
                ("Negra, sin pulso ni peristalsis", "Necrosis: resecar", ["Resección del segmento y anastomosis."])]),
  tabla=("Opciones de la pregunta", [("Líquido serohemático", False), ("Violáceo que mejora", False), ("Negra y sin pulso", True),
                                     ("Recupera el rosado", False)],
         [("Qué indica", ["Sufrimiento, no necrosis", "Asa viable", "Necrosis irreversible", "Asa viable"])]))

# CIR-134 · Adenocarcinoma de esófago T1b · ÁRBOL CON IMAGEN
S("arbol_imagen", "CIR-134", "barrett-adenocarcinoma-t1b-submucosa-esofagectomia",
  "Adenocarcinoma sobre Barrett T1b: esofagectomía con linfadenectomía",
  "Esófago de Barrett · cáncer temprano de esófago", ESP,
  ("Cáncer de esófago temprano", ["Lo que manda es la profundidad: mucosa (T1a) o submucosa (T1b).",
                                  "En la submucosa hay linfáticos: sube el riesgo de ganglios."]),
  ("Mujer de 55 años con Barrett de segmento largo", ["Lesión de 1,5 cm resecada por endoscopía.",
                                                      "Adenocarcinoma que invade la submucosa (T1b); sin metástasis."]),
  ["T1a (mucosa): la resección endoscópica puede curar (riesgo ganglionar 1-2 %).",
   "T1b (submucosa): riesgo ganglionar ~20-25 %: esofagectomía con linfadenectomía.",
   "Seguir solo con endoscopías deja crecer una enfermedad que puede estar en los ganglios."],
  "NCCN, cáncer de esófago (2024); " + SABISTON + ".",
  d=dict(rotulo="Qué profundidad tiene el tumor", tag="ESTE CASO",
         pregunta="¿Hasta qué capa llega el adenocarcinoma en la pieza resecada?",
         ramas=[("Solo mucosa: T1a", "Resección endoscópica", ["Puede ser curativa si los bordes están libres.", "Luego ablación del Barrett residual."]),
                ("Submucosa: T1b (este caso)", "Esofagectomía + linfadenectomía",
                 ["La submucosa tiene linfáticos: hay que sacar los ganglios regionales."])],
         ilu=lambda s, x, y: I.pared_capas(s, x + 70, y, I.CAPAS_ESO, invade=2, etiquetas_t=[(0, "T1a"), (2, "T1b"), (3, "T2")],
                                             titulo="Pared del esófago", sc=1.25),
         IW=560, IH=250,
         ilu_pie="El tumor (naranja) atraviesa la muscular de la mucosa y llega a la submucosa: T1b.",
         luego_titulo="Riesgo de ganglios según la profundidad",
         luego=[("T1a", ["1-2 %: la endoscopía basta."], False), ("T1b", ["20-25 %: cirugía con ganglios."], True),
                ("T2 o más, o N+", ["Neoadyuvancia y luego esofagectomía."], False)]),
  tabla=("Opciones de la pregunta", [("Resección ampliada", False), ("Seguimiento", False), ("Mucosectomía + IBP", False),
                                     ("Esofagectomía + ganglios", True)],
         [("¿Controla los ganglios?", ["No", "No", "No", "Sí"])]))

# CIR-135 · Mallampati · TERMÓMETRO
S("termometro", "CIR-135", "mallampati-clase-1-intubacion-facil-evaluacion-preanestesica",
  "Mallampati I: se espera una intubación fácil",
  "Anestesia · evaluación de la vía aérea", ESP,
  ("Escala de Mallampati", ["Con la boca abierta y la lengua afuera se mira qué estructuras de la faringe se ven.",
                            "Cuanto menos se ve, más difícil la laringoscopía."]),
  ("Niño de 5 años, cirugía por trauma facial", ["Mallampati clase I.", "Apertura bucal y movilidad cervical normales."]),
  ["Mallampati I: se ven paladar blando, úvula, fauces y pilares → intubación probablemente fácil.",
   "Mallampati III-IV + otros predictores (poca apertura, cuello rígido) → vía aérea difícil: tener videolaringoscopio.",
   "Ningún predictor es perfecto: siempre tener un plan B."],
  "Difficult Airway Society; ASA, guía de vía aérea difícil (2022).",
  d=dict(rotulo="Clase de Mallampati y dificultad esperada",
         niveles=[("Clase I", "Todo visible", ["Paladar blando, úvula,", "fauces y pilares"]),
                  ("Clase II", "Pilares ocultos", ["Paladar blando, úvula", "y fauces"]),
                  ("Clase III", "Base de la úvula", ["Paladar blando y base", "de la úvula"]),
                  ("Clase IV", "Solo paladar duro", ["No se ve el paladar blando"])],
         caso_nivel=0, ruta_titulo="Qué se espera y qué preparar", paso_label="ESTE CASO",
         pasos=[(1, "Intubación probablemente fácil", ["Laringoscopía convencional"], True),
                (2, "Clases III-IV", ["Posible vía aérea difícil: videolaringoscopio y dispositivo supraglótico"], False),
                (3, "Otros predictores", ["Apertura bucal, cuello, distancia tiromentoniana"], False)]),
  banda=B("Clases de Mallampati", D(lambda s, x, y: I.mallampati(s, x, y, 1, sc=0.9), 414, 144),
          ["Clase I (este caso): se ve toda la faringe.", "La lengua tapa más a medida que sube la clase.",
           "Clase IV: solo el paladar duro; alta probabilidad de intubación difícil."], ans=0),
  tabla=("Opciones de la pregunta", [("Intubación fácil", True), ("Videolaringoscopía obligatoria", False),
                                     ("Intubación imposible", False), ("Intubación difícil", False)],
         [("¿Encaja con clase I?", ["Sí", "No: sin predictores", "No", "No"])]))
