"""Bloque ENAM 2026 · Neurología, Traumatología, Psiquiatría, Oftalmología/ORL y Reumatología/Dermatología."""
from c26 import S, D, P, B, ILU, Q, L, HARRISON, MINSA, ATLS, NELSON
from engine7 import _img_draw
import ilu7 as I

O = I.ORANGE
EN, ET, EP, EO, ER = "NEUROLOGÍA ENAM", "TRAUMATOLOGÍA ENAM", "PSIQUIATRÍA ENAM", "OFTALMOLOGÍA Y ORL ENAM", "REUMATOLOGÍA Y DERMATOLOGÍA ENAM"
BTF = "Brain Trauma Foundation (2016)"

# NRL-062 · TEC moderado: Glasgow 9 · PUNTAJE + franja
S("puntaje", "NRL-062", "caida-arbol-glasgow-9-tec-moderado-sin-tc-via-aerea-referir",
  "Caída de un árbol con Glasgow 9 en un centro sin TC: asegurar la vía aérea y referir",
  "Traumatismo craneoencefálico · clasificación", EN,
  ("Escala de coma de Glasgow", ["Ojos (1-4) + verbal (1-5) + motor (1-6).",
                                 "TCE leve 13-15, moderado 9-12, grave 3-8."]),
  ("Varón de 20 años, centro de salud", ["Caída de 5 m con pérdida breve de conciencia; estable.",
                                         "Abre los ojos a la orden, palabras inapropiadas, flexión anormal al dolor; sin TC, hospital a 90 min."]),
  ["Glasgow 3 + 3 + 3 = 9: TCE moderado.",
   "Todo TCE moderado o grave necesita TC y neurocirugía: asegurar la vía aérea, estabilizar y referir al hospital III-1.",
   "La Rx de cráneo no descarta lesiones; ni el alta ni la observación sin referir son seguras."],
  ATLS + "; " + BTF + ".",
  d=dict(rotulo="Punto por punto", escala="Glasgow", total=9, max=15, interpreta="TCE moderado",
         items=[("Ojos: abre a la orden verbal", 3, True), ("Verbal: palabras inapropiadas", 3, True),
                ("Motor: flexión anormal (decorticación)", 3, True)],
         bandas=[("13-15", "Leve", "Observar; TC si hay factores de riesgo.", False), ("9-12", "Moderado", "TC y hospital con neurocirugía.", True),
                 ("3-8", "Grave", "Intubar, TC urgente, UCI.", False)]),
  banda=B("Lo que hace el paciente", D(lambda s, x, y: I.cuerpo(s, x + 40, y, marcas=[(1, 132, 34), (2, 120, 54), (3, 40, 170)], sc=0.7), 250, 312),
          ["Abre los ojos solo cuando se le habla: 3.", "Dice palabras sin sentido para la pregunta: 3.", "Ante el dolor dobla los brazos de forma anormal: 3."]),
  tabla=("Opciones de la pregunta", [("Vía aérea y referir a III-1", True), ("Rx de cráneo", False), ("Alta con signos de alarma", False),
                                     ("Observar 24 h sin referir", False)],
         [("Problema", ["Ninguno", "No descarta lesiones", "Inseguro", "Retrasa la TC y la cirugía"])]))

# NRL-063 · Guillain-Barré · EMBUDO + franja
_gb = "".join(I.flecha(x0, 400, x0, 330, I.ORANGE, 2.6) for x0 in (70, 170))
S("embudo", "NRL-063", "debilidad-ascendente-arreflexia-diarrea-previa-guillain-barre",
  "Debilidad simétrica ascendente con arreflexia tras una diarrea: síndrome de Guillain-Barré",
  "Neuropatías · parálisis flácida aguda", EN,
  ("Síndrome de Guillain-Barré", ["Polirradiculoneuropatía autoinmune tras una infección (Campylobacter, virus).",
                                  "Debilidad simétrica que sube desde las piernas, sin reflejos, con poca alteración sensitiva."]),
  ("Varón de 30 años", ["3 días de debilidad simétrica en las piernas; diarrea acuosa una semana antes.",
                        "Fuerza 3/5, arreflexia rotuliana y aquiliana, hipotonía; sensibilidad y esfínteres normales; afebril."]),
  ["Parálisis flácida simétrica ascendente + arreflexia + infección previa = Guillain-Barré.",
   "Confirmar con LCR (disociación albúmino-citológica) y electromiografía; vigilar la capacidad vital.",
   "Inmunoglobulina EV o plasmaféresis; los corticoides no sirven."],
  HARRISON + "; Guía europea EAN/PNS (2023).",
  d=dict(rotulo="De la debilidad a la causa", inicio="Debilidad simétrica de piernas con arreflexia",
         candidatos=["Miastenia gravis", "Mielitis transversa", "Poliomielitis", "Guillain-Barré"],
         pasos=[("¿Fatiga que empeora al usar el músculo, ptosis, reflejos normales?", ["Miastenia gravis"]),
                ("¿Nivel sensitivo y vejiga comprometida?", ["Mielitis transversa"]),
                ("¿Fiebre y parálisis asimétrica sin vacuna?", ["Poliomielitis"])],
         final=("Guillain-Barré", ["Ascendente, simétrico, sin reflejos, tras diarrea"]),
         nota="Sensibilidad y esfínteres normales con arreflexia: nervio periférico, no médula."),
  banda=B("Cómo avanza", D(lambda s, x, y: I.cuerpo(s, x + 40, y, {"pierna_d": "#bfdbfe", "pierna_i": "#bfdbfe", "muslo_d": "#dbeafe", "muslo_i": "#dbeafe"},
                                                     extra=_gb, sc=0.7), 250, 312),
          ["Empieza en los pies y sube (flechas).", "Simétrica: ambas piernas a la vez.", "Peligro: si llega al diafragma, falla la respiración."]),
  tabla=("Opciones de la pregunta", [("Miastenia gravis", False), ("Guillain-Barré", True), ("Mielitis transversa", False), ("Poliomielitis", False)],
         [("¿Encaja?", ["No: reflejos normales", "Sí", "No: sin nivel ni vejiga", "No: sin fiebre ni asimetría"])]))

# NRL-064 · Demencia vascular: lagunas · COMPARADOR (dibujos)
S("comparador", "NRL-064", "hipertenso-74-anos-sindrome-pseudobulbar-hachinski-infartos-lacunares",
  "Hipertenso con deterioro cognitivo y síndrome pseudobulbar: infartos lacunares múltiples",
  "Demencias · demencia vascular", EN,
  ("Demencia vascular subcortical", ["La hipertensión daña las arterias pequeñas: infartos lacunares y leucoaraiosis.",
                                     "Enlentecimiento, alteración de la marcha y síndrome pseudobulbar."]),
  ("Varón de 74 años, HTA de 20 años mal controlada", ["2 años de olvidos, enlentecimiento, dificultad para caminar, hablar y deglutir.",
                                                       "Hachinski 5: orienta a demencia vascular."]),
  ["TC típica: múltiples lagunas en sustancia blanca periventricular y ganglios basales, con leucoaraiosis.",
   "Alzheimer: atrofia temporal y parietal sin lesiones de sustancia blanca.",
   "Hidrocefalia normotensa: ventrículos grandes sin surcos ampliados; hematoma lobar: angiopatía amiloide."],
  HARRISON + "; AHA/ASA, deterioro cognitivo vascular (2011).",
  d=dict(rotulo="Lagunas frente a hidrocefalia", IH=262, tag="ESTE CASO",
         imgs=[dict(titulo="Infartos lacunares", on=True, ilu=lambda s, x, y: I.tc_craneo(s, x + 67, y, "lacunas"),
                    pie="Huecos oscuros (lagunas) en ganglios basales y sustancia blanca gris oscura alrededor de los ventrículos (leucoaraiosis)."),
               dict(titulo="Hidrocefalia normotensa", ilu=lambda s, x, y: I.tc_craneo(s, x + 67, y, "ventriculos"),
                    pie="Ventrículos grandes sin infartos (esquema de TC).")],
         lectura_titulo="Otras imágenes",
         lectura=[("Lagunas múltiples", ["HTA de años + pseudobulbar: este caso."], True),
                  ("Atrofia temporoparietal", ["Alzheimer."], False),
                  ("Hematoma lobar único", ["Angiopatía amiloide; es agudo."], False)]),
  tabla=("Opciones de la pregunta", [("Hematoma lobar", False), ("Atrofia temporoparietal", False), ("Ventriculomegalia", False),
                                     ("Lagunas múltiples", True)],
         [("Sugiere", ["Hemorragia aguda", "Alzheimer", "Hidrocefalia normotensa", "Demencia vascular"])]))

# NRL-065 · Temblor esencial · TARJETAS + franja
S("tarjetas", "NRL-065", "temblor-postural-bilateral-mejora-alcohol-familia-temblor-esencial",
  "Temblor postural bilateral que mejora con alcohol y es familiar: temblor esencial",
  "Trastornos del movimiento · temblor", EN,
  ("Temblor esencial", ["El trastorno del movimiento más frecuente del adulto; muchas veces familiar.",
                        "Temblor de acción y postural de las manos, a veces de la voz o la cabeza; mejora con alcohol."]),
  ("Varón de 65 años con litio hace 10 años", ["2 años de temblor progresivo de ambas manos que mejora con 1-2 cervezas.",
                                               "Padre y abuelo con temblor; temblor postural y de la voz; resto normal."]),
  ["Temblor postural bilateral + historia familiar + mejora con alcohol = temblor esencial.",
   "Tratamiento si molesta: propranolol o primidona.",
   "Litio: temblor fino con otros signos de toxicidad (ataxia, confusión); Parkinson: temblor de reposo con rigidez y bradicinesia."],
  HARRISON + "; MDS, consenso de temblor (2018).",
  d=dict(rotulo="Cuatro causas de temblor", ans=0,
         cards=[dict(titulo="Temblor esencial", datos=[("Tipo", "Postural y de acción", True), ("Familia", "Padre y abuelo", True),
                                                       ("Alcohol", "Mejora", True)], pie="Este caso."),
                dict(titulo="Intoxicación por litio", datos=[("Tipo", "Fino, con ataxia", False), ("Otros", "Confusión, diarrea", False),
                                                             ("Familia", "No", False)], pie="Examen neurológico alterado."),
                dict(titulo="Hipertiroidismo", datos=[("Tipo", "Fino, rápido", False), ("Otros", "Taquicardia, baja de peso", False),
                                                      ("Familia", "No", False)], pie="Sin otros síntomas aquí."),
                dict(titulo="Parkinson", datos=[("Tipo", "De reposo", False), ("Otros", "Rigidez, bradicinesia", False),
                                                ("Alcohol", "No mejora", False)], pie="Asimétrico al inicio.")]),
  banda=B("Espiral dibujada (esquema)", D(lambda s, x, y: I.espiral(s, x, y, sc=0.95), 345, 172),
          ["Al dibujar una espiral el trazo tiembla: temblor de acción.", "En el Parkinson el temblor es en reposo y mejora al moverse.",
           "Dificulta la escritura y las tareas finas."], ans=0),
  tabla=("Opciones de la pregunta", [("Intoxicación por litio", False), ("Temblor esencial", True), ("Hipertiroidismo", False), ("Parkinson", False)],
         [("¿Encaja?", ["No: sin otros signos", "Sí", "No: sin otros síntomas", "No: no es de reposo"])]))

# NRL-066 · TEC grave con herniación: TC urgente · ÁRBOL CON IMAGEN
S("arbol_imagen", "NRL-066", "tec-glasgow-8-midriasis-izquierda-bradicardia-tc-urgente-neurocirugia",
  "TEC grave con midriasis arreactiva tras estabilizar: TC de cráneo urgente para decidir cirugía",
  "Traumatismo craneoencefálico · herniación", EN,
  ("Herniación uncal", ["Un hematoma empuja el uncus contra el III par: pupila dilatada del mismo lado.",
                        "Puede haber bradicardia e hipertensión (Cushing): es una emergencia quirúrgica."]),
  ("Varón de 45 años, accidente de tránsito", ["Glasgow 8, PA 100/50, FC 55, pupila izquierda midriática y arreactiva.",
                                               "Vía aérea asegurada, oxígeno y estabilización en curso."]),
  ["Con la vía aérea y la PA aseguradas: TC de cráneo urgente para localizar la lesión y llevar a cirugía.",
   "Mientras tanto: cabecera a 30°, salino hipertónico o manitol como puente, normocapnia.",
   "Los corticoides están contraindicados en el TCE; no se opera sin saber dónde está la lesión."],
  ATLS + "; " + BTF + ".",
  d=dict(rotulo="¿Qué sigue tras estabilizar?", tag="ESTE CASO",
         pregunta="TEC grave con pupila dilatada: ¿ya están aseguradas la vía aérea y la PA?",
         ramas=[("No", "Primero ABC", ["Intubar, oxigenar, PAS ≥ 100-110.", "No llevar a TC a un paciente inestable."]),
                ("Sí: vía aérea asegurada", "TC de cráneo urgente",
                 ["Ubica el hematoma (epidural, subdural, contusión).", "Neurocirugía según el resultado."])],
         ilu=lambda s, x, y: I.tc_craneo(s, x, y, "epidural", lado="izq"), IW=280, IH=260,
         ilu_pie="Hematoma epidural izquierdo (esquema de TC; el lado izquierdo del paciente queda a la derecha de la imagen): lente blanca que desvía la línea media.",
         luego_titulo="Puente mientras llega la cirugía",
         luego=[("Cabecera a 30°", ["Mejora el retorno venoso."], True),
                ("Salino hipertónico o manitol", ["Bajan la presión intracraneal."], False),
                ("No dar corticoides", ["Aumentan la mortalidad en el TCE."], False)]),
  tabla=("Opciones de la pregunta", [("Dexametasona y observar", False), ("Pasar a UCI", False), ("TC urgente y decidir cirugía", True),
                                     ("Hipertónico y craniectomía a ciegas", False)],
         [("Problema", ["Contraindicada", "Retrasa el diagnóstico", "Ninguno", "Sin saber dónde está la lesión"])]))


# NRL-068 · Infarto occipitotemporal izquierdo · ANATOMÍA
def _occ(s, x, y):
    I.tc_craneo(s, x, y, "normal")
    I.g(s, x, y, I.P("M168 188 C190 200 214 196 226 176 L238 200 C220 232 180 238 156 226 Z", "#374151", "none", 0)
        + I.num(196, 214, 1) + I.num(232, 166, 2) + I.num(224, 110, 3) + I.num(150, 128, 4)
        + I.t(200, 252, "lado izquierdo del paciente →", "#94a3b8", 9.5, halo=False))


S("anatomia", "NRL-068", "fibrilacion-auricular-hemianopsia-derecha-prosopagnosia-infarto-occipitotemporal",
  "Hemianopsia homónima derecha con prosopagnosia por embolia: infarto cortical occipitotemporal",
  "Enfermedad cerebrovascular · localización", EN,
  ("Territorio de la arteria cerebral posterior", ["Corteza occipital: campo visual del lado opuesto.",
                                                   "Región occipitotemporal (giro fusiforme): reconocer caras."]),
  ("Varón de 55 años con FA no anticoagulada", ["Hace 10 h, de forma súbita, no ve su lado derecho.",
                                                "Hemianopsia homónima derecha, desorientación en ese hemicampo y no reconoce caras; sin déficit motor ni sensitivo."]),
  ["Hemianopsia homónima derecha = corteza occipital izquierda.",
   "Prosopagnosia = corteza occipitotemporal (fusiforme): el territorio es cortical occipitotemporal.",
   "Sin déficit motor ni sensitivo: no es tálamo profundo ni parietal extenso."],
  "AHA/ASA, ictus isquémico (2019); " + HARRISON + ".",
  d=dict(rotulo="Qué zona explica cada síntoma", tag="ESTE CASO",
         ilu_titulo="TC del caso (esquema)",
         ilu=_occ,
         ilu_pie="Zona oscura: infarto occipitotemporal izquierdo (en la TC el lado izquierdo del paciente queda a la derecha).",
         ans=2,
         puntos=[("Corteza occipital", ["Hemianopsia homónima del lado opuesto."]),
                 ("Región occipitotemporal (fusiforme)", ["Hemianopsia + no reconoce caras: este caso."]),
                 ("Corteza parietal posterior", ["Negligencia o apraxia; aquí no."]),
                 ("Tálamo profundo", ["Déficit sensitivo; aquí no."])]),
  tabla=("Opciones de la pregunta", [("Parietal posterior", False), ("Parietal", False), ("Talámico y occipital profundo", False),
                                     ("Cortical occipitotemporal", True)],
         [("¿Explica todo?", ["No", "No", "No: habría déficit sensitivo", "Sí"])]))


# NRL-069 · Neurocisticercosis: TC · ÁRBOL CON IMAGEN (foto real)
def _ncc(s, x, y):
    _img_draw(s, x, y, P("ncc_tc.jpg", 248, 275, [("flecha", 0.33, 0.29, 0.05, 0.08, "calcificaciones")],
                         credito="TC: I. L. Segamwenge · Commons · CC BY 4.0"))


S("arbol_imagen", "NRL-069", "agricultor-sierra-primera-convulsion-cerdo-neurocisticercosis-tc-cerebral",
  "Primera convulsión en un agricultor de zona endémica de cisticercosis: TC cerebral",
  "Epilepsia · primera crisis en zona endémica", EN,
  ("Neurocisticercosis", ["Quistes de Taenia solium en el cerebro: la causa más común de epilepsia adquirida en zonas endémicas.",
                          "Ante una primera crisis, primero se mira el cerebro."]),
  ("Varón de 38 años, sierra central", ["Primera crisis tónico-clónica; cefalea de meses; cría cerdos.",
                                        "Estable, afebril, sin rigidez de nuca ni déficit."]),
  ["Primera crisis sin fiebre ni meningismo: TC cerebral sin contraste (quistes y calcificaciones).",
   "Luego RM y serología (EITB) para clasificar; albendazol y corticoide según el tipo y número de quistes.",
   "No se da antiparasitario a ciegas; la punción lumbar no es el primer paso."],
  "IDSA/ASTMH, neurocisticercosis (2017); " + MINSA + ".",
  d=dict(rotulo="¿Qué estudio primero?", tag="ESTE CASO",
         pregunta="Primera convulsión en adulto: ¿hay fiebre o rigidez de nuca?",
         ramas=[("Sí", "Descartar infección del SNC", ["TC y luego punción lumbar.", "Antibiótico empírico si es meningitis."]),
                ("No: afebril, sin déficit", "TC cerebral sin contraste",
                 ["Busca quistes y calcificaciones.", "Después: RM, serología y tratamiento."])],
         ilu=_ncc, IW=248, IH=293,
         ilu_pie="TC real: múltiples calcificaciones puntiformes (quistes muertos) en ambos hemisferios.",
         luego_titulo="Qué sigue",
         luego=[("Antiepiléptico", ["Si se confirma la causa de la crisis."], True),
                ("Albendazol + corticoide", ["Solo en quistes viables, tras clasificar."], False),
                ("No primero", ["Punción lumbar ni tratamiento a ciegas."], False)]),
  tabla=("Opciones de la pregunta", [("TC cerebral sin contraste", True), ("Punción lumbar", False), ("Albendazol y corticoide", False),
                                     ("Serología", False)],
         [("Problema", ["Ninguno", "No es el primer paso", "A ciegas", "No muestra la lesión"])]))

# NRL-070 · Ausencias típicas · MATRIZ + franja
S("matriz", "NRL-070", "nina-7-anos-desconexiones-breves-hiperventilacion-ausencias-etosuximida",
  "Ausencias típicas en una niña: etosuximida como primera elección",
  "Epilepsia infantil · crisis de ausencia", EN,
  ("Epilepsia de ausencia infantil", ["Desconexiones de segundos, muchas veces al día, sin caída; se provocan con hiperventilación.",
                                      "EEG: punta-onda generalizada a 3 Hz."]),
  ("Niña de 7 años", ["Episodios de desconexión de < 10 s varias veces al día, sin pérdida del tono.",
                      "Se reproducen al hiperventilar."]),
  ["Ausencias típicas puras: etosuximida (mejor tolerada y tan eficaz como el valproato).",
   "Valproato si además hay crisis tónico-clónicas; lamotrigina es otra opción.",
   "Carbamazepina y fenitoína empeoran las ausencias."],
  "ILAE; Glauser et al., NEJM (2010); " + NELSON + ".",
  d=dict(rotulo="Tipo de crisis y fármaco", eje_x="Fármaco", eje_y="Crisis", caso=(0, 0),
         cols=["Etosuximida", "Valproato", "Carbamazepina o fenitoína"],
         rows=["Ausencias típicas puras", "Ausencias + tónico-clónicas", "Crisis focales", "Mioclónica juvenil"],
         cells=[[("Elección", ["Este caso"]), ("Alternativa", ["Más efectos adversos"]), ("Evitar", ["Empeoran las ausencias"])],
                [("No cubre", ["Las tónico-clónicas"]), ("Elección", ["Cubre ambas"]), ("Evitar", ["Empeoran las ausencias"])],
                [("No sirve", ["Solo ausencias"]), ("Opción", ["Amplio espectro"]), ("Útiles", ["Para crisis focales"])],
                [("No basta", ["No cubre mioclonías"]), ("Elección", ["En varones"]), ("Evitar", ["Empeoran mioclonías"])]]),
  banda=B("EEG durante la crisis (esquema)", D(lambda s, x, y: I.eeg_3hz(s, x, y, W=620), 620, 110),
          ["Punta-onda generalizada a 3 por segundo.", "Dura lo mismo que la desconexión.", "La hiperventilación la provoca."], ans=0),
  tabla=("Opciones de la pregunta", [("Valproato", False), ("Etosuximida", True), ("Fenitoína", False), ("Carbamazepina", False)],
         [("Comentario", ["Alternativa", "Elección en ausencias puras", "Empeora las ausencias", "Empeora las ausencias"])]))

# TRA-054 · Tendón flexor profundo: referir · RED + franja
S("red", "TRA-054", "corte-palmar-indice-flexor-profundo-limpiar-derivar-cirugia-mano",
  "Corte palmar con lesión del flexor profundo en el primer nivel: limpiar, cubrir y derivar",
  "Mano · lesiones tendinosas", ET,
  ("Lesión del tendón flexor profundo", ["Si no dobla la falange distal, el flexor profundo está cortado.",
                                         "La reparación requiere cirujano de mano, técnica especial y anestesia."]),
  ("Varón de 30 años, centro de salud", ["Corte con cuchillo en la palma, dedo índice, hace 1 hora.",
                                         "Herida limpia de bordes netos; no flexiona la falange distal."]),
  ["En el primer nivel: lavar, cubrir con apósito estéril, férula en posición funcional y derivar.",
   "La reparación ideal es en los primeros días, en un hospital con cirugía de mano.",
   "No abrir la vaina ni intentar reparar el tendón; solo suturar la piel retrasa el tratamiento."],
  "ASSH; " + ATLS + ".",
  d=dict(rotulo="Dónde está el paciente y a dónde va", caso="I-3", destino="II-2", flecha="Referencia", tag="ESTE CASO",
         claves=[("Limpiar, cubrir y derivar", ["Con férula en posición funcional."], True),
                 ("Reparación del tendón", ["Cirujano de mano, en pocos días."], False),
                 ("No hacer", ["Abrir la vaina, reparar en el primer nivel o solo suturar la piel."], False)]),
  banda=B("Dedo índice (esquema)", D(lambda s, x, y: I.dedo_flexor(s, x, y, sc=0.95), 345, 162),
          ["El flexor profundo llega a la falange distal.", "Cortado: la punta del dedo no se dobla.", "El flexor superficial aún dobla la falange media."], ans=1),
  tabla=("Opciones de la pregunta", [("Limpiar y derivar", True), ("Abrir la vaina y férula", False), ("Suturar piel y antibiótico", False),
                                     ("Reparar el tendón", False)],
         [("Problema", ["Ninguno", "No corresponde al primer nivel", "Deja el tendón sin reparar", "Requiere especialista"])]))

# TRA-055 · AR: inestabilidad atlantoaxial · ÁRBOL + franja
S("arbol", "TRA-055", "artritis-reumatoide-dolor-cervical-parestesias-flexion-rx-dinamica-c1-c2",
  "Artritis reumatoide con dolor cervical y parestesias al flexionar: Rx dinámica en flexión y extensión",
  "Columna · inestabilidad atlantoaxial", ET,
  ("Subluxación atlantoaxial en la AR", ["La sinovitis erosiona el ligamento transverso y la odontoides.",
                                         "El atlas se desliza en flexión y puede comprimir la médula."]),
  ("Varón de 55 años con AR erosiva de 12 años", ["6 meses de dolor y rigidez cervical; parestesias en manos al flexionar el cuello.",
                                                  "Sin déficit; reflejos algo vivos en las cuatro extremidades."]),
  ["AR de larga data + síntomas cervicales: Rx dinámica en flexión y extensión (intervalo atlas-odontoides > 3 mm).",
   "Si hay inestabilidad o mielopatía: RM y evaluación quirúrgica.",
   "Cuidado al intubar: evitar la hiperextensión del cuello."],
  "ACR; " + HARRISON + ".",
  arbol=Q("¿AR de larga data con dolor cervical o síntomas al flexionar?", [
      L("No", "Control habitual", ["Examen neurológico en cada visita"]),
      Q("¿Déficit neurológico franco?", [
          L("Sí", "RM cervical urgente", ["Y cirujano de columna"]),
          L("No: solo parestesias", "RX DINÁMICA FLEXIÓN-EXTENSIÓN", ["Mide el espacio atlas-odontoides", "> 3 mm: inestable → RM"], path=True)],
        edge="Sí", path=True)], path=True),
  banda=B("C1-C2 de perfil (esquema)", D(lambda s, x, y: I.atlas_axis(s, x, y, sc=0.95), 345, 192),
          ["En extensión el atlas está en su sitio.", "En flexión se desliza hacia adelante.", "El espacio que crece comprime la médula."], ans=1),
  tabla=("Opciones de la pregunta", [("Rx lumbar", False), ("TC sacroilíacas", False), ("RM dorsal", False), ("Rx cervical dinámica", True)],
         [("Problema", ["Otra región", "Otra enfermedad", "Otra región", "Ninguno"])]))

# TRA-056 · Displasia de cadera: reducción abierta · CRONOLOGÍA
S("cronologia", "TRA-056", "nina-13-meses-luxacion-cadera-tonnis-iii-reduccion-abierta",
  "Niña de 13 meses con cadera luxada alta (Tönnis III) sin reducir: reducción abierta",
  "Ortopedia infantil · displasia del desarrollo de la cadera", ET,
  ("Displasia del desarrollo de la cadera", ["El tratamiento depende de la edad y del grado de luxación.",
                                             "Cuanto más tarde y más alta la luxación, más invasivo el tratamiento."]),
  ("Niña de 13 meses", ["Asimetría de pliegues tratada con «doble pañal»; ahora cojea.",
                        "Abducción limitada de la cadera derecha; Rx: luxación alta (Tönnis III), sin reducción."]),
  ["Luxación alta en una niña que ya camina: reducción abierta (a veces con osteotomía).",
   "El arnés de Pavlik sirve hasta los 6 meses; el «doble pañal» no trata una luxación.",
   "Lo ideal es detectarla al nacer con Ortolani/Barlow y ecografía."],
  "AAOS, displasia de cadera (2022); " + NELSON + ".",
  d=dict(rotulo="La cadera y la edad del tratamiento", tag="ESTE CASO",
         ilu_titulo="Rx de pelvis (esquema)",
         ilu=ILU(D(lambda s, x, y: I.pelvis_ddh(s, x + 5, y + 10, "der", sc=1.0), 330, 280)),
         ilu_pie="Cabeza femoral derecha fuera del acetábulo, arriba y afuera.",
         claves=[("Reducción abierta", ["Luxación alta que no reduce, en niña que camina."], True),
                 ("Arnés de Pavlik o Frejka", ["Solo en los primeros meses."], False),
                 ("Yeso corto", ["No reduce la cadera."], False)],
         eje_titulo="Edad (meses)", eje=(0, 24), paso=4, marca=13, unidad="m",
         eje_nombre="meses de vida",
         hitos=[(0, 6, "Arnés de Pavlik", "hasta los 6 meses", False),
                (6, 18, "Reducción cerrada + yeso", "si la cadera reduce", False),
                (12, 24, "Reducción abierta", "luxación alta o falla la cerrada", True),
                (12, 18, "«Doble pañal»", "no trata la luxación", False)]),
  tabla=("Opciones de la pregunta", [("Bota de yeso corta", False), ("Arnés de Pavlik", False), ("Cojín de Frejka", False), ("Reducción abierta", True)],
         [("Problema", ["No actúa en la cadera", "Solo < 6 meses", "Solo en lactantes pequeños", "Ninguno"])]))

# PSI-043 · Trastorno de conversión · EMBUDO + franja
S("embudo", "PSI-043", "perdida-gestacional-debilidad-disfagia-examenes-normales-trastorno-conversion",
  "Síntomas neurológicos sin causa orgánica tras un duelo: trastorno de conversión",
  "Trastornos de síntomas somáticos · conversión", EP,
  ("Trastorno de conversión (síntomas neurológicos funcionales)", ["Síntomas motores o sensitivos reales que no se explican por enfermedad neurológica.",
                                                                   "Suelen aparecer tras un estrés; el paciente no los finge."]),
  ("Mujer de 35 años", ["2 semanas tras perder una gestación por FIV muy deseada: debilidad de piernas, disfagia, temblor, visión borrosa.",
                        "Examen, neuroimágenes y EMG normales; sin infecciones ni autoinmunidad."]),
  ["Síntomas neurológicos con estudios normales + estresor reciente = trastorno de conversión.",
   "No se finge (eso es facticio) ni busca un beneficio externo (eso es simulación).",
   "Manejo: explicar el diagnóstico sin culpar, psicoterapia y rehabilitación física."],
  "DSM-5-TR; " + HARRISON + ".",
  d=dict(rotulo="De los síntomas a la causa", inicio="Síntomas neurológicos con exámenes normales tras un duelo",
         candidatos=["Pródromos de esquizofrenia", "Trastorno facticio", "Sustancias hormonales", "Conversión"],
         pasos=[("¿Alucinaciones, aislamiento o pensamiento desorganizado?", ["Pródromos de esquizofrenia"]),
                ("¿Produce los síntomas a propósito para ser paciente?", ["Trastorno facticio"]),
                ("¿Toma hormonas que los expliquen?", ["Sustancias hormonales"])],
         final=("Trastorno de conversión", ["Síntomas reales, no intencionales, tras un estrés"]),
         nota="Todos los estudios son normales y hay un estresor claro."),
  banda=B("Síntomas de la paciente", D(lambda s, x, y: I.cuerpo(s, x + 40, y, {"muslo_d": "#dbeafe", "muslo_i": "#dbeafe", "pierna_d": "#dbeafe", "pierna_i": "#dbeafe"},
                                                                 marcas=[(1, 120, 74), (2, 134, 34), (3, 37, 250), (4, 98, 340)], sc=0.7), 250, 312),
          ["Disfagia (1) y visión borrosa (2).", "Temblor del brazo derecho (3) y debilidad de piernas (4).", "Ningún examen encuentra una causa."]),
  tabla=("Opciones de la pregunta", [("Sustancias hormonales", False), ("Pródromos de esquizofrenia", False), ("Trastorno de conversión", True),
                                     ("Trastorno facticio", False)],
         [("¿Encaja?", ["No se menciona", "Sin síntomas psicóticos", "Sí", "No los provoca a propósito"])]))

# PSI-044 · Metadona · BALANZA + franja
S("balanza", "PSI-044", "heroina-endovenosa-recaidas-abstinencia-mantenimiento-metadona",
  "Dependencia de heroína con recaídas: mantenimiento con metadona",
  "Trastornos por uso de sustancias · opioides", EP,
  ("Trastorno por uso de opioides", ["Los agonistas de larga duración (metadona, buprenorfina) son el tratamiento de base.",
                                     "Quitan la abstinencia y el deseo y reducen la mortalidad."]),
  ("Varón de 32 años", ["4 años de heroína EV diaria; recae tras cada suspensión brusca.",
                        "Busca un programa ambulatorio de mantenimiento a largo plazo."]),
  ["Mantenimiento con metadona (o buprenorfina): nivel estable sin picos ni abstinencia.",
   "Reduce sobredosis, infecciones por inyección y delitos; se combina con apoyo psicosocial.",
   "Benzodiacepinas, haloperidol o valproato no tratan la dependencia de opioides."],
  "OMS, tratamiento de la dependencia de opioides; ASAM (2020).",
  d=dict(rotulo="¿Qué conviene?", gana="izq", tag="ESTE CASO",
         pregunta="Mantenimiento en dependencia de heroína",
         izq=dict(titulo="Metadona", peso="elige",
                  items=["Agonista de larga duración (24-36 h)", "Quita abstinencia y deseo", "Menos mortalidad y recaídas"]),
         der=dict(titulo="Sedantes o suspensión brusca", peso="no",
                  items=["No ocupan el receptor opioide", "Abstinencia intensa: recae", "Benzodiacepinas suman riesgo"]),
         veredicto=("Metadona en un programa de mantenimiento", ["Con dosis estable y apoyo psicosocial."])),
  banda=B("Nivel de opioide en la sangre", D(lambda s, x, y: I.opioide_niveles(s, x, y, sc=0.92), 350, 184),
          ["La heroína sube y baja: euforia y luego abstinencia.", "La metadona da un nivel estable.", "Sin picos ni caídas, el deseo baja."], ans=1),
  tabla=("Opciones de la pregunta", [("Metadona", True), ("Diazepam", False), ("Haloperidol", False), ("Ácido valproico", False)],
         [("¿Trata la dependencia?", ["Sí", "No", "No", "No"])]))

# PSI-045 · Distonía aguda · ÁRBOL + franja
S("arbol", "PSI-045", "haloperidol-tres-dias-torticolis-crisis-oculogira-distonia-aguda-biperideno",
  "Tortícolis, ojos hacia arriba y lengua afuera tras iniciar haloperidol: distonía aguda, biperideno",
  "Efectos adversos de antipsicóticos · extrapiramidales", EP,
  ("Distonía aguda", ["Contracción sostenida y dolorosa en los primeros días de un antipsicótico potente.",
                      "Falta dopamina y sobra acetilcolina en los ganglios basales."]),
  ("Varón de 40 años", ["Haloperidol hace 3 días; hoy tortícolis dolorosa, ojos hacia arriba, lengua protruida.",
                        "Afebril, consciente, vía aérea sin compromiso, muy ansioso."]),
  ["Distonía aguda: anticolinérgico (biperideno IM o EV); difenhidramina es alternativa.",
   "Mejora en minutos; seguir el anticolinérgico unos días o cambiar de antipsicótico.",
   "Si hubiera laringoespasmo: urgencia de vía aérea. La levodopa no se usa."],
  "Maudsley Prescribing Guidelines (2021); " + HARRISON + ".",
  arbol=Q("¿Hay compromiso de la vía aérea (laringoespasmo)?", [
      L("Sí", "Urgencia de vía aérea", ["Biperideno EV y soporte"]),
      L("No", "BIPERIDENO IM O EV", ["Anticolinérgico: alivia en minutos", "Revisar el antipsicótico"], path=True)], path=True),
  banda=B("El paciente (esquema)", D(lambda s, x, y: I.cabeza_distonia(s, x + 10, y), 260, 232),
          ["Tortícolis dolorosa.", "Crisis oculógira: ojos hacia arriba.", "Lengua que protruye: le cuesta hablar."], ans=0),
  tabla=("Opciones de la pregunta", [("Clonazepam", False), ("Levodopa", False), ("Orfenadrina", False), ("Biperideno", True)],
         [("Comentario", ["Coadyuvante", "No se usa", "Menos usado", "Elección"])]))

# OFT-056 · OMA: abombamiento · COMPARADOR (dibujos)
S("comparador", "OFT-056", "nino-2-anos-otitis-media-aguda-timpano-abombado-antibiotico",
  "Otitis media aguda en un niño de 2 años: el abombamiento del tímpano justifica el antibiótico",
  "Otorrinolaringología · otitis media aguda", EO,
  ("Diagnóstico estricto de otitis media aguda", ["Hace falta líquido en el oído medio + inflamación aguda.",
                                                  "El abombamiento moderado o intenso del tímpano es el signo más específico."]),
  ("Niño de 2 años en un centro de salud", ["24 h de fiebre y llanto irritativo.", "Otoscopía: presión purulenta en el oído medio."]),
  ["Abombamiento intenso + fiebre en < 2 años = OMA: amoxicilina 80-90 mg/kg/día.",
   "Tímpano ámbar con burbujas: otitis media con efusión (no necesita antibiótico).",
   "Eritema leve con movilidad normal o tímpano retraído no bastan para diagnosticar OMA."],
  "AAP, otitis media aguda (2013); " + NELSON + ".",
  d=dict(rotulo="Tímpano con pus frente a efusión", IH=212, tag="ESTE CASO",
         imgs=[dict(titulo="OMA: abombado", on=True, ilu=lambda s, x, y: I.timpano(s, x + 97, y, "abombado"),
                    pie="Abombado, rojo y opaco: pus a presión."),
               dict(titulo="Otitis con efusión", ilu=lambda s, x, y: I.timpano(s, x + 97, y, "derrame"),
                    pie="Ámbar con burbujas: líquido sin infección aguda.")],
         lectura_titulo="Otros hallazgos",
         lectura=[("Abombamiento intenso", ["Justifica el antibiótico."], True),
                  ("Eritema leve con movilidad", ["Puede ser por llanto o fiebre."], False),
                  ("Retraído, martillo marcado", ["Disfunción de la trompa."], False)]),
  tabla=("Opciones de la pregunta", [("Eritema leve con movilidad", False), ("Abombamiento intenso", True), ("Retraído", False),
                                     ("Ámbar con burbujas", False)],
         [("¿Justifica antibiótico?", ["No", "Sí", "No", "No: es efusión"])]))

# OFT-057 · Quemadura química ocular · SEMÁFORO
S("semaforo", "OFT-057", "urgencias-oftalmologicas-quemadura-quimica-lavado-inmediato",
  "La quemadura química del ojo es una urgencia verdadera: lavar en minutos",
  "Oftalmología · urgencias", EO,
  ("Urgencias oculares", ["Algunas se tratan en minutos (química, oclusión arterial); otras en horas o días.",
                          "Los álcalis (lejía, amoníaco) penetran más que los ácidos."]),
  ("Pregunta de concepto", ["¿Cuál de estas situaciones es una urgencia ocular verdadera?"]),
  ["Quemadura química: lavar de inmediato con suero o agua 15-30 min, hasta pH 7,0-7,4, antes de examinar.",
   "Luego evaluar córnea y limbo y referir a oftalmología.",
   "Pterigion y orzuelo no son urgentes; el trauma contuso sin baja de visión se evalúa sin prisa extrema."],
  "AAO; " + HARRISON + ".",
  d=dict(rotulo="Imagen y semáforo de urgencia",
         ilu_titulo="Lavado ocular",
         ilu=ILU(D(lambda s, x, y: I.ojo_lavado(s, x - 10, y + 40, sc=0.95), 270, 260)),
         ilu_pie="Lavar primero, examinar después.",
         check_titulo="Las opciones",
         check=[("Quemadura química por limpiador", False), ("Golpe contuso con visión normal", True),
                ("Orzuelo de 24 horas", True), ("Pterigion que invade la córnea", True)],
         ans=2, tag="ESTE CASO",
         luces=[("Días o semanas", "Programado", ["Orzuelo, pterigion, golpe sin lesión."]),
                ("Horas", "Urgente", ["Trauma con baja de visión, glaucoma agudo, úlcera corneal."]),
                ("Minutos", "Urgencia verdadera", ["Quemadura química, oclusión de la arteria central."])]),
  tabla=("Opciones de la pregunta", [("Pterigion", False), ("Golpe sin baja de visión", False), ("Orzuelo", False), ("Quemadura química", True)],
         [("¿Urgencia verdadera?", ["No", "No", "No", "Sí"])]))


# REU-069 · Vitíligo · MAPA DE SIGNOS (foto real + dibujo)
def _vit(s, x, y):
    _img_draw(s, x + 2, y, P("vitiligo.jpg", 290, 206, [("flecha", 0.62, 0.42, 0.40, 0.06, "máculas acrómicas")],
                             credito="J. Heilman · Wikimedia Commons · CC BY-SA 3.0"))
    I.cuerpo(s, x + 88, y + 236, {"cara": "#ffffff", "mano_d": "#ffffff", "mano_i": "#ffffff", "pelvis": "#ffffff"},
             marcas=[(1, 120, 40), (2, 37, 250), (3, 120, 254)], sc=0.5)


S("mapa_signos", "REU-069", "maculas-acromicas-blanco-tiza-cara-manos-hipotiroidismo-autoinmune-vitiligo",
  "Máculas blanco tiza en cara, manos y genitales con hipotiroidismo autoinmune: vitíligo",
  "Dermatología · trastornos de la pigmentación", ER,
  ("Vitíligo", ["Destrucción autoinmune de los melanocitos: máculas acrómicas (sin pigmento), bien delimitadas.",
                "Se asocia a tiroiditis autoinmune y otras enfermedades autoinmunes."]),
  ("Mujer de 46 años con hipotiroidismo autoinmune", ["Meses de máculas acrómicas en cara, dorso de manos y genitales.",
                                                      "Blanco tiza, sin prurito ni descamación."]),
  ["Máculas blanco tiza, bien delimitadas, sin descamación, en zonas típicas + autoinmunidad = vitíligo.",
   "La luz de Wood las resalta (blanco brillante).",
   "Pitiriasis versicolor descama; la hipopigmentación postinflamatoria es menos blanca y sigue a una lesión previa."],
  "Consenso internacional de vitíligo (2023); " + HARRISON + ".",
  d=dict(rotulo="Los signos de la paciente", PH=520, tag="ESTE CASO",
         ilu_titulo="Vitíligo (foto real) y dónde aparece",
         ilu=_vit,
         ilu_pie="Arriba: vitíligo en manos (foto real). Abajo: 1 cara, 2 manos, 3 genitales.",
         signos=[dict(tit="Máculas acrómicas blanco tiza", lines=["Sin pigmento, no solo más claras."]),
                 dict(tit="Bordes bien definidos", lines=["Sin descamación al rascar."]),
                 dict(tit="Cara, manos y genitales", lines=["Zonas típicas del vitíligo."]),
                 dict(tit="Hipotiroidismo autoinmune", lines=["Comparte el origen autoinmune."]),
                 dict(tit="Causa: vitíligo", on=True, lines=["Pérdida autoinmune de melanocitos."])]),
  tabla=("Opciones de la pregunta", [("Pitiriasis versicolor", False), ("Hipopigmentación postinflamatoria", False),
                                     ("Hipomelanosis macular progresiva", False), ("Vitíligo", True)],
         [("Clave", ["Descama", "Tras una lesión previa", "Tronco, hipocrómica", "Acrómica + autoinmunidad"])]))

# REU-070 · Esclerodermia: esófago · ANATOMÍA
_eso = (I.P("M116 76 L116 150 C110 164 112 176 124 180 C136 176 132 160 126 150 L126 76 Z", "#fde68a", "#b45309", 2)
        + I.E(146, 192, 26, 16, "#fecaca", "#b91c1c", 1.5))
S("anatomia", "REU-070", "piel-dura-manos-cara-disfagia-esofago-sin-peristalsis-esclerodermia",
  "Piel endurecida en manos y cara con esófago distal dilatado y sin peristalsis: esclerodermia",
  "Enfermedades del tejido conectivo · esclerosis sistémica", ER,
  ("Esclerosis sistémica (esclerodermia)", ["Fibrosis de la piel y de los órganos internos.",
                                            "El esófago es el órgano interno más afectado: pierde la peristalsis y refluye."]),
  ("Mujer de 40 años", ["3 años de disfagia a sólidos y piel tirante y dura en manos y cara.",
                        "6 meses de pirosis, regurgitación y baja de 10 kg; bario: esófago distal dilatado sin peristalsis."]),
  ["Esclerodactilia + esófago distal sin peristalsis + reflujo grave = esclerodermia.",
   "El esfínter esofágico inferior pierde tono: reflujo, esofagitis, estenosis y Barrett.",
   "Dermatomiositis: debilidad proximal y lesiones de piel distintas; LES: sin endurecimiento de la piel."],
  "ACR/EULAR, esclerosis sistémica (2013); " + HARRISON + ".",
  d=dict(rotulo="Dónde ataca la esclerodermia", tag="ESTE CASO",
         ilu_titulo="La paciente (esquema)",
         ilu=lambda s, x, y: I.cuerpo(s, x + 116, y, {"mano_d": "#fde2e2", "mano_i": "#fde2e2", "cara": "#fde2e2"}, extra=_eso,
                                      marcas=[(1, 37, 250), (2, 140, 40), (3, 104, 160), (4, 170, 196)], sc=0.76),
         ilu_pie="1 manos, 2 cara, 3 esófago distal, 4 estómago (reflujo).",
         ans=3,
         puntos=[("Manos: esclerodactilia", ["Piel dura y brillante; a veces Raynaud."]),
                 ("Cara: piel tirante", ["Boca pequeña (microstomía)."]),
                 ("Esófago distal sin peristalsis", ["Dilatado; el contraste se vacía lento: este caso."]),
                 ("Reflujo grave", ["El esfínter inferior pierde tono."])]),
  tabla=("Opciones de la pregunta", [("Dermatomiositis", False), ("Diabetes mellitus", False), ("Esclerodermia", True), ("LES", False)],
         [("Clave", ["Debilidad proximal", "Gastroparesia, no piel dura", "Piel dura + esófago", "Sin piel dura"])]))

# REU-071 · Stevens-Johnson · TERMÓMETRO + franja (foto real)
S("termometro", "REU-071", "carbamazepina-ampollas-nikolsky-mucosas-menos-10-stevens-johnson",
  "Ampollas con Nikolsky positivo y mucosas erosionadas en < 10 % de la superficie tras carbamazepina: Stevens-Johnson",
  "Dermatología · reacciones graves a fármacos", ER,
  ("Stevens-Johnson y necrólisis epidérmica tóxica", ["Reacción grave a fármacos con necrosis de la epidermis y mucosas.",
                                                      "Se clasifican por el % de superficie despegada."]),
  ("Varón de 30 años, carbamazepina hace 10 días", ["Fiebre, malestar, máculas purpúricas que forman ampollas flácidas.",
                                                    "Nikolsky (+), < 10 % de superficie, erosiones orales y conjuntivales."]),
  ["Fármaco de riesgo + ampollas + mucosas + < 10 % = Stevens-Johnson.",
   "Suspender el fármaco de inmediato; manejo como gran quemado (unidad de quemados o UCI).",
   "Cuidado de ojos (secuelas) y mucosas; el pénfigo no tiene relación con fármacos ni fiebre así."],
  "Guías británicas de SJS/NET (BAD, 2016); " + HARRISON + ".",
  d=dict(rotulo="Superficie despegada y gravedad",
         niveles=[("SJS", "< 10 %", ["Stevens-Johnson: ampollas + mucosas"]),
                  ("SJS/NET", "10-30 %", ["Superposición"]),
                  ("NET", "> 30 %", ["Necrólisis epidérmica tóxica"])],
         caso_nivel=0, ruta_titulo="Qué se hace", paso_label="ESTE CASO",
         pasos=[(1, "Suspender la carbamazepina", ["De inmediato"], True),
                (2, "Unidad de quemados o UCI", ["Líquidos, curaciones, dolor"], False),
                (3, "Ojos y mucosas", ["Oftalmología temprana"], False)]),
  banda=B("Mucosa oral (foto real)", P("sjs.jpg", 300, 255, [("flecha", 0.45, 0.42, 0.05, 0.08, "erosiones")],
                                       credito="J. Heilman · Wikimedia Commons · CC BY-SA 3.0"),
          ["Erosiones y costras en lengua y labios.", "El compromiso de mucosas lo distingue de otras ampollas.", "Duele: comer y beber cuesta."], ans=0),
  tabla=("Opciones de la pregunta", [("Stevens-Johnson", True), ("Pénfigo vulgar", False), ("Penfigoide ampolloso", False), ("POEMS", False)],
         [("Clave", ["Fármaco + mucosas + < 10 %", "Autoinmune, sin fármaco", "Ampollas tensas, ancianos", "Neuropatía y paraproteína"])]))

# REU-072 · Osteoartritis de manos · TARJETAS + franja (foto real)
S("tarjetas", "REU-072", "dolor-mecanico-manos-nodulos-interfalangicos-osteofitos-vsg-normal-osteoartritis",
  "Dolor mecánico en manos con nódulos interfalángicos, osteofitos y VSG normal: osteoartritis",
  "Reumatología · artrosis", ER,
  ("Osteoartritis (artrosis) de manos", ["Desgaste del cartílago: dolor que empeora con el uso y mejora con el reposo.",
                                         "Nódulos de Heberden (distales) y Bouchard (proximales); VSG normal."]),
  ("Mujer de 55 años", ["Dolor en manos y rodillas que empeora con la actividad.",
                        "Nódulos interfalángicos; Rx: pinzamiento, esclerosis subcondral, osteofitos; VSG normal."]),
  ["Dolor mecánico + nódulos de Heberden/Bouchard + osteofitos + VSG normal = osteoartritis.",
   "La artritis reumatoide afecta metacarpofalángicas e interfalángicas proximales, con rigidez larga y VSG alta.",
   "Tratamiento: ejercicio, peso, AINE tópico; paracetamol según el caso."],
  "ACR, osteoartritis (2019); EULAR (2018).",
  d=dict(rotulo="Cuatro artritis posibles", ans=0,
         cards=[dict(titulo="Osteoartritis", datos=[("Dolor", "Mecánico", True), ("Articulaciones", "Interfalángicas distales", True),
                                                    ("VSG", "Normal", True)], pie="Este caso."),
                dict(titulo="Artritis reumatoide", datos=[("Dolor", "Inflamatorio, rigidez > 1 h", False), ("Articulaciones", "MCF e IFP", False),
                                                          ("VSG", "Alta", False)], pie="Erosiones, no osteofitos."),
                dict(titulo="Artritis psoriásica", datos=[("Piel", "Psoriasis, uñas", False), ("Dedos", "En salchicha", False),
                                                          ("Rx", "Lápiz en copa", False)], pie="Sin psoriasis aquí."),
                dict(titulo="Artritis reactiva", datos=[("Antes", "Infección intestinal o genital", False), ("Patrón", "Oligoartritis de piernas", False),
                                                        ("Otros", "Uretritis, conjuntivitis", False)], pie="Aguda, en jóvenes.")]),
  banda=B("Nódulos de Heberden (foto real)", P("heberden.jpg", 320, 240, [("flecha", 0.47, 0.32, 0.03, 0.06, "nódulo de Heberden")],
                                                credito="Drahreg01 · Wikimedia Commons · CC BY-SA 3.0"),
          ["Engrosamientos duros en las articulaciones de la punta de los dedos.", "Son osteofitos: hueso que crece en el borde.", "Típicos de la osteoartritis."], ans=0),
  tabla=("Opciones de la pregunta", [("Artritis reactiva", False), ("Osteoartritis", True), ("Artritis psoriásica", False), ("Artritis reumatoide", False)],
         [("¿Encaja?", ["No: sin infección previa", "Sí", "No: sin psoriasis", "No: VSG normal, dolor mecánico"])]))

# REU-073 · Fibromialgia: amitriptilina · ESCALERA
_tp = "".join(I.C(cx, cy, 5, I.ORANGE, "#7c2d12", 1) for cx, cy in [(96, 84), (144, 84), (84, 104), (156, 104), (104, 128), (136, 128),
                                                                    (60, 160), (180, 160), (90, 262), (150, 262), (98, 330), (142, 330)])
S("escalera", "REU-073", "dolor-generalizado-fatiga-sueno-no-reparador-alodinia-fibromialgia-amitriptilina",
  "Dolor generalizado con fatiga, sueño no reparador y alodinia: fibromialgia, amitriptilina nocturna",
  "Reumatología · dolor crónico", ER,
  ("Fibromialgia", ["Dolor crónico generalizado por alteración del procesamiento del dolor (sensibilización central).",
                    "Fatiga, sueño no reparador, problemas de concentración; exámenes normales."]),
  ("Mujer de 35 años", ["18 meses de dolor generalizado, fatiga y sueño no reparador; estrés por violencia conyugal.",
                        "AINE sin efecto; alodinia y dolor difuso, sin artritis; laboratorio normal."]),
  ["Base: educación, ejercicio aeróbico gradual y terapia cognitivo-conductual; atender la violencia.",
   "Fármaco de inicio: amitriptilina 10-25 mg en la noche (mejora el sueño y el dolor).",
   "AINE y opioides no sirven en la fibromialgia; duloxetina o pregabalina son alternativas."],
  "EULAR, fibromialgia (2016); ACR (2016).",
  d=dict(rotulo="Puntos dolorosos y escalera de tratamiento",
         img=dict(titulo="Puntos dolorosos (esquema)", IH=250,
                  ilu=lambda s, x, y: I.cuerpo(s, x + 372, y, extra=_tp, sc=0.56),
                  pie="Dolor difuso a la palpación en muchos puntos del cuerpo, sin articulaciones inflamadas."),
         check_titulo="¿Qué tiene?",
         check=[("Dolor generalizado > 3 meses", True), ("Fatiga y sueño no reparador", True), ("Exámenes normales; AINE sin efecto", True)],
         veredicto="FIBROMIALGIA: medidas base + fármaco",
         peldanos=[("Educación y ejercicio", ["Terapia cognitivo-conductual."]),
                   ("Amitriptilina nocturna", ["10-25 mg en la noche."]),
                   ("Duloxetina o pregabalina", ["Si no mejora."])],
         ans=1, tag="ESTE CASO", salto="Primer fármaco",
         leyenda_estable="Siempre se empieza por educación y ejercicio; el fármaco se suma.",
         leyenda_inestable="Este caso: AINE sin efecto → amitriptilina en dosis baja por la noche."),
  tabla=("Opciones de la pregunta", [("Etoricoxib", False), ("Morfina", False), ("Amitriptilina nocturna", True), ("Tramadol + paracetamol", False)],
         [("Comentario", ["Los AINE no sirven", "Opioides: no", "Elección", "Opioide: no de rutina"])]))

# REU-074 · Micosis fungoide · FASES + franja (foto real)
S("fases", "REU-074", "parches-placas-pruriginosas-anos-cd4-epidermotropismo-micosis-fungoide-linfoma",
  "Parches y placas pruriginosas de años con linfocitos T CD4 atípicos en la epidermis: micosis fungoide",
  "Dermatología · linfomas cutáneos", ER,
  ("Micosis fungoide", ["El linfoma cutáneo de células T más frecuente; no es un hongo.",
                        "Evoluciona en años: parche, placa, tumor; los linfocitos T CD4 invaden la epidermis."]),
  ("Varón de 60 años", ["Años de parches y placas eritematosas pruriginosas en tronco y extremidades.",
                        "Poca mejora con corticoide tópico; biopsia: linfocitos T CD4 atípicos en la epidermis."]),
  ["Parches y placas persistentes + linfocitos T CD4 epidermotropos = micosis fungoide (linfoma no Hodgkin T cutáneo).",
   "Fases tempranas: corticoide tópico potente, fototerapia; avanzadas: tratamientos sistémicos.",
   "Sospechar ante «eczema» o «psoriasis» que no responde: biopsiar."],
  "EORTC/ISCL, linfomas cutáneos (2018); OMS (2022).",
  d=dict(rotulo="Cómo avanza la micosis fungoide", ans=1,
         fases=[("Parche", "Años", "MANCHAS", ["Planas, finas, pruriginosas"]),
                ("Placa", "Años", "PLACAS", ["Elevadas, infiltradas"]),
                ("Tumor", "Tardía", "NÓDULOS", ["Pueden ulcerarse"]),
                ("Sézary", "Rara", "ERITRODERMIA", ["Células en sangre"])],
         curvas=[("Linfocitos T en la piel", "#7c3aed", [0.2, 0.3, 0.5, 0.65, 0.8, 0.9, 0.95]),
                 ("Mejora con corticoide tópico", "#0f766e", [0.8, 0.7, 0.5, 0.35, 0.2, 0.1, 0.05])]),
  banda=B("Micosis fungoide (foto real)", P("micosis.jpg", 330, 220, [("circulo", 0.66, 0.16, 0.08, "placa", 0.78, 0.05)],
                                           credito="Bobjgalindo · Wikimedia Commons · CC BY-SA 4.0"),
          ["Parches y placas rosadas en la pierna.", "Se confunden con eczema o psoriasis.", "La biopsia muestra los linfocitos T atípicos."], ans=0),
  tabla=("Opciones de la pregunta", [("Psoriasis eritrodérmica", False), ("Micosis profunda", False), ("Linfoma cutáneo T", True), ("LMC cutánea", False)],
         [("¿Es la naturaleza?", ["No", "No: el nombre engaña", "Sí", "No"])]))

# REU-075 · Ántrax (carbunco) · RADIAL + franja (foto real)
S("radial", "REU-075", "foliculitis-coalescentes-placa-indurada-varios-puntos-pus-antrax-estafilococico",
  "Varias foliculitis que se unen en una placa indurada con múltiples bocas de pus: ántrax",
  "Infecciones de la piel · estafilocócicas", ER,
  ("Ántrax (carbunco) estafilocócico", ["Varios forúnculos vecinos se unen en una placa inflamada que drena por varias bocas.",
                                       "Da fiebre y ganglios; es más profundo que un forúnculo."]),
  ("Niño de 15 meses", ["7 días: 3 pústulas foliculares en la rodilla que formaron una placa caliente, indurada y muy dolorosa.",
                        "Varios puntos de pus, fiebre 39 °C, adenopatía inguinal; sin mejora con amoxicilina-clavulánico."]),
  ["Forúnculos que confluyen con múltiples puntos de drenaje = ántrax (S. aureus).",
   "Drenaje quirúrgico + antibiótico antiestafilocócico (pensar en SARM si no mejora).",
   "Forúnculo: un solo folículo; impétigo: costras melicéricas; ectima: úlcera con costra."],
  "IDSA, infecciones de piel y partes blandas (2014); " + NELSON + ".",
  d=dict(rotulo="Las cuatro opciones frente al caso", ans=0, centro="Placa con varios puntos de pus",
         items=[("Ántrax", ["Varios forúnculos unidos: este caso"]),
                ("Forúnculo", ["Un solo folículo con un punto de pus"]),
                ("Impétigo", ["Costras color miel, superficial"]),
                ("Ectima", ["Úlcera con costra, más profunda"])],
         ruta=["Pústulas foliculares", "Se unen en una placa", "Varias bocas de pus", "Drenar + antibiótico"]),
  banda=B("Ántrax (foto real)", P("carbunco.jpg", 300, 240, [("circulo", 0.47, 0.45, 0.15, "varias bocas de pus", 0.05, 0.88)],
                                  credito="Medicalpal · Wikimedia Commons · CC BY-SA 4.0"),
          ["Placa roja, caliente e indurada.", "Varios puntos de supuración en la superficie.", "Foto de un adulto: en el niño el aspecto es el mismo."], ans=1),
  tabla=("Opciones de la pregunta", [("Forúnculo", False), ("Impétigo", False), ("Ectima", False), ("Ántrax", True)],
         [("¿Encaja?", ["No: un solo folículo", "No: costras superficiales", "No: úlcera", "Sí"])]))

# REU-076 · LES con síntomas B: linfoma · CRITERIOS
S("criterios", "REU-076", "lupus-fiebre-sudoracion-baja-peso-adenopatias-ldh-alta-complemento-normal-linfoma",
  "Lupus con síntomas B, adenopatías indoloras, LDH alta y complemento normal: descartar linfoma no Hodgkin",
  "Enfermedades autoinmunes · complicaciones", ER,
  ("LES y linfoma", ["Las personas con lupus tienen más riesgo de linfoma no Hodgkin.",
                     "Si los síntomas no se explican por un brote, hay que buscarlo."]),
  ("Mujer de 28 años con LES de 5 años", ["3 meses de fiebre, sudoración nocturna, baja de 6 kg y fatiga.",
                                          "Adenopatías cervicales y axilares indoloras; citopenias sin hemólisis; C3/C4 normales; LDH 600."]),
  ["Síntomas B + adenopatías indoloras + LDH alta + complemento normal = sospechar linfoma no Hodgkin.",
   "Biopsia escisional de un ganglio; TC para estadificar.",
   "La TB ganglionar y un brote lúpico son diferenciales, pero el complemento normal va en contra del brote."],
  "EULAR, LES (2023); " + HARRISON + ".",
  d=dict(rotulo="¿Pensar en linfoma?", tag="ESTE CASO",
         lista_titulo="Datos de alarma",
         items=[("Síntomas B: fiebre, sudoración, baja de peso", True, "3 meses, −6 kg"),
                ("Adenopatías indoloras", True, "Cervicales y axilares"),
                ("LDH elevada", True, "600 UI/L"),
                ("Complemento normal (no parece brote)", True, "C3 y C4 normales"),
                ("Hemólisis", False, "Sin datos de hemólisis")],
         umbral="varios datos juntos", veredicto="Biopsia escisional de ganglio para descartar linfoma no Hodgkin",
         img_titulo="La paciente", img=D(lambda s, x, y: I.cuerpo(s, x + 18, y, marcas=[(1, 108, 74), (2, 66, 100), (3, 174, 100)], sc=0.7), 230, 312),
         img_pie="1 ganglios cervicales; 2 y 3 axilares.",
         claves_titulo="Por qué no las otras",
         claves=[("Brote de LES", ["Complemento normal y LDH alta no encajan."], False),
                 ("TB o micosis", ["Posibles, pero la LDH y los ganglios indoloros orientan a linfoma."], False),
                 ("Lo prioritario", ["Linfoma no Hodgkin: biopsia."], True)]),
  tabla=("Opciones de la pregunta", [("Linfoma no Hodgkin", True), ("TB ganglionar", False), ("Reactivación de LES", False), ("Micosis profunda", False)],
         [("¿Prioritario?", ["Sí", "Diferencial", "No: complemento normal", "Menos probable"])]))


# REU-077 · Osteoartritis de rodilla · CÁLCULO
def _liq(s, x, y):
    import math as _m
    fy = lambda v: 330 - (_m.log10(v) - 2) / 3.2 * 300
    p = (f'<rect x="80" y="{fy(100000):.0f}" width="44" height="{fy(50000) - fy(100000):.0f}" fill="#fecaca"/>'
         + f'<rect x="80" y="{fy(50000):.0f}" width="44" height="{fy(2000) - fy(50000):.0f}" fill="#fde68a"/>'
         + f'<rect x="80" y="{fy(2000):.0f}" width="44" height="{fy(100) - fy(2000):.0f}" fill="#bbf7d0"/>'
         + I.t(130, (fy(100000) + fy(50000)) / 2 + 4, "séptico", I.RED, 10.5, "start")
         + I.t(130, (fy(50000) + fy(2000)) / 2 + 4, "inflamatorio", "#a16207", 10.5, "start")
         + I.t(130, (fy(2000) + fy(100)) / 2 + 4, "no inflamatorio", "#15803d", 10.5, "start")
         + "".join(I.t(74, fy(v) + 4, lab, I.MUTED, 9.5, "end", halo=False) for v, lab in [(100, "100"), (2000, "2 000"), (50000, "50 000")])
         + I.P(f"M70 {fy(1800):.0f} L134 {fy(1800):.0f}", "none", "#0f172a", 3) + I.C(102, fy(1800), 6, I.ORANGE, "#7c2d12", 2)
         + I.t(102, fy(1800) + 24, "1 800: este caso", I.ORANGE, 10.5)
         + I.t(102, 16, "Leucocitos en el líquido", I.SLATE, 10.5))
    I.g(s, x, y, p)


S("calculo", "REU-077", "dolor-mecanico-rodilla-osteofitos-liquido-1800-leucocitos-osteoartritis",
  "Dolor mecánico de rodilla con osteofitos y líquido sinovial no inflamatorio: osteoartritis",
  "Reumatología · artrosis de rodilla", ER,
  ("Líquido sinovial", ["< 2 000 leucocitos: no inflamatorio (artrosis, trauma).",
                        "2 000-50 000: inflamatorio (AR, gota); > 50 000: séptico hasta demostrar lo contrario."]),
  ("Varón de 60 años", ["2 meses de dolor de rodilla al iniciar el movimiento que cede con el reposo; sin calor ni eritema.",
                        "Rx: pinzamiento medial y osteofitos; líquido: amarillo, glucosa 82, leucocitos 1 800, 20 % PMN."]),
  ["Dolor mecánico + pinzamiento y osteofitos + líquido no inflamatorio = osteoartritis.",
   "La gota tendría cristales y líquido inflamatorio; la séptica, > 50 000 con glucosa baja.",
   "Tratamiento: ejercicio, bajar de peso, analgesia; infiltración si hay derrame doloroso."],
  "ACR, osteoartritis (2019); " + HARRISON + ".",
  d=dict(rotulo="Se suman los datos", tag="ESTE CASO",
         ilu_titulo="Líquido sinovial",
         ilu=ILU(D(_liq, 218, 360)),
         ilu_pie="Escala logarítmica: 1 800 cae en la zona no inflamatoria.",
         pasos=[("Tipo de dolor", ["Mecánico: aparece al moverse, cede con reposo."], False),
                ("Radiografía", ["Pinzamiento y osteofitos."], False),
                ("Leucocitos", ["1 800/mm³: < 2 000, no inflamatorio."], False),
                ("Neutrófilos y glucosa", ["20 % PMN; glucosa normal."], False),
                ("Resultado", ["Osteoartritis."], True)]),
  tabla=("Opciones de la pregunta", [("Artritis reumatoide", False), ("Artritis infecciosa", False), ("Osteoartritis", True), ("Gota aguda", False)],
         [("Líquido esperado", ["Inflamatorio", "Séptico", "No inflamatorio", "Inflamatorio con cristales"])]))


# REU-078 · Vitíligo localizado · SEMÁFORO (foto real)
def _vitm(s, x, y):
    _img_draw(s, x + 40, y, P("vitiligo_mano.jpg", 176, 245, [("flecha", 0.5, 0.42, 0.04, 0.06, "acromía")],
                              credito="J. Heilman · Commons · CC BY-SA 3.0"))


S("semaforo", "REU-078", "vitiligo-localizado-5-por-ciento-cara-manos-corticoide-topico",
  "Vitíligo localizado (5 % de superficie): corticoide tópico de potencia media-alta",
  "Dermatología · tratamiento del vitíligo", ER,
  ("Tratamiento del vitíligo", ["Se elige según la extensión, la actividad y la zona.",
                                "Localizado: tópicos. Extenso o que avanza rápido: fototerapia."]),
  ("Mujer de 30 años", ["2 años de máculas acrómicas en cara y dorso de manos que crecen lento.", "5 % de superficie; sin tratamientos previos."]),
  ["Vitíligo localizado: corticoide tópico de potencia media-alta en ciclos intermitentes.",
   "En cara y pliegues se prefieren inhibidores de calcineurina tópicos (menos atrofia), a menudo combinados.",
   "La fototerapia UVB de banda estrecha es para formas extensas; el trasplante, para formas estables y refractarias."],
  "Consenso internacional de vitíligo (2023); BAD (2022).",
  d=dict(rotulo="Imagen y semáforo de tratamiento",
         ilu_titulo="Vitíligo en la mano (foto real)",
         ilu=_vitm,
         ilu_pie="Acromía bien delimitada en el dorso de la mano.",
         check_titulo="Datos del caso",
         check=[("5 % de superficie: localizado", True), ("Avance lento", True), ("Sin tratamientos previos", True),
                ("Zonas visibles: cara y manos", False)],
         ans=0, tag="ESTE CASO",
         luces=[("Localizado", "Tópicos", ["Corticoide de potencia media-alta intermitente."]),
                ("Extenso o que avanza rápido", "Fototerapia UVB-BE", ["2-3 veces por semana."]),
                ("Estable y refractario", "Cirugía", ["Trasplante de melanocitos."])]),
  tabla=("Opciones de la pregunta", [("Corticoide tópico media-alta", True), ("Solo inhibidor de calcineurina", False), ("UVB-BE como monoterapia inicial", False),
                                     ("Trasplante de melanocitos", False)],
         [("¿Primera línea aquí?", ["Sí", "Útil en cara, no exclusivo", "Para formas extensas", "Solo estable y refractario"])]))

# REU-079 · Osteoporosis con fractura · TERMÓMETRO + franja
S("termometro", "REU-079", "posmenopausica-fractura-radio-t-score-menos-2-7-alendronato-calcio-vitamina-d",
  "Osteoporosis con fractura por fragilidad y T -2,7: alendronato semanal con calcio y vitamina D",
  "Metabolismo óseo · osteoporosis", ER,
  ("Osteoporosis", ["Diagnóstico: T-score ≤ -2,5 o una fractura por fragilidad.",
                    "Con fractura previa el riesgo de otra es alto: necesita fármaco."]),
  ("Mujer de 67 años posmenopáusica", ["Fractura de radio distal al caer de su altura hace 6 meses.",
                                       "DXA: T -2,7 en cuello femoral; sin ERC ni corticoides; pocos lácteos y poco sol."]),
  ["Osteoporosis con fractura: bifosfonato (alendronato 70 mg semanal) + calcio y vitamina D.",
   "Calcio y vitamina D solos no bastan; el ácido zoledrónico también necesita calcio y vitamina D.",
   "Prevenir caídas y revisar a los 3-5 años."],
  "AACE (2020); Endocrine Society (2019); NOF.",
  d=dict(rotulo="Densidad ósea y conducta",
         niveles=[("Normal", "T ≥ -1", ["Hábitos saludables"]),
                  ("Osteopenia", "T -1 a -2,5", ["Según riesgo (FRAX)"]),
                  ("Osteoporosis", "T ≤ -2,5", ["Tratar"]),
                  ("Grave", "T ≤ -2,5 + fractura", ["Tratar ya"])],
         caso_nivel=3, ruta_titulo="Qué se hace", paso_label="ESTE CASO",
         pasos=[(1, "Alendronato 70 mg semanal", ["En ayunas, de pie 30 minutos"], True),
                (2, "Calcio y vitamina D", ["Siempre junto al fármaco"], False),
                (3, "Prevenir caídas", ["Ejercicio, casa segura"], False)]),
  banda=B("Densitometría del caso", D(lambda s, x, y: I.tscore(s, x, y, -2.7, sc=0.95), 362, 100),
          ["T -2,7: rango de osteoporosis.", "Más la fractura de radio por fragilidad.", "Riesgo alto de una nueva fractura."], ans=0),
  tabla=("Opciones de la pregunta", [("Alendronato + calcio y vitamina D", True), ("Calcio, vitamina D y ejercicio", False),
                                     ("Zoledrónico sin calcio ni vitamina D", False), ("DXA anual y esperar", False)],
         [("Problema", ["Ninguno", "No basta con fractura previa", "Falta calcio y vitamina D", "Retrasa el tratamiento"])]))


# REU-080 · Urticaria aguda · ÁRBOL CON IMAGEN (foto real)
def _urt(s, x, y):
    _img_draw(s, x, y, P("urticaria.jpg", 210, 280, [("circulo", 0.5, 0.45, 0.12, "habones", 0.05, 0.06)],
                         credito="Psixtras · Wikimedia Commons · CC0"))


S("arbol_imagen", "REU-080", "habones-tras-mariscos-sin-dificultad-respiratoria-urticaria-antihistaminico",
  "Habones tras comer mariscos sin síntomas respiratorios ni hipotensión: antihistamínico oral",
  "Alergia · urticaria aguda", ER,
  ("Urticaria aguda", ["Habones rojos, elevados y pruriginosos que duran menos de 24 h cada uno.",
                       "Lo importante es descartar anafilaxia (respiración, circulación, intestino)."]),
  ("Varón de 18 años", ["2 horas de habones generalizados muy pruriginosos tras comer mariscos.",
                        "Sin fiebre, sin dificultad respiratoria, signos vitales normales."]),
  ["Urticaria sin anafilaxia: antihistamínico H1 oral no sedante y evitar el alimento.",
   "Educar en signos de alarma; adrenalina IM solo si hay anafilaxia.",
   "Los corticoides EV y los estudios no son necesarios de entrada."],
  "EAACI/GA²LEN/WAO, urticaria (2022); WAO, anafilaxia (2020).",
  d=dict(rotulo="¿Es solo piel o es anafilaxia?", tag="ESTE CASO",
         pregunta="Habones agudos: ¿hay síntomas respiratorios, hipotensión o vómitos?",
         ramas=[("Sí: anafilaxia", "Adrenalina IM", ["0,5 mg en el muslo; emergencia."]),
                ("No: solo piel", "Antihistamínico oral",
                 ["Cetirizina o loratadina.", "Evitar los mariscos."])],
         ilu=_urt, IW=210, IH=298,
         ilu_pie="Foto real: habones rojos y elevados.",
         luego_titulo="Qué más",
         luego=[("Signos de alarma", ["Volver si le cuesta respirar o se marea."], True),
                ("Si no mejora en días", ["Subir la dosis del antihistamínico."], False),
                ("No de entrada", ["Corticoides EV ni estudios."], False)]),
  tabla=("Opciones de la pregunta", [("Antihistamínico oral", True), ("Adrenalina IM", False), ("Corticoide EV", False), ("Estudios primero", False)],
         [("¿Indicado?", ["Sí", "Solo en anafilaxia", "No de entrada", "Retrasa el alivio"])]))

# NRL-067 · TEC con fractura de base: intubar antes del traslado · RED + franja
S("red", "NRL-067", "tec-glasgow-6-fractura-base-craneo-sato2-86-intubar-antes-traslado",
  "TEC grave con Glasgow 6 y SatO₂ 86 % antes de un traslado de 40 min: intubar con secuencia rápida",
  "Traumatismo craneoencefálico · traslado seguro", EN,
  ("TEC grave y lesión secundaria", ["La hipoxia y la hipotensión empeoran mucho el daño cerebral.",
                                     "Con Glasgow ≤ 8 el paciente no protege su vía aérea."]),
  ("Varón de 25 años, hospital sin neurocirugía", ["Glasgow 6, pupilas normales, SatO₂ 86 %, PA 100/60.",
                                                   "Signos de fractura de base de cráneo; traslado de 40 minutos."]),
  ["Antes del traslado: intubación orotraqueal con secuencia rápida (con protección cervical) y ventilar a normocapnia.",
   "Mantener SatO₂ > 94 % y PAS ≥ 100-110; con fractura de base, sonda orogástrica (nunca nasal).",
   "Trasladar sin vía aérea o sedar sin intubar es peligroso; el manitol no corrige la hipoxia."],
  ATLS + "; " + BTF + ".",
  d=dict(rotulo="Dónde está el paciente y a dónde va", caso="II-1", destino="III-1", flecha="Traslado intubado", tag="ESTE CASO",
         claves=[("Intubar con secuencia rápida", ["Glasgow 6 y SatO₂ 86 %."], True),
                 ("Ventilar a normocapnia", ["Evitar hipoxia e hipotensión."], False),
                 ("No hacer", ["Trasladar sin vía aérea, sedar sin intubar, sonda nasal."], False)]),
  banda=B("Signos de fractura de base (esquema)", D(lambda s, x, y: I.cabeza_base(s, x, y), 250, 270),
          ["Ojos de mapache (equimosis alrededor de los ojos).", "Signo de Battle (detrás de la oreja).", "Salida de LCR por la nariz: nada por vía nasal."], ans=0),
  tabla=("Opciones de la pregunta", [("Intubación con secuencia rápida", True), ("Manitol antes de derivar", False),
                                     ("Trasladar sin intubar", False), ("Sedar sin intubar", False)],
         [("Problema", ["Ninguno", "No corrige la hipoxia", "Riesgo de aspiración e hipoxia", "Deprime la respiración"])]))
