"""Entrega 3 · tanda t05 (25 flujogramas)."""
from c28 import S, P, PA, B, Q, L, TR, NELSON, ATLS, HARRISON, WILLIAMS, MINSA, ACOG, OMS, CDC, ADA, AHA, AAP, NICE, IDSA, ESC, KDIGO, GINA
from c27 import DOS

CC = " · Wikimedia Commons · "
PROPIO = "Esquema MedQuizPro (dibujo propio)"
ECG_PROPIO = "Trazado de enseñanza MedQuizPro (no es de un paciente)"
PMC_CERVIX = "Pongchaikul et al. · Clin Microbiol Rev 2026 · PMC13560723 (PubMed Central) · CC BY 4.0"

# INF-082 · Signo de Romaña · LECTURA (foto + vector)
S("lectura", "INF-082", "Escolar del sur del Perú con edema bipalpebral unilateral indoloro, conjuntivitis y adenopatía preauricular (signo de Romaña): enfermedad de Chagas aguda",
  "Tripanosomiasis americana · Chagas",
  ("Enfermedad de Chagas", ["Trypanosoma cruzi entra por las heces de la «chirimacha» (Triatoma infestans) al rascar la picadura o por la conjuntiva.",
                            "Fase aguda: signo de Romaña o chagoma; años después, miocardiopatía, megaesófago o megacolon."]),
  ("Adolescente de 12 años", ["Edema bipalpebral unilateral izquierdo, hiperemia conjuntival y adenopatía preauricular.", "Vive en un valle costero del suroeste del Perú."]),
  ["Fase aguda: buscar el parásito en sangre (gota gruesa, Strout); en la crónica, serología (2 técnicas).",
   "Tratamiento: benznidazol o nifurtimox 60 días (casi siempre cura en la fase aguda y en niños).",
   "Control: rociado de viviendas, mejorar paredes y techos, tamizaje en gestantes y bancos de sangre."],
  MINSA + ", NTS de enfermedad de Chagas (2023); OPS, guía de Chagas (2018).",
  op=("¿Diagnóstico?", ["No: araña; dolor y contracturas", "No: araña; placa que se necrosa", "No: verrugas o anemia, valles andinos",
                        "Sí: signo de Romaña en zona endémica", "No: dolor, fiebre, ojo rojo con limitación del movimiento"]),
  d=dict(rotulo="Lee la imagen en este orden", img_titulo="Signo de Romaña y el vector",
         img=P("romana_triatoma.jpg", 420, 180, credito="Romaña / PLOS NTD (CC BY 4.0) y CDC/OMS (dominio público)" + CC.rstrip(" · "), fondo="#ffffff"),
         pines=[(0.13, 0.42), (0.60, 0.25)],
         pasos=[("Párpados hinchados de un solo ojo", "Indoloro, violáceo: puerta de entrada conjuntival.", True),
                ("La chirimacha (vinchuca)", "Pica de noche; sus heces tienen el parásito.", False),
                ("Adenopatía preauricular", "Completa el complejo oftalmoganglionar.", False),
                ("Confirmar", "Parásito en sangre (fase aguda) y tratar con benznidazol.", False)],
         img_pie="Foto de otro paciente y del insecto.",
         veredicto=("Romaña en zona endémica = Chagas agudo", "Gota gruesa o Strout y benznidazol; rociar la vivienda.")))

# SP-115 · Carga de enfermedad: AVAD · CÁLCULO (AVAD = AVP + AVD)
S("arbol", "SP-115", "Para saber qué regiones redujeron la discapacidad y la muerte prematura con una intervención, se usa el estudio de carga de enfermedad (AVAD)",
  "Salud pública · indicadores compuestos",
  ("Carga de enfermedad", ["Mide la pérdida de salud de una población en AVAD (años de vida ajustados por discapacidad).",
                           "AVAD = años perdidos por muerte prematura (AVP) + años vividos con discapacidad (AVD)."]),
  ("Pregunta de gestión", ["Intervención para reducir la discapacidad prematura.", "¿Qué regiones se beneficiaron?"]),
  ["Permite comparar enfermedades y regiones con una sola cifra.",
   "ASIS: describe la situación de salud (más amplio, no mide AVAD por sí mismo).",
   "Ensayo clínico: prueba un tratamiento en personas, no evalúa regiones."],
  OMS + ", Global Burden of Disease; " + MINSA + ", carga de enfermedad en el Perú (CDC-MINSA, 2023).",
  op=("¿Qué solicitar?", ["No: evalúan un tratamiento", "Sí: mide AVAD por región", "No: no comparan carga", "Incluye datos, pero la medida pedida son AVAD", "No: cuenta población"]),
  arbol=Q("¿Qué pregunta quieres responder?", [
      L("¿Cuánta salud se perdió? (este caso)", "CARGA DE ENFERMEDAD", ["AVAD = AVP + AVD"], path=True),
      L("¿Cómo está la salud del territorio?", "ASIS", ["Diagnóstico situacional"]),
      L("¿Funciona un tratamiento?", "Ensayo clínico", ["Aleatorizado"])], path=True),
  escala=dict(nombre="Cómo se calculan los AVAD", modo="puntaje", que="Ejemplo para entender la fórmula.",
              items=[("AVP", "Años perdidos por muerte prematura", "Muertes × años que faltaban vivir", None),
                     ("AVD", "Años vividos con discapacidad", "Casos × duración × peso de discapacidad", None)],
              total_txt="AVAD = AVP + AVD", total_nota="1 AVAD = 1 año de vida sana perdido",
              rangos=[("↑ AVAD", "Más carga", "Priorizar"), ("↓ AVAD", "Menos carga", "La intervención funcionó")],
              caso_rango=1, porque=[("Se busca dónde bajaron los AVAD", True)], conducta="Comparar AVAD antes y después por región."))

# PED-150 · BCG sin cicatriz: no revacunar · ÁRBOL
S("arbol", "PED-150", "Lactante de 4 meses vacunado con BCG (con carné) que no tiene cicatriz ni nódulo: no requiere revacunación",
  "Inmunizaciones · BCG",
  ("Vacuna BCG", ["Se aplica al nacer (intradérmica, deltoides derecho) y protege de las formas graves de TB (meníngea, miliar).",
                  "En 10-20 % no deja cicatriz y eso no significa que no proteja."]),
  ("Lactante de 4 meses", ["Sin cicatriz ni nódulo de BCG.", "Carné de vacunación completo."]),
  ["Con registro de vacunación: no revacunar (OMS y MINSA).",
   "Sin registro y menor de 1 año: aplicar BCG.",
   "No hace falta PPD antes de vacunar en el lactante; la BCG no se repite."],
  OMS + ", posición sobre BCG (2018); " + MINSA + ", NTS del esquema nacional de vacunación (2022).",
  op=("¿Conducta?", ["Sí: está vacunado aunque no haya cicatriz", "No: no se revacuna", "No: no se revacuna", "No: no se revacuna", "No: no se pide"]),
  arbol=Q("Niño sin cicatriz de BCG: ¿tiene registro de la vacuna?", [
      L("Sí, carné completo (este caso)", "NO REVACUNAR", ["La falta de cicatriz no indica falla"], path=True),
      L("No hay registro y < 1 año", "Aplicar BCG", ["Dosis única"])], path=True))

# PED-151 · Fiebre con sonda vesical: urocultivo · RADIAL (focos nosocomiales)
S("radial", "PED-151", "Niña hospitalizada con sonda vesical que a los 2 días hace fiebre de 39 °C: sospechar infección urinaria asociada a catéter, pedir urocultivo con antibiograma",
  "Infecciones asociadas a la atención de salud",
  ("ITU asociada a catéter urinario", ["La infección intrahospitalaria más frecuente: el riesgo sube 3-7 % por cada día de sonda.",
                                       "Fiebre en un paciente con sonda: urocultivo (de la sonda nueva o del puerto, nunca de la bolsa)."]),
  ("Niña de 3 años con parálisis cerebral", ["Hospitalizada por deshidratación grave; sondas nasogástrica y vesical.", "A los 2 días: malestar y T 39 °C."]),
  ["Urocultivo con antibiograma (cambiar la sonda si lleva > 2 semanas) y además hemocultivos si está grave.",
   "Retirar la sonda en cuanto se pueda: es la mejor prevención.",
   "Antibiótico según el antibiograma; empírico si hay sepsis."],
  CDC + "/HICPAC, prevención de ITU asociada a catéter (2009; act. 2019); IDSA (2010).",
  op=("¿Examen más pertinente?", ["Sí: la sonda es el foco más probable", "No: no identifica el foco", "Complementa, si hay sepsis",
                                  "No: no está indicado", "La diarrea ya estaba; no explica la fiebre nueva"]),
  d=dict(rotulo="Fiebre en un hospitalizado: ¿qué dispositivo la causa?", centro="SONDA VESICAL", centro_sub="este caso", ans=0,
         items=[("SONDA VESICAL", ["ITU: urocultivo"]), ("CATÉTER VENOSO", ["Bacteriemia: hemocultivos"]), ("VENTILADOR", ["Neumonía: cultivo traqueal"]),
                ("HERIDA OPERATORIA", ["Infección de sitio quirúrgico"]), ("SONDA NASOGÁSTRICA", ["Sinusitis, aspiración"])],
         ruta=["Revisar dispositivos", "Urocultivo de la sonda", "Retirar la sonda", "Antibiótico según cultivo"]))

# SP-116 · Sarampión importado · DECISIÓN
S("decision", "SP-116", "Joven que estuvo hace 15 días en un país con sarampión, con fiebre, exantema maculopapular e IgM positiva: caso confirmado importado",
  "Vigilancia epidemiológica · sarampión",
  ("Clasificación de casos de sarampión", ["Sospechoso: fiebre + exantema maculopapular (o lo sospecha un trabajador de salud).",
                                           "Confirmado por laboratorio (IgM o PCR); importado si se contagió fuera del país (7-21 días antes del exantema)."]),
  ("Varón de 23 años", ["Hace 15 días estuvo en un país con transmisión.", "Fiebre, exantema maculopapular generalizado no vesicular; IgM (+)."]),
  ["Notificar en menos de 24 horas; aislamiento respiratorio hasta 4 días después del exantema.",
   "Búsqueda de contactos y vacunación de bloqueo (SPR) en 72 horas.",
   "Vitamina A en niños; el Perú mantiene la eliminación con cobertura ≥ 95 %."],
  "OPS, vigilancia del sarampión y la rubéola (2023); " + MINSA + ", NTS de vigilancia (2024).",
  op=("¿Clasificación?", ["Sí: confirmado y contagiado en el extranjero", "Ya pasó de sospechoso: tiene IgM (+)", "No: se contagió fuera",
                          "No: no es una categoría", "No: está confirmado"]),
  d=dict(rotulo="Clasificación del caso de sarampión", eje_y="Laboratorio", ancho_filas=200,
         cols=["Contagio en el país", "Contagio en el extranjero (7-21 d antes)"],
         rows=[("Sin muestra todavía", "Fiebre + exantema"), ("IgM o PCR positiva", ""), ("IgM y PCR negativas", "")],
         cells=[[("Sospechoso", ["Notificar y tomar muestra"]), ("Sospechoso", ["Notificar y tomar muestra"])],
                [("Confirmado autóctono", ["Transmisión local"]), ("Confirmado IMPORTADO", ["Viaje a zona con casos"])],
                [("Descartado", []), ("Descartado", [])]],
         caso=(1, 1), nota="La clasificación cambia lo que hace salud pública: en un importado hay que cortar la transmisión secundaria."),
  banda=B("Así es el exantema", P("sarampion_mont.jpg", 420, 147, [], credito="CDC (PHIL 6111 y 4497)" + CC + "dominio público"),
          [("Manchas de Koplik", "Puntos blancos en la mucosa de la mejilla."),
           ("Exantema maculopapular", "Empieza en la cara y baja."),
           ("Fiebre, tos, coriza y conjuntivitis", "Pródromo de 3-4 días.")],
          pie="Fotos de otros pacientes."))

# PED-152 · Hipoglucemia neonatal sintomática · REGLA + checklist
S("regla", "PED-152", "Prematuro de 34 semanas con 48 horas, hipoactivo, con temblores y glucosa de 40 mg/dL: hipoglucemia sintomática, bolo de glucosa EV 200 mg/kg",
  "Neonatología · hipoglucemia",
  ("Hipoglucemia neonatal", ["Prematuros, hijos de madre diabética, pequeños o grandes para la edad: más riesgo.",
                             "Con síntomas (temblores, hipotonía, apneas, convulsiones) se corrige por vena aunque la cifra no sea muy baja."]),
  ("RN de 34 semanas, 48 horas", ["Taquipnea, vómitos tras lactar, hipoactivo y con temblores.", "Glucosa 40 mg/dL; hemograma normal."]),
  ["Bolo de dextrosa al 10 % 2 mL/kg (200 mg/kg) EV en 5-10 min.",
   "Seguir con infusión de 6-8 mg/kg/min y controlar a los 30-60 min.",
   "Meta: > 45-50 mg/dL en las primeras 48 h y > 60 mg/dL después (PES)."],
  AAP + ", hipoglucemia neonatal (2011); Pediatric Endocrine Society (2015); " + NELSON + ".",
  op=("¿Tratamiento?", ["No: con síntomas no basta la vía oral", "Sí: sintomático = EV", "No: no basta", "No: con síntomas, EV", "No: es para ictericia"],
      {1: "200 mg/kg de glucosa EV"}),
  d=dict(rotulo="Glucosa del recién nacido",
         reglas=[dict(nombre="Glucemia (mg/dL) en el recién nacido", que="Cualquier síntoma con glucosa baja = tratamiento EV.",
                      min=0, max=100, fmt="{}", ticks=[25, 45, 60],
                      bandas=[(0, 25, "< 25: EV ya", 4), (25, 45, "Baja", 3), (45, 60, "Límite", 1), (60, 100, "Normal (> 48 h)", 0)],
                      caso=40, caso_txt="ESTE CASO: 40 + síntomas")],
         claves_titulo="Qué hacer",
         claves=[("Bolo EV", ["Dextrosa 10 %: 2 mL/kg"], True), ("Infusión", ["6-8 mg/kg/min"], True), ("Controlar", ["30-60 min después"], False)]))

# GIN-154 · Calcio desde las 20 semanas · CRONOLOGÍA de suplementos
S("reloj", "GIN-154", "La suplementación profiláctica de calcio en la gestante se da desde las 20 semanas hasta el término (previene la preeclampsia en poblaciones con poca ingesta)",
  "Control prenatal · suplementos",
  ("Calcio en el embarazo", ["En poblaciones con poca ingesta de calcio (como el Perú), 1-2 g/día reduce la preeclampsia.",
                             "El MINSA lo indica desde las 20 semanas hasta el parto; separado del hierro (no se absorben juntos)."]),
  ("Pregunta de teoría", ["¿Desde y hasta cuándo", "se da el calcio profiláctico?"]),
  ["Calcio 2 g/día (carbonato) desde las 20 semanas, 2 horas antes o después del hierro.",
   "Ácido fólico desde antes del embarazo hasta las 13 semanas; hierro + fólico desde las 14 semanas.",
   "Aspirina en dosis baja (desde las 12-16 semanas) si hay riesgo de preeclampsia."],
  OMS + ", calcio en la gestación (2018); " + MINSA + ", atención prenatal reenfocada.",
  op=("¿Desde y hasta cuándo?", ["Sí: 20 semanas al término", "No: es el ácido fólico", "No: rango incorrecto", "No: muy tarde", "No: es prenatal"],
      {0: "Desde las 20 semanas hasta el término", 2: "De las 13 a las 19 semanas"}),
  d=dict(rotulo="Suplementos a lo largo del embarazo (MINSA)",
         pasos=[("Antes", "Ácido fólico", "Desde 3 meses antes", False), ("0-13 s", "Ácido fólico", "Previene defectos del tubo neural", False),
                ("14 s", "Hierro + fólico", "Hasta el posparto", False), ("20 s", "Calcio", "Hasta el término", True), ("Parto", "Fin del calcio", "Hierro sigue en el puerperio", False)],
         veredicto=("Calcio: desde las 20 semanas hasta el término", "Separado del hierro para que ambos se absorban.")))

# PED-153 · CRED en el primer año · RELOJ
S("reloj", "PED-153", "En el control de crecimiento y desarrollo (CRED) del MINSA, el primer año tiene 4 controles en el primer mes y luego uno cada mes",
  "Atención del niño sano · CRED",
  ("Controles CRED en el Perú", ["Recién nacido: 4 controles (a los 7, 14, 21 y 28 días; o 48 h, 7, 14 y 28 días según la norma).",
                                 "Luego uno cada mes hasta los 11 meses: 11 controles más (15 en el primer año)."]),
  ("Pregunta de teoría", ["¿Cuántos controles CRED", "en el primer año de vida?"]),
  ["De 1 a 2 años: un control cada 2 meses (6 en el año); de 2 a 4 años: cada 3 meses; de 5 a 11 años: uno al año.",
   "En cada control: peso, talla, perímetro cefálico, desarrollo, vacunas, hemoglobina y consejería.",
   "Hemoglobina para descartar anemia a los 6, 12 y 18 meses."],
  MINSA + ", NTS n.º 137 de control de crecimiento y desarrollo del niño (2017).",
  op=("¿Cuántos controles?", ["No: muy pocos", "No: muy pocos", "Sí: 4 en el primer mes y luego mensual", "No: muy pocos", "No: muy pocos"]),
  d=dict(rotulo="Controles CRED del primer año",
         pasos=[("1.er mes", "4 controles", "Recién nacido", True), ("2 m", "Mensual", "Peso, talla, vacunas", False),
                ("6 m", "Mensual", "Hb y alimentación", False), ("11 m", "Último del año", "15 en total", False)],
         veredicto=("4 en el primer mes y luego uno cada mes", "Después de 1 año, cada 2 meses hasta los 2 años.")))

# SP-117 · Incidencia acumulada · ÁRBOL
S("arbol", "SP-117", "En 1000 personas aparecen 45 casos nuevos de una enfermedad: la incidencia acumulada es 45 por 1000",
  "Epidemiología · medidas de frecuencia",
  ("Incidencia", ["Casos NUEVOS en un periodo dividido entre la población en riesgo al inicio: mide el riesgo de enfermar.",
                  "Prevalencia: casos existentes (nuevos y antiguos) en un momento."]),
  ("Población de 1000 personas", ["Aparecen 45 casos nuevos.", "¿Qué se puede afirmar?"]),
  ["Incidencia = 45/1000 = 4,5 % en el periodo.",
   "Riesgo relativo y atribuible necesitan comparar dos grupos (expuestos y no expuestos).",
   "Letalidad = muertes / casos."],
  "OPS, MOPECE (2.ª ed.); Gordis, Epidemiología 6.ª ed.",
  op=("¿Afirmación correcta?", ["Sí: casos nuevos / población en riesgo", "No: serían los existentes", "No: necesita dos grupos", "No: necesita dos grupos", "No: es muertes / casos"]),
  arbol=Q("¿Qué casos se cuentan?", [
      L("Solo los nuevos (este caso)", "INCIDENCIA", ["45 / 1000 = 45 por 1000", "Riesgo de enfermar"], path=True),
      L("Todos los existentes", "Prevalencia", ["Foto en un momento"]),
      L("Los que mueren de los enfermos", "Letalidad", ["Gravedad"])], path=True))

# CB-059 · Vacunas: inmunidad activa · MATRIZ
S("matriz", "CB-059", "Al administrar una vacuna se induce inmunidad activa artificial: el propio organismo produce anticuerpos y memoria",
  "Inmunología · tipos de inmunidad",
  ("Tipos de inmunidad adquirida", ["Activa: el propio cuerpo responde al antígeno (tarda semanas, deja memoria, dura años).",
                                    "Pasiva: recibe anticuerpos hechos (inmediata, sin memoria, dura semanas o meses)."]),
  ("Pregunta de teoría", ["¿Qué inmunidad induce una vacuna?", ""]),
  ["Activa natural: tener la infección. Activa artificial: vacuna.",
   "Pasiva natural: anticuerpos de la madre (placenta, leche). Pasiva artificial: inmunoglobulinas, sueros antiveneno.",
   "Por eso en la rabia grave se dan juntas: vacuna (activa) e inmunoglobulina (pasiva)."],
  "Abbas, Inmunología celular y molecular 10.ª ed.; " + OMS + ".",
  op=("¿Tipo de inmunidad?", ["No: mixta es vacuna + inmunoglobulina juntas", "No: pasiva son anticuerpos hechos", "Sí: el cuerpo produce y recuerda",
                              "No: no es un tipo de inmunidad", "No: la innata no se induce con vacunas"]),
  d=dict(rotulo="¿Quién fabrica los anticuerpos y cómo llegan?", eje_x="Cómo se adquiere", eje_y="Quién los produce",
         cols=["Natural", "Artificial"], rows=["El propio cuerpo (activa)", "Otro (pasiva)", "Duración"], caso=(0, 1),
         cells=[[("Infección", ["Sarampión pasado"]), ("VACUNA", ["Este caso", "Memoria inmunológica"])],
                [("Madre → hijo", ["Placenta, leche"]), ("Inmunoglobulina", ["Antitetánica, antirrábica"])],
                [("Años (activa)", ["Con memoria"]), ("Semanas (pasiva)", ["Sin memoria"])]]))

# SP-118 · Transmisión por vehículo · TRANSMISIÓN
S("transmision", "SP-118", "Pseudomonas y otros gramnegativos en el agua potable del hospital: transmisión por vehículo (objeto o sustancia inanimada)",
  "Epidemiología · mecanismos de transmisión",
  ("Mecanismos de transmisión", ["Directa: contacto, gotitas. Indirecta: vehículo (agua, alimentos, objetos), vector (insectos) o aérea (núcleos de gotitas).",
                                 "El agua contaminada es un vehículo común: muchos se exponen a la vez."]),
  ("Hospital", ["Pseudomonas y otros gramnegativos en el agua potable.", "¿Contra qué vía se toman medidas?"]),
  ["Cortar la fuente: desinfectar el sistema de agua, filtros en grifos de áreas críticas, cultivos de control.",
   "Vigilar infecciones en pacientes de UCI e inmunodeprimidos.",
   "No usar agua del grifo para dispositivos (nebulizadores, humidificadores)."],
  CDC + ", control ambiental de infecciones (2003; act. 2019); " + OMS + ".",
  op=("¿Vía?", ["No: núcleos de gotitas en el aire", "Sí: el agua es el vehículo", "No: no hay insecto", "No: no son fluidos corporales", "No: no es de persona a persona"]),
  d=dict(rotulo="La cadena de esta infección y dónde se corta",
         eslabones=[("Agente", "Pseudomonas, gramnegativos", "Cultivos de vigilancia", False),
                    ("Reservorio", "Tuberías, tanques, grifos", "Desinfectar el sistema", False),
                    ("Vehículo", "Agua potable del hospital", "Filtros y agua estéril", True),
                    ("Entrada", "Heridas, vías, mucosas", "Asepsia de dispositivos", False),
                    ("Huésped", "UCI, inmunodeprimidos", "Vigilancia", False)],
         veredicto=("Agua contaminada = transmisión por vehículo", "Se corta tratando la fuente de agua.")))

# SP-119 · Acreditación: autoevaluación · PIRÁMIDE (fases)
S("piramide", "SP-119", "En la acreditación de los establecimientos de salud, la valoración que hace el propio personal de la institución es la autoevaluación",
  "Calidad en salud · acreditación",
  ("Acreditación de establecimientos (MINSA)", ["Proceso para comprobar que se cumplen estándares de calidad.",
                                               "Fases: autoevaluación (equipo interno) → evaluación externa (evaluadores ajenos) → acreditación."]),
  ("Pregunta de teoría", ["¿Cómo se llama la valoración", "que hace el personal de la propia institución?"]),
  ["Autoevaluación: el equipo interno compara su servicio con los estándares y hace planes de mejora.",
   "Evaluación externa: la hace un equipo de evaluadores acreditados ajenos al establecimiento.",
   "La auditoría médica revisa la calidad de la atención en historias clínicas."],
  MINSA + ", NTS de acreditación de establecimientos de salud (NTS 050).",
  op=("¿Cómo se denomina?", ["Sí: la hace el propio personal", "No: la hacen evaluadores de afuera", "No: es devolver resultados", "No: es otra técnica", "No: revisa historias, externa"]),
  d=dict(rotulo="Fases de la acreditación", caso=0, pie="▲ primer paso · ▼ resultado",
         niveles=[("1", "Autoevaluación", "El propio personal compara con los estándares"),
                  ("2", "Plan de mejora", "Corrige lo que falta"),
                  ("3", "Evaluación externa", "Evaluadores ajenos verifican"),
                  ("4", "Acreditación", "Se otorga si cumple (vigencia limitada)")],
         veredicto=("La valoración interna es la autoevaluación", "Luego viene la evaluación externa.")))

# REU-045 · Escabiosis en el lactante: permetrina · CHECKLIST + foto
S("checklist", "REU-045", "Lactante de 18 meses con prurito, surcos y pápulas en muñecas, espacios interdigitales, palmas, plantas, tronco y cara: escabiosis, permetrina al 5 %",
  "Ectoparasitosis · sarna",
  ("Escabiosis", ["Sarcoptes scabiei cava surcos en la piel: prurito peor de noche y contagio familiar.",
                  "En lactantes afecta también palmas, plantas, cara y cuero cabelludo (en adultos no)."]),
  ("Lactante de 18 meses", ["Lesiones que pican: surcos lineales y pápulas con costras.", "Muñecas, tronco, interdigitales, palmas, plantas y cara."]),
  ["Permetrina al 5 % en crema: de la cabeza a los pies (incluida la cara en lactantes) por 8-14 h; repetir a los 7 días.",
   "Tratar a toda la familia al mismo tiempo; lavar la ropa con agua caliente.",
   "Ivermectina oral no en < 15 kg; el prurito puede durar 2-4 semanas después."],
  CDC + ", escabiosis (2024); AAP Red Book (2024); " + MINSA + ".",
  op=("¿Tratamiento de elección?", ["Sí: segura desde los 2 meses", "Alternativa menos eficaz", "No en lactantes (irrita)", "No: neurotóxico (lindano)", "No se usa tópica así; oral no en < 15 kg"]),
  d=dict(rotulo="Cómo tratar la sarna en un lactante", tag="ELECCIÓN",
         pasos=[("Permetrina 5 % en todo el cuerpo", "Incluye cara y cuero cabelludo; dejar 8-14 h", True), ("Repetir a los 7 días", "Mata las larvas que nacen", False),
                ("Toda la familia a la vez", "Aunque no tengan síntomas", False), ("Ropa y sábanas", "Agua caliente o bolsa cerrada 72 h", False)],
         no_hacer=[("Lindano (hexacloruro)", "Neurotóxico"), ("Ivermectina oral < 15 kg", "No está aprobada"), ("Tratar solo al niño", "Se reinfecta")],
         veredicto=("Escabiosis en lactante: permetrina al 5 %", "A toda la familia y repetir en 7 días.")),
  banda=B("Así se ve la sarna", P("escabiosis.jpg", 300, 233, [], credito="Michael Geary" + CC + "dominio público"),
          [("Surcos y pápulas", "Entre los dedos y en muñecas."),
           ("Prurito nocturno", "Toda la familia se rasca."),
           ("En el lactante", "También palmas, plantas y cara.")],
          pie="Foto de otro paciente."))

# NEU-044 · Asma: factor biológico de mortalidad · RADIAL
S("radial", "NEU-044", "Entre los factores de riesgo de muerte por asma, el biológico es la resistencia a los corticoides (no mejora con ellos)",
  "Asma · riesgo de muerte",
  ("Factores de riesgo de asma fatal", ["Biológicos: crisis graves previas (intubación, UCI), resistencia a corticoides, hipoxemia, uso excesivo de salbutamol.",
                                       "Ambientales (tabaco), asistenciales (mal control) y psicosociales (problemas mentales, pobreza)."]),
  ("Pregunta de teoría", ["¿Cuál es un factor BIOLÓGICO", "de mortalidad en el asma?"]),
  ["Identificar al paciente de riesgo y darle plan de acción escrito y control frecuente.",
   "Más de 1 inhalador de salbutamol al mes (> 200 dosis): mal control y riesgo.",
   "GINA: no usar salbutamol solo; siempre con corticoide inhalado."],
  GINA + "; " + MINSA + ".",
  op=("¿Factor biológico?", ["Sí: biológico del paciente", "Ambiental", "Asistencial", "Psicosocial", "No es un factor de mortalidad establecido"],
      {0: "Resistencia a corticosteroides"}),
  d=dict(rotulo="Factores de riesgo de muerte por asma", centro="BIOLÓGICO", centro_sub="este caso", ans=0,
         items=[("BIOLÓGICO", ["Resistencia a corticoides", "Crisis graves previas"]), ("AMBIENTAL", ["Humo de tabaco", "Alérgenos"]),
                ("ASISTENCIAL", ["Mal control, sin corticoide"]), ("PSICOSOCIAL", ["Depresión, pobreza"]), ("FÁRMACOS", ["Exceso de salbutamol solo"])],
         ruta=["Identificar el riesgo", "Corticoide inhalado siempre", "Plan de acción escrito", "Control frecuente"]))

# REU-046 · Piel escaldada estafilocócica · TARJETAS + foto
S("tarjetas", "REU-046", "Lactante con fiebre de 39 °C, irritable, eritema difuso alrededor de los orificios y en pliegues con ampollas fláccidas y Nikolsky (+): síndrome de piel escaldada (Ritter)",
  "Enfermedades ampollosas · piel escaldada estafilocócica",
  ("Síndrome de piel escaldada estafilocócica (Ritter)", ["Toxinas exfoliativas de S. aureus rompen la desmogleína 1 en la capa granulosa: la piel se despega.",
                                                          "Niños < 5 años; mucosas respetadas (en la necrólisis epidérmica tóxica no)."]),
  ("Lactante, 3.er día de fiebre", ["Fiebre de 39 °C, irritable y anoréxico.", "Eritema periorificial y en pliegues, ampollas fláccidas, Nikolsky (+)."]),
  ["Hospitalizar: oxacilina o cefazolina EV (+ clindamicina para frenar la toxina); cambiar por vancomicina si hay SAMR.",
   "Líquidos, control de temperatura, curaciones suaves; no usar corticoides.",
   "Sana sin cicatriz en 1-2 semanas."],
  "AAP Red Book (2024); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: genética, ampollas desde el nacimiento", "No: localizado, sin eritema difuso ni fiebre", "No: adultos, autoinmune",
                        "Sí: lactante + eritema + Nikolsky, sin mucosas", "No: por fármacos, con mucosas, adultos"]),
  d=dict(rotulo="Ampollas con Nikolsky (+): ¿cuál?", ans=0,
         cards=[dict(titulo="Piel escaldada (Ritter)", datos=[("Edad", "< 5 años", True), ("Mucosas", "Respetadas", True), ("Causa", "Toxina de S. aureus", True)], pie="Este caso."),
                dict(titulo="Necrólisis epidérmica", datos=[("Edad", "Adultos", False), ("Mucosas", "Afectadas", False), ("Causa", "Fármacos", False)], pie="Grave."),
                dict(titulo="Impétigo ampolloso", datos=[("Extensión", "Local", False), ("Nikolsky", "Negativo", False), ("Fiebre", "No", False)], pie="Toxina local."),
                dict(titulo="Pénfigo vulgar", datos=[("Edad", "Adultos", False), ("Mucosas", "Sí, boca", False), ("Causa", "Autoinmune", False)], pie="Crónico.")]),
  banda=B("Así se ve la piel escaldada", P("ssss.jpg", 320, 224, [], credito="OpenStax Microbiology" + CC + "CC BY 4.0"),
          [("Piel que se despega", "Como una quemadura superficial."),
           ("Nikolsky (+)", "Al frotar, la piel sana se desprende."),
           ("Sin cicatriz", "La rotura es superficial (capa granulosa).")],
          pie="Foto de la mano de otro lactante."))

# REU-047 · Onicomicosis · CUADRÍCULA + foto
S("cuadricula", "REU-047", "Adolescente deportista con uñas de ambos primeros dedos de los pies blanquecinas, engrosadas y despegadas del lecho: onicomicosis",
  "Enfermedades de las uñas",
  ("Onicomicosis", ["Infección de la uña por dermatofitos (Trichophyton rubrum) que suele empezar en el borde libre.",
                    "Calzado cerrado, sudor, piscinas y pie de atleta favorecen."]),
  ("Adolescente deportista", ["Coloración blanquecina difusa y engrosamiento.", "Separación distal del lecho en ambos primeros dedos."]),
  ["Confirmar antes de tratar: KOH y cultivo de la uña.",
   "Terbinafina oral 250 mg/día por 12 semanas (pies); en compromiso leve, laca de ciclopirox o efinaconazol.",
   "Tratar el pie de atleta, secar bien los pies y no compartir calzado."],
  "AAD, onicomicosis (2024); BAD (2014).",
  op=("¿Diagnóstico?", ["No: líneas o manchas blancas, no engrosamiento", "Da hoyuelos y mancha de aceite, más en manos", "Sí: blanca, gruesa y despegada en deportista",
                        "No: una uña, sin engrosamiento progresivo", "No: inflamación del pliegue"]),
  d=dict(rotulo="Uñas alteradas: ¿qué es?", alto_img=130,
         celdas=[("Onicomicosis", ["Gruesa, amarillo-blanquecina, se despega", "KOH y cultivo"], P("onicomicosis.jpg", 400, 317), True),
                 ("Psoriasis ungueal", ["Hoyuelos (pitting), mancha de aceite", "Placas en piel y codos"], PA("una_psor.jpg", 400), False),
                 ("Paroniquia", ["Pliegue rojo, doloroso, con pus", "Aguda, bacteriana"], PA("paroniquia.jpg", 300), False),
                 ("Traumatismo", ["Hematoma o uña que cae", "Antecedente claro"], None, False)],
         credito="J. Heilman, MD (CC BY-SA 3.0), Seenms (CC BY-SA 3.0), D. M. Al Aboud (CC BY 4.0) · Wikimedia Commons",
         veredicto=("Uña gruesa, blanquecina y despegada en un deportista = onicomicosis", "Confirmar con KOH y terbinafina oral.")))

# OFT-034 · Retinoblastoma · LECTURA (leucocoria)
S("lectura", "OFT-034", "Niño de 2 años con desviación del ojo derecho hacia adentro y ausencia del reflejo rojo pupilar: retinoblastoma",
  "Oncología pediátrica · retinoblastoma",
  ("Retinoblastoma", ["El tumor maligno del ojo más frecuente en niños (casi siempre < 5 años); gen RB1.",
                      "Signos: leucocoria (pupila blanca en las fotos con flash) y estrabismo."]),
  ("Niño de 2 años", ["Inflamación periorbitaria y desviación convergente del ojo derecho.", "Reflejo pupilar derecho irregular y ausente."]),
  ["Prueba del reflejo rojo en todo control del niño: si falta o es blanco, referir a oftalmología urgente.",
   "Fondo de ojo bajo anestesia, ecografía y RM (no TC: radiación y riesgo de segundos tumores).",
   "Tratamiento: quimioterapia, láser, crioterapia o enucleación; estudiar a hermanos (hereditario)."],
  "AAP, reflejo rojo (2023); " + NELSON + ".",
  op=("¿Diagnóstico?", ["No: tras cirugía o trauma, dolor", "Puede dar leucocoria, pero es raro y congénito", "Da reflejo blanco, pero sin estrabismo ni inflamación típica",
                        "Sí: leucocoria + estrabismo en < 5 años", "No: ojo rojo con secreción"]),
  d=dict(rotulo="Mira el reflejo en este orden", img_titulo="Leucocoria en una foto con flash",
         img=P("leucocoria.jpg", 400, 112, credito="J. Morley-Smith" + CC + "dominio público"), pines=[(0.81, 0.55)],
         pasos=[("Pupila blanca (leucocoria)", "El tumor refleja la luz en vez del fondo rojo.", True),
                ("El otro ojo: reflejo rojo", "Normal: la luz rebota en la retina.", False),
                ("Estrabismo", "El ojo que no ve se desvía (aquí hacia adentro).", False),
                ("Referir urgente", "Oftalmología pediátrica; RM, no TC.", False)],
         img_pie="Foto de otro niño (solo los ojos).",
         veredicto=("Leucocoria + estrabismo en un niño de 2 años = retinoblastoma", "Referencia urgente.")))

# SP-120 · Brote de dengue · TRANSMISIÓN + Aedes
S("transmision", "SP-120", "Para que se produzca un brote de dengue se necesitan susceptibles, una persona enferma (con virus en la sangre) y el mosquito Aedes aegypti",
  "Enfermedades metaxénicas · dengue",
  ("Cadena del dengue", ["El Aedes aegypti pica a un enfermo en fase de viremia, el virus se multiplica en el mosquito (8-12 días)",
                         "y luego lo transmite a personas susceptibles. Sin cualquiera de los tres no hay brote."]),
  ("Pregunta de teoría", ["¿Qué se necesita para un brote de dengue?", ""]),
  ["Control vectorial: eliminar criaderos (recipientes con agua), larvicida, fumigación en brotes.",
   "Mosquiteros y repelente para que el enfermo no infecte más mosquitos.",
   "Vacuna (TAK-003) en grupos y zonas priorizadas según la norma vigente."],
  MINSA + ", NTS de vigilancia y control del dengue; OPS (2024).",
  op=("¿Qué se requiere?", ["Sí: los tres eslabones", "No: sin mosquito no hay brote", "Le falta el mosquito", "Le falta el enfermo", "No"]),
  d=dict(rotulo="La cadena del dengue y dónde se corta",
         eslabones=[("Enfermo", "Persona con virus en la sangre", "Mosquitero y repelente", True),
                    ("Vector", "Aedes aegypti hembra", "Eliminar criaderos, larvicida", True),
                    ("Periodo extrínseco", "8-12 días en el mosquito", "Fumigar en brotes", False),
                    ("Susceptible", "Personas sin inmunidad al serotipo", "Vacuna, protección", True)],
         img=B("El vector", P("aedes.jpg", 340, 258, [], credito="John Ragai" + CC + "CC BY 2.0"),
               [("Patas con rayas blancas", "Aedes aegypti."), ("Pica de día", "Sobre todo al amanecer y al atardecer."),
                ("Cría en agua limpia", "Baldes, llantas, floreros.")], pie="Foto de un mosquito."),
         veredicto=("Susceptibles + enfermo + mosquito = brote", "Cortar cualquiera de los tres detiene la transmisión.")))

# PED-154 · RN de muy bajo peso: insuficiencia respiratoria · RELOJ de complicaciones
S("reloj", "PED-154", "La complicación inmediata más frecuente del recién nacido de muy bajo peso es la insuficiencia respiratoria (falta de surfactante)",
  "Neonatología · prematuro de muy bajo peso",
  ("Recién nacido de muy bajo peso (< 1500 g)", ["Complicaciones por inmadurez, que aparecen en momentos distintos.",
                                                "En las primeras horas: dificultad respiratoria (membrana hialina), hipotermia, hipoglucemia."]),
  ("Pregunta de teoría", ["¿Cuál es la complicación INMEDIATA", "más frecuente?"]),
  ["Prevención: corticoides prenatales, CPAP temprano y surfactante.",
   "Primeros días: hemorragia intraventricular, ductus, sepsis; semanas: enterocolitis necrosante.",
   "Más tarde: retinopatía (desde las 31 semanas corregidas) y displasia broncopulmonar."],
  "Consenso europeo de distrés respiratorio (2022); " + NELSON + ".",
  op=("¿Complicación inmediata?", ["No: tardía", "No: semanas después", "Sí: horas tras nacer", "No: más tarde", "No: semanas después (repite)"]),
  d=dict(rotulo="Cuándo aparece cada complicación del prematuro",
         pasos=[("Horas", "Insuficiencia respiratoria", "Membrana hialina", True), ("Días", "Hemorragia ventricular", "Ductus, sepsis", False),
                ("2-3 s", "Enterocolitis", "Al alimentar", False), ("31 s", "Retinopatía", "Tamizaje", False), ("36 s", "Displasia", "Broncopulmonar", False)],
         veredicto=("La primera y más frecuente: insuficiencia respiratoria", "CPAP y surfactante. (31 s y 36 s = semanas de edad corregida.)")))

# PED-155 · Sepsis neonatal precoz: hemocultivo · CRITERIOS de riesgo
S("checklist", "PED-155", "Recién nacido de 5 horas con RPM de 18 horas, fiebre de 38 °C y succión débil: sospecha de sepsis precoz, el examen que confirma es el hemocultivo",
  "Neonatología · sepsis precoz",
  ("Sepsis neonatal precoz", ["En las primeras 72 horas, por gérmenes del canal del parto (estreptococo del grupo B, E. coli).",
                              "Factores: RPM ≥ 18 h, fiebre materna, corioamnionitis, prematuridad, colonización por EGB."]),
  ("RN de 39 semanas, 5 horas", ["RPM de 18 h; parto eutócico; Apgar 8.", "T 38 °C, succión débil."]),
  ["Hemocultivo antes del antibiótico (el único que confirma); hemograma y PCR solo apoyan.",
   "Ampicilina + gentamicina EV; punción lumbar si el hemocultivo es positivo o está grave.",
   "Suspender a las 36-48 h si el cultivo es negativo y el niño está bien."],
  AAP + ", sepsis bacteriana precoz (2019); " + MINSA + ".",
  op=("¿Examen?", ["Apoya; no confirma", "Sí: confirma la infección", "Apoya; no confirma", "Apoya; no confirma", "No: no es infeccioso"]),
  d=dict(rotulo="Sospecha de sepsis precoz: qué hacer", tag="CONFIRMA",
         pasos=[("Hemocultivo", "Antes del antibiótico", True), ("Hemograma y PCR", "Apoyan; se repiten a las 24 h", False),
                ("Ampicilina + gentamicina EV", "Empírico", False), ("Punción lumbar", "Si hemocultivo (+) o grave", False)],
         no_hacer=[("Esperar los resultados para dar antibiótico", "Retrasar aumenta la mortalidad"), ("Confiar en la PCR normal", "Puede tardar en subir")],
         veredicto=("El hemocultivo confirma la sepsis neonatal", "Antibiótico empírico en cuanto se toma.")),
  triada=TR([("RPM ≥ 18 horas", "18 horas", True), ("Fiebre del RN", "38 °C", True), ("Succión débil", "Sí", True)],
            [("Factor de riesgo + signos", 0, 2)], "Riesgo + signos clínicos: tratar como sepsis.", rotulo="Datos del caso"))

# TRA-034 · Fractura de cadera · ÁRBOL + Garden + dibujo
S("arbol", "TRA-034", "Anciana diabética que se cae con dolor intenso, no puede mover la pierna y la tiene acortada y en rotación externa: fractura de cadera",
  "Fracturas del adulto mayor · cadera",
  ("Fractura de cadera", ["Cuello femoral o intertrocantérica tras una caída de baja energía en hueso osteoporótico.",
                          "Signo clásico: miembro acortado y en rotación externa; no puede levantar la pierna."]),
  ("Mujer de 85 años, diabética", ["Caída con dolor intenso e incapacidad de mover la pierna derecha.", "Miembro inferior derecho acortado y en rotación externa."]),
  ["Rx AP de pelvis y lateral de cadera; si es negativa y la sospecha es alta, RM o TC.",
   "Analgesia (bloqueo de la fascia ilíaca) y cirugía en las primeras 24-48 h.",
   "Cuello desplazado (Garden III-IV) en anciano: prótesis; intertrocantérica: clavo endomedular."],
  "AAOS, fracturas de cadera en el adulto mayor (2021); NICE (2023).",
  op=("¿Diagnóstico?", ["La luxación posterior da acortamiento y rotación INTERNA", "Sí: acortamiento + rotación externa tras caída", "No: dolor en la pierna, no en la cadera",
                        "No: deformidad en el tobillo", "No: puede caminar"]),
  arbol=Q("Caída en anciano con dolor de cadera: ¿cómo está la pierna?", [
      L("Acortada + rotación EXTERNA (este caso)", "FRACTURA DE CADERA", ["Rx de pelvis", "Cirugía < 48 h"], path=True),
      L("Acortada + rotación INTERNA", "Luxación posterior", ["Prótesis o trauma de alta energía"])], path=True),
  escala=dict(nombre="Clasificación de Garden (cuello femoral)", que="Desplazamiento de la fractura; decide fijar o reemplazar.",
              grados=[("I", "Incompleta", ["Impactada en valgo"]), ("II", "Completa sin desplazar", []),
                      ("III", "Completa, desplazada parcial", []), ("IV", "Completa, desplazada total", [])],
              caso=None, porque_titulo="Para ubicar este caso", porque=[("Acortamiento y rotación externa sugieren desplazamiento; falta la Rx", True)],
              conducta="Rx; en la anciana con fractura desplazada se coloca prótesis."),
  banda=B("Cómo queda la pierna", PA("dib_cadera.jpg", 300, [], credito=PROPIO, fondo="#ffffff"),
          [("Más corta", "Los músculos tiran del fragmento hacia arriba."),
           ("Pie girado hacia afuera", "Rotación externa."),
           ("No levanta la pierna", "Ni con ayuda.")],
          pie="Esquema."))

# CIR-090 · Neumotórax a tensión · CUADRÍCULA de choque obstructivo + Rx
S("lectura", "CIR-090", "Politraumatizado con hipotensión, taquipnea, ingurgitación yugular, murmullo abolido y timpanismo en el hemitórax derecho: neumotórax a tensión",
  "Trauma de tórax · neumotórax a tensión",
  ("Neumotórax a tensión", ["El aire entra a la pleura y no sale: empuja el mediastino, dobla las venas cavas y cae el gasto.",
                            "El diagnóstico es CLÍNICO: no esperar la Rx para descomprimir."]),
  ("Varón de 35 años, accidente", ["PA 80/60, FR 35, FC 110, SatO₂ 91 %, Glasgow 15.", "Yugulares ingurgitadas, murmullo muy disminuido y timpanismo derecho."]),
  ["Descompresión con aguja en el 4.º-5.º espacio intercostal, línea axilar media (adulto) — ATLS 11.ª.",
   "Luego tubo de tórax en el mismo espacio.",
   "Diferencia con hemotórax masivo: allí hay matidez y yugulares planas."],
  ATLS + ".",
  op=("¿Diagnóstico?", ["No: matidez y yugulares planas", "Sí: timpanismo + yugulares + hipotensión", "No: sin choque obstructivo",
                        "No: murmullo conservado", "No: sin hipotensión ni yugulares"]),
  d=dict(rotulo="Diagnóstico clínico: no esperar la Rx", img_titulo="Así se vería en la Rx (no se pide)",
         img=P("rx_neumotorax_grande.jpg", 300, 300, credito="James Heilman" + CC + "CC BY 3.0"), pines=[(0.25, 0.3)],
         pasos=[("Hipotensión + yugulares ingurgitadas", "Choque obstructivo.", False),
                ("Timpanismo y murmullo abolido", "Aire a tensión en ese lado.", False),
                ("Descomprimir YA", "Aguja 4.º-5.º EIC, línea axilar media; luego tubo.", True),
                ("La Rx viene después", "Zona negra sin trama y mediastino desviado.", False)],
         img_pie="Rx de otro paciente.",
         veredicto=("Neumotórax a tensión derecho: descompresión inmediata", "El diagnóstico es clínico.")))

# CIR-091 · Choque hemorrágico: sangre O negativo · TERMÓMETRO (ATLS)
S("termometro", "CIR-091", "Politraumatizado en choque que no responde a cristaloides, con abdomen que se distiende, hipotensión y bradicardia: transfundir de inmediato sangre O Rh negativo",
  "Trauma · choque hemorrágico",
  ("Choque hemorrágico", ["Si no mejora con 1 L de cristaloide, sangra activamente: necesita sangre y cirugía.",
                          "Si no hay tiempo para pruebas cruzadas: O negativo (mujeres en edad fértil) u O positivo (varones)."]),
  ("Varón de 34 años, accidente", ["PA 80/50, FC 127, palidez, pulso filiforme, abdomen que se distiende y duele.", "No mejora con cristaloides; luego hipotensión marcada y bradicardia."]),
  ["Activar transfusión masiva 1:1:1 (glóbulos, plasma, plaquetas) + ácido tranexámico en < 3 h.",
   "Laparotomía de control de daños; no dar más cristaloide (empeora la coagulopatía).",
   "Bradicardia en el choque = paro inminente."],
  ATLS + "; " + "Guía europea de hemorragia en trauma (2023).",
  op=("¿Medida inmediata?", ["Sí: sangre sin esperar", "Tarda (10-15 min), se usa después", "No: no transporta oxígeno", "No: no transporta oxígeno", "No: primero volumen y control del sangrado"]),
  d=dict(rotulo="Clases de choque hemorrágico (ATLS)", caso_nivel=3, ruta_titulo="Qué hacer", paso_label="ESTE CASO",
         niveles=[("Clase I", "< 15 %", ["Signos normales"]), ("Clase II", "15-30 %", ["Taquicardia"]),
                  ("Clase III", "31-40 %", ["Hipotensión"]), ("Clase IV", "> 40 %", ["PA muy baja, bradicardia"])],
         pasos=[(1, "Sangre O sin cruzar", ["Ya"], True), (2, "Transfusión masiva 1:1:1", ["+ ácido tranexámico"], False),
                (3, "Laparotomía", ["Control de daños"], False)]))

# CAR-057 · FV: desfibrilar y seguir la RCP · RELOJ + ECG
S("reloj", "CAR-057", "Durante la RCP el monitor muestra fibrilación ventricular: desfibrilar de inmediato y reanudar las compresiones sin esperar",
  "Paro cardíaco · ritmos desfibrilables",
  ("Fibrilación ventricular", ["Ritmo caótico sin pulso: el corazón tiembla y no bombea.",
                               "Lo único que la revierte es la descarga eléctrica; cada minuto sin descarga baja la supervivencia."]),
  ("RCP en curso", ["Monitor: fibrilación ventricular.", "¿Qué procedimiento sigue?"]),
  ["Descarga (bifásico 120-200 J) y reanudar compresiones de inmediato por 2 minutos, sin revisar el pulso.",
   "Adrenalina 1 mg cada 3-5 min después de la 2.ª descarga; amiodarona 300 mg tras la 3.ª.",
   "Cardioversión sincronizada: solo con pulso (taquicardias inestables)."],
  AHA + ".",
  op=("¿Procedimiento?", ["Sí: descarga y seguir con RCP", "No: esperar sin descargar", "No: falta la descarga", "No: después de las descargas", "No: es para ritmos con pulso"],
      {1: "Masaje y esperar el monitor", 2: "Masaje y lidocaína"}),
  d=dict(rotulo="Ciclo del ritmo desfibrilable",
         pasos=[("0'", "Descarga", "120-200 J bifásico", True), ("0'", "RCP 2 min", "Sin revisar pulso", False),
                ("2'", "Ver ritmo", "¿Sigue FV? otra descarga", False), ("4'", "Adrenalina", "1 mg cada 3-5 min", False), ("6'", "Amiodarona", "300 mg tras la 3.ª", False)],
         tag="AHORA",
         veredicto=("FV: desfibrilar y seguir la RCP", "La cardioversión sincronizada es para ritmos con pulso.")),
  banda=B("Así se ve la FV", P("ecg_fv.jpg", 380, 182, [], credito=ECG_PROPIO, fondo="#ffffff"),
          [("Ondas caóticas", "Sin QRS ni ondas P."),
           ("Sin pulso", "No hay gasto cardíaco."),
           ("Desfibrilable", "Igual que la TV sin pulso.")],
          pie="Trazado de enseñanza."))

# GIN-155 · Incompetencia cervical · COMPARADOR (eco cervical normal vs corto)
S("cuadricula", "GIN-155", "Gestante de 18 semanas con pesadez pélvica, sin contracciones, con antecedentes de partos inmaduros tras RPM y cuello dilatado 5 cm: incompetencia cervical",
  "Pérdida gestacional del segundo trimestre",
  ("Incompetencia (insuficiencia) cervical", ["El cuello se abre sin dolor ni contracciones en el segundo trimestre.",
                                              "Antecedente típico: pérdidas del segundo trimestre o partos muy prematuros indoloros."]),
  ("Gestante de 18 semanas", ["Pesadez en el hipogastrio, sin contracciones ni pérdida de líquido.", "Partos inmaduros a las 27 y 25 semanas; dilatación 5 cm, borramiento 60 %."]),
  ["Por antecedente: cerclaje programado a las 12-14 semanas en el próximo embarazo.",
   "Cuello < 25 mm antes de las 24 semanas con antecedente: cerclaje; sin antecedente: progesterona vaginal.",
   "Cerclaje de rescate con dilatación avanzada: solo si no hay infección ni contracciones (aquí, con 5 cm, riesgo alto)."],
  ACOG + ", cerclaje (2014; reafirmado 2024); FIGO (2021); " + WILLIAMS + ".",
  op=("¿Diagnóstico?", ["Pierde por otro mecanismo", "No: no hay contracciones", "Pierde por otro mecanismo", "Sí: dilatación indolora + antecedente", "No: habría sangrado o dolor"]),
  d=dict(rotulo="Así se mide el cuello en la eco transvaginal", alto_img=150,
         celdas=[("Cuello normal", ["Largo ≥ 25 mm, cerrado", "Forma de «T»"], P("cervix_normal_eco.jpg", 400, 279), False),
                 ("Cuello corto con embudo", ["< 25 mm, se abre por dentro", "Forma de «Y» (este caso, avanzado)"], P("cervix_corto_eco.jpg", 400, 283), True),
                 ("Antecedente típico", ["Pérdidas del segundo trimestre", "Sin dolor ni contracciones"], None, True),
                 ("Tratamiento", ["Cerclaje (antecedente o cuello corto)", "Progesterona vaginal"], None, False)],
         credito=PMC_CERVIX + " · rótulos del autor borrados",
         veredicto=("Dilatación indolora en el 2.º trimestre + antecedente = incompetencia cervical", "Cerclaje en el próximo embarazo (o de rescate si no hay infección).")))
