"""Fuentes para los flujogramas de Ciencias Básicas."""
GOODMAN = "Goodman & Gilman. Bases farmacológicas de la terapéutica 14.ª ed. (2023)"
KATZUNG = "Katzung. Farmacología básica y clínica 16.ª ed. (2024)"
GUYTON = "Guyton y Hall. Tratado de fisiología médica 14.ª ed. (2021)"
MOORE = "Moore. Anatomía con orientación clínica 9.ª ed. (2023)"
LATARJET = "Latarjet. Anatomía humana 5.ª ed. (2019)"
LANGMAN = "Langman. Embriología médica 15.ª ed. (2023)"
ROSS = "Ross. Histología: texto y atlas 8.ª ed. (2020)"
HARPER = "Harper. Bioquímica ilustrada 32.ª ed. (2023)"
ROBBINS = "Robbins y Cotran. Patología estructural y funcional 10.ª ed. (2021)"
MURRAY = "Murray. Microbiología médica 9.ª ed. (2021)"
ABBAS = "Abbas. Inmunología celular y molecular 10.ª ed. (2022)"
BOTERO = "Botero. Parasitosis humanas 6.ª ed. (2019)"
HARRISON = "Harrison. Principios de Medicina Interna 22.ª ed. (2025)"
SANFORD = "Guía Sanford de terapéutica antimicrobiana (2024)"
MINSA_TB = "MINSA – NTS 200 de atención integral de la TB (2023)"
TOXI = "Goldfrank's Toxicologic Emergencies 11.ª ed. (2019)"
