"""Leyendas de imagen: solo la descripción (sin «de otro paciente», «Esquema.», etc.). La fuente (crédito) no se toca."""
import re, glob
M = {
 "CIR-077": [("Esquema.", "Hemorroides internas: grados I a IV")],
 "GAS-049": [("Foto de otro paciente con cirrosis.", "Cirrosis con ascitis")],
 "PED-142": [("Fondo de ojo de otro prematuro.", "Retina tratada con láser")],
 "CIR-079": [("Esquema.", "Regla de los 9 del adulto")],
 "INF-070": [("Foto de otra mordedura de perro; abajo, esquema.", "Mordedura de perro y calendario de vacunación")],
 "CB-051": [("Foto de otra persona (solo los ojos).", "Midriasis")],
 "SP-101": [("Esquema.", "Tipos de muestreo")],
 "TRA-028": [("Rx de otro paciente con fractura por compresión de L4.", "Fractura en cuña de L4"), ("DXA de otra paciente de 70 años.", "DXA de columna lumbar")],
 "CIR-080": [("Imagen de otra paciente con abscesos pericólicos (Hinchey Ib).", "Abscesos pericólicos (Hinchey Ib)")],
 "CIR-081": [("Rx de otro paciente con aire libre bajo el diafragma derecho.", "Aire libre bajo el diafragma derecho")],
 "TRA-029": [("Rx de otro paciente con gonartrosis.", "Gonartrosis")],
 "NEF-062": [("Esquema.", "Tacto rectal")],
 "INF-072": [("Foto de otro paciente.", "Úlcera de leishmaniasis cutánea")],
 "CAR-052": [("Rx de otro paciente.", "Edema agudo de pulmón")],
 "NEF-063": [("Angio-TC de otro paciente.", "Tromboembolia pulmonar en la angio-TC")],
 "TRA-030": [("Esquema.", "Territorios sensitivos de la mano")],
 "SP-104": [("Esquema.", "Tasa de ataque del brote")],
 "END-041": [("Foto de la axila de otro paciente.", "Acantosis nigricans en la axila")],
 "CIR-082": [("Rx de otro paciente con íleo adinámico.", "Íleo adinámico")],
 "GAS-052": [("TC de otro paciente.", "Cáncer de cabeza de páncreas")],
 "INF-074": [("Imágenes de otra infección herpética (zóster).", "Herpes zóster y células de Tzanck")],
 "GAS-053": [("Esquema.", "Derrame pleural")],
 "NEU-039": [("Rx de otro paciente.", "Tuberculosis cavitaria")],
 "GIN-143": [("Esquema (no es un trazado real).", "Cardiotocografía")],
 "HEM-028": [("Foto de otro paciente.", "Petequias")],
 "CIR-085": [("Esquema.", "Hernias de la pared abdominal")],
 "SP-106": [("Foto de otro paciente (solo el ojo).", "Sufusión conjuntival")],
 "REU-041": [("Foto de otro niño.", "Impétigo con costras melicéricas")],
 "NRL-041": [("TC de otro paciente con hematoma epidural derecho.", "Hematoma epidural derecho")],
 "CIR-086": [("Esquema.", "Colecistitis aguda")],
 "TRA-031": [("Rx de otro paciente.", "Fractura de húmero")],
 "NEF-066": [("Izquierda: esquema; derecha: Doppler de otro paciente.", "Torsión testicular y Doppler sin flujo")],
 "GAS-054": [("Colangiorresonancia de otro paciente.", "Coledocolitiasis")],
 "REU-043": [("Foto de otra persona.", "Urticaria")],
 "PED-145": [("Eco de otro lactante con estenosis pilórica.", "Estenosis pilórica")],
 "PED-146": [("Rx de otro recién nacido.", "Atresia de esófago")],
 "HEM-029": [("Frotis de otro paciente.", "Esquistocitos")],
 "INF-078": [("Tinta china de otra muestra.", "Criptococo con tinta china")],
 "TRA-033": [("Foto de demostración.", "Collarín cervical")],
 "REU-044": [("Rx de otro paciente.", "Sacroileítis bilateral")],
 "SP-111": [("Esquema.", "Bocio por déficit de yodo")],
 "CB-055": [("Foto de archivo (solo la boca).", "Encías del escorbuto")],
 "SP-112": [("Esquema.", "Variable independiente y dependiente")],
 "SP-113": [("Esquema.", "Diagramas de dispersión")],
 "HEM-030": [("Frotis de otro paciente.", "Microcitosis e hipocromía")],
 "GIN-151": [("Dispositivo real.", "DIU de cobre")],
 "CB-057": [("Esquema rotulado en español.", "Botón gustativo")],
 "NRL-042": [("Esquema.", "Placa neuromuscular")],
 "CIR-088": [("Esquema.", "Hernia crural")],
 "CAR-054": [("Esquema.", "Coartación de aorta")],
 "HEM-031": [("Foto de otro paciente.", "Trombosis venosa profunda")],
 "NEU-042": [("Angio-TC de otro paciente.", "Tromboembolia pulmonar en la angio-TC")],
 "NEU-043": [("Rx de otro paciente.", "Neumotórax derecho grande")],
 "INF-081": [("Foto de otro paciente (solo el ojo).", "Sufusión conjuntival")],
 "INF-082": [("Foto de otro paciente y del insecto.", "Signo de Romaña y triatoma")],
 "SP-116": [("Fotos de otros pacientes.", "Exantema del sarampión")],
 "REU-045": [("Foto de otro paciente.", "Escabiosis")],
 "REU-046": [("Foto de la mano de otro lactante.", "Piel escaldada estafilocócica")],
 "OFT-034": [("Foto de otro niño (solo los ojos).", "Leucocoria")],
 "SP-120": [("Foto de un mosquito.", "Aedes aegypti")],
 "TRA-034": [("Esquema.", "Pierna acortada y en rotación externa")],
 "CIR-090": [("Rx de otro paciente.", "Neumotórax")],
 "CAR-057": [("Trazado de enseñanza.", "Fibrilación ventricular")],
 "GIN-158": [("Esquema.", "Fórmula obstétrica")],
 "REU-048": [("Gram de otra muestra (secreción uretral).", "Diplococos gramnegativos intracelulares")],
 "END-046": [("Foto de otra persona (solo los ojos).", "Oftalmopatía de Graves")],
 "NRL-044": [("Dibujo de los lóbulos.", "Lóbulos cerebrales")],
 "REU-050": [("Fotos de otros pacientes.", "Psoriasis en placa y ungueal")],
 "PED-156": [("Foto de otro niño.", "Petequias en el paladar")],
 "REU-051": [("Foto de otra persona.", "Urticaria")],
 "REU-052": [("Foto de otro niño.", "Impétigo")],
 "OFT-035": [("Foto de otro paciente.", "Absceso periamigdalino")],
 "CIR-092": [("Esquema.", "Regla de los 9 del adulto")],
 "GAS-056": [("Foto de otra persona (solo los ojos).", "Ictericia")],
 "CB-060": [("TC de otra paciente.", "Neumonía por COVID-19 en la TC")],
 "NEF-069": [("Esquema.", "Criptorquidia")],
 "PED-157": [("Esquema (corte de lado; adelante a la izquierda).", "Malformación anorrectal (corte lateral)")],
 "CIR-093": [("Foto de otra persona.", "Gangrena seca")],
 "OFT-036": [("Foto de otra persona (solo el ojo).", "Conjuntivitis con secreción")],
 "CIR-094": [("Esquema y ecografía de otra persona.", "Torsión testicular")],
 "CIR-095": [("Rx de otra persona (otra causa de perforación).", "Neumoperitoneo")],
 "GAS-058": [("TC de otra persona.", "Metástasis hepáticas")],
 "CAR-058": [("Trazado de enseñanza.", "Infarto anterolateral")],
 "INF-083": [("Biopsia de otro paciente.", "Hifas de mucormicosis")],
 "CAR-059": [("Rx de otra persona.", "Congestión pulmonar")],
 "PED-163": [("Esquema en español.", "Persistencia del conducto arterioso")],
 "END-049": [("Foto de otra persona (solo los ojos).", "Oftalmopatía de Graves")],
 "GAS-059": [("TC de otra persona.", "Cáncer de páncreas")],
 "PED-165": [("Heces de otro paciente (cólera).", "Heces en agua de arroz")],
 "NEF-070": [("Esquema (derecha del paciente = izquierda del dibujo).", "Masa testicular")],
 "NEF-071": [("Fotos de otras personas.", "Impétigo y cilindro hemático")],
 "TRA-036": [("Foto de un collarín.", "Collarín cervical")],
 "CAR-060": [("Trazado de enseñanza.", "Fibrilación ventricular")],
 "NEU-048": [("Foto de otra persona.", "Podagra")],
 "NEU-049": [("Esquema.", "Derrame pleural")],
 "NEU-051": [("Rx de otra persona.", "Neumonía")],
 "NEF-072": [("TC de otra persona.", "Hidronefrosis")],
 "REU-053": [("Foto de otra persona.", "Liendres")],
 "PED-173": [("Foto de otra persona (solo la boca).", "Petequias en el paladar")],
 "HEM-034": [("Frotis de otro paciente.", "Esquistocitos")],
 "PED-176": [("Esquema.", "Tipos de atresia de esófago")],
 "TRA-037": [("Foto de un fijador.", "Fijador externo")],
 "TRA-038": [("Ilustración anatómica.", "Ligamentos laterales del tobillo")],
 "CIR-097": [("CPRM de otra persona.", "Coledocolitiasis")],
 "GIN-174": [("Ecografía de otra gestante.", "Signo lambda: gemelar bicorial")],
 "GIN-176": [("Muestra de otra persona.", "Cristalización en helecho")],
 "NEU-052": [("ECG de otra persona.", "ECG en la tromboembolia pulmonar")],
 "CB-066": [("Esquema.", "Volúmenes y capacidades pulmonares")],
 "SP-131": [("Foto de un mosquito.", "Aedes aegypti")],
 "NEF-073": [("Esquema (derecha del paciente = izquierda del dibujo).", "Testículo y cordón espermático")],
 "GIN-181": [("Foto de un DIU.", "DIU de cobre")],
 "REU-054": [("Placas con escama plateada; uñas con piqueteado (otras personas).", "Placas con escama plateada y uñas con piqueteado")],
 "PED-177": [("Ecografía de otro niño.", "Invaginación intestinal")],
 "PED-178": [("Foto de otra persona (solo el ojo).", "Mancha de Bitot")],
 "NEF-074": [("Trazado de enseñanza.", "Hipopotasemia en el ECG")],
 "TRA-040": [("Esquema: cadera izquierda luxada.", "Cadera izquierda luxada")],
 "GIN-184": [("Ilustración.", "Placenta previa")],
 "INF-089": [("Foto de otra persona (solo el ojo).", "Sufusión conjuntival")],
 "REU-055": [("Esquema.", "Tinción de Gram")],
 "CIR-099": [("Esquema (derecha del paciente = izquierda del dibujo).", "Bazo en el hipocondrio izquierdo")],
 "TRA-042": [("Rx de otra persona.", "Fractura de escafoides")],
 "GAS-064": [("TC de otra persona.", "Pancreatitis aguda")],
 "CIR-101": [("Esquema (derecha del paciente = izquierda del dibujo).", "Páncreas delante de la columna")],
 "CIR-102": [("Ecografía de otra persona.", "Apendicitis aguda")],
 "PED-183": [("Ecografía de otro niño.", "Invaginación intestinal")],
 "REU-056": [("Líquido de otro paciente.", "Cristales de urato con luz polarizada")],
 "PED-186": [("Rx de otro recién nacido.", "Neumatosis intestinal")],
 "NEF-076": [("Histología de otro paciente.", "Depósitos de amiloide")],
 "OFT-043": [("Otoscopia de otra persona.", "Tímpano abombado")],
 "NEF-077": [("Cilindro hemático (otro paciente)", "Cilindro hemático")],
 "HEM-036": [("Frotis de otro paciente.", "Drepanocitos")],
 "OFT-044": [("Esquema.", "Tapón de cerumen")],
 "HEM-037": [("Frotis de otro paciente.", "Neutrófilo hipersegmentado")],
 "GAS-065": [("Foto de otra persona.", "Ascitis")],
 "CIR-105": [("Esquema.", "Regla de los 9 del adulto")],
 "REU-057": [("Piel de otra persona.", "Comedones")],
 "REU-058": [("Piel de otra persona.", "Surco acarino")],
 "PED-193": [("Microscopía.", "Trofozoítos de Giardia")],
 "NEF-080": [("ECG de otro paciente.", "Ondas T picudas")],
 "CIR-106": [("Rx de otra persona.", "Niveles hidroaéreos por bridas")],
 "GAS-066": [("Colonoscopía de otra persona.", "Cáncer de colon")],
 "GIN-205": [("Ilustración/pieza de otro caso.", "Embarazo ectópico tubárico")],
 "NEF-081": [("Trazado de enseñanza.", "Hipermagnesemia en el ECG")],
 "GIN-206": [("Foto de un DIU.", "DIU de cobre")],
 "REU-059": [("Piel de otra persona (tórax).", "Pitiriasis versicolor")],
 "CAR-066": [("Trazados de enseñanza.", "Ritmo organizado y asistolia")],
 "PED-201": [("Ecografía de otra persona.", "Apendicitis aguda")],
 "NEF-083": [("Trazado de enseñanza.", "Hipopotasemia en el ECG")],
 "OFT-049": [("Esquema.", "Lavado ocular con suero")],
 "CIR-112": [("Hemoneumotórax traumático (PubMed Central).", "Hemoneumotórax traumático"),
             ('("Otra paciente", "Mismo tratamiento.")', '("Tubo de 28-32 Fr", "5.º espacio, línea axilar media.")')],
 "TRA-046": [("Luxación anterior (otra persona)", "Luxación anterior de hombro")],
 "NRL-053": [("Esquema.", "Decorticación y descerebración")],
 "OFT-042": [("Trauma ocular (otro caso)", "Trauma ocular")],
 "CAR-056": [("Otro fenómeno vascular (embolias sépticas en la planta).", "Embolias sépticas en la planta")],
}
files = {f: open(f).read() for f in sorted(glob.glob("content30[a-t].py"))}
n = 0
for i, reps in M.items():
    f = [f for f, s in files.items() if re.search(r'^S\("[a-z_]+", "%s"' % i, s, re.M)]
    assert len(f) == 1, i
    s = files[f[0]]
    a = re.search(r'^S\("[a-z_]+", "%s"' % i, s, re.M).start()
    m = re.compile(r'^(# |S\()', re.M).search(s, a + 5)
    b = m.start() if m else len(s)
    blk = s[a:b]
    for old, new in reps:
        q = old if old.startswith("(") else f'"{old}"'
        assert q in blk, (i, old)
        blk = blk.replace(q, new if old.startswith("(") else f'"{new}"', 1)
        n += 1
    files[f[0]] = s[:a] + blk + s[b:]
for f, s in files.items():
    open(f, "w").write(s)
print("reemplazos", n)
