CB,CA,CI,EN,GA,GI,HE,IN,NE,NR,NL,OF,PE,PS,RE,SP,TR="ciencias_basicas","cardiologia","cirugia","endocrinologia","gastroenterologia","ginecologia","hematologia","infectologia","nefrologia","neumologia","neurologia","oftalmo_orl","pediatria","psiquiatria","reumatologia","salud_publica","traumatologia"
SEL=[
(576,CB,"Shock hipovolémico: mecanismos compensadores"),(577,RE,"Anafilaxia por picadura de abeja"),(578,NR,"Tromboembolismo pulmonar posoperatorio"),
(579,NE,"Rabdomiólisis por aplastamiento"),(580,CB,"Intoxicación por organofosforados"),(581,NR,"Tuberculosis pleural: ADA"),
(583,CI,"Enfermedad arterial periférica: índice tobillo-brazo"),(585,CA,"Angioedema por IECA"),(588,PE,"Anemia del prematuro"),
(589,PE,"Síndrome nefrótico en el niño"),(591,EN,"Pubertad precoz central: prueba de GnRH"),(595,PE,"Convulsiones neonatales: fenobarbital"),
(596,PE,"Invaginación intestinal"),(606,PE,"Meningitis bacteriana en el lactante"),(609,PE,"Resfrío común en el lactante"),
(610,IN,"Síndrome de Löffler: albendazol"),(613,PE,"Deshidratación moderada"),(614,PE,"Síndrome urémico hemolítico"),
(615,PE,"Laringotraqueítis aguda (crup)"),(617,RE,"Impétigo"),(618,RE,"Tiña capitis"),
(620,HE,"Recuento absoluto de neutrófilos"),(621,CI,"Apendicitis aguda en el adolescente"),(622,CI,"Fístula arteriovenosa traumática"),
(623,CI,"Insuficiencia venosa crónica"),(624,CI,"Hemotórax masivo: toracotomía"),(626,OF,"Fractura del piso de la órbita"),
(628,OF,"Conjuntivitis por adenovirus"),(629,NE,"Cáncer testicular"),(630,NE,"Litiasis urinaria: tomografía helicoidal"),
(634,TR,"Síndrome compartimental agudo"),(635,TR,"Síndrome de embolia grasa"),(638,CI,"Absceso perianal"),
(640,CI,"Prolapso rectal"),(644,OF,"Rinitis alérgica"),(646,OF,"Epistaxis traumática: taponamiento anterior"),
(647,NL,"Tumor cerebral: lesión en anillo"),(649,NL,"Hematoma epidural"),(650,PE,"Hernia diafragmática congénita: clínica"),
(652,SP,"Principio de autonomía: anticoncepción de emergencia"),(654,GI,"Desprendimiento prematuro de placenta con óbito fetal"),(656,GI,"Endometritis puerperal"),
(657,GI,"Corioamnionitis"),(658,GI,"Pielonefritis en el embarazo"),(665,GI,"Embarazo prolongado: inducción del parto"),
(671,GI,"Distocia de hombros: maniobra de McRoberts"),(675,GI,"Sangrado posmenopáusico: biopsia de endometrio"),(678,GI,"Vaginitis mixta"),
(680,GI,"Tumores ováricos en la niña"),(684,PE,"Vacunación tardía: Haemophilus influenzae tipo b"),
(686,CB,"Apoptosis"),(688,CB,"Eficacia farmacológica"),(690,CB,"Miopatía por estatinas"),
(693,CB,"Anatomía laríngea: músculo cricoaritenoideo posterior"),(701,GI,"Clave roja: hemorragia obstétrica"),(703,NR,"Tumor de Pancoast"),
(704,SP,"Determinantes sociales de la salud"),(705,SP,"Estudio de cohortes"),(707,CB,"Intoxicación por gas sarín: atropina"),
(710,SP,"Ética en investigación: Declaración de Helsinki"),(713,PE,"Bronquiolitis"),(716,EN,"Hipercolesterolemia familiar"),
(718,GI,"Tricomoniasis"),(720,CB,"Intoxicación por benzodiacepinas: flumazenil"),(724,HE,"Linfoma: biopsia ganglionar"),
(726,SP,"Estudio experimental"),(731,OF,"Otitis media aguda en el lactante: otoscopía"),(735,NL,"Síndrome de Brown-Séquard"),
(740,PE,"Maltrato infantil: lesiones de distinta antigüedad"),(742,PE,"Sepsis neonatal temprana"),(746,SP,"Gestión en salud: liderazgo"),
(747,SP,"Mordeduras de perro: coordinación intersectorial"),(753,GI,"Atonía uterina"),(757,PE,"Alimentación complementaria y prevención de anemia"),
(758,RE,"Líquido sinovial inflamatorio"),(759,NE,"Síndrome de aplastamiento: CPK"),(761,OF,"Glaucoma agudo de ángulo cerrado"),
(762,GI,"Pielonefritis en el embarazo: profilaxis de recurrencia"),(766,NL,"Ataque isquémico transitorio"),(767,CI,"Politraumatizado con Glasgow 8: vía aérea"),
(769,NR,"Cáncer de pulmón: broncofibroscopía con biopsia"),(772,PS,"Trastorno de adaptación"),(773,PE,"Atresia duodenal en síndrome de Down"),
(778,PE,"Sarampión"),(781,PE,"Intoxicación por insecticidas en el adolescente"),(782,SP,"Análisis de situación de salud: análisis del entorno"),
(784,RE,"Arteritis de células gigantes"),(790,EN,"Hipertiroidismo"),
(798,GI,"Mastitis puerperal"),(800,GI,"Rotura uterina"),(801,SP,"Determinantes sociales y tuberculosis"),
(803,NE,"Litiasis renal: cólico nefrítico"),(804,PE,"Ganancia de peso insuficiente: visita domiciliaria"),(809,CB,"Intoxicación por monóxido de carbono"),
(812,RE,"Acné fulminante"),(813,GA,"Pancreatitis aguda por hipertrigliceridemia"),(814,PE,"Estenosis hipertrófica del píloro"),
(816,PE,"Neumonía adquirida en la comunidad en el niño"),(819,CI,"Taponamiento cardiaco por herida penetrante"),(822,SP,"Autonomía: voluntad anticipada"),
(823,TR,"Fractura de diáfisis humeral: mano péndula"),(826,PS,"Crisis de pánico"),(827,GA,"Insuficiencia pancreática exocrina"),
(830,EN,"Feocromocitoma"),(831,PE,"Convulsión febril compleja"),(832,GI,"Rotura prematura de membranas pretérmino"),
(833,NR,"Hipoxemia en la EPOC: desequilibrio ventilación-perfusión"),(844,PE,"Insuficiencia cardiaca en el lactante"),(847,CI,"Quemadura facial con lesión inhalatoria: intubación"),
(849,CA,"Paro por taquiarritmia sin pulso: desfibrilación"),(850,GA,"Megacolon tóxico"),(855,GI,"Diabetes gestacional: tamizaje"),
(860,GI,"Prevención de la endometritis puerperal"),(863,RE,"Dermatitis atópica: emolientes"),(864,IN,"SARS-CoV-2: receptor ACE2"),
(865,CI,"Taponamiento cardiaco traumático: toracotomía"),(868,CI,"Coledocolitiasis: papilotomía endoscópica"),(871,GI,"Vaginitis atrófica"),
(880,HE,"Leucemia linfoblástica aguda: aspirado de médula ósea"),(881,CI,"Fascitis necrotizante"),(882,GI,"Shock hipovolémico posparto"),
(887,PE,"Tos ferina"),(889,CI,"Vólvulo de sigmoides"),(890,NR,"Enfermedad pulmonar intersticial difusa"),
(894,CA,"Cuidados posparo: ventilación"),(905,CI,"Atelectasia posoperatoria"),(906,IN,"Malaria"),
(907,CI,"Cierre de heridas por tercera intención"),
(913,SP,"Estudio de casos y controles"),(915,NL,"Corea de Sydenham"),(916,HE,"Anemia perniciosa: células parietales"),
(917,GI,"Diabetes gestacional: test de O'Sullivan"),(920,PE,"Fenilcetonuria"),(921,OF,"Epistaxis anterior: compresión digital"),
(931,NL,"Ataque isquémico transitorio en el anciano"),(932,HE,"Leucemia mieloide crónica"),(934,IN,"Enfermedad de Chagas aguda"),
(936,GI,"Aborto terapéutico"),(939,IN,"Malaria por Plasmodium falciparum"),(953,PE,"Síndrome nefrótico: peritonitis primaria"),
(954,GI,"Placenta previa"),(957,GI,"Mutación BRCA1"),(959,PE,"Anemia ferropénica del lactante"),
(960,CI,"Quiste pilonidal"),(961,CB,"Intoxicación por carbamatos"),(964,EN,"Hipertrigliceridemia y pancreatitis"),
(966,GA,"Colangiocarcinoma"),(967,PE,"Bronquiolitis aguda"),(968,PE,"Síndrome de aspiración meconial"),
(969,GA,"Síndrome de Mallory-Weiss"),(970,PE,"Intoxicación por plaguicidas: descontaminación"),(972,GI,"Papanicolaou tras histerectomía total"),
(975,CI,"Hernia crural estrangulada"),(979,NR,"Tromboembolismo pulmonar tras cirugía de cadera"),(982,EN,"Nefropatía diabética: microalbuminuria"),
(983,PE,"Contacto de tuberculosis: terapia preventiva"),(988,SP,"Conflicto de intereses en investigación"),(989,IN,"Meningitis bacteriana: líquido cefalorraquídeo"),
(993,SP,"Promoción de la salud en diabetes: sedentarismo"),(994,IN,"Toxoplasmosis cerebral en VIH"),(995,GI,"Enfermedad inflamatoria pélvica: hospitalización"),
(999,PE,"Insuficiencia cardiaca congestiva en el lactante"),(1001,IN,"Giardiasis"),(1005,PE,"Atresia esofágica"),
(1006,IN,"Recién nacido expuesto al VIH: profilaxis"),(1007,CI,"Hemotórax traumático: toracotomía de urgencia"),(1009,CA,"Endocarditis infecciosa"),
(1012,PE,"Anemia ferropénica: alimentación"),(1013,OF,"Absceso periamigdalino"),
(1015,GA,"Hemorragia digestiva alta en el cirrótico: reanimación"),(1016,TR,"Luxación posterior de cadera"),(1018,NE,"Necrosis tubular aguda"),
(1019,IN,"Sífilis primaria: chancro"),(1020,GA,"Colangitis aguda"),(1028,SP,"Transmisibilidad: variante ómicron"),
(1030,GA,"Pólipos de colon: polipectomía"),(1032,CA,"Hipertensión de bata blanca"),(1033,CA,"Síndrome de vena cava superior"),
(1034,GI,"Endometrioma"),(1035,EN,"Síndrome de Turner: cariotipo"),(1037,PE,"Intoxicación por paracetamol"),
(1038,GI,"Urocultivo con Lactobacillus en gestante"),(1043,RE,"Urticaria colinérgica"),(1044,NL,"TEC moderado: tomografía"),
(1046,NE,"Hipermagnesemia por laxantes"),(1050,GI,"Apendicitis en el embarazo: ecografía"),(1051,SP,"Derecho a la calidad de la atención"),
(1053,CB,"Hipercolesterolemia familiar: receptor de LDL"),(1055,PE,"Estenosis pilórica: alcalosis hipoclorémica"),(1057,CI,"Obstrucción intestinal por bridas"),
(1058,CA,"Taponamiento cardiaco en lupus"),(1060,RE,"Pitiriasis versicolor"),(1061,SP,"No maleficencia en la pandemia"),
(1062,CA,"Contusión miocárdica: ECG seriado"),(1064,TR,"Lesión del manguito rotador"),(1066,GI,"Presentación de cara mentoposterior"),
(1067,GI,"Datación del embarazo por ecografía"),(1068,GA,"Hepatitis viral aguda"),(1070,GI,"Preeclampsia con signos de severidad"),
(1075,IN,"Dengue con signos de alarma: clasificación"),
]
