# Tanda 00 (CAR-001..060): nueva alternativa E para reemplazar rellenos («Faltan datos», «Todas/Ninguna de las anteriores»)
# o alternativas sin relación con el caso. Formato: ID: nuevo texto de la E.
R = {
"CAR-004": "Iniciar ácido acetilsalicílico",
"CAR-005": "Tronco arterioso",
"CAR-006": "Pericarditis aguda",
"CAR-008": "Verapamilo",
"CAR-009": "Adrenalina",
"CAR-011": "Betabloqueadores",
"CAR-013": "Buscar un DEA y recién después iniciar compresiones",
"CAR-014": "Angiotomografía pulmonar",
"CAR-015": "Pericarditis aguda",
"CAR-016": "Hidralazina",
"CAR-017": "Miocarditis viral",
"CAR-018": "Prolapso de válvula mitral",
"CAR-019": "Intubar antes de continuar las compresiones",
"CAR-020": "Furosemida endovenosa",
"CAR-021": "Comunicación interauricular",
"CAR-022": "Taquicardia sinusal",
"CAR-023": "Arritmogénica",
"CAR-024": "Espironolactona",
"CAR-025": "Tos nocturna",
"CAR-026": "Controlar la frecuencia cardiaca",
"CAR-027": "Tiroxina",
"CAR-028": "Amiodarona endovenosa",
"CAR-029": "Aumentar el volumen corriente",
"CAR-030": "Fiebre reumática aguda",
"CAR-031": "Resistente",
"CAR-032": "Insuficiencia cardiaca derecha",
"CAR-033": "Furosemida endovenosa",
"CAR-034": "Gammagrafía de perfusión miocárdica",
"CAR-035": "Iniciar antibiótico sin tomar cultivos",
"CAR-036": "Respiración boca a boca sin masaje",
"CAR-037": "Miocarditis viral",
"CAR-038": "Coartación de aorta",
"CAR-039": "Betabloqueante endovenoso como única medida",
"CAR-040": "Nitroglicerina endovenosa",
"CAR-041": "Valvular reumática",
"CAR-042": "Iniciar 30 compresiones torácicas",
"CAR-044": "Taquicardia supraventricular",
"CAR-045": "Amlodipino",
"CAR-046": "Furosemida",
"CAR-047": "Digoxina",
"CAR-048": "Normal con poscarga baja",
"CAR-049": "Adenosina",
"CAR-050": "Infarto agudo de miocardio",
"CAR-051": "Espironolactona",
"CAR-052": "Crisis asmática",
"CAR-053": "Ácidos grasos omega-3",
"CAR-054": "Feocromocitoma",
"CAR-055": "Agregar un antihistamínico",
"CAR-056": "Hemorragia cerebral hipertensiva",
"CAR-057": "Cardioversión sincronizada",
"CAR-058": "Disección aórtica",
"CAR-059": "Digoxina",
}
