R = {
"CIR-117": "Hemorroidectomía cerrada urgente",
"CIR-118": "Drenaje percutáneo del plastrón",
"CIR-119": "Repetir la ecografía en 24 horas",
"CIR-120": "Las trombosis arteriales agudas",
"CIR-121": "Enfermedad de Crohn",
"CIR-122": "Colocar faja abdominal y alta",
"CIR-123": "Hongos y grampositivos",
"CIR-124": "Hepatorrafia por laparoscopía",
"END-002": "Síndrome del eutiroideo enfermo",
"END-003": "Feocromocitoma",
"END-004": "Insulina en ayunas",
"END-005": "Atorvastatina más fenofibrato",
"END-006": "Yodo radiactivo",
"END-007": "Ansiedad generalizada",
"END-008": "Prueba de tolerancia oral a la glucosa con insulinemia",
"END-009": "Antibióticos de amplio espectro",
"END-010": "Tiroiditis subaguda linfocítica",
"END-011": "Acidosis láctica",
"END-012": "Insulina rápida endovenosa",
"END-013": "Magnesio sérico aislado",
"END-014": "Dosaje de estradiol aislado",
"END-015": "Disbetalipoproteinemia",
"END-016": "Trastorno de ansiedad",
"END-017": "Hipertiroidismo",
"END-018": "Diabetes mellitus",
"END-019": "Glucosa en orina",
"END-020": "Dosaje de prolactina",
"END-021": "Hipotiroidismo central",
"END-022": "Yodo radiactivo durante el embarazo",
"END-023": "Ataque de pánico",
"END-024": "Anticuerpos antitiroideos solamente",
"END-025": "Yodo oral",
"END-026": "Síndrome de Cushing",
"END-027": "Prolactinoma",
"END-028": "Sodio urinario",
"END-029": "Nodular tóxico",
"END-030": "Ejercicio intenso diario sin descanso",
"END-031": "Tiroiditis subaguda",
"END-032": "Adenoma tóxico",
"END-033": "Poliuria, densidad urinaria baja e hiponatremia",
"END-034": "Prolactina",
"END-035": "Tiroiditis supurativa aguda",
"END-036": "Hipotiroidismo",
"END-037": "Estado hiperosmolar",
"END-038": "Pancreatitis aguda",
"END-039": "Octreótido como única medida",
"END-040": "Síndrome de ovario poliquístico",
"END-041": "Enfermedad de Addison",
"END-042": "Creatinina sérica",
"END-043": "Hipoparatiroidismo",
"END-044": "Mantequilla y lácteos enteros",
"END-045": "Insulina rápida subcutánea",
"END-046": "Tiroidectomía inmediata",
"END-047": "Yodo radiactivo",
"END-048": "Aumentar metformina a 3 g/día",
"END-049": "Preeclampsia severa",
"END-050": "Miositis por yodo radiactivo",
"END-051": "Aumento de la excreción renal de bicarbonato",
"END-052": "Insulina rápida",
}
