R = {
"END-053": "Suspender el orlistat y solo vigilar",
"END-054": "Coma hiperosmolar",
"END-055": "Insulina glargina",
"END-056": "Glucosa en ayunas de 180 mg/dl",
"END-057": "Glucosa sérica",
"END-058": "Calcitonina",
"END-059": "Monitorizar el potasio sérico",
"END-060": "B12",
"END-061": "Metformina",
"END-062": "Solución salina hipertónica",
"END-063": "Sitagliptina",
"END-064": "Repetir la glucemia en un año",
"END-065": "Bicarbonato de sodio en bolo",
"END-066": "Bloqueo de la reabsorción de sodio en el asa de Henle",
"END-067": "Hipotiroidismo no tratado",
"END-068": "Aumentar la dosis de tiamazol",
"GAS-002": "Loperamida",
"GAS-003": "Pancreatectomía total",
"GAS-004": "Esofagitis eosinofílica",
"GAS-005": "Gastroscopía con biopsia",
"GAS-006": "Várices esofágicas",
"GAS-007": "Úlcera duodenal sangrante",
"GAS-008": "Hipoglucemia",
"GAS-009": "Linfoma intestinal",
"GAS-010": "Megacolon tóxico",
"GAS-011": "Leucocitos fecales abundantes",
"GAS-012": "IgG anti VHA",
"GAS-013": "Enfermedad de Crohn",
"GAS-014": "Linfoma MALT",
"GAS-015": "Gastroparesia",
"GAS-016": "Escleroterapia con alcohol absoluto",
"GAS-017": "Amilasa",
"GAS-018": "Infarto agudo de miocardio inferior",
"GAS-019": "Respiratoria",
"GAS-020": "Glucosa",
"GAS-021": "Nutrición parenteral total",
"GAS-022": "Síndrome de intestino irritable",
"GAS-023": "Colitis infecciosa por Clostridioides difficile",
"GAS-024": "Hepatitis viral",
"GAS-025": "Várices esofágicas",
"GAS-026": "Lactulosa oral",
"GAS-027": "Hepatitis viral aguda",
"GAS-028": "Hemicolectomía izquierda",
"GAS-029": "Coledocolitiasis",
"GAS-030": "Hipersecreción de pepsinógeno por células principales",
"GAS-031": "Gamma glutamil transferasa",
"GAS-032": "Pancreatitis crónica",
"GAS-033": "Colecistectomía de urgencia",
"GAS-034": "Anticuerpos anti-VHC",
"GAS-035": "Síndrome de Dubin-Johnson",
"GAS-036": "Hemodiálisis",
"GAS-037": "Metronidazol",
"GAS-038": "Hepatitis C aguda",
"GAS-039": "Ecografía endoscópica",
"GAS-040": "Prueba de esfuerzo",
"GAS-041": "Inmediatamente al ingreso",
"GAS-042": "Antibiótico oral ambulatorio",
"GAS-043": "Crónica agudizada",
"GAS-044": "Ligadura y omeprazol en infusión",
}
