R = {
"GAS-045": "Diuréticos a dosis altas",
"GAS-046": "Portador crónico inactivo",
"GAS-047": "Hepatitis viral postransfusional aguda",
"GAS-048": "Lipasa",
"GAS-049": "Insuficiencia cardiaca derecha",
"GAS-050": "Esofagitis por reflujo",
"GAS-051": "Ecografía abdominal",
"GAS-052": "Ca 125",
"GAS-053": "Edema pulmonar cardiogénico por insuficiencia cardiaca",
"GAS-054": "Hepatitis viral aguda",
"GAS-055": "Estenosis péptica benigna únicamente",
"GAS-056": "Hepatitis alcohólica",
"GAS-057": "Neurogénico",
"GAS-058": "Hueso",
"GAS-059": "Colangiocarcinoma hiliar",
"GAS-060": "Aumentar la dosis de enzimas y observar",
"GAS-061": "Ecografía Doppler hepática",
"GAS-062": "Tomografía de tórax",
"GAS-063": "Enfermedad celíaca",
"GAS-064": "Lipasa",
"GAS-065": "Peritonitis bacteriana secundaria a perforación",
"GAS-066": "Endoscopía digestiva alta",
"GAS-067": "Carga viral",
"GAS-068": "Carcinomatosis peritoneal",
"GAS-069": "Úlcera péptica perforada",
"GAS-070": "Colecistectomía de urgencia",
"GAS-071": "Ecografía abdominal",
"GAS-072": "Colonoscopía en la fase aguda",
"GAS-073": "Carbapenémicos",
"GAS-074": "Glomerulonefritis aguda",
"GAS-075": "Pancreatitis",
"GAS-076": "Hepatitis viral aguda",
"GAS-077": "Hepatitis tóxica por levotiroxina",
"GAS-078": "La lipasa activa directamente el tripsinógeno",
"GIN-002": "Alta con reposo domiciliario",
"GIN-003": "Esperar dilatación completa",
"GIN-004": "Hipertensión crónica",
"GIN-005": "Síndrome HELLP completo",
"GIN-006": "Suspender la lactancia",
"GIN-007": "Litiasis renal",
"GIN-008": "Amniotomía",
"GIN-009": "Histerosalpingografía",
"GIN-010": "Realizar versión cefálica externa",
"GIN-011": "Amnioinfusión",
"GIN-012": "Dexametasona en dosis única oral",
"GIN-013": "Embarazo ectópico",
"GIN-014": "Aborto incompleto",
"GIN-015": "Ablación endometrial",
"GIN-016": "Embarazo de menor edad gestacional",
"GIN-017": "Trichomoniasis",
"GIN-018": "Ecografía abdominal",
"GIN-019": "Parto vaginal con episiotomía",
"GIN-020": "Cesárea inmediata",
"GIN-021": "Masculino",
"GIN-022": "Control en una semana",
"GIN-023": "Pesario y alta",
"GIN-024": "Rotura uterina",
"GIN-025": "Repetir ecografía en 1 año",
"GIN-026": "24",
}
