R = {
"GIN-027": "Trabajo de parto en fase activa",
"GIN-028": "Legrado uterino inmediato",
"GIN-029": "Uso de prostaglandinas",
"GIN-030": "Inducción con misoprostol",
"GIN-031": "Mastitis puerperal",
"GIN-032": "Pielonefritis aguda",
"GIN-033": "Rotura del seno marginal",
"GIN-034": "Inducción inmediata del parto",
"GIN-035": "Hemoglobina glicosilada mensual",
"GIN-036": "Que sea su primer parto",
"GIN-037": "Amniocentesis",
"GIN-038": "Amniocentesis para madurez pulmonar",
"GIN-039": "Embarazo ectópico",
"GIN-040": "Embarazo gemelar",
"GIN-041": "Amenaza de aborto",
"GIN-042": "Vasa previa",
"GIN-043": "Colecistitis aguda",
"GIN-044": "La cabeza en la vulva",
"GIN-045": "Clotrimazol vaginal por tres días",
"GIN-046": "Hemodiálisis suspendida durante el embarazo",
"GIN-047": "Inmediatamente al diagnóstico",
"GIN-048": "Rotura del seno marginal",
"GIN-049": "Mastitis puerperal",
"GIN-050": "Infección urinaria baja",
"GIN-052": "Cesárea electiva",
"GIN-053": "Episiotomía amplia como única maniobra",
"GIN-054": "Terapia de reemplazo hormonal",
"GIN-055": "Fluconazol como única medida",
"GIN-056": "Cistoadenoma mucinoso",
"GIN-057": "Trabajo de parto prolongado",
"GIN-058": "Chlamydia trachomatis",
"GIN-059": "Rotura uterina",
"GIN-061": "Suspender la lactancia materna",
"GIN-062": "Atonía uterina",
"GIN-063": "Inducción del parto en el centro de salud",
"GIN-064": "Iniciar metformina",
"GIN-065": "Antibióticos profilácticos a todas las puérperas por 7 días",
"GIN-066": "Liquen escleroso",
"GIN-067": "Séptico",
"GIN-068": "Iniciar insulina",
"GIN-069": "Electivo",
"GIN-070": "Rotura del seno marginal",
"GIN-071": "Estómago",
"GIN-072": "Citología de cúpula vaginal anual",
"GIN-073": "Retirar el tratamiento y observar",
"GIN-074": "Absceso tubo-ovárico",
"GIN-075": "Tratar con nitrofurantoína",
"GIN-076": "Radiografía simple de abdomen",
"GIN-077": "Amnioinfusión",
"GIN-078": "Midiendo el diámetro biparietal a las 20 semanas",
"GIN-079": "Furosemida y manejo expectante",
"GIN-080": "Histerectomía de urgencia",
"GIN-081": "Indicar progesterona y alta",
"GIN-082": "Paracentesis",
"GIN-083": "Realizar amniotomía",
"GIN-084": "Ovárica por falla prematura",
"GIN-085": "Aumentar la dosis de sulfato de magnesio",
"GIN-086": "Histerectomía inmediata",
}
