R = {
"GIN-147": "Peso materno",
"GIN-148": "Paracetamol",
"GIN-149": "Fórceps profiláctico",
"GIN-150": "Hipotiroidismo y RCIU",
"GIN-151": "Anillo vaginal combinado",
"GIN-152": "Enalapril",
"GIN-153": "Preeclampsia",
"GIN-154": "Solo durante el puerperio",
"GIN-155": "Amenaza de aborto",
"GIN-156": "Indicar a las 28 semanas del siguiente embarazo",
"GIN-157": "Cesárea electiva",
"GIN-158": "G4P1111",
"GIN-159": "Metronidazol solo",
"GIN-160": "Prevenir la diabetes gestacional",
"GIN-161": "Síndrome nefrótico",
"GIN-162": "VIH y hepatitis C",
"GIN-163": "Perineal I grado",
"GIN-164": "Cesárea de emergencia",
"GIN-165": "Aumento de la frecuencia cardiaca",
"GIN-166": "Hemoglobina glicosilada",
"GIN-167": "Hipotiroidismo",
"GIN-168": "Insuficiencia placentaria",
"GIN-169": "5",
"GIN-170": "Iniciar sulfato de magnesio",
"GIN-171": "La altura uterina actual",
"GIN-172": "Grupo sanguíneo y factor Rh",
"GIN-173": "Salida de sangre oscura en escasa cantidad",
"GIN-174": "Anemia",
"GIN-175": "Prueba de VIH",
"GIN-176": "Tocólisis y alta",
"GIN-177": "Tomografía de silla turca",
"GIN-178": "Pesario como tratamiento definitivo",
"GIN-179": "Enalapril profiláctico",
"GIN-180": "Amniocentesis",
"GIN-181": "Mantener el DIU hasta el parto",
"GIN-182": "Trabajo de parto a término",
"GIN-183": "Monitoreo fetal",
"GIN-184": "Taponamiento vaginal",
"GIN-185": "Ooforectomía",
"GIN-186": "Lactancia con TARGA",
"GIN-187": "Que suspenda todos sus medicamentos",
"GIN-188": "28 a 32",
"GIN-189": "Resuturar la episiotomía",
"GIN-190": "Cirugía de cistocele",
"GIN-191": "Versión cefálica externa",
"GIN-192": "Histerectomía",
"GIN-193": "Desprendimiento prematuro de placenta",
"GIN-194": "Fórceps",
"GIN-195": "Igual que la población general",
"GIN-196": "Tocólisis",
"GIN-197": "Ceftriaxona 500 mg IM dosis única",
"GIN-198": "Drenar la mama inmediatamente",
"GIN-199": "Aborto incompleto",
"GIN-200": "Inseminación artificial inmediata",
"GIN-201": "Inmediatamente",
"GIN-202": "Tocólisis",
"GIN-203": "Alta con antibiótico oral",
"GIN-204": "Fecha probable por examen pélvico",
"GIN-205": "Observación con β-hCG en un mes",
"GIN-206": "Histeroscopía",
}
