R = {
"HEM-020": "Déficit de vitamina K",
"HEM-021": "Leucemia linfoblástica aguda",
"HEM-022": "Anemia de enfermedad crónica",
"HEM-023": "Por gotas",
"HEM-024": "Mal de montaña crónico",
"HEM-025": "Transfusión de plaquetas",
"HEM-026": "Prader-Willi",
"HEM-027": "Sexo",
"HEM-028": "Púrpura trombocitopénica inmune",
"HEM-029": "Púrpura trombocitopénica trombótica",
"HEM-030": "Sideroblástica",
"HEM-031": "Celulitis",
"HEM-032": "Viajes recientes",
"HEM-033": "Infección viral",
"HEM-034": "Sangrado agudo",
"HEM-035": "Leucemia mieloide crónica",
"HEM-036": "Esferocitos",
"HEM-037": "Hierro oral",
"HEM-038": "Electroforesis de hemoglobina",
"HEM-039": "Trombocitopenia inmune",
"HEM-040": "Suspender la warfarina y solo observar",
"HEM-041": "Tiempo de sangría",
"INF-002": "Herpesvirus",
"INF-003": "Faringitis estreptocócica",
"INF-004": "Chancroide",
"INF-005": "Sarcoma de Kaposi pulmonar",
"INF-006": "Ivermectina",
"INF-007": "Fiebre amarilla",
"INF-008": "Amoxicilina - claritromicina",
"INF-009": "Electroencefalograma",
"INF-010": "Leptospirosis",
"INF-011": "Metronidazol",
"INF-012": "Suspender la lactancia hasta terminar el tratamiento",
"INF-013": "Primiparidad",
"INF-014": "Neumonía por aspiración",
"INF-015": "Linfocitaria con eosinófilos",
"INF-016": "Anopheles",
"INF-017": "Penicilina benzatínica",
"INF-018": "Listeria monocytogenes",
"INF-019": "Ganciclovir",
"INF-020": "Parasitaria",
"INF-021": "Cisticercos",
"INF-022": "Dengue sin signos de alarma",
"INF-023": "Rotavirus",
"INF-024": "Dengue",
"INF-025": "Toxoplasmosis, cisticercosis",
"INF-026": "Cáncer de pulmón",
"INF-027": "Ivermectina",
"INF-028": "Es un virus ADN de doble cadena",
"INF-029": "Fiebre tifoidea",
"INF-030": "Culex",
"INF-031": "Ovale",
"INF-032": "Tuberculosa",
"INF-033": "Absceso bacteriano",
"INF-034": "Entamoeba histolytica",
"INF-035": "Tenofovir",
"INF-036": "Haemophilus ducreyi",
"INF-037": "Dengue grave",
"INF-038": {0: "Metronidazol", 4: "Praziquantel"},
}
