R = {
"INF-099": "Iniciar la lactancia y no vacunar hasta los 2 meses",
"INF-100": "Granuloma inguinal",
"INF-101": "Ganglionar periférica",
"INF-102": "Trombosis venosa profunda",
"INF-103": "Shigella dysenteriae",
"INF-104": "20",
"INF-105": "Exposición no ocupacional",
"INF-106": "Doxiciclina por 7 días",
"INF-107": "2",
"INF-108": "Herpes simple",
"INF-109": "Recaída",
"INF-110": "Treponema pallidum",
"INF-111": "Albendazol",
"INF-112": "Prazicuantel más corticoide en dosis única",
"INF-113": "Confirmado importado",
"INF-114": "Vacunar con BCG",
"NEF-002": "Hipopotasemia",
"NEF-003": "Apendicitis aguda",
"NEF-004": "Síndrome nefrótico",
"NEF-005": "Glomerulonefritis postestreptocócica",
"NEF-006": "Nefritis intersticial aguda",
"NEF-007": "Glomerulonefritis rápidamente progresiva",
"NEF-008": "Urografía excretora",
"NEF-009": "Orquitis urliana",
"NEF-010": "Suspender la eritropoyetina",
"NEF-011": "Glomerulonefritis aguda",
"NEF-012": "Furosemida en monoterapia",
"NEF-013": "Cetoacidosis diabética",
"NEF-014": "Varicocele",
"NEF-015": "Cistina",
"NEF-016": "Varicocele",
"NEF-017": "Hidrocele",
"NEF-018": "Nefropatía membranosa",
"NEF-019": "Antiinflamatorios no esteroideos",
"NEF-020": "Necrosis tubular aguda",
"NEF-021": "Diuréticos tiazídicos / Antiespasmódicos",
"NEF-022": "Hipocalcemia",
"NEF-023": "Nefrostomía percutánea",
"NEF-024": "Tomografía cerebral",
"NEF-025": "Bicarbonato de sodio oral",
"NEF-026": "Glomerulonefritis aguda",
"NEF-027": "Varicocele",
"NEF-028": "Gammagrafía renal",
"NEF-029": "Urocultivo",
"NEF-030": "Pielonefritis aguda",
"NEF-031": "Azoemia prerrenal",
"NEF-032": "Hiperpotasemia",
"NEF-033": "1 000",
"NEF-034": "Fosfato de calcio",
"NEF-035": "Síndrome de Alport",
"NEF-036": "Epididimitis",
"NEF-037": "Hidroclorotiazida",
"NEF-038": "Tamsulosina de por vida",
"NEF-039": "Cambio a antibiótico oral y alta",
"NEF-040": "Hidrocortisona",
"NEF-041": "Hiperaldosteronismo primario",
"NEF-042": "Furosemida endovenosa",
"NEF-043": "Sodio alto",
"NEF-044": "Riñón poliquístico",
}
