R = {
"NEU-012": "Flumazenilo y observación sin oxígeno",
"NEU-013": "Corticoides orales como única medida",
"NEU-014": "Pneumocystis jirovecii",
"NEU-015": "Penicilina benzatínica sola",
"NEU-016": "Neumonía intrahospitalaria",
"NEU-017": "Derrame paraneumónico complicado",
"NEU-018": "Síndrome del túnel carpiano",
"NEU-019": "Citología de esputo seriada",
"NEU-020": "Hipoventilación alveolar pura",
"NEU-021": "Bronquiectasias",
"NEU-022": "Neumotórax espontáneo",
"NEU-023": "Frecuencia cardiaca de 130",
"NEU-024": "Infarto agudo de miocardio",
"NEU-025": "Vacuna BCG a la gestante",
"NEU-026": "Mycobacterium tuberculosis",
"NEU-027": "Granulomas no caseificantes",
"NEU-028": "Nebulización con salbutamol y observación",
"NEU-029": "Ventilación no invasiva diferida",
"NEU-030": "Absceso pulmonar",
"NEU-031": "Persistente muy grave",
"NEU-032": "Neumotórax espontáneo",
"NEU-033": "Antibióticos de amplio espectro",
"NEU-034": "Prueba de VIH obligatoria antes de cualquier medida",
"NEU-035": "Intubación orotraqueal inmediata",
"NEU-036": "Espirometría",
"NEU-037": "Hospitalización en UCI con ventilación mecánica",
"NEU-038": "Broncoscopía",
"NEU-039": "Neumonía bacteriana",
"NEU-040": "Leve con riesgo de paro",
"NEU-041": "Edema agudo de pulmón",
"NEU-042": "Gammagrafía ósea",
"NEU-043": "Neumonía lobar",
"NEU-044": "Sexo femenino",
"NEU-045": "Isoniazida",
"NEU-046": "Leucocitosis",
"NEU-047": "8 a 10",
"NEU-048": "Retirar la rifampicina",
"NEU-049": "Biopsia pleural cerrada inmediata",
"NEU-050": "Exposición laboral a asbesto",
"NEU-051": "Neumotórax",
"NEU-052": "Shock séptico",
"NEU-053": "Intubación inmediata",
"NEU-054": "Suspender la lactancia por 6 meses",
"NEU-055": "Alta con amoxicilina oral",
"NEU-056": "Edad",
"NEU-057": "Iniciar los cuatro fármacos de primera línea de inmediato",
"NEU-058": "Ventilación mecánica invasiva inmediata",
"NEU-059": "Suspender los broncodilatadores",
"NEU-060": "Temperatura de 37 °C",
"NEU-061": "Estreptomicina",
"NEU-062": "Amoxicilina oral sola",
"NEU-063": "Edema agudo de pulmón",
"NEU-064": "Aumento del espacio muerto",
"NEU-065": "Sarcoidosis",
"NEU-066": "Incremento en VEF1 > 30% sin importar el volumen",
"NEU-067": "Pleurodesis química",
"NEU-068": "Vancomicina",
"NEU-069": "Espirometría",
"NEU-070": "Antibióticos + oxígeno a alto flujo sin broncodilatadores",
}
