R = {
"PED-006": "Vibrio cholerae",
"PED-007": "Pentavalente y neumococo",
"PED-008": "Atresia anal",
"PED-009": "Faringitis viral",
"PED-010": "Neumonía lobar",
"PED-011": "Hipotiroidismo congénito",
"PED-012": "Talla baja familiar",
"PED-013": "Vancomicina + meropenem",
"PED-014": "Impétigo ampolloso",
"PED-015": "Cirugía inmediata sin corregir líquidos",
"PED-016": "Epiglotitis",
"PED-017": "Ciprofloxacino ótico",
"PED-018": "Enfermedad celíaca",
"PED-019": "Hijos de madre diabética",
"PED-020": "Hemorragia intraventricular",
"PED-021": "Staphylococcus aureus",
"PED-022": "Hiperplasia suprarrenal congénita",
"PED-023": "Fiebre persistente de 38 °C",
"PED-024": "Gastroenteritis aguda",
"PED-025": "Benzodiacepinas",
"PED-026": "Ácido valproico oral",
"PED-027": "Neumotórax derecho",
"PED-028": "Hemofilia A",
"PED-029": "Contaminación con flora perineal",
"PED-030": "Sinusitis aguda bacteriana",
"PED-031": "Talasemia menor",
"PED-032": "Colecistitis aguda",
"PED-033": "Naloxona",
"PED-034": "Neumonía por aspiración",
"PED-035": "Apendicitis aguda",
"PED-036": "Urografía excretora",
"PED-037": "Amoxicilina oral",
"PED-038": "Esperar 5 minutos y reevaluar",
"PED-039": "Insuficiencia cardiaca congestiva",
"PED-040": "Atresia esofágica",
"PED-041": "Propranolol",
"PED-042": "Neumonía aspirativa",
"PED-043": "Síndrome nefrótico idiopático",
"PED-044": "Parálisis total del plexo braquial",
"PED-045": "Espasmos infantiles",
"PED-046": "Ictericia por leche materna",
"PED-047": "Enfermedad de Hirschsprung",
"PED-048": "Neumonía lobar",
"PED-049": "Amoxicilina oral",
"PED-050": "Endoscopía digestiva alta",
"PED-051": "Raquitismo",
"PED-052": "Ecografía abdominal",
"PED-053": "Ayuno y antiemético",
"PED-054": "Urocultivo",
"PED-055": "Hidrocefalia",
"PED-056": "Varía solo por la alimentación",
"PED-057": "Síndrome hemolítico urémico",
"PED-058": "Gluconato de calcio",
"PED-059": "Enfermedad de Hirschsprung",
"PED-060": "TAC cerebral antes de cualquier otro estudio",
"PED-061": "Bronquiolitis",
"PED-062": "Sin deshidratación",
"PED-063": "Púrpura de Henoch-Schönlein",
"PED-064": "Epiglotitis aguda",
"PED-065": "Neumonía congénita",
}
