R = {
"PED-186": "Hirschsprung",
"PED-187": "Ecografía pulmonar de rutina",
"PED-188": "Seis",
"PED-189": "Púrpura trombocitopénica inmune",
"PED-190": "Enema con contraste",
"PED-191": "Corregir el sodio en menos de 6 horas",
"PED-192": "Ayuno y antiemético",
"PED-193": "Rotavirus",
"PED-194": "1.5",
"PED-195": "10",
"PED-196": "Loratadina oral",
"PED-197": "Obesidad",
"PED-198": "Monosomía X",
"PED-199": "Sibilancias por reflujo",
"PED-200": "Alta con antibiótico oral",
"PED-201": "Gastroenteritis aguda",
"PED-202": "Coartación de aorta",
"PED-203": "Laringotraqueítis",
"PED-204": "Masaje cardiaco",
"PED-205": "Uso de hierro profiláctico",
"PED-206": "Suero oral a demanda",
"PED-207": "Esperar a los 18 meses para confirmar con ELISA",
"PED-208": "10",
"PED-209": "48",
"PED-210": "Hemoglobina glicosilada",
"PED-211": "Transposición de grandes arterias",
"PED-212": "Nitrofurantoína oral",
"PED-213": "Cuerpo extraño bronquial",
"PED-214": "Enterocolitis necrotizante",
"PED-215": "Mycoplasma pneumoniae",
"PED-216": "Indicar antipirético y alta",
"PED-217": "Clorfenamina",
"PED-218": "Neurogénico",
"PED-219": "Hipotiroidismo congénito",
"PED-220": "Ivermectina",
"PED-221": "Fototerapia",
"PED-222": "Vitamina C",
"PED-223": "Mesangial por IgA",
"PED-224": "Rotavirus",
"PED-225": "3",
"PED-226": "Insuficiencia suprarrenal neonatal",
"PED-227": "Obstrucción al tracto de salida izquierdo",
"PED-228": "Dermatitis atópica",
"PED-229": "Hernia hiatal",
"PED-230": "Corticoides endovenosos",
"PED-231": "Repetir la PCR a los 6 meses",
"PED-232": "Fenobarbital",
"PED-233": "Escorbuto",
"PED-234": "Intubación orotraqueal",
"PED-235": "Masaje cardiaco",
"PED-236": "Antibiótico tópico en las lesiones",
"PED-237": "Nistatina tópica",
"PED-238": "Escarlatina",
"PED-239": "Sexo femenino",
"PED-240": "Uso de chupón para calmarlo",
"PED-241": "Ano imperforado",
"PSI-002": "Hipertiroidismo",
"PSI-003": "Intubación orotraqueal",
"PSI-004": "Carbón activado como única medida",
}
