# Revisión preguntas 101-150
D, O, N, X = {}, {}, {}, {}

X[101] = "Repite la 79 (absorción de vitamina B12 en el íleon)"

D[102] = ("Célula parietal: secreta ácido clorhídrico y factor intrínseco", "A",
"Las células parietales u oxínticas del cuerpo y el fondo gástrico secretan ácido clorhídrico y factor intrínseco. El ácido se produce con la bomba H+/K+-ATPasa de la membrana apical, que intercambia hidrogeniones por potasio. La estimulan tres señales: la acetilcolina (receptor M3), la gastrina (receptor CCK2) y, sobre todo, la histamina (receptor H2) liberada por las células enterocromafines. Las células principales secretan pepsinógeno; las células mucosas del cuello, moco y bicarbonato, y las células G del antro, gastrina. Los inhibidores de la bomba de protones, como el omeprazol, bloquean el paso final común de la secreción ácida. En la anemia perniciosa, la destrucción de estas células causa aclorhidria y déficit de B12.")
O[102] = {"E": "Pepsinógeno y moco"}

X[103] = "Repite la 94 (arteria gástrica izquierda y curvatura menor)"

D[104] = ("Arteria pancreatoduodenal superior: rama de la gastroduodenal", "D",
"La arteria gastroduodenal nace de la hepática común y baja por detrás de la primera porción del duodeno. Da la arteria pancreatoduodenal superior, con sus ramas anterior y posterior, y termina como gastroepiploica derecha. Las pancreatoduodenales superiores se anastomosan en la cabeza del páncreas con las inferiores, que vienen de la mesentérica superior. Esa arcada une el territorio del tronco celíaco con el de la mesentérica superior y permite la circulación colateral si uno de los dos se ocluye. Importancia clínica: una úlcera de la cara posterior del bulbo duodenal puede erosionar la gastroduodenal y causar una hemorragia digestiva alta masiva.")
O[104] = {"C": "Mesentérica inferior", "E": "Gastroepiploica derecha"}

D[105] = ("Derivados del conducto mesonéfrico (de Wolff)", "A",
"El conducto mesonéfrico (de Wolff), bajo el estímulo de la testosterona, da origen al epidídimo, el conducto deferente, la vesícula seminal y el conducto eyaculatorio. Algunos túbulos mesonéfricos se convierten en los conductillos eferentes. Los túbulos seminíferos, en cambio, se forman a partir de los cordones sexuales de la gónada, es decir, del epitelio celómico y del mesénquima gonadal, junto con las células germinales primordiales. No derivan del conducto de Wolff. En la mujer, sin testosterona, el conducto de Wolff involuciona y deja restos como el conducto de Gartner, origen de quistes en la pared vaginal.")
O[105] = {"E": "Vesícula seminal"}

D[106] = ("Efectos muscarínicos: producen hipotensión, no hipertensión", "B",
"La estimulación de los receptores muscarínicos, por ejemplo en la intoxicación por organofosforados o con agonistas como la pilocarpina, produce efectos parasimpáticos. En el ojo, miosis. En las glándulas, broncorrea, sialorrea, lagrimeo (epífora) y sudoración. En los pulmones, broncoespasmo. En el corazón, bradicardia a través de receptores M2. En los vasos, vasodilatación mediada por óxido nítrico endotelial (receptores M3), que produce hipotensión. Por eso la hipertensión no es un efecto muscarínico. Si aparece hipertensión con taquicardia en un organofosforado, se debe al componente nicotínico (estimulación de ganglios simpáticos y de la médula suprarrenal).")

D[107] = ("Síndrome colinérgico: intoxicación por organofosforados", "D",
"El cuadro reúne signos muscarínicos (vómito, diarrea, sialorrea, miosis y broncoespasmo), nicotínicos (fasciculaciones) y del sistema nervioso central (sopor y convulsiones). Es el síndrome colinérgico completo, típico de la intoxicación por organofosforados o carbamatos, que inhiben la acetilcolinesterasa y acumulan acetilcolina. En el Perú es una intoxicación frecuente por plaguicidas en zonas agrícolas, accidental o con intención suicida. Los salicilatos causan taquipnea, alcalosis respiratoria y acidosis metabólica, sin miosis. Las benzodiacepinas producen sedación sin secreciones ni fasciculaciones. La meningitis y la epilepsia no explican la miosis con sialorrea y broncorrea. Tratamiento: descontaminación, atropina y pralidoxima.")
X[132] = "Repite la 107 (diagnóstico de intoxicación por organofosforados)"
X[111] = "Repite la 127 (atropina como antídoto de organofosforados)"

D[108] = ("Acinetobacter baumannii: patógeno típicamente hospitalario", "D",
"Acinetobacter baumannii es un cocobacilo gramnegativo no fermentador que sobrevive largo tiempo en superficies secas y equipos. Por eso es un patógeno casi exclusivamente hospitalario: causa neumonía asociada a ventilación mecánica, bacteriemia por catéter e infecciones de heridas en la UCI. Suele ser multirresistente, incluso a carbapenémicos, y a veces solo responde a colistina o tigeciclina. Las otras opciones son falsas: el neumococo no se trata con norfloxacina, que casi no actúa sobre grampositivos; el enterococo causa cerca del 10 % de las infecciones nosocomiales, no el 30 %; Candida sí es frecuente en diabéticos y en nutrición parenteral, y S. epidermidis es con frecuencia resistente a meticilina.")
O[108] = {"C": "Cándida es rara en pacientes con nutrición parenteral"}

D[109] = ("Antídotos: N-acetilcisteína para el paracetamol", "C",
"El único par correcto es paracetamol con N-acetilcisteína, que repone el glutatión y neutraliza el metabolito tóxico NAPQI. Los otros están equivocados. En los carbamatos, la pralidoxima casi no sirve, porque la enzima se recupera sola; el antídoto es la atropina. Para el metanol y el etilenglicol se usa etanol o fomepizol, y no al revés. Para las benzodiacepinas, el antagonista es el flumazenil; la naloxona es para los opioides. El talio se trata con azul de Prusia, y la atropina es para los organofosforados. Otros pares útiles: la deferoxamina para el hierro, el azul de metileno para la metahemoglobinemia, la hidroxocobalamina para el cianuro y la vitamina K para los cumarínicos.")

D[110] = ("Reacción de Jarisch-Herxheimer tras penicilina en sífilis", "D",
"La reacción de Jarisch-Herxheimer aparece entre 2 y 24 horas después de la primera dosis de un tratamiento eficaz contra espiroquetas, sobre todo en la sífilis secundaria. La lisis masiva de treponemas libera lipoproteínas que estimulan la producción de citocinas (TNF-alfa, IL-6, IL-8). El cuadro es fiebre, escalofríos, mialgias, cefalea, taquicardia y empeoramiento transitorio de las lesiones. Se resuelve en menos de 24 horas con antipiréticos y no es una alergia a la penicilina, así que no se suspende el tratamiento. En la gestante puede desencadenar contracciones o sufrimiento fetal, por lo que se vigila. También ocurre en la leptospirosis, la borreliosis y la fiebre recurrente.")
O[110] = {"D": "Jarisch-Herxheimer", "E": "Middlebrook-Dubos"}

D[112] = ("Edema: signo tardío en la insuficiencia cardíaca derecha", "B",
"El edema clínicamente visible exige que se acumulen varios litros de líquido en el intersticio, alrededor de 3 a 5 L en un adulto. Antes de eso, el paciente solo sube de peso. Por eso, en la insuficiencia cardíaca derecha el edema es un signo relativamente tardío: primero aparecen la ingurgitación yugular, el reflujo hepatoyugular y la hepatomegalia congestiva. Las demás afirmaciones son correctas. El edema cardíaco depende de la gravedad (declive): empeora durante el día en los tobillos, se reduce con el reposo nocturno y, en el paciente encamado, se ubica en la región sacra y lumbar. Por el contrario, el edema del síndrome nefrótico suele notarse primero en los párpados por la mañana.")
O[112] = {"A": "Se aprecia clínicamente cuando se han acumulado varios litros en el espacio intersticial"}

D[113] = ("Oponente del pulgar: nervio mediano (rama recurrente)", "E",
"Los músculos de la eminencia tenar (abductor corto, oponente y cabeza superficial del flexor corto del pulgar) están inervados por la rama motora recurrente del nervio mediano, que sale después del túnel carpiano. Por eso, en el síndrome del túnel carpiano avanzado se atrofia la eminencia tenar y se pierde la oposición del pulgar. El aductor del pulgar y la cabeza profunda del flexor corto dependen del cubital, lo que explica el signo de Froment en la lesión cubital. La lesión alta del mediano da la 'mano de predicador'; la del cubital, la 'mano en garra', y la del radial, la 'mano caída'.")
O[113] = {"A": "Musculocutáneo", "D": "Axilar (circunflejo)"}

X[114] = "Repite la 27 (pie equino y nervio peroneo profundo)"

D[115] = ("Shock hemorrágico con Hto 20 %: transfundir concentrado de hematíes", "D",
"El paciente tiene un shock hemorrágico por trauma con hematocrito del 20 %, que indica una pérdida importante (clase III o IV) y persiste tras el cristaloide inicial. Según el ATLS vigente, se limita el cristaloide a 1 L como máximo y, si no hay respuesta o esta es transitoria, se transfunden de inmediato hemoderivados: paquete globular (concentrado de hematíes) y, si hay hemorragia masiva, un protocolo 1:1:1 con plasma y plaquetas, junto con ácido tranexámico y control quirúrgico del sangrado. Los cristaloides en exceso diluyen los factores y agravan la coagulopatía, la acidosis y la hipotermia (la 'tríada letal'). Los coloides no mejoran la sobrevida, y la sangre total casi no se usa en los hospitales.")
N[115] = "Varón de 36 años, víctima de un accidente de tránsito, en shock hipovolémico con hematocrito de 20 %. Tras 1 L de cristaloide persiste hipotenso y taquicárdico. ¿Qué debe administrarse a continuación?"

D[116] = ("Toxíndrome colinérgico: bradicardia, miosis, secreciones, fasciculaciones", "A",
"El niño presenta diarrea, vómitos, bradicardia, miosis, sialorrea y fasciculaciones: es el síndrome colinérgico, por exceso de acetilcolina en los receptores muscarínicos y nicotínicos. La causa habitual son los insecticidas organofosforados y carbamatos. El síndrome anticolinérgico es su espejo: 'rojo como un tomate, seco como un hueso, caliente como una liebre, loco como una cabra y ciego como un murciélago', con midriasis, taquicardia y retención urinaria. El simpaticomimético (cocaína, anfetaminas) causa midriasis, taquicardia, HTA y sudoración. El narcótico (opioides) causa miosis con depresión respiratoria, pero sin secreciones ni fasciculaciones. Los toxíndromes orientan el tratamiento antes de identificar el tóxico.")

D[117] = ("Hipouricemiantes: el alopurinol inhibe la xantina oxidasa", "D",
"El alopurinol reduce la uricemia porque inhibe la xantina oxidasa, la enzima que convierte la hipoxantina en xantina y la xantina en ácido úrico. Es el tratamiento de base de la gota con ataques frecuentes, tofos o litiasis, y se usa para prevenir el síndrome de lisis tumoral. Se inicia a dosis baja (100 mg/día) y se sube hasta llegar a un ácido úrico menor de 6 mg/dL. Al inicio se asocia colchicina para prevenir crisis. Cuidado con la azatioprina, porque su toxicidad aumenta, y con el HLA-B*5801, asociado a reacciones cutáneas graves. La colchicina y la indometacina tratan la crisis aguda pero no bajan el ácido úrico, y la furosemida lo aumenta.")
O[117] = {"E": "Prednisona"}

X[118] = "Clave dudosa: los neuropéptidos también participan en la broncoconstricción asmática"

D[119] = ("Lavado gástrico: contraindicado en la ingestión de cáusticos", "E",
"El lavado gástrico está contraindicado en la ingestión de cáusticos, sean álcalis como la lejía y los limpiadores de hornos o ácidos. La sonda puede perforar un esófago o un estómago necrosados, y el vómito expone otra vez la mucosa al corrosivo. Tampoco se da carbón activado, que no adsorbe estas sustancias y dificulta la endoscopia. Otras contraindicaciones del lavado: hidrocarburos por riesgo de aspiración, vía aérea no protegida y riesgo de hemorragia o perforación. Hoy el lavado casi no se usa. Solo se considera en las primeras horas, ante un tóxico muy letal sin antídoto. Ante un cáustico se hace endoscopia en las primeras 12 a 48 horas para clasificar las lesiones.")
O[119] = {"E": "Álcalis (cáusticos)"}

D[120] = ("Bradicardia, miosis, sudoración e hiperperistaltismo: organofosforados", "D",
"La combinación de bradicardia (50 lpm), miosis, sudoración y aumento del peristaltismo intestinal es un síndrome muscarínico o colinérgico, típico de la inhibición de la acetilcolinesterasa por organofosforados o carbamatos. La cocaína produce lo contrario: taquicardia, midriasis, HTA e hipertermia. En el botulismo, la toxina bloquea la liberación de acetilcolina: hay midriasis, sequedad, estreñimiento y parálisis descendente. El arsénico causa gastroenteritis coleriforme, QT largo y luego neuropatía, sin miosis. El mercurio causa temblor, gingivitis y eretismo. Para confirmar un organofosforado se mide la colinesterasa eritrocitaria o plasmática, pero el tratamiento con atropina no debe esperar al resultado.")

D[121] = ("Macrólidos: prolongan el intervalo QT", "B",
"La eritromicina y otros macrólidos (claritromicina y, en menor grado, azitromicina) bloquean los canales de potasio hERG del miocardio. Así retrasan la repolarización y alargan el QT, con riesgo de taquicardia ventricular polimórfica en torsades de pointes. El riesgo aumenta con hipopotasemia, hipomagnesemia, síndrome de QT largo congénito y otros fármacos que alargan el QT, como antipsicóticos, quinolonas, ondansetrón y antiarrítmicos de clase IA y III. La eritromicina y la claritromicina también inhiben el CYP3A4 y elevan los niveles de estatinas, warfarina y carbamazepina. Otro efecto típico de la eritromicina: actúa como agonista de la motilina y causa cólicos, lo que se aprovecha como procinético.")

D[122] = ("Ingesta de hidrocarburos asintomática: observación y radiografía a las 6 h", "C",
"El principal peligro de los hidrocarburos (kerosene, gasolina, thinner) es la neumonitis química por aspiración, no la absorción intestinal. Por eso nunca se induce el vómito ni se hace lavado gástrico, y no se da aceite mineral ni carbón activado. Tampoco se dan antibióticos ni corticoides de rutina. Si el niño está asintomático, se le observa unas 6 horas con radiografía de tórax: si sigue sin síntomas, con radiografía normal y saturación normal, se le da de alta. Si aparecen tos, taquipnea, desaturación o infiltrados, se hospitaliza con oxígeno y, en casos graves, ventilación mecánica. Los cambios radiológicos pueden tardar horas en aparecer.")
N[122] = "Niño de 3 años que hace 1 hora bebió kerosene; está asintomático, con examen pulmonar y saturación normales. ¿Cuál es la conducta?"
O[122] = {"A": "Intubación y ventilación mecánica", "B": "Inducción del vómito", "C": "Observación clínica con radiografía de tórax a las 6 horas", "D": "Administración de aceite mineral", "E": "Antibióticos profilácticos"}

D[123] = ("Fractura del canal de torsión del húmero: lesión del nervio radial", "D",
"El nervio radial rodea la cara posterior de la diáfisis del húmero por el surco radial o canal de torsión, junto con la arteria braquial profunda. Por eso las fracturas del tercio medio o distal de la diáfisis humeral, como la de Holstein-Lewis, pueden lesionarlo. El resultado es una 'mano caída': no se pueden extender la muñeca, los dedos ni el pulgar, y hay hipoestesia en el dorso de la primera comisura. El tríceps suele respetarse porque sus ramas nacen más arriba. La mayoría de estas lesiones son neuroapraxias que se recuperan en 3 a 4 meses. El circunflejo o axilar se lesiona en la fractura del cuello quirúrgico, y el cubital, en la epitróclea.")

D[124] = ("Canal epitrócleo-olecraniano: nervio cubital", "A",
"El nervio cubital pasa por detrás de la epitróclea, en el canal epitrócleo-olecraniano o túnel cubital, cubierto solo por piel y el ligamento de Osborne. Es el lugar donde se golpea el 'hueso de la risa'. Allí se comprime en el síndrome del túnel cubital, la segunda neuropatía por atrapamiento más frecuente después del túnel carpiano, o se lesiona en fracturas de la epitróclea. Produce parestesias en el 4.º y 5.º dedos, debilidad de los interóseos y del aductor del pulgar (signo de Froment), atrofia del primer interóseo dorsal y, en casos avanzados, mano en garra cubital. Empeora al flexionar el codo por mucho tiempo, por ejemplo al dormir.")
N[124] = "En la lesión a nivel del canal epitrócleo-olecraniano se afecta el nervio:"
O[124] = {"D": "Musculocutáneo", "E": "Axilar"}

D[125] = ("Intoxicación por rodenticidas cumarínicos: vitamina K1 (fitomenadiona)", "D",
"Los rodenticidas a base de hidroxicumarinas, sobre todo las 'supercumarinas' como el brodifacoum, inhiben la vitamina K epóxido reductasa. Así bloquean la síntesis de los factores II, VII, IX y X. El efecto anticoagulante aparece a las 24 a 72 horas y puede durar semanas o meses. El tratamiento específico es la vitamina K1 (fitomenadiona) por vía oral o IV lenta, a dosis altas y durante semanas, controlando el INR. Si hay sangrado activo o el INR es muy alto, se añade concentrado de complejo protrombínico o plasma fresco congelado. El lavado gástrico casi nunca se indica; se puede dar carbón activado si la ingesta es reciente. El factor VIII no se afecta.")
N[125] = "Mujer de 20 años que, tras una discusión familiar, ingiere un raticida a base de hidroxicumarina. ¿Cuál es la terapia específica?"
O[125] = {"D": "Administración de fitomenadiona (vitamina K1)"}

D[126] = ("Pozos sépticos: intoxicación por ácido sulfhídrico", "B",
"El ácido sulfhídrico (H2S) se forma por la descomposición de materia orgánica en pozos sépticos, alcantarillas, curtiembres y pesca industrial. Tiene olor a huevo podrido, pero a concentraciones altas paraliza el olfato, así que el trabajador deja de percibirlo. Igual que el cianuro, inhibe la citocromo c oxidasa y bloquea la respiración celular. También irrita las mucosas y puede producir edema pulmonar, pérdida brusca de la conciencia ('knockdown') y muerte. Muchas víctimas son rescatistas que entran sin equipo. El tratamiento es retirar de la exposición, dar oxígeno al 100 % y soporte; se han usado nitritos. El monóxido de carbono no irrita y da piel rojo cereza.")

D[127] = ("Intoxicación colinérgica en niño: atropina EV", "D",
"El niño tiene miosis, sialorrea, fasciculaciones y roncantes bilaterales por broncorrea: un síndrome colinérgico, probablemente por un plaguicida organofosforado o carbamato. La prioridad es asegurar la vía aérea y dar atropina EV en dosis de 0,02 a 0,05 mg/kg, repetida o duplicada cada 5 minutos hasta secar las secreciones bronquiales, que es el objetivo principal. La taquicardia o la midriasis no son el objetivo. Se complementa con descontaminación de la piel y pralidoxima en los organofosforados. La naloxona es para opioides; la fisostigmina es un anticolinesterásico que empeoraría el cuadro; el flumazenil revierte benzodiacepinas, y los antihistamínicos no actúan aquí.")
O[127] = {"B": "Fisostigmina", "C": "Antihistamínico"}

D[128] = ("Parálisis del 'sábado por la noche': nervio radial", "A",
"El paciente se durmió ebrio con el brazo apoyado y despertó sin poder extender la muñeca ni los dedos. Es la parálisis del 'sábado por la noche': una neuroapraxia del nervio radial por compresión prolongada contra el húmero, en el canal de torsión. La embriaguez anula el reflejo de cambiar de posición. Aparece mano caída con debilidad de los extensores de la muñeca, de los dedos y del pulgar, e hipoestesia en el dorso de la mano entre el pulgar y el índice. El tríceps suele respetarse. Se trata con una férula de muñeca en extensión y fisioterapia, y casi siempre se recupera en semanas. La lesión del mediano o del cubital no produce mano caída.")
O[128] = {"C": "Musculocutáneo", "E": "Axilar"}

D[129] = ("Vagina proximal: deriva de los conductos de Müller", "A",
"Los conductos paramesonéfricos o de Müller se fusionan en la línea media para formar el útero, el cuello uterino y la porción superior de la vagina, alrededor de sus dos tercios proximales según la descripción clásica. Sus porciones craneales no fusionadas originan las trompas de Falopio. La porción inferior de la vagina deriva del seno urogenital, a partir de los bulbos senovaginales que forman la placa vaginal y luego se canalizan. El himen es el resto de la unión entre ambos. Los conductos de Wolff involucionan en la mujer. Si la fusión mülleriana falla, aparecen útero didelfo o bicorne; si la canalización falla, tabique vaginal transverso o himen imperforado.")
O[129] = {"B": "Los conductos de Wolff", "D": "Los pronefros", "E": "Los mesonefros"}

D[130] = ("Neumonía por SARM: glucopéptidos (vancomicina, teicoplanina)", "D",
"El Staphylococcus aureus resistente a meticilina (SARM) tiene una PBP2a de baja afinidad, así que es resistente a todos los betalactámicos convencionales, incluidas la dicloxacilina y las cefalosporinas como la ceftriaxona. El tratamiento de elección de las infecciones graves por SARM, como la neumonía necrotizante en niños, es un glucopéptido: vancomicina o teicoplanina. La alternativa es el linezolid, que penetra muy bien en el pulmón. La clindamicina (derivada de la lincomicina) solo sirve en cepas sensibles y casos leves, y la azitromicina no es útil. En la neumonía estafilocócica infantil se busca y se drena el empiema, y se vigilan los neumatoceles.")

X[131] = "Repite la 60 (N-acetilcisteína en la intoxicación por paracetamol)"

D[133] = ("PaCO2 normal: 35-45 mmHg (promedio 40)", "C",
"La presión arterial de CO2 normal a nivel del mar es de 35 a 45 mmHg, con un valor promedio de 40 mmHg. Refleja directamente la ventilación alveolar: si la ventilación aumenta, la PaCO2 baja. En el TEC grave con hipertensión endocraneana, una hiperventilación intensa baja la PaCO2 y produce vasoconstricción cerebral. Eso reduce el volumen de sangre y la presión intracraneana, pero también puede causar isquemia. Por eso hoy se busca mantener la PaCO2 entre 35 y 40 mmHg, y la hiperventilación a 30 a 35 mmHg se reserva, de forma breve, para un deterioro agudo o un riesgo de herniación. En la altura, la PaCO2 normal es menor por la hiperventilación fisiológica.")
N[133] = "Paciente de 40 años con TEC severo, en coma e hiperventilación, con signos de hipertensión endocraneana. Para su seguimiento necesita conocer la PaCO2. ¿Cuál es su valor normal promedio a nivel del mar, en mmHg?"

D[134] = ("Sialorrea, miosis, fasciculaciones y sudoración: organofosforado", "D",
"La combinación de sialorrea, tos con secreciones (broncorrea), miosis, sudoración profusa y fasciculaciones indica un exceso de acetilcolina en los receptores muscarínicos y nicotínicos. La sustancia más probable es un insecticida organofosforado, muy común en los hogares y el campo. La hioscina (escopolamina) y las fenotiazinas son anticolinérgicas: dan midriasis, sequedad y taquicardia. Las benzodiacepinas producen sedación con signos vitales casi normales. El paracetamol no da síntomas precoces; causa daño hepático a las 24 a 72 horas. Ante un niño con este cuadro, el tratamiento es atropina con las dosis necesarias para secar las secreciones y pralidoxima si se sospecha un organofosforado.")

D[135] = ("Síndrome colinérgico en intento suicida: atropinización", "E",
"Un joven con depresión que ingiere una sustancia y presenta miosis, fasciculaciones y sialorrea tiene muy probablemente una intoxicación por un plaguicida organofosforado. Es una forma frecuente de intento suicida en el Perú. El pilar del tratamiento es la atropinización: dosis crecientes de atropina IV hasta secar las secreciones bronquiales, con frecuencia cardíaca mayor de 80 lpm y presión arterial sistólica mayor de 80 mmHg. Se complementa con pralidoxima, descontaminación de la piel (retirar la ropa y lavar al paciente) y soporte ventilatorio. La hemodiálisis y la diuresis forzada no eliminan los organofosforados, que son liposolubles. El baño es parte de la descontaminación, pero no es la medida principal.")
O[135] = {"C": "Baño con agua y jabón como única medida"}

X[136] = "Clave discutible: la primera fase del periodo embrionario suele describirse como crecimiento"

D[137] = ("Fenitoína: hiperplasia gingival con el uso prolongado", "E",
"El uso crónico de fenitoína produce hiperplasia o hipertrofia gingival en el 20 al 50 % de los pacientes, sobre todo en niños y adolescentes con mala higiene oral. La fenitoína estimula a los fibroblastos gingivales. Otros efectos crónicos para recordar: hirsutismo, facies tosca, anemia megaloblástica por déficit de folato (no microcítica), osteomalacia por inducción del metabolismo de la vitamina D, neuropatía periférica y atrofia cerebelosa. Signos de toxicidad aguda: nistagmo, ataxia y diplopía. También puede causar Stevens-Johnson (asociado al HLA-B*1502) y es teratógena (síndrome hidantoínico fetal). Su cinética es no lineal, así que pequeños aumentos de dosis elevan mucho los niveles.")
O[137] = {"A": "Hipercarotenemia"}

D[138] = ("Descenso testicular: cruza el conducto inguinal hacia la semana 28", "B",
"El descenso del testículo ocurre en dos fases. En la fase transabdominal, entre las semanas 8 y 15, el testículo queda junto al anillo inguinal interno; esta fase depende de la hormona INSL3 y del gubernáculo. En la fase inguinoescrotal, dependiente de andrógenos, el testículo atraviesa el conducto inguinal alrededor de la semana 26 a 28 y llega al escroto hacia la semana 32 a 35. Por eso la criptorquidia es mucho más frecuente en los prematuros (hasta un 30 %) que en los nacidos a término (un 3 %). Si el testículo no ha descendido a los 6 meses de edad corregida, se deriva para orquidopexia, idealmente antes de los 18 meses.")
N[138] = "¿Hacia qué semana de gestación el testículo desciende a través del conducto inguinal?"

D[139] = ("Articulaciones esféricas (enartrosis): movimiento multiaxial", "C",
"Las articulaciones esféricas o enartrosis tienen una cabeza esférica que encaja en una cavidad cóncava, por lo que permiten movimientos en los tres ejes: flexión y extensión, abducción y aducción, rotación interna y externa, y circunducción. Son multiaxiales o poliaxiales. Ejemplos: el hombro (glenohumeral), el más móvil y el que más se luxa, y la cadera (coxofemoral), más estable gracias a su cavidad profunda. Las condíleas y las en silla de montar son biaxiales; las trocleares o gínglimos (humerocubital, interfalángicas) y las trocoides (radiocubital proximal, atloaxoidea) son uniaxiales, y las planas solo permiten deslizamientos.")

D[140] = ("Capacidad vital: aire máximo espirado tras inspiración máxima", "C",
"La capacidad vital es el volumen máximo de aire que puede expulsarse después de una inspiración máxima. Equivale al volumen corriente más los volúmenes de reserva inspiratorio y espiratorio, y en un adulto joven es de unos 4,5 a 5 L. En la espirometría forzada se mide como capacidad vital forzada (CVF). Baja en las enfermedades restrictivas, como la fibrosis, las enfermedades neuromusculares o la cifoescoliosis. En la miastenia o el Guillain-Barré, una CV menor de 15 a 20 mL/kg indica riesgo de insuficiencia respiratoria. La capacidad pulmonar total suma la CV y el volumen residual, que no puede espirarse. La capacidad inspiratoria es el volumen corriente más el volumen de reserva inspiratorio.")
O[140] = {"B": "Capacidad residual funcional"}

D[141] = ("Proteinuria masiva: lesión de los podocitos", "D",
"La barrera de filtración glomerular tiene tres capas: el endotelio fenestrado, la membrana basal glomerular (con carga negativa por el heparán sulfato) y los podocitos. Las prolongaciones de los podocitos se unen por el diafragma de hendidura (nefrina, podocina), que es la barrera final para las proteínas. En el síndrome nefrótico, con proteinuria masiva mayor de 3,5 g/día o mayor de 40 mg/m²/h en niños, el daño principal está en los podocitos: en la enfermedad de cambios mínimos, la más común en niños, se borran sus pedicelos, visible solo con microscopía electrónica, y en la glomeruloesclerosis focal y segmentaria mueren los podocitos. La mácula densa regula el filtrado y la renina.")

D[142] = ("Oclusión del tronco celíaco: el intestino conserva su irrigación", "D",
"El tronco celíaco irriga los derivados del intestino anterior: estómago, hígado, vesícula, bazo, páncreas en parte y duodeno proximal. El intestino delgado distal al duodeno y el colon derecho y transverso dependen de la arteria mesentérica superior, y el colon izquierdo, de la mesentérica inferior. Por eso, si el tronco celíaco se ocluye, el intestino mantiene su irrigación directa. Además, los órganos del celíaco suelen salvarse gracias a las arcadas pancreatoduodenales (gastroduodenal–mesentérica superior), que se agrandan si la oclusión es lenta, como en la aterosclerosis de los adultos mayores o el síndrome del ligamento arcuato medio. Por eso la isquemia mesentérica crónica suele requerir la oclusión de dos de los tres troncos.")

D[143] = ("Infartos blancos (anémicos): órganos sólidos con circulación terminal", "A",
"Los infartos blancos o anémicos aparecen cuando se ocluye una arteria en un órgano sólido con circulación terminal, es decir, sin doble aporte ni buena colateral. La sangre no vuelve a entrar en la zona necrótica. Los ejemplos típicos son el bazo, el riñón y el corazón. Los infartos rojos o hemorrágicos se dan en órganos con doble circulación (pulmón, con arterias pulmonares y bronquiales, e hígado), en tejidos laxos como el intestino, donde la sangre de las colaterales inunda la zona, en la oclusión venosa (torsión de ovario o de testículo) y cuando se reperfunde un tejido ya necrosado. Por eso el pulmón, el ovario y los intestinos suelen dar infartos rojos.")

D[144] = ("Hepatotoxicidad por paracetamol en niños por dosis repetidas", "D",
"Un niño con fiebre y rinorrea que recibió antipiréticos, a menudo paracetamol en dosis altas o repetidas, o combinado con antigripales que también lo contienen, y que luego presenta ictericia con transaminasas muy elevadas (a veces mayores de 1000 UI/L), orienta a una hepatotoxicidad por paracetamol. El metabolito NAPQI agota el glutatión y necrosa la zona centrolobulillar del hígado. Se trata con N-acetilcisteína aunque haya pasado tiempo. Los salicilatos pueden causar síndrome de Reye (vómitos, encefalopatía, transaminasas altas), pero sin ictericia y con bilirrubina normal. La clorfenamina, la loratadina y la vitamina C no producen necrosis hepática.")

D[145] = ("Corazón embrionario: cordones angioblásticos en la tercera semana", "A",
"El corazón es el primer órgano que funciona en el embrión. A mediados de la tercera semana, en el mesodermo esplácnico de la placa cardiogénica, aparecen dos cordones angioblásticos que se canalizan y forman los tubos endocárdicos. Hacia el final de esa semana se fusionan en un tubo cardíaco único, que empieza a latir alrededor del día 22 a 23. Durante la cuarta semana el tubo se pliega en asa, y entre la quinta y la octava se forman los tabiques. Por eso, las cardiopatías congénitas se originan entre la tercera y la octava semana, el periodo de mayor sensibilidad a los teratógenos, como la rubéola, el litio o el alcohol.")

D[146] = ("Saturnismo infantil en zonas mineras: encefalopatía y cólico", "B",
"Un niño que vive en un centro minero, con cambios de conducta, dolor abdominal tipo cólico y luego encefalopatía, tiene una intoxicación por plomo (saturnismo). En el Perú es un problema real en zonas como La Oroya o Cerro de Pasco. El plomo inhibe la ALA deshidratasa y la ferroquelatasa. Produce anemia microcítica con punteado basófilo, cólico saturnino, 'ribete de Burton' en las encías, bandas densas en las metáfisis y, en niños, encefalopatía con edema cerebral, además de un deterioro cognitivo irreversible. El diagnóstico es por plomo en sangre. Con niveles altos se usan quelantes: succímero oral o EDTA cálcico con dimercaprol en la encefalopatía.")
N[146] = "Varón de 9 años que vive en un centro minero. Presenta encefalopatía precedida por alteraciones de la conducta y dolor abdominal tipo cólico. Se puede diagnosticar intoxicación por:"

D[147] = ("Corteza suprarrenal: origen mesodérmico", "C",
"La glándula suprarrenal tiene doble origen. La corteza deriva del mesodermo, del epitelio celómico de la pared abdominal posterior, cerca de la cresta gonadal. Por eso comparte con la gónada la capacidad de producir esteroides y ambos órganos dependen del factor SF-1. La médula deriva del ectodermo de la cresta neural: sus células cromafines son neuronas simpáticas posganglionares modificadas que secretan adrenalina y noradrenalina. De ahí que el feocromocitoma y el neuroblastoma, tumores de la cresta neural, nazcan en la médula. En el feto, la corteza es muy grande (zona fetal) y produce DHEA para la síntesis placentaria de estrógenos.")
N[147] = "¿Cuál es el origen embriológico de la corteza suprarrenal?"
O[147] = {"C": "Mesodermo", "D": "Cresta neural"}

X[148] = "Opciones mal redactadas («ligando para VIH», «anticuerpos circulares»)"

D[149] = ("Células de Sertoli: producen hormona antimülleriana (inhibidora)", "B",
"Las células de Sertoli son las 'células nodriza' del túbulo seminífero. Sostienen la espermatogénesis, forman la barrera hematotesticular mediante uniones estrechas y producen la proteína fijadora de andrógenos (ABP). Secretan inhibina B, que frena la FSH, y aromatizan la testosterona a estradiol bajo el estímulo de la FSH. En el embrión producen la hormona antimülleriana, un factor inhibidor y no estimulante, que hace regresar los conductos de Müller. Por eso la opción B es falsa. Si falta esa hormona o su receptor, aparece el síndrome de persistencia de los conductos de Müller: un varón con útero y trompas. La testosterona la producen las células de Leydig bajo estímulo de la LH.")

D[150] = ("Metabolismo del hierro: la ferritina refleja los depósitos", "C",
"La ferritina es la proteína de depósito del hierro y su valor en el suero refleja bien las reservas corporales: una ferritina menor de 30 ng/mL confirma el déficit de hierro. Es también un reactante de fase aguda y puede estar falsamente normal o alta si hay inflamación. Las demás opciones son falsas. El ácido ascórbico favorece la absorción del hierro no hemo, porque lo reduce a su forma ferrosa (Fe2+). Los fitatos, los taninos del té, el calcio y los antiácidos la inhiben. La transferrina transporta el hierro, no lo almacena. De una dieta habitual solo se absorbe alrededor del 10 %, es decir, 1 a 2 mg al día, en el duodeno y el yeyuno proximal. La hepcidina regula la absorción.")
