# Revisión preguntas 151-200
D, O, N, X = {}, {}, {}, {}

D[151] = ("Contracción muscular: el calcio se une a la troponina C", "D",
"En el músculo estriado en reposo, la tropomiosina tapa los sitios de unión de la actina para la miosina, y el complejo de troponina (T, I y C) la mantiene en esa posición. Cuando llega el potencial de acción, el retículo sarcoplásmico libera calcio. El calcio se une a la troponina C, que cambia de forma, desplaza la tropomiosina y deja libres los sitios activos de la actina. Así se forman los puentes cruzados con la miosina y comienza la contracción. Para relajarse, la bomba SERCA devuelve el calcio al retículo, y ese proceso gasta ATP. En el músculo liso no hay troponina: el calcio se une a la calmodulina y activa la cinasa de la cadena ligera de miosina.")

D[152] = ("Noradrenalina (simpático): inhibe la motilidad intestinal", "A",
"El sistema nervioso simpático, mediante la noradrenalina, inhibe la motilidad y la secreción del tubo digestivo. Actúa sobre las neuronas del plexo entérico, reduciendo la liberación de acetilcolina, y relaja el músculo liso a través de receptores alfa-2 y beta. Además contrae los esfínteres. Por eso, en el estrés, el trauma o la cirugía abdominal hay íleo, y los alfa-2 agonistas como la clonidina estriñen. En cambio, la motilina inicia el complejo motor migratorio en ayunas, la serotonina de las células enterocromafines activa el reflejo peristáltico y la colecistocinina contrae la vesícula y estimula la motilidad del intestino delgado. La insulina no tiene un efecto directo relevante.")

D[153] = ("Tráquea: epitelio pseudoestratificado cilíndrico ciliado", "E",
"La tráquea y los bronquios están revestidos por un epitelio respiratorio típico: pseudoestratificado cilíndrico ciliado con células caliciformes. Todas sus células tocan la membrana basal, aunque sus núcleos parecen estar a distintas alturas, y de ahí el nombre 'pseudoestratificado'. Las células caliciformes secretan moco, y los cilios lo desplazan hacia la faringe; es el aparato mucociliar, que limpia partículas y bacterias. El tabaco paraliza los cilios y puede transformar el epitelio en escamoso (metaplasia escamosa), primer paso hacia el carcinoma epidermoide. En la discinesia ciliar primaria (síndrome de Kartagener) fallan los cilios, lo que causa bronquiectasias, sinusitis y situs inversus.")

D[154] = ("Esbozos de las extremidades: aparecen al final de la cuarta semana", "A",
"Los esbozos de las extremidades superiores aparecen hacia el día 26 a 27, al final de la cuarta semana, como pequeñas yemas de mesodermo cubiertas por ectodermo. Los de las inferiores aparecen uno o dos días después. En su punta, la cresta ectodérmica apical dirige el crecimiento proximodistal. Entre la quinta y la octava semana se forman los segmentos y los dedos, y las membranas interdigitales desaparecen por apoptosis. Por eso, el periodo crítico para las malformaciones de las extremidades es la cuarta a la octava semana. Ejemplo histórico: la talidomida tomada entre los días 24 y 36 causó focomelia.")

D[155] = ("LH: actúa por receptores acoplados a proteína G", "C",
"La hormona luteinizante es una glucoproteína grande e hidrosoluble que no atraviesa la membrana. Actúa sobre un receptor de membrana con siete dominios transmembrana acoplado a una proteína Gs: activa la adenilato ciclasa, aumenta el AMPc y activa la proteína cinasa A. Por la misma vía actúan la FSH, la TSH, la hCG (que usa el mismo receptor que la LH), la ACTH, el glucagón y la PTH. En el testículo, la LH estimula a las células de Leydig a producir testosterona; en el ovario, a las células de la teca a producir andrógenos, y su pico desencadena la ovulación. Los esteroides y las hormonas tiroideas actúan en cambio sobre receptores intracelulares.")

D[156] = ("Flujo sanguíneo renal: unos 1100-1200 mL/min", "C",
"Los riñones reciben alrededor del 20 al 22 % del gasto cardíaco, es decir, unos 1100 a 1200 mL de sangre por minuto en un varón de 70 kg, aunque pesan solo unos 300 g en total. Con un hematocrito del 45 %, el flujo plasmático renal es de unos 600 a 660 mL/min, y se mide con el aclaramiento de PAH. De ese plasma, el 20 % se filtra (fracción de filtración), lo que da un filtrado glomerular de unos 125 mL/min o 180 L/día. Este flujo tan alto no responde a la necesidad de oxígeno, sino a la de filtrar. El riñón lo mantiene estable entre 80 y 180 mmHg de presión arterial gracias a la autorregulación miogénica y a la retroalimentación tubuloglomerular.")

D[157] = ("Clindamicina: colitis pseudomembranosa por Clostridioides difficile", "A",
"La clindamicina es el antibiótico clásicamente asociado a la colitis pseudomembranosa. Elimina gran parte de la flora anaerobia del colon y permite que crezca Clostridioides difficile, que produce las toxinas A y B. El cuadro es diarrea acuosa, dolor abdominal, fiebre y leucocitosis. En la colonoscopía se ven placas amarillentas (pseudomembranas), y en casos graves puede haber megacolon tóxico. Hoy también se asocia mucho a las cefalosporinas y las quinolonas por su uso masivo. El diagnóstico es por toxina o PCR en heces. Tratamiento: suspender el antibiótico si es posible y dar vancomicina oral o fidaxomicina; el metronidazol se reserva para casos leves.")

D[158] = ("Bases del ADN: el uracilo es exclusivo del ARN", "E",
"El ADN tiene cuatro bases: dos purinas, adenina y guanina, y dos pirimidinas, citosina y timina. El ARN tiene las mismas, salvo que en lugar de timina tiene uracilo. La timina es un uracilo metilado; la enzima timidilato sintasa produce el dTMP a partir del dUMP. Los antineoplásicos como el 5-fluorouracilo y el metotrexato (a través del folato) atacan justo ese paso. Tener timina en lugar de uracilo permite reparar el ADN: la citosina se desamina de forma espontánea a uracilo, y la célula reconoce ese uracilo como un error y lo corrige. En el ADN, la adenina se aparea con la timina mediante dos puentes de hidrógeno, y la guanina con la citosina mediante tres.")
O[158] = {"B": "Guanina", "C": "Citosina"}

D[159] = ("Íleon y colon: intercambio de bicarbonato por cloro", "A",
"En el íleon y el colon, las células epiteliales tienen un intercambiador en la membrana apical que secreta bicarbonato hacia la luz y absorbe cloro. Eso neutraliza los ácidos que producen las bacterias del colon. Por eso, en las diarreas abundantes se pierde mucho bicarbonato y aparece acidosis metabólica con anión gap normal (hiperclorémica). En la cloridorrea congénita, un defecto de este intercambiador, el cloro no se absorbe y se pierde en las heces, con alcalosis. Ojo con las derivaciones urinarias al colon (ureterosigmoidostomía): la orina en contacto con el colon intercambia cloro por bicarbonato y produce acidosis hiperclorémica.")

D[160] = ("Trichuris trichiura: parásito hematófago del colon", "E",
"Trichuris trichiura (tricocéfalo, antes Trichocephalus dispar) introduce su extremo anterior, fino como un látigo, en la mucosa del ciego y el colon y se alimenta de sangre y tejido. En infecciones masivas causa anemia ferropénica, disentería crónica, prolapso rectal (con los gusanos visibles en la mucosa) y retraso del crecimiento en los niños. Otros hematófagos importantes son las uncinarias (Ancylostoma duodenale y Necator americanus), la principal causa parasitaria de anemia. Enterobius vive en la luz y causa prurito anal; Ascaris se alimenta del contenido intestinal; Giardia se adhiere al duodeno y causa malabsorción. Tratamiento: albendazol o mebendazol.")
O[160] = {"D": "Strongyloides stercoralis", "E": "Trichuris trichiura (Trichocephalus dispar)"}

D[161] = ("Desnutrición crónica: hiponatremia con sodio corporal total aumentado", "D",
"En la desnutrición grave, sobre todo en el kwashiorkor, la bomba Na+/K+-ATPasa falla por falta de energía y proteínas. El sodio se acumula dentro de las células y el potasio se pierde. El resultado es un sodio corporal total aumentado, con edema y retención de agua, pero con natremia baja o normal por dilución, e hipopotasemia, hipomagnesemia e hipofosfatemia. Por eso las guías de la OMS indican rehidratar a estos niños con ReSoMal, una solución con menos sodio y más potasio que la SRO estándar, y dar líquidos con cautela, porque el exceso de sodio y volumen precipita insuficiencia cardíaca. Al realimentarlos hay riesgo de síndrome de realimentación por la caída del fósforo.")

D[162] = ("Eritromicina estolato: hepatitis colestásica", "E",
"El estolato de eritromicina es la sal clásicamente asociada a hepatitis colestásica de causa inmunoalérgica. Aparece de 10 a 20 días después de iniciarla, a veces ya terminado el tratamiento, con náuseas, vómitos, dolor abdominal tipo cólico que puede simular una colecistitis, ictericia, fiebre y eosinofilia. Se resuelve al suspender el fármaco. Este niño se trató una faringoamigdalitis estreptocócica, y la eritromicina es la alternativa en los alérgicos a la penicilina. La clindamicina se asocia más a diarrea y colitis; la vancomicina, al síndrome del hombre rojo y a nefrotoxicidad; la ampicilina, a exantema, y la cefradina rara vez da daño hepático.")

D[163] = ("LH estimula a las células de Leydig", "E",
"En el varón, la LH hipofisaria actúa sobre las células de Leydig del intersticio testicular. A través de receptores acoplados a proteína G y del AMPc, activa la enzima que convierte el colesterol en pregnenolona y así estimula la síntesis de testosterona. La FSH actúa sobre las células de Sertoli: estimula la espermatogénesis, la producción de la proteína fijadora de andrógenos y la inhibina. La testosterona frena la LH por retroalimentación negativa sobre el hipotálamo y la hipófisis, y la inhibina frena la FSH. Por eso, la administración de testosterona exógena atrofia los testículos y reduce la producción de espermatozoides.")

D[164] = ("Reflejo de eyección de la leche: oxitocina", "A",
"La succión del pezón estimula terminaciones nerviosas que envían la señal al hipotálamo, a los núcleos supraóptico y paraventricular. La neurohipófisis libera entonces oxitocina, que contrae las células mioepiteliales que rodean los alvéolos y conductos mamarios y expulsa la leche: es el reflejo de eyección o 'bajada' de la leche. La prolactina de la adenohipófisis, en cambio, estimula la producción o síntesis de leche. El estrés, el dolor y la ansiedad inhiben la oxitocina y dificultan la lactancia. El llanto del bebé puede activar el reflejo por condicionamiento. La oxitocina también contrae el útero durante la lactancia, lo que ayuda a la involución uterina.")
O[164] = {"C": "Estrógenos"}

D[165] = ("Anemia perniciosa: pérdida de células parietales", "E",
"La gastritis crónica atrófica autoinmune (tipo A) afecta el cuerpo y el fondo gástrico. Se producen anticuerpos contra la bomba H+/K+-ATPasa de las células parietales y contra el factor intrínseco. Al perderse las células parietales, falta el factor intrínseco, no se absorbe la vitamina B12 en el íleon y aparece anemia megaloblástica, que puede acompañarse de glositis y degeneración combinada subaguda de la médula. También hay aclorhidria con gastrina alta, y aumenta el riesgo de tumores carcinoides y de adenocarcinoma gástrico. El tratamiento es vitamina B12 parenteral de por vida. Las células principales, o cimógenas, secretan pepsinógeno.")

D[166] = ("Células alfa del islote: glucagón", "D",
"Los islotes de Langerhans tienen varios tipos de células. Las células alfa, en la periferia del islote, producen glucagón, que eleva la glucemia estimulando la glucogenólisis y la gluconeogénesis en el hígado. Las células beta, las más numerosas y centrales, producen insulina y amilina. Las células delta producen somatostatina, que inhibe a las dos anteriores. Las células PP producen el polipéptido pancreático, y las células épsilon, grelina. La gastrina se produce en las células G del antro gástrico. Clínica: el glucagonoma produce diabetes, pérdida de peso y eritema necrolítico migratorio, y el glucagón IM o intranasal revierte la hipoglucemia grave.")

D[167] = ("Lavado gástrico: se considera en la ingesta reciente de organofosforados", "C",
"El lavado gástrico solo se considera cuando la ingesta es reciente (idealmente en la primera hora) de un tóxico potencialmente letal, como un organofosforado, y siempre con la vía aérea protegida. Está contraindicado en tres situaciones. En los cáusticos, como el hipoclorito (lejía), el ácido muriático o el permanganato de potasio, por riesgo de perforación y de volver a quemar el esófago. En los hidrocarburos, como el kerosene, por riesgo de aspiración y neumonitis química. Y en los pacientes con la vía aérea no protegida. Aun en los organofosforados, lo prioritario es la atropina y la descontaminación de la piel. Hoy el lavado se usa mucho menos que antes.")

D[168] = ("Lesión del nervio espinal accesorio (XI) en la cirugía del cuello", "E",
"El nervio espinal accesorio (XI par) inerva el esternocleidomastoideo y el trapecio. Cruza el triángulo posterior del cuello de forma superficial, por lo que se lesiona con facilidad en biopsias de ganglios, disecciones de cuello o resecciones de tumores en esa zona. Si se lesiona, el trapecio se debilita (el paciente no puede elevar el hombro, que cae, y aparece escápula alada lateral) y el esternocleidomastoideo también: no puede girar la cabeza hacia el lado contrario, porque cada ECM gira la cara hacia el lado opuesto. Este paciente no eleva el hombro derecho ni rota la cabeza a la izquierda, lo que indica una lesión del XI par derecho.")
N[168] = "Varón de 52 años operado de un tumor de la región posterosuperior del cuello que se extiende hasta el músculo esternocleidomastoideo. En el postoperatorio no puede elevar el hombro derecho ni rotar la cabeza hacia la izquierda. ¿Cuál es el nervio lesionado?"

D[169] = ("Atropinización: efecto de bloqueo colinérgico muscarínico", "B",
"Tras un intento de suicidio, probablemente con un organofosforado, el paciente recibió atropina. Ahora tiene sequedad de mucosas, midriasis y taquicardia, que son efectos de un bloqueador colinérgico muscarínico (antimuscarínico o parasimpaticolítico). Son los signos de atropinización. Las fasciculaciones persisten porque la atropina no bloquea los receptores nicotínicos de la placa motora. Para ellos se usa la pralidoxima, que reactiva la acetilcolinesterasa si se da antes del 'envejecimiento' de la enzima. Si aparecen fiebre, delirio o íleo, hay exceso de atropina y se debe espaciar o reducir. Un agonista colinérgico o parasimpaticomimético daría lo contrario: miosis, sialorrea y bradicardia.")

D[170] = ("Translocación cromosómica", "D",
"La translocación es el intercambio o la transferencia de todo o parte de un cromosoma a otro no homólogo. Puede ser recíproca, cuando dos cromosomas intercambian segmentos, o robertsoniana, cuando dos cromosomas acrocéntricos (13, 14, 15, 21, 22) se fusionan por el centrómero y se pierden los brazos cortos. Si la translocación está balanceada, el portador suele estar sano, pero tiene riesgo de abortos y de hijos con desequilibrios, como el síndrome de Down por t(14;21). Ejemplos en cáncer: t(9;22) o cromosoma Filadelfia en la LMC, t(8;14) en el linfoma de Burkitt y t(15;17) en la leucemia promielocítica. La inversión es un giro de 180 grados de un segmento dentro del mismo cromosoma.")

D[171] = ("Errores innatos del metabolismo: herencia autosómica recesiva", "C",
"La gran mayoría de los errores innatos del metabolismo se heredan de forma autosómica recesiva. Suelen deberse a la falta de una enzima, y basta con la mitad de la actividad enzimática (heterocigoto) para funcionar con normalidad. Por eso los padres portadores están sanos y cada hijo tiene un 25 % de riesgo; la consanguinidad lo aumenta. Ejemplos: fenilcetonuria, galactosemia, enfermedad de la orina de jarabe de arce, glucogenosis, la mayoría de las enfermedades lisosomales y la fibrosis quística. Las excepciones ligadas al X son la adrenoleucodistrofia, el déficit de ornitina transcarbamilasa y las enfermedades de Fabry y de Hunter. Por eso existe el tamizaje neonatal.")

D[172] = ("Acalasia: déficit de neuronas inhibitorias (VIP y óxido nítrico)", "C",
"En la acalasia se pierden de forma selectiva las neuronas inhibitorias del plexo mientérico del esófago, las que liberan óxido nítrico y péptido intestinal vasoactivo (VIP). Sin ellas, el esfínter esofágico inferior no se relaja al deglutir, su presión aumenta y el cuerpo del esófago pierde el peristaltismo. La paciente presenta disfagia para sólidos y líquidos, regurgitación, dolor retroesternal y pérdida de peso. En el esofagograma se ve el esófago dilatado en 'pico de pájaro', y el diagnóstico se confirma con manometría de alta resolución. Las neuronas excitatorias colinérgicas se conservan más. En Sudamérica, la enfermedad de Chagas produce un cuadro igual.")
N[172] = "Mujer de 30 años, natural de Arequipa, acude por sensación de llenura y dolor retroesternal con regurgitación de alimentos. El esofagograma contrastado muestra acalasia. ¿Cuál es el neurotransmisor cuya liberación es deficiente?"

D[173] = ("Biodisponibilidad: la vía oral es la menor", "A",
"La biodisponibilidad es la fracción de la dosis que llega intacta a la circulación sistémica. Por definición, la vía endovenosa tiene el 100 %. La vía oral suele tener la menor, por varios motivos: la absorción intestinal es incompleta, el ácido y las enzimas degradan parte del fármaco, la glicoproteína P lo expulsa de nuevo a la luz y, sobre todo, existe el efecto de primer paso hepático, porque toda la sangre del intestino pasa por el hígado antes de llegar a la circulación. Las vías intramuscular y subcutánea suelen tener una biodisponibilidad cercana al 100 %, aunque se absorben más lento. La sublingual y la rectal inferior evitan en parte el primer paso.")

D[174] = ("Pérdida de cargas de la membrana basal y daño podocitario: proteinuria masiva", "A",
"La barrera glomerular es selectiva por tamaño y por carga. La membrana basal tiene cargas negativas por el heparán sulfato, que repelen la albúmina, también negativa. Además, los pedicelos de los podocitos con su diafragma de hendidura impiden el paso de proteínas. Si se pierden las cargas negativas y se amplían los poros entre los podocitos, la albúmina y otras proteínas pasan en gran cantidad: proteinuria masiva, mayor de 3,5 g/día en adultos, típica del síndrome nefrótico, con hipoalbuminemia, edema e hiperlipidemia. La microalbuminuria (30 a 300 mg/día) es un marcador precoz de daño, como en la nefropatía diabética. La hematuria indica síndrome nefrítico.")

D[175] = ("Esófago: epitelio plano estratificado no queratinizado", "C",
"El esófago está revestido por epitelio plano o escamoso estratificado no queratinizado, que resiste la fricción del bolo alimenticio. El estómago, el duodeno, el íleon y el colon tienen epitelio cilíndrico simple, especializado en secretar y absorber. En la unión esofagogástrica (línea Z) cambia de forma brusca de escamoso a cilíndrico. En el reflujo crónico, el epitelio escamoso del esófago distal puede transformarse en cilíndrico con células caliciformes: es el esófago de Barrett, una metaplasia intestinal precursora del adenocarcinoma de esófago. En cambio, el carcinoma epidermoide nace del epitelio escamoso propio, con el tabaco, el alcohol y las bebidas muy calientes como factores de riesgo.")
O[175] = {"E": "Duodeno"}

D[176] = ("Conducción AV: el impulso pasa a los ventrículos por el haz de His", "D",
"El impulso nace en el nodo sinusal, recorre las aurículas (el haz de Bachmann lleva el impulso a la aurícula izquierda) y los haces internodales (anterior, medio o de Wenckebach, y posterior o de Thorel), y llega al nodo auriculoventricular. En el corazón normal, el único camino eléctrico entre aurículas y ventrículos es el haz de His, que atraviesa el esqueleto fibroso. Se divide en rama derecha y rama izquierda, y esta en fascículos anterior y posterior, que terminan en la red de Purkinje. Si existe una vía accesoria (haz de Kent), el impulso llega antes a los ventrículos: PR corto y onda delta del síndrome de Wolff-Parkinson-White.")
O[176] = {"A": "Haz de Bachmann", "B": "Haz de Wenckebach", "C": "Haz de Thorel", "D": "Haz de His"}
N[176] = "¿Por qué estructura pasa normalmente el impulso eléctrico de las aurículas a los ventrículos?"

D[177] = ("Rodilla: diartrosis (sinovial) de tipo bicondílea", "C",
"Las articulaciones se clasifican por su movilidad en tres grupos: sinartrosis, inmóviles, como las suturas del cráneo; anfiartrosis, semimóviles, como la sínfisis del pubis o los discos intervertebrales, y diartrosis, móviles y sinoviales. La rodilla es una diartrosis: tiene cápsula, membrana sinovial y cavidad con líquido sinovial, además de meniscos y ligamentos cruzados. Por su forma es bicondílea, aunque funciona casi como una tróclea, con flexión y extensión y algo de rotación cuando está flexionada. La enartrosis es otro subtipo de diartrosis, esférica, como la cadera o el hombro. La rodilla es la articulación sinovial más grande y la que más se lesiona en los deportes.")
O[177] = {"E": "Trocoide"}

D[178] = ("Tetraciclinas: los efectos gastrointestinales son los más frecuentes", "C",
"El efecto adverso más frecuente de las tetraciclinas es gastrointestinal: náuseas, vómitos, molestias epigástricas y sobre todo diarrea. Se debe tanto a la irritación directa como a la alteración de la flora intestinal. La doxiciclina puede además producir úlceras esofágicas si se toma sin agua o acostado. Otros efectos característicos, aunque menos comunes: fotosensibilidad; tinción de los dientes e hipoplasia del esmalte, por lo que se evitan en menores de 8 años y en gestantes; depósito en el hueso en crecimiento; hepatotoxicidad a dosis altas, sobre todo en el embarazo; síndrome de Fanconi con tetraciclinas caducadas, e hipertensión intracraneal benigna. Su absorción disminuye con lácteos, hierro y antiácidos.")
O[178] = {"D": "Exantema (rash)"}

D[179] = ("Reanimación inicial del shock: cristaloide isotónico (NaCl 0,9 % o Ringer)", "D",
"En la reanimación inicial de casi todos los tipos de shock se usan cristaloides isotónicos: cloruro de sodio al 0,9 % (suero fisiológico) o lactato de Ringer, en bolos de 20 a 30 mL/kg, con evaluación frecuente. Son baratos, están disponibles y expanden el volumen intravascular. Los coloides y la albúmina no han mostrado mejor sobrevida en la mayoría de los pacientes, y algunos almidones dañan el riñón. El suero hipertónico al 3 % se usa en la hiponatremia sintomática y en la hipertensión endocraneana, no en la reanimación rutinaria. El cloruro de sodio al 20 % es un concentrado para diluir y nunca se da directo. En el shock hemorrágico se pasa pronto a hemoderivados.")
O[179] = {"C": "Cloruro de sodio al 20 %", "D": "Cloruro de sodio al 0,9 %", "E": "Cloruro de sodio al 3 %"}

D[180] = ("Diuréticos de asa: rama ascendente gruesa del asa de Henle", "C",
"La furosemida, la bumetanida y la torasemida inhiben el cotransportador Na+/K+/2Cl- (NKCC2) en la membrana luminal de la rama ascendente gruesa del asa de Henle. Como este segmento reabsorbe un 25 % del sodio filtrado, son los diuréticos más potentes (de 'techo alto'). También disminuyen el gradiente de la médula renal, así que la orina no puede concentrarse ni diluirse al máximo, y aumentan la eliminación de calcio y magnesio. Las tiazidas actúan en el túbulo contorneado distal, con el cotransportador Na+/Cl-; la acetazolamida, en el túbulo proximal, y la espironolactona y la amilorida, en el colector. El síndrome de Bartter imita el efecto de los diuréticos de asa.")

D[181] = ("Cromoglicato sódico: estabilizador de mastocitos", "E",
"El cromoglicato sódico y el nedocromilo estabilizan la membrana de los mastocitos y evitan que liberen histamina, leucotrienos y otros mediadores cuando llega el alérgeno. Por eso sirven solo como tratamiento preventivo, no en la crisis. Se usan en asma leve por ejercicio o alérgica, en rinitis y en conjuntivitis alérgica, y tienen muy pocos efectos adversos. Diferencias con los otros: el omalizumab es un anticuerpo anti-IgE; el montelukast bloquea el receptor de los leucotrienos; la teofilina inhibe la fosfodiesterasa y bloquea la adenosina, con un margen terapéutico estrecho, y el ipratropio es un anticolinérgico inhalado. El ketotifeno es otro estabilizador con acción antihistamínica.")

D[182] = ("Carbamatos: síndrome colinérgico reversible", "C",
"Sialorrea, náuseas, vómitos, miosis y fasciculaciones forman el síndrome colinérgico por inhibición de la acetilcolinesterasa. De las opciones, la intoxicación por carbamatos (insecticidas como el aldicarb, conocido como 'Tres Pasitos', el carbaryl y el propoxur) es la única que lo explica. Los carbamatos inhiben la enzima de forma reversible: el cuadro es más corto y la barrera hematoencefálica los deja pasar poco, así que dan menos síntomas centrales que los organofosforados. El tratamiento es con atropina. La pralidoxima es innecesaria porque la enzima se recupera sola en horas. El asma, la intoxicación alcohólica o el edema pulmonar no producen miosis con fasciculaciones.")

D[183] = ("Células de Kupffer: macrófagos de los sinusoides hepáticos", "B",
"Las células de Kupffer son macrófagos residentes que recubren la pared de los sinusoides hepáticos. Son el mayor grupo de macrófagos fijos del organismo. Retiran de la sangre portal bacterias, endotoxinas, eritrocitos envejecidos y complejos inmunes, y liberan citocinas en la inflamación hepática. Las células de Ito, o estrelladas, están en el espacio de Disse: almacenan vitamina A y, al activarse, se transforman en miofibroblastos que producen colágeno y causan la fibrosis y la cirrosis. Las células de Merkel son mecanorreceptores de la piel, las criptas de Lieberkühn son glándulas intestinales y las células de Paneth secretan lisozima y defensinas en esas criptas.")
O[183] = {"C": "Lieberkühn", "E": "Paneth"}

D[184] = ("Aclimatación a la altura: la primera respuesta es la hiperventilación", "E",
"Al subir a 3800 m, la presión de oxígeno del aire inspirado baja y cae la PaO2. Los quimiorreceptores periféricos de los cuerpos carotídeos lo detectan de inmediato y aumentan la ventilación pulmonar, que es la respuesta más rápida. La hiperventilación eleva la PO2 alveolar pero produce alcalosis respiratoria. En los días siguientes, el riñón elimina bicarbonato para compensarla. La eritropoyetina aumenta desde las primeras horas, pero el aumento de los eritrocitos y del hematocrito tarda semanas. También aumentan con el tiempo el 2,3-DPG, la capilaridad de los tejidos y las mitocondrias. La acetazolamida acelera la aclimatación porque acidifica la sangre y estimula la ventilación.")

D[185] = ("Acetazolamida en el mal de altura: inhibe la anhidrasa carbónica", "C",
"La acetazolamida inhibe la anhidrasa carbónica en el túbulo proximal y produce pérdida de bicarbonato por la orina. Así causa una acidosis metabólica leve que estimula a los quimiorreceptores y aumenta la ventilación, contrarrestando el freno que la alcalosis respiratoria de la altura pone a la respiración. De este modo acelera la aclimatación, previene el mal de montaña agudo y mejora la respiración periódica durante el sueño. La dosis preventiva habitual es de 125 mg cada 12 horas, empezando un día antes del ascenso. Efectos adversos: parestesias, sabor metálico en las bebidas gaseosas y poliuria. Está contraindicada en la alergia grave a sulfonamidas.")
O[185] = {"A": "Antagonista de la aldosterona", "D": "Inhibición de la bomba Na+/K+/2Cl-", "B": "Inhibición del cotransportador Na+/Cl-"}

D[186] = ("Glaucoma de ángulo cerrado: contraindicados los anticolinérgicos", "C",
"Los anticolinérgicos, como la atropina, la escopolamina, los antiespasmódicos del tipo de la hioscina y los antidepresivos tricíclicos, producen midriasis. Al dilatar la pupila, el iris se engrosa en la periferia y puede cerrar el ángulo iridocorneal, bloqueando la salida del humor acuoso. Esto desencadena una crisis aguda de glaucoma de ángulo cerrado: ojo rojo y doloroso, visión borrosa con halos, pupila fija en midriasis media, ojo duro a la palpación, náuseas y vómitos. Es una urgencia. En el glaucoma de ángulo abierto el riesgo es mucho menor, pero se prefiere evitarlos. Tratamiento de la crisis: pilocarpina, timolol, acetazolamida, manitol y luego iridotomía con láser.")

D[187] = ("Interacciones del ketoconazol: la rifampicina reduce sus niveles", "B",
"La rifampicina es un potente inductor del citocromo P450, sobre todo del CYP3A4, y de la glicoproteína P. Acelera tanto el metabolismo del ketoconazol y de otros azoles que sus niveles caen a valores ineficaces, lo que explica la falta de respuesta. A la vez, el ketoconazol puede reducir la absorción de la rifampicina. Por eso no se deben combinar. El ketoconazol también necesita un medio ácido para absorberse, así que los antiácidos, los anti-H2 y los inhibidores de la bomba de protones reducen su efecto. Por el contrario, el ketoconazol inhibe el CYP3A4 y aumenta los niveles de otros fármacos, como la amiodarona y las estatinas. Hoy casi no se usa por vía oral por su hepatotoxicidad.")
O[187] = {"D": "Paracetamol"}

D[188] = ("Enfermedad hemolítica del recién nacido: IgG anti-D cruza la placenta", "D",
"La IgG es la única inmunoglobulina que atraviesa la placenta, gracias al receptor FcRn del sincitiotrofoblasto. En la isoinmunización Rh, una madre Rh negativa se sensibiliza al exponerse a hematíes Rh positivos, en un parto previo, un aborto, un trauma o un procedimiento. En el siguiente embarazo con un feto Rh positivo, sus anticuerpos IgG anti-D cruzan la placenta y hemolizan los eritrocitos fetales. El resultado es anemia, hidropesía fetal, e ictericia y kernícterus en el recién nacido. La IgM, que es grande, no cruza la placenta. La prevención es la inmunoglobulina anti-D a las 28 semanas y dentro de las 72 horas después del parto, si el recién nacido es Rh positivo.")
O[188] = {"A": "IgA", "B": "IgM", "C": "IgD", "D": "IgG", "E": "IgE"}

D[189] = ("Carotenemia: seudoictericia con escleras blancas", "A",
"La carotenemia es una coloración amarilla-naranja de la piel por exceso de carotenos en la sangre, generalmente por comer mucha zanahoria, zapallo, papaya o mango, o por hipotiroidismo, diabetes, anorexia o enfermedad renal. El caroteno se deposita en la capa córnea, por eso predomina en las palmas, las plantas y los surcos nasogenianos. La clave para diferenciarla de la ictericia es que las escleras se mantienen blancas y la bilirrubina es normal. En la ictericia verdadera, la bilirrubina tiene gran afinidad por la elastina de la esclera, que se tiñe primero. Es benigna y desaparece al moderar el consumo. La vitamina A no se eleva hasta niveles tóxicos, porque su conversión está regulada.")

D[190] = ("Déficit de zinc: acrodermatitis, alopecia y diarrea", "C",
"La tríada de dermatitis acral y periorificial, alopecia y diarrea es típica del déficit de zinc. Su forma hereditaria es la acrodermatitis enteropática, autosómica recesiva, por un defecto del transportador intestinal ZIP4. Aparece al destetar al lactante de la leche materna, que tiene un factor que favorece la absorción del zinc. Las lesiones son placas eritematosas, descamativas o ampollosas alrededor de la boca, el ano y en manos y pies. Hay también retraso del crecimiento, irritabilidad, cicatrización lenta e infecciones. La forma adquirida se ve en desnutrición, nutrición parenteral sin oligoelementos, alcoholismo y enfermedad inflamatoria intestinal. Responde de forma rápida y espectacular al zinc oral.")

X[191] = "Repite la 127 (atropina en intoxicación por organofosforados en niños)"

D[192] = ("Cáncer gástrico precoz: limitado a mucosa y submucosa", "B",
"El cáncer gástrico precoz o temprano (early gastric cancer) se define como el adenocarcinoma limitado a la mucosa o a la submucosa (T1), sin importar si hay metástasis en los ganglios linfáticos. Si llega a la muscular propia, ya es un cáncer avanzado. La clasificación japonesa lo divide en tipos macroscópicos: I protruido, II superficial (IIa elevado, IIb plano, IIc deprimido) y III excavado. Su pronóstico es excelente, con una sobrevida a 5 años mayor del 90 %. Los tumores pequeños, limitados a la mucosa y bien diferenciados pueden resecarse por endoscopía (disección submucosa). Por eso, en países con alta incidencia, como Japón y Corea, se hace tamizaje endoscópico.")
N[192] = "El cáncer gástrico precoz se define como el que invade como máximo hasta la capa:"

X[193] = "Varias afirmaciones son correctas a la vez (prazoles más potentes, anti-H2)"

D[194] = ("Absorción del hierro: mejor en forma ferrosa y en ayunas", "A",
"La afirmación incorrecta es A. El hierro se absorbe en el duodeno y el yeyuno proximal sobre todo en su forma ferrosa (Fe2+), a través del transportador DMT1. El hierro férrico (Fe3+) de los alimentos debe reducirse primero, gracias a la citocromo b duodenal y al ácido ascórbico. Por eso los suplementos se prescriben como sales ferrosas (sulfato ferroso) y se toman en ayunas o con jugo de naranja, lejos de los lácteos, el té y los antiácidos. Las demás son correctas: la mayor parte del agua se absorbe en el intestino delgado; la B12 y las sales biliares, en el íleon terminal, y la insuficiencia pancreática puede causar déficit de B12, porque faltan las proteasas que la liberan de la haptocorrina.")

X[195] = "Opciones confusas («cortejo vegetativo», «hiperpotasemia falsa»); clave poco clara"

D[196] = ("Pelagra: déficit de niacina (vitamina B3)", "B",
"La pelagra se debe al déficit de niacina (vitamina B3, ácido nicotínico) o de su precursor, el triptófano. Se reconoce por las '3 D': dermatitis en zonas expuestas al sol (el 'collar de Casal' en el cuello), diarrea y demencia; si no se trata, se añade una cuarta D, la muerte. Es típica de las dietas basadas en maíz sin nixtamalizar, del alcoholismo y de la isoniacida, que agota la piridoxina necesaria para sintetizar niacina. También aparece en el síndrome carcinoide, porque el tumor consume el triptófano para producir serotonina, y en la enfermedad de Hartnup, por falta de absorción del triptófano. Se trata con nicotinamida oral.")
X[299] = "Repite la 196 (pelagra por déficit de niacina)"

D[197] = ("Organofosforados: la taquicardia no descarta el diagnóstico", "A",
"La paciente tiene sudoración, sialorrea, pupilas mióticas (2 mm), fasciculaciones faciales, roncantes y sibilancias por broncorrea y broncoespasmo, y alteración de la conciencia. Es un síndrome colinérgico muscarínico, nicotínico y central, típico de la intoxicación por organofosforados. La taquicardia no lo descarta: aparece por estimulación nicotínica de los ganglios simpáticos, por la hipoxia o por el estrés. Las benzodiacepinas no dan secreciones ni fasciculaciones. La crisis asmática no explica la miosis ni la sialorrea. El estado postictal y la hipoglucemia no causan este cuadro colinérgico. El tratamiento es con atropina hasta secar las secreciones, con pralidoxima y soporte ventilatorio.")
N[197] = "Mujer de 20 años encontrada inconsciente en casa. Al examen: soporosa, sudorosa y con rubicundez facial, sialorrea persistente, pupilas reactivas de 2 mm, fasciculaciones en la cara, roncantes y sibilantes difusos en ambos campos pulmonares y taquicardia sinusal. Al estímulo moviliza las 4 extremidades. ¿Cuál es el diagnóstico probable?"

D[198] = ("Síntesis de colesterol: la HMG-CoA reductasa es la enzima limitante", "A",
"La hidroximetilglutaril-CoA reductasa (HMG-CoA reductasa) convierte la HMG-CoA en mevalonato en el retículo endoplasmático. Es el paso limitante y regulado de la síntesis de colesterol. La insulina la activa; el glucagón y el propio colesterol la inhiben, este último por retroalimentación. Las estatinas son inhibidores competitivos de esta enzima: bajan el colesterol dentro del hepatocito, lo que aumenta los receptores de LDL en su superficie y reduce el LDL plasmático en un 30 a 50 %. Además tienen efectos pleiotrópicos, como estabilizar la placa. Se toman de preferencia de noche si son de vida media corta, porque la síntesis de colesterol es mayor durante la noche. La lipoproteinlipasa hidroliza triglicéridos.")

D[199] = ("Heparinas de bajo peso molecular: se monitorizan con anti-Xa, no con TTPA", "D",
"La afirmación incorrecta es D. Las heparinas de bajo peso molecular, como la enoxaparina, se administran por vía subcutánea, tienen una respuesta predecible y un menor riesgo de trombocitopenia inducida por heparina. En general no requieren control. Cuando hace falta, en la insuficiencia renal, la obesidad extrema o el embarazo, se mide la actividad anti-Xa, porque apenas alargan el TTPA. La heparina no fraccionada (sódica) sí se ajusta con el TTPA. Las demás son correctas: las proteínas C y S inactivan los factores Va y VIIIa; los antagonistas de la vitamina K (warfarina) se controlan con el INR y alteran sobre todo la vía extrínseca (factor VII), y la heparina actúa a través de la antitrombina.")

D[200] = ("Fase 0 del potencial de acción ventricular: entrada rápida de sodio", "A",
"El potencial de acción del miocito ventricular tiene cinco fases. La fase 0 es una despolarización rápida por la apertura de los canales de sodio dependientes de voltaje (aumento de la conductancia al sodio). La fase 1 es una repolarización precoz por la salida transitoria de potasio. La fase 2, o meseta, se debe al equilibrio entre la entrada de calcio por canales tipo L y la salida de potasio. La fase 3, la repolarización, se debe a la salida de potasio. La fase 4 es el reposo, mantenido por los canales de potasio y la bomba Na+/K+-ATPasa. Los antiarrítmicos de clase I (lidocaína, flecainida) bloquean los canales de sodio y enlentecen la fase 0; en cambio, en el nodo sinusal la fase 0 depende del calcio.")
