# Revisión preguntas 201-250
D, O, N, X = {}, {}, {}, {}

D[201] = ("Meseta del potencial cardíaco: el calcio sostiene la contractilidad", "B",
"La meseta (fase 2) del potencial de acción del miocito ventricular dura unos 200 a 300 ms y se debe a la entrada de calcio por los canales tipo L (receptores de dihidropiridina). Ese calcio que entra hace que el retículo sarcoplásmico libere mucho más calcio a través de los receptores de rianodina; es la 'liberación de calcio inducida por calcio'. Así, determina directamente la fuerza de contracción: cuanto más calcio entra, mayor es la contractilidad. Además, la meseta prolonga el periodo refractario y evita la tetania cardíaca. Por eso los bloqueadores de los canales de calcio, como el verapamilo y el diltiazem, son inotrópicos negativos, y los agonistas beta aumentan la contractilidad al fosforilar esos canales.")

D[202] = ("Acidosis metabólica con compensación respiratoria adecuada", "A",
"Primero se mira el pH: 7,20 indica acidemia. Luego se busca la causa primaria: el bicarbonato está bajo (15 mEq/L), así que es una acidosis metabólica. Después se comprueba la compensación con la fórmula de Winter: la PCO2 esperada es 1,5 × 15 + 8 = 30,5 ± 2 mmHg. La PCO2 medida (30 mmHg) está en ese rango, por lo que la compensación respiratoria es adecuada y el trastorno es una acidosis metabólica simple. No es 'compensada' en el sentido de un pH normal, porque la compensación nunca normaliza del todo el pH. Si la PCO2 fuera mayor de 32,5 habría además una acidosis respiratoria (mixta), y si fuera menor de 28,5, una alcalosis respiratoria asociada. El siguiente paso es calcular el anión gap.")
O[202] = {"C": "Acidosis metabólica con pH normal (totalmente compensada)"}

D[203] = ("Acidosis metabólica con anión gap elevado: salicilatos", "E",
"El anión gap (Na - (Cl + HCO3), normal de 8 a 12) aumenta cuando se acumulan ácidos no medidos. Las causas se recuerdan con el acrónimo 'MUDPILES': metanol, uremia, cetoacidosis diabética, paraldehído y propilenglicol, isoniacida y hierro, ácido láctico, etilenglicol y salicilatos. La aspirina en sobredosis produce al principio alcalosis respiratoria, porque estimula el centro respiratorio, y luego acidosis metabólica con anión gap alto, porque desacopla la fosforilación oxidativa y aumenta el lactato y los cetoácidos. En cambio, la diarrea, las fístulas, la ureterosigmoidostomía, el cloruro de amonio y la acidosis tubular renal producen acidosis hiperclorémica, con anión gap normal.")

D[204] = ("Tiazidas: causa farmacológica frecuente de hiponatremia", "A",
"Las tiazidas, como la hidroclorotiazida, son los diuréticos que más a menudo causan hiponatremia, sobre todo en mujeres adultas mayores y de bajo peso, con frecuencia en las primeras semanas de uso. Actúan en el túbulo distal, en la corteza, así que no alteran el gradiente de la médula: el paciente pierde sodio pero mantiene la capacidad de concentrar la orina y reabsorber agua libre por la acción de la ADH. Además causan pérdida de potasio. Los diuréticos de asa, en cambio, reducen el gradiente medular, impiden concentrar la orina y producen menos hiponatremia; por eso se usan para tratar el SIADH junto con restricción de agua y sal. El manitol puede causar hiponatremia por dilución.")
O[204] = {"A": "Hidroclorotiazida"}

D[205] = ("Tabique nasal óseo: lámina perpendicular del etmoides y vómer", "C",
"El tabique nasal tiene una parte ósea posterior y otra cartilaginosa anterior. La parte ósea la forman sobre todo la lámina perpendicular del etmoides (arriba y adelante) y el vómer (atrás y abajo), con pequeñas contribuciones de las crestas de los huesos maxilar, palatino y nasal. La parte anterior es el cartílago septal (cuadrangular). En la zona anteroinferior del tabique está el área de Kiesselbach, donde se unen ramas de las arterias etmoidal anterior, esfenopalatina, palatina mayor y labial superior; es el origen del 90 % de las epistaxis anteriores. Un golpe en el tabique puede formar un hematoma, que hay que drenar pronto para evitar la necrosis del cartílago y la nariz en silla de montar.")

X[206] = "Repite la 60 (N-acetilcisteína en la intoxicación por paracetamol)"

D[207] = ("Glándulas sebáceas: secreción holocrina", "B",
"Las glándulas se clasifican por cómo liberan su producto. En la secreción holocrina, la célula entera se llena de secreción, muere y se desintegra, y su contenido forma el producto; es el caso de las glándulas sebáceas, que producen sebo y desembocan en el folículo piloso. En la merocrina o ecrina, la secreción sale por exocitosis sin dañar la célula; es el caso de la mayoría de las glándulas sudoríparas, las salivales y el páncreas. En la apocrina se pierde la parte apical de la célula junto con la secreción; es el caso de la glándula mamaria (los lípidos) y de las glándulas sudoríparas apocrinas de las axilas y las ingles. Las sebáceas participan en el acné, bajo el estímulo de los andrógenos.")

D[208] = ("Meromelia: ausencia parcial de una extremidad", "B",
"Las malformaciones de las extremidades se nombran según lo que falta. La amelia es la ausencia completa de una o más extremidades. La meromelia es la ausencia parcial, por ejemplo la falta de manos o pies. La focomelia es un tipo de meromelia en el que faltan los huesos largos y las manos o los pies nacen casi directamente del tronco, como en las 'aletas de foca'; fue la malformación típica de la talidomida. La sirenomelia es la fusión de las extremidades inferiores. La braquicefalia es una forma del cráneo y el sinfalangismo, la fusión de falanges. Estas malformaciones se originan entre la cuarta y la octava semana, cuando se forman los esbozos de las extremidades.")
O[208] = {"C": "Sirenomelia"}

D[209] = ("Dermatoma del ombligo: T10", "A",
"El ombligo corresponde al dermatoma T10, un punto de referencia clásico en la exploración de la sensibilidad y en la anestesia. Otras referencias útiles: T4 corresponde al pezón; T6, al apéndice xifoides; T12 a L1, a la región inguinal; L4, a la rótula y la cara medial de la pierna; L5, al dorso del pie y el primer dedo, y S1, al borde lateral del pie y el talón. El dolor visceral de la apendicitis empieza en la región periumbilical porque las fibras aferentes del apéndice entran a la médula por T10. En la anestesia espinal para una cesárea se busca un bloqueo sensitivo que llegue a T4.")

D[210] = ("Irrigación de la vagina: tercio superior por la arteria uterina", "A",
"La vagina recibe irrigación de varias arterias, en distintos niveles. El tercio superior depende de las ramas vaginales (cervicovaginales) de la arteria uterina. El tercio medio depende de la arteria vaginal, rama de la ilíaca interna o equivalente a la vesical inferior del varón. El tercio inferior depende de ramas de la arteria rectal media y de la pudenda interna. Todas forman anastomosis longitudinales, las arterias ácigos de la vagina. El drenaje linfático sigue el mismo patrón: el tercio superior drena a los ganglios ilíacos, y el inferior, a los inguinales superficiales. Esto importa para estadificar el cáncer de vagina y de cuello uterino.")
O[210] = {"D": "Arteria rectal media", "C": "Arteria vaginal (rama de la ilíaca interna)"}

D[211] = ("Células de Sertoli: sostén y maduración de los espermatozoides", "B",
"Las células de Sertoli se extienden desde la membrana basal del túbulo seminífero hasta la luz y rodean a las células germinales en todas sus etapas. Les dan sostén físico, nutrición y señales. Forman la barrera hematotesticular, que protege a las células en meiosis del sistema inmune. Producen la proteína fijadora de andrógenos, que mantiene alta la testosterona dentro del túbulo, y fagocitan el citoplasma sobrante durante la espermiogénesis, cuando la espermátide se transforma en espermatozoide. Responden a la FSH y producen inhibina. Las células de Leydig producen testosterona. La maduración final, con la motilidad y la capacidad de fecundar, se completa en el epidídimo.")
O[211] = {"A": "Células mioides peritubulares", "D": "Células de Paneth", "E": "Células de Hofbauer"}

D[212] = ("Síndrome del hombre rojo: infusión rápida de vancomicina", "A",
"El síndrome del hombre rojo aparece durante o poco después de una infusión rápida de vancomicina: eritema y prurito en la cara, el cuello y la parte superior del tronco, y a veces hipotensión y angioedema. No es una alergia mediada por IgE: la vancomicina degranula directamente a los mastocitos (por el receptor MRGPRX2) y libera histamina. Se previene infundiendo la dosis en al menos 60 minutos (o 10 mg/min) y, si hace falta, con antihistamínicos previos. Si ocurre, se detiene la infusión, se dan antihistamínicos y luego se reinicia más lento. Otros efectos de la vancomicina son la nefrotoxicidad y la ototoxicidad, que aumentan si se usa junto con aminoglucósidos.")

D[213] = ("Síndrome anticolinérgico por plantas (chamico, floripondio)", "B",
"Un agricultor con midriasis, piel seca y euforia o agitación presenta un síndrome anticolinérgico. En el Perú, la causa rural clásica son las plantas con alcaloides tropánicos (atropina, escopolamina e hiosciamina): el chamico (Datura stramonium) y el floripondio o 'toé' (Brugmansia), que se ingieren por accidente o con fines rituales o delictivos ('burundanga'). La clave es la piel seca: los simpaticomiméticos como la cocaína y el crack también dan midriasis y euforia, pero con sudoración profusa. La heroína causa miosis, y la marihuana, ojos rojos sin midriasis marcada. Tratamiento: soporte, benzodiacepinas si hay agitación y, en casos graves, fisostigmina.")
N[213] = "Un agricultor es encontrado por su familia eufórico, con pupilas midriáticas y piel seca. ¿Cuál es la causa probable de la intoxicación?"
O[213] = {"B": "Plantas con alcaloides tropánicos (chamico, floripondio)"}

X[214] = "Repite la 107 (diagnóstico de intoxicación por organofosforados)"

D[215] = ("Antituberculosos en la gestación: evitar la estreptomicina", "C",
"La estreptomicina, como los demás aminoglucósidos, atraviesa la placenta y puede dañar el octavo par del feto, con sordera congénita irreversible. Por eso está contraindicada en el embarazo. Los fármacos de primera línea (isoniacida, rifampicina, etambutol y, según la norma técnica peruana, también pirazinamida) se consideran seguros en la gestación, porque el riesgo de una tuberculosis no tratada es mucho mayor. A la gestante que recibe isoniacida se le añade piridoxina para prevenir la neuropatía. La lactancia se permite. Entre los fármacos de segunda línea, también se evitan los inyectables (amikacina, kanamicina, capreomicina) y, en lo posible, la etionamida.")
O[215] = {"A": "Isoniacida", "D": "Etambutol", "E": "Pirazinamida"}
N[215] = "¿Cuál es el antituberculoso contraindicado en la gestación?"

D[216] = ("Terapia combinada antipseudomonas: betalactámico + aminoglucósido", "C",
"En las infecciones graves por Pseudomonas aeruginosa (neutropenia febril, sepsis, neumonía asociada a ventilación), la combinación clásica es un betalactámico antipseudomonas (piperacilina-tazobactam, ceftazidima, cefepime o un carbapenémico) más un aminoglucósido (amikacina, gentamicina, tobramicina). El betalactámico daña la pared bacteriana y facilita la entrada del aminoglucósido, lo que produce sinergia. Además, se amplía la cobertura empírica mientras llega el antibiograma, frente a cepas resistentes. Una vez que se conoce la sensibilidad, suele bastar un solo fármaco activo. Los macrólidos no cubren Pseudomonas, y un betalactámico solo, al inicio, puede no alcanzar si hay riesgo de resistencia.")
O[216] = {"D": "Betalactámicos solos", "E": "Tetraciclinas + cloranfenicol"}
N[216] = "¿Cuál es la mejor combinación antibiótica empírica contra Pseudomonas aeruginosa en una infección grave?"

D[217] = ("Nociceptores: terminaciones nerviosas libres", "D",
"El dolor se detecta con los nociceptores, que son terminaciones nerviosas libres, sin cápsula, de fibras A-delta y C. Están en la piel, los músculos, las articulaciones y las vísceras. Algunos responden a estímulos mecánicos intensos, otros a la temperatura extrema y otros son polimodales. Las sustancias de la inflamación (bradicinina, prostaglandinas, histamina, potasio, sustancia P) los sensibilizan, lo que explica la hiperalgesia; por eso los AINE alivian el dolor al inhibir las prostaglandinas. Los receptores encapsulados detectan otras cosas: el corpúsculo de Pacini la vibración y la presión profunda; el de Meissner, el tacto fino; el disco de Merkel, la presión sostenida, y el de Krause, el frío.")
O[217] = {"A": "Discos de Merkel", "B": "Corpúsculos de Pacini", "C": "Bulbos de Krause", "D": "Terminaciones nerviosas libres", "E": "Corpúsculos de Meissner"}

D[218] = ("Quimiorreceptores centrales: principal control ventilatorio por la PaCO2", "B",
"Los quimiorreceptores centrales están en la superficie ventral del bulbo raquídeo y son responsables de alrededor del 70 al 80 % de la respuesta ventilatoria ante un aumento de la PaCO2. El CO2 atraviesa la barrera hematoencefálica, se convierte en ácido carbónico en el líquido cefalorraquídeo y baja su pH; los hidrogeniones estimulan a estos receptores. Los quimiorreceptores periféricos (cuerpos carotídeos y aórticos) responden más rápido y son los principales detectores de la hipoxemia (PaO2 menor de 60 mmHg). En los pacientes con EPOC e hipercapnia crónica, los receptores centrales se adaptan, y el estímulo hipóxico cobra importancia. Por eso se usa oxígeno controlado (SatO2 88-92 %).")
N[218] = "¿Qué receptores son los principales responsables del aumento de la ventilación ante una elevación de la PaCO2?"
O[218] = {"A": "Quimiorreceptores periféricos", "B": "Quimiorreceptores centrales", "C": "Barorreceptores del cayado aórtico", "D": "Barorreceptores del seno carotídeo", "E": "Receptores de estiramiento pulmonar"}

D[219] = ("Vena gonadal izquierda: drena en la vena renal izquierda", "E",
"La vena gonadal, testicular u ovárica, derecha desemboca directamente en la vena cava inferior en ángulo agudo. La izquierda, en cambio, drena en la vena renal izquierda en ángulo recto. Por eso el varicocele es más frecuente en el lado izquierdo (un 90 % de los casos): la columna de sangre es más larga, la desembocadura en ángulo recto dificulta el flujo y la vena renal izquierda puede comprimirse entre la aorta y la mesentérica superior (fenómeno del cascanueces). Si aparece un varicocele derecho, uno de inicio brusco o uno que no se vacía al acostarse, hay que descartar una masa retroperitoneal o renal que comprima, como un tumor renal con trombo en la vena.")

D[220] = ("Agenesia mülleriana: ausencia de útero y vagina superior", "D",
"Los conductos de Müller (paramesonéfricos) dan origen a las trompas, el útero, el cuello uterino y la porción superior de la vagina. Si no se forman, falta el útero y la vagina es corta o ciega: es el síndrome de Mayer-Rokitansky-Küster-Hauser. Los ovarios son normales, porque derivan de la cresta gonadal y no de los conductos de Müller; por eso hay caracteres sexuales secundarios normales y ovulación. El tercio inferior de la vagina deriva del seno urogenital y suele existir. La consulta típica es una amenorrea primaria. El útero didelfo y el tabicado se deben a defectos de fusión o de reabsorción del tabique, no a la agenesia.")

D[221] = ("Intoxicación por clorfenamina: manejo de soporte", "A",
"La sobredosis de antihistamínicos H1 de primera generación, como la clorfenamina, produce un síndrome anticolinérgico: mucosas secas, rubicundez, midriasis, taquicardia, retención urinaria, hipertermia, agitación o somnolencia y, en casos graves, convulsiones y arritmias. Tras 5 horas, ya no sirve descontaminar (el carbón activado es útil en la primera hora). El manejo es de soporte y sintomático: monitoreo cardíaco, control de la temperatura, sonda vesical si hay retención y benzodiacepinas para la agitación o las convulsiones. La fisostigmina se reserva para el delirio anticolinérgico grave sin QRS ancho. La atropina empeoraría el cuadro, y la naloxona y la N-acetilcisteína no tienen indicación.")

D[222] = ("Sínfisis: articulación de fibrocartílago", "C",
"Las articulaciones cartilaginosas son de dos tipos. Las sincondrosis son primarias: dos huesos unidos por cartílago hialino, generalmente temporales, como las placas de crecimiento o la unión de la primera costilla con el esternón. Las sínfisis son secundarias: los huesos, cubiertos de cartílago hialino, se unen a través de un disco de fibrocartílago, como en la sínfisis del pubis, los discos intervertebrales y la sínfisis del manubrio con el cuerpo del esternón. Las sínfisis permiten poco movimiento y están en la línea media. Las suturas, la gonfosis (el diente en su alvéolo) y la sindesmosis (la tibioperonea distal) son articulaciones fibrosas, no cartilaginosas.")
N[222] = "¿Cómo se llama la articulación en la que dos huesos se unen mediante un disco de fibrocartílago, como en el pubis?"
O[222] = {"B": "Gonfosis", "D": "Sincondrosis", "E": "Sindesmosis"}

D[223] = ("Almacenamiento de espermatozoides: cola del epidídimo", "C",
"Los espermatozoides salen del testículo inmóviles e incapaces de fecundar. Recorren el epidídimo durante unos 10 a 14 días, y allí adquieren motilidad progresiva y capacidad de fecundar. Luego se almacenan sobre todo en la cola del epidídimo, y en menor medida en la porción inicial del conducto deferente, hasta la eyaculación. La vesícula seminal no almacena espermatozoides: produce alrededor del 60 % del volumen del semen, que es rico en fructosa y prostaglandinas. La próstata aporta un 30 %, con el PSA y el citrato. En la eyaculación, el deferente se contrae y lleva los espermatozoides a la uretra. Tras una vasectomía, siguen presentes en el semen durante unas 20 eyaculaciones.")

D[224] = ("Metoclopramida: reacción distónica aguda", "C",
"La metoclopramida bloquea los receptores dopaminérgicos D2 del tubo digestivo, donde actúa como antiemético y procinético, pero también los del cuerpo estriado, porque cruza la barrera hematoencefálica. Por eso puede causar reacciones distónicas agudas horas después de la dosis: blefaroespasmo, tortícolis, crisis oculógiras, trismo y protrusión de la lengua. Son más frecuentes en jóvenes y en mujeres. Se tratan con difenhidramina o biperideno IV, con mejoría en minutos. Su uso prolongado puede causar discinesia tardía irreversible. La hioscina es anticolinérgica y no da distonías. El dimenhidrinato es antihistamínico, la loperamida es un opioide periférico y el tramadol puede causar convulsiones.")
O[224] = {"A": "Butilbromuro de hioscina"}

D[225] = ("Carótida común derecha: nace del tronco braquiocefálico", "A",
"Del cayado aórtico salen tres ramas: el tronco braquiocefálico, la carótida común izquierda y la subclavia izquierda. El tronco braquiocefálico sube por detrás de la articulación esternoclavicular derecha y allí se divide en subclavia derecha y carótida común derecha. Así, la carótida común derecha nace del tronco braquiocefálico, y la izquierda, directamente del cayado. Una variante frecuente es el 'arco bovino', en el que la carótida izquierda nace de un tronco común con el braquiocefálico. Otra variante es la subclavia derecha aberrante (arteria lusoria), que pasa por detrás del esófago y puede causar disfagia.")
O[225] = {"C": "Aorta ascendente", "E": "Arteria vertebral derecha"}

D[226] = ("Espermatograma: la oligozoospermia es la baja concentración", "E",
"Según la OMS (manual 2021), el límite inferior normal de la concentración espermática es de 16 millones por mL (39 millones en todo el eyaculado). Por debajo, hay oligozoospermia (oligospermia). Otros términos: astenozoospermia es la baja motilidad (motilidad progresiva menor del 30 %); teratozoospermia, las formas normales por debajo del 4 %; azoospermia, la ausencia total de espermatozoides en el eyaculado, incluso centrifugado, y criptozoospermia, cuando no se ven en la muestra fresca pero sí tras centrifugar. La infertilidad se define como no lograr un embarazo tras 12 meses de relaciones sin protección. Un espermatograma alterado debe repetirse, porque varía mucho.")
O[226] = {"D": "Criptozoospermia"}

D[227] = ("Masetero: nervio mandibular (V3)", "D",
"Los músculos de la masticación (masetero, temporal y pterigoideos medial y lateral) derivan del primer arco faríngeo. Por eso están inervados por la rama motora del nervio mandibular o maxilar inferior (V3), la única rama del trigémino con fibras motoras. El V3 también inerva el milohioideo, el vientre anterior del digástrico, el tensor del tímpano y el tensor del velo del paladar. Para explorarlo se palpa el masetero mientras el paciente aprieta los dientes; si hay lesión, la mandíbula se desvía hacia el lado lesionado al abrir la boca. El nervio facial inerva los músculos de la expresión facial (segundo arco); los nervios oftálmico (V1) y maxilar (V2) son solo sensitivos.")
O[227] = {"B": "Rama cervicofacial del facial"}

D[228] = ("Polígono de Willis: arterias cerebrales anteriores y posteriores", "C",
"El polígono o círculo arterial de Willis está en la base del cerebro, alrededor de la silla turca y del quiasma óptico. Lo forman la arteria comunicante anterior, las dos cerebrales anteriores (tramo A1), las dos carótidas internas terminales, las dos comunicantes posteriores y las dos cerebrales posteriores (tramo P1). Une el sistema carotídeo con el vertebrobasilar, lo que permite la circulación colateral si se ocluye una arteria. Las cerebrales medias salen de la carótida pero no forman parte del anillo, y las cerebelosas pertenecen al sistema vertebrobasilar. Los aneurismas saculares se forman en sus bifurcaciones, sobre todo en la comunicante anterior, y su rotura causa hemorragia subaracnoidea.")
O[228] = {"C": "Cerebrales anteriores y cerebrales posteriores"}

D[229] = ("Núcleos profundos del cerebelo", "A",
"En la sustancia blanca de cada hemisferio cerebeloso hay cuatro núcleos profundos. De medial a lateral son el fastigio (o del techo), el globoso, el emboliforme y el dentado; se recuerdan con 'Fijo Glorioso Emboló al Dentista'. El fastigio recibe del vermis y controla el equilibrio y la postura. El globoso y el emboliforme forman el interpósito, que controla el tono y la coordinación de las extremidades. El dentado, el mayor, planifica los movimientos voluntarios finos y proyecta al tálamo y a la corteza motora por el pedúnculo cerebeloso superior. El núcleo de Edinger-Westphal está en el mesencéfalo y da la inervación parasimpática de la pupila, y el putamen pertenece a los ganglios basales.")

D[230] = ("Plexo cervical: ramos anteriores de C1 a C4", "E",
"Los plexos nerviosos (cervical, braquial, lumbar y sacro) se forman con los ramos anteriores o ventrales de los nervios raquídeos. El plexo cervical nace de los ramos anteriores de C1 a C4 y da ramas sensitivas superficiales en el punto de Erb, en el borde posterior del esternocleidomastoideo: occipital menor, auricular mayor, transverso del cuello y supraclaviculares. También da ramas motoras: el asa cervical para los músculos infrahioideos y el nervio frénico (C3 a C5) para el diafragma. Los ramos posteriores o dorsales no forman plexos; inervan los músculos profundos del dorso y la piel de la espalda en forma segmentaria. El bloqueo del plexo cervical superficial se usa en cirugías de tiroides y de la carótida.")

D[231] = ("Diencéfalo: deriva del prosencéfalo", "B",
"En la cuarta semana, el tubo neural forma tres vesículas primarias: prosencéfalo, mesencéfalo y rombencéfalo. En la quinta semana se forman cinco secundarias. El prosencéfalo se divide en telencéfalo, que da los hemisferios cerebrales, y diencéfalo, que da el tálamo, el hipotálamo, el epitálamo con la glándula pineal, la neurohipófisis y la retina y el nervio óptico. El mesencéfalo no se divide. El rombencéfalo da el metencéfalo (protuberancia y cerebelo) y el mielencéfalo (bulbo raquídeo). Las cavidades se convierten en los ventrículos: los laterales en el telencéfalo, el tercero en el diencéfalo, el acueducto en el mesencéfalo y el cuarto en el rombencéfalo.")

D[232] = ("Triángulo de auscultación: dorsal ancho, trapecio y borde medial de la escápula", "B",
"El triángulo de auscultación está limitado por el borde superior del dorsal ancho (abajo), el borde lateral del trapecio (medial) y el borde medial de la escápula con el romboides mayor (lateral). Su piso son los músculos intercostales del sexto espacio y el romboides mayor. Como allí hay poca masa muscular entre la piel y la pared torácica, es el mejor lugar para auscultar los ruidos respiratorios de los segmentos posteriores del lóbulo inferior. Se agranda si el paciente cruza los brazos por delante y se inclina hacia adelante. No debe confundirse con el triángulo lumbar de Petit, que está entre el dorsal ancho, el oblicuo mayor y la cresta ilíaca, y es un sitio de hernias.")

D[233] = ("Disfonía tras tiroidectomía: lesión del nervio laríngeo recurrente", "D",
"El nervio laríngeo inferior o recurrente inerva todos los músculos intrínsecos de la laringe salvo el cricotiroideo. En el lado izquierdo rodea el cayado aórtico y sube por el surco traqueoesofágico, muy cerca de la arteria tiroidea inferior. Por eso puede lesionarse en la cirugía de tiroides. La lesión de un lado deja la cuerda vocal paralizada en posición paramediana: disfonía, voz bitonal y aspiraciones. Si se lesionan ambos, las cuerdas quedan casi juntas, con estridor y obstrucción de la vía aérea, que puede requerir traqueostomía. La rama externa del laríngeo superior inerva el cricotiroideo; si se lesiona, la voz se fatiga y se pierden los tonos agudos, sin disfonía marcada.")
N[233] = "Si un paciente queda disfónico después de una hemitiroidectomía izquierda, es porque se ha lesionado:"

D[234] = ("Esófago torácico: mediastino superior y posterior", "E",
"El esófago comienza a nivel de C6, a continuación de la faringe. Su porción torácica recorre primero el mediastino superior, por detrás de la tráquea, y luego el mediastino posterior, por detrás del pericardio y de la aurícula izquierda, hasta atravesar el hiato diafragmático a nivel de T10. Por su relación con la aurícula izquierda, una aurícula dilatada, como en la estenosis mitral, puede comprimirlo y verse en el esofagograma. La ecocardiografía transesofágica aprovecha esa cercanía. En el mediastino posterior también están la aorta descendente, el conducto torácico, las venas ácigos y hemiácigos, los nervios vagos y las cadenas simpáticas.")

D[235] = ("Estrecheces del esófago: cayado aórtico", "C",
"El esófago tiene cuatro estrecheces fisiológicas, importantes porque allí se detienen los cuerpos extraños y las lesiones por cáusticos son más intensas. La primera es la cricofaríngea, a unos 15 cm de la arcada dentaria (C6), la más estrecha. La segunda está donde lo cruza el cayado aórtico, a unos 22 a 25 cm (T4). La tercera, donde lo cruza el bronquio principal izquierdo, a unos 27 cm (T5). La cuarta es la diafragmática, en el hiato, a unos 40 cm (T10). En los niños, las monedas se atascan sobre todo en la primera estrechez. Una pila de botón en el esófago es una urgencia: hay que extraerla en menos de 2 horas.")
O[235] = {"A": "Primera vértebra cervical", "E": "Bifurcación carotídea"}

D[236] = ("Cartílagos impares de la laringe: tiroides, cricoides y epiglotis", "C",
"La laringe tiene tres cartílagos impares y tres pares. Los impares son el tiroides, el más grande, que forma la 'nuez de Adán'; el cricoides, el único anillo completo, a nivel de C6, y la epiglotis, de cartílago elástico, que cubre la entrada de la laringe al deglutir. Los pares son los aritenoides, donde se insertan las cuerdas vocales y que giran para abrirlas y cerrarlas; los corniculados (de Santorini), y los cuneiformes (de Wrisberg). El cricoides es importante en clínica: en los niños es la parte más estrecha de la vía aérea, y la cricotirotomía de emergencia se hace a través de la membrana entre el cricoides y el tiroides.")
O[236] = {"E": "Tritíceo"}

D[237] = ("Língula: pertenece al lóbulo superior izquierdo", "B",
"El pulmón izquierdo tiene solo dos lóbulos, superior e inferior. La língula es una prolongación en forma de lengua de la porción anteroinferior del lóbulo superior izquierdo. Tiene dos segmentos, lingular superior e inferior, y equivale al lóbulo medio del pulmón derecho. En la radiografía de frente, una opacidad en la língula borra el contorno del borde izquierdo del corazón ('signo de la silueta'). Del mismo modo, la neumonía del lóbulo medio borra el borde derecho del corazón. El pulmón derecho tiene tres lóbulos separados por dos cisuras, la oblicua y la horizontal, mientras que el izquierdo solo tiene la cisura oblicua.")
N[237] = "Paciente cuya radiografía de tórax muestra una tumoración a nivel de la língula. ¿En qué lóbulo se encuentra la lesión?"

D[238] = ("Plexo cardíaco: fibras vagales y simpáticas cervicales", "A",
"El plexo cardíaco está en la base del corazón, alrededor del cayado aórtico y de la bifurcación de la tráquea. Lo forman los nervios cardíacos cervicales y torácicos del vago (fibras parasimpáticas) y los nervios cardíacos de los ganglios simpáticos cervicales (superior, medio e inferior o estrellado) y de los primeros torácicos. El vago reduce la frecuencia cardíaca y la conducción en el nodo AV. El simpático aumenta la frecuencia, la conducción y la contractilidad. Las fibras aferentes que llevan el dolor isquémico acompañan a los nervios simpáticos y entran a la médula en T1 a T4; por eso el dolor del infarto se irradia al brazo izquierdo y al cuello.")

D[239] = ("Circulación bronquial: las venas bronquiales drenan solo una parte", "C",
"El pulmón tiene doble irrigación. La circulación pulmonar lleva sangre venosa por las arterias pulmonares y devuelve sangre oxigenada por las venas pulmonares a la aurícula izquierda. La circulación bronquial, que es sistémica, nutre los bronquios y proviene de la aorta. Las venas bronquiales solo drenan parte de esta sangre: las derechas van a la vena ácigos y las izquierdas a la hemiácigos accesoria o a la intercostal superior. El resto de la sangre bronquial drena en las venas pulmonares. Esa mezcla de sangre no oxigenada es parte del cortocircuito fisiológico normal (un 2 %). Por eso A y B invierten el contenido de oxígeno, y D y E invierten el drenaje.")

D[240] = ("Arteria pulmonar derecha: pasa por detrás de la aorta ascendente", "A",
"El tronco pulmonar sale del ventrículo derecho y se divide, bajo el cayado aórtico, en las arterias pulmonares derecha e izquierda. La derecha es más larga y horizontal: pasa por detrás de la aorta ascendente y de la vena cava superior, y por delante del bronquio principal derecho, para llegar al hilio. En el hilio derecho, la arteria queda por delante del bronquio y a la altura del bronquio intermedio. En el hilio izquierdo, la arteria pulmonar pasa por encima del bronquio principal izquierdo. Esta relación con el bronquio sirve para orientarse en las tomografías y en la cirugía de resección pulmonar.")

D[241] = ("Irrigación de los nodos sinusal y AV: coronaria derecha", "A",
"En la mayoría de las personas, la arteria del nodo sinusal (un 60 %) y la arteria del nodo auriculoventricular (un 80 a 90 %, en los corazones de dominancia derecha) nacen de la coronaria derecha. Por eso, el infarto inferior por oclusión de la coronaria derecha se acompaña con frecuencia de bradicardia sinusal y de bloqueos AV. Estos bloqueos suelen ser del nodo, con escape de QRS estrecho, transitorios y responden a la atropina. En el infarto anterior extenso, el bloqueo suele ser infranodal, de QRS ancho y peor pronóstico, porque la descendente anterior irriga el haz de His y sus ramas. La dominancia coronaria la define la arteria que da la descendente posterior.")

D[242] = ("Músculos de las cuerdas vocales: nervio laríngeo recurrente", "C",
"El nervio laríngeo recurrente, rama del vago, inerva todos los músculos intrínsecos de la laringe que abren, cierran y tensan las cuerdas vocales, salvo el cricotiroideo. Entre ellos está el cricoaritenoideo posterior, el único que abre la glotis. También lleva la sensibilidad de la laringe por debajo de las cuerdas vocales. El laríngeo superior tiene dos ramas: la interna, sensitiva por encima de las cuerdas y responsable del reflejo tusígeno, y la externa, que inerva el cricotiroideo y tensa las cuerdas. Un cáncer del vértice pulmonar izquierdo, un aneurisma del cayado o una estenosis mitral pueden comprimir el recurrente izquierdo y causar disfonía.")

D[243] = ("Contenido del mediastino posterior: aorta descendente", "A",
"El mediastino posterior está por detrás del pericardio y por delante de los cuerpos vertebrales de T5 a T12. Contiene la aorta torácica descendente, el esófago, los nervios vagos, el conducto torácico, las venas ácigos y hemiácigos y las cadenas simpáticas. El timo está en el mediastino anterosuperior. Las arterias mamarias internas corren por detrás de los cartílagos costales, en la pared anterior. El nervio frénico pasa por el mediastino medio, sobre el pericardio. La tráquea está en el mediastino superior. En clínica, las masas del mediastino posterior suelen ser neurogénicas (schwannoma, neuroblastoma), y las del anterior, las '4 T': timoma, teratoma, tiroides y linfoma ('terrible' linfoma).")

D[244] = ("Colon ascendente: irrigado por la arteria mesentérica superior", "E",
"La arteria mesentérica superior irriga todo el derivado del intestino medio: duodeno distal, yeyuno, íleon, ciego, apéndice, colon ascendente y los dos tercios proximales del transverso. Lo hace a través de las arterias ileocólica, cólica derecha y cólica media. La mesentérica inferior irriga el tercio distal del transverso, el descendente, el sigmoides y el recto superior mediante las arterias cólica izquierda, sigmoideas y rectal superior. Ambos territorios se unen por la arcada marginal de Drummond. El ángulo esplénico (punto de Griffiths) es una zona de irrigación débil entre los dos, por lo que es un lugar típico de colitis isquémica.")
O[244] = {"A": "Rectal superior"}

X[245] = "Repite la 17 (arco de la curvatura menor del estómago)"

D[246] = ("Ligamento inguinal: borde inferior de la aponeurosis del oblicuo mayor", "A",
"El ligamento inguinal o de Poupart es el borde inferior engrosado y replegado de la aponeurosis del oblicuo externo (oblicuo mayor). Va desde la espina ilíaca anterosuperior hasta el tubérculo del pubis. Forma el piso del conducto inguinal, y por debajo de él pasan hacia el muslo el nervio, la arteria y la vena femorales, además del conducto femoral (por eso la regla 'NAVEL', de lateral a medial). Referencias clínicas: la hernia inguinal sale por encima del ligamento y la femoral, por debajo y lateral al tubérculo del pubis; la hernia femoral es más frecuente en mujeres y tiene más riesgo de estrangularse. Su porción medial replegada forma el ligamento lacunar de Gimbernat.")

X[247] = "Repite la 94 (arteria gástrica izquierda en la curvatura menor)"

D[248] = ("Tríada portal: vena porta, arteria hepática y conducto biliar", "A",
"La tríada portal está en cada espacio porta, en los vértices del lobulillo hepático clásico. La forman una rama de la vena porta, una rama de la arteria hepática y un conductillo biliar, acompañados de vasos linfáticos y nervios. La sangre de la porta (75 % del flujo, rica en nutrientes) y de la arteria (25 %, rica en oxígeno) se mezcla en los sinusoides y drena hacia la vena central. La bilis circula en sentido contrario, hacia el espacio porta. A mayor escala, en el ligamento hepatoduodenal (borde libre del epiplón menor) están el colédoco, la arteria hepática propia y la vena porta. La maniobra de Pringle las comprime para controlar el sangrado del hígado.")
O[248] = {"D": "La arteria mesentérica superior y el colédoco"}

D[249] = ("Cabeza del páncreas: dentro del marco duodenal", "A",
"La cabeza del páncreas se aloja en la concavidad en 'C' del duodeno, a la derecha de los vasos mesentéricos superiores. Su proceso unciforme se ubica por detrás de la vena mesentérica superior. El cuello está por delante de la confluencia de las venas mesentérica superior y esplénica, donde nace la porta. El cuerpo cruza por delante de la aorta y de L1, y la cola llega al hilio esplénico. Por esta relación, un cáncer de la cabeza del páncreas comprime el colédoco intrapancreático y produce ictericia indolora con vesícula palpable (signo de Courvoisier-Terrier). Su tratamiento es la duodenopancreatectomía (Whipple). El páncreas anular puede obstruir el duodeno.")

D[250] = ("Arteria apendicular: de la ileocólica (mesentérica superior)", "A",
"La arteria apendicular nace de la arteria ileocólica, rama de la mesentérica superior, y recorre el borde libre del mesoapéndice. Es una arteria terminal, sin colaterales. Por eso, cuando el apéndice obstruido se distiende y la presión colapsa la irrigación, aparecen rápido gangrena y perforación, sobre todo después de las 24 a 36 horas de evolución. En la apendicectomía se liga la arteria en el mesoapéndice. La rectal superior es la continuación de la mesentérica inferior, y la cólica izquierda y la sigmoidea también son ramas de la mesentérica inferior. La base del apéndice se encuentra siguiendo las tenias del colon hasta que convergen en el ciego.")
