# Revisión preguntas 301-350
D, O, N, X = {}, {}, {}, {}

D[301] = ("Vitamina D: actúa como hormona esteroidea", "C",
"La vitamina D se comporta como una hormona esteroidea. Se produce en la piel con los rayos UVB a partir del 7-dehidrocolesterol, o se obtiene de la dieta. Luego se hidroxila en el hígado (25-hidroxivitamina D, la forma que se mide) y en el riñón (1,25-dihidroxivitamina D o calcitriol, la forma activa, que estimula la PTH). El calcitriol entra a la célula y se une a un receptor nuclear (VDR), que actúa como factor de transcripción, igual que los esteroides. Aumenta la absorción intestinal de calcio y fósforo, y regula la mineralización del hueso. Su déficit causa raquitismo en el niño y osteomalacia en el adulto. En la enfermedad renal crónica falla la hidroxilación renal y se usa calcitriol.")

X[302] = "Opciones sin relación con el enunciado (retinol, rodopsina)"

D[303] = ("Segundo mensajero: intermediario intracelular de señales hormonales y neurales", "B",
"Un segundo mensajero es una molécula dentro de la célula que transmite y amplifica la señal de un primer mensajero, una hormona o un neurotransmisor que no puede entrar a la célula y se une a un receptor de membrana. Los principales son el AMPc (formado por la adenilato ciclasa y regulado por proteínas Gs y Gi), el GMPc, el IP3 y el diacilglicerol (vía fosfolipasa C y proteína Gq) y el calcio. Un mismo segundo mensajero sirve a muchas hormonas y neurotransmisores distintos. Por ejemplo, el AMPc media la acción del glucagón, la adrenalina (beta), la TSH, la LH y la PTH. Las hormonas liposolubles, como los esteroides y la tiroxina, no necesitan segundo mensajero.")

D[304] = ("Vitamina A revierte el efecto de los corticoides en la cicatrización", "D",
"Los corticoides retrasan la cicatrización porque frenan la inflamación inicial, la llegada de macrófagos, la proliferación de fibroblastos, la síntesis de colágeno y la formación de nuevos vasos. La vitamina A contrarresta en buena parte estos efectos: estimula la respuesta inflamatoria, la epitelización, la síntesis de colágeno y el entrecruzamiento de sus fibras. Por eso se indica, por vía oral o tópica, en pacientes que reciben corticoides crónicos y necesitan cirugía o tienen heridas que no cierran. La vitamina C es cofactor de la síntesis de colágeno, pero no revierte el efecto de los corticoides. El zinc también es importante para cicatrizar, y la diabetes y la desnutrición retrasan la reparación.")

X[305] = "Repite la 196 (pelagra por déficit de niacina)"

D[306] = ("Déficit de riboflavina (B2): glositis, queilitis y estomatitis angular", "E",
"La riboflavina (vitamina B2) forma las coenzimas FMN y FAD, necesarias para muchas reacciones de óxido-reducción, como la cadena respiratoria y la beta-oxidación. Su déficit (arriboflavinosis) afecta sobre todo la piel y las mucosas, que se renuevan rápido. Produce queilitis y estomatitis angular (fisuras en las comisuras de la boca), glositis con atrofia de las papilas linguales y lengua de color magenta, dermatitis seborreica alrededor de la nariz y en los genitales, y vascularización de la córnea con fotofobia. Suele coexistir con el déficit de otras vitaminas del complejo B, como en el alcoholismo o la desnutrición. La neuropatía periférica es más típica del déficit de B1, B6 o B12.")
O[306] = {"E": "Atrofia de las papilas linguales"}

D[307] = ("Penetración de la zona pelúcida: enzimas acrosómicas", "D",
"Para fecundar, el espermatozoide capacitado atraviesa tres barreras. Primero pasa la corona radiata, ayudado por la hialuronidasa de su membrana y por el movimiento de su cola. Luego se une a la glucoproteína ZP3 de la zona pelúcida, lo que desencadena la reacción acrosómica: se liberan las enzimas del acrosoma, sobre todo la acrosina (una proteasa), que abren un camino en la zona pelúcida. Por último, las membranas del espermatozoide y del ovocito se fusionan. Esto provoca la reacción cortical del ovocito: los gránulos corticales liberan enzimas que cambian la zona pelúcida y bloquean la entrada de otros espermatozoides (bloqueo de la polispermia). También se completa la segunda meiosis del ovocito.")

D[308] = ("Fructosa seminal: producida por las vesículas seminales", "B",
"Las vesículas seminales aportan alrededor del 60 al 70 % del volumen del semen. Su secreción es alcalina y rica en fructosa, la principal fuente de energía de los espermatozoides eyaculados, que la usan por glucólisis para moverse. También aportan prostaglandinas, que favorecen la contracción uterina y el transporte de los espermatozoides, y semenogelina, que coagula el semen. La próstata aporta un 20 a 30 % del volumen, con ácido cítrico, zinc, fosfatasa ácida y PSA, que licúa el coágulo en 15 a 30 minutos. En la clínica, una fructosa seminal ausente con un volumen bajo y pH ácido sugiere agenesia de los conductos deferentes o de las vesículas seminales, u obstrucción de los conductos eyaculadores.")
O[308] = {"D": "Glándula de Cowper"}
X[309] = "Repite la 308 (fructosa como fuente de energía del espermatozoide)"

X[310] = "Muy similar a la CB-009 ya publicada (implantación del blastocisto)"

D[311] = ("Reacción acrosómica: se desencadena al unirse a la zona pelúcida", "A",
"La reacción acrosómica ocurre cuando el espermatozoide capacitado, tras atravesar la corona radiata, se une a la glucoproteína ZP3 de la zona pelúcida. Esa unión abre canales de calcio y hace que la membrana externa del acrosoma se fusione con la membrana plasmática. Así se liberan la acrosina y otras enzimas que digieren un paso a través de la zona pelúcida. La progesterona del cúmulo también puede inducirla. Por tanto, es un paso previo a la penetración de la zona, no posterior. La formación de los pronúcleos, la expulsión del segundo corpúsculo polar y la reanudación de la segunda meiosis ocurren después, una vez que el espermatozoide se fusiona con el ovocito.")
O[311] = {"A": "Al unirse el espermatozoide a la zona pelúcida (ZP3)"}
N[311] = "En el proceso de fecundación, ¿en qué momento se desencadena la reacción acrosómica?"

D[312] = ("Blastulación: cavitación del blastocisto e implantación", "B",
"Las etapas del desarrollo inicial son gametogénesis, fecundación, segmentación, blastulación, gastrulación y organogénesis. En la segmentación, el cigoto se divide en blastómeros y forma la mórula, de 16 a 32 células, al tercer día. En la blastulación, hacia el cuarto y quinto día, entra líquido en la mórula y se forma una cavidad (cavitación): es el blastocisto, con una masa celular interna (embrioblasto) y una capa externa (trofoblasto). El blastocisto sale de la zona pelúcida y se implanta en el endometrio entre los días 6 y 10. En la tercera semana ocurre la gastrulación: se forman las tres capas germinativas. La histogénesis y la organogénesis vienen después.")

X[313] = "Repite la 43 (anencefalia en la cuarta semana)"

D[314] = ("Bandas amnióticas: defecto por disrupción", "C",
"Los defectos congénitos se clasifican según su mecanismo. La malformación es un defecto intrínseco del desarrollo de un órgano, como la cardiopatía congénita o el labio leporino. La disrupción es la destrucción de un tejido que se estaba formando con normalidad, por una causa externa: bandas amnióticas, isquemia vascular o infección. La deformación es un cambio de forma por fuerzas mecánicas, como el pie equino por oligohidramnios. La displasia es una organización anormal de las células en un tejido, como la acondroplasia. En la secuencia de bandas amnióticas, la rotura del amnios forma bridas que estrangulan o amputan dedos o extremidades de forma asimétrica. Tienen bajo riesgo de repetirse.")
O[314] = {"A": "Malformación", "B": "Displasia", "C": "Disrupción", "D": "Asociación", "E": "Deformación"}

X[315] = "Repite la 15 (hematopoyesis inicial en el saco vitelino)"

D[316] = ("Derivados del trofoblasto: la placenta", "A",
"En el blastocisto, el trofoblasto es la capa externa que dará origen a la parte fetal de la placenta y al corion. Se diferencia en citotrofoblasto, que prolifera, y sincitiotrofoblasto, que invade el endometrio, forma las lagunas donde circula la sangre materna y produce hormonas: hCG (detectable en la prueba de embarazo), lactógeno placentario, progesterona y estrógenos. El embrioblasto o masa celular interna da el embrión, el amnios, el saco vitelino y la alantoides. La epidermis deriva del ectodermo del embrión. Si el trofoblasto prolifera de forma anormal, aparece la enfermedad trofoblástica gestacional, como la mola hidatiforme o el coriocarcinoma, que se vigila con la hCG.")

D[317] = ("Eritropoyetina fetal: se produce sobre todo en el hígado", "E",
"En el feto, la eritropoyetina (EPO) se produce principalmente en el hígado; el riñón toma el relevo alrededor del nacimiento. En el adulto, el riñón produce cerca del 90 % de la EPO, en los fibroblastos intersticiales peritubulares de la corteza, no en el túbulo proximal. La producción fetal empieza en el primer trimestre y es independiente de la materna, porque la EPO no cruza la placenta. La estimula la hipoxia a través del factor inducible por hipoxia (HIF), que se estabiliza con poco oxígeno y activa el gen de la EPO. Por eso el feto de una madre diabética o con insuficiencia placentaria tiene EPO alta y policitemia. En el prematuro, la baja producción de EPO contribuye a la anemia de la prematuridad.")
O[317] = {"B": "Ocurre principalmente en el túbulo proximal renal.", "C": "Se inhibe por el factor inducible por hipoxia.", "E": "Se produce principalmente en el hígado fetal.",
          "A": "Se inicia a partir del tercer trimestre.", "D": "No ocurre, pues es suficiente la materna."}

D[318] = ("Quiste del conducto de Gartner: resto del conducto de Wolff", "D",
"Los quistes del conducto de Gartner son restos del conducto mesonéfrico (de Wolff), que en la mujer involuciona por falta de testosterona. Se ubican en la pared anterolateral de la vagina, a lo largo del trayecto del antiguo conducto, y suelen estar revestidos por epitelio cúbico o cilíndrico, no escamoso. Casi siempre son pequeños, asintomáticos y se descubren en un examen ginecológico. Si son grandes, pueden causar dispareunia o dificultad en el parto. Pueden asociarse a anomalías renales del mismo lado, como en el síndrome de Herlyn-Werner-Wunderlich. Hay que diferenciarlos del quiste de la glándula de Bartholin, en el introito posterolateral, y del divertículo uretral.")
O[318] = {"C": "Derivan del seno urogenital"}
X[322] = "Repite la 318 (conducto de Gartner como resto del conducto de Wolff)"

D[319] = ("Diferenciación de los genitales externos: completa hacia la semana 12", "B",
"Hasta la séptima semana, los genitales externos son iguales en ambos sexos (etapa indiferenciada), con tubérculo genital, pliegues uretrales y eminencias labioescrotales. Desde la novena semana comienzan a diferenciarse, y hacia la semana 12 la diferenciación está completa. En el varón, esto depende de la dihidrotestosterona, que forma el pene y el escroto y fusiona los pliegues uretrales. En la mujer ocurre sin necesidad de hormonas. Por eso la ecografía del primer trimestre puede equivocarse al determinar el sexo, que se define con seguridad en la ecografía del segundo trimestre. Las alteraciones en esta etapa, como la hiperplasia suprarrenal congénita en fetos XX, producen genitales ambiguos.")
O[319] = {"B": "Duodécima semana"}
N[319] = "La diferenciación completa de los órganos genitales externos fetales se establece hacia la:"

D[320] = ("Testosterona fetal: la producen las células de Leydig desde la semana 7-8", "C",
"Tras la acción del gen SRY en la sexta semana, la gónada se diferencia en testículo. Hacia la séptima u octava semana, las células de Leydig fetales empiezan a producir testosterona, primero bajo el estímulo de la hCG placentaria y después de la LH fetal. Su nivel más alto se alcanza entre las semanas 12 y 14. La testosterona mantiene y desarrolla los conductos de Wolff (epidídimo, deferente, vesícula seminal). Su derivado, la dihidrotestosterona, forma la próstata y los genitales externos. Al mismo tiempo, las células de Sertoli producen hormona antimülleriana, que hace regresar los conductos de Müller. Si falta la 5-alfa-reductasa, hay genitales externos ambiguos con conductos de Wolff normales.")

D[321] = ("Circulación fetal: los cortocircuitos van de derecha a izquierda", "B",
"La afirmación incorrecta es B. En el feto, el pulmón no respira y su resistencia vascular es muy alta, mayor que la sistémica. Por eso existen tres cortocircuitos fisiológicos con flujo de derecha a izquierda: el conducto venoso de Arancio, que lleva sangre de la vena umbilical a la cava inferior sin pasar por el hígado; el foramen oval, de la aurícula derecha a la izquierda, y el conducto arterioso, de la arteria pulmonar a la aorta. El ventrículo derecho maneja cerca del 60 al 65 % del gasto combinado, y la PaO2 fetal es de solo 25 a 40 mmHg; la hemoglobina fetal compensa con su alta afinidad por el oxígeno. Al nacer, los pulmones se expanden, la resistencia pulmonar cae y los cortocircuitos se cierran.")

D[323] = ("Formación de pronúcleos: ocurre durante la fecundación", "A",
"La fecundación es el proceso que va desde el encuentro del espermatozoide con el ovocito hasta la formación del cigoto, y ocurre en la ampolla de la trompa. Cuando las membranas se fusionan, el ovocito, detenido en metafase II, completa la segunda meiosis y expulsa el segundo corpúsculo polar; su núcleo haploide forma el pronúcleo femenino. La cabeza del espermatozoide se descondensa y forma el pronúcleo masculino. Ambos replican su ADN, se acercan, sus membranas se disuelven y los cromosomas se alinean en la primera división mitótica. Esto restablece el número diploide y determina el sexo genético. Luego empieza la segmentación, con la formación de blastómeros.")
O[323] = {"C": "Blastulación"}

D[324] = ("Maduración pulmonar: alvéolos primitivos y surfactante desde la semana 20-24", "A",
"El pulmón fetal pasa por cinco etapas. La embrionaria (semanas 4 a 7) forma el brote pulmonar. La seudoglandular (semanas 5 a 17) forma los bronquios hasta los bronquiolos terminales. En la canalicular (semanas 16 a 26) aparecen los bronquiolos respiratorios, se vascularizan y, hacia las semanas 20 a 24, se forman los primeros sacos o alvéolos primitivos y los neumocitos tipo II empiezan a producir surfactante. En la sacular (semanas 24 a 36) aumentan los sacos y el surfactante. En la alveolar, desde la semana 36 hasta los 8 años, se forman los alvéolos maduros. Por eso la viabilidad empieza alrededor de las 23 a 24 semanas, y los corticoides prenatales entre las 24 y 34 semanas aceleran la producción de surfactante.")

X[325] = "Repite la 138 (paso del testículo por el conducto inguinal)"

D[326] = ("Agenesia del conducto mesonéfrico: falta riñón, uréter y vesícula seminal", "A",
"El conducto mesonéfrico o de Wolff tiene dos funciones en el desarrollo. Hacia la quinta semana emite el brote ureteral, que induce al blastema metanéfrico a formar el riñón definitivo y da origen al uréter, la pelvis, los cálices y los túbulos colectores. En el varón, además, forma el epidídimo, el conducto deferente, la vesícula seminal y el conducto eyaculador. Por eso, si un conducto mesonéfrico no se desarrolla, faltan en ese lado el riñón, el uréter y la vesícula seminal, a menudo también el conducto deferente. Ante una agenesia renal unilateral en un varón se buscan anomalías de las vías seminales; en la mujer, malformaciones müllerianas asociadas.")
N[326] = "En un varón, cuando uno de los conductos mesonéfricos (de Wolff) no se desarrolla, se produce en ese lado la ausencia de:"

D[327] = ("Madurez fetal: la determina sobre todo el pulmón", "B",
"Un feto se considera maduro cuando sus pulmones han alcanzado la madurez anatómica y funcional necesaria para respirar fuera del útero. Esto depende de que haya suficientes sacos alveolares y producción de surfactante, que evita el colapso de los alvéolos. La inmadurez pulmonar es la principal causa de muerte y morbilidad del prematuro, por el síndrome de dificultad respiratoria o enfermedad de membrana hialina. Por eso, ante un parto prematuro probable entre las 24 y 34 semanas, se dan corticoides prenatales (betametasona o dexametasona), que aceleran la maduración pulmonar. Antes se medía la relación lecitina/esfingomielina en el líquido amniótico: si era mayor de 2, había madurez pulmonar.")

D[328] = ("Riñón definitivo (metanefros): aparece en la quinta semana", "E",
"En el embrión se forman tres sistemas renales sucesivos en dirección craneocaudal. El pronefros aparece en la cuarta semana, no funciona y desaparece. El mesonefros funciona de forma transitoria entre las semanas 4 y 8 y deja su conducto (de Wolff) para las vías genitales masculinas. El metanefros, el riñón definitivo, aparece en la quinta semana cuando el brote ureteral penetra el blastema metanéfrico. Empieza a producir orina hacia la semana 10 a 12, y esa orina es el principal componente del líquido amniótico en la segunda mitad del embarazo. Por eso la agenesia renal bilateral produce oligohidramnios grave y secuencia de Potter, con hipoplasia pulmonar.")
O[328] = {"C": "Séptima"}

D[329] = ("Síndrome de Patau: trisomía 13", "A",
"El síndrome de Patau es la trisomía 13. Afecta a uno de cada 10 000 a 20 000 nacidos vivos y su frecuencia aumenta con la edad materna. Presenta defectos de la línea media: holoprosencefalia, labio y paladar hendidos, microftalmia, cutis aplasia en el cuero cabelludo, polidactilia postaxial, onfalocele, cardiopatía congénita y riñones poliquísticos. Más del 80 % muere antes del año. Otras trisomías: la 21 es el síndrome de Down; la 18 es el síndrome de Edwards (puños cerrados con dedos cabalgados, pies en mecedora, occipucio prominente); el 47,XXY es el síndrome de Klinefelter, y el 45,X, el de Turner. El tamizaje combinado del primer trimestre las detecta.")

D[330] = ("Síndrome de Patau: polidactilia, onfalocele e hipotonía", "A",
"La combinación de retraso mental, polidactilia, onfalocele, alteraciones de los pies e hipotonía orienta a la trisomía 13 (síndrome de Patau). Sus defectos típicos son de la línea media: holoprosencefalia, labio y paladar hendidos, microftalmia o anoftalmia y aplasia cutis congénita. Además hay cardiopatía y riñones poliquísticos. El síndrome de Edwards (trisomía 18) comparte la discapacidad intelectual y el onfalocele, pero se distingue por los puños cerrados con dedos cabalgados, los pies en mecedora y la hipertonía, no hipotonía. El síndrome de Down cursa con hipotonía, pero sin polidactilia. Turner y Klinefelter no producen estos defectos múltiples.")

X[331] = "Repite la 87 (definición de biodisponibilidad)"

D[332] = ("Vida media de eliminación", "D",
"La vida media (t½) es el tiempo necesario para que la concentración plasmática de un fármaco baje a la mitad. Depende del volumen de distribución y del aclaramiento: t½ = 0,693 × Vd / CL. Tiene dos usos prácticos. Primero, con dosis repetidas, el estado de equilibrio se alcanza en unas 4 a 5 vidas medias; por eso los fármacos de vida media larga, como la amiodarona o la digoxina, necesitan dosis de carga. Segundo, al suspender el fármaco, se elimina casi por completo en 4 a 5 vidas medias. La ventana o intervalo terapéutico es el rango entre la concentración mínima eficaz y la tóxica, y el periodo de latencia es el tiempo hasta que empieza el efecto.")

D[333] = ("Inductores enzimáticos: la fenitoína", "E",
"La fenitoína es un potente inductor de las enzimas del citocromo P450 (CYP3A4, CYP2C) y de la glucuronidación. Acelera el metabolismo de otros fármacos y reduce su efecto: anticonceptivos orales, warfarina, corticoides, otros antiepilépticos y la vitamina D, lo que explica la osteomalacia. Otros inductores clásicos son la carbamazepina, el fenobarbital, la rifampicina, el alcohol crónico y la hierba de San Juan. El valproato, en cambio, es un inhibidor enzimático: aumenta los niveles de la lamotrigina y del fenobarbital. La gabapentina y la pregabalina casi no se metabolizan y tienen pocas interacciones, y la tiagabina tampoco es inductora.")

D[334] = ("Unión neuromuscular: la acetilcolina es el neurotransmisor", "A",
"En la unión neuromuscular del músculo esquelético, el único neurotransmisor es la acetilcolina. El potencial de acción abre canales de calcio en la terminal nerviosa; el calcio libera la acetilcolina, que se une a receptores nicotínicos de la placa motora. Estos receptores son canales iónicos que despolarizan la fibra muscular. La acetilcolinesterasa degrada rápido la acetilcolina. Enfermedades y fármacos que actúan aquí: la miastenia gravis, con anticuerpos contra el receptor, se trata con piridostigmina; el síndrome de Lambert-Eaton, con anticuerpos contra los canales de calcio; la toxina botulínica bloquea la liberación, y los relajantes musculares, como el rocuronio y la succinilcolina, bloquean el receptor.")

D[335] = ("Generaciones de cefalosporinas", "B",
"Las cefalosporinas se agrupan en generaciones según su espectro. Primera generación (cefazolina, cefalexina, cefadroxilo, cefalotina, cefradina): muy activas contra grampositivos; se usan en profilaxis quirúrgica e infecciones de piel. Segunda (cefuroxima, cefaclor, y las cefamicinas cefoxitina y cefotetán, con acción contra anaerobios): mejor cobertura de gramnegativos respiratorios como H. influenzae. Tercera (ceftriaxona, cefotaxima, ceftazidima y cefoperazona, estas dos antipseudomonas): amplia cobertura de gramnegativos y buen paso al LCR. Cuarta (cefepima): grampositivos y gramnegativos, incluida Pseudomonas. Quinta (ceftarolina): activa contra SARM. Así: cefuroxima es de segunda, cefepima de cuarta, ceftazidima de tercera y cefadroxilo de primera.")
N[335] = "Relacione las cefalosporinas con su generación: (a) Cefuroxima, (b) Cefepima, (c) Ceftazidima, (d) Cefadroxilo; con (1) Primera, (2) Segunda, (3) Tercera, (4) Cuarta generación."

D[336] = ("Colestasis por fármacos: el paracetamol causa daño hepatocelular", "D",
"Varios fármacos causan colestasis intrahepática, que se presenta con ictericia, prurito y elevación de la fosfatasa alcalina y la GGT. Ejemplos clásicos: la clorpromazina y otras fenotiazinas, la carbamazepina, los anticonceptivos orales y los esteroides anabolizantes, la amoxicilina-clavulánico (la causa más frecuente en muchas series), la eritromicina estolato y algunos antagonistas del calcio, como la nifedipina. El paracetamol, en cambio, produce daño hepatocelular: necrosis centrolobulillar, con transaminasas muy altas, a menudo mayores de 1000 UI/L, por acumulación de NAPQI en la sobredosis, sin un patrón colestásico. Distinguir el patrón (hepatocelular, colestásico o mixto) con el índice R ayuda a sospechar el fármaco culpable.")
O[336] = {"D": "Paracetamol", "B": "Clorpromazina"}

D[337] = ("Cefoxitina (cefamicina): activa contra Bacteroides fragilis", "A",
"La cefoxitina y el cefotetán son cefamicinas, que suelen incluirse entre las cefalosporinas de segunda generación. Tienen un grupo metoxi que las hace resistentes a muchas betalactamasas, incluidas las de Bacteroides fragilis. Por eso son activas contra anaerobios y se usan en la profilaxis de la cirugía colorrectal y en infecciones pélvicas o intraabdominales leves, aunque la resistencia de B. fragilis va en aumento. Las otras cefalosporinas (cefalotina de primera; cefuroxima de segunda; ceftriaxona y cefotaxima de tercera) tienen poca actividad contra B. fragilis. Para cubrir anaerobios con seguridad se usan metronidazol, carbapenémicos o piperacilina-tazobactam.")
O[337] = {"A": "Cefoxitina"}

D[338] = ("Polimixinas: actúan sobre la membrana celular", "B",
"Las polimixinas (polimixina B y colistina) son péptidos catiónicos que se unen al lipopolisacárido de la membrana externa de los gramnegativos. Actúan como detergentes: rompen las membranas externa y citoplasmática, y la bacteria pierde su contenido. No inhiben la síntesis de proteínas. Hoy se usan como último recurso contra gramnegativos multirresistentes (Acinetobacter, Pseudomonas, enterobacterias productoras de carbapenemasas). Son nefrotóxicas y neurotóxicas. Los demás sí inhiben la síntesis de proteínas: los aminoglucósidos y las tetraciclinas en la subunidad 30S, y los macrólidos y la clindamicina en la 50S. Regla: 'buy AT 30, CCEL at 50' (aminoglucósidos y tetraciclinas en la 30S; cloranfenicol, clindamicina, eritromicina y linezolid en la 50S).")

D[339] = ("Lepra multibacilar: dapsona + rifampicina + clofazimina", "E",
"La lepra se trata siempre con varios fármacos a la vez para evitar la resistencia, igual que la tuberculosis. En la lepra lepromatosa o multibacilar, la OMS recomienda rifampicina (600 mg una vez al mes), clofazimina (300 mg al mes y 50 mg al día) y dapsona (100 mg al día) durante 12 meses. En la paucibacilar se usa el mismo esquema por 6 meses. La rifampicina es el fármaco más bactericida contra Mycobacterium leprae: una sola dosis elimina más del 99 % de los bacilos viables. Efectos adversos: la dapsona causa hemólisis en el déficit de G6PD y metahemoglobinemia; la clofazimina tiñe la piel de color rojizo o pardo.")

X[340] = "Repite la 46 (neuritis óptica por etambutol)"

D[341] = ("Pseudomonas en quemados: ceftazidima", "D",
"Pseudomonas aeruginosa es una causa importante de infección y sepsis en los grandes quemados, porque la escara húmeda y la pérdida de la barrera cutánea la favorecen. Puede dar lesiones verdosas o necróticas y ectima gangrenoso. De las opciones, la única con actividad antipseudomonas es la ceftazidima, una cefalosporina de tercera generación. En una infección grave suele combinarse con un aminoglucósido según el antibiograma, junto con el desbridamiento de la escara. El cefaclor y la cefuroxima (segunda generación), la cefalotina (primera) y la cefoxitina (cefamicina) no cubren Pseudomonas. Otras opciones son el cefepime, la piperacilina-tazobactam, los carbapenémicos y el aztreonam.")

D[342] = ("Alergia grave a penicilina con Pseudomonas: aztreonam", "A",
"El aztreonam es un monobactámico con actividad contra gramnegativos aerobios, incluida Pseudomonas aeruginosa. No tiene reactividad cruzada relevante con las penicilinas, así que puede usarse con seguridad en pacientes con anafilaxia a la penicilina. La excepción es la alergia a la ceftazidima, con la que comparte la misma cadena lateral. La ceftazidima, el meropenem, la mezlocilina y la piperacilina-tazobactam son betalactámicos: las dos últimas son penicilinas, contraindicadas, y los carbapenémicos y cefalosporinas tienen un riesgo pequeño de reacción cruzada que en una anafilaxia previa se prefiere evitar. El aztreonam no actúa sobre grampositivos ni anaerobios, por lo que a veces se combina con otros fármacos.")

D[343] = ("Infección intraabdominal nosocomial: piperacilina-tazobactam", "E",
"Una infección intraabdominal grave de origen hospitalario, en un paciente inmunosuprimido, obliga a cubrir enterobacterias resistentes, Pseudomonas aeruginosa y anaerobios, sobre todo Bacteroides fragilis. La piperacilina-tazobactam cubre los tres grupos con un solo fármaco, igual que los carbapenémicos antipseudomonas (imipenem, meropenem). Las otras opciones fallan en algo. La amikacina con penicilina no cubre bien los anaerobios gramnegativos ni actúa en abscesos. La ampicilina-sulbactam no cubre Pseudomonas. El aztreonam con amikacina no cubre los anaerobios. La ceftriaxona con clindamicina no cubre Pseudomonas. Siempre se acompaña del control del foco (drenaje o cirugía) y se ajusta según los cultivos.")
N[343] = "Paciente inmunosuprimido con infección severa de la cavidad abdominal de origen intrahospitalario. Se sospecha infección por Pseudomonas aeruginosa y anaerobios gramnegativos. ¿Cuál es la terapia antimicrobiana empírica de elección?"

X[344] = "Contradice la 32 (betalactámicos como causa más frecuente de reacciones cutáneas)"

D[345] = ("Macrólidos: inhiben la síntesis de proteínas, no la pared", "C",
"La claritromicina, como la eritromicina y la azitromicina, es un macrólido. Se une al ARN ribosomal 23S de la subunidad 50S e impide la translocación de la cadena de péptidos: inhibe la síntesis de proteínas y su efecto es bacteriostático. Los otros actúan sobre la pared celular en distintos pasos. La bacitracina bloquea el reciclaje del transportador lipídico (bactoprenol) de las unidades de peptidoglucano. La vancomicina se une al extremo D-alanil-D-alanina y bloquea la transglicosilación. Las cefalosporinas como la ceftriaxona y los carbapenémicos como el imipenem inhiben las PBP (transpeptidasas). Por eso estos últimos son bactericidas y actúan mejor sobre bacterias en crecimiento.")
O[345] = {"E": "Vancomicina"}
X[347] = "Repite la 345 (macrólidos no actúan sobre la pared)"

D[346] = ("Diarrea por Campylobacter: azitromicina", "B",
"Campylobacter jejuni es una de las causas más comunes de diarrea bacteriana, a menudo por carne de pollo mal cocida. Produce diarrea que puede ser disentérica, fiebre y dolor abdominal intenso, que puede simular una apendicitis. Suele ceder sola. Se tratan los casos graves, prolongados, con sangre, en inmunodeprimidos o en gestantes. El fármaco de elección es la azitromicina, porque la resistencia a las quinolonas, como la ciprofloxacina, es muy alta en el Perú y en todo el mundo. La ampicilina y el cotrimoxazol no son eficaces. Complicaciones importantes: el síndrome de Guillain-Barré, por mimetismo molecular con los gangliósidos, y la artritis reactiva.")

D[348] = ("Ceftazidima: cefalosporina antipseudomonas", "E",
"La ceftazidima es una cefalosporina de tercera generación con buena actividad contra Pseudomonas aeruginosa, a diferencia de la ceftriaxona o la cefotaxima. Se usa en la neutropenia febril, en las infecciones nosocomiales, en quemados y en la fibrosis quística. Hoy también existe combinada con avibactam para gramnegativos productores de carbapenemasas de tipo KPC u OXA-48. Otras cefalosporinas antipseudomonas son la cefoperazona y el cefepime (cuarta generación). La cefalotina, la cefazolina y la cefradina son de primera generación, y la cefoxitina es una cefamicina activa contra anaerobios; ninguna cubre Pseudomonas.")
O[348] = {"B": "Cefazolina"}

X[349] = "Repite la 48 (mecanismo de las fluoroquinolonas)"

D[350] = ("Meningitis tuberculosa: se añaden corticoides al tratamiento", "C",
"En la meningitis tuberculosa, añadir corticoides (dexametasona o prednisona durante 6 a 8 semanas, con reducción gradual) al tratamiento antituberculoso reduce la mortalidad y las secuelas neurológicas, porque disminuye la inflamación de la base del cráneo, la vasculitis y el riesgo de hidrocefalia. Es la indicación con mejor evidencia. También se usan en la pericarditis tuberculosa para reducir la constricción, en algunos casos de tuberculosis miliar grave con insuficiencia respiratoria y en el síndrome inflamatorio de reconstitución inmune en pacientes con VIH. En la tuberculosis pulmonar, la pleural o la peritoneal no se recomiendan de rutina. El tratamiento de la meningitis tuberculosa se prolonga de 9 a 12 meses.")
