# Revisión preguntas 401-450
D, O, N, X = {}, {}, {}, {}

D[401] = ("Nitrofurantoína: neuropatía periférica, sobre todo con insuficiencia renal", "B",
"La nitrofurantoína se usa para tratar y prevenir las infecciones urinarias bajas. Puede causar una polineuropatía sensitivomotora ascendente, a veces grave e irreversible. El riesgo aumenta mucho en la insuficiencia renal, porque el fármaco se acumula en la sangre y, a la vez, no alcanza concentraciones útiles en la orina. Por eso se evita con un aclaramiento de creatinina menor de 30 a 45 mL/min, y esta paciente tiene ERC estadio III y la usa de forma prolongada como profilaxis. Otros efectos importantes: toxicidad pulmonar aguda (neumonitis de hipersensibilidad) o crónica (fibrosis), hepatitis, y hemólisis en el déficit de G6PD. El tiamazol causa agranulocitosis, y el enalapril, tos e hiperpotasemia.")

D[402] = ("Carbamazepina: hiponatremia por efecto tipo SIADH", "E",
"La carbamazepina y, con mayor frecuencia, la oxcarbazepina producen hiponatremia. Aumentan la sensibilidad del riñón a la hormona antidiurética y tienen un efecto antidiurético propio, lo que provoca un cuadro parecido al SIADH con retención de agua. El riesgo es mayor en adultos mayores, en quienes usan diuréticos y con dosis altas. Suele ser leve y asintomático, pero puede causar confusión, más convulsiones y caídas; por eso se controla el sodio al inicio y durante el tratamiento. La lamotrigina, el topiramato, la fenitoína y el fenobarbital no suelen causar hiponatremia. El topiramato produce acidosis metabólica y cálculos renales, y la fenitoína, hiperplasia gingival e hirsutismo.")

D[403] = ("Metaplasia: sustitución reversible de un tipo celular adulto por otro", "A",
"La metaplasia es un cambio reversible en el que una célula adulta diferenciada, epitelial o mesenquimal, es reemplazada por otra de otro tipo, más resistente a una agresión crónica. No es que una célula cambie, sino que las células madre se reprograman. Ejemplos: el epitelio bronquial del fumador pasa de cilíndrico ciliado a escamoso; en el esófago de Barrett, el escamoso pasa a cilíndrico intestinal por el reflujo; en el cuello uterino se forma la zona de transformación, y hay metaplasia ósea en tejidos lesionados. Si el estímulo persiste, puede evolucionar a displasia y cáncer. La hiperplasia es un aumento del número de células; la hipertrofia, del tamaño, y la displasia, un desarrollo desordenado y premaligno.")

D[404] = ("Adaptaciones celulares: hipertrofia, hiperplasia, atrofia y metaplasia", "E",
"Ante un estrés, la célula puede adaptarse de cuatro maneras reversibles: hipertrofia (aumenta de tamaño), hiperplasia (aumenta el número de células), atrofia (disminuye de tamaño) y metaplasia (cambia de tipo celular). Si el daño supera su capacidad de adaptarse, aparece la lesión celular, primero reversible (tumefacción, cambio graso) y luego irreversible, con muerte por necrosis o por apoptosis. Las otras opciones no son adaptaciones. La apoptosis es una muerte programada. La autólisis es la digestión de la célula muerta por sus propias enzimas. La picnosis, la cariorrexis y la cariólisis son los cambios del núcleo en la necrosis: condensación, fragmentación y disolución.")
O[404] = {"D": "Cariorrexis"}

D[405] = ("Anaplasia: falta de diferenciación, rasgo de malignidad", "A",
"La anaplasia es la falta de diferenciación celular: las células pierden su forma y organización y ya no se parecen al tejido del que proceden. Es el rasgo más característico de las neoplasias malignas. Se reconoce por el pleomorfismo (células y núcleos de tamaño y forma variables), núcleos grandes e hipercromáticos con una relación núcleo/citoplasma elevada, nucléolos prominentes, mitosis abundantes y atípicas, células gigantes tumorales y pérdida de la polaridad. Cuanta más anaplasia, mayor es el grado histológico y peor el pronóstico. La atrofia, la hiperplasia, la hipertrofia y la metaplasia son adaptaciones de la célula normal y, en principio, no son malignas.")

D[406] = ("Enfermedad de Bowen: carcinoma epidermoide in situ", "A",
"La enfermedad de Bowen es un carcinoma epidermoide in situ de la piel: una neoplasia maligna limitada a todo el espesor de la epidermis, sin atravesar la membrana basal. Se presenta como una placa eritematosa, descamativa y de bordes bien definidos, de crecimiento lento, en zonas expuestas al sol o por arsénico o VPH. Puede confundirse con un eccema o una psoriasis que no responde al tratamiento. Si no se trata, un 3 a 5 % progresa a carcinoma invasor. La enfermedad de Darier es una genodermatosis, la de Takayasu una vasculitis de grandes vasos, la fibroquística de la mama es benigna y el esófago de Barrett es una metaplasia premaligna, no una neoplasia.")
O[406] = {"D": "Enfermedad fibroquística de la mama"}

D[407] = ("Folículo tiroideo: epitelio simple cúbico", "B",
"El folículo tiroideo es la unidad funcional de la tiroides: una esfera de epitelio simple, generalmente cúbico, que rodea un coloide rico en tiroglobulina. La altura del epitelio refleja su actividad. Es plano cuando la glándula está en reposo, con folículos grandes y mucho coloide, y cilíndrico cuando está estimulado por la TSH, como en la enfermedad de Graves, con poco coloide y vacuolas de reabsorción. Las células foliculares captan yodo (con el simportador NIS), lo oxidan con la tiroperoxidasa, lo incorporan a la tiroglobulina y liberan T4 y T3. Entre los folículos están las células C o parafoliculares, que producen calcitonina y originan el carcinoma medular de tiroides.")

D[408] = ("Metaplasia escamosa bronquial en el fumador", "A",
"El humo del tabaco irrita de forma crónica el epitelio respiratorio pseudoestratificado cilíndrico ciliado y lo transforma en epitelio plano estratificado (escamoso): es una metaplasia escamosa. Este epitelio resiste mejor la agresión, pero pierde los cilios y las células caliciformes, así que empeora la limpieza del moco y aparecen tos e infecciones. Si la exposición continúa, la metaplasia progresa a displasia, a carcinoma in situ y, por último, a carcinoma epidermoide, que suele ser central, en bronquios grandes, y muy ligado al tabaco. Puede causar hipercalcemia por PTHrP. Dejar de fumar puede revertir la metaplasia y, con los años, reduce el riesgo de cáncer.")

D[409] = ("Cartílago: tejido avascular", "C",
"El cartílago es un tejido conectivo especializado sin vasos sanguíneos, sin nervios y sin linfáticos. Sus células, los condrocitos, viven en lagunas dentro de una matriz rica en colágeno (de tipo II en el cartílago hialino) y proteoglucanos como el agrecano, que retienen agua y le dan resistencia a la compresión. Se nutre por difusión desde el pericondrio o, en las articulaciones, desde el líquido sinovial, ayudado por la carga y el movimiento. Por eso casi no puede repararse: las lesiones del cartílago articular cicatrizan mal y llevan a la artrosis. Hay tres tipos: hialino (articulaciones, tráquea), elástico (oreja, epiglotis) y fibrocartílago (discos, meniscos, sínfisis). La sustancia osteoide es del hueso.")

D[410] = ("Barrera hematoencefálica: endotelio y pies de astrocitos", "E",
"La barrera hematoencefálica la forman las células endoteliales de los capilares cerebrales, unidas por uniones estrechas y sin fenestraciones, junto con la membrana basal, los pericitos y los pies terminales de los astrocitos, que rodean los capilares e inducen en el endotelio sus propiedades de barrera. Solo pasan libremente las moléculas pequeñas y liposolubles; la glucosa y los aminoácidos pasan por transportadores. Hay zonas sin barrera (órganos circunventriculares, como el área postrema, donde se detectan tóxicos y se origina el vómito). La inflamación de las meninges abre la barrera, lo que permite el paso de antibióticos como la penicilina. Las células de Schwann forman mielina periférica, y las ependimarias revisten los ventrículos.")
O[410] = {"B": "La microglía", "C": "El oligodendrocito"}
X[412] = "Repite la 410 (astrocitos en la barrera hematoencefálica)"

D[411] = ("Músculo pilomotor: contracción por estímulo simpático alfa-1", "A",
"El músculo erector del pelo, o pilomotor, recibe solo inervación simpática noradrenérgica. Al activarse los receptores alfa-1, se contrae y eriza el vello ('piel de gallina') ante el frío o el miedo. La noradrenalina también contrae el músculo dilatador del iris (midriasis), los esfínteres vesical interno y digestivos, y el músculo liso de los vasos de la piel y las vísceras. En cambio, el esfínter del iris, que produce miosis, el detrusor de la vejiga, el músculo bronquial y la vesícula biliar se contraen con estímulos colinérgicos parasimpáticos. De hecho, el simpático relaja los bronquios (beta-2) y el detrusor (beta-3). Las glándulas sudoríparas son simpáticas pero colinérgicas.")

D[413] = ("Microglía: fagocitos residentes del sistema nervioso central", "D",
"La microglía está formada por los macrófagos residentes del sistema nervioso central. Deriva de precursores del saco vitelino que colonizan el cerebro en la vida fetal, no de la médula ósea. En reposo vigila el tejido con prolongaciones finas. Ante una lesión, como un trauma, un infarto o una infección, se activa, prolifera, se vuelve ameboidea y fagocita los restos de neuronas y de mielina, además de presentar antígenos y liberar citocinas. En el VIH, la microglía es la principal célula infectada del cerebro y forma nódulos microgliales. Los astrocitos, en cambio, forman la cicatriz glial (gliosis) y regulan el entorno, y los oligodendrocitos forman la mielina del SNC.")
O[413] = {"E": "Linfocitos T"}

D[414] = ("Células M: transporte de antígenos en las placas de Peyer", "D",
"Las células M, o de micropliegues, son células epiteliales especializadas del epitelio que cubre las placas de Peyer y otros folículos linfoides del intestino. No tienen un borde en cepillo desarrollado ni una capa gruesa de moco. Captan antígenos y microorganismos de la luz intestinal por transcitosis y los entregan, casi intactos, a las células dendríticas, los macrófagos y los linfocitos que se alojan en su bolsillo basolateral. Así se inicia la respuesta inmune de las mucosas, con producción de IgA secretora. Algunos patógenos las aprovechan para invadir, como Salmonella, Shigella, Yersinia, los priones y el poliovirus. Las células de Paneth, en cambio, secretan defensinas y lisozima.")

D[415] = ("Válvulas cardíacas: tejido conectivo denso cubierto por endocardio", "E",
"Las válvulas cardíacas son pliegues del endocardio con un núcleo de tejido conectivo denso, con colágeno y fibras elásticas, que se continúa con el esqueleto fibroso del corazón. Tienen tres capas: una fibrosa, que les da resistencia; una esponjosa, laxa y rica en proteoglucanos, que amortigua los golpes; y una ventricular o auricular, con fibras elásticas. Están cubiertas por endotelio en ambas caras. Las válvulas normales no tienen vasos sanguíneos y se nutren por difusión, lo que explica por qué las bacterias de la endocarditis se asientan fácilmente sobre ellas y son difíciles de erradicar. En la fiebre reumática se inflaman, se engrosan y se fusionan sus comisuras.")

D[416] = ("Vasa vasorum: irrigan la adventicia y la media externa", "A",
"Los vasa vasorum son pequeños vasos que irrigan la pared de las arterias y venas de gran calibre. Nacen de ramas vecinas o del propio vaso y se distribuyen por la adventicia y el tercio externo de la media. La íntima y la parte interna de la media se nutren por difusión directa desde la luz. En las venas, los vasa vasorum llegan más profundo, porque su sangre tiene menos oxígeno. Su importancia clínica: en la aortitis sifilítica, la endarteritis obliterante de los vasa vasorum produce isquemia de la media y la aorta toma un aspecto de 'corteza de árbol', con aneurismas de la aorta ascendente. También participan en la aterosclerosis y en la disección aórtica.")
O[416] = {"A": "La adventicia y la media externa de los vasos grandes"}

X[417] = "Enunciado ambiguo: la adventicia es de tejido conectivo en casi todos los vasos"

D[418] = ("Inhibina B: la producen las células de Sertoli", "D",
"En el varón, la inhibina B la producen las células de Sertoli bajo el estímulo de la FSH. Frena de forma selectiva la secreción de FSH por la hipófisis mediante retroalimentación negativa, sin afectar la LH. Sus niveles en sangre reflejan la actividad de la espermatogénesis. Una inhibina B baja con FSH alta indica un daño en los túbulos seminíferos (azoospermia secretora, como tras quimioterapia o en el síndrome de Klinefelter). En la mujer la producen las células de la granulosa. Las células de Leydig producen testosterona, las de Ito almacenan vitamina A en el hígado, las de Paneth son intestinales y las de Cajal son el marcapaso gastrointestinal.")

D[419] = ("Prostaglandinas del semen: vesículas seminales", "A",
"Las prostaglandinas del semen se producen sobre todo en las vesículas seminales, no en la próstata, aunque su nombre derive de ella: se describieron primero en el líquido prostático. Estas prostaglandinas, tipo E y F, estimulan las contracciones del útero y de las trompas y favorecen el transporte de los espermatozoides. También pueden reducir la respuesta inmune del tracto genital femenino. Las vesículas seminales aportan además fructosa, la energía de los espermatozoides, y semenogelina, que forma el coágulo del semen. La próstata aporta ácido cítrico, zinc, fosfatasa ácida y PSA, que licúa el semen. El epidídimo almacena y madura los espermatozoides.")
O[419] = {"A": "Las vesículas seminales"}

D[420] = ("Testosterona: la producen las células de Leydig", "A",
"La testosterona la producen sobre todo las células de Leydig, que están en el tejido intersticial entre los túbulos seminíferos. Las estimula la LH hipofisaria, que activa el paso del colesterol a pregnenolona. Una parte difunde a los túbulos, donde, unida a la proteína fijadora de andrógenos de las células de Sertoli, mantiene la espermatogénesis; la concentración dentro del testículo es unas 100 veces mayor que en la sangre. En los tejidos se convierte en dihidrotestosterona (próstata, piel, folículo piloso) o en estradiol. Las células de Leydig tienen inclusiones típicas, los cristales de Reinke. Pueden originar tumores productores de hormonas que causan pubertad precoz o ginecomastia.")
O[420] = {"E": "Mioide peritubular"}

D[421] = ("Páncreas exocrino: glándula acinar serosa", "D",
"El páncreas exocrino es una glándula tubuloacinar compuesta de tipo seroso. Sus células acinares son piramidales, con citoplasma basófilo en la base por su abundante retículo endoplasmático rugoso, y gránulos de zimógeno acidófilos en el vértice. Secretan una solución acuosa rica en enzimas: tripsinógeno, quimotripsinógeno, lipasa, amilasa y otras. La colecistocinina estimula su secreción. En el centro del acino están las células centroacinares, que inician los conductos y, junto con las células ductales, secretan bicarbonato bajo el estímulo de la secretina. El páncreas no tiene células mucosas en sus acinos. Los islotes de Langerhans forman la parte endocrina.")
O[421] = {"C": "Caliciformes"}

D[422] = ("Vesícula biliar: epitelio cilíndrico simple", "A",
"La mucosa de la vesícula biliar está revestida por un epitelio cilíndrico simple de células altas con microvellosidades, especializadas en absorber agua y electrolitos. Así concentran la bilis hasta 5 a 10 veces. La mucosa forma pliegues profundos, y la vesícula no tiene muscular de la mucosa ni submucosa, algo único en el tubo digestivo. Por eso los tumores invaden pronto la capa muscular. En la colecistitis crónica, la mucosa se hunde en la pared y forma los senos de Rokitansky-Aschoff. La vesícula en porcelana, calcificada, y los pólipos mayores de 1 cm aumentan el riesgo de adenocarcinoma, más frecuente en mujeres y en ciertas regiones de Sudamérica, como Chile y Bolivia.")
O[422] = {"B": "Pseudoestratificado cilíndrico ciliado", "C": "Cúbico simple"}

X[423] = "Repite la 102 (secreción de la célula parietal)"
X[424] = "Repite la 102 (secreción de la célula parietal)"
X[426] = "Repite la 102 (secreción de la célula parietal)"

D[425] = ("Adenopatía inguinal por carcinoma escamoso: primario en el canal anal", "A",
"Los ganglios inguinales superficiales drenan la piel de la parte inferior del abdomen, los genitales externos (el escroto, pero no el testículo), la vulva, el tercio inferior de la vagina, el canal anal por debajo de la línea pectínea, el periné y las extremidades inferiores. Un carcinoma de células escamosas en un ganglio inguinal apunta a un primario escamoso en ese territorio. El más probable es el ano (canal anal por debajo de la línea dentada), un tumor asociado al VPH 16. También podrían ser el pene, la vulva o la piel. El testículo drena a los ganglios paraaórticos, y la próstata, el recto y el sigmoides, a los ganglios pélvicos y mesentéricos; además, sus tumores suelen ser adenocarcinomas, no escamosos.")

D[427] = ("Reacción leucemoide neutrofílica: hemorragia o hemólisis aguda", "D",
"La reacción leucemoide es una leucocitosis reactiva importante, mayor de 50 000/µL, con desviación a la izquierda, que puede confundirse con una leucemia. En la forma neutrofílica, las causas típicas son las infecciones graves (sepsis, neumonía, C. difficile), la hemorragia o la hemólisis aguda, las quemaduras, los corticoides y algunos tumores, a veces metastásicos por producción de G-CSF. Se diferencia de la leucemia mieloide crónica por la fosfatasa alcalina leucocitaria, que está alta en la reacción leucemoide y baja en la LMC, por la ausencia del cromosoma Filadelfia (BCR-ABL) y porque no hay basofilia. La mononucleosis produce linfocitosis atípica, y las parasitosis, eosinofilia.")

D[428] = ("Infección subclínica: se detecta por cambios en los anticuerpos", "B",
"Una infección subclínica o inaparente es la que ocurre sin signos ni síntomas. Como no hay manifestaciones, se reconoce solo por el laboratorio: aparición de anticuerpos (seroconversión) o un aumento o descenso significativo de sus títulos en muestras pareadas, por lo general un cambio de cuatro veces o más. Ejemplos: la mayoría de las infecciones por poliovirus, hepatitis A en niños pequeños, citomegalovirus o toxoplasmosis. Epidemiológicamente son importantes porque estas personas pueden transmitir la infección sin saberlo y generan inmunidad en la población. Aislar el agente demuestra infección, pero no indica si es clínica o subclínica. Los signos y síntomas definen la infección clínica.")

D[429] = ("Macrófago: fagocita y secreta citocinas inflamatorias", "B",
"El macrófago es una célula clave de la inmunidad innata. Reconoce los patrones moleculares de los microorganismos (PAMP) con receptores como los Toll, los fagocita y los destruye con especies reactivas de oxígeno, óxido nítrico y enzimas lisosomales. Además secreta citocinas inflamatorias, como TNF-alfa, IL-1, IL-6, IL-12 y quimiocinas, que causan fiebre, reactantes de fase aguda y reclutamiento de neutrófilos. También presenta antígenos a los linfocitos T y así conecta la inmunidad innata con la adaptativa. El epitelio es una barrera física. El TNF-alfa y la IL-1 son moléculas, no células, y las lectinas activan el complemento pero no fagocitan.")

X[430] = "Repite la 143 (infartos blancos en el bazo)"

D[431] = ("Esplenomegalia masiva: linfomas y neoplasias mieloproliferativas", "E",
"Se considera esplenomegalia masiva cuando el bazo supera los 1000 a 1500 g o llega a la fosa ilíaca o cruza la línea media. Sus causas son limitadas y conviene memorizarlas. Hematológicas: leucemia mieloide crónica, mielofibrosis primaria, linfomas (sobre todo los indolentes, como el de la zona marginal esplénica), tricoleucemia y talasemia mayor. Infecciosas: malaria crónica (esplenomegalia tropical) y leishmaniasis visceral (kala-azar). Por depósito: la enfermedad de Gaucher. La insuficiencia cardíaca, la sepsis, la tuberculosis y la mielodisplasia producen una esplenomegalia leve o moderada. Un bazo gigante puede causar dolor, saciedad precoz, infartos esplénicos e hiperesplenismo con pancitopenia.")

D[432] = ("IgE: mediadora de la anafilaxia y la atopia", "D",
"La IgE media la hipersensibilidad de tipo I. En una primera exposición, el alérgeno induce, con ayuda de los linfocitos Th2 y la IL-4, la producción de IgE específica. Esta se fija con gran afinidad a los receptores FcεRI de los mastocitos y basófilos. En una nueva exposición, el alérgeno une dos moléculas de IgE, lo que desgranula las células y libera histamina, triptasa, leucotrienos y prostaglandinas. Así aparecen la anafilaxia, el asma alérgica, la rinitis, la urticaria y la dermatitis atópica. La IgE total suele estar elevada en la atopia y las parasitosis por helmintos. El omalizumab, un anticuerpo anti-IgE, se usa en el asma alérgica grave y la urticaria crónica.")
O[432] = {"A": "IgM", "B": "IgG", "C": "IgD", "D": "IgE", "E": "IgA"}
X[433] = "Repite la 432 (IgE en la anafilaxia)"

D[434] = ("Bacteroides fragilis: la cápsula polisacárida induce abscesos", "C",
"Bacteroides fragilis forma parte de la flora normal del colon. Cuando sale de su sitio, por ejemplo tras una perforación intestinal o una cirugía, causa abscesos intraabdominales y pélvicos. Su principal factor de virulencia es la cápsula de polisacárido zwitteriónico (con cargas positivas y negativas), que por sí sola es capaz de inducir abscesos en modelos experimentales, porque activa a los linfocitos T y la liberación de IL-17. Además, inhibe la fagocitosis. Su lipopolisacárido tiene poca actividad endotóxica, y la betalactamasa le da resistencia a las penicilinas, pero no forma abscesos. El tratamiento es drenar el absceso y usar antibióticos activos, como metronidazol, carbapenémicos o piperacilina-tazobactam.")
X[446] = "Repite la 434 (cápsula de Bacteroides fragilis y abscesos)"

D[435] = ("Meningitis neonatal con bacilos grampositivos: Listeria", "D",
"En el recién nacido, las principales causas de meningitis bacteriana son Streptococcus agalactiae (grupo B, cocos grampositivos en cadenas), Escherichia coli (bacilos gramnegativos) y Listeria monocytogenes. Listeria se ve en el Gram como cocobacilos o bacilos cortos grampositivos, intra y extracelulares. Se transmite por vía transplacentaria o en el parto, a partir de alimentos contaminados que consume la madre (lácteos sin pasteurizar, embutidos). Es intrínsecamente resistente a las cefalosporinas. Por eso el esquema empírico de la meningitis neonatal y en menores de 3 meses incluye ampicilina junto con cefotaxima o gentamicina. También afecta a adultos mayores de 50 años e inmunodeprimidos.")
O[435] = {"A": "Enterococcus faecalis", "E": "Streptococcus agalactiae"}

D[436] = ("Meningitis con cocobacilos gramnegativos en un niño: Haemophilus influenzae", "B",
"Los cocobacilos gramnegativos pleomórficos en el LCR de un niño pequeño con meningitis sugieren Haemophilus influenzae tipo b. Antes de la vacuna era la primera causa de meningitis entre los 3 meses y los 5 años y dejaba secuelas como hipoacusia. Gracias a la vacuna conjugada contra Hib, incluida en la pentavalente del esquema peruano, hoy es poco frecuente. Si aparece, debe revisarse el calendario de vacunación. El tratamiento es con ceftriaxona o cefotaxima, más dexametasona antes o junto con la primera dosis de antibiótico, para reducir la sordera. Los contactos de riesgo reciben profilaxis con rifampicina. Neisseria meningitidis aparece como diplococos gramnegativos, y el neumococo, como diplococos grampositivos.")
O[436] = {"B": "Haemophilus influenzae"}

D[437] = ("Toxina colérica: se une al gangliósido GM1", "A",
"La toxina colérica es una toxina AB5. Sus cinco subunidades B se unen al gangliósido GM1 de la membrana del enterocito, y la subunidad A entra a la célula. Allí ribosila con ADP a la proteína Gs y la deja activada de forma permanente. La adenilato ciclasa produce AMPc sin parar, y el canal CFTR secreta cloro y agua mientras se inhibe la absorción de sodio. El resultado es una diarrea acuosa masiva en 'agua de arroz', de hasta 1 L por hora, con deshidratación grave, hipopotasemia y acidosis. No hay inflamación ni sangre. El tratamiento principal es la rehidratación (sales orales o lactato de Ringer IV); la doxiciclina o la azitromicina acortan la enfermedad. El Perú sufrió una gran epidemia en 1991.")

D[438] = ("LCR linfocitario con glucosa baja y proteínas altas: tuberculosis", "C",
"Un LCR con pleocitosis moderada de predominio linfocitario, glucosa baja (menos de 45 mg/dL o menos del 50 % de la glucemia) y proteínas muy altas es el patrón típico de la meningitis tuberculosa. Suele tener un curso subagudo, de más de 1 a 2 semanas, con parálisis de pares craneales, sobre todo el VI, y a veces hidrocefalia. El diagnóstico se apoya en la adenosina desaminasa (ADA) elevada en el LCR, el GeneXpert y el cultivo. La meningitis viral tiene linfocitos pero glucosa normal. La bacteriana (neumococo) tiene neutrófilos. En el paciente con VIH, el criptococo da un patrón parecido y se busca con tinta china o antígeno. El tratamiento antituberculoso se acompaña de corticoides.")
N[438] = "Paciente inmunocompetente con cefalea y fiebre de 3 semanas y diplopía. El LCR muestra 50 leucocitos/µL a predominio de linfocitos, con hipoglucorraquia e hiperproteinorraquia. ¿Cuál es el agente etiológico más probable?"
O[438] = {"B": "Virus herpes simple", "C": "Mycobacterium tuberculosis", "D": "Streptococcus pneumoniae"}

D[439] = ("Shock tóxico estafilocócico: TSST-1 (superantígeno)", "A",
"El síndrome de shock tóxico estafilocócico se debe a la toxina 1 del síndrome de shock tóxico (TSST-1) y, a veces, a las enterotoxinas B o C. Son superantígenos: unen directamente el MHC II de las células presentadoras con la región V-beta del receptor T, sin procesamiento previo. Activan hasta el 20 % de los linfocitos T y provocan una liberación masiva de citocinas. El cuadro es fiebre alta, hipotensión, eritrodermia difusa que luego se descama en palmas y plantas, y compromiso de varios órganos. Se asoció a tampones superabsorbentes, taponamientos nasales y heridas. Se trata con soporte, retiro del foco y antibióticos, añadiendo clindamicina para frenar la producción de toxina. La toxina exfoliativa causa la piel escaldada.")
O[439] = {"A": "Toxina 1 del síndrome de shock tóxico (TSST-1)", "C": "Fibrinolisina (estafiloquinasa)"}

D[440] = ("Flora del colon: predominan los anaerobios, sobre todo Bacteroides", "B",
"El colon tiene la mayor población bacteriana del cuerpo, alrededor de 10¹¹ a 10¹² bacterias por gramo de contenido. Más del 99 % son anaerobias estrictas, y Bacteroides (sobre todo B. fragilis y B. thetaiotaomicron) es uno de los géneros predominantes, junto con Bifidobacterium, Eubacterium y Clostridium. Los anaerobios superan a los aerobios facultativos, como E. coli y Enterococcus, en proporción de 1000 a 1. Por eso, aunque E. coli es el aerobio más conocido, no es el predominante. Esto explica que las infecciones por perforación del colon sean polimicrobianas, con anaerobios y enterobacterias. La flora produce vitamina K y ácidos grasos de cadena corta, y protege contra patógenos.")

D[441] = ("Cápsula de S. aureus: inhibe la opsonización y la fagocitosis", "E",
"Muchas cepas de Staphylococcus aureus tienen una cápsula de polisacárido, sobre todo de los serotipos 5 y 8, que envuelve a la bacteria. Impide que el complemento y los anticuerpos que se depositan en la pared queden accesibles a los neutrófilos, por lo que inhibe la opsonización y la fagocitosis. La proteína A tiene un efecto parecido, porque se une a la porción Fc de la IgG y la 'pone al revés'. Otros factores de virulencia: la coagulasa forma una barrera de fibrina, la leucocidina de Panton-Valentine destruye leucocitos y se asocia a neumonía necrotizante y a SARM comunitario, y las toxinas exfoliativas, la enterotoxina y la TSST-1 causan cuadros específicos.")
O[441] = {"B": "Lipasa"}

D[442] = ("Campylobacter jejuni y síndrome de Guillain-Barré", "D",
"Campylobacter jejuni es la infección previa que más se asocia al síndrome de Guillain-Barré: se encuentra en un 25 a 40 % de los casos. Algunas cepas, sobre todo de ciertos serotipos de Penner, tienen lipooligosacáridos parecidos a los gangliósidos del nervio (GM1, GD1a). Los anticuerpos contra la bacteria atacan por reacción cruzada los axones o la mielina: es el mimetismo molecular. Estos casos suelen ser de la forma axonal motora aguda (AMAN), de peor pronóstico, y aparecen 1 a 3 semanas después de la diarrea. En el Perú hubo un gran brote de Guillain-Barré en 2019, asociado a C. jejuni. El tratamiento es inmunoglobulina IV o plasmaféresis. El síndrome de Miller-Fisher se asocia a anti-GQ1b.")

D[443] = ("Estreptolisina S: no es inmunógena (a diferencia de la O)", "A",
"Streptococcus pyogenes produce dos hemolisinas. La estreptolisina O es lábil al oxígeno y muy inmunógena: genera anticuerpos antiestreptolisina O (ASO), útiles para demostrar una infección estreptocócica reciente en la fiebre reumática o la glomerulonefritis posestreptocócica. La estreptolisina S es estable al oxígeno y es la responsable de la beta-hemólisis alrededor de las colonias en agar sangre. Es un péptido pequeño unido a la célula y no es inmunógena, así que no produce anticuerpos detectables. Lisa eritrocitos, leucocitos y plaquetas, y daña las membranas de los lisosomas, liberando sus enzimas. Por eso lo que no le corresponde es la inmunogenicidad.")

D[444] = ("Ureasa de Helicobacter pylori: factor de virulencia clave", "E",
"Helicobacter pylori produce una ureasa muy potente que desdobla la urea del jugo gástrico en amoníaco y CO2. El amoníaco neutraliza el ácido a su alrededor y crea un microambiente que le permite sobrevivir y moverse hacia la capa de moco, donde se adhiere al epitelio. Por eso la ureasa es indispensable para colonizar y es un factor de virulencia. Además, el amoníaco daña directamente la mucosa. Esta enzima es la base de varias pruebas diagnósticas: la prueba de la ureasa rápida en la biopsia y la prueba del aliento con urea marcada con carbono 13 o 14. Otros factores de virulencia son CagA, VacA y los flagelos. Los Campylobacter intestinales no dependen de la ureasa.")

D[445] = ("Legionella: antígeno urinario como prueba preferente", "A",
"El diagnóstico rápido de la neumonía por Legionella se hace con el antígeno en orina. Es sencillo, da resultados en minutos, es muy específico y sigue positivo días o semanas después de iniciar el tratamiento. Su limitación es que solo detecta L. pneumophila del serogrupo 1, responsable de un 70 a 80 % de los casos. El cultivo de secreciones respiratorias en agar BCYE es el patrón de referencia y permite detectar todas las especies, pero tarda de 3 a 5 días; la PCR es cada vez más usada. Hay que sospecharla ante una neumonía grave con hiponatremia, diarrea, confusión, fiebre alta con bradicardia relativa o un brote ligado a aguas contaminadas o aire acondicionado. Se trata con macrólidos o quinolonas.")

D[447] = ("Clostridium botulinum: neurotoxina que causa parálisis flácida", "A",
"Clostridium botulinum produce la toxina botulínica, la sustancia biológica más potente que se conoce. La toxina entra a las terminales nerviosas colinérgicas y degrada las proteínas SNARE (como SNAP-25 o la sinaptobrevina), que son necesarias para liberar acetilcolina. El resultado es una parálisis flácida descendente y simétrica: diplopía, ptosis, disfagia, disartria, luego debilidad de las extremidades e insuficiencia respiratoria, con midriasis y sequedad de boca y sin alteración de la conciencia ni de la sensibilidad. Formas: alimentaria (conservas caseras), por heridas y del lactante (miel). Se trata con antitoxina y soporte ventilatorio. C. tetani, en cambio, causa tétanos, una parálisis espástica.")
N[447] = "¿Cuál es la especie de Clostridium capaz de producir una toxina causante de un cuadro neurológico en el ser humano?"
O[447] = {"C": "Clostridium perfringens", "D": "Clostridium septicum", "E": "Clostridium ramosum"}

D[448] = ("Anaerobios: poco frecuentes en las infecciones urinarias", "D",
"Los anaerobios son flora normal de la boca, el colon y el tracto genital femenino. Por eso predominan en las infecciones que nacen de esas mucosas: abscesos maxilofaciales y odontógenos, abscesos pulmonares por aspiración, infecciones intraabdominales, infecciones pélvicas (EPI, endometritis, abscesos tuboováricos) e infecciones necrotizantes de partes blandas profundas. La orina, en cambio, es rica en oxígeno, y la uretra distal está colonizada por flora de la piel y enterobacterias facultativas. Por eso las infecciones urinarias casi nunca las causan anaerobios; la gran mayoría se deben a E. coli y otras enterobacterias. Signos que sugieren anaerobios: mal olor, gas en los tejidos y necrosis.")
O[448] = {"A": "Abscesos periuretrales"}

D[449] = ("Colitis por C. difficile: vancomicina oral", "A",
"Para la infección por Clostridioides difficile, las guías actuales (IDSA/SHEA) recomiendan como primera línea la vancomicina oral, 125 mg cada 6 horas durante 10 días, o la fidaxomicina. Por vía oral, la vancomicina no se absorbe y alcanza concentraciones muy altas en el colon. Por vía IV no sirve, porque no llega a la luz intestinal. El metronidazol oral quedó como alternativa solo para casos no graves cuando no hay otra opción. En la forma fulminante se combina vancomicina oral en dosis altas o por enema con metronidazol IV y se evalúa cirugía. En las recurrencias se usan la fidaxomicina, esquemas de vancomicina en dosis decrecientes o el trasplante de microbiota fecal. Lo primero siempre es suspender el antibiótico desencadenante.")

D[450] = ("Ciclo de Anopheles: metamorfosis completa (sin ninfa)", "D",
"Los mosquitos, entre ellos Anopheles, vector de la malaria, tienen una metamorfosis completa (holometábola) con cuatro estadios: huevo, larva, pupa y adulto. Los tres primeros son acuáticos. La hembra de Anopheles deposita los huevos en agua limpia, y las larvas se ubican paralelas a la superficie del agua, a diferencia de las de Culex y Aedes, que forman un ángulo. Solo la hembra adulta pica, porque necesita sangre para madurar sus huevos. El estadio de ninfa es propio de los insectos con metamorfosis incompleta (hemimetábolos), como los triatominos o chinches, vectores de la enfermedad de Chagas, y de las garrapatas. En el Perú, la malaria predomina en la Amazonía (Loreto) por Plasmodium vivax y P. falciparum.")
